### ISSUE TITLE
PlayScala plugin causes duplicate test reports on sbt 1.3.7

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#10000]
Play `2.8.0`

since we switched to Sbt `1.3.7` we have duplicate test reports for all the play modules in our multi-module build (the ones with `enablePlugins(PlayScala)`)

for those modules the `target/test-reports` looks like this
```
org.foo.XSpec.xml
org.foo.YSpec.xml
TEST-org.foo.XSpec.xml
TEST-org.foo.YSpec.xml
...
```
where for non-play modules we only have the `TEST-`-prefixed files

The sbt release notes mention a change in the junit reporting output
https://github.com/sbt/sbt/releases/tag/v1.3.7

The play plugin must be changing some test options that cause the reports to be generated twice

**Comment by wsargent** [comment]
10000!

**Comment by francisdb** [comment]
What do I win? 💰

**Comment by renatocaval** [comment]
Congrats @francisdb. Nice that you are the winner. 
I pay you a beer next time we meet!

**Comment by marcospereira** [comment]
It looks like this is https://github.com/sbt/sbt/pull/4343.

**Comment by ignasi35** [comment]
> It looks like this is [sbt/sbt#4343](https://github.com/sbt/sbt/pull/4343).

4343 introduced the report duplication and https://github.com/sbt/sbt/pull/5350 introduced the means to enable a format or the other to avoid duplicates and still generate the reports using the filename that's more convenient for each user.

**Comment by marcospereira** [comment]
> and sbt/sbt#5350 introduced the means to enable a format or the other to avoid duplicates

Yes, but no in a way that makes this possible:

> The play plugin must be changing some test options that cause the reports to be generated twice

Since this is not a setting we can override, but a JVM property that needs to be set when starting sbt.

Or am I missing something?

**Comment by francisdb** [comment]
I currently don't have the time to dig deeper into this but if nobody else can reproduce the issue it must be something else in our build causing this.

**Comment by francisdb** [comment]
At first sight it looks like migrating our tests to ScalaTest fixed this, closing this as nobody else is reporting this issue
