### ISSUE TITLE
overriding configuration in devSettings not being picked up 2.8.0

### ISSUE THREAD

**Issue by awouda** [playframework/playframework#10036]
### config.file in devSettings

Hi,

We we're behind in upgrading, coming from 2.6.
In our build.sbt we had:

`devSettings := Seq("config.file" -> (baseDirectory.value / "lokaal" / "conf" / "application-lokaal.conf").toString)
`

After upgrading to Play 2.8.0, this setting does not seem to be picked up. 
We have a workaround by using 
`javaOptions in Runtime ....`
and setting the config.file system property there. But suspect this to be a bug, as for example setting the play server to a different port via the devSettings is being picked up.

### Play Version

2.8.0

### API

Scala

### Operating System

Linux m5510 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### JDK
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

### Expected Behavior

After starting sbt run, we have a running application.

### Actual Behavior

`[aanvragen-applicatie] $ run
[warn] Credentials file /home/alex/.ivy2/.credentials does not exist

--- (Running the application, auto-reloading is enabled) ---

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/alex/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/alex/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[warn] Credentials file /home/alex/.ivy2/.credentials does not exist
[warn] Credentials file /home/alex/.ivy2/.credentials does not exist
[error] p.a.h.DefaultHttpErrorHandler -

! @7ele6pol1 - Internal server error, for (GET) [/api] ->

play.api.Configuration$$anon$1: Configuration error[application: application.conf: java.io.IOException: resource not found on classpath: application.conf, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties]
	at play.api.Configuration$.configError(Configuration.scala:138)
	at play.api.Configuration$.load(Configuration.scala:81)
	at play.api.Configuration$.load(Configuration.scala:90)
	at play.api.ApplicationLoader$Context$.create(ApplicationLoader.scala:124)
	at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:186)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:181)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:141)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:296)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:186)`

**Comment by mkurz** [comment]
This is fixed in 2.8.1, see #10010

**Comment by mkurz** [comment]
@awouda Let us know if upgrading directly to Play 2.8.1 works for you. If not, please re-open this issue.

**Comment by awouda** [comment]
Ok, missed it in my search to fix it. Did not check the issues here, sorry. 
We'll use 2.8.1.  

Thanks
