### ISSUE TITLE
Failed: failed to connect to GitHub

### ISSUE THREAD

**Issue by octonato** [playframework/playframework#10044]
Happened on CRON job in 2.7.x

https://travis-ci.com/playframework/playframework/jobs/284719424#L224

```
$ curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh

curl: (7) Failed to connect to github.com port 443: Connection timed out

/home/travis/.travis/functions: line 109: /home/travis/.jabba/jabba.sh: No such file or directory

The command "curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh" failed and exited with 1 during .
```

**Comment by renatocaval** [comment]
Also happenend on CRON job in master

https://travis-ci.com/playframework/playframework/jobs/284719439#L183

**Comment by mkurz** [comment]
Since this might be related to Travis and we use GitHub actions now, I am closing. We can open new issues if something turns up with GHA.
Also we do not use jabba anymore on CI.
