### ISSUE TITLE
Failed: when executing Jabba

### ISSUE THREAD

**Issue by renatocaval** [playframework/playframework#10045]
Failed CRON job on 2.8.x

Same as in https://github.com/lagom/lagom/issues/2679
https://travis-ci.com/playframework/playframework/jobs/284795866#L261

**Comment by seglo** [comment]
Seems to be an intermittent issue on Play! framework 2.7.x branch as well.

https://travis-ci.com/playframework/playframework/jobs/292032877?utm_medium=notification&utm_source=email

**Comment by marcospereira** [comment]
It looks like the last failure is related to Github having some issues last week. Maybe we can ask `curl` to `--retry` some times. 🤔
