### ISSUE TITLE
GzipFilterConfig threshold not exposed in Java API

### ISSUE THREAD

**Issue by slisaasquatch** [playframework/playframework#10040]
### Play Version

2.8.1

### API

Java

### Operating System
N/A

### JDK
1.8.0_232

### Library Dependencies
N/A

### Actual Behavior
`GzipFilterConfig` has a property called `threshold`, but it's missing the method `withThreshold`, making it difficult to set it in Java.

### Reproducible Test Case
N/A

**Comment by mkurz** [comment]
@slisaasquatch Do you want to provide a pull request to add the method? Here is the source you need to change: https://github.com/playframework/playframework/blob/2.8.1/web/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala

**Comment by mkurz** [comment]
Fixed by #10042.
