### ISSUE TITLE
Failed: JNotifyAdapterLinux 

### ISSUE THREAD

**Issue by renatocaval** [playframework/playframework#10048]
On CRON job 2.7.x 

https://travis-ci.com/playframework/playframework/jobs/285313669#L2151

```
[info] java.lang.ExceptionInInitializerError
[info] 	at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.<init>(Unknown Source)
```

**Comment by renatocaval** [comment]
@dwijnand, don't we have already a fix for that? 

Maybe it's just a matter of backporting it to 2.7.x?

**Comment by marcospereira** [comment]
Closing since the latest cron build is green: https://travis-ci.com/playframework/playframework/builds/148903597
