### ISSUE TITLE
similarly to HTTP pipelining, implement SPDY support

### ISSUE THREAD

**Issue by pk11** [playframework/playframework#1005]
netty supports the SPDY protocol[1], it would be great to enable it.

http://www.javacodegeeks.com/2012/05/netty-using-spdy-and-http-transparently.html

**Comment by WarFox** [comment]
Now that HTTP/2 is almost nearing being standardised, it'll be a good idea revisiting this issue. How's it going?

**Comment by jroper** [comment]
Well, we're moving to akka-http, so we'll be waiting for it to implement HTTP/2.

**Comment by WarFox** [comment]
cool. hope that happens soon. :sparkles:

**Comment by bblfish** [comment]
There's a thread on that https://github.com/akka/akka/issues/16862

**Comment by hepin1989** [comment]
http2,netty have one,and play is going to netty4,so could be added.
https://http2.akamai.com/demo

**Comment by bblfish** [comment]
It seems like in this case Play has an advantage of using netty in this regard to add features of HTTP2.0 much sooner than it is likely to appear in akka. It may be interesting to be able to have a Play with netty implementation to then compare with a later akka version.

**Comment by jroper** [comment]
That's what we're planning on doing, though one of the problems with Netty's HTTP 2 support is that not only does it use a completely different class model for HTTP2 requests/responses, it doesn't even use the Netty channel abstraction for handling HTTP2 streams, so we would have to reimplement reactive streams on top of this new Netty HTTP2 streaming abstraction, and that's likely going to be a huge task.

**Comment by mkurz** [comment]
Closing in favor of #5817
