### ISSUE TITLE
JSON body parsers do not support maxLength in the type-checking version

### ISSUE THREAD

**Issue by bursauxa** [playframework/playframework#10056]
### Play Version

Play 2.8.0 on Scala 2.12.10

### Description

There are currently three overloads of the function `json` in trait `PlayBodyParsers`:
- `json: BodyParser[JsValue]` -> uses default maxLength and weakly typed
- `json(maxLength: Long): BodyParser[JsValue]` -> takes maxLength parameter and weakly typed
- `json[A](implicit reader: Reads[A]): BodyParser[A]` -> uses default maxLength and strongly typed

I would expect a fourth overload to be available:
- `json[A](maxLength: Long)(implicit reader: Reads[A]): BodyParser[A]` -> takes maxLength parameter and strongly typed

The strongly typed version calls `jsonReads`, which is private, so it is not possible to add this overload easily in a helper class.

**Comment by marcospereira** [comment]
> The strongly typed version calls `jsonReads`, which is private, so it is not possible to add this overload easily in a helper class.

You don't need to do that, though. You can do something like:

```scala
private val tolerantFooParser: BodyParser[Foo] = parsers.tolerantJson(maxLength = 100).map(_.as[Foo])
```

I think this is a better alternative than trying to add more overloads out-of-the-box.

**Comment by bursauxa** [comment]
Having out-of-the-box HTTP 400 for invalid JSON was important to me, which is why the simple `map.as` was not enough.

On the other hand I saw your more detailed answer to the pull request (#10059) and went with that, so the overload described in this issue is not as necessary as I thought it was.

**Comment by marcospereira** [comment]
Thanks, @bursauxa.

I'm closing this issue then, and any further discussion is necessary, we can make it happen in the PR.
