### ISSUE TITLE
Database password revealed in logs

### ISSUE THREAD

**Issue by jacwah** [playframework/playframework#10073]
Play version: 2.7.3
Language: Scala

If the database password is specified using the query string of the JDBC URL, the password is leaked in the logs. According to [OWASP Logging Cheat Sheet](https://owasp.org/www-project-cheat-sheets/cheatsheets/Logging_Cheat_Sheet), authentication passwords and database connection strings should never be logged in plain text.

Example:

    [info] p.a.d.DefaultDBApi - Database [default] initialized at jdbc:postgresql://localhost/database?password=letmein

A similar issue was previously reported and fixed in 2014 (https://github.com/playframework/playframework/issues/3761).

**Comment by marcospereira** [comment]
Thanks, @jacwah.

As a workaround, I would suggest not configuring the password in the url, but I definitive fix would be rather log the url only in DEV mode:

https://github.com/playframework/playframework/blob/2.8.x/persistence/play-jdbc/src/main/scala/play/api/db/DBModule.scala#L92

So it won't happen in production, where it matter most. Or we can just completely omit the url from the log entry:

https://github.com/playframework/playframework/blob/2.8.x/persistence/play-jdbc/src/main/scala/play/api/db/DefaultDBApi.scala#L70

Do you want to submit a PR?

Thanks!
