### ISSUE TITLE
URI parsing fails for `//`

### ISSUE THREAD

**Issue by ennru** [playframework/playframework#10072]
References #6802, #3629

The problematic code is in
https://github.com/playframework/playframework/blob/6df5da49c1ddc334e92b5d5f856d99995ff09a30/transport/server/play-server/src/main/scala/play/core/server/common/PathAndQueryParser.scala#L36

### Play Version

2.8.1 (and earlier)

### Expected Behavior

~~The URI double slash `//` should be interpreted to be just `/`~~.
The illegal URL should not lead to a warning in the server logs.

### Actual Behavior

`java.net.URI` fails to parse `//` and Play logs it on warning level.

### Reproducible Test Case

```
$ telnet localhost 9000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET // HTTP/1.1
Host: 127.0.0.1
```

Fails with 
```
[debug] a.i.TcpListener - New connection accepted
[warn] p.c.s.a.AkkaModelConversion - Failed to parse path; returning empty string.
java.net.URISyntaxException: Expected authority at index 2: //
at java.net.URI$Parser.fail(URI.java:2848)
at java.net.URI$Parser.failExpecting(URI.java:2854)
at java.net.URI$Parser.parseHierarchical(URI.java:3102)
at java.net.URI$Parser.parse(URI.java:3063)
at java.net.URI.<init>(URI.java:588)
at play.core.server.common.PathAndQueryParser$.parse(PathAndQueryParser.scala:36)
at play.core.server.common.PathAndQueryParser$.parsePath(PathAndQueryParser.scala:53)
at play.core.server.akkahttp.AkkaModelConversion$$anon$2.liftedTree1$1(AkkaModelConversion.scala:101)
at play.core.server.akkahttp.AkkaModelConversion$$anon$2.path$lzycompute(AkkaModelConversion.scala:100)
at play.core.server.akkahttp.AkkaModelConversion$$anon$2.path(AkkaModelConversion.scala:99)
```

**Comment by gmethvin** [comment]
> The URI double slash // should be interpreted to be just /.

This was also discussed in https://github.com/playframework/playframework/issues/4933, where @jroper explained why returning a 400 here is the correct behavior according to the URI spec. I suppose you're saying it makes more sense to ignore the spec here for the sake of usability.

I do feel like logging at `warn` doesn't make sense, because it makes it appear that something is wrong with Play. We should probably change to `info` or `debug` for this type of exception.

**Comment by jroper** [comment]
I definitely don't think we should silently drop the slash, I would rather pass an invalid URI to the user than a different URI to what Play received. Imagine if you were expecting a load balancer to never forward requests to /, for stove security reason, but then it does foreward //, and then Play treats that as /, very bad. Perhaps we could special case // and not parse it using URI, instead just pass as is. But my preference is still to conform to the spec, and treat // as an invalid URI as the spec requires, and return bad request. We could make it configurable.

**Comment by gmethvin** [comment]
I would also prefer not to deviate from the spec. If we're concerned about users being confused, we can perhaps improve the error message in this case to make it more clear.

**Comment by ennru** [comment]
You're right, the HTTP response should not be changed.

Not reporting illegal request URIs as warnings would be better.

**Comment by fusuiyi123** [comment]
Hi @ennru I am not sure if I follow the conversation here, is this issue still pending? Thanks!
