### ISSUE TITLE
Not able to parse the Json file with its relation_tree and split into multiple Json file for each child without any hard coding of Node/Tag (As structure of Json is not always same also very lengthy json). Input and Output is pasted below : 

### ISSUE THREAD

**Issue by AnamikaSingh-DataScience** [playframework/playframework#10081]

**Comment by marcospereira** [comment]
Hello @AnamikaSingh-DataScience,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Best.
