### ISSUE TITLE
`JsonHttpErrorHandler.error` shall be protected to let inherited classes to override

### ISSUE THREAD

**Issue by b-gyula** [playframework/playframework#10093]
### Play Version

2.8.1

### API

scala

### Operating System
ALL

### JDK

All

### Expected Behavior

`play.api.http.JsonHttpErrorHandler.error` could be protected to let inherited classes to override

### Actual Behavior

Now if someone wants to have JSON error structure to be returned other than the 
```
{
 "error": { ... } 
}
```
the complete class needs to be rewritten,

**Comment by mkurz** [comment]
The `error` method is very simple:
https://github.com/playframework/playframework/blob/6bac5dadfd1879600074de868b7c1432ea96a812/core/play/src/main/scala/play/api/http/HttpErrorHandler.scala#L363
Actually I am going to remove it.

You should instead just override `devServerError`, `prodServerError` or `onClientError`. You can  also always just call `super.onClientError`,... if you want to reuse the default implementations.

**Comment by b-gyula** [comment]
I know it's very simple, but all 3 methods are using it. So if someone wants only a different JSON structure, then all 3 methods has to overridden / duplicate instead of just changing one singe line.

And the fix would be just change the visibility, that does not harm any logic...
