### ISSUE TITLE
Failure: scripts/test-scripted 'play-sbt-plugin/*3of3'

### ISSUE THREAD

**Issue by seglo** [playframework/playframework#10106]
https://travis-ci.com/playframework/playframework/jobs/292654863?utm_medium=notification&utm_source=email

```
scripts/test-scripted 'play-sbt-plugin/*3of3'
...
The command "scripts/test-scripted 'play-sbt-plugin/*3of3'" exited with 1.
```

There wasn't much other information to go on.  See build log.

**Comment by seglo** [comment]
https://travis-ci.com/playframework/playframework/jobs/292689750?utm_medium=notification&utm_source=email

```
scripts/test-scripted 'play-sbt-plugin/*2of3'
...
The command "scripts/test-scripted 'play-sbt-plugin/*2of3'" exited with 1.
```

Probably related.

**Comment by seglo** [comment]
https://travis-ci.com/playframework/playframework/jobs/292689820?utm_medium=notification&utm_source=email

**Comment by mkurz** [comment]
Since this might be related to Travis and we use GitHub actions now, I am closing. We can open new issues if something turns up with GHA.
