### ISSUE TITLE
Java 14 Support

### ISSUE THREAD

**Issue by jschwendt** [playframework/playframework#10125]
Given that Java 14 is due to launch on March 17, 2020, it would make sense to start working towards adding support for it in the upcoming versions of Play.  Here's what's new: https://medium.com/better-programming/whats-new-in-java-14-a472ec291c05

The new garbage collection model is very attractive!

**Comment by apflieger** [comment]
I found an incompatibility with the ebean plugin. The sbt play ebean plugin depends on a version of ebean-agent that doesn't support java14. An update might be sufficient

Details : The current ebean-agent does that https://github.com/ebean-orm/ebean-agent/blob/1aa70aeab69afd95afa849db8ee1eb5e00021671/src/main/java/io/ebean/enhance/asm/ClassReader.java#L182
It has been updated here https://github.com/ebean-orm/ebean-agent/commit/66a13c9c067054bc7bf7afdf0cfad2856406f4aa#diff-94e2228d56b0ae1bef52d3e21f9e81d1R194
Available in at least ebean-agent-12.1.11

**Comment by mkurz** [comment]
@apflieger You should report that in https://github.com/playframework/play-ebean

**Comment by apflieger** [comment]
Done https://github.com/playframework/play-ebean/issues/194

**Comment by ignasi35** [comment]
@jschwendt Java 14 is not an LTS so we'll probably hold until JDK 17 for any major work on supporting newer JDK's. Still, if you are only looking for GC improvements, I think running play in PROD mode on a JDK 14 "Should Work"™️.

**Comment by mkurz** [comment]
Let's close this in favor or #10478
