### ISSUE TITLE
Failed: Jabba - Syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by octonato** [playframework/playframework#10136]
Cron in `2.8.x`
https://travis-ci.com/github/playframework/playframework/jobs/299807852?utm_medium=notification&utm_source=email

Error fetching Jabba. Returned a html page instead of a file with shell script. 

```shell
$ curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh

bash: line 1: syntax error near unexpected token `newline'

bash: line 1: `<html>'

The command "curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh" failed and exited with 2 during .

Your build has been stopped.
```

**Comment by renatocaval** [comment]
Happened on another job on the same build:

https://travis-ci.com/github/playframework/playframework/jobs/299807850?utm_medium=notification&utm_source=email

**Comment by mkurz** [comment]
We use coursier now on GHA runners to set up the JVM so we can close this.
