### ISSUE TITLE
ActorSystemProvider should allow for DI aware ActorSystem

### ISSUE THREAD

**Issue by will-sargent-eero** [playframework/playframework#10160]
### Play Version

2.8.x

### API

Both

### Expected Behavior

I'm using a Play application which has some custom Akka remoting serialization classes.  The constructor has to be a single arg `ExtendedActorSystem`, with the expectation that you're using an Akka custom extension to pull everything out:

https://doc.akka.io/docs/akka/current/serialization.html

and 

https://doc.akka.io/docs/akka/current/extending-akka.html

The problem here is that we need to call out to some components that live in "Play space" through the Guice injector.

Akka *does* provide a facility for accessing custom components, but it's done through `dynamicAccess`, which by default instantiates through reflection:

https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorSystem.scala#L885

Whereas in this case we want to specify dynamic access as "resolve this through guice injector", which would then map out perfectly -- I don't think we'd even need a custom extension.

However, the configuration for doing this in Play is a bit more involved.  First, we need to override the default `Provider[ActorSystem]`, which is fair enough:

```scala
class GuiceAkkaAwareApplicationLoader extends GuiceApplicationLoader {
  protected override def overrides(context: ApplicationLoader.Context): Seq[GuiceableModule] = {
    super.overrides(context) :+ (bind[ActorSystemProvider].toProvider[GuiceAwareActorSystemProvider]: GuiceableModule)
  }
}
```

but then after that we start running into issues:

```scala
class GuiceAwareActorSystemProvider @Inject() (environment: Environment, configuration: Configuration) extends Provider[ActorSystem] {

  lazy val get: ActorSystem = ActorSystemProvider.start(environment.classLoader, configuration)
}
```

Here, the `ActorSystemProvider.start` is a method on the singleton object, so we can't swap it out very easily.  It has all kinds of configuration:

https://github.com/playframework/playframework/blob/master/core/play/src/main/scala/play/api/libs/concurrent/Akka.scala#L233

And the actual call is to the `ActorSystem.apply` method, so we can't swap that out for a subclassed instance that takes a guicified `DynamicAccess` as an argument.

## Suggestion

I think the thing to do here is to move `ActorSystemProvider.start` into the class, and then break down the `start` method into a series of smaller ones, including the instantiation, so it looks like:

```scala
class ActorSystemProvider @Inject() (environment: Environment, configuration: Configuration)
    extends Provider[ActorSystem] {
  lazy val get: ActorSystem = start(environment.classLoader, configuration)

  def start(classLoader: ClassLoader, config: Configuration): ActorSystem = ...

  def start(classLoader: ClassLoader, config: Configuration, additionalSetup: Setup): ActorSystem = ...

  def createActorSystem(name: String, actorSystemSetup): ActorSystem =  ActorSystem(name, actorSystemSetup)
}
```

This would then set things up for subclassing and DI aware versions that provided the injector / compile time application context etc.

## Related Issues

Can't find anything specific, but https://discuss.lightbend.com/t/akka-and-graal-s-native-image-tool/940/8 looks closest.

**Comment by will-sargent-eero** [comment]
Nevermind, this is trivial:

```scala
import akka.actor.{ActorSystem, _}
import javax.inject.{Inject, Provider}
import play.api.inject.guice._
import play.api.inject.{BindingKey, Injector, _}
import play.api.libs.concurrent.ActorSystemProvider
import play.api.{ApplicationLoader, Configuration, Environment}

import scala.reflect.ClassTag

class PlayAkkaApplicationLoader extends GuiceApplicationLoader {
  protected override def overrides(context: ApplicationLoader.Context): Seq[GuiceableModule] = {
    super.overrides(context) :+ (bind[ActorSystem].toProvider[GuiceAwareActorSystemProvider]: GuiceableModule)
  }
}

class GuiceAwareActorSystemProvider @Inject() (environment: Environment, configuration: Configuration, injector: Injector) extends Provider[ActorSystem] {
  lazy val get: ActorSystem = {
    val actorSystem = ActorSystemProvider.start(environment.classLoader, configuration)
    PlayAkkaExtension(actorSystem).initialize(injector)
    actorSystem
  }
}

class PlayAkkaExtensionImpl extends Extension {
  private var injector: Injector = _

  def initialize(injector: Injector): Unit = {
    this.injector = injector
  }

  def instanceOf[T](clazz: Class[T]): T = injector.instanceOf(clazz)

  def instanceOf[T: ClassTag]: T = injector.instanceOf

  def instanceOf[T](key: BindingKey[T]): T = injector.instanceOf(key)
}

object PlayAkkaExtension extends ExtensionId[PlayAkkaExtensionImpl] with ExtensionIdProvider {
  override def lookup() = PlayAkkaExtension
  override def createExtension(system: ExtendedActorSystem) = new PlayAkkaExtensionImpl
  override def get(system: ActorSystem): PlayAkkaExtensionImpl = super.get(system)
}
```

**Comment by ignasi35** [comment]
> Nevermind, this is trivial:

@will-sargent-eero I will close the issue since you seem to have found tha snwer yourself already. :)
