### ISSUE TITLE
play "test" command doesn't pickup config.file parameter

### ISSUE THREAD

**Issue by noppanit** [playframework/playframework#1017]
I'm trying to use application.conf and ci.conf to run database test in different environment. On CI  I use RDS MySQL and on local machine I use local MySQL. However, if I run this command in Jenkins (on EC2) "play -Dconfig.file=conf/ci.conf test" It still picks up application.conf. I try this by putting wrong database name. But -Dconfig.file=conf/ci.conf works for "play run/start" command but not "test" command.

**Comment by KaiStapel** [comment]
In case you want to map all system properties, you can do the following:

```
import scala.collection.JavaConversions.mapAsScalaMap
...
javaOptions in Test ++= mapAsScalaMap(System.getProperties).map(prop => s"-D${prop._1}=${prop._2}").toSeq,
```
