### ISSUE TITLE
temporary file folder no longer unique

### ISSUE THREAD

**Issue by bartschuller** [playframework/playframework#10194]
### Play Version

2.8.0-M4+

### API

Scala

### Operating System

`Linux primary 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### JDK

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

### Expected Behavior

1. We have an existing Play application which uses a file upload form. We're upgrading it from Play 2.6.21 to 2.8.1.
2. Under Play 2.6.21, when a user uploads a file, a temporary directory with a unique name is created, such as `/tmp/playtemp189725596617018652`
3. We depend on that directory being unique, because the same machine runs multiple independent Play applications, each under their own Unix user.

### Actual Behavior

1. The same application upgraded to Play 2.8.1 suddenly creates a directory `/tmp/playtemp`.
2. It's sister application running on the same machine under a different user tries to create a file within this directory (because it too is using `/tmp/playtemp` now) , but fails, because it doesn't own it.

### Reproducible Test Case

I can trace the regression to commit 940bd883b967c9334295ede160be0b38b0bc3920 belonging to #9390 which replaced a call to `JFiles.createTempDirectory(TempDirectoryPrefix)` with a call to `JFiles.createDirectories(Paths.get(s"$dir/$TempDirectoryPrefix"))`. The latter doesn't use it's argument as a prefix for a unique name.

**Comment by mkurz** [comment]
Thanks for the report. I will check. Let's target Play 2.8.2 with a fix if necessary.

**Comment by mkurz** [comment]
@bartschuller Do you want to provide a pull request with a fix?

**Comment by bartschuller** [comment]
Sorry, I don't have one.

**Comment by mkurz** [comment]
It's ok, I will take a look.
