### ISSUE TITLE
Put / Patch / Delete form

### ISSUE THREAD

**Issue by plippe** [playframework/playframework#10201]
Hey,

I was expecting the `helper.form` to behave similarly to the [Ruby on Rails one](https://guides.rubyonrails.org/form_helpers.html#how-do-forms-with-patch-put-or-delete-methods-work-questionmark), but it creates a form with unsupported methods.

This missing feature was raised as an [issue](https://github.com/playframework/playframework/issues/5313) before. 

I have a working solution. 

It uses a view to use `POST` and append a query string argument. *Please ignore the obvious bug.*
```
@(action: Call, args: (Symbol, String)*)(body: => Html)

@defining(
  if(Set("GET", "POST").contains(action.method)) { action }
  else { action.copy(url = s"${action.url}?_method=${action.method}", method = "POST") }
){ action =>
  @helper.form(action, args: _*)(body)
}
```

Once the form is posted, an `HttpRequestHandler` updates the request with the argument.

```scala
import javax.inject._  
import play.api.http._  
import play.api.mvc._  

@Singleton  
class RequestHandler @Inject()(default: DefaultHttpRequestHandler) extends HttpRequestHandler {  
 def handlerForRequest(request: RequestHeader): (RequestHeader, Handler) = {  
   val newRequest = request  
    .queryString  
    .get("_method")  
    .flatMap(_.headOption)  
    .fold(request)(request.withMethod)  

    default.handlerForRequest(newRequest)  
  }  
}  
```

Any interest in a PR for this, or should I create a library/module?

**Comment by mkurz** [comment]
Not really sure if we should include this hack in Play itself, see the discussion in the issue you referenced.
Since it looks like this could be a common issue, we could either document your workaround or, as you suggested, you could create a play module which we could reference from the play docs.

**Comment by plippe** [comment]
Hi @mkurz;

Thank you for your answer. 

Because it isn't "standard web", a library does make sense. 
Similarly, it makes sense to include features found in other popular web frameworks.
...

I will start working on the module. 
I am also happy to add my workaround in the documentation if that is something you wish.

**Comment by mkurz** [comment]
@plippe Let us know when your module is ready for prime time :+1:

**Comment by plippe** [comment]
Hey @mkurz;

I have a library up and running: https://github.com/plippe/play-form.
There are versions for play 2.6 to 2.8 as well as scala 2.11 to 2.13.

Code isn't perfect (build.sbt is 🤮), but everything should work.

I hope it helps.

**Comment by mkurz** [comment]
Nice!
You can add it to the Play modules directory: https://www.playframework.com/documentation/2.8.x/ModuleDirectory
Source: https://github.com/playframework/playframework/blob/master/documentation/manual/ModuleDirectory.md
Just open a pull request, thanks!

**Comment by plippe** [comment]
Thank you for your help
