### ISSUE TITLE
CONFIG_FORCE_: Environment variables appear twice in Configuration

### ISSUE THREAD

**Issue by GMShuhr** [playframework/playframework#10206]
### Play Version

2.8.1

### API

Scala 2.12.8

### Operating System

MacOS 10.15.4

### JDK

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

### Expected Behavior

1. Define an environment variable (e.g. CONFIG_FORCE_dummy_foo_bar=1) on the command line according to the naming scheme described in https://lightbend.github.io/config/latest/api/com/typesafe/config/ConfigFactory.html#systemEnvironmentOverrides--
2. Start sbt from command line with the option -Dconfig.override_with_env_vars=true to enable system environment overrides
3. In the running application, get the Configuration object (e.g. by dependency injection)
4. The entry "dummy.foo.bar" with value "1" should be found in the Configuration object.
5. The entry "CONFIG_FORCE_dummy_foo_bar" (i.e. the original name of the environment variable) should NOT be found in the configuration. 

### Actual Behavior

1. Define an environment variable (e.g. CONFIG_FORCE_dummy_foo_bar=1) on the command line according to the naming scheme described in https://lightbend.github.io/config/latest/api/com/typesafe/config/ConfigFactory.html#systemEnvironmentOverrides--
2. Start sbt from command line with the option -Dconfig.override_with_env_vars=true to enable system environment overrides
3. In the running application, get the Configuration object (e.g. by dependency injection)
4. The entry "dummy.foo.bar" with value "1" is found in the Configuration object.
5. The entry "CONFIG_FORCE_dummy_foo_bar" (i.e. the original name of the environment variable) with the same value IS ALSO found in the Configuration object.
6. Also any other environment variable existing at startup time whether it starts with "CONFIG_FORCE_" or not is found in the Configuration object.

The appearance of unwanted values in the Configuration object can lead to all kinds of problems, starting with name collisions and security and privacy issues.

The cause of the problem seems to be the implementation of com.typesafe.config.impl.ConfigImpl.loadEnvVariablesOverrides():

The "result" map gets initialized with all the original environment variables

`Map<String, String> result = new HashMap(System.getenv());`

It should instead be initialized to an empty map and only be filled by the loop following in the code.

**Comment by mkurz** [comment]
@GMShuhr even though Play may be affected by this behaviour, it is an issue with https://github.com/lightbend/config, therefore please open a bug report there, thanks!

**Comment by GMShuhr** [comment]
A copy of this issue was opened as [Config issue 684](https://github.com/lightbend/config/issues/684)

**Comment by mkurz** [comment]
Lets reopen this issue, maybe we can release and upgrade typesafe-config so https://github.com/lightbend/config/pull/686 makes it into Play 2.8.2

**Comment by ignasi35** [comment]
I have my doubts.

It is possible the statement `In the running application` implies starting a play application using an `sbt` task but spawning a forked JVM in which case it is possible the env var may not be visible (depending on how it was created?). I think this needs more information (or even a repdorucer)

**Comment by GMShuhr** [comment]
The bug is not that environment variables are invisible. The bug is that (if -Dconfig.override_with_env_vars=true ALL is set) ALL environment variables also end up in the configuration object without any name transformation.

The ones starting with "CONFIG_FORCE_" appear twice:
1. in the original form like all the other variables
2. in the correct transformed form, as described in [the documentation](https://lightbend.github.io/config/latest/api/com/typesafe/config/ConfigFactory.html#systemEnvironmentOverrides--)

**Comment by mkurz** [comment]
Fixed by #10492

**Comment by Normal** [comment]
I can't make it work at all, play (I use 2.7) just ignores `config.override_with_env_vars`, injected `play.api.Configuration` object doesn't override anything meanwhile `ConfigLoader.load` return overridden correct values. Is that a feature of play 2.8 or something?

**Comment by mkurz** [comment]
@Normal [The feature](https://github.com/lightbend/config/pull/620) is availabe since lightbend config version 1.3.4, which is [used since Play 2.7.2](https://github.com/playframework/playframework/blob/2.7.2/project/Dependencies.scala#L197). However there [was a bug](https://github.com/lightbend/config/issues/684), which was fixed in Play 2.8.3, [which comes with lightbend config 1.4.1](https://github.com/playframework/playframework/blob/2.8.3/project/Dependencies.scala#L200).
