### ISSUE TITLE
Play uses outdated jjwt artifact and version

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#10211]
From `./project/Dependencies.scala`:

    val jjwt = "io.jsonwebtoken" % "jjwt" % "0.9.1"

That library hasn't been updated since 2018. We should instead be using `jjwt-api`, `jjwt-impl`, and `jjwt-jackson`. The latest version is 0.11.1

For more details, see https://github.com/jwtk/jjwt#maven

**Comment by benmccann** [comment]
It looks like there was discussion of upgrading in https://github.com/playframework/playframework/issues/8446

Based on that discussion, if we upgrade jjwt then we can revert https://github.com/playframework/playframework/pull/8382

**Comment by mkurz** [comment]
Fix is here #10726
