### ISSUE TITLE
Scripted tests fail when akka/akka-http are released concurrently

### ISSUE THREAD

**Issue by raboof** [playframework/playframework#10215]
https://travis-ci.com/github/playframework/playframework/builds/161408298

When a new snapshot of akka or akka-http is released while a nightly build against those snapshots is running, the versions can get inconsistent between jobs in which case the resources won't be found.

I think we should write the play version into a file on the workspace so the scripted tests always pick the exact versions that the original compilation used.

**Comment by renatocaval** [comment]
Happened again: 
https://travis-ci.com/github/playframework/playframework/jobs/322481888#L557

**Comment by fusuiyi123** [comment]
Hi @raboof may I work on this? But i would like some pointers to start! thanks!

**Comment by seglo** [comment]
https://travis-ci.com/github/playframework/playframework/jobs/327261314

**Comment by raboof** [comment]
@fusuiyi123 of course! currently, in `.travis.yml` you can see that the phase with name `Run publishLocal` run `scripts/publish-local` and creates a workspace called `published-local`.

Since `scripts/publish-local` starts by cleaning `~/.ivy2/local`, I think we can just look in that directory to find the version number.

The scripted tests run `scripts/test-scripted`. It will use the Akka version set by `scripts/scriptLib`.

The first step would be to write a small shell snippet that extracts the version from ~/.ivy2/local. The next step is to use that to make sure AKKA_VERSION_OPTS and AKKA_HTTP_VERSION_OPTS are correctly set to that value for the scripted tests, instead of relying on the values `scriptLib` currently sets with `curl`.

Does that help?

**Comment by fusuiyi123** [comment]
thanks for your response. It's very helpful, I will send a pr:)

**Comment by fusuiyi123** [comment]
I raised https://github.com/playframework/playframework/pull/10263 , not sure if I am doing it correctly.
