### ISSUE TITLE
Allow returning JSON String

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#10219]
### Feature Description

Allow returning a JSON `String`. [The documentation](https://www.playframework.com/documentation/2.8.x/JavaJsonActions) does not describe how to do this nor can I figure it out from the API. I believe that today it's only possible to return a Jackson `JsonNode`.

### Use Case

I'm working with an API that returns me a JSON `String`. The only way I can figure out how to return this in Play with the proper content-type is to parse the string into a `JsonNode` and return that, but it's very wasteful to parse a string just to turn it back into a `String` again.

### Possible Implementations

It could be nice to add both of the following APIs:
* Allow specification of `contentType` in addition to `encoding`
* Add `StatusHeader.sendJson` method which takes a `String`

### API

Java

**Comment by mkurz** [comment]
`StatusHeader.sendJson` sets the content type to `application/json`:
https://github.com/playframework/playframework/blob/48295bc1bbf3c055c07ff5e3e0c47c797a9353b2/core/play/src/main/java/play/mvc/StatusHeader.java#L1895
What's wrong with that? Why you want/need to set it explicitely?

Adding a String overload sounds like a good idea.

**Comment by benmccann** [comment]
The `String` overload would work fine for me. I do indeed want the content type set to `application/json`.

There other thing I was suggesting an overload to `Results.status` or `Results.ok` that let me specify the content type might also let me accomplish what I'm trying to do. Today if you pass a `String` to either of those it forces the content type to be `text/html` which isn't what I want. Perhaps both overloads would be useful to give more flexibility, but I would be fine with either one.

**Comment by mkurz** [comment]
What about:
```java
Results.ok("<json>", "<charset>").as(play.mvc.Http.MimeTypes.JSON);
``?

**Comment by benmccann** [comment]
Aha! I missed that. That's great. Thanks for the pointer

I'll send a PR
