### ISSUE TITLE
Multiple (non-implicit) parameters to a symbolic/infix should be avoided

### ISSUE THREAD

**Issue by octonato** [playframework/playframework#10221]
In #10199 we added symbolic methods to TypeMap, but as signaled by @NthPortal we should avoid this. 

Triggered by: 

I'm a bit late to the party here, but multiple (non-implicit) parameters to a symbolic/infix method are highly discouraged,  and planned to be deprecated. See scala/scala-dev#496 and https://github.com/lampepfl/dotty/pull/4311#issuecomment-435593905.

_Originally posted by @NthPortal in https://github.com/playframework/playframework/pull/10199_

**Comment by renatocaval** [comment]
From my part we can remove all the new symbolic operators.

**Comment by mkurz** [comment]
> ... we added symbolic methods ... but ... we should avoid this

Just to make things clear, not symbolic methods should be avoided, but multi-params for this methods.

**Comment by renatocaval** [comment]
Yes, but we will have an imbalance in the API if we remove only a those with multi-params.

**Comment by BillyAutrey** [comment]
In #11672, I opted to do the following:

* Add multiple signatures for `updated`, to reflect all the current usages of `+`
* Also, add the same signatures for `removed`, to have parity for `-` functionality.
* Mark `+` and `-` methods as deprecated.
