### ISSUE TITLE
Recommend using a recent JDK version, de-emphasize jetty-alpn

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#10246]
See https://github.com/akka/akka-http/issues/3100
See https://github.com/akka/akka-grpc/issues/942

This includes, the plugin, docs and (¿)tests(?).

**Comment by mkurz** [comment]
For upcoming Play 2.9 how about to just completely remove `jetty-alpn` and just make JDK 8u252 the minimal JDK 8 requirement?

**Comment by ignasi35** [comment]
related to #9941

**Comment by mkurz** [comment]
Pull request: #10734
