### ISSUE TITLE
Multiple test failures usin JDK 8u252+

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#10250]
Related https://github.com/akka/akka-grpc/issues/946

JDK 8u252+ backported some improvements in ALPN handling. As a consequence, using HTTP/2 no longer requires a 3rd party ALPN agent (aka jetty-alpn-agent). At the same time, though, there's been some extra change causing several tests to break.

At the time of this writing (May 1st, 2020) Jabba still doesn't provide JDK8u252 so this can't yet be reproduced in Travis CI

**Comment by mkurz** [comment]
> At the time of this writing (May 1st, 2020) Jabba still doesn't provide JDK8u252 so this can't yet be reproduced in Travis CI

@ignasi35 252 arrived in Jabba and as expected some tests fail: https://travis-ci.com/github/playframework/playframework/jobs/331365730#L1047

Let's see if #10268 fixes them.

**Comment by mkurz** [comment]
Fixed with #10268
