### ISSUE TITLE
nightly-deploy-2.8.x: error uploading play-docs-sbt-plugin

### ISSUE THREAD

**Issue by raboof** [playframework/playframework#10305]
/home/play/logs/nightly-deploy-2.8.x-1590118926.log

```
[error] java.lang.RuntimeException: error uploading to com.typesafe.play/play-docs-sbt-plugin/scala_2.10/sbt_0.13/2.8.2-2020-05-21-bc1badd-SNAPSHOT/jars/play-docs-sbt-plugin.jar: {"message":"Failed to create version, invalid version name: 2.8.2-2020-05-21-bc1badd-SNAPSHOT"}
```

**Comment by raboof** [comment]
again in /home/play/logs/nightly-deploy-2.8.x-1590205384.log

**Comment by raboof** [comment]
again in /home/play/logs/nightly-deploy-2.8.x-1590291844.log

**Comment by raboof** [comment]
again in /home/play/logs/nightly-deploy-2.8.x-1590378419.log

this seems to be failing consistently

**Comment by ignasi35** [comment]
I think this could be related to the fact that Play `2.8.x` is already using `sbt-dynver`. So, the cron job deploying the snapshot should embrace `sbt-dynver` and stop using the [play-especific versioning strategy](https://github.com/lightbend/vegemite/blob/4cbea69ff32f144f22b64f9983141f86c13d42af/deploy/utils) (which produces  version names like `2.8.2-2020-05-21-bc1badd-SNAPSHOT`).

**Comment by patriknw** [comment]
similar "Nightly task nightly-deploy-2.8.x failed"

/home/play/logs/nightly-deploy-2.8.x-1590378419.log

```
[error] java.lang.RuntimeException: error uploading to com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.8.2-2020-05-24-bc1badd-SNAPSHOT/jars/sbt-plugin.jar: {"message":"Failed to create version, invalid version name: 2.8.2-2020-05-24-bc1badd-SNAPSHOT"}
```

**Comment by patriknw** [comment]
ah, that ^ was already reported above
