### ISSUE TITLE
Failed to download jabba from github

### ISSUE THREAD

**Issue by raboof** [playframework/playframework#10306]
Github returning 500's, curl correctly retrying but eventually giving up.

One improvement we could do here is to not download jabba at all when one is already found in the cache.

https://travis-ci.com/github/playframework/playframework/jobs/339133182

**Comment by raboof** [comment]
Also https://travis-ci.com/github/playframework/playframework/jobs/339133155

**Comment by mkurz** [comment]
No more jabba used with GitHub actions which is the new cool kid on the block now.
