### ISSUE TITLE
sbt dist included in Hello World projects is old

### ISSUE THREAD

**Issue by eed3si9n** [playframework/playframework#10315]
This is more of a bug report to Example Code Service (https://example.lightbend.com/) than Play per se, but it affects Play new users mostly.

### Play Version

2.8.2

### API

Scala

### Operating System

macOS

### JDK

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

### Expected Behavior

1. Go to https://www.playframework.com/getting-started or  https://developer.lightbend.com/start/?group=play, and download a sample Play project via "Create a project for me."
2. The sbt distribution included in the zip is the latest stable version.

### Actual Behavior

1. Go to https://www.playframework.com/getting-started or  https://developer.lightbend.com/start/?group=play, and download a sample Play project via "Create a project for me."
2. It looks like the sbt distribution included into the created build is [sbt 0.13.11](https://github.com/sbt/sbt/releases/tag/v0.13.11) from 2016.

## note

Even though `project/build.properties` dictate the sbt artifact version, `sbt` shell and batch scripts would not have any of the updates, for example fixes related to parsing modern Java versions. I think this results to occasional confused sbt bug reports saying they can't run sbt on JDK 11. Not a very good out-of-box experience.

**Comment by PromanSEW** [comment]
Already fixed
https://example.lightbend.com/v1/download/play-samples-play-java-hello-world-tutorial has sbt 1.6.2

**Comment by ihostage** [comment]
Fixed by https://github.com/playframework/play-samples/pull/158

**Comment by ihostage** [comment]
Thanks for notification, @PromanSEW!
