### ISSUE TITLE
[2.8.x failure] sbt tests can't find Play `sbt-plugin`

### ISSUE THREAD

**Issue by ennru** [playframework/playframework#10324]
All sbt tests (0.13 and 1.x) fail to resolve the Play sbt-plugin since the update to sbt 1.3.12 in https://github.com/playframework/playframework/commit/99f4b080f0d704117d18ac7c4910557d0b868cef

`module not found: com.typesafe.play#sbt-plugin;2.8.2+4-80bad4f7-akka-2.6.5+106-33d64f9d-akka-http-10.2.0-M1+103-0d857b48`

https://travis-ci.com/github/playframework/playframework/builds/169568254

**Comment by raboof** [comment]
This is the issue that's fixed by #10302 I think

**Comment by ennru** [comment]
Great, let's see how it goes tomorrow.

**Comment by mkurz** [comment]
Looks good now, I guess this issue can be closed?

**Comment by ennru** [comment]
Yes, thanks for the ping.
