### ISSUE TITLE
Failed: akka-http artifacts not found

### ISSUE THREAD

**Issue by renatocaval** [playframework/playframework#10338]
Failed to download artifacts:

https://travis-ci.com/github/playframework/playframework/jobs/349097968#L1575-L1582

```scala
[info] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[info] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] [warn] 	:: com.typesafe.play#sbt-plugin;2.8.2+11-b538b07b-akka-2.6.6+24-4f2e82e5-akka-http-10.2.0-M1+113-140025a2: not found
[info] [warn] 	:: com.typesafe.play#sbt-scripted-tools;2.8.2+11-b538b07b-akka-2.6.6+24-4f2e82e5-akka-http-10.2.0-M1+113-140025a2: not found
[info] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] [warn] 
[info] [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
```

Should have been fixed when #10083 was backported to 2.8.x, which was done in #10140.

**Comment by renatocaval** [comment]
That happen on a CRON job in 2.8.x

**Comment by raboof** [comment]
The publish task used version 10.2.0-M1+112 (https://travis-ci.com/github/playframework/playframework/jobs/349097959#L233) and claims to have saved that to disk (https://travis-ci.com/github/playframework/playframework/jobs/349097959#L5000)

However apparently the sbt job did not pick this up: https://travis-ci.com/github/playframework/playframework/jobs/349097968#L239

**Comment by raboof** [comment]
This is because the version is stored in `~/.ivy2/local/AKKA_VERSION` and  `~/.ivy2/local/AKKA_HTTP_VERSION` (https://github.com/playframework/playframework/blob/2.8.x/scripts/publish-local#L18), but only `~/.ivy2/local/com.typesafe.play` is stored in the travis workspace (https://github.com/playframework/playframework/blob/2.8.x/.travis.yml#L46)

**Comment by raboof** [comment]
(that problem also appears to exist on master)

**Comment by ignasi35** [comment]
Again in https://travis-ci.com/github/playframework/playframework/builds/171573503

**Comment by ignasi35** [comment]
Hmmm, play `2.8.x` should not try to download Akka-HTTP `10.2` and, instead, stay on `10.1.x`.
