### ISSUE TITLE
Failed: javaguide.ehcache.JavaEhCache.http assertion failure

### ISSUE THREAD

**Issue by seglo** [playframework/playframework#10332]
On cron build

https://travis-ci.com/github/playframework/playframework/jobs/346380224#L2785
	
```
[error] Test javaguide.ehcache.JavaEhCache.http failed: 
[error] Expected: "something else"
[error]      but: was "Hello world", took 0.097 sec
```

**Comment by ignasi35** [comment]
https://travis-ci.com/github/playframework/playframework/jobs/389524516#L2640

**Comment by mkurz** [comment]
I haven't seen this failure quite a while. Since this might be related to Travis and we use GitHub actions now, I am closing. We can open new issues if something turns up with GHA.
