### ISSUE TITLE
Initial scala play setup doesn't work in IntelliJ

### ISSUE THREAD

**Issue by tunesmith** [playframework/playframework#10361]
### Play Version

2.8.2

### API

Scala

### Operating System

Mac 10.14.6

### JDK

1.8.0_171

### Expected Behavior

1. When invoking `sbt new playframework/play-scala-seed.g8` I should be able to use it in IntelliJ (2020.1.2)
2. Or, when starting a new vanilla sbt project (which works in IntelliJ) using Scala 2.13.3 and SBT 1.3.13, I should be able to add the Play sbt plugin and have it work in IntelliJ

### Actual Behavior
1. For the play-scala-seed, I get 

    https://repo1.maven.org/maven2/org/webjars/npm/4.2.0/npm-4.2.0-sources.jar: not found: https://repo1.maven.org/maven2/org/webjars/npm/4.2.0/npm-4.2.0-sources.jar  

If I add `useCoursier := false`, it gets further, but then I get 

    (updateSbtClassifiers) java.lang.IllegalArgumentException: Cannot add dependency 'com.typesafe.play#sbt-routes-compiler_2.12;2.8.2' to configuration 'default' of module com.example#play-scala-seed$sbt_2.12;1.0-SNAPSHOT because this configuration doesn't exist!

2. If I start with a vanilla sbt project, the same error pattern happens if I merely add:

```scala
lazy val root = (project in file(".")).enablePlugins(PlayScala)
```
to build.sbt, and 

```scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.2")
```

to plugins.sbt . The `npm` error happens first, and then the `sbt-routes-compiler` error happens if I turn off coursier.

The end result as it stands right now is I'm not sure how to start a new Scala Play project in IntelliJ.

**Comment by tunesmith** [comment]
Believe it or not, everything started working for me when I unchecked "Download sbt sources". The errors return when I check it, and go away again when I uncheck it.

I'm not sure if this is a play bug, an IntelliJ bug, or an sbt bug, but I think this could cross up other developers. Any idea how this should be addressed or where it should be filed?

**Comment by wsargent** [comment]
This sounds like an IntelliJ Scala bug.  You could look on https://intellij-support.jetbrains.com/hc/en-us/community/topics/200381545-Scala and see if they have any advice on how to fix it, but it's not Play itself.

**Comment by tunesmith** [comment]
I will check there too, but it's notable that the bug didn't manifest until I tried adding the Play sbt plugin.

**Comment by ignasi35** [comment]
Since this seems to be unrelated to Play I'll close. 

Thanks for reporting and sharing your findings,  @tunesmith !
