### ISSUE TITLE
QueryStringBindable.bindableString.unbind() produces URL-encoded keys, other binders - don't

### ISSUE THREAD

**Issue by helllamer** [playframework/playframework#10369]
### Play Version
play-`2.8.2`

### API
Scala

### Operating System
`Linux pc 5.7.6-arch1-1 #1 SMP PREEMPT Thu, 25 Jun 2020 00:14:47 +0000 x86_64 GNU/Linux`

### JDK
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

### Library Dependencies
None

### Expected Behavior
`implicitly[QueryStringBindable[String]].unbind()` should NOT URL-encode key-part.
```
$ sbt console
import play.api.mvc.QueryStringBindable

scala> QueryStringBindable.bindableChar.unbind( "items[1]", '1' )
val res1: String = items[1]=1

scala> QueryStringBindable.bindableInt.unbind( "items[1]", 1 )
val res2: String = items[1]=1

scala> QueryStringBindable.bindableString.unbind( "items[1]", "1" )
val res3: String = items%5B1%5D=1

scala> QueryStringBindable.bindableDouble.unbind( "items[1]", 1 )
val res4: String = items[1]=1.0
```

### Actual Behavior
As you can see, the `res3` contains unexpected URL-encoded characters for `[` and `]` in key part: `items%5B1%5D`.
Other binders works as expected: `items[1]`.

Problem is in [play/api/mvc/Binders.scala#L312](https://github.com/playframework/playframework/blob/ddf3a7ee4285212ec665826ec268ef32b5a76000/core/play/src/main/scala/play/api/mvc/Binders.scala#L312).

**Comment by mkurz** [comment]
@helllamer Do you want to provide a pull request with a fix? Would be great!
