### ISSUE TITLE
Play runner failure in MacOS Big Sur

### ISSUE THREAD

**Issue by zhye9452** [playframework/playframework#10372]
### Play Version

2.8.2

### API

Scala

### Operating System

MacOS Big Sur Developer Beta Seed 1

### JDK

JDK 11

### Expected Behavior

1. `sbt run`

### Actual Behavior

1. `sbt run` fails to run with below exception
```
[error] java.lang.UnsatisfiedLinkError: Unable to load library 'Carbon':
[error] dlopen(libCarbon.dylib, 9): image not found
[error] dlopen(libCarbon.dylib, 9): image not found
[error] 	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
[error] 	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
[error] 	at com.sun.jna.Library$Handler.<init>(Library.java:192)
[error] 	at com.sun.jna.Native.loadLibrary(Native.java:646)
[error] 	at com.sun.jna.Native.loadLibrary(Native.java:630)
[error] 	at io.methvin.watchservice.jna.CarbonAPI.<clinit>(CarbonAPI.java:20)
[error] 	at io.methvin.watchservice.jna.CFStringRef.toCFString(CFStringRef.java:23)
[error] 	at io.methvin.watchservice.MacOSXListeningWatchService.register(MacOSXListeningWatchService.java:128)
[error] 	at io.methvin.watchservice.WatchablePath.register(WatchablePath.java:50)
[error] 	at io.methvin.watcher.DirectoryWatcher.register(DirectoryWatcher.java:341)
[error] 	at io.methvin.watcher.DirectoryWatcher.registerAll(DirectoryWatcher.java:315)
[error] 	at io.methvin.watcher.DirectoryWatcher.<init>(DirectoryWatcher.java:176)
[error] 	at io.methvin.watcher.DirectoryWatcher$Builder.build(DirectoryWatcher.java:117)
[error] 	at play.dev.filewatch.DefaultFileWatchService.watch(DefaultFileWatchService.scala:38)
[error] 	at play.dev.filewatch.FileWatchService$$anon$1.watch(FileWatchService.scala:87)
[error] 	at play.runsupport.Reloader.<init>(Reloader.scala:443)
[error] 	at play.runsupport.Reloader$.reloader$lzycompute$1(Reloader.scala:283)
[error] 	at play.runsupport.Reloader$.play$runsupport$Reloader$$reloader$1(Reloader.scala:275)
[error] 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:311)
[error] 	at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:98)
[error] 	at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:81)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:105)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
```

**Comment by mkurz** [comment]
@gmethvin seems like there is a bug in your [directory-watcher](https://github.com/gmethvin/directory-watcher) lib on upcoming MacOS Big Sur.

**Comment by gmethvin** [comment]
@zhye9452 @mkurz Let's report a bug on https://github.com/gmethvin/directory-watcher/issues and discuss there. In the mean time, I suppose we can switch to an alternative watch service for Play.

It looks like that library doesn't exist in Big Sur, so we'll have to figure out if there's an alternative API we can use.

**Comment by zhye9452** [comment]
@gmethvin https://github.com/gmethvin/directory-watcher/issues/52

**Comment by ignasi35** [comment]
> I suppose we can switch to an alternative watch service for Play.

While there's no fix out of the box, Play users can opt out of the default file watcher using the following play-plugin setting in their sbt build:

```
// demoes jdk7 but others are available
PlayKeys.fileWatchService := play.dev.filewatch.FileWatchService.jdk7(play.sbt.run.toLoggerProxy(sLog.value))
```

**Comment by 17hao** [comment]
> > I suppose we can switch to an alternative watch service for Play.
> 
> ~While~ _Until_ there's a fix out of the box, Play users can opt out of the default file watcher using the following play-plugin setting in their sbt build:
> 
> ```
> // demoes jdk7 but others are available
> PlayKeys.fileWatchService := play.dev.filewatch.FileWatchService.jdk7(play.sbt.run.toLoggerProxy(sLog.value))
> ```

Maybe we should add extra dependency: ["com.lightbend.play" %% "play-file-watch" % "x.x.x"](https://mvnrepository.com/artifact/com.lightbend.play/play-file-watch_2.12) :)

**Comment by esdiacglobalsystem** [comment]
> > I suppose we can switch to an alternative watch service for Play.
> 
> ~While~ _Until_ there's a fix out of the box, Play users can opt out of the default file watcher using the following play-plugin setting in their sbt build:
> 
> ```
> // demoes jdk7 but others are available
> PlayKeys.fileWatchService := play.dev.filewatch.FileWatchService.jdk7(play.sbt.run.toLoggerProxy(sLog.value))
> ```

How can we add it to a lagom project

**Comment by brabo-hi** [comment]
> > I suppose we can switch to an alternative watch service for Play.
> 
> ~While~ _Until_ there's a fix out of the box, Play users can opt out of the default file watcher using the following play-plugin setting in their sbt build:
> 
> ```
> // demoes jdk7 but others are available
> PlayKeys.fileWatchService := play.dev.filewatch.FileWatchService.jdk7(play.sbt.run.toLoggerProxy(sLog.value))
> ```

How can we add it to a lagom project

**Comment by ignasi35** [comment]
https://github.com/playframework/play-file-watch/releases/tag/1.1.13 (with BigSur support) is ready.

**Comment by mkurz** [comment]
> I suppose we can switch to an alternative watch service for Play.

I think the long term plan is to completely replace play-file-watch/directory-watcher by sbt's own file watching capabilities, introduced in sbt 1, see #9956

**Comment by ennru** [comment]
Fixed with #10450

**Comment by mariussoutier** [comment]
> How can we add it to a lagom project

lagomFileWatchService := _root_.play.dev.filewatch.FileWatchService.jdk7(_root_.play.sbt.run.toLoggerProxy(sLog.value))

**Comment by odwrotnie** [comment]
> > How can we add it to a lagom project
> 
> `lagomFileWatchService := play.dev.filewatch.FileWatchService.jdk7(play.sbt.run.toLoggerProxy(sLog.value))`

It makes no change - I have the exception anyway.

**Comment by mariussoutier** [comment]
> > > How can we add it to a lagom project
> > 
> > 
> > `lagomFileWatchService := play.dev.filewatch.FileWatchService.jdk7(play.sbt.run.toLoggerProxy(sLog.value))`
> 
> It makes no change - I have the exception anyway.

I think then it's not active, there should be no JNA exception now.

Anyway, I don't need it anymore with Azul JDK 11.0.10, native version works fine now on M1 / BigSur.
