### ISSUE TITLE
llegalArgumentException: Serializer identifier [..] of [...] is not unique

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#10384]
(this is a cross-post from https://github.com/akka/akka/issues/29351)

> In 2.6.6 we added the check of using same serializer id more than once.

As @patriknw mentioned in the issue: 

> I couldn't reproduce.

> Could be something with the config loading in Play...

It's possible this hasn't surfaced more because there's no Play release using Akka 2.6.6 out, yet. Users facing this are either using Vanilla Akka applications or a Play application with overridden dependencies of Akka.

**Comment by mkurz** [comment]
This was fixed in akka long time ago.
