### ISSUE TITLE
Form validation not working as I expected.

### ISSUE THREAD

**Issue by nrowley** [playframework/playframework#10404]
Following the example on in the documentation, posting form data to be validated within the controller doesn't seem to work.

![Screenshot 2020-07-31 at 09 21 11](https://user-images.githubusercontent.com/47508642/89015686-5b6c0f00-d30f-11ea-8a76-179ed8d304d8.png)
![Screenshot 2020-07-31 at 09 21 25](https://user-images.githubusercontent.com/47508642/89015695-5f982c80-d30f-11ea-92a0-e0de16735408.png)
![Screenshot 2020-07-31 at 09 21 30](https://user-images.githubusercontent.com/47508642/89015698-6161f000-d30f-11ea-92b4-c5179acc3fd7.png)

the username and email fields are null.

**Comment by PromanSEW** [comment]
You need set "name" attribute for inputs, not "id"

**Comment by nrowley** [comment]
thanks I will close the issue
