### ISSUE TITLE
2.8 snapshot cron not picking up correct version

### ISSUE THREAD

**Issue by chbatey** [playframework/playframework#10402]
`Using Akka SNAPSHOT 2.6.8+10-438e1953 and Akka HTTP SNAPSHOT 10.1.12+14-b9d528cc`

`info] [error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play#sbt-plugin;2.8.2+23-cf4e0cb8-akka-2.6.8+10-438e1953-akka-http-10.1.12+14-b9d528cc: not found
[info] [error] unresolved dependency: com.typesafe.play#sbt-scripted-tools;2.8.2+23-cf4e0cb8-akka-2.6.8+10-438e1953-akka-http-10.1.12+14-b9d528cc: not found`

https://travis-ci.com/github/playframework/playframework/jobs/365705052

**Comment by raboof** [comment]
again at https://travis-ci.com/github/playframework/playframework/builds/188145761

This was already fixed for master at #10341, I now triggered a backport of that change under #10467

**Comment by mkurz** [comment]
As said, this was fixed by #10467
