### ISSUE TITLE
If no new data arrives GzipFilter buffers data indefinitely up to the defined chunk size

### ISSUE THREAD

**Issue by jrudolph** [playframework/playframework#10418]
The Chunker holds back data indefinitely if the buffer is not filled.

In fact, it's unclear what the purpose of the chunker is in front of the gzip compression in GzipFlow. 

~Most likely it is an attempt to make compression work if the input data is chunked to very small pieces. Akka Stream's Compression.Gzip does a [`SYNC_FLUSH`](https://www.bolet.org/~pornin/deflate-flush.html) after each chunk which will create a new deflate block for each chunk. This leads to an extra constant 4 bytes delimiter per chunk and reduced compression rate because of potentially suboptimal Huffman encoding because short blocks do not aggregate enough statistics to warrant custom and more optimal huffman coding. In any case, the LZ part of compression (finding repetitions in recent stream history) works across chunks and the default huffman table will still be good enough for most purposes.~

~There's a tradeoff between better compression rate and sending data earlier. One reasoning not to require the extra buffers of the chunker is that if you have a high-throughput stream, you are more likely already have data in bigger chunks, i.e. extra chunking in GzipFlow is not required. On the other hand, if you send out small chunks, data will probably arrive in greater intervals, i.e. throughput is not the main concern, so there's no reason to retain data (potentially indefinitely) for the purpose of optimizing compression rate.~

*EDIT: I don't think the above explanation makes sense. This issue is just a bug AFAIU. The purpose of the chunker seems to be to limit the **maximum** amount of data to send to the gzip stage and not the **minimum**. So, there's no reason hold back data in `onPull`.*

It seems the Chunker was introduced in #6813 in 2016 and later improved in #9520. @schmitch do you happen to remember why you added the Chunker?

**Comment by schmitch** [comment]
yeah the chunker was mainly to keep the surface api the same. play can configure a `bufferSize` for gzip. thus to satisfy the api I added the chunker.

> The Chunker holds back data indefinitely if the buffer is not filled.

yeah it would hold back until no data is incoming anymore, but it should still push all the data out, if the source completes.

yeah maybe it would be better to deprecate the current interface and maybe make the `bufferSize` an `Option[Int]` which does not use the chunker if no `bufferSize` is wished. (and of course remove the default `bufferSize` of `8192` in play)

**Comment by FranklinYinanDing** [comment]
> Most likely it is an attempt to make compression work if the input data is chunked to very small pieces.

@jrudolph Maybe I understand it wrong, or something isn't right - [this line](https://github.com/playframework/playframework/pull/6813/files#diff-dc46281aa6759e9b0b71d023b83fc87aR66) uses `splitAt`, when the buffer is smaller than the `chunkSize` (say 3 vs 8192), it will still produce the entire buffer (3) and push. So if the Http.Chunked is a sequence of small chunks, Gzip is still compressing small chunks.

> yeah it would hold back until no data is incoming anymore, but it should still push all the data out, if the source completes.

@schmitch My biggest problem of this is about resizing/concatenating chunks and more-importantly, the timing of the completion of each chunk. A very late second chunk will cause the delay of the first chunk's completion (when the browser completely receives the whole), if the first chunk is a script tag for the browser to eval, then the timing of the execution of that script tag is hugely delayed. Service's own server behaves in such a way really catches users by surprise, as they are not seeing the same thing as what they send/expect.

**Comment by schmitch** [comment]
> A very late second chunk will cause the delay of the first chunk's completion (when the browser completely receives the whole), if the first chunk is a script tag for the browser to eval, then the timing of the execution of that script tag is hugely delayed.

that can't happen since the play gzip flow only works on a response body: https://github.com/playframework/playframework/blob/master/web/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala#L78

unfortunatly `GzipFlow.gzip` is a public interface, which it probably should not be. since the user should just use the akka stuff directly. the gzip filter of play is mostly designed for html/css/javascript content with a "fast producer".

**Comment by jrudolph** [comment]
> yeah the chunker was mainly to keep the surface api the same. play can configure a `bufferSize` for gzip. thus to satisfy the api I added the chunker.

Maybe that's not needed and we can just use `bufferSize = 0` for that. Another possibility would be to keep the interface but ignore the parameter for now.

**Comment by jrudolph** [comment]
@FranklinYinanDing 

> @jrudolph Maybe I understand it wrong, or something isn't right - [this line](https://github.com/playframework/playframework/pull/6813/files#diff-dc46281aa6759e9b0b71d023b83fc87aR66) uses `splitAt`, when the buffer is smaller than the `chunkSize` (say 3 vs 8192), it will still produce the entire buffer (3) and push. So if the Http.Chunked is a sequence of small chunks, Gzip is still compressing small chunks.

I think that's correct, however, `emitChunk` is only called unconditionally from `onPush`. As you noted elsewhere, `onPull` still has this precondition which will prevent sending smaller chunks:

https://github.com/playframework/playframework/blob/f6ae7c8c50556d79b95c3a42c29dd21eae3261ad/core/play-streams/src/main/scala/play/api/libs/streams/GzipFlow.scala#L43

@schmitch 

> > A very late second chunk will cause the delay of the first chunk's completion (when the browser completely receives the whole), if the first chunk is a script tag for the browser to eval, then the timing of the execution of that script tag is hugely delayed.
> 
> that can't happen since the play gzip flow only works on a response body: [https://github.com/playframework/playframework/blob/master/web/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala#L78](https://github.com/playframework/playframework/blob/master/web/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala?rgh-link-date=2020-08-11T18%3A08%3A42Z#L78)

Why not? It gets only pulled once and then the above condition prevents sending over the remaining data.

Maybe we should just fix that condition (as @FranklinYinanDing suggested elsewhere).

**Comment by schmitch** [comment]
well if I have a script file that should be gzipped and my stream would "hang" or never complete, the browser would hang forever, since the browser parser would block the remaining execution if the script tag is not defined at the end or with `defer`.

a chunkSize of 0 would not fix that, the stream would still never complete and the browser would still wait either for 1. content-length satisfied or wait for a http chunk with length zero.

**Comment by jrudolph** [comment]
Looking at the code again, you might be able to actually disable the buffer by setting the buffer size to a higher value than any of the input chunks you expect, e.g. like `Int.MaxValue`. In that case, the `splitAt` in `onPush` would always pass on all of the data it receives and no data would ever be buffered.

**Comment by jrudolph** [comment]
Fix in #10422 which also explicitly adds the possibility to disable the buffer with a value of `0`.
