### ISSUE TITLE
Same site should have 4 values : null AND None are different cases (+ Lax, Strict)

### ISSUE THREAD

**Issue by wadouk** [playframework/playframework#10433]
### Play Version

2.7.0

### API

Scala

### Operating System

Linux wadouk-pc 5.4.58-1-MANJARO

### JDK

openjdk version "1.8.0_262"

### Expected Behavior

1. SameSite should have three differents values, and a forth to remove the attribute in the cookie
2. https://web.dev/samesite-cookies-explained/

### Actual Behavior

1. When I put play.http.session.sameSite=null it removes the SameSite attribute in the set cookie header
2. When I put play.http.session.sameSite='None" i have a trace Assuming "play.http.session.sameSite = null, since "None" is not a valid SameSite value (Strict, Lax)"

None and null are two differents use cases

### What I can't do because of this

- I have to downgrade my chrome to continue to develop
- I can't no more login between front in localhost (js app) and back (play scala deployed) in the app because of this behaviour, the cookie is refused because of missing sameSite.

**Comment by mkurz** [comment]
Which _exact_ version of Play are you using?

**Comment by wadouk** [comment]
2.7.0

**Comment by mkurz** [comment]
Please upgrade to latest version 2.7.5, it will fix your problem. Since Play 2.7.4 `None` will be recognized:
https://github.com/playframework/playframework/commit/7e34df0978e443231744290d60bc4349b3fb58bf
https://github.com/playframework/playframework/commit/7d343db04c2918d97192a493bfb89f51b5a65196

**Comment by wadouk** [comment]
Ok, will be done later, maybe next time, thanks

`Detected java.lang.NoSuchMethodError error, which MAY be caused by incompatible Akka versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use akka-actor [2.5.31 (resolved from current classpath)] all other core Akka modules MUST be of the same version. External projects like Alpakka, Persistence plugins or Akka HTTP etc. have their own version numbers - please make sure you're using a compatible set of libraries.`
