### ISSUE TITLE
How to mix scala and java code together in a play program

### ISSUE THREAD

**Issue by Tasselmi** [playframework/playframework#10445]
hey guys.
I see that play framework use sbt as build tool. 
there are some scala developers and some java developers in my team. I want to mix them together. so how can I achieve this goal , Is there any doc or example?

**Comment by riccardomerolla** [comment]
I think that you need to enable both the Play plugin in your build.sbt file

`lazy val root = (project in file(".")).enablePlugins(PlayScala, PlayJava, DockerPlugin)`

**Comment by Tasselmi** [comment]
> I think that you need to enable both the Play plugin in your build.sbt file
> 
> `lazy val root = (project in file(".")).enablePlugins(PlayScala, PlayJava, DockerPlugin)`

Thanks for your help.
then how I place my project tree. Is it like this:

```
-- app
    -- controllers
        -- scala
             -- code.scala
         -- java 
             -- code.java
```

**Comment by Tasselmi** [comment]
I got the answer here: [HERE](https://www.playframework.com/documentation/2.8.x/Anatomy)
thx.

**Comment by ignasi35** [comment]
Since this seems solved, I'll close.
