### ISSUE TITLE
Custom launcher in 2.4.x or 2.5.x

### ISSUE THREAD

**Issue by thiagohora** [playframework/playframework#10452]
## Summary

Sorry, I searched in many places but I was not able to find an answer. I'm migrating a **Java Application** from Play 2.3 and to 2.4. I have a custom launcher that does somethings and after starts the application. 

In the launcher I have: 
```
 private static void run(String[] commandArgs) {
       //... do something
        play.core.server.NettyServer.main(commandArgs);
}
```

I saw in the packages that now we have `ProdServerStart.main`. However, this is not accessible. So my question is, what would be the correct way of doing this? If there is any, and also, How can I pass those **commandArgs** to the new starter.

**Comment by wsargent** [comment]
I'm a bit confused as to whether you're upgrading to 2.4 or to 2.5 here.

The docs for starting Netty and the prod server are in Embedding Play and should be version consistent:

https://www.playframework.com/documentation/2.4.x/ScalaEmbeddingPlay

https://www.playframework.com/documentation/2.5.x/ScalaEmbeddingPlay

**Comment by thiagohora** [comment]
Hey @wsargent 

Sorry, to I tried both. But My initial idea was to use 2.4. I saw the list but what a need is a way to start the server after my context has loaded some stuff, and also pass the arguments received in my customer main AppLauncher. 

Like this: 

```
 private static void run(String[] commandArgs) {
       //... do something
        play.core.server.NettyServer.main(commandArgs);
}
```

**Comment by wsargent** [comment]
The place to load stuff in your context is through your context -- literally, through your application context.  If you want custom command line options, you need to modify the script provided by sbt-native-packager using `bashScriptExtraDefines` in your `build.sbt` files i.e. https://www.scala-sbt.org/sbt-native-packager/archetypes/cheatsheet.html?highlight=bash#extra-defines

This really isn't the place for it -- you should ask on the [discuss forum](https://discuss.lightbend.com/c/play/8).  This is a place to report bugs in Play.

**Comment by thiagohora** [comment]
Sure, thank you for your support.
