### ISSUE TITLE
play.ws.ahc.disableUrlEncoding not working.

### ISSUE THREAD

**Issue by saptarshidebnath** [playframework/playframework#10473]
### Play Version

2.82.

### API

Only Java 

### Operating System

Windows

### JDK

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

### Library Dependencies

guice, javaWS
### Expected Behavior

1. With ``play.ws.ahc.disableUrlEncoding`` set to true,  The generated URL should be ``http://example.com/endpoint?param=val1+val2``. 

### Actual Behavior

1. Currently its generating the URL ``http://example.com/endpoint?param=val1%2Bval2`` with being ``play.ws.ahc.disableUrlEncoding`` set to true

```
    @Inject
    private final WSClient ws;
    ..
    ..
    WSRequest request = ws.url("http://example.com/endpoint");
    WSRequest complexRequest =
        request
            .setRequestFilter(new AhcCurlRequestLogger())
            .addQueryParameter("param", "val1+val2");
    CompletionStage<WSResponse> wsResponseCompletionStage = complexRequest.get();
```
Reference : https://www.playframework.com/documentation/2.8.2/JavaWS

**Comment by felipebonezi** [comment]
@ignasi35 how can I help in this problem?
I forked and try to search for `play.ws.ahc.disableUrlEncoding`, but didnt found anything.

**Comment by ignasi35** [comment]
Hi @felipebonezi, I think this problen is on playframework/play-ws (different repo).

(Not at my laptop ATM)

**Comment by felipebonezi** [comment]
> Hi @felipebonezi, I think this problen is on playframework/play-ws (different repo).
> 
> (Not at my laptop ATM)

@ignasi35 the problem is in the class `RequestBuilderBase` from the Shaded AHC package.
How can I fix?

![image](https://user-images.githubusercontent.com/1410319/99186802-94e74f80-2731-11eb-8a11-c54e94be98fb.png)

BTW, I found that Scala API is with the same problem.
Can you check if am I right? 
https://github.com/felipebonezi/play-ws/commit/040d9b9b91f1b74cc00b3b42e2a83b8dd8ea00a1

**Comment by mkurz** [comment]
@felipebonezi Thanks for your work! Please open a pull request in https://github.com/playframework/play-ws and let's discuss over there. thanks!

**Comment by felipebonezi** [comment]
> @felipebonezi Thanks for your work! Please open a pull request in https://github.com/playframework/play-ws and let's discuss over there. thanks!

PR opened!

**Comment by ennru** [comment]
PR in https://github.com/playframework/play-ws/pull/545

**Comment by mkurz** [comment]
New PR: https://github.com/playframework/play-ws/pull/552
