### ISSUE TITLE
Add IPFilter to restrict access to whitelisted IPs

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#10483]
I am writing a service which is allowed to communicate only with 4 fixed ip addresses.
IMHO this is such a basic requirement that it would be nice if Play would offer such a filter out of the box. Should be just a couple of lines. We just need to implement a whitelist which will be checked against `requestHeader.remoteAddress`.
(Don't confuse such an ip filter with the allowed hosts filter, which checks for the Host header).
Also see https://stackoverflow.com/a/25229204/810109

**Comment by felipebonezi** [comment]
@mkurz @ignasi35 I've implemented this filter.
Can you create the `2.9` branch so that I can open my PR?

**Comment by mkurz** [comment]
@felipebonezi master branch is the upcoming 2.9, so just use that. Thanks!
