### ISSUE TITLE
Consecutive dynamic part routes yield to routing issues

### ISSUE THREAD

**Issue by marcadella** [playframework/playframework#10481]
### Play Version

2.8.2

### API

Scala

### Operating System

Linux

### JDK

openjdk version "11.0.8" 2020-07-14

### Actual Behavior

Having defined the following routes:
```
# Home page
GET        /                             no.uit.sfb.dataui.controllers.Application.index
GET        /:ver/:id             no.uit.sfb.dataui.controllers.Application.record(id: String, ver: String)

# Prefix must match `play.assets.urlPrefix`
GET        /assets/*file                 controllers.Assets.at(file)
GET        /versionedAssets/*file        controllers.Assets.versioned(path="/public", file: Asset)
```
, when I make a GET call to `/x/y`, play returns a 404 error while trying to load a versionedAsset.

What makes me think it is a bug is that
- the asset is present
- if I change the route to `GET        /:ver/records/:id` and make a call to `/x/records/y`, everything works fine (the asset is properly found)...

My guess is that when to dynamic parameters are adjacents, somehow play messes up the routes defined after (but it is just a wild guess).

**Comment by mkurz** [comment]
I don't fully understand your problem... Based on the routes config you posted
* Calling `/x/y` will should call route:
```
GET        /:ver/:id             no.uit.sfb.dataui.controllers.Application.record(id: String, ver: String)
```

Can you please explain once more what the problem is?

**Comment by marcadella** [comment]
I probably misread the error message I get when I submitted this issue. The asset is not missing, it has the wrong Mime type:
```
Refused to execute script from 'http://localhost:9000/versionedAssets/client-fastopt-bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```
So when I make a call to `x/y`, the route is working fine, but the asset (which is the bundle js loaded from my `main.scala.html`) somehow has the wrong mime type.
It is strange that the error disappears as soon as I change the path to `/:ver/records/:id`.

It might not be related to Play though. The bundle is loaded by the following line my `main.scala.html`:
```
@scalajs.html.scripts("client", routes.Assets.versioned(_).toString, name => getClass.getResource(s"/public/$name") != null)
```
using [sbt-web-scalajs-bundler](https://github.com/vmunier/sbt-web-scalajs).

**Comment by marcadella** [comment]
I think I got it: It was just a route conflict. I moved the assets routes up in the route file, (in order to prioritize them) and it solved the isse.
