### ISSUE TITLE
Outdated 'Slick' dependency in documentation example

### ISSUE THREAD

**Issue by Luka-Abey** [playframework/playframework#10562]
For Play version 2.8.x Slick 5.0.x is [recommended](https://github.com/playframework/play-slick#current-version). In the [documentation](https://www.playframework.com/documentation/2.8.x/PlaySlick) Slick is in 4.0.0.

**Comment by Luka-Abey** [comment]
Can't for the life of me find the md file in question, the link at the bottom of [Play-Slick](https://www.playframework.com/documentation/2.8.x/PlaySlick) documentation is broken. Made it to here: https://github.com/playframework/playframework/tree/2.8.x/documentation/manual/working/commonGuide but got lost ! Any nudges warmly welcomed. Cheers

**Comment by Max-AR** [comment]
https://github.com/playframework/play-slick/pull/646

**Comment by mkurz** [comment]
I will see if I can deploy the updated docs later today.

**Comment by mkurz** [comment]
Fixed
