### ISSUE TITLE
openid: add support for associations/stateful mode

### ISSUE THREAD

**Issue by dylex** [playframework/playframework#1059]
Currently the play openid implementation has no way to establish associations, and so is stuck in stateless mode, which is less efficient and more vulnerable to mitm attacks.

OpenID 8. Associations:
> An association between the Relying Party and the OpenID Provider establishes a shared secret between them, which is used to verify subsequent protocol messages and reduce round trips.
> It is RECOMMENDED that a Relying Party form associations if it is possible for it to do so.

While ideally play would be able to maintain associations and state, just providing an inteface for establishing them and passing assoc_handle to redirectURL would be sufficient for now.

If I find time and there's interest, I can produce a patch for this.

**Comment by cchantep** [comment]
As there is nothing new there, it can be closed for now (and reopened if needed according uptodate requirements). Best regards.
