### ISSUE TITLE
Failed: Bind failed for TCP channel on endpoint

### ISSUE THREAD

**Issue by octonato** [playframework/playframework#10618]
https://travis-ci.com/github/playframework/playframework/jobs/467787617#L4445

```scala
info] [error] a.i.TcpListener - Bind failed for TCP channel on endpoint [/0.0.0.0:9443]
[info] java.net.BindException: [/0.0.0.0:9443] Address already in use
[info] 	at sun.nio.ch.Net.bind0(Native Method)
[info] 	at sun.nio.ch.Net.bind(Net.java:461)
[info] 	at sun.nio.ch.Net.bind(Net.java:453)
[info] 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
[info] 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
[info] 	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:60)
[info] 	at akka.io.TcpListener.<init>(TcpListener.scala:57)
[info] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 ```

**Comment by AltiorBahA** [comment]
Hi. i'm facing the same error with lagom 1.6  when i run the runAll command

**Comment by octonato** [comment]
@AltiorBahA, that must be something else. 

We mark issues with `failed` label when one of our nightly builds fail. In that specific case, that's probably caused by some race condition in our tests. 

That shouldn't be the case when running `runAll` in Lagom.  Try to collect more information and post in [our user forum](https://discuss.lightbend.com/c/lagom/9). That must be some misconfiguration.

**Comment by mkurz** [comment]
Since this might be related to Travis and we use GitHub actions now, I am closing. We can open new issues if something turns up with GHA.
