### ISSUE TITLE
Play's dependency should require guice, but it is not mentioned in the documentation.

### ISSUE THREAD

**Issue by rysh** [playframework/playframework#10614]
### Play Version
2.6 or higher

### API
documentation/manual/working/commonGuide/build/BuildOverview.md

### Operating System
Darwin ys.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

### JDK
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Expected Behavior

1. When I create a project according to the documentation, I will have the same structure as the official sample project.

### Actual Behavior

1. The official sample projects and templates have the guice dependency added, but the documentation does not mention it.

**Comment by GKuldeepak-Knoldus** [comment]
Hi Everyone,
Is the issue has been fixed, if not can I pick this issue?

**Comment by mkurz** [comment]
@GKuldeepak-Knoldus feel free to open a pull request, I am happy to review it. thanks!
