### ISSUE TITLE
[ Feature ] Return caches/cache names from CaffeineCacheManager 

### ISSUE THREAD

**Issue by gokhanoner** [playframework/playframework#10612]
Current [CaffeineCacheManager](https://github.com/playframework/playframework/blob/master/cache/play-caffeine-cache/src/main/scala/play/api/cache/caffeine/CaffeineCacheManager.scala) implementation only exposes `getCache(name)` method, which is very limited for a cache manager.

adding a method that returns `cacheMap`, or returning cache names only, will make it much more useful since one can access raw Cache implementations & do anything I need to do, in case I need to. One common use case is to do same operation in all caches, like cleaning all caches (especially useful in tests ). Just because of this, we're currently using `EhCache` which exposes a `clearAll` method but cost 10Mb additional dependency ( since Play still uses v2.8 )

**Comment by gokhanoner** [comment]
Any update on this request?

**Comment by mkurz** [comment]
What you could do right now is get the names of the caches from the config:
https://github.com/playframework/playframework/blob/2f67c254d783a2b057d4712210c5d07d4a56571b/cache/play-caffeine-cache/src/main/scala/play/api/cache/caffeine/CaffeineCacheApi.scala#L65-L66
Now you can just iterate over the names and use `cacheManager.getCache(name)` and do what you need to do.

Of course your suggestion is valid is well, we are happy if you want to provide a pull request :wink:

**Comment by gokhanoner** [comment]
@mkurz I created a PR. Can you pls add the necessary PR reviewers and/or review the changes.
also, I'd really appreciate if this can be released as part of 2.8.X as well :D

**Comment by mkurz** [comment]
@gokhanoner I will do my best
