### ISSUE TITLE
Rename tests in PathsTest and CallTest from play/core

### ISSUE THREAD

**Issue by Captain1653** [playframework/playframework#10629]
There are many tests in PathsTest and CallTest with "general" name like that:

`/** Current Path: /playframework Target Path: /one Relative Path: one */`
`  @Test`
`  public void testRelative1() {`
`    final String startPath = "/playframework";`
`    final String targetPath = "/one";`

`    assertEquals(`
`        "Relative path should return sibling path without common root",`
`        "one",`
`        Paths.relative(startPath, targetPath));`
`  }`

These tests can be renamed (maybe I'm wrong). The error message can be the name of the corresponding test. It will look something like that: 
`@Test`
`  public void relativePathShouldReturnSiblingPathWithoutCommonRoot() {`
 `   final String startPath = "/playframework";`
`    final String targetPath = "/one";`
 `   assertEquals("one", Paths.relative(startPath, targetPath));`
  `}`

I didn't delete the `final` modificator, but... Is it really needed?

**Comment by mkurz** [comment]
@Captain1653 You don't have to open an issue **and** a pull request afterwards to fix that issue. Just a pull request is enough.

**Comment by Captain1653** [comment]
Thank you @mkurz  . I'll do it next time.
