### ISSUE TITLE
[2.8.8] Release new play-ws version

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#10675]
Before cutting 2.8.8, https://github.com/playframework/play-ws/pull/552 and its backport https://github.com/playframework/play-ws/pull/553 should be merged and a new play-ws version should be released.
The release should be done from the [2.1.x branch](https://github.com/playframework/play-ws/tree/2.1.x), probably it will be 2.1.3

**Comment by octonato** [comment]
@mkurz both PRs are merged. Can you take care of release play-ws?

**Comment by mkurz** [comment]
@octonato I will try (not sure if for the 2.1.x branch release by tag is enabled)

**Comment by mkurz** [comment]
Done.
