### ISSUE TITLE
Iteratees are not working in Scala Play. How are infinite Streams Handled Now?

### ISSUE THREAD

**Issue by SarpongAbasimi** [playframework/playframework#10687]
I am trying to stream data from twitter but I am getting an infinite stream of data.(View never renders)
I realised that `Iteratees` are no longer being used in Play so I was wondering how streams are handled now.

I have tried using 

```
def chunked = Action {
  val data                               = getDataStream
  val dataContent: Source[ByteString, _] = StreamConverters.fromInputStream(() => data)
  Ok.chunked(dataContent)
}
```

but that still does not terminate.

**Comment by wsargent** [comment]
Please see the streaming, chatroom and websocket examples in https://github.com/playframework/play-samples.
