### ISSUE TITLE
[2.8.8] Release new interplay version(s)

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#10713]
Before releasing Play 2.8.8 please merge
- https://github.com/playframework/interplay/pull/146 and
- https://github.com/playframework/interplay/pull/147
and release interplay 2.1.6 from the 2.1.x branch and also 3.0.1 (or 3.1.0) from the master branch.
Upgrading to Scala [2.12.13](https://github.com/scala/scala/releases/tag/v2.12.13) allows us to use `@nowarn` and `-Wconf` in Play.

**Comment by mkurz** [comment]
akka 2.6.13 also requires the latest Scala versions now, so we definitely should upgrade, see #10717

**Comment by ignasi35** [comment]
Is there any project still using `interplay`?
The long term goal is to get rid of `interplay` so if we start paying the price of moving away from it it'll be worth it.

**Comment by mkurz** [comment]
@ignasi35 Yes, Play is using interplay: https://github.com/playframework/playframework/search?q=interplay

**Comment by ignasi35** [comment]
Raised https://github.com/playframework/interplay/issues/150

**Comment by mkurz** [comment]
Interplay 2.1.6 released.
