### ISSUE TITLE
Failed: Injected component fails (scripted tests)

### ISSUE THREAD

**Issue by octonato** [playframework/playframework#10742]
Script tests failed
https://travis-ci.com/github/playframework/playframework/jobs/487998500#L4010-L4015

This is new test introduced in #10711. It was green when merged and there is nothing obviously wrong with it.

**Comment by octonato** [comment]
Also here: 

https://travis-ci.com/github/playframework/playframework/jobs/488391572#L3280-L3285

Now on another file, but same new scripted tests

**Comment by mkurz** [comment]
Nothing to worry about, I will increase the timeout to fix that.

**Comment by octonato** [comment]
I guessed it was a timeout issue, but I was wondering why we don't see it in other tests. Isn't the timeouts just the same as in other scripted tests?

**Comment by mkurz** [comment]
Which other tests do you mean? I can just talk about the `dev-mode-compile-and-config-error-source` test:
https://github.com/playframework/playframework/blob/2a43f632191e2fbc9b4557f25fe80424f2c9073a/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test#L53-L63
It seems 2 seconds sometimes (but no always) is just too low to give the app time to re-compile.
I think if we increase all the timeouts in these test to like 4 or 5 seconds we should be fine.

**Comment by mkurz** [comment]
I will fix that with one of the upcoming pull requests.

**Comment by octonato** [comment]
There are similar tests that test recompilation, no?

**Comment by mkurz** [comment]
I added scripted tests

- `dev-mode-compile-and-config-error-source`
- `dev-mode-runtime-error-source`

for both of them I will increase _all_ the timeouts in their `test` file.

**Comment by mkurz** [comment]
Timeouts will be increased by #10655

**Comment by patriknw** [comment]
Not sure if it's the same (I don't know how to find the actual test failures in the Play build), but dev-mode-compile-and-config-error-source failed in https://travis-ci.com/github/playframework/playframework/jobs/489354615

**Comment by patriknw** [comment]
and https://travis-ci.com/github/playframework/playframework/jobs/488832070

**Comment by mkurz** [comment]
@patriknw It's the same. I am increasing the timouts in #10655 to fix that problem.
