### ISSUE TITLE
Tidy up deprecated methods in iteratee module

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#1077]
Remove deprecated methods in iteratee module. Will need to move the functionality of `Concurrent.hub` into `Concurrent.broadcast`.

See also discussion: https://github.com/playframework/Play20/pull/996#issuecomment-16288989

**Comment by marcospereira** [comment]
@richdougherty is this stills relevant? `Concurrent.hub` is now private.

**Comment by jroper** [comment]
Even if it's still relevant, it's not likely going to get done.
