### ISSUE TITLE
Bump to Akka 2.6.14 (with Jackson 2.11) 

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#10787]
In https://github.com/playframework/playframework/pull/10781/files#diff-ad2642dc77b3679e4ad2c7d3b2f59a2dcf48c1bf5b93a558a4fa44828315a34cR41-R44 there's a few explicit dependencies that are not necessary (they are just aligning versions to prevent Jackson runtime errors).

Once Akka 2.6.14 is released and bumped in play, those explicit dependencies should be removed.

**Comment by mkurz** [comment]
Done!
