### ISSUE TITLE
[Feature] Add support for OptionalInt, OptionalLong and OptionalDouble in routes

### ISSUE THREAD

**Issue by PromanSEW** [playframework/playframework#10816]
Please add binders for Java `OptionalInt`, `OptionalLong` and `OptionalDouble` in addition to `Optional`

**Comment by PromanSEW** [comment]
I try to implement myself in my project, but Play does not recognize them :(
https://gist.github.com/PromanSEW/84b929a0672fa132ae71078f1848d6ff
How to make them working?

**Comment by mkurz** [comment]
@PromanSEW You need to add your implicit binders to the routes import in `build.sbt`:
```scala
    routesImport += "util.OptionalBinders._",
```
A pull request is welcome of course.
