### ISSUE TITLE
Security vulnerability among indirect dependencies

### ISSUE THREAD

**Issue by mkubala** [playframework/playframework#10862]
One of the indirect play-test 2.8.8 dependencies, `jetty-io` has a major security issue (see https://snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-1090340).

Here's the full dependency path:
`com.typesafe.play:play-test_2.12@2.8.8 > org.seleniumhq.selenium:htmlunit-driver@2.36.0 > net.sourceforge.htmlunit:htmlunit@2.36.0 > org.eclipse.jetty.websocket:websocket-client@9.4.20.v20190813 > org.eclipse.jetty:jetty-io@9.4.20.v20190813`

The issue was fixed in `9.4.39`, `10.0.2`, `11.0.2`

This can be fixed by updating `org.seleniumhq.selenium:htmlunit-driver` to `2.50.0`, which depends on jetty `9.4.41.v20210516`.

**Comment by mkurz** [comment]
Thanks! IMHO this isn't really urgent since only the play-test project is effected, so production apps should not be effected.

**Comment by mkurz** [comment]
Like stated already, this dependency only effects play-test, which (should) never make it into production, so I don't think there is a need to upgrade `htmlunit-driver` in 2.8.x (It was upgraded in the master branch to the latest version already however).
IMHO we can cut 2.8.9 without "fixing" this issue.

**Comment by octonato** [comment]
Remove the milestone. Since this is affecting a test library, we should not be that worry nor have it to a milestone. If someone wants to fix, PRs are welcome.

**Comment by mkurz** [comment]
I am closing this a fixed because the dependency got upgraded in the main branch already.
For 2.8 there is no need since it's a library only used in tests.
