### ISSUE TITLE
Parsing error in CSP reports

### ISSUE THREAD

**Issue by KrzysiekAgi** [playframework/playframework#10876]
When trying to publish a CSP report in Play, parsing from an actual browser generated report to `ScalaCSPReport` fails. 
Play's `ScalaCSPReport` expects most parameters to be `Option[String]` inlcuding `lineNumber` and `columnNumber`. While [w3.org specification](https://www.w3.org/TR/CSP2/#violation-reports) doesn't suggest any type, one would expect these to be numbers. They are also generated as numbers/`Int`s in both Firefox and Chrome which causes the validation to fail. Why these fields are of type `Option[String]` in Play?

### Play Version
sbt version: 1.4.4
Play framework version: 2.8.7

### API
Scala

### Operating System
Windows 10

### JDK
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

### Expected Behavior
1. There is a CSP violation on the server
2. CSP violation is blocked
3. CSP report is automatically sent to a configured endpoint
4. Endpoint action is invoked (in my case log the violation details)

### Actual Behavior
1. There is a CSP violation on the server
2. CSP violation is blocked
3. CSP report is automatically sent to a configured endpoint
4. `ScalaCSPReport` validation fails due to `lineNumber` and `columnNumber` being `Int`s not `String`s

### Reproducible Test Case
Simplest scenario can be found [in the gist](https://gist.github.com/KrzysiekAgi/b066d728acf303ffbf5e1ba09f9e6478)

**Comment by mkurz** [comment]
Thanks for the report @KrzysiekAgi

It seems `lineNumber` and `columnNumber` weren't tested in [`JavaCSPReportSpec`](https://github.com/playframework/playframework/blob/master/web/play-filters-helpers/src/test/scala/play/filters/csp/JavaCSPReportSpec.scala) and [`ScalaCSPReportSpec`](https://github.com/playframework/playframework/blob/master/web/play-filters-helpers/src/test/scala/play/filters/csp/ScalaCSPReportSpec.scala), which were introduced in #8242.

Can you provide a pull request with a fix and updated the tests as well? Thanks

**Comment by KrzysiekAgi** [comment]
Sure, I'll do that.

**Comment by wsargent** [comment]
At the time that CSP reports were generated, there were multiple conflicting implementations (some of which is detailed in the docs).  If this is cleaned up now and they have standardized on numbers it makes sense that the parsing should be changed, although by its nature this PR will break any reporting that relies on the line number being a string.

**Comment by KrzysiekAgi** [comment]
Yes, it may lead to breaking such implementation. I can't however think of any reason (which doesn't mean it cannot exist, of course) why one would expect a `String` there. In most browsers (I haven't tested Opera and Safari) these fields are numbers, so one would have to manually cast the report and not use `cspReportAction`. 

What do you suggest then @wsargent? Reject this PR, accept it, some interim solution like try to read these fields as `Int`s and if it fails then try again as `String`s?

**Comment by wsargent** [comment]
At the time the code was written, there were four different implementations of CSP reports: “Blink”, “Firefox”, “Webkit”, and “Old Webkit”. 

https://www.tollmanz.com/content-security-policy-report-samples/

If things have settled down to the point where there's only one, then I think breaking it and standardizing is fine.

**Comment by KrzysiekAgi** [comment]
I am working on the documentation adjustment, but in the meantime, together with my colleague, we came up with possible solution that can read either string or a number. This would add some boilerplate code perhaps, but wouldn't cause any breaking change. I've put a sample in the [gist](https://gist.github.com/KrzysiekAgi/3e148a30191ebbb8e1299db1d17abee9). 
Which solution do you think would be best? 

BTW. I'm not sure how I should include this URL in case of parsing fail. Do you mean a logger, or some different way?

**Comment by mkurz** [comment]
> Which solution do you think would be best?

If you can open a pull request with the approach that handles both long and string, I think that would be the best solution.
