### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by bursauxa** [playframework/playframework#10886]
### Play Version

2.8.8

### API

Scala

### JDK

Java 11

### Expected Behavior

Running a basic Play project should not issue any warning

### Actual Behavior

The following warning is produced at start:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:<omitted>/com/google/inject/guice/4.2.3/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### Additional information

This warning starts with Java 9, it was not present in Java 8. The root cause is an issue in Guice (https://github.com/google/guice/issues/1133) that is fixed in Guice 5.0.1.

However, despite the dependencies file (https://github.com/playframework/playframework/blob/master/project/Dependencies.scala) listing guice 5.0.1 since February 27th, play-guice 2.8.8 released on April 8th still pulls guice 4.2.3, as evidenced by the dependency graph below:

```
com.typesafe.play:play-guice_2.13:2.8.8
    com.google.inject.extensions:guice-assistedinject:4.2.3
        com.google.inject:guice:4.2.3
    com.google.inject:guice:4.2.3
    com.typesafe.play:play_2.13:2.8.8
```

**Comment by mkurz** [comment]
This got fixed in the master branch already. You have to wait for Play 2.9.

**Comment by bursauxa** [comment]
Thanks @mkurz, I will be waiting then :tada:

**Comment by claytonjacobs** [comment]
Still waiting.  Blocker for updating to Java 11.

**Comment by claytonjacobs** [comment]
> Still waiting. Blocker for updating to Java 11.

Adding this to libraryDependencies (and leaving in guice) in build.sbt got rid of the errors.

`"com.google.inject" % "guice" % "5.1.0"`

**Comment by bursauxa** [comment]
> Thanks @mkurz, I will be waiting then 🎉

The wait is finally over :smile:
