### ISSUE TITLE
Global onRequest action called after action composition annotations

### ISSUE THREAD

**Issue by ferdy-lw** [playframework/playframework#1088]
The action returned by the Global ```onRequest``` method is ```call()```ed after the [@with/@custom] annotations of the controller action. This stops the global onRequest action from adding args into the context that the compositions might depend on - like a user object determined from the authorization header.

The global onRequest action isn't guaranteed to be called before any other [composed] action. Also, the global action wont be able to 'cancel' or change the flow to another controller action without the original controller action composition actions being executed.

**Comment by twistedpair** [comment]
:+1:
Given that Java servlet `Filters` execute in the order of appearance in the `web.xml` and `AspectJ`/`AOP` and similar cutpoint frameworks have an `Order` property, I think we should have that here. If I'd been using Play for more than 2 months, I'd contribute to the PR myself :( . Thanks!

**Comment by mkurz** [comment]
@twistedpair Just in case you want to get started providing a PR, probably [this line](https://github.com/playframework/playframework/blob/ca664a7d108c24e08e86fb815e7104fcf326bf6e/framework/src/play/src/main/scala/play/core/j/JavaAction.scala#L39) could be a starting point.

**Comment by mkurz** [comment]
I just opened #5457 to fix this issue.
