### ISSUE TITLE
Play fails to run on homebrew-supplied JDK 17ea for M1 Apple Silicon due to JEP 403: 'Strongly Encapsulate JDK Internals' illegal access to internal JDK classes

### ISSUE THREAD

**Issue by msm** [playframework/playframework#10883]
### Play Version

2.8.8, although this will be an issue for all previous versions too.

### API

scala, although this will be an issue on the java flavor as well.

### Operating System

This will be a problem across all operating systems.

### JDK

openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Homebrew (build 17+0)
OpenJDK 64-Bit Server VM Homebrew (build 17+0, mixed mode)

### Library Dependencies

This issue specifically occurs because Homebrew is shipping a java 17 early access build for macOS computers that use Apple Silicon CPUs (e.g., any M1 based ARM Mac).

Homebrew is shipping java 17 early access builds for ARM cpus (even though the formula "states" its version as 16 and *is* 16 for non-M1 computers) because the recent macOS 11.4 update results in the currently available java 16 build crashing on startup. See here for the rundown:

https://github.com/Homebrew/homebrew-core/issues/77954

To be clear, normally I wouldn't bother reporting issues against early access JDK builds that aren't due to be released for many months. In this case, I expect that given popularity of Homebrew, as well as a growing number of developers using M1-based Macs, I expect this will become a relatively common problem. Note also that JDK 17 is a LTS release, so this will likely need to be addressed at some point.

### Expected Behavior

1. A play application will start and run under java 17 early access builds.

### Actual Behavior

```
[ERROR] [SECURITY][05/31/2021 07:56:43.674] [application-akka.actor.default-dispatcher-29] [akka.actor.ActorSystemImpl(application)] Uncaught error from thread [application-akka.actor.default-dispatcher-29]: class play.utils.Resources$ (in unnamed module @0x1a71c900) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x1a71c900, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.IllegalAccessError: class play.utils.Resources$ (in unnamed module @0x1a71c900) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x1a71c900
	at play.utils.Resources$.isUrlConnectionADirectory(Resources.scala:36)
```

Note the specific error here is the usage of internal jdk class `sun.net.www.protocol.file.FileURLConnection`

### Reproducible Test Case

(any play application will likely reproduce this)

**Comment by mkurz** [comment]
This error was fixed already: https://github.com/playframework/playframework/pull/10731/files#diff-25b6212057b12034d5f7ef976fda2e58d6e67aaeeeff5a5fcaf24732dc03fe75

I am working on Java 17 support here #10819 already, using the latest available AdoptOpenJDK binary build for Java 17 ea.
It looks very promising so far, Play compiles and builds with Java 17, all tests, it tests and scripted tests pass, only for one use case (self signed certificates) a `--add-exports` flag is needed, however that effects only dev mode.

**Comment by msm** [comment]
@mkurz apologies for not seeing #10819 already. Glad to hear its being worked on!
