### ISSUE TITLE
Add onLoadMessage

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#10887]
See
* https://github.com/sbt/sbt/blob/develop/build.sbt#L178-L192
* https://github.com/akka/alpakka/blob/master/build.sbt#L56-L72
* https://github.com/scalacenter/sbt-scalafix/blob/main/build.sbt#L10
* https://github.com/scalacenter/scalafix/blob/main/build.sbt#L6

**Comment by PromanSEW** [comment]
I remember that it was in old Play versions as 2.3 etc. Seems to be...

**Comment by mkurz** [comment]
Fixed by #11070
