### ISSUE TITLE
Too large evolution script failing not reported

### ISSUE THREAD

**Issue by gaeljw** [playframework/playframework#10892]
### Play Version

2.8.8

### API

Scala

### Operating System

Linux

### JDK

Openjdk 11.0.11 2021-04-20

### Library Dependencies

mariadb-java-client 2.7.3 (but doesn't seem related to mariadb or the driver)

### Expected Behavior

Given an evolution which is too big (more than what is accepted in the `apply_script` column in `play_evolutions` table)
I expect to have:
- an error in the logs about the fact that the script couldn't be applied
- optionally, an error in `play_evolutions` table in `last_problem` column

### Actual Behavior

- No logs at all, even with log level set to `DEBUG`.
- No error traced in `play_evolutions` table

Happens both in DEV mode or PROD mode.

In DEV mode there's a "hint" which is that even with `autoApply=true`, Play keep displaying the message _Database 'default' needs evolution![An SQL script need to be run on your database.]_ but without more details.

### Reproducible Test Case

None yet but I could probably using a Docker container for a MariaDB instance if you feel it's needed.

### Additional info

Connecting in debug to the JVM, I was able to understand the issue thanks to a breakpoint at https://github.com/playframework/playframework/blob/master/persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L406

What I was able to see is:
- the variable message containing the value `(conn=8) Data too long for column 'apply_script' at row 1 [ERROR:1406, 
SQLSTATE:22001]`
- then, as autocommit was enabled, it tries to run `updateLastProblem` to update `last_problem` in `play_evolutions` but there was no row in the table in the 1st place as data too big to be inserted

:bulb: My feeling is that a quick fix would be to:
- always log an error (even if autocommit is enabled)
- optionally, do an `UPSERT` for the `last_problem` (https://github.com/playframework/playframework/blob/master/persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L370)

**Comment by mkurz** [comment]
Which database are you using? It seems like it has to be mysql, because that is the only db which which uses `mediumtext` with a limit of 16mb for the `apply_script` column. [All others use text for clob](https://github.com/playframework/playframework/blob/2464d6bc32795fe93e24ac03428483566ce803f8/persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L543-L607). How large was your script?
Not sure if we can use `UPSERT`, because not sure i fall db's suppor that.

**Comment by gaeljw** [comment]
> Which database are you using?

Indeed, MariaDB 10.x

> How large was your script?

I don't have it anymore but the limit was 64kb and my script was something like 100kb.

The limit was far less than 16mb.

> Not sure if we can use UPSERT, because not sure i fall db's suppor that.

Fair enough. I think the least we can except is a clear error message in the logs. UPSERT is a bonus.

**Comment by mkurz** [comment]
OK, interesting.

> Fair enough. I think the least we can except is a clear error message in the logs. UPSERT is a bonus.

Can you provide a pull request?

**Comment by gaeljw** [comment]
Opened #10892 to always log the error message
