### ISSUE TITLE
No way to rotate play application secret

### ISSUE THREAD

**Issue by vsabella** [playframework/playframework#10911]
There is no official way in Play Framework to rotate or support multiple application secrets. This is a problem as this secret is used for many things (like cookies) and is difficult to change without end-user impact.

**Comment by wsargent** [comment]
The application secret is there for the cookie baker.  You can swap out the cookie baker with your own implementation.  

See https://github.com/playframework/playframework/blob/2.8.x/core/play/src/main/scala/play/api/mvc/Cookie.scala#L827

Also check out https://github.com/playframework/play-samples/tree/2.8.x/play-scala-secure-session-example and https://blog.nvisium.com/play-2-6-security-analysis for some background.

**Comment by davidfurey** [comment]
You might find https://github.com/guardian/play-secret-rotation useful.

**Comment by mkurz** [comment]
Seems like https://github.com/guardian/play-secret-rotation is exactly what @vsabella was asking for. We might want to add it to our modules page: https://www.playframework.com/documentation/2.8.x/ModuleDirectory

**Comment by arpitbhardwaj** [comment]
@mkurz Let me know if add this info under Utilities Section in Module Directory page
