### ISSUE TITLE
Unicode text passed to TolerantText BodyParser truncates the actual text input 

### ISSUE THREAD

**Issue by sathyarr** [playframework/playframework#10915]
### Play Version

2.8.0

### API

Scala

### Operating System

Windows 10

### JDK

java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

### Expected Behavior

The Inputs to my server can be a Unicode Text.
The Default Body Parser does not help me as it always uses US-ASCII.

So, I thought of using TolerantText.
Because, it’ll first try US-ASCII and fallback to UTF-8.

As in here, https://github.com/playframework/playframework/blob/master/core/play/src/main/scala/play/api/mvc/BodyParsers.scala#L491

I expect the Output of Tolerant Text BodyParser to be exactly same as what I give as Input

**Input 1:**
Waldenström’s
Waldenström’s

**Output 1:**
Waldenström’s
Waldenström’s

**Input 2:**
Walöm’sdenström’s

**Output 2:**
Walöm’sdenström’s

### Actual Behavior

It falls back to UTF-8 as expected.

But, once the BodyParser completes, I am not getting the whole Input as Output.

I am getting only from the location where an Unicode character starts.

**Input 1:**
Waldenström’s
Waldenström’s

**Output 2:**
öm’s
Waldenström’s

**Input 2:**
Walöm’sdenström’s

**Output 2:**
öm’sdenström’s

But, if I debug like,
`scala.io.Source.fromBytes(byteBuffer.array(), “UTF-8”).mkString()` at
https://github.com/playframework/playframework/blob/master/core/play/src/main/scala/play/api/mvc/BodyParsers.scala#L491, I can see a proper expected output.

Going inside and coming out of `decoder.decode(byteBuffer).toString` truncates the beginning of text (until first unicode character)

**Comment by sathyarr** [comment]
Seems to be fixed in Version **2.8.8** 

Would like to know if the approach taken to  preserve the  Unicode characters is right?

**Comment by mkurz** [comment]
@sathyarr So can you confirm your problem is fixed in 2.8.8?

> Would like to know if the approach taken to preserve the Unicode characters is right?

What do you mean?

**Comment by sathyarr** [comment]
@mkurz 

yes, the problem is fixed from 2.8.2

With,
> Would like to know if the approach taken to preserve the Unicode characters is right?

I mean, is there any other way to preserve the Unicode characters rather using `TolerantText` instead of `Text` ?

**Comment by mkurz** [comment]
> yes, the problem is fixed from 2.8.2

So let's close this issue then.

> I mean, is there any other way to preserve the Unicode characters rather using `TolerantText` instead of `Text` ?

Looking at [`BodyParsers.scala`](https://github.com/playframework/playframework/blob/2.8.x/core/play/src/main/scala/play/api/mvc/BodyParsers.scala), I don't think there is, but maybe I am wrong...
