### ISSUE TITLE
In tests, allow changing address to bind to

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#10927]
An instance of `play.test.TestServer` (and therefore also the `WithServer` helper) always binds to `0.0.0.0`. There is no way to change that. I don't like this approach, since even when running tests I don't want to expose my app to the whole world.

We can already change the port a test server is running on by using the system property `testserver.port`:
https://github.com/playframework/playframework/blob/9a1138bce538aa68fdf19ced7ce3b55064aeb62d/testkit/play-test/src/main/scala/play/api/test/Helpers.scala#L138-L142

IMHO we should allow to do the same with the address. I think it would even make sense to allow to set the address by reading a env variable like we already do with `PLAY_HTTP_ADDRESS` (with fallback to the sys property), which let's you set the address in dev and prod mode (however I probably would use `PLAY_TEST_HTTP_ADDRESS` for this case)

**Comment by mkurz** [comment]
@morellik I had a look and I think what needs to be done is:
Below this line we should have a variable that stores the test server address:
https://github.com/playframework/playframework/blob/6e3403ec43ff3f633668ef147172e8c541bacd5e/testkit/play-test/src/main/scala/play/api/test/Helpers.scala#L142
```scala
lazy val testServerAddress: String = sys.props.get("testserver.address").orElse(sys.env.get("PLAY_TEST_SERVER_HTTP_ADDRESS")).getOrElse("0.0.0.0")
```
Now we need to use this variable when creating a test server.
For Play Java that is here:
https://github.com/playframework/playframework/blob/6e3403ec43ff3f633668ef147172e8c541bacd5e/testkit/play-test/src/main/java/play/test/TestServer.java#L55
So we can just replace that line with:
```scala
  play.api.test.Helpers.testServerAddress(),
```
For the Scala API we also need to set it:
https://github.com/playframework/playframework/blob/6e3403ec43ff3f633668ef147172e8c541bacd5e/testkit/play-test/src/main/scala/play/api/test/TestServer.scala#L104
Here `0.0.0.0` was not set explicitly, but it is the default value for the address param of `ServerConfig`. So we need to change that as well by simply:
```scala
ServerConfig(address = Helpers.testServerAddress, port = ...
```

I also found out there is the TestServerFactory which needs that address setting as well:
https://github.com/playframework/playframework/blob/6e3403ec43ff3f633668ef147172e8c541bacd5e/testkit/play-test/src/main/scala/play/api/test/TestServerFactory.scala#L64
Again we need to override the default `0.0.0.0` address here too:
```scala
val sc = ServerConfig(address = Helpers.testServerAddress, port = ...
```

What do you think? Do you want to provide a pull request?

**Comment by morellik** [comment]
Ok, I'll try to do it

**Comment by morellik** [comment]
I pulled the request. I hope that all works fine
