### ISSUE TITLE
scripted play-sbt-plugin/dev-mode: configuration error

### ISSUE THREAD

**Issue by raboof** [playframework/playframework#10930]
https://app.travis-ci.com/github/playframework/playframework/jobs/525069379

So the token is `'?' (Reserved character '?' is not allowed outside quotes)`? Weird.

```
[error] Configuration error: Configuration error[application.conf @ file:/tmp/sbt_ff9cc2b0/target/classes/application.conf: 1: Expecting a value but got wrong token: '?' (Reserved character '?' is not allowed outside quotes) (if you intended '?' (Reserved character '?' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)]
```

**Comment by raboof** [comment]
Again at https://app.travis-ci.com/github/playframework/playframework/jobs/527317158

**Comment by raboof** [comment]
Looking closer, it seems the *real* problem is `[info] java.lang.OutOfMemoryError: Metaspace`...

**Comment by ihostage** [comment]
@raboof Looks like can be closed after https://github.com/playframework/playframework/pull/10877 merged.
