### ISSUE TITLE
Caffeine-based cache (SyncCacheApi) does not have a size limit ➔ prone to "out of memory" JVM crash

### ISSUE THREAD

**Issue by dEajL3kA** [playframework/playframework#10955]
### Play Version

2.8.8

### API

Java / SyncCacheApi

### Operating System

Ubuntu 20.04 LTS
```
Linux 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### JDK

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

### Expected Behavior

I think that the **Caffeine**-based cache implementation of Play Framework should have a size limit (by default), just like the **Ehcache**-based cache implementation *does* have.

Even though [the documentation](https://www.playframework.com/documentation/2.8.x/JavaCache) leaves this ***unclear***, I figured out, *by testing*, that the **Ehcache**-based cache implementation has a (default) size limit of `10,000` items. As far as I can tell, the **Caffeine**-based cache implementation, has **no** size limit at all!

Limiting the cache size (by default) seems reasonable, since an unbounded cache can easily cause "out of memory" problems.

### Actual Behavior

The **Caffeine**-based cache does **not** seem to have size limit. Not only is this inconsistent with **Ehcache**, also if the application keeps on adding *many* items to the cache over time, then, with the **Caffeine**-based cache, the JVM will sooner or later ***crash*** because of  "out of memory" error! I have actually reproduced this crash in my Play Framrwork-based application 😨 

(Note: I'm talking about cached items ***without*** an explicit expiration time. But these *are* perfectly allowed, so still a valid point)

### Reproducible Test Case

Create a loop that keeps on adding items for *random* (non-repeating) keys to the cache. You will see that, with **Ehcache**, this can keep on running "forever"; old items will simply be evicted. Not so with **Caffeine**! It will crash the JVM, eventually.

**Comment by logesh-sahaj** [comment]
Hi @mkurz/ @jroper Can I pick this up. I feel this can be fixed by having common default maximum size for the Caffeine cache.

**Comment by dEajL3kA** [comment]
> Hi @mkurz @jroper Can I pick this up. I feel this can be fixed by having common default maximum size for the Caffeine cache.

👍

**Comment by morellik** [comment]
Fix pulled

**Comment by dEajL3kA** [comment]
👍

**Comment by ihostage** [comment]
I think that this issue should be open while RP is open
