### ISSUE TITLE
Release notes refer to @mergify a lot

### ISSUE THREAD

**Issue by melezov** [playframework/playframework#10965]
Short note that the @mergify bot is referenced 33 times instead of the actual authors in the last release notes:
https://github.com/playframework/playframework/releases/tag/2.8.8

Perhaps a better contributor extractor is required.

**Comment by mkurz** [comment]
We should be able to work around that, see https://github.com/playframework/play-meta/issues/216

**Comment by PromanSEW** [comment]
Fixed by #11167

**Comment by mkurz** [comment]
I keep this open since this needs to be done for every project that uses mergify (basically every project in the Play org).

**Comment by mkurz** [comment]
Closing, mergify config was synced to all other repos thanks to @ihostage: 
* https://github.com/playframework/.github/pull/34
* https://github.com/playframework/.github/actions/runs/3052335818/workflow

and we have https://github.com/playframework/play-meta/issues/216 anyway instead
