### ISSUE TITLE
Environment variables from envVars sbt key are not passed to the application

### ISSUE THREAD

**Issue by Dani3lB** [playframework/playframework#10972]
The envVars sbt key does not work with play framework, the given environment variables are not passed to the application.

### Play Version
2.8.8
### API
Scala
### JDK
openjdk 11.0.12 2021-07-20 LTS
OpenJDK Runtime Environment Zulu11.50+19-CA (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.50+19-CA (build 11.0.12+7-LTS, mixed mode)

### Reproducible Test Case
1. add key to application.conf that reads from an env var
2. add env var to envVars key in build.sbt
3. start application

**Comment by mkurz** [comment]
[Values of `envVars` are only passed when forking the JVM](https://github.com/sbt/sbt/blob/50c3cf10825bae3e89af11b3a2c9741e6d98add5/main/src/main/scala/sbt/Keys.scala#L296):
```scala
val envVars = taskKey[Map[String, String]]("Environment variables used when forking a new JVM").withRank(BTask)
```
By default, when using `sbt run` the JVM doesn't get forked. Therefore everything is ok.
Actually setting `fork := true` for `sbt run` does not even work, see #11120.

However you can set
```
Test / fork := true

envVars += ("testvar" -> "foo")
```
and use that env var in a test. I tested this with following `application.conf`:
```
foo-var = ${?mytestvar}
```

and a test like

```java
    @Test
    public void testIndex() {
        assertEquals("foo", app.config().getString("foo-var"));
    }
```

and it passed when running `sbt test`.

So there is no bug.

**Comment by mkurz** [comment]
BTW: I was using this reproducer: https://github.com/mkurz/playframework-reproducers/tree/main/playframework-10972
