### ISSUE TITLE
Should drop Travis CI

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#10983]
See https://github.com/sbt/sbt-web/issues/183 and https://twitter.com/peter_szilagyi/status/1437646118700175360

Also https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by PromanSEW** [comment]
@mkurz it can be closed?

**Comment by mkurz** [comment]
Yes, thanks for the reminder!
