### ISSUE TITLE
Zentasks documentation error

### ISSUE THREAD

**Issue by ironmaiden189** [playframework/playframework#1099]
Hi,
I was following the Zentasks tutorial (http://www.playframework.com/documentation/2.1.0/JavaGuide3) and I found out there are path errors regarding the view elements.

First the file index.scala.html is in the package app/views, then it's located in the package app/views/html, and some other files present the same strange behaviours.

I would like to report that the download link for the download of a sample dataset and for the LESS scripts are corrupted. YAML broken download link is this: http://www.playframework.com/documentation/2.1.0/javaGuide/tutorials/zentasks/files/test-data.yml, and it's located in this page: http://www.playframework.com/documentation/2.1.0/JavaGuide2
LESS scripts broken download link is this: http://www.playframework.com/documentation/2.1.0/javaGuide/tutorials/zentasks/files/less-stylesheets.tar.gz, and it's located in this page: http://www.playframework.com/documentation/2.1.0/JavaGuide3

Please rectify the docs for other newbies like me.
Thank you and keep up with the good work.

**Comment by nikhilbedi** [comment]
Hi, the links still seem to be broken.
