### ISSUE TITLE
scala-java8-compat causing havoc when trying to upgrade akka

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#11004]
### Play Version

2.8.8

### API

Scala

### Operating System

MacOS

### JDK

openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

### Expected Behavior

We can upgrade akka to `2.6.17`

### Actual Behavior

For all project modules that depend on the `PlayScala` plugin we can't seem to get rid of the following issue

```
[error] 	* org.scala-lang.modules:scala-java8-compat_2.13:1.0.0 (early-semver) is selected over {0.9.1, 0.9.1}
[error] 	    +- com.typesafe.akka:akka-actor_2.13:2.6.17           (depends on 1.0.0)
[error] 	    +- com.typesafe.play:play_2.13:2.8.8                  (depends on 0.9.1)
[error] 	    +- com.typesafe.play:play-streams_2.13:2.8.8          (depends on 0.9.1)
```

How do we exclude `scala-java8-compat` from the dependencies added by the plugin?

A solution would be releasing a new play version with only this library updated.

I found these related tickets
https://github.com/akka/akka/pull/30375
https://github.com/playframework/playframework/issues/10971
https://github.com/playframework/playframework/pull/10900

**Comment by mkurz** [comment]
I am working on this in #10969

**Comment by francisdb** [comment]
This has been fixed
