### ISSUE TITLE
How to run Playframework tests using play scala test in gradle? 

### ISSUE THREAD

**Issue by vigneshbrb** [playframework/playframework#11002]
### Are you looking for help?

I have been trying to run play scala test in gradle. Whenever I try to run the test cases, it always reports in IntelliJ that "No test events were received"  With SBT, it works perfectly fine. 

![image](https://user-images.githubusercontent.com/20576119/138402908-4049650e-aa65-41b9-bc07-aa5184db0910.png)

Also there are no proper documentations or samples for Playframework with Scala and gradle. 

### Play Version

2.8.0

### API

Scala

### Operating System

Windows 10 64 Bit

### JDK

JDK 1.8

### Library Dependencies

build.gradle

```java
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.9.1/userguide/building_java_projects.html
 */
plugins {
    id 'org.gradle.playframework' version '0.12'
}

play {
    platform {
        playVersion = '2.8.0'
        scalaVersion = '2.12.10'
        javaVersion = JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'org.scala-lang:scala-library:2.12.10'
    implementation 'com.typesafe.play:play-guice_2.12:2.8.0'
    testImplementation group: 'org.scalatestplus.play', name: 'scalatestplus-play_2.12', version: '5.1.0'
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        name "lightbend-maven-releases"
        url "https://repo.lightbend.com/lightbend/maven-release"
    }
    ivy {
        name "lightbend-ivy-release"
        url "https://repo.lightbend.com/lightbend/ivy-releases"
        layout "ivy"
    }
    maven { url "https://plugins.gradle.org/m2/" }
}

```

### Expected Behavior

1. Running `gradle test` should run all the tests inside `test` directory
2. compileScalaTest should compile and generate scala class files

### Actual Behavior
  - gradle test does not receive any events as the plugin does support only Junit and TestNG, here in playframework with scala, I am using scala play test
  - compileScalaTest is not generating scala class files

**Comment by mkurz** [comment]
I think a better place to ask this question is in the repo of the Gradle Play Plugin: https://github.com/gradle/playframework/
