### ISSUE TITLE
Bump FasterXML version

### ISSUE THREAD

**Issue by KarolPK** [playframework/playframework#11017]
FasterXML in version used here (2.11.4) has DoS bug described here https://github.com/FasterXML/jackson-dataformats-binary/commit/e35d4a04682ee779050ae9656d8d4ae2738efec3

Some dependency scanners see this as vulerability to block using Play.

It for sure touches Scala 2.8.x version

**Comment by mkurz** [comment]
"Recommended Security Severity: Low". according to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32173.
Also I don't think we will upgrade Jackson in the 2.8.x branch anymore. Users still can override the dependency if desired.

Let's keep this open for Play 2.9 however, we should be able to upgrade to Jackson 2.13.x, even though akka still depends on 2.11, see this comment: https://github.com/akka/akka/issues/31097#issuecomment-1024872663

**Comment by mkurz** [comment]
Please see https://github.com/playframework/playframework/discussions/11222 how to upgrade Jackson in your Play 2.8 application.
Also this is the pull request to upgrade to latest Jackson 2.13 for the next Play major release: #11219
