### ISSUE TITLE
gRPC reflection in Play

### ISSUE THREAD

**Issue by haghard** [playframework/playframework#11025]
### Problem statement
Although gRPC reflection feature https://doc.akka.io/docs/akka-grpc/current/server/reflection.html works for project where akka-http is used it doesn't work for Playframework apps. 

### Reproducible Test Case
I took play-scala-grpc-example from official Play Framework samples and tried to make it work which led me to nothing. See: https://github.com/haghard/play-scala-grpc-example.git

**Comment by haghard** [comment]
Now I know how to enable  gRPC reflection

**Comment by bmo-at** [comment]
Do you mind sharing?

**Comment by enzeart** [comment]
There is a lack of documentation that demonstrates how to enable Server Reflection with Play gRPC. I was able to figure out a working solution through random searches on the internet. Here are the relevant links:

1. [gRPC reflection in Play #11025](https://github.com/playframework/playframework/issues/11025)
2. [haghard/play-scala-grpc-example](https://github.com/haghard/play-scala-grpc-example)
3. [GreeterServiceReflectionRouter.scala](https://github.com/haghard/play-scala-grpc-example/blob/master/app/routers/GreeterServiceReflectionRouter.scala)
4. [routes](https://github.com/haghard/play-scala-grpc-example/blob/master/conf/routes)
5. [Server reflection is experimental #850](https://github.com/akka/akka-grpc/issues/850)

Enable Server Reflection with the following steps:

1. Create a class that extends play.grpc.internal.PlayRouter("grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo")
2. Override the "respond" field of this class and set the value similar to the example from link 3 listed above.
3. Configure a route for this router similar to the example from link 4 listed above.

**Comment by mkurz** [comment]
@enzeart A PR for docs improvement would be welcome, thanks!
