### ISSUE TITLE
Unable to upgrade to Play Framework 2.8.9

### ISSUE THREAD

**Issue by tsuyoshizawa** [playframework/playframework#11027]
Play Framework 2.8.9 was released and I tried to upgrade, but I got the following compilation error and could not upgrade.

```
[info] Fetched artifacts of
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error]         * org.scala-lang.modules:scala-java8-compat_2.13:1.0.0 (early-semver) is selected over 0.9.1
[error]             +- com.typesafe.play:play_2.13:2.8.9                  (depends on 1.0.0)
[error]             +- com.typesafe.play:play-streams_2.13:2.8.9          (depends on 1.0.0)
[error]             +- com.typesafe.akka:akka-actor_2.13:2.6.17           (depends on 1.0.0)
[error]             +- com.typesafe.play:play-ahc-ws-standalone_2.13:2.1.3 (depends on 0.9.1)
```

I couldn't find the play-ws v2.1.3 tag, so I didn't know exactly which scala-java8-compat version it was specifying.
https://github.com/playframework/play-ws/tree/v2.1.3

### Play Version

2.8.9

### Scala version

2.13.6

### API

Scala and Java

### Operating System

macOS 12.0.1

### JDK

openjdk version "11.0.13" 2021-10-19 LTS

### Library Dependencies

`com.typesafe.play:play-ahc-ws-standalone`

### Expected Behavior

1. Update to `addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.9")` on plugins.sbt
2. Run`sbt compile`
3. Compilation completes normally

### Actual Behavior

1. Update to `addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.9")` on plugins.sbt
2. Run`sbt compile`
3. Abnormal termination during compilation

### Reproducible Test Case

None

**Comment by ennru** [comment]
Thanks for reporting. We're looking into it and will most likely release another patch version.

**Comment by coding4cc** [comment]
play-twirl[https://github.com/playframework/twirl] dependency on [org.scala-lang.modules:scala-xml_2.13:1.2.0] also cause this problem

**Comment by octonato** [comment]
@coding4cc, could you create an issue in https://github.com/playframework/twirl repo with more details? 

Twirl doesn't use `scala-java8-compat`. There are some logic indeed regarding which version of Scala xml is selected, but I guess the issue you are having is different.

**Comment by coding4cc** [comment]
> @coding4cc, could you create an issue in https://github.com/playframework/twirl repo with more details?
> 
> Twirl doesn't use `scala-java8-compat`. There are some logic indeed regarding which version of Scala xml is selected, but I guess the issue you are having is different.

my fault:   In my project , when i upgrade scala-xml  version to 2.0.1 cause this problem:
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.13:2.0.1 (early-semver) is selected over 1.2.0

**Comment by ennru** [comment]
Fixed with https://github.com/playframework/playframework/pull/11028 and https://github.com/playframework/play-meta/issues/198

**Comment by tsuyoshizawa** [comment]
Thank you for the release.
I have confirmed that the compilation completes with Play Framework 2.8.10.
