### ISSUE TITLE
Drop support for Java 8

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#11078]
~I suggest Play 2.9 should be the last release that gets build with Java 8.~
Play 2.9 will drop support for Java 8.

Newer releases of some libraries that Play depends on are already not compatible with Java 8 anymore (but only with Java 11) and more might follow: https://github.com/playframework/playframework/labels/topic%3Ajdk-next
That means we can't upgrade to these new releases which is a bit unfortunate in case the library authors stop to backport bug fixes and features (which I think already happens to HikariCP AFAIK).

We should add an announcement for this ~in the Play 2.9 release notes~, so people get aware of it.

BTW: I know that Java 8 still is going strong, however it also seems that Java 11 is catching up as well.
So, if we release 2.9 at some point in 2022, Java 8 will be 8 years old already.
Release dates of Java LTS versions:
Java 8: March 18, 2014
Java 11: September 25, 2018
Java 17: September 14, 2021

I am also open to discuss to drop Java 8 for Play 2.9 already.

**Comment by mkurz** [comment]
Reminder to not forget to unpin dependencies [marked as incompatible with Java 8 in `.scala-steward.conf`](https://github.com/playframework/playframework/blob/ce33e56107f69aaeab5a1e289712162071b4865c/.scala-steward.conf#L30). (Also check the `updates.ignore` section as well)

**Comment by mkurz** [comment]
Because I just stumbled over it: Also upcoming Hibernate 6 will drop support for Java 8: https://hibernate.org/orm/releases/6.0/

**Comment by gokhanoner** [comment]
@mkurz anything specific that prevents removing Java 8 support in 2.9? As long as its announced a couple of months before, its a better option I believe. March 2022 is the end of Premier Support for Java 8 by Oracle, so it makes sense to deprecate Java 8 in the next major 2.x release, which is 2.9

**Comment by gmethvin** [comment]
I agree this seems like the right time to drop support.

**Comment by nafg** [comment]
I plan to drop it in Slick after 3.4.0, after two Scala Steward library upgrades no longer support Java 8, including hikaricp

**Comment by mkurz** [comment]
Well, I guess it makes sense to drop support Java 8 for Play 2.9 already :+1:

**Comment by mkurz** [comment]
One more reason to drop Java 8: Just released Ebean 13 only works with Java 11+ as well: https://github.com/playframework/play-ebean/pull/252
