### ISSUE TITLE
Akka 2.6.18

### ISSUE THREAD

**Issue by ahjohannessen** [playframework/playframework#11073]
@mkurz Any chance to get a Play release with Akka 2.6.18 - Reason for asking is that Akka 2.6.18 brings about Scala 3 support. I know that Play is not quite there yet, but it would be great for upstream libs that could start using Scala 3 without getting into issues with 2.6.17 vs. 2.6.18 that Akka checks for.

**Comment by mkurz** [comment]
There is already a PR with various version upgrades: #1096 - where akka already gets bumpted to 2.6.17 - I will update to 2.6.18 when I continue to work on it.

**Comment by ahjohannessen** [comment]
@mkurz I think your reference is wrong, it points to an issue from 2013 :)

ok, that sounds great :)

**Comment by ahjohannessen** [comment]
I assume you mean this #10969

**Comment by ahjohannessen** [comment]
@mkurz I see that 2.8.x already has akka 2.6.17, see https://github.com/playframework/playframework/commit/0a60b0f27f7f5f69c0f4a0981c666a155c8217ca

The PR that you point to seems to be a bit more than just akka minor bump.

**Comment by mkurz** [comment]
Next Play 2.8.12 will use akka 2.6.18, see #11076, also bumped for master branch in #10969

**Comment by ahjohannessen** [comment]
👍
