### ISSUE TITLE
how to exclude io.jsonwebtoken:jjwt:0.9.1 from Play's sbt build

### ISSUE THREAD

**Issue by coderman2022** [playframework/playframework#11085]
### Play Version
2.8.11

### Operating System
macOS Monterey 12.1

### JDK
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Expected Behavior
Play has dependencies on io.jsonwebtoken:jjwt:0.9.1. Normally this causes no problems. However, unfortunately I am using a library that uses a different implementation of JWT, namely com.auth0:java-jwt:3.4.0. When this library makes a JWT call, it causes a fatal error in Play (java.lang.NoSuchMethodError) and exits the server process.

I need a way to exclude io.jsonwebtoken:jjwt:0.9.1 from the Play target jar created by sbt. I tried adding

`excludeDependencies += "io.jsonwebtoken" % "jjwt"` in build.sbt, but this does not remove io.jsonwebtoken:jjwt:0.9.1 from teh build.

What is the recommended way to accomplish this?

**Comment by coderman2022** [comment]
I tried adding this:

`excludeDependencies += "io.jsonwebtoken" % "jjwt",`

after `libraryDependencies ++= Seq(...)`

but when I do `sbt dependencyTree`, the jwt still shows up unfortunately.

**Comment by mkurz** [comment]
I tried with Play 2.8.11, sbt 1.5.8 and Scala 2.13.7 and `excludeDependencies += "io.jsonwebtoken" % "jjwt"` did work for me.
Did you run `reload` or did you restart sbt after changing `build.sbt`.
If that still does not work, can you please post your `libraryDependencies` config? Also which sbt-plugins have you enabled?

**Comment by coderman2022** [comment]
Thanks for your help! My mistake was that I was not putting `excludeDependencies` at the top level of build.sbt, and was only putting it after my own explicitly-listed dependencies. That meant the "exclude" was not affecting Play's transitive dependencies (for example `com.typesafe.play:filters-helpers_2.12:2.8.11` brings in `io.jsonwebtoken`), which do not appear explicitly in the `build.sbt`, but are I think brought in implicitly via the `.enablePlugins(PlayJava)`.
