### ISSUE TITLE
Update the external links

### ISSUE THREAD

**Issue by GKuldeepak-Knoldus** [playframework/playframework#11089]
I have been observing that there are few external links that contain `http` and can be upgraded to `https`.

**Comment by ndeverge** [comment]
@GKuldeepak-Knoldus thanks. Could you please create a pull request, or tell us which urls need to be upgraded?

**Comment by GKuldeepak-Knoldus** [comment]
Hi @ndeverge , 
Thanks for responding me back. I have raised a PR for the same which includes some fixes.

**Comment by GKuldeepak-Knoldus** [comment]
Hi @ndeverge ,
I believe that there might be some other links that also need to be updated as well. So, it would be better if we again open this issue for further updates.
Thanks

**Comment by ndeverge** [comment]
IMO, the best way is to create a new pull request if new links have to be updated.
And thanks for your contribution!
