### ISSUE TITLE
Correctly set snapshot version

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#11143]
We use [sbt-dynver](https://github.com/dwijnand/sbt-dynver) to set the version for the Play project based on git tags.
E.g. when you run sbt in the Play project folder you will see:

```
// If you haven't you need to get the Play framework source code
git clone git@github.com:playframework/playframework.git
cd ./playframework

// You are in the master branch now, from which we want to release Play 2.9 one day
$ sbt
sbt:Play-Framework> version
...
[info] 	2.8.1+1473-78bcdb4e-SNAPSHOT
```

You can see even we are on the master branch and even though we are working on Play 2.9 it shows `2.8.1+....`
So the version is based of the 2.8.1 tag, because this is the last tag that sbt-dynver can see on the master branch.
(After 2.8.1 tag the 2.8.x branch got created, so the next tags 2.8.2, 2.8.3 live on the 2.8.x branch, but not on the master branch anymore).
1473 means there were 1473 commits since the 2.8.1 tag (the distance)
`78bcdb4e` is a commit SHA
You can find all that information in the [README of the sbt-dynver](https://github.com/dwijnand/sbt-dynver) repo. Also if you have a dirty working directory (meaning you have changes which are not committed yet, the date will also be added to the version string, e.g. `2.8.1+1473-78bcdb4e+20220203-1216-SNAPSHOT`)

For the master branch, what we would like to have is that the version now looks like `2.9.0-78bcdb4e-SNAPSHOT`, so 2.8.1 changes to 2.9.0 and **the distance should be removed**.

For the `2.8.x` branch, we would do the same, however it's a bit different:
Let's change to the 2.8.x branch:
```
git checkout 2.8.x
$ sbt
sbt:Play-Framework> version
...
[info] 	2.8.13+19-54101e55-SNAPSHOT
...
```
Here again the version is based on the latest tag 2.8.13 that sbt-dynver can see on the 2.8.x branch.
Again, we want the version to be `2.8.14+54101e55-SNAPSHOT`, so 2.8.13 changes to the next version 2.8.14 and the **the distance should be removed**.

All this can be done by configuring sbt-dynver to use a custom version string: https://github.com/dwijnand/sbt-dynver#custom-version-string
Wo what needs to be done is in `build.sbt` set
```
ThisBuild / version ~= ...
ThisBuild / dynver  ~= ...
```
I already worked on this long time ago, but we closed it, however you can use it as an example: https://github.com/playframework/playframework/pull/10843/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R24-R26

If you change `build.sbt` don't forget to reload sbt each time you make a change and want to check if it worked:

```
// Reload after editing build.sbt
sbt:Play-Framework> reload
// Check the version again
sbt:Play-Framework> version
....
```

**Comment by gaeljw** [comment]
@mkurz How would you detect if the `x.y.z` version should be last tag with bugfix incremented by 1 or minor incremented by 1?

For example, if last tag is `2.8.13`, on which criteria should the version be `2.8.14` versus `2.9.0`?
I initially though of using the branch name (`main` meaning increment minor version, anything else meaning increment bugfix version) but this doesn't make much sense as people will create branches from `2.8.x` or `main` with names we cannot assume.

(Or maybe I didn't understand correctly the goal :) )

**Comment by mkurz** [comment]
@gaeljw Since the code will either live in the `main` branch or the `2.8.x` branch, it doesn't really have to check for the branch name. The code in the `main` branch will just increment to `2.9.0` because its the code in the main branch. Same for the 2.8.x branch. No detection needed. Do you know what I mean?

**Comment by gaeljw** [comment]
Oh you mean it's "static" and when `main` will be for version 2.10.x we'll manually update the _build.sbt_?

And for branch `2.8.x`, should the `2.8.14` be "static" as well and updated as part of the release process?

**Comment by ihostage** [comment]
> Oh you mean it's "static" and when main will be for version 2.10.x we'll manually update the build.sbt?

No, it will be not static. It will be dynamic, but code in the `main` branch will increase a **MINOR** version, and code in other branches will increase a **PATCH** version. 😉

> And for branch 2.8.x, should the 2.8.14 be "static" as well and updated as part of the release process?

No, code won't change in the release process, because it will work correctly after release just finds a new release tag. 😉

**Comment by ihostage** [comment]
`x.y.z` - found latest release tag.

`main` branch:
 **now** - `x.y.z` ➡️ `x.y.z+distance-...-SNAPSHOT`
 **to be** - `x.y.z` ➡️ `x.${y+1}.z-SNAPSHOT`
 
`2.8.x` branch:
 **now** - `x.y.z` ➡️ `x.y.z+distance-...-SNAPSHOT`
 **to be** - `x.y.z` ➡️ `x.y.${z+1}-SNAPSHOT`

**Comment by mkurz** [comment]
Thanks @ihostage, nice explanation. So basically the dynamic part is to increase the minor version in the main branch and to increase the patch version in the 2.8.x branch. However IMHO it is not necessary to detect, based on the branch, if the minor or the patch version should be increased. That can be hardcoded and as soon as we fork the 2.9.x branch from the main branch, we will just change the logic on the 2.9.x branch.

**Comment by mkurz** [comment]
@gaeljw You want to work on this? Was our explanation good enough or is there something unclear?

**Comment by gaeljw** [comment]
> That can be hardcoded and as soon as we fork the 2.9.x branch from the main branch, we will just change the logic on the 2.9.x branch.

@mkurz Okay, then I can give it a try when I have a bit of time.

**Comment by gaeljw** [comment]
Pushed a quick draft that works for the `main` branch:
```
[info] version
[info] 	2.9.0-ae909637-SNAPSHOT
```

Tested by making a local tag `2.9.x` and running again:
- if no change since tag => `2.9.x`
- any change => `2.10.0-sha-SNAPSHOT`

I have to admit I'm not hyper confident with this, any feedback welcome.
