### ISSUE TITLE
AkkaHttpServer should use PhaseServiceRequestsDone to drain requests

### ISSUE THREAD

**Issue by jrudolph** [playframework/playframework#11164]
`AkkaHttpServer` runs `binding.terminate` inside the `PhaseServiceUnbind` phase:

https://github.com/playframework/playframework/blob/6514ebdad9143cbef4a114997c35eb36720f31f6/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L469-L485

Akka actually provides two phases for unbinding and then for draining existing requests.

Here's how akka-http uses the phases when CoordinatedShutdown is enabled:

https://github.com/akka/akka-http/blob/2353ca43af2960f943ce74421863b0d95a08473c/akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala#L1010-L1019

Play could be changed to do the same.

**Comment by mkurz** [comment]
Thanks!
Maybe we can do that as part of the work to switch to akka 10.2.x in #10411

**Comment by mkurz** [comment]
PR: #11758
