### ISSUE TITLE
Security issue: Play allows unauthenticated uploads 

### ISSUE THREAD

**Issue by GithubUser8080** [playframework/playframework#11170]
Hi, we have encountered a critical security issue using Play 2.8. It looks like bodyparsers are run before any authentication actions. This means that controllers which required a token to be accessed can be used to upload malicious files temporarily without any present authentication, due to the default multipart bodyparser.

We would appreciate any workaround to this, or a potential future fix. Thank you

EDIT: We have also tried the play.mvc.Security package actions and the same behavior persists.

**Comment by BillyAutrey** [comment]
Hi @GithubUser8080 - do you have a minimal reproducer that we can examine?

**Comment by BillyAutrey** [comment]
Ah, interesting.  So this doesn't even need to technically accept `Action(parse.multipartFormData)`?  Just by using a custom action builder, you're saying that it processes (and accepts upload of) a file on a `POST     /     com.example.MyClass.controller()`?

A minimal reproducer doesn't necessarily need to be in your domain, however.  If you are able to provide a minimal reproducer (and just share it with me, or the Play Committee), that can speed things up.

In the meanwhile, I'll see about examining this in the contributor's group.

**Comment by GithubUser8080** [comment]
Thanks @mkurz, your PR is definitely the feature we need. If it makes it in 2.9 it would be great news.  I suppose you can close this issue as a duplicate then!

**Comment by mkurz** [comment]
@GithubUser8080 Just merge the PR, will make it into 2.9
