### ISSUE TITLE
Implement timeout for IO activitiy

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#1120]
We should use the Netty IdleStateHandler to implement a timeout on no IO activity.  This should be disabled by default, since it does not work well with comet/websockets, and open connections, slow reading/writing clients etc consume very few resources in Play.  But for some users who are unable/don't want to increase max files, this will prevent DoS attacks.

**Comment by estsauver** [comment]
Hey there! it looks like this has been resolved by code here:  https://github.com/playframework/playframework/blob/master/framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala#L180

Can this ticket be closed?

**Comment by matanster** [comment]
Looking at the code it seems indeed to address overriding the default http connection timeout of the embedded Netty server. Should this be added to [the documentation](https://www.playframework.com/documentation/2.5.x/ProductionConfiguration#General-configuration) then?

**Comment by mkurz** [comment]
This was fixed long time ago, eg: #5948
