### ISSUE TITLE
Adding JAR in /lib caused NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V

### ISSUE THREAD

**Issue by tantalate** [playframework/playframework#11225]
### Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.14+8-LTS-263, mixed mode)

After I added a JAR file in /lib folder, I got the following runtime error (occurred on any request).
The JAR file is an SDK comes from our cooperative team, and it works well independently.  The file is named as `business.sdk-1.0.2-tool-jar-with-dependencies.jar` in case the name matters.

 Does play have special requirements of the unmanaged dependencies?

      NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
    
    No source available, here is the exception stack trace:
    ->java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
        com.google.inject.Key.ensureRetainedAtRuntime(Key.java:349)
        com.google.inject.Key.strategyFor(Key.java:325)
        com.google.inject.Key.get(Key.java:232)
        play.api.inject.guice.GuiceKey$.apply(GuiceInjectorBuilder.scala:416)
        play.api.inject.guice.GuiceableModuleConversions$$anon$4.$anonfun$configure$2(GuiceInjectorBuilder.scala:376)
        play.api.inject.guice.GuiceableModuleConversions$$anon$4.$anonfun$configure$2$adapted(GuiceInjectorBuilder.scala:374)
        scala.collection.immutable.List.foreach(List.scala:333)
        play.api.inject.guice.GuiceableModuleConversions$$anon$4.configure(GuiceInjectorBuilder.scala:374)
        com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        com.google.inject.spi.Elements.getElements(Elements.java:104)
        com.google.inject.util.Modules$OverrideModule.configure(Modules.java:214)
        com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        com.google.inject.spi.Elements.getElements(Elements.java:104)
        com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
        com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
        com.google.inject.Guice.createInjector(Guice.java:87)
        com.google.inject.Guice.createInjector(Guice.java:78)
        play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
        play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
        play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        play.core.server.DevServerStart$$anon$1.$anonfun$reload$2(DevServerStart.scala:193)
        play.utils.Threads$.withContextClassLoader(Threads.scala:22)
        play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:185)
        play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:148)
        play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:302)
        play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:224)
        akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1307)
        akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
        akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
        akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
        akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
        akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
        akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
        akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
        akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
        akka.actor.Actor.aroundReceive(Actor.scala:537)
        akka.actor.Actor.aroundReceive$(Actor.scala:535)
        akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
        akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
        akka.actor.ActorCell.invoke(ActorCell.scala:548)
        akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        akka.dispatch.Mailbox.run(Mailbox.scala:231)
        akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by mkurz** [comment]
Please don't create both an issue and a discussion (#11224) for the same problem.
Continuing at the discussion, since this is very likely not a Play problem (but we will see).
