### ISSUE TITLE
[2.3.10] unrecognized_name SSL error when using WS

### ISSUE THREAD

**Issue by iammichiel** [playframework/playframework#11243]
Hello, 

When trying to access a file over HTTPS, I get the following error : 

```
[ConnectException: Received fatal alert: unrecognized_name to https://photos.altai-travel.com/1920x0/plongee-medes-a-porquerolles-19178.jpg]
```

The line that throws the error : 
```
WS.url("https://photos.altai-travel.com/1920x0/plongee-medes-a-porquerolles-19178.jpg").get().map {
``` 

From the comments I read online, this seems to be related to the SNI. Switching the url to google.com seems to work. I have tried the following : 

- Add `ws.acceptAnyCertificate=true` in configuration, 
- Add `ws.ssl.loose.disableHostnameVerification=true` 
- Tried adding this in `Global.scala` in startup method `System.setProperty("jsse.enableSNIExtension", "false");`

None of the above seems to fix the issue. 
Any help/ideas on how to fix this ?

**Comment by mkurz** [comment]
Like said by Proman Play 2.3.x is not supported anymore.
