### ISSUE TITLE
Remove 3rd Party Tools page

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#11246]
https://www.playframework.com/documentation/2.8.x/ThirdPartyTools
`documentation/manual/hacking/ThirdPartyTools.md`

After removing travis #11142
We don't use any third party tools AFAIK.

**Comment by ihostage** [comment]
What about YourKit? Maybe needs to send a request to YourKit for get a free license for Play maintainers 😄

**Comment by mkurz** [comment]
👍 haha sure we can do that

**Comment by felipebonezi** [comment]
@mkurz can I remove this page or is it better to wait until you decide about YourKit?

**Comment by mkurz** [comment]
Let's remove it fo now, we can add a similar page later if needed
