### ISSUE TITLE
Duplicate filters enabled when in dev mode

### ISSUE THREAD

**Issue by seansabour** [playframework/playframework#11255]
### Play Version

2.8.15

### API

Scala

### Operating System

Mac OS 11.6.4
### JDK

```
[sean.sabour | ~/Desktop/kenobi-core-service-play]> java -version
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment Zulu11.50+19-CA (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.50+19-CA (build 11.0.12+7-LTS, mixed mode)
```
### Library Dependencies

```
name := "simple-play"
organization := "test.app"
version := sys.env.getOrElse("VERSION", "1.0-SNAPSHOT")
scalaVersion := "2.13.8"

lazy val root = (project in file(".")).enablePlugins(PlayScala, JavaAgent)
  // Use sbt default layout
  .disablePlugins(PlayLayoutPlugin)

libraryDependencies ++= Seq(
  guice,
  "org.scalatestplus.play" %% "scalatestplus-play" % "5.0.0" % Test,
  "com.typesafe.play" %% "play-slick" % "5.0.0",
  "com.typesafe.play" %% "play-slick-evolutions" % "5.0.0",
  "io.kamon" %% "kamon-bundle" % "2.4.7",
  "io.kamon" %% "kamon-prometheus" % "2.4.7"
)
Compile / doc / sources := Seq.empty
Compile / packageDoc / publishArtifact := false
Test / parallelExecution := true
Test / fork  := false
```

### Expected Behavior

Enabling a filter should only add the filter once...

1. Add a GZIP filter to the enabled filters using ```play.filters.enabled += "play.filters.gzip.GzipFilter"```
2. Run your application in dev mode: ```sbt run```
3. View the logs and check to see that GzipFilter is only added once. 

FYI. running the application in production mode works as expected and only adds the filter in once.

### Actual Behavior

1. Add a GZIP filter to the enabled filters using ```play.filters.enabled += "play.filters.gzip.GzipFilter"```
2. Run your application in dev mode: ```sbt run```
3. View the logs and check to see that GzipFilter is added two times.

```
2022-04-27 13:48:20 INFO  play.api.http.EnabledFilters  Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter
    play.filters.gzip.GzipFilter
    play.filters.gzip.GzipFilter

```

### Reproducible Test Case

I created a blank project using ```sbt new playframework/play-scala-seed.g8``` and enable a filter.

**Comment by mkurz** [comment]
Hi @seansabour,

I tried to reproduce your problem, but for me the filter was added only once.
Please have a look at the reproducer project I set up: https://github.com/mkurz/playframework-reproducers/tree/main/playframework-11255 and let me know if that works for you.
IMHO probably you made mistake somewhere else in your config(s), but of course I could be wrong. Please let us know, thanks!

**Comment by mkurz** [comment]
I again tried to reproduce the problem, this time also with Play 3.0.2 but everything worked as expected. Tried my reproducer project which is 1:1 what you described and also tried with `play-scala-seed.g8`.

I am pretty sure you misconfigured something in your application conf.

@seansabour If you still have problems and have more details please let us know, meanwhile I am closing this issue.
