### ISSUE TITLE
Urgent CSRF issue

### ISSUE THREAD

**Issue by risenhoover** [playframework/playframework#11365]
### Discussed in https://github.com/orgs/playframework/discussions/11364

<div type='discussions-op-text'>

<sup>Originally posted by **risenhoover** July 22, 2022</sup>
Play Framework 2.7.9 -> As of three days ago, we started getting reports of people not being able to login, even if they present valid credentials. Upon investigation, they were getting the gray "unauthorized" page provided by the Framework. This happens with various people but others are able to login without issues. We use SecureSocial for authentication and authorization.

The log reports the following message: "[warn] - play.filters.CSRF - [CSRF] Check failed because no token found in headers for /auth/authenticate/userpass"

Additionally, if we open a private window, we can reproduce this error ad infinitum - it's never possible to login and get past the CSRF check and failure. We are also able to see this same issue on other forms protected by CSRF token, in particular our payment page :(.

I have verified that the login page does in fact have a CSRF token in the form, and it is being submitted properly. What is strange is that if you look at the message and the source ( https://github.com/playframework/playframework/blob/d8ebf7cbdb8d360ee499333cc853de708a9eac49/web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala )

it says "NO TOKEN FOUND" - so somewhere somehow this token is getting lost in transit.  
</div>

**Comment by mkurz** [comment]
Closing in favor of #11364, since there are more comments already. If we have more details we can later open another issue again.
