### ISSUE TITLE
Expects DELETE body

### ISSUE THREAD

**Issue by bastaware** [playframework/playframework#11398]
It appears that Play expects http DELETE to contain a body, even though it's optional.

I've got a IOS client that can't send a body and this results in "Invalid Json: No content to map due to end-of-input" when trying to handle the Action.

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE](url)
[https://peterdaugaardrasmussen.com/2020/11/14/rest-should-you-use-a-body-for-your-http-delete-requests/](url)

### Play Version

2.8.16

### API

Scala 2.13.8

### Operating System

OSX

### JDK

Java 11.0.2

### Expected Behavior

App sends empty DELETE request to service.
Play service passes request to Action

### Actual Behavior
Play service isn't able to handle the request and fails before passing it to Action

### Reproducible Test Case

_routes file:_

`DELETE  /favorite/:id          controllers.MyController.deleteFavorite(id: Long)`

_MyController.scala_

```
  def deleteFavorite(id: Long): Action[AnyContent] = {
    println("Enter")
    val result = Action { request =>
      println("Inside")
      Ok(s"Result")
    }
    println("Exit");
    result
  }
```
The above code prints:
Enter
Exit

### Can be tested using:

_Working example:_
`curl --header Accept: --header "Content-Type: application/json" --compressed --cookie "PLAY_SESSION=eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzZXIiOiJHSDNDNkRyekhFYnpBOEJQSENiWU50VnAzYWMyfGZhbHNlIn0sIm5iZiI6MTY2MTM4ODQ1MiwiaWF0IjoxNjYxMzg4NDUyfQ.xceqlZ8IXHvSRg3weoRzmQWfmPtsZczY7EHQWfaWiIQ;SameSite=None;Path=/" --header "transfer-encoding: chunked" --user-agent "Dart/2.17 (dart:io)" --data-raw '{"id":76}' --request DELETE http://localhost:9000/favorite/76`

Returns:
**Result**

_Failing example (notice data is empty):_

`curl --header Accept: --header "Content-Type: application/json" --compressed --cookie "PLAY_SESSION=eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzZXIiOiJHSDNDNkRyekhFYnpBOEJQSENiWU50VnAzYWMyfGZhbHNlIn0sIm5iZiI6MTY2MTM4ODQ1MiwiaWF0IjoxNjYxMzg4NDUyfQ.xceqlZ8IXHvSRg3weoRzmQWfmPtsZczY7EHQWfaWiIQ;SameSite=None;Path=/" --header "transfer-encoding: chunked" --user-agent "Dart/2.17 (dart:io)" --data "" --request DELETE http://localhost:9000/favorite/76`

Returns:
**Invalid Json: No content to map due to end-of-input
 at [Source: (akka.util.ByteIterator$ByteArrayIterator$$anon$1); line: 1, column: 0]**

**Comment by ihostage** [comment]
Hi, @bastaware! 👋 
Why you send the `Content-Type: application/json` header with empty body? 🤔 
Empty string is really [invalid json](https://stackoverflow.com/questions/30621802/why-does-json-parse-fail-with-the-empty-string) 😄 
Can you try to send a request without `Content-Type` header or change it to something else (`application/octet-stream` for example)?

**Comment by bastaware** [comment]
Hi @ihostage 

Thanks a bunch. I didn't even consider that as it's default.

The client framework doesn't allow empty Content-Type, but setting it to "application/octet-stream" solved the problem!
