### ISSUE TITLE
Play Router Annotations In Play 2.x.x

### ISSUE THREAD

**Issue by javahas** [playframework/playframework#1139]
Hi 

It's more 'nice to have' feature, not an issue. I have started using Play 2 and seems to me that it would be more comfortable to have routes as annotations in the controller classes. I have noticed that this module was implemented in Play 1.x. Are you planning to implement it for Play 2? 

Best Regards,
Jasmine

**Comment by bes1002t** [comment]
@jroper the problem using plugins is, that not every plugin is for java and scala. I would prefer scala as programming language, but it is not possible to use these annotations in scala with the jaxrs plugin. Imho it would be nicer to provide this feature in the core. It is much more cleaner than using the scala way imho.
