### ISSUE TITLE
Json.format error if case class has 22 fields (Scala 2.10.1)

### ISSUE THREAD

**Issue by Claus1** [playframework/playframework#1141]
implicit val geoFormat = Json.format[Class22]

produces error : value apply is not a member of play.api.libs.functional.FunctionalBuilder[play.api.libs.json.OFormat]#CanBuild22[Option[String],Option[String],List[models.Price],String,Option[Int],Option[Int],Option[Int],Option[String],List[Double],List[Double],Option[Int],Int,Option[Boolean],Option[Boolean],Option[Boolean],Option[Int],Option[Int],Option[Int],List[models.Price],List[String],Option[String],Option[String]] Note: implicit value propertyFormat is not applicable here because it comes after the application point and it lacks an explicit result type

**Comment by pedrofurla** [comment]
Any workaround on this issue so far?

**Comment by kevinmeredith** [comment]
workaround interest +1
