### ISSUE TITLE
Update of Play and Flyway version in existing application

### ISSUE THREAD

**Issue by ashishpmalkar** [playframework/playframework#11437]
Play Version (2.5.x / etc)
2.5.14

API (Scala / Java / Neither / Both)
Java 1.8

FlyWay Version 3.2
sbt.version=0.13.11
scalaVersion := "2.11.7"

Expected Behavior

New version i am trying addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.x")
sbt.version=1.3.10
scalaVersion := "2.13.8"
When i tried to update the play and flayway versions as per below link it should build and run successfully
https://github.com/flyway/flyway-play
https://www.playframework.com/documentation/2.8.x/Migration28

Actual Behavior
I am getting build error 
```
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-gzip_2.12_1.0/1.0.0/sbt-gzip-1.0.0.pom
[error]   not found: https://jcenter.bintray.com/com/typesafe/sbt/sbt-gzip_2.12_1.0/1.0.0/sbt-gzip-1.0.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-gzip/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-gzip/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-gzip_2.12_1.0/1.0.0/sbt-gzip-1.0.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/simple/maven-releases/com/typesafe/sbt/sbt-gzip_2.12_1.0/1.0.0/sbt-gzip-1.0.0.pom
[error] Error downloading com.typesafe.sbt:sbt-play-ebean;sbtVersion=1.0;scalaVersion=2.12:3.0.0
[error]   Not found
```

**Comment by tototoshi** [comment]
I'm guessing from the error message. The problem is that the version of sbt-gzip or sbt-play-ebean you are using are not compatible with sbt 1.x.
Please try using the latest version of sbt-gzip or sbt-play-ebean.

**Comment by ihostage** [comment]
Thank you, @tototoshi!
