### ISSUE TITLE
[2.8.16] Adding a dependency that uses SLF4J 2.0.x breaks logging

### ISSUE THREAD

**Issue by slisaasquatch** [playframework/playframework#11436]
### Play Version

2.8.16

### API

Java

### Operating System

Windows 10

### JDK

1.8.0_282

### Library Dependencies

```scala
"com.graphql-java-kickstart" % "graphql-java-tools" % "13.0.1"
```

### Expected Behavior

I expect logging to work when I add a dependency that depends on SLF4J 2.0.x.

### Actual Behavior

When the app starts I get this error message

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/C:/Users/username/AppData/Local/Coursier/Cache/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

And then any SLF4J/Logback logging doesn't work.

### Reproducible Test Case

I modified the hello world Java example project [here](https://github.com/slisaasquatch/play-samples/blob/issue-20220921/play-java-hello-world-tutorial/build.sbt) by including `"com.graphql-java-kickstart" % "graphql-java-tools" % "13.0.1"`, which has a dependency for SLF4J 2.0.0, and any logging stops working. If the version is switched to `13.0.0`, which uses SLF4J 1.x.x, then logging works.

I'm not entirely sure if this issue is on Play or GraphQL Java Tools and I created an issue [over there](https://github.com/graphql-java-kickstart/graphql-java-tools/issues/705) as well for reference.

**Comment by ndeverge** [comment]
The issue has already been raised at https://github.com/playframework/playframework/issues/11400 
and it's fixed (https://github.com/playframework/playframework/pull/11433)

You have to wait for the next release.
