### ISSUE TITLE
Json.format  causes NullPointerException if class contains a field like Option[List[CaseClassX]]

### ISSUE THREAD

**Issue by Claus1** [playframework/playframework#1147]
case class Inner(x: Int, y: Int)

case class Outer(arr: Option[List[Inner]], str: String)

implicit val fi = Json.format[Inner]
implicit val fo = Json.format[Outer]
val ds = Json.toJson(Outer(Some(List(Inner(0,1))), ""))

java.lang.NullPointerException: 
     play.api.libs.json.Json$.toJson(Json.scala:83)
     play.api.libs.json.DefaultWrites$$anon$3$$anonfun$writes$2.apply(Writes.scala:166)
     play.api.libs.json.DefaultWrites$$anon$3$$anonfun$writes$2.apply(Writes.scala:166)
     scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
     scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
     scala.collection.immutable.List.foreach(List.scala:318)
...

**Comment by mcku** [comment]
It looks like the issue is still ongoing. Especially when you forget about it and rely on the compiler.

Would it be possible to make sure that the wrong order of implicits is detected by the compiler?
