### ISSUE TITLE
Make netty http backend default (again)?

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#11495]
For upcoming 2.9 release, because akka-http currently has no Scala 3 artifacts.
Not sure if that 3for2 thing works out well.

**Comment by mkurz** [comment]
We need to be aware that run some netty related tests in only daily, they will be skipped for pull requests and branch builds: https://github.com/playframework/playframework/blob/62ea4e281c14edb51402dafdd8c0fdd3d8cd6d99/core/play-integration-test/src/it/scala/play/it/ServerIntegrationSpecification.scala#L93
We probably want to change that if we do make netty the default.

**Comment by BillyAutrey** [comment]
It looks like they're publishing developer snapshots for 2.6 support of Scala 3. Should we ask @octonato or someone if there is any intent to release Akka HTTP Scala 3 jars?

**Comment by mkurz** [comment]
> Should we ask @octonato or someone if there is any intent to release Akka HTTP Scala 3 jars?

I think we are out of luck here, I asked that already: https://github.com/akka/akka-http/pull/4079#issuecomment-1308471022 I don't think they are willing to add Scala 3 support to akka-http 10.2.x anymore...

However we should be able to use the `.cross(CrossVersion.for3Use2_13))` workaround for now.

_In case_ we decide to move to pekko-http this year, the maintainers say they will provide Scala 3 artifacts according to [this comment](https://github.com/apache/incubator-pekko/discussions/144#discussioncomment-4861894):
> Scala 3 support for pekko-http has been deferred to this v1.1.0 release, for instance, but this work is already largely done - just waiting for the conservative v1.0.0 release before it is merged into the main branch.

Also there is this open issue https://github.com/apache/incubator-pekko-http/issues/17 and a scala-3 branch.

Again, I just want to mention that since I follow the pekko development recently , not forcing anything.

@eloots I think you mentioned you have experience with the `CrossVersion.for3Use2_13` approach - are you aware of any performance problems, incompatibles or other caveats? Or is it totally save to use that?

**Comment by BillyAutrey** [comment]
I think making netty the default backend + using `CrossVersion` in our checks is a good compromise. It at least gives those who want to experiment a path forward, and ensures we're prepared to support it if Pekko comes along.

**Comment by jtjeferreira** [comment]
When working on #11551, I noticed some tests were much slower when running in netty vs akka-http, but I didnt investigate further...

**Comment by jtjeferreira** [comment]
> @jtjeferreira I know, I haven't looked into that as well, but I think that just occurs during tests

I dont recall which tests were the problematic ones, but my suspicion at the time, was that something was being reinitialized on every test while with akka-http it wasn't...

**Comment by octonato** [comment]
Guys, sorry for the silence here. I was on vacation the last two weeks. 
Anyway, I guess the question about akka-http compiled to Scala 3 got sorted out.

**Comment by mkurz** [comment]
@octonato It would be really awesome if Lightbend could backport the Scala 3 pull request for akka-http to its 10.2.x branch...
Basically all modules in akka 2.6 provide Scala 3 artifacts, only akka-http does not.

**Comment by mkurz** [comment]
@octonato I am talking about https://github.com/akka/akka-http/pull/4079

**Comment by xuwei-k** [comment]
> talking about https://github.com/akka/akka-http/pull/4079

😢 

https://github.com/akka/akka-http/pull/4079#issuecomment-1308478026

> Is there any chance this gets backported to 10.2.x?

> No, we will only address critical security updates and critical bugs in the 10.2 series (as announced by Jonas here: https://discuss.lightbend.com/t/2-6-x-maintenance-proposal/9949/2 )

**Comment by mkurz** [comment]
Not happening in 2.9, see comment here: https://github.com/playframework/playframework/pull/11711#issuecomment-1488588285

**Comment by mkurz** [comment]
Not relevant anymore. Akka HTTP stays the default for 2.9, Pekko HTTP for 3.0
