### ISSUE TITLE
java testing: RequestBuilder.bodyMultipart does not work

### ISSUE THREAD

**Issue by martinariehm** [playframework/playframework#11496]
### Play Version

2.8.18

### API

Java

### Operating System

Linux tr-XPS-9320 5.14.0-1051-oem #58-Ubuntu SMP Fri Aug 26 05:50:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### JDK

openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)

### Library Dependencies

N.A.

### Expected Behavior

1. Call a route in a unittest via` play.test.Helpers.route(Application, RequestBuilder) `using a `Requestbuilder` with a body added with `play.mvc.Http.RequestBuilder.bodyMultipart(Map<String, String[]>, List<FilePart>)`.
2. The called Controller method should be able to read the body via 
`MultipartFormData<TemporaryFile> body=request.body().asMultipartFormData();`

### Actual Behavior

When calling the route, an error is thrown:

```
[error] Test controllers.HomeControllerTest.testIndex failed: java.lang.NullPointerException: Element must not be null, rule 2.13, took 2.347 sec
[error]     at akka.stream.impl.ReactiveStreamsCompliance$.elementMustNotBeNullException(ReactiveStreamsCompliance.scala:49)
[error]     at akka.stream.impl.ReactiveStreamsCompliance$.requireNonNullElement(ReactiveStreamsCompliance.scala:75)
[error]     at akka.stream.impl.fusing.GraphStages$SingleSource.<init>(GraphStages.scala:272)
[error]     at akka.stream.scaladsl.Source$.single(Source.scala:406)
[error]     at play.api.test.EssentialActionCaller.call(Helpers.scala:270)
[error]     at play.api.test.EssentialActionCaller.call$(Helpers.scala:259)
[error]     at play.api.test.Helpers$.call(Helpers.scala:672)
[error]     at play.api.test.RouteInvokers.route(Helpers.scala:292)
[error]     at play.api.test.RouteInvokers.route$(Helpers.scala:287)
[error]     at play.api.test.Helpers$.route(Helpers.scala:672)
[error]     at play.api.test.RouteInvokers.jRoute(Helpers.scala:279)
[error]     at play.api.test.RouteInvokers.jRoute$(Helpers.scala:278)
[error]     at play.api.test.Helpers$.jRoute(Helpers.scala:672)
[error]     at play.api.test.Helpers.jRoute(Helpers.scala)
[error]     at play.test.Helpers.route(Helpers.java:473)
[error]     at play.test.Helpers.route(Helpers.java:459)
[error]     at controllers.HomeControllerTest.testIndex(HomeControllerTest.java:32)
```

The reason is that `RequestBuilder.bodyMultipart` stores the `body` in `RequestBody` as `MultipartFormData` and `play.api.test.RouteInvokers.jRoute` (line 278) gets the content via `RequestBody.asBytes()`, which does not handle `MultipartFormData`, as is documented in its Javadoc. So it returns null, which triggers the listed error.

### Reproducible Test Case

Starting from `sbt new playframework/play-java-seed.g8`:

`routes`:

```
# An example controller showing a sample home page
GET     /                           controllers.HomeController.index()
POST     /test                           controllers.HomeController.test(request: Request)

# Map static resources from the /public folder to the /assets URL path
GET     /assets/*file               controllers.Assets.versioned(path="/public", file: Asset)
```

`HomeController.java`:

```
package controllers;

import play.mvc.*;
import play.mvc.Http.Request;
import play.libs.Files.TemporaryFile;
import play.mvc.Http.MultipartFormData;

/**
 * This controller contains an action to handle HTTP requests
 * to the application's home page.
 */
public class HomeController extends Controller {

    public Result index() {
        return ok(views.html.index.render());
    }

    public Result test(Request request) {
        MultipartFormData<TemporaryFile> body=request.body().asMultipartFormData();
        return ok(views.html.index.render());
    }

}
```

`HomeControllerTest`:

```
package controllers;

import java.util.*;
import org.junit.Test;
import play.Application;
import play.inject.guice.GuiceApplicationBuilder;
import play.mvc.Http;
import play.mvc.Result;
import play.test.WithApplication;

import static org.junit.Assert.assertEquals;
import static play.mvc.Http.Status.OK;
import static play.test.Helpers.POST;
import static play.test.Helpers.route;

public class HomeControllerTest extends WithApplication {

    @Override
    protected Application provideApplication() {
        return new GuiceApplicationBuilder().build();
    }

    @Test
    public void testIndex() {
        final Map<String, String[]> postParams = new HashMap<>();
        postParams.put("value", new String[]{"value"});
        Http.RequestBuilder request = new Http.RequestBuilder()
                .method(POST)
                .bodyMultipart(postParams, Collections.emptyList())
                .uri("/test");

        Result result = route(app, request);
        assertEquals(OK, result.status());
    }

}
```

**Comment by mkurz** [comment]
Did this occur after an upgrade to Play 2.8.18 - so what I am asking: did this work with Play 2.8.17 or 2.8.16? Or did you just try with Play 2.8.18 in a fresh project? We did fix something regardind multipart form requests in 2.8.18 and wondering if that is related.

**Comment by martinariehm** [comment]
It occurred in our project running on 2.8.16. For the test case I created a fresh project which was running on 2.8.18. The same error occurred. However the setup is slightly different in our project so the stack trace might have been a bit different. But the main issue is the same: the Java compatibility layer calls RequestBody.asBytes which does not support MultipartFormData.

I am pretty sure the same issue occurred on 2.7, since in all our Unittests we are using bodyRaw for multipart/formdata, because bodyMultipart didn't work and I remember having had the problem before.

**Comment by mkurz** [comment]
OK, thanks so this didn't happen because of our changes on the recent 2.8.18 release, thanks.

**Comment by adrianlyjak** [comment]
I submitted a PR fix for this. Looking for feedback and whether its an appropriate solution.
