### ISSUE TITLE
Consider upgrading Jackson 2.13 in the stable 2.8 branch

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#11508]
The reason we never upgraded from Jackson 2.11 in Play 2.8.x was that akka never upgraded as well. So there was a fear that if Play upgraded but not akka that might be problematic. However akka finally upgraded to 2.13.x for their recent akka 2.7 release: https://github.com/akka/akka/pull/31595 According their migration guide:
> The Jackson dependency ... has been updated to 2.13.4 in Akka 2.7.0. That bump includes many fixes and changes to Jackson, but it should not introduce any incompatibility in serialized format.

That pull request didn't break anything and no tests needed changes. Actually, for Scala 3 akka already did use Jackson 2.13 in it's last 2.6.x releases: https://github.com/akka/akka/blob/044bb2dc0a3804d7fe33a1d3e988830256c108fa/project/Dependencies.scala#L29-L30 So it seems they were worried more about problems caused by dependencies:
https://github.com/akka/akka/issues/31282#issuecomment-1087439343
> I wouldn't do that in a patch release of the stable release train of Play. Would probably become a mess with transitive dependencies between Akka, Play and Lagom.

Also see #11222 and the issues it refers, there were many discussions going on about an upgrade already and the argument against it was to keep it in sync with akka... I think now however from the akka perspective it's pretty safe to upgrade.

That's why I think we should consider to finally upgrade to 2.13 but of course make that clear to people in the release notes and refer to the Jackson release notes (https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12 and https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13). The same applies for play-json and play-ws. We should also check which upgraded and new dependencies a new jackson version pulls in.
BTW: In the main branch we upgraded already: #11219

**Comment by pasindusenevirathne** [comment]
Hi,

We have updated our Play project to these versions,

Play Version - 2.8.18
Scala version - 2.13.10
Akka version - 2.6.20
Play pac4j version - 11.1.0-PLAY2.8
Pac4j core version - 5.6.1
Pac4j http version - 5.6.1
Pac4j saml version - 5.6.1

However these versions complained me about the **jackson-module-scala** version that we were using **2.12.2**, and we had to update to **2.13.4**.
My question is, is it recommended to update jackson-module-scala to this version ?

**Comment by mkurz** [comment]
> My question is, is it recommended to update jackson-module-scala to this version ?

@pasindusenevirathne It should be fine from Play's perspective. However I highly recommend to upgrade _all_ jackson libraries to 2.13.x, no just `jackson-module-scala` - look here: #11222
Also just make sure before you deploy that all parts of your app that make use of jackson/json are testet and still work correctly.

**Comment by pasindusenevirathne** [comment]
> > My question is, is it recommended to update jackson-module-scala to this version ?
> 
> @pasindusenevirathne It should be fine from Play's perspective. However I highly recommend to upgrade _all_ jackson libraries to 2.13.x, no just `jackson-module-scala` - look here: #11222 Also just make sure before you deploy that all parts of your app that make use of jackson/json are testet and still work correctly.

Thanks @mkurz . We'll do it.

**Comment by ruiwchina** [comment]
Hi @mkurz, we are also looking forward to this change. May I ask if there are specific plans and timelines for 2.8.20?
Thanks!

**Comment by mkurz** [comment]
This won't happen anymore in Play 2.8. Recommendation is to upgrade to Play 2.9 instead: https://github.com/playframework/playframework/releases/tag/2.9.0-RC2
You can still upgrade Jackson yourself in 2.8 if desired, see https://www.playframework.com/documentation/2.9.x/General#End-of-life-(EOL)-Dates.
