### ISSUE TITLE
Upgrade scalafmt from 2 to 3 in order to sort scala imports

### ISSUE THREAD

**Issue by adrianlyjak** [playframework/playframework#11510]
It was brought up in the recent java format changes that playframework should also sort scala imports

https://github.com/playframework/playframework/pull/11502#issuecomment-1289268792

Looks like playframework is on an old version of scalafmt (2.x). That will need to be addressed first, because the import rewrite rule wasn't introduced until scalafmt 3.0.

I made some preliminary changes, but would like to discuss some of the format changes in more detail. Looks like if upgrading blindly, there are a lot of new formats change

I tried to break this down by commit so that we could discuss in a little more details

- [Second commit](https://github.com/adrianlyjak/playframework/pull/1/commits/c81b03ced6c3dfcf5809b929ced0be3aa4aad32c) runs the ugprade rewrites, with as many disabled as  I could figure out
- [Fourth Commit](https://github.com/adrianlyjak/playframework/pull/1/commits/df5db7e2d438bea943a674b075d740b84fe8f98a) adds scala import sorting
- [Sixth commit](https://github.com/adrianlyjak/playframework/pull/1/commits/ec412ad18db4522cbc02a2e259251d641fd2699d) opts into some of the new defaults

I can make a PR to upgrade just the scalafmt version with as minimal format changes as possible, or just submit a big PR that does the whole shebang. Any preference?

**Comment by felipebonezi** [comment]
It would be more careful to first upgrade with minimal effort on changes.
I believe that code format isn't a problem right now and only the `sort` functionality must be our goal for now.

**Comment by jtjeferreira** [comment]
This will also be important for scala3 migration #11260
