### ISSUE TITLE
Evolutions not work for mssql jtds driver

### ISSUE THREAD

**Issue by thanh-ngvt** [playframework/playframework#11530]
### Play Version

2.8.18

### API

Java

### Operating System

Window

### JDK

openjdk version "1.8.0_332"
OpenJDK Runtime Environment (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (build 25.332-b09, mixed mode)

### Expected Behavior

Evolution script should run when using jtds sqlserver
```
db.default.url="jdbc:jtds:sqlserver://TODO
```

### Actual Behavior

Evolution script can not run success fully

Root cause: 
```
ERROR: Use INSERT with a column list to exclude the timestamp column, or insert a DEFAULT into the timestamp column

stack trace: play/api/db/evolutions/EvolutionsApi.scala#logBefore:174
```
If using db.default.url="jdbc:jtds:sqlserver://TODO" the play_evolutions table will create applied_at timestamp column
and prepareStatement for insert new entry is using `ps.setTimestamp(3, new Timestamp(System.currentTimeMillis()))`

**Comment by mkurz** [comment]
Hmm.. 
> `ERROR: Use INSERT with a column list to exclude the timestamp column, or insert a DEFAULT into the timestamp column`

Let's see:
https://github.com/playframework/playframework/blob/37543872239bd95de6fbaf4b7799cb56aaa15698/persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L170-L181

We do use a column list, but explicitely set the ´applied_at` field. I can't see why this code would not work. Do you know if the jTDS driver handles timestamps different?

Anyway, looking at the [jTDS](https://jtds.sourceforge.net/) driver it seems it's very very outdated:
- Last release from 2013: https://sourceforge.net/projects/jtds/files/jtds/
- Last code update in 2016: https://sourceforge.net/p/jtds/code/HEAD/tree/

I recommend to switch to the official, MIT licensed [mssql-jdbc](https://github.com/microsoft/mssql-jdbc/) driver, it's available [from Maven Central as well](https://github.com/microsoft/mssql-jdbc/#download-the-driver).
Any reason to stick with jTDS?

**Comment by thanh-ngvt** [comment]
I found that play_evolution table for sqlserver ` applied_at` should be datatime https://github.com/playframework/playframework/blob/37543872239bd95de6fbaf4b7799cb56aaa15698/persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L384-L395

but in case we use jtds driver for mssql `applied_at` column is timestamp, because of jtds URL fornat is `jdbc:jtds:sqlserver://TODO` but this switch case right here only create play_evolution for mssql when jdbc format is `jdbc:sqlserver`
https://github.com/playframework/playframework/blob/37543872239bd95de6fbaf4b7799cb56aaa15698/persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L267-L276
https://github.com/playframework/playframework/blob/37543872239bd95de6fbaf4b7799cb56aaa15698/persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala#L90

So yes, using the mssql-driver that you suggested, it worked 👯

**Comment by mkurz** [comment]
Good. We could of course also make jTDS use the same sql statements as the mssql driver in Play by simply updating the regex:
```scala
 val SqlServerJdbcUrl = "^(jdbc|jtds):sqlserver:.*".r 
```
If you want to keep using jTDS you can provide a pull request for that, otherwise we can close this issue.

**Comment by thanh-ngvt** [comment]
Thanks a lot, jTDS is too outdated I will use the newer one.
