### ISSUE TITLE
play-java-forms should use jakarta.validation imports

### ISSUE THREAD

**Issue by gitterrost4** [playframework/playframework#11653]
The play-java-forms library currently is dependent on jakarta.validation:2.0.2 which uses the javax.validation package name.

Numerous libraries already use version 3 of jakarta.validation which includes a switch to the jakarta.validation package names. In order to use Play in conjunction with current libraries, this change needs to be made here as well. Through eviction mechanics, the javax.validation package will be completely removed and a ClassNotFound error is thrown.

**Comment by mkurz** [comment]
Thanks! We are aware of that, see #11079

**Comment by mkurz** [comment]
Fixed by
- #11686

**Comment by sumit-ff** [comment]
so you are saying, if i am upgrading my play version from 2.9 to 3.0.x then i am able to shift from javax to jakarta completely??

**Comment by mkurz** [comment]
- Ref #13262
