### ISSUE TITLE
Reminder: Check if all 2.8.x changes are ported to main branch before 2.9 release

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#11673]
Just a reminder to check if all commits/pull requests of the 2.8.x branch were ported to main:
https://github.com/playframework/playframework/compare/2.8.0...2.8.x
Sometimes people open PRs against 2.8.x, so it could happen we forgot to forward port things.
We could also merge 2.8.x into main, but I think that would cause to many conflicts at this point.

**Comment by BillyAutrey** [comment]
The link to show merges to `2.8.x`: [link](https://github.com/playframework/playframework/pulls?q=is%3Apr+is%3Aclosed+base%3A2.8.x+merged%3A%3E2023-01-12+)

Looking at the 2.8.19 release, everything newer than #11604 needs to be evaluated. Working through it now.

**Comment by BillyAutrey** [comment]
New link to check when the time comes: [link](is:pr is:closed base:2.8.x merged:>2023-02-16 )

**Comment by mkurz** [comment]
@BillyAutrey Thanks! So you checked the 2.8.19 release or the whole 2.8.x branch?

**Comment by BillyAutrey** [comment]
I checked all merges to `2.8.x` since `2.8.19` was released - I did _not_ check the `2.8.19` release. Should we?

**Comment by mkurz** [comment]
Yeah, I was thinking to check everything from starting from 2.8.0 until today. We don't have to comment on everything, just a very quick check. Also there is no need to check pull requests that just upgrade dependencies, we are up-to-date in main anyway because of scala-steward. Seems like https://github.com/playframework/playframework/pulls?q=is%3Apr+is%3Aclosed+base%3A2.8.x is what I mean... haha we don't have to do that at once, maybe one or two pages per day.
I just feel like we should do check this, since it would suck if we ship 2.9 and miss some bugfix or feature which we just merged into 2.8.x.

**Comment by mkurz** [comment]
A lot of PR's are from mergify anyway, also we can look for comments at the bottom from mergify which says "Backports have been created" for the main branch.

**Comment by BillyAutrey** [comment]
Does mergify tag? Or should we tag things a certain way that we've already checked? That would simplify the filtering process.

**Comment by mkurz** [comment]
Yeah! We can use `-author:app/mergify`: https://github.com/playframework/playframework/pulls?q=is%3Apr+is%3Aclosed+base%3A2.8.x+-author%3Aapp%2Fmergify+
Now it's almost half!

**Comment by mkurz** [comment]
Now we can then split that in two batches:
* One with adding `commenter:app/mergify`: https://github.com/playframework/playframework/pulls?q=is%3Apr+is%3Aclosed+base%3A2.8.x+-author%3Aapp%2Fmergify+commenter%3Aapp%2Fmergify+
These are very likely that they have been ported to main, since mergify did not author, but comment on.
* One with the opposite `-commenter:app/mergify`: https://github.com/playframework/playframework/pulls?q=is%3Apr+is%3Aclosed+base%3A2.8.x+-author%3Aapp%2Fmergify+-commenter%3Aapp%2Fmergify+
So these ones mergify didn't author nor comment on. So they need to be checked a bit closer. But like said, if the title already says something like "upgrade dependency xyz" we don't even have to look into that.

**Comment by BillyAutrey** [comment]
I think we could go a little further here, and save ourselves some duplicate work. Maybe introduce a tag to the project for things that have been backported, so we can easily filter out the ones we've inspected. I might look through the tags to see if any fit - or create one, if we think it's a decent idea.

**Comment by mkurz** [comment]
@BillyAutrey yeah we can just create a temporary label for that and exclude it in the search.

**Comment by mkurz** [comment]
looking at this now
