### ISSUE TITLE
Check / update / release all the needed sbt-web plugin projects

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#11675]
Another reminder:
Not looking at this right now, however if I recall correctly, Play makes use of sbt-web and sbt-js-engine and other dependencies.
I remember vaguely that there was something going on or needs to be fixed (?):
- [x] I do have an email from James Roper in my inbox regarding this projects what needs to be done, take a look

Take a look at following projects:
- [x] https://github.com/sbt/sbt-web
- [x] https://github.com/sbt/sbt-web-build-base
- [x] https://github.com/sbt/sbt-js-engine
- [x] https://github.com/typesafehub/npm
- [x] https://github.com/typesafehub/js-engine
- [x] Also need to make sure all of that stuff is working with the latest node/npm release

**Comment by adrianlyjak** [comment]
I'm guessing this might be related to what I'm running into. Builds started failing a few hours ago for lots of play related sbt plugins. Did maybe the typesafe repo stop paying jfrog for hosting these sbt plugins? 

With my coursier cache cleared I'm seeing errors like below:

```
[error]   checksum format error: /Users/adrianlyjak/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml.sha1
[error]   checksum format error: /Users/adrianlyjak/Library/Caches/Coursier/v1/https/repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml.sha1
```

Coursier attempting to download sha file seems to just be some generic jfrog page:

https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml.sha1

```
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/favicon.ico"><title>MyJFrog - JFrog Customer Portal</title><link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800&display=swap" rel="stylesheet"><script>VERSION = "2023.3.223";
      API_PROXY_URL = "https://myjfrog-api.jfrog.com/api/v1/";
      MYJFROG_UI_URL = "https://my.jfrog.com";
      COOKIES_DOMAIN = "jfrog.com";
...
```

<img width="557" alt="image" src="https://user-images.githubusercontent.com/2024018/230529912-2573926e-ed3b-41dd-84c0-3e3888d1358e.png">

**Comment by tsuyoshizawa** [comment]
Ref https://github.com/sbt/sbt/issues/7202

**Comment by mkurz** [comment]
Done. Now that #11811 got merged this can be closed.
Also the plugins are now hosted on maven central, not https://repo.scala-sbt.org/ anymore :+1:
