### ISSUE TITLE
Fix Link For `Download the binary package` 

### ISSUE THREAD

**Issue by amolmote** [playframework/playframework#11752]
I am trying to install the binary package for play. I am getting server not found issue. Can somebody redirect this page to correct link for downloading binary for play.
 
page need to fix
[Play binary package](http://download.playframework.org/)

**Comment by mkurz** [comment]
Which page refered you to http://download.playframework.org/? Are you talking about Play 1 or Play 2? For Play 2 you don't need to download a binary package. To get started take a look  at https://www.playframework.com/getting-started
