### ISSUE TITLE
Trailing newlines are ignored in SSE

### ISSUE THREAD

**Issue by ryoppy** [playframework/playframework#11834]
There's an issue where trailing newlines are ignored in SSE (Server-Sent Events). For SSE, according to its specifications and as observed in the Play Framework's EventSource, newlines are used to output `data:` consecutively. However, it seems that consideration for cases where there is a newline at the end has been overlooked.

It handles newlines that aren't at the end just fine. (ref: [EventSourceSpec](https://github.com/playframework/playframework/blob/6e706ab88e843d7119609fad8247291b921efaeb/core/play/src/test/scala/play/api/libs/EventSourceSpec.scala))

```
Event("a\nb").formatted // data: a\ndata: b\n\n
```

However, it unfortunately ignores a trailing newline.

```
Event("a\n").formatted // data: a\n\n
```

Ideally, it should work as follows.

```
Event("a\n").formatted // data: a\ndata: \n\n
```

I am planning to fix this by adding -1 to [the split here](https://github.com/playframework/playframework/blob/6e706ab88e843d7119609fad8247291b921efaeb/core/play/src/main/scala/play/api/libs/EventSource.scala#L75).

If there's no issue with this, I can create a Pull Request. What do you think?

**Comment by mkurz** [comment]
@ryoppy please provide a PR , this seems reasonable to me. I am just wondering, what's your use case to add a new line at the end to just send `data: \n\n`?

**Comment by ryoppy** [comment]
@mkurz I'm using ChatGPT API to return stream text with playframework SSR. stream sends text in parts, so there are many cases where there is a new line at the end.

I have submitted a pull request. https://github.com/playframework/playframework/pull/11848
