### ISSUE TITLE
Can't use Java 17 with 2.9-M6 milestone if application is using ehcache

### ISSUE THREAD

**Issue by yle-heikkij** [playframework/playframework#11852]
### Play Version

2.9.0-M6

### API

Scala

### Operating System

MacOS 13.4.1 (22F82)

### JDK

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode)

### Expected Behavior

We have small Play Framework application I tried to run with 2.9.0-M6 in Java 17 environment. App uses ehcache. Everything works fine if Java version is 11

### Actual Behavior

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @61fbe4c1
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.getAllFields(ObjectGraphWalker.java:271)
```

-->

**Comment by xuwei-k** [comment]
Maybe playframework should update to ehcache version 3.x 🤔 

- https://github.com/ehcache/ehcache3
- https://github.com/ehcache/ehcache2
- https://github.com/playframework/playframework/blob/63c8845ca6392094f079c35652a04a12b153d779/project/Dependencies.scala#L301-L303

**Comment by ihostage** [comment]
@yle-heikkij Can you try to add this JVM parameter `--add-opens=java.base/java.lang=ALL-UNNAMED` to your run application command? 

@xuwei-k I agree with you, we should add upgrade Ehcache into our plans 📝

**Comment by yle-heikkij** [comment]
> @yle-heikkij Can you try to add this JVM parameter `--add-opens=java.base/java.lang=ALL-UNNAMED` to your run application command?
Yes, I tested and error went away

**Comment by mkurz** [comment]
Yeah, ehcache should be upgraded, however this will not make it into 2.9 anymore. Tagged for next major release.

**Comment by ben-manes** [comment]
fyi ehcache2 is fully end of life (no maintenance or critical/security fixes)

**Comment by mkurz** [comment]
fyi, we are thinking about to remove play ehcache support. You can either provide a pull request to  upgrade to ehcache 3 or you can of course also write a Play module and host it in your own repo.
No one from the Play team will work on that however, so if no one steps forward, we will eventually delete the current Play ehcache module which is still based on ehcache 2.

**Comment by yle-heikkij** [comment]
We decided just to stop using ehcache in out product
