### ISSUE TITLE
Upgrade akka to version 2.6.21

### ISSUE THREAD

**Issue by ashleymercer** [playframework/playframework#11851]
### Play Version
2.8.19

### API
Both

### Library Dependencies
akka 2.6.20

### Expected Behavior
akka recently released version 2.6.21 which contains a back-port of a critical performance fix:
https://github.com/akka/akka/issues/29922
https://github.com/akka/akka/releases/tag/v2.6.21

Strictly, this actually seems to be a bug in the JVM itself but 2.6.21 adds a workaround in akka which detects the buggy behviour. Without this fix, the JVM can get into a state where it consumes a whole CPU core indefinitely.

The version bump from 2.6.20 -> 2.6.21 only includes this one fix, so should be a drop-in replacement.

**Comment by PromanSEW** [comment]
#11849

**Comment by mkurz** [comment]
https://github.com/playframework/playframework/pull/11849#issuecomment-1613848936

**Comment by mkurz** [comment]
Fixed by #11874, next 2.8.x release this week.

**Comment by mkurz** [comment]
Part of just released Play 2.8.20: https://github.com/playframework/playframework/releases/tag/2.8.20
