### ISSUE TITLE
Using AkkaHttpServer, request.queryString return empty string key when url ends with ?.

### ISSUE THREAD

**Issue by kijuky** [playframework/playframework#11870]
### Play Version

- Play: 2.8.19

### API

- Scala: 2.13.11
- Java: 11.0.9.1

### Operating System

```
Darwin macbook-pro-16-inch-2019.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64
```

### JDK

```
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)
```

### Library Dependencies

None.

### Expected Behavior

1. run `sbt new playframework/play-scala-seed.g8`
2. Write println(request.queryString) in HomeController's index method.
3. run `sbt run`
4. open `http://localhost:9000?`
5. output `Map()`

### Actual Behavior

1. run `sbt new playframework/play-scala-seed.g8`
2. Write println(request.queryString) in HomeController's index method.
3. run `sbt run`
4. open `http://localhost:9000?`
5. output `Map( -> List())`. This mean is empty string key.

### Remarks

- It only happens when using AkkaHttpServer. When using NettyServer it behaves as expected.
- see https://github.com/playframework/playframework/blob/main/transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala#L70

**Comment by kijuky** [comment]
solved by https://github.com/playframework/playframework/pull/11667

**Comment by kijuky** [comment]
Thanks @mkurz . I confirmed that play-2.9.0-M6 solved it.

**Comment by ihostage** [comment]
Thanks @kijuky! 👍
