### ISSUE TITLE
logback-classic 1.4.9 contains breaking change that breaks Play

### ISSUE THREAD

**Issue by felixkrull-neuland** [playframework/playframework#11907]
logback-classic 1.4.9 removed a public method from their API that's used by Play. I haven't looked more closely, but I suspect this version would break any Play app that uses Logback? This is the stacktrace I get from our integration tests:

```
[error] java.lang.NoSuchMethodError: 'void ch.qos.logback.classic.util.ContextInitializer.configureByResource(java.net.URL)'
[error] 	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:125)
[error] 	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:73)
[error] 	at play.api.inject.guice.GuiceApplicationBuilder.$anonfun$configureLoggerFactory$1(GuiceApplicationBuilder.scala:137)
[error] 	at scala.Option.map(Option.scala:242)
[error] 	at play.api.inject.guice.GuiceApplicationBuilder.configureLoggerFactory(GuiceApplicationBuilder.scala:136)
[error] 	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:112)
[error] 	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:201)
[error] 	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
[...stacktrace continues]
```

To be clear: this sucks, and IMO they shouldn't do this. But apparently [their guidance on this is "just copy the method into your own code"](https://mailman.qos.ch/pipermail/logback-user/2023-August/005284.html). This is the commit that removed the method: https://github.com/qos-ch/logback/commit/4b06e062488e4cb87f22be6ae96e4d7d6350ed6b Presumably this is the newest version of this code.

### Play Version
2.8.19, but likely older as well

### API
Scala, but probably either

### Operating System
Linux, but probably all OS

### JDK
JDK 11 ("Amazon.com Inc. Java 11.0.18"), but probably others as well

### Library Dependencies
ch.qos.logback:logback-classic 1.4.9

### Expected Behavior
Play doesn't crash on startup and logback logging works.

### Actual Behavior
Play crashes on startup. This is the stacktrace when actually running the application:
```
VM settings:
    Max. Heap Size (Estimated): 10.67G
    Using VM: OpenJDK 64-Bit Server VM

Oops, cannot start the server.
java.lang.NoSuchMethodError: 'void ch.qos.logback.classic.util.ContextInitializer.configureByResource(java.net.URL)'
	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:125)
	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:73)
	at play.api.inject.guice.GuiceApplicationBuilder.$anonfun$configureLoggerFactory$1(GuiceApplicationBuilder.scala:137)
	at scala.Option.map(Option.scala:242)
	at play.api.inject.guice.GuiceApplicationBuilder.configureLoggerFactory(GuiceApplicationBuilder.scala:136)
	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:112)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:201)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:53)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:29)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

**Comment by beikern** [comment]
Can confirm. Play just breaks with the same stack trace that you provided.

**Comment by gaeljw** [comment]
Having the issue as well.

To be fair, the method was deprecated in logback for some time already.

**Comment by iaco86** [comment]
This affects also people using logback `1.3.9`

**Comment by gervaisb** [comment]
In case of someone want to know without going to the history of Logback (https://github.com/qos-ch/logback/commit/4b06e062488e4cb87f22be6ae96e4d7d6350ed6b), Play is working well with **logback 1.4.8**

**Comment by mkurz** [comment]
Bites us in https://github.com/playframework/play-samples/pull/383

**Comment by mkurz** [comment]
> To be fair, the method was deprecated in logback for some time already.

This method was deprecated with logback PATCH release 1.4.6 ([commit](https://github.com/qos-ch/logback/commit/86f388965204df28843039f65b0bc437aff007f5)) and removed in logback PATCH release 1.4.9 ([commit](https://github.com/qos-ch/logback/commit/4b06e062488e4cb87f22be6ae96e4d7d6350ed6b)), so I can not support the statement "the method was deprecated in logback for some time already". This is very very bad bad practise from logback IMHO, since it's common practise to not break code and/or remove methods and/or classes in patch releases (except if it is absoluty necessary and unavoidable in case of security bug fixes, but then it should be mentioned in release notes including migration steps).

**Comment by mkurz** [comment]
BTW: Others running in the problem as well, it's definitely not just Play: https://mailman.qos.ch/pipermail/logback-user/2023-August/005288.html

**Comment by gaeljw** [comment]
Indeed. I only saw it was deprecated and assumed it was for at least 1 minor version. I meant no offense to Play maintainers ;)

**Comment by mkurz** [comment]
:wink: Don't worry, just wanted to clarify. Taking a look now at this.
