### ISSUE TITLE
Akka throws exception on Websocket timeout when using Scala 3

### ISSUE THREAD

**Issue by iachimoe** [playframework/playframework#11928]
### Play Version

2.9.0-M6

### API

Scala 3

### Operating System

MacOS Ventura 13.5.1

### JDK

```
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)
```

### Library Dependencies

Scala 3.3.0/Akka 2.6.20

### Expected Behavior

Websocket is closed if it hasn't been interacted with within the idle timeout period (which seems to default to 75 seconds)

### Actual Behavior

```
[warn] p.c.s.c.WebSocketFlowHandler - WebSocket communication problem: HTTP idle-timeout encountered, no bytes passed in the last 75 seconds. This is configurable by akka.http.[server|client].idle-timeout.
Uncaught error from thread [application-akka.actor.default-dispatcher-23]: 'akka.actor.Status$Failure akka.actor.Status$Failure$.unapply(akka.actor.Status$Failure)', shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: 'akka.actor.Status$Failure akka.actor.Status$Failure$.unapply(akka.actor.Status$Failure)'
	at play.api.libs.streams.ActorFlow$$anon$2.applyOrElse(ActorFlow.scala:53)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at play.api.libs.streams.ActorFlow$$anon$1.aroundReceive(ActorFlow.scala:49)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

According to https://github.com/akka/akka/blob/v2.6.21/akka-actor/src/main/scala/akka/actor/Actor.scala#L296 , `akka.actor.Status` has been "superseded" by `akka.pattern.StatusReply` , though I'm not sure whether this information leads to any realistic way of fixing the issue as it is experienced by Play. Ideally there would be a new version of Akka 2.6 with the missing `unapply` method added.

### Reproducible Test Case

My apologies, I don't have time to make a minimal test case at this moment, and will soon be on vacation without a computer until mid-September.
However, I believe that any standard Play app using Scala 3 that uses websockets would exhibit this behaviour.

**Comment by mkurz** [comment]
You should use Scala 3.3.0 (because you wrote 3.3.0)

How do include Play in your application? Do you activate the sbt plugin with `enablePlugins(PlayScala)` (or `PlayJava`) in your `build.sbt`?

**Comment by iachimoe** [comment]
Apologies, I am using 3.3.0, I have corrected the typo.
I do activate the sbt plugin with `.enablePlugins(PlayScala)`. The particular project is a multi-project build, though that particular setup has been working without much change since Play 2.5.

**Comment by mkurz** [comment]
Fix is here: #11929
When will your vacation start? Will you have time tomorrow to test this if I cut a M7?

BTW: Also I am pretty sure this exception would not occur if you would switch to the netty backend ( `.enablePlugins(PlayScala, PlayNettyServer).disablePlugins(PlayAkkaHttpServer)`)

**Comment by iachimoe** [comment]
Nice! My vacation doesn't start until Thursday and I will definitely have time to test before then if you can get a new milestone out tomorrow.
I guess I could switch to the netty backend, but sticking to the default (i.e. akka-http) has worked fine for me until now. With the combined licencing/scala 3 issues around Akka, is netty likely to be the preferred choice going forward?

**Comment by mkurz** [comment]
Fantastic! Thanks for checking!
