### ISSUE TITLE
"Insecure HTTP request is unsupported" Error in Scala

### ISSUE THREAD

**Issue by pratham-0709** [playframework/playframework#11940]
Hello all , I am new to scala and was trying and performing CRUD operations in scala using playframework and Slick while performing I came across this issue for which image has been attached for your reference ... 
![error](https://github.com/playframework/playframework/assets/53365574/fd14c4aa-1d00-4e50-a447-fd721a7a6da7)

In this case , used concept called resolvers what does that mean how can i resolve the issue raised for more understanding also added the sharing build.sbt file for which image is attached for your reference ...  
![sbt](https://github.com/playframework/playframework/assets/53365574/40448b69-e02c-4f8e-bd36-7e7d9e7152d0)

Let me know how can i work on it ... if any solution or reference regarding it , you can share it too.. 

Thanks.

**Comment by mkurz** [comment]
You have to use `https` for the scalaz-bintray repo and the error should go away. However you very likely don't need that repo and can just remove that line.

**Comment by pratham-0709** [comment]
Thanks [mkurz](https://github.com/mkurz) , 

The issue is been resolved .
