### ISSUE TITLE
not found `routes-compiler_2.13` and `_3` 2.9.0-M7

### ISSUE THREAD

**Issue by xuwei-k** [playframework/playframework#11964]
### Play Version

2.9.0-M7

### API

Scala

### Library Dependencies

```scala
libraryDependencies += "com.typesafe.play" %% "routes-compiler" % "2.9.0-M7"

scalaVersion := "3.3.1"
```

### Expected Behavior

success `sbt update`

### Actual Behavior

```
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.play:routes-compiler_3:2.9.0-M7
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/play/routes-compiler_3/2.9.0-M7/routes-compiler_3-2.9.0-M7.pom
```
https://repo1.maven.org/maven2/com/typesafe/play/routes-compiler_2.13/
https://repo1.maven.org/maven2/com/typesafe/play/routes-compiler_3/

<img width="521" src="https://github.com/playframework/playframework/assets/389787/0c7b138b-7063-41f0-a5cc-d2bb182d3949">
<img width="548" src="https://github.com/playframework/playframework/assets/389787/bc4f0e41-69b3-40f3-b326-ef4c34a0656f">

**Comment by mkurz** [comment]
Was renamed to `play-routes-compiler`.
See
* https://repo1.maven.org/maven2/com/typesafe/play/play-routes-compiler_2.13/
* https://repo1.maven.org/maven2/com/typesafe/play/play-routes-compiler_3/
* #11927
* https://github.com/scala-steward-org/scala-steward/pull/3146
* https://github.com/playframework/playframework/blob/main/documentation/manual/releases/release29/migration29/Migration29.md#changed-artifact-names
