### ISSUE TITLE
sbt-pekko-version-check sbt plugin?

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#11986]
Until Play 2.9 we use the [sbt-akka-version-check](https://github.com/johanandren/sbt-akka-version-check) plugin to validate the akka versions [here](https://github.com/playframework/playframework/blob/8395f65a37bd2f66905193378d6a69871e7bd0ea/build.sbt#L517). . Might make sense to fork it for Pekko; the Pekko org itself will not do the fork, see

* https://github.com/apache/incubator-pekko/discussions/671

Not that important currently, but if with more major/minor Pekko versions we might want to introduce such a `sbt-pekko-version-check` plugin.

**Comment by Philippus** [comment]
I've forked it, and made some, what I think of as, improvements. Feel free to check/try it out: https://github.com/Philippus/sbt-pekko-version-check

**Comment by mkurz** [comment]
Thanks! If you open a PR with your fork to replace 
https://github.com/playframework/playframework/blob/dd4a6746811727d996d8d83c60787f498e72d606/project/plugins.sbt#L36
I might look at it later.
