### ISSUE TITLE
[scala3-play2.9] ClassNotFoundException: akka.http.scaladsl.model.Uri$ParsingMode

### ISSUE THREAD

**Issue by mfirry** [playframework/playframework#12025]
**Play Version**

2.9.0-RC3

**API**
Scala "3.3.1

**Operating System**
macOS 13.6

**JDK**
OpenJDK Runtime Environment Zulu21.28+85-CA (build 21+35)

I'm trying to use Scala 3 on a very simple play project (can provide link to repo) and I'm getting the following when I do `sbt run`
```
[error] java.lang.NoClassDefFoundError: akka/http/scaladsl/model/Uri$ParsingMode
[error] 	at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:742)
[error] 	at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:741)
[error] 	at play.core.server.DevServerStart.mainDev$$anonfun$1(DevServerStart.scala:328)
[error] 	at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
[error] 	at play.core.server.DevServerStart.mainDev(DevServerStart.scala:332)
[error] 	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:80)
[error] 	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:55)
[error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[error] 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:312)
[error] Caused by: java.lang.ClassNotFoundException: akka.http.scaladsl.model.Uri$ParsingMode
```

my `build.sbt` looks like this:

```
scalaVersion := "3.3.1"

val akkaVersion = "2.6.21"

lazy val root = (project
  .in(file("."))
  .settings(
    PlayKeys.akkaHttpScala3Artifacts := true,
    libraryDependencies ++= Seq(
      guice,
      "com.typesafe.play" %% "play-json" % "[2.10,2.11)",
      "com.typesafe.akka" %% "akka-actor"                 % akkaVersion,
      "com.typesafe.akka" %% "akka-actor-typed"           % akkaVersion,
      "com.typesafe.akka" %% "akka-stream"                % akkaVersion,
      "com.typesafe.akka" %% "akka-slf4j"                 % akkaVersion,
      "com.typesafe.akka" %% "akka-serialization-jackson" % akkaVersion,
    )
  )
  .enablePlugins(PlayScala)
  .disablePlugins(PlayLayoutPlugin))
```

**Comment by mkurz** [comment]
This can't work because you set `PlayKeys.akkaHttpScala3Artifacts` to `true` but you keep using Akka HTTP 10.2 (by enabling the `PlayScala` plugin) which does not have Scala 3 artifacts. What is your goal here? To use Scala 3? Then you don't have to do anything special. Please take a look at
* https://www.playframework.com/documentation/2.9.x/Scala3Migration and
* https://www.playframework.com/documentation/2.9.x/ScalaAkka#Updating-Akka-version

**Comment by mfirry** [comment]
Thanks @mkurz I thought if I have `.disablePlugins(PlayLayoutPlugin))` I need to put `.enablePlugins(PlayScala)`

**Comment by mfirry** [comment]
Sorry, mine was a question: if I do not want to use the Play Layout... is the PlayScala plugin needed?

**Comment by mkurz** [comment]
If you want to use Play Scala in a "normal way", then yes the PlayScala plugin is still needed, see:
https://www.playframework.com/documentation/latest/Anatomy#Default-sbt-layout

**Comment by mfirry** [comment]
Ok then it's not possible as of now to use that and Scala 3, correct?

**Comment by mkurz** [comment]
It is possible with Play 2.9, please take a look at

* https://github.com/playframework/playframework/releases/tag/2.9.0-RC2
* https://www.playframework.com/documentation/2.9.x/Highlights29

Just use Play 2.9.0-RC3 for now, I will work hard to push out the 2.9.0 final asap.

**Comment by mfirry** [comment]
I meant, it's not possible if I want to use Default-sbt-layout

**Comment by mkurz** [comment]
It should be possible, using Scala 3 has nothing to do which layout (Play Layout or sbt default layout) to use. This a different things not interfering each other.

**Comment by mfirry** [comment]
I'm confused. You earlier seemed to state that _"by enabling the PlayScala plugin (...) which does not have Scala 3 artifacts"_. 
`PlayScala` plugin is needed though to be able to disable `PlayLayoutPlugin`, or am I gettin this wrong?

**Comment by mkurz** [comment]
I think there was a misunderstanding: I wrote

> but you **keep using Akka HTTP 10.2** (by enabling the `PlayScala` plugin)

the point here is **you keep using Akka HTTP 10.2**. Look at the `libraryDependencies` in your initial post, you do not include akka-http in that list. However when you enable the `PlayScala` plugin it will automagically include a dependency to 

```
"com.typesafe.akka" %% "akka-http-core" % "10.2.10"
```

to your `libraryDependencies`. But akka http 10.2 does not have Scala 3 artifacts yet. Now, to be 100% exact what will be really  included is:

```
("com.typesafe.akka" %% "akka-http-core" % "10.2.10").cross(CrossVersion.for3Use2_13)
```

Let me tell you, if you want to use Scala 3, just run
```
sbt new playframework/play-scala-seed.g8
```
and set the Scala version to 3.3.1.
This sets up a project you can use, which does run with Scala 3. 
I recommend you read through
* https://www.playframework.com/documentation/2.9.x/Highlights29
* and specially: https://www.playframework.com/documentation/2.9.x/General#How-Play-Deals-with-Akkas-License-Change

If you want to use Pekko then just use Play version 3.3.0-M3 for now, it is very close to release and api's don't change  anymore. Just watch this repository for releases in should come in the next days.

**Comment by mfirry** [comment]
Ok thanks so much.

Adding 
`val akkaHTTPVersion = "10.5.0"` and the explicit dependency `"com.typesafe.akka" %% "akka-http-core" % akkaHTTPVersion` seemed to have solved the issue.

It'd be super great to have a g8 template that also asks to have default sbt layout.
Thanks!
