### ISSUE TITLE
[Play 2.9 RC2] Cannot integrate swagger-ui

### ISSUE THREAD

**Issue by devinjz** [playframework/playframework#12041]
### Play Version

2.9.0-RC2

### Operating System

windows

### JDK

Java 17

### Expected Behavior

Add `"org.webjars" % "swagger-ui" % "4.17.1"` to the libraryDependencies in the build.sbt.
In the previous 2.8.x, sbt run can generate the "web-modules" which includes the files in the jar in the folder "target\web\".

### Actual Behavior

After upgrading to 2.9.0-RC2, the "web-modules" is missing. It will affect the swagger functionality.

I can reproduce it based on the [helloworld project](https://github.com/playframework/play-samples/tree/2.9.x/play-scala-hello-world-tutorial).

Add the dependency to build.sbt.

![image](https://github.com/playframework/playframework/assets/10953505/008776d9-ec5d-4de3-b7d1-24f73143d72d)

2.8.x can work. 
![image](https://github.com/playframework/playframework/assets/10953505/6a92fd6f-7c80-4ed5-a696-c4bfb09f308a)

2.9.0-RC2 cannot work.
![image](https://github.com/playframework/playframework/assets/10953505/d0c19c98-8ab9-47aa-9f05-0255f29f8bed)

**Comment by mkurz** [comment]
Thanks, seems there is something going on with webjars...

**Comment by mkurz** [comment]
Sorry I can not reproduce your problem by using https://github.com/playframework/play-samples/tree/2.9.x/play-scala-hello-world-tutorial

Please try yourself, I copied the project and set up this repo: https://github.com/mkurz/play-12041 with [two branches](https://github.com/mkurz/play-12041/branches/all):
* `play29` of course uses Play 2.9.0-RC3 (you used RC2 but that should not matter)
* `play28` just adds one commit to switch to Play 2.8.20

For both branches a `target/web/web-modules` folder is generated, I removed the `target` folder between runs.
Play 2.9:
```
target/
└── web
    └── web-modules
        └── main
            └── webjars
                └── lib
                    └── swagger-ui
                        ├── favicon-16x16.png
                        ├── favicon-32x32.png
                        ├── index.css
                        ├── index.css.gz
                        ├── index.html
                        ├── index.html.gz
                        ├── oauth2-redirect.html
                        ├── oauth2-redirect.html.gz
                        ├── swagger-initializer.js
                        ├── swagger-initializer.js.gz
                        ├── swagger-ui-bundle.js
                        ├── swagger-ui-bundle.js.gz
                        ├── swagger-ui-bundle.js.map
                        ├── swagger-ui.css
                        ├── swagger-ui.css.gz
                        ├── swagger-ui.css.map
                        ├── swagger-ui-es-bundle-core.js
                        ├── swagger-ui-es-bundle-core.js.gz
                        ├── swagger-ui-es-bundle-core.js.map
                        ├── swagger-ui-es-bundle.js
                        ├── swagger-ui-es-bundle.js.gz
                        ├── swagger-ui-es-bundle.js.map
                        ├── swagger-ui.js
                        ├── swagger-ui.js.gz
                        ├── swagger-ui.js.map
                        ├── swagger-ui-standalone-preset.js
                        ├── swagger-ui-standalone-preset.js.gz
                        └── swagger-ui-standalone-preset.js.map
```

Play 2.8:
```
target/
└── web
    └── web-modules
        ├── main
        │   └── webjars
        │       └── lib
        │           └── swagger-ui
        │               ├── favicon-16x16.png
        │               ├── favicon-32x32.png
        │               ├── index.css
        │               ├── index.css.gz
        │               ├── index.html
        │               ├── index.html.gz
        │               ├── oauth2-redirect.html
        │               ├── oauth2-redirect.html.gz
        │               ├── swagger-initializer.js
        │               ├── swagger-initializer.js.gz
        │               ├── swagger-ui-bundle.js
        │               ├── swagger-ui-bundle.js.gz
        │               ├── swagger-ui-bundle.js.map
        │               ├── swagger-ui.css
        │               ├── swagger-ui.css.gz
        │               ├── swagger-ui.css.map
        │               ├── swagger-ui-es-bundle-core.js
        │               ├── swagger-ui-es-bundle-core.js.gz
        │               ├── swagger-ui-es-bundle-core.js.map
        │               ├── swagger-ui-es-bundle.js
        │               ├── swagger-ui-es-bundle.js.gz
        │               ├── swagger-ui-es-bundle.js.map
        │               ├── swagger-ui.js
        │               ├── swagger-ui.js.gz
        │               ├── swagger-ui.js.map
        │               ├── swagger-ui-standalone-preset.js
        │               ├── swagger-ui-standalone-preset.js.gz
        │               └── swagger-ui-standalone-preset.js.map
        └── webjars-main.cache
```
Both contain the exact same files, except 2.8 still had `webjars-main.cache`, but that caching gone in newer sbt-web releases, but for this issue this is not relevant anyway.

**Comment by mkurz** [comment]
So you are using Windows, how to you run Play? From the IDE (like Intellij) or from the command line?
Do you have npm and/or node installed locally?
Can you please show me what
```
$ node --version
$ npm --version
```

prints? Thanks!

**Comment by mkurz** [comment]
Please forget the npm/node thing, since this is not required to extract webjars, I was on the wrong path here.
Right now I think this has to do because you use Windows. You have other OS to test your project with?

**Comment by devinjz** [comment]
Yes. I am using intellij sbt shell based on windows OS. I can test mac later.

**Comment by devinjz** [comment]
Mac can work. It seems to be windows specific issue (no matter IDE or cmd).

**Comment by mkurz** [comment]
I can reproduce this. This is a bug introduced in webjars-locator-core version 0.39 via https://github.com/webjars/webjars-locator-core/pull/28
Play 2.8.20 still uses webjars-locator-core 0.36 via sbt-web 1.4.4:
* https://github.com/playframework/playframework/blob/2.8.x/project/Dependencies.scala#L219
* https://github.com/sbt/sbt-web/blob/1.4.4/build.sbt#L12

I provided a fix here: https://github.com/webjars/webjars-locator-core/pull/119

I can confirm my patch fixes this issue, tried on a Windows machine myself.

**Comment by mkurz** [comment]
@devinjz Please add
```sbt
dependencyOverrides += "org.webjars" % "webjars-locator-core" % "0.54"
```
to your `project/plugins.sbt` file and let me know if it is working.
Thanks!
