### ISSUE TITLE
CSRF token is not generated in DEV

### ISSUE THREAD

**Issue by mahadi-hossain** [playframework/playframework#12198]
### Play Version

2.9.0-RC3, 3.0.0

### API

Scala

### Operating System
```
Linux  5.15.0-88-generic #98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### JDK

openjdk version "11.0.20.1" 

### Expected Behavior

1. will produce csrf token 
2. will check csrf token

### Actual Behavior

1. CSRF.getToken does not generate the token in the dev mood (production mood not tested)
2. csrf token is not checked when I send a post request from curl/postman. 
3. In dev mood if I enable the csrf token filter in the application.conf, nothing happens. And produce duplicate filter in 
the logging 

### Reproducible Test Case
**controller**
```scala
package controllers

import javax.inject._
import play.api._
import play.api.mvc._
import play.filters.csrf.CSRF

@Singleton
class HomeController @Inject()(val controllerComponents: ControllerComponents) extends BaseController {
 
  def post() = Action(parse.json) { implicit request =>
    
    Ok("") // not checking the csrf token 
  }

}
```
**routes**

```
POST	/post			     controllers.HomeController.post()

# Map static resources from the /public folder to the /assets URL path
GET     /assets/*file               controllers.Assets.versioned(path="/public", file: Asset)
```
**application.conf**
```
play.filters.enabled += "play.filters.csrf.CSRFFilter"
```

**duplicate csrf filter on run logging-**

```
2023-11-13 13:45:01 INFO  p.a.http.HttpErrorHandlerExceptions  Registering exception handler: guice-provision-exception-handler
2023-11-13 13:45:02 INFO  play.api.http.EnabledFilters  Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter
    play.filters.csrf.CSRFFilter
2023-11-13 13:45:02 INFO  play.api.Play  Application started (Dev) (no global state)
```

**Comment by mkurz** [comment]
The CSRFFilter is enabled automatically in Play, you do **not** need to enable it with `play.filters.enabled += "play.filters.csrf.CSRFFilter"`, please remove that. See https://www.playframework.com/documentation/3.0.x/Filters#Default-Filters

How do yo call your `/post` route? From a twirl view? With curl? You need to send generate a csrf token or cookie somehow before and send that to this route so Play knows about it.

**Comment by mahadi-hossain** [comment]
1. Without `play.filters.enabled += "play.filters.csrf.CSRFFilter"` is also not generated. That is why I added that in application.conf.
2. I used postman for calling the "/post". In the previous versions of play I did not encounter such thing.

**Comment by mahadi-hossain** [comment]
The main issue is crsf token is not checked by the application.

**Comment by mkurz** [comment]
Can you please provide me the exact curl command you run, including the `-v` verbose flag? Thanks!

**Comment by mkurz** [comment]
And you say in Play 2.8 it behaved differently?

**Comment by mahadi-hossain** [comment]
```
curl -X POST -H "Content-Type: application/json" -d '{"name": "John Doe", "age": 30, "city": "New York"}' http://127.0.0.1:9000/post -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:9000...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 9000 (#0)
> POST /post HTTP/1.1
> Host: 127.0.0.1:9000
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 51
> 
* upload completely sent off: 51 out of 51 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< X-Frame-Options: DENY
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Permitted-Cross-Domain-Policies: master-only
< Date: Mon, 13 Nov 2023 08:26:24 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 4
< 
* Connection #0 to host 127.0.0.1 left intact

```

**Comment by mahadi-hossain** [comment]
> And you say in Play 2.8 it behaved differently?
yes,  that would return a 401 (If I am not wrong)

**Comment by mkurz** [comment]
I am pretty sure everything is ok. Please read the [docs](https://www.playframework.com/documentation/3.0.x/ScalaCsrf):
>  Play will require a CSRF check when all of the following are true:
> 
> The request method is not `GET`, `HEAD` or `OPTIONS`.
> The request has one or more `Cookie` or `Authorization` headers.
> The CORS filter is not configured to trust the request’s origin.

Your curl command does not have a cookie nor a `Authorization` header.
When I
1. add `--cookie "USER_TOKEN=Yes"` to your curl command *or*
2. add a header `-H "Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l"`

then I get a `403 Forbidden` response. Also the Play app now logs:
```
2023-11-13 12:35:25 WARN  play.filters.CSRF  [CSRF] Check failed because no token found in headers for /post
```

I also tested with Play 2.8.21 and it has the exact same behaviour. If no cookie and no `Authorization` header gets send then it reponds with 200 OK.
I also checked
```
git difftool 2.8.21..2.9.0 web/play-filters-helpers/src/main/scala/play/filters/csrf/
git difftool 2.8.21..2.9.0 web/play-filters-helpers/src/main/java/play/filters/csrf/
```
and there are no relevant changes that would change the behaviour.

I am pretty sure everything is ok.

**Comment by mahadi-hossain** [comment]
Thanks a lot for figuring out my understanding gap about the "Aditional Cookie part" for so long.  I am very sorry for wasting your time.
