### ISSUE TITLE
`playUpdateSecret` should not blindly write in first line

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#12200]
Running `playUpdateSecret` always write to first line in app conf, e.g.

```
play.http.secret.key="..."
# https://www.playframework.com/documentation/latest/Configuration
```

This is a bit annoying IMHO, I think it should take care of comments `#` and add it's value after the first non `#` line (also include an empty line.

**Comment by janani-reddy9** [comment]
Hi @mkurz, I'm a newbie to OSS and this is the first issue I am looking at. Sharing my view on this one.

At times, some people will separate the comments by a new line and then specify some more comments, like below,

```
#comment-1
#comment-2

#comment-3
key1=value1
```

In this scenario, where do we need to add the generated http key? In the line-3(inplace of empty line) or line-5(in place of key1=value1)

To simplify this, why not to add the key at the end of the file?

**Comment by mkurz** [comment]
> To simplify this, can we not add the key at the end of the file?

Yeah we can do that, it's probably the sanest thing to do. Would you like to provide a pull request?

**Comment by janani-reddy9** [comment]
Yes, I was checking on how to add the secret key in middle. I will raise PR with relevant changes.
