### ISSUE TITLE
[Feature] Add option to disable Javascript routers

### ISSUE THREAD

**Issue by PromanSEW** [playframework/playframework#12262]
I did not found in [documentation](https://www.playframework.com/documentation/3.0.x/ScalaJavascriptRouting) how to turn off generation of JavaScript routers
It would be nice to have that, for decreasing of unused generated code.
Example: REST client (`PlayService`) without web interface, so JavaScript routers will never be used here.

**Comment by PromanSEW** [comment]
Fun fact: there is no Java equivalent for `ScalaJavascriptRouting` page

**Comment by ihostage** [comment]
> I did not found in [documentation](https://www.playframework.com/documentation/3.0.x/ScalaJavascriptRouting) how to turn off generation of JavaScript routers It would be nice to have that, for decreasing of unused generated code. Example: REST client (`PlayService`) without web interface, so JavaScript routers will never be used here.

Hi, Roman! 👋  You are right, it's not possible to turn off right now. But I caught the same thoughts about this opportunity while adding Gradle support  and I agree it would be nice to have the related settings. 👍 
Would you be keen to provide a pull request for that feature?

**Comment by PromanSEW** [comment]
Hmm... I realized that `RoutesKeys.generateReverseRouter := false` in `build.sbt` is the one I am looking for.
It disables all reverse routes as I want, nice
So, issue can be closed because this option exists already

**Comment by mkurz** [comment]
Perfect!

**Comment by ihostage** [comment]
> So, issue can be closed because this option exists already

I'm not sure that `generateReverseRouter` settings and subject of this issue is equals 🤔 
@mkurz Can you correct me or can I reopen this issue otherwise? 😄

**Comment by mkurz** [comment]
Yes it is no 100% what the original request was, but the problem was solved for Roman.
Anyway, we can re-open to have a separate config to disable javascript routes.

**Comment by PromanSEW** [comment]
I am working on PR for this

**Comment by henricook** [comment]
@PromanSEW Would you mind telling me how to disable this in 3.0.2 please? It sounds like it might save some unused code generation in my purely Scala Play project? I didn't see a docs update, please forgive me if you've already documented this somewhere

**Comment by mkurz** [comment]
@henricook 

```sbt
generateJsReverseRouter := false
```
in `build.sbt` (Fully qualified: `play.sbt.routes.RoutesKeys.generateJsReverseRouter`).
