### ISSUE TITLE
The link for Zenexity has been broken in Play Philosophy page

### ISSUE THREAD

**Issue by dongxuwang** [playframework/playframework#12295]
See the very beginning of this page **now [Zengularity](https://zengularity.com/en)** -> https://www.playframework.com/documentation/3.0.x/Philosophy

**Comment by mkurz** [comment]
Thanks! They got acquired a couple of years ago, seems they took the website offline meanwhile: https://www.cambonpartners.com/en/transactions/none-none-80

Let's link to their GitHub org instead:
- #12328
