### ISSUE TITLE
The link for guiding user to source in document is broken

### ISSUE THREAD

**Issue by dongxuwang** [playframework/playframework#12293]
For example: in this page https://www.playframework.com/documentation/3.0.x/ScalaHome

At the bottom of above page, the [here](https://github.com/playframework/playframework/edit/3.0.x/documentation/manual/working/scalaGuide/main/ScalaHome.md) link has been 404 

<img width="982" alt="Screenshot 2024-01-11 at 23 23 49" src="https://github.com/playframework/playframework/assets/4261431/5aa699f9-b51f-4ba3-b8e5-0de0341032a2">

**Comment by mkurz** [comment]
That's because we do not have a 3.0.x branch yet. This will fix itself as soon as we branch of 3.0.x

**Comment by mkurz** [comment]
We have a `3.0.x` branch now and the link is working now.
