### ISSUE TITLE
Comprehensive List of Config Options: Missing or Hard to Find

### ISSUE THREAD

**Issue by ConnorDoyle** [playframework/playframework#1231]
Is there a section of the current release docs similar to the [list of configuration options for version 1.2.3](http://www.playframework.com/documentation/1.2.3/configuration)?

If it does exist, this should be featured more prominently in the documentation on playframework.com.

**Comment by jroper** [comment]
Play now puts all its config options in `reference.conf` files, and includes them in the documentation.
