### ISSUE TITLE
Loss `Result` attributes by any modification

### ISSUE THREAD

**Issue by hertg** [playframework/playframework#12333]
### Play Version

`3.0.0`

### API

Java

### JDK

```
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Corretto-21.0.1.12.1 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.1.12.1 (build 21.0.1+12-LTS, mixed mode, sharing)
```

### Expected Behavior

Adding cookies to an `Http.Result` should not clear the `Http.Result` attrs.

### Actual Behavior

I found this unexpected side effect of the `withCookies()` method by implementing something similar to this inside a [Filter](https://www.playframework.com/documentation/2.8.x/Filters):

```java
// pseudo-code
return next.apply(rh)
        .thenApply(result -> {
            if (result.attrs().getOptional(CREATE_FOO_COOKIE).isPresent()) {
                // this has the unintended side-effect of clearing the result attrs
                return result.withCookies(fooCookie);
            }
            return result;
        })
        .thenApply(result -> {
            // the attrs will be empty if the foo cookie above was created
            if (result.attrs().getOptional(CREATE_BAR_COOKIE).isPresent()) {
                return result.withCookies(barCookie);
            }
            return result;
        });
```

### Workaround

My workaround will probably be to simply do this in a single step, and adding all cookies at once. Since I do not need the attrs at a later stage, this will be sufficient for me. However, I do feel that this is unexpected behavior and a loss of the result's `attrs` may impact anyone who relies on those in their action composition.

### Fix

I expect this to be fairly easy to fix. The LOC at fault is https://github.com/playframework/playframework/blob/a77da07e0b2d594af5d538c38803ba2466e20517/core/play/src/main/java/play/mvc/Result.java#L474

This calls the constructor here: https://github.com/playframework/playframework/blob/a77da07e0b2d594af5d538c38803ba2466e20517/core/play/src/main/java/play/mvc/Result.java#L82-L84

When it should probably call this constructor directly: https://github.com/playframework/playframework/blob/a77da07e0b2d594af5d538c38803ba2466e20517/core/play/src/main/java/play/mvc/Result.java#L58-L71

**Comment by ihostage** [comment]
Hi, @hertg! Good catch, you are right! 👍 
Do you want to create a pull request to fix that?

**Comment by hertg** [comment]
@ihostage I could probably prepare a PR tomorrow or later this week
@mkurz unless you are already active on it? I'm assuming the list you posted is non-exhaustive?

**Comment by mkurz** [comment]
@hertg I am not working on this, happy if you provide a PR. Not 100% sure if there are more places which need to be fixed, I _think_ my list should cover all (?) but better if you check if the constructor
https://github.com/playframework/playframework/blob/a77da07e0b2d594af5d538c38803ba2466e20517/core/play/src/main/java/play/mvc/Result.java#L82-L84
gets called somewhere else.
Thanks!
