### ISSUE TITLE
Documentation spelling fix

### ISSUE THREAD

**Issue by muskangupta-tc** [playframework/playframework#12362]
In Action.scala file the documentation for refine method says
```diff
< This is the main method than an ActionRefiner has to implement
> This is the main method that an ActionRefiner has to implement
```

**Comment by mkurz** [comment]
@muskangupta-tc Can you please provide a pull request? Thanks!

**Comment by muskangupta-tc** [comment]
Sure, will create a pull request from my personal github account

**Comment by pckrishnadas88** [comment]
@mkurz kindly review this PR https://github.com/playframework/playframework/pull/12532
