### ISSUE TITLE
play 2.9 is trying to fetch guice-6.0.0-no_aop jar, caused not found error

### ISSUE THREAD

**Issue by JayZYan** [playframework/playframework#12521]
```
[error] (update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/com/google/inject/guice/6.0.0/guice-6.0.0-no_aop.jar: not found: https://repo1.maven.org/maven2/com/google/inject/guice/6.0.0/guice-6.0.0-no_aop.jar
[error] (ssExtractDependencies) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/com/google/inject/guice/6.0.0/guice-6.0.0-no_aop.jar: not found: https://repo1.maven.org/maven2/com/google/inject/guice/6.0.0/guice-6.0.0-no_aop.jar

```

play 2.9 is trying to fetch guice-6.0.0-no_aop jar,, but https://repo1.maven.org/maven2/com/google/inject/guice/6.0.0/
the no_aop version has already been removed. Do we know if any dependency is introducing this guice-6.0.0-no_aop jar?

Thanks!

### Play Version

2.9.2

### API

Java 17
Scala 2.13.13

### Operating System

mac

**Comment by mkurz** [comment]
Also, please do not double post, I deleted the discussion #12522

**Comment by mkurz** [comment]
@JayZYan can you provide more information? If not, I will close this issue soon.

**Comment by mkurz** [comment]
@JayZYa I am closing this issue because you did not replay for 3 weeks. If you can provide more details, like I described above, please let us now by adding a new comment below, thanks!

**Comment by anitha1729** [comment]
Hi mkurz, I am getting the this error when I tried with Play 2.9.2, sbt 1.9.6, scala 2.13.13 and jdk 17 and "com.google.inject" % "guice" % "6.0.0". Could you please help me fix this

**Comment by mkurz** [comment]
Can you post your `build.sbt` and `project/plugins.sbt`? And/or run `sbt dependencyTree` so we find out which dependencies get pull in?
