### ISSUE TITLE
[UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item]

### ISSUE THREAD

**Issue by anitha1729** [playframework/playframework#12634]
I took your config from [above's comment](https://github.com/playframework/playframework/issues/12630#issuecomment-2105219211) and made it work with Play 2.9.2. I uploaded the result in to this repo https://github.com/mkurz/playframework-12630

You can see what I changed here: https://github.com/mkurz/playframework-12630/commit/ea5dcc10efa431a278ace100280568fc84797aeb

This is 100% not a bug in Play but you just messed up the config.

_Originally posted by @mkurz in https://github.com/playframework/playframework/issues/12630#issuecomment-2107125749_

**Comment by anitha1729** [comment]
I am still getting the same error even after making the changes you suggested

**Comment by mkurz** [comment]
Please do not open new issues all the time, the discussion is here:
- #12631
