### ISSUE TITLE
Gitandpio

### ISSUE THREAD

**Issue by GitPio** [playframework/playframework#12645]
https://github.com/playframework/playframework/blob/a456b49882baf8b51bd44fe0afdc0f4560d02389/core/play/src/main/scala/play/api/mvc/Action.scala#L572piotrjansch00@gmail.comcore/play-integration-test/src/it/scala/play/it/http/parsingdeferred/DeferredBodyParsin
![Screenshot_20240523_014053_Android System](https://github.com/playframework/playframework/assets/112967579/1fe5273b-f767-4763-8275-aed5865d1de6)
gSpec.scala

**Comment by mkurz** [comment]
Seems like spam.
