### ISSUE TITLE
Sbt dist command creates invalid .bat file under Windows

### ISSUE THREAD

**Issue by nemoo** [playframework/playframework#12642]
### Play Version
3.0.2

### API
Scala
### Operating System
Windows 11
### JDK
21
### Expected Behavior
`sbt dist` should create a distribution of play framework that can be run under Windows. Expectation is that the `myapp.bat` file found under `target/universal/myapp-1.0-SNAPSHOT.zip` can be executed under Windows after unpacking the .zip file. 
### Actual Behavior
Running the myapp.bat file under windows fails with this error: 
```
C:\temp\test> .\myapp.bat
Die eingegebene Zeile ist zu lang.
Syntaxfehler.
```
#### myapp.bat
It seems that myapp.bat contains a line that is too long. And it seems to be this line (replaced the rest of the line with ..., in the rest of the line about 160 .jar files are referenced in my example): 
`set "APP_CLASSPATH=%APP_LIB_DIR%\..\conf\;%APP_LIB_DIR%\myapp.myapp-1.0-SNAPSHOT-sans-externalized.jar;.......`

As a result, the play framework distribution cannot be run under windows.

**Comment by mkurz** [comment]
This is not directly a problem in Play but [sbt-native-packager](https://github.com/sbt/sbt-native-packager/), please see:
- https://sbt-native-packager.readthedocs.io/en/latest/recipes/longclasspath.html (https://github.com/sbt/sbt-native-packager/issues/1327)
- https://github.com/sbt/sbt-native-packager/issues/1466

**Comment by nemoo** [comment]
For me, adding ` .enablePlugins(LauncherJarPlugin)` to my build.sbt fixed this problem. This was also the solution proposed in https://sbt-native-packager.readthedocs.io/en/latest/recipes/longclasspath.html
