### ISSUE TITLE
Add `.sdkmanrc` for better dev experience

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#12714]
Thinking about adding a `.sdkmanrc` so devs using sdkman automatically switch to the correct jdk:
- https://sdkman.io/usage#env
- Best experience is with `sdkman_auto_env=true` in sdk man config, which makes sdkman automatically switch jdks when entering a directory in the shell

So for main branch we can set jdk to 17 tem, in 3.0.x and 2.9.x to 11 tem.

There is only one "problem" I can think of:
- You can not set major versions like `17-tem`, but the version has top be exact like `17.0.11-tem`. So to stay up to date, I propose to write a simple GitHub action that runs `sdk list java | grep tem`, parses the most right column, filters by major version (e.g. starts with `"17."`, sorts those versions correctly and then opens a pull request against each branch to update the `.sdkmanrc` file.

Not high priority, but I was thinking about this for longer already.

**Comment by ihostage** [comment]
> There is only one "problem" I can think of:

Personally, I use `librca` instead of `tem` 😄

**Comment by ihostage** [comment]
As opposited to Temurin (https://github.com/adoptium/adoptium-support/issues/962), Liberica has ARM compatible builds.

And also, Liberica is recommended by Spring https://spring.io/quickstart
> We recommend [BellSoft Liberica JDK](https://bell-sw.com/pages/downloads/#/java-17-lts) version 17.

**Comment by mkurz** [comment]
Hmm.. Temurin does have arm support... (?) See:
- https://adoptium.net/de/temurin/releases/?arch=aarch64

 I am not an expert in cpu architecture, but AFAIK [`aarch64` is basically arm,](https://en.wikipedia.org/wiki/AArch64) I did quite some research in
- https://github.com/VirtusLab/scala-cli/issues/1714 and
- https://github.com/coursier/coursier/issues/2636#issuecomment-1363491391

Also I am running Linux on aarch64 (Apple M1 Pro), and Temurin Java 8 to 21 works without any problems, also fast (and it is native, not some emulation or something).
You are on macOS right, so I think you can use the aarch64 builds or not?

So thinking about the `.sdkmanrc` thing, I think maybe we should just add it to `.gitignore`, so everyone can just set up his/her own JDK. So you prefer librca, I use tem. And not just this... I use some "special mkurz" approach for sdkman... So I use symlinks that always point to the latest java 8, java 11, ... releases. So this is what my `~/.sdkman/candidates/java/` folder looks like:
```
11.0.23-tem
11-tem -> 11.0.23-tem
17.0.11-tem
17-tem -> 17.0.11-tem
21.0.3-tem
21-tem -> 21.0.3-tem
22.1.0.r17-grl
8.0.412-tem
8-tem -> 8.0.412-tem
current -> 11-tem
```
So you see I have symlinks like `17-tem` that points to `17.0.11-tem`. So whenever I have to enter a JDK installation folder, e.g. in IntelliJ, I juse use `~/.sdkman/candidates/java/17-tem` and I do not have to change the JDK version anymore in the software, because it will always point to the latest release. Only when I upgrade java in sdkman I afterwards have to run e..g.:
```sh
cd ~/.sdkman/candidates/java/
rm 17-tem; ln -s 17.0.11-tem 17-tem
```
And all software that uses java 17 is up to date with latest JDK 17.

This is also supported by sdkman, it does read the symlinks:
```sh
$ sdk list java | grep tem 
 Temurin       |     | 22.0.1       | tem     |            | 22.0.1-tem          
               |     | 21           | tem     | local only | 21-tem              
               |     | 21.0.3       | tem     | installed  | 21.0.3-tem          
               |     | 17           | tem     | local only | 17-tem              
               |     | 17.0.11      | tem     | installed  | 17.0.11-tem         
               | >>> | 11           | tem     | local only | 11-tem              
               |     | 11.0.23      | tem     | installed  | 11.0.23-tem         
               |     | 8            | tem     | local only | 8-tem               
               |     | 8.0.412      | tem     | installed  | 8.0.412-tem   
```

So I can use sdkman to switch to latest jdk 17 with running:
```
sdk use java 17-tem
```

So this is also why I do not put `java=17.0.11-tem` in my `.sdkmanrc` config files, but `java=17-tem` (for the Play `main` branch) or `java=11-tem` (for Play `3.0.x` branch), etc. (btw I use git worktrees to checkout different Play branches in different folders).

Unfortunately `.sdkmanrc` does not support a fallback mechanism :cry: so we could but just put:
```
java=17-tem` # for mkurz
java=17.0.11-librca` # for ihostage
java=17.0.11-tem # for every other dev ;)
```
This does not work...

So I think we should just put `.sdkmanrc` in `.gitignore` so everyone can just set up his/her own jdk. Also so we don't have to write a GitHub action to stay up to date with latest jdk in `.sdkmanrc`...

**Comment by ihostage** [comment]
> So I think we should just put `.sdkmanrc` in `.gitignore` so everyone can just set up his/her own jdk. Also so we don't have to write a GitHub action to stay up to date with latest jdk in `.sdkmanrc`...

Yep, I agree. It's good variant 👍

**Comment by mkurz** [comment]
Updated `.gitignore` in
- #12730
