### ISSUE TITLE
URL is not decoding properly after play upgrade from 2.6.x to 2.8.x

### ISSUE THREAD

**Issue by ilapavuluri** [playframework/playframework#12823]
### Play Version

2.8

### API

Java

### Operating System

Windows

### JDK

1.8

mine is a java application which runs on play framework, in the routes file I have below route for rest endpoints:
```
GET /api/$factory<[^\(\)]+>('$id<[a-z\:0-9]+>') 
```

I can call the above rest end point like below 
http://localhost:8080/bui/cr('400001')

as well as below (by encoding)

http://localhost:8080/bui/cr(%27400001%27)

Both are working without any issue in Play 2.6, after play upgrade to 2.8 only http://localhost:8080/bui/cr('400001') is only working for the other one  I am getting below error:
```
Catched Client Error: (Resource not found by Assets controller) ; Code (404) 
```
Why it is not able to decode? what is broken after play upgrade?

Appreciate any help on this, this became a blocker for my upgrade.

**Comment by ilapavuluri** [comment]
@mkurz, appreciate your help on this.

**Comment by mkurz** [comment]
If you want to accept both `'` and `%27` you can use following workaround:
```
GET /api/$factory<[^\(\)]+>($foo1<'|%27>$id<[a-z\:0-9]+>$foo2<'|%27>)  controllers.HomeController.foo(factory, id, foo1, foo2)
```

where `foo1` and `foo2` are unused variables (you also have to add them in your actions methods params).

There is an old request to support regex in routes without identifier:
- #3346

which, if implemented, would avoid having the dummy variables `foo1´ and `foo2`.

**Comment by ilapavuluri** [comment]
Thank you so much @mkurz, yes mine is 2.6.15 before 2.6.22 only hence it was working.

I tried the above workaround it worked for me, is it possible to avoid dummy variables or support for decoding in future releases?

Thanks
Ashok.

**Comment by mkurz** [comment]
> I tried the above workaround it worked for me, is it possible to avoid dummy variables or support for decoding in future releases?

Like said, this is tracked in

 - #3346

seems someone tried to fix that already but stopped working on it. One point that needs to be solved is reverse routing, see https://github.com/playframework/playframework/pull/4255#issuecomment-94052843
Looks there was not much demand for this feature and I can not remember someone complaining yet.

Not sure, but you may be able to solve this with pathbindle as well: https://www.playframework.com/documentation/3.0.x/RequestBinders
