### ISSUE TITLE
Assets controller are not isolated in sub-projects configuration

### ISSUE THREAD

**Issue by julien-lafont** [playframework/playframework#1336]
I've just discovered a strange behavior which happens in sub-project configuration.

The `main` play project aggregates two play sub-projects `fo` and `bo`.
Each sub-project define a custom Asset controller, as explained in the documentation (http://www.playframework.com/documentation/2.1.x/SBTSubProjects)

```
package controllers.fo

import play.api._
import play.api.mvc._

object Application extends Controller {
  def index = Action Ok("bo")
}

object Assets extends controllers.AssetsBuilder
```

and it's own route file

```
GET     /                           controllers.fo.Application.index
GET     /assets/*file               controllers.fo.Assets.at(path="/public", file)
```

There is also a root router

```
-> /bo                              bo.Routes
-> /fo                              fo.Routes
```

For now, all is fine.

Then i've added a file with the **same name** in `/module/fo/public` and `/module/bo/public`.

**When I call /fo/assets/test.txt  and /bo/assets/test.txt, only one file is returned randomly**
If i create the file /public/test.txt (root project), this file will always be returned.

Is it a bug (public folders should be isolated) or a feature (public folders are shared)?

(You can reproduce this behavior in this project https://github.com/studiodev/play2-assets-subprojects-bug `sbt test`)

**Comment by lcamilo15** [comment]
I just started writing about solving this type of issues with play 2.4.x hopefully this helps http://luiscamilo.com/2015/07/27/play-framework-2-4-x-modulesub-project-assets/
