### ISSUE TITLE
[2.X] AspectJ in Load-Time

### ISSUE THREAD

**Issue by rfranco** [playframework/playframework#1372]
I have problem to run Play with AspectJ 
I use sbt-aspectj plugin, it works with compiler-time but if i try to run with Load-Time, it doesn't work

because it doesn't add javaOptions when execute run command also it doesn't add javaOptions to start.sh in dist command.

``` scala
  val aop = Project("aop", file("aop"))
    .settings(buildSettings: _ *)
    .settings(aspectjSettings: _*)
    .settings(
    compileOnly in Aspectj := true,
    products in Compile <++= products in Aspectj
  )
  val web = play.Project(name = "web", path = file("web"))
    .settings(buildSettings: _ *)
    .settings(aspectjSettings: _*)
    .settings(
    fork in run := true,
    javaOptions in run <++= weaverOptions in Aspectj
  ).dependsOn(aop)
```

**Comment by toggm** [comment]
you can use the following command line option to integrate aspectjweaver in play framework 2.3.8 in dev mode:
activator run  -J-javaagent:<path_to_aspect>/aspectjweaver-1.8.4.jar
