### ISSUE TITLE
JavaGuide2 - "Using Fixtures" & Yaml.load

### ISSUE THREAD

**Issue by richardbroersma** [playframework/playframework#1380]
In the section:

<h2>Using Fixtures to write more complicated tests</h2>

yaml is used to populate this in-memory database using the following code:

<strong></span><span class="typ">Ebean</span><span class="pun">.</span><span class="pln">save</span><span class="pun">((</span><span class="typ">List</span><span class="pun">)</span><span class="pln"> </span><span class="typ">Yaml</span><span class="pun">.</span><span class="pln">load</span><span class="pun">(</span><span class="str">"test-data.yml"</span><span class="pun">));</span></strong>

It'd be helpful if the following imports were also mentioned in JavaGuide2:

<strong>import com.avaje.ebean._;
import play.libs._;</strong>

Otherwise the resulting test gives complication errors.

**Comment by vnikiten01** [comment]
Hey guys, I was going through the guide and fell into this problem.  Would love to fix the documentation, just cant find it.  jroper, can you guide me to the right area.

**Comment by jroper** [comment]
This tutorial was remove from Play 2.3, you can find it here: https://github.com/playframework/playframework/blob/2.2.x/documentation/manual/javaGuide/tutorials/zentasks/JavaGuide2.md
