### ISSUE TITLE
Websocket clients can disconnect ungracefully, don't notify application

### ISSUE THREAD

**Issue by andrewconner** [playframework/playframework#1388]
When using a long-lived websocket connection, clients frequently are able to disconnect uncleanly. Typically this happens (on desktop and mobile) when they lose wifi signal, close their laptop lid, power off abruptly, etc.

Play doesn't seem to get any notification this has happened, so the server believes the client is still connected. Taken from the Play examples:

``` scala
    def index = WebSocket.using[String] { request => 
      val in = Iteratee.foreach[String](println).mapDone { _ =>
        println("Disconnected")
      }
      val out = Enumerator("Hello!")
      (in, out)
    }
```

You'd expect that the mapDone would be called in all cases. However, in unclean disconnect cases, it's not called.

To reproduce, you'll likely need two computers (or virtual machines). Run Play! on one, and connect with the other. If you disconnect by closing the browser, leaving the page, etc, everything works as expected. Reconnect, then cause the client to abruptly disconnect (`kill -9` does not work here) — my favorite is using a virtual machine and simulating pulling the power.

"Disconnected" _never_ hits the console. This is more than a bookkeeping issue, because it can cause resources to be left open, and for the server to try to push things down the socket.

I realize that much of this may be hitting limits of netty. However, what are our options here? Our current solution is an application-level ping, with a cleanup actor. Works alright for websockets, but not so well for something like a chunked response.

**Comment by david04** [comment]
Is this now available in the latest Play versions? (the read and idle timeouts on websockets)
Thanks!

**Comment by TheChifer** [comment]
Is this something available with Play2.5?

**Comment by pauldraper** [comment]
> There are open tickets for read/idle timeouts, these would apply to both WebSockets and ordinary requests.

@jroper, I cannot find these issues https://github.com/playframework/playframework/issues?utf8=%E2%9C%93&q=is%3Aissue+idle
