### ISSUE TITLE
Support for dependency injection of plugins

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#1389]
It would be great if Play had a programmatic way to provide instances of plugins that can be used with a dependency injection framework such as Guice.

Ideally, we should be able to instantiate anything that implements `Plugin` via a DI framework and give it to Play to treat like a normal plugin. This way Play can manage the life cycle for you and also make it available to other plugins via the `use[PluginName]` syntax.

Many third-party plugins are designed to use instances of other plugins implemented by your application. SecureSocial is one plugin that uses this pattern extensively. In these situations, we usually want to use constructor injection to provide our custom implementation of the base class, and instantiate that via Guice, but this is impossible to do with the current architecture. The best workaround I know is to have a wrapper Play plugin which gets the injector from the global and instantiates and delegates to the implementation class.

**Comment by benmccann** [comment]
Is this issue resolved with Play 2.4?

**Comment by jroper** [comment]
Yes.
