### ISSUE TITLE
Shared dependency-free reverse router across multiple projects

### ISSUE THREAD

**Issue by andrewconner** [playframework/playframework#1390]
We use multi-projects with split routes files. We would like to use the Play reverse router in all of the projects. i.e., from ServiceA, call `serviceB.routes.SomeController.someAction(id, name)` (where ServiceA and ServiceB are *not* dependent on each other). Specifically, we only want to share the reverse routes, not the controllers or other classes. 

Relevant group discussions:
https://groups.google.com/forum/#!topic/play-framework/h9Iab7SvOIY (this is the most thourough explaining the current issue, and the use case)
https://groups.google.com/forum/#!topic/play-framework/VwwM3K9mGDo
and eventually, a "solution"
https://groups.google.com/forum/#!topic/play-framework/RXzAXNLd_Jc

The solution, however, just builds it's own reverse router, instead of using Play's. That works, but means developers have to maintain their own routes parser, and doesn't work immediately with custom types. It would be really nice to be able to export the reverse routes, by themselves, into a common project.

This is most definitely possible (since it's simply a mapping from a method call with parameters to URL), but is not compatible with the reverse routing classes Play generates (which *are* dependent on the controllers).

Along with dependency-free reverse route classes, the ability to easily export them into a project would make multi-projects a lot more accessible for more developers.

**Comment by chych** [comment]
+1 
jroper says : I don't think we (the Play core devs) will have the time to implement this for 2.3
please create an article to explain how to to do a custom implementation in scala and Java.

I'm a newbie on JAVA i don't know very well yet the framework, so help us.

**Comment by benmccann** [comment]
There have been lots of good changes to the routing lately that should help with this. I've just submitted another PR that will help quite a bit with making progress towards implementing this. https://github.com/playframework/playframework/pull/4006

**Comment by jroper** [comment]
See attached pull request #4131 that implements this.

**Comment by jroper** [comment]
For those interested in what the final result looks like, it's really simple:

```scala
lazy val common: Project = (project in file("common"))
  .enablePlugins(PlayScala)
  .settings(
    aggregateReverseRoutes := Seq(api, web)
  )

lazy val api = (project in file("api"))
  .enablePlugins(PlayScala)
  .dependsOn(common)

lazy val web = (project in file("web"))
  .enablePlugins(PlayScala)
  .dependsOn(common)
```

That's all you need in your `build.sbt` to get this to work.

**Comment by andrewconner** [comment]
Wonderful, thanks a ton James.

**Comment by godenji** [comment]
Awesome, @jroper thanks!

Question: can this functionality be extended into javascript reverse routes? One thing I dislike about the current 2.3.x js router is the fact that it generates the routes at runtime (i.e. on every single request). 

I currently print the routes to static file(s) at compile time, but it would be nice to leave behind my hacks and have a framework supported version, all the more so given the rise of Scala.js ;-)

**Comment by jroper** [comment]
@godenji this functionality isn't really related to javascript reverse routes, generating static javascript reverse routers would be completely unrelated.

There are two things that you may want for javascript reverse routes:

1. A new routes generator, that delegates to the existing routes generators, but also generates a javascript file containing all the Javascript reverse routes.
2. Something that aggregated all routes files in a project into one compilation unit, so that you can get the paths right, and output only one javascript router, instead of outputting one per routes file.  Currently all routes files are compiled separately, but a refactor of the routes plugin could mean they could be compiled together.
