### ISSUE TITLE
Anorm with MySQL Boolean

### ISSUE THREAD

**Issue by AntonFagerberg** [playframework/playframework#1405]
Retrieving a Boolean value from MySQL does not work with Anorm.

``` SQL
SQL(
  """
  |SELECT
  | TRUE
  """.stripMargin
).as(
  scalar[Boolean] single
)
```

This results in:

```
play.api.Application$$anon$1: Execution exception[[RuntimeException: TypeDoesNotMatch(Cannot convert 1:class java.lang.Long to Boolean for column ColumnName(.TRUE,Some(TRUE)))]]
```

Same thing with FALSE which turns in to 0:class java.lang.Long to Boolean...

MySQL represents TRUE and FALSE as TINYINT(1) and TINYINT(0) and it should be possible to parse them as boolean values as in the code above.

**Comment by dportabella** [comment]
this is not working `implicit def intToBool: Column[Bool]` (error: "only classes can have declared but undefined members"), and I don't see a solution on the documentation: https://www.playframework.com/documentation/2.6.x/ScalaAnorm
Can you please explain how to achieve this?

**Comment by cchantep** [comment]
Please use [SO](https://stackoverflow.com/questions/tagged/anorm) to ask questions/for help (this tracker is for confirmed issue). Best regards.
