### ISSUE TITLE
HTTP cookie's max-age attribute gets transformed into expires attribute

### ISSUE THREAD

**Issue by varju** [playframework/playframework#1414]
Cookies.encode uses Netty's CookieEncoder to convert a cookie to an HTTP header.  Since we aren't setting a version attribute on the DefaultCookie, Netty automatically transforms the maxAge attribute into an expires attribute based on the current server time.  This can cause the cookie to be rejected by the client's browser if their date is not set correctly.

I looked briefly at calling nc.setVersion(1), which did allow maxAge to be passed through verbatim, but this caused other problems with my application, possibly because we're using httpOnly cookies.

Problem seen with Play 2.1.1, but I expect it affects all versions based on my reading of the Netty code.

**Comment by cchantep** [comment]
As there is nothing new there, I guess this can be closed (and a new ticket raised if similar issue found for recent Play versions). Best regards.
