### ISSUE TITLE
Play project scala version for scala library dependencies

### ISSUE THREAD

**Issue by huntc** [playframework/playframework#1459]
Ensure that scala library runtime dependencies e.g. the reflection library, are scoped to "provided" within Play. The sbt Play plugin should be the provider of these libraries using the project's scalar version, not the Play library scala version.

**Comment by wsargent** [comment]
This looks simple enough:

https://github.com/playframework/playframework/blob/master/framework/project/Dependencies.scala#L161

**Comment by PromanSEW** [comment]
Can be closed because of #8887
