### ISSUE TITLE
Play 2.1.1 HTTP 413 trigger

### ISSUE THREAD

**Issue by linde12** [playframework/playframework#1473]
Hello.

I noticed that if you cross the 100kb default by a few bytes you'll get a "HTTP/1.1 413 Request Entity Too Large" however, when i cross it with 105947(maybe this value is just for me) bytes i get a "HTTP/1.1 200 OK" again - which is bad since then all my validation returns false(because body is null).

I am assuming this is a bug?

Reproduce code:

```
    public static Result test() {
      Form form = Form.form.bindFromRequest();
      ObjectNode result = Json.newObject();

      // Return w/e the user sent as json
      return ok(Json.toJson(form.get()));
    }
```

**Comment by peter-fu** [comment]
I can confirm this issue is still valid for Play 2.2.3.

Some test results

Case 1:
content length: 103445
response: 413

Case 2:
content length: 140568
body is null in controller

_I haven't tested the issue for other versions of Play._

**Comment by patrik7** [comment]
Getting this on Play 2.4.2

with application/x-www-form-urlencoded
and Content-Length:104245

@jroper any chance this was fixed in a newer version, but it's not mentioned in this thread?

**Comment by patrik7** [comment]
Maybe a clarification is in order. I don't need a method to find out that body is too big. I want to be able to submit a form that has large body and process it on the server side - ideally without getting 413 screen of death.

**Comment by hirohanin** [comment]
> Maybe a clarification is in order. I don't need a method to find out that body is too big. I want to be able to submit a form that has large body and process it on the server side - ideally without getting 413 screen of death.

were you able to figure out a workaround
