### ISSUE TITLE
Form processing with limited "allowedFields" list

### ISSUE THREAD

**Issue by Skyr** [playframework/playframework#1610]
When limiting the editable fields by passing an allowedFields parameter to Form.bindFromRequest(..), all other data stored in an object will be cleared, resulting e.g. in validation errors if an excluded field is marked as @required.

Background: In my application, users may change only a subset of the data they initially entered in a form (a longer description of what I'm trying to do and my problem is [on the Google Play Framework group](https://groups.google.com/forum/#!topic/play-framework/LYvSRJktjnQ)). Limiting the fields using allowedFields results in the problem described above. Unfortunately the documentation of the parameter is rather brief, so I can only suspect that I'm trying to solve my problem with the right tool...

**Comment by mkurz** [comment]
> The actual change that should happen here is that validation is limited to just the required fields. This is an improvement, a PR would be welcomed.

Will be fixed in 2.6:
https://www.playframework.com/documentation/2.6.x/JavaForms#Partial-form-validation-via-groups
