### ISSUE TITLE
playframework killed automatically where I can find the log files or error message?

### ISSUE THREAD

**Issue by thinksource** [playframework/playframework#1616]
Actually, I posted this at mail list, but no response since now(https://groups.google.com/forum/#!topic/play-framework/-oV0vbibM2o), so I repost here. 

My server is Ubuntu 13.04 x64
My play is play-2.1.4-RC2
My java version is:
root@wemet:~# java -version
java version "1.7.0_25"
OpenJDK Runtime Environment (IcedTea 2.3.10) (7u25-2.3.10-1ubuntu0.13.04.2)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)
I install scala by copy the last version of scala zip file and set $SCALA_HOME & $PATH

root@wemet:~# echo $SCALA_HOME
/opt/scala
root@wemet:~# echo $PATH
/usr/local/rvm/gems/ruby-2.0.0-p247/bin:/usr/local/rvm/gems/ruby-2.0.0-p247@glob
al/bin:/usr/local/rvm/rubies/ruby-2.0.0-p247/bin:/usr/local/rvm/bin:/usr/local/s
bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/ho
me/web/play:/opt/scala/bin

but my play killed automatically(both java and scala version they all killed automatically):

root@wemet:/home/web# play new wemet
       _            _
 _ __ | | __ _ _  _| |
| '_ | |/ _' | || |_|
|  **/|_|__**|__ (_)
|_|            |__/

play! 2.1.4-RC2 (using Java 1.7.0_25 and Scala 2.10.0), http://www.playframework
.org

The new application will be created in /home/web/wemet

What is the application name? [wemet]

> wemet

Which template do you want to use for this new application?

  1             - Create a simple Scala application
  2             - Create a simple Java application

> 2
> OK, application wemet is created.

Have fun!

root@wemet:/home/web# cd wemet
root@wemet:/home/web/wemet# play run
[info] Loading project definition from /home/web/wemet/project
[info] Set current project to wemet (in build file:/home/web/wemet/)

Killed
root@wemet:/home/web/wemet# play
[info] Loading project definition from /home/web/wemet/project
[info] Set current project to wemet (in build file:/home/web/wemet/)
       _            _
 _ __ | | __ _ _  _| |
| '_ | |/ _' | || |_|
|  **/|_|__**|__ (_)
|_|            |__/

play! 2.1.4-RC2 (using Java 1.7.0_25 and Scala 2.10.0), http://www.playframework
.org

> Type "help play" or "license" for more information.
> Type "exit" or use Ctrl+D to leave this console.

[wemet] $ run

[info] Updating {file:/home/web/wemet/}wemet...
[info] Resolving org.hibernate.javax.persistence#hibernate-jpa-2.0-api;1.0.1.Fin

[info] Done updating.
--- (Running the application from SBT, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 4 Scala sources and 2 Java sources to /home/web/wemet/target/sc
ala-2.10/classes...
Killed

I hope the playframework can print or log the error why it process killed.

**Comment by mharisce** [comment]
The following discussion might help you. https://groups.google.com/forum/#!topic/play-framework/ftKR6SM-Yrs 

I have the similar issue. What i did is i added a script to check and restart my service if it is down. and I have added to cron job to run that script every minute.
