### ISSUE TITLE
Better filtering for static assets

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#1629]
There are a few things we could tidy up in the Assets controller. None of these are serious problems, but they're not that great either.
- Using File.isDirectory doesn't do anything, because we're not serving from the filesystem. Better to look for paths ending in "/".
- File.getCanonicalPath.startsWith allows paths to escape the enclosing directory temporarily, so long as they reenter it again. e.g. Assets.at(path="/public", file) accepts paths like "../public/myfile.png".
- Encoded slashes (%2f) are treated like path separators. Better if they were forbidden entirely.

Here's a commit that we could use as a base to fix up some of this stuff: https://github.com/richdougherty/playframework/commit/490b1fcc912fe10c4559aec052c0e90726400f16

**Comment by marcospereira** [comment]
All these problems are now solved. So closing.
