### ISSUE TITLE
Deprecate play.Logger

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#1669]
We've had lots of trouble with play.Logger and have removed it from our codebase. I'd love to see it deprecated to save others the same time-consuming troubleshooting that we've faced.

The problems we've faced:
- The logs all just show "application" instead of the actual class and package name (for all logs with %logger% in the formatting string)
- Can't turn on logging of line numbers (though this is resource intensive it can be helpful in development or temporarily in production for diagnosing some problems)
- LogEntries, the hosted service we use to collect our logs, does not handle it well and makes our stack traces much less useful
- Our codebase was complicated by the use of multiple logging APIs. E.g. we don't want a dependency on Play in our data access library, so need to use slf4j directly there

The biggest reason Play provides its own logging API is to make the log messages lazily evaluated. But this only works in Scala, since Java doesn't support lazy parameters. So keeping the Scala logger makes a lot of sense, but in Java it just causes problems and doesn't solve any. The only benefit in Java is the brevity of calling it, but there are many other better solutions to that don't have the drawbacks listed above (we use Lombok for this).

**Comment by mkurz** [comment]
#5194 got merged which moves logback out to a module so it is replaceable.
Is this good enough so we can close this issue or does somebody still want `play.Logger` to be deprecated/removed?
/cc @benmccann

**Comment by wsargent** [comment]
@mkurz Play.logger is still terrible for different reasons.  It doesn't support marker API, for example.

**Comment by dotta** [comment]
+1 for deprecating both the Java and Scala Logger API. It doesn't really deliver any value over SLF4J. Note that Scala by-name arguments are quite costly (a lambda is created at every call), to the point that I fear evaluating the log message could be faster in many cases than creating the lambda. For Scala, [scala-logging](https://github.com/typesafehub/scala-logging) may be a much better/performant option.

**Comment by mkurz** [comment]
Maybe this is something we could tackle for the 2.6 release.

**Comment by almothafar** [comment]
I believe it would be nice to get this soon, I was about to suggest this :) 
Is it still planned for 2.6.x? no?

**Comment by richdougherty** [comment]
This change is probably too big to go into our stable branch, but I'll tag it 2.7.0 so we can consider it for the next version. cc @benmccann.

**Comment by mkurz** [comment]
Closing because addressed by #7727
