### ISSUE TITLE
Missing @documentation css & jquery min in first play app

### ISSUE THREAD

**Issue by magegu** [playframework/playframework#1685]
I just installed play via homebrew  ... 

$ play new blogapp
[...]
play! 2.1.4 (using Java 1.7.0_12-ea and Scala 2.10.0), http://www.playframework.org
[..]

$ cd blogapp
$ sbt
[blogapp] $ play
[blogapp] $ run
[...]
--- (Running the application from SBT, auto-reloading is enabled) ---
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
(Server started, use Ctrl+D to stop and go back to the console...)
[info] play - Application started (Dev)

When i point my chrome to my play application the welcome site will pop up but no css will be rendered. My Chrome console will print the following: 

GET http://localhost:9000/@documentation/resources/style/main.css 404 (Not Found) localhost/:21
GET http://localhost:9000/assets/javascripts/jquery.min.map 404 (Not Found)

**Comment by TRANTANKHOA** [comment]
Can anyone tell me where to find this file: /@documentation/resources/style/main.css. I just want to figure out how play manages these resources.
