### ISSUE TITLE
Try to use application ActorSystem in dev mode

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#1693]
The default user ExecutionContext comes from the application's ActorSystem. However, when running in dev mode, request can come in before the application is available or when the application is unavailable entirely due to compilation errors. Therefore in dev mode there is a fallback ActorSystem that is used.

However this ActorSystem and its ExecutionContext is used even when an application is available. Play should prefer the application ActorSystem once it becomes available. This could be done by making an application-aware ExecutionContext that waits for an application to start and uses the application ExecutionContext if possible.

Another thing to think about is how to shutdown the fallback ActorSystem once we finish in dev mode, see #1453.

**Comment by megazord** [comment]
Was this fixed by #4250?
