### ISSUE TITLE
Improve Java Json performance

### ISSUE THREAD

**Issue by huntc** [playframework/playframework#1732]
From @jroper:

> I don't think this impacts the techempower benchmark, but in Java, when we receive a JSON body, we decode it to the Scala JsValue, then reencode it as a String, and then decode it to JsonNode.  Obviously, this is just stupid, there's no reason it needs to be like that, it's just that we always use the any content Scala parser first, which saves a bit of effort, but not enough to justify such poor performance.  We should write a purpose built Java parser that deserialises direct to the required Java types.

> For sending a JSON body, it's not as bad, but we could probably save a few buffer copies because we currently serialise it to a String, which means at least one copy on String creation, and then we apply a codec to transform it to a byte array, which means another buffer copy.  Jackson should be able to serialise it directly to a byte array with our desired encoding.  Though, the length of the JSON being returned is tiny, so I don't expect this to have a significant impact, maybe a few percent.

> In fact we actually do the same thing with Scala, so maybe we could also improve Scala performance there.  Though the difference with Scala is we're converting from JsValue, which is not a native type to Jackson, and we convert simply by calling toString which just does String building.  We'd have to implement custom Jackson serialisers in order to avoid the buffer copies in Scala.  Since the Java API uses the Jackson JSONNode type, and Jackson serialisers know about this type, there should be a lot more performance to be gained out of optimising the Java here than the Scala.

**Comment by benmccann** [comment]
It sounds like this has been partially addressed according to @jroper's comment on https://github.com/playframework/playframework/issues/3784#issuecomment-69134846. Perhaps @jroper or someone else would like to weigh in as to whether this bug should be closed or there is still additional work that can be done to improve the situation

**Comment by gmethvin** [comment]
This might be part of a bigger project to make it possible to write body parsers in Java.

Ideally we'd want to have a Java body parser that creates `JsonNode`s directly, using the Jackson streaming API for best performance. You should be able to easily create a body parser to parse any type supported by the `ObjectMapper`, without having to go through `JsValue`.

**Comment by benmccann** [comment]
Whether the body parser is written in Java or Scala it does seem like you'd want to be able to go straight from the HTTP input  to Jackson without having an intermediate step of going through JsValue
