### ISSUE TITLE
TLS: Client Certificate support

### ISSUE THREAD

**Issue by bblfish** [playframework/playframework#1760]
Client certificates can be very user friendly if [one does it right](http://webid.info/) . 
The following patch allows the server to be very intelligent about when to ask
certificates, allowing to give the browser user an optimal user experience

By adding the method to the `RequestHeader` the method  ` def certs(required:Boolean): Future[Seq[Certificate]]` the server can do all the following efficiently:

 * be able to tell what action the browser is asking to apply to which resource (`GET`, `POST`, `PUT`,...) , verify the
  ACLs for that resource, and then ask for identity ( it is usually rude to ask for an identity for public resources - but that is who most TLS servers are set up by default )
 * be able to tell what kind of browser is on the other side, and potentially if the browser has a client certificate ( we are looking to standardise a header for this )
 * That one renegotiation the TLS connection in `NEED` or `WANT` mode depending on the browser
 * That one be able to not have to rely on CA signed certificates by using [WebID over TLS](https://dvcs.w3.org/hg/WebID/raw-file/tip/spec/index.html) authentication for example

**Comment by bblfish** [comment]
For the moment it seems I am stuck on using client certificates in Play 2.3 as it is no longer possible since 2.4 to access the netty connection.

There is some thinking going on about this akka. See: [Implement TLS session renegotiation support for client certification authentication](https://github.com/akka/akka/issues/18351).

Given that Netty allows this feature it would be useful to see if Play 2.5 could allow one to make this work. One way of doing this would be to allow the client to send message to the netty actor that is in charge of the connection. 

Also note that the whole issue of ClientCertificate Authentication is not as closed as it may have seemed to be. There is a discussion [on the HTTP-WG](https://lists.w3.org/Archives/Public/ietf-http-wg/2015JulSep/) on how to tie in TLS 1.3 and HTTP2 as the demand for it is much larger than they initially expected.

We are also exploring ways to use public key crypto and HTTP Authentication, but those have other limitations.... Having a server that allows both would enable clear comparison.

**Comment by wsargent** [comment]
Looks like this is covered by `SSLEngineProvider` https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/server/api/SSLEngineProvider.scala which will expose client certificates -- https://github.com/typesafehub/activator-play-tls-example/blob/master/app/https/CustomSSLEngineProvider.scala
