### ISSUE TITLE
[Play 2.2] "play idea" creates not working source mapping in target

### ISSUE THREAD

**Issue by q42jaap** [playframework/playframework#1784]
The folder /target/scala-2.10/src_managed/main contains two files:
- routes_reverseRouting.scala
- routes_routing.scala.

However, the "idea" play command generates the following source folders:
- app
- target\scala-2.10\src_managed\main\controllers
- target\scala-2.10\src_managed\main\someotherdir
- target\scala-2.10\src_managed\main\views
- conf

So the routes_\* files in "main" are missing in the compiler paths. This makes IntelliJ show hint errors and false code problems.

I'm fixing this by hand by deleting the source mapping for the individual folders and add a source mapping for the whole main folder.

**Comment by AlphaJuliettOmega** [comment]
Is there a Documentation page on how to mark Play folders correctly for Intellisense?

There's a project I'm working on with 11 modules

The workaround @crfeliz mentioned isn't viable anymore because the structure has changed since 2013
