### ISSUE TITLE
Websocket hijacking protection

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#1788]
Websockets don't implement the same origin policy that is used in HTML for protection against hijacking.  Possible protection:
- Check the Origin header of the WebSocket handshake request on the server, since that header was designed to protect the server against attacker-initiated cross-site connections of victim browsers!
- Use session-individual random tokens (like CSRF-Tokens) on the handshake request and verify them on the server.

Taken from http://www.christian-schneider.net/CrossSiteWebSocketHijacking.html

**Comment by wsargent** [comment]
Should take another stab at this in 2.6.x.  This is included in the sample code:

https://github.com/playframework/play-scala-chatroom-example/blob/master/app/controllers/HomeController.scala

```
class HomeController @Inject()(implicit actorSystem: ActorSystem,
                               mat: Materializer,
                               executionContext: ExecutionContext)
  extends Controller {

  private type WSMessage = String

  private val logger = org.slf4j.LoggerFactory.getLogger(this.getClass)

  private implicit val logging = Logging(actorSystem.eventStream, logger.getName)

  // chat room many clients -> merge hub -> broadcasthub -> many clients
  private val (chatSink, chatSource) = {

    // Don't log MergeHub$ProducerFailed as error if the client disconnects.
    // recoverWithRetries -1 is essentially "recoverWith"
    val source = MergeHub.source[WSMessage]
      .log("source")
      .recoverWithRetries(-1, { case _: Exception ⇒ Source.empty })

    val sink = BroadcastHub.sink[WSMessage]
    source.toMat(sink)(Keep.both).run()
  }

  private val userFlow: Flow[WSMessage, WSMessage, _] = {
     Flow.fromSinkAndSource(chatSink, chatSource).log("userFlow")
  }

  def index: Action[AnyContent] = Action { implicit request =>
    val url = routes.HomeController.chat().webSocketURL()
    Ok(views.html.index(url))
  }

  def chat: WebSocket = {
    WebSocket.acceptOrResult[WSMessage, WSMessage] {
      case rh if sameOriginCheck(rh) =>
        Future.successful(userFlow).map { flow =>
          Right(flow)
        }.recover {
          case e: Exception =>
            val msg = "Cannot create websocket"
            logger.error(msg, e)
            val result = InternalServerError(msg)
            Left(result)
        }

      case rejected =>
        logger.error(s"Request ${rejected} failed same origin check")
        Future.successful {
          Left(Forbidden("forbidden"))
        }
    }
  }

  /**
   * Checks that the WebSocket comes from the same origin.  This is necessary to protect
   * against Cross-Site WebSocket Hijacking as WebSocket does not implement Same Origin Policy.
   *
   * See https://tools.ietf.org/html/rfc6455#section-1.3 and
   * http://blog.dewhurstsecurity.com/2013/08/30/security-testing-html5-websockets.html
   */
  private def sameOriginCheck(rh: RequestHeader): Boolean = {
    rh.headers.get("Origin") match {
      case Some(originValue) if originMatches(originValue) =>
        logger.debug(s"originCheck: originValue = $originValue")
        true

      case Some(badOrigin) =>
        logger.error(s"originCheck: rejecting request because Origin header value ${badOrigin} is not in the same origin")
        false

      case None =>
        logger.error("originCheck: rejecting request because no Origin header found")
        false
    }
  }

  /**
   * Returns true if the value of the Origin header contains an acceptable value.
   */
  private def originMatches(origin: String): Boolean = {
    try {
      val url = new URL(origin)
      url.getHost == "localhost" &&
        (url.getPort match { case 9000 | 19001 => true; case _ => false })
    } catch {
      case e: Exception => false
    }
  }

}
```

**Comment by wsargent** [comment]
This is fixed with the SecurityHeadersFilter using a `Content-Security-Policy: default-src: self` -- a `connect-src: self` is roughly the same as a Origin check.  So fixed by https://github.com/playframework/playframework/pull/7023

**Comment by wsargent** [comment]
Okay, so this isn't quite as clean -- `self` is not equivalent because "ws" or "wss" are different policies.

```
class ContentSecurityPolicyFilter @Inject()(implicit ec: ExecutionContext) extends EssentialFilter {

  override def apply(next: EssentialAction): EssentialAction = EssentialAction { request: RequestHeader =>
    val webSocketUrl = routes.HomeController.chat().webSocketURL()(request)
    next(request).map { result =>
      result.withHeaders("Content-Security-Policy" -> s"connect-src 'self' $webSocketUrl")
    }
  }
}
```

**Comment by lol768** [comment]
>This is fixed with the SecurityHeadersFilter using a Content-Security-Policy: default-src: self -- a connect-src: self is roughly the same as a Origin check

Can you explain how you came to this conclusion, @wsargent ?

It's still early morning for me and I'm due another coffee, so possible I'm missing something.. but my understanding was that:

* A `Content-Security-Policy` only applies to the document for which they it was issued for in the HTTP response headers
* As a result, an attaker with a third-party `evil.com` site will _not_ have any such CSP set, so the browser will happily connect to any `wss://`/`ws://` URL when passed to the JavaScript `WebSocket` constructor.
*  I don't believe that browsers will check CSP headers during an Upgrade request.
* As a result, there isn't any protection against cross-origin WebSocket hijacking.

I still think there needs to be an `Origin` check.

**Comment by wsargent** [comment]
Things like https://outlandish.com/blog/configure-content-security-policy-with-websockets-and-express/ for example.

**Comment by lol768** [comment]
I think that locks down _outgoing_ connections.
