### ISSUE TITLE
Implement "graceful shutdown"

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#1789]
From https://groups.google.com/forum/#!msg/play-framework/GDDuIZ1YqiM/Yer0wAELz-0J

I would love to know how to make Play do a graceful shutdown where it goes into "lame duck" mode for some configurable amount of time where it continues processing existing requests, but not accepting new ones. Then it can shut down knowing that it is not in the middle of processing user requests. Not sure if this should be handled at the app server, or load balancer, or how they interact here. Maybe this is not directly Play's responsibility, but even in that case it would be great to document that you should look at configuring it in your load balancer and a link to the relevant documentation for one popular load balancer such as nginx or haproxy.

**Comment by edouardKaiser** [comment]
Sorry for resurrecting that topic but the framework has evolved, the Global `onStop` is deprecated, and now the shutdown is managed through the `ApplicationLifecycle`. I was wondering if someone had any clean solution to handle properly SIGTERM in a Play application?

What I would call a "proper handling" in our case is:
1. Wait for current requests to finish
2. Refuse any new incoming requests
3. Cancel any task scheduled on the Akka actor system scheduler
4. Shutdown database connections

2 is doable through the filter example provided by @jroper,  3 and 4 are easy to manage with the `addStopHook` on ApplicationLifecycle. 

The first point is the real issue for us: How do we make the "shutdown execution" to sleep for a certain amount of time to give time to the current requests to finish in case of a SIGTERM ?

We tried to hack it by putting a sleep in the last "stop hook" added through `addStopHook` (will be the first executed), but the entire application is freezing when that happens.
 
Context: An application running in a Kubernetes cluster. When scaling down, Kubernetes sends a SIGTERM to let the application shutdown gracefully and wait a certain amount of time before removing it. With a Play Framework app, a SIGTERM ends the application immediately and current requests don't have time to finish. It's hard to update without downtime.

Modern schedulers (like Mesos Marathon or Kubernetes) are relying on the fact that application can handle a graceful shutdown when SIGTERM is sent.

Thank you all for your help,

**Comment by wsargent** [comment]
@edouardKaiser the standard behavior of a process killed with SIGTERM is to exit with code 143, so I'm not sure where this expectation came from -- if the scheduler can do something other than send a signal, it would be far more useful.  Also see for reference:

* https://github.com/playframework/playframework/issues/5933 
* https://github.com/sbt/sbt-native-packager/issues/770

**Comment by benmccann** [comment]
Could Play add support for installing a signal listener that would allow the user to handle in a manner of their choosing?

**Comment by wsargent** [comment]
This is typically handled through shutdown hooks at the application level: http://www.oracle.com/technetwork/java/javase/signals-139944.html

**Comment by edouardKaiser** [comment]
SIGTERM is the normal way to politely ask a program to terminate. A polite way to terminate would be to wait for current requests to finish but not accept new one. Just like when a shop is closing, it finishes serving current customers but can't accept new one :)  

It doesn't mean necessarily that the program has to stop immediately (contrary to SIGKILL for immediate termination). 

Of course, the interpretation of "graceful shutdown" is very open and will change depending the application.

This is why schedulers rely on SIGTERM.

**Comment by edouardKaiser** [comment]
So no one ?

Regarding our situation, I think we'll have to intercept the SIGTERM signal from the scheduler.
The application won't receive any new requests (because scheduler removes the app from the balancer after sending SIGTERM), but it wont die immediately (that means it will finish processing the current requests).

Then later, the scheduler will SIGKILL the app. It's not an issue because it's not used anymore, but it won't be a clean shut down.

By doing this, we should avoid any downtime during a deployment, at the price of a dirty shutdown.

**Comment by pauldraper** [comment]
> The point is, if you're going to have a let it fail approach to your server design (highly recommended), then you don't need fancy graceful shutdown logic. Just exit .. that's what the operator wanted.

Naturally, you will never eliminate all failures: network outage, power loss, disk corruption, etc. But designing for failure doesn't mean adding failure where it can be avoided.

Yes, a user can just reload the page, or resubmit the payment info. But it's nice to avoid it as much as possible.

> people might decided to use kill -9 for other reasons

There's SIGTERM and SIGKILL. I suppose someone can always use the latter, but that's their choice. Most system try SIGTERM first, for a graceful shutdown.

**Comment by edouardKaiser** [comment]
If some people are interested: We swallow SIGTERM, and delay a manual shutdown of the application through the Akka scheduler. The method `isShuttingDown` is used by our `HealthCheckController`. As soon as it's set to true, our health endpoint does not return 200 anymore, Kubernetes considers the application not healthy, removes it behind the service/balancer. Meanwhile it can still finish serving the current requests. And it will stop the Play app when reaching the `STOP_DELAY`.

Works like a charm, shutdown properly hikari pool, Logback... You can adjust `STOP_DELAY` according to your Kubernetes graceful shutdown period. And the delay should of course come from configuration, up to you how you configure your app.
 
```
import scala.concurrent.duration.Duration;
import scala.concurrent.duration.FiniteDuration;

import play.api.Application;
import play.api.Play;

import akka.actor.ActorSystem;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import sun.misc.Signal;

import java.util.concurrent.TimeUnit;
import javax.inject.Inject;
import javax.inject.Provider;
import javax.inject.Singleton;

@Singleton
public class SignalHandler {

  private static final Logger LOG = LoggerFactory.getLogger(SignalHandler.class);

  private static final FiniteDuration STOP_DELAY = Duration.create(40, TimeUnit.SECONDS);

  private volatile boolean isShuttingDown = false;

  @Inject
  SignalHandler(ActorSystem actorSystem, Provider<Application> applicationProvider) {
    Signal.handle(new Signal("TERM"), new sun.misc.SignalHandler() {
      @Override
      public void handle(Signal signal) {
        isShuttingDown = true;
        LOG.info("Termination required, swallowing SIGTERM to allow current requests to finish");
        actorSystem.scheduler().scheduleOnce(STOP_DELAY, () -> {
          Play.stop(applicationProvider.get());
        }, actorSystem.dispatcher());
      }
    });
  }

  public boolean isShuttingDown() {
    return isShuttingDown;
  }

}
```

**Comment by schmitch** [comment]
@edouardKaiser on 2.5 that will not shutdown the `NettyServer`. Actually not a problem in your cause tough. Also you should not call `Play.stop` and instead inject `play.api.inject.DefaultApplicationLifecycle` and call `stop()` on it. `Play.stop` is actually a wrapper for `Application.stop` which is a wrapper for `DefaultApplicationLifecycle.stop()`.
And be aware that `sun.misc.Signal` and might be encapsulated in Future JDK Versions.

**Comment by edouardKaiser** [comment]
Thanks for the information @schmitch!

**Comment by jasongoodwin** [comment]
This was helpful for me working in DC/OS. Thanks guys.

**Comment by PatrickSauts** [comment]
Another way is to provide a different NettyServerProvider
in `application.conf`
```
play.server {
	provider = "com.github.MyNettyServerProvider"
}
```

the provider class in Scala

```
class MyNettyServerProvider extends ServerProvider {
  def createServer(context: ServerProvider.Context) = new MyNettyServer(
    context.config,
    context.appProvider,
    context.stopHook,
    context.actorSystem)(
    context.materializer)
}

class MyNettyServer(config: ServerConfig,
    override val applicationProvider: ApplicationProvider,
    stopHook: () => Future[_],
    override val actorSystem: ActorSystem)(override implicit val materializer: Materializer) extends NettyServer(config, applicationProvider, stopHook, actorSystem )(materializer) {
    private val LOG: Logger = LoggerFactory.getLogger(this.getClass.getName)

  override def stop() {
    LOG.info("Starting stopping")
    HealthCheckService.stopping = true
    //stop my schedulers and else
    foo.stop()
    // Wait for the LB to take the server offline
    Thread.sleep(15000) 
    LOG.info("Stopping Server")
    super.stop()
  }
}
```
