### ISSUE TITLE
Arrays binding issue with form submissions

### ISSUE THREAD

**Issue by synhershko** [playframework/playframework#1829]
We have an html form with:

```
<input type="hidden" name="foo" value="some url">
<input type="hidden" name="foo" value="other url">
```

And we bind it like the docs describe: http://www.playframework.com/documentation/2.0/JavaForms

Our Java class has an array defined:

```
public String[] foo;
```

But doesn't matter what we do there is always only one record added to the array. We go around this by doing:

```
tfim.foo = request().body().asFormUrlEncoded().get("foo");
```

Which works great. Changing to a List doesn't solve the problem, and we did verify the POST request is sent properly.

We are using 2.2.0

**Comment by greenled** [comment]
This "feature" made it to Play 2.4.6 :( Docs should cover this case
