### ISSUE TITLE
CSRF not fully supported for Play/Java?

### ISSUE THREAD

**Issue by brikis98** [playframework/playframework#1855]
The class [csrf.scala](https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala) has a [getToken](https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala#L66) method to read the CSRF token from a `RequestHeader`. However, I can't find any equivalent method for Java users to read the token from a `Context` object.

Similarly, while I see the [CSRF docs for Scala](http://www.playframework.com/documentation/2.2.x/ScalaCsrf), I can't find the equivalent for Java users.

**Comment by jroper** [comment]
Fixed in #4132.
