### ISSUE TITLE
[WS] Add getStream to WSRequest

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#1874]
This would be useful for getting hold of enumerators:

```
def getStream: Future[WSResponse, Enumerator[Array[Byte]]]
```

**Comment by cchantep** [comment]
Seems implemented at https://github.com/playframework/playframework/commit/97c170e1bb59732d332750e7004bf4384b1c2136#diff-de5b238615b352ff9143bbb102be70a3R495
