### ISSUE TITLE
Remove workaround for Specs2/JUnit conflicts

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#1889]
In #1841 I added a workaround for a problem with Specs2 and JUnit. The workaround is not very nice, and probably a bit fragile, so it would be good to reverse it once the [underlying junit-interface](https://github.com/szeiger/junit-interface/issues/30) issue is fixed.

I'm creating this Play issue so we don't forget to remove the workaround once the junit-interface issue is fixed.

**Comment by richdougherty** [comment]
I agree, we should be able to remove this workaround now. I've marked this as community in the hope that someone will help out with the fix. If not, I should eventually get to it for 2.4. :smile: 

To resolve this issue, the change in PR #1841 needs to be reversed. Then the test steps given in the first comment of PR #1841 need to be followed to make sure that the problem still doesn't occur. Once that's been verified, and a PR made, we can close this issue.

**Comment by benmccann** [comment]
@richdougherty PR here: https://github.com/playframework/playframework/pull/3786
