### ISSUE TITLE
WS.post blocking on DNS issues (play-2.2.1 scala]

### ISSUE THREAD

**Issue by oalper** [playframework/playframework#1997]
We are trying to do a basic web service call, and realized that even though it returns a Future, it blocks on DNS lookup, so the whole thing will end up blocking the action if there is a DNS issue. To elaborate this, let's say you have the following code:

val response: Future[Response] = WS.url("http://www.myservice.com/service/").post

response map { r =>
  Ok(r.body)
}

The problem I am getting is, if DNS lookup on myservice.com hangs, it will wait till that DNS lookup times out, and this will happen in the main controller thread, not the future, so you will end up blocking the whole action.

I traced the issue all the way down to NettyAsyncHttpProvider.doConnect, basically this method is trying to create a InetSocketAddress object within the main thread, and that blocks the main thread if you have any DNS issues.

From Play's point of view, this is not really a play problem, but it will end up choking the server and it will run out of threads if this ever happens?

**Comment by wsargent** [comment]
@kybishop FYI Netty async DNS resolution is out in 4.1: http://netty.io/4.1/api/io/netty/resolver/dns/package-summary.html

**Comment by wsargent** [comment]
Closing since this is dependent on AHC 2.1 being on Netty 4.1, and therefore https://github.com/AsyncHttpClient/async-http-client/issues/1161 and https://github.com/AsyncHttpClient/async-http-client/issues/414 are where this needs to happen.

**Comment by schmitch** [comment]
@wsargent actually ahc backported the DNS resolver so it is just blocked by #5895 since the DNS resolver needs an Eventloop
