### ISSUE TITLE
Play ignores missing configuration files, and documentation is confusing

### ISSUE THREAD

**Issue by vnicolici** [playframework/playframework#2007]
I was trying to use multiple configuration files, and according to the documentation at http://www.playframework.com/documentation/2.2.x/Configuration said:

►config.resource specifies a resource name - not a basename, i.e. application and not application.conf

Of course, I read that as:

►config.resource specifies a resource name - not a basename, i.e. **you should** use application and not application.conf

I think that should be rephrased.

Only after losing some time fighting "play.api.UnexpectedException: Unexpected exception[Exception: DB plugin is not registered.]" and noticing that the error doesn't occur when I don't specify a non-default config file I realized that it was not finding a config file at all.

So, instead of giving you a warning that the file does not exist, play silently skips missing config files.

This is a bit annoying.

**Comment by megazord** [comment]
At the master branch, both `Configuration.md` and `ProductionConfiguration.md` are very clear about using the `.conf` extension.

From `Configuration.md`:

>  `config.resource` specifies a resource name including the extension, i.e. `application.conf` and not just `application`

And from `ProductionConfiguration.md`:

> ## Using `-Dconfig.resource`
> 
> This will search for an alternative configuration file in the application classpath (you usually provide these alternative configuration files into your application `conf/` directory before packaging). Play will look into `conf/` so you don't have to add `conf/`.
> 
>    $ /path/to/bin/<project-name> -Dconfig.resource=prod.conf

@jroper, I think you can close this issue.
