### ISSUE TITLE
Windows startup scripts generated by "dist" use too large argument lists

### ISSUE THREAD

**Issue by stefcl** [playframework/playframework#2025]
The following error message is printed in the console when I try to run my app using the generated bat file on windows :

"The input line is too long."

It happens near the final lines when the script is trying to execute the java process. A little debugging shows that the classpath argument is causing the problem, it's like : 

````
java -cp c:\<fullpath>\..\lib\jar1.jar;c:\<fullpath>\..\lib\jar2.jar;c:\<fullpath>\..\lib\jar3.jar
````
With such a syntax, the framework core dependencies coupled with a moderate amount of user libraries can quickly exceed windows maximum command line length which is something between 2k and 8k.

There is a KB article about this problem : 
http://support.microsoft.com/kb/830473

But no real solution, may I suggest you use the following syntax in the generated scripts instead:

````
java -cp c:\<fullpath>\..\lib\*; 
````
? (note the semicolon that prevents wildcard expansion)

**Comment by marcospereira** [comment]
As stated here:

https://github.com/sbt/sbt-native-packager/issues/72#issuecomment-87619120

This is already fixed in sbt-native-packager 1.0.0, which is used by Play 2.4.0. The possible solutions are documented here:

http://www.scala-sbt.org/sbt-native-packager/topics/longclasspath.html
