### ISSUE TITLE
EBean Doesn't Escape Keywords

### ISSUE THREAD

**Issue by JamesBewley** [playframework/playframework#2035]
I'm trying to create a model named "order" but Play generates SQL which doesn't escape the table name (order).

db.default.driver=com.mysql.jdbc.Driver
db.default.url="jdbc:mysql://localhost/order_tracker?characterEncoding=UTF-8&quot;
db.default.user=user
db.default.password="secret"

ebean.default="models.*"

**Comment by richdougherty** [comment]
I'm closing this issue so that we can consolidate similar tickets. Further discussion can happen under #2365.
