### ISSUE TITLE
ForkJoinPool for play.core.Execution.internalContext lacks an uncaught exception handler

### ISSUE THREAD

**Issue by dwhjames** [playframework/playframework#2052]
from `play.core.Execution.internalContext`
```scala
…
      val service = new ForkJoinPool(
        numberOfThreads,
        NamedFjpThreadFactory("play-internal-execution-context"),
        null,
        true)
…
```
Shouldn’t this pool be given a `Thread.UncaughtExceptionHandler` rather than `null`?

**Comment by richdougherty** [comment]
Play now uses Akka to initialise its thread pool. It sets a handler that ignores the error.

If we want different behaviour we may need to raise an issue with the Akka project.

**Comment by wsargent** [comment]
Closing, as the underlying execution is from Akka's default dispatcher:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/core/Execution.scala#L19
