### ISSUE TITLE
Passed locale in custom formatter is wrong 

### ISSUE THREAD

**Issue by mazmaz** [playframework/playframework#2065]
[Play 2.2.1]
I'd like to configure my own DateFormatter to parse and print the date based on my current user's locale. (gregorian for 'en' and jalali for 'fa' users)
I extend SimpleFormatter and everything is fine. But I have a problem, I think the passed locale in my custom formatter is wrong, it always passes me "en" locale that is default and resolved by the header request. In my project I changed the user's locale (by calling changeLang method in controller) and it is set in the user's cookie.
The bigger problem is in printing error messages. When I throw an exception in the case of an invalid date string, it prints the 'en' message whilst other parts of page are being rendered in 'fa'.

I think there exists some kind of bug on play.

**Comment by mkurz** [comment]
See #4945 for additional useful information for this bug.

**Comment by mkurz** [comment]
I would like to get this bug fixed.

Based on [this comment](https://github.com/playframework/playframework/issues/4945#issue-99220991) could someone help me out and tell me what's the best place to set the `ThreadLocal` of `LocaleContextHolder`? Thanks!
/cc @richdougherty @gmethvin @jroper

**Comment by richdougherty** [comment]
Skimming this issue it looks like the fix would be to read the language/locale from the `Http.Context.current()`. The benefit of using the `Http.Context` is that Play automatically manages propagating the `Http.Context` for you.

If you want to propagate your own thread-local state you can do it by using your own `ExecutionContext` that behaves in a similar way to the built-in one.

See:
* https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/libs/concurrent/HttpExecutionContext.java
* https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/libs/concurrent/HttpExecution.java
* https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala#L50

**Comment by mkurz** [comment]
How about removing the `Locale` parameter from the `AnnotationFormatter` and `SimpleFormatter` parse and print methods? It looks like they never worked anyway... Instead we could mention `Http.Context.current().lang()` in the javadoc.

**Comment by mkurz** [comment]
Would be the easiest solution.

**Comment by mkurz** [comment]
I set up #5548 to remove the locale param. Have a look there for more explanation.
