### ISSUE TITLE
No ability to customize the error message for a missing Json read

### ISSUE THREAD

**Issue by bigjason** [playframework/playframework#2119]
Currently there is no way add a custom error message for a missing value.  For example the reader:

```scala
 val userReader: Reads[(String, String, Option[String])] =
    ((__ \ "username").read[String] and
     (__ \ "email").read[String] and
     (__ \ "realName").readNullable[String]).tupled
```

When I call validate on say an empty Json object, I will get back an error with the missing fields error being `"validate.error.missing-path"`.  I asked about this on the mailing list (<https://groups.google.com/d/msg/play-framework/7wKtt8ZjlXs/q7FcLIoGXaAJ>) and have since fleshed out the solution to the following:

```scala
import play.api.libs.json._
import play.api.libs.functional.syntax._
import play.api.data.validation.ValidationError

implicit class JsPathPimps(path: JsPath) extends JsPath {
  def readOrError[T](error: => String)(implicit r: Reads[T]): Reads[T] = new Reads[T] {
    def reads(json: JsValue): JsResult[T] = path.readNullable(r).reads(json) match {
      case JsSuccess(Some(value), _) => JsSuccess(value, path)
      case JsSuccess(None, _)        => JsError((path, ValidationError(error)))
      case err@JsError(_)            => err
    }
  }

  def formatOrError[T](error: => String)(implicit r: Format[T]): OFormat[T] =
    OFormat(readOrError(error), Writes.at(path)(r))
}
```

I would love to have this in the actual library as it seems like a glaring omission to me.  I would be happy to put together a PR that overloads `JsPath.read` (or something similar), but before I put the time in I wanted to be sure that this is something the Play team would be interested in.

**Comment by shanethehat** [comment]
I encountered this restriction recently in 2.5.1, and the supplied solution is still valid. Is this issue still something that would be considered valuable?

**Comment by cchantep** [comment]
See #6517

**Comment by Dziman** [comment]
@cchantep I think #6517 completely not related to this issue

**Comment by JakubKahovec** [comment]
@Dziman is right. #6517 is related to the form validation constraints whereas this issue is related to the Json reads validation. It'd be nice to be able to provide a custom error message. The same is also valid for others like maxLength, minLength, min etc
