### ISSUE TITLE
Add withFile() to Java RequestBuilder

### ISSUE THREAD

**Issue by Desnoo** [playframework/playframework#2125]
Add withFile() to RequestBuilder to help testing file upload

**Comment by benmccann** [comment]
FakeRequest is going away and being updated with RequestBuilder. I'm updating this ticket accordingly

**Comment by megazord** [comment]
Is this issue duplicated with #2289?

**Comment by richdougherty** [comment]
@megazord, I'm not sure if this is a duplicate issue. I'll wait for someone else to comment.

**Comment by mkurz** [comment]
Any news here for the `withFile()` feature?

**Comment by mkurz** [comment]
Is there a workaround?

**Comment by marcospereira** [comment]
@mkurz there is a possible workaround linked here:

https://github.com/playframework/playframework/issues/2289#issuecomment-94978091

It will need some work thought, since it was made for Play 2.2.x.

**Comment by mkurz** [comment]
I saw this. I thought maybe someone has a workaround for 2.4.
Anyway, would be nice to get this in Play core...

**Comment by marcospereira** [comment]
Closing. See discussion at https://github.com/playframework/playframework/pull/5698#issuecomment-198765510.
