### ISSUE TITLE
Tests with FakeApplication run in parallel fail when using both Java and Scala

### ISSUE THREAD

**Issue by bbarkley** [playframework/playframework#2132]
We have run into a case where we have unit tests written in both Java and Scala testing controllers written in their respective languages in the same project. When run in parallel they often fail due to a lack of synchronization across the different Helpers classes.

The Helpers.java has running() synchronize on itself, and Helpers.scala synchronizes on itself. Is there a good reason to keep these separate, or can they be changed to synchronize on a common object?

**Comment by dotta** [comment]
@jroper Isn't this commit https://github.com/playframework/playframework/commit/06c967aae7b1063ededdfce810250d3eef322647 from you fixing this issue?

**Comment by jroper** [comment]
Yep.
