### ISSUE TITLE
Move JavaScript routing docs to live outside Scala docs or create a Java version

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#2167]
The [JavaScript routing docs](http://www.playframework.com/documentation/2.1.1/ScalaJavascriptRouting) are available only for Scala. They aren't really Scala-specific except for a small block of code in the "Router resource" section, so it would be good to move them to a common location so that Java users can see the same docs.

**Comment by benmccann** [comment]
@huntc I'm guessing the JS router isn't going away anytime soon, so we should fix this issue still

**Comment by huntc** [comment]
Yeah, sorry about that.

**Comment by marcospereira** [comment]
See PR #5693.
