### ISSUE TITLE
Improve the Play/Java Result API

### ISSUE THREAD

**Issue by nraychaudhuri** [playframework/playframework#2178]
Last week we had a bit of trouble working our way out through play.mvc.Result API.  brikis98 has a nice gist that demonstrates some of the pain point with action composition https://gist.github.com/brikis98/8000277

I know that Result type is supposed to be deprecated maybe there is more pending cleanup but right now its quite hard to check simple things like status of a given play.mvc.Result. There is play.core.j.JavaResultExtractor but it doesn't provide all the helper methods. Interestingly this class is only used from play.test.Helper. 

Ideally it will be great if play.mvc.SimpleResult can expose same API as Scala version.

**Comment by marcospereira** [comment]
Are we there yet? :-)

**Comment by gmethvin** [comment]
> Essentially, I don't think Java results should wrap Scala results, I think they should be idiomatic Java objects - with a fluid API to setting headers etc.

So from this persective, no. Java results still use a Scala `ResponseHeader`.
