### ISSUE TITLE
Dist on Windows packages files in conf folder incorrectly

### ISSUE THREAD

**Issue by jerusalemer** [playframework/playframework#2184]
File names under conf directory in the result .zip file start with '\'. As a result application fails to start.

Steps to reproduce: on dev machine (Windows 7) in play console run 'dist'
Copy zip file to target server (Linux). Run 'unzip xxx.zip', cd 'xxx/bin', ./xxx. Nothing happens and the application fails to start. 

That's how conf directory looks like:
[root@RH-ENGINE-QA]# ll conf
-rwxr-xr-x 1 root root 1926 Nov 21 15:52 \application.conf
-rwxr-xr-x 1 root root  919 Dec 10 16:05 \ehcache.xml
-rwxr-xr-x 1 root root  305 Dec 15 11:50 \servers.xml
-rwxr-xr-x 1 root root  827 Dec 15 12:05 \trade-monitor-context.xml

After renaming files to be without leading '\', the startup succeeds.

Play version 2.2.1

**Comment by zhengcan** [comment]
Any progress here?

**Comment by kristian-lange** [comment]
Ping. Any progress?

**Comment by jroper** [comment]
I believe this should be fixed in #3473, if it wasn't already fixed.  Could someone verify whether this is still an issue on Windows in Play 2.4.0-RC1?
