### ISSUE TITLE
Play-2.1.5 Remove warnings in routes file

### ISSUE THREAD

**Issue by antonhajdinaj** [playframework/playframework#2185]
For example, in my routes file when I have : 
GET     /someUri            controllers.AController.index()
GET     /someOtherUri    controllers.AController.index()

When I do a compile of the application, It warns me that the second line is unreachable 
[warn] C:\Users\antha\git\myProject\conf\routes:19: unreachable code
[warn] GET     /someOtherUri               controllers.AController.index()

Also when I have 
POST    /registration/show      controllers.Registration.show()
GET     /registration/show      controllers.Registration.show()
I have the same "Unreachable code" warning.

I've tested it and both declarations work fine and I absolutely need such declaration in my application. When I do /someOtherUri, the index() method is well called and when I do a GET request to /registration.show, the action is performed well.

Everything compiles well, but these warnings are not correct.

**Comment by tkruse** [comment]
Using play 2.6.11 here, with gradle play plugin, and ran into the same issue today, but `gradle compilePlayBinaryPlayRoutes` just silently failed to generate anything. Not sure if this is a fault with play or the gradle plugin. Would be nice to have an error instead.
