### ISSUE TITLE
Ability to convert WS.Response to Result object

### ISSUE THREAD

**Issue by hadesara** [playframework/playframework#2239]
There are many inconsistencies in convert the response from WS to the result object.

I would love! to do this:

```
private static Result getResult(WS.Response wsResponse)
{
return status(wsResponse.getStatus(), wsResponse.getBody()).as(wsResponse.getHeader(CONTENT_TYPE));
}
```

**Comment by jamesbrems** [comment]
The following implicit conversion works for me (play 2.3.9):

```  
implicit def Response2Result(response: Future[WSResponse]): Future[Result] = {
    response map {
      response =>
        val headers = response.allHeaders map {
          h => (h._1, h._2.head)
        }
        Result(ResponseHeader(response.status, headers), Enumerator(response.body.getBytes))
    }
  }
```

**Comment by wsargent** [comment]
@jamesbrems that's clever!  Would you consider adding it to the docs in a PR?  https://github.com/playframework/playframework/blob/master/documentation/manual/working/scalaGuide/main/ws/ScalaWS.md

**Comment by marcospereira** [comment]
Further discussion is happening in # #4787.
