### ISSUE TITLE
Add WSResponse.headers(): Map<String, String[]>

### ISSUE THREAD

**Issue by hadesara** [playframework/playframework#2240]
`play.mvc.Http.RequestHeader.headers()` returns a `Map<String, String[]>`
`play.mvc.Http.RequestHeader.getHeader()` return just a `String` and not `String[]`
`WS.Response.getHeader()` return just a `String` and not a `String[]`

Some consistencies would be nice.

**Comment by wsargent** [comment]
Closing because of https://github.com/playframework/play-ws/issues/101 -- @marcospereira can rationalize `Http.RequestHeader` :-)
