### ISSUE TITLE
Symbol value does not exist in somemethod

### ISSUE THREAD

**Issue by Archangelix** [playframework/playframework#2251]
First, let me clarify that I'm not sure to whom I should report this issue to: Play, ScalaTest, Selenium, or Scala itself.

I'm putting the detailed issue [here](http://stackoverflow.com/questions/21047345/symbol-value-does-not-exist-in-somemethod). Please let me know if you need me to copy-paste the details here as well. And if you're kind enough please give me a clue as where I should report this issue to in case it doesn't belong here.

In summary, the problem lies in this code below:

```
import org.openqa.selenium.firefox.FirefoxDriver
import org.scalatest.FlatSpec
import org.scalatest.Matchers    
import play.api.test.FakeApplication
import play.api.test.WithApplication    
class FunctionalSpec extends FlatSpec with Matchers {
  def withDriver(f: FirefoxDriver => Unit) = {
    val driver = new FirefoxDriver
    try {
      new WithApplication(
        new FakeApplication(additionalConfiguration = Map("application.secret" -> "secret"))) {
        f(driver)
      }
    } finally {
      driver.quit
    }
  }
}
```

And [this](http://pastebin.com/FkJJU7UR) is the detailed (and very long) error message. There is this part in the error:

> symbol value f$1 does not exist in test.FunctionalSpec$$anon$1$delayedInit$body.apply

Any idea what's happening? Any suggestion for a workaround?

**Comment by cvogt** [comment]
also see https://github.com/scalatest/scalatest/issues/620
