### ISSUE TITLE
Database evolutions with special characters

### ISSUE THREAD

**Issue by c100k** [playframework/playframework#2262]
This is my migration script 3.sql :

```
insert into currencies (id, created, updated, iso_code, name, symbol) values
(null, now(), now(), 'AED', 'United Arab Emirates Dirham', 'د.إ'),
(null, now(), now(), 'AFN', 'Afghan Afghani', '؋'),
(null, now(), now(), 'ALL', 'Albanian Lek', 'L');
```

When I run my app, the migrations are done (the 3 lines in the play_evolutions table are marked as applied). But despite this, I keep having the error when I refresh my page :

```
Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
```

If I apply directly my script in phpMyAdmin, everything works fine.
If I remove the special characters from the script, it works as well.

When the script is applied first, why is 'د.إ' replaced by '?.?' ? I think the problem comes from here... An encoding problem maybe...

**Comment by Gacko** [comment]
@jroper Are you using macOS? A coworker is having the exact same problem with Polish special characters on his Debian box. His database is UTF8 encoded as well as the SQL files.

I can not reproduce his issue on macOS with the same file and database encoding while he's getting the error every time.

**Comment by Gacko** [comment]
Update: Seems it's related to how your database is encoded. I can reproduce the issue using default encoding of MySQL which is latin1.
