### ISSUE TITLE
2.2.1 server returns 404 on HEAD request

### ISSUE THREAD

**Issue by StefanGIT** [playframework/playframework#2280]
If i create a new application in play 2.2.1 and try to get the HEAD request, i get a 404 error:
~/play-2.2.1/play new test
       _
 _ __ | | __ _ _  _
| '_ | |/ _' | || |
|  __/|_|____|__ /
|_|            |__/

play 2.2.1 built with Scala 2.10.2 (running Java 1.7.0_25), http://www.playframework.com

The new application will be created in /home/richtesn/teste/test

What is the application name? [test]

Which template do you want to use for this new application? 

  1             - Create a simple Scala application
  2             - Create a simple Java application

> 2
> OK, application test is created.

Have fun!

[richtesn@gaia:~/teste]$ cd test
[richtesn@gaia:~/teste/test]$ play run
[info] Loading project definition from /home/richtesn/teste/test/project
[info] Set current project to test (in build file:/home/richtesn/teste/test/)
[info] Updating {file:/home/richtesn/teste/test/}test...
[info] Resolving org.hibernate.javax.persistence#hibernate-jpa-2.0-api;1.0.1.Fin[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.

--- (Running the application from SBT, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 4 Scala sources and 2 Java sources to /home/richtesn/teste/test/target/scala-2.10/classes...
[info] play - Application started (Dev)

Then using a different terminal (HEAD is part of the libwww-perl package:
libwww-perl: /usr/bin/HEAD):

HEAD http://localhost:9000
404 Not Found
Content-Length: 4024
Content-Type: text/html; charset=utf-8
Client-Date: Fri, 17 Jan 2014 15:35:39 GMT
Client-Peer: 127.0.0.1:9000
Client-Response-Num: 1

The page is still delivered (using a GET request), but if i want to enter the link to the server in a system that checks the response code it is refused due to the 404 Not found.

EDIT (January, 23rd, 2014): if i contact the server via telnet, i see the repsonsce code:

telnet localhost 9000
Trying 127.0.0.1...
Connected to localhost (127.0.0.1).
Escape character is '^]'.
 HEAD /index.html  HTTP/1.1

HTTP/1.1 404 Not Found
Content-Type: text/html; charset=utf-8
Content-Length: 4034

<!DOCTYPE html>
<html>
    <head>

**Comment by gbsmith** [comment]
@jroper, echoing dhirenpratap's remarks, is there some trick to getting this to work with our 2.2.x Global.java file? I am not sure what to do with the RequestHeader copy call which doesn't seem exist in the Java version.

**Comment by jroper** [comment]
@gbsmith Copy the scala code into your project - you can't implement it in Java.  Just because you're using Java doesn't mean you can't have Scala code in your project.

**Comment by gbsmith** [comment]
@jroper So just copy the Global.scala in wholesale and have both a Global.java and a Global.scala?
