### ISSUE TITLE
Unable to set schema for play_evolutions db

### ISSUE THREAD

**Issue by mountash** [playframework/playframework#2286]
It would be grat if there would be an opportunity to set schema for the play_evolutions in  application.conf.

And also script 
create table play_evolutions (
                        id int not null primary key, hash varchar(255) not null, 
                        applied_at timestamp not null, 
                        apply_script text, 
                        revert_script text, 
                        state varchar(255), 
                        last_problem text
                    )
not workink in ORACLE cause there is no such type "text".

**Comment by lkt** [comment]
Same issue exists on Postgres. play_evolutions and play_evolutions_lock tables cannot be created on other schemas than 'public'

**Comment by mkurz** [comment]
Fix can be found here: #5485
