### ISSUE TITLE
Possibly-empty Int parameter?

### ISSUE THREAD

**Issue by nonameplum** [playframework/playframework#2290]
Hi,

 I have the same problem like Kenji Matsuoka described in google groups:
https://groups.google.com/forum/#!msg/play-framework/E2kQrMRlG4A/xYvRkvhxNm4J

> "In the routes file is it possible to declare an Int parameter that can be empty?  For example, my route looks lkike
> 
> GET     /sheep                        controllers.Counting.sheep(num: Int ?= 0)
> 
> I would like to be able to handle both requests like /sheep?num=3 and /sheep?num=, where the latter would assign num a value of 0, but instead I get
> 
> Cannot parse parameter num as Int: For input string: ""
> 
> Declaring num as an Option[Int] also doesn't work."

**Comment by ilucker** [comment]
If you use a form with a method "GET", browser will send values of all form elements in the query string. Some form element, like selects, can have an empty value and in this case Play is unable to handle such request.

**Comment by wwkudu** [comment]
Request that this be re-opened. Am struggling with last (form method='GET') use case. Thanks in advance.

**Comment by marcospereira** [comment]
Hello @wwkudu,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.
