### ISSUE TITLE
Make the timeout value for java testing configurable

### ISSUE THREAD

**Issue by sschwell** [playframework/playframework#2299]
Issue 1002 "solves" this by recommending use of get(timeout). 
However play.test.Helpers.wrapScalaResult() still calls the deprecated get() method, or more recently hard codes it to 10000.

There should be a way to change the default timeout for java functional testing.

**Comment by megazord** [comment]
Was this issue fixed by 452f78166d3d913337a3412a44f94088981cf352? It was merged at PR #2414.
