### ISSUE TITLE
[2.2.2-RC2] dev keeps reloading and compiling twice... 

### ISSUE THREAD

**Issue by AdrianScott** [playframework/playframework#2307]
App was generally working in 2.2.1. Trying 2.2.2-rc2, and when i 'run' in the play console, and then load localhost:9000, the server keeps reloading and appears to compile the Scala sources TWICE, showing this message:

[info] "Compiling 10 Scala sources to"

so the server is unusable in its current state.

Environment:
Fedora 18
JDK 1.7 using export _JAVA_OPTIONS=-XX:-UseSplitVerifier
dev using Eclipse Kepler but tried with Eclipse closed, and after first doing play clean-all, then play, and in play console, compile, and then finally run.

Thanks for any help with this! Am hoping 2.2.2 will solve my other premature MySQL db  closing bugs related to ebeans...

**Comment by AddiJamshidiExcellion** [comment]
This is NOT fixed in 2.2.6 - unless I am missing something... please advise.
