### ISSUE TITLE
Add buildin ScalaJs support

### ISSUE THREAD

**Issue by antonkulaga** [playframework/playframework#2321]
When developing responsive reactive websites a huge ammount of time is spent on front-end development as interactivity is standard de facto now and there developers have to use ugly dynamic JavaScript (Coffeescript a little bit improves the situation but not very much). Adding ScalaJS support will allow developers use the beuty of scala for the frontend, reuse part of scalacode in front-end development.

**Comment by strelec** [comment]
@reid-spencer: How's your progress on this matter?

**Comment by sjrd** [comment]
@vmunier's example [play-with-scalajs-example](https://github.com/vmunier/play-with-scalajs-example) now uses his own sbt plugin [sbt-play-scalajs](https://github.com/vmunier/sbt-play-scalajs). I think this qualifies as a proper sbt-web plugin for Scala.js.

**Comment by reid-spencer** [comment]
@strelec - My interest in Play has waned and I haven't made any progress at all. Fortunately, it seems like vmunier has. :)

**Comment by vmunier** [comment]
Hi, I found the main interest for [sbt-play-scalajs](https://github.com/vmunier/sbt-play-scalajs) to use sbt-web is to not depend on Play itself.
So `sbt-play-scalajs` depends on `Scala.js` and `sbt-web` only. It does not follow sbt-web directory layout though, because Scala.js projects are already sbt projects with a regular directory structure. :)

**Comment by InTheNow** [comment]
Also there is sbt-web support [bundled in the other sbt-scalajs plugin](https://github.com/InTheNow/sbt-scalajs/blob/master/src/main/scala/SbtScalajsWeb.scala) 

Its doc'd as experimental - but that's more of a disclaimer

**Comment by wsargent** [comment]
The sbt-web plugin is in https://github.com/InTheNow/sbt-scalajs

Also, ScalaTest 3.0.0 should help with Scala.JS testing:

* http://www.scalatest.org/release_notes/3.0.0
* http://www.artima.com/weblogs/viewpost.jsp?thread=375597

So I think this is covered.
