### ISSUE TITLE
controllers.AssetsBuilder.resourceNameAt incorrectly looks at local file system

### ISSUE THREAD

**Issue by dylex** [playframework/playframework#2337]
We ran into a strange situation where controllers.Assets was working on some systems and not others.  This is because one function is treating the paths as local filesystem paths rather than resource paths:

```
Assets.scala:177: if (new File(resourceName).isDirectory || !new File(resourceName).getCanonicalPath.startsWith(new File(path).getCanonicalPath)) {
```

Elsewhere in Assets, path is correctly treated as a resource path, but here it actually constructs Files out of the raw path (e.g., "/public/foo").  If "/public/foo" happens to exist on the local machine and be a directory, Assets returns 404, even though there is a perfectly good resource called "/public/foo".

**Comment by marcospereira** [comment]
I would say this is fixed in 2.6.latest and 2.7. as well. So closing.
