### ISSUE TITLE
Database should be clear between each test

### ISSUE THREAD

**Issue by asouza** [playframework/playframework#2338]
It is necessary for run multiples tests that use database... Currently i am doing this as part of my test suite.

```java
	public void dropDb() {

		String serverName = "default";

		EbeanServer server = Ebean.getServer(serverName);

		ServerConfig config = new ServerConfig();

		DdlGenerator ddl = new DdlGenerator();
		ddl.setup((SpiEbeanServer) server, new MySqlPlatform(), config);

		// Drop
		ddl.runScript(false, ddl.generateDropDdl());
		
		SqlUpdate dropEvolutions = Ebean.createSqlUpdate("drop table play_evolutions");
		Ebean.execute(dropEvolutions);

	}
```

I have to drop play_evolutions to force the recreation of tables.

**Comment by megazord** [comment]
@asouza are the new test APIs enough for what you wanted?

1. https://playframework.com/documentation/2.4.x/ScalaTestingWithDatabases
2. https://playframework.com/documentation/2.4.x/JavaTestingWithDatabases

If so, I think you can close this issue. :-)
