### ISSUE TITLE
Json.toJson Float

### ISSUE THREAD

**Issue by RodneyAtRealWineLists** [playframework/playframework#2339]
scala code:

println(Json.toJson(3.1))
println(Json.toJson(3.1f))

java code:
System.out.println(Json.toJson(3.1).toString());
System.out.println(Json.toJson(3.1f).toString());

outputs:
3.1
3.0999999046325684

using Play 2.2.1

**Comment by benwaffle** [comment]
Is there a way we can tell `Json` to use `Float.toString` so that `Json.toJson(3.1f)` results in `3.1` and not `3.0999999046325684`

**Comment by cchantep** [comment]
Please use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask questions.
