### ISSUE TITLE
Ebean doesn't escape MySql column names

### ISSUE THREAD

**Issue by somid3** [playframework/playframework#2348]
When trying to create a table (i.e.: Play Model Object) with a property called "key" an error occurs in MySql because the ORM creates the following code:

create table consumer_c (
id                        bigint auto_increment not null,
consumer_id      bigint,
key                     varchar(255),
value                  varchar(255),
constraint pk_consumer_c primary key (id));

Here the ORM needs to escape the column names with a ` (tilde) that way allowing one to create Java property names by default that do not conflict with the underlying DB. In understand one can use an annotation to change the column name. But for the out of the box experience this is confusing.

For example, the ORM should output:

create table consumer_c (
`id`                        bigint auto_increment not null,
`consumer_id`               bigint,
`key`                       varchar(255),
`value`                     varchar(255),
constraint pk_consumer_c primary key (id));

Otherwise Play is great! My favorite framework!!

**Comment by richdougherty** [comment]
I'm closing this issue so that we can consolidate similar tickets. Further discussion can happen under #2365.
