### ISSUE TITLE
Upgrade to Netty 4

### ISSUE THREAD

**Issue by nraychaudhuri** [playframework/playframework#2354]
Apart from these changes http://netty.io/wiki/new-and-noteworthy-in-4.x.html
Netty 4 fixes couple of issues I found recently. 

- By default Play netty worker threads shows up as New I/O Worker and doesn't use the name passed through the executor pool

- Netty 4 finally uses kern.ipc.somaxconn setting to configure the backlog property to increase the queue of incoming connection. Right now its limited to 50 connections for mac os

**Comment by megazord** [comment]
After [this discussion](https://groups.google.com/forum/#!searchin/play-framework-dev/netty/play-framework-dev/IvXLc7P2xfk/JDK5QXa1gq8J), I don't think this upgrade will happen.

Can we close this issue?

**Comment by mynap** [comment]
With Play 2.5 using netty 4. Is there any move to do the same with akka?
