### ISSUE TITLE
Calling request.accept(...) on a request coming from Chrome always return true

### ISSUE THREAD

**Issue by matthieus** [playframework/playframework#2406]
Play 2.2.1, Chrome 33.

When Request.accept(...) is called on a Chrome request, the following debug message is displayed:

```
Unable to parse part of media range header 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
```

**Comment by nicky-isaacs** [comment]
So in summary:

 - It "looks like a bug"
 - We are going to close the issue without taking action

Do I understand this correctly?

**Comment by jroper** [comment]
The reported bug (that accept always returns true) is not a bug, so I closed this. Feel free to open another issue about the log message.
