### ISSUE TITLE
Improve documentation on how to extend SBT build in Play 2.2.x

### ISSUE THREAD

**Issue by Mogztter** [playframework/playframework#2408]
I think the build system documentation should cover the internal build process to know exactly what play compile, clean, test, stage is doing.

This will allow user to understand how to add a custom task after/before a particular phase.

I found some resources on Stackoverflow and on the mailing list but none are working in Play 2.2.x:
https://groups.google.com/forum/#!topic/play-framework/3xvwfBl5ZTQ
https://groups.google.com/forum/#!topic/play-framework/4DMWSTNM4kQ
http://stackoverflow.com/questions/8554992/how-to-attach-custom-task-to-execute-before-the-test-task-in-sbt

The documentation should also cover how to enable/disable build feature. Ex: "How to disable Scaladoc ?"
http://stackoverflow.com/questions/21461798/how-to-disable-scaladoc-in-playframework-2-2-x-dist-sbt-task

**Comment by jroper** [comment]
I'm going to close this as it is very general and far reaching.  If there are any specific lackings in Play's documentation, please raise separate issues for them.
