### ISSUE TITLE
Change package naming convention, move java api to play.java

### ISSUE THREAD

**Issue by antonkulaga** [playframework/playframework#2421]
At the moment there is a lot of confusion between play and play.api packages, it is pretty common to import the wrong package (a lot of imports are done by IDE in a semiautomated fasion) and wonder why some methods are missing. 
So I suggest to move all java api under play.java namespace as it is more natural to expect java bindings there and if developer mistakenly will import something with play.java it will be very easy for him/her to figure out that something is wrong in imports. In the same time it will also be easy for java developers to find java wrappers

Overall current namespace conventions are contrintuitive, because it is natural to expect either interfaces (with less methods than in implementations) or wrappers in  {something}.api  To be honest when I first started learning play I thought that play.api is for java classes as it is natural to expect that java wrappers on top of original scala code will be called "api".

**Comment by kflorence** [comment]
+1 for making this distinction clearer -- we frequently have this problem with new devs.

**Comment by jroper** [comment]
For a discussion on how/when we intend to proceed on this (feel free to contribute yourself) see [here](https://groups.google.com/forum/#!topic/play-framework-dev/OFCqXBgsYdI).

**Comment by mkurz** [comment]
Closing in favor of #5816
