### ISSUE TITLE
provide a documentation related to dependencies loaders and versions collisions

### ISSUE THREAD

**Issue by gaydenko** [playframework/playframework#2441]
It would be great to have a documentation related to dependencies loaders and versions collisions: what is possible, and what must be avoided (custom akka, custom netty, ...). I mean the situation when Play framework itself depends on some project, and a Play application depends on the same project, while last one has another version.

**Comment by marcospereira** [comment]
Hi @gaydenko, this is already documented in sbt docs:

http://www.scala-sbt.org/0.13/docs/Library-Management.html#Conflict+Management

Play is using the default behavior (latest revision is selected).

Do you think this is enough?

**Comment by marcospereira** [comment]
See PR #5701.

**Comment by gaydenko** [comment]
@marcospereira , yes, I guess the issue can be closed, thanks!
