### ISSUE TITLE
Switch to HikariCP

### ISSUE THREAD

**Issue by brettwooldridge** [playframework/playframework#2445]
Consider this an enhancement request, but a biased one.  Play is a great framework touting both usability and performance.  Over at the [HikariCP](https://github.com/brettwooldridge/HikariCP) connection pool project, we care about usability and performance too.  We'd love to see HikariCP become the default connection pool provider for Play.  We know it's up to the task.

Not only is [HikariCP](https://github.com/brettwooldridge/HikariCP) the fastest pool around, it is also the most stable and "correct".  We've done our homework, and unlike most projects can say, we've read every line of code of our competitors code.  We've created a [pool analysis](https://github.com/brettwooldridge/HikariCP/wiki/Pool-Analysis) to illuminate the issues we've found in our studies.

When most people pick up a connection pool library off of the internet, they assume that because it is popular it must be solid.  But some not very deep Googling later you will find a myriad of issues from deadlocks to livelocks.

But don't take our word for it, give [HikariCP](https://github.com/brettwooldridge/HikariCP) a try, throwing anything at it you want, and when you're done make an informed decision.  That's all we can hope for.

**Comment by cchantep** [comment]
(Late) @richdougherty There is no BoneCP specific test, but `play.api.db.DatabaseSpec` checking connection and basic statement execution against the pool.

I guess it would be nice to run HikariCP plugin against this one.

**Comment by richdougherty** [comment]
OK thanks @cchantep.

**Comment by cchantep** [comment]
Plugin seems fine. Either it's forked and moved in the repo along with current BoneCP impl, and it could be covered with spec there, or a PR could be pushed to Edulify repo to check the plugin.
