### ISSUE TITLE
Check whether RUNNING_PID is accurate

### ISSUE THREAD

**Issue by YousefED** [playframework/playframework#2495]
After an unexpected shutdown (e.g.: jvm crash), the RUNNING_PID file points to a process which is not running anymore. This will prevent play to automatically start again (for example by an upstart script).

Would it be a good idea to check whether RUNNING_PID points to a process which exists (and if not; ignore it)?

**Comment by francisdb** [comment]
What a mess, why would you write a PID file if you do not check if the process is still alive? Every time we do an upgrade using the .deb packager the server won't start any more.
