### ISSUE TITLE
improve the document for how to write an plugin both in java and scala

### ISSUE THREAD

**Issue by hepin1989** [playframework/playframework#2503]
I think that we should improve the document to show the user how to write a plugin both in java and scala.
by the way,may be Play! should provide some convenient interface to implement an plugin.

for now ,I just found that the triant HandleWebCommandSupport is not accesable in java.so if I want to implement an plugin just like Evolution,then it was not that convinient.

now the document is so week,even we clould learn how to by reading others' code,but I think if the document show the best practice,then that should  be nice.

**Comment by megazord** [comment]
Is this issue stills relevant, since plugins will be deprecated in Play 2.4.0?
