### ISSUE TITLE
Provide a way to generate document or html api page from the route file

### ISSUE THREAD

**Issue by He-Pin** [playframework/playframework#2504]
Hi ,I have an idea with the route,How about provide one way ,helper.scala.html or SBT task to generate an html page or document from the route file.

The motivation is that if we using the Play to implement a REST service,then we need to explain how to using the play service right?If we could provide one way to generate the API defination just like what java doc does from the route file,then that should be handy.

the current route file just can only handle comment via (#) 

```
# add gcm configuration for app
POST          /app/:id/gcm                 controllers.App.addGCM(id :Long)
```

and how about if this support this

```
# add gcm configuration for app
#  @param id the app id
#  @return *** 
POST          /app/:id/gcm                 controllers.App.addGCM(id :Long)
```

then generate the document as (html)

```
definition : add gcm configuration for app
url :           http:host/app/:id/gcm
method :   POST
param :    id  the app id 
```

Anyway ,some thing like this.
And the user could generate an static html page via sbt task or provide it via an webpage with the helper class.

WDYT?

**Comment by scofier** [comment]
@jroper   Swagger API module  It needs too many annotations...
