### ISSUE TITLE
Documentation doesn't clearly explain what "modules" and "plugins" are

### ISSUE THREAD

**Issue by kipsigman** [playframework/playframework#2519]
Going through the Play documentation, I'm not finding a section/page that describes "modules" and "plugins" well. It would be helpful to developers to understand the basic concepts of these.

**Comment by mslinn** [comment]
It would be most helpful if the Play team would publish updated and complete docs on how to write Play Framework 2 modules. Some topics to discuss:

 * Brief history of Play Framework modules
 * How to set up `app/` as a source root (so Twirl templates can be included), vs. `src/` (for modules that do not have a UI component). Actual working examples of simple modules would be best.
 * Examples of how to set up `build.sbt` for various scenarios
 * Example of using `publish-local` to test the module in a sample app, with a discussion of maven-style vs. ivy-style
 * Example of `publish` to bintray
 * Description of how `conf/play.plugins` in a Play app relates to the plugin
 * Upcoming changes to modules, if any

**Comment by jroper** [comment]
Documentation on what a module is is now here:

https://www.playframework.com/documentation/2.4.x/Modules
