### ISSUE TITLE
object play.api.i18n.Lang should not define implicit value defaultLang

### ISSUE THREAD

**Issue by tayama0324** [playframework/playframework#2590]
Because of `implicit val defaultLang` defined in play.api.i18n.Lang, we cannot pass language parameter to templates implicitly.

```
@* views/sample/sayhello.scala.html *@
@(name: String)(implicit lang: Lang)

<p>@Messages("hello")(lang), @name.</p>
```

```
import play.api.i18n.Lang

object Controller {
  def sayhello(name: String) = Action { request =>
    implicit val lang = Lang("ja")
    Ok(views.html.sample.sayhello(name))
  }
}
```

In example above, to our surprise, views.html.sample.sayhello never takes `Lang("ja")`. play.api.i18n.Lang.defaultLang ( https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/i18n/Messages.scala#L65 ) is used instead.

The mechanism is as follows: sayhello.scala.html is complied into sayhello.scala like this;

```
import play.api.i18n.Lang

object sayhello {
  def apply(name: String)(implicit lang Lang) = { ... }
}
```

Implicit values from import always precedes ones visible from callers scope. An only way to inject `lang` to `apply` is passing explicitly, like `sayhello(name)(Lang(ja))`. 

It is painful to me that I cannot use implicit Lang, which is a part of play i18n framework. Moreover, it is very difficult to find out why sayhello ignores implicit parameter because we need to understand scala's complicated resolution rule for implicit parameters, and need to know the fact that Lang has an implicit defaultLang. Although compilation fails if two or more implicit values of same type is defined in the same scope, (at least my) compiler does not even prints warning message in above case.

Generally we should not define public implicit values in objects which have non-implicit values or methods, I think. scala.concurrent.ExecutionContext provides the same value in two ways; implicit manner (ExecutionContext.Implicits.global) and non-implicit manner (ExecutionContext.global).

**Comment by slorber** [comment]
@jroper `The people that want to use the default implicit are people who don't care about i18n`

Another problem is that it is unclear if we want to force one language if we should use `application.langs="fr"` or the JVM locale settings.

Related to https://github.com/playframework/playframework/issues/3852

**Comment by nlochschmidt** [comment]
@jroper This has been quite a pain for us as well. We have a couple of nested presentation classes and whenever we forget an `(implicit lang: Lang)` on any method that calls another method that needs an implicit language we get the default one. A compile error would be much more preferable.
