### ISSUE TITLE
Make test timeout configurable

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#2593]
I recently increased Play's default test timeout from 5 seconds up to 20 seconds (#2592). I had to do this because Play would sometimes fail when running on our cloud CI box, presumably because tests run much more slowly on that box.

But increasing a high timeout isn't ideal because it will slow down test failures during normal development. Ideally we would have a low timeout during development and a higher one when running on slower systems… in other words, something that's configurable!

Options are: system property, Typesafe Config value, etc.

**Comment by megazord** [comment]
Is this issue duplicated with #2299?

**Comment by megazord** [comment]
@jroper and @richdougherty, #2299 was already closed and I think this is a duplicated.
