### ISSUE TITLE
Add animal-sniffer JDK 1.6 signature detection to build

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#2609]
Animal sniffer has a feature which ensures that code must adhere to a specific version of the JDK, so that people cannot write code which uses methods that only exist in JDK 1.7 or JDK 1.8.

http://mojo.codehaus.org/animal-sniffer-maven-plugin/examples/generating-java-signatures.html

**Comment by megazord** [comment]
@wsargent as far as I know, Play 2.4.0 will support Java 8+. Is this issue stills relevant?

**Comment by wsargent** [comment]
No, we can close this.

Sent from Outlook




On Mon, Apr 6, 2015 at 7:57 PM -0700, "Megazord" <notifications@github.com> wrote:












@wsargent as far as I know, Play 2.4.0 will support Java 8+. Is this issue stills relevant?

**Comment by megazord** [comment]
@jroper could you please close this issue?

Thanks. :-)
