### ISSUE TITLE
Add test that ensures all play.plugins files end with new line

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#2618]
IntelliJ strips new lines which leads to trouble. See https://github.com/playframework/playframework/pull/2386

**Comment by mkurz** [comment]
Given that Plugins are deprecated and are removed in 2.5 I think it is safe to close this issue.
Also in the `2.4.x` branch there is only one `play.plugins` file left, in the `master` branch (=upcoming `2.5.x` branch) there none anymore.
