### ISSUE TITLE
Use Enter key to stop play run command

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#2671]
Using Ctrl-D for stopping the `run` command is risky since Ctrl-D is also used for terminating SBT. I regularly terminate SBT when I only mean to stop the run command.

We should allow Enter to be used to stop the run command. SBT already uses Enter to terminate other interactive commands, such as `~compile`, `~test`, etc. To make the transition easy for users we can still support Ctrl-D in addition to Enter, but I suggest we only advertise Enter to new users.

Currently:

```
$ run

--- (Running the application from SBT, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)
```

I suggest we say:

```
(Server started, use Enter to stop and go back to the console...)
```

**Comment by zhengcan** [comment]
Currently in v2.5, I use Enter to add empty lines in sbt console to make the log readable more.
In v2.6, I fell so sad that it's really easy to unexpected to stop the run command.

Can we use another key rather than Enter to stop the run command?
Or I can disable the new feature in build.sbt?
