### ISSUE TITLE
Play 2.3-M1: Constantly reloading on every request

### ISSUE THREAD

**Issue by cedricziel** [playframework/playframework#2717]
I wanted to give the Milestone a shot, and while I know there might some rough edges, I experience some strange behaviour:

1.) I followed the given advices about upgrading sbt to `sbt.version=0.13.5-M2`
2.) I switched my whole JavaScript to use RequireJS in order to leverage sbt-web capabilities

What happens now, is that The project is reloading on every request wether it's a managed asset or a "normal" controller action.

```
[info] play - database [default] connected at jdbc:h2:mem:play 
[warn] application - A user service was already registered - replacing the old one, however this might hint to a configuration problem if this is a production environment. 
[info] play - Application started (Dev) 
 --- (RELOAD) --- 
[info] play - database [default] connected at jdbc:h2:mem:play 
[warn] application - A user service was already registered - replacing the old one, however this might hint to a configuration problem if this is a production environment. 
[info] play - Application started (Dev)  
--- (RELOAD) ---  
[info] play - database [default] connected at jdbc:h2:mem:play
[warn] application - A user service was already registered - replacing the old one, however this might hint to a configuration problem if this is a production environment. 
[info] play - Application started (Dev)  
--- (RELOAD) --- 
```

While this is crazy enough, after some request cycles (I guess like ~200, respectively 200 http requests) the JVM is out of memory and dies.

I would appreciate every feedback and would happily post the configuration you desire.

Thank you in advance.

**Comment by akurathi-m** [comment]
Constantly reloading on every request Please help me

**Comment by marcospereira** [comment]
@akurathi-m could you please discuss that at our mail list?

Thanks!

**Comment by AddiJamshidiExcellion** [comment]
I have 2.2.6. On every request it keep reloading:

[info] play - Application started (Dev)
[info] Compiling 13 Scala sources to C:\aj
oudPlay\target\scala-2.10\classes...
[info] Compiling 13 Scala sources to C:\aj
oudPlay\target\scala-2.10\classes...

And goes and on and on for 13 times on every request.

What is the fix?

**Comment by cedricziel** [comment]
Upgrading :)

**Comment by AddiJamshidiExcellion** [comment]
Upgrading to what...?

**Comment by cedricziel** [comment]
A current version of `Play!`.

You mentioned using 2.2.6, 2.5.6 is the current stable.

**Comment by ashok4ch** [comment]
I am facing the same issue. My envi details : OS: Windows 10 pro, play: 2.2.3  what is the fix?

**Comment by renatocaval** [comment]
@ashok4ch, you are using Play 2.2.3. The current version is 2.7.3, you are quite behind. I suggest you upgrade your app. 

Play 2.2.x is not being maintained anymore so don't expect any fix for this.

**Comment by ashok4ch** [comment]
Issue fixed by installing JNotify correctly on Windows 10 pro. Apps using Play 2.2.3 work fine now.

**Comment by ashok4ch** [comment]
@renatocaval   Thank you.  sure will update.
