### ISSUE TITLE
Logging is noisy in IntelliJ IDEA

### ISSUE THREAD

**Issue by akkie** [playframework/playframework#2730]
Logback uses [automatic status printing](http://logback.qos.ch/manual/configuration.html#automaticStatusPrinting) if warnings or errors occur during the parsing of the configuration file. The problem with play is that lockback fails with the following error message:
```
11:47:38,157 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@3462482a - There is no conversion class registered for conversion word [coloredLevel]
11:47:38,157 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@3462482a - [coloredLevel] is not a valid conversion word
```

This is due the fact that the default logback configuration shipped with Play uses the following conversion pattern:
```xml
<conversionRule conversionWord="coloredLevel" converterClass="play.api.Logger$ColoredLevel" />
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%coloredLevel %logger{15} - %message%n%xException{5}</pattern>
    </encoder>
  </appender>
```

If I override the default logback config and remove the conversion pattern, then the error disappears and the log is no longer noisy.

I have no idea why the registered converter class isn't used by logback. Maybe this is a class loader or IntelliJ IDEA problem. 

This may be related to #1448.

**Comment by jroper** [comment]
There are a few things that have probably fixed or alleviated this:

* Play no longer ships with a `logback.xml` file, so if running outside of a Play app, you shouldn't have this problem.
* There were race conditions in Play's logging loading code that could trigger errors like this.  This is now fixed.
