### ISSUE TITLE
Ebean startup time, WEB-INF resourceDirectory search

### ISSUE THREAD

**Issue by astorath** [playframework/playframework#2814]
Play reload is very slow on windows platform due to some deep directory search on startup at `com.avaje.ebeaninternal.server.resource.ResourceManagerFactory#createResourceSource`. I suggest to add some fake `com.avaje.ebean.config.ServerConfig#resourceDirectory` option on server creation to skip the search.

**Comment by arminbauer** [comment]
I can confirm this. If the working directory is not set to a good value, ebean will search a lot of directories and startup will be very slow.

**Comment by mkurz** [comment]
@arminbauer Pull requests are welcome :wink:

**Comment by marcospereira** [comment]
Is this a issue with Ebean or Play?

**Comment by heat** [comment]
I wanna test this. which play version did you use? If does set a default `ebean.default = ["models.*"]` configuration is a good approach to resolve that?

**Comment by wsargent** [comment]
Closing -- this may be more applicable to https://github.com/ebean-orm/avaje-ebeanorm
