### ISSUE TITLE
Allow play logger to read variables specified in app configuration

### ISSUE THREAD

**Issue by xunnanxu** [playframework/playframework#2833]
Right now the logger xml config can read properties from those specified by -D, but not those in app configuration. The only exception might be the application.home, which is hard-coded to be passed when the app gets started.
This eliminates the possibility to provide a centralized config when specifying -D parameters is not an alternative. For instance if all app logging configs need to be the same except the file name, right now we have to maintain the almost identical application-logger.xml everywhere. But if we could specify logging.filename in the app config, and use ${logging.filename} in the xml, then we only need to maintain one logging config.

**Comment by wsargent** [comment]
So logback relies on the Joran configurator, so combining that would involve making JoranConfigurator take properties from typesafe config: http://logback.qos.ch/manual/configuration.html#joranDirectly

**Comment by wsargent** [comment]
* https://github.com/qos-ch/logback/blob/master/logback-classic/src/test/java/ch/qos/logback/classic/joran/JoranConfiguratorTest.java
* http://shibboleth.1660669.n2.nabble.com/Logback-config-with-properties-td7602446.html

**Comment by wsargent** [comment]
The problem with adding this to play-logback is that no doubt there would be cases where typesafe config added variables that didn't use to exist, possibly breaking fallback behavior in the logs...
