### ISSUE TITLE
Can't run a dist on windows

### ISSUE THREAD

**Issue by patsimon** [playframework/playframework#2854]
On play-2.2.3

The "play dist" commands creates 2 scripts for starting up the app in either windows or *nix.

The windows command [appname].bat results in the following error:
The input line is too long.
The syntax of the command is incorrect.

**Comment by simplemx** [comment]
@frosforever thx for your comment.It works for me.

change APP_CLASSPATH to *.jar generate ClassNotFoundError in my project.

**Comment by ronalexander4** [comment]
Actually, it should be:

set "APP_CLASSPATH=%APP_LIB_DIR%\*

(leave off the ".jar")

**Comment by sam-lex** [comment]
Play 2.6 - same problem. @frosforever solution works, but needs to be done every time before starting server.

`set "APP_CLASSPATH=%APP_LIB_DIR%\*.jar`
`set "APP_CLASSPATH=%APP_LIB_DIR%*"`

Both of these two gives ClassNotFountError.

Is there a permanent solution?

**Comment by ronalexander4** [comment]
Permanent solution: Don't use the play framework. It's a scam to extract
support money from you after you've implemented your system on top of it
(gotten pregnant with them). They make major changes in every version
requiring significant porting efforts, their documentation is practically
non-existent, and they refuse to offer *any* help unless you pay them
minimum $25,000. Been down that road, never again.

Just my $.02.

**Comment by sam-lex** [comment]
Got it working again without any changes to the .bat file, and it was to move it into a "short" path, something like: `C:\app`.

Originally it was into a folder like: `Downloads\test_app\server`

**Comment by ricklambrechts** [comment]
Hi, this is still a problem with the current version.
For me the solution is:
`set "APP_CLASSPATH=%APP_LIB_DIR%\..\conf\;%APP_LIB_DIR%*"`
