### ISSUE TITLE
ApplicationSecretGenerator doesn't gather sufficient entropy

### ISSUE THREAD

**Issue by alsmola** [playframework/playframework#2879]
The ApplicationSecretGenerator.generateSecret function uses the SecureRandom.nextInt function to generate 64 characters with an ASCII code between 48 (0) and 122 (Z). While this generates a readable 64 character UTF-8 string with about 400 bits of entropy, only the first sixteen characters of the secret are used in the Crypto.encryptAES function, yielding about 99 bits of entropy, rather than the optimal 128 bits.

Something like the following code could be used to preserve entropy:

```
val keyBytes = new Array[Byte](32)
random.nextBytes(keyBytes)
new String(keyBytes, "UTF-8")
```

However, this would not necessarily be readable in console output. A cleaner approach might be to convert the secret to bytes and take 16, rather than taking a 16 character substring and then converting to bytes.

**Comment by v6ak** [comment]
According to the source, it seems to be fixed in 2.4 for new formats, see https://github.com/playframework/playframework/blob/925912922929464bcbb0a2b5aba1c200ffaaec67/framework/src/play/src/main/scala/play/api/libs/Crypto.scala#L444 and its usage.
