### ISSUE TITLE
2.3.0-RC1 Double compilation in dev mode

### ISSUE THREAD

**Issue by astorath** [playframework/playframework#2904]
Issuing page refresh while compilation is active due to auto-reload (**~run**) sometimes trigger second compilation. Compilation occasionally fails on missing file.

**Comment by benmccann** [comment]
This is now fixed with the latest version of sbteclipse. 

Use the latest by adding the following to your `project/plugins.sbt` and then running `activator eclipse` and refreshing your project in Eclipse:

    addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "3.0.0")
