### ISSUE TITLE
Application reloads on assets or public files changes

### ISSUE THREAD

**Issue by astorath** [playframework/playframework#2905]
In dev mode Play triggers full app reload after any change in assets files or in public folder. This is pretty much useless and it takes a lot of time (3-5 secs). Any workaround on this? Maybe there is a way to control app reload behavior?

**Comment by michaelahlers** [comment]
I'm running into this—application reload with changes to files in `/public`—with 2.4, and not finding any relevant resources. Any ideas?

**Comment by kobier** [comment]
I have the same problem, using Play 2.4.3, after changing a JavaScript file in ```/public``` folder, server reloads. Disabling Web plugins in ```plugins.sbt``` didn't help.

Any word of advice would be appreciated!

**Comment by ajozwik** [comment]
I had the same behaviour. The problem is with watcher. 
The work-around is to remove all target dirs ( find . -name target | xargs rm -Rf). I ran fsck on my filesystem too. Modern hard discs have a cache - the files are not synchronized immediately. And then when sbt compare the timestamp - it is different than expected.

**Comment by kobier** [comment]
My problem was having node_modules in /public folder... Server wasn't actually restarting, but had to keep track of all files (~12k) in node_modules, that's why it took very long (~15s) to reload the page. Not a problem with Play Framework :)

**Comment by mikebridge** [comment]
I have this problem with Play 2.4.6 --- every time I modify a .js file in a subproject's 'public' directory it triggers a recompilation of all the scala and java sources and a reloads Play.

**Comment by mikebridge** [comment]
@michaelahlers did you find a solution to this with 2.4?

**Comment by mikebridge** [comment]
Looks like this had to do with ScalariForm.  It was enabled globally and was causing some scala files to get reformatted and recompiled.  Removing it from the plugins stopped the reloading.

**Comment by ajozwik** [comment]
@mikebridge do you know how to disable plugin in develop mode? I have the same problem, but I want to have this plugin enabled before commit to git.

**Comment by mikebridge** [comment]
@ajozwik Unfortunately I don't have the sbt knowhow to turn it off but [this](http://stackoverflow.com/questions/32284670/disable-an-autoplugin-from-the-sbt-command-line) might be helpful.   I have it configured transitively in IntelliJ via the scalastyle plugin and that seems to work pretty well.

**Comment by michaelahlers** [comment]
@mikebridge, I haven't visited this for a while (since having moved towards using webpack to generate fully static web app. clients), but I _do_ have this snippet in `build.sbt` which _might_ have helped.

```scala
watchSources := (watchSources.value
                 --- baseDirectory.value / "app/assets" ** "*"
                 --- baseDirectory.value / "public"     ** "*").get
```

Take this with a grain of salt. And by “grain of salt” I mean [deer lick](https://en.wikipedia.org/wiki/Mineral_lick).

**Comment by codeepic** [comment]
@shkhln

This code snippet doesn't work for Play 2.5.2

`watchSources := (watchSources.value
                 --- baseDirectory.value / "app/assets" ** "*"
                 --- baseDirectory.value / "public"     ** "*").get`

When added to `build.sbt` the Play framework never compiles the files and doesn't serve the app in the browser. It's just stuck in a page reload indefinitely.
