### ISSUE TITLE
Make the Java Json library a first class citizen

### ISSUE THREAD

**Issue by 0xdevalias** [playframework/playframework#2939]
Currently there appears to be functionality available in the Scala Json class that isn't available in the Java framework equivalent (a minor example being [pretty print](http://stackoverflow.com/questions/22222293/prettyprint-jsonnode-in-play/23862995#23862995))

Java: https://github.com/playframework/playframework/blob/master/framework/src/play-json/src/main/java/play/libs/Json.java

Scala: https://github.com/playframework/playframework/blob/master/framework/src/play-json/src/main/scala/play/api/libs/json/Json.scala

**Comment by charlescapps** [comment]
@gmethvin / @jroper we would very much like to allow using a custom Jackson `PrettyPrinter` for one call of `play.api.libs.json.Json.prettyPrint(...)` in Scala.

We have a unique Scala application where the JSON formatting is very important, in particular we need to add newlines after each entry in a JSON Array. (Can be accomplished by calling `printer.indentArraysWith(new Lf2SpacesIndenter())` but alas we can't set the printer directly.)

Moreover, we have custom logic in our `play.api.libs.json.Format` converters, so we can't use Jackson directly on our case classes, and Jackson doesn't work to serialize `JsValue` into a string.  

This would be a trivial change for a new version of play! I'll create a ticket later.
