### ISSUE TITLE
CI on Windows

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#2997]
Investigate setting up continuous integration on Windows. Codeship.io is a possibility. I enabled it briefly but it interfered with existing PR validation. Maybe we could get it to validate only code on a special windows branch, and then have a script that regularly syncs with the master branch?

**Comment by richdougherty** [comment]
sbt-native-packager has a Windows AppVeyor build happening: https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml

**Comment by richdougherty** [comment]
I'll implement this one day. :)

**Comment by wsargent** [comment]
Closing -- this is way down the list.
