### ISSUE TITLE
Play 2.3 Global.java onRequest not being called

### ISSUE THREAD

**Issue by CHI-Sean** [playframework/playframework#3004]
My Global.java class in the default package, which extends GlobalSettings overrides onRequest.

onRequest gets called for our controllers ( which are also implemented in java ), however, onRequest is not being called for controllers.Assets.at() .  

This is easily reproduced in a standard playFramework template application by overriding onRequest as I specified above and requesting a static asset from the application.  Your onRequest method will NOT be called ( as described in the online documentation ).

**Comment by wsargent** [comment]
Fixed in 2.5
