### ISSUE TITLE
Custom error result in JSON body parser

### ISSUE THREAD

**Issue by xolvo** [playframework/playframework#3039]
When calling actions with POST and header `Content-Type: application/json` and body with invalid JSON (something like {foo:}) framework generates Bad request response. It is possible to catch this error in `Global#onBadRequest` or `Global#onRouteRequest` and show message like "Invalid Json" to the user. But it's NOT possible to catch it in Action.Simple or any other part of application.
BTW without Content-Type header everything works ok - I could catch invalid json and make response with my custom message.

So, I consider it as bug. Especially if someone is writing RESTful API with JSON responses in many languages and there is no way to override default message - Invalid Json. Actually there is a way but it's a hack:
```java
@Override
public Promise<Result> onBadRequest(RequestHeader request, String error) {
	if("Invalid Json".equals(error)) {
		// generate JSON response with message in requested language
		// and about some errors in JSON
	} else {
		// generate any other response about bad request in requested language
	}
}
```

__Framework version__
2.3.0 Java

__How to reproduce this problem__
Create new Java application, write action to handle any POST request and call it
`curl -d "{foo:}" -H "Content-Type: application/json" http://localhost:9000/test`
You'll get Bad request

Make another call without header Content-Type: application/json
`curl -d "{foo:}" http://localhost:9000/test`
No bad request, get response with 200 status code

**Comment by oleg-gr** [comment]
What's the issue with just passing the exception to `onBadRequest`, i.e. `protected CompletionStage<Result> onBadRequest(RequestHeader request, String message, Exception exception)` so that users can do at least something without the need to meddle with body parsers, which seems like a huge pain if you are using Java?
