### ISSUE TITLE
Document how `activator start` has changed in 2.3

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#3085]
Maybe something we could add to the migration docs. The `start` command has changed so that it properly stages the build. One effect is that the RUNNING_PID file is in a different location. See: https://github.com/typesafehub/activator/issues/563. There may be other implications of this change that we want to document too.

**Comment by wsargent** [comment]
Is this still applicable?

**Comment by hepin1989** [comment]
I think we should so do add document about how to use Play from sbt directly.

**Comment by wsargent** [comment]
Still applicable?

**Comment by wsargent** [comment]
I'm thinking not applicable.
