### ISSUE TITLE
Using akka.event.slf4j.Slf4jLogger leads to akka.ConfigurationException on startup

### ISSUE THREAD

**Issue by mariussoutier** [playframework/playframework#3106]
Hi,

in 2.2 we’ve been using Akka’s logger, as mentioned in the documentation (http://www.playframework.com/documentation/2.3.x/SettingsLogger). Now with 2.3, I get the following exception when running the app:

``` scala
akka.ConfigurationException: Could not start logger due to 
[akka.ConfigurationException: Logger specified in config can't be loaded 
[akka.event.slf4j.Slf4jLogger] due to [java.lang.ClassNotFoundException: akka.event.slf4j.Slf4jLogger]]
```

This prevents the app from launching, and the only solution is to disable the event logger.
Classpath-wise everything seems fine.

Running tests works fine.

We are using `application.conf` only on staging and production servers. Locally every sub-project has a `reference.conf` and we are running the app with `-Dconfig.file=dev.conf`, where the dev.conf includes the reference.conf. When I rename `reference.conf` to `application.conf` everything seems to work fine.

**Comment by vbeffa** [comment]
I am still seeing this exception even after adding the `sbt-web` plugin.

**Comment by mprzydatek** [comment]
same with me. Still getting the exception.

**Comment by dragisak** [comment]
I see this with Play 2.3.7 Even when I remove all web plugins.

I have only `addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.7")` in my plugins.sbt

**Comment by mariussoutier** [comment]
This issue has also reoccurred for me in another project.

**Comment by jroper** [comment]
We haven't upgraded Play 2.3.x to sbt-web 1.1.0 because the behaviour of sbt-web 1.1.x in multi modules changes how assets are made available across modules, which would break existing multi module Play 2.3.x projects.

**Comment by gkarthik21** [comment]
is this resolved?I am getting this issue on play 2.4.8. Do I have to still explicitly specify sbt-web 1.1.1?

**Comment by JohnMurray** [comment]
Just a note that I have seen this in Play 2.5.12. Not sure why, but found this thread when searching for the issue.

**Comment by mcanalesmayo** [comment]
We are also experiencing this in Play 2.6.21 with Gradle build

**Comment by oldcwj** [comment]
[error] akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
