### ISSUE TITLE
OfflineEvolutions should let you override the configuration

### ISSUE THREAD

**Issue by fzakaria** [playframework/playframework#3147]
Very similar to how starting an application allows you to specify a Map which adds to the Configuration, OfflineEvolutions should also allow you to do the same.

The use case, is that for Scala Test all the test classes are ran simultaneously. As a result, I create a unique database name (generally the class name) for each test file. I'd like to be able to load offline evolutions with a unique database name for each test class.

**Comment by jroper** [comment]
I think this is now fixed, the evolutions API has had a major overhaul which allows completely specifying the configuration manually.

**Comment by fzakaria** [comment]
Thanks for closing / looking into it.
Sadly no longer using play.
