### ISSUE TITLE
Implement support for > 22 field case classes in macros

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#3174]
In Scala 2.11, a case class can have more than 22 fields.  We could modify our existing macros to support these.  Here's approximately how to do it:
- Detect > 22 field case class - if it's not greater than 22 fields, then simply generate reads/writes identical to the way they are generated now.
- Group fields into groups of 22 (or less).
- Generate reads/writes for tuples of each of the groups fields
- Generate reads/writes for the case class that combines the reads/writes for the groups.  It will have to use the constructor to create the class, and access the fields directly to write the class into a set of tuples, rather than using the apply/unapply methods of the companion object.

Then we should be able to support case classes with 484 parameters.  I don't know if it's possible to create such a thing, since I think there's a 255 parameter limit for methods.

**Comment by mushtaq** [comment]
+1

**Comment by analyticspot** [comment]
+1

**Comment by xuwei-k** [comment]
> Then we should be able to support case classes with 484 parameters. I don't know if it's possible to create such a thing, since I think there's a 255 parameter limit for methods.

```scala
final val MaximumJvmParameters = 254
```

https://github.com/scala/scala/blob/v2.11.5/src/compiler/scala/tools/nsc/backend/jvm/GenASM.scala#L34
https://github.com/scala/scala/commit/5cc2eb872432f5a00dd53

**Comment by cvogt** [comment]
I released a play-json macro with support for arbitrary size case classes for scala 2.11 and play-json 2.3.4. https://github.com/cvogt/play-json-extensions
It can be used as a drop-in until play comes up with a solution itself.

@jroper Please check out the code, it's tiny. I also looked at the play-json macros at some point. They seem overly complex. Part of the complexity stems from not using quasi quotes and from general 2.10 compatibility. When is play expecting to drop 2.10 support?

**Comment by cvogt** [comment]
@jroper I wouldn't mind creating a PR from this as long as I don't have to add 2.10 support.

**Comment by jroper** [comment]
@cvogt We don't have any plans to drop 2.10.  Of course, that doesn't mean that we won't drop it at some point, but we just haven't planned to do that yet.  I guess we'll drop 2.10 support when we adopt 2.12 support, that will likely be Play 3.

Given that we don't need to support 23 parameter case classes in Scala 2.10, one option we could have is to create `scala-2.10` and `scala-2.11` source directories in the `play-json` project, and put the `JsMacroImpl` object in there, with the old code in the `scala-2.10` directory and your code in `scala-2.11`.

**Comment by cvogt** [comment]
Good idea. I'll put together a PR and then we can go from there. What's the release cycle for play-json? Any deadline I should be aware of?

**Comment by jroper** [comment]
Play 2.4.0-RC1 is scheduled to be released in the next few days.

**Comment by prophe05** [comment]
+1

**Comment by Uditmittal** [comment]
@cvogt  How can i use more than 22 column case class list in your plugin.
it will give error 
diverging implicit expansion for type org.cvogt.scala.constraint.boolean.!
and it doesn't show validation message also

**Comment by cvogt** [comment]
@Uditmittal please submit an issue at https://github.com/cvogt/play-json-extensions including a code snippet that allows me to reproduce the problem.

**Comment by vito-c** [comment]
+1

**Comment by Tvaroh** [comment]
+1

**Comment by pathikrit** [comment]
+1

**Comment by noru** [comment]
+1

**Comment by moqichenle** [comment]
+1

**Comment by recastrodiaz** [comment]
+1

**Comment by meghana-viswanath** [comment]
+1

**Comment by pylesage** [comment]
+1

**Comment by pylesage** [comment]
+1

**Comment by shorani** [comment]
+1

**Comment by mikibe** [comment]
+1

**Comment by etspaceman** [comment]
+1

**Comment by loicdescotte** [comment]
+1

**Comment by angeloh** [comment]
+1

**Comment by vj077** [comment]
+1

**Comment by ssemichev** [comment]
+1

**Comment by wsargent** [comment]
@cvogt 2.5.x has dropped 2.10 support https://www.playframework.com/documentation/2.5.x/Migration25#Scala-2.10-support-discontinued so if you want to use quasiquotes, it's all good :-)

**Comment by hjz** [comment]
+11

**Comment by cvogt** [comment]
I spend all of my free time on CBT these days. Does somebody else want to execute the migration of play-json-extensions into play-json?

**Comment by konasp** [comment]
+1

**Comment by wsargent** [comment]
FYI Play-Json has moved to https://github.com/playframework/play-json

**Comment by gmethvin** [comment]
Moved to playframework/play-json#3

**Comment by Uditmittal** [comment]
+1

**Comment by kevinmeredith** [comment]
So the reason for not supporting 22+ fields is Scala 2.10 support?

Thanks

**Comment by alexroussos** [comment]
> @Uditmittal please submit an issue at https://github.com/cvogt/play-json-extensions including a code snippet that allows me to reproduce the problem.

@cvogt I don't see an issue for this, do you still need someone to create it?

**Comment by cvogt** [comment]
@alexroussos did you hit the same problem? Yes, please create an issue

**Comment by jmess4** [comment]
@jroper your example does not compile. It looks like maybe you initially created it for a Reads but then went back and updated it for a Format. Could you please update it?
