### ISSUE TITLE
Activator start command ignores -Dhttps.port property

### ISSUE THREAD

**Issue by akkie** [playframework/playframework#3190]
The following command doesn't start the play application on the defined HTTPS port:

```
activator -Dhttps.port=12345 start
```

```
[info] application - Application has started
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
```

The `run` command works as expected:
```
activator -Dhttps.port=12345 run
```

```
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[info] play - Listening for HTTPS on port /0:0:0:0:0:0:0:0:12345
```

**Comment by wsargent** [comment]
activator start is deprecated, as is testProd, so the way to test this going forward is `activator stage` followed by running the script with `-Dhttps.port` -- which does actually work.  So closing.
