### ISSUE TITLE
Play application, packaged as a .war, deployed in an application server based on osgi

### ISSUE THREAD

**Issue by jlc** [playframework/playframework#3212]
Hi!

Here is a short description of the context, and a proposed fix for this issue.

We are developing a web application based on play which is run either as a standalone application (mostly for development) or within an application server based on OSGi.

In this last scenario, we first create a .war archive (using play2-war-plugin which package all .jar dependencies in the WEB-INF, create a MANIFEST and other things).
Then, we use the maven-bundle-plugin for the "OSGifycation" of the .war (which mostly consist of listing the provided and optional packages from the .war).

After having upgraded our play application from play 2.2.2 to play 2.3.1, we've hit the following exception:

```
IllegalArgumentException: Cannot check isDirectory for a URL with protocol='bundle',
```

which is throw from 

```
src/play/src/main/scala/utils/Resources.scala, in Resources.isDirectory().
```

Within an OSGi context, the protocol of the URLs is "bundle" (e.g. bundle://303.42:12/messages). In this context, Resources.isDirectory should also take care of the "bundle" protocol and test the resource accordingly.

The best solution I could find out to test if the given resource is a directory is to use the classloader.getResource(name) and classloader.getResource(name+"/"). In the second case, only directories return non-null.

Please find below the link to a proposed fix (based on master, work on 2.3.x too).
https://github.com/jlc/playframework/commit/83a62b3c2c9394ba9d925a45bd31626f8f52d436
Wish you a nice day!

Jean Luc

**Comment by asaelitz** [comment]
Hi @jroper.
I have the same issue with `bundleresource` protocol, and seems this solution of `bundle` is fit to this issue.
Can you please check this?

Regards,
Asael

**Comment by jroper** [comment]
I don't work on Play anymore, and I very much doubt anyone will take up an issue like this. If you want it fixed, I suggest you create your own PR.
