### ISSUE TITLE
Can't create "user" table in Postgresql

### ISSUE THREAD

**Issue by thomasbeauvais** [playframework/playframework#3218]
I have a User class (which should be legit) and Play is generating the evolution script:

`create table user (
  id                        bigint not null,
  constraint pk_user primary key (id))
;`

The problem is that `user` is a keyword.  

`ERROR: syntax error at or near "user"`

I am wondering why Play doesn't wrap everything in qutations which are legal in most (if not all) SQL databases.. 

`create table "user" (
  id                        bigint not null,
  constraint pk_user primary key (id))
;`

Any thoughts?  Thanks and have a cheery day!  Keep up the great work!

**Comment by AdamStelmaszczyk** [comment]
So, when I have:

@Entity
public class User

What's the solution? Rename? Or can I turn on quotations wrapping?

**Comment by thomastoye** [comment]
Hi Adam, I just avoided names like this when working with Ebean. Not the
best solution but it worked for me while I made the switch to another
database layer.

Please refer to #2365. Discussion on this issue is being moved there since
there's a lot of issues referencing this.
