### ISSUE TITLE
Internationalization : 'withLang' not working for first request

### ISSUE THREAD

**Issue by loicdescotte** [playframework/playframework#3233]
Use case summary :  display a page with the right language according to a "lang" parameter in the URL

Controller code : 

``` scala
Ok(views.html.myTemplate(myData)).withLang(Lang(request.queryString("lang").head))
```

The template retrieves the language with an implicit parameter  :

``` scala
@(myData: MyModel)(implicit l: Lang)
...
@Messages("my.message")
```

This is working perfectly except for the first request. The first one always displays the default language, I guess because the lang cookie is not set yet.

Note: If you pass explicitly the lang from the controller to the template (or if you declare an implicit val lang) instead of using withLang, it works as expected.
Note 2 : There is a workaround using a 'Redirect' to force the update : http://stackoverflow.com/a/17771495/591922

**Comment by DieterLi** [comment]
As to the sample code provided by jroper, I got the following error:
ambiguous implicit values:
 both method request2lang in trait Controller of type (implicit request: play.api.mvc.RequestHeader)play.api.i18n.Lang
 and value lang of type play.api.i18n.Lang
 match expected type play.api.i18n.Lang

I wonder whether it is an effective way to change the implicit lang? Thanks.
