### ISSUE TITLE
EbeanPlugin: Add support for read-only data-sources

### ISSUE THREAD

**Issue by jarmo** [playframework/playframework#3237]
Currently (Play 2.2, Play 2.3) when using multiple data-sources then it is not possible to disable evolutions and DDL automatic generation. This is usually not a problem, but becomes a problem with at least one of the sources being read-only.

There is a [PR](https://github.com/playframework/playframework/pull/2528) for disabling evolutions for specific data-sources, but there is no way to disable DDL generation per data-source. Only way is to disable `EbeanPlugin` DDL generation globally like this:

```
evolutionplugin=disabled
```

This does not solve the problem, because we want evolutions for non-read-only datasources.

Currently, when `evolutionplugin` is `enabled` (the default behavior) then evolution scripts are generated automatically by using DDL extraction [here](https://github.com/playframework/playframework/blob/0c130d1bd20350d1ceb529a404fe009ecaa9ce4e/framework/src/play-java-ebean/src/main/java/play/db/ebean/EbeanPlugin.java#L93-L103). The scripts are created and created and since this is a read-only datasource then they cannot be applied.

There should be a data-source specific option to disable automatic DDL generation. 

PS! The option name `evolutionplugin` is also misleading for this particular use-case.

**Comment by wsargent** [comment]
Moved to https://github.com/playframework/play-ebean/issues/118
