### ISSUE TITLE
Make Json.reads macro handle case class default params gracefully 

### ISSUE THREAD

**Issue by acjay** [playframework/playframework#3244]
It would be nice if `Json.reads` was able to synthesize `Reads` classes for `case class`s with default parameter values. So riffing on the example, we might have:

``` scala
case class Person(name: String, age: Int, lovesChocolate: Boolean, favoriteColor: String = "blue")

implicit val personReads = (
  (__ \ 'name).read[String] and
  (__ \ 'age).read[Int] and
  (__ \ 'lovesChocolate).read[Boolean] and
  ((__ \ 'favoriteColor).read[String] orElse Reads.pure("blue"))
)(Person)
```

(I imagine, there's probably some non-trivial reflection needed to get the default parameter value.)

Perhaps of interest to @mandubian

**Comment by gmethvin** [comment]
Moved to playframework/play-json#4
