### ISSUE TITLE
Update to specs2 2.4 or 2.4.1

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#3307]
Note: This brings in Scalaz 7.1, which isn't compatible with Scalaz 7.0.6.

**Comment by diwalak** [comment]
Is this still planned for 2.4 ? 
With all the changes around testing helpers, it would be great if the specs2 dependency gets isolated (and probably also upgraded to specs2 3.0 )

**Comment by dwijnand** [comment]
@diwalak looks like it's going in 2.4, but it's not specs2 3.0: https://github.com/jroper/playframework/commit/6c782d342031bc96604d50206f71f7bc8867a044
