### ISSUE TITLE
[2.2.3] IndexOutOfBoundsException when binding larger POST to form

### ISSUE THREAD

**Issue by FrEaKmAn** [playframework/playframework#3334]
I have a form which contains one field.

```
public class AlarmLogFilterForm
{
    @Constraints.Required
    public List<String> keys;
}
```

and in a controller I bind POST request to form

```
// url is /alarms/filter
public Result filter()
{
    Form<AlarmLogFilterForm> form = Form.form(AlarmLogFilterForm.class).bindFromRequest();

    // validate for error ...

    List<String> keys = form.get().keys;

    // other ...
}
```

Pretty standard stuff. Then I test this with

```
import requests

payload = {'keys[]': list(range(0, 1000))}
r = requests.post("http://localhost:9000/alarms/filter", data=payload)

print r.request.headers

print r.status_code
```

When a number of keys is > 100 (or somewhere close), I get

```
play.api.Application$$anon$1: Execution exception[[InvalidPropertyException: Invalid property 'keys[369]' of bean class [forms.AlarmLogFilterForm]: Invalid list index in property path 'keys[369]'; nested exception is java.lang.IndexOutOfBoundsException: Index: 369, Size: 0]]
```

Of course the request length is much lower then the limit defined at https://www.playframework.com/documentation/2.2.x/JavaBodyParsers so I don't think this is a problem. 

The working code for me is to access POST data via request()

```
Map<String, String[]> body = request().body().asFormUrlEncoded();
List<String> keys = Arrays.asList(body.get("keys[]"));
```

My question is - is this normal? Should I write code differently to be able to bind larger POST to form?

**Comment by mowcixo** [comment]
@FrEaKmAn I understand that it wouldn't be changed by default, but Play should have the ability to change it at Form level, not having to use request() for that and having to write your own validation.
