### ISSUE TITLE
Website - Search Box Overlapping Text

### ISSUE THREAD

**Issue by jamesward** [playframework/playframework#3358]
https://www.playframework.com/documentation/2.3.x/Tutorials

![screen shot 2014-09-01 at 10 22 22 am](https://cloud.githubusercontent.com/assets/65043/4110566/37f1f3c2-31f4-11e4-8651-4bd92357a700.png)

cc @Warry

**Comment by megazord** [comment]
It is not happening anymore. I tested with both Firefox (37.0.1) and Google Chrome (42.0.2311.90).
