### ISSUE TITLE
Bad application path when running dist

### ISSUE THREAD

**Issue by mchmielarz** [playframework/playframework#3362]
I generated dist package using ```activator dist``` command. When I try to start the application using bat script from bin folder using ```script.bat -Dhttp.port=1234``` I get "Bad application path: -Dhttp.port=1234" message.

What can be the reason of this?

I'm running on Windows 7. PlayFramework version is 2.3.3. I'm using JDK 1.7u10 64bit.

**Comment by sebdotv** [comment]
Duplicate of #3081?
