### ISSUE TITLE
Play OAuth should use Future[T] for network operations

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#3365]
"Just noticed when trying to interact with twitter oauth, the methods on Oauth (retrieveRequestToken, retrieveAccessToken) returns Either[OAuthException, RequestToken] and not Future[RequestToken] even though they require a http call to the oauth server, so I take it they are blocking? (why?)"

https://groups.google.com/d/msg/play-framework/lfp6-KQSv7M/VOdI3guDNmgJ

**Comment by kflorence** [comment]
We have been using this with success: https://github.com/nulab/scala-oauth2-provider

**Comment by marcospereira** [comment]
What about https://github.com/kovacshuni/koauth? It has an async API.

**Comment by nafg** [comment]
@kflorence I think the discussion is about consumers, not providers

**Comment by rtyley** [comment]
> Yes, we currently use signpost, which isn't async, to do oauth.

As a sidenote - signpost no longer looks actively developed, and actually has a rather nasty issue in that it includes copy'n'paste versions of `com.google.gdata.util.common.base.*` classes within it's own source code (no renaming of package, so clash with the legitimate classes): https://github.com/mttkay/signpost/pull/14

**Comment by schmitch** [comment]
That an issue I wanted to tackle as well, however the question is, should we still maintain oauth 1.0?

**Comment by wsargent** [comment]
@schmitch there are a ton of people who use OAuth1.0, especially where public APIs are exposed.

**Comment by wsargent** [comment]
Okay, closing this and creating a new bug explicitly about breaking out the API from Signpost.
