### ISSUE TITLE
Alter Router.Routes to give PathPattern information

### ISSUE THREAD

**Issue by mrpmorris** [playframework/playframework#3378]
In order for plugins to know more information about the incoming request could PlayFramework alter the Router.Routes trait so that it is possible to get the Method and PathPattern?

The intent is for the Global object to be able to use onRequestReceived to extract values from the request's URL

GET        /x/:name/:age        controllers.Application.tester(name: String, age: Int)

I could then get a list of parameters, their types, and their values as per the current request.

**Comment by shezi** [comment]
All of this is very nice and workable, but completely unavailable from Java code. Being able to access the path parameters from Java would make a whole class of Action compositions possible in Java. 

Even the official documentation shows something of the like (but then ducks out of actually showing how to get the user parameter) in https://www.playframework.com/documentation/2.4.x/JavaActionsComposition#Passing-objects-from-action-to-controller

What exactly would be the drawback of carrying an array with all the URL parameters somewhere?

**Comment by shezi** [comment]
One more note: It does not seem to be a huge amount of code considering that this can be implemented/hacked in about 30 lines *when using Scala*. As shown here: https://alots.wordpress.com/2014/05/01/accessing-url-parameters-as-get-parameters-in-play/

Also note that there are now quite a few indications that this would be a useful feature.

**Comment by kiamesdavies** [comment]
I found a way of accessing Route. Check this  
http://stackoverflow.com/questions/25699895/how-do-i-extract-the-value-of-a-route-variable-from-the-url-in-a-scala-play-app/38919004#38919004
