### ISSUE TITLE
2.3.4:   multiple main-*.js files are not served in production

### ISSUE THREAD

**Issue by cnrudd** [playframework/playframework#3381]
Hi,

I am building an application that has multiple main-*.js files loaded via require.js.

In my build.sbt, I have:

RjsKeys.modules := Seq(
    WebJs.JS.Object("name" -> "main-welcome"),
    WebJs.JS.Object("name" -> "main-member"),
    WebJs.JS.Object("name" -> "main-mentor"),
    WebJs.JS.Object("name" -> "main-admin")
)

In my main.scala.html template, I have:
      &lt;script>var angularApp = "@userType";&lt;/script>
    @if(userType == "member") {
      &lt;script data-main="@routes.Assets.versioned("javascripts/main-member.js")" type="text/javascript" src="@routes.Assets.versioned("lib/requirejs/require.js")">&lt;/script>
        } else {
          @if(userType == "mentor") {
      &lt;script data-main="@routes.Assets.versioned("javascripts/main-mentor.js")" type="text/javascript" src="@routes.Assets.versioned("lib/requirejs/require.js")">&lt;/script>
          }else{
            @if(userType == "admin"){
      &lt;script data-main="@routes.Assets.versioned("javascripts/main-admin.js")" type="text/javascript" src="@routes.Assets.versioned("lib/requirejs/require.js")">&lt;/script>
            }
          }
        }

This is working well in dev mode, when I do "activator ~run".
But the js is 404 when I do "activator start".

[projectname] $ start
[info] Wrote /Users/***_/workspace/projectname/target/scala-2.11/projectname_2.11-0.0.1-SNAPSHOT.pom
[info] Optimizing JavaScript with RequireJS
[info] Error: Error: /Users/**__/workspace/projectname/target/web/rjs/appdir/javascripts/main.js does not exist.
[info] Packaging /Users/_***/workspace/projectname/target/projectname-0.0.1-SNAPSHOT-assets.jar ...
[info] Done packaging.

Any ideas as to what I need to fix?
Is there a special config file for production that I need to edit somewhere?

Thanks,
Colin

**Comment by thomaslhostis** [comment]
Hello @cnrudd, have you figured out how to obtain multiple minified and concatenated main.js?
