### ISSUE TITLE
Json macros - make implicit for automatic Reads / Writes / Format materialisation

### ISSUE THREAD

**Issue by brendanator** [playframework/playframework#3382]
Currently you can write 

```scala
case class Dog(favouriteBone: String)

object Dog {
  implicit val dogFormat = Json.format[Dog]
}
```

Using implicit macros this format can be materialised automatically by the compiler

It would be important to make this implicit macro as low priority as possible so an explicit format declared in the companion object would be used in preference

**Comment by OlegYch** [comment]
not sure if anyone has considered it, but currently you can know if the class is used for json just by looking at the companion object, and eg if you rename a field of a class you can be fairly sure if it breaks your json clients or not
with the proposed implicitly materialized format there is no way to know if the class is converted to json somewhere in your application, and so changing any class in backwards incompatible way might break your json clients
