### ISSUE TITLE
Javascript routes support for fingerprinted assets

### ISSUE THREAD

**Issue by jserranohidalgo** [playframework/playframework#3435]
The `jsRoutes` reverse router generated for Javascript doesn't work for fingerprinted assets, i.e. a call to 
`jsRoutes.controllers.Assets.versioned(<<path>>).url` always returns the unversioned asset, even if a fingerprinted one is available. The expected behaviour of `jsRoutes` here should mimic the one of its Scala equivalent `routes.Assets.versioned(<<path>>).url`.

Discussion for this issue was initiated at: https://groups.google.com/forum/#!topic/play-framework/X3syPQpMbBQ

**Comment by pvlugter** [comment]
I've added asset index generation to the sbt-digest plugin. Available in a stamped snapshot. This can be used to get versioned paths for fingerprinted assets from javascript. And can be patched into the javascript reverse router for now.

A [sample project](https://github.com/pvlugter/js-routes-versioned) and commit [here](https://github.com/pvlugter/js-routes-versioned/commit/6d3da7afdd331a7ef747ef0eec3c0dc3215dcd07) demonstrates it, based on the `play-scala` activator template.

An updated sbt-digest is needed. In `plugins.sbt`:

``` scala
addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.0.1-20141003-74432ce")
```

Enable an index file to be generated, and simply make it a global `versioned` map:

``` scala
pipelineStages := Seq(digest)

// Create a map of versioned assets, replacing the empty versioned.js
DigestKeys.indexPath := Some("javascripts/versioned.js")

// Assign the asset index to a global versioned var
DigestKeys.indexWriter ~= { writer => index => s"var versioned = ${writer(index)};" }
```

The `versioned` object can then be used to get versioned paths. For example:

``` javascript
versioned["images/favicon.png"]
// returns "images/84a01dc6c53f0d2a58a2f7ff9e17a294-favicon.png"
```

And this can also be patched into the reverse router. For example:

``` javascript
(function() {
  var oldVersioned = jsRoutes.controllers.Assets.versioned;
  jsRoutes.controllers.Assets.versioned = function(path) {
    return oldVersioned.apply(jsRoutes.controllers.Assets, [typeof versioned !== "undefined" && versioned[path] || path]);
  };
})();
```

See the [sample project](https://github.com/pvlugter/js-routes-versioned) for the full set up in a project.

**Updated Sept. 2025**: A newer demo can be found here: https://github.com/mkurz/sbt-digest-indexwriter

**Comment by mkurz** [comment]
I think this can be closed.
