### ISSUE TITLE
netty-http-pipelining deployment problems

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [playframework/playframework#3436]
2 things:

1) netty-http-pipelining is missing form maven central (while present in typesafe repository)
http://search.maven.org/#search%7Cga%7C1%7Cnetty-http-pipelining
http://repo.typesafe.com/typesafe/releases/com/typesafe/netty/netty-http-pipelining/

2) it still depends on netty 3.6

we would like to avoid depending on typesafe repository in certain build scenarios

**Comment by jroper** [comment]
Fixed here: https://github.com/typesafehub/netty-http-pipelining/pull/12
