### ISSUE TITLE
play logging should be less intrusive

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [playframework/playframework#3441]
1) Problem
As these things go, logging is always a popular topic :-)
https://github.com/playframework/playframework/issues?q=logback+logger

in our case, ```Logger.configure(...)``` is destroying similar but different
modifications we make to JUL, logback, etc. only much earlier in the application life cycle.

that has to do with running inside the cloud, logging to aws sns / loggly etc.

2) Solution
There is one feature missing from play logger, 
which would remove all future complains: ability to disable  it in one shot:
https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala#L33

Preferably, via ```reference.conf``` (no system properties, please)
```
play {
   logger {
         enable-easy-config = false
   }
}
```

In general it would help to introduce more of these "kill easy mode" switches
which would help people get more control of the framework, 
after they become sufficiently familiar with it.

**Comment by wsargent** [comment]
Resolved with https://github.com/playframework/playframework/pull/5194
