### ISSUE TITLE
local development: delay in handling response after modifying asset file

### ISSUE THREAD

**Issue by q42jaap** [playframework/playframework#3460]
I've tried create a minimal example with the activator (play version 2.3.4) and I've found that there is a delay in play after netty receives the request when an asset has been changed in the mean time (local development only of course).

This is how a normal (dynamic) request looks like with `logger.play=TRACE`:

```
16:04:50.683 [trace] play - Http request received by netty: DefaultHttpRequest(chunked: false)
GET / HTTP/1.1
Host: localhost:9000
Connection: keep-alive
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.77 Safari/537.36
Accept: */*
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8,nl;q=0.6,ru;q=0.4
Cookie: PLAY_SESSION="..."
16:04:50.685 [trace] play - Serving this request with: <function1>
16:04:50.685 [trace] play - Parsing AnyContent as empty
16:04:50.686 [trace] play - Invoking action with request: GET /
```

The I edit one css/js/html file in /public/, it doesn't really matter what file, the play execution gets delayed between the netty receive log and the "Serving this request with" log. In the log below the delay is 500ms, but in bigger projects I've seen this get up to a 10 second delay.

```
----- alter a js/css/html file in /public/, notice the delay 16:05:23.398 - 16:05:23.953 of > 500ms ----

16:05:23.398 [trace] play - Http request received by netty: DefaultHttpRequest(chunked: false)
GET / HTTP/1.1
Host: localhost:9000
Connection: keep-alive
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.77 Safari/537.36
Accept: */*
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8,nl;q=0.6,ru;q=0.4
Cookie: PLAY_SESSION="..."
16:05:23.953 [trace] play - Serving this request with: <function1>
16:05:23.953 [trace] play - Parsing AnyContent as empty
16:05:23.954 [trace] play - Invoking action with request: GET /
```

I would expect a minimal impact when an asset changes on normal request handling, in dev mode. 500ms would be workable, but as a project gets bigger the delay gets bigger (I assume that that is what's causing more delay in my actual project). 10 seconds between refreshing the page and getting the response, where the actual action takes under 100ms is not really workable.

**Comment by peter-fu** [comment]
I have the same problem. My code base is large, the "silent" time is 15 seconds or so.

By changing sbt log level to Debug, I can see some output by sbt during the "silent" time.
`set logLevel in Global := Level.Debug`

I guess it might be related to this issue of sbt, which is hopefully part of sbt 1.0.0.
https://github.com/sbt/sbt/issues/2525
