### ISSUE TITLE
BoneCP creates a large number of connections after recovering from a DB connection failure

### ISSUE THREAD

**Issue by ksit** [playframework/playframework#3466]
(This issue was originally submitted to Typesafe via support case 3556.  I am creating this issue on github so that I can track the issue and make the workaround available to others who are experiencing the same issue.)

We are using Play! version 2.2.2, with Scala 2.10.4 running on Java 1.7.

Recently, one of the database servers in our test environment went down and we observed a rather awkward behaviour in BoneCP at the time when we managed to bring the database server back in operation.

When the DB server became online again, we noticed a spike in the number of database connections. Further investigation led us to believe that the root cause is located in the connection handle code in BoneCP.

Steps we used to reproduce the issue:
* Start the Play! server
* Make sure the connection pool is up and running
* Shut down the database server
* Let the connection pool test the connectivity (and keep reporting failures)
* Wait for the retry to fail (after 10 attempts)
* Bring the database server back up
* By this point, the active connection count is incorrectly set to a negative number, and at the end, we might end up having more connections than the maximum we set in the configuration 

We were using database monitoring tools to monitor the number of active connections.

We have a workaround that involves changing the BoneCP source code, but it feels like a temporary hack.

```java
// ConnectionHandle.java
try{
    this.connection = newConnection ? pool.obtainInternalConnection(this) : connection;
} catch(SQLException e){
    final SQLException sqlException = markPossiblyBroken(e);
    if (newConnection && this.logicallyClosed.get()) {
        // BUG FIX : Increment the created count, to offset the decrement
        // that happened in markPossiblyBroken
        partition.updateCreatedConnections(1);
    }
    throw sqlException;
}
```

@jroper has already raised this issue with [BoneCP](https://bugs.launchpad.net/bonecp/+bug/1367056).

**Comment by jroper** [comment]
Closing because bonecp is in maintenance and we now support hirakicp.
