### ISSUE TITLE
Incompatibility with JBoss/WildFly 7+ 

### ISSUE THREAD

**Issue by JonnyHeavey** [playframework/playframework#3487]
Play applications (deployed as wars) seem to be incompatible with JBoss/WildFly 7+ due to the servers use of 'VFS' URLs. There is code within play which qualifies URLs and throws an exception if an unexpected protocol is found (such as vfs://).

@gilbertw1 seems to have fixed the issue on his fork, but doesn't seem to have produced a pull request. His implementation / fix highlights the issue: https://github.com/gilbertw1/playframework/commit/9f9618d52ea54308418d08d29d711c5855c1d3b1

I noticed that a similar fix was implemented to support 'bundle' URLs recently: https://github.com/playframework/playframework/commit/9f212ff8ce158d6792d2fdbab6e2a591b2b46ef5

I was hoping that something similar could be done to support VFS URLs.

I appreciate that a war deployment isn't the suggested approach with play, but I'm in the position where its a project constraint.

**Comment by wsargent** [comment]
https://github.com/play2war/play2-war-plugin has support for JBoss 8.
