### ISSUE TITLE
[play-json] 'isEmptyNode'/'isObject'

### ISSUE THREAD

**Issue by alias1** [playframework/playframework#3489]
In Jackson all nodes have the isEmptyNode(): Boolean method.

I was wondering what the equivalent 'best practice' is for the scala Json library?

If there isn't an equivalent on JsValue (which from what I have seen currently I don't think so) I think it would be useful to include.

In a similar area, testing to see whether a JsValue is a JsObject, and converting accordingly. (I'm guessing isInstanceOf/asInstanceOf, but it would be nicer if there was a cleaner way that wraps it up)

**Comment by gmethvin** [comment]
I would prefer to keep `JsValue` and its subclasses as minimal as possible and use extractors/implicits to add additional functionality.

Maybe I'm missing something but I'm not familiar with `isEmptyNode` in Jackson. There's an `isMissingNode`, which identifies a node that doesn't contain a value, similar to our `JsUndefined`. In 2.4 `JsUndefined` is no longer in the `JsValue` hierarchy; you deal with undefined lookups either using pattern matching or the methods on `JsLookupResult` (e.g. `toOption`, `validate`, etc.).

To check/convert to `JsObject` (or any other play-json type), you can also call `jsValue.asOpt[JsObject]` to get an `Option[JsObject]`.

We notably don't have a direct way to distinguish between container and value nodes, but I guess I'm not really sure where that would be used.
