### ISSUE TITLE
Performance problems when looking up missing configuration

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#3495]
See this blog post: http://tech.kinja.com/gaining-performance-in-play-framework-writing-default-c-1643844013. Looking up configuration for the body parser `maxLength` and for the `trustxforwarded` configuration options caused performance problems because missing configuration values throw exceptions. We can fix this by supplying default values (like the author of that post did) or by using dependency injection to lookup values only once, instead of on every request.

Related: https://github.com/playframework/playframework/pull/2628

**Comment by megazord** [comment]
An "has-pr" label would be nice. :-)

See PR #4189.

**Comment by richdougherty** [comment]
"has-pr" label added. :)

**Comment by megazord** [comment]
Oops, I think the label should be added here. You added it at the PR itself. :-)
