### ISSUE TITLE
Play 2.3.5 release includes snapshot version of sbt-run-support-210

### ISSUE THREAD

**Issue by fiadliel** [playframework/playframework#3506]
In the Ivy file for Play's sbt-plugin for 2.3.5, one dependency is:

``` xml
<dependency org="sbt-run-support-210" name="sbt-run-support-210_2.10" rev="0.1-SNAPSHOT" conf="compile->default(compile)"/>
```

There are a few issues with this:
1. Snapshot releases are not good practice, builds may not be reproducible.
2. The `sbt-run-support-210_2.10` artifacts are in the Typesafe snapshots repo, and this may cause build failures for people who use a Nexus server as a proxy, and have not included the repository.
3. `sbt-run-support-210_2.10` does not follow best practices for the groupId.

While it's up to you to decide whether to make a Play 2.3.6 release... the current setup is not ideal.

**Comment by luisobo** [comment]
Not sure if it was just me but sbt failed to resolve this dependency. Seems like it was deleted several weeks ago but I haven't notices because of my local cache.

**Comment by marcospereira** [comment]
@IhabSoliman and @luisobo, 

Which version of Play are you guys using? This was fixed in 2.3.6 (see the [changelog](https://www.playframework.com/changelog)).

**Comment by luisobo** [comment]
I was using 2.3.5. Saw this issue so I updated to 2.3.8 (latest) and that
fixed the issue.

My comment was trying to be more informative than anything else, in case
anyone else found this problem.

2015-04-27 14:19 GMT-04:00 Marcos Silva Pereira <notifications@github.com>:

**Comment by marcospereira** [comment]
@luisobo ok, thank you. :+1:

**Comment by emanuelef1** [comment]
I'm having this issue since this morning, updated to activator 1.3.2 (latest version)

**Comment by jroper** [comment]
Upgrading activator does nothing.  What version of Play are you using?  Check your `project/plugins.sbt`.  If it's 2.3.5, update it.

**Comment by emanuelef1** [comment]
@jroper thank you, I was looking at the wrong place. Changing the version in 

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.8")

fixed the issue. Thank you!

**Comment by Favorlock** [comment]
@jroper suggestion worked for me as well. JetBrains needs to update their template I think.

**Comment by mahmoudabbasi** [comment]
hi 
i can't do download 
when used vpn :
The error occurs :
[error] Server access Error: Connection reset url=http://repo.typesafe.com/typesafe/ivy-releases/sbt-run-support-21
0/sbt-run-support-210_2.10/0.1-SNAPSHOT/ivys/ivy.xml
[error] Server access Error: Connection reset url=http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/sbt-run-su
pport-210/sbt-run-support-210_2.10/0.1-SNAPSHOT/ivys/ivy.xml
[error] Server access Error: Connection reset url=http://repo.typesafe.com/typesafe/releases/sbt-run-support-210/sb
t-run-support-210_2.10/0.1-SNAPSHOT/maven-metadata.xml
[error] Server access Error: Connection reset url=http://repo.typesafe.com/typesafe/releases/sbt-run-support-210/sb
t-run-support-210_2.10/0.1-SNAPSHOT/sbt-run-support-210_2.10-0.1-SNAPSHOT.pom

question : Will the entire package be downloaded for offline every time there isn't a need to check Internet
