### ISSUE TITLE
static assets in routes doesn't work after migrating from 2.3.3 to 2.3.5

### ISSUE THREAD

**Issue by aacanakin** [playframework/playframework#3517]
I have a route file dispatching static scripts by the following;
```
GET     /assets/*file               controllers.Assets.at(path="/public", file)
```
My public folder tree is the following;
```
- public
  - app
    - css
      - app.css
```
In my `main.scala.html`, I have the following style statement;
```html
<link rel="stylesheet" href='/assets/app/css/app.css'>
```

It currently gives 404 Not Found.
The 2.3.3 version was perfectly handling the static scripts. However, 2.3.5 results in problems.

All I did is to increase the play version from 2.3.3 to 2.3.5 in `plugins.sbt`.

Is this a known issue currently or do we need to change anything in `routes` file ?

**Comment by antonini** [comment]
Anyone found a solution? I'm using 2.3.8 and my public assets are not been exposed when running `activator start`.

But when I run `activator run` my public assets are there.

I noticed that the target dir doesn't contains my public files when running the start. Neither when publishing the project using something like `activator rpm:package-bin`.

**Comment by antonini** [comment]
I found the problem on my environment.
I was using a new version of the plugin [sbt-native-packager](https://github.com/sbt/sbt-native-packager) with a really old configuration that I copied from an old project.
This was causing all my problem with static assets!

**Comment by jilen** [comment]
@antonini  If you add something like `packageArchetype.java_server` in build.sbt that will override play settings

**Comment by antonini** [comment]
@jilen. Yes. That was my problem. I was using the configuration that you said and `packageArchetype.java_application` too.

When I removed both of these configurations the project worked as expected on production.

**Comment by sivailango** [comment]
Hi,

Last week i upgraded my project to 2.3.8. I started the app with activator run command, When try load image from Public folder in Java Controller, it loads and i don't have any issue. But when i try to start app using activator start command, it did not loads. Then i googled and found some answers. There is no public folder in /target/universal. That caused the problem. How to resolve it? Where to place our static assets in 2.3.8 project? How to package it to production?

**Comment by antonini** [comment]
@sivailango... Have you checked your build.sbt as @jilen said two comments up?
I had the same problem and It worked for me.

**Comment by sivailango** [comment]
@antonini.... This is my build.sbt. When i add packageArchetype.java_server, it does not load any static assets.

import com.typesafe.sbt.SbtNativePackager._
import NativePackagerKeys._
import com.typesafe.sbt.SbtAspectj.{ Aspectj, aspectjSettings, compiledClasses }
import com.typesafe.sbt.SbtAspectj.AspectjKeys.{ binaries, inputs, lintProperties }

name := "test"

packageArchetype.java_server

version := "1.0-SNAPSHOT"

sbtPlugin := true

organization := "com.test"

name := "test"

version := "0.1"

libraryDependencies += javaWs

libraryDependencies ++= Seq(
  javaJdbc,
  javaEbean,
  cache,
  "mysql" % "mysql-connector-java" % "5.1.26",
  "org.hibernate" % "hibernate-entitymanager" % "4.2.2.Final",
  "com.typesafe.play" %% "play-jdbc" % "2.2.0" exclude("com.jolbox", "bonecp"),
  "com.jolbox" % "bonecp" % "0.8.0.RELEASE",
  "com.google.zxing" % "core" % "2.2",
  "com.google.zxing" % "javase" % "2.2",
  "commons-codec" % "commons-codec" % "1.7",
  "commons-codec" % "commons-codec" % "1.6",
  "org.apache.commons" % "commons-email" % "1.3.2",
  "org.apache.commons" % "commons-io" % "1.3.2",
  "org.apache.commons" % "commons-lang3" % "3.0",
  "com.google.api-client" % "google-api-client" % "1.18.0-rc",  
  "com.google.http-client" % "google-http-client" % "1.18.0-rc",
  "com.google.http-client" % "google-http-client-jackson2" % "1.18.0-rc",
  "com.couchbase.client" % "couchbase-client" % "1.4.2",
  "com.google.code.gson" % "gson" % "2.2",
  "org.seleniumhq.selenium" % "selenium-java" % "2.41.0",
  "org.aspectj" % "aspectjtools" % "1.8.1",
  "org.julienrf" %% "play-jsmessages" % "1.6.2"
)

lazy val root = (project in file(".")).enablePlugins(PlayJava)

aspectjSettings

inputs in Aspectj <+= compiledClasses

products in Compile <<= products in Aspectj

products in Runtime <<= products in Compile

**Comment by antonini** [comment]
@sivailango As said before, you have to remove the `packageArchetype.java_server` of your build.sbt

**Comment by megazord** [comment]
Should we close this issue? I think the discussion here is more suitable for the user group.

**Comment by antonini** [comment]
I think it can be closed. Is there any FAQ or something like a migration page? It would be nice put it on a similar page.

**Comment by megazord** [comment]
@antonini, you are probably looking for these pages:

https://github.com/playframework/playframework/tree/master/documentation/manual/releases

@jroper, @cchantep, @benmccann, could you please closes this issue?
