### ISSUE TITLE
Play Evolutions from SBT Subdependencies

### ISSUE THREAD

**Issue by jclyons** [playframework/playframework#3522]
We are managing a quite large Play Scala project that is growing larger, and we've decided to separate out certain common subdependencies into their own repositories/projects/sbt artifacts. The problem is that these subdependencies often have their own evolutions to run, and we want to run these evolutions from subdependencies in any top-level projects that require them without reproducing the evolution scripts in the top-level project's source tree. This is primarily because if we change a subdependency's schema we really don't want to have to manually  change the evolutions of all inheriting projects.

So a couple of questions:

1) Is this currently possible within Play Framework without modifying the framework itself to run evolutions from subdependencies?

2) If, as a I suspect, the answer to #1 is no, could this be added in an upcoming version of the framework? It would really be useful definitely for us and I"m sure for other users that are growing larger and are having trouble managing their huge projects. 

3) Could hooks into the runner be created for example to mutate an evolution before it runs? Let's say I want to rename a table from one of my subdependencies but keep everything else about it the same. I would need to automate that and automate the changing of every foreign key that refers to that table as well. Creating hooks into the evolutions runner that would enable this kind of automatic transformation would be enormously helpful.

I've cross-posted this on the Play Framework Google Group.

And yes, we have considered using sbt play subprojects, but in order to properly separate the repositories we would need to use git submodules or git subtrees, both of which present problems for our workflow.

Jonathan

**Comment by robert589** [comment]
how?
