### ISSUE TITLE
npm dependency resolution issue with sbt-web

### ISSUE THREAD

**Issue by manuelbernhardt** [playframework/playframework#3565]
The sbt-js-engine makes it possible to pull in npm modules using a `package.json` file at the root of the project. This mechanism works fine (most of the time - see e.g. sbt/sbt-js-engine#20), however when the project is a Play project, it doesn't function anymore (again, maybe only in some cases).

There's a test project here demonstrating the issue: https://github.com/AlexanderDaniel/play-react-mocha

Running the `mocha` command should demonstrate the NPM dependency resolution failing.

**Comment by laguiz** [comment]
@huntc Any chance to look at this one? Using this plugin in a Play project.

**Comment by Ingwar** [comment]
@huntc Is there any progress on this issue?

**Comment by benmccann** [comment]
I believe this is fixed now with Play 2.4.2. Please test and let us know if it is not

**Comment by lqbweb** [comment]
after having spent several hours, this is not fixed in Play 2.5.1. when you do "web-assets:jseNpmNodeModules", the dependencies do get downloaded in the node_modules, but do not get populated to /target/web/public/main, (or any other place).

More people with the same problem here:

http://stackoverflow.com/questions/28265069/cant-get-sbt-web-to-work-with-npm-for-frontend-dependencies

**Comment by marcospereira** [comment]
@lqbweb could you please provide a project using 2.5.1 that shows the problem?

**Comment by centaure** [comment]
I have asked [this question](https://groups.google.com/forum/#!topic/play-framework/nxRXfdPfVVE) more than a year ago, but never got an answer. Could anyone please help me out?

I want my dependencies in package.json copied over to the public/lib folder. The [play docs ](https://playframework.com/documentation/2.5.x/Migration23
) clearly indicate this should happen when I run my project. Particularly:

     "npm can be used as well as WebJars by declaring a package.json file in the root of your project.   
     Assets from npm packages are extracted into the same lib folder as WebJars so that, from a code  
     perspective, there is no concern whether the asset is sourced from a WebJar or from an npm
     package."

Is this an error in the docs? The following gives some insight into what I am trying to do:

I would like to load the dustjs libraries from npm; so the package.json file in my project root has the following dependencies:

    "dependencies": {
      "dustjs-helpers": "^1.6.1",
      "dustjs-linkedin": "^2.6.1"
    }

However, on running my play app, (i.e. "activator run" followed by loading up my app's webpage), the package.json dependencies are not copied over into the public/lib folder. This seems to contradict the play documentation above. Am I missing something here? I am running play 2.5.2 and any help would be appreciated.

**Comment by cpoissonnier** [comment]
This issue is still happening in 2.5.10
