### ISSUE TITLE
Fix the start command. Update the docs to promote stage/dist as the way to use Play in production

### ISSUE THREAD

**Issue by Daxten** [playframework/playframework#3573]
For months nothing on the deploy side seems to work right. Play was one of the easiest deployable applications imo, but now most of it doesn't work anymore.

All tested on play 2.3.6 with java 1.6 on an ubuntu server via ssh

commands tested with activator, sbt and start command
-Dmyconfig=true -> doesn't change the config (tested inside the global.scala)
-Dconfig.resource=prod.conf -> IO Error
-Dconfig.file=./conf/prod.conf -> Works, but myconfig is still not set (tested inside the global.scala)

is start not supported for deploying anymore and stage is the new way to go?

**Comment by marcospereira** [comment]
@jroper 

I think #4194 fixes this issue. Please, reopen if necessary. :-)
