### ISSUE TITLE
Warnings when missing included conf files

### ISSUE THREAD

**Issue by tikurahul** [playframework/playframework#3577]
Sometimes `conf` files can include other `conf` files. If the included `conf` file was missing / not resolved can you please log a warning? That way we can tell easily which `conf` files failed to get included.

**Comment by marcospereira** [comment]
Closing. This should be an issue at https://github.com/typesafehub/config.

**Comment by mkurz** [comment]
Actually #6954 upgrades Typesafe Config to version 1.3.1 which adds the `include required("foo")` syntax - which fails when a config can't be found. This may be of use for @tikurahul
