### ISSUE TITLE
Sample Java project errors when running IntegrationTest in Eclipse

### ISSUE THREAD

**Issue by jschulz79** [playframework/playframework#3604]
I am following the Java Tutorial and created a new Play app with activator new play-java

I then ran the eclipse command to create a project and imported it to Eclipse.

When running the IntegrationTest.java file as a JUnit test in Eclipse, I am getting:

 java.io.IOException: Unable to download JavaScript from 'http://localhost:3333/assets/javascripts/hello.js'

It seems to run ok from Play Console test command.

I read the similar issue for IDEA about adding the line:

unmanagedResourceDirectories in Test <+= baseDirectory ( _ /"target/web/public/test" )

to the build.sbt file, but that did not work for me.

I can see the hello.js file in the target/web/public/test directory.

**Comment by benmccann** [comment]
We fixed multiple issues in sbteclipse that would have stopped this from working before. Use the latest version of sbteclipse by adding the following to your `project/plugins.sbt` and then running `activator eclipse` and refreshing your project in Eclipse:

    addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "3.0.0")

Let me know if that fixes this issue or if there are still remaining problems left.
