### ISSUE TITLE
application.conf always required - even when blank

### ISSUE THREAD

**Issue by huntc** [playframework/playframework#3609]
Even if no default overrides are required then an empty `application.conf` is required. This tripped me up when creating a Play project from scratch (useful for when demo-ing Play).

**Comment by richdougherty** [comment]
The behaviour, as of #4203, is for both prod and dev mode to require `application.conf`.

If anyone wants to change this, we need to edit the configuration loading that happens in `ProdServerStart`, `DevServerStart` and `ApplicationLoader`. It's changeable by passing a different flag to the `Configuration.load` method.

**Comment by jroper** [comment]
Actually, it seems to be the opposite, the `allowMissingApplicationConf` flag is being ignored, and `true` is always been passed:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/Configuration.scala#L72

**Comment by jroper** [comment]
PR here: https://github.com/playframework/playframework/pull/4376

**Comment by richdougherty** [comment]
Thanks for fixing this up. There are quite a few errors. To fix the errors I think the `Configuration.load(Environment)` method (called by `GuiceApplicationBuilder`) needs to default to `allowMissingConfig = true` when the `Environment`'s mode is `Test`.
