### ISSUE TITLE
[2.3.6] Changing files in assets and public is slow

### ISSUE THREAD

**Issue by Naddiseo** [playframework/playframework#3615]
The first page refresh after changing a file in assets or public takes ~5 seconds. Play doesn't say that it reloads, but I can see from `top` that java is doing something. Is there a way to tell play to completely ignore those directories? 

Might be related to #2905.

**Comment by ornicar** [comment]
It does not *reload*, but it does *restart* the application. While it's ok for a hello world app, some real life applications (in my case, http://lichess.org) can take up to 10s to restart.

I'm at the point where I have to `stage` and start the application when I want to make CSS changes, to prevent restarts. Then back to sbt watch to make scala changes.

So to be clear, when touching something in `public/`:

- play **does not** compile scala or java sources
- play **does not** display `--- (RELOAD) ---`
- play **does** restart the application, and it can be very slow

It can be reproduced with a fresh application with latest play build.

**Comment by jroper** [comment]
@ornicar Do you see the same behaviour when you run `~run` vs `run`?  The difference between `~run` and `run` is that `run` uses Play's custom very efficient file watching to detect changes, but `~run` uses sbts resource hungry polling based file watching to detect changes.  Both give you hot reloads when you make a code change.  I recommend always using `run`.

**Comment by ywelsch-t** [comment]
We are having a similar issue in a large play 2.3.6 application:

- touching a JavaScript / CSS file in the "public" folder does not restart the application (good!)
- touching a JavaScript / CSS  file in the "app/assets" folder does restart the application. Why is a restart necessary in that case? (bad!)

Same thing occurs independently of whether run or ~run is used.

**Comment by jroper** [comment]
@ywelsch-t Are you using sbt-web 1.1 or 1.0?

**Comment by pvlugter** [comment]
I've been trying to reproduce these issues, but haven't had any luck. If someone could create a sample application that demonstrates the reloading issues that would be really useful.

**Comment by ywelsch-t** [comment]
Thank you for responding so fast! Fortunately, our issue is unrelated to this ticket. I narrowed it down to the following bad lines in the build script:
```
unmanagedResourceDirectories in Compile <+= baseDirectory / "app",
excludeFilter in unmanagedResources := "*.java",
```

One solution is to extend the excludeFilter, for example:
```
excludeFilter in unmanagedResources := "*.java" || "*.js",
```

We can happily report now that asset reloading works as intended ;-)
