### ISSUE TITLE
Provision to specify the directory for a db from where evolutions need to be run

### ISSUE THREAD

**Issue by sharbel-clearfood** [playframework/playframework#3624]
Currently evolutions are run from a folder with the same name as the db in conf/evolutions, ie. conf/evolutions${db}. 

In our case, we have a requirement where the scripts to be run changes depending on some deployment scenarios. Currently we are managing by copying the respective files into the default folder before the evolutions are run but this is creating other problems in productions. Morover in development, we want to run multiple play instances connecting to different db's with different evolutions. So copying to default folder is not working out as a solution.

So, is it possible to add a property that can be used to define a different folder from where evolutions need to be run?

**Comment by cchantep** [comment]
Closed as inactive and not immediately actionable.
