### ISSUE TITLE
Csrf Documentation

### ISSUE THREAD

**Issue by ErunamoJAZZ** [playframework/playframework#3672]
Hi.

In https://www.playframework.com/documentation/2.4.x/ScalaCsrf , _"Getting the current token"_ secction, the documentation say:

> The current CSRF token can be accessed using the `getToken` method. It takes an implicit `RequestHeader`, **so ensure that one is in scope**.

I really dont understood this until I found a example in: http://nickcarroll.me/2013/02/11/protect-your-play-application-with-the-csrf-filter/

Pls, add the

> @(signInForm: Form[(String,String)])**(implicit token: play.filters.csrf.CSRF.Token)**

to documentation. Very thanks.

**Comment by wsargent** [comment]
Closed via #6428
