### ISSUE TITLE
Fix hardcoded references to conf directory

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#3677]
EbeanDynamicEvolutions and FakeKeyStore have hardcoded references to the conf directory:

[./src/play-java-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java](https://github.com/playframework/playframework/blob/master/framework/src/play-java-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java):

```
File evolutions = environment.getFile("conf/evolutions/" + key + "/1.sql");
Files.createDirectory(environment.getFile("conf/evolutions/" + key));
```

[./src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala](https://github.com/playframework/playframework/blob/master/framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala):

```
val GeneratedKeyStore = "conf/generated.keystore"
```

**Comment by wsargent** [comment]
Still a thing, but should be in playframework/play-ebean

https://github.com/playframework/play-ebean/blob/master/play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java#L61
