### ISSUE TITLE
play `dist` command generates a broken bash script (2.3.*)

### ISSUE THREAD

**Issue by tsvetanYordanov** [playframework/playframework#3715]
This bug was noticed when our webapp, which uses play and sbt made the switch from play 2.2.* to 2.3.3 . We are currently up to 2.3.6 and the bug is still persistent. 
The source of the problem seems to be coming from the run() function of the auto-generated script. 
There is a call to the execRunner operation which takes a java command along with a java_opts and java_args array.

The passing of ${java_args[@]} without adding the double string quotes around it makes java get confused and tries to pass all the arguments as a single one, the error looks like this:

2014-11-27 16:24:24,150 - DEBUG: 74 [application] - main: Play application startup hook running []
2014-11-27 16:24:24,165 - INFO : 93 [play] - main: Application started (Prod) []
Oops, cannot start the server.
java.lang.NumberFormatException: For input string: "some_value some_prop=some_value some_prop=some_value..."

We've managed to find a workaround by modifying our script after each generation of it, but it is a manual a tedious task that should not be needed.

**Comment by marcospereira** [comment]
@tsvetanYordanov could you please test against Play 2.4.0-RC1. A lot of things have changed since you opened this issue, including an upgrade of sbt-native-packager.

**Comment by wsargent** [comment]
Closing from lack of response -- please reopen if this still happens.
