### ISSUE TITLE
unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.5a: not found in play 2.4.0-M2

### ISSUE THREAD

**Issue by zarinfam** [playframework/playframework#3716]
I have got this error when i configure play project to use 2.4.0-M2, but when change it to 2.4.0-M1, it works good without any error.

**Comment by francisdb** [comment]
Add this to your sbt build

```sbt
resolvers += "Scalaz Bintray Repo" at "http://dl.bintray.com/scalaz/releases"
```

see https://github.com/etorreborre/specs2/issues/295

**Comment by superyonjan** [comment]
I am still having problem resolving `scalaz` in my Play application.
 
    [error] (*:update) sbt.ResolveException: unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.6a: not found

plugins.sbt
 
    resolvers += "Scalaz Bintray Repo" at "http://dl.bintray.com/scalaz/releases"

build.sbt
 
    libraryDependencies ++= Seq (
	jdbc,
	"joda-time" % "joda-time" % "2.7",
	"org.joda" % "joda-convert" % "1.7",
	"com.typesafe.play" %% "play" % "2.3.7",
	"org.postgresql" % "postgresql" % "9.3-1100-jdbc4",
	"com.h2database" % "h2" % "1.4.185" % "test",
    "com.typesafe.play" %% "play-slick" % "0.8.0-RC1",
    "com.nw.example" %% "pingo-domain" % "0.1.0-SNAPSHOT",
    "org.specs2" %% "specs2-core" % "3.1" % "test"
   )
    
    scalacOptions in Test ++= Seq("-Yrangepos")
