### ISSUE TITLE
Add Result.withDateHeaders method

### ISSUE THREAD

**Issue by maxcom** [playframework/playframework#3724]
Play provides no convenient way to write http header with date in result. Servlet API has `HttpServletResponse.addDateHeader` method for that. I think that is is good to have `withDateHeaders(headers: (String, DateTime)*)` method in `Result` that would add headers with properly formatted date. 

Please tell what you think. I can contribute code that adds this method.

**Comment by megazord** [comment]
Will PR #4214 fix issues?

**Comment by maxcom** [comment]
Partially. #4214 focuses only on "Date" header. I also need function to format "Last-Modified" header.

**Comment by maxcom** [comment]
Done in #4214
