### ISSUE TITLE
Chunks.Out.onDisconnected() callback is never getting called

### ISSUE THREAD

**Issue by krispypen** [playframework/playframework#3728]
This may be related to #872 which is closed a year ago.

With the latest play-java version 2.3.7, it's still a problem, also tried 2.3.2 and also has the problem, looks like a race condition.

```
public static Result index() {
		Chunks<String> chunks = new StringChunks() {

			// Called when the stream is ready
			@Override
			public void onReady(Chunks.Out<String> out) {
				System.out.println("ready");
				out.onDisconnected(new F.Callback0() {

					@Override
					public void invoke() throws Throwable {
						System.out.println("disconnect invoked");
					}
				});
				out.write("ok\n");
				try {
					Thread.sleep(10000);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
				out.write("10 seconds later\n");
			}
		};
		try {
			Thread.sleep(5000);
			System.out.println("5 seconds later");
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		return ok(chunks);
}
```

Problems: 
* When you do 'curl -i "http://localhost:9000/"' and then close it before 5 seconds, the disconnect callback WILL NEVER be executed.
* When you do 'curl -i "http://localhost:9000/"' and then close it between 5 and 15 seconds, the disconnect callback WILL BE executed but always after 15 seconds, so only after the out.write happened.
* When you do 'curl -i "http://localhost:9000/"' and then close it after 15 seconds, the disconnect callback WILL NEVER BE executed.

For the 3rd problem we can work arround it by writing dummy content every 30 seconds to the out channel, but for the first problem you can absolutely never know if the socket is closed, the write to the channel just succeeds even if the curl is closed.

I'm using thread.sleep in the example to make it easier for debugging.

You can also check out the test project: https://github.com/krispypen/chunkdebugger which is a fresh play-java project where only the app/controllers/Application.java is changed.

**Comment by krispypen** [comment]
Is this already verified? :)

**Comment by bakie** [comment]
@jroper can someone verify this ? I tried this with 2.4.3 and the problem is still there.

**Comment by dimitrizetzsche** [comment]
Finally someone who has the same problem. I'm fighting with it for several months. Can someone look into it!?

**Comment by jroper** [comment]
`Chunks` is actually now deprecated in Play master, it's been replaced by Akka streams, and this bug is almost 100% likely to be in the Play code for handling `Chunks`, so won't affect Akka streams. Hence, it's not likely that any of the core Play contributors are going to look into this because replacing with Akka streams already fixes it - I'd recommend if you need it fixed, look into it yourself.
