### ISSUE TITLE
[2.2.4] Syntax errors in IntelliJ 14 Ultimate after importing a project with SBT

### ISSUE THREAD

**Issue by kflorence** [playframework/playframework#3754]
Similar to #1784, but doesn't seem to be related to the `sbt-idea` plugin. Importing a play version 2.2.4 project in IntelliJ 14 Ultimate using the `Import project from external model (SBT)` functionality (including sources and docs) along with the `Scala` plugin (which now has bundled Play support) results in a project with missing routes and default imports inside of Twirl templates.

It is possible that there my be some additional configuration we are missing that is required when upgrading from using `sbt gen-idea` and IJ 12 Ultimate. It also may be the case that the version of Play we are using is simply too old for this stuff to work correctly, I'm okay either way, I just want to know what the overall problem is.

**Comment by chrisjenx** [comment]
I'm seeing this too. Play is happy to compile, its intellij/sbt plugin issue.

**Comment by megazord** [comment]
This is not happening with IntelliJ 14.1 and Scala plugin 1.4.15.

I think we can close this issue.

**Comment by chrisjenx** [comment]
This happened to me on 14.1 + Plugin 1.4.15.

**Comment by kflorence** [comment]
We have just finished upgrading to Play 2.3.8 and syntax highlighting has improved greatly. There are still problems with reverse routing -- I'm not sure if this is a problem with the IntelliJ Scala plugin or Play itself, but all of the other issues are most definitely related to the IntelliJ Scala plugin.

@jroper I remember seeing some other threads about reverse routing issues, if that's being handled elsewhere I think this can be closed out.

**Comment by jroper** [comment]
Well, the issue with routes was a bug in sbt-idea, but changes we've made in Play 2.4 have meant that bug no longer should impact reverse routes.
