### ISSUE TITLE
Play using an older version of org.reflections

### ISSUE THREAD

**Issue by chanan** [playframework/playframework#3755]
Hello,

Can the version of org.reflections be upgraded to 0.9.9 from 0.9.8 - the Api is not the same, this forces plugin writers to use the older version 0.9.8 which is much slower. Causing unit tests to take a very long time to finish.

**Comment by benmccann** [comment]
Fixed here: https://github.com/playframework/playframework/commit/a7e9e74bb1f508ed64882b6d868cf173138ee845

It would be appreciated if you would be able to test.

Also, if you are interested in helping to improve this code, it could use a unit test.
