### ISSUE TITLE
Concurrent.broadcast generates ClosedChannelException after client disconects

### ISSUE THREAD

**Issue by ayashjorden** [playframework/playframework#3779]
When using Concurrent.broadcast to create an (Enumerator,Concurrent.Channel), we assign the enumerator to the response for the client(s) to use.
On the event that one of the connected clients disconnects(either by navigating out of the page or other) and we still publish messages to the channel, we get a 'java.nio.channels.ClosedChannelException'.

---

Play version: 2.3.7
Java version: 1.7.0_65
OS: ubuntu 14.04

---

Code example:

---

``` scala
package controllers

import _root_.util.DualPlayLogger
import play.api.libs.concurrent.Execution.Implicits.defaultContext
import play.api.libs.iteratee.Concurrent.Channel
import play.api.libs.iteratee.{Concurrent, Enumerator, Iteratee}
import play.api.libs.json._
import play.api.mvc.{Controller, WebSocket}

object WebSocketController extends Controller with DualPlayLogger{

  val perPageBroadCast = collection.mutable.Map.empty[String,(Enumerator[JsValue],Channel[JsValue])]
  def getBroadcastSocket(page:String) = WebSocket.using[JsValue] { implicit request =>
    appLog info s"Got WebSocket request for page [$page]"
    val br = perPageBroadCast.getOrElseUpdate(page, Concurrent.broadcast[JsValue])
    val in = Iteratee.foreach[JsValue](m => appLog.info(m.toString())).map { _ => appLog.info("Disconnected")}

    (in,br._1)
  }

  def publish(socketKey:String,msg:JsValue): Unit = perPageBroadCast get socketKey match {
    case Some(channel) => channel._2.push(msg)
    case None          => appLog debug s"No channel found for $socketKey"
  }
}

publish messagees scheduler:(on another controller that handles client's request for pages)
readTask = actorSystem.scheduler.schedule(3 seconds,1 second,new Runnable {
        override def run(): Unit = WebSocketController.publish(RenderTokens.LIVE,liveData)
      })
```

---

In order to reproduce the exception:
1. Create an application that uses the above code to provide websocket objects upon client request.
2. upon first websocket request, schedule a publish message task with delay of 1 second
   system.scheduler.schedule(3 seconds,1 second,new Runnable { override def run(): Unit = WebSocketController.publish("live",<SOME_JsValue>)})
3. connect mutiple client to the application(by opening multiple tabs or browsers)
4, disconnect one client by closing its browser's tab/window.

Full stack-trace

---

```
 [play] java.nio.channels.ClosedChannelException
 [play]     at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
 [play]     at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128)
 [play]     at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
 [play]     at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
 [play]     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
 [play]     at org.jboss.netty.channel.Channels.write(Channels.java:725)
 [play]     at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
 [play]     at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
 [play]     at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
 [play]     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
 [play]     at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
 [play]     at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
 [play]     at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.handleDownstream(HttpPipeliningHandler.java:106)
 [play]     at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
 [play]     at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
 [play]     at org.jboss.netty.channel.Channels.write(Channels.java:704)
 [play]     at org.jboss.netty.channel.Channels.write(Channels.java:671)
 [play]     at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248)
 [play]     at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$play$core$server$netty$PlayDefaultUpstreamHandler$$iteratee$1$1.apply(PlayDefaultUpstreamHandler.scala:351)
 [play]     at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$play$core$server$netty$PlayDefaultUpstreamHandler$$iteratee$1$1.apply(PlayDefaultUpstreamHandler.scala:348)
 [play]     at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503)
 [play]     at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503)
 [play]     at play.api.libs.iteratee.Concurrent$$anonfun$1$$anonfun$apply$8.apply(Concurrent.scala:117)
 [play]     at play.api.libs.iteratee.Concurrent$$anonfun$1$$anonfun$apply$8.apply(Concurrent.scala:114)
 [play]     at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670)
 [play]     at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670)
 [play]     at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
 [play]     at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
 [play]     at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
 [play]     at scala.concurrent.impl.Future$.apply(Future.scala:31)
 [play]     at scala.concurrent.Future$.apply(Future.scala:485)
 [play]     at play.api.libs.iteratee.RunQueue.execute(RunQueue.scala:123)
 [play]     at play.api.libs.iteratee.RunQueue.schedule(RunQueue.scala:116)
 [play]     at play.api.libs.iteratee.RunQueue.schedule(RunQueue.scala:66)
 [play]     at play.api.libs.iteratee.RunQueue.scheduleSimple(RunQueue.scala:88)
 [play]     at play.api.libs.iteratee.Concurrent$$anon$6.schedule(Concurrent.scala:179)
 [play]     at play.api.libs.iteratee.Concurrent$$anon$6.push(Concurrent.scala:181)
 [play]     at play.api.libs.iteratee.Concurrent$Channel$class.push(Concurrent.scala:50)
 [play]     at play.api.libs.iteratee.Concurrent$$anon$6.push(Concurrent.scala:176)
 [play]     at controllers.WebSocketController$.publish(WebSocketController.scala:22)
 [play]     at controllers.Application$$anonfun$read$1$$anon$1.run(Application.scala:87)
 [play]     at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242)
 [play]     at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
 [play]     at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
 [play]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 [play]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 [play]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 [play]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Thanks in advance for any idea/guidance/soluation
Yarden

**Comment by jroper** [comment]
Is it just the first message that you send after disconnecting that throws this exception, or is it every message?

You would be much better off using Akka for this.

**Comment by ayashjorden** [comment]
Is it just the first message after disconnecting that throws this exception, while other sockets continue regularly.

It's still kind of buggy that a broadcaster can't handle disconnections nor have the API to pass some callback to handle disconnections.

I can do solve it with 'acceptWithActor' and write the broadcast logic myself, but this won't solve the issue Concurrent.broadcast disconnection handling, is it !?

**Comment by jroper** [comment]
This has nothing to do with the broadcast enumerator.

There's probably an improvement we could put in Play, but at the end of the day, exceptions like this are impossible to get rid of.  There is no way to know for sure, when you send a message, whether the connection is still open.  Even if you check just before you send, the connection could still be closed by the remote end in between the check and when you send.

Are you actually seeing any negative effects of this, or are you just seeing the exception?

**Comment by ayashjorden** [comment]
The only negative effect is the exception in the logs.

In my scenario, the socket gets closed gracefully, meaning that when the browser window invokes 'WsSocket.close()' before unloading the page.
 
Can't the broadcaster(Enumerator or channel) somehow detect the close event sent by the websocket from the client side when the user closes the socket(either by navigating out of the page or other)?

Thanks,
Yarden

**Comment by jroper** [comment]
Sort of. The iteratees API doesn't allow sending close events back to the enumerator, the enumerator can't find out if a socket is closed until it attempts to write to it.  What we could do is in the implementation of the iteratee that consumes the iterator, we could check if the socket is open first, and if it's closed, just ignore that chunk, and go into the EOF state.

**Comment by ayashjorden** [comment]
Sounds like a plan!

Thanks,
Yarden

**Comment by ayashjorden** [comment]
one last thing, Is there a way for  me to catch the exception so I can just print a nice message instead of the StackTrace?

**Comment by jroper** [comment]
Possibly, but it wouldn't be straight forward.  You'd have to write an enumeratee that wrapped every `k` callback that came out of the iteratee.

**Comment by fdurden** [comment]
Hi. So if we're better off using Akka for this, how does one implement a simple broadcast scenario like the one below with actors, where you can send messages to the client (here using channel) from outside the webSocket method:

```scala
val (output, channel) = Concurrent.broadcast[JsValue]
def webSocket = WebSocket.using[JsValue] { request =>
  val in = Iteratee.ignore[JsValue]
  (in, output)
}
```

Thanks!

**Comment by jroper** [comment]
When the websocket connects, the actor handling the websocket sends a subscribe message to the broadcasting actor.  The broadcasting actor keeps a reference to the sender of the subscribe message in a list of subscribers, and sends all messages that it has to broadcast to that list.

Or, even simpler, you could use the Akka distributed pub sub extension, and then you can distribute your app, you'll get broadcast over an entire cluster of Play instances working for free:

http://doc.akka.io/docs/akka/snapshot/contrib/distributed-pub-sub.html

**Comment by chabashilah** [comment]
Hi. I had almost same issue with this post.
My question is how to check if the socket is open in the implementation of the iteratee that consumes the iterator.
I tried to find the method to check connection status but I couldn't.

Thanks!

**Comment by mjrussell** [comment]
I had the same problem as the submitter of the issue. Understanding that down the line Actors are the right way to go, I was still able to get rid of the exception issue by using the asynchronous version of WebSockets.

I changed WebSocket.using to WebSocket.tryAccept and wrapped the Iteratee with a Future. Obviously be mindful of any potential concurrency bugs.

**Comment by martende** [comment]
I am using Actors aproach and in closing state receiving the exception whith the same callstack

**Comment by urquilla** [comment]
+1 Also had to fight with this issue, it was pretty unexpected not being able to catch it

**Comment by ilanbiala** [comment]
Is there still no fix available for this?

**Comment by kjozsa** [comment]
I'm also using the Actor approach and get this exception too. I understand the reason but would like to get it handled in a more graceful way, it definetely looks like an error while it's pretty much normal..

**Comment by kristian-lange** [comment]
Also here. Using Akka. Can't catch. Filling my logs with exceptions. :(

**Comment by sasinda** [comment]
+1
cant catch exception,( anyway I m having a manual broadcast list and removing the connection from list in the close event, but there will be a problem if the connection was not removed and some how written.)

**Comment by vicaba** [comment]
I'm using WebSockets with Actors. When the client disconnects, a java.nio.channels.ClosedChannelException is thrown. I don't send any messages through the WebSocket at the server side. Neither before or after the client disconnects. This issue talks about an Exception thrown when the serverside tries to write to closed clients, but my server does not. Is it related to this issue throwing this exception then?

**Comment by cquiroz** [comment]
This affects me too, Ideally there should be a way to at least hide the stack trace

**Comment by JosephSe** [comment]
D'oh !!! I'm having it too
+1

**Comment by mkurz** [comment]
This is about Play 2.3.x using Enumerator, closing.
