### ISSUE TITLE
views.html.helpers are coupled with the i18n API that relies on runtime DI

### ISSUE THREAD

**Issue by julienrf** [playframework/playframework#3781]
See [here](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/views/helper/Helpers.scala#L20) for instance.

A solution would be to take an implicit `Messages` instead of an implicit `Lang`.

**Comment by cchantep** [comment]
Covered by #3782 I would say

**Comment by julienrf** [comment]
Yes, it is.
