### ISSUE TITLE
Update logging settings and docs for Akka 2.4

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#3795]
Once Akka 2.4 is released.

Follow recommendations for Akka Slf4j logging:
* Change `loglevel` to `DEBUG`.
* Add `loging-filter` for Slf4j.

**Comment by benmccann** [comment]
@richdougherty should we take this off the 2.4.0 milestone since we're no longer waiting for Akka 2.4 to be released?

**Comment by richdougherty** [comment]
Agreed. I've removed the milestone label.

**Comment by wsargent** [comment]
Akka 2.4.1 is out as of November 27 2015

**Comment by mkurz** [comment]
Shouldn't it get the 2.5 milestone?

**Comment by wsargent** [comment]
Don't we already have this? https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/resources/play/reference-overrides.conf#L39

**Comment by richdougherty** [comment]
Yeah, I think you just need to set debug.
