### ISSUE TITLE
Play should not use packageArchetype.java_server

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#3801]
@muuki88 says `packageArchetype.java_server ++` [in Project.scala](https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/main/scala/play/Project.scala#L34) overrides everything you love.

@muuki88 what do you suggest we replace it with?

@jsuereth looks like you added a line we have a question about in playframework/playframework@f64336d. Do you know more about it? Sounds like from the commit comment that it was maybe meant to be temporary?

**Comment by jroper** [comment]
@benmccann Play must use that, that is the mechanism for bringing in the base configuration that Play can then modifies for it's own purposes, if we didn't include it, all users would have to configure it in their build.sbt manually themselves, including several lines of the Play specific stuff. When we upgrade to a version of native packager that uses auto plugins, then we can replace this with just declaring a dependency on native packager in the Play AutoPlugins.requires, that will ensure that the autoplugins configuration is brought in first, and then Play is able to provide its own configuration to add to it.

**Comment by muuki88** [comment]
@jroper  is correct. However `1.0.x` sbt native packager is autoplugin ready,
so this should just be a matter of

1. removing `packageArchetype.java_server`
2. add `override def requires =  ... && JavaServerAppPackaging`

**Comment by huntc** [comment]
To use Play 2.3 with sbt-native-packager 1.0:

    enablePlugins(JavaAppPackaging, PlayScala)

...and ensure that you remove import statements with respect to the native package from your build.sbt files.

**Comment by benmccann** [comment]
I sent a PR with the suggestions contained here: https://github.com/playframework/playframework/pull/3806

**Comment by benmccann** [comment]
This is fixed now
