### ISSUE TITLE
Running Test H2 in-memory database seems to be ignoring MODE=postgreSQL

### ISSUE THREAD

**Issue by rcritt** [playframework/playframework#3804]
I was running code with an earlier version of Scala Play, 2.2.3. 
We used an H2 in-memory database with MODE=postgreSQL for the hinting.

I am finding that this is not working in Activator 2.3.7.

For a work-around I am using a standalone PostgreSQL instance for the tests.

**Comment by jroper** [comment]
Can you supply any more info? What does your configuration/code look like? What makes you think setting the mode isn't working?

**Comment by rcritt** [comment]
Hi James,

I have two code bases for this, one is the original code that runs Play
2.2.3, the other is for Play 2.3.7.

In both I had an in-memory database created with "MODE=PostgreSQL" at the
end.  I just tried the 2.2.3 version again, it works great.

One variable in all of this is we used a modified Tomcat JDBC for the
plug-in in 2.2.3.  In 2.3.7 I use the included BoneCP.

Maybe there is no issue here but it looked like I was getting the same
errors about Blobs etc whether or not "MODE=PostgreSQL" was included in the
URL.

We have the application as-follows in 2.2.3.
===
def testApp = FakeApplication(additionalConfiguration =
TestUtil.inMemoryDatabase(testDb, Map("MODE" -> "PostgreSQL")))
===

Then a map is used for that info as-follows (in TestUtil's companion
object).
===
def inMemoryDatabase(name: String = "default", options: Map[String, String]
= Map.empty[String, String]): Map[String, String] = {
    val optionsForDbUrl = options.map { case (k, v) => k + "=" + v
}.mkString(";", ";", "")

    Map(
      ("tomcatdb." + name + ".driver") -> "org.h2.Driver",
      ("tomcatdb." + name + ".url") -> ("jdbc:h2:mem:play-test" +
optionsForDbUrl)
    )
  }
===

Today, using PostgreSQL as the test database, works great, no issues.
Going forward that is what we are using post-migration.

On Mon, Jan 12, 2015 at 6:12 PM, James Roper <notifications@github.com>
wrote:

> Can you supply any more info? What does your configuration/code look like?
> What makes you think setting the mode isn't working?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playframework/playframework/issues/3804#issuecomment-69665928>
> .
>



-- 
=================
Rollin Crittendon

**Comment by jroper** [comment]
Can you provide a test project that reproduces the issue?

**Comment by rcritt** [comment]
Note: I have sent further info offline on this issue with you just now.

**Comment by megazord** [comment]
Can we close this issue (given the new API to test with databases)?

**Comment by jroper** [comment]
@megazord I sent you an email the other day, just wondering if you got it, maybe I used the wrong email address.  If you didn't get it, please email me at james at typesafe.com.

**Comment by megazord** [comment]
@jroper just sent you a reply!
