### ISSUE TITLE
In Twirl @{Messages("key")(lang)} does not always parse

### ISSUE THREAD

**Issue by rcritt** [playframework/playframework#3807]
I have a line in a Twirl template that is a combination of parameters.  At the start of the line we have a Messages function call like the following.
`
@{Messages("keyA")(lang)}
`

Later on we have, on that same line, some other @Messages, like the following.
`
@{Messages("keyB")(lang)}
`

This stuff worked fine in 2.2.3 of the Play Framework.

In the 2.3.7 version of the Play Framework some of the messages calls after the first one return the following error.
`
type mismatch;
 found   : String
 required: Int
`

My current solution is to just call the following sort of thing.  In addition I will look into having the lang be implicit instead of explicitly passed.
`
@Messages("keyB")
`

**Comment by jroper** [comment]
Could you provide a template that reproduces this, plus the full error output?

**Comment by rcritt** [comment]
Note: I have sent further info offline on this issue with you just now.

**Comment by pvlugter** [comment]
Hi @rcritt. This looks like a difference between the old and new twirl parsers. You can enable the old parser again for now with this sbt setting:

```scala
TwirlKeys.useOldParser := true
```

**Comment by pvlugter** [comment]
With the new parser, Twirl is creating Scala code where the `@{Messages ...` becomes a parameter to the apply method for something before it, which in this case is a String.

A workaround you can use in the templates for now is to use braces for all the `@`s in this line. So where there is this in your example:

```scala
@text1 @java.net.URLEncoder.encode("\n\n","UTF-8")@{Messages("b")(lang)}
```

it should work with this:

```scala
@{text1} @{java.net.URLEncoder.encode("\n\n","UTF-8")}@{Messages("b")(lang)}
```

**Comment by rcritt** [comment]
Using more @{} bracketing did help on this, thank you very much.

**Comment by pvlugter** [comment]
Created an issue under twirl for this: https://github.com/playframework/twirl/issues/62
