### ISSUE TITLE
Failing to import Play Java project with build errors in Eclipse

### ISSUE THREAD

**Issue by dotta** [playframework/playframework#3818]
To import a Play project in Eclipse one needs first to generate the required Eclipse metadata files via the `eclipse` command. The `eclipse` command triggers a project's compilation, as both the templates and routes files need to be compiled prior to import the project (otherwise build errors may be reported once the project is opened in Eclipse).
However, if a Play project cannot be compiled, it should still be possible to import the project in Eclipse. As explained in the [Play documentation](https://www.playframework.com/documentation/2.3.x/IDE), this can be achieved by adding the following setting in the `build.sbt`:

`EclipsePlugin.EclipseKeys.preTasks := Seq()`

Unfortunately, it doesn't work for a Play Java project.

The reason why it doesn't work is the definition of `addScalaLib` in [PlayEclipse.scala](https://github.com/playframework/playframework/blob/eb2267cd2fa58e6a510a0b086e9c395ef4f69fd6/framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala#L56), in particular the following expression `dependencyClasspath in Runtime`, which forces compilation of the project.

To get around the problem, add the following settings in the `build.sbt`:

```
EclipseKeys.classpathTransformerFactories := EclipseKeys.classpathTransformerFactories.value.init
EclipsePlugin.EclipseKeys.preTasks := Seq()
```

The fix should be as simple as changing `dependencyClasspath in Runtime` to `dependencyClasspath in Compile` [here](https://github.com/playframework/playframework/blob/eb2267cd2fa58e6a510a0b086e9c395ef4f69fd6/framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala#L58).

However, I really can't see why we need the `addScalaLib` transformer for a Play Java project (see [here](https://github.com/playframework/playframework/blob/eb2267cd2fa58e6a510a0b086e9c395ef4f69fd6/framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala#L111)). Could it be that sbteclipse used to remove the scala library from the Eclipse classpath entries for a plain Java project? cc-ing @jsuereth @hseeberger who may help clarifying this point.

**Comment by lutzh** [comment]
For the time being, I think we should update the documentation in https://github.com/playframework/playframework/blob/master/documentation/manual/gettingStarted/IDE.md 
For simplicity, can we tell people to always include the
`EclipseKeys.classpathTransformerFactories := EclipseKeys.classpathTransformerFactories.value.init`
line, or will it have an impact on Scala projects and should only be used in Java projects?

**Comment by dotta** [comment]
@lutzh The workaround should be used only for Java Play projects
