### ISSUE TITLE
Security filter shouldn't set empty headers

### ISSUE THREAD

**Issue by ejain** [playframework/playframework#3826]
When including the `play.filters.headers.SecurityHeadersFilter`, you can override, but not remove any of the 5 headers that are set. For example:

`play.filters.headers.frameOptions=null` -> `X-Frame-Options: DENY` (default value)
`play.filters.headers.frameOptions=""` -> `X-Frame-Options:`

Instead of including a header with no value, the header could simply be left out in the latter case.

**Comment by cchantep** [comment]
PR welcomed

**Comment by wsargent** [comment]
This is working as designed.  Per https://www.playframework.com/documentation/2.3.x/SecurityHeaders

"NOTE: Because these are security headers, they are “secure by default.” If the filter is applied, but these fields are NOT defined in Configuration, the defaults on the filter are NOT omitted, but are instead set to the strictest possible value."

You can use "ALLOW-FROM uri" or SAMEORIGIN  to disable the clickjacking protection conditionally.

**Comment by ejain** [comment]
`X-Frame-Options: DENY` is actually the only security header I'm interested in, but I haven't enabled it, because I can't do so without pulling in the whole shebang of headers, some of which ('Content-Security-Policy') end up being quite verbose. Makes sense to default to the most restrictive values, but should be able to exclude a header! Browsers btw seem to ignore security headers with empty values.

**Comment by jroper** [comment]
If you only want to add that one header, why not just write a filter to do it yourself?

```scala
Filter { (next, request) =>
  next(request).map(_.withHeaders(
    "X-Frame-Options" -> "DENY"
  ))
}
```

**Comment by ejain** [comment]
I would, if you could do this with Java...

**Comment by jroper** [comment]
In Java it's even simpler, implement `GlobalSettings.onRequest` like so:

```java
    public Action onRequest(Request request, Method actionMethod) {
        return new Action.Simple() {
            public F.Promise<Result> call(Context ctx) throws Throwable {
                ctx.response().setHeader("X-Frame-Options", "DENY");
                return delegate.call(ctx);
            }
        };
    }
```

**Comment by ejain** [comment]
Unfortunately overriding `GlobalSettings.onRequest` doesn't appear to catch requests for static assets, like an `index.html`.

**Comment by jroper** [comment]
Ok, then add the following Scala file to your project:

```scala
package mypackage

import play.api.mvc._
import play.api.libs.concurrent.Execution.Implicits._

class DenyFrames extends EssentialFilter {
  def apply(next: EssentialAction) = EssentialAction { req =>
    next(req).map(_.withHeaders(
      "X-Frame-Options" -> "DENY"
    ))
  }
}
```

And then add that as a filter in your `Global.filters` method.

**Comment by ejain** [comment]
Thanks for the suggestions, but to be honest, adding that Scala file to the project complicates life more than is worth just for adding a header (would have to set up Scala IDE, maybe get some more RAM)...

**Comment by jroper** [comment]
Why would you have to set up Scala IDE?  You don't need Scala IDE to write Scala code, they are just text files.  Note that the routes file and scala templates both compile to Scala, and Eclipse has no problem with that, with or without Scala IDE.

**Comment by ejain** [comment]
Eclipse doesn't mind `.scala` files in the `app` folder, but tends to clear out the corresponding `.class` files from `target/scala-2.11/classes/`. Once this happens, a full clean build is required. This is not an issue for the routes file etc, which are compiled to `classes_managed`.

**Comment by jroper** [comment]
This is fixed in #4142, it's now possible to set

    play.filters.headers.frameOptions = null

While the default still remains as `DENY` if nothing (as opposed to null) is set.

**Comment by jeberdson** [comment]
> If you only want to add that one header, why not just write a filter to do it yourself?
> 
> ```scala
> Filter { (next, request) =>
>   next(request).map(_.withHeaders(
>     "X-Frame-Options" -> "DENY"
>   ))
> }
> ```



> Ok, then add the following Scala file to your project:
> 
> ```scala
> package mypackage
> 
> import play.api.mvc._
> import play.api.libs.concurrent.Execution.Implicits._
> 
> class DenyFrames extends EssentialFilter {
>   def apply(next: EssentialAction) = EssentialAction { req =>
>     next(req).map(_.withHeaders(
>       "X-Frame-Options" -> "DENY"
>     ))
>   }
> }
> ```
> 
> And then add that as a filter in your `Global.filters` method.

I am using play version 2.7

How to add this filter in Global.filters method?

**Comment by marcospereira** [comment]
@jeberdson see documentation here: https://www.playframework.com/documentation/2.7.x/ScalaHttpFilters

Moreover, our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

Best.
