### ISSUE TITLE
@OnApplicationStart fails if you disable the JPAPlugin

### ISSUE THREAD

**Issue by emilycrutcher** [playframework/playframework#3827]
You can reproduce the problem by adding the following to any application.conf
plugins.disable.1=play.db.jpa.JPAPlugin

I have a sample project showing it as well, but the zip got rejected by the issue tracker.

**Comment by jroper** [comment]
Hi @emilycrutcher, this looks like an issue with Play 1.  Issues for Play 1 are tracked here:

http://play.lighthouseapp.com/projects/57987-play-framework/overview
