### ISSUE TITLE
Suppress exception when CSRF token is missing

### ISSUE THREAD

**Issue by yeonhoyoon** [playframework/playframework#3828]
In the following code snippet in csrf.scala, `getToken` throws a `RuntimeException` when csrf token is tampered with. As the missing token is probably a result of a bad request on user's part, wouldn't it be better to suppress the exception?

```  
object Token {
    val RequestTag = "CSRF_TOKEN"

    implicit def getToken(implicit request: RequestHeader): Token = {
      CSRF.getToken(request).getOrElse(sys.error("Missing CSRF Token"))
    }
 }
```

https://github.com/playframework/playframework/blob/2.3.x/framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala#L90

**Comment by timohirt** [comment]
I also think into that direction @yeonhoyoon. Why throwing a `RuntimeException` instead of responding a `BadRequest()`?

**Comment by C1mone** [comment]
I also meet this problem in vulnerable test. Is there any recommended solution? I currently catch "Missing CSRF Token" string to return `BadRequest()`

**Comment by mkurz** [comment]
+1
A pull request would be welcome.

**Comment by mkurz** [comment]
Can we actually remove [`Token.getToken`](https://github.com/playframework/playframework/blob/2.5.0-M2/framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala#L120-L122)? It's just used twice for tests ([1](https://github.com/playframework/playframework/blob/2.5.0-M2/framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala#L89) and [2](https://github.com/playframework/playframework/blob/2.5.0-M2/framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala#L114)).
The way how to access the token is `CSRF.getToken(...);`.

/cc @richdougherty @jroper @gmethvin

**Comment by richdougherty** [comment]
I'm open to API changes if you think it would simplify things. Those methods will need to be deprecated for one release before we make them `play[private]`.

**Comment by mkurz** [comment]
I think the method isn't needed anymore. I will provide a PR which marks it deprecated.
Of course I could be wrong, so if somebody wants to keep it let know.

**Comment by gmethvin** [comment]
@mkurz Currently it's used mainly implicitly. If you have a template with an implicit `RequestHeader`, this method will be used to get the token. But I'm making some API changes in #5526 so I could also take care of this.

I think it might be okay to remove it, since there are other ways of doing the same thing (`CSRF.getToken`). I would rather not have implicits that access global state.

**Comment by mkurz** [comment]
@gmethvin I think it would be could to take care of it in #5526

**Comment by gmethvin** [comment]
@yeonhoyoon What do you mean by the token being "tampered with"? Are you referring to the token not having a valid signature? I think that should result in a CSRF check error instead of attempting to render the form.

**Comment by gmethvin** [comment]
If the form is just displaying the token currently in the session, and you have a CSRF filter installed, the token should always be regenerated if it is invalid. There really is no need to show any sort of error unless we are doing a check on a user-submitted form. We can just silently regenerate the token.

Previously we did not regenerate if the signature is invalid, but #5627 fixes this.

**Comment by gmethvin** [comment]
@yeonhoyoon I'm going to assume that my assumptions are correct and close this issue, since #5627 is merged. If you find another scenario in which the token does not exist feel free to reopen or create a new issue.
