### ISSUE TITLE
Crypto references Play.current and Play.maybeApplication

### ISSUE THREAD

**Issue by jamesward** [playframework/playframework#3839]
Should take `Application` as a param instead.

**Comment by gmethvin** [comment]
@jamesward Are you referring to 2.3.x? In 2.4 creating a `Crypto` instance should no longer require an application.

**Comment by jamesward** [comment]
Yeah, 2.3.x.  So unlikely to be fixed but thought I'd file it since I noticed it.

**Comment by jroper** [comment]
Yeah, we can't fix in 2.3.x since that would be a binary compatibility issue.  In 2.4, it's fixed.
