### ISSUE TITLE
WS client should re-sign the request upon following 302

### ISSUE THREAD

**Issue by tdrozdowski** [playframework/playframework#3841]
It would be nice if the WS client would re-sign the request when it follows a 302 (re-apply the SignatureCalculator). Otherwise, the signature calculated is likely invalid (in the case of algorithms that are based on HMAC)

Current behavior is to keep the same result from the signature calculation upon redirecting to the URL provided in the 302's Location header.  Which I'd imagine in a lot of cases will be invalid.

I understand I can turn off follow redirects and handle this myself - would be nice for it to 'just work.'

**Comment by jroper** [comment]
I'm not sure whether resigning is a good idea here.  Authenticated redirects are thwart with problems, I've found vulnerabilities in these types of APIs before that leverage redirects. The OAuth 1.0a spec makes no mention about them.  Maybe there is no vulnerability, but I think it's better to be cautious here and not allow it.

**Comment by tdrozdowski** [comment]
The protocol I implemented a SignatureCalculator for is similar to Hawk (and OAuth2 HMAC).  The APIs provided by this particular company use redirects to send us to the 'latest' version of a particular REST resource.

Would it be possible to make it optional - just like follow redirects is an option?  Or just switch the default behavior to NOT follow 302s if we're being fully cautious here.

**Comment by marcospereira** [comment]
@tdrozdowski it is already possible to configure if a request will follow redirects or not:

https://www.playframework.com/documentation/2.4.0-RC1/ScalaWS#Request-with-follow-redirects
https://www.playframework.com/documentation/2.4.0-RC1/JavaWS#Request-with-follow-redirects

@jroper I think we can close this issue.

**Comment by wsargent** [comment]
Closing -- this can happen manually and I share jroper's concerns.
