### ISSUE TITLE
Add support for enumeration  in ScalaJson

### ISSUE THREAD

**Issue by hanfeisun** [playframework/playframework#3845]
I found the ScalaJson in playframe doesn't support Enumeration natively.. It would be more elegant if ScalaJson could support enumeration type..

**Comment by gmethvin** [comment]
Enumeration is used pretty rarely these days. Normally people use case objects extending a sealed trait or class.

If we're going to do anything along these lines, it would probably be more useful to provide some tools for mapping case objects to/from strings.

That said, if you just need a format that maps your enumeration value to/from ints, you could do something like this:
```scala
import play.api.libs.json._
object WeekDay extends Enumeration {
  val Mon, Tue, Wed, Thu, Fri, Sat, Sun = Value
  implicit val format = Format[Value](Reads(_.validate[Int] map apply), Writes(v => JsNumber(v.id)))
}
```

**Comment by ottovw** [comment]
Play has some basic enum support https://github.com/playframework/playframework/pull/3101

**Comment by gmethvin** [comment]
Thanks @ottovw. Didn't realize that was already in master. I'll close this then.
