### ISSUE TITLE
Little confusion about internationalization / default lang for constraint translations

### ISSUE THREAD

**Issue by slorber** [playframework/playframework#3852]
I'm working on an english-based OS with an english-based browser, but I'm building an app in french lang only.

I wanted to be able to customize the error messages of forms (form constraints).

So I did:

```
application.langs="fr"
```

And I added a `conf/messages.fr` file with some translations, based on  `messages.default` of the sources

Unfurtunately I was unable to translate these constraints in french.

It required an additional step, adding the implicit lang to the context:

```
@(authForm: Form[Application.AuthenticateData])(implicit lang: Lang)
```

I think there's something a bit confusing here. If I want to hardcode the lang to french (temporarily or not), I should be able to do so without passing everywhere an implicit parameter I guess.

I think it may be related to the way Play select the default lang:

```
  implicit lazy val defaultLang = {
    val defaultLocale = java.util.Locale.getDefault
    Lang(defaultLocale.getLanguage, defaultLocale.getCountry)
  }
```

Maybe Play could select the JVM default locale Lang only if it is found in the `application.langs` conf?

It seems to me that if there's a single language in `application.langs` it would be better to always use this language, no matter implicit parameters being passed or not, no matter default JVM default locale.

**Comment by jroper** [comment]
@slorber If you have one language, then you should just use a `messages` file, not `messages.fr`.  `messages.fr` is only used if French is explicitly selected.

While the `defaultLang` could look at the configured application langs, in future, it won't be able to, as we're getting rid of all global state in Play.  This means there's no way for it to lookup the configuration.  Using the default locale is therefore the only option.

You can also select a default locale for the JVM explicitly using system properties when you invoke sbt/activator, using `-Duser.language=fr`.

**Comment by slorber** [comment]
ok thanks will replace `messages.fr` by `messages` then
