### ISSUE TITLE
[2.4.0-M2] CacheApi always returns None when type not provided

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#3858]
I don't think this is expected:

    cache.set("oops", "test")
    println(cache.get("oops"))
    println(cache.get[Any]("oops"))

logs the following

    None             <--- bug?
    Some(test)

**Comment by jroper** [comment]
Yeah, interesting. We probably need to check the class tag to see if it's `Any`, I don't know what `runtimeClass()` returns for `Any`, but it's probably not `Object` since that would be for `AnyRef`.

**Comment by francisdb** [comment]
Have the impression that primitives also always return None

**Comment by stephennancekivell** [comment]
Hi, I submitted a pull request.

What do you guys think, Is this fix Ok? Im a bit unsure about matching on the Nothing, but it seems to work.

https://github.com/playframework/playframework/pull/3860

**Comment by francisdb** [comment]
@stephennancekivell Looks good to me if the tests succeeds, maybe you can also add a test case for boolean (primitive) as I also had problems there

    cache.set("test", true)
    println(cache.get[Boolean]("test"))      <-- also gave me a None

**Comment by stephennancekivell** [comment]
Ok @francisdb,
I've extended the test in https://github.com/playframework/playframework/pull/3860
