### ISSUE TITLE
Play 2.3, integration tests -> BoneCPPlugin is not restartable

### ISSUE THREAD

**Issue by slorber** [playframework/playframework#3867]
When using BoneCP plugin during integration tests for DAO/Repositories, it appears that the plugin is not restartable. I don't know if it's the case above 2.3 because code seems to have changed.

I mean If you call `Play.start()`, `Play.stop()` and again `Play.start()`, the plugin won't let you borrow any connection, telling you that the connection pool has already been shutdown.

A workaroud for this is to bypass the `stop` method for tests:

```scala
import play.api.test._
import play.api.test.Helpers.inMemoryDatabase

import scala.slick.jdbc.JdbcBackend


/**
 * @author Sebastien Lorber (lorber.sebastien@gmail.com)
 */
package object repository {

  val repositoryTestFakeApp = FakeApplication(
    additionalConfiguration = inMemoryDatabase(),
    withoutPlugins = Seq("play.api.db.BoneCPPlugin"),
    additionalPlugins = Seq("play.api.db.RestartableBoneCPPlugin")
  )

  abstract class RepositoryTest extends WithApplication(repositoryTestFakeApp) {
    implicit lazy val dbSession: JdbcBackend#Session = models.QualisocialDB.createSession()
  }

}


package play.api.db {
  class RestartableBoneCPPlugin(app: play.api.Application) extends BoneCPPlugin(app) {
    override def onStop() { }
  }
}
```

This issue has already been discussed here:
https://groups.google.com/d/msg/play-framework/znFuqeRz84w/AzfVxaJoluEJ
http://stackoverflow.com/questions/22637738/multiple-play-tests-error-obtain-a-connection-from-a-pool-that-has-already-bee

**Comment by jroper** [comment]
This is by design, the entire Play application is not restartable.  You should create a new `FakeApplication` per test.

**Comment by slorber** [comment]
@jroper I also tried with creating a new FakeApplication for each test example and it does not work better. It seems the same connection pool is shared between all the FakeApplications

**Comment by slorber** [comment]
well my mistake @jroper it does not seem to be related to Play / BoneCP restart problem

Actually it's a problem you know related to `Around` in specs2. I have a subclass of WithApplication, and it seems to cause the Play runner to run twice for every example, leading the same FakeApp to start/stop/start for the same example before executing my example

**Comment by jroper** [comment]
I can't remember exactly why that happens, if it's a bug in Scala or just it behaving as specified, but it happens when a subclass of `DelayedInit` provides some initialisation code, and then something inherits from that (which is what happens when you use specs2 `Around` traits).

Basically, you need to ensure that there is no initalization code in your custom `Around`.  This means no vals, and no expressions.  So for example, let's say you have something that looks like this:

```scala
abstract class CustomWithApplication(val app: FakeApplication = FakeApplication()) extends WithApplication(app) {
  val foo = "foo"
}
```

There is some initialization code (the setting up of the `foo` field).  To remove it, change it to a lazy val or def.

**Comment by slorber** [comment]
yes thanks I used to have a `var session` here but replaced it with:

```
  def repositoryTestFakeApp = {
    val fakeApp = FakeApplication(
      additionalConfiguration = inMemoryDatabase()
    )
    //Logger.info(s"FakeApplication created for test: $fakeApp")
    fakeApp
  }


  abstract class RepositoryTest extends WithApplication(repositoryTestFakeApp) {
    implicit lazy val session = models.MySlickDB.createSession
  }
```
