### ISSUE TITLE
[Play 2.3.7] Can't use weird but legal parameter name in routes file

### ISSUE THREAD

**Issue by jxtps** [playframework/playframework#3870]
```
GET /myroute controllers.Application.myroute(weird-parameter-name)
```

Causes the routes parser to barf. I've tried escaping the dashes with %-encoding, backslash, enclosing the whole name in quotes (', ", `), nothing works. 

From what I can tell this is a perfectly legal http parameter name. 

See also: 
http://www.ietf.org/rfc/rfc2396
http://stackoverflow.com/questions/814700/http-url-allowed-characters-in-parameter-names

**Comment by jxtps** [comment]
From the RFC: 

Section 3.3 defines `param` as `pchar`, which contains `unreserved`. Section 2.3 defines `unreserved` as `alphanum | mark`, and dashes are part of `mark`, so params are allowed to contain dashes.

**Comment by wsargent** [comment]
That's a really interesting question.  I looked at the routes parser spec
and there doesn't seem to be anything covering that case:

https://github.com/playframework/playframework/blob/master/framework/src/routes-compiler/src/test/scala/play/routes/compiler/RoutesFileParserSpec.scala

Can you file an issue at
https://github.com/playframework/playframework/issues



Will Sargent
Consultant, Professional Services
Typesafe <http://typesafe.com>, the company behind Play Framework
<http://www.playframework.com>, Akka <http://akka.io> and Scala
<http://www.scala-lang.org/>

**Comment by wsargent** [comment]
@jxtps BTW, you should reference http://tools.ietf.org/html/rfc3986 instead of rfc2396, which is obsolete.

**Comment by jroper** [comment]
We should probably add back tick support to the routes file.

**Comment by wsargent** [comment]
Fixed by https://github.com/playframework/playframework/pull/5129
