### ISSUE TITLE
Multi Project in Java

### ISSUE THREAD

**Issue by sivailango** [playframework/playframework#3871]
Hi,
    I want to run two projects on play, For example localhost:9000/testA points to one project, and localhost:9000/testA points to another project. I followed http://eng.kifi.com/multi-project-deployment-in-play-framework/. Its written for Scala,

I have sub project within modules folder named "testA" from parent project "multi-play"

 i tried to write in for Java, my build.sbt is 

name := "multi-play"

version := "1.0-SNAPSHOT"

libraryDependencies ++= Seq(
  javaJdbc,
  javaEbean,
  cache
)     

val testA = play.Project("testA", path = file("modules/testA")).settings(
	javaOptions in Test += "-Dconfig.resource=testA-application.conf"
)

val aaaMultiProject = play.Project("multi-play").settings(
).dependsOn(testA % "test->test;compile->compile").aggregate(testA)

Routes:

GET     /                           controllers.Application.index()

-> / testA.Routes # It gives error

How do we acheive it?

**Comment by cchantep** [comment]
Hi @sivailango . Please ask such question on the [mailing list](https://groups.google.com/forum/#!forum/play-framework) or on [SO](https://stackoverflow.com/questions/tagged/playframework).
