### ISSUE TITLE
Can't see websocket actors in activator ui inspector

### ISSUE THREAD

**Issue by marceloemanoel** [playframework/playframework#3872]
Hi guys. 

I've built a play application that handles websockets with actors. I tried to se their statistics in the Activator UI Inspector but the only actors that appear in it are the ones that I've created by hand. The actors created by play to handle the websockets aren't appearing there. 

I've looked at the websocket actor's creation code and found out that the WebSocketExtension creates websocket handler actors in the system namespace. Maybe that's the reason they're not appearing in the inspector. 

Is there any workaround? Or am I doing something wrong?

Thanks in advance.

**Comment by jroper** [comment]
This is because they path of those actors is not under the `user` path, they live under the Play WebSockets actor extension.  I guess Activator Inspect should be updated to be able to include non user websockets.

**Comment by marceloemanoel** [comment]
Hello @jroper.

Thank you for your reply. I've opened an issue in the activator project, questioning the same thing. Here's their [answer](https://github.com/typesafehub/activator/issues/878). They say that system actors should be internal and therefore they don't have plans to add it. 

But now I'm questioning... should the websocket handlers really be in the `system` namespace? Even when they are created by the framework user? Shouldn't it be in the `user` namespace then?

**Comment by pvlugter** [comment]
@marceloemanoel, activator doesn't trace system actors by default but they certainly can be traced. To trace all the play websocket actors, including the supervisor, use this sbt setting:

```scala
EchoKeys.traceable in Echo += "/system/websockets*" -> true
```

Or you can enable tracing for all system actors with:

```scala
EchoKeys.traceable in Echo += "/system/*" -> true
```

Which actors are traced (and also the sampling rate used for each actor) can be configured by actor path. You can also use a wildcard at the end to match all actors in a subtree.

Let us know if that works for you.
