### ISSUE TITLE
IOException: invalid constant type: 110 at 122

### ISSUE THREAD

**Issue by prithvirajan** [playframework/playframework#3877]
Here is an exception, that occured recenty, due to the increase in size of a scala template file. In my case i have lot of input fields, and it has grown enormously around 300(Input fields are hidden and shown dynamically with jquery hide/show). Still i need to add few more input fields to the existing page. Any help would be much appreciated.

**Comment by cchantep** [comment]
Hi @sivailango . Please ask such question (with details) on the [mailing list](https://groups.google.com/forum/#!forum/play-framework) or on [SO](https://stackoverflow.com/questions/tagged/playframework).
