### ISSUE TITLE
Allow for custom jackson dataformats in play-json

### ISSUE THREAD

**Issue by jvliwanag** [playframework/playframework#3880]
There are a number of interesting dataformats available for jackson, including:
- [MsgPack](https://github.com/msgpack/msgpack-java/tree/v07-develop/msgpack-jackson)
- [Yaml](https://github.com/FasterXML/jackson-dataformat-yaml)
- [Smile](https://github.com/FasterXML/jackson-dataformat-smile)

This probably involves transforming `JacksonJson` into a class that accepts a custom json factory.

**Comment by jroper** [comment]
I think the best way to do this is actually to make the Play JacksonJson module public, so that it can be reused.

**Comment by gsmaverick** [comment]
@jroper Is this still something that is desired and if so any guidance on what exactly you'd like to see done to resolve this issue?

**Comment by gmethvin** [comment]
Moved to playframework/play-json#5
