### ISSUE TITLE
[Scala-2.3.7] WS doesn't support SNI => can't HTTPS to virtual host

### ISSUE THREAD

**Issue by jxtps** [playframework/playframework#3894]
See https://groups.google.com/d/msg/play-framework/T7ZhclgAAMU/PUgaZ4f84cMJ

The Ning async http library v1.8.x doesn't support SNI, Server Name Indication, which is required to make HTTPS connections to virtual hosts. 

It has been fixed in v1.9.x (by Will Sargent no less), but they renamed a bunch of methods such that NingAsyncHttpClientConfigBuilder breaks.

**Comment by wsargent** [comment]
I'll upgrade in 2.4.x.  The problem about upgrading is that anyone who has dependencies on 1.8.x will see their code break.  It may be possible to create a distinct artifact of WS for 1.9.x, but obviously that has its own dependencies.

**Comment by wsargent** [comment]
Also a big problem -- AHC 1.9 has a note saying "Target JDK7, drop support for JDK5 and JDK6".  It's using JDK 1.7 specific calls.  Play supports JDK 1.6, so anyone running WS on 1.6 would break when upgraded.

**Comment by jxtps** [comment]
Ah. Not good. Sigh. 

What's the Typesafe deprecation policy on JDK 1.6? At some point it's got to go, but I understand the desire to keep it on for as long as possible. 

Not being able to WS HTTPS to a virtual host may unexpectedly break people's Play websites if web APIs they depend upon change their infrastructure, even with proper notification (very easy to miss / ignore / be unaware of the implications, then oops).

**Comment by wsargent** [comment]
Play will be JDK 1.8 only in 3.0, per the roadmap https://docs.google.com/a/typesafe.com/document/d/11sVi1-REAIDFVHvwBrfRt1uXkBzROHQYgmcZNGJtDnA/pub

**Comment by jroper** [comment]
Happy to drop 1.6 support for 2.4.x.  Hopefully then we can get rid of the PlayIO class and replace it with JDK 7 Files, and we can also get rid of all the crazy reflection we do in the JDK7WatchService, and replace it with ordinary code.

**Comment by wsargent** [comment]
Should be fixed as part of the upgrade to 1.9.10, tracked in https://github.com/playframework/playframework/pull/3955

**Comment by wsargent** [comment]
#3955 is merged, we should close this out.
