### ISSUE TITLE
[2.4.0-M2] Function tests using testServer / Selenium Webdriver makes Guice blow up

### ISSUE THREAD

**Issue by igmar** [playframework/playframework#3895]
Hi,

I'm trying to unit-test my new shiny 2.4.0-M2 app. That doesn't end well : I see Guice blowing up the moment the testServer() code starts to run. The application works fine outside the testscope.

The stacktrace is pretty much useless due to issue playframework#3768

Any clues on how to proceed ? I can help debug this, since it's running on my devbox.

**Comment by jroper** [comment]
Can you test it with Java 7?

**Comment by jroper** [comment]
Another straight forward fix is:

```scala
"com.google.inject" % "guice" % "3.0" classifier "no_aop"
```

**Comment by igmar** [comment]
testing with Java7 is going to be an issue : The code is full of stuff that is Java8 only. I'll apply your fix, and see if I can get a decent stacktrace.

**Comment by igmar** [comment]
That shed some light : 

[error] Test CoolgamesRouterTest.testRoutes failed: java.lang.RuntimeException: com.google.inject.ProvisionException: Guice provision errors:
[error]
[error] 1) No implementation for com.bm.template.TemplateRenderer was bound.
[error]   while locating com.bm.template.TemplateRenderer
[error]     for field at controllers.Asset.renderer(Unknown Source)
[error]   while locating controllers.Asset
[error]     for parameter 3 at Routes.<init>(Unknown Source)
[error]   while locating Routes
[error]   at play.api.test.FakeBuiltinModule.bindings(Fakes.scala:299):
[error] Binding(interface play.core.Router$Routes to ProviderTarget(play.api.test.FakeRoutesProvider@78ff57e))
[error]   while locating play.core.Router$Routes

I'll recheck : This is probably an error on my part, or the play.modules.enabled don't work. I'll reopen if this is really an issue with Play!

**Comment by igmar** [comment]
Related question : Is it handy that I run Play from the master branch ? For testing etc ?

**Comment by jroper** [comment]
Yes.
