### ISSUE TITLE
string2Asset not available from Java

### ISSUE THREAD

**Issue by umbreak** [playframework/playframework#3898]
As commented [here](https://github.com/SocialFinance/play-2.3-java-reverse-routing/blob/master/README.md#issue-3) `Assets.versioned()` required a Asset as a parameter and in Java `controllers.Assets.Asset.string2Asset` does not work. 

I'm aware of the workaround:

    public static controllers.Assets.Asset toAsset(name: String) {
      return new controllers.Assets.Asset(name);
    }
But why that method (string2Asset) is not added for Java?

**Comment by cchantep** [comment]
Hi @umbreak , please ask question on the [mailing list](https://groups.google.com/forum/m/#!forum/play-framework), before reporting there confirmed issue. Thanks.
