### ISSUE TITLE
content-length header included in 304 response which is forbidden by the HTTP spec

### ISSUE THREAD

**Issue by fgutmann** [playframework/playframework#3899]
When returning a not modified result from an action in Play 2.3.7, the resulting HTTP response includes a content-length header.

This field must not be included in a 304 response:
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.5

The problem is reproducible in both Scala and Java.

When content-length it is sent some http client libraries misbehave (eg. picasso on android).
We had to completely disable if-modified-since handling in our project to avoid this, which is obviously a very costly workaround.

**Comment by jroper** [comment]
Notes for whoever wants to fix this:

* A new test needs to be added to `ScalaResultsHandlingSpec` that asserts that a 304 response has no `Content-Length` header sent.  Note, you should use the `BasicHttpClient` for this test.  Test that it fails before implementing the fix.
* The fix will go in `NettyResultsStreamer` and `ServerResultUtils`, which will have to treat 304 status code differently - ie, feed the body into a Done iteratee and ignore the result, filter out any `Content-Length` headers already set, and send the response right away.

**Comment by guersam** [comment]
FYI just in case, `206 Partial Content` has similar constraint (#1097): http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.7

**Comment by jroper** [comment]
Interesting, the `206` constraint only applies if an `If-Range` request header was present.

**Comment by fgutmann** [comment]
Thanks for fixing!
Any chance that this can land in 2.3.x?

**Comment by richdougherty** [comment]
The backport for this probably isn't too hard, but it's also not trivial because the server backend code changed between 2.3 and 2.4. Play 2.4 has two server backends, but Play 2.3 only supports Netty as a server backend. This means a 2.3 backport will need slightly different code. If you're willing to write and test the backport code then we could probably get it into a 2.3 release. @jroper, do you have any thoughts on this?

**Comment by jroper** [comment]
I have no problems with backporting this fix.

**Comment by rbastian** [comment]
@jroper Was this fix backported and if so to which 2.3.x version?

**Comment by jroper** [comment]
I don't believe it was.
