### ISSUE TITLE
request2lang not available outside of controller

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#3903]
The Controller trait defines 

```
  implicit def request2lang(implicit request: RequestHeader) = {
    Messages.messagesApi.map(_.preferred(request).lang)
      .getOrElse(request.acceptLanguages.headOption.getOrElse(play.api.i18n.Lang.defaultLang))
  }
```

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/Controller.scala#L64

Which means if you have a request and you want a lang, but you're not in a Controller, you have to do this:

```
val lang = new Controller {
  val lang = request2lang(rawRequest)
}.lang
```

This is a bit awkward.  Can we have the logic moved out?

**Comment by cchantep** [comment]
Related to #3782 ?

**Comment by wsargent** [comment]
Yes, definitely related.

**Comment by julienrf** [comment]
Yep, #3872 moves the conversion in a I18NSupport trait.

**Comment by cchantep** [comment]
May be easier to work on this one after the recent I18N changes.

**Comment by julienrf** [comment]
The conversion is now provided by the [I18nSupport](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/i18n/I18nSupport.scala) trait that you can mix in your code where you want.

**Comment by cchantep** [comment]
Right
