### ISSUE TITLE
i18n messages 'javascript router'

### ISSUE THREAD

**Issue by SRGOM** [playframework/playframework#3904]
AFAICT, currently there is no way to share i18n messages between server side code (Scala JVM) and client side code (Javascript). Just like there is a feature for "javascript router" for routes, would it be possible to create a feature for "javascript routing" of messages? The javascript file requested thus will have functions that would take the message id and return a message for the specified language.

Usage: I'm consider the following usages

Script loading:
* The required javascript is sent when page is loaded.
* Ajax request for the messages javascript is made and the script executed.

Language determination
* The server has a fallback/default messages file, in addition to language specific messages.jp, messages.cn files.
* The client could want 'default messages' based on the current language in which the server request was sent, or messages for a specific language.

One possible design could be to allow contexts inside messages file of the form. (ids should be unique even if they are inside different contexts)

    common{
      user.create=Create new user
      user.delete=Delete new user
    },
    main{
      login.new = Please sign up
      login.old = Please log in
    },
    sports
    {
      record.new=New world record
    },
    admin
    {
      review.accept = Review {0} accepted
      review.reject  = Review {0} rejected
    }

The server side \@Message( msg ) call could ignore the namespaces. 
The javascript "router" could work as follows:

controller/Application.scala

    def javascriptMessages( 
       contexts: String, 
       languages: String,
       includeDefault : Boolean = true 
    ){
      // Parse languages as comma separated i18n.lang names.
      // Parse contexts as comma separated lists of contexts. 
      // Create js functions for each message and send the resulting file
    }

JS api could be as follows. 

    function getMessage( msgId: String, language: String, params: Array ){
      if( language === undefined ) 
      {
        if( global.i18n.language = undefined )
        {
          language= "fallback"
        }
        else
        {
          language = global.i18n.language;
          //Where does this come from?
          //in the server side code, this would be a statement inside the script tags.
          //@()(implicit lang: play.api.i18n.lang) 
          //<script> var global.i18n.language = lang.code </script>
        }
      }

      var msgFn =  messageRouter[ language ][ msgId ]
      if( msgFun === undefined )
        msgFun = messageRouter[ "fallback" ][ msgId ]

      if( msgFun === undefined )
        return msgId
      else return
        msgFun( params )
    }

JS function for context = "admin", msgId = "review.accept"

    function( params ){
      return "Review" + params[ 0 ] + "accepted"
    }

I think I might have overlooked some details, but I was wondering if you guys think this makes sense at all? If so, I could help out in fleshing out more details

**Comment by mkurz** [comment]
@SRGOM 
Play 1 already had an `#{i18n /}` template tag which basically rendered a javascript function to retrieve messages. But it did not work with ajax, all messages where instead rendered into an `i18nMessages` js-variable. Have a look on its [documentation](https://www.playframework.com/documentation/1.3.x/tags#anamei18ni18na) and its [source code](https://github.com/playframework/play1/blob/1.3.x/framework/templates/tags/i18n.tag) how this was solved back then.

**Comment by SRGOM** [comment]
@mkurz Great minds think alike! haha. Seriously though, this is a nice feature to have. I wonder why it was dropped. Also, pardon me but I don't understand why it wouldn't work with ajax. I can create a template with just these keys, and send an ajax request for it, wouldn't that work?

**Comment by mkurz** [comment]
@SRGOM I'm not saying it wouldn't work with ajax, I'm just pointing out how it was implemented in Play 1. Also this feature wasn't really dropped in Play 2 because the framework was completely rewritten from 1 to 2, so it just doesn't exist in Play 2 (yet).

Probably it's best to wait for a reply from the Play team what they think - if this feature makes sense to them and how it should be implemented. I just wanted to add some additional information to this issue which came to my mind when I noticed it :wink:

**Comment by SRGOM** [comment]
@mkurz Thanks for clarifying. An existing implementation is definitely a good vote of confidence.

**Comment by julienrf** [comment]
Hi, please note that I wrote a library that does just that: [play-jsmessages](http://github.com/julienrf/play-jsmessages)

**Comment by julienrf** [comment]
Hi, please note that I wrote a library that does just that: [play-jsmessages](http://github.com/julienrf/play-jsmessages)

**Comment by SRGOM** [comment]
@julienrf I will check this out, thank you. 
What are your thoughts about integrating this functionality into play itself?

**Comment by julienrf** [comment]
I would be happy to see it in the core of Play but it also works well as a third party library…

**Comment by jroper** [comment]
In general, we want to have more outside of the core of Play as third party libraries than inside, a major focus of the past few releases has been modularisation, pulling more functionality out of Play.  Anything in Play gets stuck, improvements take months (or years) to reach end users because they need to wait for the next major release because they break binary compatibility, fixes don't get backported because we prefer to err on the side of caution with backports, etc.  I think it's better both for the feature and for Play in general to keep it out of the core Play.

**Comment by SRGOM** [comment]
@jroper Thank you. I wonder if you guys have any blessed plugins? I looked at play-jsmessages and it looks really cool. If it were part of github.com/playframework/play-jsmessages, the community would be much bigger because people would be more confident, I think. Have you guys thought about that?

**Comment by cchantep** [comment]
I think this discussion can be now on the [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework).
