### ISSUE TITLE
Config library needs to support Java 8

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#3921]
The [config](https://github.com/typesafehub/config) tests fail when run under Java 8. It seems they depend on some unspecified behavior like map ordering that has changed between Java 7 and Java 8. We should fix this at least before Play 2.4.0 is released. We may want to backport the fix to 2.3.x as well though

See https://github.com/typesafehub/config/issues/253 for details

**Comment by jroper** [comment]
Correct me if I'm wrong, but it looks to me like it's just a bug in the config tests, not config itself, is that right?

**Comment by benmccann** [comment]
Nope, the bug is in config itself. It seems to rely on the iteration order of a `HashMap` which isn't something it should be doing since it isn't guaranteed.

**Comment by benmccann** [comment]
config now uses java 8: https://github.com/typesafehub/config/commit/9d16f3bf610dfc1ca4fe3c9660e8b2f6256cb1c9

havoc said that the expected behavior for the case that was failing is undefined, so he's not concerned that the behavior changed between java 7 and java 8. he just changed the expected result in the test and there were no code changes, so i guess there's nothing to do here. if a new version is released i'll probably upgrade us because there are some nice things i'd like to use that are in the works, but it's no longer a blocker
