### ISSUE TITLE
JNDI DBAppender logback with play

### ISSUE THREAD

**Issue by UlTriX** [playframework/playframework#3925]
I am trying to save the logs to the same default database i am using in my play application.
 
I have exposed jndi in application.conf with db.default.jndiName = DefaultDS and in the logger.xml

```
<appender name="DB" class="ch.qos.logback.classic.db.DBAppender">
        <connectionSource class="ch.qos.logback.core.db.JNDIConnectionSource">
            <jndiLocation>DefaultDS</jndiLocation>
        </connectionSource>
    </appender>
```

It always gives me ch.qos.logback.core.db.JNDIConnectionSource cannot find it.
I believe it is because play only exposes the jndi after the init of the logger.

Is there any workaround?

**Comment by cchantep** [comment]
Hi @UITrix , please ask question on the [Mailing List](https://groups.google.com/forum/#!forum/play-framework), before filing on this issue tracker.
