### ISSUE TITLE
activator eclipse build path

### ISSUE THREAD

**Issue by stabenau** [playframework/playframework#3933]
The activator eclipse command doesn't copy the conf directory into the target classpath. It makes it necessary to recompile from activator to make resource changes stick.

**Comment by benmccann** [comment]
This should be fixed in Play 2.3.8, which is using the latest version of sbteclipse to fix this problem and a few others.

**Comment by benmccann** [comment]
@stabenau I'm going to close this as I believe it is already fixed. Please feel free to comment here if you believe otherwise and we can possibly reopen it

**Comment by stabenau** [comment]
Sorry for posting, I later realised that similar reports were already in the system. Thanks for taking care of it. (It is fixed!)
