### ISSUE TITLE
@AttributeOverride annotation does not seem to work (Play 2.2.0)

### ISSUE THREAD

**Issue by dbremmen** [playframework/playframework#3936]
Hi!

I'm trying to use @AttributeOverride to use a different database column name in a subclass but it doesn't seem to work. I tried everything but with no good results :(

I Have a base class like this:
```
@MappedSuperclass
public class BaseProject extends Model {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long id;

    public String name;
}
```
And a subclass:
```
@Table(name = "cmp_alienproject")
@Entity
@AttributeOverride(name="name", column=@Column(name = "APRJ_NAME"))
public class AlienProject extends BaseProject {
   
    public static Finder<Long, AlienProject> find = new Finder<Long, AlienProject>(Long.class, AlienProject.class);
   
    @Required
    @Column(name = "APRJ_PATH")
    public String path;

}
```
When I try to save the entity using the following code:

```
AlienProject project = new AlienProject();
project.name = "test";
project.save();
```

The following error is displayed:

play.api.Application$$anon$1: Execution exception[[PersistenceException: ERROR executing DML bindLog[] error[Unknown column 'name' in 'field list']]]

So It seems that the AttributeOverride takes no effect.. I'm really lost, I tried to move the AttributeOverride in different areas of the sublcass but it always fails with the same error

**Comment by jroper** [comment]
Please raise ebean issues on the [ebean issue tracker](https://github.com/ebean-orm/avaje-ebeanorm).
