### ISSUE TITLE
Evolutions directory should be configurable

### ISSUE THREAD

**Issue by stephennancekivell** [playframework/playframework#3966]
I have a bunch of micro services with a shared database and use evolutions. Currently I have to copy and paste changes between `1.sql`'s in each micro services `conf/evolutions` path. I want to be able to configure the evolutions directory to be something like `conf/../../common-evolutions`. This may not be the ideal architecture but I think it should be possible to change this path.

What do you guys think of this idea?

I have a implementation, what do you think of it? I've added it straight into `Evolutions.scala`, should it be in `DefaultEvolutionsDatasourceConfig` or something.

What should the config name be? It looks like you've refactored those lately.

**Comment by mkurz** [comment]
Even though this issue was closed, it never was resolved.
But it is now, 8 years later, starting with Play 2.9 you will be able to configure the location of the evolution scripts: #11917
