### ISSUE TITLE
Support http.address in dev mode

### ISSUE THREAD

**Issue by pvlugter** [playframework/playframework#3969]
We currently support configuring http.port and https.port in dev mode, but not http.address.

**Comment by benmccann** [comment]
What would it be besides localhost?

**Comment by morsch** [comment]
A single host can have more than one address. Localhost is always
127.0.0.1, but maybe you want to bind it to 192.168.100.1. This also lets
you run a second or third instance on the same server, without using
non-standard ports, by binding them to different addresses.

**Comment by jroper** [comment]
I've had setups before where I've had multiple loopback interfaces, 127.0.0.1, 127.0.0.2 etc.  Handy when your testing situations where you simulate multiple servers, you can put entries in your `resolv.conf` to point any arbitrary hostname to these ip addresses.

**Comment by nafg** [comment]
Also it allows to access it from other devices on the network.
