### ISSUE TITLE
evolution lock for multiple hosts won't work for mysql DB

### ISSUE THREAD

**Issue by carolliu** [playframework/playframework#3977]
We set up an mysql DB.  We're using play 2.3.7.  When using evolution and setting up "evolutions.use.locks=true" for multiple hosts, "play_evalutions_lock" table failed to be created because of mysql syntax error.  We later run mysql directly in DB and hit the same problem:

mysql> create table play_evolutions_lock ( lock int not null,primary key(`lock`) );
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'lock int not null,primary key(`lock`) )' at line 1

The code causing this problem is in line 145 of https://github.com/playframework/playframework/blob/master/framework/src/play-jdbc/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala.

Is there any way to overcome this problem?

**Comment by carolliu** [comment]
This issue is closely related to #2286 which is opened for a year.

**Comment by megazord** [comment]
Looks like lock support for MySQL is completely broken. Both table creation and also lock acquirement SQL commands are invalid. Even worse, there are no tests for this part of the code. I'm not sure if it worth (or even possible) to test evolutions lock using H2 compatibility mode to emulate different databases.

Moreover, I suspect that other databases are affected by this problem too (looks like SQL Server does not supports `"for update nowait"`).

Any tips on how to proceed here?

**Comment by jroper** [comment]
This is documented:

https://www.playframework.com/documentation/2.3.x/Evolutions#Evolutions-and-multiple-hosts-using-Postgres-or-Oracle

**Comment by jroper** [comment]
What needs to be done is for evolutions to be made very configurable.  We should create a dialects abstraction that has db specific ddl templates for evolutions, allow things like specifying a schema in databases that support it, and allow everything to be completely overridden in config.

**Comment by megazord** [comment]
Got it. Looks like there is a lot of work to do in order to have configurable evolutions. I mean, support specific database dialects is not a simple task, even if we decide to use something that already exists (like Hibernate or maybe Ebean). 

This discussion is probably related with #2365 and #2286. Should we close these issues in favor of a more elaborated approach like the one you explained?

**Comment by marcospereira** [comment]
PR #4293 is related to this issue.

**Comment by marcospereira** [comment]
#4293 was merged.
