### ISSUE TITLE
Play does not support alpha-3/ISO 639-2 language codes

### ISSUE THREAD

**Issue by intracer** [playframework/playframework#4014]
Although https://www.playframework.com/documentation/2.3.x/ScalaI18N states that "A valid language code is specified by a valid ISO 639-2 language code" play actually rejects alpha-3/ISO 639-2 language codes, Play only allows two byte language codes
play.api.i18n.Lang#get
  def get(code: String): Option[Lang] = {
    code match {
      case SimpleLocale(language) => Some(Lang(language, ""))
      case CountryLocale(language, country) => Some(Lang(language, country))
      case _ => None
    }
  }

  private val SimpleLocale = """([a-zA-Z]{2})""".r
  private val CountryLocale = (SimpleLocale.toString + """-([a-zA-Z]{2}|[0-9]{3})""").r

while http://www.loc.gov/standards/iso639-2/php/code_list.php  iso639-2 codes are 3 byte and many languages do not have corresponding 2 byte codes, for example crh	 - Crimean Tatar language

**Comment by cchantep** [comment]
Moved to #4024
