### ISSUE TITLE
[Scala-2.3.8] Validation.emailRegex doesn't allow single-letter domains

### ISSUE THREAD

**Issue by jxtps** [playframework/playframework#4022]
[Validation.emailRegex](https://github.com/playframework/playframework/blob/a0a8bd5796c746334dac1d88f65cda66975cb6a8/framework/src/play/src/main/scala/play/api/data/validation/Validation.scala#L76) doesn't allow email addresses with single-letter domains such as example@x.com.

**Comment by jxtps** [comment]
Adding a ()? around the first section in the domain-check seems to resolve the issue. I.e. changing:  

    """^(?!\.)("([^"\r\\]|\\["\r\\])*"|([-a-zA-Z0-9!#$%&'*+/=?^_`{|}~]|(?<!\.)\.)*)(?<!\.)@[a-zA-Z0-9][\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]$""".r
to: 

    """^(?!\.)("([^"\r\\]|\\["\r\\])*"|([-a-zA-Z0-9!#$%&'*+/=?^_`{|}~]|(?<!\.)\.)*)(?<!\.)@([a-zA-Z0-9][\w\.-]*)?[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]$""".r

**Comment by jroper** [comment]
I'm a little hesitant here.  We used to use the html5 regex, this was done in #1703.  But then we updated it to a new one, and I don't know where that regex comes from, in #2141.  Unless there's a good reason not to, I'd rather go back to the html5 regex.

**Comment by intracer** [comment]
We had this issue too, in Ukriane i.ua is quite popular email domain

**Comment by jroper** [comment]
Ok, so based on [this](https://github.com/playframework/playframework/pull/1894/files#r25748323) discussion, I think the first step we should take is to move to the html5 email validation regex, which can be found here:

http://www.w3.org/TR/html5/forms.html#e-mail-state-(type=email)

And see how that goes.  Looking at that, it looks like it supports one letter domain names.

**Comment by felixmulder** [comment]
In our tests we consider ".@mail.com" an invalid address because of the dot. As far as I can see the regex that @jroper references does not take this into account. Our regex also considers "blabla..blabla@mail.com" an invalid address (double dots in the middle). Disassembling the regex is a pain, but comparing the two, I think that is the fundamental difference between the RFC and our implementation. Commit 6593f4e9e2407f0494355e5c2663b321c2e4820f allows for one letter domains without relinquishing our interpretation of the RFC.

**Comment by jroper** [comment]
The HTML5 regular expression is by no means comprehensive, but then, no regular expression for validating email addresses is.  At the end of the day, if you want to validate an email address, the only real way to do it is to send an email to it with a secret token.  For this reason, false positives are not a big problem, what is a big problem is false negatives, ie issues like this very bug.  By using a regular expression that's been developed very carefully as part of the HTML5 spec and is used all over the web as a defacto standard, we ensure with a high degree of certainty that we aren't don't have any false negatives.  In contrast, using a home grown regular expression like the one currently used opens us up to issues like this one.

**Comment by felixmulder** [comment]
Very sound logic, that seems like the best approach. This would break some tests, I will fix this and create a separate pull request.

**Comment by wsargent** [comment]
The only comprehensive, RFC-compliant Java library I know of for email validation is Dominic Sayer's IsEmail: https://code.google.com/p/isemail/source/browse/Java/trunk/src/com/dominicsayers/isemail/IsEMail.java?r=65
