### ISSUE TITLE
Play's run command make the json4s read/extraction failed for class property with default value 

### ISSUE THREAD

**Issue by sdiwu** [playframework/playframework#4033]
Recently I encountered [this json4s bug][1] on Play, but I found out the problem only happened if I run the code through Play's `activator -> run` command. So it seems this is Play's bugs.

Basically the problem is the [json4s][2] library will fail to read/extract a json to a class that have default value on its field/property but no key-value exist in the json, however it only fail if the code is run through Play's `activator -> run` command. It won't give error if I run through other ways like: activator -> start, test/test-only, console, def main, etc.

I have uploaded the example code at [here][3].

**Bug description**

I have a scala class with default value for the field `name`:

    class TestModel(val id: String, val name: String = "john")

Then I have a controller:

    import play.api._
    import play.api.mvc._
    import org.json4s._
    import org.json4s.native.Serialization.read
    import models.TestModel
    
    object Application extends Controller {
    
      def test = {
    	implicit val formats = DefaultFormats
    
    	val jsonStr = """{"id":"01"}"""
    
        val tm = read[TestModel](jsonStr)    // error at this line
    
    	println("ID: " + tm.id)
    	println("Name: " + tm.name)
      }
      
      def index = Action {
        test
        Ok(views.html.index("Your new application is ready."))
      }
    
    }

So at this line: 

    val tm = read[TestModel](jsonStr)

It will read the json string into TestModel class instance. Although the json `{"id":"01"}` doesn't have `name` key-value on it, however the `TestModel.name` has been assigned with default value so it should be read successfully. However error happened when it's run with Play's run command.

**How to produce the bugs**

 1. Run: `activator` -> `run` for the code above.
 2. Open browser, navigate to: localhost:9000
 3. It will fail at line `read[TestModel](jsonStr)` and produces exception as shown below:

    play.api.Application$$anon$1: Execution exception[[MappingException: No usable value for name
    Did not find value which can be converted into java.lang.String]]
    	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.8.jar:2.3.8]
    	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.8.jar:2.3.8]
    	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.8.jar:2.3.8]
    ...

  [1]: https://github.com/json4s/json4s/issues/174
  [2]: https://github.com/json4s/json4s
  [3]: https://github.com/sdiwu/play-json4s-defaultvalue-bugs

**Comment by jroper** [comment]
If it works in prod mode but not dev mode, then the cause is most likely a bug in json4s not using the right classloader, or a bug in your code not passing json4s the right classloader.  We have our own json library in Play which keeps us occupied enough, if you want to use another json library that's fine, but the onus is on you to debug and find the cause of the bug, please don't expect us to do that for you.  If it does turn out to be a problem in Play, you can reopen this issue, but I strongly suspect the problem is either in your code or json4s.

**Comment by sdiwu** [comment]
I debugged the json4s code, I found out json4s code uses `Class.forName(c, true, iter.next())` and I checked the 3rd parameter (class loader) is `PlayDependencyClassLoader` when run in dev mode. I did some googling about PlayDependencyClassLoader and it leads up to [this issue][1]. So I guess there is nothing can do about this?

  [1]: https://github.com/playframework/playframework/issues/822

**Comment by jroper** [comment]
`Class.forName` may only be used if you know for sure that the class you are loading can be found in your own classloader.  json4s does not know this for sure, therefore this is a bug in json4s (assuming they don't provide an alternative mechanism).

json4s has two options:

* Allow the user to provide a classloader. This is the best option.
* Use the context classloader.  This works, but the onus is on the user of the library to ensure that the context classloader is set correctly, in an asynchronous framework like Play, this means you would have to set the context classloader before making any calls to json4s.
