### ISSUE TITLE
Arrows inside activator console not working on Windows when using remote desktop

### ISSUE THREAD

**Issue by icl7126** [playframework/playframework#4058]
Since the new version 2.3 I cannot use arrows in activator console. When arrow "up" is pressed, "ÓH" is written. Rest of the arrows looks like this:
down: ÓP
left:ÓK
right: ÓM
If I use Shift + arrow_on_numeric_keybord, it works as expected.
I'm working on Windows 8.1 x64 machine which is running inside virtualbox. I'm accessing this machine through the Windows RDP from again Win. 8.1, x64 machine.
Problem first appeared in version 2.3,  previous 2.2.x was ok.
I'm using 1.2.8 activator.

EDIT:
After further inspection I discovered the problem is not connected with RDP. When I try to use keyboard directly in Virtualbox window it doesn't work. Virtualbox is running in Linux Mint 15 Olivia x64.

**Comment by jroper** [comment]
What happens if you use vanilla sbt?

**Comment by icl7126** [comment]
I"m not sure what you mean but if I create new project from a template it's still broken.

**Comment by jroper** [comment]
If you download and install sbt, and run it instead of activator?

**Comment by icl7126** [comment]
As you probably expected, problem is in SBT :)
I suppose I should create bug-report on theirs page...
