### ISSUE TITLE
Can not custom /helper/inputText.scala.html

### ISSUE THREAD

**Issue by phucnh** [playframework/playframework#4076]
I want to add some class to input tag:
Example:
```html
<input class="myCustomClass "/>
```
I have try many but not success, what should i do in Play 2.3.8. If current version can not do it. Do you have any plan for custom it (like Field Constructor)

**Comment by cchantep** [comment]
The question is broad. Would be better to move it first on the [MailingList](https://groups.google.com/forum/#!forum/play-framework).
