### ISSUE TITLE
2.4.0 - upgrade to sbteclipse 4.0.0

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#4078]
I'm working on upstreaming all Play modifications to sbteclipse so that Play can use vanilla sbteclipse and so that all sbteclipse users can benefit from these improvements. I'm leaving this here tied to the 2.4.0 release so that we can track the changes

Want to try getting the fix for Play issue https://github.com/playframework/playframework/issues/4125 checked into sbteclipse

The other Play/sbteclipse changes have all been merged:
https://github.com/typesafehub/sbteclipse/pull/243
https://github.com/typesafehub/sbteclipse/pull/244
https://github.com/typesafehub/sbteclipse/pull/245
https://github.com/typesafehub/sbteclipse/pull/246
https://github.com/typesafehub/sbteclipse/pull/247

**Comment by benmccann** [comment]
@dragos would you be able to review these sbteclipse changes? I'd love to get a new version of sbteclipse into the upcoming Play 2.4.0 RC

**Comment by benmccann** [comment]
@dragos @jsuereth i could really use some help getting the pending PRs for sbteclipse checked in (also happy to be a project maintainer if you guys want some help)

**Comment by dotta** [comment]
@benmccann I'm wondering if you've also looked at how to prevent importing in Eclipse empty source folders (I remember you pointing out this issue at some point, but maybe my memory is failing me).

Again, thanks for the fantastic clean-up!

**Comment by benmccann** [comment]
@dotta yes! that fix was merged to sbteclipse (#247)

**Comment by dotta** [comment]
@benmccann Lovely! Btw, I guess you meant https://github.com/typesafehub/sbteclipse/pull/247 :-)

**Comment by benmccann** [comment]
Only one issue left. Hopefully some SBT expert will help me :-)

https://github.com/typesafehub/sbteclipse/issues/254

**Comment by megazord** [comment]
@benmccann

typesafehub/sbteclipse#254 was closed. Can we close this issue?

**Comment by benmccann** [comment]
@megazord we'll be able to close this in a couple days. i haven't upgraded us to sbteclipse 4.0.0 yet because i'm waiting for someone to cut that release

**Comment by benmccann** [comment]
Sent a PR for this: https://github.com/playframework/playframework/pull/4226

**Comment by megazord** [comment]
@benmccann, what about now? :-)

**Comment by benmccann** [comment]
:-)

**Comment by dotta** [comment]
@benmccann I just used sbteclipse 4.0-RC1, and let me say that I'm so thankful for the work and time you put on this. Much less clutter (no more empty source folders)! Good job man.

**Comment by benmccann** [comment]
Yay, glad it worked for you! (It probably only works with Play 2.4-RC1 or newer or non-Play projects. Older versions of Play tried to do their own Eclipse settings which will make it fail)

**Comment by dotta** [comment]
I'm working on play-slick, any my branch is indeed on Play 2.4-RC1. The play-slick project has several nested sample Play projects, and sbteclipse 4.0-RC1 works perfectly with all of them.

**Comment by benmccann** [comment]
That's awesome! I haven't gotten to test it much in practice, so I'm happy to hear!
