### ISSUE TITLE
activator start -Dhttp.port doesn't work on windows

### ISSUE THREAD

**Issue by donpironet** [playframework/playframework#4083]
The command activator start -Dhttp.port=9090 works fine on my mac but the clients server is a windows 2012 server.

I wanted to deploy the server there with the same command and then I get:

input line too long followed by the syntax of the command is incorrect.

I found many topics about this and I even tried like they suggested:

activator start '-Dhttp.port=9090' or even activator '-Dhttp.port=9090' 'start 9090' and so on. Nothing works.

How can I fix this so the server can be deployed?

**Comment by jroper** [comment]
Avoid `activator start`.  Use `activator dist` instead.

**Comment by krns** [comment]
How can I pass parameters as '-Dhttp.port=9090' to the application in case of using dist? If I make 'activator dist' and run the '<appname>.bat' file I am not able to pass anything because of a 'Bad application path: <passed parameter>'

**Comment by TheChifer** [comment]
Use 
activator "run -Dhttps.port=443 -Dhttp.port=8080"

Earlier versions of activator supported -D configurations without "

**Comment by marcospereira** [comment]
Duplicated with #4083.
