### ISSUE TITLE
JsPath - Compose with \

### ISSUE THREAD

**Issue by alias1** [playframework/playframework#4085]
Was just playing around with JsPaths and thought I should be able to do something like

```
val myJson = Json.obj()
val path = (__ \ "a")

val result = (myJson \ pathA)
```

But it appears `\` only supports strings. Is this sort of thing possible currently, and if so, could someone point out what I missed please? If not, is it something we could get added? (should be pretty simple I think since `JsPath.compose(JsPath)` already exists?)

Cheers

**Comment by jroper** [comment]
Seems straight forward to me... though the question for me is, should we overload `\` to take both `String` and `JsPath`, or should we make `\` take `JsPath`, and provide an implicit conversion from `String` to `JsPath`?

**Comment by jroper** [comment]
Related: #3896

**Comment by alias1** [comment]
Not sure I have a good answer. I like the API discoverability of overloading, but implicits are pretty nice too..

**Comment by nafg** [comment]
...or you could use a type class...

**Comment by gmethvin** [comment]
What do we do when the `JsPath` contains multiple paths (`_ \\ "foo"`)? Should we do the same thing as `JsPath#asSingleJson`? If the method only makes sense for a specific subset of `JsPath` values, I feel like it should be named something more descriptive than `\`.

**Comment by cchantep** [comment]
Close it for now (as inactive and need discussion). It can be discussed on the [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework).
