### ISSUE TITLE
Using typesafehub/config for i18n

### ISSUE THREAD

**Issue by SRGOM** [playframework/playframework#4097]
Hello, I have a quick and dirty implementation of i18n api that uses typesafe config. If you guys would be open to a change from current messages api to this, please let me know and I will "productionize" and commit.

Pros: 
* Remove the parser, doesn't belong in play.
* Benefits of typesafehub/config include substitution, better modularization, different lang configs for test and prod 

Cons:
* Transition will involve: 
    * a rename from messages.<ll> to messages.<ll>.conf and wrapping the entire file content into <ll>{}
    * and a new messages.conf file that has include "messages.<ll>.conf" for all languages. Might require wrapping this around langs{}. (code in gist doesn't take this into account)

See here for a gist: (Changes are made against play-2.3.7, and diffs would be similar too)
https://gist.github.com/SRGOM/768ee758a84e8cf4013a 

What this doesn't do yet and I will do before committing:
1) Tests
2) I will see if java changes are required
3) Currently it's only the messages api, I'll have to look to see how to get it working correctly with the plugin system.

I've read the contribution guide but didn't post on groups because I'm not a developer here.

**Comment by benmccann** [comment]
I'm not clear on what the benefit would be as an end user

I don't think we'd want to change the 2.3.x branch. Perhaps we could use the DI in 2.4.x to make the i18n implementation pluggable

**Comment by SRGOM** [comment]
@benmccann My changes are against 2.3.7 because that's what I had on my system, not proposing to merge there, in fact not even in 2.4.x, but in the version thereafter (3.0?). 

Re; benefits for an end user of this library, two things that come to mind are: automatically "enforced" modularity and ease of substitution. The following example might seem synthetic, but I am facing a much more complex version of the same in one my projects (not knowing what to call a certain 'thing')

    en{
      place{
         name = location #change later to place
         review = Write your ${en.action.review} for this ${place.name}
         checkin = ${en.action.checkin} this ${place.name}
      }

      action{
        review = "Review" #change later to testimonial
        checkin = "Check in" #change later to enter
      }
    }
    
    fr #I don't know
    {
      place{
         name = plc
         review = ${fr.place.name} review
         checkin = ${fr.place.name} check dans
      }
    }

**Comment by jroper** [comment]
This could be an alternate implementation - I'm not that keen on making it the default, translation companies have a hard enough time handling the Java messages format, if our format differs too much from that, it's going to make things a pain for users.

**Comment by benmccann** [comment]
Also, I think that doing something like `review = Write your ${en.action.review} for this ${en.restaurant.name}` is something I would avoid as much as possible when you're doing translations. Some languages have very different sentence structures or word choice would be different depending on context making this extremely difficult. Here's a [good article with more details](http://www.multilingual.com/articleDetail.php?id=594).

**Comment by SRGOM** [comment]
@jroper: Ok, in that case, I'll add this as a separate API and plugin. I'll discuss (this issue or google groups?) how to deal with the plugin system and submit changes. I might be slightly swamped in the immediate future so would take a while to start.

@benmccann I actually had a another hypothetical language example that I deleted later. And I think that this format would work even better in that case. 

hy{
  restaurant{
     name = rst 
     review =  ${en.restaurant.name} ${en.action.review} do
     checkin = ${en.restaurant.name} ${en.action.checkin} do
  }

  hotel{
     name =  htl
     review =  ${en.hotel.name} ${en.action.review} do
     checkin = ${en.hotel.name} ${en.action.checkin} do
  }

  action{
    review  = "rvw" 
    checkin = "entr" 
  }
}
