### ISSUE TITLE
Race condition in routing a request ?

### ISSUE THREAD

**Issue by elvenking** [playframework/playframework#4101]
I have following REST API:

GET /api/some-json-resource1   SomeController.someJsonFromStaticFile
GET /api/some-json-resource2   SomeController.someDifferentJsonConstructedFromXml

Play version: 2.3.8

The problem is, that i am getting the same response to different REST resources.
I making ajax calls basically at the same moment to these two resources.

Ajax request 1 to /api/some-json-resource1  --> returns correct JSON response, served by someJsonFromStaticFile
Ajax request 2 to /api/some-json-resource2  --> SOMETIMES gets served by an action method of resource1. Incorrect. It should be served by someDifferentJsonConstructedFromXml

Sample pseudo-log
Format: [{log level}] {logger} - {controller method name}: {request() path}

Correct run:

[debug] application - someJsonFromStaticFile: /api/some-json-resource1
[debug] application - someDifferentJsonConstructedFromXml: /api/some-json-resource2

Race condition ?:

[debug] application - someJsonFromStaticFile: /api/some-json-resource1
[debug] application - someJsonFromStaticFile: /api/some-json-resource2   <--- this is bad

Thanks !

**Comment by jroper** [comment]
Hi @elvenking. Most likely is that you are using Spring, and your actions are singletons.  Actions need to be prototype, they have the delegate injected into them for each request, so if you have a singleton one, then there is a race condition that it invokes the delegate before the next request comes.

**Comment by elvenking** [comment]
I forgot this fact. Now it works.

Thank you James !
