### ISSUE TITLE
GzipFilter drops any information carried in subclasses of [Simple]Result

### ISSUE THREAD

**Issue by omnilinguist** [playframework/playframework#4105]
This issue is best illustrated by the following proposed change: https://gist.github.com/omnilinguist/3624fb8e4b41bdedd8b5

Note that currently, the `GzipFilter` creates new `Result`s (`SimpleResult`s in earlier Play versions) , so that in case we want to subclass the `[Simple]Result` to carry additional information through the filter chain, these data get lost at the `GzipFilter` step of the filter chain because it creates a new `[Simple]Result` with only the basic class elements. Does this seem like a reasonable use case and fix?

**Comment by julienrf** [comment]
`Result` should be final.

**Comment by omnilinguist** [comment]
If that is the case, then how are metadata that are we would like to be associated with each request (but not part of the actual request/response) be accessible within the filter chain?

**Comment by julienrf** [comment]
The right way to do this would probably to use an existential type in place of `Result`. But this would lead to a lot of complexity. Unfortunately there is currently no way to achieve what you want. What is your use case?

**Comment by jroper** [comment]
I think there's a legitimate question of whether we should attach a generic context map to the `RequestHeader` and `Result`.  I personally don't think it's a good way to do things, composition at the action level allows you to pass context with the result at the action level, making things explicit and type safe.  But the discussion is worth having.

**Comment by omnilinguist** [comment]
To answer @julienrf's question, this is something that was initially put into place by @brikis98 (possibly with consultation from @nraychaudhuri and/or some other Typesafe folks, though I am not sure about this as it was before my time) in order to do essentially the equivalent of what @jroper is saying ("attach a generic context map to the ```RequestHeader``` and ```Result```"). After talking with @bbarkley, it sounds like this suggestion ("composition at the action level") was already given in a separate discussion that I was not privy to, so at least there has been consistency there. Since the advice was repeated, I infer that this is not something Typesafe feels is a good pattern to use, so we will have to take that into consideration in the next major iteration of our integration platform. This would imply that some of the features we have that depend on this particular hack (from Typesafe's perspective) may need to be reevaluated to be in line with these standards, if the discussion you are alluding to fails to sway Typesafe from its current position.

**Comment by marcospereira** [comment]
This is already fixed for both 2.5.x and master branch.
