### ISSUE TITLE
classes_managed support is gone breaking Eclipse

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#4125]
PlayEclipse depends on [classes_managed](https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala) to be present. This directory is no longer generated, which will break Eclipse support.

**Comment by jroper** [comment]
It was removed here:

https://github.com/playframework/playframework/pull/3691/files#diff-a3c855f21b91ad4e482bd0176fe8711fL119

**Comment by benmccann** [comment]
Ah, thanks. Yeah I see now:

    // Copy managed classes - only needed in Compile scope
    // This is done to ease integration with Eclipse, but it's doubtful as to how effective it is.
    if (scope.name.toLowerCase == "compile") {
      val managedClassesDirectory = classes.getParentFile / (classes.getName + "_managed")
      val managedClasses = ((srcManaged ** "*.scala").get ++ (srcManaged ** "*.java").get).map { managedSourceFile =>
        analysis.relations.products(managedSourceFile)
      }.flatten pair rebase(classes, managedClassesDirectory)
      // Copy modified class files
      val managedSet = IO.copy(managedClasses)
      // Remove deleted class files
      (managedClassesDirectory ** "*.class").get.filterNot(managedSet.contains(_)).foreach(_.delete())
    }

I was originally planning on submitting classes_managed support to sbteclipse, but I hadn't realized that classes_managed was something we were doing and not something provided by SBT. Even if it is a bit hacky, it does seems like it'd be smarter to tie it to a flag where if we're using src_managed in Eclipse instead of classes_managed then we shouldn't need to do this.

**Comment by benmccann** [comment]
I took a bit of a look at this earlier, but while I've been picking up more Scala & SBT, I'm still not familiar enough with them to figure out how to get this change into sbteclipse, which seems to use SBT keys in a way that's slightly different from other projects i've seen. @jroper @dotta not sure if either of you would want to take a stab at getting these few lines into sbteclipse?

**Comment by benmccann** [comment]
It sounds like Josh would be okay if we wanted to add classes_managed support to SBT
https://groups.google.com/forum/#!topic/sbt-dev/ip86t7Biw_w

**Comment by benmccann** [comment]
Working on getting this into sbteclipse. See https://github.com/typesafehub/sbteclipse/commit/d46dcc2fc39843981952c5235754e61b0bd1077d

**Comment by benmccann** [comment]
Sent a PR to remove from Play since it's currently broken: https://github.com/playframework/playframework/pull/4174

It will get added back when we upgrade sbteclipse to the next version
