### ISSUE TITLE
Test with sbt 0.13.8

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#4127]
From @mslinn:

> Just noticed sbt 0.13.8 creates app-2.10/11 & test-2.10/11. The SBT docs mention the acceptance of src/main/scala-2.10/11 but there is no mention of how the new SBT interacts with Play

We should verify this behaviour with Play 2.4 and fix - also we should consider whether the fix should be backported to 2.3.x.

I think Play does create source directories, I think it might have something to do with file watching (probably legacy, not needed anymore).  It may also have something to do with IDEs.

**Comment by mslinn** [comment]
I hope that Play with SBT 0.13.8+ will continue to accept app-2.xx and test-2.xx directories and use them as per the new [Cross-version support for Scala sources](https://github.com/sbt/sbt/releases/tag/v0.13.8) behavior. Play does not need to continuously create these directories if they do not exist, however.

**Comment by benmccann** [comment]
I'm not sure if it matters for this issue, but sbteclipse does create some directories if they do not exist. This was recently fixed https://github.com/typesafehub/sbteclipse/commit/ac825d5453d837a86675ec047dbedebd2470e0cd though we'll need to release a new version of sbteclipse and upgrade Play to use it

**Comment by jroper** [comment]
Play will definitely support them, we just need to not create those directories.
