### ISSUE TITLE
preferred Lang method can return a Lang that is not available

### ISSUE THREAD

**Issue by slorber** [playframework/playframework#4144]
```
def preferred(request: RequestHeader) = {
    val maybeLangFromCookie = request.cookies.get(langCookieName)
      .flatMap(c => Lang.get(c.value))
    val lang = maybeLangFromCookie.getOrElse(langs.preferred(request.acceptLanguages))
    Messages(lang, this)
  }
```

If the lang cookie contains "fr" Lang, and my app has `application.langs="en"` only, then the preferred method still returns "fr" because it has been set in the cookie.

I have an app with french landing pages that set the cookie to "fr" for future usages, but app internationalization is currently in progress so we only use "en" for now. But when time comes we want the users that came from french landing pages to switch automatically to "fr" lang

It could be nice to ensure that `preferred` only return application available languages, or maybe add a method `preferredAndAvailable` I don't know...

cc @jroper

**Comment by slorber** [comment]
this is somehow related but I don't really like the "default lang" to be able to be returned without being able to be in app available languages. I would rather use the first `application.langs` as default lang

**Comment by cchantep** [comment]
cc @julienrf

**Comment by jroper** [comment]
This was fixed here: https://github.com/playframework/playframework/pull/2619
