### ISSUE TITLE
Activator and default run task documentation is problematic re: playRun and playRunHooks

### ISSUE THREAD

**Issue by qberticus** [playframework/playframework#4147]
The documentation for 2.3.x and the upcoming 2.4.x now highlight the recommended use of the activator to run the console. The docs note that we should use the command _run_ in the console as the development mode task. The _run_ task is distinct from the _playRun_ task. This is a problem since the _run_ task does not run any of the _playRunHooks_ if they are assigned in the built.sbt file. None of the documentation makes it clear that _playRunHooks_ are only executed when the _playRun_ task is used from the console. 

This issue can affect those who use plugins that use _playRunHooks_ or create their own like the Grunt example now in the 2.4.x documentation.

I am not sure if this is a problem in the documentation or the current implementation of the _run_ task, however, either way it was pretty confusing. :)

**Comment by jroper** [comment]
This is only a problem when use the fork run plugin.  Remove that from your build and you should have no problems.

**Comment by cchantep** [comment]
I guess this can be closed now.

**Comment by jroper** [comment]
I don't think it's solved yet - I think there's a bug in the fork run plugin.

**Comment by wsargent** [comment]
Can it be closed now?

**Comment by PromanSEW** [comment]
Activator is not used anymore. Can be closed

**Comment by marcospereira** [comment]
Yes, fork run plugin does not even exist anymore (since 2.6).
