### ISSUE TITLE
Fix JavaFunctionalTest documentation

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#4168]
https://www.playframework.com/documentation/2.4.x/JavaFunctionalTest

has the following problems:

* `GuiceApplicationBuilder` should be used in favour of `FakeApplication`, so this should be briefly demonstrated, with links to JavaTestingWithGuice for full documentation.
* `WithApplication` only gets a brief mention, `WithServer` and `WithBrowser` don't get mentioned at all, these should have the spotlight on this page.
* References to `fakeRequest` should be replaced with documentation on how to use `play.mvc.Http.RequestBuilder`

**Comment by megazord** [comment]
@jroper PR attached. :-)
