### ISSUE TITLE
Http address binding to fqdn is ignored as command line agrument

### ISSUE THREAD

**Issue by dcdieci** [playframework/playframework#4169]
Hi,

I urgently need to run the application on another address rather than localhost in dev mode.
Therefore I tried to pass it in as argument like this:

activator -jvm-debug 9999 "run -Dhttp.port=1808 -Dhttp.address=myhost"

Looking into "playframework/framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala"
it seems to me that only the port argument is getting considered?!

How is it possible to set the address in dev mode (Ver, 2.3.8) ?

**Comment by jroper** [comment]
This isn't supported in dev mode, support was recently added in #3990, which will be available in Play 2.4.

If you require urgent support and are unable to fix things like this yourself, then perhaps you should consider getting Typesafe commercial support [here](http://typesafe.com/subscription).
