### ISSUE TITLE
Brand "Play" as "Play"

### ISSUE THREAD

**Issue by lazaridis-com** [playframework/playframework#4172]
(This is of course just an enhancement suggestion, which results out of my personal non-understanding experience. I believe that it would benefit newcomers in general.)

The Activator functionality, especially it's ui, is something very(!) positive.

The negative thing is that play get's intermixed with Activator (and Typesafe). The first Play! contact shows more "Activator" than "Play" (even the folder is named "Activator" and not "Play"), which can become very confusing.

To keep things for newcomers simple and straightforward, **Play!** should possibly simply be **Play!**

**Suggested Solution**

* make activator brandable (see typesafehub/activator#995)
* Brand "play" as "play"

**Look & Feel**

* **play** command is introduced again
* **play ui** launches the current Activator ui
* The ui shows Play! logos and links to **community** resources
* The ui shows only a discreet(!) "commercial support" which links to Typesafe

**Comment by wsargent** [comment]
+1

**Comment by cchantep** [comment]
Hi, I think this would be better discussed on the [Mailing List](https://groups.google.com/forum/#!forum/play-framework) rather on this issue tracker. Feel free to move the discussion.

**Comment by lazaridis-com** [comment]
I've invested some time & energy to isolate the most important issues subjecting play.

Feel free (as a team) to ignore them (or discuss them, on the mailing-list), but please note that this here **is** an **open** issue, category **enhancement** and/or **regression**, and thus it is correctly filed within the issue-tracker (and should of course be open).

**Comment by jroper** [comment]
The specific enhancement you've suggested is not something that we're willing to do.  While we certainly appreciate the feedback, and definitely will prioritise time to address this hopefully before the 2.4 release, there are multiple ways this can be addressed (better documentation is one example, making vanilla sbt more prominent in the docs is another example), and the mailing list is the best place to discuss what directions we might take.

**Comment by lazaridis-com** [comment]
I don't want to go into discussions. My main interest was to see if the team will get back on the usability-track, which it has clearly lost by introducing a chaos with the Activator tool. In any way, I've the answer I was seeking.

(just one final suggestion: you should tag this issue as "wontfix" or "worksforme", thus it becomes immediately clear why it was close)

**Comment by lazaridis-com** [comment]
Related Issue: #4179
