### ISSUE TITLE
Does not close the database connection active after recompiling

### ISSUE THREAD

**Issue by kuflash** [playframework/playframework#4173]
There is a problem with reconnecting to the database after recompilation. When there is a process, then why is the old connection is not closed. This leads to the fact that accumulated unsecured connection. Reset unsecured connection is possible only when the application stops. To work with the database I use ```JPA.em ("default")```

**Comment by cchantep** [comment]
Hi @kuflash , please ask question on the [Mailing List](https://groups.google.com/forum/#!forum/play-framework) to determine the, before filing a detailed issue.
