### ISSUE TITLE
[doc] Improve "first hour" experience of Play

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#4179]
From https://groups.google.com/d/msg/play-framework/z6lhHE3q3lE/I_fkVK8MrN8J

> After a few years hiatus from the Java web development world, I just got into the Play framework to evaluate it.
> 
> Here are some initial thoughts about my experience as a complete novice to Play. I'm hoping they will give the Play team some information to work with when creating the documentation, structure and features. If someone new to the framework has to struggle for just first run, they're going to abandon it for another framework. Neglecting this facet is the principal reason for lack of uptake.
>
> https://www.playframework.com/documentation/2.3.x/Installing
>
> The installation documentation leads you to a 400MB install for Typesafe Activator, rather than the minimal 1.5MB version. This is an immediate turn off, as a developer I think to myself: If just the "installer/manager" is 400MB, how big will the deploy end up being?
> 
> TypeSafe's web site lists some confusing licensing information. Will I need to subscribe for commercial deployments of Play? This still isn't completely clear to me, and there's only a link to contact a sales rep. Not a warm feeling from that, especially due to lack of clarity and no up front costs table for evaluation if a surprise paid license is dropped on my lap.
>
> https://www.playframework.com/documentation/2.3.x/NewApplication
>
> Missing a critical piece: Nowhere does this page state that you need to type "run".
>
> On my end, running the command "activator ui" took 10 minutes, without any indication it was doing anything. To be honest, I tried it a few times before and just closed the console window. But finally, as I was typing this it opened up a new tab in the background. The initial usability of this isn't ideal, especially considering there's no context as to what to expect: That it'll churn as long as it takes without indicators and then at some point open a browser tab. Second run was faster, but still about a 1min wait time.
>
>
> https://www.playframework.com/documentation/2.3.x/IDE
>
> Out of date for the Eclipse configuration, maybe more. Had to google that the correct way is to  run activator then type "eclipse my-app-name". This raises an interesting point: Why aren't the docs in a wiki, so they can be updated by the community? Is there a compelling reason to lock the community out of creating and maintaining docs?
>
>  The Play project imported, but initially had a bunch of compile errors. The project wasn't set to the correct JDK version - if there is a minimal JDK the project should flag that or this should be documented in the Eclipse setup page.
>
> The Debug Configuration as documented doesn't work. There are no .launch files created by the "eclipse" command. No remedy from Google. Was not able to debug even once.
>  
> https://www.playframework.com/documentation/2.3.x/PlayConsole
>
> This should be either in the "New Application" documentation, or that page should very strongly link that this is the next important thing to learn. As a developer, when I see "Play Console" I think to myself a wysiwyg tool for admin, but want to get right into writing code.
> 
> Overall:
> How activator, stb, typesafe, the play ui, the activator ui, the command line versions, scala vs java, etc of these all interrelate is completely opaque to a novice. 
> I'm a bit into researching this, following the documentation closely, and I still haven't been able to debug anything in Eclipse.
> The documentation is sorely fragmented and out of date, especially for the all important "first hour"
> Googling for help, it's often mixed with 1.x framework techniques. I understand the need for refactoring with 2.x, but this is working against you at the moment.

**Comment by benmccann** [comment]
Existing bugs discussing the activator default download:
https://github.com/typesafehub/activator/issues/602
https://github.com/typesafehub/activator/issues/798

Filed a bug for the SBT portion: https://github.com/sbt/sbt/issues/1954

Asked for follow-up on the Eclipse issue on the mailing list because I can't reproduce.

**Comment by lazaridis-com** [comment]
@wsargent , please be aware that you don't get always an **hour** from a newcomer. You can scare him away in the first minutes (or even seconds).

So, the goal should be to "Improve the first **contact** experience of Play" (= try to not scare away the newcomer in the first seconds, minutes, hours).

**Comment by wsargent** [comment]
Vastly improved in 2.5.x, closing.
