### ISSUE TITLE
Integrate Stormpath to Play2 application

### ISSUE THREAD

**Issue by terencetaih** [playframework/playframework#4188]
Hi all, 
I want to integration one of the best Oauth framework to my Play application, STORMPATH. 
But stormpath use javax.servlet.http.HttpServletRequest for authentication or authorizaion.
http://docs.stormpath.com/guides/api-key-management/#how-api-key-and-token-authentication-works

But play doesn't support ServletAPI. 
Please teach me how to solve this issue?

Thanks, 
Terence

**Comment by cchantep** [comment]
Hi, please ask on the [Mailing List](https://groups.google.com/forum/#!forum/play-framework) rather on this issue tracker.
