### ISSUE TITLE
Add reason phrase to Java API

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#4192]
It was added to the Scala API here: https://github.com/playframework/playframework/pull/4183

@pauldraper not sure if you want to take a stab at this, but usually we like to have feature parity between the two APIs

**Comment by pauldraper** [comment]
Yeah, I'll fix this.

**Comment by mkurz** [comment]
Friendly ping @pauldraper :smile:

**Comment by marcospereira** [comment]
@benmccann I think we can close this issue:

https://github.com/marcospereira/playframework/blob/ef34765a84b398b48e5800cbe6558c0ef034cfd6/framework/src/play/src/main/java/play/mvc/Result.java#L98-L105
