### ISSUE TITLE
Recreate the Samples Overview

### ISSUE THREAD

**Issue by lazaridis-com** [playframework/playframework#4198]
Regression

A nice Samples Overview was available for play 2.2.x

https://www.playframework.com/documentation/2.2.x/Samples

It seems that it was removed in 2.3.0

https://www.playframework.com/documentation/2.3.x/Samples

This samples-overview should be recreated  again (or provided in another way), thus a newcomer gets an attractive (screenshots) overview of available samples.

The (screen-shot containing) samples-overview could be alternatively provided right within the activator ui, see typesafehub/activator#997

**Comment by jroper** [comment]
The sample applications were replaced with activator templates:

http://typesafe.com/activator/templates

**Comment by lazaridis-com** [comment]
Yes, and this is an impressive list. But it does not contain the screenshots anymore, which is the main regression. So, the minimum would be to provide the screenshots again (see issue typesafehub/activator#997).

Now, if you think of Play! as a self-contained subsystem, then the samples should be under the playframework.com domain, and of course **only** the ones which address the open-source Play Framework.

Possibly at least a few (5 to 10) high-quality (and impressive) samples could be placed under the play domain (e.g. autogenerated from the central template list).

or, as stated, *"The (screen-shot containing) samples-overview could be alternatively provided right within the activator ui"*
