### ISSUE TITLE
`ConfigurationProvider` is defined without `@Inject` annotation

### ISSUE THREAD

**Issue by OlegIlyenko** [playframework/playframework#4199]
Looks like `ConfigurationProvider` was introduced in M3 and was defined without `@Inject` annotation. This is a problem, because at some point it's bound with `toProvider` method which translates in `ProviderConstructionTarget` thus requires class to follow JSR 330 annotation semantics. I commented a commit, that introduced this class:

https://github.com/playframework/playframework/commit/45bd537c6846345115d7b76ed4c92dc802a30b69#commitcomment-10612787

**Comment by jroper** [comment]
`@Inject` is only needed if the DI container is expected to instantiate it.  On line 21, you can see:

```scala
bind[ConfigurationProvider].to(new ConfigurationProvider(configuration)),
```

Since we explicitly provide an instance, this is ok.  Or, at least it's ok in Guice.  If it's a problem for other DI containers, then we should fix.

**Comment by OlegIlyenko** [comment]
Sorry, my fault - I was a little but confused and jumped into conclusions too fast :) The `ConfigurationProvider` is actually also bound explicitly just one line above, so it can be used for injection. You are right, it's a valid use-case.
