### ISSUE TITLE
[2.4.0-M3] Implicit formatter for Options not being passed

### ISSUE THREAD

**Issue by HandsomeCam** [playframework/playframework#4211]
In version 2.4.0-M3, when expecting an implicit format of an Option[A] where A does have an implicit format defined, the compiler can no longer detect the implicit format of the Option. 

This is somewhat hard to describe, so I've included a code sample that triggers the issue

    import play.api.libs.json.{ Json, Format, JsValue }

    case class Thing(a: String, b: Int) 

    object Thing {
      implicit val format = Json.format[Thing]
    }

    case class ThingWrapper(c: String, d: JsValue)

    object ThingWrapper {
      implicit val format = Json.format[ThingWrapper]
  
      def returnThing = {
        val thing = Thing("xxx", 0)
        val canWrap = WrappedResponse(thing)
    
        val canWrapList = WrappedResponse(List(thing))

        val tOpt = Option(thing)
        // compiler errors here --v
        val failWrap = WrappedResponse(tOpt)
    
        Json.toJson(failWrap)
      }
    }

    object WrappedResponse {
      def apply[A](value: A)(implicit f: Format[A]) = {
        ThingWrapper("ok", Json.toJson(value))
      }
    }

This same code *does* work in 2.3.8

OSX 10.10.2
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by julienrf** [comment]
Always write the return type of your implicit definitions:

~~~ scala
implicit val format: Format[Thing] = Json.format[Thing]
~~~

**Comment by HandsomeCam** [comment]
Thanks, will make sure to do that moving forward. Unfortunately it does not solve the problem in this case.

**Comment by HandsomeCam** [comment]
This is limited to `Format`. Changing the implicit argument to a `Writes` causes the sample code to compile correctly (with and without the explicit return type of the `format` val in the `Thing` object)

    object WrappedResponse {
      def apply[A](value: A)(implicit f: Writes[A]) = {
        ThingWrapper("ok", Json.toJson(value))
      }
    }

**Comment by cchantep** [comment]
Hi, this question should better be discussed on the [dedicated mailing list](https://groups.google.com/forum/m/#!forum/play-framework). Best regards.

**Comment by jroper** [comment]
This was removed in #3521, because the type `Option` doesn't adequately describe what the behaviour should be... is the values presence optional?  Is the value nullable?  Is it optionally the given type?  The answer to these three questions dramatically changes how `Reads[Option[A]]` should be implemented, but there's no way via implicit resolution that this can be known, so rather than providing surprising (and buggy) behaviour, we removed it, deciding that you should be explicit when reading of what you want.
