### ISSUE TITLE
Rebrand "Play" as "Activator"

### ISSUE THREAD

**Issue by lazaridis-com** [playframework/playframework#4219]
**Current Situation**

The confusion starts with the Play! download: you're not downloading play, **no** folder is named play, and **no** command is named play.

This leads to a very bad user experience, an example from #4179 

>How activator, stb, typesafe, the play ui, the activator ui, the command line versions, scala vs java, etc of these all interrelate is completely opaque to a novice.

This cannot be made better by changing documentation (as suggested in #4179). If the documented system is inconsistent, the documentation has to explain inconsistencies. If the system is consistent, then it becomes self-documenting (and thus not much documentation is needed).

And it is very important that the team **listens** to the feedback and realize: Play! is currently inconsistent.

The General Rule: Framework-Name = Command = UI Labels & Logos etc.

**Solutions**

The **first** solution is to revert the name-change (use the logical `play` command again, and to make Play! look more like Play!), see #4172.

The **second** (alternative) solution would be to simply let **Play!** become **Activator**  (The Activator Framework). If you read the docs, the website and take look at the ui of Play!, then it looks that this has already happen.

It is clear that the second solution is a big step. But if Typesafe plans this anyway, then it should do it without delays, simply to avoid the reduced adoption by confused users (as described nicely in #4179).

One positive influence would be, that Activator is relatively new, and thus this one would be solved, too:

>The documentation is sorely fragmented and out of date, especially for the all important "first hour"

**Comment by nafg** [comment]
@lazaridis-com you were already told that before opening tickets, you should start a discussion on the mailing list. Don't you care whether the community agrees with you are not?

**Comment by lazaridis-com** [comment]
@nafg, I care mostly to finish my evaluation, I care a bit about that Play! gets back on the usability-track, and I care to get relevant feedback (usually from the relevant people) within the media that I prefer (which is the issue-tracker). So, please, stay relevant and in-topic.

**Comment by cchantep** [comment]
Hi @lazaridis-com, thanks for your interest in Play. Obviously you are free to evaluate Play. Please consider [contribution rules](https://github.com/playframework/playframework/blob/master/CONTRIBUTING.md#reporting-issues) and first [use the Mailing List](https://groups.google.com/forum/#!forum/play-framework) to discuss changes which are not bug (see @jroper [comment](https://github.com/playframework/playframework/pull/4204#issuecomment-91387288)).
