### ISSUE TITLE
Futures with json transforms/reads?

### ISSUE THREAD

**Issue by alias1** [playframework/playframework#4221]
Heya,

So I was wondering if there is a way/best practice pattern to use Futures inside json reads/transforms. My basic usecase is that I want to read a string, encrypt it async, and update the key with the future encrypted value

```
case class EncryptedTFN(display: String, ciphertext: String)

implicit lazy val encryptedTfnFormat: Format[EncryptedTFN] = (
    (__ \ "display").format[String] ~
    (__ \ "ciphertext").format[String])(EncryptedTFN.apply, unlift(EncryptedTFN.unapply))

def transformTfn2EncryptedTfn(keyId: String)(implicit ec: ExecutionContext, kms: KMSClient) = 
    (__ \ "tfn").json.update(
      of[JsString].map { case JsString(tfn) => EncryptedTFN.encrypt(tfn, keyId) map { Json.toJson(_)}) })
```

To the best of my understanding digging around in JsPath/JsValue/Reads/etc, it seems there currently isn't any sort of support for futures there.

Looking at [JsPath.json](https://www.playframework.com/documentation/2.3.x/api/scala/index.html#play.api.libs.json.JsPath$json$) there is currently

`update[A <: JsValue](reads: Reads[A]): Reads[JsObject]`

Whereas I would see the future-enabled version probably looking something maybe like

`updateF[A <: JsValue](reads: Future[Reads[A]]): Future[Reads[JsObject]]`

And then eventually I would be able to use something like [JsValue's](https://www.playframework.com/documentation/2.3.x/api/scala/index.html#play.api.libs.json.JsValue) transform

`transformF[A <: JsValue](rds: Future[Reads[A]]): Future[JsResult[A]]`

Not understanding the deep technicalities of the current implementation, is this possible? And is this something you would be see as useful to include in the library? Or is there a better/more standard way to achieve what i'm attempting?

Edit: I also came across @mandubian's [play-json-zipper](https://github.com/mandubian/play-json-zipper/) which doesn't look to have been updated in a while, but might possibly be usable for what I want..?

**Comment by jroper** [comment]
To bake it into the library would mean all transformations have to be asynchronous, because as soon as one thing returns a `Future`, everything has to return a `Future` because you can't turn a `Future` into something that doesn't return `Future`.

A lot of the mechanics behind the json validation syntax though are generic enough that they could work with futures, though you may get much better milage out of using scalaz, which offers a lot more generalised helpers.

**Comment by cchantep** [comment]
I guess more questions about that can be asked on the [Mailing List](https://groups.google.com/forum/#!forum/play-framework).
