### ISSUE TITLE
Remove dependence on repo.typesafe.com/typesafe/releases

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#4223]
We want to remove our reliance on all repositories that aren't included with sbt by default, and the one that we currently rely on that isn't is http://repo.typesafe.com/typesafe/releases. While there should be no application dependencies there, build dependencies (eg sbt plugins and their dependencies) that only live there that I've discovered include:

* `net.contentobjects.jnotify:jnotify:0.94`
* `com.typesafe:jse_2.10:1.0.0`
* `com.typesafe:npm_2.10:1.0.0`
* `com.typesafe:webdriver_2.10:1.0.0`

At the moment we don't want to forgo the jnotify dependency, as it is the only option we have for event based (not polling) notification of filesystem changes.  We could solve this by deploying it to the play sbt bintray repository.  Ideally we'd shade it, but given that it's a jni library, we'd have to shade the binaries too, which is not really practical.

jse, npm and webdriver need to be updated to publish to maven central.

**Comment by jroper** [comment]
jse update publish to maven PR: https://github.com/typesafehub/js-engine/pull/36

**Comment by jroper** [comment]
webdriver update publish to maven PR: https://github.com/typesafehub/webdriver/pull/11

**Comment by jroper** [comment]
npm update publish to maven PR: https://github.com/typesafehub/npm/pull/1

**Comment by megazord** [comment]
@jroper #4224 was merged. Can we close this issue?

**Comment by jroper** [comment]
@megazord, no, #4224 was just removing the dependence on runtime dependencies, this issue is about build dependencies, which is addressed in #4235, but looks like it's going to be more work than I originally thought.

**Comment by cchantep** [comment]
See #4235
