### ISSUE TITLE
Failing parameterized tests are not failing test run when run via "activator test" or "test-only"

### ISSUE THREAD

**Issue by mknudsen** [playframework/playframework#4233]
@RunWith(Parameterized.class)
	public class ConfigFilesIntegrationTest {
	
	    @Parameterized.Parameter(0)
	    public String foo;
	
	    @Parameterized.Parameters
	    public static Collection<Object[]> data() {
	
	        return Lists.newArrayList(
	                new Object[]{"fooa"},
	                new Object[]{"foob"}
	        );
	    }
	
	    @Test
	    public void testSomething() throws Exception {
	        assertThat(somethingDependingOnTheValue(foo)).isNotNull().exists().isDirectory();
	    }
    }
    
Where the test is expected to fail for some values of `foo`. 
    
When I run the test suite via `activator run` or by running `test-only somepackage.ConfigFilesIntegrationTest` I can see the test failing since it emits `[error]`-lines to the console, yet the test run does not include the failed test in it's result (it counts as neither failing nor passing).

**Comment by cchantep** [comment]
I don't think `activator run` will run your tests (it's meant to run the webapp, not its tests).

Which errors do you see for `activator test`?

**Comment by mknudsen** [comment]
Yes sorry, `activator test` is was I meant (and ran). I've created an example project here https://github.com/mknudsen/play-parameterized-junit

If you run `activator test` there you will get

```
$ ./activator test
[info] Loading project definition from /private/tmp/play-parameterized-junit/project
[info] Updating {file:/private/tmp/play-parameterized-junit/project/}play-parameterized-junit-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to parameterized (in build file:/private/tmp/play-parameterized-junit/)
[info] Updating {file:/private/tmp/play-parameterized-junit/}root...
[info] Resolving jline#jline;2.11 ...
[info] Done updating.
[info] Compiling 4 Scala sources and 2 Java sources to /private/tmp/play-parameterized-junit/target/scala-2.11/classes...
[info] Compiling 1 Java source to /private/tmp/play-parameterized-junit/target/scala-2.11/test-classes...
[error] Test ApplicationTest.isNotBar[1] failed: actual value:<'bar'> should not be equal to:<'bar'>, took 0.003 sec
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[success] Total time: 8 s, completed 15.04.2015 09:19:01
```

Clearly the test is being executed (and in part failing), yet we get a success as well as 0 tests run in total.

**Comment by cchantep** [comment]
I tend to think that not specific to Play (or activator), so it's better you "move" this as question on the [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework) to get a broader help.

You can first try `sbt test` (instead of `activator test`) and have a look at [SBT test interface]( http://www.scala-sbt.org/0.13/docs/Testing.html).

**Comment by mknudsen** [comment]
Okay thanks. Does play use the sbt junit-interface by any chance? If so there seems to be a corresponding bug ticket here https://github.com/sbt/junit-interface/issues/66

**Comment by cchantep** [comment]
Play apps are built using either directly SBT or activator (which is an improved 'frontend' to SBT), so yes tests are runned using SBT test interface (nothing specific to Play indeed).
