### ISSUE TITLE
[WS] Warn on SHA-1 ciphers

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#4241]
Per http://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html

> The SHA-1 cryptographic hash algorithm has been known to be considerably weaker than it was designed to be since at least 2005 — 9 years ago. Collision attacks against SHA-1 are too affordable for us to consider it safe for the public web PKI. We can only expect that attacks will get cheaper.
>
> That’s why Chrome will start the process of sunsetting SHA-1 (as used in certificate signatures for HTTPS) with Chrome 39 in November. HTTPS sites whose certificate chains use SHA-1 and are valid past 1 January 2017 will no longer appear to be fully trustworthy in Chrome’s user interface.

WS should still accept SHA-1 certificates, but log warnings whenever they are used in an HTTPS connection.

**Comment by jroper** [comment]
Agree. Is it easy for us to do this, or would it require implementing a lot of custom things to get to a level where we can do that check?

**Comment by wsargent** [comment]
It's pretty easy.
