### ISSUE TITLE
sbt-native-packager doesn't copy configuration when play plugin is enabled

### ISSUE THREAD

**Issue by Kyprus** [playframework/playframework#4242]
The sbt-native-packager docs say [here](http://www.scala-sbt.org/sbt-native-packager/archetypes/java_server/customize.html#linux-configuration) that you can create an `application.ini` in `src/universal/conf` and it will process it and put it in the app's `conf` directory. When the play plugin is enabled this file does not end up in the conf directory. The sbt guys said this seems to be a problem with play.

https://github.com/Kyprus/sbt-native-packager-test demonstrates the issue

**Comment by huntc** [comment]
I suspect that this is `1.0.0` of the native packager as I think `application.ini` was added there. You should be able to use mappings as a work-around, but Play may need to take care of this in 2.4.

**Comment by Kyprus** [comment]
Yes, this is in 1.0.0 and play 2.4-M3. Should have mentioned that, sorry.

@huntc I'm not sure what you mean, which mappings?

**Comment by jroper** [comment]
The native packager source directory in Play is the `dist` directory, not `src/universal`.  So put your file in `dist/conf`.

**Comment by Kyprus** [comment]
@jroper Thanks! That worked. Also I noticed in the latest play docs (master) it says to put it in `src/universal/conf/` so that should probably be updated?

**Comment by jroper** [comment]
Pull request here: #4251
