### ISSUE TITLE
Controller definition with 22+ parameters

### ISSUE THREAD

**Issue by ClaraAllende** [playframework/playframework#4243]
As discussed in https://groups.google.com/forum/#!topic/play-framework/xh0GIoHMz48

Currently controllers in route definitions cannot use more that 22 parameters, even though Scala compiler has already lifted this limitation. This is due to the existing coupling between call method and FunctionN + tuples (which still have the 22 parameter limit).

Even though I could extract the parameters from the query string, I'd rather not, because I lose the type check, and because it seems somehow consistent to allow an arbitrary amount of parameters in controllers, since Scala has already lifted the limit up.

**Comment by cchantep** [comment]
See #4245

**Comment by megazord** [comment]
@cchantep I can't understand the relation between this issue and #4245.

**Comment by cchantep** [comment]
-1 => #4244
