### ISSUE TITLE
A specs2 concurrent specification runs sequentially in the activator

### ISSUE THREAD

**Issue by etorreborre** [playframework/playframework#4253]
Please have a look at [this issue](https://github.com/etorreborre/specs2/issues/359). The test case can be reproduced with a simple specification like this one:
```scala
class TestMutableSpec extends org.specs2.mutable.Specification {
  "test1" >> {
    Thread.sleep(400)
    "test1".pp
    ok
  }
  "test2" >> {
    Thread.sleep(300)
    "test2".pp
    ok
  }
  "test3" >> {
    Thread.sleep(200)
    "test3".pp
    ok
  }
  "test4" >> {
    Thread.sleep(100)
    "test4".pp
    ok
  }
}
```

Under `sbt` this specification prints out (as expected):
```
test4
test3
test2
test1
```

However with Play's sbt configuration the output is:
```
test1
test2
test3
test4
```

As if the specification was forced to run sequentially.

**Comment by cchantep** [comment]
Hi @etorreborre. Thanks for reporting that. Do use get this result using directly `sbt` or with `activator`? Which play version is involved?

**Comment by etorreborre** [comment]
You can try [this project](https://github.com/andyczerwonka/tyrion/tree/spec2_issue_359). I think this is with play `2.3.8`. I have just observed the issue by running `./sbt` locally, not with the activator (and Andy writes that he sees the activator running tests sequentially while sbt native runs them concurrently so I am a bit lost here).

**Comment by etorreborre** [comment]
I tried activator. I still see the tests passing sequentially.

**Comment by etorreborre** [comment]
No, Andy's right, the `activator ui` runs them concurrently.

**Comment by jroper** [comment]
@etorreborre that's correct. We configure Play projects to run sequentially by default:

https://github.com/playframework/playframework/blob/221bb54d21bc0836cbc40f54b9b624971e0ecda9/framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L77

Of course, users can override this, by setting it back to true, however, the problem is that with Play's global state, running tests in parallel typically leads to unpredictable test behaviour.  And even if we fixed the global state problem (which we're working on), it's quite normal in Play tests to start a test server to test against, which will bind to a port (a global resource), and so running the tests in parallel will lead to bind failures.

**Comment by etorreborre** [comment]
Thanks for the explanation James. Just for completeness you are also referring to https://github.com/playframework/playframework/blob/221bb54d21bc0836cbc40f54b9b624971e0ecda9/framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L81 where the concurrent execution of specs2 specifications is deactivated as well as between classes.

**Comment by andyczerwonka** [comment]
I'll create a PR to update the docs.

**Comment by megazord** [comment]
@jroper and @etorreborre, 

Does it means that we can remove lines like this?

https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala#L23

**Comment by andyczerwonka** [comment]
@megazord You can if you only run the test in sbt. If you run it in JUnit, you still need that.

**Comment by jroper** [comment]
@megazord there's also something odd about how we have things configured, currently, everything runs sequentially when you run `test`, but when you run `testOnly` or `testQuick` they only run sequentially if the spec is explicitly made `sequential`.  I've never got around to investigating why or how to fix.

**Comment by etorreborre** [comment]
@jroper maybe you have to add
```scala
testOptions in testOnly += Tests.Argument(TestFrameworks.Specs2, "sequential", "true", "junitxml", "console")
testOptions in testQuick += Tests.Argument(TestFrameworks.Specs2, "sequential", "true", "junitxml", "console")
```

**Comment by jroper** [comment]
Probably.
