### ISSUE TITLE
Multipart form data

### ISSUE THREAD

**Issue by hdlopesrocha** [playframework/playframework#4260]
request().body().asMultipartFormData() returns null if Http Boundary is something like
boundary====(random string here)===
boundary with '=' symbols

**Comment by wsargent** [comment]
Can you include a test case?

**Comment by wsargent** [comment]
Also, if you can be specific about what version of Play / Scala / JVM / OS you're running on, that helps too.

**Comment by hdlopesrocha** [comment]
I used MultipartUtility with Android, http://www.codejava.net/java-se/networking/upload-files-by-sending-multipart-request-programmatically#comment-2013

I'm not sure about the version that I am using, I can check that on monday

**Comment by hdlopesrocha** [comment]
Sorry for the late answer.
Play 2.3.8 (java) 

$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

OS: Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-32-generic x86_64)

**Comment by mkurz** [comment]
@hdlopesrocha Are you still having this issue with Play 2.4?

**Comment by hdlopesrocha** [comment]
I solved that problem by changing the "boundary" of that android utility, later my team moved to square's okhttp utility and we are not having problems so far.
