### ISSUE TITLE
[PROJECT] Provide a Github Issues Frontend

### ISSUE THREAD

**Issue by lazaridis-com** [playframework/playframework#4262]
(follow-up to #4228)

Getting an overview of the issues can be very difficult for both, team members and users/evaluators.

A `Github Issues Frontend` can simplify the work with the Issues.

One example is this one (possibly, other solutions are available):
* https://waffle.io/

**Comment by lazaridis-com** [comment]
testing waffle.io commenting via https://waffle.io/playframework/playframework

**Comment by cchantep** [comment]
Hi, such proposition must be discussed on the Mailing List.

**Comment by lazaridis-com** [comment]
Note to readers: **must**

**Comment by lazaridis-com** [comment]
http://huboard.com - another tool, free for open source
