### ISSUE TITLE
Make it easier to fake multipart form data request from Java

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#4272]
The FakeRequest object has methods that support JSON, raw, etc, but no method for multipart form data. The only solution I can see involves going via Scala objects: http://stackoverflow.com/questions/10890381/test-multipartformdata-in-play-2-0-fakerequest/28130543#28130543

We should add support for this.

**Comment by megazord** [comment]
@richdougherty,

I think this is duplicated with #2289 and maybe with #2125. Maybe we can consolidate these three issues.

**Comment by richdougherty** [comment]
Duplicate of #2280. Closing.
