### ISSUE TITLE
Simplify Download

### ISSUE THREAD

**Issue by lazaridis-com** [playframework/playframework#4282]
Currently, at the very first step of the Play! installation (Download), the user needs to think, because he's send to the Typesafe Website.

Naturally, the download text should link to a file, hosted on the playframework.com domain.

Ideally, this should be the `minimal` version, without even mentioning the alternate available version.

The resulting instruction would be:

* **Download** the `latest Play! Activator` (this links directly to playframework.com/download/activator-1.3.2) 

(this affects #4179)

**Comment by cchantep** [comment]
Big button to download the latest version directly start downloading ( https://playframework.com/download ). Same for older version.

**Comment by marcospereira** [comment]
@cchantep true, but I think a little repetition here could be a good thing. Since we are already directly linking Activator at the landing page, I don't see why to link to do the same thing at the Getting Started page.

**Comment by cchantep** [comment]
@marcospereira the ticket was about "Naturally, the download text should link to a file, hosted on the playframework.com domain.", not about repetition.

**Comment by marcospereira** [comment]
@cchantep I understood that this issue was about the getting started documentation. The [current version](https://github.com/playframework/playframework/blame/4af5159ff2786795caa4c880012150ef1eb1059c/documentation/manual/gettingStarted/Installing.md#L10) does not link to Activator's file (like the Play landing page does), but to Activator landing page. The repetition was about using the same link in both places.

**Comment by jroper** [comment]
Which page is this referring to?  This one?

https://playframework.com/documentation/2.3.x/Installing

If so, I thinks it's fair that that should point to https://playframework.com/download.

**Comment by lazaridis-com** [comment]
(@cchantep , having fun?)

Sorry, referring to [Getting Started/Install.md](https://github.com/playframework/playframework/blob/4af5159ff2786795caa4c880012150ef1eb1059c/documentation/manual/gettingStarted/Installing.md)

This issue (which in reality is **open**, but obviously @cchantep has his own reality) is something like a grand-issue, and contains:

- [ ] link directly to the *.zip (http://downloads.typesafe.com/typesafe-activator/1.3.2/typesafe-activator-1.3.2-minimal.zip)
- [ ] rename the zip to not contain the "minimal" part (see #798)
- [ ] move the zip to the playframework.com domain (the natural order of things)

The first step is easy (I can do it, as I currently work on the Install.md). The others need intervention from the team.

**Comment by cchantep** [comment]
@lazaridis-com in my reality changes which are not obvious need to be discussed, as indicated in the **contributions rules**, as it has been said on previous tickets.

Moreover the **cohabitation of Play w/ Activator & Typesafe services** has already been mentioned on previous tickets. There is nothing immediately actionable about that, it need to be discussed before.

**Comment by lazaridis-com** [comment]
(Note to readers: It's very easy to identify @cchantep  as a **major** barrier to play's evolution.)

**Comment by jroper** [comment]
Hi @lazaridis-com,

As I have [explained before](https://github.com/playframework/playframework/issues/4228#issuecomment-92595362), @cchantep is acting within the boundaries of what we expect from core Play team members.  You [made it clear that you didn't read](https://github.com/playframework/playframework/issues/4228#issuecomment-93113129) that, so I am not going to explain again.

Saying that @cchantep is in his own reality is a personal attack and therefore is in violation of our [code of conduct](https://playframework.com/conduct).  While we appreciate your feedback and efforts to make the first user experience of Play better, open source is first and foremost about a community of people working together, the code/documentation comes second to that.  If you cannot follow our guidelines for how our community works, or respect our code of conduct, then you will leave us no choice but to block you.

Regards,

James

**Comment by lazaridis-com** [comment]
(I'll ignore for now what is a **clear** attack against my personality, individualism and finally contributions)

It would be nice if people would just **focus** on the issue at hand. The overhead of changing just a tiny link  is getting quite exhausting. This issues real status is still **open**, and I'm wondering why everybody ignores reality, and keeps it closed.

(Please keep your further writings in-topic, it's an issue-tracker here, not a mailing-list)

-----

(Note to readers: @jroper = Teach Lead of Playframework)

**Comment by lukaswelte** [comment]
Sometimes the change of a tiny thing might cause a significant change for the user.
Think of your operating system is changing the color of its close window button (or "just" switching the position). 

I clarify I am not connected with the Typesafe Team, I am just a user of the play framework.
In my perspective it is up to the maintainers of a Open Source Project, how they want to maintain it.
It is not an easy job doing this, especially for a large project like the Play Framework. 
As a maintainer you need to find a balance between speed of innovation, quality and support. 
The separation between concrete issues regarding the project and meta discussion to the project (and its documentation) into separate platforms might cause difficulties to choose the right platform for the discussion, but in the same time it makes sense for a lot of problems.

I think every contribution should be taken serious, regardless wether they come from ancient or new users. One can learn a lot from both of these groups.
But in the same time I think that contributors should try to understand the maintainers side in dealing with all these contributions / suggestions.

To sum this all up. 
I do not think @jroper and @cchantep wanted to attack your personality, they just wanted you refine your contribution and place it at the proper place (the place the contributors find most accurate).
On the criticism side.. @cchantep might have closed this issue to early while he may misunderstood your contribution. And @lazaridis-com would have done better when you would try to re-express yourself in different words and maybe come up with a more detailed description of your contribution, than being offended by the action of the contributor. Take care of your language and do not offend others (especially when you do not want others to offend you). The use of aggressive voice never helps in such situations.

I hope @lazaridis-com you can start the discussion about this feature and show people why you think this is needed and valuable.

**Comment by cchantep** [comment]
This ticket
