### ISSUE TITLE
2.4.0-RC1: Custom log level doesn't identify Logger(this.getClass())

### ISSUE THREAD

**Issue by markusjura** [playframework/playframework#4289]
The Play documentation in 2.4.0-RC1 recommends to use a distinct logger per class: https://www.playframework.com/documentation/2.4.0-RC1/ScalaLogging

> A common strategy for logging application events is to use a distinct logger per class using the class name. The logging API supports this with a factory method that takes a class argument:
```
val logger: Logger = Logger(this.getClass())
```

If this distinct logger for a certain class should log different log levels we need to create a custom `logback.xml` in the `conf` directory. However, the distinct logger is not identified from the logging system and therefor the log messages are treated with the log level as specified in the `root` node of the `logback.xml`.

Example Class:
```
class UserController extends Controller {
  // Name of logger is 'c.UserController'
  val log = Logger(this.getClass())

  def renderUser = Action {
    log.debug("this is a debug message")
    Ok("Render user")
  }
}
```

Example logback.xml:
```
<configuration>

  <conversionRule conversionWord="coloredLevel" converterClass="play.api.Logger$ColoredLevel" />

  <appender name="FILE" class="ch.qos.logback.core.FileAppender">
    <file>${application.home}/logs/application.log</file>
    <encoder>
      <pattern>%date [%level] from %logger in %thread - %message%n%xException</pattern>
    </encoder>
  </appender>

  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%coloredLevel %logger{15} - %message%n%xException{10}</pattern>
    </encoder>
  </appender>

  <logger name="play" level="INFO" />
  <logger name="application" level="DEBUG" />
  <logger name="ApplicationController" level="DEBUG" />
  <logger name="c.UserController" level="DEBUG" />

  <!-- Off these ones as they are annoying, and anyway we manage configuration ourself -->
  <logger name="com.avaje.ebean.config.PropertyMapLoader" level="OFF" />
  <logger name="com.avaje.ebeaninternal.server.core.XmlConfigLoader" level="OFF" />
  <logger name="com.avaje.ebeaninternal.server.lib.BackgroundThread" level="OFF" />
  <logger name="com.gargoylesoftware.htmlunit.javascript" level="OFF" />

  <root level="INFO">
    <appender-ref ref="STDOUT" />
    <appender-ref ref="FILE" />
  </root>

</configuration>
```

Interestingly this problem only occurs if `Logger(this.getClass())` is used. If I'd specify `Logger("c.UserController")` the custom configuration from `logback.xml` for this logger is picked up correctly.

A sample project with this error has been created here: https://github.com/markusjura/play24-logging

In this example the `NewsController` and `UserController` are both using a custom logger with a logging configuration of log level debug. However logging messages in debug only works for the `NewsController`, but not for the `UserController`. `NewsController` creates the custom logger by specifying a string while `UserController` uses `this.getClass()`.

**Comment by jroper** [comment]
@markusjura, what is the name of the package that your controller lives in?  `controllers`?  If so, then the name of the logger is `controllers.UserController`, not `c.UserController`, and you should configure that:

```xml
<logger name="controllers.UserController" level="DEBUG" />
```

The `c.UserController` that you see in the log output is just an abbreviation, controlled by the 15 in the pattern layout string `%logger{15}` - what logback does is attempts to keep the logger less than 15 characters, by abbreviating package names to one character from left to right.  This ensures that your logs aren't full of 100 characters of typically meaningless package name data for every log statement, forcing the actual messages way to the right and making the logs hard to read.

**Comment by markusjura** [comment]
@jroper That makes completely sense. With `<logger name="controllers.UserController" level="DEBUG" />` in the logback.xml it is working.

Thanks for the quick help.
