### ISSUE TITLE
[WS] Standalone play-ws

### ISSUE THREAD

**Issue by jvliwanag** [playframework/playframework#4297]
Play-ws is an awesome simple to use web client. It is unfortunate however that I cannot use it for writing client libraries since it depends on the entire play project.

It would be preferrable if play-wa can stand on its own with a minimal set of dependencies similar to play-json.

**Comment by jroper** [comment]
Doing this would require significant detangling.  For example, play-ws's xml support depends on Play's XML parser instance, which is configured to avoid many xml security vulnerabilities.  Making play-ws not depend on Play would require either duplicating that, or putting it into a separate library.  There are a number of other similar dependencies from play-ws to the play core codebase, especially in the play-ws Java support.

**Comment by wsargent** [comment]
@jvliwanag if you're interested in working on a branch, you could move out the WSClient API into another project and map out the dependencies and see how much would it would be.

**Comment by nafg** [comment]
+1

**Comment by wsargent** [comment]
This looks like 2.5 or 3.0 at the earliest.

**Comment by ktoso** [comment]
+1, sounds pretty useful :)

**Comment by wsargent** [comment]
This is something that could benefit if we could put in shims to isolate the XML and JS functionality i.e. json4s, the "secure by default" XML parser in its own package, etc.

**Comment by queirozfcom** [comment]
+1

**Comment by wsargent** [comment]
We have typesafe/ssl-config now, so at least one down...

**Comment by ariens** [comment]
+1, looking to use alongside Spark streaming from Kafka and need a light weight yet functional and versatile HTTP client

**Comment by giovannicandido** [comment]
Very usefull

**Comment by nartamonov** [comment]
+1

**Comment by vpagliari** [comment]
Definetly +1, would be very useful if it were available for at least Akka projects that doesn't have Play on it..

**Comment by dwijnand** [comment]
https://github.com/eed3si9n/gigahorse might be of interest.

**Comment by wsargent** [comment]
This is being addressed at https://github.com/playframework/play-ws
