### ISSUE TITLE
2.4.0-RC1 - GlobalSettings.filter broken

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#4311]
My index page had `@CSRF.formField`. It would error when I hit the page

I had the CSRF filter configured in a Global, which wasn't working. I had to create a `Filters` class instead

Maybe we should just get rid of Global since there seems to be a better way (https://github.com/playframework/playframework/pull/4308) to do this now

**Comment by jroper** [comment]
I think that can be fixed, we can make the default Filters implementation delegate to the Java global settings if it exists.

**Comment by richdougherty** [comment]
Filters defined in Java GlobalSettings objects seem to work OK. I wrote some integration tests in #4443 and the filters ran fine. I'll investigate in a real Java project and see if I can find the cause.

**Comment by gmethvin** [comment]
Reopening. Github seemed to think #4443 fixed this.

**Comment by richdougherty** [comment]
@benmccann, I tried to reproduce this in a small Play-Java app using `Global.filters` and `@CSRF.formField` but it worked fine for me. I used yesterday's nightly (`2.4.0-2015-05-13-527e4ee-SNAPSHOT`). Can you give some more info?

**Comment by benmccann** [comment]
Hmm. Maybe it's fixed now. I think it could have been fixed by https://github.com/playframework/playframework/commit/fa84a4ccae2499c614175601d5cf7c7ff40fb4b1 

Anyhow, I guess we can close this now. Thanks for taking a look at it Rich!

**Comment by richdougherty** [comment]
OK no worries!
