### ISSUE TITLE
Adding anchors to sub-headings within the documentation.

### ISSUE THREAD

**Issue by mhzajac** [playframework/playframework#4325]
When linking to pages in the documentation, it would be highly convenient to have anchors at each major sub-heading. Many pages are quite long, so when directing someone to a specific heading, all one can really do now is link the relevant page, and tell them what section to look for. For example, [ScalaJsonCombinators](https://www.playframework.com/documentation/2.3.x/ScalaJsonCombinators). If I want to direct someone to the **Recursive Types** sub-heading, it would be nice to use the url https://www.playframework.com/documentation/2.3.x/ScalaJsonCombinators#RecursiveTypes

**Comment by jroper** [comment]
https://www.playframework.com/documentation/2.3.x/ScalaJsonCombinators#Recursive-Types
