### ISSUE TITLE
2.4.0-RC1 Regression: Debian-Packager creates "broken" packages

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#4329]
I upgraded my app from Play 2.3 to the latest 2.4.0-RC1. 
When creating debian packages with 
```
sbt debian:packageBin
```
the resulting debian package is unable to run on my production system.
(Meaning, a Java Process is started, but my app never starts serving on port 9000)

It looks like, that the local configuration in /etc/default/appname is not read anymore. 

my /etc/default/appname in 2.3 looked like

```
-Dpidfile.path=/var/run/appname/play.pid
-Ddb.default.url=jdbc:postgresql://192.168.57.50/appname
```
in 2.4 it seems to have a new syntax and i changed it to 

```
JAVA_OPTS="-Dpidfile.path=/var/run/appname/play.pid $JAVA_OPTS"
JAVA_OPTS="-Ddb.default.url=jdbc:postgresql://192.168.57.50/appname $JAVA_OPTS"
```

The migration guide mentions no change in this area.

**Comment by domdorn** [comment]
ok, the problem only is with Upstart packaging. When I change to SystemV, the /etc/default/appname.conf is correctly sourced

```scala
import com.typesafe.sbt.packager.archetypes.ServerLoader.{SystemV, Upstart}

serverLoading in Debian := SystemV
```

**Comment by benmccann** [comment]
I'm not all that familiar with the deb packaging myself. Perhaps @muuki88 can chime in whether it's a bug in [native packager](https://github.com/sbt/sbt-native-packager), in Play, or user error.

**Comment by jroper** [comment]
Hmm... it'd be nice if native packager maintained a changelog/migration guide that we could link to from the Play migration guide.

**Comment by huntc** [comment]
Hey @jroper - this is what they have: https://github.com/sbt/sbt-native-packager/releases

On the subject of /etc/defaults, files in that folder are expected to be scripts as a general Unix convention. The 1.0 of native packager now honours that. The equivalent now is an `application.ini` file in your archive's `conf` folder.

HTH.

**Comment by jroper** [comment]
Oh that's awesome.  We should update the Play migration guide to link to that.  And I see that this breaking change is mentioned there... though perhaps a little more explanation of what the consequence of sourcing /etc/default is would be nice.

**Comment by muuki88** [comment]
I added a link  in the releases notes from `1.0.0` to `1.0.0-RC1` where the change was introduced and is explained in a bit more detail.

**Comment by domdorn** [comment]
I adjusted the migration guide
pull req. is https://github.com/playframework/playframework/pull/4337

**Comment by muuki88** [comment]
+1

**Comment by cchantep** [comment]
See #4337

**Comment by muuki88** [comment]
Also take a look at the [sbt-native-packager docs on play](http://www.scala-sbt.org/sbt-native-packager/topics/play.html)
