### ISSUE TITLE
Maven dependencies version format unsupported?

### ISSUE THREAD

**Issue by palako** [playframework/playframework#4341]
Added a maven dependency to dependencies.yml which in turn had some other dependencies in its pom file. One of these dependencies had a version field with a complex format that could not be resolved.

Here are the details to better illustrate the issue:

dependencies.yml
require:
   - play
   - com.nimbusds -> oauth2-oidc-sdk 4.13

When running play dependencies, the error is an unresolved dependency:

com.nimbusds#nimbus-jose-jwt;[3.9.2,]: not found

Inside oauth2-oidc-sdk 4.13 pom.xml there's this dependency:

<dependency>
<groupId>com.nimbusds</groupId>
<artifactId>nimbus-jose-jwt</artifactId>
<version>[3.9.2,]</version>
</dependency>

I've been able to go around this issue by adding the dependency to the yml:
require:
    - play
    - com.nimbusds -> nimbus-jose-jwt 3.10
    - com.nimbusds -> oauth2-oidc-sdk 4.13

Play! version 1.2.7

**Comment by cchantep** [comment]
Hi, please first ask on the [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework). If the issue is confirmed, please raise it on [Play 1 issue tracker](https://github.com/playframework/play1/issues).
