### ISSUE TITLE
Request of Change: Iteratee

### ISSUE THREAD

**Issue by Hayena** [playframework/playframework#4344]
In the `Iteratee` object a trait `EofOrElse` is defined. The otherwise parameter is not lazy which means that it is always executed. This means if you want to put some kind of error handling inside the otherwise it will always be executed even when it is not needed.

An example of how this could be fixed:
```scala
trait EofOrElse[E] {
    def apply[A, B](otherwise: => B)(eofValue: A): Iteratee[E, Either[B, A]]
  }
```

```scala
private def eofOrElse[E] = new EofOrElse[E] {
  def apply[A, B](otherwise: => B)(eofValue: A): Iteratee[E, Either[B, A]] = {
    def cont: Iteratee[E, Either[B, A]] = Cont((in: Input[E]) => {
      in match {
        case Input.El(e) => Done(Left(otherwise), in)
        case Input.EOF   => Done(Right(eofValue), in)
        case Input.Empty => cont
      }
    })
    cont
    }
}
```

**Comment by cchantep** [comment]
Thanks for reporting. Would you mind attaching a PR with the suggested changes?

**Comment by Hayena** [comment]
https://github.com/playframework/playframework/pull/4345
