### ISSUE TITLE
optional(text) doesn't cater for the empty string

### ISSUE THREAD

**Issue by akash1810** [playframework/playframework#4346]
I've a use case of allowing a user to set custom metadata on an asset which will always override system generated metadata. For example, an asset has a title associated with it, if a user doesn't want a title set, they can enter an empty string. There's a problem with OptionalMapping as it converts the empty string to null:

```scala
// routes
PUT /test controllers.Application.test()
```

```scala
// Application.scala
import play.api.data._, Forms._
import play.api.mvc.{Action, Controller}
import play.api.libs.json._

object Application extends Controller {
  val stringForm: Form[Option[String]] = Form(
     single("data" -> optional(text))
       .transform[Option[String]]({ case (value)       => value },
                                  { case value: Option[String] => value })
  )

  def test() = Action.async(parse.json) {req =>
    stringForm.bindFromRequest()(req).fold(
      hasErrors => Future.successful(BadRequest(hasErrors.errorsAsJson)),
      success => Future.successful(respond(success))
    )
  }
}
```

Performing a `PUT` request to `/test` with the payload `{"data": ""}` yields the result `{"data": null}` which isn't entirely correct.

The data store for this application is a Dynamo instance; Dynamo cannot store `null` [see here](https://forums.aws.amazon.com/message.jspa?messageID=389032).

**Comment by jroper** [comment]
Not sure what you're talking about - where is the null?

**Comment by akash1810** [comment]
`null` is in the response. When I `PUT` `{"data": "hi"}` the response is `{"data": "hi"}` as expected. When I `PUT` `{"data": ""}` the response is `{"data": null}` when the expected (and desired) response is `{"data": ""}`.

**Comment by jroper** [comment]
What's the implementation of the `respond` method?

**Comment by jroper** [comment]
Btw:

```scala
       .transform[Option[String]]({ case (value)       => value },
                                  { case value: Option[String] => value })
```

Does nothing, that's a noop.

And why are you using the form API to parse JSON?  It's very limited for that purpose, it only exists as a convenience for when you have an HTML form, and you want to be able to submit it both as a form and as json.  If you're not doing that, then you should use the json API instead.

**Comment by jroper** [comment]
And, that's why "" is leading to null, because in an HTML form, no value is the empty value.  That's why you shouldn't use the form API to parse JSON, use the JSON API.
