### ISSUE TITLE
initialSettings should be Map<String,Object> instead of Map<String,String>?

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#4362]
initialSettings has type Map[String, String]:
https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/ApplicationLoader.scala#L88
https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/ApplicationLoader.java#L70

This doesn't seem right to me. What if you want to pass a setting that isn't a String?

**Comment by jroper** [comment]
Agreed.

**Comment by benmccann** [comment]
Actually, I'm realizing that Map<String,?> is probably more appropriate. But I just tried that am not sure how to get that to compile
