### ISSUE TITLE
Fix late April performance regression

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#4364]
[Prune](http://playframework.github.io/prune/) shows that a performance regression occurred in late April.  This was probably caused by the change to add the Date header to all outgoing requests, see #4214. Discussion of the probably cause: https://github.com/playframework/playframework/pull/4214#issuecomment-96428142

cc @gmethvin.

**Comment by gmethvin** [comment]
From a performance standpoint it seems fair to add it in NettyResultStreamer. The filter-based solution was aimed more at giving us flexibility down the line to add different default headers, but I wasn't really sure if it'd be worth the overhead to have it on every response.

**Comment by richdougherty** [comment]
#4367 has improved performance, but maybe not to quite what it was before the Date header was added back in #4214. Before #4214, performance on scala-simple was about 63–64k req/s. After #4214 it went down to 56–57k req/s. #4637 has lifted performance back up to 62k req/s, about 1–2k req/s less than before. I think this is OK performance, so I don't think we need to spend any more time on this, but it's interesting how even a small change can slow things down!
