### ISSUE TITLE
Wrapping parse.multipartFormData with parse.maxLength always returns BadRequest

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#4374]
Doesn't matter what value I provide to `parse.maxLength`, the result is always the same: `Request Entity Too Large`. I am testing with a 1MB file to upload.
````
def upload = Action(parse.maxLength(10000000, parse.multipartFormData)) { request =>
   ... 
}
````
Here is the Ajax that does the upload:
````
  var data = JSON.stringify(form.serializeObject());
  var route = jsRoutes.controllers.AjaxController.upload();
  $.ajax({
    type: "POST",
    dataType: "json",
    url: route.url,
    data: data,
    error: function(xmlHttpRequest) {
      console.log(xmlHttpRequest);
    },
    success: function(data) {
      console.log(data);
    }
  });
````

BTW, it might be worth mentioning in the docs that the largest file that can be uploaded is of length `Int.MaxLength` (2147483647 bytes).

**Comment by richdougherty** [comment]
What version of Play are you using?

**Comment by mslinn** [comment]
Oops, 2.4.0-RC1

**Comment by mslinn** [comment]
My Ajax was at fault. No problem with Play. Apologies!
