### ISSUE TITLE
Play 2.3.8 - Play Plugins Duplicated produce EHCache error

### ISSUE THREAD

**Issue by rkpost** [playframework/playframework#4382]
Situation:
add Play with sources and cache plugin to your project

SBT Dependencies
val playVersion = "2.3.8"
val playCore = "com.typesafe.play" %% "play" % playVersion
val playCache = "com.typesafe.play" %% "play-cache" % playVersion
val playWs = "com.typesafe.play" %% "play-ws" % playVersion
val play = Seq(playCore, playWs, playCache).map(_.withSources())

Then WithDefaultPlugins finds six files, binary and sources
val pluginFiles = self.classloader.getResources("play.plugins").asScala.toList ++ self.classloader.getResources("conf/play.plugins").asScala.toList

pluginFiles.distinct doesnt work because are different, so Play create all of them twice.

If you try to use EhCache plugin, doesnt work because Play will try to create 2 caches (second one fails)

Recommendation, add a pluginFiles.filter() in order to remove sources
jar:file:/home/xxxxx/.ivy2/cache/com.typesafe.play/play-cache_2.11/jars/play-cache_2.11-2.3.8-sources.jar!/play.plugins

**Comment by jroper** [comment]
Since plugins are deprecated in Play 2.4, this won't be fixed. But why are you adding sources to the classpath of project? IDEs etc are able to resolve sources without them having to actually be on the classpath.
