### ISSUE TITLE
Remove thread pool Configurator once upgraded to Akka 2.4

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#4383]
In #4278 I copied and modified some Akka 2.3 code to add a new thread pool configuration option. We can remove the copied code once we upgrade to Akka 2.4.

Code to remove: https://github.com/playframework/playframework/blob/3ae7a1c799bdef9e737f5d9752674f16ba5a52b5/framework/src/play/src/main/scala/play/api/libs/concurrent/PlayAkkaDispatcherConfigurator.scala

Akka issue to track: https://github.com/akka/akka/issues/17274

**Comment by 2m** [comment]
Freshly released Akka `2.3.11` contains this configuration options as well.

**Comment by richdougherty** [comment]
I'd like to remove this code for the next 2.4.0 RC, but it's not urgent.
