### ISSUE TITLE
Update to latest Akka HTTP and Streams

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#4384]
We're a few releases behind now. We should update Play's dependencies before we release Play 2.4.

**Comment by benmccann** [comment]
Just be aware of this issue: https://github.com/playframework/playframework/commit/bc6bf49f447c1c7b804a065f8e3c4a0bfff1d602

**Comment by richdougherty** [comment]
OK I'll keep #4381 and https://github.com/akka/akka/issues/16327 in mind.
