### ISSUE TITLE
Investigate slow chunked performance

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#4387]
Our automated performance tests show very slow performance with chunked encoding. Streaming 50kb non-chunked gives about 44,000 requests/second and latency of 0.7ms. Streaming it chunked gives 800 requests/second and latency 40ms.

Yes, that's 44,000 vs 800—a 55× difference!

You can see the differences on the [Prune results page](http://playframework.github.io/prune/). The non-chunked tests have names ending with _-download-50k_, the chunked tests have names ending with _-download-chunked-50k_.

This is not a regression on master since it was already present in Play 2.3, however it is something that we need to investigate.

Something that is extremely suspicious is the fact that the latency for chunked responses is almost exactly 40ms which is the [default delay for Nagle's Algorithm on Linux](http://stackoverflow.com/a/2253620/49630).

I did a packet dump on my machine (Mac OS) and I couldn't reproduce the 40ms delay. The next thing to try is getting a packet dump on the Prune test machine or on another Linux machine.

**Comment by richdougherty** [comment]
Here is the code for the test: https://github.com/playframework/prune/blob/apps-master-3/scala-bench/app/controllers/Application.scala#L21-L40

**Comment by wsargent** [comment]
I know that we've had TTFB problems resulting from the [combination of Nagle's and Delayed Ack](https://www.extrahop.com/company/blog/2016/tcp-nodelay-nagle-quickack-best-practices/).  If you turn on TCP_NODELAY, do you still see it?

**Comment by richdougherty** [comment]
I think we can close this now because performance is now 8k req/s for chunked responses.
