### ISSUE TITLE
[WS] Give WSResponse a reference to its WSRequest

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#4405]
Giving `WSResponse` a reference to its `WSRequest` would be very useful.

**Comment by marcospereira** [comment]
Hello @dwijnand,

What would be use case here? Why do you think this is important?

**Comment by wsargent** [comment]
Is there a reason you'd want this in the core framework, rather than writing an application wrapper for it?

**Comment by dwijnand** [comment]
@marcospereira My use case is logging. Before I opened this ticket I was holding on to a reference of the request (actually the builder) so that I could log information on failure, but I'm safely casting the response to `AHCResponse`, and using `getUri`.

@wsargent I'm happy for it to be outside of the framework, but what did you have in mind?

**Comment by wsargent** [comment]
@dwijnand I think you're already doing what I had in mind -- the application should hold on to the request and tie it to the response:

```
val request =  wsClient.url(someURL)
val pair = request.get().map { response =>
   (request, response)
}
```

**Comment by wsargent** [comment]
Closing.

**Comment by dwijnand** [comment]
why?

**Comment by wsargent** [comment]
AHC doesn't do it. It's not done anywhere else in the code base (i.e. a Play result doesn't have the request attached to it) and if it's needed, you can map through to a Future[(WSRequest, WSResponse)] in application code.

**Comment by dwijnand** [comment]
Ok. Thanks.
