### ISSUE TITLE
Add `specs2-scalacheck` support?

### ISSUE THREAD

**Issue by hanfeisun** [playframework/playframework#4409]
I want to add `specs2-scalacheck`. However, I didn't find a way to get the `Specs2Version` used by Playframework in my own `build.sbt`. (I thought it was defined in https://github.com/playframework/playframework/blob/8d8e022178ab5c5fcebc68f35263dde6acf8f111/framework/project/Dependencies.scala)

Is there a way to use `specs2-scalacheck` using the same version as the `Specs2Version` of Playframework?

**Comment by cchantep** [comment]
Hi @hanfeisun . Please ask such question first on the [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework), where you will get more help in this case. Then if any improvement/fix is seen as actionable, a ticket can be filed in this issue tracker. Best regards.
