### ISSUE TITLE
Security: application.secret is logged

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#4418]
I just had someone on my team send me this. We definitely want to avoid our application secret being logged in production

!! WARNING !! -mem option is ignored. Please use -J-Xmx and -J-Xms
2015-05-08 17:17:38,171 - [WARN] - application in main - 
Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.

2015-05-08 17:17:46,292 - [WARN] - application in main - 
/usr/local/users/connectifier/application.conf: 7: application.secret is deprecated, use play.crypto.secret instead:

2015-05-08 17:17:46,354 - [WARN] - application in main - 
application.secret="[redacted]"

**Comment by jroper** [comment]
Indeed.  It only gets logged if you use the deprecated config path, but
yes, we shouldn't do that for the application secret.

On 9 May 2015 at 05:33, Ben McCann <notifications@github.com> wrote:

> I just had someone on my team send me this. We definitely want to avoid
> our application secret being logged in production
>
> !! WARNING !! -mem option is ignored. Please use -J-Xmx and -J-Xms
> 2015-05-08 17:17:38,171 - [WARN] - application in main -
> Logger configuration in conf files is deprecated and has no effect. Use a
> logback configuration file instead.
>
> 2015-05-08 17:17:46,292 - [WARN] - application in main -
> /usr/local/users/connectifier/application.conf: 7: application.secret is
> deprecated, use play.crypto.secret instead:
>
> 2015-05-08 17:17:46,354 - [WARN] - application in main -
> application.secret="[redacted]"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playframework/playframework/issues/4418>.
>



-- 
*James Roper*
*Software Engineer*

Typesafe <http://typesafe.com/> – Build reactive apps!
Twitter: @jroper <https://twitter.com/jroper>

**Comment by richdougherty** [comment]
Fixed by #4421.
