### ISSUE TITLE
Incompatibility with async-http-client 1.9

### ISSUE THREAD

**Issue by bertvh** [playframework/playframework#4428]
In the play testing documentation (https://www.playframework.com/documentation/2.3.9/ScalaFunctionalTestingWithScalaTest), the following line shows how to call an http method:

```val response = await(WS.url(testPaymentGatewayURL).withQueryString("callbackURL" -> callbackURL).get())```

When doing so, the test crashes with 

```java.lang.NoSuchMethodError: com.ning.http.client.AsyncHttpClientConfig$Builder.setConnectionTimeoutInMs```

Indeed in the async-http-client library, that method doesn't exist anymore and is replaced by  `setConnectTimeout` (I guess).

Is there a workaround for this until it is fixed?

See also: https://github.com/AsyncHttpClient/async-http-client/issues/684

**Comment by marcospereira** [comment]
Did you upgraded async-http-client by yourself? The version used by Play 2.3.9 is 1.8.15:

https://github.com/playframework/playframework/blob/2.3.9/framework/project/Dependencies.scala#L245

**Comment by bertvh** [comment]
Apologies. I double checked and noticed there is another library that depends transitively on the async-http-client 1.9. I totally missed that.
