### ISSUE TITLE
[Play 2.3.8] If condition bring line feed in scala template

### ISSUE THREAD

**Issue by puneetar** [playframework/playframework#4433]
Hi all,

I am facing issue with if conditions in scala template. In the following circumstance, the html will break due to the line find between two divs. 

````
<div>
    content in previous div.
</div>
@if(condition) {
    <div>
        content in next div
    </div>

}

**Comment by marcospereira** [comment]
@puneetar 

What code is rendered and what code is expected? What do you mean by "break"? Moreover, if there is an issue, is should probably be discussed at the playframewor/twirl project instead.

**Comment by puneetar** [comment]
@marcospereira, it actually results into a line break and white spaces in the HTML.
Will discuss it on the twirl project.

Thanks
