### ISSUE TITLE
Session configuration is sometimes ignored

### ISSUE THREAD

**Issue by fernandezpablo85** [playframework/playframework#4434]
The fact that `play.mvc.Session` object has `val`s for the keys `cookieName`, `maxAge` and `httpOnly` makes it ignore plays configuration values if the `Session` object is referenced before `Play.maybeApplication` is loaded.

This is not at all an edge case, consider this `Filter`, for example: 

```scala
object ExpiredSession extends Filter {

  val redirectHome = Results.Redirect(controllers.routes.Application.home).withNewSession

  def apply(next: (RequestHeader) => Future[Result])(request: RequestHeader) = {

      if (sessionExpired)
        Future.successful(redirectHome)
      else
        next(request)
  }
}
```

This will cause the `Session` object to initialise before the application is ready, and the `session.httpOnly` config (and others) would be ignored forever.

**Comment by fernandezpablo85** [comment]
@julienrf shall we close this?

**Comment by marcospereira** [comment]
@fernandezpablo85 I think we can close this issue, considering that both #4435 and #4437 were merged. 

By the way, thanks for your time to contribute.

**Comment by fernandezpablo85** [comment]
you're welcome!
