### ISSUE TITLE
Weird behavior when generating junitxml 

### ISSUE THREAD

**Issue by slorber** [playframework/playframework#4446]
How to reproduce:

```
sebastien@sebastien-xps:testplay$ activator --version
sbt launcher version 0.13.5
```

```
activator new testPlat
cd testPlay
```

Copy `test/ApplicationSpec` as `test/myPackage/MySpec`

Run `activator test`

The output is:

```
sebastien@sebastien-xps:testplay$ ll target/test-reports/
total 48
drwxrwxr-x 2 sebastien sebastien  4096 mai   13 10:42 ./
drwxrwxr-x 8 sebastien sebastien  4096 mai   13 10:40 ../
-rw-rw-r-- 1 sebastien sebastien  4700 mai   13 10:42 ApplicationSpec.xml
-rw-rw-r-- 1 sebastien sebastien  4589 mai   13 10:42 IntegrationSpec.xml
-rw-rw-r-- 1 sebastien sebastien  4703 mai   13 10:42 myPackage.MySpec.xml
-rw-rw-r-- 1 sebastien sebastien 14212 mai   13 10:42 MySpec.xml
```

As you can see, we can find both `MySpec.xml` and `myPackage.MySpec.xml`.
For specs without package I suspect the same behavior but probably as the qualified and not qualified names are the same it leads to an override of an already written file.

The one with the package name contains things like:

```
<testcase classname="myPackage.MySpec" name="(It is not a test)" time="-0.001"> 
                    </testcase><testcase classname="myPackage.MySpec" name="(It is not a test)" time="-0.001"> 
                    </testcase>
```

On an older version of Play (my real project actually) I got some weird behavior too, that is different for the `test` and `it:test` I setup. You can find more informations here:

https://github.com/sbt/sbt/issues/2007
http://stackoverflow.com/questions/30099944/specs2-sbt-play-how-to-output-example-names-in-junitxml-files

I think this is a bug that default Play settings lead to this strange behavior of duplicate xml report (with one of them being quite strange). For my it:test goal in my real project I could only generate a single file - and it's the wrong one - making it unsuitable for tracking failed integration tests in Jenkins

**Comment by cchantep** [comment]
Hi @slober. Please first copy this question to the [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework). If there is a confirmed issue, an actionable ticket can be then raised on this issue tracker. Best regards
