### ISSUE TITLE
[2.4.0-RC3] Bug: Global.onRequest(request, actionMethod) not called anymore

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#4462]
For a quick a test:
```java
public class Global extends GlobalSettings {

    @Override
    public Action onRequest(Request request, Method actionMethod) {
        System.out.println("Global.onRequest"); // Does not get called 
        return new Action.Simple() {
            public F.Promise<Result> call(Context ctx) throws Throwable {
                return delegate.call(ctx);
            }
        };
    }
}
```
It seems the `onRequest` never gets called (It does not matter if you use `InjectedRoutesGenerator` or not).

**Comment by richdougherty** [comment]
What's your configuration for `play.http.requestHandler`? I think the default setup for a Java application is meant to use [`GlobalSettingsHttpRequestHandler`](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/http/GlobalSettingsHttpRequestHandler.java) which calls `GlobalSettings.onRequest`. But I'm a bit confused by the logic in [`HttpRequestHandler`](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala#L42-L63) so I'm not sure whether there's a bug or not.

**Comment by jroper** [comment]
Problem is, it was attempting to cast `play.api.GlobalSettings` to `play.GlobalSettings`, which is never the case, rather if it's a Java `GlobalSettings`, then it will be `JavaGlobalSettingsAdapter`.

**Comment by jroper** [comment]
Pull request attached.

**Comment by jroper** [comment]
Backported to 2.4.x: 80d83fd
