### ISSUE TITLE
Document use of GuiceApplicationLoader in tests

### ISSUE THREAD

**Issue by jCalamari** [playframework/playframework#4466]
I am migrating play `2.3.8` app to `2.4.0-RC3`. I extended `GuiceApplicationLoader`, added following entry to `application.conf`:

`play.application.loader = classname`

Applications itself runs with no issues, however when running tests, guice dependencies are not injected:

```
import play.test.WithApplication;

import static play.test.Helpers.GET;
import static play.test.Helpers.fakeRequest;
import static play.test.Helpers.route;

public class Test extends WithApplication {

    @org.junit.Test
    public void test() {
        route(fakeRequest(GET, "/"));
    }
}

```
`fakeApplication` fails to start:

>[info] application - Creating Pool for datasource 'test'
[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] p.a.l.c.ActorSystemProvider - Shutdown application default Akka system: application
[info] application - Shutting down connection pool.

>com.google.inject.ProvisionException: Unable to provision, see the following errors:

>1) No implementation for models.services.agent.IAgentService was bound.
 while locating models.services.agent.IAgentService
    for field at controllers.AgentController.agentService(AgentController.java:13)
  while locating com.google.inject.Provider<controllers.AgentController>
    for parameter 9 at router.Routes.<init>(routes_routing.scala:108)
  while locating router.Routes
  while locating play.api.test.FakeRouterProvider
  while locating play.api.routing.Router

**Comment by benmccann** [comment]
I inject the Application and other components into my tests:

    @Before
    public void setup() {
      PlayApplicationLoader loader = new PlayApplicationLoader();
      ApplicationLoader.Context ctx = new ApplicationLoader.Context(Environment.simple());
      GuiceableModule[] guiceables = new GuiceableModule[] {
          Guiceable.module(new MyGuiceModule())
      };
      GuiceApplicationBuilder builder = loader.builder(ctx).overrides(guiceables);
      Guice.createInjector(builder.applicationModule()).injectMembers(this);
    }

It could be helpful to document this approach. And maybe to create a method that can be called to create an injector from an environment, config, and list of modules.

**Comment by jCalamari** [comment]
>It could be helpful to document this approach. And maybe to create a method that can be called to create an injector from an environment, config, and list of modules.

+1

**Comment by jCalamari** [comment]
@benmccann 
BTW,
>GuiceApplicationBuilder builder = loader.builder(ctx).overrides(guiceables);
`builder` method in RC3 is protected. Cannot be accessed like so.

**Comment by benmccann** [comment]
Thanks for pointing that out @jCalamari. I was using my own custom version where I'd overridden that class and made that method public. I sent a PR to add some docs and make that method public.

**Comment by jCalamari** [comment]
@benmccann `load` method is public bth.

**Comment by jCalamari** [comment]
Below piece makes tests seriously slow. Any advice?

```
@Before
public void setup() {
  GuiceApplicationBuilder builder = new PlayApplicationLoader()
      .builder(new Context(Environment.simple()))
      .overrides(new MyGuiceModule());
  builder.injector().injectMembers(this);
}

```

**Comment by benmccann** [comment]
This should be addressed now
