### ISSUE TITLE
The method Cookies.mergeCookieHeader doesn't merge cookies

### ISSUE THREAD

**Issue by akkie** [playframework/playframework#4467]
The method `Cookies.mergeCookieHeader` doesn't merge two cookies. Instead it returns only the last cookie.

```scala
println(FakeRequest().withCookies(Cookie("foo", "foo"), Cookie("bar", "bar"), Cookie("baz", "baz")).cookies)
```

prints
```
Map(baz -> Cookie(baz,baz,None,/,None,false,true))
```

**Comment by mkurz** [comment]
Which version version of Play are you using?

**Comment by akkie** [comment]
This method was newly added in [Play 2.4.0-RC3](https://github.com/playframework/playframework/commit/663dadb2e3c9908e20d208c424239ebde350c638#diff-c626071e49ea7a445f0e5c63226871d1R944).
