### ISSUE TITLE
Add documentation for debugging thread leaks

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#4469]
You need to be extra careful to cleanup threads in Play's dev mode compared to other application servers. It'd be good to document how to debug a thread leak since it's something that lots of people hit.

Instructions for taking a thread dump.

Run `ps -ef` to find the PID.

    $ ps -ef | grep sbt
    bmccann  21331  6322  0 12:11 pts/10   00:00:00 bash /usr/bin/sbt
    bmccann  21390 21331 34 12:11 pts/10   00:01:43 java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -jar /usr/share/sbt-launcher-packaging/bin/sbt-launch.jar
    bmccann  21669  9185  0 12:16 pts/7    00:00:00 grep --colour=auto sbt

Then run `jstack PID` (`jstack 21390` in the previous example).

The main thing to do is to look for objects/threads that increase in number for each run invocation or for each reload during a run. If you see 1 new thread per 1 reload then that gives a good hint about the thread leak.

Places where I've hit this include not closing a MongoDB or ElasticSearch client on shutdown.

**Comment by richdougherty** [comment]
Usually this is caused by a threads being started but not stopped during a `run` reload. The `Thread`s hold on to their `ClassLoader`s and the `ClassLoader`s hold onto their classes. In Java 7 you'd get a permgen error when you run out of space for classes. I think Metaspace is the Java 8 equivalent memory area for classes.

If you take thread dumps during `run` reloads or between invocations of `run`, do you see any threads hanging around?

**Comment by benmccann** [comment]
I think I remember some previous thread where there was discussion of how to thread dump and what to look for. I found [this one](https://github.com/playframework/playframework/issues/3799#issuecomment-70626353) talking about taking a heap dump, but that sounds maybe slightly different. Any tips on the thread dump?

We should probably document this :-) Even when Play is bug-free, end users cause this problem to themselves often enough.

**Comment by hepin1989** [comment]
ha,the classloader leak.

**Comment by richdougherty** [comment]
You can do the same thing for heap dumps, but thread dumps are easier to capture, and often work too. The main thing to do is to look for objects/threads that increase in number for each `run` invocation or for each reload during a `run`. If you see 1 new thread per 1 reload then that gives a good hint about the thread leak. In previous instances we've had Ehcache leaking a timer thread, Guice creating leaking a thread, etc.

**Comment by benmccann** [comment]
Instructions for taking a thread dump.

Run `ps -ef`to find the PID.

    $ ps -ef | grep sbt
    bmccann  21331  6322  0 12:11 pts/10   00:00:00 bash /usr/bin/sbt
    bmccann  21390 21331 34 12:11 pts/10   00:01:43 java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -jar /usr/share/sbt-launcher-packaging/bin/sbt-launch.jar
    bmccann  21669  9185  0 12:16 pts/7    00:00:00 grep --colour=auto sbt

Then run `jstack PID` (`jstack 21390` in the previous example).

**Comment by benmccann** [comment]
@richdougherty looks like our thread leaks are fixed in 2.4! the error was in my code

i've left the bug open to request some documentation for describing how to track down these errors. i've changed the description to include the content we should put in the docs. i think the main thing is just figuring out where the docs would best live

**Comment by marcospereira** [comment]
@benmccann I was thinking about a troubleshooting page some days ago, mostly things related to the sbt. Maybe it is a good place to put this kind of information.

**Comment by richdougherty** [comment]
In case you didn't see them, @jroper wrote some good sbt debugging docs here: https://www.playframework.com/documentation/2.4.x/SBTDebugging.

**Comment by jroper** [comment]
I think I started writing some debug docs on debugging memory leaks too, but I've got no idea where they are.

**Comment by nafg** [comment]
FWIW there's also jps to list pids of java apps

**Comment by anildes** [comment]
richdougherty  we still get a memory leakage and sometimes we get this 
Shown below is the logs from lxmkpd04.corp.equinix.com
com.mongodb.MongoSocketReadException: Prematurely reached end of stream
        at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:218) ~[mongodb-driver-core-3.0.4.jar:na]
        at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:205) ~[mongodb-driver-core-3.0.4.jar:na]
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[na:1.8.0_51]
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:430) ~[na:1.8.0_51]
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191) ~[na:1.8.0_51]

**Comment by anildes** [comment]
Shown below is the Thread stack
"cluster-ClusterId{value='5678cc2c6725a120e9763ebb', description='MarketplaceFiles'}-sv2lxmkpd01:27019" #97 daemon prio=5 os_prio=0 tid=0x00007fa1d4229000 nid=0x25b4 waiting on condition [0x00007fa1cfbfa000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000c386ae48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForSignalOrTimeout(DefaultServerMonitor.java:237)
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForNext(DefaultServerMonitor.java:218)
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:167)
        - locked <0x00000000c386ae60> (a com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable)
        at java.lang.Thread.run(Thread.java:745)

  Thread Dump
Locked ownable synchronizers:
        - None

"cluster-ClusterId{value='5678cc2c6725a120e9763ebb', description='MarketplaceFiles'}-sv2lxmkpd01:27018" #96 daemon prio=5 os_prio=0 tid=0x00007fa1d4227800 nid=0x25b3 waiting on condition [0x00007fa1cfcfb000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000c38a9b48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForSignalOrTimeout(DefaultServerMonitor.java:237)
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForNext(DefaultServerMonitor.java:218)
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:167)
        - locked <0x00000000c38a8558> (a com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable)
        at java.lang.Thread.run(Thread.java:745)

**Comment by wsargent** [comment]
Agreed that there needs to be a page (or a book) on thread leaks, but I don't think Play is it.

**Comment by marcospereira** [comment]
Maybe we can just have points to specific parts of [Java Platform, Standard Edition Troubleshooting Guide](http://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/index.html). [This article](https://www.toptal.com/java/hunting-memory-leaks-in-java) looks pretty good too.

**Comment by wsargent** [comment]
I'm fine with pointing to blog posts and authoritative sources.  I'm not really sure what a "Debugging Play" page would look like, though.  @marcospereira you want this?

**Comment by marcospereira** [comment]
@wsargent I was thinking about "evolve" the SBTDebugging page into a Troubleshooting page (or pages) instead, which would cover problems related to SBT and also with finding memory/thread leaks. Didn't had time to go for it though.
