### ISSUE TITLE
JsPath shouldn't use List[PathNode]

### ISSUE THREAD

**Issue by dlwh** [playframework/playframework#4470]
Or at least, shouldn't append to the end of the list as its main operation if it's going to use List...

https://github.com/playframework/playframework/blob/7dff09cf7a64017a289c928f3f441469d17cfd65/framework/src/play-json/src/main/scala/play/api/libs/json/JsPath.scala#L158

I always like scala.collection.immutable.Vector

While I'm at it, could I ask for a convenience method for taking prefixes/suffixes of a jspath?

**Comment by jroper** [comment]
Have you been able to measure the performance impact?  This will only be a problem for very deeply nested json structures, and even then, to my knowledge, paths are generally not manipulated during serialisation/deserialisation.

Given that changing the type here is a breaking change, unless the change actually yields some measurable improvement in real world use cases, then it's not worth it.

**Comment by dlwh** [comment]
It's a bottleneck in my application, which is precisely generating lots of
paths in a reasonably deep (and very broad) document. But we needed to roll
our own JsPath equivalent anyway, because we need efficient
prefix/suffixing, so whatever.

Note that the json being medium-depth and broad is also pretty bad for List
in terms of memory sharing.

**Comment by jroper** [comment]
Are you storing deserialisers/serialisers in defs or vals/lazy vals? Does using a val/lazy val instead of a def help?

**Comment by dlwh** [comment]
I'm literally just trying to reason over paths themselves for a machine
learning application. Doing my best to not use serializers at all.

**Comment by dlwh** [comment]
but like I said, JsPaths turned out to not be suitable for a couple of
other reasons, so if it's going to cause problems for you guys to change
it, don't worry about it.
