### ISSUE TITLE
Old documentation published for 2.4.x 

### ISSUE THREAD

**Issue by dotta** [playframework/playframework#4473]
Looks like our nightly is publishing the old documentation for Play 2.4.x

E.g., 

https://www.playframework.com/documentation/2.4.x/ScalaI18N vs https://www.playframework.com/documentation/2.4.0-RC3/ScalaI18N

or 

https://www.playframework.com/documentation/2.4.x/ScalaSlick while it should be https://www.playframework.com/documentation/2.4.x/PlaySlick (in fact, the RC3 doc can be found under  https://www.playframework.com/documentation/2.4.0-RC3/PlaySlick)

**Comment by jroper** [comment]
I haven't fixed the nightly deploy yet, but actually the original problem was that when I branched 2.4.x, I branched it on a very old master. So I just fast forwarded it, and it works now:

https://www.playframework.com/documentation/2.4.x/PlaySlick

But nightly deploy isn't fixed yet.
