### ISSUE TITLE
2.4.0-RC3: Scala FakeRequest does not work with Multipart.parsers

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#4474]
Documented on this thread on the google group: https://groups.google.com/forum/#!topic/play-framework-dev/iGVW2vdSmfE

It seems that FakeRequest does not work (correctly) anymore with Multipart-Parsers. 

I've created a sample project here: https://github.com/domdorn/play-2.4.0-RC3-bug-4474

p.s.: I know that I'm using "FakeRequest(POST, "/collector_working").withFormUrlEncodedBody" instead of "FakeRequest(POST, "/collector_working").withMultipartFormDataBody" in the test. 
This used to work in 2.3 and the withMultipartFormDataBody has an inconvenient API.

**Comment by jroper** [comment]
So `withMultipartFormDataBody` works?  I would say that it was a bug that posting a `application/x-www-form-urlencoded` body to an action that expects `multipart/form-data` worked.  If the API for `withMultipartFormDataBody` is inconvenient, then that should be addressed, we shouldn't make a method with says it does one thing actually do another.

**Comment by cchantep** [comment]
Closing it for now. If a related issue is confirmed against master, an up-to-date can be raised. The possible API changes should be first discussed on the MailingList. Best regards.
