### ISSUE TITLE
Return value in JSON package-level docs is wrong

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#4485]
The [package-level docs](https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.libs.json.package) shows the `reads` method returning `User` instead of `JsResult[User]`, and of course the method needs to wrap the returned value in `JsSuccess`.

**Comment by gmethvin** [comment]
Yeah, that is using the old API before `JsResult` was introduced. The `reads` method ideally should validate the input rather than just wrapping in `JsSuccess`.
