### ISSUE TITLE
[2.4] EhCacheApi.get[T](key: String) always returns None for 'primitive' T

### ISSUE THREAD

**Issue by njrich28** [playframework/playframework#4488]
I've found an issue with `EhCacheApi.get[T](key: String)` implementation where it will always return `None` when called with a 'primitive' type parameter (ie. one of Byte, Short, Char, Int, Long, Float, Double, Boolean) even if the cache contains an entry of the correct type.

The following example action demonstrates the case:

```scala
class Application @Inject() (cacheApi: CacheApi) extends Controller {
  def index = Action {
    cacheApi.set("foo", "string")
    val resString = cacheApi.get[String]("foo") // returns Some(string)

    val i: Int = 31
    cacheApi.set("bar", i)
    val resInt = cacheApi.get[Int]("bar") // returns None
    Ok(views.html.index())
  }
}
```
The unit tests only cover the case of setting and getting a String and so pass OK. Adding tests for primitive types will cause it to fail.

I've got a fix I can submit, along with test cases.

**Comment by marcospereira** [comment]
@njrich28 please submit the fix and we will do our best to merge it. :-)

**Comment by francisdb** [comment]
Just pitching in to get this merged. Major issue if you ask me.
