### ISSUE TITLE
JsReadable not shown in ScalaDoc

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#4489]
Neither the ScalaDoc for 2.4.x nor 2.4.0-RC3 shows `JsValue` subclassing `JsReadable` (in fact they fail to show `JsReadable` at all), but the source code for both does.

    sealed trait JsValue extends JsReadable

**Comment by jroper** [comment]
The 2.4.0-RC3 docs do show this:

![jsvalue_-_play_api_libs_json_jsvalue](https://cloud.githubusercontent.com/assets/105833/7693602/5912cc30-fe17-11e4-875e-83de1965ebe5.png)

https://www.playframework.com/documentation/2.4.0-RC3/api/scala/index.html#play.api.libs.json.JsValue

The 2.4.x docs are a bit broken, we're working on fixing the nightly docs deployment in #4473.
