### ISSUE TITLE
2.4.0-RC4 and RC5 has unresolvable dependency

### ISSUE THREAD

**Issue by ejisan** [playframework/playframework#4497]
SBT shows a warning "com.typesafe.play#play-omnidoc_2.11;2.4.0-RC5: not found" with sbt-plugin 2.4.0-RC4 and RC5.

https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-omnidoc_2.11/

**Comment by cchantep** [comment]
Hi @ejisan , wherr do you see this dependency?

**Comment by jroper** [comment]
I'm still in the process of releasing 2.4.0-RC5, that's why it's not there - please don't report issues against a version of Play that we haven't even announced the release of yet.

**Comment by mkurz** [comment]
@ejisan You can add 
```
PlayKeys.playOmnidoc := false
```
to your `build.sbt` as a workaround until omnidoc is released.
