### ISSUE TITLE
[doc] [2.4.0] Controller defined as singleton object in ScalaActions.md

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#4508]
https://playframework.com/documentation/2.4.x/ScalaActions

```
A Controller is nothing more than a singleton object that generates Action values.
```

A controller isn't a Scala singleton object any more in 2.4.x -- it's a class that's injected.

**Comment by marcospereira** [comment]
Both are supported. I think that using a object is the default.

**Comment by marcospereira** [comment]
Ok, the code snippet is inconsistent and we don't have documentation for both object and classes with dependency injection.

**Comment by jroper** [comment]
I don't think we necessarily need to document objects - the recommended approach, and the only possible way in a future version of Play, is to use classes.  Newly created projects use classes, not objects, and the documentation is most important for new users on new projects, adding documentation for objects introduces noise, and the value from the noise is questionable.

**Comment by damirv** [comment]
@jroper but the injected controller instances are by default singletons, right?

**Comment by jroper** [comment]
Not really - if using Guice, each time the controller is injected into something, a new instance will be created by default. That said, the router is a singleton, and so by association, the controllers it invokes are singleton.  But if you inject a controller somewhere else, it will be instantiated newly for that component.

**Comment by marcospereira** [comment]
See PR #5700.
