### ISSUE TITLE
[2.4.0-RC5] conf/logback.xml occures twice in distribution classpath

### ISSUE THREAD

**Issue by maxcom** [playframework/playframework#4512]
I created custom conf/logback.xml and made distribution via "sbt stage" task.

When I run production application, I see noisy warning from logback on application start:

```
|-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
|-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
|-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/opt/prodadd/prodapp-play-server/conf/logback.xml]
|-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
|-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/opt/prodapp/prodapp-play-server/conf/logback.xml]
|-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/prodapp/prodapp-play-server/lib/prodapp-server.prodapp-server-1.0-c3d43b864ed2d3fd0c4206e3394335206290b319.jar!/logback.xml]

```

I think that it is caused by appearance of logback.xml in both conf/logback.xml and in main application jar file. This files contains the same content.

**Comment by jroper** [comment]
That's annoying.  You can work around this by the way by setting `PlayKeys.externalizeResources := false` in your build.

We could fix this by, if `externalizeResources` is true, ensuring it doesn't make it in the final package.  But that will cause a problem for sub projects that have resources in the `conf` directory.  Maybe we could make `logback.xml` a special case.  Or, if we make `externalizeResources` false by default.

**Comment by david-bouyssie** [comment]
Hi guys I have a similar issue with play.plugin under Play 2.3.
I have understood my problem after having look to this issue: 
https://github.com/playframework/playframework/issues/1079

Here jroper said:
_Also, there is an issue with copying the conf directory to the dist directory - if you put a play.plugins file into the conf directory, you'll get it twice on the classpath, which means any plugins in it may end up being loaded twice._

So what do you suggest to exclude play.plugins from being packaged when using Play 2.3 ?
