### ISSUE TITLE
Missing implicit Char binding for PathBindable, QueryStringBindable breaks routes.

### ISSUE THREAD

**Issue by godenji** [playframework/playframework#4523]
This causes of couple of problems, notably that the user is forced to define their own bindable for what should be a play built-in, and worse, makes it impossible to define custom char based value classes as the underlying primitive type `Char` has no implicit binder in scope.

Hopefully this can go into 2.4, and be backported to 2.3.x

Fix is simple enough, `Binders.scala`:

    implicit object bindableChar extends Parsing[Char](
      _.charAt(0), _.toString, (key: String, e: Exception) =>
      "Cannot parse parameter %s as Char: %s".format(key, e.getMessage)
    )

**Comment by julienrf** [comment]
Hi, I would be happy to merge a pull request for that.

**Comment by godenji** [comment]
@julienrf done, issued pull request.

**Comment by marcospereira** [comment]
Fixed by #4528.
