### ISSUE TITLE
Fails: Reads.instantReads(DateTimeFormatter.ISO_INSTANT)

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#4529]
I think I have this right, but it fails:

    scala> import java.time.format.DateTimeFormatter
    import java.time.format.DateTimeFormatter

    scala> Json.fromJson(JsString("2011-12-03T10:15:30"))(Reads.instantReads(DateTimeFormatter.ISO_INSTANT))
    res0: play.api.libs.json.JsResult[java.time.Instant] = JsError(List((,List(ValidationError(List(error.expected.date.isoformat),WrappedArray(ParseCaseSensitive(false)Instant()))))))

This one works:

````
scala> Json.fromJson(JsString("2015-12-13 at 12:34:56"))(Reads.instantReads("yyyy-MM-dd 'at' HH:mm:ss"))
res1: play.api.libs.json.JsResult[java.time.Instant] = JsSuccess(2015-12-13T12:34:56Z,)
````

**Comment by cchantep** [comment]
Hi @mslinn , thanks for reporting. Please first ask on the [MailingList]( https://groups.google.com/forum/m/#!forum/play-framework). This ticket could be reopened if there is a confirmed issue. Best regards.
