### ISSUE TITLE
Invalid warning when a database needs an evolution: wrong key

### ISSUE THREAD

**Issue by studiodev** [playframework/playframework#4533]
Hello,

I think there is an error in the warning displayed when the database needs an evolution.

The configuration key mentioned is `play.modules.evolutions.db.$db.autoApply` ([ApplicationEvolutions.scala](https://github.com/playframework/playframework/blob/ed330deada1545d54a2a012f3bf088b8086efc31/framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala#L66-72)), but the right is `play.evolutions.db.$db.autoApply` (same for `autoApplyDowns`).

The `application.conf` templates are also wrong.

I can do a PR if you want.

**Comment by dotta** [comment]
Thanks @studiodev!
