### ISSUE TITLE
[doc] [3.0] docs for 3.0 selectable on playframework.com but are not working

### ISSUE THREAD

**Issue by coniurare** [playframework/playframework#4535]
Hi,

it's not important since 3.0 is a long way off before it gets released and even 2.4 final is not out yet, but I want to point out that it is possible to select the documentation for version 3.0 on playframework.com which results in the following error:

> We're sorry, your request could not be completed as dialed. Please check the URL and try your request again.

Is this related to the not yet fixed nightly deploy @jroper mentioned here: https://github.com/playframework/playframework/issues/4473#issuecomment-103324821 or is this something else?

cheers

**Comment by jroper** [comment]
Yeah I know, I just haven't got around to fixing it. Anyway, it's fixed now:
https://github.com/playframework/playframework.com/commit/933d0f5075fa5347442f6fa7767fac3452eaa9d1
