### ISSUE TITLE
[2.4.0] sbt generators not called when using sbt run and refreshing the page

### ISSUE THREAD

**Issue by vmunier** [playframework/playframework#4541]
Hi,

The behaviour of `sbt run` has changed in 2.4.0-RC1 compared to previous versions, including 2.3.x and even Play 2.4.0-M3.

So in Play versions prior to 2.4.0-RC1, sbt generators (sourceGenerators, resourceGenerators) used to be called when using `sbt run` and when the browser page was refreshed.
Simple example to put in any sbt config that prints something with 2.4.0-M3 but not with 2.4.0-RCx:
`sourceGenerators in Assets <+= Def.task { println("Triggered on browser refresh!"); Seq[File]() }`

Is that change intentional or should it be reverted?

Regards,
Vincent

**Comment by jroper** [comment]
It definitely wasn't called every time a page is refreshed (it if it was, that indicates that you had a problem in your build that was causing recompiles on every page refresh), but only if there are source changes.  If they were called on every page refresh, this would potentially cause big problems.

Anyway, I just checked, source generators are being invoked when you change a source file, and then refresh the page, as expected.
