### ISSUE TITLE
Dev-reload causes morphia MappingExceptions in WebSocket-related code.

### ISSUE THREAD

**Issue by daut-morina** [playframework/playframework#4557]
I am using atmosphere via atmosphere play plugin to extend the provided WebSocket functionality. It happens that after play does a dev-reload morphia isn't able to map some classes. I thought that it must be some problem with atmosphere I would have to figure out but after I've seen the problem this guy is having (http://stackoverflow.com/questions/29179396/play-morphia-mappingexception-in-websocket-iteratee-after-reload) I thought it might have to do with the way play reloads the app.

Morphia is not able to map the classes because they're not registered in the class loader after a dev-reload. Any ideas?

**Comment by cchantep** [comment]
Hi @daut-morina, you will get more help for such question on the user [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework) rather than in this issue tracker. If the discussion on the mailing list confirms there is an issue, then it can filed there. Best regards.
