### ISSUE TITLE
Templates doesn't reload when using the default SBT layout

### ISSUE THREAD

**Issue by dengalepirat** [playframework/playframework#4558]
I'm having a rather funny problem when using the default SBT layout and compiling twirl templates in a new Play 2.4.0 project.  

If I run activator with the ~run then templates are compiled and everything works fine on startup, but if I make a change to one of the templates, then activator pickups up this change and compiles the template, but it doesn't reload the application, so it is impossible to see the change in the browser. When using the run command nothing happens, when a make a change to one of the templates.

I have converted the project back to the default Play layout, to test if something was wrong with my machine, but then everything works perfectly. So machine wasn't the problem as far as I can tell.

I know the default SBT layout is experimental, so I'm just letting you know that there is an issue.

**Comment by cchantep** [comment]
Hi @dengalepirat, you will get more help for such question on the user [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework) rather than in this issue tracker. If the discussion on the mailing list confirm there is an issue, then it can filed there. Best regards.

**Comment by jroper** [comment]
Add

```
PlayKeys.playMonitoredFiles ++= (sourceDirectories in (Compile, TwirlKeys.compileTemplates)).value
```

to your build.  Play's file modification detection is based on directories, and so can't use SBTs watched files config, which Twirl configures.

**Comment by dengalepirat** [comment]
@cchantep I'll remember that next time.

@jroper Thanks, will try that out
