### ISSUE TITLE
Json.obj results in invalid JSON

### ISSUE THREAD

**Issue by phillro** [playframework/playframework#4566]
Json.obj("test" -> "hello")

Omits the quote on the field name, resulting in: {test:"hello"}

Per the RFC (http://tools.ietf.org/html/rfc4627) fields names are strings and hence should be in quotes.

**Comment by jroper** [comment]
Firstly, `Json.obj` doesn't produce json, it produces an abstract representation of json in Scala objects, it's not until you convert it to json that there can be any problem here, eg, using `Json.stringify`.  So, how did you convert it to json, and what makes you think the quotes are omitted?

```
scala> Json.stringify(Json.obj("test" -> "hello"))
res1: String = {"test":"hello"}
```

Looks like they're there to me.  I don't think it's possible for such a fundamental bug to go unnoticed in Play, so this sounds like the error is on your end to me.
