### ISSUE TITLE
Document how to extend Play with custom plugins and Guice [2.4] 

### ISSUE THREAD

**Issue by jCalamari** [playframework/playframework#4572]
I would like to write a custom Play java plugin however play.Plugin is deprecated.

https://playframework.com/documentation/2.4.x/JavaPlugins

**Comment by marcospereira** [comment]
This is already documented:

https://playframework.com/documentation/2.4.x/Modules

The page above has links for both scala and java docs.

**Comment by gmethvin** [comment]
There is documentation here for how to create Play modules: https://www.playframework.com/documentation/2.4.x/JavaDependencyInjection#Play-libraries

@dotta is still working on the docs for migrating plugins to modules (#4543), which has some useful details/examples. It does seem like we need some more docs on how to write play libraries/modules from scratch.

**Comment by jCalamari** [comment]
>It does seem like we need some more docs on how to write play libraries/modules from scratch.

@marcospereira  And this is the issue. There is no info on play libraries/modules in link you posted.
