### ISSUE TITLE
Play 2.3.8 bindFromRequest different behavior on hasErrors

### ISSUE THREAD

**Issue by umbreak** [playframework/playframework#4573]
I have a model with a list of enum `List<Role> role` and other stuff.

When the form is submitted, I make a bindFromRequest. If the Form has errors (`.hasErrors()`), it turns out that the role field.value is null. If it doesn't it contains all the elements in the list ([ENUM1,ENUM2,...]):

However, `userForm.field("role").indexes()` returns always the number of indexes correctly (in my case 2). So doing `userForm.field("role[0]").value()` will show a valuer (ENUM1 in my case).

But why the value of the list element (role) is null when the form has errors and it contains the list of values when it doesn't?

**Comment by marcospereira** [comment]
Hello @umbreak,

Could you please discuss this at the mail list first?  If we confirm there is an bug, then we open an issue here. 

Thanks.
