### ISSUE TITLE
[2.4.0] Subproject assets not found

### ISSUE THREAD

**Issue by dwickern** [playframework/playframework#4576]
After upgrading from 2.3 to 2.4, I get a 404 when loading subproject assets. The subproject assets are being generated, but the main project's router doesn't find them.

Maybe related, the example from the [subprojects documentation](https://www.playframework.com/documentation/2.4.x/SBTSubProjects) doesn't compile:
```
package controllers.admin
object Assets extends controllers.AssetsBuilder
```

So I changed the subproject's controller to this (which wasn't part of the migration guide)
```
package controllers.admin
object Assets extends controllers.AssetsBuilder(play.api.http.LazyHttpErrorHandler)
```

Possibly related:
https://groups.google.com/forum/#!msg/play-framework/PeiEesLFUWs/w7nCX-VB_PYJ

**Comment by mkurz** [comment]
Probably also related:
https://groups.google.com/forum/#!topic/play-framework/z3OKPdfyocM

**Comment by dwickern** [comment]
After reading the source, it looks like you can restore the old behavior by setting `importDirectly := true`

**Comment by marcospereira** [comment]
Closing. See discussion and PR #4788.
