### ISSUE TITLE
DefaultApplication example in Application's ScalaDoc is wrong

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#4577]
Given the [new parameters of DefaultApplication](https://github.com/playframework/playframework/blob/2.4.0/framework/src/play/src/main/scala/play/api/Application.scala#L240-L247), the [example in Application's Scaladoc](https://github.com/playframework/playframework/blob/2.4.0/framework/src/play/src/main/scala/play/api/Application.scala#L33-L35) is wrong.

**Comment by marcospereira** [comment]
This is also related to #4593.
