### ISSUE TITLE
Improvement - Java Templates

### ISSUE THREAD

**Issue by AzureusNation** [playframework/playframework#4583]
Will there ever be the option of using Java in the HTML templates instead of just scala. As there is the choice of whether to use Java or Scala for the Models and Controller surely it would be nice to also have that option with the HTML templates.

I'll be honest I have no idea on how the framework works or whether it is even possible.

**Comment by cchantep** [comment]
Hi, please ask such question on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework), to get more help (rather than on this issue tracker). Best regards

**Comment by jroper** [comment]
The templates are just functions, the following template:

```scala
@(name: String)

Hello @name
```

Essentially just compiles to a method that looks like this:

```java
public String myTemplate(String name) {
  return "Hello " + name;
}
```

Of course, it's more complex than that, but the point is, you can use whatever templating mechanism you want, including freemarker, velocity, or some of the groovy based template languages - if you can invoke it like a function, you can use it in Play.
