### ISSUE TITLE
ZonedDateTimeNumberWrites has multiple errors in the code example.

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#4584]
[ZonedDateTimeNumberWrites](https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.libs.json.Writes$@ZonedDateTimeNumberWrites:play.api.libs.json.Writes[java.time.ZonedDateTime]) has a bad import in the code example.

    import play.api.libs.json.Java8Writes

Also, the next line in the example has 3 errors:

    implicit val Writes = ZonedDateTimeNumberWrites[ZonedDateTime]

(Name of variable, missing classname and type parameter supplied). Here is a corrected line:

    implicit val zdtnWrites = Writes.ZonedDateTimeNumberWrites

Finally, why is this `val` not defined as `implicit`?

**Comment by marcospereira** [comment]
Closing. Please see PR #4911.
