### ISSUE TITLE
[doc] Better routing documentation

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#4585]
If you look at the documentation for the routes documentation, it has a number of issues: 

https://playframework.com/documentation/2.4.x/ScalaRouting

It does not have a link to the SIRD router.  It does not cover QueryStringBindable or PathBindable.  And It does not cover query parameters very well.  

For example, it doesn't cover lists:

```
# /lists?params=test1&params=test2&params=test3
GET     /lists                      controllers.Application.lists(params:Seq[String])
```

Nor does it cover the limitations:

```
# Doesn't compile!
GET     /quoted                      controllers.Application.quoted(`quoted-string`:String)
```

Also, it looks like the JavaRouting documentation is almost identical:

https://www.playframework.com/documentation/2.4.x/JavaRouting

**Comment by benmccann** [comment]
We should also document how to use the Java routing DSL. There's some usage shown in the [embedded server documentation page] (https://www.playframework.com/documentation/2.4.x/JavaEmbeddingPlay), but we need some documentation that describes the routing DSL independently and covers topics like registering it with the application, limitations, etc.

**Comment by benmccann** [comment]
We should also fix https://github.com/playframework/playframework/issues/2167
