### ISSUE TITLE
[doc] SIRD router does not show embedding usage

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#4586]
The SIRD router documentation page shows how to create a SIRD router, but not how people would bind a SIRD router into the application -- whether it's bind[Router] or overriding DefaultHttpRequestHandler, it'd be good to have more examples of usage in context.

https://playframework.com/documentation/2.4.x/ScalaSirdRouter

**Comment by nlhkh** [comment]
+1

**Comment by wsargent** [comment]
To use SIRD in conjunction with conf/routes:

```
package routers

import play.api.mvc._
import play.api.routing._
import play.api.routing.sird._

class MyRouter extends SimpleRouter {
  def routes = {
    ...
  }
}
```

Add this in conf/routes: 

```
->      /api                        routers.MyRouter
```

**Comment by abelbryo** [comment]
How do you make a call to the controller class `UserController` using dependency injection as in Play 2.4.x ? 
This code would have worked if `UserController` is an object. I have no idea how I can do that when it is a class and the documentation is no help.
```
package routers

import play.api.mvc._
import play.api.routing._
import play.api.routing.sird._

class MyRouter extends SimpleRouter {
  def routes = {
    val router = Router.from {
        case GET(p"/hello/$to") => Action { Results.Ok(s"Hello $to")}
        case POST(p"/create") => controllers.UserController.create
    }
   router.routes
  }
}
```

**Comment by wsargent** [comment]
@abelbryo This isn't part of the issue -- please ask on the mailing list or on https://gitter.im/playframework/playframework for help.

**Comment by wsargent** [comment]
@abelbryo you want 

```
class MyRouter @Inject() (controller:UserController) extends SImpleRouter {
 def routes = {
    val router = Router.from {
        case GET(p"/hello/$to") => Action { Results.Ok(s"Hello $to")}
        case POST(p"/create") => userController.create
    }
   router.routes
  }
}
```

**Comment by uryyyyyyy** [comment]
I tried implementing MyRouter  (refer to @abelbryo post, extends SimpleRouter), 
but it seem not working.(i.e. no route changed)

Are there any other necessary settings to use "sird"?

**Comment by benmccann** [comment]
While we're improving the SIRD documentation let's also add a note about why it's not available from Java. I think there's a legitimate reason, which we should mention to let Java users know they're not being treated as second-class citizens. If there's not a reason then we should file an issue tracker to bring the Java API to parity

**Comment by cchantep** [comment]
Should be ok now

**Comment by wsargent** [comment]
No, this still doesn't cover the /conf/routes to SIRD router case described in https://github.com/playframework/playframework/issues/4586#issuecomment-107765687
