### ISSUE TITLE
Abstract traits are required for compile time DI

### ISSUE THREAD

**Issue by gakuzzzz** [playframework/playframework#4591]
I welcome that Play2 modules are loosely coupled
And I like compile time DI.

I provide some libraries what use Cache API and Crypt API internally.
I want to be the library users could choose runtime DI or compile time DI and change Cache API implementation.

So my library depends following abstract trait.

```scala
trait CacheApiComponents {
  type CacheApiImpl <: CacheApi 
  def cacheApi: CacheApiImpl 
} 
```

and `EhCacheComponents` mix in the abstract trait.

```scala
trait EhCacheComponents extends CacheApiComponents {
  type CacheApiImpl = EhCacheApi
  ...
```

Others API (ex Crypt, DBPlugin,..) should be same.

**Comment by cchantep** [comment]
Hi @gakuzzzz, please first ask such question on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to get more help. Then if an issue is confirmed, it can be raised there. Best regards.

**Comment by jroper** [comment]
From https://www.playframework.com/documentation/2.4.x/ScalaCompileTimeDependencyInjection:

> In addition to providing public constructors and factory methods, all of Play’s out of the box modules provide some traits that implement a lightweight form of the cake pattern, for convenience. These are built on top of the public constructors, and are completely optional. In some applications, they will not be appropriate to use, but in many applications, they will be a very convenient mechanism to wiring the components provided by Play.

The components traits are intentionally very simple, they implement a very lightweight form of the cake pattern.  They are not meant to be a complete solution, just a convenient helper.  When they aren't appropriate, it's very straight forward to not use them.  If they don't work for you, simply don't use them.
