### ISSUE TITLE
[2.4] Getting dependency instance from Injector by BindingKey<T> in PlayJava.

### ISSUE THREAD

**Issue by jCalamari** [playframework/playframework#4592]
This is how I inject dependencies programmatically: 

```
Play.application().injector().instanceOf((new BindingKey<>(SomeService.class, Option.apply(new QualifierClass<>(SomeAnnotation.class))));
```
As you can see, it is a long chain of calls. Moreover, I am forced to use scala api (BindingKey, Option) to get the desired instance. Is there a better and syntax-short way (java way) to get java dependency? Would you consider implementing something similar to [Google Guice Key API](http://google.github.io/guice/api-docs/latest/javadoc/index.html?com/google/inject/Key.html) - especially static get methods?

Edit: I have just found play.inject.Bindings class however it contains only one method, no annotation allowed:
```
package play.inject;

import play.api.inject.BindingKey;

public class Bindings {

    /**
     * Create a binding key for the given class.
     */
    public static final <T> BindingKey<T> bind(Class<T> clazz) {
        return new BindingKey(clazz);
    }

}
```
Brief implementation:
```
public static <T> BindingKey<T> bind(Class<T> clazz, Class<? extends Annotation> annotation) {
        return bind(clazz).qualifiedWith(annotation);
}
```

**Comment by richdougherty** [comment]
Are you using this API in a Play plugin or in a Play application?
* If this is a Play application then we recommend that you use the underlying DI framework API, e.g. use Guice directly. You can do that by injecting the Guice injector as a dependency.
* If this is a Play plugin, then the usual way is to write a Scala core and use Java wrappers. That means you can have both a Scala and Java API for your plugin.

**Comment by jCalamari** [comment]
In Play application, obviously. 
>If this is a Play application then we recommend that you use the underlying DI framework API, e.g. use Guice directly. You can do that by injecting the Guice injector as a dependency.

There are certain situations where I cannot inject guice dependency i.e. Java actions and forms:

```
public class SimpleAction extends Action.Simple {

    @Override
    public F.Promise<Result> call(play.mvc.Http.Context ctx) throws Throwable {
        SomeService service = Play.application().injector().instanceOf((new BindingKey<>(SomeService.class, Option.apply(new QualifierClass<>(SomeAnnotation.class))));
        // ...
    }

}

public class SimpleForm {
    public String validate() {
        ValidateService userSvc = Play.application().injector().instanceOf((new BindingKey<>(ValidationService.class, Option.apply(new QualifierClass<>(CSRF.class))));
    }
}
```

**Comment by jroper** [comment]
I think:

```java
bind(SomeService.class).qualifiedWith(SomeAnnotation.class)
```

is simple enough.  Overloading factory methods when a perfectly suitable builder API exists is not a good idea - builders are far superior to overloaded methods.

**Comment by jCalamari** [comment]
>Overloading factory methods when a perfectly suitable builder API exists is not a good idea - builders are far superior to overloaded methods.

Well said.

```
bind(SomeService.class).qualifiedWith(SomeAnnotation.class)
```
Is it safe to mix java with scala API in Play Java project?

**Comment by jroper** [comment]
Yes, this particular API is designed for use from both Java and Scala.

**Comment by jCalamari** [comment]
>Yes, this particular API is designed for use from both Java and Scala.

Great. I guess this issue can be closed as it does not bring anything to the project.
