### ISSUE TITLE
[2.4 Java JPA] Strange behavior  with eclipselink in dist/stage mode

### ISSUE THREAD

**Issue by scattbrain** [playframework/playframework#4594]
In a 2.4 project with injected routes and eclipselink as JPA provider I've found this strange behavior:
If i start the project in dist mode via bin script passing the config.resource as a parameter, e.g.
`testapp -Dconfig.resource=application.conf` the persistence provider was unable to find the entities 

otherwise if I start the project without the `config.resource` all works as expected.

Following the eclipselink log:
*with config-resource*
`
[EL Info]: server: 2015-06-01 22:23:45.799--ServerSession(419792179)--Detected server platform: org.eclipse.persistence.platform.server.NoServerPlatform.
[EL Finest]: jpa: 2015-06-01 22:23:45.806--ServerSession(419792179)--Thread(Thread[main,5,main])--Begin predeploying Persistence Unit defaultPersistenceUnit; session /file:/home/giorgio/workspaces/git/velaTecmark/mainWebApp/target/universal/stage/conf/_defaultPersistenceUnit; state Initial; factoryCount 0
[EL Finest]: properties: 2015-06-01 22:23:45.81--ServerSession(419792179)--Thread(Thread[main,5,main])--property=eclipselink.orm.throw.exceptions; default value=true
[EL Finest]: properties: 2015-06-01 22:23:45.811--ServerSession(419792179)--Thread(Thread[main,5,main])--property=eclipselink.multitenant.tenants-share-emf; default value=true
[EL Finest]: properties: 2015-06-01 22:23:45.811--ServerSession(419792179)--Thread(Thread[main,5,main])--property=eclipselink.multitenant.tenants-share-cache; default value=false
[EL Finer]: metadata: 2015-06-01 22:23:45.83--Thread(Thread[main,5,main])--Searching for mapping file: [META-INF/orm.xml] at root URL: [file:/home/giorgio/workspaces/git/velaTest/mainWebApp/target/universal/stage/conf/].
[EL Finer]: metadata: 2015-06-01 22:23:45.832--Thread(Thread[main,5,main])--Searching for mapping file: [META-INF/eclipselink-orm.xml] at root URL: [file:/home/giorgio/workspaces/git/velaTest/mainWebApp/target/universal/stage/conf/].
[EL Finest]: jpa: 2015-06-01 22:23:45.845--ServerSession(419792179)--Thread(Thread[main,5,main])--End predeploying Persistence Unit defaultPersistenceUnit; session /file:/home/giorgio/workspaces/git/velaTest/mainWebApp/target/universal/stage/conf/_defaultPersistenceUnit; state Predeployed; factoryCount 0
[EL Finer]: weaver: 2015-06-01 22:23:45.845--Thread(Thread[main,5,main])--JavaSECMPInitializer - transformer is null.
[EL Finest]: jpa: 2015-06-01 22:23:45.845--ServerSession(419792179)--Thread(Thread[main,5,main])--Begin predeploying Persistence Unit defaultPersistenceUnit; session /file:/home/giorgio/workspaces/git/velaTest/mainWebApp/target/universal/stage/conf/_defaultPersistenceUnit; state Predeployed; factoryCount 0
[EL Finest]: jpa: 2015-06-01 22:23:45.846--ServerSession(419792179)--Thread(Thread[main,5,main])--End predeploying Persistence Unit defaultPersistenceUnit; session /file:/home/giorgio/workspaces/git/velaTest/mainWebApp/target/universal/stage/conf/_defaultPersistenceUnit; state Predeployed; factoryCount 1
[EL Finer]: metamodel: 2015-06-01 22:23:45.852--ServerSession(419792179)--Thread(Thread[main,5,main])--`**The collection of metamodel types is empty.**` Model classes may not have been found during entity search for Java SE and some Java EE container managed persistence units.  Please verify that your entity classes are referenced in persistence.xml using either <class> elements or a global <exclude-unlisted-classes>false</exclude-unlisted-classes> element
`  
and the same *without config-resource*
`
[EL Info]: server: 2015-06-01 22:07:29.177--ServerSession(1109461985)--Detected server platform: org.eclipse.persistence.platform.server.NoServerPlatform.
`

**Comment by richdougherty** [comment]
Hmm, might be a ClassLoader related issue. See also #4590.

**Comment by jroper** [comment]
Could you check whether this still happens if you add:

```scala
PlayKeys.externalizeResources := false
```

to your `build.sbt`?  If so, this is likely caused by the same problem as #4512 and fixed by #4522.

**Comment by scattbrain** [comment]
Just tried, adding
`
PlayKeys.externalizeResources := false
`
to `build.sbt` as suggested by @jroper  the problem has gone,
many thanks for the support

**Comment by marcospereira** [comment]
We should add some information about this in our docs:

https://github.com/playframework/playframework/blob/master/documentation/manual/working/javaGuide/main/sql/JavaJPA.md

I've opened issue #4611.
