### ISSUE TITLE
Project not loaded properly: java.lang.NoClassDefFoundError: play/Play$

### ISSUE THREAD

**Issue by schwannden** [playframework/playframework#4595]
I downloaded activator, use activator ui to setup and download this project, and the following happened

[Loading] Scanning directory /home/schwannden/Downloads/play-scala-intro
[Loading] Found root project root w/ remaining 
play/Play$
java.lang.NoClassDefFoundError: play/Play$
Use 'last' for the full log.
> load-failed
Failed to load project.
> server-wait-for-reboot

**Comment by mkurz** [comment]
There is a discussion in the mailing list too:
https://groups.google.com/forum/?fromgroups#!topic/play-framework/_devPRu0rLg

**Comment by jamesward** [comment]
Same here.

**Comment by jamesward** [comment]
Duplicate of: https://github.com/playframework/playframework/issues/4563

**Comment by cchantep** [comment]
Thanks @jamesward . Fix to be attached to #4595 .

**Comment by schwannden** [comment]
Thanks all!
