### ISSUE TITLE
[2.4.0] play.api.libs.json.Json.{writes & reads} not work well with Slick row definition case class

### ISSUE THREAD

**Issue by DieterLi** [playframework/playframework#4598]
In previous versions of Playframework, I directly use writes/reads functions to create implicit json converters with Slick row definition case classes, which were good. 

But in 2.4.0, I got the error as following:
```
import models.Tables.UserRow
...
[error]  found   : play.api.libs.json.OWrites[Tables.this.UserRow]
[error]  required: play.api.libs.json.Writes[models.Tables.UserRow]
[error]  Note: implicit value userWrites is not applicable here because it comes after the application point and it lacks an explicit result type
[error]   implicit val userWrites = Json.writes[UserRow]
```
UserRow is the case class automatically generated by slick.codegen.SourceCodeGenerator. I haven't found any clue on this issue. Please help, thanks.

**Comment by cchantep** [comment]
I guess you have to refactor your `OWrites` as `Writes`. Please first ask the question on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework). If there is an issue confirmed on Play side an actionable issue can be then filed there. Best regards.

**Comment by takezoe** [comment]
I have same issue. Found a thread below but there are no response.
https://groups.google.com/forum/#!topic/play-framework/yz6_Wh5EYVY

Any idea?

**Comment by DieterLi** [comment]
@tekezoe I don't know why there is no one response this, no materials explain format/writes/reads started with O, and no clue till to now. And the referred Google group topic was posted by me, twice. 

ぜんぜん　わかりません。

Have to wait and keep searching.

**Comment by takezoe** [comment]
@DieterLi I expect macro implementation has been changed in 2.4. But I don't know about Scala macro well...

**Comment by DieterLi** [comment]
@takezoe Definitely, you are quite right. And I also checked some materials about Scala reflection. It seems the problem about the type path, but I haven't figured out a clear explanation about it. But the changes front 2.4.x is a good sign, because it proves that playframework works on more Scala fundamental elements, in a pure Scala way, from my prospective.

So you can try that:
1. case class defined in normal package, not in a trait, JSON Inception works as expected;

2. any case class defined in trait, the error happens. 

I will keep you posted, once I got something can really make it clear.

**Comment by ergomesh** [comment]
did anyone figured this out. Im trying to get codegen working without duplicating my case classes from the codegen. any time i try to define a `implicit val atcFmt = json.format[Tables.Cat]` i get the same errors as noted above.

 I would prefer to keep the tables from codegen in traits.

**Comment by mseravalli** [comment]
+1 
same issue still not solved 
https://github.com/playframework/playframework/issues/4974

**Comment by mrwillis** [comment]
Is there any workaround for this?
