### ISSUE TITLE
[request] Integrating a WAMP implementation

### ISSUE THREAD

**Issue by makoConstruct** [playframework/playframework#4604]
WAMP is a really good websocket subprotocol. RPC, one of the things it provides, is pretty much a necessity for complex websocket apps. It would be great to have a WAMP implementation built into play.

If you wanted to use an outside project, https://github.com/Matthias247/jawampa is looking quite good. It supports netty, so it may be should be quite easy to integrate.

If this is not to be, I would greatly appreciate a side project, or instruction as to where to start in building a side project myself that makes it easy to wrap a ws.wamp.jawampa.WampRouterHandler (implements io.netty.channel.ChannelHandler) into a play.api.mvc.WebSocket[In, Out] and plug it into an application route.

**Comment by cchantep** [comment]
Thanks for the suggestion. Please first discuss the feature request on the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework). Best regards.
