### ISSUE TITLE
[2.3] Problem with Database Evolution in Production Mode

### ISSUE THREAD

**Issue by micha-09** [playframework/playframework#4605]
Hello Guys,

we use PlayFramework 2.3.6 in our Project. From a day to another day, we have a problem with evolution.
We use the command "activator clean stage" to build our play project after that we start with "target/universal/stage/bin/infoscreen -DapplyEvolutions.default=true -DapplyDownEvolutions.default=true"
But if there are changes in the model, this would not be recognize by playframework. So the application start, but the database isn`t actual.
If we build with the "run" command, play will recognize the database changes and offer us to manual make evolution in browser.

So i don`t understand why run is working but production mode not. Any ideas?
Thanks

**Comment by cchantep** [comment]
Hi, please first ask such question on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework). Then if an issue is confirmed, an actionable ticket can be filed there. Best regards.
