### ISSUE TITLE
[2.3.8] Invalid token found in form body

### ISSUE THREAD

**Issue by kurochenko** [playframework/playframework#4607]
Hello,

I'm using Play with SecureSocial for auth. On fresh start of app (with cookies cleared e.g. using private window in browser). When i first try to log in i get `Invalid token found in form body` message. All other trials of login work. I tried to investigate why is this happening and here is what i found.

In my application `Global` object extends `WithFilters(CSRFFilter())`. Filter calls `CSRFAction` which checks http headers for csrf token and if there is none it **creates new token**, adds it to `request.tags` (important!) and to response.

SecureSocial uses `CSRFAddToken` object for login action creation (see https://github.com/jaliss/securesocial/blob/2b8f363ed84a5ee20d0079fff03f0de9db6975e3/module-code/app/securesocial/controllers/LoginPage.scala) which finds `csrf token` in request headers and if there is none **new token is generated**.

Now when i go to `/auth/login` this happens: 
 1. `CSRFFilter` (global filter) creates new token (no token exists yet because of clear environment) and adds it to `request.tags` and to `response`
 1. `CSRFAddToken` (login controller) tries to find token in request, but it checks only cookies etc. but not `tags`! After it fails to find token it creates new one (different from step one) and ads it to html form for login purpose.
 1. When i try to log-in the two tokens are not equal and this error occurs. 
 1. any consequent login request etc works fine already as there is token stored in cookies and session  and both `CSRFFilter` and `CSRFAddToken` takes token from same place.

Can anyone, please, look at it? Maybe i configured something in a wrong way. This happens only once per user on clean environment. But still it's not pretty.

Maybe `CSRFAddToken` should also try to look up token in `request.tags`?

Thanks everybody for help solving this issue.

**Comment by marcospereira** [comment]
Hello, @kurochenko. Could you please discuss that at the [user mailing list](https://groups.google.com/forum/m/#!forum/play-framework) and, if we confirm there is an issue, then we will open one.

Thanks.
