### ISSUE TITLE
[2.4] GuiceBuilder does not utilize com.google.inject.Stage.PRODUCTION

### ISSUE THREAD

**Issue by jCalamari** [playframework/playframework#4608]
```
def injector(): PlayInjector = {
    try {
      val guiceInjector = Guice.createInjector(applicationModule())
      guiceInjector.getInstance(classOf[PlayInjector])
    } catch {
      case e: CreationException => e.getCause match {
        case p: PlayException => throw p
        case _ => throw e
      }
    }
  }
```

Above method from `GuiceBuilder` creates `guiceInjector` with default stage which is `Stage.DEVELOPMENT` for all environments. Wouldn't it be wiser to use `Stage.PRODUCTION` in `PROD` environment?

**Comment by matiwinnetou** [comment]
+1.  I also noticed, please keep in mind that Stage from Guice is not equal 100% to Play's mode, there is a missing stage for Mode.TEST from play.

**Comment by jCalamari** [comment]
> please keep in mind that Stage from Guice is not equal 100% to Play's mode, there is a missing stage for Mode.TEST from play.

True. There are only two stages from Guice which match Play environment anyway.

**Comment by jwshin** [comment]
+1

**Comment by richdougherty** [comment]
:+1:

**Comment by jCalamari** [comment]
Something went wrong with pull request and instead of attaching the pull request to the issue, new issue was created.

https://github.com/playframework/playframework/pull/4847

**Comment by cchantep** [comment]
Closing this one as a PR is available.

**Comment by marcospereira** [comment]
Hey @JindalMohit,

If I understood correctly, this is a different problem. Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

Best.
