### ISSUE TITLE
minified javascript files not available at javascripts-min path

### ISSUE THREAD

**Issue by nlhkh** [playframework/playframework#4609]
If I create some javascript files under `app/assets/javascripts`, then when I run in production mode, the path to the scripts changes from `javascripts` to `javascripts-min`. However, there is no files under `javascripts-min`, and the minified files are under `javascripts`. Is this a bug?

**Comment by jroper** [comment]
Explain what you mean by *the path to the scripts changes from javascripts to javascripts-min*?

**Comment by nlhkh** [comment]
It does not happen any longer. I cannot reproduce it. Please close it for now.

Thanks
