### ISSUE TITLE
Avoid Logging Errors in RequestBodyHandler.scala

### ISSUE THREAD

**Issue by McKizzle** [playframework/playframework#4610]
When a browser terminates a connection abruptly Play logs a ClosedChannelException as an error. Since the exception is originating from Netty and is not within direct the control of those using the Play framework. It would be better if the errors were logged either as a warning or info message. Which wouldmake it a lot easier to focus on errors that are relevant to the application.

Cheers,
MrMcKizzle

**Comment by cchantep** [comment]
Hi @McKizzle , please first discuss of this logging on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework). If a feature request is then confirmed, a ticket or PR can be created in this issue tracker. Best regards.

**Comment by McKizzle** [comment]
Thanks @cchantep I'll do that!
