### ISSUE TITLE
Document the use of externalizeResources

### ISSUE THREAD

**Issue by marcospereira** [playframework/playframework#4611]
See #4594 and #4590.

**Comment by mkurz** [comment]
Are you sure we should document this bug? Isn't this fixed in upcoming Play 2.4.1 anyway, so that there is no need anymore to set externalizeResources?

**Comment by mtrovo** [comment]
I think this change is not needed anymore as the correction is on v2.4.1.
see https://github.com/playframework/playframework/pull/4522

**Comment by jroper** [comment]
`externalizeResources` should still be documented regardless of whether it can be used to work around any bug or not.

**Comment by mtrovo** [comment]
Looking further I think it's already being documented by commit 9f030eb3b77634fe3580715d95778637640b64a0

**Comment by mkurz** [comment]
@jroper Is the documentation merged in #5013 enough?
If so I think we can close this issue.
