### ISSUE TITLE
Update Scalatest doc

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#4613]
https://www.playframework.com/documentation/2.4.x/ScalaTestingWithScalaTest still points to scalatest 1.2.0 although there is a dependency on Play 2.3.0 there.

There is no 2.4.x version of Scalatest-Play, but when https://github.com/scalatest/scalatestplus-play/pull/16 lands we should update this.

**Comment by marcospereira** [comment]
@wsargent This is ok for 2.5.x docs.

Can we close this issue?

**Comment by wsargent** [comment]
Yeah, is good.
