### ISSUE TITLE
[2.4] WebSockets won't open with compile-time DI

### ISSUE THREAD

**Issue by codingismy11to7** [playframework/playframework#4614]
Simple reproduction of this issue: https://github.com/CodeMettle/play-24-cake-di-no-websocket

This may just be a documentation issue (I've read all of the 2.4 DI, migration, and WebSocket docs multiple times), but I can't figure out how to make WebSockets work while using compile-time DI. The linked project is the activator `play-scala` project with a WebSocket added in; if play.application.loader is set then it refuses to open a websocket, if commented out (so the compile-time DI is ignored and default application loading is used) then everything works properly. I've looked through all of the *Components classes I could find, and experimented with `NettyServerComponents`, but nothing I've tried has worked. Something isn't being configured properly in Netty.

**Comment by codingismy11to7** [comment]
Posted on mailing list:

I ran into this one as well. It seems that WebSocket methods try to use the global actor system, and it runs into this error when the loader can't find one. The problem is in framework/src/play/src/main/scala/play/api/mvc/WebSocket.scala on line 174, it tries to create the actor in the global Akka.system, when what we really want is to pass in the instantiated actorsystem we create in our application loader.

For the time being, I ripped out the tryAcceptWithActor code into my controller so I could directly pass in the actorsystem to use. It also meant copying WebSocketsActor because the message it expects, WebSocketsActor.Connect, is private.

However, tryAcceptWithActor needs to be changed so that compile-time DI users can pass in their actorsystem.

**Comment by emergentcypher** [comment]
I ran into this problem as well. The issue seems to be in WebSocket.scala line 174:

https://github.com/playframework/playframework/blob/a0a8bd5796c746334dac1d88f65cda66975cb6a8/framework/src/play/src/main/scala/play/api/mvc/WebSocket.scala#L174

It attempts to create the actor with Akka.system, but compile-time DI users need to be able to pass in their own actorSystem that they instantiate in their application loader.

I'm working around this in my project right now by redefining tryAcceptWithActor to accept the actorSystem from my controller's constructor arguments.

**Comment by gmethvin** [comment]
I think the best solution here is to change the implicit `Application` to an implicit `ActorSystem`.

As a workaround you could also add the `ActorSystem` to the runtime injector used by play (see https://github.com/playframework/playframework/blob/2.4.0/framework/src/play/src/main/scala/play/api/Application.scala#L269)

**Comment by emergentcypher** [comment]
I first tried adding it to the injector but ran into different exceptions related to instantiating the actorsystem and couldn't get it working...

**Comment by dkharrat** [comment]
fyi, I managed to get the workaround suggested by @gmethvin working. I posted how in my StackOverflow question: http://stackoverflow.com/q/31336904/120930

Hopefully this gets fixed in the next release though.

**Comment by richdougherty** [comment]
A fix is to change `Akka.system` to just read `actorSystem` field out of the `Application` object.

E.g.
```scala
  def system(implicit app: Application): ActorSystem = app.actorSystem
```

For future versions we should probably deprecate this method, now that `actorSystem` is just a field in the `Application` anyway.
