### ISSUE TITLE
`app.routes` initialized outside of application's context classloader

### ISSUE THREAD

**Issue by OlegIlyenko** [playframework/playframework#4616]
In this place:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/Play.scala#L89

`routes` is initialized outside of application's classloader. Is there a particular reason for this?

The problem I'm currently facing is that initialization of `routes` in a DI container can cause loading of application-specific classes, like controllers (I noticed it when I switched to `routesGenerator := InjectedRoutesGenerator`). I debugged it a little bit, and only in this particular place the context class loader is `PlayDependencyClassLoader` instead of `ReloadableClassLoader`.

This causes all kinds of errors, including `ClassNotFoundException`:

    java.lang.ClassNotFoundException: controllers.Application

I checked other places, like `applicationLoader.load(...)`, and they all are executed with current application's classloader being a context class loader of the current thread.

**Comment by jroper** [comment]
Are you seeing these problems in 2.4?

Yes, I definitely think the router should be initialised with the context classloader set.

**Comment by OlegIlyenko** [comment]
Yes, I noticed this issue after moving to 2.4 and using `InjectedRoutesGenerator`. For the moment being I created a workaround by setting up the context class loader myself for all injected dependencies:

https://github.com/scaldi/scaldi-play/blob/master/src/main/scala/scaldi/play/ScaldiInjector.scala#L38

Now that you confirmed my assumption, I felt brave enough to create a PR for this issue :) 

https://github.com/playframework/playframework/pull/4669
