### ISSUE TITLE
Make ValidationError a trait.

### ISSUE THREAD

**Issue by bitbender** [playframework/playframework#4619]
I am currently using the validators to validate incoming json. Basically I want to have my own definition of how ErrorMessages should look like.

I tried a lot to trick play into doing what I want but it seems to be the case that I need to replace the ValidationError with my own ValidationError class. This isn't possible since extending a case class is not the way to go see:

* [Scala case class inheritance](http://stackoverflow.com/questions/12705309/scala-case-class-inheritance)
* [Extending scala case class without constantly duplicating contructors vals?](http://stackoverflow.com/questions/11165432/extending-scala-case-class-without-constantly-duplicating-contructors-vals)

Therefore I would suggest to change the ValidationError case class into a trait plus some default implementation. This way anyone could replace the ValidationError class with his own implementation.

Thanks

**Comment by cchantep** [comment]
Hi. The [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework) is a good place to discuss of such API change. Best regards.
