### ISSUE TITLE
scala playframework 2.4.0 - json seq deserialization problem - 

### ISSUE THREAD

**Issue by limuhob** [playframework/playframework#4622]
Hello. 

I have a problem with a deserialization of Seq from json in playframework 2.4.0. This test:

        import org.specs2.mutable.Specification
        import play.api.libs.json._

        class JsonProblemSpec extends Specification {

            case class Foo(data: Seq[String])

            def createReads[T](r: Reads[T]): Reads[T] = {
                __.json.update(__.read[JsObject].map(js => js)) andThen r
            }

            implicit val f1 = createReads(Json.format[Foo])

            val sampleJson = Json.parse("""{"data":["a","b"]}""")
    
            "json lib" should {

                "deserialize list" in {
                    sampleJson.as[Foo].data.size === 2
                }
            }
        }

should be success but actual seq size is 4 and Foo looks this way:

    Foo(List(a, b, a, b))

The same test in playframework 2.3.x is ok.

**Comment by cchantep** [comment]
Hi. The `createReads` seems weird. What is the goal there?

**Comment by limuhob** [comment]
This is symplification. The goal of the real code is creating a Reads[T] with input json preprocessing based on some parameters. Something like this:

    def createReads[T](r: Reads[T], parameters ...): Reads[T] = {
        __.json.update(__.read[JsObject].map(js => modifyInputJsObject(js, parameters))) andThen r
    }

**Comment by cchantep** [comment]
I think it's better to first ask question about your code (with a more complete sample) on the [user MailingList](https://groups.google.com/forum/#!forum/play-framework). Then an detailed/actionable ticket can be filed there if an issue is confirmed. Best regards.

**Comment by limuhob** [comment]
I don't think that questions about my code helps to diagnose and solve the bug. In my opinion this code demonstrate the bug clearly. But OK I'm going to ask mailing list.
