### ISSUE TITLE
play.api.Plugin is marked as deprecated, but the documentation states you should extend it.

### ISSUE THREAD

**Issue by ghost** [playframework/playframework#4625]
At playframework/documentation/manual/working/scalaGuide/advanced/extending/ScalaPlugins.md, it states to create a Plugin you should extend play.api.Plugin. However when you do so, you are presented with a warning since it is marked as deprecated. So declaring a Plugin with:
```scala
class SwaggerPlugin @Inject() (application: Application, router: Router) extends Plugin {
```

Will produce the following warning:
```
swagger-core/modules/swagger-play2/app/play/modules/swagger/SwaggerPlugin.scala:29: trait Plugin in package api is deprecated: Use modules instead
```

**Comment by matiwinnetou** [comment]
Plugin is indeed deprecated in 2.4 and the version you try to use is working with Play 2.3.

You can however use this library, which I pushed today to maven central:

https://github.com/matiwinnetou/swagger-play24

**Comment by matiwinnetou** [comment]
I suggest closing this (Play Commiters)

**Comment by mikalveli** [comment]
Right, I just posted that code as a reference since I'm updating the swagger-core/swagger-play2 plugin for our project. It still seems to be a problem, to me anyway, if the documentation is telling you that you should extend Plugin, but it is marked as deprecated.

**Comment by matiwinnetou** [comment]
You are looking to a deprecated documentation (Play 2.3)

**Comment by matiwinnetou** [comment]
Ah, I see what you mean now,

this page should be removed to be frank:

https://playframework.com/documentation/2.4.x/ScalaPlugins
