### ISSUE TITLE
Unable to create a new 2.3.X application

### ISSUE THREAD

**Issue by skrigs** [playframework/playframework#4627]
I needed to create a new application using play 2.3.X, however activator set up a 2.4 version, which I then needed to downgrade. i.e. activator app-name play-java

It would be useful if the seed could include the play version to create a previous version.

**Comment by marcospereira** [comment]
Probably more related to Activator then with Play itself. Anyway, do you mind discuss that first on the [user mailing list](https://groups.google.com/forum/m/#!forum/play-framework)? If we confirm that there is an error with Play, than we can open an issue with Activator or Play.

Thanks.

**Comment by jroper** [comment]
I've just fixed this in 16c7db3, you can now create a new Play 2.3 project by using the `play-scala-2.3` or `play-java-2.3` templates.
