### ISSUE TITLE
Allow to use custom actor system for web sockets

### ISSUE THREAD

**Issue by codenamestif** [playframework/playframework#4632]
Play docs say that if you need to use Akka, you can use or inbuilt actor system or your own. It's ok. But for web socket actor you don't have choice, because play uses only unbuilt one and it's a little bit sad. If you tries to use only your own actor system, you don't worry about instantiating of several instances of some connection pool that wrapped by akka extension. But you should because you really don't have choice, you need to use only unbuilt actor system to avoid such cases. So please think about ability to use custom actor system for web sockets.  [The cause is here](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play/src/main/scala/play/api/mvc/WebSocket.scala#L181).

**Comment by wsargent** [comment]
Can you provide a test case or some sample code please?

**Comment by gmethvin** [comment]
Related: #4614

**Comment by codenamestif** [comment]
Let me try to explain you, if it doesn't help, i will provide you sample code.

1. You have your own actor system
2. You have connection pool that wrapped by akka extension (DatabaseConnectionProvider)
3. You have simple service actor that do something by http request
4. You have simple web socket actor that do something by incoming message

You expect that you have only one instance of connection pool for whole application, because akka extensions load once per actor system. So if you have one actor system, that means you have one instance of you extension, that means you have one instance of you connection pool ([doc](http://doc.akka.io/docs/akka/snapshot/scala/extending-akka.html)).

In every actor you have this line:
```scala
 val connection = DatabaseConnectionProvider(context.system).getMyConnection
```
You expect that if you have only one actor system and all actor were instantiated in it, context.system refers to the same and the only actor system, and as result you have the only instance of connection pool) 

But what if actor was instantiated using ```WebSocket.tryAcceptWithActor``` method?
That means it was instantiated in play's unbuilt actor system, and as result ```context.system``` refers to inbuilt actor system. And if you try to get connection as it is above, you will create new instance of extension, that means new instance of connection pool, because it's usual behaviour of akka extensions. And it isn't good.

**Comment by jroper** [comment]
I agree with @gmethvin, the proposed solution in #4618 is the solution to this issue as well, since it will make the builder for these websockets injected with the actor system, making it possible to instantiate your own.

**Comment by wsargent** [comment]
I think this is fixed with `accept` / `acceptOrResult` https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/WebSocket.scala#L241
