### ISSUE TITLE
Document routing regex syntax about ^ and $.

### ISSUE THREAD

**Issue by vantonio** [playframework/playframework#4639]
this syntax won't match anything:
```
/page/$id<^[0-9]{8}$>
```
but it's valid regex expression.

**Comment by jroper** [comment]
Sure, there are plenty of valid regex expressions that cannot match anything.  That ones saying "match the start of the path half way through the path".  Is it so necessary to document that such a paradox won't match anything?

**Comment by cchantep** [comment]
Hi @vantonio, please ask such question on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework). Best regards.

**Comment by vantonio** [comment]
@jroper, Ah I see, we are matching against the whole path, not the id part. 
Sorry for the noise and thanks for your time..
