### ISSUE TITLE
Default webjars install dependency includes PHP files

### ISSUE THREAD

**Issue by m242** [playframework/playframework#4640]
Run an activator new play-scala template, then an activator compile.

${PROJECT_HOME}/project/target/node-modules/webjars/npm/node_modules/request/node_modules/tough-cookie/node_modules/punycode/vendor/docdown/docdown.php is a thing that exists (among others).

I realize that this may be a necessary evil due to the vagaries of the webjars project, but this *feels* wrong to me. The fact that deep down in a generated jar file lurks some random PHP scripts makes me very uncomfortable from an overall security aspect.

Is there a way that the default activator dependencies can exclude *.php?

**Comment by jroper** [comment]
We could exclude these files from the npm webjar, but other than that no.  Note there's a tonne of js there, as well as scala code through out your build - there is nothing intrinsically more dangerous about having a php file on your system than having any other file from any other programming language.

**Comment by cchantep** [comment]
Closing it for now. It can be reopened if more feedback.
