### ISSUE TITLE
Problem with CXF clent

### ISSUE THREAD

**Issue by lnowak** [playframework/playframework#4644]
I am using CXF client in Play Framework. Recenty I have moved to latest version of Play Framework, but after that I am receiving this error:
[RuntimeException: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 55 in XML document from class path resource [spring-config-jaxrs-client.xml] is invalid; nested exception is org.xml.sax.SAXParseException; systemId: jar:file:/C:/Users/Łukasz/.ivy2/cache/org.apache.cxf/cxf-rt-transports-http/jars/cxf-rt-transports-http-2.7.12.jar!/schemas/configuration/http-conf.xsd; lineNumber: 55; columnNumber: 66; src-resolve: Cannot resolve the name 'http-conf:client' to a 'element declaration' component.]
I have also tried latest CXF version 3.1.1, but still the same error.

**Comment by marcospereira** [comment]
Hello @lnowak, do you mind discuss that first on the [user mailing list](https://groups.google.com/forum/m/#!forum/play-framework)? If we confirm that there is an error with Play, than we can open an issue.

Thanks.
