### ISSUE TITLE
[2.4] Migration guide about loose SSL configuration

### ISSUE THREAD

**Issue by edouardKaiser** [playframework/playframework#4654]
In the migration guide (https://www.playframework.com/documentation/2.4.x/Migration24) it says that to accept any X.509 certificate without validation we should use **play.ws.loose.acceptAnyCertificate**

But in the Loose SSL section (https://www.playframework.com/documentation/2.4.x/LooseSSL) it says **play.ws.ssl.loose.acceptAnyCertificate**

It looks like the correct one is the one in the Loose SSL section.

**Comment by cchantep** [comment]
See #4659
