### ISSUE TITLE
Inject Akka shard region in proxy-only mode  

### ISSUE THREAD

**Issue by bolshakov** [playframework/playframework#4655]
I have a fornt-end/backend architecture where Play works as front-end to Akka Cluster.
From the Play's point of view I  start shard region in proxy-only mode since front-end does not have access to the actor class.

So I could not use `AkkaGuiceSupport` trait to inject ActorRef dependency into controller since it requires  an actor class to be present. Example from the [Integrating with Akka](https://www.playframework.com/documentation/2.4.x/ScalaAkka) docs:

```scala
class MyModule extends AbstractModule with AkkaGuiceSupport {
  def configure = {
    bindActor[ConfiguredActor]("configured-actor")
  }
}
```

But in front-end app I access sharded actor by name, not by class:

```scala
ClusterSharding(system).start(
      typeName = "User",
      entryProps = None,
      idExtractor = UserRegion.idExtractor,
      shardResolver = UserRegion.shardResolver
)

ClusterSharding(system).shardRegion("User")
```

**Comment by cchantep** [comment]
Hi, please first ask such question on the [user Mailing List](https://groups.google.com/forum/m/#!forum/play-framework). If an issue is confirmed, then a ticket can be filed on this tracker. Best regards.

**Comment by bolshakov** [comment]
I've already asked in mailing list https://groups.google.com/forum/m/#!topic/play-framework/N3e8PZucOq0

**Comment by bolshakov** [comment]
How can I confirm the issue?

**Comment by bolshakov** [comment]
@cchantep could you help me to report the issue? Is there any guidelines? 

I reported a problem to Play user mailing list https://groups.google.com/forum/m/#!topic/play-framework/N3e8PZucOq0 without any feedback. Then I created this issue but you have closed it.

What's wrong with my report?

**Comment by jroper** [comment]
@bolshakov Guidelines are here:

https://playframework.com/contributing

In short, this is not a support system, it's for reporting bugs.  What you're reporting is not a bug, it's a request for help.  If you need help and aren't satisfied by the avenues provided by the community, then you should consider whether you want to purchase a commercial subscription from Typesafe.
