### ISSUE TITLE
Cannot build play 2.4.0 from source

### ISSUE THREAD

**Issue by eswenson1** [playframework/playframework#4657]
I'm trying to build Play 2.4.0 from source and after checking out the "2.4.0" tag, and running "build", I get the following error:

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#play-iteratees_2.11;2.4.0: configuration not public in com.typesafe.play#play-iteratees_2.11;2.4.0: 'test'. It was required from com.typesafe.play#play_2.11;2.4.0 test
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.play:play-iteratees_2.11:2.4.0
[warn] 		  +- com.typesafe.play:play-json_2.11:2.4.0
[warn] 		  +- com.typesafe.play:play_2.11:2.4.0

**Comment by wsargent** [comment]
Hi @eswenson1, Please ask on the mailing list: https://groups.google.com/forum/#!forum/play-framework-dev -- it also helps if you copy your .history file and sbt history so it's clear exactly what you typed.
