### ISSUE TITLE
Missing `s` before string interpolation in error message NettyServer.scala

### ISSUE THREAD

**Issue by gavares** [playframework/playframework#4674]
See https://github.com/playframework/playframework/blob/f88b38fd9187bc6adf79c41288f2fc7bd4938880/framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala#L216

```scala
 System.err.println("NettyServer.main is deprecated. Please start your Play server with the ${ProdServerStart.getClass.getName}.main.")
    ProdServerStart.main(args)
```

should be:
```scala
 System.err.println(s"NettyServer.main is deprecated. Please start your Play server with the ${ProdServerStart.getClass.getName}.main.")
    ProdServerStart.main(args)
```

Notice the `s` char at the front of the string.

**Comment by marcospereira** [comment]
Thanks for pointing that, @gavares. Do you mind to submit a pull request to fix that?

**Comment by gavares** [comment]
No problem.

**Comment by marcospereira** [comment]
Merged. 

Thanks, @gavares!
