### ISSUE TITLE
Extending the GuiceApplicationLoader Documentation is broken

### ISSUE THREAD

**Issue by baank** [playframework/playframework#4678]
On this page:
https://www.playframework.com/documentation/3.0.x/ScalaDependencyInjection

Under:
Advanced: Extending the GuiceApplicationLoader

It references an initialBuilder variable in the code example which does not exist.

**Comment by marcospereira** [comment]
@baank 

It actually exists:

https://github.com/marcospereira/playframework/blob/master/documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/RuntimeDependencyInjection.scala#L232-L247

Notice that the example is extending `GuiceApplicationLoader` which declares a `initialBuilder` variable:

https://github.com/marcospereira/playframework/blob/master/framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala#L15

Also, most of the code examples in the docs are extracted as [compiled code snippets](https://www.playframework.com/documentation/2.4.x/Documentation#Code-samples) to help us guarantee they are correct.
