### ISSUE TITLE
Replace `play.libs.F.Function` with Java 8 equivalents

### ISSUE THREAD

**Issue by dotta** [playframework/playframework#4690]
Replace `play.libs.F.Function` and friends with `java.util.function.Function` and friends.

**Comment by hepin1989** [comment]
@dotta 
how about add other functions via 
https://github.com/sbt/sbt-boilerplate?

**Comment by dotta** [comment]
@hepin1989 Thanks for pointing that out. I haven't really made up my mind, but we are also considering using a third-party library such as [javaslang](http://javaslang.com/) for some of the types that are not available in the Java8 standard library. We will see.

**Comment by hepin1989** [comment]
you guys make Play grate and our life easier,btw,I think that play doc should add something like best practice :)

**Comment by dotta** [comment]
> you guys make Play grate and our life easier,btw,I think that play doc should add something like best practice :)

Thanks, though this ticket is not the right place for communicating ideas for improving the doc :-)

**Comment by TheUnknownCylon** [comment]
Hi, just a short remark.
In DefaultJPAApi.java, function `public <T> T withTransaction(String name, boolean readOnly, Supplier<T> block) {`

You could remove the following code block. Supplier does not throw anything, so nothing to catch. Is assume the compiler detects this and doesn't give you an error that you have an unhandeled exception. 

        } catch (Throwable t) {
            if (tx != null) {
                try { tx.rollback(); } catch (Throwable e) {}
            }
            throw t;


Cheers!
