### ISSUE TITLE
Allow backticks quoted parameters in routes

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#4693]
Was trying this in my routes:
```
GET    /search        controllers.PeopleController.list(`tags[]`: Seq[String] ?= Seq.empty)
```

I'm getting a routes compilation error on the next line `Compilation error[Identifier expected]`
The controller itself has no issue with a `tags[]` argument

By default it seems that jQuery puts array parameters as `?tags[]=foo&tags[]=bar` but I can't get this to work properly in the routes file.
On the jQuery side this can be configured using the `traditional` setting but I have no control over the client.
http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings
http://api.jquery.com/jQuery.param/

My current workaround looks like this:
```scala
def list(tags:Seq[String]) = Action.async{ implicit request =>
  // since we can not define this in the routes file
  // https://github.com/playframework/playframework/issues/4693
  val arrayTags = request.queryString.get("tags[]")
  val actualTags = arrayTags.getOrElse(tags)
  // continuing with this actualTags
  ...
```

**Comment by wsargent** [comment]
Be aware that square brackets are illegal in URLs according to [RFC 3986](https://tools.ietf.org/html/rfc3986):

```
A host identified by an Internet Protocol literal address, version 6
   [RFC3513] or later, is distinguished by enclosing the IP literal
   within square brackets ("[" and "]").  This is the only place where
   square bracket characters are allowed in the URI syntax.
```

**Comment by francisdb** [comment]
I suppose they must be passed in encoded form `%5B` and `%5D` as shown in http://api.jquery.com/jQuery.param/
