### ISSUE TITLE
Poor performance of MessagesParser

### ISSUE THREAD

**Issue by sebdotv** [playframework/playframework#4696]
play.api.i18n.Messages.MessagesParser, which is based on scala.util.parsing.combinator.RegexParsers, offers very poor performance even with only 1000 lines to parse.

The following measurement was obtained by parsing a simple file with Play 2.3, but I suspect nothing's changed in 2.4 or master.

java.util.Properties.load: 12.84 ms
play.api.i18n.Messages.messages: 7.615 s

```
key_1=some very long line that will take quiet some to parse; some very long line that will take quiet some to parse; some very long line that will take quiet some to parse; some very long line that will take quiet some to parse
key_2=some very long line that will take quiet some to parse; some very long line that will take quiet some to parse; some very long line that will take quiet some to parse; some very long line that will take quiet some to parse
[...]
key_1000=some very long line that will take quiet some to parse; some very long line that will take quiet some to parse; some very long line that will take quiet some to parse; some very long line that will take quiet some to parse
```

**Comment by cchantep** [comment]
Hi @sebdotv, please first ask such question on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework). Then if an issue is confirmed, a ticket can be raised on the tracker. Best regards.

**Comment by sebdotv** [comment]
done at https://groups.google.com/d/msg/play-framework/TXd3xfLC1Ts/5Ooxtjai8xMJ
