### ISSUE TITLE
JSON Prune Function Fails on Missing Path

### ISSUE THREAD

**Issue by michaelahlers** [playframework/playframework#4697]
According to the [JSON transformers documentation](playframework.com/documentation/2.3.x/ScalaJsonTransformers), a call to `json.prune` “doesn’t generate any error and returns unchanged JSON” when applied to a missing path. However, I'm getting `error.path.missing` errors when pruning optional branches of JSON objects.

This test case:

```scala
import org.specs2.mutable.Specification
import play.api.libs.json._

class JsonPruneSpec extends Specification {

  "JSON prune" should {
    "disregard missing paths" in {
      val exemplar = Json.obj("foo" -> "bear")
      val expected = JsSuccess(exemplar)
      val actual = exemplar.validate((__ \ 'fu \ 'bar).json.prune)
      actual must be equalTo expected
    }
  }

}
```

Produces:

```
[info] JSON prune should
[info] x disregard missing paths
[error]    'JsError(List((/fu/bar,List(ValidationError(error.path.missing,WrappedArray())))))'
[error]    
[error]     is not equal to 
[error]    
[error]    'JsSuccess({"foo":"bear"},)' (JsonPruneSpec.scala:11)
[error] Expected: JsSuccess({"foo":"bear"},)
[error] Actual:   JsError(List((/fu/bar,List(ValidationError(error.path.missing,WrappedArray())))))
```

Note: with dependency `"com.typesafe.play" %% "play-json" % "2.3.9"`.

**Comment by michaelahlers** [comment]
@mandubian, am I misreading anything here?

**Comment by mandubian** [comment]
Who wrote this stupid doc???
Oh it's me :)
I have looked code and it seems that doc is completely false.
I can't remember what happened as it was 2 years ago but I think this doc is just wrong and the behavior implemented in the code is "if missing path, it returns JsError".

**Comment by michaelahlers** [comment]
@mandubian, I always enjoy your comments. :smile: Is there any work-around that allows for optional paths? (I've blindly tried tacking `.orElse(Reads.pure(Json.obj()))` to each `prune`, but that only succeeds in wiping the whole document.)

**Comment by mandubian** [comment]
do you have code sample of what you're trying to write to be sure?

**Comment by michaelahlers** [comment]
Sure! Here's that test case with my work-around:

```scala
import org.specs2.mutable.Specification
import play.api.libs.json._

class JsonPruneSpec extends Specification {

  "JSON prune" should {
    "make no changes when optional and path is missing" in {
      val exemplar = Json.obj(
        "foo" -> "bear",
        "path0" -> Json.obj(
          "path00" -> "value00"
        )
      )

      val expected = exemplar
      val actual = exemplar.as((__ \ 'fu \ 'bar).json.prune.orElse(Reads.pure(Json.obj())))

      actual must be equalTo expected
    }
  }

}
```

Produces:

```
[info] JSON prune should
[info] x make no changes when optional and path is missing
[error]    '{}'
[error]    
[error]     is not equal to 
[error]    
[error]    '{"foo":"bear","path0":{"path00":"value00"}}' (JsonPruneSpec.scala:25)
[error] Expected: {"foo":"bear","path0":{"path00":"value00"}}
[error] Actual:   {}
```

**Comment by mandubian** [comment]
have you tried something like (not sure it will work as I haven't used that for years :D):

```
      val actual = exemplar.as((__ \ 'fu \ 'bar).json.prune.orElse(__.json.pick))
```

**Comment by michaelahlers** [comment]
@mandubian, sweet! A minor tweak: use `pickBranch` (`prune` operates on `JsObject` while `pick` operates on all `Jsvalue`).

Now this:

```scala
import org.specs2.mutable.Specification
import play.api.libs.json._

class JsonPruneSpec extends Specification {

  "JSON prune" should {
    "make no changes when optional and path is missing" in {
      val exemplar = Json.obj(
        "foo" -> "bear",
        "path0" -> Json.obj(
          "path00" -> "value00"
        )
      )

      val expected = exemplar
      val actual = exemplar.as((__ \ 'fu \ 'bar).json.prune.orElse(__.json.pickBranch))

      actual must be equalTo expected
    }
  }

}
```

Produces:

```
[info] JSON prune should
[info] + make no changes when optional and path is missing
```

So, not a bug; fixed by correct usage of the API. :wink:

Thanks for your help!

**Comment by mandubian** [comment]
cool...
for complex json manipulation, jszipper or lenses are far better IMHO... json transformers are more a side-effect than anything else...
