### ISSUE TITLE
In Fedora 21, activator-1.3.4 thinks Java 8 is broken

### ISSUE THREAD

**Issue by davecb** [playframework/playframework#4698]
$ activator -v clean
$ activator -v clean
# Executing command line:
java
-Dactivator.home=/usr/local/activator-1.3.4
-Xms1024m
-Xmx1024m
-XX:MetaspaceSize=64m
-XX:MaxMetaspaceSize=256m
-jar
/usr/local/activator-1.3.4/activator-launch-1.3.4.jar
clean

error: error while loading CharSequence, class file '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-39.b14.fc21.x86_64/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(bad constant pool tag 18 at byte 10)
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

I updated from activator-1.3.2 when this first happened, based on comments in stackoverflow that suggested I had too old a Play! or Scala.  Alas, it had no effect

I'm running 
$ uname -a 
Linux susie 4.0.4-202.fc21.x86_64 #1 SMP Wed May 27 22:28:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ java -version
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)

$activator -version
JavaScript strict warning: jar:file:///export/home/davecb/.mozilla/firefox/2tiq0i3a.default/extensions/remember-passwords@stanimir-stamenkov.addons.mozilla.org.xpi!/components/nsLoginManager.js, line 62: ReferenceError: reference to undefined property Cc[contractID]^M
JavaScript error: jar:file:///export/home/davecb/.mozilla/firefox/2tiq0i3a.default/extensions/remember-passwords@stanimir-stamenkov.addons.mozilla.org.xpi!/components/nsLoginManager.js, line 62: TypeError: Cc[contractID] is undefined^M
console.error: ^M

**Comment by cchantep** [comment]
Hi @davecb, please first ask such question on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework). Then if an issue is confirmed, a ticket can be raised on the tracker. Best regards.
