### ISSUE TITLE
Documentation Play 2.4.0 Java: instructions for using Play with IntelliJ are wrong

### ISSUE THREAD

**Issue by slimandslam** [playframework/playframework#4703]
With Play 2.4.x,  IntelliJ 14.1.3 and Scala Plugin 1.5.2, there is no "Play2" app as described
here:

https://www.playframework.com/documentation/2.4.x/IDE

It says:

```  
To run a Play application:

In the project tree, right-click the application.
From the list in the context menu, select Run Play2 App.
```

It should say:

```
go to   Run -> Edit Configurations
Add a new configuration 
Choose "SBT Task"
Under "tasks", simply put "run"
Apply change and select OK.
Now you can just use "Run" from the main Run menu
```

**Comment by jroper** [comment]
At the bottom of the page you link to, there's this message:

> Found an error in this documentation? The source code for this page can be found [here](https://github.com/playframework/playframework/blob/2.4.x/documentation/manual/gettingStarted/IDE.md). After reading the [documentation guidelines](https://www.playframework.com/documentation/latest/Documentation), please feel free to contribute a pull request.

GitHub allows you to edit the markdown for that page from your web browser, a PR with your suggested changes would be welcomed.

**Comment by slimandslam** [comment]
https://github.com/slimandslam/playframework/pull/1

**Comment by richdougherty** [comment]
I think you merged that PR into your own fork's master branch, rather than raising a PR against the _playframework_ repository. I'm not quite sure what happened, but here are instructions for editing the docs and raising a PR against the _playframework_ repository.

https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by slimandslam** [comment]
Oops. Ok. I just re-did it the right way. Still, it gave some warnings:

**Comment by richdougherty** [comment]
I see your PR now: #4724. I'll comment on the warnings over on the PR.
