### ISSUE TITLE
Username set in Action is not propagated to Controller with the new API.

### ISSUE THREAD

**Issue by salex89** [playframework/playframework#4706]
In the new Java API (Play 2.4) the [setUsername](https://www.playframework.com/documentation/2.4.x/api/java/play/mvc/Http.Request.html#setUsername-java.lang.String-) method is depricated, and the recommended way is to use the `withUsername` method which returns a new `Request`, with the username set. Since the `delegate.call` expects the `Context`, we build it like this (it's immutable now):

    Context newContext = new Http.Context(context.request().withUsername(usr));
    return this.delegate.call(newContext);

However, when we call `request()` in the controller, the request username is null. 

Just to be clear, we are building our own authenticating action. Using the setUsername, everything works, and has worked, as it should.

**Comment by jroper** [comment]
That's a good point, and an oversight on our part.  A potential solution here may be to re-set the context just before the final action is invoked, or even not set it until just before the action is invoked.  The the latter would potentially break apps, so is probably a Play 2.5 thing.

**Comment by jroper** [comment]
Fixed in #4710
