### ISSUE TITLE
Can't control which responses are gzipped when using Java

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#4708]
Subject says it all.

If there is a way, it should be documented [here](https://www.playframework.com/documentation/2.4.x/GzipEncoding#Controlling-which-responses-are-gzipped), as only the Scala way is described now.

**Comment by jroper** [comment]
There is a way, but it involves interacting with the Scala API, creating a Scala function, etc.  We should be able to give Java users much better control of things like this in Play 3.

**Comment by mkurz** [comment]
@gmethvin you wrote #5500 - do you think you can also create a Java API for `GzipFilter` to fix this issue here? We are writing mostly pure Play Java projects and the gzip filter is the only thing (besides some TemplateImplicits) for which we have to add Scala files for.

**Comment by gmethvin** [comment]
Now we have the ability to write filters in Java we should be able to do this. I'm also thinking we could provide a wrapper that allows you to extend existing Scala filters easily.

**Comment by mkurz** [comment]
Cool! Looking forward to it :smile:

**Comment by mkurz** [comment]
Fixed with #5576
