### ISSUE TITLE
Hot-reloading does not detect source changes on Twirl files when PlayLayoutPlugin is disabled

### ISSUE THREAD

**Issue by julienrf** [playframework/playframework#4715]
If you disable `PlayLayoutPlugin`, changes made to files in the twirl source directory do not trigger a recompilation. Manually calling the `compile` sbt command recompile them as expected, though.

**Comment by julienrf** [comment]
cc @benmccann

**Comment by benmccann** [comment]
Sounds like PlayKeys.playMonitoredFiles` is being set incorrectly.

**Comment by benmccann** [comment]
@jroper It looks like https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala#L96 only looks at `unmanagedSourceDirecories`. Shouldn't it look at managedSourceDirectories as well? I believe Twirl is considered a managed source. How does this work today with `PlayLayoutPlugin` enabled?

**Comment by jroper** [comment]
No, it definitely shouldn't look at managed source directories, that would cause double reloads.

The problem is, twirl adds itself to sbt watched files, but Play doesn't use that because its a list of files, not directories, Play's watch support works on directories (and this is in part because JDK7 WatchService only works on directories).  Since Play depends on twirl, we can fix this in Play by adding `sourceDirectories in (Compile, TwirlKeys.compileTemplates)` to `PlayKeys.playMonitoredFiles`.  We can't fix this for other source generators though.

**Comment by mariussoutier** [comment]
:+1: Please fix this.

**Comment by jroper** [comment]
@mariussoutier does

```scala
PlayKeys.playMonitoredFiles ++= unmanagedSourceDirectories in (Compile, TwirlKeys.compileTemplates)
```

work for you?

**Comment by mariussoutier** [comment]
build.sbt:19: error: No implicit for Append.Values[Seq[sbt.File], sbt.SettingKey[Seq[java.io.File]]] found,
       so sbt.SettingKey[Seq[java.io.File]] cannot be appended to Seq[sbt.File]
    PlayKeys.playMonitoredFiles ++= (unmanagedSourceDirectories in (Compile, TwirlKeys.compileTemplates))
                                ^
     [error] Type error in expression

**Comment by mariussoutier** [comment]
When I add `.value` it compiles, but it still doesn't reload the templates.

**Comment by mariussoutier** [comment]
When using `~run` I can see the templates get recompiled upon change, but the new version isn't served.

**Comment by mariussoutier** [comment]
`PlayKeys.playMonitoredFiles ++= (managedSourceDirectories in (Compile, TwirlKeys.compileTemplates)).value` seems to do the trick.

**Comment by sakthipriyan** [comment]
Adding following lines to `build.sbt` file didn't fix it for me. Do I need to add more config?

    PlayKeys.playMonitoredFiles ++= (managedSourceDirectories in (Compile, TwirlKeys.compileTemplates)).value

**Comment by benmccann** [comment]
How does SBT monitor files and not directories? Can we use their file monitoring in Play?

Or if SBT's monitoring is less efficient and not scalable to our needs, then should we ask the SBT folks if they can monitor directories instead of files?

**Comment by domdorn** [comment]
we should stick to directories... I have a task where I have to add some static resources (generated by gulp) to the unmanagedSrcDirectory of my assets project.. now SBT has over 13K keys and everything takes a long sbt takes a long time to get ready. With directories, I could have added just a single key and would have been done with it.

**Comment by landlockedsurfer** [comment]
Hi!
I still seem to be running into this issue in Play! 2.8.2.
This repo contains a minimal example to reproduce the issue:
https://github.com/landlockedsurfer/play-default-layout-example

**Comment by mkurz** [comment]
@landlockedsurfer I can reproduce as well. 

The output of 
```
sbt:play-default-layout-example> show playMonitoredFiles
[info] core / playMonitoredFiles
[info] 	List(./play-default-layout-example/core/src/main/scala, ./play-default-layout-example/core/src/main/twirl)
[info] app / playMonitoredFiles
[info] 	List(./play-default-layout-example/core/src/main/scala, ./play-default-layout-example/app/src/main/scala, ./play-default-layout-example/app/src/main/resources, ./play-default-layout-example/app/src/main/twirl)
```

tells us that `./play-default-layout-example/core/src/main/twirl` was only added to the core project, but not the app project, unlike `./play-default-layout-example/core/src/main/scala`, which gets added to both.

Not sure, but I think the `core/src/main/scala` gets added to both projects in https://github.com/playframework/playframework/blob/2d81591b7618202b6ab447e65cb549fa81f7e9bc/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L120 via the [`playMonitoredFilesTask`](https://github.com/playframework/playframework/blob/2d81591b7618202b6ab447e65cb549fa81f7e9bc/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala#L88), whereas when adding the twirl templates here
https://github.com/playframework/playframework/blob/2d81591b7618202b6ab447e65cb549fa81f7e9bc/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L214
`core/src/main/twirl` only gets added to the core project, when it should be added to `app` as well...

Maybe also
https://github.com/playframework/playframework/blob/2d81591b7618202b6ab447e65cb549fa81f7e9bc/dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala#L92-L93
causes a problem, but I don't think so...

**Comment by mkurz** [comment]
Opened #10831 instead
