### ISSUE TITLE
evolution doesn't work with play.http.context set, routed via an Apache proxy

### ISSUE THREAD

**Issue by leonyah** [playframework/playframework#4720]
I am running my application via Apache proxy, which proxies requests to certain path to my Play application.  This means that my Play application must be started with play.http.context set to a certain path in order for all the URLs to be generated properly. I run my application with -Dplay.http.context="/somepath". 
Going to the app for the first time, I am asked to apply the evolution. 
Clicking on "Apply this script now" button, I am taken to "http://localhost/@evolutions/apply/default" which is incorrect URL (ignores my http.context path).
The only way to run the evolution is to go to URL without the context path, directly to the Play server port.

**Comment by marcospereira** [comment]
The problem is here:

https://github.com/playframework/playframework/blob/master/framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala#L382-L384

**Comment by mkurz** [comment]
PR: #5536
