### ISSUE TITLE
Rewrite CSRF filter to use Akka streams

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#4731]
The CSRF filter currently uses iteratees to extract the token out of the body, it should be rewritten to use Akka streams.

**Comment by jroper** [comment]
I actually think the iteratees based solution we have now is the best way to go.

The problem is, Akka streams makes this really difficult because you can't dynamically plug a new flow/sink/whatever into the stream processing mid stream.  This means, we can't delay executing the action without materialising a second flow mid stream, and once the second stream was materialised, Akka streams simply does not provide any nice API for plugging this into the first, you'd have to do all your own synchronisation etc, the only API we could use would be an AsyncStage, and I just tried, it'd be several hundred lines of quite fragile code to manage the different states, where with iteratees, it's only a few lines of essentially plumbing, no real state to think about in your head - if it compiles it works.

So I think we're best off keeping iteratees here.

**Comment by hepin1989** [comment]
Maybe move this to backoff?
Once akka add some support for this I think it should be fine to re open this.
I think this should be possible that we don't plug any new flow/sink/whatever but change a special one,which support plug more processing but keep the shape.from the outside,it always the same.

**Comment by jroper** [comment]
Actually, I just looked at this again - what I want to do can be achieved using `Flow.splitWhen`.
