### ISSUE TITLE
Download says JDK6+ (outdated) but documentation correctly says JDK8 only

### ISSUE THREAD

**Issue by fabiankessler** [playframework/playframework#4738]
Best explained with screenshots taken today, see the URLs for the affected pages:

![2015-06-22 16_39_14-downloads](https://cloud.githubusercontent.com/assets/2506130/8283077/b105b06e-18fd-11e5-9349-3dff5a05f211.png)

![2015-06-22 16_40_06-migration24](https://cloud.githubusercontent.com/assets/2506130/8283082/bb1bed98-18fd-11e5-8d49-34be4cbf67e3.png)

**Comment by marcospereira** [comment]
This was fixed by https://github.com/playframework/playframework.com/pull/28.

@jroper, I will let this issue open as a reminder that we need to send that PR to production.

**Comment by jroper** [comment]
I just deployed it then with the 2.4.1 release.
