### ISSUE TITLE
'activator test' using default "changeme" password for DB login

### ISSUE THREAD

**Issue by fxer** [playframework/playframework#4741]
Apparently the command `activator test -Dconfig.file=/var/application.prod.conf` doesn't supply play with the correct DB credentials stored in application.prod.conf, as suggested here: https://www.playframework.com/documentation/2.3.x/ProductionConfiguration#Specifying-alternative-configuration-file

Play attempts to connect to the DB using the default password of "changeme" from the version of application.conf you keep checked into version control.

**Comment by jroper** [comment]
What about `activator -Dconfig.file=/var/application.prod.conf test`?

**Comment by fxer** [comment]
Same issue unfortunately. does the 'activator' command not take the same parameters as running the '/project/target/universal/stage/application -Dconfig.file=/var/application.prod.conf' does?

**Comment by marcospereira** [comment]
Which version of activator are your using?

**Comment by fxer** [comment]
Originally 1.3.2, just upgraded to 1.3.5 but having the same problem

**Comment by marcospereira** [comment]
Could you please try with `sbt -Dconfig.file=/var/application.prod.conf test` and tell us if it works? So we can see if it is a problem with Play or activator.

**Comment by fxer** [comment]
Hmm its not in my path, how do I run from sbt directly? I've got the activator-minimal package and a play 2.3 project

**Comment by fxer** [comment]
Same issue passing other parameters, like a custom java keystore:

`/opt/activator/activator -Djavax.net.ssl.trustStore=/tmp/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit test`

**Comment by PromanSEW** [comment]
Activator was replaced by SBT long time ago, this issue can be closed
