### ISSUE TITLE
JsObject ++ (String, Json.JsValueWrapper)*

### ISSUE THREAD

**Issue by cchantep** [playframework/playframework#4747]
Allows to add 0 or n fields to an existing JsObject, without having to prior create a second object to be merged with the first one.

```scala
val obj = Json.obj("foo" -> "bar")

obj ++ ("lorem" -> 2/*, "ipsum" -> 2.3*/)
```

**Comment by gmethvin** [comment]
I like this but it is inconsistent with other collection types, where `++` accepts a container type instead of being varargs. I can see adding something like
```scala
obj ++ Seq("lorem" -> 2, "ipsum" -> 2.3)
```
and this should work for any type of iterable.

**Comment by gmethvin** [comment]
Another syntax I like is
```scala
obj.copy("lorem" -> 2, "ipsum" -> 2.3)
```
We can use a name other than `copy` but I can't think of a better name.

**Comment by cchantep** [comment]
I'm not fond of `copy` syntax, which doesn't make it explicit that fields are added. I don't really see an issue with `++`, first as `JsObject` is not a collection type (even if based on) and then varargs is a convenient way to pass a `Seq`.

**Comment by gmethvin** [comment]
@cchantep I've just never seen the convention of defining a `++` method as varargs, so it seems inconsistent with other Scala libraries I've seen. I would be okay with adding another variant of `+` for doing this, though:
```scala
obj + ("lorem" -> 2) // already works
obj + ("lorem" -> 2, "ipsum" -> 2.3/*,"dolor" -> 3*/) // works with new `+`
```
This is consistent with the behavior of scala `Map`, which `JsObject` is based on.

**Comment by gmethvin** [comment]
We also might want to make that method accept `(String, JsValueWrapper)` arguments so it works like `Json.obj`.

**Comment by cchantep** [comment]
Right, that's what I had in mind but miswrite in the issue title.
