### ISSUE TITLE
Cleanup of FLASH cookie prevents other cookies from being set (e.g., CSRF token)

### ISSUE THREAD

**Issue by seantbrady** [playframework/playframework#4753]
*Description*
Cleanup of FLASH cookie prevents other cookies from being set (e.g., CSRF token)

*How to Reproduce*
1. Run sample app: https://github.com/seantbrady/play-flash-sample
2. Go to http://localhost:9000/ and observe HELLO cookie is set
3. Clear cookies
4. Go to http://localhost:9000/setflash which sets a flash cookie and redirects to http://localhost:9000/
5. Observe HELLO cookie is NOT set when it should be

**Comment by jroper** [comment]
I'm surprised we don't have a test for that... and I think there was a similar issue reported a while ago that we fixed...
