### ISSUE TITLE
should add removeAll to cacheApi

### ISSUE THREAD

**Issue by hepin1989** [playframework/playframework#4757]
I think it's needed.some time I just want to invalidate the cache.

**Comment by AliMoradian** [comment]
I agree that it's needed. I think for now you might be able to use this workaround:

        String CACHE_NAME = "play";
        CacheManager cacheManager = CacheManager.create();
        Ehcache ehCache = cacheManager.getCache(CACHE_NAME);
        ehCache.removeAll();

**Comment by hepin1989** [comment]
yeah,thanks,I used a actor to track all the cached key and then listen on the CacheNeedInvalidate Event.not that nice:)

**Comment by gmethvin** [comment]
Adding a `removeAll` method to `CacheApi` means all implementations need to support it. In the case of `EhCache` that might be relatively cheap to do, but that's not the case for all caches.

Memcached for example has no easy way to clear all keys with a given prefix, so it usually makes more sense to include a version number in your key that you can change when you want to "invalidate" the cache.

**Comment by kostaskougios** [comment]
I also think a flush() method should be provided, it is required i.e. when there is an offline database update and live servers must be notified and flush caches.

Regarding memcache not supporting it, there is no reason why different caches can't support different functionality, i.e. 
cache match {
case cacheWithFlush:FlushCapability => cacheWithFlush.flush()
...
}
