### ISSUE TITLE
Register with Coverity

### ISSUE THREAD

**Issue by kravietz** [playframework/playframework#4761]
Hi, I think it would make sense to register Play Framework with https://scan.coverity.com/ which offers a free code quality and security scans for open-source projects. I've been using it for some of my open-source projects with pretty good results. The registration is simple but requires someone who does commit to the project to complete it.

**Comment by jroper** [comment]
I'd like to see what it looks like before adding it to the project.  If you can demo it working on a fork of Play, then we can evaluate to see if it a) will work with Play, and b) give us value.

**Comment by kravietz** [comment]
@jroper I'm not in any way related to Coverity, just using it for my own projects. I'm also using Play and think it's quite a good opportunity to have the project scanned with one of the leading scanners for free. I tried to set up a project for Play fork, but then realized that it does not make much sense as the onboarding process is non-trivial  and not fully automatic (Coverity does per-project review and manual approval before enabling the scanner) so if you later consider it useful, you'd need to repeat the whole process. What we could do is I just create some trivial Pull Request (documentation improvements) and this way become a contributor to Play, which should be sufficient to register the project and then I can transfer all the ownership to you.

**Comment by jroper** [comment]
@kravietz I didn't realise it would take so much to setup.  My biggest concern then is if the effort is that great, then the effort to maintain it may also be just as great.

**Comment by kravietz** [comment]
As with every source code scanner the main operational effort is to browse and triage the reported issues. Coverity seems to be quite cautious as it comes to reporting false positives so I haven't seen any "best practice violations" report that typically inflate reports of other scanners. I granted you access to my projects so you can have a look & feel.

**Comment by wsargent** [comment]
Coverity Scan doesn't cover Scala.  Closing.
