### ISSUE TITLE
jodaDate not accepting all joda date time patterns

### ISSUE THREAD

**Issue by Christewart** [playframework/playframework#4767]
I'm having an issue with forms binding different datetimes from a POST from a webpage. Here is the stackoverflow question that I have posted about it: 

https://stackoverflow.com/questions/31034902/joda-datetime-handle-both-acronym-and-explicit-timezones

I'm using Scala Play 2.3.x

**Comment by cchantep** [comment]
Please ask such question on SO (as your link) or on the user MailingList. A ticket can be then filed if an issue is confirmed. Best regards.
