### ISSUE TITLE
[2.4] Evolutions interface not work

### ISSUE THREAD

**Issue by marcosinigaglia** [playframework/playframework#4773]
Hi, I upgraded a project from play 2.3 to 2.4, now in development the evolutions pages don't work.
If I use play.evolutions.autoApply everything is ok but if I use the web interface the button does nothing and I have a redirect to the same page. The button's link is http://localhost:9000/@evolutions/apply/default and there are no errors on console (except the play.api.db.evolutions.InvalidDatabaseRevision).
Thanks.

**Comment by cchantep** [comment]
Hi @larcosinigaglia , to get more help for such question, please ask it on the [user MailingList]( https://groups.google.com/forum/m/#!forum/play-framework) first. Then if an issue is confirmed, an actionable ticket can be then reported on this tracker. Best regards.

**Comment by pan5431333** [comment]
Hi, I've encountered the same issue. Could you tell me how you solved it? Thanks!

**Comment by marcosinigaglia** [comment]
Hi, I don't remeber, try to disable all the handlers for the errors.
