### ISSUE TITLE
In which order are callbacks added to the stop hook called?

### ISSUE THREAD

**Issue by julienrf** [playframework/playframework#4785]
The current implementation is to call them in the reverse order they have been added. Is this an implementation detail? Can applications rely on this property? If so, the documentation should be updated to mention it.

**Comment by jroper** [comment]
From the [scala](https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.inject.ApplicationLifecycle) and [java](https://www.playframework.com/documentation/2.4.x/api/java/play/inject/ApplicationLifecycle.html) api docs:

> Stop hooks are executed when the application is shutdown, in reverse from when they were registered.

**Comment by julienrf** [comment]
Oh, indeed. I only looked at the addStopHook method documentation, not the class.

Another question: maybe we should publicly expose a Future that is resolved after the application is stopped?

**Comment by jroper** [comment]
What's the use case for that?

**Comment by julienrf** [comment]
Hi, see this thread: https://groups.google.com/d/msg/play-framework/JTzI8CFPxQ0/ievuFz91-6QJ

**Comment by wsargent** [comment]
The order of stop hooks is documented, so this can be closed.
