### ISSUE TITLE
Should fail on evolutions script without ups section declared correctly.

### ISSUE THREAD

**Issue by ghost** [playframework/playframework#4793]
I had improperly created an evolutions script (48.sql) in my project where I accidentally left the hash off of Ups.

``` --- !Ups```

The application ran fine, all tests worked, but after adding another evolution file (49.sql), it attempted to run 49.sql's Ups section twice which caused an error stating the relation I was attempting to create already existed. I would propose having the evolutions fail if there is no Ups section declared inside the file.

Sample Evolutions to trigger it:

1.sql
```
 --- !Ups
create table my_table (
  id  bigint not null,
  constraint pk_my_table primary key (id)
);

# --- !Downs
drop table if exists my_table;
```

2.sql
```
# --- !Ups
create sequence my_table_seq;

# --- !Downs
drop sequence if exists my_table_seq;
```

I would suggest treating the lack of a properly defined Ups section as a failure just as though a SQL exception had been thrown.

**Comment by cchantep** [comment]
Closing for now, an up-to-date ticket could be created if an issue is confirmed on master (after discussion on the MailingList). Best regards.
