### ISSUE TITLE
2.4.1-Java JsHint not running

### ISSUE THREAD

**Issue by adis-me** [playframework/playframework#4801]
Hi,

According to the documents all javascript files present in `app/assets/**/*/js` should be processed by jshint on every browser refresh, or at least when something changes. I have one javascript file inside `app/assets/javascripts/app.js` with some wrong code.

When I paste the content of this file on jshint.com I get three errors, but Play is not barking at me for these errors. In the `plugins.sbt` the jshint is included by:

     addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.3")

Also when I add this task in the Asset pipeline in my build.sbt with the following line:

     pipelineStages in Assets := Seq(jshint)

I get the following error on `./activator clean run`:

    pipelineStages in Assets := Seq(jshint, cssCompress)
                                ^
    [error] Type error in expression
    Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 

But the strange thing is that I see the following lines in the terminal, looks like it ran jshint?!

    [info] LESS compiling on 4 source(s)
    [info] JavaScript linting on 2 source(s)
    [info] Compressing file lib/bootstrap/css/bootstrap.css

**Comment by marcospereira** [comment]
You don't need to *scope* the configuration to `Assets`. From [assets docs](https://www.playframework.com/documentation/2.4.x/Assets#Reverse-routing-and-fingerprinting-for-public-assets):

```scala
pipelineStages := Seq(rjs, digest, gzip)
```

Also @adis-me , do you mind discuss these issues  first on the [user mailing list](https://groups.google.com/forum/m/#!forum/play-framework)? If we confirm that there is an error with Play, than we can open an issues here. ;-)

Thanks.
