### ISSUE TITLE
2.4.1-Java Less Compilation is not running automatically

### ISSUE THREAD

**Issue by adis-me** [playframework/playframework#4802]
In the [documentation](https://www.playframework.com/documentation/2.4.x/AssetsLess#Using-LESS-CSS) you can read the following:

> For example, a LESS source file at app/assets/stylesheets/main.less will be available as a standard resource at public/stylesheets/main.css. Play will compile main.less automatically.

This is not true, I think, because for me this is not working. I have to manually put this in the `build.sbt`:

    // What to include when running Assets task
    includeFilter in (Assets, LessKeys.less) := "*.less"

Is the documentation wrong is this not working as intended?

**Comment by marcospereira** [comment]
None? This is included in the docs:

https://www.playframework.com/documentation/2.4.x/AssetsLess#Working-with-partial-LESS-source-files

Even the section in mention has information about this:

> For example, a LESS source file at app/assets/stylesheets/main.less will be available as a standard resource at public/stylesheets/main.css. Play will compile main.less automatically. **Other LESS files need to be included in your build.sbt file**:
> 
>     includeFilter in (Assets, LessKeys.less) := "foo.less" | "bar.less"

Anyway, if you think this could be more clear, could you please submit a pull request to add more comprehensive examples? You just need to edit this documentation page:

https://github.com/playframework/playframework/blob/master/documentation/manual/detailedTopics/assets/AssetsLess.md
