### ISSUE TITLE
Outdated documentation for Heroku deployment.

### ISSUE THREAD

**Issue by Norpadon** [playframework/playframework#4804]
https://www.playframework.com/documentation/2.4.x/ProductionHeroku

I followed all instructions and got error "Configuration error: Configuration error[Cannot connect to database [default]]".
It took two days to find out that it is a bug somewhere in old Postgres driver. It was fixed in newer versons (currently I'am using 9.4-1201-jdbc41, which was moved from "postgres" to "org.postgres" group). But documentation still suggests using "postgresql" % "postgresql" % "9.1-901-1.jdbc4".

**Comment by marcospereira** [comment]
Thanks, @Norpadon. Do you mind submitting a pull request to fix this? You just need to edit this file:

https://github.com/playframework/playframework/blob/master/documentation/manual/detailedTopics/production/cloud/ProductionHeroku.md

**Comment by Norpadon** [comment]
@marcospereira this file is already OK, history says it was fixed 8 days ago, but information on playframework.com is stiil outdated.

**Comment by marcospereira** [comment]
Ok. This change was not backported to branch 2.4.x, that is why you are not seeing it in playframework.com. Looks like this was actually my fault, since I did merge the PR (#4760) which fixed the docs, but forgot to backport the change.

**Comment by marcospereira** [comment]
Backport done here: 71cf13f
