### ISSUE TITLE
Play 2.3.x + JPA + Hibernate - problem with the current model - documentation improvement perhaps?

### ISSUE THREAD

**Issue by joantune** [playframework/playframework#4805]
Hi All!

So, I'm writing this because I think that at the very least a warning or a paragraph on Play's documentation might be useful and save future problems for other users.

Also, please do correct me if my expectations were wrong from the start.

 So the problem that I found was:

While running a block of code that basically processed events ( it's an EventSourcing system), like so:
```
 do {
  JPA.withTransaction(new F.Callback0() {
  [Processing of events]
});
} while(thereAreStillEvents())
```

Which I did to make sure that the app wouldn't break if the number of events got too big to fit in memory, I ran into a big problem. The problem was that the processing relied on the previously processed values, and when I closed and opened the transaction (in the same thread) the values had changed, i.e. they were not the same ones that were on the database.

Was this silly of me to expect? Originally I thought that I would get away with this because I was in the same thread, and the persistence mechanism knew about the changes that I just made. But to be honest I never digged enough on Hibernate's documentation to be quite sure about it.

 Still I think that this is the default expectation, thus I think that the docs should add a note about this.

Another thing was, while trying to solve this problem, I ran into another issue whose source is still not clear to me, I tried using Pessmistic Locking by setting ```db.default.isolation=SERIALIZABLE``` but oddly enough to no avail!

Currently, I do something like:

```
try {
 JPA.withTransaction(new F.Callback0() {
 do {
    if (JPA.em().getTransaction().isActive() == false) {
           JPA.em().getTransaction().begin();
      }

  [Processing of events]
 JPA.em().flush();
 JPA.em().clear();
 JPA.em().getTransaction().commit();
} while(thereAreStillEvents())
});
} catch (RuntimeException e) {
                    if (e.getCause() instanceof IllegalStateException) {
// we could further check here the message to make sure that the problem is that we are calling JPA.getTransaction().commit on a transaction who is not active i.e. JPA.getTransaction().isActive == false
                    } else {
                        throw e;
                    }
```
which works. So, obviously this would be avoided from the start if we reused the same entity manager throughout the same thread, although I'm not sure about its feasibility. Two things are certain, the alternative is very ugly, and the ```db.default.isolation=SERIALIZABLE``` not working is very strange..

**Comment by jroper** [comment]
@joantune it would be better to ask questions like this on the mailing list, please discuss there rather than replying here.

`withTransaction` will commit the transaction for you (and flush, etc), if you then load the objects again in a new transaction after the first one, you should see the updates.  If you're not, there may be some caching, maybe you're reading stale objects, or maybe you are updating detached objects that aren't being persisted.  I'm not sure why, but it's likely got nothing to do with Play.
