### ISSUE TITLE
[Play 2.4.2 Java] Option for applying evolution script in dev-mode not offered when using Guice & Ebean

### ISSUE THREAD

**Issue by cdraeger** [playframework/playframework#4808]
I'm in the process of migrating from Play 2.3 to 2.4. I am using Ebean ORM, had Guice DI set up in my `Global`, and was also inserting some rows into a table programmatically in `GlobalSettings.onStart`.

As stated in the [documentation](https://playframework.com/documentation/2.4.x/GlobalSettings), I got rid of the `Global` (specified my Guice modules in application.conf), and also moved the database interaction from `onStart()` to the constructor of an injected service as suggested.

When running the application in dev-mode I now get 2 errors, the first being an unexpected `SQLException` that the table I am inserting into (in the constructor of my injected service) does not exist. The second error is that my database needs evolution.

From my understanding, I should be offered to apply the evolution script before any database interaction occurs. This was working fine when I had the database-interaction in the `GlobalSettings.onStart` method. The only way to get my app running now is to use `play.evolutions.db.default.autoApply=true` in my application.conf. Then, everything seems to work just fine.

The errors:
```
CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, javax.persistence.PersistenceException: Query threw SQLException:Table "ROLE" not found

2) Error in custom provider, @6mkkdagnm: Database 'default' needs evolution!
  while locating play.api.db.evolutions.ApplicationEvolutionsProvider
  at play.api.db.evolutions.EvolutionsModule.bindings(EvolutionsModule.scala:22)
```

**Comment by jroper** [comment]
This should be documented, but isn't, if you want to depend on the evolutions being run, then you need to add a dependency on the thing that runs the evolutions to your component.  That thing is `play.api.db.evolutions.ApplicationEvolutions`.

**Comment by cdraeger** [comment]
Ok I tried that, but it doesn't seem to work. Let me clarify what I'm doing with code, maybe I didn't get you right.

In a module, I am binding a service-class:
```java
bind(MyService.class).asEagerSingleton();
```

In the constructor of this class, I am inserting some values into the database programmatically if required (happens only once at app start because of the eager-singleton binding):
```java
public class MyService {

  @Inject
  public MyService(Environment environment, ApplicationEvolutions applicationEvolutions, DbRepository dbRepository) {
    this.environment = environment;
    this.applicationEvolutions = applicationEvolutions;
    this.dbRepository = dbRepository;

    // applicationEvolutions.start() --> doesn't change anything
    insertMissingValuesIntoDb();
  }
}
```

Doing this without injecting the `ApplicationEvolutions` results in the problem first described in this issue. Doing it with your suggestion still results in two errors, but this time both Evolution exceptions:
```
Error in custom provider, @6ml2bgfcc: Database 'default' needs evolution!
  while locating play.api.db.evolutions.ApplicationEvolutionsProvider
  at play.api.db.evolutions.EvolutionsModule.bindings(EvolutionsModule.scala:22):
```

However, I still don't get the option to apply evolutions in the browser, just the unexpected "CreationException: Unable to create injector" error. Adding `applicationEvolutions.start()` before db operations doesn't change that. Another problem I see with this is that I would have to do this in a redundant way in every injected component relying on database evolutions, it complicates instantiating the service for unit tests etc.

**Comment by jroper** [comment]
Ok, the `CreationException` not being detected as a need for the evolutions to be applied is a bug.

**Comment by cdraeger** [comment]
Ok thanks good to know.

Am I right in assuming that injecting `play.api.db.evolutions.ApplicationEvolutions` in my component is not necessary then? Like I said, I would want to avoid that for above reasons. If the `CreationException` is caught first I should be able to apply evolutions manually before the database code is reached, because this is what happens when I activate `autoApply`, it works fine then.

**Comment by jroper** [comment]
It's necessary, but Play should be unwrapping the creation exception to find the evolutions exception, and rendering the evolutions page as a result.  It uses that exception to know whether it should render the apply evolutions page.

**Comment by oexza** [comment]
i'm having this same issue, is there a work around before its fixed?

**Comment by cdraeger** [comment]
@oexza Put `play.evolutions.db.default.autoApply=true` in your `application.conf`. That works for me (although I would prefer to apply evolutions manually in dev mode, which should be possible again once it's fixed).

**Comment by keepscoding** [comment]
+1

**Comment by TigranTsat** [comment]
Is there fix planned? I also ran into it. Applying evolutions manually in dev mode is really convenient.

**Comment by gkteck** [comment]
I am seeing the same issue, the thing is this works fine with the play in-build netty server.
Only the issue comes to light, When the war file is crated --> deployed in tomcat.

**Comment by neowinx** [comment]
Happy holidays everyone! :santa:

Bumping this since I would like it to be fixed too. Not an real issue though, but as @cdraeger says in dev mode it's a plus that everyone gets a big red message when evolutions have been added to the codebase.

Regards

**Comment by greenled** [comment]
Hi. Happy new year. Any progress on this?

**Comment by mkurz** [comment]
@jroper I think about to provide a PR. Could you advice me how and where to fix this exactly?

**Comment by mkurz** [comment]
Could someone provide a test project which reproduces the bug?

**Comment by mkurz** [comment]
Opened #5541 to fix this issue. Did test and can confirm it fixed the bug.
