### ISSUE TITLE
[Play 2.4 Java] Ability to specify a test-database with the GuiceApplicationLoader

### ISSUE THREAD

**Issue by cdraeger** [playframework/playframework#4809]
Maybe I just haven't wrapped my head around this yet, but I'm confused about how to specify a database when using the `GuiceApplicationLoader` for tests.

As suggested in the [documentation](https://www.playframework.com/documentation/2.4.x/JavaFunctionalTest), I want to get rid of the `Helpers.fakeApplication()` calls. Currently with Play 2.3 I am doing this:

``` java
running(fakeApplication(inMemoryDatabase(), testGlobal), () -> {
  // test here
});
```

I just switched to the proper implemenation for Guice DI, and since I didn't know any other way specified a database by overriding the config:

``` java
Application application = new GuiceApplicationBuilder()
        .configure("db.default.url", "jdbc:h2:mem:test")
        .overrides(bind(Component.class).to(MockComponent.class))
        .build();

running(application, () -> {
  // test here
});
```

I don't know if this is as intended.. honestly I would have expected convenience builder-methods, like so:

``` java
Database database = Databases.inMemory();
// Evolutions.applyEvolutions(database); --> should probably happen automatically?
Application application = new GuiceApplicationBuilder()
        .with(database)
        .overrides(bind(Component.class).to(MockComponent.class))
        .build();
```

Or maybe I'm just doing this wrong? I can't always use the `FakeApplication` like before because I need to override bindings.

**Comment by jroper** [comment]
One way to do it should be:

```java
Application application = new GuiceApplicationBuilder()
        .configure(Helpers.inMemoryDatabase())
        .overrides(bind(Component.class).to(MockComponent.class))
        .build();
```

However, this doesn't work, because `inMemoryDatabase` returns `Map<String, String>`, while `configure` expects `Map<String, Object>`.  So, we should modify `configure` to expect `Map<String, ? extends Object>`.  As a work around, you can do this:

```java
Application application = new GuiceApplicationBuilder()
        .configure((Map) Helpers.inMemoryDatabase())
        .overrides(bind(Component.class).to(MockComponent.class))
        .build();
```

The other way to achieve this is to do this:

```java
Application application = new GuiceApplicationBuilder()
        .overrides(
            bind(Database.class).to(Databases.inMemory()),
            bind(Component.class).to(MockComponent.class)
        ).build();
```

The only gotcha with that one is that evolutions won't be applied, so that may be a problem if you're using evolutions.

Do either of those two solutions work for you?

I'll keep this issue open to fix the signature of `configure`.

**Comment by cdraeger** [comment]
Thanks @jroper for your suggestions. Solution 1 with the workaround seems to work just fine: `configure((Map) Helpers.inMemoryDatabase())`. Of course I get an 'unchecked assignment' warning, so fixing the signature of `configure` would be appreciated (and maybe mentioning this possibility in the testing documentation).

I really like your second idea since this seems to be more flexible, I didn't know about the binding to `Database`. It doesn't work your way (because I can't bind to an instance via `bind()`), but this works:
```java
Database database = Databases.inMemory();

// in a util-class
public static Application getDefaultApplicationWithTestDb(final Database database) {
    return new GuiceApplicationBuilder().overrides(new Module() {
      @Override
      public void configure(Binder binder) {
      }

      @Provides
      public Database provideDatabase() {
        return database;
      }
    }).build();
  }
```

There are problems with it though, just not as expected:
1. Evolutions apparently are applied using this database in a live application via `Helpers.running()`. But, manually controlling that e.g. via `Evolutions.cleanupEvolutions(database)` does not seem to have any effect, even if I am building a new application with that database.
2. The database stays in memory for the test-run, even if I instantiate a new one for every test. This is a problem when I need to start tests with an empty database, and since I can't control evolutions as explained in point 1 (maybe the two points are related), unfortunately I don't see a work-around.

**Comment by jroper** [comment]
Ah, this one should work:

```java
Application application = new GuiceApplicationBuilder()
        .overrides(
            bind(Database.class).toInstance(Databases.inMemory()),
            bind(Component.class).to(MockComponent.class)
        ).build();
```

If you want a new in memory database for every test, make sure you close the database after the test, eg:

```java
database.shutdown();
```

As for evolutions, could you post some example code showing the problem?  Or put an example project on GitHub?

**Comment by cdraeger** [comment]
Ah ok, `toInstance` it is of course, thanks that's cleaner. As for the rest.. I'm confused now. I set up a demo project to demonstrate my problems: https://github.com/cdraeger/play-test-db-sscce

When I first ran the `DemoTest1` Test, it failed as it does for my main project: the database persisted in memory across tests and I got the `javax.persistence.PersistenceException: Unique index or primary key violation`. After some more playing around, the same tests succeeded and behaved as you said they would. I don't get it.

The Ebean tests worked from the get-go in the above sample-project. But doing the same in my main project consistently doesn't work, the tests fail there because the database persists in memory. Even if I add `database.shutdown`, it just won't work. Unfortunately I can't tell you anything else right now. So, I'm lost.. I'm afraid there's not much you can do without any more info. What you said works in the sample but not in my main project, I don't see a difference in what I'm doing here and there.

**Comment by cdraeger** [comment]
@jroper I think I found the problem. When I'm creating an application with the `GuiceApplicationBuilder`, and I'm overriding the `Database.class` dependency like this, then the default database configured in the `application.conf` is still being used by injected services in that application!

I just realized that by switching to Postgres. I have dev-database configured as 'default' in `application.conf`, and a test database that I only use for tests:
```java
public class Demo {

  public final Database database;

  public WithDatabase() {
    database = Databases.createFrom(
        "org.postgresql.Driver",
        "jdbc:postgresql://localhost/test-db",
        ImmutableMap.of("username", "tester")
    );
  }

  @Before
  public void setUp() {
    Evolutions.applyEvolutions(database);
  }

  @After
  public void cleanUp() {
    Evolutions.cleanupEvolutions(database);
    database.shutdown();
  }
  
  @Test
  public void test() {
    final Application application = new GuiceApplicationBuilder()
        .overrides(bind(Database.class).toInstance(database))
        .overrides(bind(Component.class).to(MockComponent.class))
        .build();
    running(application, () -> {
      // this service still uses the `default` database from application.conf
      final MyService myService = application.injector().instanceOf(MyService.class); 
    });
  }
}
```

Above test ignores the overridden `Database.class` dependency and writes into the dev-database. I guess I could just overwrite the config and make my test-database the default there, but that means your solution is not working. Is that as intended?

**Comment by schmitch** [comment]
@cdraeger I think he meant that you Component should also be mocked, currently my company makes two test types, one with a test database and one without inside the mocked tests we have things like:

```
    public GuiceApplicationBuilder getBuilder() {
        GuiceApplicationBuilder builder = new GuiceApplicationBuilder();
        return builder
            .disable(play.db.DBModule.class)
            .disable(play.api.db.DBModule.class)
            .bindings(bind(play.api.db.DBApi.class).to(DummyScalaDBApi.class))
            .bindings(bind(play.api.db.Database.class).to(DummyScalaDatabase.class))
            .bindings(bind(play.db.Database.class).to(DummyJavaDatabase.class))
            .configure("envisia.path", folder.getRoot().toString());
    }

    public Application provideApplication() {
        return getBuilder().build();
    }
```

Then you have a function to generate a builder. Now write a test with:
```
    DeviceDao dd = mock(DeviceDao.class);
    CategoryDao cd = mock(CategoryDao.class);
    AdditionalDao ad = mock(AdditionalDao.class);

    @Override
    public GuiceApplicationBuilder getBuilder() {
        GuiceApplicationBuilder builder = super.getBuilder();
        setUp();
        return builder.overrides(bind(DeviceDao.class).toInstance(dd), bind(AdditionalDao.class).toInstance(ad),
            bind(CategoryDao.class).toInstance(cd));
    }
```

Now you could easily mock out everything:

```
when(cd.getCategory(1L)).thenReturn(new Category(1L, "HelloWorld"));
Call url = controllers.routes.MySuperController();
        Http.RequestBuilder rb = fakeRequest(url);
        assertEquals(Http.Status.OK, route(rb).status());
```

et voìla.

So you could write really fast tests without *EVER* touching the database.

However you should still write integration tests against a test database here we override with:

```
        return builder
            .configure("envisia.path", folder.getRoot().toString())
            .configure("db.default.url", databaseUrl)
            .build();
```

Currently database URL is either a Environment Variable (which could be set easily inside the IDE or a default string like "jdbc:postgresql://localhost/local_test" which every developer could use as his test database. And our testservers could easily override it.

**Comment by davidonlaptop** [comment]
What if we want to load the default database from the application.conf (e.g. a non in-memory database) ?

Something like this:
```
        Application app = new GuiceApplicationBuilder()
                .load( new DBModule() )
                .build();
```

This snippet fails with these errors:
```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for play.api.db.ConnectionPool was bound.
  while locating play.api.db.ConnectionPool
    for parameter 0 at play.db.DefaultConnectionPool.<init>(DefaultConnectionPool.java:24)
  at play.db.DBModule.bindings(DBModule.java:34):
Binding(interface play.db.ConnectionPool to ConstructionTarget(class play.db.DefaultConnectionPool)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

2) No implementation for play.api.db.DBApi was bound.
  while locating play.api.db.DBApi
    for parameter 0 at play.db.DefaultDBApi.<init>(DefaultDBApi.java:27)
  at play.db.DBModule.bindings(DBModule.java:35):
Binding(interface play.db.DBApi to ConstructionTarget(class play.db.DefaultDBApi)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
```

**Comment by bravegag** [comment]
I am on Play 2.5.10 and have the same problems. This is a common use case and the solution is very obscure with tons of runtime errors on the way. This is my particular use-case:

- I have one Postgres default database configured in application.conf
- I have two evolutions scripts 1.sql and 2.sql. 1.sql can be applied np to Postgres or H2 in PostgresQL mode whereas 2.sql is Postgres prop only.
- Therefore I have tried defining in an application.test.conf a test H2 database so that evolutions will pick the evolutions/test path but then it wants to load default too. So I disable it but then I can't override Guice builder to pick up test and then a myriad of troubles and documentation is useless etc etc 
- I then try using inMemoryDatabase but evolutions wont be applied ... total frustration.

**Comment by wsargent** [comment]
Possibly relevant blog post: http://www.pmatiello.me/2014/12/using-a-different-configuration-file-when-running-tests-in-a-play-project.html

**Comment by bravegag** [comment]
@wsargent Thank you! yes I was using that already ... at the end I gave up on employing H2 for testing and simply use Postgres for test/dev/prod and it is anyway not really a bad idea because H2 requires having a somehow different setup.
