### ISSUE TITLE
Play 2.4 JavaI18N Scala Messages within Template not recognising language change

### ISSUE THREAD

**Issue by archie-sh** [playframework/playframework#4814]
We use one application server for different domains one .de and one .com for example. Inside a RequestHandler we get the request host and then change the language for the user accordingly, the following is a sample gist https://gist.github.com/archie-sh/7336e568624ed9a08f04 

After the language has been changed if we use the Scala Messages object within the template the language change is not applied. If we use Java's play.i18n.Messages then the language change is applied. The code is migrated from play 2.3 and changing the language always worked before.

**Comment by jroper** [comment]
Please ask about this on the mailing list.  I suspect you are not passing an implicit `Messages` class.
