### ISSUE TITLE
No error or warning when trying to including non-existing file in configuration file

### ISSUE THREAD

**Issue by kmatheussen** [playframework/playframework#4815]
I.e.
```
include "/nothing/here"
```

Play 2.4.2

**Comment by cchantep** [comment]
Hi, please note that this is on purpose, and is described in the [documentation](https://www.playframework.com/documentation/2.4.x/Configuration#Include-semantics:-missing-files). 

To get helped or discuss of such behaviour, the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework) is the place to go, rather than this issue tracker.

Best regards

**Comment by kmatheussen** [comment]
Thank you. I think it would make more sense if you introduced a new keyword, like "include_but_may_not_exist" (just an example), if the file may not exist though.

**Comment by cchantep** [comment]
The [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) must be used to discuss about new feature (not this issue tracker, as indicated in the [contribution guidelines](https://github.com/playframework/playframework/blob/master/CONTRIBUTING.md)). Best regards.

**Comment by kmatheussen** [comment]
I agree, but this seemed like an obvious bug. Actually, I think this is quite a dangerous behavior. If the file for some reason, deleted by accident, etc., is not available, there's a large chance you wouldn't notice. Can't think of a very good example right now - upload file limit is one example that wouldn't be noticed - but there's probably worse things that could happen. Sorry about discussing it here, and thanks for the quick and polite replies.

**Comment by jroper** [comment]
@kmatheussen This actually isn't related to Play, it's related to the Typesafe config library, you may be interested in following this issue:

https://github.com/typesafehub/config/issues/121
