### ISSUE TITLE
[Play 2.4.2 scala] Unable to include configuration files in other directories

### ISSUE THREAD

**Issue by kmatheussen** [playframework/playframework#4816]
i.e.

```
include /tmp/hello.conf
```

doesn't work.

**Comment by mkurz** [comment]
Hello @kmatheussen, do you mind discuss that first on the [user mailing list](https://groups.google.com/forum/?fromgroups#!forum/play-framework)? If we confirm that there is an error with Play, than we can open an issue.

Thanks!

About you the problem you are running into:  As far as I know a file that gets included in the config should be on the classpath. Abviously `/tmp/hello.conf` probably isn't.
Hower you can also include files which are not on the classpath like this:
```
include file("/tmp/hello.conf")
```

**Comment by kmatheussen** [comment]
Thank you, using "file" worked. I'll ask on the user mailing list next time. However, this worked in 4.3 (at least when accessing a file in a relative path (i.e. "../../somewhere/something.conf"), and since this issue was not mentioned in the play 2.4 upgrade guide,  I thought it was a bug.
