### ISSUE TITLE
[Play 2.4.2 Java] Must manually create `conf` subdirectory when running in HTTPS production mode

### ISSUE THREAD

**Issue by fushar** [playframework/playframework#4820]
Due to the workaround in #4590, the `conf` subdirectory in the directory produced by `dist` task is now gone. But, if we run the executable in HTTPS, it needs to create a file inside the `conf` directory:

    xxxx-xx-xx xx:xx:xx +xx00 - [INFO] - from play.core.server.ssl.FakeKeyStore in New I/O server boss #5
    Generating HTTPS key pair in XXX/conf/generated.keystore - this may take some time. If nothing happens, try moving the mouse/typing on the keyboard to generate some entropy.

My workaround is to manually create the `conf` directory, otherwise the executable can't run.

Please fix this, maybe by creating the `conf` directory when needed if it is not present.

**Comment by jroper** [comment]
You should **not** be using the generated key store and self signed certificate in production.  If anything, we should change Play to fail to start at all if you're running in prod mode with https enabled and you haven't configured the keystore and certificate, this would prevent users from making serious security mistakes like the one you're making.

**Comment by dragoon20** [comment]
If we used nginx as reverse proxy to handle the https negotiation, can we just used the self signed certificate anyway?

**Comment by jroper** [comment]
If you use a reverse proxy to handle https, then you don't need to enable https in the Play app, just enable http and have the reverse proxy talk http to the Play app, unless you want secure communications between the Play app and the reverse proxy.  If you want secure communications between the Play app and the reverse proxy, then a self signed certificate is fine, but having the Play app generate the key and the certificate for you is not, since you'll need to configure nginx to trust Play certificate first.

**Comment by fushar** [comment]
The thing is, our app needs to send an absolute URL of one of its pages to another party. We used `play.mvc.Call.absoluteURL(request(), request().secure())`, which will return the URL in http (which is unintended) if the Play app does not enable https.

**Comment by marcospereira** [comment]
@fushar I don't think this is true. When configured to do [ssl termination](https://www.nginx.com/resources/admin-guide/nginx-ssl-termination/) and to communicate with Play using HTTP, if you pass the proper [`scheme`](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_scheme), Play will recognize this and generate the absolute urls using that scheme. See the `proxy_set_headers` directives recommended when [setting up Play with nginx](https://playframework.com/documentation/2.4.x/HTTPServer#Set-up-with-nginx).

**Comment by dragoon20** [comment]
@marcospereira Can you show me the code that parse the http or https request into RequestHeader class in play framework? I try to search and traverse to this file: https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala

I have tried to pass the scheme using https to the play server handling http but request().secure() seems to always return false.

**Comment by fushar** [comment]
@marceloemanoel Sorry, you are right. This is resolved. The problem was in our nginx config, we did `proxy_pass` to  `https`. Changing that to `http` solved the problem. Thank you!
