### ISSUE TITLE
[Play 2.4 Scala] withBody method no longer has implicit ContentTypeOf

### ISSUE THREAD

**Issue by Hayena** [playframework/playframework#4828]
During a upgrade of one of our libraries to Play 2.4 we noticed that the `withBody` method on the `WSRequestHolder` trait no longer has a implicit `ContentTypeOf` field. We could use the `withHeader` method to set the `Content-Type` header but the `withBody` method already has functionality to set the header.

**Comment by marcospereira** [comment]
Hello @Hayena, do you mind discuss that first on the [user mailing list](https://groups.google.com/forum/m/#!forum/play-framework)? If we confirm that there is an error with Play, than we can open an issue.

Thanks.

**Comment by EECOLOR** [comment]
@marcospereira There has been no response on the mailing list. Is this a new policy, to close an issue and refer to the mailinglist?

**Comment by EECOLOR** [comment]
There has been no response on the mailinglist
