### ISSUE TITLE
[Play 2.4 Scala] Testing default settings

### ISSUE THREAD

**Issue by Hayena** [playframework/playframework#4829]
In one of our libraries we have some tests to check if the defaults are picked up properly. In Play 2.3 we were able to unset a variable by setting it to null in the `additionalConfiguration` parameter of `FakeApplication`, this would cause the getString function on `Configuration` to return a `None`. With Play 2.4 doing this will cause the application to throw an exception instead of returning `None`.

**Comment by marcospereira** [comment]
Hello @Hayena, do you mind discuss that first on the [user mailing list](https://groups.google.com/forum/m/#!forum/play-framework)? If we confirm that there is an error with Play, than we can open an issue.

Also, could you please provide a test case for this scenario?

Thanks.

**Comment by EECOLOR** [comment]
@marcospereira There has been no response on the mailing list. Is this a new policy, to close an issue and refer to the mailinglist?

**Comment by jroper** [comment]
@EECOLOR this has always been the policy, see https://www.playframework.com/contributing:

> If you are not 100% sure that it is a bug, then ask about it on the mailing list first. You will get a lot more help a lot quicker on the mailing list if you raise it there. The issue tracker is for verified bugs, not for questions.

@marcospereira asked for a test case, if a test case is provided, we will reopen.

**Comment by EECOLOR** [comment]
@jroper Thank you for the quick and clear response.

**Comment by EECOLOR** [comment]
There has been no response on the mailinglist

**Comment by EECOLOR** [comment]
In combination with #4827 this is a serious problem for us. Because now we can not run our tests using different configurations.
