### ISSUE TITLE
Access jboss datasource via JNDI

### ISSUE THREAD

**Issue by pdincau** [playframework/playframework#4830]
Hello,

I would like to know if I can configure my application.conf  so that my play application will use an external datasource via jndi (the application is hosted on JBoss).

thanks

**Comment by marcospereira** [comment]
Hello @pdincau, do you mind discuss that first on the [user mailing list](https://groups.google.com/forum/m/#!forum/play-framework)? If we confirm that there is an error with Play, than we can open an issue.

Thanks.

**Comment by pdincau** [comment]
Sure! Thanks for pointing out

**Comment by pdincau** [comment]
Hi, i got no feedback from the mailing list: https://groups.google.com/forum/m/#!topic/play-framework/FdSvRqO4lhA

Is at all possible to use the jboss datasource?
