### ISSUE TITLE
Dependency Injection and Akka Router

### ISSUE THREAD

**Issue by WeiZheng** [playframework/playframework#4832]
Hi,

I've read the document on Dependency injecting actors, but I still cannot figure out how to create Akka Router by using Dependency Injection.

For example, in the normal usage, I can just do:
```
val ApiExecutionRecorderRouter = Akka.system.actorOf(RoundRobinPool(5).props(Props[ApiExecutionRecorder]), "library.actors.ApiExecutionRecorderRouter")
```
but since now the ApiExecutionRecorder is managed by Guice, I don't know the correct way to instantiate it. 

Thanks.

Regards,

**Comment by jroper** [comment]
Hi @WeiZheng,

The issue tracker isn't for asking questions, please ask questions like this on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).

Regards,

James
