### ISSUE TITLE
[Play 2.4.2 Java] Field injection does not work for derived classes of Security.Authenticator

### ISSUE THREAD

**Issue by chunyang** [playframework/playframework#4835]
In [Security.java](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/mvc/Security.java#L36), since AuthenticatedActions calls `newInstance` on the Authenticator class directly, fields in the Authenticator marked with `@Inject` are not injected.

Is it possible to instantiate the class via the injector? Perhaps by replacing

    Authenticator authenticator = configuration.value().newInstance();

with

    Authenticator authenticator = Play.application().injector().instanceOf(configuration.value());

**Comment by richdougherty** [comment]
You're right, we should be using the injector to create the class.

**Comment by chunyang** [comment]
The same defect occurs with custom validators.

https://github.com/playframework/playframework/blob/master/framework/src/play-java/src/main/java/play/data/validation/Constraints.java#L482

**Comment by gmethvin** [comment]
Yep. That code hasn't changed in over three years. We should check if there are other places in the codebase where we use runtime reflection directly (e.g. `newInstance`) to make sure it wouldn't make more sense to use DI instead.

**Comment by chunyang** [comment]
Fixed in #4913
