### ISSUE TITLE
(play 2.4.2) substitution of classes in main project

### ISSUE THREAD

**Issue by kitgrund** [playframework/playframework#4840]
An html-view (*.scala.html) of a play-project from the dependencies cannot be replaced in the depending project anymore. Apparently the classloader does not search for the classes within the depending project at all. This does not affect the tests, where the classloader searches and replaces it correctly, but only the running application.

**Comment by richdougherty** [comment]
Can you please create a small sample project that demonstrates this issue? There are a number of subtle things that can affect classloading behaviour and inter-project dependencies. It's hard to tell if there's a problem without a concrete example.

**Comment by jroper** [comment]
Play has never supported "replacing" views as such - the fact that this worked for you before would have been a fluke of classloader ordering, and we have always strongly advised not depending on classloader ordering.

**Comment by cchantep** [comment]
Closing it for now
