### ISSUE TITLE
(play 2.4.2) defective default page

### ISSUE THREAD

**Issue by kitgrund** [playframework/playframework#4841]
The "views.html.defaultpages.notFound"-page displays "Action Not Found".

**Comment by richdougherty** [comment]
This sounds like correct behaviour. The purpose of the `views.html.defaultpages.notFound` template is to display a "not found" message.

Can you explain what you think is defective about the page?

**Comment by kitgrund** [comment]
How about a simple "Not Found"? I guess it is not right to display "Action Not Found" in any such case where a controller action is found in the first place that returns a not found http status due to further conditions. Shouldn't the term "action" be kept internally within the application anyway?

**Comment by marcospereira** [comment]
@kitgrund do you mind submitting a PR to change this? Thank you!
