### ISSUE TITLE
Default stringy JSON format for joda.time.DateTime is "YYYY-MM-DD"

### ISSUE THREAD

**Issue by pathikrit** [playframework/playframework#4844]
Although `joda.time.DateTime` can have precision information of hours, minutes, seconds etc the only acceptable default JSON formats for it in play-json are unix timestamps (longs) and `YYYY-MM-DD`. See [these lines of code](https://github.com/playframework/playframework/blob/52a7504e8613ab2a7ea6a91f8210515a8eb6d2cb/framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala#L636-L665) which make it impossible to specify minutes/hours etc in a string-based format. 
This bad pattern probably came from the [method itself being incorrectly named here](https://github.com/playframework/playframework/blob/52a7504e8613ab2a7ea6a91f8210515a8eb6d2cb/framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala#L642) - it should be `def jodaDateTimeReads` instead of `def jodaDateReads` since it returns `Reads[joda.time.DateTime]` and not `Reads[joda.time.Date]`

`Reads[joda.time.DateTime]`s should use the [ISODateTimeFormat.dateTimeParser](http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTimeParser()) instead of specifying an explicit pattern. This strategy was correctly used for `Reads[joda.time.LocalDate]` which [correctly falls back to the ISODateTimeFormat.localDateParser](https://github.com/playframework/playframework/blob/52a7504e8613ab2a7ea6a91f8210515a8eb6d2cb/framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala#L677) when an explicit pattern is not specified.

I understand, I can always create my own implicit and use it but it makes things harder when I am relying on external macro libraries like [metarest](https://github.com/pathikrit/metarest) or [this](https://github.com/kifi/json-annotation) which rely on the default Readers

**Comment by cchantep** [comment]
Hi @pathikrit, please move this discussion on the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework), which is the place to discuss of design changes and/or new features. Best regards.

**Comment by pathikrit** [comment]
Ok, discussion continued here: https://groups.google.com/forum/#!topic/play-framework/vofrDXZqpTI

**Comment by pathikrit** [comment]
The conclusion of the mailing list was that this is a bug or at best something we should definately do. Can we reopen this issue?

**Comment by gmethvin** [comment]
I will reopen, but we'll probably want to wait until we significantly change our JSON APIs (likely 3.0).

I think JSR-310 is already fully supported. Are there any types you want that don't have serializers?

**Comment by wsargent** [comment]
https://github.com/json4s/json4s is mentioned as part of 3.0:

> * Switch to json4s for Scala JSON modelling

https://docs.google.com/document/d/11sVi1-REAIDFVHvwBrfRt1uXkBzROHQYgmcZNGJtDnA/pub

**Comment by wsargent** [comment]
Is this still relevant given https://github.com/playframework/playframework/pull/6340 removes joda-time?

**Comment by gmethvin** [comment]
Yeah, we could move this to https://github.com/playframework/play-joda but it's still likely to break stuff since `DateTime` is so commonly used. Maybe we should just release a new version of play-joda that explicitly changes the default, and note that in the migration guide.
