### ISSUE TITLE
[2.4.x Scala] Not possible to set infinite WS request timeout

### ISSUE THREAD

**Issue by njrich28** [playframework/playframework#4846]
In Play 2.3.x it was possible to set a WS request timeout of -1 to indicate that the request should not be timed-out but this is now not possible in 2.4.x. This is required when using "streaming" style services - eg. Twitter Streaming APIs - which never complete.

Example code borrowed from [Reactive Web Applications](http://www.manning.com/bernhardt/):
```scala
      WS.url("https://stream.twitter.com/1.1/statuses/filter.json")
        .withRequestTimeout(-1)
        .sign(OAuthCalculator(consumerKey, requestToken))
        .withQueryString("track" -> "mondaymotivation")
        .get { response =>
          Logger.info("Status: " + response.status)
          iteratee
        }.map { _ =>
          Ok("Stream closed")
        }
```

The reason it's not possible is some extra validation has been put into [NingWS.scala](https://github.com/playframework/playframework/blob/2.4.x/framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala#L116) to check that the request timeout is a positive integer. Not setting a request timeout just uses the default (120 seconds).

Looking at the underlying AHC a request timeout of -1 is treated as a special case:
https://github.com/AsyncHttpClient/async-http-client/blob/master/providers/netty3/src/main/java/org/asynchttpclient/netty/request/NettyRequestSender.java#L380

I can submit PR for code fix, tests and documentation changes.

**Comment by richdougherty** [comment]
Yes a fix and tests for this would be great.

**Comment by jroper** [comment]
You can configure this for the whole Play app by setting `play.ws.timeout.request = null`.  The right solution for the API is to change the type of timeout accepted by `withRequestTimeout` to `Duration`, and add support for `Duration.Inf`.

**Comment by njrich28** [comment]
Would it be best to do this as 2 fixes: one for 2.4.x which changes the validation to enable setting the request timeout to -1 and another for master which changes the API  to accept `Duration` as recommended by @jroper ?

This fixes the regression in the short term and doesn't cause any breaking changes.

**Comment by jroper** [comment]
@njrich28 you're right that we have to be careful of breaking changes - adding support for -1 to Play 2.4 seems to be the best approach. When you do your PR, make it on master first, including tests/documentation, then either you or I or someone else, whoever gets to it first, can backport to 2.4.x, ensuring the mechanism is changed to supporting -1.

**Comment by lucianenache** [comment]
I've also had this issue, even tough for me a possible workaround was using '''Int.MaxValue''' , I belive that it is not concise because setting the t/o  the '''Int.MaxValue''' is not the same as disabling it.

**Comment by daron666** [comment]
Anyone knows in which version this fix will be included?

**Comment by jroper** [comment]
The fix in #4863 will be in Play 2.5, and can't be backported because it's a breaking change.  A fix for 2.4.x that maintains binary compatibility is possible, but no one has made it yet.

**Comment by daron666** [comment]
@jroper  thnx for clarification.

**Comment by taraxe** [comment]
My 2 cents,
If you need WS request timeout in play 2.4.x you can force it like this:
```
ws.url(URL)
.asInstanceOf[NingWSRequest]
.copy(requestTimeout = Some(-1))
.get()
```

**Comment by daron666** [comment]
Yeah. I did so.
