### ISSUE TITLE
[play 1.3.1 logger]  Problem configure Log4j by creating custom log4j.properties file

### ISSUE THREAD

**Issue by olzhas-pazyldayev** [playframework/playframework#4848]
In play 1.3.1 when you create custom log4j.properties file in conf/ folder. Play don't use it as custom configuration file, skips it and use default log4j.properties file included in play-1.3.1.jar.

**Comment by cchantep** [comment]
Hi, this issue tracker is dedicated to Play 2.x. You can find the [Play 1.x tracker](https://github.com/playframework/play1/pulls). You can first ask question on [SO tag](http://stackoverflow.com/questions/tagged/playframework-1.x). Best regards.
