### ISSUE TITLE
What Singletons does Play! Framework 2.4 provide out of the box?

### ISSUE THREAD

**Issue by ipsq** [playframework/playframework#4849]
I asked this question on StackOverflow but I think it should also be defined in the documentation somewhere. Frameworks like Laravel have sections like this: http://laravel.com/docs/5.1/contracts#contract-reference

StackOverflow question: http://stackoverflow.com/questions/31388088/what-singletons-does-play-framework-2-4-provide-out-of-the-box

**Comment by ipsq** [comment]
Found this so far: https://github.com/playframework/playframework/blob/912ea929f61a5c452e090715e6d02a22871a0dbb/framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala

**Comment by cchantep** [comment]
Until there is a precise/actionable documentation PR to be attached to that (in which case it can be reopened), please use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) for further discussion. Best regards.
