### ISSUE TITLE
Unexpected by value call for JsLookupResult.getOrElse

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#4851]
I was expecting this to behave like Option (which it delegates to) but in JsLookupResult getOrElse is by value where in Option the default is passed by name.

```scala
def getOrElse(v: JsValue): JsValue
```
vs
```scala
def getOrElse[B >: A](default: => B): B
```

**Comment by gmethvin** [comment]
You're right. It should be `=> JsValue`. As a workaround you can use `.toOption.getOrElse`.
