### ISSUE TITLE
Optionally filter private IP address ranges from RequestHeader.remoteAddress

### ISSUE THREAD

**Issue by jxtps** [playframework/playframework#4853]
While it is possible to exclude trusted proxies in the evaluation of the remoteAddress, it would be convenient to in one stroke exclude all private IP addresses from consideration - for public facing websites, they're definitely not going to be the IP that you're looking for. 

If for example you're on AWS using ELB -> NGINX -> Play, then the ELB will have a private IP address, and a simple boolean configuration flag could make remoteAddress work, instead of each Play user having to look up the IP address range specifications for private IP addresses.

**Comment by jroper** [comment]
The trusted proxies are not about excluding the addresses that you're not looking for, they're about white listing proxies that you trust to prevent attackers from spoofing trusted proxy headers.  Do you really trust every private IP address on AWS?  I could start my own server on AWS, and connect to the private IP address of your server, and if you trust all private IP addresses, then that means I can say I'm any remote IP address I like - a major security vulnerability if you're using IP addresses as part of your security.

If you're not using the remote IP address for the purposes of security, then do you really care if some user is trying to spoof their IP address?  In which case, you may as well just trust all proxies by configuring `[ "0.0.0.0/0" ]`.  If you do want to only trust private IP addresses, you can do this easily using `[ "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16" ]`, but I don't think there are many valid use cases for that, and I think adding a flag would lead to mistakes like thinking that all private ip addresses are trusted proxies.

**Comment by jxtps** [comment]
Excellent points James. I was only intending to use IP addresses for logging, not security, but you're absolutely right that it's a little sloppy and probably shouldn't be in Play as suggested. 

The underlying driver is two fronts of dynamic change. 

On the one hand the proxy IP addresses: the ELB IP addresses change over time (and it's a pain to even get the internal IP addresses there - nslookup of the ELB DNS name gives external addresses, but you can re-map these to EC2 DNS names and nslookup on those gives internal IPs), and if you start doing whole site delivery with CloudFront, then those addresses also change over time (see https://aws.amazon.com/blogs/aws/aws-ip-ranges-json/ - "You can expect it to change several times per week and should poll accordingly."). 

On the other hand, the infrastructure configuration may change over time. You can have a single box with NGINX -> Play, then scale up to ELB -> NGINX -> Play, then maybe experiment with CloudFront -> ELB -> NGINX -> Play. 

Ideally "it should just work" without having to re-deploy the app with an updated configuration when those changes happen. I realize that it's probably going to have to be up to the end user to custom-develop that, and it is probably a futile effort to have dedicated configuration machinery in Play to handle these types of dynamic cases.
