### ISSUE TITLE
Setting up the JSON Object Mapper still requires GlobalSettings

### ISSUE THREAD

**Issue by salex89** [playframework/playframework#4864]
I noticed this while trying to set up the ObjectMapper in Java (to show Dates as Timestamps, looks like that is not the default behaviour) and noticed that even the official docs say that the `GlobalSettings.onStart` should be used to configure it. That is in conflict that GlobalSettings should be removable if everything is properly designed.

https://www.playframework.com/documentation/2.4.x/JavaJsonActions#Advanced-usage

And btw. I still have not found a way to serialize Joda DateTime or Java Instant to ISO8601. The automatic serialization always returns the object internal structure. But this is a separate issue I guess.

**Comment by gmethvin** [comment]
The documentation should be updated here. You don't need to do it in `GlobalSettings`. You just need to set the `ObjectMapper` at some point during application start.

You can do this in a custom `ApplicationLoader` or by creating a module that does the initialization.

**Comment by wsargent** [comment]
> And btw. I still have not found a way to serialize Joda DateTime or Java Instant to ISO8601. The automatic serialization always returns the object internal structure. But this is a separate issue I guess.

@salex89 can you file another issue for that?

**Comment by hsl43** [comment]
@wsargent - regarding the Joda DateTime serialization behavior above, i've now bumped into this behavior myself (using Play 2.5's Java API). are you aware if @salex89 filed a bug report for it? if not, i can do so.

**Comment by salex89** [comment]
I have not, obviously. I don't really even remember what it was about, bug was also resolved somehow. It may not even be the same one :) .
