### ISSUE TITLE
logback.xml file not used in dev mode with Compile time DI

### ISSUE THREAD

**Issue by studiodev** [playframework/playframework#4869]
Hello,

It seems that the `conf/logback.xml` file is not loaded if both of these conditions are filled:
 - The app run in dev mode (sbt run)
 - The app use Compile time DI

If the same app is launched in "prod" context (sbt dist and run the executable), there is no problem. Idem if the ApplicationLoader is removed.

I've created a sample project which shows the problem: https://github.com/studiodev/play24-compile-di-log-bug/.

**Comment by richdougherty** [comment]
May be related to #4570.

**Comment by studiodev** [comment]
You're right, adding `Logger.configure(context.environment)` fix the problem.

I close this ticket, #4570 already provides the solution.

**Comment by richdougherty** [comment]
Great. Hopefully we can get #4570 merged soon…
