### ISSUE TITLE
javacOptions in build.sbt has no effect since 2.4

### ISSUE THREAD

**Issue by alex-vas** [playframework/playframework#4871]
I have noticed after updating from 2.3.9 to 2.4.0 or 2.4.2 that the javacOptions property in build.sbt or Build.scala does not  have any effect anymore.

I have tried my own project and the standard brand new "reactive stocks" from the demos.

My modification is as follows (see javacOptions below):

````scala
name := """reactive-stocks"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.6"

// scalaz-bintray resolver needed for specs2 library
resolvers += "scalaz-bintray" at "https://dl.bintray.com/scalaz/releases"

libraryDependencies ++= Seq(
  ws, // Play's web services module
  specs2 % Test,
  "org.specs2" %% "specs2-matcher-extra" % "3.6" % Test,
  "org.easytesting" % "fest-assert" % "1.4" % Test,
  "com.typesafe.akka" %% "akka-testkit" % "2.3.11" % Test,
  "org.webjars" % "bootstrap" % "2.3.2",
  "org.webjars" % "flot" % "0.8.0"
)

javacOptions += "-XDignore.symbol.file"

routesGenerator := InjectedRoutesGenerator
````

**Comment by alex-vas** [comment]
Looks like it is an SBT issue introduced in 1.3.8

 * https://github.com/sbt/sbt/issues/1968

The workaround is to downgrade SBT to 1.3.7 in build.properties

**Comment by cchantep** [comment]
Hi, this issue tracker is for ticket about Play itself. Please note it's best to first ask question on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework), before creating a ticket if the issue is confirmed. Best regards.
