### ISSUE TITLE
Wrong exception handling in SqlRequestError as of Anorm 2.4.0?

### ISSUE THREAD

**Issue by christian-schlichtherle** [playframework/playframework#4873]
In Anorm 2.4.0, file anorm/Anorm.scala, lines 19 and 20 it reads:

    /** Returns error as a failure. */
    def toFailure = Failure(sys.error(message))

In Scala 2.11.7, file scala/sys/package.scala, line 27 it reads:

    def error(message: String): Nothing = throw new RuntimeException(message)

Mind the `throw` keyword! Next, in Scala 2.11.7, file scala/Try.scala, line 198 it reads:

    final case class Failure[+T](exception: Throwable) extends Try[T] {

This leads me to the conclusion that a `Failure` object is never returned, but a `RuntimeException` is thrown instead each time execution hits the initial `toFailure` method/function.

BTW: Wouldn't it be better to use an `SQLException` instead anyway? This would describe the problem domain much better than a generic `RuntimeException`.

**Comment by christian-schlichtherle** [comment]
I guess this explains why I don't get a reasonable error message sometimes, for example if I forget to provide a parameter to an SqlQuery. Example:

    SQL("SELECT content FROM documents WHERE isbn = {isbn}") as myParser.single

Here I forgot to provide the `{isbn}` parameter.

**Comment by cchantep** [comment]
Hi, note that the issue tracker for Anorm [is there](https://github.com/playframework/anorm/issues) (separate repository). Before raising an Anorm ticket, please to [submit a question](http://stackoverflow.com/questions/tagged/anorm) (issue trackers, for Play and associated projects like Anorm, are for confirmed/actionable ticket). Best regards.

**Comment by nafg** [comment]
Looks pretty open-shut to me...
