### ISSUE TITLE
Testing a controller with mocked dependencies 2.4

### ISSUE THREAD

**Issue by Kdoherty11** [playframework/playframework#4876]
I am migrating my application from to 2.4. In my controller unit tests, I had set up the controller along with its associated mocked dependencies before each test.

It seems that the getControllerInstance method was removed from GlobalSettings in 2.4 so now I can't override it to return my controller instance.
```
@RunWith(MockitoJUnitRunner.class)
public class PublicRoomsControllerTest extends WithApplication {

    @Mock
    private MyService myService;

    private MyController myController;

    @Before
    public void setUp() {
        myController = new MyController(myService);

        GlobalSettings global = new GlobalSettings() {

            public <T> T getControllerInstance(Class<T> clazz) {
                return (T) controller;
            }

        };

        start(fakeApplication(global));
    }

    @Test
    public void myTest() {
        Result result = route(new RequestBuilder().method(POST).uri("/test"));
        assertEquals(OK, result.status());
    }

}
```
I know I can call the method directly on my controller instance from my test such as:
```
Result result = myController.someMethod();
assertEquals(OK, result.status());
```
This approach seems to work fine until someMethod() relies on form data in the request like
```
 Map<String, String> data = Form.form().bindFromRequest().data();
```
Is there someway for the test to route requests, which may include form data, to use my controller instance?

(I am using Guice, Mockito, and JUnit)

**Comment by benmccann** [comment]
Look at `Helpers.invokeWithContext`. That would solve the problem of accessing the form data.

You could also use `Helpers.route` if you don't want to create the controller instance yourself

**Comment by Kdoherty11** [comment]
Awesome Helpers.invokeWithContext is exactly what I was looking for. Thanks for the help!
