### ISSUE TITLE
[Play 2.4.2] CipherSuites documentation

### ISSUE THREAD

**Issue by edouardKaiser** [playframework/playframework#4877]
Hi all,

In https://www.playframework.com/documentation/2.4.2/CipherSuites it says the option is _play.ws.ssl.enabledCiphers_ but in reality it's _play.ws.ssl.enabledCipherSuites_   (play/api/libs/ws/ssl/Config.scala line 217).

Cheers

**Comment by marcospereira** [comment]
Hi @edouardKaiser, do you mind submitting a pull request to correct the docs?

Thank you very much!

**Comment by edouardKaiser** [comment]
Sure I'll do it

**Comment by edouardKaiser** [comment]
Done

https://github.com/playframework/play-generated-docs/pull/5

**Comment by wsargent** [comment]
Hi @edouardKaiser please see https://github.com/playframework/play-generated-docs/pull/5#issuecomment-125259629 -- the docs are generated from inside the main project, not play-generated-docs.

**Comment by wsargent** [comment]
Checked in a fix, closing.
