### ISSUE TITLE
Nesting 8 defining statements in a template generates a compliation error of "File name too long"

### ISSUE THREAD

**Issue by stusmall** [playframework/playframework#4882]
I ran into a strange compilation error when working on a project.  I made a new project with the smallest example of code that triggers the problem.  The example code can be found at:

https://github.com/stusmall/templatebug

Just clone the repo and run "sbt compile" to see the problem.  Output is as follows:

stusmall@T520:~/workspace/templatebug$ sbt compile
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
[info] Loading project definition from /home/stusmall/workspace/templatebug/project
[info] Set current project to templatebug (in build file:/home/stusmall/workspace/templatebug/)
[info] Updating {file:/home/stusmall/workspace/templatebug/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 6 Scala sources and 1 Java source to /home/stusmall/workspace/templatebug/target/scala-2.11/classes...
[error] File name too long
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 13 s, completed Jul 22, 2015 10:41:36 PM
stusmall@T520:~/workspace/templatebug$

**Comment by marcospereira** [comment]
I was not able to reproduce the problem using your project.

1. Which JVM version are you using?
2. Which operating system? Ubuntu? Mac OSX?
3. I've notice that you are using a java agent (`JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar`). What is does?

**Comment by stusmall** [comment]
I'm using Ubuntu 15.04 and for my java version:

stusmall@T520:~/workspace/templatebug$ java -version 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
stusmall@T520:~/workspace/templatebug$ 

As for jayatanaag:
http://stackoverflow.com/questions/26074446/picked-up-java-tool-options-javaagent-usr-share-java-jayatanaag-jar-when-st

Even when removing jayatanaag I get the same issue:

stusmall@T520:~/workspace/templatebug$ sbt compile
[info] Loading project definition from /home/stusmall/workspace/templatebug/project
[info] Set current project to templatebug (in build file:/home/stusmall/workspace/templatebug/)
[info] Compiling 6 Scala sources and 1 Java source to /home/stusmall/workspace/templatebug/target/scala-2.11/classes...
[error] File name too long
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 9 s, completed Jul 23, 2015 12:57:32 AM
stusmall@T520:~/workspace/templatebug$

**Comment by teozkr** [comment]
Are you using Ubuntu's encrypted home folder option? Lambdas generate new class files, which combined with ecryptfs massively increasing the length of file names can easily blow past the 255-character limit.

Adding `scalacOptions ++= Seq("-Xmax-classfile-name", "140")` to your build.sbt should fix it.

**Comment by stusmall** [comment]
Well, yes I am!  Brilliant, that fixed it!  Thank you very much!

**Comment by teozkr** [comment]
No problem! That said, since I'm not the only one bit by this, I'd say this should probably be documented somewhere, or even added as a default option (since AFAIK it doesn't have any negative effects).

**Comment by stusmall** [comment]
I'll write a pull request for this tonight.  If you had a preference on a change, would it be doc fix or updated defaults?

**Comment by teozkr** [comment]
I'd go for changing the default, but adding it to the generated build.sbt to make it obvious what's happening.

**Comment by richdougherty** [comment]
This doesn't seem like a Play-specific issue. I'd say a fix should go into sbt or Scala rather than going into Play.

**Comment by stusmall** [comment]
Looks like the root cause is in the scala-lang bug tracker as https://issues.scala-lang.org/browse/SI-9319

I'll hit up the scalac community to see if they are open to a PR to change the default size.

**Comment by teozkr** [comment]
@richdougherty I'd agree, it affects class names which might have compatibility repercussions that don't apply to "application"-type projects.

**Comment by stusmall** [comment]
Here is where I've reached out to the scala internals community: https://groups.google.com/forum/#!topic/scala-internals/oExx6DmKIPo

**Comment by stusmall** [comment]
Looks like there is a binary compatibility issue with changing this values default[1]  and ecrypt doesn't have plans to fix the underlying issue[2].  Looks like a doc fix and a better error message might be the best option here.

1. http://scala-language.1934581.n4.nabble.com/Xmax-classfile-name-td4637574.html
2. https://bugs.launchpad.net/ecryptfs/+bug/344878

**Comment by stusmall** [comment]
Patch for this was landed here: https://github.com/scala/scala/pull/4678
