### ISSUE TITLE
Brand new install failing: unresolved dependency: commons-logging

### ISSUE THREAD

**Issue by EvertHoff** [playframework/playframework#4884]
I'm new to Scala, Play2 and Activator and am getting stuck at the very first step. 

I've just done a brand new install of play scala and it failed. Here are the steps I followed:

0. Installed JDK 8
1. Downloaded and installed activator-dist-1.3.5
2. activator new
3. play-scala
4. myproject
5. cd myproject
6. activator
7. compile

Then I got the error below:

MacBook-Pro:projects evert$ activator new

Fetching the latest list of templates...

Browse the list of templates: http://typesafe.com/activator/templates
Choose from these featured templates or enter a template name:
  1) minimal-akka-java-seed
  2) minimal-akka-scala-seed
  3) minimal-java
  4) minimal-scala
  5) play-java
  6) play-scala
(hit tab to see a list of all templates)
> play-scala
Enter a name for your application (just press enter for 'play-scala')
> myproject
OK, application "myproject" is being created using the "play-scala" template.

To run "myproject" from the command line, "cd myproject" then:
/data/projects/myproject/activator run

To run the test for "myproject" from the command line, "cd myproject" then:
/data/projects/myproject/activator test

To run the Activator UI for "myproject" from the command line, "cd myproject" then:
/data/projects/myproject/activator ui

MacBook-Pro:projects evert$ cd myproject/
MacBook-Pro:myproject evert$ activator
[info] Loading project definition from /data/projects/myproject/project
[info] Updating {file:/data/projects/myproject/project/}myproject-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to myproject (in build file:/data/projects/myproject/)
[myproject] $ compile
[info] Updating {file:/data/projects/myproject/}root...
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: commons-logging#commons-logging;1.1.1: configuration not found in commons-logging#commons-logging;1.1.1: 'master(compile)'. Missing configuration: 'compile'. It was required from org.apache.httpcomponents#httpclient;4.0.1 compile
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		commons-logging:commons-logging:1.1.1
[warn] 		  +- org.apache.httpcomponents:httpclient:4.0.1
[warn] 		  +- oauth.signpost:signpost-commonshttp4:1.2.1.2
[warn] 		  +- com.typesafe.play:play-ws_2.11:2.4.2 (/data/projects/myproject/build.sbt#L9-15)
[warn] 		  +- myproject:myproject_2.11:1.0-SNAPSHOT
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: commons-logging#commons-logging;1.1.1: configuration not found in commons-logging#commons-logging;1.1.1: 'master(compile)'. Missing configuration: 'compile'. It was required from org.apache.httpcomponents#httpclient;4.0.1 compile
[error] Total time: 1 s, completed 23 Jul 2015 8:07:40 AM

I've also tried it with "play-slick" instead of "play-scala", but get the same problem.

Please help. 

Thanks,
Evert

**Comment by teozkr** [comment]
Seems to work on my machine with a fresh install.

Can you post the results of `$ ls ~/.ivy2/cache/commons-logging/commons-logging`, as well as the contents of `~/.ivy2/cache/commons-logging/commons-logging/ivy-1.1.1.xml`?

**Comment by EvertHoff** [comment]
MacBook-Pro:/ evert$ ls -l ~/.ivy2/cache/commons-logging/commons-logging
total 48
-rw-r--r--  1 evert  staff    423 Oct  8  2014 ivy-1.1.1.xml
-rw-r--r--  1 evert  staff  10099 Jun 17 14:20 ivy-1.1.3.xml
-rw-r--r--  1 evert  staff    333 Jul 23 07:04 ivydata-1.1.1.properties
-rw-r--r--  1 evert  staff    894 Jul 23 07:07 ivydata-1.1.3.properties
MacBook-Pro:/ evert$ cat ~/.ivy2/cache/commons-logging/commons-logging/ivy-1.1.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
	<info organisation="commons-logging"
		module="commons-logging"
		revision="1.1.1"
		status="release"
		publication="20141008145326"
		default="true"
	/>
	<configurations>
		<conf name="default" visibility="public"/>
	</configurations>
	<publications>
		<artifact name="commons-logging" type="jar" ext="jar" conf="default"/>
	</publications>
</ivy-module>

**Comment by teozkr** [comment]
Looks like the artifact manifest got corrupted somehow, deleting `~/.ivy2/cache` should fix it. Otherwise, what else do `~/.ivy2`, `~/.sbt/0.13`, and `~/.sbt/0.13/staging` contain?

**Comment by EvertHoff** [comment]
Deleting ~/.ivy2/cache worked.

Thanks,
Evert

**Comment by mattvukas** [comment]
Deleting ~/.ivy2/cache solved this problem for me as well

**Comment by Alvaroisit** [comment]
Here is copy paste command: rm -rf ~/.ivy2/cache

**Comment by marcospereira** [comment]
@vikash6928 sometimes it could get corrupted (for reasons not related to Play) and recreate it solves these file corruptions problems. But this should not be something you do frequently, quite the opposite.
