### ISSUE TITLE
Inconsistent database error is not aware of transactional evolutions

### ISSUE THREAD

**Issue by teozkr** [playframework/playframework#4885]
Transactional evolutions don't (well, shouldn't) leave broken state, so the current error language doesn't make a lot of sense.

Current:
![ErrorMessage](http://i.imgur.com/jwkanZh.png)

If nothing else it'd be nice to either change or remove the button to something that is more relevant (like retry).

**Comment by richdougherty** [comment]
When an error occurs while applying evolutions, maybe you need two buttons, one to retry and one to mark as resolved. Would that work?

**Comment by nafg** [comment]
+1

**Comment by teozkr** [comment]
@richdougherty I can't see a case where having both retry *and* mark-as-resolved would be sensible. If transactional evolutions are on then you simply don't get inconsistent state from that, if they're off then, well, retrying wouldn't make much sense anyway.

**Comment by richdougherty** [comment]
OK I see what you mean. Your original suggestion makes sense to me now.

**Comment by marcospereira** [comment]
@teozkr please, keep in mind that not all databases have support for transactional DDLs. [MySQL doesn't](https://dev.mysql.com/doc/refman/5.7/en/cannot-roll-back.html), per instance. Also, are you suggesting that all the pending evolutions are applied in a single transaction or that we have a separated transaction for each pending evolution?

**Comment by teozkr** [comment]
@marcospereira Play already supports transactional DDL, behind a config flag ([evolutions.autocommit](https://www.playframework.com/documentation/2.4.x/Evolutions#Transactional-DDL)). The bug is that the error UI isn't aware of this config flag.

**Comment by mkurz** [comment]
PR: #5478
