### ISSUE TITLE
Usage of Java's Messages.get().

### ISSUE THREAD

**Issue by mshibanami** [playframework/playframework#4886]
https://github.com/playframework/playframework/blob/2.4.x/documentation/manual/working/javaGuide/main/i18n/JavaI18N.md
This document explains how to use `Messages.get()` like this.
```java
String title = Messages.get(new Lang(Lang.forCode("fr")), "home.title")
```
Is it same as this?
```java
String title = Messages.get(Lang.forCode("fr"), "home.title")
```

**Comment by richdougherty** [comment]
Yes I think they are the same. The docs should be fixed to use the simpler version.

When fixing the docs, the code should be moved into `JavaI18N.java` so that it will be automatically compiled and tested.

**Comment by mshibanami** [comment]
Thank you (^_^)
I'll send a PR.
