### ISSUE TITLE
[Play 2.3.9] zipWithIndex in templates on a java object gives two leading zeros.

### ISSUE THREAD

**Issue by themattchan** [playframework/playframework#4887]
If I pass a java list `lst = ["a","b","c","d"]` into a template and do

```
@for((char, idx) <- lst.zipWithIndex) { @char, @idx :: }
> "a", 0 :: "b", 0 :: "c", 1 :: "d", 2
```

Whereas it works fine if you use a scala list.

**Comment by katzelad** [comment]
could not produce this error, it's always `a, 0 :: b, 1 :: c, 2 :: d, 3 ::` for me.

**Comment by jroper** [comment]
@themattchan Can you provide some code examples or a project that demonstrates this?
