### ISSUE TITLE
Adopt minimalized AST for Json (json4s-ast)

### ISSUE THREAD

**Issue by mdedetrich** [playframework/playframework#4889]
Some time ago, `Play` was interested in adopting a minimalized `AST` of `json4s`, in an attempt to establish a common json AST to be used by scala libraries. I believe @jroper  was instantiating the conversation from `Play`'s side.

At JSON4s we have recently begun reviving this effort. If you are still interested, we would be glad to have your input either at gitter (json4s/json4s) or you can comment directly on the pull request/issues here https://github.com/json4s/json4s-ast/issues.

**Comment by gmethvin** [comment]
Yes. It seems like the current play-json library is pretty close to "minimal" in the sense that it represents each JSON type with one Scala type. Is that what you guys are aiming for here?

**Comment by mdedetrich** [comment]
We have actually ended up developing 2 `AST`s (both are barebone and minimal). The difference is one is designed purely for parsing, serializing (it uses `Array`'s internally for performance), where as the other `AST` is designed for correctness/purity as well as effective constant lookup time for things like `JObject`/`JArray` (uses `Vector`/`Map`)

You can view the latest implementation at https://github.com/mdedetrich/json4s-ast/tree/reboot, you can also join us in the gitter room (json4s/json4s), and the issues link was posted earlier

**Comment by cchantep** [comment]
I guess the MailingList is a better place for such discussion. Best regards.
