### ISSUE TITLE
Unmanaged dependencies not found & packaged incorrectly

### ISSUE THREAD

**Issue by Leopard2A5** [playframework/playframework#4891]
I have a jar file (let's call it JarName) in the lib dir under the project root. When i run `activator run` and open the app in the browser it says

`java.io.FileNotFoundException: /home/user/.../project/target/scala-2.11/classes/lib/JarName-1.0.1.jar (No such file or directory)`

Furthermore, when i run `activator dist` and then unzip the created archive (from target/universal) and start it by running the executable in the `bin` directory it says

`java.io.FileNotFoundException: /tmp/play/project-1.0-SNAPSHOT/conf/lib/JarName-1.0.1.jar (No such file or directory)`

because the dist task puts the `lib` directory into the root directory and not `conf`. When i move the `lib` dir to `conf` the app won't start, however when i put a symbolic link there it starts and works.

**Comment by marcospereira** [comment]
@Leopard2A5 do you mind creating a small project that we can use to see this problem happening?

**Comment by Leopard2A5** [comment]
Will do. Might take until friday or so.

**Comment by Leopard2A5** [comment]
It seems i can't replicate the error anymore...

**Comment by marcospereira** [comment]
Ok. I will close this for a while. Feel free to reopen it if necessary.
