### ISSUE TITLE
How can I prevent hacking the routes?

### ISSUE THREAD

**Issue by momiji** [playframework/playframework#4892]
Hello,

This is my first post here, as I do not use Play yet, but one of these so many stack frameworks that got inspiration from play, rails, and so on.

However, we discovered a strange behavior in the way route works, and I wanted to share with the Play! community, as I made some tests with Play! that shows the same strangity.

In case this is a real problem, I wondered whether it must be solved in the framework itself, or in a component above/before the framework, like maybe the web server (Apache, Nginx, ...) or a network component (Reverse Proxy, F5 security component, ...).

## The problem
I was able to get strange values in a route with simple arguments.
For example, in a route like `/display/:name`, I could get the parameter `name` with a value like `../delete/:name`.

In case this parameter is used to locate file on disk or REST resources for example, this may lead to undesired effects, and maybe security issues.

## Setup to test
For testing, I just create a new "play-java-intro" using the activator ui, and do very small modifications:
* a new route like this:

```
GET     /display/:name               controllers.Application.displayName(name)
GET     /displays/*name              controllers.Application.displayName(name)
```
* a new method in Application.java like this:

```java
    @Transactional
    public Result displayName(String name) {
        return ok(name);
    }
```

I'm using chrome navigator and Fiddler for testing, to prevent url modification by chrome.

## Tests
All urls start wirh http://localhost:9000, as I launched directly from activator ui.

As expected:
```
/display/x    => x
/display/x/y  => error
/displays/x   => x
/displays/x/y => x/y
```

As not expected:
```
/display/x%2Fy                 => (1) x/y
/display/x%2F..%2Fy            => (2) x/../y
/display/x%2F..%2F..%2F..%2Fy  => (3) x/../../../y
/displays/x%2F..%2F..%2F..%2Fy => (4) x%2F..%2F..%2F..%2Fy
/displays/x/../../../y         => (5) x/../../../y
```

Some explanations: in (1), I was able to force `:name` param to act like `*name`, allowing me to put whatever I want in `name`, that was proved with (2) and (3). Strangely, the `*name` param did not recognize the `%2F` as being a `/` character, and maybe this is a very good thing, however I wonder what may happen if I reuse this parameter to call another service that does work like (1), (2) or (3). And last, in (5), we were able to move outside the root of the site (/) by moving twice upward it. 

## Thoughts and guesses
I'm not an expert in all those IETF norms and so on, but I would expect all this to work in a uniform way, and probably am I wrong, but I would prefer something more secure than not enough, without adding too much constraints on the developers.

For example, I would have imagined the following:
* in (1), url should have been simplified to `/display/x/y`, and the route should not have been called
* in (2), the same simplified to `/display/y`
* in (3), the same simplified to `/y`, to prevent from going upward than `/`
* in (4), url converted to `/displays/x/../../../y` then simplified to `/y`, like in (3)
* in (5), url simplified again to `/y`, like in (3)

## How to correct
I'm not sure at all on how to correct this. Maybe some library already exists for doing this, maybe not. I'm of course interested if someone knows the "good" way for avoiding these hacking.
As a very simple developer, I just wrote my own simplification method, based on Files.simplifyPath you can find in the guava library, that translates all `%2F` to `/`, `%5C` to `\` (for fixing on Windows) and `%2E` when used for `.` and `..` path traversal before simplifying the url.

Just for information, it looks like Jetty (the framework I'm using runs a jetty embedded server) is doing something similar, as displayed when activating debug logs, and even if I didn't yet took the time to track when and how, it uses some of the methods in URIUtils. However, the simplified uri they got is not sent to the framework, it looks like it is only used internally to jetty. How unlucky...

Here is the code with test cases below.

```java
    /**
     * Simplify a url to compact and remove all path traversal like ../ and deals with encoded . / and \.
     * <br><br>
     * For example, /path/folder/../file will be simplified to /path/file
     * 
     * @param url the url to simplify
     * @return the simplified url, with all path traversal removed, or null if input was null or "." if url was ""
     */
    public static String simplifyUrl(String url) {
        if (url == null) return null;
        if (url.length() == 0) return ".";

        // replace all %2F with /
        url = url.replace("%2F", "/");
        url = url.replace("\\", "/");
        url = url.replace("%5C", "/");

        // split the path apart
        Iterable<String> components = Splitter.on('/').omitEmptyStrings().split(url);
        List<String> path = new ArrayList<String>();

        // resolve ., .., and // (. can also be a %2E)
        boolean lastIsFolder = false;
        for (String component : components) {
            lastIsFolder = true;
            String converted = component.replace("%2E", ".");
            if (converted.equals(".")) {
                continue;
            } else if (converted.equals("..")) {
                if (path.size() > 0) {
                    path.remove(path.size() - 1);
                }
            } else {
                lastIsFolder = false;
                path.add(component);
            }
        }
        if (url.endsWith("/")) {
            lastIsFolder = true;
        }

        // put it back together
        String result = Joiner.on('/').join(path);
        if (url.charAt(0) == '/') {
            result = "/" + result;
        }
        if (lastIsFolder && !path.isEmpty()) {
            result += "/";
        }

        while (result.startsWith("/../")) {
            result = result.substring(3);
        }
        if (result.equals("/..")) {
            result = "/";
        } else if ("".equals(result)) {
            result = ".";
        }

        return result;
    }

    @Test
    public void testSimplifyUrl() {
        testForwardAndBackwardSlashes(".", "");
        
        testForwardAndBackwardSlashes("/", "/");
        testForwardAndBackwardSlashes("/", "/.");
        testForwardAndBackwardSlashes("/", "/./");
        testForwardAndBackwardSlashes("/", "/./.");
        testForwardAndBackwardSlashes("/", "/..");
        testForwardAndBackwardSlashes("/", "/../.");
        testForwardAndBackwardSlashes("/", "/.././");
        testForwardAndBackwardSlashes("/", "/../..");
        testForwardAndBackwardSlashes("/", "/../../");
        testForwardAndBackwardSlashes("/b", "/./b");
        testForwardAndBackwardSlashes("/b", "/../b");
        testForwardAndBackwardSlashes("/b", "/.././b");
        testForwardAndBackwardSlashes("/b", "/../../b");
        testForwardAndBackwardSlashes("/b/", "/./b/");
        testForwardAndBackwardSlashes("/b/", "/../b/");
        testForwardAndBackwardSlashes("/b/", "/.././b/");
        testForwardAndBackwardSlashes("/b/", "/../../b/");
        testForwardAndBackwardSlashes("/b/", "/./b/.");
        testForwardAndBackwardSlashes("/b/", "/../b/.");
        testForwardAndBackwardSlashes("/b/", "/.././b/.");
        testForwardAndBackwardSlashes("/b/", "/../../b/.");
        testForwardAndBackwardSlashes("/", "/./b/..");
        testForwardAndBackwardSlashes("/", "/../b/..");
        testForwardAndBackwardSlashes("/", "/.././b/..");
        testForwardAndBackwardSlashes("/", "/../../b/..");
        
        testForwardAndBackwardSlashes(".", "");
        testForwardAndBackwardSlashes(".", ".");
        testForwardAndBackwardSlashes(".", "./");
        testForwardAndBackwardSlashes(".", "./.");
        testForwardAndBackwardSlashes(".", "./../");
        testForwardAndBackwardSlashes(".", "./../.");
        
        testForwardAndBackwardSlashes(".", "..");
        testForwardAndBackwardSlashes(".", "../");
        testForwardAndBackwardSlashes(".", "../.");
        testForwardAndBackwardSlashes(".", "../..");
        testForwardAndBackwardSlashes(".", "../../");
        testForwardAndBackwardSlashes(".", "../../.");
        
        testForwardAndBackwardSlashes("b", "././b");
        testForwardAndBackwardSlashes("b", "./../b");
        testForwardAndBackwardSlashes("b", "./.././b");
        testForwardAndBackwardSlashes("b", "./../../b");
        testForwardAndBackwardSlashes("b/", "././b/");
        testForwardAndBackwardSlashes("b/", "./../b/");
        testForwardAndBackwardSlashes("b/", "./.././b/");
        testForwardAndBackwardSlashes("b/", "./../../b/");
        testForwardAndBackwardSlashes("b/", "././b/.");
        testForwardAndBackwardSlashes("b/", "./../b/.");
        testForwardAndBackwardSlashes("b/", "./.././b/.");
        testForwardAndBackwardSlashes("b/", "./../../b/.");
        testForwardAndBackwardSlashes(".", "././b/..");
        testForwardAndBackwardSlashes(".", "./../b/..");
        testForwardAndBackwardSlashes(".", "./.././b/..");
        testForwardAndBackwardSlashes(".", "./../../b/..");

        testForwardAndBackwardSlashes("/b", "/a/../b");
        testForwardAndBackwardSlashes("/b/", "/a/../b/");
        testForwardAndBackwardSlashes("/b/", "/a/../b/.");
        testForwardAndBackwardSlashes("/b/", "/a/../b/./");
        //
        testForwardAndBackwardSlashes("/b/", "/a%2F..%2Fb/");
        testForwardAndBackwardSlashes("/b/", "/a%2F%2E%2E%2Fb/");
        testForwardAndBackwardSlashes("/b/", "/a%2F%2E.%2Fb/");
        testForwardAndBackwardSlashes("/b/", "/a%2F%2E.%2Fb/.");
        testForwardAndBackwardSlashes("/b/", "/a%2F%2E.%2Fb/%2E");
    }
    
    private void testForwardAndBackwardSlashes(String expected, String actual) {
        assertEquals(expected, SwissKnife.simplifyUrl(actual));
        assertEquals(expected, SwissKnife.simplifyUrl(actual.replace("/","\\")));
    }
```

**Comment by wsargent** [comment]
Please use the mailing list or stackoverflow.com for questions like this.

**Comment by momiji** [comment]
I apologize, I was thinking here would be a good place to report a "might be" security issue.
I don't think stackoverflow would be a good place, maybe the mailing lists.

**Comment by wsargent** [comment]
URL normalization is described in https://tools.ietf.org/html/rfc3986 --  you're removing a dot segment from the root, which is a no-op.  You can see it described in Wikipedia here: https://en.wikipedia.org/wiki/URL_normalization

**Comment by momiji** [comment]
Thank you, I'll have a look on it.
Should I undetstand that path traversal injection is à feature and not a possible issue?

**Comment by gmethvin** [comment]
@momiji It's only a security issue if your code manually constructs the path to an arbitrary file on the filesystem, which, at least as I understand it, is not that common. Most of the time you'd want to use [`Assets`](https://www.playframework.com/documentation/2.4.x/Assets) or get the path directly from the application's resources.

**Comment by momiji** [comment]
Hello, I'm not very fluent in describing complex things in english, let me know if something is not clear enough.

Yes :) and No.

You are right, the first use case is serving file from the filesystem. If developers use the Assets, all is probably good. If they don't, or can't because customers may want something special, we're out.
Of course, nowadays, many senior (not junior) developers are aware that serving files from disk can be risky, and tend to do more checks, but not all. Personaly, I don't, because I trust the documentation, and didn't expect to receive a path traversal in a unique URI path segment. I should probably call another method in Files to verify that the real path is really under folder it should be.

> The default matching strategy for a dynamic part is defined by the regular expression [^/]+, meaning that any dynamic part defined as __:id will match exactly one URI path segment__.

But there are other use case, like the controller calling a REST service using the ":name" parameter, and the developer believing he can just add it to the url. Here again, it is possible to call whatever url (well not completly, it has to be in the same domain, port, ...) from the REST service. This is probably less common than serving a file, and I doubt anybody will ever think that he has to check the :name value. And I don't know if there is a method to check if the URL+:name is really under/below the URL path, like we can do with files.

This leads me to the real problem, what to do here. Is it something the framework must deal with, or may be a library on top of the framework, or maybe the web server itself, ... or is it something we don't care so it's the developers problem, but in that case don't you think 100% of developers should take care of it?

It recalls me these old days before SQL frameworks, where we had to manually take care of SQL injection. All framework now do the job, and all developers now believe that the framework do as it says in the documentation, and nobody test the SQL parameters anymore in their code.

For me, it is the same here, we have an HTTP routing feature, that says that :id is different than * id, and as I'm a lazy developer, I'm expecting that :id is not a path traveresal, and mush more, that * id is also not a path traversal outside it's parent, meaning /path/*id cannot go outside /path.

**Comment by gmethvin** [comment]
Moving the discussion here: https://groups.google.com/forum/#!topic/play-framework/KCcWk72CwVU

**Comment by ibahdanau** [comment]
Big chunk of your code can be replaced with java.util.URI(url).normalize().getPath(). You'll only will have to manually de-escape characters.
