### ISSUE TITLE
playframework/framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSRequest.java

### ISSUE THREAD

**Issue by stabenau** [playframework/playframework#4898]
Request (and earlier RequestHolders) are built by using 

    reference  = URI.create (uri); // and then later  
    reference.getQuery();

This will extract a URL decoded version of the querystring, effectively making it impossible to have correctly encoded urls as parameters inside the uri. Likely reference.getRawQuery() should be correct.

The error message that we get is normally "QueryString parameter should not have more than 2 = per part" due to parameters in the url we have as parameter. 
Example: uri = http://some.host/that/hasAUrlParam?url=http%3A%2F%2Fother.host%2Fwith%2Fparam%3Fdummy%3Ddummy

**Comment by marcospereira** [comment]
@stabenau Could you please:

1. Change the issue title to something more clear and descriptive?
2. Give us a clear test case with what you see and what you were expecting? It would be great if you add some code here.

Thanks.

**Comment by stabenau** [comment]
Sorry, totally forgot about this one.

Can't really come up with a test case, but an explanation at least. getQuery() removes the escaping of the query string. If you had escaped '&' or '=' in there (parameters that contain '&/=' basically), those become unescaped. This in turn will make correct parameter extraction later on impossible. (see error message)

I guess not many people have that problem ...
