### ISSUE TITLE
Default selenium version does not work with Firefox 38

### ISSUE THREAD

**Issue by myrosia** [playframework/playframework#4899]
The default selenium version in Play is 2.44 and it does not work with Firefox 38 - a known issue
https://code.google.com/p/selenium/issues/detail?id=8399

There is a newer release available now, 2.46, which resolves the problem. It would be good to upgrade Play defaults accordingly.

**Comment by marcospereira** [comment]
Selenium is added by [FluentLenium](https://github.com/FluentLenium/FluentLenium) project. You can easily upgrade the version in your project by adding the more recent version to your `build.sbt` file:

```scala
libraryDependencies += "org.seleniumhq.selenium" % "selenium-java" % "2.47.1"
```

To me this is the most sustainable way to keep up with browser versions, which are released in shorter cycles, compared to Playframework itself.
