### ISSUE TITLE
Field `form` value need not be private

### ISSUE THREAD

**Issue by kirked** [playframework/playframework#4900]
`play.api.data.Field` is implemented with `private val form: Form[_]`, and should not be.

There are times when it is useful for a (partial) template to be able to access other fields not in the current field subtree, and the private restriction really has no point since top-level templates use it directly.

My intended usage:

    Template A[Form[a]] -> Partial B(Field) -> Partial C(Form[_])
    Template D[Form[d]] -> Partial E(Field) -> Partial C(Form[_])

In the above, `Partial C` implements a complexly-derived select helper using values from the forms not in subtrees of either Partial B or E. I shouldn't have to pass `Form[a]` or `Form[d]` through the intermediate partials in order to get the functionality I desire. Both intermediate partials should be able to pass `field.form` to Partial C directly.

**Comment by kirked** [comment]
Additionally, I'd prefer this to be backported to 2.3.x since we haven't upgraded yet.

**Comment by cchantep** [comment]
Closing this one. New ticket can be raised for master if needed.
