### ISSUE TITLE
Cannot instantiate TemporaryFile when using play.api.BuiltInComponents#injector

### ISSUE THREAD

**Issue by phleemac** [playframework/playframework#4909]
This is related to https://github.com/playframework/playframework/issues/4707.  <code>TemporaryFile()</code> throws <code>InstantiationException</code> when using compile time dependency injection (ref: https://www.playframework.com/documentation/2.4.x/ScalaCompileTimeDependencyInjection)

**Comment by cchantep** [comment]
See #4912
