### ISSUE TITLE
Missing "Developer & Contributor Guidelines" in 2.4.x documentation

### ISSUE THREAD

**Issue by falconepl** [playframework/playframework#4914]
There is missing "Developer & Contributor Guidelines" (available [here](https://www.playframework.com/documentation/2.3.x/Guidelines) for 2.3.x) in Play's 2.4.x documentation. It's still referenced in `README.md` as:
http://www.playframework.com/documentation/latest/Guidelines

**Comment by jroper** [comment]
I've updated the README to point to the new home for the contributor guidelines (https://www.playframework.com/contributing).
