### ISSUE TITLE
Using PLAINTEXT for oauth_signature_method

### ISSUE THREAD

**Issue by techmag** [playframework/playframework#4924]
Based on my question (and 2/3s hack solution so far...) here: http://stackoverflow.com/questions/31751260/play-framework-2-4-x-openid-and-oauth-using-plaintext-for-oauth-signature-m/31754629#31754629 

Is there anyway we can get PLAINTEXT signatures baked into the library? 

Freshbooks and DropBox use this method and I haven't really looked all that hard so I suspect there will be others. 

As there is a setMessageSigner(new PlainTextMessageSigner()) already available we just need to expose or connect some more dots to make it accessible in the Play APIs.

**Comment by cchantep** [comment]
Hi, please first ask question on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework), then if there is a confirmed issue or some actionable improvement, a ticket can be raised on this tracker. Best regards.
