### ISSUE TITLE
Return support for Integers (make it configurable)

### ISSUE THREAD

**Issue by markpiller** [playframework/playframework#4926]
First of all shutting down a discussion of an issue the way is done in 4897 is a sign of immaturity and not being able to take responsibility for your actions.  https://github.com/playframework/playframework/issues/4897

Your changes broke our code. This is on its own is BAD. Your lack of desire to even LISTEN to what we have going on why your changes are not considerate is even WORSE.

A mature framework would when it breaks backward compatibility would at least consider providing a configuration switch to allow NUMEROUS projects which already use Play to run without any problems - unchanged. That's what experienced developers do. If you disregard everyone who is happy with your project (like us before 2.4 release), and only listen to those who ask for change, you LOSE supporters of your framework, because we simply cannot trust that you're doing the right thing and we do not believe that you will not break something else in the future.

You called my response to you "an attack". But from my perspective breaking our project is your attack on us. Have you thought about it that way? Or that would require some experience, huh?

**Comment by wsargent** [comment]
Hi @markpiller,

I understand that you're unhappy with the decision to break backwards compatibility in 2.4.x -- this is unfortunate, and the Play team does their best to minimize it, but there are cases where breaking backwards compatibility is necessary for the project to move forward.  

As someone who has been on the other end of breaking changes in code (and had to waste my weekends in fixing them), I understand your frustration -- but Play Framework has a code of conduct <https://www.playframework.com/conduct> which talks about empathy and not letting frustration turn into a personal attack.

The issues list is not the place for a discussion of project direction and policy: such things are better raised on the mailing list: https://groups.google.com/forum/#!forum/play-framework

**Comment by markpiller** [comment]
When I hear someone saying "we had no choice" (which is what you're saying about breaking backward compatibility in order to move the project forward), that's simply not true. There is always a choice. And ultimately, what you should really care about is giving YOUR USERS the choice. If you'd really cared about your users, creating a configuration item to allow switching between old way of serializing numbers and the new way would be a sign of care and maturity in thinking and just plain good standards in engineering. It is vary sad to see you're lacking all those.

Your code of conduct somehow works only one way, or at least that's how you see it. There is absolutely no empathy coming from your guys. The proof is right there - in the way Cédric responded (on more than one occasion) and closed the discussion just to shut us up.

**Comment by wsargent** [comment]
@markpiller Play has many different constituencies, and they all have different priorities and different desires.  It would be great if all decisions made all users 100% happy, but most API choices come with tradeoffs.

Regardless: this is not the appropriate forum, and personal attacks on contributors are against the code of conduct, no matter how strongly you feel about the topic.  Locking.
