### ISSUE TITLE
Inline file attachments using sendFile() have no way of specifying file names

### ISSUE THREAD

**Issue by pathikrit** [playframework/playframework#4936]
See [this line](https://github.com/playframework/playframework/blob/5d7adcbc246323310f6c9a9ef26555902e0ba3dc/framework/src/play/src/main/scala/play/api/mvc/Results.scala#L415) of code. Currently it is:
```scala
if (inline) Map.empty else Map(CONTENT_DISPOSITION -> ("attachment; filename=\"" + name + "\""))
```

I think it should be:
```scala
Map(CONTENT_DISPOSITION -> s"""${if (inline) "inline" else "attachment"};filename="$name"""")
```

Otherwise there is no way to specify `inline=true` and still have an appropriate name for the file if the browser fails to render the file inline and treats it as an attachment.

Reference: http://stackoverflow.com/questions/1395151/content-dispositionwhat-are-the-differences-between-inline-and-attachment

**Comment by jroper** [comment]
Here's the RFC describing the behaviour:

https://tools.ietf.org/html/rfc6266

From that:

> On the other hand, if it matches "inline" (case-insensitively), this implies default processing.  Therefore, the disposition type "inline" is only useful when it is augmented with additional parameters, such as the filename (see below).

So I think that's fine to use inline, though I do hope the browsers all implement the spec correctly - this is an area where historically browsers have differed in their behaviour.

**Comment by gmethvin** [comment]
I think we should always specify the filename. The worst case is that some browsers that could potentially display the file inline instead decide to download it. But it's much more useful to have a meaningful filename if the browser can't/won't display the file inline.

**Comment by jroper** [comment]
One thing to consider though is unintelligible filenames - eg timestamps, hashes etc.  Or worse, filenames that leak system info.  Often when serving a file, the URL actually contains the best filename, while the underlying filename is just some random value from the datastore.  Anyway, I'm not sure how that would actually impact people, I don't tend to ever use sendFile myself.

**Comment by pathikrit** [comment]
The unintelligible fileName/leaking info concern still remains if sendFile is called with default args or with inline=false. Also, if you hit save on a browser rendered inline document, if the fileName is set, you get the correct fileName in the save dialog in most browsers.

**Comment by jroper** [comment]
Well, not really, the browser will simply extract the filename from the URL, which may or may not be intelligible.  For example, Play's assets controller doesn't set a content disposition header, but you get meaningful filenames there, because the filename matches the URL.

**Comment by gmethvin** [comment]
I think we should set the filename consistently for both `inline` and `attachment`. But I can also see why someone would want to leave out the filename and let the browser specify it for them. Maybe we should change the `fileName` argument to allow specifying no filename.
