### ISSUE TITLE
Evolutions support for Derby DB

### ISSUE THREAD

**Issue by dotta** [playframework/playframework#4944]
Play Evolutions currently doesn't support Apache Derby DB[1]. As discussed in the mailing list [2], adding support for Derby boils down to having a specific Derby SQL statement for creating the `play_evolutions` table, just like we have for other databases [3].

A possible workaround until a fix is available is to manually create the `play_evolutions table`, so play won't try to create it. You can try with the following SQL:

```
create table play_evolutions (
    id int not null primary key,
    hash varchar(255) not null,
    applied_at timestamp not null,
    apply_script clob,
    revert_script clob,
    state varchar(255),
    last_problem clob
)
```

[1] http://db.apache.org/derby/
[2] https://groups.google.com/forum/#!topic/play-framework/Z8olAtkQLhY
[3] https://github.com/playframework/playframework/blob/master/framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L328-L366

**Comment by marcospereira** [comment]
Has PR #4981.

**Comment by marcospereira** [comment]
By the way, I will close this to keep further discussion on the PR. :-)

**Comment by dotta** [comment]
@marcospereira Personally, I'd prefer if issues are closed after the related PR is merged.
