### ISSUE TITLE
[2.4] Server is not stopped when using `start`

### ISSUE THREAD

**Issue by mariussoutier** [playframework/playframework#4953]
When testing production mode using `sbt start`, the server is not stopped after hitting Ctrl-D. The app exits, but the server is still running. `jps` shows `<pid> ProdServerStart` which then needs to be killed.

This happens since 2.4.

**Comment by matiwinnetou** [comment]
Confirmed, I experience this every day. I thought I was the only one that had this issue.

**Comment by jroper** [comment]
I'm pretty sure that's always been the behaviour, and it's intentional, from [the docs](https://www.playframework.com/documentation/2.3.x/Production#Using-the-start-command):

> If you type Ctrl+D, the Play console will quit, but the created server process will continue running in background. The forked JVM’s standard output stream is then closed, and logging can be read from the logs/application.log file.
>
> If you type Ctrl+C, you will kill both JVMs: the Play console and the forked Play server.

**Comment by mariussoutier** [comment]
James you're right, it's just very unintuitive to stop the server in development using Ctrl-D, and in "production" using Ctrl-C.
