### ISSUE TITLE
Incorrect RequestTimeout documentation in 2.3.x

### ISSUE THREAD

**Issue by cgbaker** [playframework/playframework#4955]
In version 2.3.8, in the Scala WS module documentation at: 
playframework/documentation/manual/scalaGuide/main/ws/ScalaWS.md
it is documented that the default request timeout is None, to support stream consumption. However, in the code, the NingAsyncHttpClientConfigBuilder is configured first with the value from application.conf, and then with the value from play.api.libs.ws.Defaults as a fall-back. The latter is set, as of 2.3.8, to 120 seconds: 
https://github.com/playframework/playframework/blob/2.3.8/framework/src/play-ws/src/main/scala/play/api/libs/ws/Defaults.scala
(this seems to be the case in 2.3.10, the most recent 2.3.x) 

The result is that, 120 seconds after connecting to a text/event-stream connection, my connection is dropped by the com.ning.http.client.providers.netty.timeout.RequestTimeoutTimerTask

The workaround apparently is to manually add a request timeout of -1 to the request holder. However, this is a magic number for the Ning client, and I imagine that other clients could pick a different number to represent "no timeout" (e.g., zero).

I looked at the most recent code in 2.4.x and it appears that this may still be an issue (I haven't tested it): 
https://github.com/playframework/playframework/blob/2.4.x/framework/src/play-ws/src/main/scala/play/api/libs/ws/Config.scala
The default here is set to 2 minutes; over-riding it to disable the timeout with a value of -1 (assuming this work the version of Ning used by 2.4.x) is still likely to be provider-specific. The documentation for 2.4.x correctly lists the timeout as 2 minutes, but it doesn't seem to indicate how to remove the request timeout. Ultimately, and IMHO, I think this is something that should be handled, on a provider-specific basis, by the WS library.

**Comment by njrich28** [comment]
I think this may have been fixed by #4863 where the WSRequest.withRequestTimout method was modified to accept a `Duration` which naturally includes `Duration.Inf` to represent no timeout. The underlying Ning implementation interprets `Duration.Inf` as -1 (which is special to Ning). Other underlying implementations could interpret `Duration.Inf` as they wish.

You still have to override it on a per-request basis though.

**Comment by cgbaker** [comment]
`Duration.Inf` sounds great to me. And per-request is not much of a burden; streaming use cases already require `Accept: text/event-stream`; an addition call on the request holder to set the timeout is no inconvenience. The default behavior of a finite timeout is, in my opinion, more reasonable.

**Comment by mkurz** [comment]
Looks like #4863 fixes this issue. Feel free to reopen if it does not.
