### ISSUE TITLE
java8 breaking WS lib's SNI functionality

### ISSUE THREAD

**Issue by patrik7** [playframework/playframework#4958]
Hi,

I run into issue where I cannot connect to SSL server that requires client to do SNI check.

The java8 bug is described here:
https://bugs.openjdk.java.net/browse/JDK-8072464

Unfortunatelly, I do not see any way how to disable the call to setHostnameVerifier(..) that WS lib does automatically. (I am also not 100% sure if not calling that would actually help)

Can you suggest a workaround, as it may take ages until Oracle fixes it.

**Comment by wsargent** [comment]
You don't describe which version of Play you are using.  Assuming you are using Play 2.4.x, WS wraps the AsyncHttpClient 1.9.x, which calls setEndpointIdentificationAlgorithm("HTTPS") internally.  It cannot be disabled, which means that hostname verification always occurs.

The best option here is to generate some custom X.509 certificates according to https://www.playframework.com/documentation/2.4.x/CertificateGeneration and add them to your server's trust store as described in https://www.playframework.com/documentation/2.4.x/KeyStores and https://www.playframework.com/documentation/2.4.x/ExampleSSLConfig.

**Comment by patrik7** [comment]
Hi,

I appretiate the quick reply. Sorry, for not mentioning the version, we are on 2.3.4.

The problem is that SNI does not occure. I am sure, as with -Djavax.net.debug=ssl,handshake it should write out line as: `Extension server_name, server_name` which it doesn't.

What I THINK is happening, is that java8's bug is triggered, due to the call setHostnameVerifier() that WS does: https://bugs.openjdk.java.net/browse/JDK-8072464

**Comment by wsargent** [comment]
Well... not exactly the same thing.  The hostname verifier in AsyncHttpClient 1.8.x runs after the handshake has been completed (because Netty doesn't do it internally), so you should still see it:

https://github.com/wsargent/async-http-client/commit/8e4d787565b9bc3929c9e24c82accd6c8b7233e7#diff-afb8fbb32a9b370f66b6fbdd6104f354R77

**Comment by patrik7** [comment]
Hi, upgrading to play 2.4.2 solved the problem!
