### ISSUE TITLE
play 2.3.10 with Exception "Unsupported major.minor version 52.0"

### ISSUE THREAD

**Issue by deanzz** [playframework/playframework#4959]
I want to upgrade my play version from 2.3.8 to 2.3.10 with jdk 7.
My java version is "1.7.0_11", OS is OSX Yosemite(10.10.4).
I see that 2.4.x require Java 8, so I download Play 2.3.10 (activator) on page https://www.playframework.com/download.
But I got the error 
"java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0" 
when I was compiling my project.
How did I got Java 8 compatible files?
Please help me solve the issue.
Thanks so much.

**Comment by dotta** [comment]
From the error message, my guess is that the Typesafe Config library v1.3.0 (which is for Java8 only) is in your project’s classpath. I guess you’ll have to debug your build. You may find sbt-dependency-graph helpful.

----------------
Mirco Dotta - @mircodotta

Typesafe – Build reactive apps!

**Comment by dotta** [comment]
Also, please use the [user MailingList](https://groups.google.com/forum/#!forum/play-framework) for asking questions about Play.

**Comment by deanzz** [comment]
Thanks datta.
I will try it.
