### ISSUE TITLE
play.api.test.WithApplication is missing

### ISSUE THREAD

**Issue by compmstr** [playframework/playframework#4961]
It looks like the play.api.test.Specs.scala file is missing from the 2.4.x branches, However both the main docs and the generated api docs still refer to code within that, mainly WithApplication.

Was that file meant to be removed?

**Comment by dotta** [comment]
Hi @compmstr, please use the [user MailingList](https://groups.google.com/forum/#!forum/play-framework) for asking questions about Play. 

P.S. https://www.playframework.com/documentation/2.4.x/Migration24#Specs2-support-in-a-separate-module is a hint toward a solution to your problem.
