### ISSUE TITLE
Incorrect documentation for testing with router

### ISSUE THREAD

**Issue by zinking** [playframework/playframework#4962]
https://www.playframework.com/documentation/2.4.2/ScalaFunctionalTestingWithScalaTest

    "respond to the index Action" in new App(fakeApplication) {

there is no such thing as `App` , but indeed `WithApplication`.

**Comment by marcospereira** [comment]
Hello @zinking 

There is no problem here. [ScalaTest Plus](http://www.scalatest.org/plus) has a different way to start a fake application for functional tests. You can see the [code used by our documentation](https://github.com/marcospereira/playframework/blob/master/documentation/manual/working/scalaGuide/main/tests/code-scalatestplus-play/ScalaFunctionalTestSpec.scala#L48-L57) and even compile and execute it by yourself. The nice thing here is that most of the code you see at our docs are fully executed by our build to guarantee that the examples are updated and correct.

Closing the issue.
