### ISSUE TITLE
Run Global.onStart without waiting for first request

### ISSUE THREAD

**Issue by yifanmai** [playframework/playframework#4967]
I have an app that does a significant amount of initialization work in `Global.onStart`. Currently, `onStart` only runs after the server has received the first request, even in dev mode. For reasons of developer ergonomics, I'd like to have the app compile and run onStart immediately, rather than waiting for a first request. Other devs have run into this issue before ([1](https://groups.google.com/forum/#!topic/play-framework/EdrHLgYB7Qw), [2](http://stackoverflow.com/questions/18316584/globalsettings-onstart-fires-only-after-first-request)).

Could we add a configuration setting to turn on or off this behavior?

**Comment by benmccann** [comment]
+1

**Comment by mkurz** [comment]
> even in dev mode
You probably mean "only in dev mode". In prod mode it starts immediately already.

**Comment by jroper** [comment]
`Global.onStart` is (or soon well be) deprecated.  I think what you want is an eager init mode, that compiles/starts Play immediately.

**Comment by Abhi11981198** [comment]
In production mode, i.e. $ activator start , Global.onStart() executes before the first request or we can say before the app starts listening on your specified port.

**Comment by nafg** [comment]
You can get it to compile immediately if you do ~run.

**Comment by mkurz** [comment]
Given that `Global` will be deprecated starting with Play 2.5 I don't think this will be changed anymore. Even though if someone wants to provide a PR feel free to do so.
