### ISSUE TITLE
[Play 2.3.X] - JPAPlugin - Allow programatic override of all settings (including persistence.xml)

### ISSUE THREAD

**Issue by joantune** [playframework/playframework#4969]
Hi!

Working with JPA, I found it a common requirement to run tests, while changing the database URL only.

The above stated behaviour is easy to accomplish with something like:

```java
 running(testServer(3333, fakeApplication(additionalConf))
```

where `additionalConf` is given by something like:

```java
   Map<String, String> additionalConf = new HashMap<String, String>();
        additionalConf.put("db.default.url", "jdbc:postgresql://psql-machine:5432/projectnametest");
```

 but if you want to change anything that exists only in the  persistence.xml, you cannot. The reason is that JPAPlugin's onStart uses

```java
javax.persistence.Persistence.createEntityManagerFactory(persistenceUnit)
```

instead of:

```java
public static EntityManagerFactory createEntityManagerFactory(String persistenceUnitName, Map properties) {
```

which states that:

```
@param properties Additional properties to use when creating the factory. The values of these properties override any values that may have been configured elsewhere
```

My proposed suggestion is to change the onStart, and if one has any parameter after the
`jpa.key` e.g. `jpa.key.hibernate.xpto.setting` then everything after the `jpa.key` should be passed as a Map to the `createEntityManagerFactory(String persistenceUnitName, Map properties)` method. 
I'm happy to provide a PR.

I thought on simply for now making an alternate JPAPlugin that overrides the onStart, however, I'm not sure how exactly the dependencies work with internal modules, i.e. the 'voodoo' that allows this:

```scala
libraryDependencies ++= Seq(
  javaJpa
)
```

to work, instead of something like:

```scala
libraryDependencies ++= Seq(
  "org.hibernate" % "hibernate-entitymanager" % "4.2.19.Final",
```

If you do not agree with this change, it would be great if you could point to the docs on how this 'magic' works or give some kind of hint, so that I won't take too long to do that JPAPluginV2 class

For now, and because it's easier, now I just copy paste the `<persistence-unit>` definition in persistence.xml, name it something else, as well as the DataSource, and then add something like:

```scala
   additionalConf.put("db.default.jndiName", "TestDS");
        additionalConf.put("jpa.default", "defaultTestPersistenceUnit");
```

when running the `fakeApplication` but of course, it is prone to errors as it is avoidably not very DRY.

**Comment by jroper** [comment]
Hi @joantune, the codebase to start with discussing this is Play master, not Play 2.3.x, since that's where the change is going to go first, and then it may be backported if necessary.  On Play master, we use DI, and there are probably some ways to solve this already, it's probably simply a matter of providing more convenience.

**Comment by cchantep** [comment]
Hi, I guess this should better be first discussed on the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework). Best regards.

**Comment by joantune** [comment]
To prevent future waste of time, could you please state that 'Issue' requirement (i.e. an issue only applies to the 'master' branch) here: https://github.com/playframework/playframework/blob/master/CONTRIBUTING.md ? 

I would also appreciate if any pointers can be given on how I could extend the ```JPAPlugin```, and then include it on the ```build.sbt```. No final solutions are needed, pointers as in documentation webpages or even simply terms to google are appreciated (i.e. is this an SBT thing, how does Play know that the JPAPlugin is called javaJPA?).

Also, perhaps a pointer of what should be in the MailingList, and what should be an Issue on the CONTRIBUTING.md might be good..
