### ISSUE TITLE
CacheApi getOrElse does not perform atomically

### ISSUE THREAD

**Issue by jCalamari** [playframework/playframework#4972]
How about replacing it with `putIfAbsent`? 

```
def getOrElse[A: ClassTag](key: String, expiration: Duration)(orElse: => A) = {
    get[A](key).getOrElse {
      val value = orElse
      set(key, value, expiration)
      value
    }
  }
```

Does setting value here make sense? Default implementation in `java.util.concurrent.ConcurrentMap` does not set the value.

```
@Override
public default V getOrDefault(Object key, V defaultValue) {
    V v;
    return ((v = get(key)) != null) ? v : defaultValue;
}
```

**Comment by marcospereira** [comment]
This is a kind of memoization, I think. Maybe we can just rename the method to `getOrElseUpdate` (like in [scala.collection.mutable.Map](http://www.scala-lang.org/api/current/index.html#scala.collection.mutable.Map@getOrElseUpdate\(key:A,op:=>B\):B) or keep this method, remove this memoization and then add a new `getOrElseUpdate`.

What do you think?

**Comment by jroper** [comment]
It depends on the cache implementation as to whether its atomic or not - if a cache provides an atomic update method, it can override the `getOrElse` with something that's atomic.

**Comment by jCalamari** [comment]
`getOrElse` sounds to me as `read only` method, thus I would imagine the method as follows, which is consistent with `ConcurrentMap`:

```
def getOrElse[A: ClassTag](key: String, expiration: Duration)(orElse: => A) = {
  get[A](key).getOrElse(orElse)
}
```
> It depends on the cache implementation as to whether its atomic or not - if a cache provides an atomic update method, it can override the getOrElse with something that's atomic.

`Ehcache` provides `putIfAbsent` which is atomic.

**Comment by gmethvin** [comment]
I agree about the naming. `getOrElse

**Comment by EnverOsmanov** [comment]
I think the issue could be closed as `CacheApi` became deprecated.

**Comment by marcospereira** [comment]
@EnverOsmanov I've submitted #6882 after inspecting the current APIs to ensure that we can really close this issue. #6882 just fix a small issue I've found.

**Comment by marcospereira** [comment]
Closing since #6882 was already merged.
