### ISSUE TITLE
Json inception breaks on classes defined inside traits (was: Json inception macros fail with slick-codegen generated model classes)

### ISSUE THREAD

**Issue by asazernik** [playframework/playframework#4974]
As reported by several people (including me) on [the mailing list](https://groups.google.com/forum/#!topic/play-framework/yz6_Wh5EYVY), the JSON inception macros throw a type-check error on compilation, as follows:

```
[error] /opt/parsley/app/models/JsonConversions.scala:10: type mismatch;
[error]  found   : play.api.libs.json.Reads[Tables.this.SuppliersRow]
[error]  required: play.api.libs.json.Reads[models.Tables.SuppliersRow]
[error]  Note: implicit value supplierFormat is not applicable here because it comes after the application point and it lacks an explicit result type
[error]   implicit val supplierFormat = Json.reads[SuppliersRow]
[error]                                           ^
```

For reference, the code that throws this error is:

```scala
package models

import play.api.libs.json._
import play.api.libs.functional.syntax._

import Tables.SuppliersRow

object JsonConversions extends DefaultReads {
  implicit val supplierFormat = Json.reads[SuppliersRow]

}
```

(The original report from the mailing list was with the `formats[SomeType]` macro, but that included another type mismatch between Format and OFormat; the error in the `Reads[SomeType]` case is more minimal.)

This is a pretty bad pain point, since Slick Codegen classes are both a big feature of the recommended DB access library for Play, and since these tend to be some of the largest case classes in most applications (and hence the most painful to hand-code Format, Reads, and Writes for).

**Comment by maylukas** [comment]
+1

**Comment by nafg** [comment]
+100

FWIW, the latest argonaut's macro works on case classes from slick codegen.

TBH though, I think slick should keep the case classes out of the trait.

**Comment by hepin1989** [comment]
I change to code generator to generate the formats code just besides it,then that works.
I think this issue is relate this https://github.com/slick/slick/issues/1189
@asazernik

**Comment by asazernik** [comment]
@hepin1989 Yeah, definitely related to slick/slick#1189 (and slick/slick#1382, which you also found) is a workaround for this issue. And I think your and @fabriziofortino's workarounds demonstrate pretty clearly that the issue is with classes inside traits, as does this toy example I tried after reading those.

```scala
trait test {
    case class serializable(thingOne: String, thingTwo: Int)
}

object test extends test

object otherObj {
    implicit val testFormat: Format[test.serializable] = Json.format[serializable]
}
```

Having `object otherObj` extend the `test` trait doesn't change anything; pulling the serializable class out to the top level makes this work.

Updating the title to reflect this.

**Comment by cchantep** [comment]
As inactive, closing for now. A new/updated report can be done if reproduced on the latest release.

**Comment by mirikle** [comment]
Reporting: issue reproduced in latest release play 2.5 with slick-codegen 3.1.1.

**Comment by mrwillis** [comment]
Is there any workaround here?
