### ISSUE TITLE
ProdServerStart.main From Another Project Not Serving WebJar Assets

### ISSUE THREAD

**Issue by cretz** [playframework/playframework#4978]
I run a separate project that does acceptance tests and I want to start the Play server internally and it works fine with ProdServerStart.main except my route for Assets that is:

```
GET   /assets/*file                     controllers.Assets.at(path="/public", file)
```

I just get an "Action not found" whereas using `sbt run` I get served the proper WebJar asset. I can provide a tiny example for this if necessary, but it's basically just project A w/ that route and a WebJar and project B depending on project A and running ProdServerStart.main. I mentioned this on the mailing list: https://groups.google.com/forum/#!topic/play-framework/A9J9cIvLeM0

**Comment by evshi** [comment]
Hi cretz, were you able to find a solution to your issue? I am running into the same problem.

**Comment by evshi** [comment]
I think the correct approach (depending on what you need the production server for) is outlined here: https://www.playframework.com/documentation/2.4.x/Production#Running-a-production-server-in-place. 
You should stage the project and use the generated script to start the server, using the config file and arguments to stub external dependencies. If anyone has a better solution, let me know!

**Comment by cretz** [comment]
@evshi - While that may be one way to run the server it should not be the only way. There are a myriad of use cases for `ProdServerStart.main` and it was written to support this use case, so there is still a bug here.

**Comment by cchantep** [comment]
Closing as inactive. The [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) is available for discussion.

**Comment by cretz** [comment]
@cchantep - The mailing list was tried first and was unresponsive for what I consider a bug. Inactive bugs are still bugs.

**Comment by cchantep** [comment]
Unconfirmed issue is not bug
