### ISSUE TITLE
[2.4.X] Reverse router prefix, regression from 2.3.x

### ISSUE THREAD

**Issue by gmarti** [playframework/playframework#4984]
There is a bug in the reverse router with sub packages that is not in 2.3.x

In a controller if trying to access the reverse router just after creation of the controller, the prefix is wrong and routes are wrong.

So if you write this :

```scala
class Example extends Controller{
  *val* Home = Redirect(controllers.example.routes.Example.index)
```

It will not work, and Home will not redirect you to the right url.

This simple test show the bug :

```scala
 *val* prefix1 = example.RoutesPrefix.prefix

  *def* prefix2 = example.RoutesPrefix.prefix

  def index = Action {
    Ok(views.html.index(s"p1 : $prefix1 p2 : $prefix2"))
  }
```

Will print : "p1 : / p2 :  /example"

The prefix is not the same if using a val, because the router prefix is calculated after the controller creation.

## Example repository :

I have created an example in [github repository](https://github.com/gmarti/play-bug-10082015)

## Require :

Sbt 0.13.8
Play 2.4.2
Scala 2.11.6
Java 1.8.51

## Problem in the example application : 

http://127.0.0.1:9000/example/test redirect you to http://127.0.0.1:9000/ but should redirect to http://127.0.0.1:9000/example/

http://127.0.0.1:9000/example/ show you the 2 prefixes and they are not the same.

**Comment by pycloux** [comment]
Hi @gmarti 
Please see #4977 this is a known issue.
I am suggesting a workaround which should work in most of the cases (at least for me :-)).
Regards,
PYC

**Comment by gmarti** [comment]
Thank you, i changed from :
```scala
*val* Home = Redirect(controllers.example.routes.Example.index)
//to  
*def* Home = Redirect(controllers.example.routes.Example.index)
```
