### ISSUE TITLE
[2.4.2] RoutesGenerator namespace woes

### ISSUE THREAD

**Issue by avdv** [playframework/playframework#4990]
Hi.

I'm using the InjectedRoutesGenerator.

In `conf/data.routes`:
```
GET /       data.controllers.Root.index()

GET /foo    controllers.Foo.index()
```

This generates code like this in Routes.scala:

```scala
package data

class Routes(
  override val errorHandler: play.api.http.HttpErrorHandler, 
  Root_0: data.controllers.Root,
  Foo_1: controllers.Foo,
  val prefix: String
) extends GeneratedRouter {
...
}
```

This produces a compile error at line 3 of the data.routes file, that "type Foo is not a member of package data.controllers".

Changing it to:

```
GET /       data.controllers.Root.index()

GET /foo    _root_.controllers.Foo.index()
```

generates a different error:

```
conf/data.routes:3: _root_ is already defined as package _root_ in package object <none>
[error] GET /foo    _root_.controllers.Foo.index()
```

Because of this code in `ReverseRoutes.scala`:

```scala
// @LINE:3
package _root_.controllers {
   // ...
}
```

Furthermore, in `routes.java` the "\_root\_" prefix sneaked in too:

```java
package _root_.controllers;
```

**Comment by jroper** [comment]
The first situation - I don't think there's much we can or should do about that.  The second, we could support that by checking for and stripping `_root_` from the package name when it shouldn't be there.

But in the meantime, I would recommend calling your routes file `data.router.routes`.

**Comment by cchantep** [comment]
I guess this can rather be discussed on the MailingList. Best regards.

**Comment by MattRMcFarland** [comment]
A workaround is presented below:

So we just ran into this issue in our application. We were trying to use the `_root_.controllers.Assets` resources in a submodule routing file. This was conflicting with the reverse routes `_root_.controllers` package as mentioned above.

@jaliss, a teammate, figured out a simple solution however. You can create a `Assets` controller in the subproject's `controllers` directory and simply extend Play's `Assets` controller. Then you can route to `modulename.controllers.Assets`. Here's an example of that extended Assets controller.

https://github.com/jaliss/securesocial/blob/master/module-code/app/securesocial/controllers/Assets.scala#L3****
