### ISSUE TITLE
Allow external implementation of Java PathBindable

### ISSUE THREAD

**Issue by sentolacco** [playframework/playframework#4992]
As far as I can see, there is no way of implementing the [Java PathBindable](https://github.com/playframework/playframework/blob/5d7adcbc246323310f6c9a9ef26555902e0ba3dc/framework/src/play/src/main/java/play/mvc/PathBindable.java) Interface other than with the class to bind. This prevents the implementation of wrapper binders, i.e. for model classes which cannot be changed.

In the [history](https://github.com/playframework/playframework/commit/6b32bc53fc3ca47e696e6669a3b8e7e3c9e48147) I can see, that this change was introduced, when tests and documentation were added, but I do not see any reason, why this change was performed. Did I miss something?

Changing the Interface definition back from
```
public interface PathBindable<T extends PathBindable<T>>
```
to
```
public interface PathBindable<T>
```
should allow to implement wrapper binders again.

The same might be true for [Java QueryStringBindable](https://github.com/playframework/playframework/blob/8b6c8242a8e923d25bba40b902a84398ab1cc178/framework/src/play/src/main/java/play/mvc/QueryStringBindable.java)

**Comment by jroper** [comment]
The problem with that is that Play uses implicit resolution to find path bindables - but that's a Scala feature, it doesn't exist in Java.  So, although you *could* implement a path bindable in Java for another type, there would be no way to get Play to actually use it.  This is why the bound type has to implement `PathBindable`.
