### ISSUE TITLE
2.4.2 No EntityManager found on first request randomly

### ISSUE THREAD

**Issue by michalzubkowicz** [playframework/playframework#5000]
Sometimes i've got No EntityManager, when I repeat request (with same data) it's ok. 

Can anybody point me to where I should search to make case more repeatable because now it's too random to make correct bug report. 

Of course action is annotated with @play.db.jpa.Transactional

**Comment by marcospereira** [comment]
Hi @michalzubkowicz, thanks for the feedback. However, it would be better if this kind of problems could be discussed first in the [play mailing list](https://groups.google.com/forum/#!forum/play-framework). You can also please add the stack trace to discussion.
