### ISSUE TITLE
[Play 2.3.x] Remove logback.xml from src/main/resources

### ISSUE THREAD

**Issue by billoneil** [playframework/playframework#5007]
This is a major inconvenience having play overwrite custom logback settings.  I was happy to see this was fixed in 2.4 however we are not ready to upgrade to Java8.  Its very disappointing to see this file lingering around for several versions.

**Comment by jimdickinson** [comment]
Yes - please backport https://github.com/playframework/playframework/pull/1448

:+1:

**Comment by wsargent** [comment]
Closing -- this is fixed in 2.4 / 2.5.
