### ISSUE TITLE
FakeApplication (scala): add ability to specify override modules

### ISSUE THREAD

**Issue by thesamet** [playframework/playframework#5018]
Currently FakeApplication does not allow the caller to specify GuicableModules that can be passed to the GuicableApplicationBuilder.

This is useful when certain functional tests require customized modules that override functionality in the application's default module. Although it's easy to to create Application instances easily using GuiceApplicationBuilder, sometimes a FakeApplication instance is needed (for example for OneAppPerTest)

**Comment by jroper** [comment]
`FakeApplication` will soon be deprecated, and then removed.  New code should use `GuiceApplicationBuilder`, and the play scalatest support (which we don't maintain) should be updated to use `Application`, not `FakeApplication`.
