### ISSUE TITLE
sub-project assets requireJS not working play 2.3.10

### ISSUE THREAD

**Issue by umbreak** [playframework/playframework#5019]
I have 3 modules `common`, `frontend` and `backend` (frontend and backend dependsOn common). 

common project contains public assets which are recognized by requireJS and they work correctly when running as `activator start`.

However, the public assets in the project frontend (for example) are not generated and not accessible. When requireJS is not used, that works correctly.

The assets for frontend have been added as the [Documentation](https://www.playframework.com/documentation/2.3.x/SBTSubProjects#Assets-and-controller-classes-should-be-all-defined-in-the-controllers.admin-package) states.

**Comment by cchantep** [comment]
Hi, please use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask questions/for help. Best regards.
