### ISSUE TITLE
[2.4] Cannot use custom logfile

### ISSUE THREAD

**Issue by mariussoutier** [playframework/playframework#5028]
Specifying a custom logfile as per [documentation](https://www.playframework.com/documentation/2.4.x/ProductionConfiguration#Logging-configuration) doesn't seem to work for me. In dev mode, some loggers are completely ignored. In testProd mode the logger work fine but a custom log file is not used (only the settings from logback.xml).

I have created this example project to illustrate the issue:
https://github.com/mariussoutier/play-logger-probs

**Comment by nlochschmidt** [comment]
I think this is only the case when using compile-time DI. Attaching a debugger shows that [`Logger.init()`](https://github.com/playframework/playframework/blob/2b5f708d5cf912af4eb8410a2534ce298a4e54cb/framework/src/play/src/main/scala/play/api/Logger.scala#L198-L203) gets called which configures the logger using the fallback configurations `logback-play-{dev|prod}.xml`. Afterwards I expected [`Logger.configure(Environment)`](https://github.com/playframework/playframework/blob/2b5f708d5cf912af4eb8410a2534ce298a4e54cb/framework/src/play/src/main/scala/play/api/Logger.scala#L208) to be called but it is not. 

By the way, when using runtime DI the Logger is configured from the [`GuiceApplicationBuilder. applicationModule()`](https://github.com/playframework/playframework/blob/65a99e9095f262e8027c64bd539cb2b654f4de86/framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala#L73).

**Comment by yanns** [comment]
@mariussoutier whould that help: https://github.com/playframework/playframework/pull/4570 ?

**Comment by mariussoutier** [comment]
@nlochschmidt @yanns Thanks guys, calling `Logger.configure(environment)` does the trick.
