### ISSUE TITLE
What do I need to import to reference JPAApi?

### ISSUE THREAD

**Issue by prettyvoid** [playframework/playframework#5030]
This is my build.sbt
```
name := "untitled"

version := "1.0"

lazy val `untitled` = (project in file(".")).enablePlugins(PlayJava)

scalaVersion := "2.11.7"

libraryDependencies ++= Seq(javaJpa.exclude("org.hibernate.javax.persistence", "hibernate-jpa-2.0-api"),
  "org.hibernate" % "hibernate-entitymanager" % "4.3.5.Final",
  javaJdbc , cache , javaWs , "mysql" % "mysql-connector-java" % "5.1.36")

unmanagedResourceDirectories in Test <+=  baseDirectory ( _ /"target/web/public/test" )  
```
I want to use Hibernate with Play Framework 2.4.2. My plugins.sbt:

`addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.2")`
I'm trying to access JPAApi but the IDE isn't recognizing it. Any idea what imports I'm missing?

Apologize if this sounds trivial but I just spent a couple of hours trying to achieve something to no avail.

**Comment by cchantep** [comment]
Hi, please use the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask question (rather than this issue tracker). Best regards
