### ISSUE TITLE
Play @Transactional does not work, clarification needed please

### ISSUE THREAD

**Issue by TigranTsat** [playframework/playframework#5032]
Hello,

I am trying to use @Transactional annotation on static service layer method and it does not work. I think that I misunderstood something in docs.
https://www.playframework.com/documentation/2.1.x/JavaEbean Does it means that this annotation will work on any static method or only action? What is "action" and how it is different from static method?

Code snippet below. It works fine, when I explicitly declare beginTransaction, etc. But does not work with annotation.

@Transactional
	public static Poi createPoi(PoiModify poiModifyObject, String ownerUUID) {
		// Ebean.beginTransaction();
		try {
			// Ebean.commitTransaction();
			return poiToCreate;
		} finally {
			// Ebean.endTransaction();
		}
	}

**Comment by cchantep** [comment]
Hi, please use the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask such questions. Best regards.
