### ISSUE TITLE
get and post data concatinated if accessed in a @Before filter in 1.3.1

### ISSUE THREAD

**Issue by alexanderkjall** [playframework/playframework#5033]
If you use request.params.get() to access a field that is sent to the service as both GET and POST then the content is concatinated with a ", " in play 1.3.1, and it wasn't in play 1.2.3.

If you instead use request.get().params.data.get() then the data isn't concatinated.

Here is a test case class:

```java
package controllers;

import play.mvc.*;

public class Bug extends Controller {

    @Before
    protected static void before() {
        //request.params.get("menuId");

        if (request.params.data.get("menuId") != null) {
            System.out.println(request.params.data.get("menuId")[0]);
        }
    }

    public static void index() {
        render();
    }

    public static void bug(String type) {
        renderText(
            "type: " + type +
            "<br>\nrequest.params.get(type): " + request.params.get("type") +
            // "<br>request.params.get(type): " + request.params.get("type") +
            "<br>\nrequest.params.get(abc): " + request.params.get("abc") + "\n"
        );
    }
}
```

output with line 9 commented out:
```bash
$ curl --data "type=test" localhost:8888/Bug/bug?type=abc 
type: abc<br>
request.params.get(type): abc<br>
request.params.get(abc): null
```

output with line 9 commented in:
```bash
$ curl --data "type=test" localhost:8888/Bug/bug?type=abc 
type: abc, test<br>
request.params.get(type): abc<br>
request.params.get(abc): null
```

**Comment by gmethvin** [comment]
@alexanderkjall This tracker is for play 2.x. You can report play 1.x bugs here: https://play.lighthouseapp.com

**Comment by alexanderkjall** [comment]
Ticket created here: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1977-get-and-post-data-concatinated-if-accessed-in-a-before-filter-in-131

(in case of someone else having the same problem and find this by google)
