### ISSUE TITLE
[Play-Json] Make type classes serialisable

### ISSUE THREAD

**Issue by crakjie** [playframework/playframework#5043]
Because apache-spark need to have every thing serializable it's could be a great enhancement if Writers Reads and Formats are serializable. 

It will allow play-json to be easily use in apache-spark.

**Comment by cchantep** [comment]
Hi, please first ask on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework). Best regards.

**Comment by jroper** [comment]
I actually had a go at doing this before, I got blocked on this issue:

https://issues.scala-lang.org/browse/SI-9363

There are a number of other issues, for example, Java datetime serializers aren't serializable, so if you have dates in your JSON, your reads/writes won't be serializable.

A simple work around is to do something like this:

```scala
def lazyReads[T](r: => Reads[T]): Reads[T] = new Reads[T] with Serializable {
  @transient private lazy val lr = r
  def reads(json: JsValue) = lr.reads(json)
}

case class User(...)
object User {
  implicit val reads = lazyReads(Json.reads[User])
}
```

Then wrap the reads you're capturing in `lazyReads` (and you can do the same for writes/formats).  Of course, the best option is to simply not send your reads (which can be quite large) across the wire, generally they're not needed.

**Comment by crakjie** [comment]
Thanks for the hint.

Yes It's possible to not send writes/reads, tipicaly by specifing the type inside de worker.
But is a lose of genericity :/

And event if the read/write is havy weight it just send once.

I have tried ti have wrapper without succes, I will try your wrapper thx



Envoyé de mon iPhone

**Comment by caeus** [comment]
Sorry to bother, but I tried this wrapper and it worked. But know I'm itching because I don't understand why it worked. Could you explain?
