### ISSUE TITLE
Java multipart/form-data custom file part handling

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#5044]
It should be possible for Java users to define a custom body parser for multipart/form-data handling that allows handling file parts using Akka streams.

**Comment by wsargent** [comment]
@jroper well, it's possible.   Added https://github.com/wsargent/play-fileupload-java as an example project.

**Comment by mkurz** [comment]
I think if we backport #6369 this would be fixed.

**Comment by schmitch** [comment]
Closed via #6394
