### ISSUE TITLE
[2.4.X] Play doesn't start as SBT submodule

### ISSUE THREAD

**Issue by promanenko** [playframework/playframework#5046]
When I run Play as SBT submodule with a command: `activator "project rest" "run"`

I get the following error:

[warn] Run 'evicted' to see detailed eviction warnings
[error] scala.pickling.PicklingException: Not a primitive: scala.Nothing, found JNothing
[error] 	at sbt.serialization.json.VerifyingJSONPickleReader.sbt$serialization$json$VerifyingJSONPickleReader$$unpickleHelper$1(JSONPickleFormat.scala:367)
[error] 	at sbt.serialization.json.VerifyingJSONPickleReader.readPrimitive(JSONPickleFormat.scala:373)
[error] 	at scala.pickling.pickler.PrimitivePickler.unpickle(Primitives.scala:28)
[error] 	at play.forkrun.protocol.Serializers$PlayForkrunProtocolForkConfigUnpickler1$2$.unpickle(Serializers.scala:73)
[error] 	at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
[error] 	at play.forkrun.protocol.Serializers$PlayForkrunProtocolForkConfigUnpickler1$2$.unpickleEntry(Serializers.scala:73)
[error] 	at scala.pickling.functions$.unpickle(functions.scala:11)
[error] 	at sbt.serialization.JsonValue$$anonfun$parse$1.apply(SerializedValue.scala:104)
[error] 	at scala.util.Try$.apply(Try.scala:161)
[error] 	at sbt.serialization.JsonValue.parse(SerializedValue.scala:104)
[error] 	at sbt.protocol.BuildValue.value(Values.scala:11)
[error] 	at sbt.protocol.TaskSuccess.resultWithCustomThrowable(Values.scala:65)
[error] 	at sbt.protocol.TaskResult$class.result(Values.scala:56)
[error] 	at sbt.protocol.TaskSuccess.result(Values.scala:62)
[error] 	at play.forkrun.ForkRun$$anonfun$settingUp$1.applyOrElse(ForkRun.scala:165)
[error] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
[error] 	at play.forkrun.ForkRun.aroundReceive(ForkRun.scala:152)
[error] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[error] 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[error] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[error] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Play fork run has failed due to:
[error] scala.pickling.PicklingException: error in unpickle of primitive unpickler 'java.lang.Integer':
[error] tag in unpickle: 'scala.Nothing'
[error] message:
[error] Not a primitive: scala.Nothing, found JNothing
[error] 	at scala.pickling.pickler.PrimitivePickler.unpickle(Primitives.scala:31)
[error] 	at play.forkrun.protocol.Serializers$PlayForkrunProtocolForkConfigUnpickler1$2$.unpickle(Serializers.scala:73)
[error] 	at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
[error] 	at play.forkrun.protocol.Serializers$PlayForkrunProtocolForkConfigUnpickler1$2$.unpickleEntry(Serializers.scala:73)
[error] 	at scala.pickling.functions$.unpickle(functions.scala:11)
[error] 	at sbt.serialization.JsonValue$$anonfun$parse$1.apply(SerializedValue.scala:104)
[error] 	at scala.util.Try$.apply(Try.scala:161)
[error] 	at sbt.serialization.JsonValue.parse(SerializedValue.scala:104)
[error] 	at sbt.protocol.BuildValue.value(Values.scala:11)
[error] 	at sbt.protocol.TaskSuccess.resultWithCustomThrowable(Values.scala:65)
[error] 	at sbt.protocol.TaskResult$class.result(Values.scala:56)
[error] 	at sbt.protocol.TaskSuccess.result(Values.scala:62)
[error] 	at play.forkrun.ForkRun$$anonfun$settingUp$1.applyOrElse(ForkRun.scala:165)
[error] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
[error] 	at play.forkrun.ForkRun.aroundReceive(ForkRun.scala:152)
[error] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[error] 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[error] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[error] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
^C[info] Stopping Play fork run ...
[info] JVM exiting, shutting down Play fork run ...
[info] Play fork run already stopped ...
[info] Forked Play process exited with status: 130

root **build.sbt**
```
name := "xxx"

version := "1.0-SNAPSHOT"

scalaVersion := "2.10.4"

lazy val root = project.in(file("."))
  .aggregate(common, feeder, rest, spark)

lazy val common = project.in(file("common"))

lazy val feeder = project.in(file("feeder")).dependsOn(common)

lazy val rest = project.in(file("rest")).dependsOn(common)
                                .enablePlugins(PlayScala)
                                .settings(fork in run := true)

lazy val spark = project.in(file("spark-processing")).dependsOn(common)
```
Play submodule's **build.sbt**

```
name := "dynamic-pricing-rest"

version := "1.0-SNAPSHOT"

libraryDependencies ++= Seq(
  "com.datastax.cassandra" % "cassandra-driver-core" % "2.1.2"
)
```

**Comment by cchantep** [comment]
Hi, please first ask question on the [user MailingList](https://groups.google.com/forum/#!forum/play-framework). Then if an issue about Play is confirmed, a ticket can be raised in this issue tracker. Best regards.

**Comment by themikejones** [comment]
Ran into the same issue in both play 2.4 and play 2.5 recently so this is still an issue.  Adding the Play Scala plugin to the aggregate root project (only necessary to get run in fork operational) worked for me.  YMMV

**Comment by japgolly** [comment]
Any advice? I've got this issue now.

**Comment by cchantep** [comment]
Please first ask on the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework)

**Comment by themikejones** [comment]
@japgolly,
try adding the play plugin to the top level aggregate project...

`lazy val root = project.in(file("."))
  .aggregate(common, feeder, rest, spark)
  .enablePlugins(PlayScala)`
