### ISSUE TITLE
[Request | Java] Enhance the CacheApi interface by increment/decrement methods

### ISSUE THREAD

**Issue by cdraeger** [playframework/playframework#5048]
The [CacheApi](https://playframework.com/documentation/2.4.x/api/java/play/cache/CacheApi.html) interface ([on GitHub](https://github.com/playframework/playframework/blob/5d7adcbc246323310f6c9a9ef26555902e0ba3dc/framework/src/play-cache/src/main/java/play/cache/CacheApi.java)) currently offers only very basic commands.

However, there are two important commands that I'm missing: `increment` and `decrement`. Of course I've read the documentation which says the API is intentionally minimal, but using more advanced methods would require a plugin instead of just injecting a custom implementation, so just using the interface is more difficult. I believe counters are so essential that adding appropriate methods to the interface would be justified.

If counting is handled in code with normal `get` and `set` methods, we are more likely to run into race conditions, especially if there are several Play instances with access to the same (or replicated) cache instance (e.g. when using a load balancer). I think atomic increment/decrement commands offered by most cache implementations should be used instead if available (see e.g. the [INCR](http://redis.io/commands/incr) and [DECR](http://redis.io/commands/decr) commands by Redis, or the [Counter](http://ehcache.org/apidocs/2.9/index.html?net/sf/ehcache/util/counter/Counter.html) by Ehcache). Expiration should be included just like when using `set`.

An example implementation could be:

``` java
public interface CacheApi {

    // removed existent methods for a cleaner showcase

    default void increment(String key, int expiration) {
      increment(key, 1, expiration);
    }

    default void increment(String key) {
      increment(key, 1);
    }

    default void decrement(String key, int expiration) {
      decrement(key, 1, expiration);
    }

    default void decrement(String key) {
      decrement(key, 1);
    }

    public void increment(String key, long amount, int expiration);

    public void increment(String key, long amount);

    public void decrement(String key, long amount, int expiration);

    public void decrement(String key, long amount);
}
```

Any thoughts on this? Worries about compatibility issues could be resolved by utilizing default implementations, using just `set`... that would work for every cache implementation.

**Comment by marcospereira** [comment]
As far as I know, Caffeine (which is the new default cache framework used by Play) does not support counters. This explains why we keeping the API small is the right decision for Play. Summoning @ben-manes to confirm that. :-D

Other can provide extensions of the cache API with such methods, but I think this is now beyond the scope of what we have for this API.

**Comment by ben-manes** [comment]
I would agree counters are out of scope for a local, in-memory cache. In that case you can be optimistic by using Java's `AtomicLong` or `LongAdder` if accounting for races, or use a `Map.compute` with a `Long` if pessimistic. The use of atomic computations is quite powerful and flexible, so we leave such things to users to work out.

A remote or distributed cache might make it a first class feature to leverage network optimizations. I think that being available in Redis makes sense, and Ehcache's offering is perhaps due distributed caching being a commercial feature. However remote caches don't offer atomic computations, so first class support is a requirement for these cases.

I don't think there is a good way to make a universal API that fits everyone. What Play! finds most valuable should be first class, and should have a recommended strategy for extensions (second class). It sounds like that's likely to use those APIs directly and not rely on this basic abstraction, which is a fair stance.
