### ISSUE TITLE
HTTPS support for Java embedded Play server

### ISSUE THREAD

**Issue by oustriem** [playframework/playframework#5059]
According to the documentation https://www.playframework.com/documentation/2.4.x/JavaEmbeddingPlay, we tried to start an embedded Play server in a Java application with HTTPS.
```java
httpServer = Server.forRouter(routingDsl, mode, httpPort);
```
Unfortunately, it seems that the JavaServerHelper only provides the HTTP port to be set, but not the HTTPS (variable sslPort).
Please extend the Java API with the possibility to start the Play server with HTTPS. Many thanks in advance!

**Comment by benmccann** [comment]
Yes, good call. Here's the source for that file in case you want to send a PR

https://github.com/playframework/playframework/blob/master/framework/src/play-server/src/main/java/play/server/Server.java

**Comment by oustriem** [comment]
Thanks for your answer. Unfortunately, we decided not to use Play (due to another reason) and that is why I have no capacities for a PR.

**Comment by eboto** [comment]
Issue seemed like a low-hanging fruit...

**Comment by benmccann** [comment]
Thanks for the PR @eboto !

**Comment by eboto** [comment]
No problem @benmccann !

Looks like the fix is merged, so feel free to close this issue =)
