### ISSUE TITLE
Support other types than String for Request tags values

### ISSUE THREAD

**Issue by knshiro** [playframework/playframework#5060]
Hi everyone,

I just made an experimental [http4s](http://http4s.org) backend for Play to be able to have reusable middlewares for different frameworks like Rack in Ruby. It's here https://github.com/knshiro/play-server-http4s
I started playing with middlewares and the problem comes when I want to inject attributes in the request.
In http4s they have a `Map[AttributeKey[_],Any]` to be able to inject type safely anything in their request where in Play there is only `Request.tags` of type `Map[String,String]`.
It's not really convenient for values of type `Iterable` so I "fixed" so far with this:
https://github.com/knshiro/play-server-http4s/commit/daf2db7e3208674c6f7471d0ef42569288c9e54d
I was wondering if it was of any interest to extend the tag type to `Map[String,Any]` or use something similar to http4s' `Request.attributes`.

**Comment by cchantep** [comment]
Hi @knshiro , for such discussion, please move to the [user MailingList](https://groups.google.com/forum/#!forum/play-framework). Best regards.

**Comment by jroper** [comment]
Play 3 will be changing the Play headers to be strongly typed - this will allow arbitrary internal attributes to be attached to requests as if they were headers.

**Comment by knshiro** [comment]
Awesome thanks!
