### ISSUE TITLE
There is a broken link on the play framework download page

### ISSUE THREAD

**Issue by bsebhat** [playframework/playframework#5061]
On the download page at https://www.playframework.com/download, the link to download the typesafe activator is httpss://downloads.typesafe.com/typesafe-activator/1.3.5/typesafe-activator-1.3.5-minimal.zip

It looks like the https protocol has an extra "s" in the link.  I had to remove the extra "s" to get file:
https://downloads.typesafe.com/typesafe-activator/1.3.5/typesafe-activator-1.3.5-minimal.zip

**Comment by cchantep** [comment]
You're right, thanks for reporting it.

**Comment by jroper** [comment]
Fixed in https://github.com/playframework/playframework.com/commit/99e59f52c4a2e015d83ddd73881714225eedbe1c.
