### ISSUE TITLE
Broken Links on Older Versions Downoad Page

### ISSUE THREAD

**Issue by shaleenx** [playframework/playframework#5063]
The download links for older pay releases at https://www.playframework.com/download#older-versions have 'httpss' instead of 'https' at most places. This needs to be changed in the website.

**Comment by adis-me** [comment]
Same as #5061?

**Comment by shaleenx** [comment]
@adis-me That is correct. Pardon Me.

**Comment by adis-me** [comment]
No problem, please close this issue
