### ISSUE TITLE
Play 2.4.3

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#5070]
I didn't see a changelog file in the source tree, so posting the changes here until I know where else to put them

Netty upgrade from 3.10.3 to 3.10.4
Akka-http upgrade from 1.0-RC2 to 1.0
Fixes for dev mode memory leaks
Fix packaging when externalizeResources or executableScriptName settings are used
Made Helpers.invokeWithContext static
Allow Authenticator for Security.Authenticated to be injected
Scala JSON Reads for java.time.Instant
Support for HikariCP connectionInitSql
Demoted akka initialization logging to debug level

**Comment by benmccann** [comment]
Ah, found [the changelog](https://www.playframework.com/changelog). I went through and tagged all the issues that were fixed with the 2.4.3 milestone since I see the tagged issues get linked to

https://github.com/playframework/playframework/issues?q=is%3Aclosed+milestone%3A2.4.3

**Comment by marcospereira** [comment]
Closing since Play 2.4.3 was already released.

@benmccann thank you for compiling the issues related with this release and also for made their titles more clear. ;-)
