### ISSUE TITLE
Can't run newly created app in IntelliJ IDEA: package org.junit does not exist

### ISSUE THREAD

**Issue by tomekceszke** [playframework/playframework#5080]
To reproduce just create new play application (activator new tcc3 play-java) and import it into IntelliJ IDEA.
Then run it using new SBT task (according to documentation).
Compilation completed with 11 errors and 1 warning: 
```
D:\Projects\tcc3\test\IntegrationTest.java
Error:(1, 1) java: package org.junit does not exist
Error:(8, 24) java: package org.junit does not exist
Error:(18, 6) java: cannot find symbol
  symbol:   class Test
  location: class IntegrationTest
Error:(23, 17) java: cannot find symbol
  symbol: method assertTrue(boolean)
D:\Projects\tcc3\test\ApplicationTest.java
...
```
Environment:
* Play: 2.4.3
* Java 1.8.0_51
* Idea 14.1.4 with bundled SBT

**Comment by cchantep** [comment]
Hi, please use the [user Mailing list](https://groups.google.com/forum/m/#!forum/play-framework) to ask for help (this tracker is for confirmed issue). Best regards.
