### ISSUE TITLE
Add and maintain support for Google App Engine

### ISSUE THREAD

**Issue by atrauzzi** [playframework/playframework#5085]
I've been creating applications for Google App Engine using other languages and environments and was interested in trying out Java & Scala on the platform.

There aren't too many frameworks (especially as modern and of the caliber of Play) that run on the JVM that also work on GAE.

Would love to see the Play Framework get some built in support for working on a google app engine.  Especially without the need of an external plugin of any type.

**Comment by jroper** [comment]
The problem with GAE is that its JVM is servlet based.  Play is not servlet based.  You can put Play on top of servlets, but that introduces the second problem, Play uses asynchronous IO, GAE provides Servlet 2.5, but the minimum servlet version needed to do asynchronous IO is Servlet 3.1.  Now, while you could bridge Play's asynchronous IO model on top of the Servlet API, doing so has major performance costs, and you lose a lot of the benefits of using Play when you do this.

Anyway, supporting specific platforms is not something that we want to do in the core of Play, these can and should be provided by external libraries, so as this is the issue tracker for the core of Play, I'm going to close this issue.

**Comment by atrauzzi** [comment]
Thanks for the info!  I'll try to advocate elsewhere and hopefully they can get something together for Servlet 3.1.
