### ISSUE TITLE
Json.format error if case class has 22 fields in Scala 2.11.7

### ISSUE THREAD

**Issue by vito-c** [playframework/playframework#5090]
I am using play framework 2.3.9 maybe this has been fixed in 2.4.0? Regardless the ticket referenced below was closed prematurely :)
`value apply is not a member of play.api.libs.functional.FunctionalBuilder[play.api.libs.json.OFormat]#CanBuild22`
https://github.com/playframework/playframework/issues/1141

**Comment by jroper** [comment]
Duplicate of #3174.
