### ISSUE TITLE
[Play 2.3.x] - Cached - An HTTP response(an image) cached by an authenticated user can not be retrieved from another browser

### ISSUE THREAD

**Issue by evanzeng** [playframework/playframework#5102]
I first login and show an image saved in a mongodb using the following code:

```
def showImage(id: String) = cached(id) {
  Action.async {
    val file = gridFS.find[JsObject, JSONReadFile](Json.obj("_id" -> id))
    serve[JsString, JSONReadFile](gridFS)(file, CONTENT_DISPOSITION_INLINE)
  }
}
```

The image is showed and cached both on my browser side and the server side. Then I try to show the image from another browser but the browser will wait until time out.

I guess play caches the 'resultWithHeaders' on the server side, and the cache can not be retrieved from another browser.

Is it possible to cache an HTTP response only on the client side?

**Comment by jroper** [comment]
I guess you're returning and caching an ephermal stream out of MongoDB - the first time the response is written out, that stream is consumed, on subsequent requests, the stream has already been consumed, so it returns nothing.  But, the code you're showing shows nothing about how the response is constructed, so I'm blind.

> Is it possible to cache an HTTP response only on the client side?

Yes, set an appropriate `Cache-Control` header, or set an `ETag` header and use in combination with `If-None-Match`.

If you have any further questions, ask them on the mailing list, the issue tracker isn't for questions.
