### ISSUE TITLE
Document Forwarded header handling

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#5115]
Play provides extensive support for handling `Forwarded` headers, but it's not documented.  It should be. 

Also, the forwarded default configuration is not in `reference.conf`.  It should be, so it can be documented there as well, and the code that loads it should depend on it being there rather than inserting its own defaults.

**Comment by estsauver** [comment]
Hi there! I'm going to take this on. It seems like there is some work that has been done to document the headers here: https://www.playframework.com/documentation/2.5.x/HTTPServer#Advanced-proxy-setting.

However, I don't think it's documented in the reference.conf in play-server. I'll both take a look to make sure the documentation is thorough and matches the code and add a reference configuration to the reference.conf file.

**Comment by wsargent** [comment]
Yep!  Closing.
