### ISSUE TITLE
Play 2.4.3. "name in Universal" ignored.

### ISSUE THREAD

**Issue by mikhalchenko-alexander** [playframework/playframework#5117]
In Play `2.3.6` with `build.sbt` containing
```
name := "some_app"
name in Universal := "my_app"
version := "1.0-SNAPSHOT"
```
`activator dist` generates `./target/universal/my_app.zip`

In `2.4.3` it generates `./target/universal/some_app-1.0-SNAPSHOT.zip` which is obviously has incorrect name. It seems that Play `2.4.3` completely ignores Universal config.
I want to:
a) Change .zip name in Universal configuration;
b) Remove version from .zip name.

**Comment by benmccann** [comment]
That's sbt-native-packager which is used for packaging. According to their docs it seems like that should work: http://www.scala-sbt.org/sbt-native-packager/formats/universal.html

**Comment by mikhalchenko-alexander** [comment]
Thanks, @benmccann. It seems that for new version of sbt-native-packager the correct setting is
`packageName in Universal := "my_app"` and not `name in Universal := "my_app"`. `name` seems to work in Play 2.3.x (I've tried 2.3.6 and 2.3.8). For Play 2.4.x correct field is `packageName`.
