### ISSUE TITLE
FakeRoutes is private and app.routes is deprecated?

### ISSUE THREAD

**Issue by Ciantic** [playframework/playframework#5119]
I'm trying to test my ErrorHandler with signature

```
class ApiErrorHandler @Inject() (
    env: Environment,
    config: Configuration,
    sourceMapper: OptionalSourceMapper,
    router: Provider[Router] // <-- Having problems with this
  ) extends DefaultHttpErrorHandler(env, config, sourceMapper, router) {
// ...
}
```

I've created a FakeApplication, but turns out it's property "routes" is deprecated, and saying I should create routes myself.

But the FakeRoutes is private class, I think it would work for me.

If there is another way to create Router in tests, I'd like to know

**Comment by cchantep** [comment]
Hi, please rather use the [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework) to ask for help. Best regards.

**Comment by Ciantic** [comment]
@cchantep this is not a ask for help. It's a bug report in a form of a question.

1. FakeApplication.routes is deprecated,
2. FakeRoutes is private

There is no way to mock routes.

**Comment by jroper** [comment]
Example of creating a router in tests:

https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala#L145

**Comment by Ciantic** [comment]
@jroper thanks

I'll paste my solution here if someone else is wondering how to replace `FakeApplication.routes` in their tests when migrating.

Apparently it is as simple as:

    val router = Router.from {
      case _ => Action(Results.Ok("Test"))
    }

And to make this complete, if you have a provider you can use:

    new Provider[Router]{ def get() = router }
