### ISSUE TITLE
Json.parse strange behavior

### ISSUE THREAD

**Issue by daron666** [playframework/playframework#5121]
Json parse has a signature:
```scala
    Json.parse(input: String): JsValue
```

So when I'm trying to parse some string, I wanna get JsString as JsValue, but instead I'm getting error:
```
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'value': was expecting ('true', 'false' or 'null')
```

But when I'm using :
```scala
    Json.toJson(input: String)
```
I'm getting JsString as a result. 

I think this maybe inconsistent behavior. I think it should return JsObject instead of JsValue, cause it may confuse somebody.
```scala
Json.parse(input: String): JsObject
```

**Comment by studiodev** [comment]
The root of a json object can be an `object` or an `array`. So it's not possible to return a `JsObject` when parsing a json, it can also be a `JsArray`.

The `toJson` return the most precise type (JsString, JsArray, JsObject, JsNumber...), but all these classes inherits JsValue.

**Comment by daron666** [comment]
But question is why Json.parse returns JsValue? JsString is also JsValue, but I can't parse raw strings.

And JavaDoc comment is a bit confusing. 

```scala
  /**
   * Parse a String representing a json, and return it as a JsValue.
   *
   * @param input a String to parse
   * @return the JsValue representing the string
   */
  def parse(input: String): JsValue = JacksonJson.parseJsValue(input)
```

**Comment by m-sp** [comment]
Well actually if you look at the spec there is no root, so therefore it is correct that you can parse a string

```
scala> Json.parse("\"value\"")
res1: play.api.libs.json.JsValue = "value"

```

works just fine for me, please note that you have to quote your string

**Comment by daron666** [comment]
Yeah. I knew it. But I suspected this behavior from Json.parse method. My word is about "unclear" method name and not about how to do it another way.

**Comment by cchantep** [comment]
I guess it's better to discuss that on the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) rather than on this issue tracker. Best regards.

**Comment by jroper** [comment]
The `Json.parse` method parses JSON represented as a String.  Here examples of valid JSON string representations:

```
{"foo":"bar"}
[1,2,3]
"value"
true
23.1
```

The are all valid JSON.  What you're passing is:

```
value
```

That's not valid JSON, so it fails to parse.
