### ISSUE TITLE
java.lang.ClassCastException: javassist.bytecode.InterfaceMethodrefInfo cannot be cast to javassist.bytecode.MethodrefInfo

### ISSUE THREAD

**Issue by rajeshetty** [playframework/playframework#5127]
Using Play 2.3.x and I see this error

java.lang.ClassCastException: javassist.bytecode.InterfaceMethodrefInfo cannot be cast to javassist.bytecode.MethodrefInfo

Found few places where everyone talking about it like below , but did not find the solution on this yet.

https://groups.google.com/forum/#!searchin/play-framework/https$3A$2F$2Fgithub.com$2Fjboss-javassist$2Fjavassist$2Fpull$2F10/play-framework/Oiqqk4SZr5Y/kYhv_tG_uqQJ

I have added 3.20 javassit in the build.sbt , even then it doesn't work.

Any idea how to solve this issue . apart from hunting down which java8 code is causing this  ?

-Thanks

**Comment by jroper** [comment]
You probably need to add the 3.20 javassist upgrade to `project/plugins.sbt`, since javassist is being used by sbt at compile time by an sbt plugin, not by your application at runtime.

**Comment by rajeshetty** [comment]
Example to upgrade javassist in plugins.sbt would be nice. Would you have that handy ?

**Comment by jroper** [comment]
```scala
libraryDependencies += "org.javassist" % "javassist" % "3.20.0-GA"
```
