### ISSUE TITLE
can't access uploaded files in 'dist' mode

### ISSUE THREAD

**Issue by ShaikhNargis** [playframework/playframework#5130]
Hi,
I have done all mandatory / required steps to run the project in 'dist' mode,though it is running perfectly,i can't access the files which i've uploaded in the same.
i can see the uploaded files,in 'my_project\bin\public' folder but not able to download it.
being newbie in play framework i would like to facilitate the users who have uploaded their files in the system to download the same.

**Comment by dotta** [comment]
Hi @ShaikhNargis, usage questions are better asked in the [play framework mailing list](https://groups.google.com/forum/#!forum/play-framework). I'm closing this ticket and kindly ask you to post your question there.

Cheers,
Mirco
