### ISSUE TITLE
The string auto-generated from routes has a `$` causing `scalac -Xlint` to complain

### ISSUE THREAD

**Issue by SRGOM** [playframework/playframework#5134]
Error: `conf/routes:115: possible missing interpolator: detected interpolated identifier $text`
Some of us like having the -Xlint option on but the false positives make it harder to glance at errors.

**Comment by jroper** [comment]
You can use `-Xlint:-warn-missing-interpolator` to turn it off.

**Comment by jroper** [comment]
Fixed in #5135.

**Comment by SRGOM** [comment]
Thanks for the tip and fix!

**Comment by caseyhoward** [comment]
I had to use -Xlint:-missing-interpolator not -Xlint:-warn-missing-interpolator
