### ISSUE TITLE
Java Routing DSL does not work with Java 1.8.0_51 onwards

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#5136]
Users see this error:

    java.lang.IllegalArgumentException: Don't know how to bind argument of type class net.jodah.typetools.TypeResolver$Unknown

The root cause is https://github.com/jhalterman/typetools/pull/10.

**Comment by bhilst-searshc** [comment]
Is there any workaround for this problem?

**Comment by mttdbrd** [comment]
@bhilst-searshc The "workaround" is to use 1.8.0_51 or earlier. But it looks like they've fixed it. The real question is, has this been backported to 2.4.x.
