### ISSUE TITLE
Play framework action composition goes not work for Promise<Result>

### ISSUE THREAD

**Issue by TigranTsat** [playframework/playframework#5143]
I am following that link (https://gist.github.com/richdougherty/8926339#file-resultexceptionhandlingaction-java) to create exception handling annotation.
It works perfectly fine with controller methods that return Result.
````
@SecureAction
@RestErrorHandlerAction
public static Result myCoolFoo() {
    // actions
   throw new OperationFailedException("Some failure");
}
```

But it does not work for method that returns promise.


	@SecureAction
	@RestErrorHandlerAction
	public static F.Promise<Result> suggestCity(String country, String cityNameToSearch) {
		F.Promise<WSResponse> suggestCityPromise = GeoCoderService.suggestCity(country, cityNameToSearch);
		F.Promise<Result> promiseOfResult = suggestCityPromise.map(new Function<WSResponse, Result>() {
			@Override
			public Result apply(WSResponse response) {
				String responseBody = response.getBody();
				if (response.getStatus() != 200) {
					LOG.warn("Error responseBody={}, status={} ", responseBody,
							response.getStatus());
					throw new OperationFailedException("Falure to geo search");
				}
				return ok(responseBody);
			}
		});
		return promiseOfResult;
	}

That's what is in stack trace and I do not see my action was called.


```
play.api.Application$$anon$1: Execution exception[[OperationFailedException: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:2.3.8]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.1.jar:na]
Caused by: controllers.composition.rest.OperationFailedException: null
	at controllers.api.GeoCoderController$1.apply(GeoCoderController.java:85) ~[classes/:na]
	at controllers.api.GeoCoderController$1.apply(GeoCoderController.java:78) ~[classes/:na]
	at play.core.j.FPromiseHelper$$anonfun$map$1.apply(FPromiseHelper.scala:98) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) ~[scala-library-2.11.1.jar:na]
	at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.1.jar:na]
```

Is that's an issue or handling exceptions from Promise is being done other way?
Thanks for help

**Comment by richdougherty** [comment]
This might be a better question for the mailing list, since it's probably not a core Play issue, but I do have a suggestion. What I suggest you do is debug the control flow from [the line where the delegate action is called](https://gist.github.com/richdougherty/8926339#file-resultexceptionhandlingaction-java-L11). Does the returned promise contain an exception, is it detected by the [call to recover](https://gist.github.com/richdougherty/8926339#file-resultexceptionhandlingaction-java-L12), etc?

**Comment by TigranTsat** [comment]
Looks like happen next stuff:
1. My handler is being called, but since exception is not throw right away, it finish execution.
2. Then play executes  "public Result apply()" method which throws exception and since there is no wrapping, exception is not handled.
Is it interesting that if I add recover to "promiseOfResult", recover will be called, but play will return standard error, instead of what is being told from handler.

**Comment by richdougherty** [comment]
I would expect the exception thrown by the handler to be thrown here:
https://gist.github.com/richdougherty/8926339#file-resultexceptionhandlingaction-java-L11
Does that happen?

Then the exception should be caught here:
https://gist.github.com/richdougherty/8926339#file-resultexceptionhandlingaction-java-L25
But it might not be caught if the exception if the wrong type. Does the catch block catch your OperationFailedException?

**Comment by TigranTsat** [comment]
I am not sure about this, but I think that it is NOT thrown. Because that's async block. Flow to initialize async block does not throw anything.
Exception is of right type. And it will work exactly as you described for non-async (the one that return Result or throw exception). 

In my case, it will return future, which when called will throw exception. Because of that nothing is thrown in delegate call.
