### ISSUE TITLE
Problem with session

### ISSUE THREAD

**Issue by alexbereza** [playframework/playframework#5145]
There is a problem with session. I've tried to create Authentication using Redirect(...).withSession but i've been redirected without session. The same problem description i found (http://www.frattv.com/scala-play-security-issue/). This problem was in version 2.2.1 and the problem still remains.

This is code which i'm using

<code><pre>
val isUser = [Some DB Query]
if (isUser.isDefined) {
    Redirect(routes.Application.index).withSession(request.session + ("user" -> authorization.email))
}
else
{
    Redirect(routes.Authenticate.login)
}
</pre></code>

Can somebody help with this? 

Thanks

**Comment by gmethvin** [comment]
Hi @alexbereza,

The best place to discuss this would be the [Play mailing list](https://groups.google.com/forum/#!forum/play-framework). If after discussing there you find that there is a legitimate bug, you can resubmit the issue.

**Comment by harveywi** [comment]
I think I might be affected by this as well (using Play 2.4.2).  Here is a link to discussion on the Google group:

https://groups.google.com/d/msg/play-framework/dl4kF3ssQ4Y/LK6FloUTCQAJ
