### ISSUE TITLE
Issue in play 2.4.3 and com.ning.http.client.multipart

### ISSUE THREAD

**Issue by kanchu1708** [playframework/playframework#5151]
my code 
import play.api._
import play.api.libs.ws._
import play.api.mvc._
//import javax.inject.Inject
import play.api.Play.current
import scala.concurrent.ExecutionContext.Implicits.global
import play.api.libs.ws.WSAuthScheme
import com.ning.http.client.AsyncHttpClient
import com.ning.http.client.multipart.FilePart
import com.ning.http.client.multipart.StringPart
import java.io.File
import org.apache.commons.codec.binary.Base64.encodeBase64

class Application extends Controller {

  def index = Action {
    Ok(views.html.index("Your new application is ready."))
  }

def postUpload=Action(parse.multipartFormData){request=>

   val groupingType= request.body.dataParts("Grouping type").mkString
    val email=request.body.dataParts("NotificationRecepients").mkString
    val custId=request.body.dataParts("CustomerId").mkString
    val custIdFinal:Int=custId.toInt

val url="mywebservice"
   request.body.file("file").map { file =>

  val file1=file.ref.file.getAbsolutePath;

  val fileName = file.filename 
    val contentType = file.contentType

 
     val user = "myUser";
      val password = "myPassword";

 val encodedCredentials =
      new String(encodeBase64("%s:%s".format(user, password).getBytes))

    val asyncHttpClient:AsyncHttpClient =WS.client.underlying
    val postBuilder = asyncHttpClient.preparePost(url)
    val builder = postBuilder
      .addHeader("Authorization", "Basic " + encodedCredentials)
      .addBodyPart(new StringPart("selectedGroupType", "Functional Grouping", "UTF-8"))
      .addBodyPart(new StringPart("mailRecipients", "kancgupt@cisco.com", "UTF-8"))
      .addBodyPart(new StringPart("selectedFile", "Sample_group_upload_file.xlsx", "UTF-8"))
      .addBodyPart(new FilePart("file",new File("/home/kanchan/Downloads/Sample_group_upload_file.xlsx")))

    val response = asyncHttpClient.executeRequest(builder.build()).get();
   Ok(response.getResponseBody)

  }.getOrElse {

     Ok( "Missing file")

  }
}
}

this code is working fine with play 2.1.5 but problem with 2.1.5 but with play 2.1.5 I am uanble to create war file so I switched from play 2.1.5 to 2.4.3 and I should use latest that is also one  reason for switching but this code is not working with play 2.4.3 problem is this is not adding data in body part of the the request I am unable to understand why it is not adding  I think with play 2.4.3 there is some problem with com.ning.http.client.multipart package so some one can tell me what I am missing or how can I make it work in play 2.4.3

**Comment by cchantep** [comment]
Hi, please use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask question/for help (this tracker being for confurmed issues). Best regards
