### ISSUE TITLE
The issue while running unit test in Play scala project : NoSuchAlgorithmException: : EC KeyFactory not available

### ISSUE THREAD

**Issue by lalkhum** [playframework/playframework#5155]
Hi all,
I am using
- play 2.3.9
- java jdk 1.8.0_31
- OS: CentOS release 6.7 (Final)

I have got an error while running unit test as follows.
{code}
AAP9b85aBtbiIQT2jNKU4P0+vIKc0PTOvWC8xrzgzOT8nv0gvODO3ICfVoyQ3xy+/JNU2Yj/Tagmf50wMjD4M7CWJ6SCJEgYhn6zEskT9nMS8dP3gkqLMvHTriiIGKaihyfl5xfk5qXrOEBpkDgMEMDIxMFQUlDCw2+gXFyTm2QEAI9P8iI4AAAA=[0m]    NoSuchAlgorithmException: : EC KeyFactory not available  (Algorithms.scala:119)
[error] play.api.libs.ws.ssl.Algorithms$$anonfun$translateKey$2.apply(Algorithms.scala:119)
[error] play.api.libs.ws.ssl.Algorithms$$anonfun$translateKey$2.apply(Algorithms.scala:118)
[error] play.api.libs.ws.ssl.package$.foldVersion(package.scala:40)
[error] play.api.libs.ws.ssl.Algorithms$.translateKey(Algorithms.scala:107)
[error] play.api.libs.ws.ssl.Algorithms$.keySize(Algorithms.scala:85)
{code} 

However, this issue is not there while using java jdk 1.7 version.

Could someone please share what might have caused this?

Updates:
- Found that the issue is resolved in jdk version 1.8.0_51

Thanks & Regards

**Comment by queirozfcom** [comment]
Can this be closed then @lalkhum ? If so, please do.

**Comment by dotta** [comment]
@lalkhum Thanks for updating your ticket and share the solution. Also, in the future, please prefer asking usage questions in the [playframework mailing list](https://groups.google.com/forum/#!forum/play-framework). Thanks!
