### ISSUE TITLE
Intellij IDE: A binding to play.api.db.DBApi was already configured, evolutions and injector error with play-slick

### ISSUE THREAD

**Issue by ysihaoy** [playframework/playframework#5159]
I want to introduce slick to my play project, so I add the following dependencies to build.sbt:
```
"com.typesafe.play"          %% "play-slick"               % "1.0.1"     withSources(),
  "com.typesafe.play"          %% "play-slick-evolutions"    % "1.0.1"     withSources(),
```
Then, when I run an integration spec for controller I got following exception both on Intellij IDE and command line activator test. After Google I found the solution: https://www.playframework.com/documentation/2.4.x/PlaySlickFAQ#A-binding-to-play.api.db.DBApi-was-already-configured

After I removed the jdbc dependency, the integration spec passed when I using the command line, however I still got the same error when I run the test on Intellij IDE as following error: Exception encountered when invoking run on a nested suite - Unable to create injector, see the following errors:

Exception encountered when invoking run on a nested suite - Unable to create injector, see the following errors:
```
1) A binding to play.api.db.DBApi was already configured at play.api.db.DBModule.bindings(DBModule.scala:25):
Binding(interface play.api.db.DBApi to ProviderConstructionTarget(class play.api.db.DBApiProvider)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1).
  at play.api.db.slick.evolutions.EvolutionsModule.bindings(EvolutionsModule.scala:15):
Binding(interface play.api.db.DBApi to ConstructionTarget(class play.api.db.slick.evolutions.internal.DBApiAdapter) in interface javax.inject.Singleton) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to play.api.db.DBApi was already configured at play.api.db.DBModule.bindings(DBModule.scala:25):
Binding(interface play.api.db.DBApi to ProviderConstructionTarget(class play.api.db.DBApiProvider)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1).
  at play.api.db.slick.evolutions.EvolutionsModule.bindings(EvolutionsModule.scala:15):
Binding(interface play.api.db.DBApi to ConstructionTarget(class play.api.db.slick.evolutions.internal.DBApiAdapter) in interface javax.inject.Singleton) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
	at play.api.test.FakeApplication.<init>(Fakes.scala:216)
	at org.scalatestplus.play.OneServerPerSuite$class.app(OneServerPerSuite.scala:152)
```

**Comment by jroper** [comment]
Hi @ysihaoy, in future please ask for help on the mailing list.  You need to reload the sbt project in IntelliJ for it to pick up your changes to the classpath.

**Comment by ysihaoy** [comment]
Hi @jroper I did reload the sbt project in Intellij after remove jdbc plugin. But still not working. Any thought?
Sorry about that, do I need to raise this issue on the mailing list again?

**Comment by dotta** [comment]
@ysihaoy If it works from the command line and it doesn't work from within IntelliJ, then I'd say it's very likely an IntelliJ bug.

**Comment by ysihaoy** [comment]
@dotta Probably. Not sure anyone has same problem as myself? Or do I need to do additionally setup on Intellij?

**Comment by hellomaya** [comment]
@ysihaoy 

I have encountered the same issue, here is how to resolve it

first, make sure import your project with "auto import" checked in IU

And then, please comment jdbc, and add this in your dependence (which is build.sbt)

  "com.h2database" % "h2" % "1.4.187"

comment jdbc

  //jdbc in build.sbt

The reason is here 

https://www.playframework.com/documentation/2.4.x/PlaySlick
