### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by laran** [playframework/playframework#5175]
https://www.playframework.com/documentation/1.2.4/libs

"type does not clearly shows" should be "type does not clearly show"

**Comment by ultimate1352** [comment]
Hello Iaran.

For this issue, I think that better solution is make PR.

regards.

**Comment by laran** [comment]
Happy to. What's the repo/link to file to modify?

**Comment by marcospereira** [comment]
@laran thanks for report this.

I'm closing this issue here because it is related to Play 1, which has its own repository:

https://github.com/playframework/play1

Of course, you can open a new issue there. :-)
