### ISSUE TITLE
Support disabled options in select fields

### ISSUE THREAD

**Issue by eurafa** [playframework/playframework#5177]
Hello.
I'd like to contribute with a code to support to insert the **disabled** attribute to option inside select field.
For example: http://www.w3schools.com/tags/att_option_disabled.asp

This week I need this attribute and I have to custom an already customized field.

I mean a native support in Play, without to custom the template.
By the way, I think the default input templates should to give the possibility to output in the DOM element all attributes from HTML specification, cross-browser or not.

Please, tell me if that makes sense for you.
Thank you

**Comment by cchantep** [comment]
Hi, this tracker is for confirmed issue. For help, please use the Mailing list.
