### ISSUE TITLE
Reporting a broken link in 2.4 documentation

### ISSUE THREAD

**Issue by msgfxeg** [playframework/playframework#5187]
Hi, I would like to report a broken link in the Play Framework 2.4 documentation.
The link is :link https://typesafe.com/activator/template/play-java-intro-reactive-platform-15v01 
and is located at https://www.playframework.com/documentation/2.4.x/Tutorials under Java Tutorials Section on the page and titled "Play Java Intro".

Kind Regards,

**Comment by marcospereira** [comment]
Thanks, @msgfxeg.

Do you want to submit a pull request to fix that?

**Comment by msgfxeg** [comment]
@marcospereira Yes I would like to do so but actually I do not know the correct link to fix that !.
If you know the correct link kindly send it to me here and I will submit a pull request also, I will try to search for the correct link by myself till

**Comment by heroic** [comment]
A bit off topic, but the entire site has been giving me ERR_TOO_MANY_REDIRECTS. I have been trying to get my hands onto the framework, but just can't!

**Comment by wsargent** [comment]
Should be fixed by https://github.com/playframework/playframework/pull/5643
