### ISSUE TITLE
Regression issue with play.json - Seq that contains Option lost its implicit format

### ISSUE THREAD

**Issue by jeffsteinmetz** [playframework/playframework#5196]
This worked in Play 2.3.x

```
case class Test (bar: Vector[Option[String]])
object Test {
  implicit val testReads = Json.reads[Test]
}
```

In order to read valid json such as `{"foo":["a",null,"b"]}`

Play 2.4.3 reports 
`No implicit format for Vector[Option[String]] available.`
Because of the `Option`  (Note: the type of Seq doesn't matter: Vector, List, Seq all exhibit the same results)

Here is a complete example that works in 2.3.8

```
import play.api.libs.json.{JsSuccess, Json}

case class Test (foo: Vector[Option[String]])
object Test {
  implicit val testReads = Json.reads[Test]

  def example = {
    val j = "{\"foo\":[\"a\", null,\"b\"]}"
    val foo = Json.parse(j)
    foo.validate[Test] match {
      case f: JsSuccess[Test] =>
         f.get
    }
  }
}
```

calling `Test.example` will return
`Test(Vector(Some(a), None, Some(b)))`

**Comment by gmethvin** [comment]
```
implicit val optionStringFormat = play.api.libs.json.Format.optionWithNull[String]
```
inside your `object Test` should fix it.

Inside an array, `null` is really the only reasonable representation of an `Option`. But in other contexts there was some ambiguity over what the default format should do, so it was removed from the default scope in 2.4. Maybe there is a case for bringing it back in 2.5 with a more "correct" behavior, but we'd have to get more feedback.

**Comment by jeffsteinmetz** [comment]
Great!  That worked, thank you.

I see mention of `OptionReads` here:
https://www.playframework.com/documentation/2.4.x/Migration24#Reading-Options

The hint you have above is pretty handy when using the Play JSON reader Macros - it might be handy for others as well.  Maybe it could be added to this migration guide location or future migration guides?

So far the rest of the migration guide has been really handy - the rest of my 2.3 to 2.4 went smoothly.
Thank you again.
