### ISSUE TITLE
how to use play framework(2.4.x) without typesafe(activator )

### ISSUE THREAD

**Issue by iiitmahesh** [playframework/playframework#5201]
how to use play framework(2.4.x) without type safe(activator )
Since high memory and starting errors , fetching data from internet every time.
I want use play alone with activator, is it possible??

I don't know please help me (I am beginner of play framework )

**Comment by gmethvin** [comment]
Hi @iiitmahesh,

This tracker is for issues in Play Framework itself. You'd probably have better luck asking on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).

Activator is just a wrapper for sbt with some additional functionality, including a gui and templates. Play framework only requires sbt to work, but activator is useful for things like easily setting up a project from a template.
