### ISSUE TITLE
Not able to turn on Foreign Key Support With SQLite db

### ISSUE THREAD

**Issue by slimandslam** [playframework/playframework#5202]
The way to turn on foreign key support when using the SQLite db is to send the SQL string "PRAGMA foreign_keys = ON" with each JDBC connection.

However, configuring Play 2.4.3 in the conf file with this statement:

db.default.hikaricp.connectionInitSql="PRAGMA foreign_keys = ON"

still yields the foreign key error during db evolution:

We got the following error: [SQLITE_ERROR] SQL error or missing database (near "constraint": syntax error) [ERROR:1, SQLSTATE:null], while trying to run this SQL script:

Switching to bonecp:

play.db.pool = bonecp
db.default.bonecp.initSQL="PRAGMA foreign_keys = ON"

still yields the same error.

**Comment by wsargent** [comment]
connectionInitSql is deprecated in HikariCP 2.3.0:

https://groups.google.com/forum/#!topic/hikari-cp/9n-N5W0FIOI

```
In the HikariCP 2.3.0 release, the connectionInitSql and connectionCustomizerClassName properties will be marked as deprecated, and HikariCP will log a WARN-level message if used.
```

**Comment by searhiy** [comment]
Any updates? It's actual for me
