### ISSUE TITLE
Make it easier to run a single assembly

### ISSUE THREAD

**Issue by schmitch** [playframework/playframework#5205]
Hello, currently I love it to run single *.jar files however play makes it hard to have a single jar file since it has a lot of dependencies and as your project grows lot's of things will broke.

Currently what would be great is, if the sbt-assembly paragraph inside the docs would be upgraded to the latest version of sbt-assembly which makes a working version.

At the moment I failed to generate a working jar without having DI problems in 2.4.x+.

**Comment by hepin1989** [comment]
we are deploy via zip and later via deb.
how about that way？
