### ISSUE TITLE
Broken code example in "Compile Time Dependency Injection" docs

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#5208]
The code example following [To use this router in an actual application:](https://www.playframework.com/documentation/2.4.x/ScalaCompileTimeDependencyInjection) does not have valid imports, and I think it uses deprecated method calls. I would love to know what the correct code example would look like.

````
import play.api._
import play.api.ApplicationLoader.Context
import router.Routes

class MyApplicationLoader extends ApplicationLoader {
  def load(context: Context) = {
    new MyComponents(context).application
  }
}

class MyComponents(context: Context) extends BuiltInComponentsFromContext(context) {

  lazy val router = new Routes(httpErrorHandler, applicationController, barRoutes, assets)

  lazy val barRoutes = new bar.Routes(httpErrorHandler)
  lazy val applicationController = new controllers.Application()
  lazy val assets = new controllers.Assets(httpErrorHandler)
}
````

**Comment by marcospereira** [comment]
Hey @mslinn, Please see #5262 to confirm if it fixes this issue too.

**Comment by mslinn** [comment]
I looked around but can't find modified code. Can you point me to the improved code?
Tx, Mike

**Comment by marcospereira** [comment]
@mslinn could you please give me more information about what is wrong? Looking at the [documentation code](https://raw.githubusercontent.com/playframework/playframework/master/documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaCompileTimeDependencyInjection.md) you can see that code examples are external code snippets, which are compiled, so all the imports are valid.

**Comment by mslinn** [comment]
No answer to my Nov 22 question yet.

**Comment by gmethvin** [comment]
@mslinn As far as I can tell #5262 doesn't change this code example. Still it's not clear what is wrong with the code example. `bar.Routes` would not be defined by default but I think it's fine for the code samples to assume certain things about your project for the sake of example.

**Comment by mslinn** [comment]
Assumptions should be stated. Code should be runnable. Mere mortals cannot run this code.

**Comment by wsargent** [comment]
Hi @mslinn, can you detail the steps you're following to create a sample application, the error you're getting, and the expected result?  A reproducible Play project in Github would help to point out where the confusion is here.

**Comment by mslinn** [comment]
Simply paste in the code verbatim into a blank project and try to compile.

**Comment by wsargent** [comment]
@mslinn Unfortunately, the Play team gets many, many issues that assume something about a project or an environment which can't be reproduced on a developer's machine.  In this case, the documentation is explicit about making assumptions, and so compilation or non-compilation doesn't resolve the question here of what is unclear about the code example.
