### ISSUE TITLE
[2.4.3] testProd fails on Windows with "input line too long"

### ISSUE THREAD

**Issue by albuch** [playframework/playframework#5209]
When starting a app with testProd on Windows it fails with "Input line too long"

    > testProd
    [info] Wrote D:\projects\oss\myapp\target\scala-2.11\myapp_2.11-1.0-SNAPSHOT.pom
    [info] Packaging D:\projects\oss\myapp\target\scala-2.11\myapp_2.11-1.0-SNAPSHOT-web-assets.jar ...
    [info] Done packaging.
    
    (Starting server. Type Ctrl+D to exit logs, the server will remain in background)
    
    Die eingegebene Zeile ist zu lang.
    Syntaxfehler.

As far as I can see there was already a bug reported that got fixed for dist and stage : https://github.com/playframework/playframework/issues/2025 
Was testProd forgotten to be fixed or is this a different issue?

**Comment by albuch** [comment]
My fault, didn't see in the original bug report that one has to enable ClasspathJarPlugin or LauncherJarPlugin in build.sbt for the fix to apply.

**Comment by JFCote** [comment]
@albuch I know it's been a long time but can you elaborate on the solution for this? What are ClasspathJarPlugin or LauncherJarPlugin? Where do I get them? Thanks!
