### ISSUE TITLE
"&rsquo;" problems due to js/style code after </html> on playframework.com?

### ISSUE THREAD

**Issue by BjornHamels** [playframework/playframework#5211]
On github the help page renders fine, but on live playframwork.com it does not in Firefox/IE. It's related to the "`&rsquo;`" quote used on some pages (inconsistently mind you). Compare the sentence "All of Play[&raquo;]s asynchronous API calls give you a Future." (3rd heading, after the code) on Firefox/IE on the following two pages:
* https://www.playframework.com/documentation/2.5.x/ScalaAsync
* https://github.com/playframework/playframework/blob/master/documentation/manual/working/scalaGuide/main/async/ScalaAsync.md
You'll notice the typical Firefox 3x"<?>" and IE's 3x"[ ]" for the 3 byte UTF-8 that fails to render to a "`&rsquo;`" on the page hosted on playframework.com.

![naamloos](https://cloud.githubusercontent.com/assets/12029472/10805569/f601436e-7dce-11e5-9571-a2ec972afef6.png) (image)

At first I thought the playframework.com site was not hinting at UTF-8, but it seems it is. So checking the code I noticed the playframwork.com page appends some styling and javascript after the closing(!) `</html>` tag. Not sure if that's allowed, and perhaps that's the reason why IE/Firefox fail to render the "`&rsquo;`" correctly?

I'm no expert. Idea's to fix:
* Search and replace the occasional usage of  -  mind you, it's use is not consistent!  -  quote and replace it with the more often (in this documentation) use of the prime('). (Quick fix? Fixes consistency. Willing to make a patch/PR.)
* Figure out why it fails to render correctly here on github and not on playframework.com by someone more knowledgeable than me.
* Possibly: remove the non compliant javascript / styping after the closing `</html>` tag; might fix this but unsure.

**Comment by jroper** [comment]
In the original file, it's stored as a UTF-8 encoded right single quotation mark, `0xE2 0x80 0x99`.  In the HTML page, what's actually there is the 9 byte sequence `0xEF 0xBF 0xBD 0xEF 0xBF 0xBD 0xEF 0xBF 0xBD` which is the "unicode replacement character" encoded as UTF-8 repeated 3 times.   The unicode replacement character is used when you convert from one encoding to unicode, and there exists no way to encode a character in that encoding as unicode.

So, what's happening is at some point, playframework.com is reading the character, but not as UTF-8, it's using some other encoding, and in that encoding, what is read is not representable in unicode.

**Comment by jroper** [comment]
Fixed in https://github.com/playframework/play-doc/pull/19 and https://github.com/playframework/playframework.com/commit/0e8ed5571e2c711dbee99702bc8eda91a505f807.
