### ISSUE TITLE
Could you make the second constructor of GuiceApplicationBuilder, public?

### ISSUE THREAD

**Issue by schmitch** [playframework/playframework#5233]
Hello, currently we are using both, Java and Scala. However in our tests we needed to duplicate some code which could be easily replaced if:

https://github.com/playframework/playframework/blob/master/framework/src/play-java/src/main/java/play/inject/guice/GuiceApplicationBuilder.java#L25

Would be public.

Currently we do something like that:
```
trait EnvisiaScalaTestApplication {
    val folder: File

    def createBuilder: GuiceApplicationBuilder = {
        val builder = new GuiceApplicationBuilder
        builder.configure(("envisia.path", folder.toString));
    }
}
```

now our java could look interface like that:
```
public interface EnvisiaTestApplication extends EnvisiaScalaTestApplication {

    @Rule
    TemporaryFolder temporaryFolder = new TemporaryFolder();

    java.io.File folder = temporaryFolder.getRoot();

    default GuiceApplicationBuilder getBuilder() {

        return new GuiceApplicationBuilder(createBuilder());
    }

}
```

However that can't work, since this Constructor is hidden and there is no way to set it, only to duplicate both so we can't share too much code. I also don't see any reason why this is hidden.

**Comment by gmethvin** [comment]
It might be better to introduce a static factory method instead, to avoid any possible confusion (e.g. Java users thinking it is a copy constructor for the Java builder).

**Comment by gmethvin** [comment]
@schmitch Let me know if the solution I proposed works for you. Instead of using the constructor, it would just be
```scala
GuiceApplicationBuilder.fromScalaBuilder(createBuilder())
```
I think this is more clear than having multiple public constructors.

**Comment by schmitch** [comment]
@gmethvin, yeah that would be fine, too.
