### ISSUE TITLE
too many open files Exception of play 2.1.0 

### ISSUE THREAD

**Issue by qinghaibo** [playframework/playframework#5241]
i'm a newer of playframework, we found that too many tcp ESTABLISHED connections 
(netstat -anop|grep 8443) like below:
tcp     0      0 10.145.132.207:8443     10.146.34.233:61025     ESTABLISHED 26212/java  off(0.00/0/0)
 ,leads to the service down, we always need to restart the service, otherwise the connections will never relaeased.

it can be recur when meet some network anomaly (such as, disable client  local connection / unplug the network cable) 

how could we solve it in current version? Or, is there any other new feature to solve it?
thanks for any ideas.

**Comment by gmethvin** [comment]
I would suggest first posting on the mailing list or stackoverflow in more detail to see if you can get help diagnosing your problem. A "too many open files" exception can have a number of different causes. [This blog post](http://blog.codacy.com/2015/08/07/fixing-a-too-many-open-files-exception/) explains some of them.
