### ISSUE TITLE
Support -Dhttps.port=disabled for consistency

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#5245]
Per #915 it is possible to disable `http` with this Java system variable:

    -Dhttp.port=disabled

However the only way to disable `https` is to ensure that `https.port` is not assigned a value. For consistency, I think it would make sense to also support:

    -Dhttps.port=disabled

**Comment by richdougherty** [comment]
This should be a good enhancement for someone who wants to get started with contributing to Play. You can find the code you need to change by grepping for `"disabled"`. Remember to update the tests and docs! If you have any questions, you can ask on the play-framework-dev mailing list.
