### ISSUE TITLE
Support non-ASCII parameters in Content-Disposition header according to rfc5987

### ISSUE THREAD

**Issue by avdv** [playframework/playframework#5253]
The most famous browsers already seem to support  [rfc5987](http://tools.ietf.org/html/rfc5987).

So, when using `Ok.sendFile(filename = "...", ...)` the filename would be encoded in UTF-8 and then percent-encoded using the filename* parameter:

`Content-Disposition: attachment; filename=xyx.txt filename*=UTF-8''F%1ancy.txt`

**Comment by richdougherty** [comment]
Seems like a good idea!
