### ISSUE TITLE
Session-Based Content Remains In View After Session Cleared

### ISSUE THREAD

**Issue by neilchaudhuri** [playframework/playframework#5257]
I have content in my view, particularly the navigation bar, that only appears for those with role Admin, and that role is found in the session. The view code looks like this:

`@session.get("role").filter(_ == Role.Admin).map { role =>
  //Stuff only an admin can see
}
`

The problem is that when I clear the session like this:

`Ok(views.html.products.find("Find")).withNewSession`

The session is cleared, but the Admin-only content remains--probably because the content is generated for the `Result` while the session remains. Then the session is invalidated, but it's too late.

I understand I could work around this with caching, but I would prefer to use the session for this purpose.

This seems like a bug. Or is there another way I can clear the session *before* the content is generated?

Thanks.

**Comment by cchantep** [comment]
Hi, as this is unclear, I would suggest to discuss it on the [Mailing list](https://groups.google.com/forum/m/#!forum/play-framework), to confirm whether there is a Play issue. Best regards.

**Comment by cailhuiris** [comment]
I think, you can use session from Request directly. 
```
@()(implicit Request[AnyContent])
@if(request.session.get("role").filter(_ == Role.Admin).isDefined) {
    // content here.
}
```

**Comment by neilchaudhuri** [comment]
I guess I'm not sure what is unclear. The view `views.html.products.find("Find")` renders dynamic content based on the `session`, but when I call `Ok(views.html.products.find("Find")).withNewSession`, the session is only cleared *after* the view content has been rendered. Thus the resulting view on the client is as if the session remains. *Subsequent* interaction has no session.

Put another way, there is content on this view only admins can see and is controlled via session. When I render this view with `Ok(views.html.products.find("Find")).withNewSession`, that admin-specific content remains. That's bad. If I refresh the page, then it's gone--one cycle too late.

Anyway, I worked around this with a `Redirect`.

**Comment by wsargent** [comment]
This isn't a bug, this is how HTTP works -- cookies are set in a header as the page is rendered.   Redirect after POST, also known as PRG, is required whenever you want to see any changes to cookie values.  Please see https://en.wikipedia.org/wiki/Post/Redirect/Get for more details.
