### ISSUE TITLE
Assets request returning 500 internal server error - Play 2.4.3

### ISSUE THREAD

**Issue by harsh00008** [playframework/playframework#5264]
Hi,
Recently I upgraded from 2.3.8 to 2.4.3 with activator 1.3.6. Though everything works, my application is unable to serve Asset requests. It returns a 500 internal server error. Due to that, I'm unable to have css/image files in the application.
I tried manually adding commons-codec from build.sbt but still doesn't seem to work.
I tried to manually put an image file in public/images/. When I try to retrieve it, I get the same error. I'm unable to figure out what is wrong.

The stack trace is as below for each asset request:
```
MESSAGE: java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.sha1Hex(Ljava/lang/String;)Ljava/lang/String;  CAUSED BY : java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.sha1Hex(Ljava/lang/String;)Ljava/lang/String; STACK TRACE BELOW: 

play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:498)
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
play.utils.Threads$.withContextClassLoader(Threads.scala:21)
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
scala.Option.map(Option.scala:146)
play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741)
play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741)
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Build.sbt:
```
name := """PROJECT_NAME"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayJava,PlayEbean,SbtWeb)

scalaVersion := "2.11.6"

libraryDependencies ++= Seq(
  javaJdbc,
  cache,
  javaWs
)

libraryDependencies += evolutions

libraryDependencies += "commons-codec" % "commons-codec" % "1.10"

libraryDependencies += "mysql" % "mysql-connector-java" % "5.1.29"

includeFilter in (Assets, LessKeys.less) := "*.less"

excludeFilter in (Assets, LessKeys.less) := "_*.less"
```

plugins.sbt:
```
resolvers += "Typesafe repository" at "https://repo.typesafe.com/typesafe/releases/"

// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.3")

// web plugins

addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-coffeescript" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.0.6")

addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.1")

addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.1")

addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "1.0.0")
```

**Comment by richdougherty** [comment]
I looked at [the dependencies for Play 2.4](https://github.com/playframework/playframework/blob/2.4.x/framework/project/Dependencies.scala#L116) and commons-codec 1.10 looks like the right version. Would you be able to do some [build file debugging](https://www.playframework.com/documentation/2.4.x/SBTDebugging) to check which verison of commons-codec your project is actually using?

**Comment by harsh00008** [comment]
Even I checked the framework and it has the proper dependency (1.10). I looked at the debugging file, and it shows selection of 1.10 over any dependency with version less than that: 
![screen shot 2015-11-16 at 6 11 37 pm](https://cloud.githubusercontent.com/assets/3741668/11200896/466cfab4-8c8e-11e5-892a-dbd4ef4d1136.png)

For all the other tabs (compile, internal, runtime, etc. ) in the report, I see 1.10 is being selected over any previous version.
Also, in dependecy overview, wherever commons-codec is being used I see this pattern in the debug file, example: 
![screen shot 2015-11-16 at 6 20 15 pm](https://cloud.githubusercontent.com/assets/3741668/11200950/bf263ccc-8c8e-11e5-8f57-fdef134ef8c5.png)

I hope things are correct?

**Comment by harsh00008** [comment]
I also noticed that whenever I disable evolutions in application.conf (uncommenting  play.evolutions.enabled=false), I get 500 page with the same error (application doesn't start). When I comment it again, the application starts, but I get the same 500 error on Assets request (css/images/js).

**Comment by richdougherty** [comment]
That looks OK. Are you getting Play 2.4.3 for all your dependencies. You're not accidentally getting Play 2.3 for anything are you?

**Comment by harsh00008** [comment]
Yes. As far as I can see, seems like it is 2.4.3 everywhere.

**Comment by marcospereira** [comment]
@harsh00008 wild guess here, but could you please try to remove your dependency local cache and see if it will works? Maybe some dependency is corrupted.

**Comment by liuzhihai520** [comment]
I also have the same problem....Too tired!

**Comment by harsh00008** [comment]
I think the problem was with one of my external dependencies. It was using an old version of the codec, since it was an older version. Somehow, the framework, despite of showing the correct dependency in the reports, was getting that (older version from the external dependency) codec library. When I updated all of my external libraries, the error went away. @liuzhihai520 try updating all your external dependencies to the latest version. The problem might go away.

**Comment by liuzhihai520** [comment]
yes,I also found this problem.I introduced an external file[jar].This problem is happening....only new a play-scala and copy file to new project then  it's ok.

**Comment by cchantep** [comment]
I guess the discussion can go on, if needed, using the [Mailing list](https://groups.google.com/forum/m/#!forum/play-framework) (rather than this issue tracker). Best regards.
