### ISSUE TITLE
[doc] play.editor configuration documentation is misleading

### ISSUE THREAD

**Issue by michalzubkowicz** [playframework/playframework#5270]
Play editor as is documented should create hyperlinks on error pages, I've tried it adding via command line
-Dplay.editor=http://localhost:8091/?message=%s:%s -Dapplication.mode=dev, also tried in application conf but none of them is working. 

Documentation needs also updating because IntelliJ's Remote Call plugin is not supported anymore. It should use InteliJ Rest Api and configuration option in such case should look like:
-Dplay.editor="http://localhost:63342/api/file/?file=%s&line=%s"

**Comment by jxtps** [comment]
I also could not get this to work. [Looking at the source](https://github.com/playframework/playframework/blob/cde65d987b6cf3c307dfab8269b87a65c5e84575/framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala#L121) for the usage of this it looks like it just gets this from the Play configuration, and despite being able to query this information in my code: 

    Play.configuration.getString("play.editor"): 'Some(http://localhost:63342/api/file%s:%s)'

the error links are still not generated!?

Play 2.4.4, developing on Windows 10.

**Comment by jxtps** [comment]
Note that it works for runtime exceptions, but not for compilation errors.

**Comment by michalzubkowicz** [comment]
Oooh, it was not mentioned in documentation also.

Ok, then correct option is:
-Dplay.editor=http://localhost:63342/api/file/?file=%s&line=%s  , now everything works

**Comment by jxtps** [comment]
Did you get it to work for compilation errors as well?

**Comment by michalzubkowicz** [comment]
Nope, only for runtime errors.

**Comment by dhensche** [comment]
Is it supposed to work for both compilation and runtime? If not, maybe just an update of the documentation is required. Took me a while to find this page and realize that it was just compilation errors that were not being linked

**Comment by wsargent** [comment]
Documentation is at https://github.com/playframework/playframework/blob/master/documentation/manual/gettingStarted/IDE.md#navigate-from-an-error-page-to-the-source-code

**Comment by jxtps** [comment]
Ideally the links would also be generated for compilation errors. 

Does anyone have a pointer to where the compile time errors are generated / handled in the code? Might it be possible to use the playEditor there as well?

**Comment by wsargent** [comment]
You can't do this from compile time errors from Play.  It's SBT based, so it's outside of context.

You CAN do it using the activator UI though: https://www.lightbend.com/activator/docs

The play.editor update is done, so closing.

**Comment by mariussoutier** [comment]
Hi @wsargent, what do you mean, you cannot do this from compile time errors? The devError page shows where in the source the error occurrs, so why can't we add a hyperlink to that?

**Comment by mkurz** [comment]
Offtopic: Upcoming Eclipse release now also supports opening files at a specific line number/column: https://bugs.eclipse.org/bugs/show_bug.cgi?id=305336

**Comment by wsargent** [comment]
@mariussoutier I mean you have to have the application running and compiling first before you can do this -- you can't do it from a cold start.

**Comment by wsargent** [comment]
Okay, let's try this again:

**Comment by wsargent** [comment]
Fixed the actual bug with https://github.com/playframework/playframework/pull/6009

**Comment by wsargent** [comment]
https://github.com/playframework/playframework/pull/6009 did not fix the actual documentation though...

**Comment by mslinn** [comment]
Not sure if I should open a new issue for this. The default `application.conf` created by Activator 1.3.10 contains this:

```
## IDE
# https://www.playframework.com/documentation/latest/IDE
# ~~~~~
# Depending on your IDE, you can add a hyperlink for errors that will jump you
# directly to the code location in the IDE in dev mode. The following line makes
# use of the IntelliJ IDEA REST interface:
#play.editor=http://localhost:63342/api/file/?file=%s&line=%s
```

Two problems:
 1. Uncommenting the line that defines `play.editor` causes an error because the value needs to be quoted, like this:

    play.editor="http://localhost:63342/api/file/?file=%s&line=%s"

 2. Nothing happens when there is an error. This is a no-op.

**Comment by wsargent** [comment]
@mslinn that is a real issue -- if you can create a PR that quotes that line we can merge it.

**Comment by mslinn** [comment]
Done

**Comment by schmitch** [comment]
Fixed with https://github.com/playframework/playframework/commit/01cf23e240623526c9562d663ab0325d90a12267

**Comment by schmitch** [comment]
@wsargent guess this is fixed then? Wasn't exactuly sure

**Comment by wsargent** [comment]
@schmitch added https://github.com/playframework/playframework/pull/6267 for the fix here.
