### ISSUE TITLE
Using play 2.5.x WS api within akka actors

### ISSUE THREAD

**Issue by georgeyanev** [playframework/playframework#5272]
I'm using akka with java and looking for a way to use asynchronous Play WS api from within akka actors.

In play WS 2.4.x the method WSRequest.get() returns an F.Promise which easyly can be converted to Scala Future and then piped with akka.pattern.Patterns.pipe to some akka actor in order the http response to be received as an akka message.

In play WS 2.5.x the method WSRequest.get() returns a CompletionStage which I can not figure out how to pipe it to an Akka actor.

How can I properly use the play WS 2.5.x api from within an Akka actor?

**Comment by dotta** [comment]
@georgeyanev Hi, the issue tracker is for confirmed issues. Please, ask usage question in the [playframework mailing list](https://groups.google.com/forum/#!forum/play-framework). Thanks!

**Comment by hepin1989** [comment]
@georgeyanev just as @dotta said ,please using the gitter.
You could Inject the WSApi and pass it to the Actor's controller,or let the Actor to retrieve from some where ,like send a message and get a response back which contains the WS instance.

**Comment by dotta** [comment]
A `CompletionStage` can be easily converted to a `Future`, but as said we should really have this discussion in the mailing list as other may benefit from it.
