### ISSUE TITLE
Misleading description in ScalaCache.md

### ISSUE THREAD

**Issue by noru** [playframework/playframework#5274]
Line 67:
> **Note:** Play HTTP `Result` instances are safe to cache and reuse later.

That is simply not true since `Result` is not serializable and will fail in cacheApi implementation other than ehcache (e.g.: redis).

I think at least it should be pointed out that `Result` cannot be cached via serialization/deserialization.

**Comment by gmethvin** [comment]
Results with strict (in-memory) HTTP entities can be cached. The `Cached` helper, described on that page below the note, uses the following wrapper for Results to make it work correctly: https://github.com/playframework/playframework/blob/master/framework/src/play-cache/src/main/scala/play/api/cache/SerializableResult.scala

So as long as you use the wrapper (following the examples shown there) it should work fine wth any cache implementation. Still, feel free to submit a PR if you want to clarify the wording.

**Comment by noru** [comment]
I was trying to implement my own wrapper and wondering if it is done already, after all it is a common requirement. Thanks for your notice.

Anyhow, I still think there is plenty of space to improve about the documentation, and ye I consider submit a PR for it.

Thanks again.
