### ISSUE TITLE
Provide helper method to parse json requests

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#5275]
Right now to get the value of a JSON request you need to do:

```
Json.fromJson(request().body().asJson(), Pet.class)
```

It seems like it'd be simpler to have a method that was something a bit more like:

```
request().body().asJson(Pet.class)
```

**Comment by gmethvin** [comment]
I think it's a great idea but I wasn't sure about the naming `asJson`, since that makes it think it's returning some kind of json-like object. Maybe `fromJson`, `fromJsonAs`, `parseJsonAs` or something like that?

**Comment by benmccann** [comment]
Ok, I renamed to `parseJson`. Thanks for the feedback!

**Comment by phillip055** [comment]
I am working on this 👍

**Comment by lousanna** [comment]
Hi @phillip055, are you still working on this?

**Comment by chetankm-cs** [comment]
Hi, if its still available I want to work on this.
Also should we add scala api for the same use case ?

**Comment by phillip055** [comment]
Yes, will send pr today
