### ISSUE TITLE
Documentation of "JSON Inception" could use a rewrite

### ISSUE THREAD

**Issue by implicitdef** [playframework/playframework#5298]
Hi,

This page of doc https://www.playframework.com/documentation/2.4.x/ScalaJsonInception could be better IMO. It was originally a blog post and its style really doesn't match the rest of the documentation.

 I will work on a pull-request if you agree.

What I want to change : 
- The writing style (use of the first person, smileys sometimes or a bit too much caps)
- There is *a lot* of rambling about the motivations and the inner workings of the implementations, the actual code showing "how to use it" is hard to find. I would start the page by a first short section with the code samples and describing the advantages for the user. All the rest would be kept but should be *after*, and probably shorter.
- Renaming : the name "JSON Inception" is cryptic, it doesn't give an idea of what is it. Most users don't read the entire doc, they just browse the table of contents looking for something useful for them. They're likely to think *"Inception ?? Oh, that must be a really complicated feature for a very complicated use-case, not for me"*. When in fact it's a really simple feature that probably everybody uses. I suggest "JSON automatisation".

**Comment by marcospereira** [comment]
Have the same opinion. Go for it!

**Comment by nafg** [comment]
+100

Actually better yet, there should not be a separate page; the docs should
show this as the first thing.
*Writing custom Formats* is what should be considered an advanced and
somewhat obscure subject, that can be covered later for atypical use cases.

**Comment by gmethvin** [comment]
We could just call them JSON macros. Most people should know what we mean, at least after we introduce the subject briefly.

We also should clearly outline the limitations of these macros (some of which hopefully we can address soon). Currently it only supports serialization to JSON where the property names are the same as the field names in the class. As a result there are certain design decisions you have to make if you want to rely only only on the macros as opposed to writing your own serializers.

**Comment by implicitdef** [comment]
I went for "JSON automated mapping". I think it conveys appropriately what it offers to the user.

For me, as a end-user, the fact that it's a macro is really an implementation detail, so I chose not to stress it as much as before. I did kept information about how it works and what are the limitations, but I have trimmed it to the minimum.
