### ISSUE TITLE
Ebean generates false SQLite Statements

### ISSUE THREAD

**Issue by toschill** [playframework/playframework#5302]
I try to create an OneToMany relationship using ebean and SQLite. This fails because ebean generates a `alter table <table> add constraint <name> foreign key..` statement for the n:m matching table. SQLite does not support "alter table add constraint"  as stated [here](https://www.sqlite.org/omitted.html).

Any solution or workaround is highly appreciated. For me this happens on creation time of the table so it should be possible to tell ebean to add the key-Settings in the create table statement instead of altering it afterwards.

**Comment by benmccann** [comment]
I've moved this issue to the Ebean issue tracker since the bug is there. See https://github.com/ebean-orm/avaje-ebeanorm/issues/471 If the bug is fixed in Ebean then we can upgrade play-ebean to use the fixed version.
