### ISSUE TITLE
Remove Play 2.4 deprecated code

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#5309]
Before we release Play 2.5 we should remove code that was deprecated in Play 2.4. The only reason to keep something is if we think migration is really difficult and users might need longer to upgrade. Most deprecated code can just be removed. Removing code will help keep our codebase smaller and cleaner.

**Comment by wsargent** [comment]
+1

**Comment by richdougherty** [comment]
Tagged as *newbie* because you can fix this by grepping for deprecation and removing code!

**Comment by benmccann** [comment]
I did this for play-ebean if someone can review the pending PRs there: https://github.com/playframework/play-ebean/pulls
