### ISSUE TITLE
Add helper or hidden input to re-route to PUT/DELETE/etc. routes on GET/POST from the web browser

### ISSUE THREAD

**Issue by marccarre** [playframework/playframework#5313]
[restful-test.zip.txt](https://github.com/playframework/playframework/files/46267/restful-test.zip.txt)

Correct me if I missed something, but currently, if one wants to both:
- support HTML form requests from web browsers without JavaScript (`POST`/`GET` only),
- define a RESTful API and support any RESTful / JavaScript client (`POST`/`GET`/`PUT`/`PATCH`/`DELETE`/`HEAD`/etc.),

my understanding is that one has to come up with alias routes, e.g. :

    POST   /items/:id/delete # This endpoint would be used by HTML forms
    DELETE /items/:id        # This endpoint would be used by any other RESTful client

as the `helper`/front controller doesn't re-route the `POST` request to the `DELETE` route, even if you provide `'method -> "DELETE"` or `<input name="_method" type="hidden" value="delete" />` (like, e.g. [Ruby on Rails](http://guides.rubyonrails.org/form_helpers.html#how-do-forms-with-patch-put-or-delete-methods-work-questionmark) would).

I wanted to know if this is by design or is a(n) (un)known limitation.
If the latter, I am happy to provide a patch provided minimal guidance.

Thanks,
Marc.

----
**Detailed explanations**:

Assuming routes like:

    # Renders the list of languages either as text or as a HTML table, with deletion forms:
    GET     /languages      controllers.Languages.list

    DELETE  /languages/:id  controllers.Languages.delete(id: Int)

1. If one simply uses:

        @helper.form(action = routes.Languages.delete(id)) {
          <input type="submit" value="x" />
        }

    the request is routed to the equivalent `GET`:

        Action not found
        For request 'GET /languages/1'

2. If thought maybe the `helper` would play nicely with an overriden `method` attribute:

        @helper.form(action = routes.Languages.delete(id), 'method -> "delete") { ... }

    but this doesn't change anything compared to 1.

3. If one tries tricks you can find in other frameworks, e.g. [Ruby on Rails](http://guides.rubyonrails.org/form_helpers.html#how-do-forms-with-patch-put-or-delete-methods-work-questionmark):

        @helper.form(action = routes.Languages.delete(id)) {
          <input name="_method" type="hidden" value="delete" />
          <input type="submit" value="x" />
        }

    the request is still routed to the equivalent `GET`:

        Action not found
        For request 'GET /languages/1?_method=delete'

4. So it seems the only way to have this working is to have the below routes:

        GET     /languages      controllers.Languages.list
        POST    /languages/:id  controllers.Languages.delete(id: Int)
        DELETE  /languages/:id  controllers.Languages.delete(id: Int)

    Note that: 

    - if you swap `POST` and `DELETE`, then you end up in case 1.
    - if you need `POST` for some other semantics in your API, then you are forced to have something like:

            GET     /languages             controllers.Languages.list
            POST    /languages/:id         controllers.Languages.someOtherAction(...)
            DELETE  /languages/:id         controllers.Languages.delete(id: Int)
            POST    /languages/:id/delete  controllers.Languages.delete(id: Int)

Again, I may be missing obvious, but I could not see this covered in:

- https://www.playframework.com/documentation/2.4.x/ScalaRouting
- https://www.playframework.com/documentation/2.4.x/ScalaForms

Sample project attached, for convenience (sorry for the double extension, GitHub rejects whatever doesn't have one of the following extensions: `.png`, `.gif`, `.jpg`, `.docx`, `.pptx`, `.xlsx`, `.txt`, `.pdf`).

**Comment by gmethvin** [comment]
@marccarre The [form helper](https://github.com/playframework/playframework/blob/2.4.x/framework/src/play/src/main/scala/views/helper/form.scala.html) takes the method directly from the `Call` defined in the routes, so the html is setting `method="delete"`, but your browser just doesn't support it. Browsers don't generally support methods other than GET and POST in HTML forms.

Play doesn't by default support any hacks for specifying another method in the form, though you could implement it yourself with a [filter](https://www.playframework.com/documentation/2.4.x/ScalaHttpFilters) that modifies the incoming request.

If I were you, though, if you can't use JavaScript I would avoid trying to stick to a "pure" REST implementation. There's no significant benefit I can see.

I'm closing this issue since I think more discussion is warranted on the mailing list or some other forum before we decide there is an issue.

**Comment by marccarre** [comment]
Thanks @gmethvin for your reply and suggestion to use a filter! I'll probably use this for now, and implement the same hack which RoR has.

Regarding defining a "pure" REST API, but still be able to leverage it with plain HTML forms, I believe this could be useful if one:

- uses the same API for both his website and external users (as a public API for other programmers to leverage) together with content negotiation,
- wants his website to "gracefully degrade" to simple HTML (e.g. if JavaScript is disabled),

while keeping the API as "DRY" and RESTful as possible.

Cheers,
Marc.

**Comment by gmethvin** [comment]
In my experience it doesn't seriously violate DRY to have separate endpoints. Typically there are differences between what your pure HTML forms are doing and what your REST APIs are doing, such as the input/output content types.

If it makes sense for you feel free to try it though. You should be able to make your own helpers/filters to do it without having to modify Play.
