### ISSUE TITLE
javaWs still returns a Promise instead of CompletionStage as of 2.5.0-M1

### ISSUE THREAD

**Issue by oleg-gr** [playframework/playframework#5316]
[javaWs still returns a Promise instead of CompletionStage.](https://github.com/playframework/playframework/blob/416f2df60ecb0facf753e6f0c9dba0edf4261e29/framework/src/play-java-ws/src/main/java/play/libs/ws/WSRequest.java#L36) Is this going to be addressed in M2? I am trying to rewrite a whole project before the actual 2.5.0 release and it's really inconvenient that some interfaces still return Promises.

**Comment by gmethvin** [comment]
`Promise` does implement `CompletionStage`, so just use the `CompletionStage` methods on it.

I'm not sure what the plans are right now to migrate the WSAPI away from `F.Promise`, though.

**Comment by hepin1989** [comment]
https://docs.google.com/document/d/1OejviUX5TDlRVeKg1JD9L4qh2Tn21giItmyxRXCydN0/edit

**Comment by oleg-gr** [comment]
@gmethvin that's what I ended up doing, but I thought I would mention it since I thought the idea was that all internal APIs are going to return `CompletionStage` directly as per the google doc shared by @hepin1989 

You can close the issue, or label it as "improvement"

**Comment by oleg-gr** [comment]
@gmethvin @hepin1989 
I am curious about something. How can scala ExecutionContext be used with CompletionStage now?

If you get an execution context like this:
```
ExecutionContext myExecutionContext = Akka.system().dispatchers().lookup("123");
```
in 2.4.x you could do something like
```
F.Promise<Integer> integerPromise = F.Promise.promise(() -> 100, myExecutionContext);
```
but since now Play is switching to using CompletionStage instead, there is no easy way to convert Scala's `ExecutionContext` to Java's `Executor` as far as I know. So something like this won't work obviously
```
CompletionStage<Integer> integerCompletionStage = CompletableFuture.supplyAsync(() -> 100, myExecutionContext);
```
So what's your suggested way of managing multiple thread pools for java projects?

**Comment by wsargent** [comment]
@gmethvin @oleg-gr I will handle it in https://github.com/playframework/playframework/pull/5505
