### ISSUE TITLE
Add gitter.im to documentation

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#5319]
Seems like we should mention the chat rooms on this page?
https://www.playframework.com/get-involved

**Comment by gmethvin** [comment]
The chat rooms should probably be at the top, maybe before the mailing list section.

The other issue with that page is that we link to the deprecated Plugins documentation. It should link to a page about modules (though https://www.playframework.com/documentation/2.4.x/Modules doesn't really do a good job explaining how to create a Play module...)

Also I think this should be an issue on https://github.com/playframework/playframework.com

**Comment by dwhu** [comment]
I can take this.
