### ISSUE TITLE
Rename testProd

### ISSUE THREAD

**Issue by mariussoutier** [playframework/playframework#5320]
Hi,

can we rename `testProd` to something less ambiguous? Commands starting with "test" should run tests, not run the application.

**Comment by benmccann** [comment]
Command is referred to on this documentation page: https://www.playframework.com/documentation/2.4.x/Production

**Comment by mariussoutier** [comment]
> To run an application in prod mode, run `testProd`

Fixed:

> To run an application in prod mode, run `runProd`

**Comment by gslowikowski** [comment]
I have a question.

There was `start` command in the beginning. [This commit](https://github.com/playframework/playframework/commit/e7a411a874fe8eb36d2b2b3ec53b4910882c4368) says that `start` name is passe and `testProd` will be better. Now you don't like `testProd` and renamed it to `runProd`.

There are three methods now - `runProd` and two depracated: `testProd` and `start`.
Can you tell, why `start` name is wrong and `runProd` is OK (`run` and `runProd` implementations are so different).

Additionally, previously there was `stop` command, now renamed to `stopProd`.

`start/stop` pair was sensible and easy to remember (these commands were already in Play! 1.x).
`runProd/stopProd` pair is much worse IMO.
