### ISSUE TITLE
Injecting Config oder WSClient failed in UntypedActor

### ISSUE THREAD

**Issue by aBuder** [playframework/playframework#5328]
I see, that we can use Dependency Injection in an UntypedActor class, but if I use the @Inject annotation my injected Configuration is null. Where is the problem. I'm confused.

```java
package actors;

import akka.actor.UntypedActor;
import play.Configuration;
import play.Logger;
import play.libs.akka.AkkaGuiceSupport;

import javax.inject.Inject;

public class MyActor extends UntypedActor {

    @Inject
    Configuration configuration;

    @Override
    public void onReceive(Object message) throws Exception {
        Logger.info("--- Actor started ---");
        Logger.info("Key: ", configuration.getString("app.test.key"));
        Logger.info("--- Actor ended ---");
    }

}

```

**Comment by gmethvin** [comment]
Hi @aBuder. If you're looking for help please try stackoverflow, the [mailing list](https://groups.google.com/forum/#!forum/play-framework), or the [gitter channel](https://gitter.im/playframework/playframework). This tracker is for reporting bugs in play.
