### ISSUE TITLE
Make it possible to inject / set Application (app) in FakeApplication

### ISSUE THREAD

**Issue by regispl** [playframework/playframework#5329]
Little introduction: 
**I'm using Play Framework 2.4 with Scalatest (I'm extending FlatSpec) and I want to "override" some Guice bindings with mocks for FakeApplication in controller tests (e.g. stuff that talks to the database, to Kafka etc.).**
I've read about GuiceApplicationBuilder and I know how to create Application and override the bindings that I want to override, I know that I can override "app" in my test suites, but I have no clue how to put these two things together in a nice way, because "app" is of type FakeApplication (which extends Application AND "has" Application built by Guice in it as a private val at the same time) while GuiceApplicationBuilder builds Application - see the source with my inlined comment:

```scala
// in src/play-test/src/main/scala/play/api/test/Fakes.scala
case class FakeApplication(
    override val path: java.io.File = new java.io.File("."),
    override val classloader: ClassLoader = classOf[FakeApplication].getClassLoader,
    additionalPlugins: Seq[String] = Nil,
    withoutPlugins: Seq[String] = Nil,
    additionalConfiguration: Map[String, _ <: Any] = Map.empty,
    withGlobal: Option[play.api.GlobalSettings] = None,
    withRoutes: PartialFunction[(String, String), Handler] = PartialFunction.empty) extends Application {

  // I'd like to be able to modify this:
  private val app: Application = new GuiceApplicationBuilder()    
    // some default configuration. bindings etc.
    // ...
    .build

  override def mode: Mode.Mode = app.mode
  // more overrides
  // ...
}
```

**There seems to be no way to "inject" Application created by Guice to FakeApplication or set it later and I'm wondering if there's any specific reason why it's impossible?**

An alternative approach, similar to Spec2's withApplication() helper that allows to define an Application to be used in every test would be OK too. I know about Play's WithApplication, but since it's a class that I have to extend, it would stop me from using FlatSpec, which I don't want to do of course.

For the moment I ended up with a dirty solution of implementing my own equivalent of OneAppPerSuite that overrides app with my own Application generated by GuiceApplicationBuilder with the bindings overriden as I want, but this solution just feels and looks dirty.

I'm a Play Framework newbie, so sorry if this question doesn't make sense for some obvious reasons I don't understand yet - that's the problem I encountered when trying to make my stuff work, so I'm wondering if I'm doing something wrong and missing an obvious solution or I'm the only person on the planet having this problem? ;-) 

Of course if this approach (or similar, suggested / advised by someone more experienced with Play?) makes sense, I'm happy to make that change and open a PR.

**Comment by gmethvin** [comment]
`FakeApplication` is basically just a helper for creating a test application with reasonable defaults. There's no reason you have to use it. You can create your own application using the guice builder and use that for your tests.

**Comment by regispl** [comment]
Thanks for response. 

Yes, I definitely see your point, but if I'm using ScalaTest with e.g. OneAppPerSuite from ScalaTest+Play it's "forcing me" to use FakeApplication (that's the type of the "app" field which I can set to define my own test application, while Guice builder builds an object of type Application. Of course I can try some weird workarounds, but it would be awesome if I could just Build my own Application using Guice builder and either: (a) inject it to FakeApplication (this question) OR (b) overwrite the default FakeApplication with it. Unfortunately, neither of the above is possible at the moment, so I'm trying to figure out what can be done about it :-) 

Do you think that it might be actually a bad design of the ScalaTest+Play that it requires FakeApplication rather than Application and it's better to talk to ScalaTest+Play maintainers re the possibility to "relax" the type requirements for app field in OneAppPerSuite and similar?

https://github.com/scalatest/scalatestplus-play/blob/master/src/main/scala/org/scalatestplus/play/OneAppPerSuite.scala

**Comment by regispl** [comment]
Actually, I just found this issue: https://github.com/scalatest/scalatestplus-play/issues/24
It seems like exactly what I need, but despite of the comments there it seems to be still not implemented in the master branch (it's still FakeApplication rather than Application). I'll follow up there and see if that's a way to go.
Thanks for help, feel free to close that Issue (I don't think I can do it?)
