### ISSUE TITLE
ZonedDateTime zone is by default truncated when serializing to JSON

### ISSUE THREAD

**Issue by paul-lysak** [playframework/playframework#5342]
By default time zone information for Java 8 `ZonedDateTime` is simply thrown away. For example:

    case class MyClass(createdAt: ZonedDateTime)
    implicit val myWrites = Json.writes[MyClass]
    ...
    val d = MyClass(ZonedDateTime.parse("2015-10-01T12:13:14.00+02:00"))
    val json = Json.toJson(d)

produces following JSON: `{"createdAt": "2015-10-01T12:13:14"}`
Comments in `play.api.libs.json.Writes/implicit val DefaultZonedDateTimeWrites` say:

    /**
     * The default typeclass to write a `java.time.ZonedDateTime`,
     * using '2011-12-03T10:15:30' format, and default time zone.
     */

But it doesn't convert the date to any standard time zone - you may add following code to `play.api.libs.json.WritesSpec/"Zoned date/time" should` to see it yourself:

    "be written in the same way if points to same instant in different time zones" in {
      writes(dateTime("2011-12-03T10:15:30+02:00")) must_== (writes(dateTime("2011-12-03T09:15:30+01:00")))
    }

All though such behavior isn't hard to override in a specific project, that doesn't seem to me as a reasonable default - in fact, that was the reason for creating ZonedDateTime: to embrace concept of time zone. 
Would you please consider one of 2 options:

- either switch default writes for ZonedDateTime to display time zone (seems more reasonable to me)
- or at least convert ZonedDateTime to some standard zone ?

Thanks!

**Comment by cchantep** [comment]
See #5190

**Comment by paul-lysak** [comment]
Oh, that's great. Looking forward for this pull request to get into Play release.
