### ISSUE TITLE
Fix 2.4 migration doc

### ISSUE THREAD

**Issue by kkirancse** [playframework/playframework#5352]
Play doc (https://www.playframework.com/documentation/2.4.x/Migration24#Ebean-dependency) is not working as expected.  When I changed the dependency to  play-ebean 1.0.0-RC3 rather than 1.0.0 as specified in the doc it started working. Please fix the documentation to help others.

**Comment by wsargent** [comment]
You need to state what you mean by "not working as expected" and "started working."  Without a clear understanding of the issue and how to reproduce it, the documentation can't be fixed.
