### ISSUE TITLE
Java Form does not expose backed type class

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#5354]
The play.data.Form class does not expose the type it is eventually backed by. Thus it's impossible in subclasses or other helper methods to make decisions based on the type or even create a new form generally based on a existing form. 

I suggest to enhance the form with a getter for the 
    private final Class<T> backedType;

Additionally, it would be helpful to have
    private T blankInstance() {
as protected or protected final. 

I could help out with a PR if this change makes sense to the play core team.

**Comment by mkurz** [comment]
Sounds reasonable.
@richdougherty @jroper toughts?

**Comment by mkurz** [comment]
Fixed by #5726 
Actually I would have needed a getter for `backedType` in the past as well.
