### ISSUE TITLE
Play - load guice module based on application mode

### ISSUE THREAD

**Issue by tpraizler** [playframework/playframework#5355]
I want to control the modules I am loading based on the current application mode.

So if I have the following modules: ModuleDev, ModuleProd I want to write something like this:

    class CostumGuiceApplicationLoader extends GuiceApplicationLoader {
       override def builder(context: ApplicationLoader.Context): GuiceApplicationBuilder = {
          initialBuilder
          .in(context.environment)
          .loadConfig(context.initialConfiguration)
          .overrides(overrides(context): _*)

         play.api.Play.current match{
           case Mode.Prod => initialBuilder.bindings(new ModuleProd)
           case Mode.Dev => initialBuilder.bindings(new ModuleDev)
        }
     } 
But I get an exception: java.lang.RuntimeException: There is no started application

So I am not sure where in the life cycle of my app I should add this logic.
I was using this [article](https://www.playframework.com/documentation/2.4.x/ScalaDependencyInjection#Advanced:-Extending-the-GuiceApplicationLoader) as reference

**Comment by wsargent** [comment]
This isn't a bug in Play -- you should use the mailing list at https://groups.google.com/forum/#!forum/play-framework

So... you need to get access to play.api.Environment -- that's the thing that has a `env.mode` which you will use to switch on.

https://www.playframework.com/documentation/2.4.0-RC2/api/scala/index.html#play.api.Environment

To do this, you'll need to add a module.  You have the right page, but the wrong section.  You actually want:

https://www.playframework.com/documentation/2.4.x/ScalaDependencyInjection#Configurable-bindings

**Comment by tpraizler** [comment]
Awesome thanks!
