### ISSUE TITLE
Make JavaCompatibleHttpRequestHandler the default HttpRequestHandler

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#5357]
~~As part of deprecating `GlobalSettings`~~, we should move to the `JavaCompatibleHttpRequestHandler` and add the following to `reference.conf`

```
play.http.requestHandler = "play.api.http.JavaCompatibleHttpRequestHandler"
```

https://www.playframework.com/documentation/2.4.x/ScalaHttpRequestHandlers#Configuring-the-http-request-handler

**Comment by marceloemanoel** [comment]
If I got this right, to fix this issue I just have to change 
[this line](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/resources/reference.conf#L33) to this:

```scala
requestHandler = "play.api.http.DefaultHttpRequestHandler"
```

is it correct? Or Do I need to change anything else?

**Comment by richdougherty** [comment]
Hi @marceloemanoel, the main code change should happen here: https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala#L45-L62. You'll need to replace the reference to the Scala and Java `GlobalSettingsHttpRequestHandler`s with references to `DefaultHttpRequestHandler`s.

That's not the whole change though! :)

* You'll also need to add a note to `Migration25` telling people about the new default value and telling them what they should do if they want to keep the old value.
* You should also grep the code (.scala, .java), configuration (.conf) and docs (.md) for references to `GlobalSettingsHttpRequestHandler` and `DefaultHttpRequestHandler` and make sure they correctly describe the new default. E.g. the comment in the `reference.conf` you linked to would need to be updated.
* Finally you should mark the Java and Scala `GlobalSettingsHttpRequestHandler` classes as deprecated, just in case anyone is referring to them directly in their code.

@wsargent, this issue isn't about deprecating `GlobalSettings` itself. Is there another issue to track that work?

**Comment by wsargent** [comment]
@richdougherty GlobalSettings was deprecated as part of https://github.com/playframework/playframework/pull/5339 but there isn't an entry for it in Migration.  Added an issue: https://github.com/playframework/playframework/issues/5366

**Comment by marceloemanoel** [comment]
Hi, @richdougherty.

Thanks for the directions. I'll get back to these changes tonight.

**Comment by mkurz** [comment]
@marceloemanoel Some work was done in #5369 just now.

**Comment by mtrovo** [comment]
Sorry about that, I had a ongoing work for the last two days and didn't know someone was already working on this one.

**Comment by marceloemanoel** [comment]
No problem guys :)

**Comment by richdougherty** [comment]
I just learned from @jroper that the default for Play apps should be the `JavaCompatibleHttpRequestHandler`, not the `DefaultHttpRequestHandler`. The `JavaCompatibleHttpRequestHandler` extends `DefaultHttpRequestHandler` and adds support for Java actions. If you don't use this handler then Java applications are going to have errors.

```
play.http.requestHandler = "play.api.http.JavaCompatibleHttpRequestHandler"
```
