### ISSUE TITLE
[2.4.3] Enumerator.flatten does not recover from exceptions

### ISSUE THREAD

**Issue by prasannata** [playframework/playframework#5362]
```
val eventualEnumerator: Future[Enumerator[Array[Byte]]] = api.stream(fileName)
Enumerator.flatten(eventualEnumerator) //Eats up any exception.
```
In the above example, I would prefer `api.stream` to return `Enumerator[Array[Byte]]` instead of a `Future[T]` but if I do that, I am not able to recover from exceptions.

**Comment by cchantep** [comment]
Hi, has it been discussed on the [MailingList]( https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo)? If not would be nice to, before raising an actionable ticket there. Best regards.
