### ISSUE TITLE
FakeKeyStore incorrectly regenerates certificate every time

### ISSUE THREAD

**Issue by tyth** [playframework/playframework#5367]
`play.core.server.ssl.FakeKeyStore` checks if existing certificate public key has `SHA256withRSA` as an algorithm. If the algorithm is different, it regenerates certificate. 

But a certificate that is generated by `FakeKeyStore` itself doesn't pass that validation. Certificate public key algorithm is always `RSA`, not `SHA256withRSA`.
Algorithm of a certificate itself, on the other hand, is correct `SHA256withRSA`. 

This can be fixed by simple replacing public key algorithm validation with certificate algorithm validation. 
Then in FakeKeyStore.scala at line 48 `key.getAlgorithm != SignatureAlgorithmName` has to be replaced with `c.asInstanceOf[X509CertImpl].getSigAlgName != SignatureAlgorithmName`.
But there also could be other solution/problem here.

Play framework version is 2.4.x.

**Comment by maxcom** [comment]
I think that this bug is related to #5255  and #5254

**Comment by wsargent** [comment]
Yeah, this is from https://github.com/easel/playframework/commit/235b502d42614de56ab6ec20ffe270499997153c#diff-d4309620061d4c5901b7a44c8432ba30R48

**Comment by maxcom** [comment]
Please fix this bug in 2.4.x too. It is very annoying to accept new certificate in browser after every restart.
