### ISSUE TITLE
[2.5.x] Add plugins removal to Migration25.md

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#5371]
Add the removal of plugins to the 2.5.0 migration.

https://github.com/playframework/playframework/blob/master/documentation/manual/releases/Migration25.md

**Comment by benmccann** [comment]
I personally would think it's probably better to put in the migration guide than the highlights

**Comment by cchantep** [comment]
I agree with @benmccann

**Comment by wsargent** [comment]
Added it to Migration25.md
