### ISSUE TITLE
[2.3.x] Routes aren't falling through properly with different types

### ISSUE THREAD

**Issue by logicbomb** [playframework/playframework#5372]
I have a single HTTP route that needs to be serviced by 2 different controller methods, depending on the type of the parameter specified route segment.

e.g.
/route/:id                controller.get(id: UUID)
/route/:name          controller.get(name: String, requiredQuerystringParam: String)

When I call `http://localhost/route/logicbomb` I get a HTTP400 
> [Cannot parse parameter name as UUID: Invalid UUID string: logicbomb]

**Comment by gmethvin** [comment]
@logicbomb Both of those routes match "/route/" followed by some string, and Play's router always [uses the first route](https://www.playframework.com/documentation/2.3.x/ScalaRouting#Routing-priority) in this situation. If you only want the first one to match UUIDs, you could consider [using a regular expression](https://www.playframework.com/documentation/2.3.x/ScalaRouting#Dynamic-parts-with-custom-regular-expressions) in your route to make the first one only match UUIDs.

**Comment by carymrobbins** [comment]
@gmethvin - I'm a little surprised by this.  Is there any reason the the routes don't fall through in the event that the PathBindable fails?

**Comment by gmethvin** [comment]
@carymrobbins I wasn't involved in the design of the routes, but I guess it was just in the interest of simplicity. Most situations, like the one here, can be handled reasonably well using a single action, or using patterns in the routes. And it's a lot easier to understand which controller methods will be called by just reading the routes file.

**Comment by carymrobbins** [comment]
I can see that.  A single action could just delegate to the appropriate controller method, and that even adds some additional flexibility.

Thanks @gmethvin!
