### ISSUE TITLE
Optimalizations in serialization algorithm

### ISSUE THREAD

**Issue by jwisniewski100** [playframework/playframework#5373]
During creating JsValue, serialization algorithm uses mapWrite function from Writes.scala (play.api.libs.json package) .
We can simplify it by returning Map[String, JsValue].
Instead of:
```
implicit def mapWrites[V](implicit fmtv: Writes[V]): OWrites[collection.immutable.Map[String, V]] = OWrites[collection.immutable.Map[String, V]] { ts =>
    JsObject(ts.map { case (k, v) => (k, toJson(v)(fmtv)) }.toList)
  }
```
can be used:
```
implicit def mapWrites[V](implicit fmtv: Writes[V]): OWrites[collection.immutable.Map[String, V]] = OWrites[collection.immutable.Map[String, V]] { ts =>
    val x = ts.mapValues(v => toJson(v)(fmtv))
    JsObject.create(x)

  }
```
Second change I propose is in method apply from JsValue.scala. JsObject definition can be improved by using:
```
object JsObject {
  /**
   * Construct a new JsObject, with the order of fields in the Seq.
   */

  def apply(fields: Seq[(String, JsValue)]): JsObject = new JsObject(fields.toMap)

  def create(m: Map[String, JsValue]) = new JsObject(m)
}
```

Results of tests show that algorithm can work up to 1500% better than before.

**Comment by cchantep** [comment]
Where are the benchmarks/tests?

**Comment by gmethvin** [comment]
@jaceklaskowski I would also really like to see what tests you are running.

And that will actually break the API, because the ordering of the fields in the `Seq` is no longer preserved.

**Comment by jwisniewski100** [comment]
I would like to apologize. I made a mistake in my tests.
