### ISSUE TITLE
Templates: consider Sass instead of or in addition to Less

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#5380]
[The templates currently have](https://github.com/playframework/playframework/blob/master/templates/play-java/project/plugins.sbt):

    addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "%LESS_VERSION%")

[Foundation uses Sass](http://foundation.zurb.com/sites/docs/v/5.5.3/sass.html) and [Bootstrap 4 is switching to Sass because "more people use SCSS, libsass is crazy fast, and the syntax is more explicitly clear"](https://twitter.com/mdo/status/591364406816079873). I haven't used Sass myself, but if both the major CSS frameworks are using Sass, it seems like that'd be the logical choice for Play to use. [Google Trends also provides evidence that Sass is becoming more popular than Less](https://www.google.com/trends/explore#q=%2Fm%2F054k6n_%2C%20%2Fm%2F0gjd0jv&cmpt=q&tz=Etc%2FGMT%2B8).

I think @irundaia's [sbt-sassify](https://github.com/irundaia/sbt-sassify) might be a decent bet for supporting sass. It uses libsass, so you don't have to install ruby and it should be pretty fast. It also looks like it doesn't require any new resolvers to be added to the project, which is a plus as well.

**Comment by mkurz** [comment]
+1

**Comment by gmethvin** [comment]
I think both would be okay. For Sass we should also add documentation similar to  https://www.playframework.com/documentation/2.4.x/AssetsLess to describe how to use it.

**Comment by irundaia** [comment]
I'm on it :)

**Comment by irundaia** [comment]
Is it at all possible that the Travis tests are a bit flaky? I've tried several times, but every time a different test fails (for code that I haven't really touched). In any case, I hope the added descriptions proves to be sufficient.

**Comment by benmccann** [comment]
Yeah, Travis has been a bit flaky lately. You can close and reopen the PR to make it kick off another build.

**Comment by irundaia** [comment]
Done, the tests succeeded now. Thanks

**Comment by benmccann** [comment]
@irundaia's documentation has been merged. I think we should consider adding it in the templates as well. Not sure if we should have both the Less and Sass plugins enabled by default. I guess that would be okay though and then folks can remove one or both depending on what they want to use.

**Comment by wsargent** [comment]
@benmccann what would be added to the templates?

**Comment by benmccann** [comment]
yeah
