### ISSUE TITLE
NPE in Netty

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#5395]
I see regular read errors when running *wrk* performance tests against master. I've create a Netty issue to track the problem: https://github.com/netty/netty/issues/4571

**Comment by richdougherty** [comment]
From @normanmaurer's [comment](https://github.com/netty/netty/issues/4571#issuecomment-165252216):

> it is kind of bad usage of netty... You should only call read() once isRegistered() returns true or the ChannelFuture of register(...) is notified. That said we should never throw a NPE, so I will fix this

So I think we need to fix up https://github.com/typesafehub/netty-reactive-streams/blob/master/netty-reactive-streams/src/main/java/com/typesafe/netty/HandlerPublisher.java to use Netty properly.

**Comment by richdougherty** [comment]
@jroper, is this fixed now? I see you've updated netty-reactive-streams, just checking if the fix has made it into Play.

**Comment by jroper** [comment]
It's made it into Play.
