### ISSUE TITLE
[security] Insecure resolver in template

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#5396]
Do we need this resolver in [templates/play-scala/build.sbt](https://github.com/playframework/playframework/blob/master/templates/play-scala/build.sbt)? I don't think we should be depending on stuff that's not in a default repository.

    resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

If we're going to keep it, can we at least make it `https`? See more about the security risk here: http://blog.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/

**Comment by benmccann** [comment]
Apparently in 2.4.x you can get this error without the resolver:

>[info] Resolving org.scalaz.stream#scalaz-stream_2.11;0.7a ...
[warn]  module not found: org.scalaz.stream#scalaz-stream_2.11;0.7a
[warn] ==== local: tried
[warn]   /Users/Joseph/.ivy2/local/org.scalaz.stream/scalaz-stream_2.11/0.7a/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /Users/Joseph/.activator/repository/org.scalaz.stream/scalaz-stream_2.11/0.7a/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   /opt/typesafe/activator-1.3.6/repository/org.scalaz.stream/scalaz-stream_2.11/0.7a/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.11/0.7a/scalaz-stream_2.11-0.7a.pom

However, if we used a newer version then I think we could get it from Maven Central. See https://github.com/functional-streams-for-scala/fs2/issues/258#issuecomment-124001847

**Comment by benmccann** [comment]
Apparently we should use a newer version of specs2 to fix this. See https://github.com/etorreborre/specs2/issues/295

**Comment by wsargent** [comment]
Closing with https://github.com/playframework/playframework/pull/5397
