### ISSUE TITLE
[doc] Thread pools doc needs to be more specific

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#5400]
The ThreadPools documentation has sections that deal with thread pools configured for blocking IO:

https://www.playframework.com/documentation/2.4.x/ThreadPools

These sections need to point out that thread-pool-executor is better than fork-join in a blocking environment, and be more specific about the core pool size:

```
 blocking-io-dispatcher {
      type = "Dispatcher"
      executor = "thread-pool-executor"
      throughput = 1
      thread-pool-executor {
        core-pool-size-min = <size of max (NOT MIN) db connection pool>
        core-pool-size-max = <size of max db connection pool>
      }
    }
```

Also, akka.actor.default-dispatcher is roughly equivalent to Play's internal thread pool, and so should not be used for user-level tasks -- okay to use for Akka's scheduler, nothing else.  The page should point this out and define a general "user level thread pool".

**Comment by huntc** [comment]
This feels a little like déjà vu. I remember a conversation involving @viktorklang and others a couple of years ago. I recall the conversation steering toward there not being much difference and it occurring around the time I did the initial Techempower tests. My recall could be wobbly on this though.

**Comment by patriknw** [comment]
Note that the size-min, size-max is not a dynamic size, it's just the min/max cap of the pool size calculation based on number of processors.
Therefore I don't thinkt this makes sense:

```
        core-pool-size-min = <size of min db connection pool>
        core-pool-size-max = <size of max db connection pool>
```

I think it should be:

```
        core-pool-size-min = <size of max db connection pool>
        core-pool-size-max = <size of max db connection pool>
```

**Comment by wsargent** [comment]
also see https://github.com/akka/akka/issues/19201
