### ISSUE TITLE
activator test does not report correct execution status

### ISSUE THREAD

**Issue by carguel** [playframework/playframework#5403]
Command  ```activator test``` shows that several tests fail, for example:
```
[error] Test unittests.controllers.erp.SEISAPSSConfigurationControllerTest.getDefaultSEISConf failed: expected:<[200]> but was:<[404]>, took 0.003 sec
``` 
however final status at the end of execution is: 
```
[info] Passed: Total 25, Failed 0, Errors 0, Passed 21, Skipped 4
[success] Total time: 16 s, completed 16 déc. 2015 13:46:56
```
All failures are confirmed when I execute those tests directly from Eclipse.

After some investigations, it seems that only tests that extent  WithApplication have their status properly reported at the end of test execution.

Note also that report files under target/test-reports/*.xml do not include any failures.

Here are details of my configuration: 
 * play 2.3.8
 * activator 1.3.2
 * sbt  0.13.5

**Comment by carguel** [comment]
As an additional note, unit tests whose status is not properly reported are runned by a specific Junit Runner: 

```
   @RunWith(SpringJUnit4ClassRunner.class)
```

This is needed as my Play project depends on a third party library whose services are injected in my controllers by Spring.

**Comment by cchantep** [comment]
Closing it for now. Could be raised in a new ticket if reproduced against master.
