### ISSUE TITLE
Ebean enhancement in subprojects

### ISSUE THREAD

**Issue by oexza** [playframework/playframework#5407]
i asked this question in the group, gitter and stackoverflow but got no answer, asking her is my last resort

I'm trying to connect a simple application to two databases, the application has a subproject.
the model for the default database is in the main project while the model for the second database is in the subproject, like so;
    root/app/models/MainModel
    root/sub/app/mods/SubModel
now i configure the application.conf like so;
     
    db.default.driver=org.h2.Driver
    db.default.url="jdbc:h2:mem:play"
    #db.default.user=sa
    #db.default.password=""

     db.sub.driver=org.postgresql.Driver
     db.sub.url="jdbc:postgresql://localhost:5432/test"
     db.sub.username= postgres
     db.sub.password="password@1"

    ebean.default = ["models.*"]
    ebean.sub = ["mods.*"]
(yes i use postgre as the second db)
and the build.sbt like so

    lazy val sub = project.in(file("sub")).enablePlugins(PlayEbean, PlayEnhancer)

    lazy val root = (project in file(".")).enablePlugins(PlayJava, PlayEbean)
    .aggregate(sub)
    .dependsOn(sub)
    playEbeanModels in Compile := Seq("models.*", "mods.*")

but when i run the application i get this exception;

CreationException: Unable to create injector, see the following errors: 1) 
Error injecting constructor, java.lang.IllegalStateException: Bean class mods.SubModel is not enhanced?
what am i missing? how do i get this to work?

**Comment by adis-me** [comment]
This is not the place to ask Question, group or Stackoverflow is the place. Please post link to you SO question and close this issue. I will try to help you, but you need to post you Model and Submodel classes.

**Comment by oexza** [comment]
the MainModel and SubModel classes are simply entity classes marked with @Entity annotation.

**Comment by oexza** [comment]
this is the link to the stackoverflow question http://stackoverflow.com/questions/34345334/ebean-model-class-in-subproject-not-enhanced
