### ISSUE TITLE
Upgrade play-ebean

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#5410]
We should upgrade play-ebean before the 2.5.0 release.

Before upgrading we need to cut a new release for Play to use

When upgrading:

* We should remove ebean references from `./src/play-logback/src/main/resources/logback-play-default.xml` and `./src/play-logback/src/main/resources/logback-play-dev.xml` since the excessive logging is fixed by https://github.com/playframework/play-ebean/pull/68

**Comment by marcospereira** [comment]
After playframework/play-ebean#72 and playframework/play-ebean#72 I think we can move forward here.

@benmccann WDYT?

**Comment by benmccann** [comment]
@marcospereira yeah I think we can move forward on this
