### ISSUE TITLE
play 2.4.3 junit rule was not compeletely invoked when running unit test with a server.

### ISSUE THREAD

**Issue by Saber-Altria** [playframework/playframework#5419]
Hello:
I want to print log before and after a @Test method is execute.I define MyRule as follow:

    package rule;
    
    import org.junit.rules.MethodRule;
    import org.junit.runners.model.Statement;
    
    import play.Logger;
    
    import org.junit.runners.model.FrameworkMethod;
    
    public class MyRule implements MethodRule {
    	@Override
    	public Statement apply(Statement base, FrameworkMethod method, Object target) {
    		return new Statement() {
    			@Override
    			public void evaluate() throws Throwable {
    				Logger.info("start process " + target.getClass().getName() + "." + method.getName());
    				try {
    					base.evaluate();
    				} finally {
    					Logger.info("stop process " + target.getClass().getName() + "." + method.getName());
    				}
    			}
    
    		};
    	}
    }
then my TestRule class is  

    package rule;
    
    import org.junit.Rule;
    import org.junit.Test;
    
    import play.Logger;
    import play.test.WithServer;
    
    public class TestRule extends WithServer{
    
	    @Rule
	    public MyRule rule = new MyRule();
    
    	@Test
    	public void test1(){
    		Logger.info("execute test1");
    	}
    
    	@Test
    	public void test2(){
    		Logger.info("execute test2");
    	}
    }
I get the following result：

    [play_unit_test] $ testOnly rule.TestRule
    [info] - application - start process rule.TestRule.test1
    [info] - application - execute test1
    [info] - application - execute test2
    [info] Passed: Total 2, Failed 0, Errors 0, Passed 2
    [success] Total time: 3 s, completed 2015-12-22 18:25:32
after I remove extends WithServer in TestRule:

    package rule;
    
    import org.junit.Rule;
    import org.junit.Test;
    
    import play.Logger;
    import play.test.WithServer;
    
    public class TestRule {
    
	    @Rule
	    public MyRule rule = new MyRule();
    
    	@Test
    	public void test1(){
    		Logger.info("execute test1");
    	}
    
    	@Test
    	public void test2(){
    		Logger.info("execute test2");
    	}
    }
I get the expected result:

    [play_unit_test] $ testOnly rule.TestRule
    [info] - application - start process rule.TestRule.test1
    [info] - application - execute test1
    [info] - application - stop process rule.TestRule.test1
    [info] - application - start process rule.TestRule.test2
    [info] - application - execute test2
    [info] - application - stop process rule.TestRule.test2
    [info] Passed: Total 2, Failed 0, Errors 0, Passed 2
    [success] Total time: 1 s, completed 2015-12-22 18:29:04

it seems play does not invoke MyRule compeletely when test with a server .The same issue occure when test with a browser.

**Comment by benmccann** [comment]
If there's a bug here, you'll probably have a lot more luck getting it fixed if you can track it down and point out where it is as the team doesn't have the resources to do this type of investigative work on every issue that's submitted. This issue could be in https://github.com/sbt/junit-interface. I'd start by trying to repro the issue without Play just using junit-interface

**Comment by Saber-Altria** [comment]
Thank you for reply. In my further investigation ,I replace the Logger.info() method in finally bolck with System.out.println method. Ther I get following result:

[play_unit_test] $ testOnly rule.TestRule
[info] - application - start process rule.TestRule.test1
[info] - application - execute test1
stop process rule.TestRule.test1
[info] - application - execute test2
stop process rule.TestRule.test2
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 9 s, completed 2015-12-24 14:33:09

It seems the logger log the info to somewhere else rather than directly to console.
