### ISSUE TITLE
Separating  routes into different packages in play just like controllers.

### ISSUE THREAD

**Issue by pamu** [playframework/playframework#5421]
declaring Routes in the respective controllers package in play

Controller can be any class or object which extends Play.api.mvc.Controller and they can be in any package. I want to write routes along with the Controllers in the same package. This allows clean separation of concerns.  

![componentmodel](https://cloud.githubusercontent.com/assets/4508686/12003276/fa1b1a00-ab3d-11e5-9538-04da07df9dda.png)

In the above picture in the buyers package routes of buyers are declared along with the controller and same in case of analytics package also. The routes of analytics are declared along with analytics controllers in the same package.

**Comment by gsmaverick** [comment]
@pamu This is not an issue with the Play framework and should probably be posted on the mailing list instead: https://groups.google.com/forum/#!forum/play-framework

**Comment by pamu** [comment]
@gsmaverick  Sure, Thanks
