### ISSUE TITLE
Play Json BigDecimal type lost precision when writing

### ISSUE THREAD

**Issue by ysihaoy** [playframework/playframework#5423]
For example I have following code
```
case class Person(name: String, pay: BigDecimal)
val person = Person(name = "Scala", pay = BigDecimal(10.00))
Json.toJson(person))
```

The JSON result should be
```
{
  "name": "Scala"
  "pay": 10.00
}
```
However the result is not as expected that's: 
```
{
  "name": "Scala"
  "pay": 10
}
```

Even I writes a Play Json implicit writes and it's still not working as expected:
```
implicit val bigdecimalWrites = new Writes[BigDecimal] {
    def writes(o: BigDecimal): JsValue = {
      JsNumber(o.setScala(2))
    }
  }
```
This issue should be fixed with the precision we specified.

It seems Gson has the same issue before but fixed. https://github.com/google/gson/issues/72

I guess it's a bug of Play Json

**Comment by mizerlou** [comment]
floats and doubles don't carry around a scale, so you either need to set the scale on the BigDecimal directly (or use the string constructor):

    scala> BigDecimal(10.00)
    res6: scala.math.BigDecimal = 10.0

    scala> BigDecimal(10.00).setScale(2)
    res7: scala.math.BigDecimal = 10.00

    scala> BigDecimal("10.00")
    res8: scala.math.BigDecimal = 10.00

so, try:

    Person("Scala", BigDecimal("10.00"))

or

    Person("Scala", BigDecimal(10).setScale(2))

**Comment by ysihaoy** [comment]
@mizerlou 

Thanks for reply. I tried your way as well, even I write implicit writes as following still not working:

```
implicit val bigdecimalWrites = new Writes[BigDecimal] {
    def writes(o: BigDecimal): JsValue = {
      JsNumber(o.setScala(2))
    }
  }
```

**Comment by gmethvin** [comment]
@ysihaoy Currently the Scala JSON library doesn't make any guarantees about how the number will be represented. From a JSON perspective, the number `10` is equivalent to `10.00`. Here it seems logical that it would use the simplest possible representation of the number.

**Comment by ysihaoy** [comment]
@gmethvin Thanks for reply.

I totally understand this and also that's what JSON number does. However any other json libraries for both Scala and Java provide a way called serializer or whatever to achieve ```10.00```.

I tried the following approach and it's not working.

```
implicit val bigdecimalWrites = new Writes[BigDecimal] {
    def writes(o: BigDecimal): JsValue = {
      JsNumber(o.setScala(2))
    }
  }
```

Or it will be great if you can help me to modify this code. Also, it doesn't quite make sense to let JSON return a String as we want it returns BigDecimal.

PS: For banking, finance industry, it's quite important to do this.

**Comment by mslinn** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/JSON#Data_portability_issues) "Numbers in JSON are agnostic with regards to their representation within programming languages. No differentiation is made between an integer and floating-point value: some implementations may treat 42, 42.0, and 4.2E+1 as the same number while others may not. Furthermore, no requirements are made regarding implementation issues such as overflow, underflow, loss of precision, or rounding. Additionally, JSON says nothing about the treatment of signed zeros: whether 0.0 is distinct from -0.0. Most implementations that use the IEEE 754 floating-point standard, including JavaScript, will preserve signed zeros; but not all JSON implementations may do so"

The issue you face has as much to do with `BigDecimal` as with JSON. You need to separate the issues in order to achieve the results you want. I modified, updated, improved and extended [this Currency class](http://www.thomasknierim.com/114/scala/scala-currency-class/) and it behaves nicely now. The class is several hundred lines of code now.

A couple of years ago I asked the original author to apply a license to his work, preferably Apache or MIT, but he never responded. If he gives his blessing I would be happy to make the modified source  for the `Currency` class. In the meantime, I suggest you get a `Currency` class working the way you like, then you will find that persisting it becomes quite easy.

**Comment by ysihaoy** [comment]
@mslinn Thanks for reply.

I think I need to modify my post and add following code I write for ```implicit writes```

```
implicit val bigdecimalWrites = new Writes[BigDecimal] {
    def writes(o: BigDecimal): JsValue = {
      JsNumber(o.setScala(2))
    }
  }
```

Can you point out that what's the issue with this code? It's great for you ```Currency``` code. But I really don't want to add this to my code base as it's just a simple ```BigDecimal``` type and want to return the json two reserve two decimal types.

I still think it's a bug of Play Json as other libraries achieve the expected result for me.

**Comment by mslinn** [comment]
It is amazing the problems that go away when the proper abstraction is chosen. A low-level approach will be fragile, and will be acquire a reputation for code that must not be touched, lest it break. A `Currency` type imposes low overhead (if implemented properly) and is robust.

**Comment by gmethvin** [comment]
@ysihaoy I also agree with @mslinn that you should rethink the abstractions you're using.

As someone who has written financial software in a couple different contexts, I would generally avoid using JSON numbers where precision is important. The most popular JSON parsers (including ECMAScript's JSON.parse) will treat your number the same way regardless of the way it is in the source, and the JSON representation of your value should be robust to this.

play-json tries to write the simplest representation of  your `JsNumber`. This is not a bug. I think it _may_ be a valid feature request to allow configurability here (I believe Jackson allows this), but I'm not sure your reasons for doing it are valid.

You should create a thread on the mailing list if you would like to discuss further.

**Comment by ysihaoy** [comment]
@gmethvin You shouldn't close this issue. 

As Play Json should support this feature to allow us to do this using Json.

I can't understand why Play framework community is not welcome to allow new feature to come and also I raised this in mailing list and no one answer this which is so weird.

If your play framework community keeps doing this, I wouldn't recommend using that.

**Comment by ysihaoy** [comment]
@gmethvin 

If you don't think there is a bug for Play Json, so please answer me why the following code not working.
```
implicit val bigdecimalWrites = new Writes[BigDecimal] {
    def writes(o: BigDecimal): JsValue = {
      JsNumber(o.setScala(2))
    }
  }
```

Thanks.

**Comment by cchantep** [comment]
Hi, as indicated in the [contribution guidelines](https://github.com/playframework/playframework/blob/master/CONTRIBUTING.md), I think the better place to discuss it is the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) (not this issue tracker dedicated to confirmed issues & actionable requests). Best regards.

**Comment by gmethvin** [comment]
@ysihaoy You can only use a `Writes` to change which JSON types your Scala types are transformed into, not how those JSON types are written out. In this case, we always write a `JsNumber` the same way regardless of what the scale is, so your code doesn't really do anything.

**Comment by mslinn** [comment]
@ysihaoy You'll need to serialize to `JsString` in order to completely control the representation
