### ISSUE TITLE
Play Json BigDecimal Precision bugs

### ISSUE THREAD

**Issue by ysihaoy** [playframework/playframework#5424]
Given the source code in playframework,

https://github.com/playframework/playframework/blob/master/framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala 
and
https://github.com/playframework/playframework/blob/master/framework/src/play-json/src/main/scala/play/api/libs/json/Json.scala

There seems a bug for Play Json regards the code ```BigDecimal("10.00")``` as ```BigDecimal("10")``` and you only consider the situation for the case ```BigDecimal("10.01")```.

That's the reason the implicit writes code following:
```
implicit val bigdecimalWrites = new Writes[BigDecimal] {
    def writes(o: BigDecimal): JsValue = {
      JsNumber(o.setScala(2))
    }
  }
```
or
```
implicit val bigdecimalWrites = new Writes[BigDecimal] {
    def writes(o: BigDecimal): JsValue = {
      JsNumber(BigDecimal(o.setScala(2)))
    }
  }
```
doesn't work.

Should fix this bug.

**Comment by gmethvin** [comment]
`10.00` is the same number as `10` in JSON. Please open a discussion on the mailing list if you would like to discuss further.
