### ISSUE TITLE
2.4 Crypto global object misses configuration

### ISSUE THREAD

**Issue by eleaar** [playframework/playframework#5425]
Hi,

In the case of no current Application, the crypto global object [link](https://github.com/playframework/playframework/blob/702e89841fc54f5603a0d981c3488ed9883561fe/framework/src/play/src/main/scala/play/api/libs/Crypto.scala#L41) is created with an incomplete configuration. 
As `play.crypto.secret` and `play.crypto.provider` are missing (instead of being null), an exception will be thrown by PlayConfig#getOptional.

**Comment by wsargent** [comment]
Closing -- Play framework assumes a running Play application, and Crypto (and other global static methods that can be called outside of a Play context) are still subject to that.

**Comment by gmethvin** [comment]
@wsargent if so, I think the code should throw an exception immediately there instead of making a partial attempt to create an instance.

**Comment by wsargent** [comment]
Okay.
