### ISSUE TITLE
Getting an Error connecting to almost all databases

### ISSUE THREAD

**Issue by allnash** [playframework/playframework#5433]
CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, Configuration error: Configuration error[Cannot connect to database [default]]
  while locating play.api.db.DBApiProvider
  while locating play.api.db.DBApi
    for parameter 0 at play.db.DefaultDBApi.<init>(DefaultDBApi.java:28)
  at play.db.DefaultDBApi.class(DefaultDBApi.java:28)
  while locating play.db.DefaultDBApi
  while locating play.db.DBApi
    for field at play.db.DBModule$NamedDatabaseProvider.dbApi(DBModule.java:61)
  while locating play.db.DBModule$NamedDatabaseProvider
  at com.google.inject.util.Providers$GuicifiedProviderWithDependencies.initialize(Providers.java:149)
  at play.db.DBModule.bindings(DBModule.java:40):
Binding(interface play.db.Database qualified with QualifierInstance(@play.db.NamedDatabase(value=default)) to ProviderTarget(play.db.DBModule$NamedDatabaseProvider@5c759de3)) (via modules: com.google.inject.util.Modules$Override

I have verified that the set up works for PLAY version 2.4.3 

Please take a look at the attached project.

[one.zip](https://github.com/playframework/playframework/files/76671/one.zip)

**Comment by allnash** [comment]
Basically can't create - evolve any databases which is weird.

**Comment by gmethvin** [comment]
This tracker is for reporting bugs in Play. I would suggest posting this on stackoverflow or the [mailing list](https://groups.google.com/forum/#!forum/play-framework) to get help debugging the issue. Once you've confirmed an actual bug you can report it here.
