### ISSUE TITLE
2.4 Testing with Fakeapplication: h2 database is not reset after each test

### ISSUE THREAD

**Issue by nemoo** [playframework/playframework#5437]
This works in Play 2.3:
I am using a h2 database for tests. The h2 database is reset after each single test. This is what i want to achieve so that my individual test cases are fully isolated from each other.
Example test in play 2.3 project (passes):
https://github.com/nemoo/democratizer/blob/master/test/IsolationSpec.scala

In Play 2.4 the behaviour changed:
I am using a h2 database for tests. The h2 database is NOT reset after each single test.
Example test in play 2.4 project with Specs 2 (fails):
https://github.com/nemoo/play-slick3-example/blob/master/test/ModelSpec.scala
Example test in play 2.4 project with Scalatest (fails):
https://github.com/nemoo/play-slick3-example/blob/master/test/ModelSpec2.scala

I have already asked about this in the google group https://groups.google.com/forum/#!topic/play-framework/PYZLtXZC8ss and on stackoverflow: http://stackoverflow.com/questions/34559080/how-to-reset-the-in-memory-database-in-tests-with-play2-slick3-specs2

Since works nicely in Play 2.3, this looks like a regression to me. Or am I doing something wrong?

**Comment by wsargent** [comment]
Closing -- h2 is not included with Play in 2.6 going forward.
