### ISSUE TITLE
Needs Better Json parsing error message

### ISSUE THREAD

**Issue by cwei-bgl** [playframework/playframework#5438]
Having something like below is difficult to locate the problems. What do you think?
```
java.lang.RuntimeException: JsError(List((/_id,List(ValidationError(List(error.expected.jsstring),WrappedArray())))))
at scala.sys.package$.error(package.scala:27)
```

**Comment by cchantep** [comment]
Hi, for design discussion, please first post on the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework). Best regards.
