### ISSUE TITLE
Bug in email validation

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#5440]
Having a form with ```play.data.validation.Constraints.Email``` annotation:
```
public class LoginForm {
	@Constraints.Email
	@Constraints.Required
	private String email;
}
```
allows this email: ```foo@bar``` which is wrong

**Comment by studiodev** [comment]
Everybody has a different interpretation of "what is a valid email address ?"

According to the RFC, foo@bar is a valid email (eg john@localhost). But I don't know any internet website that would intentionally accept this email.

I recommend to you to create your own email validation by using the Regex validator.
And maybe we could discuss about the rightfulness of the email validator in Play, but in the ML ;)

**Comment by pauldraper** [comment]
See https://github.com/playframework/playframework/issues/4022.

**Comment by eximius313** [comment]
ok, thanks
