### ISSUE TITLE
Allow configuration of play.core.Execution.internalContext

### ISSUE THREAD

**Issue by pauldraper** [playframework/playframework#5441]
I want to be able to configure `play.core.Execution.internalContext`.

Or replace it with the configurable `play.api.libs.ExecutionContext.defaultContext`. (Why are there two?)

---

This is a bit of a tangent, but here's my motivating use case:

I want to be able to link the initial request to all logged messages in my application.

I can use [MDC](http://www.slf4j.org/api/org/slf4j/MDC.html) for logging thread local information. Using an EssentialFilter, I set a thread local "flow id" when the request arrives, and that id is included in every log. However, Play is asynchronous, so the logical flow often switches threads.

For that reason, I have a ExecutorService that wraps another. It reads the current thread local flow id, and then wraps the `Callable`/`Runnable`, which when run, sets the flow id on that next thread. I can substitute my custom ExecutionContext provider via `play.akka.actor`.

This works perfectly, with one exception. The problem is, that if there is more than 1024 bytes, Play's body parsers wind up switching to another thread on their own private ExecutionContext and lose it. Sample:

``` scala
package example

import play.api.mvc._

object Flow extends Controller {
  def apply() = Action(parse.tolerentText)(Ok(s"${FlowId.get}\n"))
}
```

``` hocon
play.akka.actor.default-dispatcher.executor = example.MyExecutorProvider

# and add the EssentialFilter elsewhere
```

``` sh
$ curl -X POST -d "$(base64 /dev/urandom | head -c 1024)" http://localhost/flow
Some(CBWOXQ)
$ curl -X POST -d "$(base64 /dev/urandom | head -c 1025)" http://localhost/flow
None
```

---

I can implement wrappers around Play's default body parsers, but it's tedious to make sure those are always used; it'd be nice if I was able to control the `ExecutionContext`/`ExecutorService`, like I was for the Akka ExecutorService.

....or just not have a separate context for the body parsers. That context is private to play so I can't use it in my own custom parsers unless I put them in packages named `play`.

**Comment by schmitch** [comment]
Currently play automatically generate's a request id. (https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/Http.scala#L24)

Also I don't think that is is suitable, since Play follows the Netty Thread Model which switches the Thread anyway: http://netty.io/wiki/thread-model.html

**Comment by pauldraper** [comment]
> Currently play automatically generate's a request id. 

I use [MDC](http://www.slf4j.org/api/org/slf4j/MDC.html) so that I don't need to have a implicit `Request` everywhere, for every log message.

> Also I don't think that is is suitable

This works perfectly now, with one exception: requests with entities that are over 1kb and parsed by Play's body parsers.

---

I mentioned that use case only as a bit background.

Independent of that, there are ultimately three issues with `play.core.Execution.internalContext`.

1. It is partially configurable, but no via the same mechanism as Play's [other thread pools](https://www.playframework.com/documentation/2.3.x/ThreadPools), which are configurable via Akka. The inconsistency is a little odd.

2. The thread pool is inaccessible outside the `play` package. In particular, this means *I can't write the same body parsers* as Play. Body parsers are meant to be an extensible part of Play, but there is something "special" about Play's own default body parsers.

3. There is no reason (that I can see) for body parsers to use a different thread pool than everything else.

Changing the internal thread pool to use Akka would fix 1 and 2. Removing it altogether would fix all three.

**Comment by wsargent** [comment]
The internal context shouldn't be accessible by end user -- the best way to ensure context is with an implicit marker context:

https://playframework.com/documentation/2.6.x/Highlights26#Logging-Marker-API

As @schmitch says, using a logging model that depends on internal thread assumptions is dangerous, especially since 2.6.x switches to Akka-HTTP (and may do more things with switching threads streams internally)
