### ISSUE TITLE
java.lang.IllegalArgumentException: invalid version format

### ISSUE THREAD

**Issue by andyczerwonka** [playframework/playframework#5442]
I don't know if this is an issue in configuration of whether this is a bug, but I thought I had better log it to get visibility.

There is no application code in this stack trace, so I'm not even sure how to triage this.

https://gist.github.com/andyczerwonka/2ddfcd1039577271586a

**Comment by andyczerwonka** [comment]
Just a note, my Play 2.4.3 application is behind and nginx front-end with the following configuration.

```
proxy_buffering    off;
proxy_set_header   X-Real-IP $remote_addr;
proxy_set_header   X-Forwarded-Proto $scheme;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header   Host $http_host;
proxy_http_version 1.1;
```

**Comment by pauldraper** [comment]
IIRC, this means that HTTPS is being sent to Play which is expecting HTTP.

**Comment by andyczerwonka** [comment]
Hmnnn... I configured as per [the instructions](https://www.playframework.com/documentation/2.4.x/HTTPServer). So I have to get Play to expect HTTPS somehow?

**Comment by gmethvin** [comment]
@andyczerwonka I am almost positive your nginx proxy is not configured properly. It's best to debug this problem on the mailing list before reporting an issue with Play.
