### ISSUE TITLE
PlayJava Websocket documentation shows static controller method

### ISSUE THREAD

**Issue by scmurdock** [playframework/playframework#5445]
https://www.playframework.com/documentation/2.3.x/JavaWebSockets

This code will not run because the method is static:

package controllers;

import play.*;
import play.mvc.*;

import views.html.*;

public class Application extends Controller {

    public static WebSocket<String> socket() {
         return WebSocket.withActor(MyWebSocketActor::props);
    }

    public Result index() {
        return ok(index.render("Your new application is ready."));
    }

}

Compiling 6 Scala sources and 3 Java sources to C:\Users\Administrator\play-java\target\scala-2.11\classes...
C:\Users\Administrator\play-java\conf\routes:11: value socket is not a member of controllers.Application
GET     /socket                     controllers.Application.socket()
one error found

**Comment by gmethvin** [comment]
Hi @scmurdock,

You've linked the 2.3 documentation there. At the time static controllers were still the "recommended" way to do things. The [2.4 documentation](https://www.playframework.com/documentation/2.4.x/JavaWebSockets) shows the non-static version.

If you like you could submit a PR to clarify, but I think we use the same convention throughout the documentation.
