### ISSUE TITLE
Composing Actions with andWith breaks typing for custom WrappedRequests with extra type parameters

### ISSUE THREAD

**Issue by rgladwell** [playframework/playframework#5446]
Combining an `ActionBuilder` that transforms a request into a custom `WrappedRequest` with an additional type parameter, and then combining that with another `Action` or `ActionFilter` using `andWhen` causes the type of the custom `WrappedRequest` to  be dropped.

For example, lets say I need to an authentication `ActionBuilder` and an optional, authorisation `ActionFilter` where the user type we need can vary depending on use.

See this contrived code:

```scala
    case class AuthRequest[A, U](val request: Request[A], val user: U) extends WrappedRequest[A](request)

    case class TestUser(id: String)
    
    case class AuthenticationAction[A]() extends ActionBuilder[({type λ[B] = AuthRequest[B, TestUser]})#λ] {
    
      override def invokeBlock[A](request: Request[A], block: (AuthRequest[A, TestUser]) => Future[Result]): Future[Result] =
        block(AuthRequest(request, TestUser("test-id")))
    
    }
    
    case class AuthorisedAction[A]() extends ActionFilter[({type λ[B] = AuthRequest[B, TestUser]})#λ] {
    
      // does some additional authorisation checks for added security
      def authorised(user: TestUser) = true
    
      override def filter[A](request: AuthRequest[A, TestUser]) = Future.successful {
        if( authorised(request.user) ) None
        else Some(Unauthorized)
      }
    
    }
```

**Please note:** The type function in the above is required as per [this Stackoverflow answer](http://stackoverflow.com/a/19345482/48611) because of the additional type parameter on the `AuthRequest`. Again this is required because this API will be used with more than one type of user.

If I then implement a controller that uses the above:

```scala
    class ExampleController extends Controller {
      
      def secured = (AuthenticationAction() andThen AuthorisedAction()) { request =>
        Ok(request.user.id)
      }
    
    }
```

I get a compiler error (`value user is not a member of play.api.mvc.WrappedRequest[play.api.mvc.AnyContent]`). In other words, the type of the variable `request` above is `WrappedRequest` instead of the expected type of `AuthRequest[play.api.mvc.AnyContent, TestUser]`!

I understand that most use cases the `AuthenticationAction` and `AuthorisedAction` would be combined into a single action but, because authorisation is optional, I would like to keep these as separate concerns.

Is this possible? Is this a bug in the Play Framework API? Or a Scala bug? Or human error?

Please see this sample project for an example of the code that doesn't compile:

https://github.com/rgladwell/test-action-compose-with-custom-wrapped

**Comment by cchantep** [comment]
Hi, please ask question or discuss design on the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework), rather than this tracker (dedicated to confirmed issue or actionable feature request). Best regards.

**Comment by lovepocky** [comment]
I met same problem.
I have solved it by replacing `A andThen B` with `B compose A`.
but I don't known the cause.
