### ISSUE TITLE
WS client dont get right cookie in case of duplication

### ISSUE THREAD

**Issue by sanjarbek** [playframework/playframework#5448]
Today I have a problem of getting right cookie by name causing of duplication. I made login request with post method to web site. In cookies I have two session_id. The second one is right cookie. But when I do <code>response.cookie("session_id")</code>
I get first one which seems old.  I analyze, now I am doing like this
<code>response.cookies.last</code>
Of course it is now works every time. So is there any standard and is it possible to do it work right with ws client?
I tested with php curl, no problem.

**Comment by cchantep** [comment]
Hi, please first ask question on the [MailingList]( https://groups.google.com/forum/m/#!forum/play-framework) (rather than this tracker dedicated to confirmed issue). Best regards.

**Comment by sanjarbek** [comment]
@cchantep I already looked up there. https://groups.google.com/forum/m/#!searchin/play-framework/ws$20client$20cookie/play-framework/B_FXQXQUQtI
But seems nothing changed.
