### ISSUE TITLE
Play 2 Option Missing Under Scala Plugin w/Intellij 15 CE

### ISSUE THREAD

**Issue by ronaldpetty** [playframework/playframework#5455]
Hi,

I have the following set up:
* Mac 10.11.2
* JDK 8
* Intellij 15 CE
* Scala Plugin

I am attempting this tutorial here: https://www.playframework.com/documentation/2.2.x/IDE#IntelliJ

Play 2 does not seem to be a project option under the Scala plugin.  I have so far not found anything conclusive on how to enable Play 2.x in that mentioned version of Intellij+Scala plugin.  I see under the Ultimate edition it might already be built in and supported.  For the record, SBT and Activator are listed under the options.  I tried activator thinking maybe there would be options to create a play based system, but there are none that I can find.

Any guidance appreciated.

Regards.

Ron

**Comment by djx314** [comment]
Are you already setting the project jdk in file -> project structrue -> project settings -> project -> project sdk ? It need to be set in any project use jdk.

**Comment by ronaldpetty** [comment]
Hi @djx314 

To your point, I had to add the JDK after the fact.  I created a new Activator project because again "Play 2" was not an option.  It does compile, but no "Run as" option exists.  I also attached a screen of the tests failing (which I see reported around town as an issue with the latest version, I can't confirm that though.)

![image](https://cloud.githubusercontent.com/assets/1390435/12228533/bcaf3b72-b7f1-11e5-847d-7bf84750e7e9.png)

![image](https://cloud.githubusercontent.com/assets/1390435/12228595/b1062ef6-b7f2-11e5-9c4f-53d18ee4e0b9.png)

Thank you for assisting.

Ron

**Comment by nafg** [comment]
Yes you need Ultimate. But this is not a bug for the issue tracker, it's a
question for the mailing list.

**Comment by ronaldpetty** [comment]
Nafg, 

I was not sure if it was a bug or just a feature issue.  Thanks, I suppose we can close this and see if I can find a way to use Play on CE via the forum.

Regards.

Ron

**Comment by rarcot** [comment]
@ronaldpetty - Yep agree. It should mention IntelliJ Ultimate.
