### ISSUE TITLE
Broken example in JavaHttpFilters documentation page

### ISSUE THREAD

**Issue by vidvid** [playframework/playframework#5456]
At [JavaHttpFilters](https://www.playframework.com/documentation/2.4.x/JavaHttpFilters) documentation page for play 2.4, after the sentence *"In that case, you might update the logTime method to look like this:"* no code example follows.

**Comment by mkurz** [comment]
@dotta You created this docs.

**Comment by wsargent** [comment]
@mkurz I don't think you can create a filter in Java at all, so the only thing you can do from Filters is reference a Scala filter.

**Comment by wsargent** [comment]
Also see https://github.com/playframework/playframework/pull/5500

**Comment by mkurz** [comment]
This has been fixed with #5500
