### ISSUE TITLE
[doc] Document play.filters.csrf.header.bypass

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#5458]
In https://www.playframework.com/documentation/2.4.x/ScalaCsrf#Plays-CSRF-protection, there is a section talking about how `X-Requested-By` will bypass the CSRF filter.

There is a setting 

```
play.filters.csrf.header.bypass = false
```

That should be documented in this section to disable this check.

**Comment by mkurz** [comment]
+1

**Comment by gmethvin** [comment]
This should have been superseded by my changes to the CSRF config to use `bypassHeaders` and `protectHeaders`.
