### ISSUE TITLE
Use DELETE_ON_CLOSE for TemporaryFile

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#5459]
The TemporaryFile system access uses straight FileOutputStream and will close the file descriptor using a finalizer:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/libs/Files.scala#L105

It would be nice if TemporaryFile access used DELETE_ON_CLOSE so that TemporaryFile lifecycle is directly connected to the IO:

https://www.securecoding.cert.org/confluence/display/java/FIO03-J.+Remove+temporary+files+before+termination

**Comment by gmethvin** [comment]
I started trying to fix this and ran into a couple of issues including one similar to http://stackoverflow.com/questions/18146637/delete-on-close-deletes-files-before-close-on-linux.

Also it seems some of the APIs and tests currently involving closing files and reopening them (often indirectly).
