### ISSUE TITLE
Override default play settings

### ISSUE THREAD

**Issue by shyamsalimkumar** [playframework/playframework#5461]
So I want to move my project from the default `app` folder to the `src/main/scala` folder. I'm using play `2.4.3`. For this I attempted to do the following in my `Build.scala`, but now it seems that its not detecting my routes.
```
lazy val api = Project(
    "api",
    file("."),
    settings = buildSettings ++ Seq(
      libraryDependencies ++= Dependencies.api,
      sourceDirectory in Compile <<= baseDirectory(_ / "src" / "main"),
      sourceDirectory in Test <<= baseDirectory(_ / "src" / "test"),
      confDirectory <<= baseDirectory(_ / "src" / "main" / "resources"),
      resourceDirectory in Compile <<= baseDirectory(_ / "src" / "main" / "resources"),
      mainClass in (Compile, run) := Some("play.core.server.NettyServer")
    )
  )
```

My current folder (broken application) structure
```
src/
|-- main
|   |-- java
|   |-- resources
|   |   |-- application.conf
|   |   `-- routes
|   `-- scala
```
Could someone point out what I'm doing wrong?

**Comment by dotta** [comment]
@shyamsalimkumar Hi! Please, ask usage questions in the [playframework mailing list](https://groups.google.com/forum/#!forum/play-framework). For reference, you can achieve what you want by disabling the `PlayLayoutPlugin` in your build, see https://www.playframework.com/documentation/2.4.x/Anatomy#Default-SBT-layout (if you have follow up questions, please ask them in the playframework mailing list. Thanks!).
