### ISSUE TITLE
Cann't Custom Error Page in PlayFramework2.4.x

### ISSUE THREAD

**Issue by nikkofu** [playframework/playframework#5464]
I did these and still can't see my custom page, please help,

1. add MyGlobal.java extends GlobalSettings

2. add onHandlerNotFound to override:

    @Override
	public F.Promise<Result> onHandlerNotFound(RequestHeader request) {
		Logger.error("onHandlerNotFound!");
		return Promise.<Result> pure(Results
				.notFound(views.html.page404.render()));
	}

3. add application.global = "MyGlobal"  in application.conf

But nothing happened, play2.4.6 still runs out the default page from devNotFound.scala.html in playframework source folder of framework/play/src/main/scala/views/defaultpages/

thanks.

**Comment by mkurz** [comment]
This should be discussed on the mailing list: ps.google.com/forum/?fromgroups#!forum/play-framework

In dev mode you always see the `devNotFound.scala.html` page - only in prod (production) mode you will see your own defined 404 page.
