### ISSUE TITLE
Distribute play activator using sdk package manager

### ISSUE THREAD

**Issue by simonmittag** [playframework/playframework#5470]
please consider distributing the activator binaries via the sdk package manager (http://sdkman.io/) which already has support for scala and sbt. this would make one neat package manager for all my java/scala related frameworks.

activator is notably absent from the below list: 

sdk current
Using:
ant: 1.9.6
gradle: 2.10
grails: 3.0.11
groovy: 2.4.5
maven: 3.3.9
sbt: 0.13.9
scala: 2.11.7
springboot: 1.3.1.RELEASE
vertx: 3.2.0

**Comment by benmccann** [comment]
You'd probably do better filing requests for activator at https://github.com/typesafehub/activator/issues

**Comment by mkurz** [comment]
See https://github.com/typesafehub/activator/issues/1088
