### ISSUE TITLE
[scaladoc] DefaultHttpErrorHandler and GlobalSettingsHttpErrorHandler both claim default

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#5474]
Minor bug, but before I forget about it:

```
/**
 * HTTP error handler that delegates to legacy GlobalSettings methods.
 *
 * This is the default error handler, and ensures that applications that provide custom onHandlerNotFound, onBadRequest,
 * and onError implementations on GlobalSettings still work.
 *
 * The dependency on GlobalSettings is wrapped in a Provider to avoid a circular dependency, since other methods on
 * GlobalSettings also require invoking this.
 */
```

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala#L62

and 

```
/**
 * The default HTTP error handler.
 *
 * This class is intended to be extended, allowing users to reuse some of the functionality provided here.
 *
 * @param environment The environment
 * @param router An optional router.
 *               If provided, in dev mode, will be used to display more debug information when a handler can't be found.
 *               This is a lazy parameter, to avoid circular dependency issues, since the router may well depend on
 *               this.
 */
```

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala#L101

**Comment by gmethvin** [comment]
We are deprecating `GlobalSettingsHttpErrorHandler` right? We could do that in the same PR as fixing this.

But it would also be good to backport a documentation change to 2.4.x

**Comment by wsargent** [comment]
It's not quite that simple -- GlobalSettingsHttpErrorHandler is already play private, so deprecating it isn't any good because users can't get to it anyway.   The `play.it.mvc.GlobalFiltersSpec` makes use of the GlobalSettingsHttpHandler internally when calling out to GuiceApplicationBuilder.global, so if you take out GlobalSettingsHttpHandler, it's that which fails if you change the binding configuration:

```

trait GlobalFiltersSpec extends FiltersSpec {
  def withServer[T](settings: Map[String, String] = Map.empty, errorHandler: Option[HttpErrorHandler] = None)(filters: EssentialFilter*)(block: WSClient => T) = {

    import play.api.inject.bind

    val app = new GuiceApplicationBuilder()
      .configure(settings)
      .overrides(bind[Router].toInstance(testRouter))
      .global(
        new WithFilters(filters: _*) {
          override def onHandlerNotFound(request: RequestHeader) = {
            errorHandler.fold(super.onHandlerNotFound(request))(_.onClientError(request, 404, ""))
          }
        }
      ).build()

    Server.withApplication(app) { implicit port =>
      import app.materializer
      WsTestClient.withClient(block)
    }
  }
}
```

GlobalSettings itself is deprecated, so when it goes, this should go as well.  You could make a good argument for deprecating `GuiceAppliationBuilder.global` I suppose

**Comment by gmethvin** [comment]
@wsargent Thanks for enlightening me. I neglected to look at the code to see that it wasn't public API.

I wouldn't have a problem with deprecating `GuiceApplicationBuilder.global`. As long as GlobalSettings and related public classes are deprecated we should be okay, though. That test code would still throw deprecation warnings on `WithFilters`.
