### ISSUE TITLE
Windows .bat file could not be run

### ISSUE THREAD

**Issue by samuelstein** [playframework/playframework#5475]
When trying to start the generated .bat file  “Path too long” or “Input line too long” type of an error occurs.
A fix is described here: https://msopentech.com/blog/2014/09/25/tutorial-running-play-framework-applications-microsoft-azure-cloud-services-2/
Would be good to modify .bat generator.

**Comment by mkurz** [comment]
Check out https://github.com/sbt/sbt-native-packager/issues/72 and https://github.com/sbt/sbt-native-packager/pull/397
