### ISSUE TITLE
Repeated query parameters handling when binding requestData

### ISSUE THREAD

**Issue by archie-sh** [playframework/playframework#5476]
In Form.java line 207 when binding query parameters only one value is bound:
```
               if(values.length > 0) {
                    data.put(key, values[0]);
                }
```
if I use the following two query parameters localhost:9000/example?test=1&test=2 I expect to have two query parameters bound not only one.

**Comment by gmethvin** [comment]
It seems like it works if you do `test[]=1&test[]=2`. Not sure if there is currently a way for it to tell that it's an array besides using the `[]`.
