### ISSUE TITLE
[2.4.x-2.4.6] scala custom HttpErrorHandler ignored

### ISSUE THREAD

**Issue by jesterhazy** [playframework/playframework#5479]
play-scala is ignoring my CustomHttpErrorHandler and using the DefaultHttpErrorHandler instead.

I tested this in play-scala 2.4.1.-2.4.6. I believe issue is also present in 2.5.0-M2.

Sample project demonstrating the error is in this (github repo)[https://github.com/jesterhazy/playScalaCustomErrorHandlerTest].

Related to #4857, which is same problem but in play-java.

**Comment by wsargent** [comment]
So from:

https://github.com/jesterhazy/playScalaCustomErrorHandlerTest/blob/master/app/global/CustomHttpErrorHandler.scala#L19

You are overriding onProdServerError, but you are running your code using "activator run" which is in "dev" mode.  Try overriding `onServerError` instead.

**Comment by jesterhazy** [comment]
lol. right you are.
