### ISSUE TITLE
Why JPAApi does not have em method without argument?

### ISSUE THREAD

**Issue by zarinfam** [playframework/playframework#5482]
I have some code that using JPA global state and because of JPAApi does not have em method without argument, i can not use JPAApi: 

    private Task addTask(Task task) throws Throwable {
        return JPA.withTransaction("test1", false, () -> {
            JPA.em().persist(task);
            return task;
        });
    }

I can not use JPAApi because em method with String argument return new EntityManager that is not connect to transaction and the em method without argument does not exist in JPAApi.

**Comment by cchantep** [comment]
Hi, please use the [Mailing list](https://groups.google.com/forum/m/#!forum/play-framework) to ask question, or discuss of possible improvement. This tracker is dedicated to confirmed issue, or actionable feature request. Best regards.

**Comment by zarinfam** [comment]
This is not a question, this is a bug in JPAApi.
