### ISSUE TITLE
customised akka system stops unit test from launching 

### ISSUE THREAD

**Issue by zinking** [playframework/playframework#5488]
if I override the Global `onStart` `onStop` method, specs could not be launched in Intellij. 
some console logs

>[DEBUG] [01/23/2016 10:48:02.888] [main] [EventStream(akka://application)] logger log1-Slf4jLogger started
>[DEBUG] [01/23/2016 10:48:02.888] [main] [EventStream(akka://application)] Default Loggers started
[>[37minfo[0m] - play.api.libs.concurrent.ActorSystemProvider - Starting application default Akka system: application
>[[37minfo[0m] - application - Application shutdown
>[[37minfo[0m] - play.api.libs.concurrent.ActorSystemProvider - Shutdown application default Akka system: application
>[DEBUG] [01/23/2016 10:48:02.892] [application-akka.actor.default-dispatcher-2] [EventStream] shutting down: StandardOutLogger started
>[DEBUG] [01/23/2016 10:48:02.892] [application-akka.actor.default-dispatcher-2] [EventStream] all default loggers stopped

if the overriding is removed, then everything works again.

I even tried to guard the block with environment settings, but it doesn't work either

    override def onStart(app: Application) {
        if (!.env.equals("test")){
            Akka.system().actorOf(Manager.props, "feed-refresh-actor")
        }
        Logger.info("Application has started")
    }

    override def onStop(app: Application) {
        Logger.info("Application shutdown")
    }

**Comment by zinking** [comment]
I am using 2.11-2.4.2

**Comment by cchantep** [comment]
Hi, please use [the MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask question/for help. Best regards
