### ISSUE TITLE
Using RequestBuilder with disableUrlEncoding in NingWSRequest

### ISSUE THREAD

**Issue by chtefi** [playframework/playframework#5501]
Hey,

I had to deal with a non-escaped querystring for some authentication requirements.
`AsyncHttpClient` provides this feature, but because of the Play wrapper, it's not available :

Play code : (`play.libs.ws.ning`)
```java
public class NingWSRequest implements WSRequest {
...
  Request buildRequest() {
    RequestBuilder builder = new RequestBuilder(method);
```

But there is another parameter `disableUrlEncoding` that I wanted to set to `true` :

async-http-client (`com.ning.http.client`) :
```java
public class RequestBuilder extends RequestBuilderBase<RequestBuilder> {
  public RequestBuilder(String method) {
    super(RequestBuilder.class, method, false);
  }
  public RequestBuilder(String method, boolean disableUrlEncoding) {
    super(RequestBuilder.class, method, disableUrlEncoding);
  }
```

Right now, I have to build myself the `RequestBuilder`, such as :
```java
RequestBuilder builder = new RequestBuilder("GET", true);
builder.setUrl(url);
headers.forEach(builder::setHeader);
Request req = builder.build();
```

And use it with `AsyncHttpClient`, manually, instead of using the nice Play wrapper `WSClient.url(...)` that can return a `Promise<WSResponse>`.

Could it be possible to add something to set this parameter in the Play wrapper ?

I'm using Play 2.4.4 btw.

Thanks,

Stéphane

**Comment by wsargent** [comment]
I believe this is "play.ws.ning.useRawUrl": https://www.playframework.com/documentation/2.4.x/JavaWS#Using-WSClient
