### ISSUE TITLE
Method OPTIONS should accept body

### ISSUE THREAD

**Issue by dgofman** [playframework/playframework#5503]
Please can you include body for method OPTIONS

https://github.com/playframework/playframework/blob/master/framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala#L527

Base on HTTP documentation OPTIONS can accept body parameters 

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

> If the OPTIONS request includes an entity-body (as indicated by the presence of Content-Length or Transfer-Encoding), then the media type MUST be indicated by a Content-Type field. Although this specification does not define any use for such a body, future extensions to HTTP might use the OPTIONS body to make more detailed queries on the server. A server that does not support such an extension MAY discard the request body.

I hope these changes should fix this issue:

```scala
  def options[T](body: T)(implicit wrt: Writeable[T]): Future[WSResponse] =
    withMethod("OPTIONS").withBody(body).execute()

 /**
   * Perform a OPTIONS on the request asynchronously.
   * Request body won't be chunked
   */
  def options(body: File): Future[WSResponse] = withMethod("OPTIONS").withBody(FileBody(body)).execute()
  ```

**Comment by gmethvin** [comment]
@dgofman Do you actually have a use case for including a body? It's just a shorthand method for `withMethod("OPTIONS").withBody(body).execute()` so you can still use the WS client without it.

**Comment by dgofman** [comment]
I am using POSTMAN and we are planning to use method "OPTIONS" for avoid audit request payload.
As you know GET cannot accept body parameters. So, I planed to use method "PROPFIND" but you are not supporting. Please can you at least add body for "OPTIONS"


![image](https://cloud.githubusercontent.com/assets/147298/12620054/8f752a00-c4cf-11e5-91d1-088f605da36b.png)

![image](https://cloud.githubusercontent.com/assets/147298/12620078/a2138fb2-c4cf-11e5-9e98-463fa8aeff90.png)

**Comment by wsargent** [comment]
FYI, RFC 7231 replaces 2616 https://tools.ietf.org/html/rfc7231#section-4.3.7

**Comment by wsargent** [comment]
@dgofman As Greg said, you can use any method, including "PROPFIND", using the "withMethod" call: https://github.com/playframework/playframework/blob/master/framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala#L415

**Comment by marcospereira** [comment]
I think there is a minor misunderstanding here.

@dgofman In your second comment, you state that you are using Postman to send requests, but you suggested to change Play HTTP **client** code instead, which does not handle requests made to a Play application, but instead **executes** requests to other HTTP services.

If what you really want to do is to enable your Play application to (not **execute** but) **receive** and handle `OPTIONS` requests, the change should be done at another place:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala#L581-L595

Is that correct?

**Comment by dgofman** [comment]
Thanks @marcospereira , so I can defined my own method? Yes, I would like to pass body preload to the server by avoiding using POST/PUT/DELETE/PATCH methods

**Comment by gmethvin** [comment]
@dgofman It's not clear where the actual bug is here. I would suggest getting help on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).

It should be possible to define custom methods in Play, but you will probably have to explicitly set a body parser, since the default parser (as @marcospereira mentioned) does not work with arbitrary HTTP methods.

**Comment by dgofman** [comment]
@gmethvin  we are using workaround but I feel you may need to add body payload in OPTIONS request by documentation.
