### ISSUE TITLE
2.4.x `ignored` form fields should be retained as-is if form is filled with existing object

### ISSUE THREAD

**Issue by makkarpov** [playframework/playframework#5525]
Suppose you have following user structure:

```scala
case class User(username: String, password: String, isAdmin: Boolean = false)
```

And following form to allow users change their username and password:

```scala
val form = Form(
  mapping(
    "username" -> text,
    "password" -> text,
    "isAdmin"  -> ignored(false)
  )(User.apply)(User.unapply)
)
```

Of course, you don't want to allow users to edit `isAdmin` attribute through form, but admins should not lose their power when they want to change password.

The following code illustrates the issue:

```scala
val admin = User("admin", "password", true)
val data = Map("username" -> "admin", "password" -> "Pa$$word")
form.fill(admin).bind(data).get // User(admin, Pa$$word, false)
```

Either there should be another type of field that will retain existing values or this functionality should be added to `ignore` field.

**Comment by gmethvin** [comment]
@makkarpov As it is right now, `bind` is expected to fill all the values of the form. You could possibly achieve the same thing by creating a form for each user:

```scala
def formModifyingUser(user: User): Form[User] = Form(
  mapping(
    "username" -> text,
    "password" -> text,
    "isAdmin" -> ignored(user.isAdmin)
  )(User.apply)(User.unapply)
)

formModifyingUser(admin).bind(data).get
```

It's probably best to be explicit when dealing with sensitive stuff like admin privileges.

If you would like to discuss further I think it would be better to discuss on the [mailing list](https://groups.google.com/forum/#!forum/play-framework). It's possible some people rely on the existing functionality, so we would be unlikely to change it or add to the API without some discussion.
