### ISSUE TITLE
cannot run the play source code to do web project

### ISSUE THREAD

**Issue by wangyiran126** [playframework/playframework#5530]
i want to create a web project with play which is the  source code not the jar ,but i cannot find a way to configure the build.sbt to refer the source,and i try some way it report there is no main method ,and i cannot find the completed document to do it.

**Comment by marcospereira** [comment]
Please, use the [mailing list](https://groups.google.com/forum/#!forum/play-framework) when you have doubts about how to use the framework. 

The issue tracker here is reserved for bug and new features only.
