### ISSUE TITLE
JsError.toFlatJson is deprecated, but indicated alternative is a private method

### ISSUE THREAD

**Issue by maesenka** [playframework/playframework#5531]
This method carries a deprecated notice saying "Use toJson which include alternative message keys", but the relevant method is defined as private

**Comment by marcospereira** [comment]
The methods matching the signature of the deprecated methods are public:

https://github.com/marcospereira/playframework/blob/ef34765a84b398b48e5800cbe6558c0ef034cfd6/framework/src/play-json/src/main/scala/play/api/libs/json/JsResult.scala#L43-L44

The same is true to Play 2.4.x branch:

https://github.com/marcospereira/playframework/blob/2.4.x/framework/src/play-json/src/main/scala/play/api/libs/json/JsResult.scala#L43-L44

@maesenka, can we close this issue?

**Comment by maesenka** [comment]
The methods matching the signature of the deprecated methods are not those, but 
https://github.com/marcospereira/playframework/blob/ef34765a84b398b48e5800cbe6558c0ef034cfd6/framework/src/play-json/src/main/scala/play/api/libs/json/JsResult.scala#L53

**Comment by wsargent** [comment]
Looks like this was deprecated and added as private all in one commit: https://github.com/marcospereira/playframework/commit/60f60a0f1e8f25453396546994b8593438529856

**Comment by saosebastiao** [comment]
Could we re-enable this functionality? Either `JsError.toJson(e,true)` or `JsError.toFlatJson` is fine by me.

**Comment by graingert** [comment]
@cchantep looks like this is a pretty popular feature. Why was it removed?

**Comment by cchantep** [comment]
This is not removed but replaced by `JsError.toJson` alternatives.

**Comment by saosebastiao** [comment]
As explained in the thread, the toJson method which allows flattening is marked private. Is there a merged request that fixes this?

**Comment by graingert** [comment]
@cchantep ^

**Comment by fkoehler** [comment]
^^?

**Comment by graingert** [comment]
@cchantep can you explain in more detail please?

**Comment by cchantep** [comment]
Please use the [MailingList](https://groups.google.com/forum/#!forum/play-framework) to ask question.

**Comment by graingert** [comment]
@cchantep this is not a question. It's an issue. Please remove the deprecation notice on this feature or update it to show what the new code should be

**Comment by marcospereira** [comment]
Hey,

The relevant code was moved to play-json repository and that repository is now the best place to have this discussion. See:

https://github.com/playframework/play-json/blob/48ced14066dc4f400adecf998433d7835c9318d5/play-json/src/main/scala/play/api/libs/json/JsResult.scala#L44-L57

So, lets keep this issue closed and further discussion could happen there. My opinion here is that we can make the method public. Since this is a pretty simple change, maybe a more productive approach is to submit a pull request to play-json (please, consider adding tests).

What do you think?
