### ISSUE TITLE
Using Mockito with Akka Actors

### ISSUE THREAD

**Issue by noru** [playframework/playframework#5539]
Hi,

I'm using mockito & specs2 to mock a service in my project, to verify if a method is called as wishes, just like this: 

`there were 1.times(mockObj).someMethod(someParameters)`

The problem comes out when using actor system. The target method was called by an actor which is not the same context of the test. So I got:

> The mock was not called as expected:
Wanted but not invoked:
 mock.method();
 -> at [Test context]
 However, there were other interactions with this mock:
-> at [Actor context]

Any idea to get pass this?

**Comment by marcospereira** [comment]
Hi, @noru, 

Please, you the [mailing list](https://groups.google.com/forum/#!forum/play-framework) to discuss doubts about how to use Playframework. The issue tracker here is intended to be used just to bugs and new features.

**Comment by noru** [comment]
Sorry.
