### ISSUE TITLE
Update outdated comment which mentions plugins and Global

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#5540]
Stumpled over an comment which will be outdated with Play 2.5 and thought I write it down.

Plugins and `Global.onStart` are deprecated so this comment should be updated:
https://github.com/playframework/playframework/blob/2.5.0-M2/framework/src/play-json/src/main/java/play/libs/Json.java#L163

**Comment by marcospereira** [comment]
I think the best idea is to deprecate `play.api.libs.Json`/`play.libs.Json` and provide Guice modules, just as suggested for Crypto classes (see #5186).

**Comment by wsargent** [comment]
Making a JSON module is tough, because there are binary dependencies on JSON in forms and in other places which are Play core still.  It's probably better done when moving to json4s as an intermediate API...
