### ISSUE TITLE
Temporary files are not deleted if TemporaryFile objects are not garbage collected

### ISSUE THREAD

**Issue by chunyang** [playframework/playframework#5545]
Temporary files are not deleted from disk unless the corresponding TemporaryFile objects are garbage collected. When garbage collection is not run in a timely manner, the files accumulate on disk and can lead to a denial of service.

The problem is exacerbated for requests that exceed `maxDiskBuffer` as handles to the temporary files are never passed to client code, so the client does not have an opportunity to delete the files.

**Comment by richdougherty** [comment]
I agree this is a problem, see my comment from [here](https://github.com/playframework/playframework/issues/4707#issuecomment-113194091):

> …I don't really like the way the delete happens in a finalize method. I'd like us to have a better way of cleaning up resources when a request finishes. Maybe each request could have an object where we could add "request finished" hooks.

**Comment by wsargent** [comment]
Possibly a dup of https://github.com/playframework/playframework/issues/5545

**Comment by mkurz** [comment]
+1

**Comment by mkurz** [comment]
Related: #4707, #3913 and #4762
Also [this comment](https://github.com/playframework/playframework/issues/4707#issuecomment-113302421):
> I'd rather the user explicitly does something if they want to keep it around after the request is complete, e.g. some sort of `acquire/release` operation, or maybe moving the file elsewhere.

As discussed in one of the above issues I am assigning the Play 3 milestone.

**Comment by wsargent** [comment]
This can be handled by enabling the TemporaryFileReaper in 2.6.x: https://www.playframework.com/documentation/2.6.x/ScalaFileUpload#Cleaning-up-temporary-files
