### ISSUE TITLE
Deprecate FakeApplication

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5549]
FakeApplication just delegates to GuiceApplicationBuilder.

**Comment by jroper** [comment]
What would `GuiceApplicationBuilder.fakeApplication()` do that a regular Guice application builder doesn't do?

**Comment by gmethvin** [comment]
For some reason I thought it was setting defaults that the `GuiceApplicationBuilder` doesn't have, but now that I look at it in more depth, it's pretty much setting the same defaults again if you start with no arguments.

**Comment by gmethvin** [comment]
Though it might be useful to add a helper for binding a fake router.
