### ISSUE TITLE
Java APIs for filters

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5551]
Related to #4708. `CSRFFilter`, `GzipFilter`, et al. need an easy way to extend in Java.

**Comment by mkurz** [comment]
Now that #5553 got merged it would be nice to update [this documentation](https://www.playframework.com/documentation/2.5.x/GzipEncoding#Controlling-which-responses-are-gzipped) to also contain a Java example.

**Comment by gmethvin** [comment]
I think we can provide a cleaner API for Java specific to the GzipFilter though.

**Comment by mkurz** [comment]
OK :smile:
