### ISSUE TITLE
Dev server starts even when port in use

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#5568]
If you start a dev server while port 9000 is already in use then the server will start but not work properly. The server should *not* start, it should report that the port is in use and abort. I think this is a regression from behaviour in Play 2.4.

Here's the output from running the `play-java` template on master. Notice it says that it's listening on port `null`…
```
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on null

(Server started, use Ctrl+D to stop and go back to the console...)
```

**Comment by mkurz** [comment]
I experience the same bug.
