### ISSUE TITLE
[Play 2.4.x] -mem argument for dist startup script seems to be ignored

### ISSUE THREAD

**Issue by keithblaha** [playframework/playframework#5579]
After running dist and unzipping it on my server, I usually start the app by doing something like this:

`./bin/$PROJECT -mem 2048 -J-server -Dhttp.port=$PORT -Dconfig.resource=production.conf -Dlogger.resource=logback-prod.xml`

However, I see this message printed:
`!! WARNING !! -mem option is ignored. Please use -J-Xmx and -J-Xms`

The documentation says that either should work: https://www.playframework.com/documentation/2.4.x/ProductionConfiguration#JVM-configuration

Is the -mem option no longer supported? If so, we should update the documentation to reflect that (happy to do so, but want to confirm)

**Comment by Skamander** [comment]
This seems to be ignored since 2.4.x: https://github.com/playframework/playframework/pull/5100 for 2.5.x: the documentation is already fixed: https://www.playframework.com/documentation/2.5.x/ProductionConfiguration#JVM-configuration but it seems 2.4.x was forgotten?

**Comment by keithblaha** [comment]
Ah- thank you, I didn't see that while searching for more information about -mem. Thank you for the info. I've submitted a PR to fix the documentation for 2.4.x
