### ISSUE TITLE
Idea (Eclipse) and Activator: difference in Form validation

### ISSUE THREAD

**Issue by pchayka** [playframework/playframework#5585]
Idea and Eclipse have support for play! and I had issue with form validation using validate() from bindRequest().

```
public static class Register extends Misc.Form {
        @Override
        public String validate() throws SQLException {
            if(email == null)
                return Messages.get("flash.secure.empty-login");
            return null;
        }
    }
```
This piece of code returns email = NULL when using Idea or web-gui compilation and run
and when I use

activator.bat project ~run

email is read fine.

The issue is described here too: http://stackoverflow.com/questions/25365707/issue-with-bindfromrequest-in-play-framework-2-3

**Comment by cchantep** [comment]
Hi, please use SO or the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask question. This tracker is for issue confirmed for Play itself. Best regards.
