### ISSUE TITLE
[Play 2.4.6] Why play framework 2.4 is so slow when using @routes.Assets.versioned in twirl?

### ISSUE THREAD

**Issue by zarinfam** [playframework/playframework#5588]
I have a controller and two scala template file that generated by default using activator new (main.scala.html and index.scala.html), when i render a index.scala.html twirl template and return it in my action. the play performance decrease about 5 time (15000 Requests per second in apache benchmark). but when i return json in this action play performance increase about 5 time  (79000 Requests per second in apache benchmark). I have a very simple twirl template:
I find that when i use @routes.Assets.versioned instead of @routes.Assets.at to address assets this problem occurs.

**Comment by cchantep** [comment]
Hi, please use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask question or discuss possible enhancements. This tracker is for confirmed issue or actionable ticket. Best regards.
