### ISSUE TITLE
Filters can't override Request object?

### ISSUE THREAD

**Issue by brikis98** [playframework/playframework#5601]
I'm trying to create a Filter that will replace the `Request` object my Action sees. 

The Filter:

```scala
object TmpFilter extends Filter {
  override def apply(next: (RequestHeader) => Future[Result])(rh: RequestHeader): Future[Result] = {
    val action = Action.async { req =>
      val newRequest = TmpRequest("foo", req)
      println(s"Replacing request with class ${newRequest.getClass}")
      next(newRequest)
    }
    action(rh).run
  }
}

case class TmpRequest[A](foo: String, req: Request[A]) extends WrappedRequest[A](req)
```

The Action: 

```scala
def tmp = Action { req =>
  println(s"Action sees request with class ${req.getClass}")
  Ok("OK")
}
```

The log output I get:

```
Replacing request with class class filters.TmpRequest
Action sees request with class play.api.mvc.Request$$anon$2
```

I was expecting the Action to see class `filters.TmpRequest`, but it seems to be getting swapped out somewhere along the way. FWIW, if I add another filter in the chain, it *does* see `TmpRequest`, but an Action in a Controller does not.

Is there any way to make this work?

**Comment by gmethvin** [comment]
Action's default `apply` creates a new request when it parses the body. Pretty much anything in the filter chain can replace the original request as well. Is there a reason you need a custom type?

**Comment by brikis98** [comment]
I'm doing authentication in the filter chain. The alternative is an `AuthenticatedAction`, but I was trying to avoid the case where someone, out of force of habit, uses a plain old `Action`, and we end up with an unauthenticated endpoint. Therefore, the idea was to check auth and fetch the profile in a filter and add it to the `Request` object. 

So a more accurate representation of my code is:

```scala
object AuthFilter extends Filter {
  override def apply(next: (RequestHeader) => Future[Result])(rh: RequestHeader): Future[Result] = {
    val action = Action.async { req =>
      if (isAuthenticated(req)) {
        val profile = fetchProfile(req)
        val authRequest = AuthRequest(profile, req)
        next(authRequest)
      } else {
        Results.NotAuthorized
      }
    }
    action(rh).run
  }
}

case class AuthRequest[A](profile: Profile, req: Request[A]) extends WrappedRequest[A](req)
```

I then created an `AuthenticatedAction` class that just looks up if the current `Request` object and if it's already an `AuthRequest` it casts it accordingly, and if it isn't, throws an error, so the following controller works: 

```scala
// All requests to this controller are authenticated
class MyController extends Controller {
  // If you need the profile, you use AuthenticatedAction
  def withProfile = AuthenticatedAction { request =>
    val profile = request.profile
    // ...
  }

  // If you don't need the profile, you can use Action, but this action is still authenticated by the filter!
  def withoutProfile = Action {
    // ...
  }
}
```
I guess I'll have to change my approach to leave the `isAuthenticated` check in the `AuthFilter` but move the `fetchProfile` into `AuthenticatedAction` itself. It makes the code a bit more cumbersome, but I guess it's not a blocker.

**Comment by gmethvin** [comment]
Well, it might be possible to add tags to your request for your profile. Your AuthenticatedAction would then need to check for those tags and create a profile. That seems like a hack though since you have to convert your profile to a string representation and back.

This is a design discussion which would be better done on the mailing list than github issues though.
