### ISSUE TITLE
[doc] [2.4.x] Need to document that compile-time dependency injection requires you to call Logger.configure

### ISSUE THREAD

**Issue by brikis98** [playframework/playframework#5615]
The Play [logging configuration docs](https://www.playframework.com/documentation/2.4.x/SettingsLogger) recommend using `${application.home}` to define the path for the log file. This works in dev when running from SBT. However, if you use the `dist` command to package the app for prod and run it using the script generated in the `bin` directory, you find that the value gets set to `application.home_IS_UNDEFINED`. 

I'm using [compile-time dependency injection](https://www.playframework.com/documentation/2.4.x/ScalaCompileTimeDependencyInjection) and calling `Logger.configure(context.environment)`, something that isn't documented, but without it, logback doesn't work at all (I found that hint originally [here](http://loicdescotte.github.io/posts/play24-compile-time-di/)). Perhaps there is some other log config that I'm still missing?

**Comment by brikis98** [comment]
Ah, I take that back. I was looking at an old log entry. Adding the `Logger.configure` call fixes the `application.home` issue. But it really needs to be documented somewhere in the compile-time dependency injection docs, so I'll update the title of this issue.

**Comment by wsargent** [comment]
This may also be ameliorated by https://github.com/playframework/playframework/pull/5555

**Comment by brikis98** [comment]
I think if you don't call `Logger.configure`, Play doesn't set up logback correctly at all.

**Comment by wsargent** [comment]
It's better in 2.5.x now that there's LoggerConfigurator:

* https://www.playframework.com/documentation/2.5.x/SettingsLogger#Using-a-Custom-Logging-Framework
* https://www.playframework.com/documentation/2.5.x/ScalaCompileTimeDependencyInjection#Application-entry-point

**Comment by brikis98** [comment]
Ah, good to see that stuff in the 2.5.x docs. Up to you if it's worth updating the 2.4.x docs at this point.

**Comment by nafg** [comment]
The 2.5 docs could still afford to be a LOT more explicit, from what I can tell. Now that I know about this I "see" it in the docs, but if I didn't know, and was just trying to follow the docs, it would not be obvious at all.

**Comment by wsargent** [comment]
@nafg what would you suggest?

**Comment by soren-schmidt** [comment]
For all those who are still wondering what exactly they have to do, here is an example:
class MyApplicationLoader extends ApplicationLoader {
  def load(context: ApplicationLoader.Context) = {
    LoggerConfigurator(context.environment.classLoader).foreach {
      _.configure(context.environment)
    }
    new MyComponents(context).application
  }
}
Copied from:
https://github.com/playframework/play-scala-compile-di-with-tests/blob/master/app/MyApplicationLoader.scala

**Comment by wsargent** [comment]
2.6.x docs even more explicit, 2.4.x is deprecated, lots of code available.
