### ISSUE TITLE
Model from subproject is not mapped

### ISSUE THREAD

**Issue by victorjussiani** [playframework/playframework#5616]
I'm trying to use a model mapped in another subproject, but it is throwing an org.hibernate.hql.internal.ast.QuerySyntaxException: Post is not mapped.

My projects are configured like this:

```
lazy val commonSettings = Seq(
	PlayKeys.externalizeResources := false,
)

// Sub projects
lazy val website = (project in file("modules/frontend-website")).enablePlugins(PlayScala, SbtWeb).settings(commonSettings: _*).settings(name := "frontend-website").dependsOn(commom)

lazy val commom = (project in file("modules/frontend-commom")).enablePlugins(PlayScala).settings(commonSettings: _*).settings(name := "frontend-commom")

// Root project
lazy val root = (project in file(".")).enablePlugins(PlayJava).aggregate(website, commom).dependsOn(website).settings(commonSettings: _*)

PlayKeys.externalizeResources := false

```

My model is on subproject Commom and I want to use it in Website, can someone help me to solve this error.

**Comment by marcospereira** [comment]
@victorjussiani, please use the [mailing list](https://groups.google.com/forum/#!forum/play-framework) to get help about how to use the framework. If we confirm that there is a bug, we can reopen this issue later.
