### ISSUE TITLE
request.secure unusable in multiple environments

### ISSUE THREAD

**Issue by urcadox** [playframework/playframework#5621]
Hello,

Since [this update](https://github.com/playframework/playframework/commit/48f6772c857a851617c7170a74b8fa630ca4) (I guess), request.secure is returning false in cases where it should return true.

This behavior was tested on [Clever Cloud](https://www.clever-cloud.com/), but my Google searches tell me it also happens on Heroku and probably other environments.

Anyway, with this configuration:

```
play.http.forwarded.version="x-forwarded"
play.http.forwarded.trustedProxies=["0.0.0.0","::"]
```

If the application receives these headers:

```
X-Forwarded-Proto: https
X-Forwarded-Protocol: https
X-Forwarded-For: <Client IP>
```

Then, `request.secure` equals false.

I'm a developer at Clever Cloud, so if we can do anything on our side to fix this, please tell me. :)

**Comment by wsargent** [comment]
Hi @urcadox -- can you put together a failing test in Play for this?

**Comment by wsargent** [comment]
Also, you're saying that `request.secure` equals false if both `X-Forwarded-Protocol` and `X-Forwarded-Proto` are defined, or all three of them?

**Comment by wsargent** [comment]
Also, `X-Forwarded-Protocol` doesn't seem to be a standard header: https://tools.ietf.org/html/rfc7239

**Comment by jroper** [comment]
Play uses CIDR notation for `trustedProxies`.  `0.0.0.0` and `::` will only match incoming requests with those exact IP addresses.  If you want to trust all IP addresses, you have to use `0.0.0.0/0` and `::/0`.

**Comment by jroper** [comment]
And the change that broke things here was fixing a bug where the incoming actual IP address wasn't checked to see if it was a trusted proxy.

**Comment by jroper** [comment]
I've submitted this PR to improve the documentation here, including adding documentation specifically about how to trust all proxies:

https://github.com/playframework/playframework/pull/5642

**Comment by urcadox** [comment]
@jroper Thanks :)

**Comment by jamesward** [comment]
It would also be nice to have something in the 2.4 migration guide about this since it was essentially a breaking change.
