### ISSUE TITLE
play.http.HttpFilters should use Java Filter API

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#5625]
`play.http.HttpFilters` currently returns an array of `play.api.mvc.EssentialFilter`. It should rather return an array of `play.mvc.EssentialFilter`.

**Comment by gmethvin** [comment]
And it would probably also make sense to have asJava/asScala on that too.

**Comment by gmethvin** [comment]
Actually after I started writing the fix to this I realized we'll need to adapt the built-in filters to the Java interface. So we'd need to create Java versions of CSRFFilter, GzipFilter, et. al., or have another API for making that return the Java filter array.
