### ISSUE TITLE
Compilation of reverse routes inconsistent

### ISSUE THREAD

**Issue by irundaia** [playframework/playframework#5633]
I've been trying to work with reverse routing. However, adding and/or removing white space can break compilation with a message stating that the action cannot be found in the reverse controller. 

I've tested this behaviour with play versions on OS X 11.3:
- 2.3.10
- 2.4.4
- 2.4.6

An example repo where the reverse routes won't work can be found [here](https://github.com/irundaia/play-reverse-routing-error).

**Comment by wsargent** [comment]
Works fine for me.

http://localhost:9000/moop -> lkfnekfn

**Comment by irundaia** [comment]
It seems I might have oversimplified things a bit. I've committed a version which fails consistently. I think the issue occurs because the target/main/controllers/ReverseRoutes.scala is overwritten with the last routes file thats been compiled.

**Comment by wsargent** [comment]
Error is 

```
[root] $ compile
[info] Compiling 8 Scala sources and 1 Java source to /Users/wsargent/work/play-reverse-routing-error/target/scala-2.11/classes...
[error] /Users/wsargent/work/play-reverse-routing-error/app/controllers/Application.scala:8: value moop is not a member of controllers.ReverseApplication
[error]     Redirect(routes.Application.moop())
[error]                                 ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 4 s, completed Feb 12, 2016 2:27:37 PM
[root] $
```

**Comment by wsargent** [comment]
I think you need to namespace your controller if you're doing that:

https://www.playframework.com/documentation/2.4.x/SBTSubProjects#Assets-and-controller-classes-should-be-all-defined-in-the-controllers.admin-package

**Comment by irundaia** [comment]
This page explains what to do with multi-module play projects. I was looking at a single play application with the routes split over multiple files. Even the controllers can be shared between the different `*.routes` files. 

But if I understand correctly, we're currently misusing the feature to split the routes.
