### ISSUE TITLE
Provide useful error message when ColoredLevel cannot be found

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#5639]
We should provide a useful message when `play.api.Logger$ColoredLevel` cannot be found.

My suggestion is that rather than letting logback not find this class, we provide the class, and although of course the class can't implement the Logback interface Logback expects it to, what we can do is cause it to fail to load by adding a static initialiser that throws an exception, and this exception can have a meaningful error message in it saying how to switch to the new logger.

The class will have to be implemented in Java, since it's impossible in Scala to put a static initializer on a class.

**Comment by marcospereira** [comment]
Fixed by #5641.
