### ISSUE TITLE
[2.4.6] Log exceptions thrown in Global.onStart(...) to File using logback

### ISSUE THREAD

**Issue by recastrodiaz** [playframework/playframework#5658]
Exceptions in onStart are sent to console using System.err (See https://github.com/playframework/playframework/blob/master/framework/src/play-server/src/main/scala/play/core/server/ServerProcess.scala#L48) and there doesn't seem to be an easy way to redirect this error stream to a log file using logback.

``` LOG
Oops, cannot start the server.
@6p22o1b6c: Cannot load module
[...]
```

Is there any reason the code is using System.err instead of logback to log the stacktrackes? Would it be possible to use logback instead in...?  .i.e logger.error("Oops, cannot start the server.", throwable)

``` JAVA
def exit(message: String, cause: Option[Throwable] = None, returnCode: Int = -1): Nothing = {
    System.err.println(message)
    cause.foreach(_.printStackTrace())
    System.exit(returnCode)
    // Code never reached, but throw an exception to give a type of Nothing
    throw new Exception("SystemProcess.exit called")
  }
```

We've seen these errors whenever we get some Guice Module wrong, like missing a dependency etc. This is hard to catch as DI modules are usually different between Prod and Dev, and in prod there is no information in the log file.

See previous issue and how to replicate it: https://github.com/playframework/playframework/issues/2118#issuecomment-178512127

If we can use logback for this, I'm happy to create a PR.
Let me know what you think,

Thanks,
Rodrigo

**Comment by wsargent** [comment]
What version of Play is this happening in?

**Comment by recastrodiaz** [comment]
We're using playframework version 2.4.6, but we've been experiencing this issue at least since version 2.3.X.

Additionally, we're running on Ubuntu 12.04 using an upstart script created by Puppet. See: https://github.com/recastrodiaz/puppet-play/blob/master/templates/playframework.erb#L29

```SH
exec start-stop-daemon --pidfile <%= @path %>/target/universal/stage/RUNNING_PID --chdir <%= @path %> --chuid $USER:$GROUP --exec <%= @path %>/target/universal/stage/bin/<%= @projectName %> --background --start -- <%= @javaOptions %>
```

Using the upstart script above, the console output gets lost in the void.
The start-stop-daemon line is based on the docs: https://www.playframework.com/documentation/2.4.x/Production#Running-a-production-server-in-place

As a workaround, we've tried redirecting the console output to a log file based on a stackoverflow answer, but the syntax doesn't seem to be quite correct just yet (Play doesn't start or upstart launches too many instances): http://stackoverflow.com/questions/8251933/how-can-i-log-the-stdout-of-a-process-started-by-start-stop-daemon 


```SH
exec start-stop-daemon --pidfile <%= @path %>/target/universal/stage/RUNNING_PID --chdir <%= @path %> --chuid $USER:$GROUP --startas /bin/bash -- -c "<%= @path %>/target/universal/stage/bin/<%= @projectName %> --background --start -- <%= @javaOptions %> >> /var/log/some.log 2>&1"
```

**Comment by jroper** [comment]
I'm not 100% sure why it uses `System.err`, but I do wonder what would happen if there was a problem in trying to initialise logback, and an attempt was made here to log it using logback.

**Comment by wsargent** [comment]
2.4.x is EOL
