### ISSUE TITLE
Allow signing the Flash cookie

### ISSUE THREAD

**Issue by jxtps** [playframework/playframework#5661]
I'd like to be able to put stuff in the flash cookie that I don't want the user to be able to tamper with. There's currently no `signed` option for the Flash. Could we add one? 

The [FlashConfiguration](https://github.com/playframework/playframework/blob/4a15b9d2d6926f3f9664f002abbf4125ffed81c9/framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala#L76) would need an added `signed: Boolean` member. 

`override val isSigned = config.signed` would need to be added to the [Flash object](https://github.com/playframework/playframework/blob/5c923ff454845914a7a7c2609ce2f737de95f3d3/framework/src/play/src/main/scala/play/api/mvc/Http.scala#L758). 

`signed = config.get[Boolean]("play.http.flash.signed")` would need to be added to the [parsing section](https://github.com/playframework/playframework/blob/4a15b9d2d6926f3f9664f002abbf4125ffed81c9/framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala#L137) of `HttpConfiguration`. 

And a default value of `signed = false` would need to be added to the [flash configuration section](https://github.com/mkurz/playframework/blob/master/framework/src/play/src/main/resources/reference.conf#L109) in [reference.conf](https://github.com/mkurz/playframework/blob/master/framework/src/play/src/main/resources/reference.conf).

That should be it?

**Comment by wsargent** [comment]
The Flash cookie's lifetime should be for exactly one redirect, and should be discarded after that.  There shouldn't be a window for the user to be able to tamper with it, and it shouldn't be used as a persistent session state cookie -- there's PLAY_SESSION for that.

**Comment by jxtps** [comment]
Absolutely, but I need to store some transient but sensitive state (ecommerce tracking data, links, email addresses). Arguably the user could only really hurt themselves if they were to tamper with most of it, so sure, you could say it's being overly paranoid, but on the other hand: why *not* sign it?

**Comment by wsargent** [comment]
That's not what the Flash cookie is for.  If you need to store information that you don't want to be in the Play session, then you should use a CookieBaker to create a signed cookie with its own lifecycle.

**Comment by jxtps** [comment]
Ok, fair enough. 

Separately, shouldn't the flash cookie just be signed? (i.e. putting `override val isSigned = true` into the Flash object)

Any cookie can be set by a (malicious) user at any time to any value, so it would seem to fall under the "Always Validate User Input" / "The Gun Is Always Loaded" type categories? 

What if a Play user starts doing something analogous to [render a dynamic partial in Rails](http://thepugautomatic.com/2012/08/the-rails-flash/)? Looks like a potential "fetch any file" type security hole unless the cookie is signed? 

People do crazy things, web security can be tricky, and shouldn't the Play default behavior be as-safe-as-possible?

**Comment by wsargent** [comment]
A Flash cookie renders a message in a Twirl template.  The contents of that cookie will be escaped, unless the application explicitly calls `Html(request.flash)` on it, at which point you can have XSS -- so no matter what data is in the Flash cookie, it should not turn into HTML.  You can sign it, but it still doesn't prevent the application from taking user input, sticking it into the Flash, and then producing a reflected XSS attack.

Ultimately, any security you put into signing the Flash cookie would led to supposition about its security -- the safest thing to do is to make it clear that a Flash cookie's value contains text, only text, and nothing but text.
