### ISSUE TITLE
Extract iteratees library into its own repository

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#5677]
The Play iteratees library should be extracted into its own repository.  As part of this work, the following should be done:

* Delete deprecated iteratees methods in play-json, and remove dependence on iteratees library
* Copy iteratees trampoline execution context into main Play code base - eventually we will remove the dependency on the iteratees library, and this execution context is heavily used throughout Play, we don't want to keep the dependency around for the sake of this context.
* Move iteratees reactive streams implementation into the extracted iteratees library (probably best as a separate artifact, since at some point another artifact will need to be introduced for JDK9 reactive streams support), and deprecate play.api.libs.streams.Streams methods for iteratees to reactive streams conversions.

**Comment by wsargent** [comment]
See https://github.com/playframework/play-iteratees

**Comment by wsargent** [comment]
Resolved by https://github.com/playframework/playframework/pull/5955
