### ISSUE TITLE
Refactor play.data.Form and related classes to use DI

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5678]
I suggest we move the static `Form.form` and other methods to something like a `FormBuilder` that is injected into a class. Then `Form` should accept a `MessagesApi` and any other dependencies (which are currently global).

**Comment by mkurz** [comment]
Just additional information: Also see [this conversation](https://github.com/playframework/playframework/pull/5671#issuecomment-185514493).

**Comment by mkurz** [comment]
See #5726 for a proposal of how to implement this.
