### ISSUE TITLE
CORS filter not working on cross-protocol on same domain

### ISSUE THREAD

**Issue by marklieberman** [playframework/playframework#5687]
I'm having a small problem with the CORSFilter and I think I know why.

I am on __http__://example.com and want to use XHR to invoke some REST endpoint on __https__://example.com. Since the protocol changes (even though the host does not), this is a cross-domain request and CORS is required.

Now, I'm not a Scala guy but it looks like https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala#L51 is only comparing the host/post and not the scheme. So, my request fails because the CORS headers are not applied to the response.

**Comment by maxkremer** [comment]
is there any way this can be back-ported to to 2.4.x?

**Comment by gmethvin** [comment]
@maxkremer See #5723

**Comment by maxkremer** [comment]
much thanks @gmethvin  !!!

**Comment by elmalto** [comment]
@gmethvin is there an easy way to disable this feature? I have play running behind haproxy with ssl termination. The browser sends a request from https://mydomain.com -> https://mydomain.com/restpoint, but haproxy forwards it to play as http and I get CORS errors
