### ISSUE TITLE
Misleading ScalaRouting Guide

### ISSUE THREAD

**Issue by cheeseng** [playframework/playframework#5688]
As of 19 Feb 2016, the Dependency Injection section of the following page: 

https://www.playframework.com/documentation/2.5.x/ScalaRouting

mentioned that: 

Play supports generating two types of routers, one is a dependency injected router, the other is a static router. The default is the static router, but if you created a new Play application using the Play seed Activator templates, your project will include the following configuration in build.sbt telling it to use the injected router:

```
routesGenerator := InjectedRoutesGenerator
```

This is no longer correct as InjectedRoutesGenerator is not the default.

**Comment by cheeseng** [comment]
It was discussed earlier here: 

https://github.com/playframework/playframework/pull/5680

**Comment by gmethvin** [comment]
Fixed by #5682
