### ISSUE TITLE
Play.current() dependency on java JPA.

### ISSUE THREAD

**Issue by mlight3** [playframework/playframework#5696]
Need to remove dependency of Play.current() in play.db.jpa.JPA class.

```
public static JPAApi jpaApi() {
    return Play.current().injector().instanceOf(JPAApi.class);
}
```

When I use JPA in OnStartModule for checking data from database, 
it shows "there is no started application" exception that occurred from Play.current().

**Comment by gmethvin** [comment]
@mlight3 Yes, that method and all the static methods using it should be deprecated.

**Comment by mlight3** [comment]
@gmethvin How can I use JPAApi class instead of JPA static method? All 'withTransaction' method is deprecated.

**Comment by gmethvin** [comment]
@mlight3 You should use [dependency injection](https://www.playframework.com/documentation/2.5.x/JavaDependencyInjection) inject the `JPAApi` into your component
