### ISSUE TITLE
2.5.0-RC1 BodyParser maxLength behaviour

### ISSUE THREAD

**Issue by mikesname** [playframework/playframework#5704]
The `maxLength` body parser appears to not work at all in 2.5.0-RC1 if the parser it's wrapping has any length constraint, always returning a 413 result rather than allowing the user to handle MaxSizeExceeded themselves. 

The cause appears to be that when the MaxLengthLimitAttained exception is thrown it's intercepted by the recoverWith block of `enforceMaxLength` ([here](https://github.com/playframework/playframework/blob/56cb2066c2761930bb2b0de5b497851a1e106bc6/framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala#L725)), _even if it's a different limit being enforced_ (i.e. one lower than `enforceMaxLength` itself expected).

One easy solution to _partially_ fix the problem is to check if the limit being enforced is the same as expected (see [this patch](https://github.com/playframework/playframework/compare/master...mikesname:max_length_fix?expand=1)). However, if the length limit is __the same__ as that of the underlying body parser the latter will "win", returning 413 instead of the expected MaxSizeExceeded, which is a change in behaviour from 2.4.x. 

Another potential solution I considered was intercepting a 413 result from the underlying parser inside `maxLength` itself, but as the result does not carry the info about the length limit being applied this gets lost.

I did notice that the `maxLength` body parser was [removed](https://github.com/playframework/playframework/pull/5394) from the Java API, so perhaps the Scala one has just been forgotten.

**Comment by jroper** [comment]
Ok, that makes sense - I wasn't too keen on using exceptions to carry the max length status anyway. I think as a solution we should rewrite both the `enforceMaxLength` function and the `maxLength` body parser to use a `Sink` that communicates the length exceeded condition directly to the materialized value.
