### ISSUE TITLE
Dev server doesn't fail to start when port already bound

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#5709]
In Play 2.4.x and earlier, when running `sbt run`, if port 9000 is already bound, an error is thrown.  In 2.5.0-RC1, no error is thrown, instead you just see this:

```
[play-java] $ run

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on null

(Server started, use Ctrl+D to stop and go back to the console...)
```

It should fail if either the http or https (if configured) ports fail to bind.  While we're at it, if possible, we should make a nice error message, rather than an exception (hint, sbt has an `AlreadyHandledException` that suppresses logging of a tasks thrown exception, we can log a pretty error and throw a subclass of that).

**Comment by mkurz** [comment]
That's a duplicate fo #5568
