### ISSUE TITLE
Json.toJson order randomized if my map too big

### ISSUE THREAD

**Issue by tg44** [playframework/playframework#5711]
Play Version (2.4.x)
API (Scala possibly Both)

### Expected Behavior

So when I make a map to json I want the orders of the paramaters the same as I gave them.
I know the specification told us this can be shuffled, but its really inconsistent, and hard to test because this behaviour. (+ I doesn't really trust my clients json parser implementations and it would be nice if I can reproduce the legacy json to them without modification)

### Actual Behavior

When I parse a string to json and make it string again and when I make a (5+ elements) LinkedMap to a json and make it to string the output is not even close. 

### Reproducible Test Case
First test pass always, second fails always.
```
    "toJson" should {
		"keep the insertion order on LinkedMap" in {
			val test = Json.toJson(
				ListMap(
					"name" -> "foo",
					"zip" -> "foo",
					"city" -> "foo"
				))
			val req = """{"name":"foo","zip": "foo","city": "foo"}"""
			test.toString must beEqualTo(Json.parse(req).toString).ignoreSpace
		}
		"keep insertion order on big Linked map" in {
			val test = Json.toJson(
				ListMap(
					"name" -> "a",	"zip" -> "foo",	"city" -> "foo",
					"address" -> "foo",	"phone" -> "foo",	"latitude" -> "foo",
					"longitude" -> "foo",	"hny" -> "foo",	"hz" -> "foo",
					"hek" -> "foo",	"hev" -> "foo",	"kny" -> "foo",
					"kz" -> "foo",	"kek" -> "foo",	"kev" -> "foo",
					"szeny" -> "foo",	"szez" -> "foo",	"szeek" -> "foo",
					"szeev" -> "foo",	"csny" -> "foo",	"csz" -> "foo",
					"csek" -> "foo",	"csev" -> "foo",	"pny" -> "foo",
					"pz" -> "foo",	"pek" -> "foo",	"pev" -> "foo",
					"szony" -> "foo",	"szoz" -> "foo",	"szoek" -> "foo",
					"szoev" -> "foo",	"vny" -> "foo",	"vz" -> "foo",
					"vek" -> "foo",	"vev" -> "foo"
				)
			)
			val req = """{"name": "a", "zip": "foo", "city": "foo", "address": "foo", "phone": "foo", "latitude": "foo", "longitude": "foo", "hny": "foo", "hz": "foo", "hek": "foo", "hev": "foo", "kny": "foo", "kz": "foo", "kek": "foo", "kev": "foo", "szeny": "foo", "szez": "foo", "szeek": "foo", "szeev": "foo", "csny": "foo", "csz": "foo", "csek": "foo", "csev": "foo", "pny": "foo", "pz": "foo", "pek": "foo", "pev": "foo", "szony": "foo", "szoz": "foo", "szoek": "foo", "szoev": "foo", "vny": "foo", "vz": "foo", "vek": "foo", "vev": "foo"}"""
			test.toString must beEqualTo(Json.parse(req).toString).ignoreSpace
		}
     }
```

**Comment by gmethvin** [comment]
Hi @tg44,

I agree this should probably be the default behavior. You can work around the issue by defining this implicit in scope and importing it:
```scala
implicit def mapWrites[V](implicit fmtv: Writes[V]): OWrites[collection.immutable.Map[String, V]] = OWrites[collection.immutable.Map[String, V]] { ts =>
  JsObject(ts.mapValues(toJson(_)(fmtv)).toSeq)
}
```
The current implementation of `MapWrites` calls `map` on the `Map` passed to the serializer. That method only returns a regular map when called on `ListMap`, thus causing it to lose its ordering.

It's also worth noting that if you call `Json.obj("foo" -> "bar", "baz" -> "quux")` the order should be preserved in the JSON output.
