### ISSUE TITLE
Update HttpRequestHandler documentation for Java users

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5715]
We probably clarify that Java users should just extend `DefaultHttpRequestHandler` instead of `JavaCompatibleHttpRequestHandler` (which uses Scala types). Also some more sophisticated examples of extending the default `HttpRequestHandler` in Java would be nice.

Also perhaps we should reimplement the Scala `DefaultHttpRequestHandler` completely in Java to give users access to methods like `routeRequest` they can override. It would make it much easier to customize behavior.

**Comment by richdougherty** [comment]
Closing because created an issue that incorporates this idea: #8278.
