### ISSUE TITLE
Re-factor guice injected spring data classes between sbt sub-projects

### ISSUE THREAD

**Issue by ITler** [playframework/playframework#5749]
Hello guys,

would anybody be so kind and help me out with [this issue](http://stackoverflow.com/questions/35505016/share-guice-injected-spring-data-classes-between-sbt-sub-projects-in-playframewo) already described on stackoverflow, please? I assume this is a newbie question, so I guess it is easy for you to answer it.

Thank you
ITler

**Comment by ITler** [comment]
I've got an inspiration. Too easy

**Comment by mkurz** [comment]
Please ask on the mailing list next time.
