### ISSUE TITLE
[doc] Update Scalatest references

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#5759]
### Play Version (2.5.x / etc)

2.5.0
## Actual Behavior

The documentation for Scalatest / Play uses outdated version numbers.

https://www.playframework.com/documentation/2.5.x/ScalaTestingWithScalaTest#Using-ScalaTest-+-Play

This is actually a call out to scaltestplus-play so have filed this as https://github.com/playframework/scalatestplus-play/issues/44.

**Comment by marcospereira** [comment]
https://github.com/playframework/scalatestplus-play/pull/88 and https://github.com/playframework/scalatestplus-play/pull/89 should be enough to close this.

**Comment by marcospereira** [comment]
I'm closing this since and playframework/scalatestplus-play#88 and playframework/scalatestplus-play#89 were already merged with updates to documentation.
