### ISSUE TITLE
There is no CacheComponents trait for compile time DI

### ISSUE THREAD

**Issue by povder** [playframework/playframework#5761]
- Play Version 2.5.0-RC2
- API: Scala
- Module: cache

In play/api/cache/Cache.scala there is EhCacheComponents trait that is supposed to provide cache components for compile time DI. However, there is no general CacheComponents trait that can be used to define a dependency on cache without requiring a concrete implementation (EH Cache). There should be a CacheComponents trait.

I'm creating this issue toghether with proposing a PR.

**Comment by gmethvin** [comment]
@povder We could do this for other components traits as well. `WSComponents` is one for sure.

**Comment by povder** [comment]
Closing as wontfix, see the discussion here: https://groups.google.com/forum/#!topic/play-framework-dev/87vSkU9Foz0/discussion
