### ISSUE TITLE
[Play 2.5 RC2] Play-Akka-http-Server request.uri has protocol + domain + port

### ISSUE THREAD

**Issue by schmitch** [playframework/playframework#5780]
### Are you looking for help?

Hello, I have a logging Handler which is something along these lines:

```scala

class LoggingFilter @Inject()(implicit val mat: Materializer, ec: ExecutionContext) extends Filter {

  val logger = Logger(this.getClass)

  def apply(nextFilter: RequestHeader => Future[Result])
           (requestHeader: RequestHeader): Future[Result] = {

    val startTime = System.currentTimeMillis

    nextFilter(requestHeader).map { result =>

      val endTime = System.currentTimeMillis
      val requestTime = endTime - startTime

      if (!requestHeader.uri.startsWith("/assets")) {
        logger.info(s"${requestHeader.method} ${requestHeader.uri} " +
          s"took ${requestTime}ms and returned ${result.header.status}")
      }

      result.withHeaders("Request-Time" -> requestTime.toString)
    }
  }

}
```

On Netty it will actually print GET /myurl took ...
On Play-Akka-Http it will actually print GET http://localhost:9090/myurl took ...

### Play Version (2.5.x / etc)

Play 2.5 RC2

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Use `uname -a` if on Linux.

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

schmitch@SHANGHAI:~$ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

**Comment by gmethvin** [comment]
@schmitch What is the actual url sent on the status line? My guess is that the concept of `Uri` used by akka-http doesn't represent the actual URI on the status line.

**Comment by schmitch** [comment]
What do you mean?
I meant that under Netty it will print:
> /url
and
Akka uses:
> http://localhost:9000/url

**Comment by gmethvin** [comment]
When the request is sent to the Play server it will have a status line that looks like:
```
GET /url
```
or perhaps
```
GET http://localhost:9000/url
```

What's the status line actually being sent? I'm just trying to figure out whether netty or akka-http has the correct one.

**Comment by schmitch** [comment]
Actually that was a browser request.
However inside ``play.api.mvc.RequestHeader`` the ``def uri`` has the following comment:
``
    /**
     * The complete request URI, containing both path and query string.
     * The URI is what was on the status line after the request method.
     * E.g. in "GET /foo/bar?q=s HTTP/1.1" the URI should be /foo/bar?q=s.
     * It could be absolute, some clients send absolute URLs, especially proxies.
     */
    def uri: String
``

So Netty is correct and I think the model conversion of akka-http assume's that Akka-Http's uri is without the domain, which isn't true.

**Comment by gmethvin** [comment]
@schmitch It looks like the Akka HTTP API doesn't have a direct way of doing it. However, as a workaround you can enable the setting `akka.http.server.raw-request-uri-header = true`, which will add a `Raw-Request-URI` header.

**Comment by schmitch** [comment]
@gmethvin Actually I just thought that we should change the ModelConversion of either Netty or Akka, it would be aweful if RequestHeader.uri() would be different based on the Server. The RFC of URI (https://tools.ietf.org/html/rfc3986) says that actually a URI could be with scheme and authority, however in Play until Akka-http it was always without it as seen in the Comment.

So I think we should either change:
https://github.com/playframework/playframework/blob/master/framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala#L61
or that:
https://github.com/playframework/playframework/blob/master/framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala#L75

**Comment by gmethvin** [comment]
Ideally we should be able to get the raw URL. So maybe it should be exposed in a better way in Akka HTTP so we can get access to it.

**Comment by benmccann** [comment]
Yeah I agree that as an end user I wouldn't want my code doing different things depending on the backend I'm using. That should be transparent
