### ISSUE TITLE
Better default content types for error pages

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5782]
It should be easy to have Play provide errors in other common formats like JSON and text. For example, if I'm building an API that only uses JSON, my error responses should all be JSON too.

**Comment by schmitch** [comment]
Duplicates: https://github.com/playframework/playframework/issues/3893

**Comment by richdougherty** [comment]
By the way #6171 captures the discussion about improving error handling generally.

**Comment by guizmaii** [comment]
Can we close this issue now ?

**Comment by gmethvin** [comment]
Yeah, let's close since it was fixed by #8299 and #8540.

**Comment by guizmaii** [comment]
Thanks for your help in this work @gmethvin ! :)
