### ISSUE TITLE
[2.5.0-RC2] Ok.sendFile for directories and non-existent files

### ISSUE THREAD

**Issue by avdv** [playframework/playframework#5788]
### Play Version (2.5.x / etc)

2.5.0-RC2

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

`Linux claudio-think 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux`

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
OpenJDK Runtime Environment (build 1.8.0_74-b02)
OpenJDK 64-Bit Server VM (build 25.74-b02, mixed mode)
```

### Expected Behavior

For `Ok.sendFile` if the given file is a directory I would expect a 500 response.

For `Ok.sendFile` if the given file does not exist, I would expect a 404 response (or even a 500).

### Actual Behavior

```
Ok.sendFile(new File(""), inline = true)
```

I get the following response:

```
HTTP/1.1 200 OK
Content-Disposition: attachment; filename=""
Content-Length: 0
Content-Type: application/octet-stream
Date: Tue, 01 Mar 2016 07:52:48 GMT
```

Note the filename is empty, which is interpreted as "the empty abstract pathname" and "may be used to access the current user directory". But, `new File("").isDirectory` is `false`, whereas `new File("").getAbsoluteFile.isDirectory` is `true`.

Furthermore,

```
Ok.sendFile(new File("."))
```

is worse because it returns an invalid response:

```
HTTP/1.1 200 OK
Content-Disposition: attachment; filename="."
Content-Length: 130
Content-Type: application/octet-stream
Date: Tue, 01 Mar 2016 08:01:50 GMT

curl: (18) transfer closed with 130 bytes remaining to read
```

For non-existent files, there's an empty response again:

```
HTTP/1.1 200 OK
Content-Disposition: attachment; filename="sdfasdfasdf"
Content-Length: 0
Content-Type: application/octet-stream
Date: Tue, 01 Mar 2016 08:05:58 GMT
```

Even if checking that a given File is not a directory and that it actually exists before calling sendFile, there's still always the chance for a race condition that the file is gone at the time the server tries to access it. So I think this should be handled when actually sending out the response.

**Comment by jroper** [comment]
> Even if checking that a given File is not a directory and that it actually exists before calling sendFile, there's still always the chance for a race condition that the file is gone at the time the server tries to access it. So I think this should be handled when actually sending out the response.

The race condition is unavoidable.  Sending out a response, as you put it, is not an atomic action, first you write a response header down the socket, then you stream the file down the socket.  So, between writing the response header, and streaming the file, the file could still disappear.  Similarly, while streaming the file out, the file could be truncated or changed in some way, that would make the response invalid.  There's nothing Play can do to recover from these scenarios, you can't unsend the response header once it's been sent, and you can't know for sure when you send the response header that the file is going to be successfully opened and read in full.  So what you're suggesting is impossible to implement.

While it probably does make sense to validate that the file exists when `sendFile` is invoked, it is up to the application to ensure that when it invokes `sendFile`, that that file stays around for long enough to ensure it gets sent safely.  There's really no recovery that Play could do if it disappears.

It's also the applications responsibility to ensure that the file exists and is a directory - the only thing Play should do in `sendFile` if it doesn't exist is throw an exception, which would result in a 500 error.  If it instead sent a 404 response, that would be very bad, trying to send a file that doesn't exist is an application bug, one that should be loudly indicated with an error and an exception in the logs, so developer can see they have a bug and do something about.  It's not a client error for the application to try and send a file that doesn't exist, it's a server error.

**Comment by Gacko** [comment]
Is sendFile throwing some kind of "FileNotFoundException"? A developer could catch this and send an alternative file instead - so quietly returning 404 instead would be bad. Also I'd except a call like `Ok.sendFile` to actually send Ok and nothing else.

**Comment by avdv** [comment]
> The race condition is unavoidable. Sending out a response, as you put it, is not an atomic action, first you write a response header down the socket, then you stream the file down the socket. So, between writing the response header, and streaming the file, the file could still disappear.

Absolutely. So you should not send out the headers until you have opened the file!

> There's nothing Play can do to recover from these scenarios, you can't unsend the response header once it's been sent, and you can't know for sure when you send the response header that the file is going to be successfully opened and read in full. So what you're suggesting is impossible to implement.

Of course, there are always possibilities for errors which is unavoidable, but I think the situation could / must be improved. At least don't pretend to the receiver that everything was OK when you failed miserably on the server side. (so, actually the broken download is not worse as I first have thought, but at least it some kind of error reporting to the client)

> While it probably does make sense to validate that the file exists when sendFile is invoked, it is up to the application to ensure that when it invokes sendFile, that that file stays around for long enough to ensure it gets sent safely. There's really no recovery that Play could do if it disappears.

I disaggree. There are so many different things that could prevent the server from fulfilling the contract of `Ok.sendFile` that it is impractical and even impossible for the user to foresee and check those things prior of actually processing the response. E.g. there need to be enough file descriptors left to open the file et cetera. Also, besides of its exsistence, the file needs to be readable, which you cannot check easily if e.g. AppArmor is involved as it doesn't suffice to check the file's permissions without *really opening the file*.

> Is sendFile throwing some kind of FileNotFoundException?

I don't think that Ok.sendFile should open the file by itself. It's the servers responsibility to process the Action and at the end that doesn't improve the error handling.

> Also I'd except a call like Ok.sendFile to actually send 200 OK and nothing else.

Yes, at first I also thought that it would be a bit weird if `Ok.sendFile` would suddenly send out a different status code than 200. But I think that's actually the most sensible thing to do, at least sent out a 500 status to signal an error.

**Comment by cchantep** [comment]
Hi, At this point a discussion on the MailingList or Gitter room seems necessary to me, to figure out whether it's actionable. Best regards.
