### ISSUE TITLE
Documentation for loose ssl mentions the property wrongly for Play 2.3.x

### ISSUE THREAD

**Issue by abbi-gaurav** [playframework/playframework#5789]
### Play Version (2.3.x / etc)
the property that works is 
ws.acceptAnyCertificate=true, 
but on the page https://www.playframework.com/documentation/2.3.x/LooseSSL
it is mentioned ws.acceptAllCertificates=true

I spent some time figuring it out :)

**Comment by marcospereira** [comment]
Thanks, @abbi-gaurav. Do you mind submitting a pull request?

BTW, this is already fixed for 2.4.x and master.

**Comment by abbi-gaurav** [comment]
I have created the pull request.

Best Regards,
Gaurav Abbi

**Comment by marcospereira** [comment]
Thank you so much, @abbi-gaurav. PR #5794 was already merged so I'm closing the issue.

**Comment by abbi-gaurav** [comment]
Thanks for accepting the pull request.

Best Regards,
Gaurav Abbi
