### ISSUE TITLE
Missing information in Akka streams migration guide

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5803]
https://www.playframework.com/documentation/2.5.x/StreamsMigration25

e.g. "To learn how to migrate a WebSocket.In to a Sink, see XXXX."

**Comment by marcospereira** [comment]
See #5799. Specially https://github.com/playframework/playframework/pull/5799#discussion-diff-55104742.

**Comment by gmethvin** [comment]
I think this issue was resolved by #5899. There is a separate section on WebSockets now.
