### ISSUE TITLE
Typed request fields

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5814]
We should have a way to tag requests that can store structured data. This would be useful for filters to provide additional information on the request.

It could also help us deal with the global state in the HTTP context for Java. If we can store the context (with dependencies injected) on the request, we could write a filter or HttpRequestHandler that does it.

**Comment by richdougherty** [comment]
I've been exploring this issue [here](https://github.com/richdougherty/playframework/tree/custom-request-fields) and [here](https://github.com/richdougherty/frolic2).

**Comment by gmethvin** [comment]
To be more clear, there are two purposes for this:
 1. For caching data on the request (request-scoped dependency injection?)
 2. For computing strongly typed values based on the headers already on the request. This could also be related to #5811.
