### ISSUE TITLE
Injectable ActionBuilders

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5815]
We should recommend (in documentation) a canonical way of creating ActionBuilders that have their dependencies injected into them.

This would be useful for libraries who want to create builders using application state/configuration in some way but do not want to force the user to manually provide all their dependencies.

**Comment by schmitch** [comment]
Actually for Scala this already works fine:
```scala
class LoggingAction @Inject()(injectedLogger) extends ActionBuilder[Request] {
  def invokeBlock[A](request: Request[A], block: (Request[A]) => Future[Result]) = {
    injectedLogger.info("Calling action")
    block(request)
  }
}
class DemoController @Inject()(loggingAction: LoggingAction) extends Controller {
}
```

The only problem is Java here since it actually uses annotations to do it.

**Comment by marcospereira** [comment]
Java is not a problem here since you can also inject components in your actions:

```java
public class MetricsAction extends Action<Metrics> {

    private final MetricsRegister metricsRegister;

    @Inject
    public MetricsAction(MetricsRegister metricsRegister) {
        this.metricsRegister = metricsRegister;
    }

    public CompletionStage<Result> call(Http.Context ctx) {
        // do your thing
    }
}
```
The annotations are used only to mark the actions/controllers, but the actual action composition already happens using Dependency Injection.

@gmethvin are we missing something here?

**Comment by gmethvin** [comment]
This is more of a documentation issue (tagged the issue as such). @marcospereira you are correct that this is already technically possible. I think the main documentation for custom action builders is here: https://www.playframework.com/documentation/2.5.x/ScalaActionsComposition#Custom-action-builders

Previously we suggested people define action builders as objects/methods inside controllers, but there are a lot of benefits to injecting `ActionBuilder`s as well.

**Comment by wsargent** [comment]
We have some documentation in the Play REST API paper for the tech hub, notably in the `PostController` that takes a `PostAction`:

https://developer.lightbend.com/guides/play-rest-api/part-1/index.html
