### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5817]

**Comment by mkurz** [comment]
Akka issue: https://github.com/akka/akka/issues/16862
Closed duplicate: #1005

**Comment by jsw** [comment]
+1

**Comment by schmitch** [comment]
Just for tracking what needs to be done before:
- [ ] Upgrade to Netty 4.1
- [ ] Upgrade netty-reactive-streams to Netty 4.1 (should be done soon)
- [ ] Upgrade AHC to Netty 4.1

Maybe we could ship this in 2.6. Netty 4.1 would work on 2.5 branches, but AHC will refuse to work so this needs some manpower I guess.

**Comment by wsargent** [comment]
Also see https://github.com/AsyncHttpClient/async-http-client/issues/1161 for AHC issue.

**Comment by ahjohannessen** [comment]
What is the status on upgrading to netty 4.1.x - can users expect to see it in 2.6?

**Comment by gmethvin** [comment]
@schmitch I agree this should be a 2.6 feature. We have it on the roadmap but I'd forgotten to update the milestone here.

We will be able to have someone from the core team work on it, but we'd be happy to get outside help too. Will has a lot of experience with AHC so he can help there.

**Comment by urosn** [comment]
I would like to ask if it is possible to add support for QUIC protocol, too? Than, Play will have one major feature more over other frameworks. I agree that this feature is not up to Play completely.

**Comment by gmethvin** [comment]
There's a netty issue for that: netty/netty#3778

**Comment by urosn** [comment]
If play is switching to akka-http from netty is it possible to incorporate QUIC protocol now?

**Comment by ktoso** [comment]
No-one is talking about QUIC implementations here :-)

**Comment by dmyersturnbull** [comment]
Is this an issue only when running Play standalone, or even on top of a webserver with HTTP 2 support, like Apache httpd or [Caddy](https://github.com/mholt/caddy)?

**Comment by natemurthy** [comment]
Happy New Years everyone! 

Any update on this request from the community? We use Play pretty heavily for a variety of services on my team. I've been considering building my own web framework on top of Netty 4.1 to make use of HTTP/2 but would very much like to continue to use Play for my apps. 

@wsargent @ktoso Can we expect Netty 4.1 to be in Play 2.6.x ? According to @Tolsi, async-http-client has been upgraded to Netty 4.1, so looks like it shouldn't be too hard to start using HTTP/2 with WSClient at the very least.

**Comment by natemurthy** [comment]
Adding reference to https://github.com/playframework/playframework/issues/5817

**Comment by natemurthy** [comment]
Adding reference to https://github.com/playframework/playframework/issues/6809

**Comment by ktoso** [comment]
FYI: Akka HTTP is not addressing the client side question here, we're developing the server. (at least for now).

**Comment by marcospereira** [comment]
See #7324.
