### ISSUE TITLE
Play 2.5 OneAppPerSuite for controller unit test causes some SCoverage coverage issue for Logger

### ISSUE THREAD

**Issue by ysihaoy** [playframework/playframework#5819]
Before I upgrade to Play 2.5, my controller unit tests don't need to mixin the trait `OneAppPerSuite`. And my coverage is good using SCoverage even I have some Logger.debug or info.

But after I upgrade to Play 2.5, I need to mixin the trait called `OneAppPerSuite` because of the implicit `Materializer`. After adding this my controller unit tests passed, but there are some coverage issue for all logging stuff and I can't see the log print on the console (I can see it before upgrade). However for the tests which don't mixin that trait have no coverage issues.

Don't know it's the root cause or not? But Play team should look at this.

Thanks.

**Comment by schmitch** [comment]
you could actually create a ActorSystem for your tests and get a Materializer out of that so you don't need a whole application.

**Comment by ysihaoy** [comment]
Could you please give me some examples for the code.

BTW, if I just use Logger.debug or info it works. But now
Logger.classOf[this.class]

Anyway, I still quite interested to know the code of your suggestions.

Thanks.

On Tue, 8 Mar 2016, 00:23 Schmitt Christian <notifications@github.com>
wrote:

> you could actually create a ActorSystem for your tests and get a
> Materializer out of that so you don't need a whole application.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playframework/playframework/issues/5819#issuecomment-193245934>
> .
>
-- 

Tianhao

Sent from Google Inbox

**Comment by marcospereira** [comment]
@ysihaoy, as @schmitch said, the [mailing list](https://groups.google.com/forum/#!forum/play-framework) is a better place to this kind of discussion.
