### ISSUE TITLE
Move Guice support into an AutoPlugin that is enabled by default and can be disabled

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#5822]
Similar to how one can opt out of Logback (by disabling the AutoPlugin), it would be nice to be able to opt out of Guice and it's tree of dependencies.

I particularly would like this as I want to define typed http clients in Scala which use compile-time DI and therefore never use Guice, nor want to bring that to the dependency graph.

### Are you looking for help?

This is a feature request, which I have discussed on the [developer mailing list](https://groups.google.com/forum/#!forum/play-framework-dev) (see ["play-ws as a separate module"](https://groups.google.com/forum/#!topic/play-framework-dev/tSPvfLrZM7U)).

### Play Version (2.5.x / etc)

2.6.x (or later)

### API (Scala / Java / Neither / Both)

I assume both, but I only have experience on the Scala side.

**Comment by wsargent** [comment]
Play uses play.api.inject for internal, and provides a Guice implementation:

https://github.com/playframework/playframework/tree/2.5.0/framework/src/play/src/main/scala/play/api/inject/guice

It's theoretically possible to use another DI framework for `play.api.inject` functionality, but it's not a runtime issue or a compile time issue -- it could potentially be an issue if there were two different versions of Guice that were binary incompatible, but at the rate Guice versions come out, that seems unlikely.

**Comment by schmitch** [comment]
@wsargent maybe we could vendorize functions used by commons lang.
Actually it only uses two functions of StringEscapeUtils so we could slim it down more.

**Comment by gmethvin** [comment]
My suggestion is the following (currently working on this in #6178):
 - Similar to how we have `PlayJava` and `PlayScala` SBT plugins, we can provide `PlayJavaGuice` and `PlayScalaGuice`, which essentially be guice-flavored versions of those plugins. I think the more explicit approach makes it clear that the Guice support is something separate from the core of Play, and makes it obvious how to use Play without Guice

 - The `play.api.inject` APIs would stay in Play core, to allow other implementations to work with Play.

 - In the default configuration with no DI modules installed, Play would throw an exception prompting the user to define an application loader, or to include a module like `play-guice` that defines one. Another option I'm considering is finding a way to instead generate an application loader that works for simple applications, possibly as part of the routes compiler.

/cc @wsargent @dwijnand

**Comment by dwijnand** [comment]
Sounds good to me, but I expect a non-explosive out-the-box experience is probably preferable, either by making Play*Guice plugin auto-trigger (and then disable-able) or with a minimal application loader, I don't mind.

**Comment by gmethvin** [comment]
@dwijnand I think having the Guice plugin auto-trigger would make for the smoothest migration experience, so I'm leaning more toward that now. The application loader should really be in the user's code, since it would probably require explicitly defining the controllers, assuming we don't generate the code for them.
