### ISSUE TITLE
Move Twirl support into an AutoPlugin that is enabled by default and can be disabled

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#5823]
Similar to how one can opt out of Logback (by disabling the AutoPlugin), it would be nice to be able to opt out of Twirl and it's tree of dependencies.

I particularly would like this as I want to define typed http clients in Scala which use compile-time DI and therefore never use Twirl, nor want to bring that to the dependency graph.
### Are you looking for help?

This is a feature request, which I have discussed on the [developer mailing list](https://groups.google.com/forum/#!forum/play-framework-dev) (see ["play-ws as a separate module"](https://groups.google.com/forum/#!topic/play-framework-dev/tSPvfLrZM7U)).
### Play Version (2.5.x / etc)

2.6.x (or later)
### API (Scala / Java / Neither / Both)

I assume both, but I only have experience on the Scala side.

**Comment by schmitch** [comment]
I doubt this is possible since twirl will also be used to create the routes file.

**Comment by diwalak** [comment]
+1 for this.
We use play as an API Server and don't use twirl.

**Comment by nafg** [comment]
What does twirl have to do with the routes?

**Comment by schmitch** [comment]
the routes file gets generated with a twirl template:
https://github.com/playframework/playframework/blob/master/framework/src/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl

You can't disable SbtTwirl, since the routes file will not be compiled then.
You could actually run play without Twirl or any sbt plugin at all, however than you need to use the manual router:

https://www.playframework.com/documentation/2.5.x/ScalaEmbeddingPlay You just need to have the following dependencies:

    "com.typesafe.play" %% "play" % "2.5",
    "com.typesafe.play" %% "play-netty-server" % "2.5",
    "com.typesafe.play" %% "play-logback" % "2.5",

if twirl gets disabled than you would need to create your routes by yourself. Or you don't use the play plugin and loose the auto reload.

**Comment by wsargent** [comment]
You don't need to use Play's built in routing.  For example, https://github.com/teamon/play-navigator and https://github.com/lloydmeta/slim-play don't use the routes file.

**Comment by wsargent** [comment]
Also, it's not clear what dependencies in Twirl are objectionable: looking at https://github.com/playframework/twirl/blob/master/build.sbt#L90 it's pretty minimal.

**Comment by dwijnand** [comment]
Yeah, it's less than Guice, I created the ticket because @jroper mentioned it. It's a nice to have.

**Comment by nafg** [comment]
On Wed, Mar 9, 2016 at 5:02 AM Schmitt Christian <notifications@github.com>
wrote:

> the routes file gets generated with a twirl template:
>
> https://github.com/playframework/playframework/blob/master/framework/src/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl
>
Interesting! I never thought of using twirl as a scala source code
generator.

I wonder if it would make sense for Slick...

You can't disable SbtTwirl, since the routes file will not be compiled then.

**Comment by nafg** [comment]
On Wed, Mar 9, 2016 at 1:18 PM Dale Wijnand <notifications@github.com>
wrote:

> Yeah, it's less than Guice, I created the ticket because @jroper
> <https://github.com/jroper> mentioned it. It's a nice to have.
>

+1 for more modularity

**Comment by nafg** [comment]
But it does mean that the autoplugin should be responsible for both:
disabling it should mean that none of the built-in router code should be on
the classpath.

**Comment by schmitch** [comment]
@wsargent what about trying to include those two methods of apache-commons-lang3? it only uses two things of StringEscapeUtils, I doubt it would be "big" to create such methods in scala.

**Comment by 0xbaadf00d** [comment]
I agree, it could be nice to have hability to remove Twirl to get a smaller binary package. Really usefull in case Play is used only to serve Json document (API - microservice)

**Comment by schmitch** [comment]
twirl 1.3 does not have any dependencies and the api package is only 9kb big.
the other dependencies it has are included in play anyway.

**Comment by dwijnand** [comment]
Indeed they look tiny:
* http://repo1.maven.org/maven2/com/typesafe/play/twirl-api_2.12/1.3.13/
* http://repo1.maven.org/maven2/com/typesafe/play/twirl-parser_2.12/1.3.13/
* http://repo1.maven.org/maven2/com/typesafe/play/twirl-compiler_2.12/1.3.13/

and so does the number of dependencies:
* https://search.maven.org/remotecontent?filepath=com/typesafe/play/twirl-api_2.12/1.3.13/twirl-api_2.12-1.3.13.pom
* https://search.maven.org/remotecontent?filepath=com/typesafe/play/twirl-parser_2.12/1.3.13/twirl-parser_2.12-1.3.13.pom
* https://search.maven.org/remotecontent?filepath=com/typesafe/play/twirl-compiler_2.12/1.3.13/twirl-compiler_2.12-1.3.13.pom

So I agree the ROI for this doesn't look good.

**Comment by marcospereira** [comment]
For future reference, see #8011.
