### ISSUE TITLE
[doc] [2.5.x] Play WS docs some SSL Configs are using list, but the doc mentions a String

### ISSUE THREAD

**Issue by schmitch** [playframework/playframework#5826]
### Play Version (2.5.x / etc)

2.5.x

### API (Scala / Java / Neither / Both)

Both

### Actual Behavior
Docs are mention a String but in reference.conf it is using a list, and a string will throw an error

### Expected Behavior
Docs should change of

- play.ws.ssl.disabledKeyAlgorithms
- play.ws.ssl.disabledSignatureAlgorithms

To use a list

**Comment by wsargent** [comment]
@schmitch Do you have a reference I can look at?  There is no documentation link attached to this bug, and https://github.com/playframework/playframework/blob/master/documentation/manual/working/commonGuide/configuration/ws/DebuggingSSL.md does not show strings, but boolean properties.

**Comment by schmitch** [comment]
@wsargent these two:
- https://www.playframework.com/documentation/2.5.x/CertificateValidation#Disabling-Certificates-with-Weak-Signature-Algorithms
- https://www.playframework.com/documentation/2.5.x/CertificateValidation#Disabling-Certificates-With-Weak-Key-Sizes

**Comment by wsargent** [comment]
Where is revocationLists mentioned in CertificateValidation.md?

**Comment by schmitch** [comment]
yeah as said that was a copy paste mistake only:
- play.ws.ssl.disabledKeyAlgorithms
- play.ws.ssl.disabledSignatureAlgorithms

are wrong
