### ISSUE TITLE
Behaviour of request.secure has changed in 2.4.6

### ISSUE THREAD

**Issue by cb372** [playframework/playframework#5829]
Since upgrading an app from 2.4.3 to 2.4.6, the value of `request.secure` is always false, even when using HTTPS.

Play is running on port 9000 on an EC2 machine. TLS termination is performed by an Elastic Load Balancer. We do not have any value configured for `play.http.forwarded.trustedProxies`.

Is this change of behaviour expected? I believe it is caused by the changes in #5266 and #5326.

By the way, I found somebody with the same problem on the mailing list [here].(https://groups.google.com/forum/#!msg/play-framework/q3bDdtbCaSQ/N--87ZR_BQAJ)

### Play Version (2.5.x / etc)

2.4.6

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Ubuntu Wily on EC2

```
Linux ip-10-248-78-189 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)
```

### Expected Behavior

1. Configure ELB to accept HTTPS connections
2. Access https://myapp.com/ (where myapp.com is CNAMEd to the ELB)
3. `request.secure` is true

### Actual Behavior

1. Configure ELB to accept HTTPS connections
2. Access https://myapp.com/ (where myapp.com is CNAMEd to the ELB)
3. `request.secure` is false

### Reproducible Test Case

Tricky, as I would have to register a domain and create a TLS certificate in order to reproduce.

**Comment by gmethvin** [comment]
Does it work if you configure `trustedProxies`? That change just made the determination of `secure` more  secure. It won't blindly trust the `Forwarded` headers from the proxy unless you tell it to.

**Comment by cb372** [comment]
I've confirmed that setting `play.http.forwarded.trustedProxies = [ "0.0.0.0/0" ]` resolves the issue.
