### ISSUE TITLE
Activator Showing Unsupported version of Play 2.5.0

### ISSUE THREAD

**Issue by kishorenayar** [playframework/playframework#5834]
I have downloaded latest Lightbend Activator from this [URL](https://playframework.com/download). But when I tried to run the project I'm getting the following error in the activator

Using unsupported version of Play: 2.5.0

How do I resolve this ?

**Comment by fvthree** [comment]
same as mine. works fine with 2.4 but not with 2.5

**Comment by kishorenayar** [comment]
Any Idea how this can be fixed ?

**Comment by fvthree** [comment]
When using activator ui, "Using unsupported version of Play: 2.5.0" is being logged. It doesnt show when using the activator in command prompt.

**Comment by wsargent** [comment]
Activator UI is another project.  Please file an issue at https://github.com/typesafehub/activator -- you also need to provide a reproducible test case and step by step instructions, including logs.
