### ISSUE TITLE
[2.5.0] outActor created using ActorFlow.actorRef is not terminated when flowActor terminates

### ISSUE THREAD

**Issue by danishin** [playframework/playframework#5838]
### Play Version (2.5.x / etc)
2.5.0

### Expected Behavior
1. Create `WebSocket` using `ActorFlow.actorRef`
2. Terminate `flowActor` via `self ! PoisonPill` or `context stop self`
3. `outActor` is terminated (which was the behavior in 2.4)

### Actual Behavior
1. `outActor` is not terminated. 

I'm not sure whether this is an expected breaking change introduced in 2.5.x or not as documentation for WebSocket hasn't been updated.

**Comment by an-tex** [comment]
+1

**Comment by wsargent** [comment]
Hi @danishin -- can you include a project or a failing test case showing this behavior?

Also, are you using watchTermination?  Please see the example project at playframework/play-websocket-scala:

https://github.com/playframework/play-websocket-scala/blob/master/app/controllers/HomeController.scala#L160

**Comment by petermullins** [comment]
It seems that the actor in `ActorFlow.actorRef()` does receive the `Terminated` message when its `flowActor` is terminated, but the message is not matched correctly, so it gets ignored:

https://github.com/playframework/playframework/blob/6e5fd6b197cbe8f4b50999e5281ef85213e2fac0/framework/src/play-streams/src/main/scala/play/api/libs/streams/ActorFlow.scala#L43

Changing `case Terminated =>` to `case Terminated(_) =>` appears to fix the problem.

**Comment by marcospereira** [comment]
@petermullins do you mind submitting a pull request?

**Comment by monktastic** [comment]
This will be available in the next release? For now I'm sending outActor a PoisonPill as a workaround.

**Comment by gmethvin** [comment]
Yes, the fix will be in 2.5.5.
