### ISSUE TITLE
Default logging configuration in dev mode for application should be DEBUG

### ISSUE THREAD

**Issue by jonasanso** [playframework/playframework#5842]
Found in play 2.5 master today, although the issue might be quite old.

There are two logback files, one for production (logback-play-default.xml) and one for development (logback-play-dev.xml)

In logback-play-default.xml we find
```
  <logger name="application" level="DEBUG" />
```
While in logback-play-dev.xml we see
```
  <logger name="application" level="INFO" />
```

After creating a new play scala app without overriding the logging configuration.
Run the app in DEV mode and hit any Logger.debug(...). It does not show the logging.
Run the app in PROD mode and hit any Logger.debug(...). It DOES show the logging.

I have checked the history of the files and this just seem to be a non intended behaviour.

What I do not know is what should be the proper solution. Maybe invert the situation? 

It is the first issue I create, so let me know if I can do anything else.

**Comment by marcospereira** [comment]
Thanks @jonasanso. I don't think this is intentional. Could you please submit a PR to solve this issue?

**Comment by jonasanso** [comment]
Thanks @marcospereira  for your help.

I have submitted a PR https://github.com/playframework/playframework/pull/5916 
It is my first PR, I have read the documentation provided but if I missed anything please let me know.
