### ISSUE TITLE
CSRFFilter is hard to initialize correctly unless you rely on global state or on javax.inject

### ISSUE THREAD

**Issue by julienrf** [playframework/playframework#5847]
The actual constructor relies on the global state or javax.inject because the default value of the `tokenProvider` parameter explicitly uses `Crypto.crypto`, which itself uses either `Play.privateMaybeApplication` or `Application.instanceCache`.

More generally, it is currently quite hard to write code that does **not** indirectly rely on javax.inject or the global state. We should definitely push more effort into making these situations more explicit so that they can not happen unbeknownst to the developer.

**Comment by gmethvin** [comment]
It does use global state, but it will create a default instance if there is no application in scope. Perhaps we should just avoid using the application state altogether and just create a default instance, but then it could create subtle breakage in some people's apps...

**Comment by julienrf** [comment]
> Perhaps we should just avoid using the application state altogether and just create a default instance

No, that would be worse. The best solution is to *really* remove the global state and to not make an heavy use of application’s `injector`.

**Comment by gmethvin** [comment]
What I meant is we could set the default to some constant value, which would not be stateful at all.

**Comment by julienrf** [comment]
And it would not be useful at all either :)

**Comment by julienrf** [comment]
After more digging, it seems that the problem is that the runtime injector created by `BuiltInComponents` does not tell how to inject a `Crypto`. Am I right?
In my case, writing to the session cookie does not work because this component can not be retrieved. I will create a dedicated issue for that.

**Comment by gmethvin** [comment]
Yes, you're right. We should just add it to the injector in BuiltInComponents.

**Comment by julienrf** [comment]
I just opened #5856
