### ISSUE TITLE
Cookies can not be used with “compile-time DI”

### ISSUE THREAD

**Issue by julienrf** [playframework/playframework#5848]
Cookie decoding [explicitly uses](https://github.com/playframework/playframework/blob/207c1018891b9d8d16ad831ed1303450e5ba627c/framework/src/play/src/main/scala/play/api/mvc/Http.scala#L957) `Cookies.config`, which itself [explicitly uses](https://github.com/playframework/playframework/blob/207c1018891b9d8d16ad831ed1303450e5ba627c/framework/src/play/src/main/scala/play/api/mvc/Http.scala#L844) `GlobalStateHttpConfiguration.httpConfiguration`, which itself [explicitly uses](https://github.com/playframework/playframework/blob/207c1018891b9d8d16ad831ed1303450e5ba627c/framework/src/play/src/main/scala/play/api/mvc/Http.scala#L22) `HttpConfiguration.current`, which itself [relies on javax.inject](https://github.com/playframework/playframework/blob/207c1018891b9d8d16ad831ed1303450e5ba627c/framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala#L149), which does not work when you don’t use Guice.

**Comment by gmethvin** [comment]
You're right that there is global state here, which should be removed, but it should still work with compile-time DI if you use `BuiltInComponents` since it [configures a runtime injector](https://github.com/playframework/playframework/blob/2.5.0/framework/src/play/src/main/scala/play/api/Application.scala#L249). That doesn't require Guice at all.

**Comment by julienrf** [comment]
Indeed, it should work, so maybe my problem comes from somewhere else, because my application still does not run (though it compiles). I will check further and update or close this ticket.

**Comment by julienrf** [comment]
The exception I was seeing was not caused by this part of the code. The runtime injector configured by `BuiltInComponents` works well with … built-in components, but not, for instance, with optional components like I18n…
