### ISSUE TITLE
Evolutions INSERT INTO statement should specify column names

### ISSUE THREAD

**Issue by kristijanbambir** [playframework/playframework#5850]
Currently in [`play.api.db.evolutions.EvolutionsApi.evolve()`](https://github.com/playframework/playframework/blob/b9d21b04599f1c0d0247ca8be27e3d8d91cfcfc9/framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L154) the INSERT INTO statement does not specify column names. This is an issue when working with [Crate.IO](https://crate.io/) because Crate uses lexical ordering when column name list is omitted. This results in `applied_at` column being used as `id` column.

**Comment by mkurz** [comment]
@kristijanbambir If you could provide a pull request that would be nice.
