### ISSUE TITLE
[2.5.0] Scala WebSocket documentation is not updated

### ISSUE THREAD

**Issue by vrcod** [playframework/playframework#5855]
`WebSocket.acceptWithActor` is marked as deprecated, but an example in documentation (https://playframework.com/documentation/2.5.x/ScalaWebSockets#Handling-WebSockets-with-actors) still features it instead of the new approach.

**Comment by gmethvin** [comment]
Not exactly a duplicate, but fixing #5803 will help fix this too.

**Comment by marcospereira** [comment]
Duplicated with #5057.
