### ISSUE TITLE
[2.5.0] LESS plugin

### ISSUE THREAD

**Issue by vrcod** [playframework/playframework#5862]
Since plugins were deprecated, what's the approach now to include LESS plugin that was actually part of 2.4 documentation (https://playframework.com/documentation/2.4.x/AssetsLess)?

**Comment by gmethvin** [comment]
SBT plugins are not deprecated so you can still use the LESS SBT plugin. We
deprecated the play.api.Plugin interface, which was used to integrate with
Play's application lifecycle.

You should be able to follow the latest documentation here:
https://playframework.com/documentation/2.5.x/AssetsLess

On Fri, Mar 11, 2016 at 8:35 AM, vrcod <notifications@github.com> wrote:

> Since plugins were deprecated, what's the approach now to include LESS
> plugin that was actually part of 2.4 documentation (
> https://playframework.com/documentation/2.4.x/AssetsLess)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playframework/playframework/issues/5862>.
>



-- 
*Greg Methvin*
*Senior Software Engineer*
Lightbend, Inc. <https://www.lightbend.com/>

**Comment by vrcod** [comment]
Thanks. It started working again after reload/clean.
