### ISSUE TITLE
[>=Play 2.4] How to replace the GlobalSettings and Play.isDev() etc...

### ISSUE THREAD

**Issue by snowyu** [playframework/playframework#5867]
It's very lack of the documentation.

Many APIs have been marked to be deprecated since play 2.4.
But It hasn't a simple way to replace it, Why?

Such as, `GlobalSettings.onStart`: how to inject a method after the application startup(all plugins, modules are loaded and initialized)?

This is not the proper way if you wanna startup after all modules are initialized, such as the evolution module(#4808), So what's the common injection point for this(afterr all modules, not a special module)?

```java
public class Startup {
  @Inject
  public Startup(Application application) {
  }
}

```
Maybe create a new GlobalSettings module to keep compatibility. And the replacement of other API is no documents. 

Many plugins have been not worked after upgraded to 2.5 Why not to keep deprecated instead of removing until Play 3.0..

**Comment by gmethvin** [comment]
Hi @snowyu,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Also, you may find some of your answers in past mailing list posts, as many of these issues have already been discussed.
