### ISSUE TITLE
Small inconsistencies at Java Results API

### ISSUE THREAD

**Issue by marcospereira** [playframework/playframework#5872]
### Play Version

2.5.0

### API

Java

### Actual Behavior

1. [`StatusHeader.sendFile`](https://github.com/playframework/playframework/blob/58a150d/framework/src/play/src/main/java/play/mvc/StatusHeader.java#L170) and [`StatusHeader.sendResource`](https://github.com/playframework/playframework/blob/58a150d/framework/src/play/src/main/java/play/mvc/StatusHeader.java#L94) both have `inline=true` as default and [`StatusHeader.sendPath`](https://github.com/playframework/playframework/blob/58a150d/framework/src/play/src/main/java/play/mvc/StatusHeader.java#L130) has **`inline=false`** as default.
2. There is a [`sendPath(Path path, boolean inline, String filename)`](https://github.com/playframework/playframework/blob/58a150d/framework/src/play/src/main/java/play/mvc/StatusHeader.java#L152), but there is no equivalent `sendFile` or `sendResource`. Also, Scala Results API have methods to set both if the File/Path will be delivered inline and the content disposition filename.
3. [`sendInputStream(InputStream stream)`](https://github.com/playframework/playframework/blob/58a150d/framework/src/play/src/main/java/play/mvc/StatusHeader.java#L55) uses a `HttpEntity.chunked` and [`sendInputStream(InputStream stream, long contentLength)`](https://github.com/playframework/playframework/blob/58a150d/framework/src/play/src/main/java/play/mvc/StatusHeader.java#L70) uses a `HttpEntity.Streamed` (`File` and `Path` methods [uses `HttpEntity.Streamed`](https://github.com/playframework/playframework/blob/58a150d/framework/src/play/src/main/java/play/mvc/StatusHeader.java#L209)).

**Comment by wsargent** [comment]
Also see https://github.com/playframework/playframework/issues/2178
