### ISSUE TITLE
[2.5.0] [HAProxy] Some responses are shorter than declared in Content-length

### ISSUE THREAD

**Issue by vipo** [playframework/playframework#5874]
### Play Version

2.5.0

Older version (i.e. 2.4.6) works as expected without any problems. So workaround for us is simple: we just downgraded play.

### API

Scala 2.11.7

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Docker image java:8u66-jdk, Mesos, Marathon.

### Expected Behavior

Application built on play-netty-server (embedded) works as expected if is called directly (docker exposed port or when you run it locally). It returns csv plain text responses, which size might vary from 55kb to a few megabytes.

We want play 2.5.0 version to work behind LB in the same way as version 2.4.6 does.

### Actual Behavior

If we put this application under HAProxy 1.6 load balancing (marathon-lb) _some_ (like 20%) responses (plain/html, plain/text) become truncated (to approx 19kb): it is much shorter than declared in Content-Lenght header. This behavior is reproducible with Chrome (net::ERR_CONTENT_LENGTH_MISMATCH), Firefox (which is quite silent in such situations) and even curl (which also says content is shorter than expected).

HAProxy LB options were tested: keep alive, tunnel, server close -- all with same negative result.

I am pretty sure this issue is related to #5835 which is closed.

**Comment by jroper** [comment]
Fixed in #5899

**Comment by marcospereira** [comment]
Closing after #5932.

**Comment by ztaoo** [comment]
hi, there,

	Our team are using play-2.5.0 with nginx to develop the next version of the product.
	We also met this issue.
	When will play-2.5.1 released? or we should back to play-2.4.6?
	thinks.

**Comment by ztaoo** [comment]
Hi,  @jroper  @marcospereira 
Our team are using play-2.5.0 with nginx to develop the next version of the product.
We also met this issue.
When will play-2.5.1 released? or we should back to play-2.4.6?
thinks.

**Comment by ztaoo** [comment]
Hi, @jroper @marcospereira
Our team are using play-2.5.0 with nginx to develop the next version of the product.
We also met this issue.
When will play-2.5.1 released? or we should back to play-2.4.6?
thanks.

**Comment by muuki88** [comment]
@ztaoo you can just add the netty-reactive dependency manually

```scala
libraryDependencies += "com.typesafe.netty" % "netty-reactive-streams-http" % "1.0.4"
```

After you upgrade to 2.5.1 you can remove it again.

**Comment by swoopster-sb** [comment]
still getting net::ERR_CONTENT_LENGTH_MISMATCH on play-2.5.3 when running in production mode.
(in debug mode everything works fine)

**Comment by maxyermayank** [comment]
still getting net::ERR_CONTENT_LENGTH_MISMATCH on play-2.5.10 when running in production mode.
(in debug mode everything works fine)

**Comment by marcospereira** [comment]
@swoopster-sb and @maxyermayank, it will be pretty hard to figure out what is happening without further information.

Could you please create reproducible test scenario for this issue? If you are using a frontend http server, it would be good to know how it is configured in your scenarios too.

**Comment by maxyermayank** [comment]
@marcospereira Please ignore my comment. 

Figured out the problem. Had Race condition in Asynchronous code, it somehow worked in Play 2.4.x. Ok.sendFile works fine now just had to use onClose function to avoid race condition.
