### ISSUE TITLE
JavaScript CSRF support

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#5881]
Play needs some support and documentation CSRF protection in JavaScript single page applications especially with the changes introduce in 2.5 to add stricter CSRF checking. Right now the Play helpers are only geared toward Twirl templates.

As an example of what this looks like in a JavaScript single page app, Angular looks for a cookie named `XSRF-TOKEN` and then copies that into HTTP header named `X-XSRF-TOKEN`. See the [Wikipedia CSRF article](
https://en.wikipedia.org/wiki/Cross-site_request_forgery#Cookie-to-Header_Token) for more details on how this protects an application.

It'd be good to have a filter available to set a configurable `XSRF-TOKEN` cookie and for the CSRF filter to check a configurable header name like `X-XSRF-TOKEN`.

**Comment by schmitch** [comment]
Singlepage Apps shouldn't need CSRF Protection.
Most Single Page Apps should avoid Sessions.

**Comment by gmethvin** [comment]
@benmccann Can't you just configure the CSRF filter like:
```
play.filters.csrf {
  cookie.name = "XSRF-TOKEN"
  header.name = "X-XSRF-TOKEN"
}
```
?

**Comment by gmethvin** [comment]
@benmccann Can you clarify if you think any work needs to be done here? I thought this already should be possible with the current CSRF filter implementation

**Comment by benmccann** [comment]
Thanks!

**Comment by ntenisOT** [comment]
@gmethvin I configured the suggested filter but if you serve your Angular files (homepage) using Assets.at, play does not include the cookie. 

Is it possible to somehow explicitly add the token? 

Please check
http://stackoverflow.com/questions/37541706/add-csrf-to-assets-for-angular
