### ISSUE TITLE
Allow exempting certain URLs from CSRF protection

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#5882]
We should add a way to have certain URLs bypass CSRF protections. It makes the process of turning on CSRF protection easier because you can do it more gradually, but it's also oftentimes required. Just as an example, if you want to integrate with Stripe's Webhook API, you need to turn off CSRF protection on a URL: https://stripe.com/docs/webhooks#receiving-webooks-with-csrf-protection

I'm not sure what the best syntax for this would be. One option would be to allow for placing a comment in the routes file like:

```
# NOCSRF
POST    /stripe/webhook                     @controllers.Stripe.webhook()
```

That's pretty easy to look for in the filter with something like this:

```
if (rh.tags.getOrElse("ROUTE_COMMENTS", "").contains("NOCSRF")) {
  nextFilter(rh)
} else {
  chainedFilter(rh)
}
```

Or another option could be an annotation on the method:

```
@NoCSRF
public Result webhook() {
  ...
}
```

If we can agree on a syntax I'd be happy to send a pull request

**Comment by wsargent** [comment]
This seems like a case where you'd use an action composition with `CSRFAction` rather than an exemption to the filter.

**Comment by benmccann** [comment]
I'm not following your suggestion. I think `CSRFAction` is a Scala thing? I don't really know what that means in Java land.

Anyway, it sounds like you're suggesting that CSRF is not applied by default and we turn it on for each URL we want it on. I have about 500 URLs in my app and 499 of them need CSRF. Not having CSRF on by default and making my developers remember to turn it on means that they will eventually forget to enable it on some number of URLs causing security issues. That would be scary to me. I think it's much better that it's on by default and then we exempt URLs where it isn't needed.

**Comment by schmitch** [comment]
Actually there is a Java Annotation: https://www.playframework.com/documentation/2.5.x/JavaCsrf#Applying-CSRF-filtering-on-a-per-action-basis

However what I can think of would've been more a way of Grouping Filters to different Routers.

I.E.: Router1 has gzip and csrf and Router2 has only gzip. Somehow that would make sense since API's not always needing CSRF.

**Comment by benmccann** [comment]
Ah, looks like there's a Java Annotation for requiring a CSRF check. But we need one that does the reverse and skips CSRF check. CSRF should be on by default for security and disabled only when absolutely required.

**Comment by domdorn** [comment]
just stumbled upon this... I wrote blog posts for this some time ago..
Play 2.5: http://dominikdorn.com/2016/06/playframework-2-5-global-csrf-protection-disable-csrf-selectively/
Play 2.3 / 2.4: http://dominikdorn.com/2014/07/playframework-2-3-global-csrf-protection-disable-csrf-selectively/

Of course, it would be great to see my simple #NOCSRF built into the framework itself, so I can stop implementing the filters myself for every upgrade :)

**Comment by marcospereira** [comment]
Hey @domdorn and @benmccann,

Do you guys want to submit a pull request to address this issue? It looks like, based on the example showed by @domdorn, that we need to change `CSRFAction` (which is used by the `CSRFFilter`) to consider the route comments.

**Comment by gmethvin** [comment]
Perhaps it would be best to have a more well-defined mechanism for "tagging" requests in the routes. Something like:

```
!NOCSRF
POST    /stripe/webhook                     @controllers.Stripe.webhook()
```
It could either be within the comments or a completely new syntax in the routes file. Then we would create an attribute on the request with all the route tags so they could be queried in a structured way.

**Comment by gmethvin** [comment]
I mean we should actually parse out the individual tags before each route definition. Right now we're just recording the route comments all together in a Play request tag (`ROUTE_COMMENTS`, which should be moved to attributes at some point before the release).

I was actually suggesting we could have an alternate syntax different from comments (maybe `!` instead of `#`) so it's clear that it means something important. It would be fairly straightforward to modify the parser to collect a list of "tags" (starting with !) in addition to generic comments. I'm not sure it needs to be anything sophisticated, just string key/value pairs like `!csrf=false`.

**Comment by benmccann** [comment]
I've seen people put yaml in the routes syntax before. E.g. [iheartradio/play-swagger](https://github.com/iheartradio/play-swagger). If we use something like HOCON or YAML then it'd be good to prefix with `play`. That way the keys are namespaced and people who are using routes comments in others ways (like [iheartradio/play-swagger](https://github.com/iheartradio/play-swagger)) can easily separate comments used for different purposes.

I do like the `!` suggestion. (I'm also a little scared of touching the routes parser, so might have to leave a PR to someone else if we go with that syntax, but that probably shouldn't influence which syntax we go with)

**Comment by mkurz** [comment]
Any chance a solution for this issue will make it in 2.6?
