### ISSUE TITLE
Crypto API 2.5.0 - No configuration setting found for key 'play.crypto.secret'

### ISSUE THREAD

**Issue by andyczerwonka** [playframework/playframework#5884]
I understand that the Crypto API is now officially deprecated. I've upgraded with an eye from migrating away, but in 2.5.0 I get an error. I would assume it would still work given the deprecated status.

```
[error] - akka.actor.OneForOneStrategy - No configuration setting found for key 'play.crypto.secret'
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'play.crypto.secret'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:198)
	at com.typesafe.config.impl.SimpleConfig.getIsNull(SimpleConfig.java:208)
	at play.api.ConfigLoader$$anon$4.load(Configuration.scala:1075)
	at play.api.ConfigLoader$$anon$4.load(Configuration.scala:1073)
	at play.api.PlayConfig.get(Configuration.scala:916)
	at play.api.PlayConfig$$anonfun$getDeprecated$2.apply(Configuration.scala:960)
	at scala.Option.getOrElse(Option.scala:121)
	at play.api.PlayConfig.getDeprecated(Configuration.scala:959)
	at play.api.libs.crypto.CryptoConfigParser.get$lzycompute(Crypto.scala:494)
	at play.api.libs.crypto.CryptoConfigParser.get(Crypto.scala:465)
	at play.api.libs.Crypto$$anonfun$crypto$1.apply(Crypto.scala:58)
	at play.api.libs.Crypto$$anonfun$crypto$1.apply(Crypto.scala:55)
	at scala.Option.fold(Option.scala:158)
	at play.api.libs.Crypto$.crypto(Crypto.scala:63)
	at play.api.libs.Crypto$.decryptAES(Crypto.scala:86)
	at models.Site$.findByApiKey(Site.scala:146)
```

**Comment by wsargent** [comment]
It's still in reference.conf:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/resources/reference.conf#L233

I would turn on `akka.log-config-on-start` and debug your application.conf file:

https://github.com/playframework/playframework/blob/master/templates/play-common/conf/application.conf#L24-L35

**Comment by andyczerwonka** [comment]
@wsargent I did do that, and it is there. That's the point, the secret is there and Crypto can't find it.

```
        "crypto" : {
            # reference.conf @ jar:file:/home/aczerwon/.ivy2/cache/com.typesafe.play/play_2.11/jars/play_2.11-2.5.0.jar!/reference.conf: 239
            "aes" : {
                # reference.conf @ jar:file:/home/aczerwon/.ivy2/cache/com.typesafe.play/play_2.11/jars/play_2.11-2.5.0.jar!/reference.conf: 240
                "transformation" : "AES/CTR/NoPadding"
            },
            # reference.conf @ jar:file:/home/aczerwon/.ivy2/cache/com.typesafe.play/play_2.11/jars/play_2.11-2.5.0.jar!/reference.conf: 236
            # The JCE provider to use. If null, uses the platform default.
            "provider" : null,
            # application.conf @ file:/home/aczerwon/work/tyrion/target/scala-2.11/classes/application.conf: 12
            # Secret key
            # ~~~~~
            # The secret key is used to secure cryptographics functions.
            # If you deploy your application to several instances be sure to use the same key!
            "secret" : "B:ZiI7caw?_:p=fPl^jVwIiZ^=n4I8q5AcZ`uLGs<uJp?^AnINvC1yh9;]K[e][p"
        }
```

**Comment by wsargent** [comment]
In that case, you must be referencing something other than Play's config.  Change your `Site` singleton object to a DI @Singleton and use @Inject() (config: play.api.Configuration) in the constructor.

BTW you should absolutely change your secret now -- there are automated scripts that run through Github and associate secret keys with websites for attacks later, so this will be picked up by them.

**Comment by andyczerwonka** [comment]
The point is that it used to work just fine. Can you suggest what has changed? How is it that the Crypto singleton is now referencing something else as you suggest?

**Comment by andyczerwonka** [comment]
I'm guessing you mean `AESCrypter`, not `AESSigner`.

**Comment by julienrf** [comment]
@andyczerwonka are you using Guice?

**Comment by andyczerwonka** [comment]
@julienrf yes, the default for Play as per the migration instructions.

**Comment by wsargent** [comment]
To your point that it used to work fine and there's a breaking change in Play: the stack trace doesn't help here, and I can't reproduce this.  I need a repeatable test case, otherwise I'm just guessing at what's going on.

**Comment by andyczerwonka** [comment]
@wsargent Thanks for the note. 

The point is that the `Crypto.encrypt` implementation depends on `application.conf`, and in my case it clearly can't find it. The dependency is not explicit, it is implicit in the implementation. In this specific case, an actor is triggering this call. The same method is called from controllers, and those work just fine. This actor is created in the injected application lifecycle, which is new in my code, replaced by a `GlobalSettings` implementation that used to work. I'm wondering if it's a classloader issue or something, where I'm reaching out the the `Crypto` singleton from a place that doesn't have access to the `application.conf`.

**Comment by wsargent** [comment]
@andyczerwonka The only thing I can think of is that you are running `Crypto.decryptAES` from outside of a running Play application.  

If that's the case, cry replacing the static `Crypto.decryptAES` with `new AESCrypterProvider(cryptoConfig)` and get the config from `new CryptoConfigParser(config)`

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/libs/crypto/Crypto.scala#L463

**Comment by wsargent** [comment]
Also see https://github.com/playframework/playframework/issues/5425

**Comment by andyczerwonka** [comment]
@wsargent Thanks, I'll give that a try. 

I must be doing something out of the norm by using the Akka scheduler from a class injects the ApplicationLifecycle that is eagerly bound from a Module. I would think that given its created from the lifecycle, Play is running. 

Nevertheless, I'll keep trying. I will create a sample if I can.

**Comment by andyczerwonka** [comment]
@wsargent I created a sample do demonstrate the issue I'm having. I took the standard `ApplicationTimer` module example as per your request and added only the code that demonstrates the exception that started this thread.

https://github.com/andyczerwonka/crypto-akka-exception/blob/master/app/services/ApplicationTimer.scala

The only change is to send an actor a message, and inside that actor I try and encrypt using the depracated `Crypto` API. You will notice that it throws the exception the first time through and works afterwards.

``` scala
def startActor() = {
    import scala.concurrent.duration.{FiniteDuration, Duration, DurationInt}
    val cryptoActor = akka.actorOf(Props[CryptoActor], "Crypto-Actor")
    akka.scheduler.schedule(0 seconds, 5 seconds, cryptoActor, "a messaage")
  }
```

``` scala
class CryptoActor extends Actor {
  override def receive = {
    case _ =>
      Logger.info("Attempting to encrypt a string")
      Crypto.encryptAES("This will throw an exception the first time through")
  }
}
```
