### ISSUE TITLE
Incorrect processing of URL query parameters in WS module 

### ISSUE THREAD

**Issue by stabenau** [playframework/playframework#5889]
Hello,

I posted earlier, but we ran again into this issue, so now I try with better subject and test case!

WS, when given URLs does not correctly process them. The query parameters are not correctly extracted, when they contain characters that are correctly escaped but influence the construction of the parameter string.

Example:

Retrieve a file called ===
(somewhat nonsensical filename but illustrates the problem)

Using this practical service to see what is requested
http://httpbin.org/get?file==== 

--- relevant part of the result ---
 "args": {
    "file": "==="
  }, 
--- ---

Now with a bit of code and WS (play 2.3.8), 

```
package controllers;

import play.libs.F.Promise;
import play.libs.ws.WS;
import play.libs.ws.WSRequestHolder;
import play.libs.ws.WSResponse;
import play.mvc.Controller;
import play.mvc.Result;

public class WSTest extends Controller {
	public static  Promise<Result> test() {
		WSRequestHolder holder = WS.url("http://httpbin.org/get?file=%3D%3D%3D");
		return holder.get().map( response -> { return ok( response.getBody()); } );
	}
}
```

The relevant part of the output is 

 "args": {
    "file": ""
  }, 

The parameter is not correctly escaped and transmitted. 

The Problem affects all versions of play (including 3.0). On construction of the Request (differently named in different Play versions) a java URI object is created with the url-String. The parameters are then extracted from URI.getQuery() - which does a URL decode before returning, littering the String (in this case with extra ===). Splitting on "=" then gives gibberish. Use of getRawQuery() should fix this.  

I hope this is more concise than last time :-)

**Comment by wsargent** [comment]
Play 2.3.8 uses AHC 1.8.15, which is known to have bugs in the URL processing.  

One way to work around it is to use [scala-uri](https://github.com/NET-A-PORTER/scala-uri) and

and create a custom WSClient with your own AsyncHttpClientConfig:

https://www.playframework.com/documentation/2.3.x/ScalaWS#Using-WSClient

Specifically, you want to disable AHC's URL handling by creating your own AsyncHttpClientConfig using `AsyncHttpClientConfig.Builder` and setting `useRawUrl`.

https://github.com/AsyncHttpClient/async-http-client/blob/1.8.x/src/main/java/com/ning/http/client/AsyncHttpClientConfig.java#L943

After which, any changes you make through scala-uri will be carried through directly.

**Comment by wsargent** [comment]
Also, the bug should not affect Play 3.0, as it isn't out yet.

**Comment by stabenau** [comment]
One last message and I promise I leave it at that:

In play 2.3.8 - play-java-ws/src/main/java/play/libs/ws/ning/NingWSRequestHolder.java

```
 public NingWSRequestHolder(NingWSClient client, String url) {
..
        URI reference = URI.create(url);

        this.url = url;
..
        if (reference.getQuery() != null) {
            this.setQueryString(reference.getQuery());
        }
..
   public WSRequestHolder setQueryString(String query) {
        String[] params = query.split("&");
        for (String param : params) {
            String[] keyValue = param.split("=");
            if (keyValue.length > 2) {

```
Clearly this will have problems with the URI.getQuery() return value being decoded.

in current master - play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java

```
   public AhcWSRequest(AhcWSClient client, String url, Materializer materializer) {
..
        URI reference = URI.create(url);

        this.url = url;
..
        if (reference.getQuery() != null) {
            this.setQueryString(reference.getQuery());
        }
    }
..
   @Override
    public WSRequest setQueryString(String query) {
        String[] params = query.split("&");
        for (String param : params) {
            String[] keyValue = param.split("=");
            if (keyValue.length > 2) {

```

Looks very familiar, same code, same problem.

I really just want to help out here, if you can't or don't want to fix it or I'm miss-reading the code, I'm totally fine with that. Play is awesome, we like it a lot, keep up the good work!!
