### ISSUE TITLE
How to get config in an object when  play.api.Play methods deprecated

### ISSUE THREAD

**Issue by viennv-septeni** [playframework/playframework#5915]
I can't inject an Environment or Configuration instance into object

**Comment by gmethvin** [comment]
If you absolutely need to use statics you can create your own `ApplicationLoader` and set some static variables for those things, or you can use Guice [static injection](https://github.com/google/guice/wiki/Injections#static-injections).

If you'd like to discuss more, please post on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).
