### ISSUE TITLE
[doc] Point people at the offline distribution by default

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#5918]
Right now, if you look at the root playframework.com page, it points them to the "download" button, but that is the online distribution, which downloads 400MB of jar files as dependencies, one dependency at a time.

This is understandably unpopular.

https://twitter.com/shekhargulati/status/711132035146907648

Now, there is a section in the manual which points people to the offline distribution... but people typically don't realize the problem until they're halfway through the download:

https://www.playframework.com/documentation/2.5.x/Installing#Downloading-Activator

We should have the bundled version as the default and provide the "minimal" version as a backup.

**Comment by nafg** [comment]
Or, it should use coursier, so it doesn't take nearly as long ;)

**Comment by julienrf** [comment]
IMHO, the bundles are useless (whether they are offline or online), we should just say that installing Play is a matter of adding the Play sbt plugin. That’s one line in the `project/plugins.sbt` file.

**Comment by schmitch** [comment]
Actually at the moment you can use Play via `project/plugins.sbt` or add atleast the following dependencies and configure it yourself:

-  "com.typesafe.play" %% "play" % playVersion
-  "com.typesafe.play" %% "play-netty-server" % playVersion or "com.typesafe.play" %% "play-akka-http-server-experimental" % playVersion 
-  "com.typesafe.play" %% "play-logback" % playVersion
