### ISSUE TITLE
FormUrlEncoded problem with UTF-8 in play 2.5

### ISSUE THREAD

**Issue by mohsenkashi** [playframework/playframework#5919]
In play 2.5 `FormUrlEncoded` (HTML form) can not decoded in server side, see [question in stack](http://stackoverflow.com/questions/36085014/play-framework-2-5-form-encoding).
Form in .scala.html:
 

```
@helper.form(action = routes.UserController.register(), 'class -> "form-horizontal", Symbol("accept-charset") ->"UTF-8")
```
Controller method:

```
@BodyParser.Of(BodyParser.FormUrlEncoded.class)//// TODO: 3/19/16 Farsi problem in form post
    public Result register() {
.
.
.
```

even changing `accept-charset` in form does not resolve problem for Unicode characters  but Latin chars comes okay with `ISO-8859-1` 

example of Farsi text for test is  "تهران" that converts to "ØªÙØ±Ø§Ù"

**Comment by gmethvin** [comment]
@mohsenkashi Looks like a bug. In the 2.4 -> 2.5 rewrite of Java body parsers we must have accidentally changed the default charset to ISO-8859-1. We should be able to get it working as before by switching that back.

**Comment by gmethvin** [comment]
Also play's implementation should be reading the `Accept-Charset` header and apparently it isn't.

**Comment by adis-me** [comment]
Aren't these body parses not tested? I just hit the same bug
