### ISSUE TITLE
Injectable default body parsers

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5930]
The body parsers in `BodyParsers.parse` should have their configuration and materializer injected rather than using the global application.

**Comment by schmitch** [comment]
Wouldn't that mean that we need to inject controllers, too?
I mean we could prolly write something like that in the BodyParsers trait:
``
   @Inject
  var configuration: Configuration = null
``

But this looks horrible...

**Comment by gmethvin** [comment]
My thought would be that you would inject `parse: DefaultBodyParsers` or similar, and we remove `BodyParsers` from the controller cake.

This change would probably go along with #5815. The `Action` helper takes advantage of the default body parsers as well.

**Comment by schmitch** [comment]
Eh yeah that's what I meant.. I wanted to write Action's but somehow I've written Controllers since I looked at that trait...

**Comment by gmethvin** [comment]
But yeah, this would basically mean every controller has to have something injected in. That's just one solution though. We could possibly get around it by having some pieces of state on the request.

**Comment by gmethvin** [comment]
Assuming we want to go the traditional DI route, one way of handling this is to have a `ControllerComponents` injected into every controller, e.g.

```scala
class FooController @Inject() (bar: Bar, baz: Baz, components: ControllerComponents)
    extends AbstractController(components) {
  // ...
}
```

The interesting thing here is that you could create your own components class with various things you need in all controllers, so you don't need to pass everything as constructor parameters.

Right now I think the default body parsers and action builder are the only thing you'd need. With this approach we could probably keep the syntax the same within your controllers too.

**Comment by wsargent** [comment]
Can we use an assisted inject to provide an automatic default?  I'm not clear exactly how they work, but they look interesting.  https://github.com/google/guice/wiki/AssistedInject

**Comment by schmitch** [comment]
Wouldn't that mean that upgrading from 2.5 to 2.6 will be huge? Doubt if that is enterprise friendly. 

Also I'm not sure if that is a great thing to inject components and add a `extends Something` I disliked that on the slick api and the I18nMessages.

**Comment by wsargent** [comment]
Yes, not having to inject i18nMessages would be huge.  It's a bit silly that it has to be manually injected for a form: https://www.theguardian.com/info/developer-blog/2015/dec/30/how-to-add-a-form-to-a-play-application

**Comment by schmitch** [comment]
Actually something like that would do inside a trait:
``
  private var environment: Environment = _

  @Inject
  def setEnvironment(environment: Environment): Unit = {
    this.environment = environment
  }

  def getEnvironment: Environment = environment
``

However that turns the Scala Code into Java Spagetti.

**Comment by gmethvin** [comment]
We could bundle all those components like `i18nMessages` together into `ControllerComponents` so there's only one thing to inject, at least.

We could possibly provide method injection as a migration path so existing Guice users don't need to change any code.

**Comment by gmethvin** [comment]
Also, Java actions and body parsers are already using DI. So it shouldn't require any Java API changes until we introduce a functional API for Java.

**Comment by nafg** [comment]
I hope this is being designed with vanilla Scala compile-time "DI" in mind

**Comment by gmethvin** [comment]
I've started experimenting with moving Actions/BodyParsers to this strategy here: https://github.com/gmethvin/playframework/blob/actions/framework/src/play/src/main/scala/play/api/mvc/Controller.scala

So, the `Action` helper in the controller can be fixed by adding a val, but anywhere else you use `Action` also needs to be injected, which makes things a bit ugly in other places, like in tests or using the SIRD. I haven't tried to migrate any of that yet.

**Comment by schmitch** [comment]
Actually this version looks good, the only thing which is aweful (but there is no other way) is the ultimative verboseness.
I mean from:
```
class AbcController extends Controller
```

To at least:
```
class AbcController @Inject()(components: ControllerComponents) extends AbstractController(components)
```

Is quite a heavy thing. (This also means that the code needs to change ridiculous in every project).
Still I've seen that we need to do that since testing a BodyParser which needs a Materializer is just bad.

Actually I like the design of the ControllerComponents. Couldn't we at least make 2.6 a version where:
```
protected def components: ControllerComponents
```

Will be:
```
protected def components: ControllerComponents = ControllerComponents.global
```

And change the deprecation notice to something like:
```
@deprecated("Controllers should be classes with their components injected prefer using AbstractController for Guice or override the components method when using constructor DI, see: http://migrationguideblbabla", "2.6.0")
```

**Comment by gmethvin** [comment]
@schmitch Yes something like that should be possible. We just need to make sure the deprecation notice is visible to the user. So it should be on some method or object they are actually using (like Action).

At this point I'm more concerned about how to make Action accessible outside of a controller, or provide a convenient pattern for getting it.

**Comment by julienrf** [comment]
Why isn't it possible to have the following? 

class MyController(action: ActionBuilder) {
  val foo = action(Ok)
}

**Comment by schmitch** [comment]
Actually if you would've make the `HttpErrorHandler` an Optional value and somehow add a way to load the typesafe config in a static object (which wouldn't be too bad if only the typesafe config is available via a statefull object) Then you could make the Action something like that:
```
Action(config: HttpConfiguration, httpErrorHandler: Option[HttpErrorHandler])).apply()(implicit mat: Materializer)
```
So you could create a static Action for SIRD:
```
 SIRDAction = Action(GlobalConfig, None))
```

**Comment by gmethvin** [comment]
@julienrf It is possible, though you need to inject a specific kind of action builder (you would probably want to inject `DefaultActionBuilder` or something). This is more or less what I was trying to do, except I also wanted to keep the idiomatic `Action` syntax for default actions. Maybe this isn't as big of a deal as I think it is, since many people are using custom action builders anyway.

Also, there are other pieces of state that need to be injected into the controller, like the i18n stuff, so I thought it made sense to encapsulate that in a `ControllerComponents`. That way we can add components over time without requiring major code changes.

**Comment by julienrf** [comment]
@gmethvin I see. We could go with the following, what do you think?

~~~ scala
class MyController(val controllerConfig: ControllerConfig) extends Controller {
  val foo = action(Ok)
}
~~~

Where the `Controller` trait would have an abtsract `controllerConfig` member that would be used by the `Action` action builder, the body parsers, etc.

In order to provide a smooth migration path we would probably have to introduce another trait than `Controller`, which is already widely used:

~~~ scala
trait ConfigurableController {
  def controllerConfig: ControllerConfig

  lazy val action: ActionBuilder = … // (something that uses controllerConfig)
}
~~~

**Comment by schmitch** [comment]
@gmethvin with https://github.com/playframework/playframework/pull/6178 merged is this still possible "easily"?

**Comment by marcospereira** [comment]
@gmethvin can we close this?

**Comment by gmethvin** [comment]
Yes, this is implemented as `PlayBodyParsers`/`PlayBodyParsersImpl`.
