### ISSUE TITLE
Client-side caching for WS

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5931]
See https://github.com/playframework/play-ws-cache

**Comment by marcospereira** [comment]
@wsargent can we close this?

**Comment by wsargent** [comment]
So it's ALMOST there. If you look at https://github.com/playframework/play-ws/blob/master/play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSClient.scala#L101 then the apply method will let you take a `javax.cache.Cache[EffectiveURIKey, ResponseEntry]`:

```
  def apply(config: AhcWSClientConfig = AhcWSClientConfigFactory.forConfig(), cache: Option[Cache[EffectiveURIKey, ResponseEntry]] = None)(implicit materializer: Materializer): StandaloneAhcWSClient = {
```

However, the mapping from JCache to EhCache / play.api.Cache doesn't seem to exist -- the 3.0 version of ehcache has JCache, but Play WS uses EhCache 2.8.

So if we can get a `javax.cache.Cache` compatible layer in, then we can add a provider which takes in a cache and have that be seamless to the end user.

**Comment by edouardKaiser** [comment]
Is there a way today to have a `WSClient` managed as a part of Play's lifecycle with caching enabled? (the user would have to provide a `javax.cache.Cache` implementation).

**Comment by marcospereira** [comment]
See #7255.
