### ISSUE TITLE
Play should handle sigterm

### ISSUE THREAD

**Issue by meddulla** [playframework/playframework#5933]
When stopping a play app using the systemd init system, systemd sends a SIGTERM to the process, the jvm then exits with the 143 code which, since it's nonzero, is treated as a failure by systemd. 

I think play should handle this itself and exit cleanly. As it is, we have to add SuccessExitStatus=143 to the service file (for a similar discussion see https://tickets.puppetlabs.com/si/jira.issueviews:issue-html/SERVER-70/SERVER-70.html).

Anyway, thanks for all the hard work :)

**Comment by wsargent** [comment]
Play exits with code 143 because the JVM is a unix process, and the standard behavior of a process killed with SIGTERM is to exit with code 143.   

You should be using "ExecStart=-" to disable that behavior: 

> If the absolute filename is prefixed with "-", an exit code of the command normally considered a failure (i.e. non-zero exit status or abnormal exit due to signal) is ignored and considered success.

http://0pointer.de/public/systemd-man/systemd.service.html

Is this something that you're attaching to the deploy script of Play?  That's actually handled through sbt-native-packager normally: http://www.scala-sbt.org/sbt-native-packager/archetypes/java_server/index.html#customize

**Comment by baloo** [comment]
From POSIX (http://pubs.opengroup.org/onlinepubs/9699919799/utilities/wait.html#tag_20_153_14): 
```
If the process terminated abnormally due to the receipt of a signal, the exit status shall be greater than 128 and shall be distinct from the exit status generated by other signals, but the exact value is unspecified.
```

Although the behavior is undefined, on linux (and other various operating systems) it happens to be 128 + n, n being the signal number. 15(SIGTERM) + 128 = 143.

**Comment by meddulla** [comment]
I'm already using sbt-native-packager (javaserverpackage) and the issue is exactly that the service file needs to be customised so that a play framework app is handled by systemd correctly, either through

- ExecStart=- or
- SuccessExitStatus=143

I chose the later because from the description of ExecStart=- it seemed that _all_ non-zero codes would be considered a success which is not ideal. Using SuccessExitStatus it's scoped to this single exit code. Or am I missing something?

The service file _needs_ to be customised because the app doesn't handle sigterm correctly (or signals the init system that the exit was an error) which is what both systemd/upstart will send when calling 

> service app stop

Since most deployments will be in linux I think this would be useful for most users. From https://www.python.org/dev/peps/pep-3143/#correct-daemon-behaviour:

> a program should perform the following steps to become a Unix daemon process:
> [..]
> Correctly handle the following circumstances:

> Started by System V init process.
> Daemon termination by SIGTERM signal.
> Children generate SIGCLD signal.

**Comment by wsargent** [comment]
> Or am I missing something?

@meddulla I'm not getting why you want this attached to Play specifically rather than to sbt-native-packager.

**Comment by wsargent** [comment]
Closing as sbt-native-packager will handle this.
