### ISSUE TITLE
use log4j2 with play 2.5.0 and Java

### ISSUE THREAD

**Issue by duluosheng** [playframework/playframework#5934]
I use play 2.5.0 and java to create a restful api server.
But I get a trouble when I use log4j2 to log.
I run with "-Dlog4j.configurationFile=conf/log4j2.xml" and set ".disablePlugins(PlayLogback)", but it doesn't work.
I just get "No play.logger.configurator found: logging must be configured entirely by the application."

**Comment by mkurz** [comment]
Please ask question on the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/play-framework).

For you particular problem please read:
https://www.playframework.com/documentation/2.5.x/Highlights25#Support-for-other-logging-frameworks
https://www.playframework.com/documentation/2.5.x/Migration25#Change-to-Logback-configuration
https://www.playframework.com/documentation/2.5.x/SettingsLogger#Using-a-Custom-Logging-Framework
