### ISSUE TITLE
Doc for request timeout setting.

### ISSUE THREAD

**Issue by djx314** [playframework/playframework#5937]
### Play Version
2.5

### API
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Ubuntu 15.10
Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Azul Zing

### Issue
About the issue https://github.com/playframework/playframework/issues/5751 and play does not provide a quick fix version. My file upload form always get a timeout response. So I find the doc in playframeowrk.com but I can't find the doc to set the request timeout. Though I knew it's a akka-http's response, but I think it's really need to add the request timeout config doc to play because I have many built-in system to waste a long time in some requests.

### Expected Behavior
Upload files successfully.

### Actual Behavior
```
The server was not able to produce a timely response to your request.
Please try again in a short while!
```

###Additional Comments
And I think https://github.com/playframework/playframework/issues/5751 is really a worst bug because upgrade to 2.5.x need to change many code and after upgraded I can't upload files. The whole website can't work. So I suggest that play can release a quick fix version.

**Comment by schmitch** [comment]
Actually there will soon be a 2.5.1 please be patient.

**Comment by djx314** [comment]
Sorry for the complain.
But my main issue is not file upload. Because I can fix it by copy the code in the pull request.
My main issue is is there any doc in play so that I can config the akka-http that I can control the request timeout? Because some of my website has the requirement(some request has to do a lot of work and I don't care the time in these work).

**Comment by marcospereira** [comment]
@djx314 I think you can use `akka.http.server.request-timeout` configuration, but I'm not sure about. Also, keep in mind that the akka-http support still experimental.

**Comment by marcospereira** [comment]
Moreover, I will close this issue since the file upload issue is already fixed.

@djx314 feel free to continue this discussion using the [mailing list](https://groups.google.com/forum/#!forum/play-framework).
