### ISSUE TITLE
JsObject.apply should support varargs

### ISSUE THREAD

**Issue by kubukoz** [playframework/playframework#5947]
in [JsValue.scala:151](https://github.com/playframework/playframework/blob/master/framework/src/play-json/src/main/scala/play/api/libs/json/JsValue.scala#L151)

`JsObject.apply` only supports a `Seq[(String, JsValue)]`, and the class's constructor takes a Map. I think it would be a good idea to add a `(String, JsValue)*` overload to the `apply` method, unless it's somehow impossible.

**Comment by gmethvin** [comment]
Well, we do have `Json.obj` which pretty much does what you're looking for, along with some implicit conversions to automatically convert the values to `JsValue`.

**Comment by kubukoz** [comment]
Works as expected, thanks! Maybe it would be a good idea to document it somewhere in `JsObject`'s doc?
