### ISSUE TITLE
Strange behavior on url matching

### ISSUE THREAD

**Issue by SeriousJul** [playframework/playframework#5970]
### Play Version (2.5.x / 2.4 / ?)

API Java & Scala
### Operating System (Windows 7 / Debian)

Windows 7 professional SP1 x64 
It also occurs on ours productions environments running in docker containers. Those containers are build from java:latest : https://hub.docker.com/_/java/
`root@ff51df340509:/# uname -r`
`3.10.0-327.el7.x86_64`
### JDK (Oracle 1.8.0_XX)

`java version "1.8.0_65"`
`Java(TM) SE Runtime Environment (build 1.8.0_65-b17)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)`
### Expected Behavior

Expected
1. GET http://localhost:9000/count => HTTP 200
2. GET http://localhost:9000/azerty => HTTP 404
3. GET http://localhost:9000//azerty => HTTP 404
4. GET http://localhost:9000//azerty/count => HTTP 404
### Actual Behavior
1. GET http://localhost:9000/count => HTTP 200
2. GET http://localhost:9000/azerty => HTTP 404
3. GET http://localhost:9000//azerty => HTTP 404
4. GET http://localhost:9000//azerty/count => HTTP 200

For the last point, I expect to have an HTTP 404 response, but somehow play managed to bind the url.
### Reproducible Test Case

Starting from a brand new project
1. activator new bug-play play-java 
2. cd bug-play
3. activator run

**Comment by cchantep** [comment]
Hi,

I don't see the mentioned difference using Play 2.5.10+ : `//foo` returns 404 and also `//foo/bar` .

Best regards

**Comment by schmitch** [comment]
I guess https://github.com/playframework/playframework/pull/6839 also fixed that, one (I Guess)
