### ISSUE TITLE
POST/PUT with empty body hangs forever

### ISSUE THREAD

**Issue by chrisghost** [playframework/playframework#5972]
### Expected Behavior
1. POST/PUT on any URL with an empty body
2. Get the reply from server every time

### Actual Behavior
I launch an apache benchmark with : ```ab -n 200  -m POST localhost:9001/hi```

This is the logs (I included what seems to be the logs of a replying query first, the last one to correctly reply, and then the one that hangs forever) ([full logs](http://pastebin.com/Ur3DuPGb) )

```
[trace] p.c.s.n.PlayRequestHandler - Http request received by netty: com.typesafe.netty.http.EmptyHttpRequest(DefaultHttpRequest(decodeResult: success, version: HTTP/1.0)
POST /hi HTTP/1.0
Host: localhost:9001
User-Agent: ApacheBench/2.3
Accept: */*)
[trace] p.a.m.BodyParsers - Parsing AnyContent as raw
[trace] p.c.s.n.PlayRequestHandler - channelReadComplete: ctx = io.netty.channel.DefaultChannelHandlerContext@58123ccc
[trace] p.a.mvc.Action - Invoking action with request: POST /hi
[trace] p.c.s.n.PlayRequestHandler - channelRead: ctx = io.netty.channel.DefaultChannelHandlerContext@255fffed, msg = com.typesafe.netty.http.EmptyHttpRequest(DefaultHttpRequest(decodeResult: success, version: HTTP/1.0)
POST /hi HTTP/1.0
Host: localhost:9001
User-Agent: ApacheBench/2.3
Accept: */*)
[trace] p.c.s.n.PlayRequestHandler - Http request received by netty: com.typesafe.netty.http.EmptyHttpRequest(DefaultHttpRequest(decodeResult: success, version: HTTP/1.0)
POST /hi HTTP/1.0
Host: localhost:9001
User-Agent: ApacheBench/2.3
Accept: */*)
[trace] p.a.m.BodyParsers - Parsing AnyContent as raw
[trace] p.c.s.n.PlayRequestHandler - channelReadComplete: ctx = io.netty.channel.DefaultChannelHandlerContext@255fffed

```
### Reproducible Test Case
[https://github.com/chrisghost/play25-emptybody](https://github.com/chrisghost/play25-emptybody)

Note: I have this behavior on every request with an application from work (which is way more complicated than the test case).
I wasn't able to make the error reproduce after the same number of queries, it's different each time and seems to occur more rapidly after each run of apache-benchmark on the same application instance

**Comment by marcospereira** [comment]
Is this related to #5975? From your logs, is possible to see that you are running the app in dev mode:

```
[debug] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] play.api.Play - Application started (Dev)
```

**Comment by chrisghost** [comment]
@marcospereira Yes, I cannot reproduce the issue using a production build
