### ISSUE TITLE
Idiomatic Config usage

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5979]
Now that we are using `reference.conf` we should change our config APIs to no longer return `Option` by default. We basically can use the `PlayConfig` class in Scala, and perhaps just use a raw `Config` object in Java since it is already a Java API.

**Comment by benmccann** [comment]
+1 to using underlying library directly in Java

**Comment by gmethvin** [comment]
For Scala, I think we can deprecate most of the methods on `Configuration` and add `get[T: ConfigLoader]` from PlayConfig. I'm not actually sure why there are methods that return Java types. It seems reasonable that if you want Java types you would drop down to the underlying `Config`.

**Comment by studiodev** [comment]
I leaved PlayConfig since I discovered libraries like https://github.com/iheartradio/ficus, that provides an `.as[T]` methods on Typesafe Config, which works for primitive types and case class (macro based).

What about providing something like that in Play (at least for the scala api) ?

**Comment by gmethvin** [comment]
The [PlayConfig](https://github.com/playframework/playframework/blob/2.5.1/framework/src/play/src/main/scala/play/api/Configuration.scala#L910) class already has a mechanism for defining `ConfigLoader`s for specific types and getting configuration using `config.get[T]("foo")`. I think that is similar to what ficus is doing. That is the direction I'm suggesting in this issue.

**Comment by gmethvin** [comment]
This was fixed in #6001. If anyone has additional, more specific feature requests they can open a new issue.
