### ISSUE TITLE
WSClient Multipart Upload broken in async-http-client 2.0.0-MS-16 

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#5988]
### Play Version (2.5.x / etc)
2.5.1

Uploading files in WSClient as Multipart/Form-Data is broken in the bundled async-http-client 2.0.0-MS-16 
I advise to change to MS-17 or later, where this bug is fixed. 
Bug is tracked here: https://github.com/AsyncHttpClient/async-http-client/issues/1123

**Comment by schmitch** [comment]
Actually as a Fix you could try out the new multipart/form-data of play which doesn't depend on the async-http-client.

**Comment by domdorn** [comment]
@schmitch as far as I understood, the changes mentioned in 
https://www.playframework.com/documentation/2.5.x/ScalaFileUpload
refer to how file uploads are handled in the controller, not how to upload files to a (remote) server using the WSClient... are you referring to this or something else?

https://www.playframework.com/documentation/2.5.x/ScalaWS#Submitting-multipart/form-data is affected by this bug as well.

**Comment by schmitch** [comment]
@domdorn it's not affected by this bug, the docs are just wrong.
It doesn't take a `Seq[org.asynchttpclient.request.body.multipart.Part]`. And it doesn't use the multipart formatter of async-http-client.

Actually I push a PR with the fixed docs.

**Comment by domdorn** [comment]
Ah, very nice to know, thank you!

**Comment by mkurz** [comment]
So probably it would be good to upgrade to latest `async-http-client` (which is `2.0-RC19` currently) in the `2.5.x` branch as well?

**Comment by domdorn** [comment]
correct

**Comment by gmethvin** [comment]
I think we'll release 2.5.2 in the not too distant future, so we can update to the latest AHC just prior to the release.

**Comment by mkurz** [comment]
I assigned the issue the `2.5.2` milestone so we don't forget about it.
