### ISSUE TITLE
Custom filter is incompatible with POST request

### ISSUE THREAD

**Issue by gaydenko** [playframework/playframework#5990]
### Operating System
```
$ uname -a
Linux user 4.4.5-1-zen #1 ZEN SMP PREEMPT Thu Mar 10 12:43:55 UTC 2016 x86_64 GNU/Linux
```

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
```
$ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

### Library Dependencies
Nothing

### Expected Behavior
1. Use custom filters
2. Use custom request handler
3. POST request must not hang

### Actual Behavior
Post requests hang from time to time. The simplest way is to run
`$ ab -c 10 -n 10000 -m GET http://localhost:9000/`
to be sure we are on the horse, and then
`$ ab -c 10 -n 10000 -m POST http://localhost:9000/`
to get instant hang.
In fact it is possible to get the hang with
`$ curl -X POST http://localhost:9000/`
But it can get few dozens of repeated attempts.

### Reproducible Test Case
https://github.com/gaydenko/playpost
Just run the project and use `ab` as described above.
You can see, a filter in use just passes execution to `next`.

**Comment by gaydenko** [comment]
To be sure a filter is the issue cause, just replace `val filters = Nil` in `MyFilters` definition and start `ab -m POST ...` again.

**Comment by gmethvin** [comment]
This was fixed by #5982. I just tested your project against 2.5.x and it doesn't seem to have the problem.

**Comment by gaydenko** [comment]
@gmethvin , great, thanks! Can you, please, roughly estimate the date the fix will be released (that is 2.5.2, I guess)?

**Comment by francisdb** [comment]
We are seeing similar issues where eg the CORS filter combined with a GET using `Action(parse.raw)`  causes requests sometimes to not arrive at the controller.
@gmethvin do you think this is related or should I create a new issue?

**Comment by gmethvin** [comment]
@francisdb It's likely the same issue. If you want you can publish a local snapshot off the 2.5.x branch and see if it's fixed.

**Comment by francisdb** [comment]
@gmethvin I can confirm my issue is also fixed in `2.5.2-SNAPSHOT`
Serious bug requiring release if you ask me

**Comment by gmethvin** [comment]
@francisdb We are planning a release this week.

**Comment by francisdb** [comment]
Great!
