### ISSUE TITLE
[2.5.1] Request body not available in `WsSignatureCalculator`

### ISSUE THREAD

**Issue by timohirt** [playframework/playframework#5996]
### Play Version (2.5.x / etc)

Play 2.5.1
### API (Scala / Java / Neither / Both)

Scala
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Ubuntu 14.04
Arch Linux Kernel 4.4.5-1
### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)
### Expected Behavior

First let me give you some context: In order to secure our services we use HMAC signatures. So, when a client sends a request it calculates a signature based on some header fields and the body. It set the `Authorization` header to the signature and some meta data. On der server side, we implemented an `Action` which also calculates the signature and then verifies it is the same as the one in the request provided by the client.

On the server side everything works fine. For clients we implemented a `WsSignatureCalculator` which can be added to a `WSRequest` like this:

```
wsClient
        .url("https:/localhost:9000/upload-some-file")
        .sign(hmacSignatureCalculator)
        .post(file)
```

And I also tried:

```
wsClient
        .url("https:/localhost:9000/upload-some-file")
        .withBody(FileBody(file))
        .sign(hmacSignatureCalculator)
        .execute("POST")
```

Please describe the expected behavior of the issue, starting from the first action.
1. During `AhcWSRequest.buildRequest` the  `hmacSignatureCalculator` is called with a `Request` which provides the body of the actual request.
2. The SHA1 hash of the body is calculated and used to calculate the HMAC signature.
3. The server accepts the request because the signature provided by the client is valid.
### Actual Behavior

The body of the `Request` provided to  `hmacSignatureCalculator` is always`null`. The same is true for `Request.getFile` and `Request.getBodyGenerator`.
1. The body of the `Request` provided to `hmacSignatureCalculator` is not set.
2. The SHA1 hash cannot be calculated.
3. The server calculates the SHA1 and thus a different HMAC signature and rejects the request.

With the underlying `AsyncHttpClient` the `Request.getBody` is not `null`. 

```
val client: AsyncHttpClient = wsClient.underlying
val request = client
  .preparePost(urls.uploadOrder(processId).toString)
  .setSignatureCalculator(hmacSignatureCalculator)
  .setBody(file)
  .build()

val result = Promise[AhcWSResponse]()
client.executeRequest(request, new AsyncCompletionHandler[Response]() {
  override def onCompleted(response: Response) = {
    result.success(AhcWSResponse(response))
    response
  }

  override def onThrowable(t: Throwable) = {
    result.failure(t)
  }
})
val responseFuture = result.future
```

**Comment by wsargent** [comment]
The problem with verifying this is that the example created a custom `WsSignatureCalculator` but doesn't include the code.  @timohirt do you have a small github project you could provide as the example?

**Comment by wsargent** [comment]
Moved to https://github.com/playframework/play-ws/issues/154
