### ISSUE TITLE
[2.5.x] LinkageError when using AspectJ as JavaAgent with sbt stage generated bin script

### ISSUE THREAD

**Issue by el-dom** [playframework/playframework#5997]
### Play Version (2.5.x / etc)
`>=2.5.0`
Not reproducible with 2.4.x

### API (Scala / Java / Neither / Both)
Scala 2.11.8

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Ubuntu 14.04 (Production Environment)
Linux W540 4.4.6-1-MANJARO #1 SMP PREEMPT Sat Mar 19 06:00:37 CET 2016 x86_64 GNU/Linux (Development Environment)

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

### Library Dependencies
"org.aspectj" % "aspectjweaver" % "1.8.9"

### Expected Behavior
We're trying to use aspectjweaver as a javaagent (required for [Kamon](http://kamon.io/))
Expected behaviour for the start script would be proper application startup

### Actual Behavior
Generating a start script with ```sbt stage``` and starting the application with 
```env JAVA_OPTS="-javaagent:./target/universal/stage/lib/org.aspectj.aspectjweaver-1.8.9.jar -verbose:class" target/universal/stage/bin/linkageerrortest```
results in a crash on startup

```
Exception in thread "main" [Loaded java.lang.Throwable$PrintStreamOrWriter from /usr/lib/jvm/java-8-jdk/jre/lib/rt.jar]
[Loaded java.lang.Throwable$WrappedPrintStream from /usr/lib/jvm/java-8-jdk/jre/lib/rt.jar]
java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "org/slf4j/LoggerFactory"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:85)
	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:56)
	at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$applicationModule$1.apply(GuiceApplicationBuilder.scala:102)
	at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$applicationModule$1.apply(GuiceApplicationBuilder.scala:102)
	at scala.Option.foreach(Option.scala:257)
	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:101)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:47)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```
The start call attempts to load org.slf4j.LoggerFactory which got already loaded by the aspectjweaver jar and dies immediately.
This can only be reproduced with play 2.5.x. We did the same with play 2.4.x and it was working fine.

### Reproducible Test Case
Minimal play application for reproduction can be found at
https://github.com/el-dom/play_linkage_error

After cloning, reproduce with 
1.`sbt stage`
2a. `env JAVA_OPTS="-javaagent:./target/universal/stage/lib/org.aspectj.aspectjweaver-1.8.9.jar -verbose:class" target/universal/stage/bin/linkageerrortest` (will crash with LinkageError)
2b. alternatively use `target/universal/stage/bin/linkageerrortest -J-javaagent:target/universal/stage/lib/org.aspectj.aspectjweaver-1.8.9.jar` (will crash with LinkageError)
3. The depcreated `sbt start` command yields the same result

**Comment by wsargent** [comment]
Can you try disabling the PlayLogback plugin?

https://www.playframework.com/documentation/2.5.x/SettingsLogger#using-a-custom-logging-framework

**Comment by el-dom** [comment]
That's indeed working. Thank you very much!

**Comment by markus1189** [comment]
Curiously, AFAIK play 2.4.x also used `logback` right? I wonder whether there is any way to fix the incompatibility that seems to have been introduced in play 2.5.x?

**Comment by wsargent** [comment]
@markus1189 I don't know what you mean.

**Comment by wsargent** [comment]
@markus1189 2.5.x isn't a minor release.  The release scheme is <epoch>.<major>.<minor> -- 2.5.x is binary incompatible by design.

**Comment by markus1189** [comment]
@wsargent I was just wondering if there is a way to use play 2.5.x and the logback plugin together with e.g. `aspectjweaver` without running in the class loader issue reported above, as was the case with play 2.4.x.  We would prefer not to switch away from logback.

**Comment by wsargent** [comment]
I don't know what's going on with AspectJ, but you can install Logback yourself at the application level, using the LoggerConfigurator.  There's an example project here (using log4j2): https://github.com/wsargent/play-2.5-log4j2

**Comment by an-tex** [comment]
@markus1189 did you find a solution? I've tried @wsargent approach and ended up copying the whole play.api.libs.logback.LogbackLoggerConfigurator class into my module. This works but is pretty silly...

**Comment by markus1189** [comment]
Hi @an-tex.  We are working on a solution for our project, but until now no
luck.  Are you using aspectj together with your solution for the
LogbackLoggerConfigurator?  If your approach works I would be curious to
see how you did that ;)

**Comment by an-tex** [comment]
Hi @markus1189, unfortunately it didn't work after all. But I had to disable aspectj for now anyway due to https://github.com/kamon-io/Kamon/issues/340 :/

**Comment by dspasojevic** [comment]
@markus1189 I am in the same boat. I could not get the provided `LogbackLoggerConfigurator` to work with AspectJ. Interestingly, disabling the provided `LogbackLoggerConfigurator` and enabling a near identical copy of it (as @wsargent suggested) does work.

**Comment by markus1189** [comment]
@dspasojevic Interesting, what did you change excactly to make it work?

**Comment by dspasojevic** [comment]
@markus1189 Changing nothing in the Configurator implementation, but duplicating it and enabling the duplicate seems to be enough: https://github.com/dspasojevic/play_linkage_error/commit/efe5946b8d722ffa574cb3cddfc9e4767ad40443

**Comment by meloniasty** [comment]
hi, @dspasojevic, does your solution works? I mean did you succesfully use logback? I tested https://github.com/dspasojevic/play_linkage_error/commit/efe5946b8d722ffa574cb3cddfc9e4767ad40443 and it seems the same error.

**Comment by el-dom** [comment]
@meloniasty That didn't work here either. Ultimately, we had to wrap a Future around the `LoggerContext` loading.
```val ctx = Await.result(Future.successful(LoggerFactory.getILoggerFactory.asInstanceOf[LoggerContext]), 10 milliseconds)``` to force it into another classloader. We're very unhappy with this hack but nothing else worked.

**Comment by dpsoft** [comment]
I've avoided this weird error setting -Dorg.aspectj.tracing.factory=default, this force AspectJ to use it's built-in trace infrastructure that logs to stderr instead of java.util.logging/commons.logging. But I'm not really sure about the origin of the problem. I need investigate a little more

**Comment by mirkof** [comment]
@dpsoft addind `-Dorg.aspectj.tracing.factory=default` solved the problem. Thank you :grinning:

**Comment by GMadorell** [comment]
@dpsoft This also solved the problem for me. Thanks!

I'm still left wondering if this has any downside, though. Did you have any problems with this approach?

**Comment by kuzkdmy** [comment]
I just got the same issue.
And it was resolved with a small update, almost all mentioned upper, but part as one solution, part as other

application.conf
`
logger.configurator= "play.api.libs.logback.LogbackLoggerConfigurator"
`

build.sbt
`
lazy val sspWeb = project
  .in(file("ssp-web"))
  .disablePlugins(PlayLogback)
`

javaOptions from dockerized settings
`-Dorg.aspectj.tracing.factory=default`

Thanks.
