### ISSUE TITLE
[2.5.x] PlayConfig is too restrictive

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6020]
There are cases where `SSLConfigParser(config: Configuration)` should be called, because different SSL clients need different certificates and it's useful to parse them a different configuration:

```
letsencrypt.ws.ssl {
   trustManagers = {
      ...
   }
}
```

Because SSLConfigParser now uses `PlayConfig` and `PlayConfig` is private[play], that means application code can't instantiate a custom parser without moving it under the play namespace.

**Comment by gmethvin** [comment]
@wsargent In 2.6 this will be fixed by #6001.

For 2.5, I think we should just make `SSLConfigParser`'s constructor accept `Configuration`. We could even keep the one that accepts `PlayConfig` if you wanted to ensure full binary compatibility.
