### ISSUE TITLE
java.net.MalformedURLException: QueryString parameter should not have more than 2 = per part

### ISSUE THREAD

**Issue by ltm4545** [playframework/playframework#6024]
hi，

When i try to execute a query to get the response from other website. i used 

String url = "https://query.yahooapis.com/v1/public/yql?q=select%20item.condition%20from%20weather.forecast%20where%20woeid%wo%3D%202487889&format=xml&env=store%3A%2Fdatatables.org%2Falltableswithkeys";

WSRequestHolder holder = WS.url(url);

But i got a error java.net.MalformedURLException: QueryString parameter should not have more than 2 = per part.

I think i should use method "setqueryparameter()" . But i can't find the solution.
Some one has idea to solve this issue?

**Comment by gmethvin** [comment]
It would probably be best to discuss on the [mailing list](https://groups.google.com/forum/#!forum/play-framework) before submitting an issue. There it would also help to provide the version of play you are using and the stacktrace of the error.
