### ISSUE TITLE
Use Google’s GSON to replace Jackson JSON or as 2nd option

### ISSUE THREAD

**Issue by almothafar** [playframework/playframework#6026]
So simple as suggestion for improvements to use GSON instead of Current Jackson? I'm not sure if there is a base for decision to use Jackson at first place but I would suggest GSON to replace or as an option behind play's wrapper.

I know that I can add GSON to sbt, but I mean here the json things in requests and so on.

http://blog.takipi.com/the-ultimate-json-library-json-simple-vs-gson-vs-jackson-vs-json/

http://www.doublecloud.org/2015/03/gson-vs-jackson-which-to-use-for-json-in-java/

Actually I got to suggest this because I just go causes that Gson would better if used instead of Jackson.

**Comment by cchantep** [comment]
Hi, as it been discussed on the MailingList as suggested in the guide lines if this issue tracker. Otherwise that's the first place for this suggestion (and this ticket should be closed until discussion is ok). Best regards.
