### ISSUE TITLE
[doc] Add example of simple standalone WSClient 

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6040]
### Play Version (2.5.x / etc)

2.5.x
### API (Scala / Java / Neither / Both)

Both
### Actual Behavior

Add examples of simple, no-frills WSClient outside the browser usage to 

https://www.playframework.com/documentation/2.5.x/ScalaWS and https://www.playframework.com/documentation/2.5.x/JavaWS

i.e.

```
import play.api.libs.ws.ahc.AhcWSClient
import akka.stream.ActorMaterializer
import akka.actor.ActorSystem

implicit val system = ActorSystem()
implicit val materializer = ActorMaterializer()
val ws = AhcWSClient()

val req = ws.url("http://example.com").get().map{
  resp => resp.body
}(system.dispatcher)

// after all futures completed...
ws.close()
```

**Comment by Jacke** [comment]
Thanks for example

**Comment by wsargent** [comment]
This is super done thanks to https://github.com/playframework/play-ws

**Comment by tenstriker** [comment]
how to accept any ssl certificate ? I can't seem to find any configuration for that
