### ISSUE TITLE
DefaultJPAApi withTransaction is hiding the root exceptions when entityManagerContext.pop(true) fails in finally block

### ISSUE THREAD

**Issue by rajendrag** [playframework/playframework#6041]
If there is an exception (in my case exception throws few times because of Guice static injection) while creating EntityManager and it won't be pushed into the entityManagerContext and yet the finally block trying to pop it from context and it is throwing that the em is not there to pop. But the root cause is actually something else.

Play Version (2.5.1)
API(Java)
Operating System (MacOS 10.11.4)
JDK (Oracle 1.8.0_65)
### Library Dependencies

JPA, Hibernate
### Expected Behavior

Should log and throw the actual exception.
### Actual Behavior

Throwing an exception with message "Tried to remove the EntityManager, but none was set"
### Reproducible Test Case

In cases where the entitymanager can not be created, like a custom connection provider fails with null pointer etc

**Comment by mkurz** [comment]
I want to change some things on the JPA API for the 2.6 release, so maybe I can tackle this here too.

**Comment by stonehorsecd** [comment]
How to resolve this issue now ?

**Comment by zarinfam** [comment]
I have this problem too, how can i fix it?

**Comment by rajendrag** [comment]
The workaround, if you know where the actual exception is (while debugging), fix that problem, so that you won't get into this case.

**Comment by mkurz** [comment]
I did address this in #6777 - When no entity manager gets set I won't even try to remove it in the `finally` (see `if(ems.contains(entityManager)) {...}`)
