### ISSUE TITLE
Add Java API for LoggerConfigurator

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6045]
### Play Version (2.5.x / etc)

2.6.x
### API (Scala / Java / Neither / Both)

Java
### Expected Behavior

There should be a Java API equivalent of `play.api.LoggerConfigurator` -- currently, you have to call `play.api.LoggerConfigurator$.MODULE$.apply(..)` if you're going to call the method from Java.

Documentation should be in 2.5.x and is filed as https://github.com/playframework/playframework/issues/6045

**Comment by driverpt** [comment]
What do you think of creating a LoggerConfiguratorBuilder using Builder Pattern for a Java API ?

**Comment by mkurz** [comment]
@wsargent if this could make it in before 2.6 final that would be great :smile:
