### ISSUE TITLE
[2.5.x][doc] Add note to Migration25 / SettingsLogger on calling LoggerConfigurator from Java

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6046]
We should add a note in the docs at https://www.playframework.com/documentation/2.5.x/Migration25#Change-to-Logback-configuration and to SettingsLogger.md that you have to call play.api.LoggerConfigurator$.MODULE$.apply(..) if you're going to call the method from Java.

Implementation of Java API is https://github.com/playframework/playframework/issues/6045 for 2.6.x

**Comment by kyouz** [comment]
Hi,
Look what they have for you, I guess it's worth reading, more info here <http://balance.ioutax.com/e3yqkmv>

Yours truly, amsdta_09@yahoo.com

**Comment by marcospereira** [comment]
Closing since there is now a Java API for LoggerConfigurator.
