### ISSUE TITLE
[doc] Update documentation on the Remote Call IntelliJ plugin

### ISSUE THREAD

**Issue by mmizutani** [playframework/playframework#6054]
The latest documentation [mentions the installation of the Remote Call IntelliJ plugin](https://playframework.com/documentation/2.5.x/IDE#Navigate-from-an-error-page-to-the-source-code), but the [Remote Call IntelliJ plugin](https://github.com/Zolotov/RemoteCall) is deprecated and taken over by the [IntelliJ Platform REST API](http://develar.org/idea-rest-api/#api-Platform-file) as described on the readme of the RemoteCall IntelliJ Plugin repository.

**Comment by cchantep** [comment]
Hi, as [indicated in the guide lines](https://github.com/playframework/playframework/blob/master/.github/ISSUE_TEMPLATE.md), please use the [MailingList](https://groups.google.com/forum/#!forum/play-framework) to ask question. Best regards.

**Comment by nafg** [comment]
How is this a question? He's right, the documentation is outdated

**Comment by wsargent** [comment]
Related to https://github.com/playframework/playframework/issues/5270

**Comment by wsargent** [comment]
Will address in #5270, treating this as dup
