### ISSUE TITLE
Cookies still use global state

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#6056]
The `Session` and `Flash` cookie bakers still use global state. We should inject these instead. This also goes for the `Cookies` helpers. Unfortunately these are used in quite a few places, including in the Java Result API, so we may need to rethink this or have a clever way of getting at what we need.

It's also confusing that `CookieBaker#COOKIE_NAME` looks like a constant, but for Session and Flash it's actually a value obtained from the global `httpConfiguration`. I don't think it should be styled as a constant.

**Comment by gmethvin** [comment]
Since the request uses these directly (`request.session` and similar methods), we'll either need to have state injected into the request or maybe change the API to accept an implicit somewhere.

**Comment by gmethvin** [comment]
We can also store the session, flash, and cookies as a data structure on the request rather than parsing and encoding the header. Then the `HttpRequestHandler` can take those data structures and construct the headers based on the user's configuration. This is similar to what we did with response bodies.

**Comment by mkurz** [comment]
Fixed via #6807?

**Comment by marcospereira** [comment]
Fixed by and #6807 #6816.
