### ISSUE TITLE
Add back tests for WebSockets

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#6060]
Many of the [tests in WebSocketSpec](https://github.com/playframework/playframework/blob/2.5.2/framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala#L346) were removed in #5955. Instead they should be updated to use `ActorFlow` and other relevant Akka Streams utilities. Currently much of the WebSocket code is untested.

**Comment by marcospereira** [comment]
Wasn't this moved to docs code examples?

https://github.com/playframework/playframework/blob/77983111f2d91a17e7f97aa6ae01e0ce010201bb/documentation/manual/working/scalaGuide/main/async/code/ScalaWebSockets.scala#L41

**Comment by gmethvin** [comment]
I guess that covers some of it, but I'd rather have them in the play core tests
