### ISSUE TITLE
Play depends on hibernate and spring

### ISSUE THREAD

**Issue by mriehl** [playframework/playframework#6061]
Hi,

It seems that play 2.5.x now depends on both hibernate and spring libraries. Is it really necessary to depend on these? `hibernate-validator` makes sense I suppose, but `spring-core`?

```
[project] $ whatDependsOn org.hibernate hibernate-validator 5.2.4.Final
[info] org.hibernate:hibernate-validator:5.2.4.Final
[info]   +-com.typesafe.play:play-java_2.11:2.5.2 [S]
[info]     +-com.typesafe.play:filters-helpers_2.11:2.5.2 [S]
[info]       +-project:project_2.11:20160419091607 [S]
[info]       
[success] Total time: 0 s, completed Apr 19, 2016 9:19:06 AM
[project] $ whatDependsOn org.springframework spring-core 4.2.4.RELEASE
[info] org.springframework:spring-core:4.2.4.RELEASE
[info]   +-com.typesafe.play:play-java_2.11:2.5.2 [S]
[info]     +-com.typesafe.play:filters-helpers_2.11:2.5.2 [S]
[info]       +-project:project_2.11:20160419091607 [S]
[info]       
[success] Total time: 0 s, completed Apr 19, 2016 9:19:55 AM
```

**Comment by benmccann** [comment]
I think it's just a couple jars though, right? I don't think it's pulling in the entirety of Spring

spring-core's TypeDescriptor is used in Formatters.java and SimpleNamespaceContext in XPath.java
spring-beans, spring-context, and spring-core are used in Form.java

**Comment by marcospereira** [comment]
Hey @mriehl,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Anyway, I don't think this is a big deal since we only add three spring dependencies.
