### ISSUE TITLE
Asset path case not consistent between modes

### ISSUE THREAD

**Issue by austek-mdsol** [playframework/playframework#6065]
### Play Version
2.5.1
### API
Scala
### Operating System
MacOS 10.11.3
### JDK
Oracle 1.8.0_45
### Expected Behavior
```
├── build.sbt
├── conf
│   ├── application.conf
│   └── routes
├── modules
│   ├── subProject1
│   │   ├── app
│   │   │   ├── assets
│   │   │   │   ├── javascripts
│   │   │   │   │  ├── bundle.js
│   │   ├── conf
│   │   │   ├── subProject1-application.conf
│   │   │   └── subProject1.routes
│   └── subProject2
│   │   ├── app
│   │   ├── conf
│   │   │   ├── subProject2-application.conf
│   │   │   └── subProject2.routes
├── project
│   ├── BuildSettings.scala
│   ├── Dependencies.scala
│   ├── build.properties
│   ├── plugins.sbt
│   ├── project
```
Please describe the expected behavior of the issue, starting from the first action.
1. Create asset controller for subProject1 `class Assets extends controllers.AssetsBuilder(LazyHttpErrorHandler)`
2. Add assets entry to subProject1.routes `GET        /sub1/assets/*file        controllers.subProject1.Assets.at("/public/lib/subProject1", file)`
3. in both all `Test, Dev, Prod...` modes `modules/subProject1/app/assets/javascripts/bundle.js` should be served with `/subProject1/assets/javascripts/bundle.js`

### Actual Behavior
In `Prod` bundle.js served as `/subproject1/assets/javascripts/bundle.js` module name in lowercase and in other modes `/subProject1/assets/javascripts/bundle.js` module name in upper case.

**Comment by baloo** [comment]
I believe this is because macos filesystem is case insensitive (by default). Files are served from disk in all but prod mode. In prod mode files are served from jars (zip files) which are case sensitive.

**Comment by austek-mdsol** [comment]
It's true that the macos is case insensitive.  However, Play shouldn't change the case of the module name,  devs will expect to have exactly what they have typed.

**Comment by estsauver** [comment]
Huh, this is interesting. I didn't realize that distinction about zip files. I have two seperate thoughts on why it might make sense to leave it as is. 

1) In the current system, the paths are always equivalent based on whatever rules the filesystem sets. It is a little weird to have it be differently cased, but if you `ls /subProject1/assets/javascripts/bundle.js` it's always going to show up correctly. 

2) Changing this may break quite a number of tests. Anywhere where the module name is different (for end users or inside playframework/playframework) the tests will need to be modified.

**Comment by cchantep** [comment]
Hi, as said it's more than probably related to os/fs specific behaviour that JVM cannot recover from. Moreover, indicated in contribution guidelines that's better to first discuss on the MailingList to confirm issue before raising a ticket there. Meanwhile this can be closed. Best regards.
