### ISSUE TITLE
[2.5.x][doc] JavaWebSocket.md needs better examples

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6074]
### Play Version (2.5.x / etc)

2.5.x
### API (Scala / Java / Neither / Both)

Java
### Expected Behavior

https://www.playframework.com/documentation/2.5.x/JavaWebSockets examples should not include LegacyWebSocket, and should use the accept() method as described in https://www.playframework.com/documentation/2.5.x/StreamsMigration25#Migrating-Java-WebSockets
### Actual Behavior

The pages still refer to `LegacyWebSocket` and while there's deprecation messages, they say "Use Websocket.accept()" but don't provide effective examples.

**Comment by naoyabuzz** [comment]
I made simple and easy chat. Just for reference :)
https://github.com/naoyabuzz/chat-websocket-akkastream-play2.5

![gif](https://j.gifs.com/Z4N7Mv.gif "gif")

**Comment by Captain1653** [comment]
I think the old issue can be closed. Play 2.5.x aren't mantained anymore. And documentation [2.7.x](https://www.playframework.com/documentation/2.7.x/JavaWebSockets) and [2.8.x](https://www.playframework.com/documentation/2.8.x/JavaWebSockets) doesn't include LegacyWebSocket.
