### ISSUE TITLE
[2.5.x][doc] Broken links in documentation

### ISSUE THREAD

**Issue by jtcwang** [playframework/playframework#6081]
One of the link on this page is not linked properly. Under **Database Config** section I'm seeing this:
```
First, note that the above is a valid Slick configuration (for the complete list of configuration parameters that you can use to configure a database see the Slick ScalaDoc for [Database.forConfig](http://slick.typesafe.com/doc/3.1.0/api/index.html#slick.jdbc.JdbcBackend$DatabaseFactoryDef@forConfig(String,Config,Driver,ClassLoader):Database)
```
 ^ The markup is in its original form for some reason instead of being rendered.

Observed on both FF and Chrome.

Also at the bottom of the page, the link *here* in "The source code of the page can be found *here*" is broken as well (https://github.com/playframework/playframework/blob/2.5.x/documentation/manual/working/scalaGuide/main/sql/slick/PlaySlick.md leads to github 404)

**Comment by gmethvin** [comment]
The issue seems to be that there are unencoded parentheses in the URL. The fix should just be to URL-encode.

I opened playframework/playframework.com#86 for the source code link issue.
