### ISSUE TITLE
Assets.assetAt() now assumes all static assets are Range requested and automatically setting a Content-Disposition of attachment

### ISSUE THREAD

**Issue by justinnichols** [playframework/playframework#6090]
### Play Version (2.5.x / etc)

2.5.2

### API (Scala / Java / Neither / Both)

Both, but it is rooted in the Scala side

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Ubuntu 16.04
Linux river 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

### Expected Behavior

Referencing static assets via path from HTML output will yield the browser to render it, not download it.

1. Best example is to use an iframe and set its source to a static asset path, such as /assets/html/foo.html
2. When the iFrame loads, it should render foo.html

### Actual Behavior

Since Play 2.5 with this commit: https://github.com/playframework/playframework/blob/7ca3505a17f0adc09d5e2cbcb60fc5da1e259f55/framework/src/play/src/main/scala/play/api/controllers/Assets.scala

All assets are being treated as a Range request and inside RangeResult.ofSource(), the following is being added as a "common" header:  `fileName.map(f => CONTENT_DISPOSITION -> s"""attachment; filename="$f"""")`

1. Best example is to use an iframe and set its source to a static asset path, such as /assets/html/foo.html
2. When the iFrame loads, it is downloading the html as an attachment instead of rendering.

### Reproducible Test Case

Sadly I do not have time to create this as I'm frantically trying to figure out a way around this.  It's pretty obvious that static assets are being treated as such in the code referenced above.  Play 2.4.x did not have this issue.

**Comment by justinnichols** [comment]
Also to note, static assets should not be assumed to be a range request unless the Range request header exists and most certainly should not be assumed that the client should download the asset instead.

**Comment by marcospereira** [comment]
See #6058.

**Comment by justinnichols** [comment]
Okay, thank you.
