### ISSUE TITLE
[2.5.x] On first reload in "run" command, project build is executed twice

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6091]
### Play Version (2.5.x / etc)

2.5.x
### API (Scala / Java / Neither / Both)

Both
### Actual Behavior

From https://groups.google.com/d/topic/play-framework/qOtTe0CU7Ts/discussion

In Play! 2.5.x versions, on first reload in "run" command, project build 
is executed twice (first result is ignored). 

This is caused by two "applicationProvider.get" calls. 

First is in "PlayRequestHandler.scala" : 
https://github.com/playframework/playframework/blob/2.5.2/framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala#L50 

Second in "Server.scala" : 
https://github.com/playframework/playframework/blob/2.5.2/framework/src/play-server/src/main/scala/play/core/server/Server.scala#L53 

This problem doesn't exist in Play! Framework 2.3.x and 2.4.x (tested 
versions 2.3.10 and 2.4.6).

**Comment by estsauver** [comment]
It seems like it would make sense to not even expose the applicationProvider directly, but to instead expose an `application` method that could call applicationProvider under the hood and cache this call. 

I'm new to contributing to play, but would be happy to take this on.
