### ISSUE TITLE
Documentation for Multi-value support is out of date

### ISSUE THREAD

**Issue by gnomff** [playframework/playframework#6094]
### Play Version (2.5.x / etc)
2.3 and up

### Doc Problem
SeqParameter has the signature:  
`def apply[A](seq: Seq[A], sep: String = ", ", pre: String = "", post: String = "")`  
but in the documentation it looks like  
`SeqParameter(
    values = Seq("a", "b", "c"), separator = " OR ", 
    pre = "EXISTS (SELECT NULL FROM j WHERE t.id=j.id AND name=",
    post = ")")`  

it should be  
`SeqParameter(
    seq = Seq("a", "b", "c"), sep = " OR ", 
    pre = "EXISTS (SELECT NULL FROM j WHERE t.id=j.id AND name=",
    post = ")")`

**Comment by marcospereira** [comment]
Hi @gnomff, which page?

**Comment by gmethvin** [comment]
Hi @gnomff, this is a bug in [anorm](https://github.com/playframework/anorm), not in Play. I'm closing this and you can open a new issue there, or you can submit a pull request for [this page](https://github.com/playframework/anorm/blob/master/docs/manual/working/scalaGuide/main/sql/ScalaAnorm.md#multi-value-support).

**Comment by gnomff** [comment]
Ok cool, thanks for the link. Now that I know where the docs reside I'll make a PR
