### ISSUE TITLE
[2.4.x] Content length is not calculated if client specifies connection close header

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#6100]
This issue only impacts Play 2.4, not Play 2.5.  If a client sends a `Connection: close` header, Play will not attempt to calculate the content length of the response.  This is bad behaviour, it should make a best effort attempt to always send a content length, and do its usual buffering to see if there's only one chunk and if there is, send the content length for that.

**Comment by marcospereira** [comment]
Closing since we don't maintain 2.4.x any more.
