### ISSUE TITLE
[doc] Google Closure Compiler doesn't mention that you have to enable plugin to work

### ISSUE THREAD

**Issue by michalzubkowicz** [playframework/playframework#6104]
It should mention that you need to enable repository:
Resolver.sonatypeRepo("releases")

plugin SbtWeb and 
addSbtPlugin("net.ground5hark.sbt" % "sbt-closure" % "0.1.4")

and add pipelineStage
pipelineStages := Seq(closure)

Or something else because as based on documentation it doesn't work for sure. 
(put file in app/assets/javascripts/main.js) and use it with versioned asset

**Comment by marcospereira** [comment]
Hello @michalzubkowicz, 

This should (and it is) documented at the plugin page: https://github.com/ground5hark/sbt-closure

😉

**Comment by michalzubkowicz** [comment]
By why Play Documentation doesn't mention this page? :)  It would be a lot easier.
