### ISSUE TITLE
Make it easier to concat SIRD Routers

### ISSUE THREAD

**Issue by schmitch** [playframework/playframework#6107]
Actually it's really simple to specify a Play! Router without the routes file:

``` scala
import controllers.Assets
import play.api.routing.SimpleRouter
import play.api.mvc._
import play.api.routing._
import play.api.routing.sird._

class DemoRouter @Inject()() extends SimpleRouter {

  override def routes = {
    case GET(p"/assets/$file*") => Assets.versioned(path = "/public", file = file)
  }

}
```

However concating multiple of these while one is the "master" router isn't as easy as it should.

the best way would be defining it like it is on the routes file, something like 
`case ->(p"/prefix/") => injectedOtherRouter`

**Comment by julienrf** [comment]
Hi, I think it should be possible to write something like the following:

~~~ scala
mainRouter.routes.orElse(injectedOtherRouter.withPrefix("/prefix").routes)
~~~

But maybe it would be worth adding an `orElse` method on `Router`.

**Comment by schmitch** [comment]
actually yeah that is possible, but if you need to include multiple routers that will get ugly.
this issue isn't "important" but it's helpful.

**Comment by wsargent** [comment]
@schmitch https://gist.github.com/tabdulradi/ea958a34c8926a20d287#file-compositerouter-scala

**Comment by schmitch** [comment]
Maybe it's enough to just document that, or create such a composite router in play-core.

**Comment by marcospereira** [comment]
It is now possible to do `router1.orElse(router2)`, so I'm closing this.

@schmitch feel free to reopen it if you think there is something missing.
