### ISSUE TITLE
Cross build for Scala 2.12

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#6110]
Play 2.6 will support Scala 2.12. We should set up cross building so we can build with both Scala 2.11 and the latest milestone of 2.12.

**Comment by schmitch** [comment]
Actually this is nearly done with:

- [ ] https://github.com/playframework/playframework/pull/6432
- [ ] fix sbt-rc: https://github.com/sbt/sbt-remote-control (last commit was 1 year ago...) used for fork-run

and await publish new version of play-doc, twirl and await Scala 2.12.0-RC2.

**Comment by wsargent** [comment]
We can't use a travis ci build matrix, because the crossbuild is in https://github.com/playframework/interplay -- so there's got to be an update there as well.

**Comment by wsargent** [comment]
So a brief update -- there's two places that depend on 2.12 in dependencies: https://github.com/playframework/playframework/blob/master/framework/project/Dependencies.scala#L184

```
  // use partial version so that non-standard scala binary versions from dbuild also work
  def sbtRcClient(scalaBinaryVersion: String): ModuleID = CrossVersion.partialVersion(scalaBinaryVersion) match {
    case Some((2, 10)) => "com.typesafe.sbtrc" % "client-2-10" % sbtRcVersion
    case Some((2, 11)) => "com.typesafe.sbtrc" % "client-2-11" % sbtRcVersion
    case Some((2, 12)) => "com.typesafe.sbtrc" % "client-2-12" % sbtRcVersion
    case _ => sys.error(s"Unsupported scala version: $scalaBinaryVersion")
  }
```

and https://github.com/playframework/playframework/blob/master/framework/project/Dependencies.scala#L196

```
  def sbtRcActorClient(scalaBinaryVersion: String): ModuleID = CrossVersion.partialVersion(scalaBinaryVersion) match {
    case Some((2, 10)) => "com.typesafe.sbtrc" % "actor-client-2-10" % sbtRcVersion
    case Some((2, 11)) => "com.typesafe.sbtrc" % "actor-client-2-11" % sbtRcVersion
    case Some((2, 12)) => "com.typesafe.sbtrc" % "actor-client-2-12" % sbtRcVersion
    case _ => sys.error(s"Unsupported scala version: $scalaBinaryVersion")
  }
```

This code points to https://github.com/sbt/sbt-remote-control/blob/master/project/build.scala#L30

```
    lazy val publishedProjects: Seq[Project] = Seq(client, client211, client212, terminal, clientAll, clientAll211, clientAll212, actorClient, actorClient211, actorClient212) ++ sbt13ProbeProjects
```

sbt-remote-control in turn depends on three projects:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-sbt#serialization_2.12.0-M5;0.1.2: not found
[warn] 	:: org.scala-sbt#io_2.12.0-M5;0.13.9: not found
[warn] 	:: org.scala-sbt#collections_2.12.0-M5;0.13.9: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

and sbt-serialization needs 
https://github.com/sbt/serialization/blob/master/build.sbt#L7

```
  crossScalaVersions := Seq(scala210Version, scala211Version, scala212Version),
```

but sbt-serialization also depends on 

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-lang.modules#scala-pickling_2.12.0-M5;0.10.1: not found
[warn] 	:: org.spire-math#jawn-parser_2.12.0-M5;0.6.0: not found
[warn] 	:: org.spire-math#json4s-support_2.12.0-M5;0.6.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

So... there's a ways to go yet.

**Comment by SethTisue** [comment]
you might subscribe to https://github.com/akka/akka/issues/21705 to find out when Akka is ready

**Comment by SethTisue** [comment]
Akka has published 2.4.11 for 2.12.0-RC2

**Comment by SethTisue** [comment]
a newer version of Jawn has been published for RC2: `"org.spire-math"                   %% "jawn-parser"               % "0.10.2"`

**Comment by SethTisue** [comment]
on the sbt parts, is @dwijnand aware?

**Comment by schmitch** [comment]
> after removing:
`def watch(filesToWatch: List[File], onChange: Callable[Void]): FileWatcher  ...` (the Java delegation which wasn't used anywhere) in FileWatchService.scala
and changing the build to use the "old sbt IO" version for 2.12.: 
```
   def sbtIO(sbtVersion: String, scalaVersion: String): ModuleID = CrossVersion.partialVersion(scalaVersion) match {
     case Some((2, 11)) => "org.scala-sbt" %% "io" % "0.13.11" % "provided"
     case _ => "org.scala-sbt" % "io" % sbtVersion % "provided"
   }
```
and publishLocal: twirl, play-doc, interplay
then i did `+test` and it worked fine.

just to quote myself from gitter.

not sure about how important sbt-io is, I asked here: https://github.com/sbt/sbt/issues/2793
guess it's mostly used for `sbt run`.

**Comment by dwijnand** [comment]
Wasn't rc removed from Play a few weeks ago?

**Comment by schmitch** [comment]
yeah it was, but we still require "io".

**Comment by schmitch** [comment]
Here are my steps to get a 2.12.0-RC2 working:

- `+publishLocal +plugin/publishLocal`  twirl (master)
- `+publishLocal` interplay (master)
- `+publishLocal` play-doc with https://gist.github.com/schmitch/9894e893c46abd6f00b285d038dfb30e applied against master
- `+test` play with https://gist.github.com/schmitch/26ce348d127be6c750433669b9f6fa44 applied against master

actually I sometimes run into some wierd errors which are fixed with `+clean`. after running the build multiple times. And I can't run `scripted` tests since it won't pick up my local snapshots somehow. but `+publishLocal` and running a simple project works.

I have `JAVA_OPTS` set to `-Xmx8G -Xss2M -XX:MaxMetaspaceSize=512M -XX:ReservedCodeCacheSize=192M -Dfile.encoding=UTF-8` so  I guess some errors only happens sometimes, I basically run into the same error than we had on community-builds  once so far:
```
java.lang.StackOverflowError
	at scala.tools.nsc.util.JavaCharArrayReader.next(JavaCharArrayReader.scala:28)
	at scala.tools.nsc.javac.JavaScanners$JavaScanner.putCommentChar(JavaScanners.scala:580)
	at scala.tools.nsc.javac.JavaScanners$JavaScanner.skipBlockComment(JavaScanners.scala:585)
```
however I guess my `JAVA_OPTS` are mostly preventing it, since I've run the test suite like 4-5 times now and only run into it once. I also had a compilation failure of java code at the beginning, but after `+clean` it never happened again.
Maybe other people can check as well if my steps are working for them.

**Comment by SethTisue** [comment]
seen recently at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/881/consoleFull:

```
[play2-core] [info] Test play.mvc.RangeResultsTest.shouldNotReturnRangeResultForPathWhenFilenameHasSpecialChars started
[play2-core] [error] Test play.mvc.RangeResultsTest.shouldNotReturnRangeResultForPathWhenFilenameHasSpecialChars failed: org.mockito.exceptions.misusing.UnfinishedVerificationException: 
[play2-core] [error] Missing method call for verify(mock) here:
[play2-core] [error] -> at play.i18n.MessagesTest.testMessageCall(MessagesTest.java:25)
[play2-core] [error] 
[play2-core] [error] Example of correct verification:
[play2-core] [error]     verify(mock).doSomething()
[play2-core] [error] 
[play2-core] [error] Also, this error might show up because you verify either of: final/private/equals()/hashCode() methods.
[play2-core] [error] Those methods *cannot* be stubbed/verified.
[play2-core] [error] , took 0.003 sec
[play2-core] [error]     at play.mvc.RangeResultsTest.setUpHttpContext(RangeResultsTest.java:45)
[play2-core] [error]     ...
```

**Comment by schmitch** [comment]
Does that happen on subsequent runs, too? 

Guess it's https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/java/play/i18n/MessagesTest.java#L25 where it at least needs to be `verify(messagesApi). get(lang, "hello.world");`

**Comment by schmitch** [comment]
We still Need to Cross Build

**Comment by SethTisue** [comment]
play2-core in the community build seems to be OK lately

**Comment by schmitch** [comment]
Fixed with https://github.com/playframework/playframework/pull/6691
Actually still needs some improvements, but I guess the overall issue can be closed.

**Comment by SethTisue** [comment]
are there 2.12 artifacts we could include in https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md ? does it make sense to remove Play from the "Pending" section at the bottom?

**Comment by marcospereira** [comment]
@SethTisue we don't have a release that people can use yet, so I think you can keep us at the pending section.

ps.: Slick 3.2.0-M2 has a Scala 2.12 build: http://central.maven.org/maven2/com/typesafe/slick/slick_2.12/3.2.0-M2/

**Comment by domdorn** [comment]
any updates? can we already try it with a RC or something?

**Comment by schmitch** [comment]
actually play publishes a snapshot **every** day. so you could've tried it since day 1:
 
https://www.playframework.com/documentation/2.6.x/Repositories and look for the version here:

https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.12/

**Comment by wsargent** [comment]
Also M1 is out now :-)

**Comment by domdorn** [comment]
yeah, already trying to get my project working with it... some scala plugins/libs I'm using still need migration, but we're on a good path! :)
