### ISSUE TITLE
NettyModelConversion overwrites the content-length header in responses to HEAD requests

### ISSUE THREAD

**Issue by anurag-prakash-singh** [playframework/playframework#6126]
### Play

2.5.2

### API (Scala / Java / Neither / Both)
Scala (as tested, but the Java API *should* be affected too)

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.11.4

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

1.8.0_65

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Send an HTTP HEAD request.
2. In the response to the request, set the 'Content-Length' header to a non-zero value (in our application, the value is the size of an existing image).
3. Do not have a body in the response.
4. When the response arrives at the client (e.g. the browser), the header should have the same 'Content-Length' that was set by the server application (it should not have been modified by a lower layer).

### Actual Behavior

1. Send an HTTP HEAD request.
2. In the response to the request, set the 'Content-Length' header to a non-zero value.
3. Do not have a body in the response.
4. When the response arrives at the client (e.g. the browser), the header has a 'Content-Length' of '0'. Additionally, Netty emits the following warning message: "[warn] 13:43:52.147 NettyModelConversion  - Content-Length header was set manually in the header (70541149) but is not the same as actual content length (0)."

This is where 'Content-Length' is overwritten:

https://github.com/playframework/playframework/blob/ad22900e377715a3bb48d0b24e60a441ca84fbb6/framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala#L201

**Comment by gmethvin** [comment]
I really think we should improve this API, but you should be able to send an `HttpEntity` with an empty stream and a content length:
```scala
Result(ResponseHeader(OK),
  HttpEntity.Streamed(Source.empty, Some(contentLength), Some(contentType))
)
```
In general Play trusts the content length from the `HttpEntity` more than it does the one explicitly set in the headers. The default is `NoEntity`, which is actually an entity with a `Content-Length` of zero. So by not explicitly setting a body you're actually telling Play you want a body with a Content-Length of 0, thus causing this conflict.

**Comment by johanandren** [comment]
What about the existing `HttpEntity.empty(ContentType)`?

**Comment by gavares** [comment]
@gmethvin Thanks for the reply. Your solution is exactly the conclusion we came to as well. Our only complaint is that it took some time with failing tests and then we had to read through Play code to figure out the problem as well as as workaround. 

At the end of the day, my reading of the HTTP spec for HEAD requests seems to indicate that Play is non-compliant and should be updated.

**Comment by gmethvin** [comment]
@gavares Perhaps we could improve things by creating an explicit `HttpEntity.Head` response entity type and adding a warning about it if you manually set the `Content-Type` in a `HEAD` request.

Normally `HEAD` is handled by the same actions as `GET` so the APIs are designed to work well for that scenario. The Source will immediately be cancelled when responding to a `HEAD` request, so you can actually "send" the same response in both `GET` and `HEAD`, while still saving the effort of computing the body if you have a large stream of data.

**Comment by gavares** [comment]
@gmethvin, looks like you've taken care of this already. Thanks again for the help and solution.
