### ISSUE TITLE
[doc] JavaWS.md refers to wrong method name in exception-recovery section

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6132]
### Play Version (2.5.x / etc)

2.5.x

### API (Scala / Java / Neither / Both)

Java

### Actual Behavior

The documentation refers to the Scala API instead of the Java API: 

"If you want to recover from an exception in the call, you can use recover or recoverWith to substitute a response." 

However, the method name in the example is `handle` in the Java API, so this is incorrect.

https://www.playframework.com/documentation/2.5.x/JavaWS#exception-recovery

**Comment by gmethvin** [comment]
Also you can use `exceptionally` to cover from an exception.
