### ISSUE TITLE
[doc] Document RoutesProvider for use with Guice

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6133]
### Play Version (2.5.x / etc)

2.5.x

### API (Scala / Java / Neither / Both)

Scala

### Expected Behavior

```
@Singleton
class RoutesProvider @Inject() (injector: Injector, environment: Environment, configuration: Configuration, httpConfig: HttpConfiguration) extends Provider[Router] {
  lazy val get = {
    val prefix = httpConfig.context

    val router = Router.load(environment, configuration).fold[Router](Router.empty)(injector.instanceOf(_))
    router.withPrefix(prefix)
  }
}
```

**Comment by gmethvin** [comment]
Given that the RoutesProvider loads the router at runtime and uses the runtime injector, it doesn't seem like it's meant to be used with compile-time DI.

**Comment by wsargent** [comment]
This was something that @schmitch was running into.

**Comment by gmethvin** [comment]
Oh I see, from gitter. It looks like he's actually trying to use a SIRD router with Guice, but right now we only really document manual DI for SIRD.

**Comment by wsargent** [comment]
Sort of related to https://github.com/playframework/playframework/issues/6107
