### ISSUE TITLE
p.a.h.MediaRange -  - Unable to parse part of media range header '*/*'

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#6139]
### Play Version (2.4.x / etc)
2.4.6

### API (Scala / Java / Neither / Both)
Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.10.5

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. CURL request to http://localhost:9000/ 
2. Response is returned, no logs are created

### Actual Behavior

1. curl http://localhost:9000/
2. Response is created, a log entry is created as well:
"[debug] p.a.h.MediaRange -  - Unable to parse part of media range header '*/*'"

Play should be able to handle a standard CURL request without creating log entries. 

### Reproducible Test Case
curl http://localhost:9000/

**Comment by gmethvin** [comment]
> Play should be able to handle a standard CURL request without creating log entries.

To be fair, it's logged at the debug level. The log message is slightly misleading though.

**Comment by gmethvin** [comment]
Actually I think this is the "bug" discussed in [this comment on #2406](https://github.com/playframework/playframework/issues/2406#issuecomment-35862341):
> Whether that log message is printed or not is guarded by an if statement, and it looks like the predicate should be negated.

[This is the relevant code.](https://github.com/playframework/playframework/blob/2.5.3/framework/src/play/src/main/scala/play/api/http/MediaRange.scala#L103)
