### ISSUE TITLE
[2.4.6] requestHeader.secure not updated by X-Forwarded-Proto

### ISSUE THREAD

**Issue by judu** [playframework/playframework#6141]
### Version

This appeared between 2.4.3 and 2.4.6.

### API

I only tested it using the scala API.

### My Story

I'm trying to update an application from 2.4.3 to 2.4.6, and I get a weird behavior:
I implemented a "redirect-to-https" filter, following this guide: https://www.clever-cloud.com/blog/engineering/2015/12/01/redirect-to-https-in-play/ (I put all that into a lib and use it in all my projects, without a problem).

It works fine for 2.4.3, but in 2.4.6 (the only change I made was to change the sbt-plugin version in project/plugins.sbt) I get an infinite redirection loop: https://mysite.com/ -> https://mysite.com/ -> https://mysite.com/…

Reading my code indicated that what causing it was that requestHeader.secure is always `false`.

### Operating System

The application is running on a Linux host behind Haproxy:

```
Client --[HTTPS]--> Haproxy (set X-Forwarded-Proto) --[HTTP]--> Application
```

### JDK

OpenJDK 1.8.x

**Comment by gmethvin** [comment]
Hi @judu,

Have you configured [trusted proxies](https://www.playframework.com/documentation/2.4.x/HTTPServer#Configure-trusted-proxies) to trust the proxy sending the `X-Forwarded-Proto` header?

This was intentionally changed by #5260 for security reasons.

**Comment by judu** [comment]
Oh, I made some tests, and it turns out that now I need to add the "/CIDR" to the address.
I was putting "X.X.X.X" (for instance), and now I need to put "X.X.X.X/X". That seems to have changed.

**Comment by amertum** [comment]
Should we reopen this issue or create a new one as I still have this problem with play-scala-2.5.6 on heroku.

The request arriving on the server has these headers :
- `Via -> 1.1 vegur`
- `Host -> xxx.herokuapp.com`
- `Accept -> text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`
- `Cookie -> PLAY_SESSION=9f4f5a4cba1530a53ca5e29e31db401ed2a1a8e1-uid=54fg6f`
- `Referer -> https://dashboard.heroku.com/`
- `Connection -> close`
- `User-Agent -> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36`
- `Connect-Time -> 0`
- `X-Request-Id -> 6067c1fa-7ff6-455e-b19a-28b5c3484869`
- `Cache-Control -> max-age=0`
- `Accept-Encoding -> gzip, deflate, sdch, br`
- `Accept-Language -> en-US,en;q=0.8,fr;q=0.6`
- `X-Forwarded-For -> xx.xxx.xx.xx`
- `X-Request-Start -> 1472813154430`
- `Total-Route-Time -> 0`
- `X-Forwarded-Port -> 443`
- `X-Forwarded-Proto -> https`
- `Upgrade-Insecure-Requests -> 1`

I've tried these 4 configurations :
```
play.http.forwarded.trustedProxies=["127.0.0.1", "::1"]
play.http.forwarded.version=x-forwarded
```
```
play.http.forwarded.trustedProxies=["127.0.0.1", "::1"]
play.http.forwarded.version=rfc7239
```
```
play.http.forwarded.trustedProxies=["0.0.0.0/0", "::/0"]
play.http.forwarded.version=x-forwarded
```
```
play.http.forwarded.trustedProxies=["0.0.0.0/0", "::/0"]
play.http.forwarded.version=rfc7239
```

And for each I've `request.secure = false` within a controller or a filter.
