### ISSUE TITLE
CSRF Filter does not consider cookie token in some parts of the code

### ISSUE THREAD

**Issue by OlegIlyenko** [playframework/playframework#6142]
### Play Version (2.5.x / etc)

2.5.3

### API (Scala / Java / Neither / Both)

Scala

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

1.8.0_91

### Expected Behavior  

After configuring the `CSRFFilter`:

```
play.filters.csrf.token.sign = true
play.filters.csrf.cookie.name = "PLAY_CSRF_TOKEN"
```

I would expect this fake request to succeed with status code 200:

```scala
val app = inject [Application]
val crypto = inject [CSRFTokenSigner]
val token = crypto.generateSignedToken

val request = FakeRequest("POST", "/posturl")
  .withHeaders("Accept-Language" → "en-US")
  .withCookies(Cookie("useLang", "de"), Cookie("PLAY_CSRF_TOKEN", token))
  .withBody(Json.obj("foo" → "bar"))

val Some(result) = route(app, request)
```

because I provide CSRF Token via cookie. Unfortunately, request fails with 403 and I can see following log entry:

```
[trace] play.filters - [CSRF] Check failed because application/json request
```

### Root Cause

After some debugging I stumbled upon this part of the code, which verifies the CSRF token:

https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala#L59-L62

It turns out that `getTokenToValidate` is able to find the token in the cookie, but then `getHeaderToken` only searches [query string and headers](https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala#L412-L413) for a token, so it unable to find provided token in the cookie. Since my content is a JSON object, it results in error (403 status code).

**Is this behavior intentional or would you consider it to be a bug?**

As a temporary workaround, I provide the token in header and in cookie:

```scala
FakeRequest("POST", "/posturl")
  .withHeaders("Accept-Language" → "en-US", "Csrf-Token" → token)
  .withCookies(Cookie("useLang", "de"), Cookie("PLAY_CSRF_TOKEN", token))
  .withBody(Json.obj("foo" → "bar"))
```

**Comment by gmethvin** [comment]
@OlegIlyenko CSRF validation works like this:
 1. Play sends the token to the browser (usually in a form) and sets a cookie to compare against in the next request.
 2. The user submits the token back to the Play server, either in a form body, query string or HTTP header.
 3. Play compares the submitted token in the cookie against the one saved in the cookie.

I would not expect your initial request to succeed under any configuration because there need to be two values to compare. Usually the cookie is used to store the *server-generated token*, not the token submitted by the user.

**Comment by OlegIlyenko** [comment]
I see. Thank you very much for detailed explanation!

**Comment by littlebox692** [comment]
@gmethvin , I encounter the same issue while using httpClient for request.  client: java project , server: play project .`    public ResponseEntity post() {
		String forwardInfo = "....";
		String url = "...";
	    HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setContentType(MediaType.APPLICATION_JSON_UTF8);
        HttpEntity httpEntity = new HttpEntity(forwardInfo, httpHeaders);
        SSLContext sslContext = null;
        String filePath = loadPropertiesContent(...);
		sslContext = new SSLContextBuilder().loadTrustMaterial(
                    new File(filePath)).build();

        SSLConnectionSocketFactory socketFactory = new SSLConnectionSocketFactory(sslContext);
        Registry<ConnectionSocketFactory> socketFactoryRegistry = RegistryBuilder.<ConnectionSocketFactory>create()
                .register("http", PlainConnectionSocketFactory.getSocketFactory())
                .register("https", socketFactory).build();
        PoolingHttpClientConnectionManager connMgr = new PoolingHttpClientConnectionManager(socketFactoryRegistry);
        connMgr.setMaxTotal(200);
        connMgr.setDefaultMaxPerRoute(100);
        CloseableHttpClient client = HttpClientBuilder.create().setSSLContext(sslContext).setConnectionManager(connMgr).build();
        HttpComponentsClientHttpRequestFactory clientHttpRequestFactory = new HttpComponentsClientHttpRequestFactory(client);
        RestTemplate restTemplate = new RestTemplate(clientHttpRequestFactory);
		restTemplate.postForEntity(url, httpEntity, byte[].class);
    }` , I use https for auth.  for server(play project), the method just like this `  def enquireSchedulerJobDetail: Action[AnyContent] = withRecover("cannot get applicable data content for schedulerJob detail", "enquireSchedulerJobDetail operation failed"){
    (request: Request[AnyContent]) =>
      val processor = new SchedulerJobUIProcessor with SchedulerJobRepo with DatabaseProvider
      val json = request.body.asJson
      val schedID = (json.get \ "data" \ "schedID").as[Long]
      processor.enquireSingleSchedulerJobTaskParams(schedID).map{result =>
        Ok(Json.toJson(UIResponse(result, Constants.UI_RESPONSE_STATUS_SUCCESS, "", "")).toString())
      }
  }` any suggestion? wish your repsonse, thx

**Comment by gmethvin** [comment]
@littlebox692 This tracker is for bugs in Play. If you're looking for help I'd suggest posting on https://discuss.lightbend.com/c/play.
