### ISSUE TITLE
Assets controller does not serve gzipped + digested version

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#6144]
### Play Version (2.5.x / etc)

2.4.6
### API (Scala / Java / Neither / Both)

Both
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Mac 10.10.5
### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
### Library Dependencies

not applicable. 
### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.
1. Resources (JS, CSS) get digested and gzipped. so of main.min.js -> Seq(9e674895a7a423d8327fc4e1494d3313-main.min.js, 9e674895a7a423d8327fc4e1494d3313-main.min.js.gz)
2. Assets controller looks if there is a digested version. if there is, it also looks if this version got gzipped
3. if the client requested gzip and it found a gzipped version (either of the digested filename or the plain filename), it should serve the gzipped version. 
### Actual Behavior
1. Resources (JS, CSS) get digested and gzipped. so of main.min.js -> Seq(9e674895a7a423d8327fc4e1494d3313-main.min.js, 9e674895a7a423d8327fc4e1494d3313-main.min.js.gz)
2. Assets controller looks if there is a gzipped version of the base name "main.min.js.gz". It does not look if there is a gzipped version of the diggested file. 
3. only the digested file is served. 
### Reproducible Test Case

The Problem is in 
https://github.com/playframework/playframework/blob/a5decc4ec81d311a769208ce007771a1e45b570b/framework/src/play/src/main/scala/play/api/controllers/Assets.scala#L303

As we can see, the controller looks for a resourcename.gz when it actually should first do the digesting, and if that succeeds, look for a digest-resourcename.gz . 

I'd change that to something like this:

``` scala
        val digestUrl: Option[String] = digest(name)
        val gzipUrl: Option[URL] = digestUrl.flatMap(url => resource(url + ".gz")).orElse(resource(name + ".gz"))
        new AssetInfo(name, url, gzipUrl, digestUrl)
```

If wished, I can provide a patch for this.

**Comment by marcospereira** [comment]
@domdorn a pull request would be nice. ;-)

**Comment by domdorn** [comment]
@marcospereira I found another bug related to this one (gzip serving does not work when the .min version is used). I'll create a pull request with enhanced tests that fixes both issues. 
I'll base it on the 2.4.6 branch because we're using that version of the project atm (can't upgrade to 2.5 yet), so maybe we can then roll a 2.4.7 and merge the changes upstream to 2.5 ?

**Comment by domdorn** [comment]
Ok, I've got some time to work on this again. Please give your opinion on the following logic (change) in the assets controller.

unbind - the process of generating the resource filenames in the template:
example filename: main.js
# input: main.js
# generate minified filename: main.min.js 
# check if there is a digest for it main.min.js.md5
# if yes, generate the minified digested filename: abc-main.min.js
# check if the file exists, if yes return filename: abc-main.min.js
# no -> check if minified file exists, if yes, return filename: main.min.js
# no -> check if non-minified digest exist: main.js.md5
# if yes, generate the digested filename: abc-main.js
# check if digested filename exists, if yes, return: abc-main.js
# no -> return main.js

**Comment by domdorn** [comment]
PR (for own reference) https://github.com/playframework/playframework/pull/6552
still has some issues.. working on it again.

**Comment by domdorn** [comment]
@marcospereira PR updated.

**Comment by gmethvin** [comment]
@domdorn I'm closing this due to your fixes
