### ISSUE TITLE
Play 2.5.x local documentation RuntimeException with kalium denpendency

### ISSUE THREAD

**Issue by eugene-c** [playframework/playframework#6145]
### Play Version (2.5.x / etc)
2.5.x

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Oracle 1.8.0_72

### Library Dependencies
```
libraryDependencies ++= Seq(
  "mysql" % "mysql-connector-java" % "5.1.38",
  "com.typesafe.play" %% "play-slick" % "2.0.0",
  "org.abstractj.kalium" % "kalium" % "0.5.0.Alpha1",
  "org.scalatestplus.play" %% "scalatestplus-play" % "1.5.1" % Test
)
```
### Issue

Visit http://localhost:9000/@documentation/Home in web browser and you get 
```
[RuntimeException: Error creating extended parser class: null]
```

**Comment by wsargent** [comment]
This is an issue tracker for reporting bugs in Play -- please use the mailing list or Stackoverflow if you have a bug in your local project.

In this particular case, you're using Kalium -- there's a sample play-kalium project at https://github.com/playframework/play-kalium that can help.  Make sure you read the README and install libsodium before you start the project.
