### ISSUE TITLE
How get upload file progress intime

### ISSUE THREAD

**Issue by mirszhao** [playframework/playframework#6166]
Hi all:
when i upload a file ,i want get upload progress intime,
i debug the upload action ,in fact when the file is complete uploaded, the action is being trigger

but i think should be have a listener or other conf   listen the upload progress.

i use Playframework 2.3.8

**Comment by marcospereira** [comment]
Hello @mirszhao,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

Thanks.
