### ISSUE TITLE
Play 2.5.3 fails to stop on error

### ISSUE THREAD

**Issue by Discipe** [playframework/playframework#6167]
How to reproduce:
Create Play app from activator's Play seed.
routes:
`GET     /oom                        controllers.AsyncController.oom`

AsyncController.scala:
```
def oom() = Action.async {
  throw new OutOfMemoryError()
  Future.successful(Ok("Finished?!"))
}
```

Opening of `http://localhost:9000/oom` address in a browser results in exception right away:
`[error] a.a.ActorSystemImpl - Uncaught fatal error from thread [application-akka.actor.default-dispatcher-3] shutting down ActorSystem [application]`

But application does not stop, after some time it starts to repeat following error:
```
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
[info] java.lang.IllegalStateException: Attempted to call materialize() after the ActorMaterializer has been shut down.
[info] 	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:88)
[info] 	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:79)
[info] 	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:367)
[info] 	at play.api.libs.streams.SinkAccumulator.run(Accumulator.scala:125)
[info] 	at play.api.libs.streams.SinkAccumulator.run(Accumulator.scala:129)
[info] 	at play.core.server.netty.PlayRequestHandler.play$core$server$netty$PlayRequestHandler$$handleAction(PlayRequestHandler.scala:256)
[info] 	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:103)
[info] 	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:163)
[info] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
[info] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
```

As a result Play process hangs in a state when it works, but cannot serve any requests, which doesn't look like a good thing.

**Comment by beingsagir** [comment]
I am getting ```
play.core.server.netty.PlayRequestHandler - Exception caught in channelRead future
java.lang.IllegalStateException: Attempted to call materialize() after the ActorMaterializer has been shut down.
```

this while converting a multi module project from 2.4 to 2.5 
Will update soon.

**Comment by wsargent** [comment]
This is probably because `jvm-exit-on-fatal-error` is set to false in config.

OOM is thrown for reasons that aren't actually OOM related, such as not being able to spawn a new native thread, so it's more complicated than simply checking the type and throwing.  However, if you absolutely want this, upgrade to 8u92 and set `-XX:CrashOnOutOfMemoryError` as a JVM option.
