### ISSUE TITLE
Documentation (Spanish)

### ISSUE THREAD

**Issue by oscarvarto** [playframework/playframework#6172]
I have started a Spanish translation of the docs in master.

As an example, please take a look at:

https://github.com/oscarvarto/playframework/blob/documentationSpanish/documentationSpanish/manual/ModuleDirectory.md

Is there any interest in work like this? Should I continue/stop?

**Comment by wsargent** [comment]
Hi @oscarvarto there is interest in a Spanish translation of the docs -- there's a documentation page at
https://www.playframework.com/documentation/2.5.x/Translations and we have Turkish https://www.playframework.com/documentation/tr/2.4.x/Home and Japanese https://www.playframework.com/documentation/ja/2.4.x/Home translations available

**Comment by marcospereira** [comment]
Hi @oscarvarto, while there is interest in a Spanish translation, this won't be handled at this repository, [as documented here](https://www.playframework.com/documentation/2.5.x/Translations#Deploying-documentation-to-playframework.com):

> playframework.com serves documentation out of git repositories. If you want your translation to be served from playframework.com, you’ll need to put your documentation into a GitHub repository, and contact the Play team to have them add it to playframework.com.

So I'm closing this issue.
