### ISSUE TITLE
Js FORMAT errors during READ

### ISSUE THREAD

**Issue by dsounded** [playframework/playframework#6176]
This is my case class:

`case class Country(id: Long = 0, title: String, abbreviation: String, isActive: Boolean = true, createdAt: Timestamp = TimeUtil.now)`

And these are my read/write methods:

`trait CountrySerializer {`
  `  val countryReads: Reads[Country] = (`
    `  (JsPath \ "title").read[String] and`
    `  (JsPath \ "abbreviaton").read[String]`
    ` )(Country.apply _)`

  `  val countryWrites: Writes[Country] = (`
    `  (JsPath \ "title").write[String] and`
    `  (JsPath \ "abbreviaton").write[String]`
    ` )(unlift(Country.unapply))`

  `implicit val countryFormat: Format[Country] =`
    `  Format(countryReads, countryWrites)`
`}`

it throws: `Overloaded method value [apply] cannot be applied to  ((Long, String, String, Boolean, java.sql.Timestamp) =&gt; models.Country)`

when I try to create apply method on my companion object, it throws:

`reference to overloaded definition,
both method apply in object Country of type (id: Long, title: String, abbreviation: String, isActive: Boolean, createdAt: java.sql.Timestamp)models.Country
and  method apply in object Country of type (title: String, abbr: String)models.Country
match expected type ?`

Can I workaround this somehow, because It's natural that you have less fields for reading and more for writing

**Comment by marcospereira** [comment]
Hello @dsounded,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

Of course, if we decide that there is a bug, we can open an issue here. 😉

**Comment by dsounded** [comment]
@marcospereira I see, but could you give an answer is it possible to do in current `Play` realization ?
