### ISSUE TITLE
Progress monitoring of multipart/form-data POST requests in Play WS

### ISSUE THREAD

**Issue by david-bouyssie** [playframework/playframework#6181]
Since version 2.5.1 Play supports now post of multipart/form-data (https://github.com/playframework/playframework/issues/902).

This would be very useful if one could monitor the progress of data upload when doing such kind of post requests.

Could it be possible to have access to `onContentWriteProgress` callback or is it too complicated to interface it with the Play API ?
https://asynchttpclient.github.io/async-http-client/apidocs/com/ning/http/client/AsyncCompletionHandler.html#onContentWriteProgress%28long,%20long,%20long%29

**Comment by wsargent** [comment]
Hi @david-bouyssie there aren't any plans right now, but please feel free to submit a pull request.

**Comment by estsauver** [comment]
Hey there, 

I can take a crack at this soon. Any sense for what this api should look like? Right now it's returning a `Future[WSResposne]`, but I'd love some suggestions on the types that it should return.

~Earl

**Comment by david-bouyssie** [comment]
Hi !

Thank you for your answer Earl :D

I think that a a simple implementation could be to use attach a kind of ProgressAsyncHandler to the WSRequest just before calling the post method:

```
ws.url(url).withAsyncHandler(handler: ProgressAsyncHandler).post(...)
```

For a description of ProgressAsyncHandler, see: https://asynchttpclient.github.io/async-http-client/apidocs/com/ning/http/client/ProgressAsyncHandler.html

We should thus derive a type inspired from the asynchttpclient's ProgressAsyncHandler.

**Comment by schmitch** [comment]
that won't work since we don't send a `a File, String or FileInputStream` we use `ReactiveStreamsBodyGenerator` with full backpressure thats why we can't make any assumptions about the content that is coming. Thats why a signature generatore **can't** work.
For a Progress Handler you would **need** to know which data is coming **before** you send it. So either you need to manually input the size of the data which is akward on multipart-form data, however you actually know when a Publisher is consumed since the Subscriber will actually fire a onComplete which somehow could be intercepted when you fix ahc.

**Comment by david-bouyssie** [comment]
Thank you @schmitch for the explanations.

What do you mean by "which somehow could be intercepted when you fix ahc" ?

I agree with the fact that it is difficult to know the data size when the Request is fired. However I guess that we could compute the number of read bytes during the streaming operation ?

The onContentWriteProgress callback has 3 parameters:
    amount - The amount of bytes to transfer
    current - The amount of bytes transferred
    total - The total number of bytes transferred

The **amount** is thus the tricky part but **current** and **total** might be computed more easily.
If the request caller knows the data size he would be thus able to compute a percentage of progression. In the other case he will only have the number of read bytes, which could be used for instance to compute real time data transfer speed or anything else that could be useful for the caller.

So why not create another signature like `onContentWriteProgress(current: long, total: long)` ?

**Comment by schmitch** [comment]
@david-bouyssie you are wrong. The **amount**/**current** isn't the tricky part. it's the **total** who is tricky. You don't know the current total, as already mentioned. You would need to buffer the **whole** stuff to know it, which we don't.

You could add methods to the ``Subscriber`` which are telling you when the request is finished and what bytes he will write. i.e. http://www.reactive-streams.org/reactive-streams-1.0.0-javadoc/org/reactivestreams/Subscriber.html

**Comment by david-bouyssie** [comment]
@schmitch I was not thinking about maintaining all the bytes in memory but rather computing the **amount** value by summing the different data buffer lengths (**current** values), each time the IO stream is updated. Isn't it possible ?

However I was not aware that the `Subscriber.onComplete` callback was called before sending the bytes. In my mind the request was finished when all bytes were sent.

**Comment by schmitch** [comment]
is onComplete before all bytes are sent? that shouldn't happen normally.

As you've seen you don't have the total length at start of the progress (which you need) else you can't say you already have  30% or something.
You know where you are, but not where you need to go.

**Comment by david-bouyssie** [comment]
*is onComplete before all bytes are sent? that shouldn't happen normally.*
No, it was just a miss-understanding from me of the previous statement *when the request is finished and what bytes he will write* (I was disturbed by the use of the future).

*As you've seen you don't have the total length at start of the progress (which you need) else you can't say you already have 30% or something.
You know where you are, but not where you need to go.*
Yes I perfectly understand that it its difficult to compute a percentage value but I'm not sure that we should express the progress as a relative value (this computation could be delegated to the caller). As I said before the actual number of bytes that have been read at a given time point may be enough information for the caller.
So if we know where we are, maybe we could only return this value.

Don't you think that we could define a `readBytesCount` variable that would be updated just before the publisher send a new block of bytes (readBytesCount incremented with the previous bytes block length) or when the Subscriber fires an onComplete signal ?

**Comment by schmitch** [comment]
@david-bouyssie that is definitv possible however I doubt that it is a easy task. ;)

**Comment by wsargent** [comment]
I have an example of a custom body parser here: https://github.com/wsargent/play-fileupload-scala -- is this something you'd want progress monitoring in the parthandler?

**Comment by david-bouyssie** [comment]
If I understand your example it corresponds to an upload of a file from a webpage to the Play server. What I would like to do is to monitor the upload of a file from a given Play server to another Play server (or any equivalent HTTP server).

**Comment by cchantep** [comment]
No news there. Would be better to first discuss on the MailingList before reopening. Best regards.
