### ISSUE TITLE
Fix displaying runtime exception coming from Twirl template while running in development mode

### ISSUE THREAD

**Issue by gslowikowski** [playframework/playframework#6190]
### Play Version (2.5.x / etc)

2.4.0 -

 2.5.3

### Expected Behavior

In case of runtime exception in Twirl template in dev mode, Play! should render template fragment around the line which thrown the exception.

### Actual Behavior

Fragment of the Scala source generated from the template is shown. In other words, mapping from generated to original source does not work.

### Reproducible Test Case

For some reason I cannot attach zipped test project to this issue.

### Details

This functionality was broken by [this commit](https://github.com/playframework/playframework/commit/1dfaab4ce6563a2f54503b203be5276719c2f6fc)

Code before that change:

[PlayReloader.scala](https://github.com/playframework/playframework/blob/b64e3993658dfb85931d712d21987f1521015516/framework/src/sbt-plugin/src/main/scala/PlayReloader.scala#L138-156):

```scala
      def findSource(className: String, line: java.lang.Integer): Array[java.lang.Object] = {
        val topType = className.split('$').head
        currentAnalysis.flatMap { analysis =>
          analysis.apis.internal.flatMap {
            case (sourceFile, source) =>
              source.api.definitions.find(defined => defined.name == topType).map(_ => {
                sourceFile: java.io.File
              } -> line)
          }.headOption.map {
            case (source, maybeLine) =>
              play.twirl.compiler.MaybeGeneratedSource.unapply(source).map { generatedSource =>
                generatedSource.source.get -> Option(maybeLine).map(l => generatedSource.mapLine(l): java.lang.Integer).orNull
              }.getOrElse(source -> maybeLine)
          }
        }.map {
          case (file, l) =>
            Array[java.lang.Object](file, l)
        }.orNull
      }
```

Code after that change:

[PlayReload.scala](https://github.com/playframework/playframework/blob/1dfaab4ce6563a2f54503b203be5276719c2f6fc/framework/src/sbt-plugin/src/main/scala/PlayReload.scala#L35-37):

```scala
  def originalSource(file: File): Option[File] = {
    play.twirl.compiler.MaybeGeneratedSource.unapply(file).map(_.file)
  }
```

[Reloader.scala](https://github.com/playframework/playframework/blob/1dfaab4ce6563a2f54503b203be5276719c2f6fc/framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala#L341-348):

```scala
  def findSource(className: String, line: java.lang.Integer): Array[java.lang.Object] = {
    val topType = className.split('$').head
    currentSourceMap.flatMap { sources =>
      sources.get(topType).map { source =>
        Array[java.lang.Object](source.original.getOrElse(source.file), line)
      }
    }.orNull
  }
```

Here we have two bugs introduced:
- in `PlayReload.scala` in `map(_.file)` fragment `file` is the generated file (Scala), not the original (Twirl template)
- in `Reloader.scala` in `Array[java.lang.Object](source.original.getOrElse(source.file), line)` fragment `line` is line number in generated file, there is no code to map it to line number in original file

I will provide PR soon.

###Additional notes

IMO, [current solution introduced by that buggy commit](https://github.com/playframework/playframework/blob/1dfaab4ce6563a2f54503b203be5276719c2f6fc/framework/src/sbt-plugin/src/main/scala/PlayReload.scala#L30), with finding original source for every source file (from `sbt.inc.Analysis` object) after successful every compilation is **very** expensive, because it requires reading all files into memory (check `MaybeGeneratedSource.unapply` implementation). But this is not the right place to discuss it in details, I think.

It would be great to backport the fix to `2.4.x` and `2.5.x` branches.

**Comment by gmethvin** [comment]
I wonder if we can use/provide some generic source map representation so we don't need to depend directly on the twirl compiler here.

**Comment by gslowikowski** [comment]
I doubt. What does it mean "more generic". You find original sources eagerly, but you need source line mappings too. Would you load and store them too?
I thought about at least using lazy vals for `Source.original` and whatever additional data would be added there.
