### ISSUE TITLE
play-test 2.5.3 Scala route() fails when app is specified

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#6204]
I used this dependency, which transitively brought in `play-test` 2.5.3:

    "org.scalatestplus.play" %% "scalatestplus-play" % "1.5.1"

The following ([taken from this demo app on github](https://github.com/mslinn/multiproject/blob/master/modules/serviceA/test/controllers/serviceA/ServiceASpec.scala#L33-L40)) gives a deprecation warning; the warning suggests that the version of route be used that accepts an `app`. This code works fine despite the warning:

      val app = FakeApplication(path = modulePath)
      running(app) {
        route(FakeRequest(GET, "/a")).foreach { result =>
          status(result) must equal(OK)
          contentType(result) mustBe Some("text/html")
          contentAsString(result) must include ("Hello there")
        }
      }

When the route invocation is altered to incorporate `app`, it looks like this:

     route(app, FakeRequest(GET, "/a"))

... and fails at runtime with this error:

    Attempted to call materialize() after the ActorMaterializer has been shut down.

The same thing happens if `OneAppPerSuite` is used to define `app`.

**Comment by GitsMcGee** [comment]
Hi @mslinn. I'm curious why you closed this. I'm getting the exact same issue. Did you find a solution?

**Comment by mslinn** [comment]
Yes, I figured it out. Check out the link above
