### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH in play 2.5 scala production using sendFile

### ISSUE THREAD

**Issue by swoopster-sb** [playframework/playframework#6205]
```
Ok.sendFile(
        content = new java.io.File("data.jpg"),
        inline = true
      )
```
results in a empty response, producing net::ERR_CONTENT_LENGTH_MISMATCH in chome.

The response header seems fine:
```
Content-Disposition:inline; filename="data.jpg"; filename*=utf-8''data.jpg
Content-Length:175189
Content-Type:image/jpeg
```

but the content is empty.

Using play 2.5.3, scala production on linux

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

how to reproduce:

* create a new empty play-scala project using activator.
* change the HomeController.index to
```
  def index = Action {
    Ok.sendFile(content=new java.io.File("data.jpg"), inline=true)
  }
```
* get your favorite data.jpg in place
* change app secret (to make it run in production)
* compile for production `sbt stage`
* run `./target/universal/stage/bin/play-scala`
* open http://localhost:9000/ in browser

### Expected Behavior
image file should be sent

### Actual Behavior
empty response (0 bytes) received

Note: `sbt run` works fine, error only occurs on production (which is quite bad!)

**Comment by shkhln** [comment]
```
% cd /etc
% scala -Duser.dir=/home
Welcome to Scala version 2.11.7 (OpenJDK 64-Bit Server VM, Java 1.8.0_77).
Type in expressions to have them evaluated.
Type :help for more information.

scala> new java.io.File("passwd").getAbsolutePath
res0: String = /home/passwd

scala> new java.io.File("passwd").getAbsoluteFile.length
res1: Long = 0

scala> new java.io.File("passwd").length
res2: Long = 2711
```

**Comment by shkhln** [comment]
> File.length doesn't respect user.dir property

https://bugs.openjdk.java.net/browse/JDK-4117557

**Comment by marcospereira** [comment]
@shkhln is right here. 

While `File.length` gives the correct value to [set `Content-Length`](https://github.com/playframework/playframework/blob/2.5.3/framework/src/play/src/main/scala/play/api/mvc/Results.scala#L380-L407), the file could not be found to be read. When sending files like this (in other words, not using the `Assets` controller), it is your responsibility to ensure the file exists and is readable.

Changing the code to use an absolute path will works perfectly, so I'm closing this issue.

**Comment by shkhln** [comment]
I should probably clarify that in this case `user.dir` is being set by the Play startup script.

**Comment by swoopster-sb** [comment]
good point, didnt think of the possibility that the file wasn't found, since it got it's size correct.

using `environment.getFile("data.jpg")` solves the problem.

Thanks!
