### ISSUE TITLE
Enable netty access logs in play 2.5  application

### ISSUE THREAD

**Issue by nuwan1025** [playframework/playframework#6218]
### Expected Behavior
I need to write access logs through netty by making log.wire enabled. In our play version 2.4.3 application, we had following configurations and it did work.
In logback.xml:
   <logger name="org.jboss.netty.handler.logging.LoggingHandler" level="DEBUG" additivity="false">
        <appender-ref ref="ACCESS_FILE"/>
    </logger>

In application start additional configurations
-Dhttp.netty.log.wire=true

--------------------
Now we are upgrading the application to play 2.5.3 and the above configuration no longer works. So did the changes as per the documentation https://www.playframework.com/documentation/2.5.x/ProductionConfiguration .  
But it is not successful. Following are the changes made

In application.conf
play.server{
  provider="play.core.server.NettyServerProvider"
  netty{
    log.wire=true
  }
}

In logback.xml

    <appender name="ACCESS_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${application.home}/logs/access/access.log</file>
        
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${application.home}/logs/access/access-log-%d{yyyy-MM-dd}.%i.gz</fileNamePattern>
            <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                
                <maxFileSize>10MB</maxFileSize>
            </timeBasedFileNamingAndTriggeringPolicy>
            
            <maxHistory>7</maxHistory>
        </rollingPolicy>
        <encoder>
            <pattern>
                %date{yyyy-MM-dd HH:mm:ss.SSS ZZZZ} %message%n
            </pattern>
        </encoder>
    </appender>

    <logger name="access" level="INFO" additivity="false">
        <appender-ref ref="ACCESS_FILE"/>
    </logger>

Is there something to additionally to be done to enable access logs?

**Comment by wsargent** [comment]
log.wire will add a `io.netty.handler.logging.LoggingHandler` to the server:

```
if (logWire) {
  pipeline.addLast("logging", new LoggingHandler(LogLevel.DEBUG))
}
```

https://github.com/playframework/playframework/blob/master/framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala#L176

However, LoggingHandler delegates to an InternalLogger and it logs all events at a DEBUG level, as per the Javadocs: http://netty.io/4.0/api/io/netty/handler/logging/LoggingHandler.html

So you need to set <logger name="io.netty.handler" level="DEBUG"/> to turn up Netty's debug logger.

**Comment by nuwan1025** [comment]
Thanks Will for the answer...
I got the access logs working in our application. I will share the configuration.

In logback.xml: 

```
 <logger name="io.netty.handler" level="DEBUG" additivity="false">
        <appender-ref ref="ACCESS_FILE"/>
 </logger>
```
And passed `-Dplay.server.netty.log.wire=true` as an additional parameter at application start up.

***********************
I was trying to configure netty server in application.conf as per the documentation but it was not successful which forced me to pass it as a additional parameter. 

Following is the configuration that didnt work.
```
play.server{
  provider = "play.core.server.NettyServerProvider"
  netty {
    log.wire = true
  }
}
```

Any feedback on the reason for this issue is appreciated.

**Comment by nuwan1025** [comment]
In netty 4 access log format has changed. Earlier in Netty 3 WRITE event did not log the message body of application/json content type messages. Now it logs the message body. So the access log file size increases rapidly.
Is there a flag in netty server to stop logging body content?

**Comment by fortuneFelix** [comment]
>> And passed -Dplay.server.netty.log.wire=true as an additional parameter at application start up.

I had exactly the same problem. I was not able to specify this in my application.conf file:

play.server{
  provider = "play.core.server.NettyServerProvider"
  netty {
    log.wire = true
  }
}

This seems to be a unexpected issue = bug?!?

**Comment by wuservices** [comment]
I couldn't really get Netty logging to log anything for some reason even with the config here or @nuwan1025's great post https://nuwankblog.wordpress.com/2016/06/13/acess-logs-configurations-for-play-2-5/.

However, the filter at https://www.playframework.com/documentation/2.5.x/ScalaLogging seems more flexible and straightfoward anyways so that works!
