### ISSUE TITLE
Move Java forms to separate module

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#6221]
The original reason for creating the Play-Java module was to separate out Java forms/validation library and its dependency on Spring for validation. I think it makes sense to move the other Java wrappers back into the Play project and essentially rename Play-Java to Play-Java-Forms.

Then, perhaps instead of having it automatically added by the sbt plugin, we could require the user to explicitly add `javaForms` as a dependency.

**Comment by mkurz** [comment]
Done via #6559
