### ISSUE TITLE
[2.5.3 Java] Not possible to set infinite WS request timeout with stream()

### ISSUE THREAD

**Issue by albuch** [playframework/playframework#6225]
### Play Version (2.5.x / etc)

2.5.3
### API (Scala / Java / Neither / Both)

Java
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 8.1
### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle  JDK 1.8.0_92
### Library Dependencies

None
### Expected Behavior
1. Setting `setRequestTimeout(-1)`for a WSClient request and calling `stream()` should respect the timeout being infinite.
2. In the case of a timeout it should result in a Throwable being emitted to `whenComplete()`
### Actual Behavior

The following code reaches `.whenComplete()` without an exception after 120 seconds.

``` Java
    CompletionStage<StreamedResponse> events = ws.url("https://example.com/events")
            .setMethod("GET")
            .setHeader("Accept", "text/event-stream")
            .setRequestTimeout(-1)
            .stream();
    events.thenCompose(res -> {
        Source<ByteString, ?> responseBody = res.getBody();
        return responseBody.via(Framing.delimiter(ByteString.fromString("\n"), Integer.MAX_VALUE, FramingTruncation.ALLOW)).map(ByteString::utf8String).runForeach(data -> logger.info(data), materializer);
    }).whenComplete((done, throwable) -> {
        if (throwable != null) {
            logger.error(throwable.getMessage(), throwable);
        }
        logger.info("Done");
    });
```

When setting the timeout to `Integer.MAX_VALUE` the call doesn't timeout after 120 seconds.
When changing to `get()` instead of `stream()` the infinite setting seems to be respected. However this doesn't help with Server-Sent Events and Akka Streams. Might be related to #4846.

Is there a workaround to get an infinite event-stream processing with Play 2.5?

**Comment by wsargent** [comment]
Moved to https://github.com/playframework/play-ws/issues/153
