### ISSUE TITLE
Java Form.data should be a copyOnWrite Map

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#6232]
### Play Version (2.5.x / etc)

2.4.6
### API (Scala / Java / Neither / Both)

Java/Both
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

irrelevant
### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

irrelevant
### Expected Behavior

the 
    private final Map<String,String> data;
in
https://github.com/playframework/playframework/blob/d6c2673d91d85fd37de424951ee5ad9f4f4cce98/framework/src/play-java/src/main/java/play/data/Form.java
is a mutable data structure. 
the class itself first looks like a immutable class. People (e.g. me) are  expecting that changes (e.g. bindFromRequest() ) are returning a new instance and don't modify the old one. this way, its also perfectly save to store the bare/prototype form of the form as a constant like

private static final Form<MyDataDTO> PROTOTYPE = Form.form(MyDataDTO.class); 

and use it in the code like

form = PROTOTYPE.bindFromRequest(...)
### Actual Behavior

Because the instance#data is a mutable data structure, this class is not thread safe anymore. 
usage like mentioned in the "expected behaviour" leads to very hard to find bugs in multithreaded environments.

**Comment by marcospereira** [comment]
`bindFromRequest` actually creates a complete new `data` Map, as you can see here:

https://github.com/playframework/playframework/blob/3d47da5277dfbb0ecdc44ffda7b1b3322b535bb5/framework/src/play-java/src/main/java/play/data/Form.java#L152-L157

But I agree that exposing `data` via `data()` method, exposes the inner state to changes that can occur outside of the Form scope. The same is true for `errors` Map.

**Comment by peq** [comment]
I would suggest to at least fix this in the documentation. The class should not be documented as immutable, if it is not. 

From https://www.playframework.com/documentation/2.5.x/JavaForms:

> Tip: Form objects are immutable - calls to methods like bind() and fill() will return a new object filled with the new data.

Maybe change this to:

> Tip: Form objects are copy-on-write - calls to most methods (for example  bind() and fill()) will not change the state of the object and return a new object filled with the new data instead.

**Comment by marcospereira** [comment]
@domdorn and @peq,

Do you guys want to submit a PR to fix this?

**Comment by peq** [comment]
Would you prefer a fix in the documentation or in the code?

Fixing the code would probably not be backwards compatible.

**Comment by marcospereira** [comment]
@peq fix in the code and the necessary updates on documentation.

I think we can make it as much compatible as possible, but if not possible, we won't backport it to 2.5.x.

Thanks for taking care of this.

**Comment by mkurz** [comment]
+1 for code fix in the master branch

**Comment by mkurz** [comment]
Fixed via #6984, #7167, #6964 and #7168.
