### ISSUE TITLE
URL query param Option[List[String]] is always Some(List(...))

### ISSUE THREAD

**Issue by ozmad** [playframework/playframework#6236]
### Operating System (Ubuntu 15.10 )

Use `uname -a` if on Linux.
Linux oms 4.2.0-36-generic #42-Ubuntu SMP Thu May 12 22:05:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Paste the output from `java -version` at the command line.
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

### Library Dependencies
creating new "  6) play-scala"
--build.sbt:
name := """aaa"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.7"

libraryDependencies ++= Seq(
  jdbc,
  cache,
  ws,
  "org.scalatestplus.play" %% "scalatestplus-play" % "1.5.1" % Test
)

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. "Option" url query params should be "None" unless explicitly provided
2. adding params e.g: 
  controllers.CountController.count(p: Option[List[String]], s: Option[String])

### Actual Behavior

access the count url without params (http://localhost:9000/count) and print that params these are the values: 
  "p = Some(List()), s = None"

### Reproducible Test Case

1. just create a default 'scala-play" project with "activator new" and pick number 6.
2. modify the count route and controller: controllers.CountController.count(p: Option[List[String]], s: Option[String])
3. print the new params (or debug to see their values)
3. access "http://localhost:9000/count" 

Please provide a PR with a failing test.  

If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

**Comment by cchantep** [comment]
Hi,

I'm not sure binding a parameter as `Option[List[T]]` make sense, as in such context `Nil` list can considered as equivalent to `None`. If you want to bind an optional non-empty list, it needs better typing for me.

Would be nice to discuss first on the MailingList.

**Comment by ozmad** [comment]
Hi all,
@Cédric, Thanks for your reply.

What you says makes sense in some cases but in my case I feel that I am
loosing information on the way.

This is my scenario:
My Items has tags.
Using a list of tags in a query-string to filter results according to the
following rules:

   1. No tags-list at all -> no filter -> find all items (no matter what
   tags they have, if at all)
   2. List exists - find only items that contains all items in the list
   (empty list is a valid filter to collect items with empty tag-lists)


BR,
Oz.

On Sat, Jun 11, 2016 at 11:28 PM, Cédric Chantepie <notifications@github.com

**Comment by cchantep** [comment]
Hi, as indicated this kind of question is to be asked on the [MailingList](https://groups.google.com/forum/#!forum/play-framework) (not clearly an issue/defect, not an actionable feature request). Best regards

**Comment by ozmad** [comment]
Thank you. I will ask it there.
