### ISSUE TITLE
WS/OAuth calls signed with OAuthCalculator not being properly signed & therefore rejected

### ISSUE THREAD

**Issue by ChickenSniper** [playframework/playframework#6251]
### Play Version

2.5.3 (but also not working in 2.4.2)
### API

Scala
### Operating System

Windows 10 (also tested on MacOSX & CentOS Linux)
### JDK

Oracle 1.8.0_77
### Library Dependencies

N/A
### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.
1. We extended the code example found here for OAuth 1.0a: https://www.playframework.com/documentation/2.5.x/ScalaOAuth
2. The first part, using the consumer key & secret to get an access token & secret works without issue.
3. The second part, signing a WS request using OAuthCalculator fails.
### Actual Behavior

We have tested with both Twitter & Intuit Quickbooks Online.
1. As outlined before, we are able to get a valid access token & secret.  We know this because it works when we use the token/secret obtained from out Play app making an API call on https://www.hurl.it/ and other OAuth 1.0a testing tools.
2. The part that fails is the actual WS.url("url").sign(OAuthCalculator(KEY, credentials)).get, it seams the 
### Reproducible Test Case

Source code example here: https://github.com/ChickenSniper/Play-OAuth1a-Tset

To test against Twitter...run route /authQBO.  The API response is
{"errors":[{"code":89,"message":"Invalid or expired token."}]}
although the token was just generated!

To test against Intuit Quickbooks Online...run route /authTwitter.  The API response is
<ReconnectResponse xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://platform.intuit.com/api/v1">
  <ErrorMessage>OAuth Token rejected</ErrorMessage>
  <ErrorCode>270</ErrorCode>
  <ServerTime>2016-06-17T16:40:06.0266294Z</ServerTime>
</ReconnectResponse>
although the token was just generated!

**Comment by wsargent** [comment]
Moved to https://github.com/playframework/play-ws/issues/155
