### ISSUE TITLE
`import play.api.db.Databases` from tutorial doesn't work

### ISSUE THREAD

**Issue by dsounded** [playframework/playframework#6254]
https://www.playframework.com/documentation/2.5.x/ScalaTestingWithDatabases

Anyway, I've got `object Databases is not a member of package play.api.db`, any updates ?

**Comment by wsargent** [comment]
Please use the mailing list or gitter for application issues: the bug tracker is for bugs in the project.

As mentioned in the gitter channel, you probably don't have jdbc in your libraryDependencies:

https://www.playframework.com/documentation/2.5.x/ScalaDatabase#configuring-jdbc-connection-pools
