### ISSUE TITLE
Kotlin support for auto-reload

### ISSUE THREAD

**Issue by rattrayalex** [playframework/playframework#6259]
Kotlin is a new JVM language from JetBrains that aims to be 100% compatible with Java. It is growing in popularity with web developers with a scripting language background (like myself) and may provide an avenue for new users to Play.

Currently, changes to Kotlin files do not trigger the auto-reload feature of Play, which is a major selling point of the framework, especially for those coming from dynamic languages. Otherwise, Kotlin does appear to work with Play at a basic level.

If there is a way to accomplish this currently (without outside tools such as JRebel), please see http://stackoverflow.com/q/37915583/1048433 and close this issue.

**Comment by cchantep** [comment]
Hi, thanks for the feedback. As indicated in the [guide](https://github.com/playframework/playframework/blob/master/.github/ISSUE_TEMPLATE.md), this is better to be discussed on the [MailingList](https://groups.google.com/forum/#!forum/play-framework). Best regards.
