### ISSUE TITLE
Calling Action with parse.anyContent body parser with empty body and content type application/json throws exception

### ISSUE THREAD

**Issue by KarlSjostrand** [playframework/playframework#6266]
### Platform

* Play: 2.5.4
* API: Scala
* JDK: 1.8.0_91
* Operating system: Windows 10

### Expected Behavior

As far as I can understand, the standard allows for empty requests with specified content type. Therefore, we expect a successful response when calling an Action with an empty body and content type set to `application/json` and an otherwise well-formed request. This should work also with the following Action:
`Action(parse.anyContent) { request => Ok() }`

### Actual Behavior

Letting Play pick a suitable body parser using `parse.anyContent` based on content type and using `application/json` as content type *and* supplying an empty body leads to an Akka exception `Invalid Json: No content to map due to end-of-input at [Source: akka.util.ByteIterator]` and a Bad Request status. .

### Reproducible Test Case

Self contained project with tests: https://github.com/KarlSjostrand/play-bodyparser-bug

**Comment by schmitch** [comment]
Actually I guess a empty Json content is at least {} and not ""

**Comment by gmethvin** [comment]
The HTTP standard does allow empty bodies with a content type, but whether that body is valid depends on the specification for that content type. An empty byte string is not a valid JSON document according to the JSON spec, nor is it valid in many other content types.

So I still think the correct behavior is to return a 400 error. The only thing that I might improve is what the error message actually looks like when the body is empty. It would be nice to show a more meaningful JSON parsing error.

Also keep in mind that an empty body is different from no body. It seems like your client should really be sending no body at all.

**Comment by KarlSjostrand** [comment]
Thanks for making clear how the HTTP and JSON standards are reconciled in this case. What confused us was what we saw as an inconsistency in Play's `Action` API and this is what we tried to demonstrate in the supplied test application. The following controller method returns 200 with said request,
`def index() = Action { Ok("index") }`
while this method returns 400
`def custom() = Action(parse.anyContent) { request => Ok("custom") }`.
It seems we are only *specifying* a parser in the latter case; it is not evident that parsing is taking place since we make no reference to the body. 

As a side note, the issue emerged when we were using Action composition where several types of requests were wired through `Action(parse.anyContent)` in conjuction with a client API for JSON which had content type set to `application/json` globally. We had to find a workaround stripping the content type header to make this work.

A potential improvement (if I understand `ContentTypes.scala` correctly) would be if `anyContent` would return the `empty` body parser for requests with no body.

**Comment by schmitch** [comment]
There is no "potential" improvment since `parser.default` will actually give a EmptyBody for HTTP methods that don't define a body. and if you set "application/json" than there should be at least a empty json document. else you could create your own parser, for your edge cases.

**Comment by schmitch** [comment]
What *maybe* would be possible would be a parse.anyContentOption and parse.jsonOption. Which would give a Option[JsValue] or a Option[AnyContentAsJson] etc..

**Comment by KarlSjostrand** [comment]
Thanks for explaining this. I was sure this was not the intended behavior, but I wasn't fully up to speed with the various available body parsers and the effect of specifying a parser in an Action method. This closes the issue for me.
