### ISSUE TITLE
play_evolutions.applied_at should use "timestamp with timezone" in PostgreSQL instead of "timestamp without timezone"

### ISSUE THREAD

**Issue by pathikrit** [playframework/playframework#6279]

**Comment by mkurz** [comment]
What is your use case for the need of timezone?
Also, if we change the date type, we should change it for every db-engine, not just PostgreSQL.

**Comment by mkurz** [comment]
If you want to provide a pull request - that's the code you need to change: https://github.com/playframework/playframework/blob/2.5.4/framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L334-L399

**Comment by cchantep** [comment]
Hi, it would be nice to first discuss it on the [MailingList](https://groups.google.com/forum/#!forum/play-framework).
