### ISSUE TITLE
Improve assets configuration

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#6292]
Currently, assets are configured using keys like `assets.*`, but these should probably be in the play namespace, e.g. `play.assets.*` Also, we should add the configuration keys to reference.conf.

**Comment by mkurz** [comment]
Just a note: Whoever puts `assets.checkForMinified` in the `reference.conf` please don't set it to `true` or `false` - just comment it out or set it to `null` - so we can be sure the default behaviour will be invoked (which is false for dev and true for non-dev modes)

**Comment by gmethvin** [comment]
Yes, the new convention now is to set to null if there is some special default behavior, and add a comment explaining what null means in the reference.conf.

**Comment by kunalkanojia** [comment]
Created a PR for the task - #6348
