### ISSUE TITLE
Allow multiline method call definiitions in routes file

### ISSUE THREAD

**Issue by mdedetrich** [playframework/playframework#6299]
Play 2.5.3
Scala API
Mac OSX 10.11.5
JDK 1.8.0_77-b03

### Expected Behavior
The ability to define method calls in the `conf/routes` file to go over multiple lines. Currently you have to the following which uses a huge amount of horizontal real estate

```scala
GET     /more_than_21               controllers.AsyncController.moreThan21(one: Option[String], two: Option[String], three: Option[String], four: Option[String], five: Option[String], six: Option[String], seven: Option[String], eight: Option[String], nine: Option[String], ten: Option[String], eleven: Option[String], twelve: Option[String], thirteen: Option[String], fourteen: Option[String], fifteen: Option[String], sixteen: Option[String], seventeen: Option[String], eighteen: Option[String], nineteen: Option[String], twenty: Option[String], twenty_one: Option[String], twenty_two: Option[String])
```

### Actual Behavior

You can define something like this in `/app/routes`

```scala
GET     /more_than_21               controllers.AsyncController.moreThan21(one: Option[String],
                                                                           two: Option[String],
                                                                           three: Option[String],
                                                                           four: Option[String],
                                                                           five: Option[String],
                                                                           six: Option[String],
                                                                           seven: Option[String],
                                                                           eight: Option[String],
                                                                           nine: Option[String],
                                                                           ten: Option[String],
                                                                           eleven: Option[String],
                                                                           twelve: Option[String],
                                                                           thirteen: Option[String],
                                                                           fourteen: Option[String],
                                                                           fifteen: Option[String],
                                                                           sixteen: Option[String],
                                                                           seventeen: Option[String],
                                                                           eighteen: Option[String],
                                                                           nineteen: Option[String],
                                                                           twenty: Option[String],
                                                                           twenty_one: Option[String],
                                                                           twenty_two: Option[String])
```

**Comment by schmitch** [comment]
Actually I don't see a reason for that since there are two other ways of defining such things:
1. Custom QueryStringBindable
2. Reading request.queryString
3. Using a form

**Comment by mkurz** [comment]
I agree with @schmitch 
You are probably better off with a QueryStringBindable.
Java: https://www.playframework.com/documentation/2.5.x/RequestBinders
Scala: https://www.playframework.com/documentation/2.5.x/ScalaRequestBinders#PathBindable

**Comment by mdedetrich** [comment]
The issue more comes into play if you use something like play-swagger (where you make swagger documentation in `routes` file). Its then kind of weird that you have the definition in another place.

Also it may not even be a case of having a lot of query parameters, you could just have a few query parameters but you could have the same problem because your route name is really long.

**Comment by mdedetrich** [comment]
The other issue in our case is we use `QueryStringBindable` for the `routes` and apparently you can't reuse that for `Forms` (or at least I haven't found a way how, there appears to be no way of making a mapping from a `QueryStringBindable`), although this may be another issue

**Comment by schmitch** [comment]
if you already have a `Form` you can just use the form.

**Comment by mdedetrich** [comment]
@schmitch This is for query parameters through a GET request, I though that `Form` is only for post requests?

**Comment by schmitch** [comment]
Actually a Form Binds to everything. You can bind a Form to Query parameters.
Actually a Form either needs `form.bind(data: Map[String, String])` or `bindFromRequest()(implicit request: play.api.mvc.Request[_])` or `bindFromRequest(data: Map[String, Seq[String]])`. And inside `bindFromRequest`:

```
  def bindFromRequest()(implicit request: play.api.mvc.Request[_]): Form[T] = {
    bindFromRequest {
      (request.body match {
        case body: play.api.mvc.AnyContent if body.asFormUrlEncoded.isDefined => body.asFormUrlEncoded.get
        case body: play.api.mvc.AnyContent if body.asMultipartFormData.isDefined => body.asMultipartFormData.get.asFormUrlEncoded
        case body: play.api.mvc.AnyContent if body.asJson.isDefined => FormUtils.fromJson(js = body.asJson.get).mapValues(Seq(_))
        case body: Map[_, _] => body.asInstanceOf[Map[String, Seq[String]]]
        case body: play.api.mvc.MultipartFormData[_] => body.asFormUrlEncoded
        case body: play.api.libs.json.JsValue => FormUtils.fromJson(js = body).mapValues(Seq(_))
        case _ => Map.empty[String, Seq[String]]
      }) ++ request.queryString
    }
  }
```

So as you can see request.queryString will be added to the `Form`.

**Comment by cchantep** [comment]
Hi, I think the [MailingList](https://groups.google.com/forum/#!forum/play-framework) a better to place to discuss it, rather than this issue tracker. Best regards.

**Comment by mdedetrich** [comment]
@schmitch Thanks for the tip, forgot that you could use forms with query parameters. Unfortunately one of the issues with forms is the 22 field limit, and unfortunately you can't really get around this with nesting since you are dealing with query params (which are designed to be flat)

**Comment by schmitch** [comment]
@mdedetrich Yeah the 22 field limit is  a non goal, I still don't see a reason to make the parser more complicated just to have long fields. Actually a form isn't "flat". You can do nesting without having "nesting" since you can just use bindFromRequest(request.queryString) if the query string is something like:
nested.name1 it will be inside the nested element of the form so mostly you can rewrite the query strings to assign to a nested form. Also 22 query parameters is really really a lot and I don't think it's a good design to have a function which takes more than 22 parameters either.

**Comment by mdedetrich** [comment]
> Also 22 query parameters is really really a lot and I don't think it's a good design to have a function which takes more than 22 parameters either.

This is actually for a search request, so its understandable why it can have more than 22 query parameters (and it isn't something that nesting can help solve in this case). I have had this argument with the guys at Slick as well, and the "If you have more than 22 parameters than you have a design problem" isn't a good argument. The number 22 is arbitrary (albeit its set by the Scala compiler), and there are certain problems where its perfectly legitimate to have more than 22 parameters.

In any case, I have had this issue with Json Read formats, but they have a workaround which you can use (i.e. split up your read formats into blocks with less than 22 fields, and then you can combine them with the `~` application syntax. Unfortunately you can't do this with forms at least from what I can see).

**Comment by dirkhillbrecht** [comment]
Multiline routes file syntax for long routes also makes sense when it comes to modelling REST GET queries with lots of parameters. It makes no fun at all to put them all together with their type definitions in one line...

**Comment by df3n5** [comment]
Why was this closed? This seems like a reasonable request.

**Comment by mdedetrich** [comment]
> Why was this closed? This seems like a reasonable request.

Yeah, the routes file in some of our play projects is taking up the entire horizontal real estate on the screen and there isn't any way to address this.

I would rather the Play project not use a custom routes file syntax and instead use proper scala code with some maco. The routes file is a mistake and it always creates problems in other areas (i.e. red code in Intellij)
