### ISSUE TITLE
[doc] incorrect documentation on composing Actions

### ISSUE THREAD

**Issue by dportabella** [playframework/playframework#6300]
The [doc](https://www.playframework.com/documentation/2.5.x/ScalaActionsComposition#custom-action-builders) tells:

> Since `ActionBuilder` provides all the different methods of building actions, this also works with, for example, declaring a custom body parser:
> ```
> def submit = LoggingAction(parse.text) { request =>
>   Ok("Got a body " + request.body.length + " bytes long")
> }
> ```

`LoggingAction(parse.text)` uses `ActionBuilder.apply` which creates `new Action {...}`, so the resulting `submit` is not a `LoggingAction` but an `Action`, and so this action builder does not work as suggested.

**Comment by schmitch** [comment]
Actually it's still a `LoggingAction`.
ActionBuilder.apply will call `async` which calls `invokeBlock`:
https://github.com/playframework/playframework/blob/d6c2673d91d85fd37de424951ee5ad9f4f4cce98/framework/src/play/src/main/scala/play/api/mvc/Action.scala#L426

The documentation is totally correct. If you need any help regarding your code etc. Please ask on the Mailing List.
