### ISSUE TITLE
How can I reuse the dependency downloaded before?

### ISSUE THREAD

**Issue by ice-melon** [playframework/playframework#6307]
I am new to Play and  from the Rails Community .
When I activator run a new project, the same dependencies like sbt, scala complier will be downloaded. While I live in china and it takes about 2 hour to finish the task. Could I reuse the dependencies in other projects?   Or How can I change the addresses of these dependencies? Since there are some good  maven mirrors in China.

**Comment by gmethvin** [comment]
@ice-melon Can you post this with some of your suggestions on the [mailing list](https://groups.google.com/forum/#!forum/play-framework)? It would be good to start a discussion there on how we can improve the experience for users with slow or throttled connections.

**Comment by ice-melon** [comment]
I find a great tool called [REPOX](https://github.com/Centaur/repox) to cache the dependencies. It can also set the priority of different sources. This tool is great for both team and individual development.
