### ISSUE TITLE
play.api.data.Form vs play.data.Form when using form helpers

### ISSUE THREAD

**Issue by nitzantomer** [playframework/playframework#6313]
When using the java api and trying to create a form using the form template helpers, there's a contradiction between the scala Form and the java Form.

A simple example:

Controller
```
public class HomeController extends Controller {
	@Inject
	FormFactory formFactory;

	public Result form() {
		final Form<FormData> myform = formFactory.form(FormData.class).bindFromRequest();
		return ok(form.render(myform));
	}

	public static class FormData {
		@Constraints.Required()
		@Constraints.MinLength(5)
		private String field1;

		public FormData() {}

		public void setField1(String field1) {
			this.field1 = field1;
		}

		public String getField1() {
			return this.field1;
		}
	}
}
```

Template
```
@(myform: Form[controllers.HomeController.FormData])

<div>
	@helper.form(action = routes.HomeController.form()) {
		@helper.inputText(myform("field1"))
	}
</div>
```

Routes:
```
GET /form controllers.HomeController.form
POST /form controllers.HomeController.form
```

In the controller I get the following error:
> 'render(play.api.data.Form<FormData>)' cannot be applied to 'play.data.Form<FormData>'

If I change the form in the template to the java `Form`:
`@(myform: play.data.Form[controllers.HomeController.FormData])`

Then I can not use the form helper functions, as this:
`@helper.inputText(myform("field1"))`

Has this error:
> Type mismatch, expected: Field, actual: Form.Field

I haven't found a way to go around this problem, and so it seems that when using the java api it isn't possible to use the form template helpers. 

Play version: 2.5.4 with the java api
Java: Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
OS: OS X 10.11

**Comment by mkurz** [comment]
Are you using a play-java project?
Do you have
```
lazy val root = (project in file(".")).enablePlugins(PlayJava)
```
in your `build.sbt`?
What Play version are you using?

**Comment by nitzantomer** [comment]
@mkurz 
Never mind, turns out that it's an issue with IntelliJ that shows these errors, but when I run the application it seems to work just fine.
I just haven't even tried to run it because the ide complained and I thought it won't compile/run.

I wonder why the ide doesn't seem to like it, but I better check that with them.
Thanks.
