### ISSUE TITLE
What time the Play3 will come?And is it be friendly to Java?

### ISSUE THREAD

**Issue by yuhuanxi** [playframework/playframework#6314]
I am a Chinese Java coder,around with me , few people knew PlayFramework,but when I first meet it,I love it.I think it is greate!

And now I am very concerned about Play3,many people says that it is not friendly to Java，If it true,oh,that may be a sad story.Can somebody tell something about Play3?

Thank you!

**Comment by marcospereira** [comment]
Hello @yuhuanxi,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to ask/discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

**Comment by yuhuanxi** [comment]
Ok,thank you so much
