### ISSUE TITLE
Playframework not started correctly when I use Mysql connector 6.0.x

### ISSUE THREAD

**Issue by almothafar** [playframework/playframework#6319]
Inside the build.sbt I added the following library for dependencies: 
`"mysql" % "mysql-connector-java" % "6.0.3"`

And nothing changed in the application.conf I get the following in bamboo tasks:

```
13-Jul-2016 18:41:55	Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
13-Jul-2016 18:41:55	[info] - application - Creating Pool for datasource 'default'
13-Jul-2016 18:41:55	[warn] - com.zaxxer.hikari.util.DriverDataSource - Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
```

Then : 
`Failing task since return code of [./ci/ci-start-all.sh] was 1 while expected 0

If I change `db.default.driver` to  `com.mysql.cj.jdbc.Driver` I simply get no warning bust still getting the last fail message, its seems that loading `com.zaxxer.hikari.util.DriverDataSource` with warning.
`

**Comment by wsargent** [comment]
Hi @almothafar the bug tracker is for tracking bugs in Play itself -- please ask general questions and support on the mailing list @ https://groups.google.com/forum/#!forum/play-framework
