### ISSUE TITLE
Provide a default set of filters

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#6324]
In order to encourage better security practices, it would be nice if we enabled `SecurityHeadersFilter` and `CSRFFilter` by default in Play.

The question is how best to do this. If Play configures its own `HttpFilters` class, then if a user overrides that, those filters will be disabled. One option is to do something similar to modules and have `play.filters.enabled` and `play.filters.disabled` in configuration. Or maybe we only allow them to add filters with configuration, and to remove you have to override the `HttpFilters` completely.

**Comment by wsargent** [comment]
+1 for play.filters.enabled, but I remember there being concerns about inserting into the middle of a list in HOCON.  It'd be nice if you could do "insert before element" and "insert after element" as well.

**Comment by schmitch** [comment]
I actually didn't liked the design of `play.modules.enabled`.
Especially when play uses that people need at least disable two filters if they don't need them.

Especially for REST style Apps that have another frontend app or directly a JS Gui which never uses any cookies at all, these two aren't helpful.

I think the best way would be to have a way to disable all at once and still set your own.
Or maybe like Django define a HOCON which has a Ordered Array:
```
play.filters = [
"play.filters.headers.SecurityHeadersFilter",
"play.filters.csrf.CSRFFilter"
]
```
But I guess since this is HOCON and not real code like the Django settings.

But even then the more things we put into HOCON the more we move away from "Convention over Configuration".

**Comment by gmethvin** [comment]
@schmitch You're right it doesn't always make sense to have them, but it does in a lot of cases, and it would be nice if we could have new Play users start with a fairly secure configuration and provide an option to change it than the other way around. I guess this could also be done by changing the starter templates to enable them by default.

If you're not using cookies, I actually think the default CSRF configuration won't check those requests, so it's fine. The only thing you might need to change is the `Content-Security-Policy`, if you're including external scripts.

In general the goal is to have more secure defaults, hopefully in a way that is fairly unobtrusive to new users. I'm open to other ideas on how to do it, though.

**Comment by marcospereira** [comment]
> I guess this could also be done by changing the starter templates to enable them by default.

+1 for this idea. By the way, this is something we can do just right now (even without releasing a version I suppose).

**Comment by gmethvin** [comment]
@marcospereira Yeah, maybe that is the right approach. That is how we suggest people get started anyway. We can also document why we chose the defaults in application.conf, and mention it in the 2.6 migration guide.

**Comment by wsargent** [comment]
This is enabled in the play-scala-seed and play-java-seed templates:

* https://github.com/playframework/play-scala-seed.g8/blob/master/src/main/g8/app/Filters.scala
* https://github.com/playframework/play-java-seed.g8/blob/master/src/main/g8/app/Filters.java

**Comment by wsargent** [comment]
Closed with https://github.com/playframework/playframework/pull/7023
