### ISSUE TITLE
Customization for Jackson ObjectMapper (Scala)

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#6333]
`Json.parse` and `Json.stringify` currently don't allow any customization for how values are converted to and from `JsValue`. In some cases one may want to do that. For example, one may want to pretty-print the JSON value in dev mode but not in production.

**Comment by gmethvin** [comment]
Moved to playframework/play-json#9

**Comment by mkurz** [comment]
Thanks to #12662 also the Play JSON objectmapper used in `Json.parse`, `Json.stringify`, etc. can now be configured via the `pekko.serialization.jackson.play {}` [config key](https://github.com/playframework/playframework/blob/523a401fc59e3fbeec0ac865f75360c9309677fd/core/play/src/main/resources/reference.conf#L1028). Plus: A Play app can now also configure the Play JSON standalone specific settings [via `play.json {}`](https://github.com/playframework/playframework/blob/523a401fc59e3fbeec0ac865f75360c9309677fd/core/play/src/main/resources/reference.conf#L990-L1025) (which when using Play JSON standalone can only be set via system properties).
