### ISSUE TITLE
META-INF/resources duplicated

### ISSUE THREAD

**Issue by fliptoo** [playframework/playframework#6345]
Play bundle all resources into the META-INF/resources of the main code jar meanwhile assets.jar is holding totally same content as META-INF/resources. There are few related issue at discussion group but end up with no answer. 

Resources folder size can be very huge and it is not make sense to having duplicated resources when doing update/batching.

Can we have a solution on this issue?

**Comment by marcospereira** [comment]
Is this a duplicated of #5765?

**Comment by fliptoo** [comment]
Yes, it is duplicated. #5765 is there since 28 Feb, i would like to know is there any update regarding this behaviour?

**Comment by cchantep** [comment]
Duplicate
