### ISSUE TITLE
WSClient send request twice

### ISSUE THREAD

**Issue by gregu** [playframework/playframework#6347]
Sometimes WSClient send request twice. Im not sure why, but i suppose the reason is this part of code: _thenApply(response -> ok(response.getBody()));_

Here is whole Action:

	public CompletionStage<Result> send() {
		ObjectNode json = Json.newObject();
		json.put("username", SmsApiController.user);
		json.put("password", SmsApiController.pass);
		json.put("phone", SmsApiController.phone);
		json.put("text", "message server sms "+new Date().toString());
		
	    return ws.url(SmsApiController.serwerSMS).post(json).thenApply(response -> ok(response.asJson()));
	    
	}

Play 2.5.x
API JAVA
Mac OS X 10.11.5
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by marcospereira** [comment]
How are you verifying that the request was sent twice?

**Comment by gregu** [comment]
Two different sms services sent me the same sms twice. I have no idea how to reproduce this situation.

**Comment by gmethvin** [comment]
Then what makes you think this is an issue with Play WS? Have you verified that the `post` method can be called once and the request is actually sent twice?

**Comment by studiodev** [comment]
You can use https://requestb.in/ (for example) to inspect the request(s) made by you ws client.

**Comment by gregu** [comment]
I made one request - call method from url (open url in browser).
Info from service provider: "We got  two request, first logged at July 21st 2016 18: 45: 23.392 and second at July 21st 2016 18: 45: 23.421. It seems that this is a problem with your software."

It happens from time to time, so its really difficult to debug.

**Comment by gregu** [comment]
I think requestb.in isn't good tool for this kind of test, because response very quick and there is very small lag.
I think long time between request and response is a reason of making request twice, but still don't know how to reproduce.

**Comment by gmethvin** [comment]
@gregu Do you have logs showing that the The `send` method was called only once, then?

Or is it possible that your action is being called twice? That might happen if you're using a GET for this action and the browser is preloading the action.

I think a better forum for this would be the mailing list. We'd be happy to help but with the information you've given it's not clear this is a bug.
