### ISSUE TITLE
BeanList deferred Problem

### ISSUE THREAD

**Issue by yuhuanxi** [playframework/playframework#6349]
Hi,nice people,today I have encountered a problem like that:

> I use the OneToMany Annotation, and I search the result from DB,
> It comes the problem

**

> Room{id=1, roomName='room 1', students=BeanList deferred }
> Student{id=1, room=Room{id=1, roomName='room 1', students=BeanList deferred }, name='student 1'}

**
my version of play is 2.5.4 and ebean is 3.0.0。

here are my java code

**Room Model**

`
@Entity
public class Room extends Model {

    @Id
    public Long id;

    public String roomName;

    @OneToMany
    public List<Student> students;

    @Override
    public String toString() {
        return "Room{" +
                "id=" + id +
                ", roomName='" + roomName + '\'' +
                ", students=" + students +
                '}';
    }

    public static Finder<Long, Room> finder = new Finder<Long, Room>(Room.class);
}
`

**Student Model**

`
@Entity
public class Student extends Model {

    @Id
    public Long id;

    @ManyToOne
    public Room room;

    public String name;

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", room=" + room +
                ", name='" + name + '\'' +
                '}';
    }

    public static Finder<Long, Student> finder = new Finder<Long, Student>(Student.class);
}
`
**The Controller Method**
`
public Result findStudentById(Long id) {

        Room room = Room.finder.byId(id);

        System.out.println(room);

        return ok(Json.toJson(room));
    }`

**Comment by gmethvin** [comment]
Hi @yuhuanxi,

This is a tracker for reporting bugs in Play. It seems to me this is about Ebean, not Play, and you're asking for help rather than trying to report a bug. Perhaps you should try asking on the [ebean mailing list](https://groups.google.com/forum/#!forum/ebean).
