### ISSUE TITLE
Redirect does not use fragment when constructing URL string

### ISSUE THREAD

**Issue by rvangsgaard** [playframework/playframework#6360]
`play.api.mvc.Results#Redirect`

Current
```
  def Redirect(call: Call): Result = Redirect(call.url)
```
should be something like
```
  def Redirect(call: Call): Result = Redirect(call.toString)
```
or `call.url` should take fragment into consideration.

**Comment by mkurz** [comment]
Maybe `.withFragment(...)` is what you are looking for? See #4152

**Comment by rvangsgaard** [comment]
My issue is concerning Redirect https://github.com/playframework/playframework/blob/2.4.x/framework/src/play/src/main/scala/play/api/mvc/Results.scala#L858

With #4152 in mind, we should use `call.path` instead of `call.toString` in my example.

**Comment by rvangsgaard** [comment]
Changing Call.url() to include the fragment would fix it, and still be correct. What do you think?

**Comment by schmitch** [comment]
Actually you are right and it should actually just be `call.path`.

**Comment by rvangsgaard** [comment]
I will give it a try.

What is your opinion on letting `call.url` include fragment? It seem more correct, but it may break something.

**Comment by schmitch** [comment]
actually a url will probably also include the Fragment, so its more correct. But it's harder to do. But breakage is not a problem for Play 2.6, if you want to backport it to older version you should probably just use `call.path`.

Also a simple unit test would just need to construct a Response and check the Location header. 
Something like that:
```
    "redirect with a fragment" in {
      Results.Redirect(Call("GET", "", "")).header.headers.get(HeaderNames.LOCATION) must_== Option("Location: Your url")
    }
```

inside `play.mvc.ResultSpec`

**Comment by rvangsgaard** [comment]
#6363
