### ISSUE TITLE
Support for Guice's requireAtInjectOnConstructors configuration option

### ISSUE THREAD

**Issue by mikem** [playframework/playframework#6384]
I wanted to turn on Guice's `requireAtInjectOnConstructors()` configuration option in my project. I tried doing this in my module:

```scala
import com.google.inject.AbstractModule

class Module extends AbstractModule {

  override def configure() = {
    binder().requireAtInjectOnConstructors()
  }

}
```

and by extending `GuiceApplicationBuilder`:

```scala
import play.api.ApplicationLoader
import play.api.inject.guice.{ GuiceApplicationBuilder, GuiceApplicationLoader }

class CustomApplicationLoader extends GuiceApplicationLoader {

  override def builder(context: ApplicationLoader.Context): GuiceApplicationBuilder = {
    initialBuilder.requireAtInjectOnConstructors()
  }

}
```

With either of those, Play throws an exception when trying to inject some internal dependencies. See below for the detailed stack trace.

### Play Version (2.5.x / etc)

2.5.4

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.11.6

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
$ java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

### Steps to Reproduce

1. Enable `requireAtInjectOnConstructors()` in one of the two ways described above
2. Execute `sbt run` to launch the development server
3. Visit http://localhost:9000

*Expected Behavior:* I can see the root page of my app.

*Actual Behavior:* The server renders an error with the following:

```
! @7115jkk8o - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

1) Explicit @Inject annotations are required on constructors, but play.api.inject.DefaultApplicationLifecycle has no constructors annotated with @Inject.
  at play.api.inject.BuiltinModule.bindings(BuiltinModule.scala:42):
  Binding(class play.api.inject.DefaultApplicationLifecycle to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

2) Explicit @Inject annotations are required on constructors, but play.api.http.NoHttpFilters has no constructors annotated with @Inject.
  at play.utils.Reflect$.bindingsFromConfiguration(Reflect.scala:53):
  Binding(interface play.api.http.HttpFilters to ConstructionTarget(class play.api.http.NoHttpFilters)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
```

### Reproducible Test Case

Here's a repo you can use to reproduce the issue: https://github.com/mikem/play-guiceannotationrequired -- it's an app created with `activator new guiceannotationrequired play-scala` and [`requireAtInjectOnConstructors()` enabled](https://github.com/mikem/play-guiceannotationrequired/commit/4c226e3f01659bd65df0a96fc9fc7ff92c1aa57b).

---

I also posted this as [a question on StackOverflow](http://stackoverflow.com/questions/38734550/how-do-i-configure-guice-in-play-framework-to-require-an-inject-annotation-for).

**Comment by gmethvin** [comment]
@mikem We apparently missed a few empty constructors that we should've added @Inject to. That adds those and a test.

**Comment by gmethvin** [comment]
(see #6385)

**Comment by mikem** [comment]
Thanks @gmethvin!
