### ISSUE TITLE
DB Connection leak in evolutions when there is a problem (inconsistent state) 

### ISSUE THREAD

**Issue by rajendrag** [playframework/playframework#6386]
Play Version (2.5.x)
API (Scala)
Operating System (MacOS 10.11.6)
JDK (Oracle 1.8.0_65)

### Expected Behavior
When the evolutions are inconsistent state (when state = 'applying_up'), play throws an error "play.api.db.evolutions.InconsistentDatabase" from `checkEvolutionsState()` of EvolutionsApi. In this curcumstance, we are not closing the connection. 

### Actual Behavior
The method should be called within "try" block of "databaseEvolutions" (EvolutionsApi.scala:124) as the connection will be closed in finally.

**Comment by mkurz** [comment]
Fixed via #6391
