### ISSUE TITLE
Trampoline execution context should be available somewhere

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6390]
### Play Version (2.5.x / etc)

master

### API (Scala / Java / Neither / Both)

Scala

### Expected Behavior

Trampoline should be accessible to end user applications

### Actual behavior

The `trampoline` object was moved from Iteratees to Streams, but was made play private in the last commit, so it's not accessible by applications in master:

https://github.com/playframework/playframework/blob/master/framework/src/play-streams/src/main/scala/play/api/libs/streams/Execution.scala#L31

If you look in 2.5.x, it was available:

https://github.com/playframework/playframework/blob/2.5.x/framework/src/iteratees/src/main/scala/play/api/libs/iteratee/Execution.scala#L3

There isn't a specific mention of trampoline in the commit:

https://github.com/playframework/playframework/commit/77983111f2d91a17e7f97aa6ae01e0ce010201bb

So I think it should probably exist somewhere.  My preference would be play.api.libs.concurrent.Execution:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/libs/concurrent/Execution.scala

There is a reference to it under play.core.Execution, but that is also play private:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/core/Execution.scala#L22

**Comment by schmitch** [comment]
Do you think that's a good idea?
I mean if somebody is lazy (and I guess there will be some lazy people) who schedule anything on the trampoline it could probably block the whole application. if he does something bad / wrong.

**Comment by wsargent** [comment]
I think there's a difference between making it accessible and making it advisable, and trampoline is something that you might reasonably want in filter logic, for example.

There's not much we can do about lazy people.  Someone is truly lazy, they'll import ExecutionContext.Implicits.global and spawn threads all over the place...

**Comment by gmethvin** [comment]
I would just add in the scaladoc there what its purpose is and be clear that it shouldn't be imported everywhere.

**Comment by schmitch** [comment]
Actually there is also: https://groups.google.com/forum/#!msg/scala-internals/QgtKugpqUlk/llVXveEuFAAJ
That discusses if scala should ship one by default.

**Comment by wsargent** [comment]
Following up on this, it turns out that a trampoline context has problems in a user context, because you can easily run into deadlocks in a production.  Here's a quote from the initial discussion adding trampoline context:

https://groups.google.com/d/msg/play-framework/hf1HP_68PvA/ZwyHmdudQhQJ

“Never use a trampoline execution context for mapping a future from a WS call, this is dangerous especially if you’re doing blocking in the callbacks. The trampoline execution context won’t have any significant performance improvement on your code unless you’re deep in iteratee code.”

So... given that trampoline is not widely known and won't lead to performance advantages in most cases, closing.

**Comment by domdorn** [comment]
For everyone stumbling over this in search for a trampoline (e.g. when you want to subclass `PlayBodyParsers`), you can access the trampoline in your code like this (I'm on Play 2.7.x):
```
  override def json[A](implicit reader: Reads[A]): BodyParser[A] =
    BodyParser("json reader") { request =>
      implicit val ec: ExecutionContext = controllers.Execution.trampoline // <-- here
      json(request) mapFuture {
        case Left(simpleResult) =>
          Future.successful(Left(simpleResult))
        case Right(jsValue) =>
          jsValue.validate(reader) map { a =>
            Future.successful(Right(a))
          } recoverTotal { jsError =>
            val msg = s"Json validation error ${JsError.toFlatForm(jsError)}"
            myErrorHandler.createBadResult(jsError)(request) map Left.apply
          }
      }
    }
```
