### ISSUE TITLE
Define static TRUE/FALSE values for JsBoolean

### ISSUE THREAD

**Issue by crumbpicker** [playframework/playframework#6399]
As I understand the current implementation of JsBoolean (a case class and not a value class) it wraps a boolean value each time the JsBoolean constructor is called. 
I think it could be great if the JsBoolean companion object could provide static references to TRUE/FALSE values.

```
object JsBoolean {
  val TRUE = play.api.libs.json.JsBoolean(true)
  val FALSE = play.api.libs.json.JsBoolean(false)
}
```

**Comment by gmethvin** [comment]
I would prefer `val True` and `val False`, or maybe `JsTrue` and `JsFalse` to make it more clear.

**Comment by kunalkanojia** [comment]
Created a quick PR to close this. #6528

**Comment by crumbpicker** [comment]
Nice ! Thank you :)
