### ISSUE TITLE
[doc] Better future timeout documentation

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6400]
### Play Version (2.5.x / etc)

2.5.x

### API (Scala / Java / Neither / Both)

scala

### Actual Behavior

Looking at the play.api.libs.concurrent.Promise class, the timeout methods are deprecated:

https://playframework.com/documentation/2.5.x/api/scala/index.html#play.api.libs.concurrent.Promise$@timeout[A](message:=>A,duration:scala.concurrent.duration.Duration)(implicitec:scala.concurrent.ExecutionContext):scala.concurrent.Future[A]

"Use akka.pattern.after(duration, actorSystem.scheduler)(Future(message)) instead".

The "message" parameter name here is meaningless, this is a call by name parameter so it's more accurate to say "block".  More importantly, this is only half of the puzzle -- you need to use this in conjunction with Future.firstCompletedOf to get something useful back out.

```
  private def withTimeout[A](result: => Future[Result]): Future[Result] = {
    val timeoutResult = akka.pattern.after(timeoutDuration, actorSystem.scheduler) {
      val msg = s"Timeout after $timeoutDuration"
      Future.failed(new TimeoutException(msg))
    }(actorSystem.dispatchers.defaultGlobalDispatcher)
    Future.firstCompletedOf(Seq(result, timeoutResult))
  }
```

Either we need to document this or may want to use https://github.com/johanandren/futiles#timeouts---markattafutilestimeouts for better Future control, given most people aren't going to know this...

**Comment by schmitch** [comment]
I wouldn't pull in a library for that.

However `firstCompletedOf` will still run the `Future` no matter if the timeout happened or not.

I mean we could at least look for a library that's good enough and tell people that they should use it (would be a little bit opinionated). But for 2.6.x I plan to reduce as much unnecessary libraries as possible and just adding a wrapper for another library is probable not a lot of help.

**Comment by wsargent** [comment]
I'd rather document it rather than pull another library in, absolutely.
