### ISSUE TITLE
Header Status code always return 0 on Safari browser

### ISSUE THREAD

**Issue by sidodinh88** [playframework/playframework#6403]
Hi everybody,
I'm newbie with PlayFramework and occur issues as follow:
- I execute request Ajax from html page to Controller,
- Controller handle and return StatusHeader (example: return `status(1001)`)
- If i working on Chrome, Firefox. It's work well, i receive status code is `1001` on response object of ajax request. But, if i working on Safari, status code receive always is `0`.

I hope, someone can help me to resolve this problem.
Thanks

**Comment by marcospereira** [comment]
Hey @sidodinh88,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.
