### ISSUE TITLE
playGenerateSecret Shows No Output if logLevel := Level.Warn

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#6412]
The `playGenerateSecret` output should not be sent to a logger. Instead, `playGenerateSecret` should send output to the default output mechanisms for SBT tasks.

**Comment by gmethvin** [comment]
Why is this a problem? You don't really need to see it print what the secret is, and there may be reasons you don't want to. I think using the logger makes sense.

**Comment by mslinn** [comment]
`playGenerateSecret`'s only action is to display a newly generated secret. The secret is not stored anywhere. Therefor if you cannot read the secret, `playGenerateSecret` performs no purpose. Perhaps you were thinking of `playUpdateSecret`?

Loggers are for conditional output. `playGenerateSecret` must always generate output. I agree that it might make sense to send the output to `stdout`, so it could be redirected ... but that output must always be generated.

**Comment by gmethvin** [comment]
@mslinn Okay, in the docs we do suggest using generateSecret to actually display the secret, so in that sense there is a problem.

The other way it's used, though, is simply as an SBT task that generates the secret and returns it, which is also used in updateSecret. In the updateSecret case the generated secret doesn't have to be shown.

**Comment by mslinn** [comment]
Correct. That is why I filed a separate issue for updateSecret's unrelated problem.
