### ISSUE TITLE
Deprecate play.api.libs.concurrent.Execution.Implicits

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6425]
### Play Version (2.5.x / etc)

master

### API (Scala / Java / Neither / Both)

Scala

### Actual Behavior

It's common to get access to Play's default execution context by doing the following:

```
import play.api.libs.concurrent.Execution.Implicits._
```

The problem is, this relies on `Play.current` under the hood -- it actually calls out to `app.actorSystem.dispatcher`.

A better way to pull in the default application context is through injection using `(implicit ec: ExecutionContext)`:

``` scala
class Samples @Inject() (wsClient: WSClient)(implicit ec: ExecutionContext) {
  def someAsyncAction = Action.async {
    wsClient.url("http://www.example.com").get().map { response =>
      Results.Ok("The response code was " + response.status)
    }
  }
}
```

So we should deprecate the import and suggest an implicit class parameter instead.

**Comment by wsargent** [comment]
Also see https://github.com/playframework/playframework/issues/5441 and https://github.com/playframework/playframework/issues/6390

**Comment by schmitch** [comment]
We would need to add it to BuiltInComponents. I'm not a static DI guy, but I guess a lot of people would just complain.

**Comment by wsargent** [comment]
Adding it to BuiltinComponents is fine.  it's essentially an alias to `actorSystem.dispatcher` anyway, so if you can get to the actorSystem, you can get to the dispatcher...

**Comment by gmethvin** [comment]
It's already in `BuiltInComponents` actually: https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/Application.scala#L253

**Comment by schmitch** [comment]
yeah I basically looked at the 2.5.x sources.
