### ISSUE TITLE
Randomly getting 401 responses from requests with DIGEST auth, after WS moved to AsyncHttpClient 2

### ISSUE THREAD

**Issue by Leammas** [playframework/playframework#6467]
### Play Version (2.5.x / etc)

2.5.4

### API (Scala / Java / Neither / Both)

Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux dev2 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

### Expected Behavior

There should be two requests made under the cover in case of Digest auth. First to get cnonce, second with auth data. isUsePreemptiveAuth flag should be set to false according to [this comment](https://github.com/AsyncHttpClient/async-http-client/issues/792#issuecomment-69026231)

### Actual Behavior

When performing Digest auth request with isUsePreemptiveAuth set to true, it randomly results in 

```
org.asynchttpclient.netty.handler.intercept.Unauthorized401Interceptor - Can't handle 401 as auth was already performed
```

I can attach the whole log if needed

### Reproducible Test Case

Tests in PR below

For standalone reproduction with running server, see https://github.com/Leammas/play-ws-digest-bug-exposed

**Comment by arjunchhabra** [comment]
I'm encountering this same issue in play-java-ws_2.11:2.5.14. Can this fix be applied to the java library as well?

**Comment by Leammas** [comment]
I've introduced changes to the Java API in the same PR. I'm not sure if it's in the Play release or only in  the play-ws release.
