### ISSUE TITLE
Insufficient details about play service bindings

### ISSUE THREAD

**Issue by ishwar1987** [playframework/playframework#6479]
Hi,
I read from url  
https://www.playframework.com/documentation/2.5.x/Deploying-CloudFoundry#Connecting-to-Cloud-Foundry-Services
 for auto configuration cloud foundry  provides for play framework. but i am not able to see the cloud.properties in cloud foundry . does any body has any idea. how to enable auto configure in cloud foundry for play framework?
Let me know if there is an document for this.
Thanks in advance

**Comment by cchantep** [comment]
Hi, please use the [Mailing list](https://groups.google.com/forum/m/#!forum/play-framework) to ask for help (this tracker is for confirmed issue). Best regards.
