### ISSUE TITLE
[Play 2.5 Java] Varying code execution sequence in DEV vs PROD.

### ISSUE THREAD

**Issue by danielmorozoff** [playframework/playframework#6483]
### Play Version (2.5.x / etc)
Play 2.5.3

### API (Scala / Java / Neither / Both)
Java

### Operating System MacOS 10.11.6
Darwin Hostname 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

### JDK 
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

### Problem
Issue with running code in DEV and PROD modes- behaviors are supposed to be the same. 

Specifically, it seems that Controller.class instantiation time differs in the 2 modes when it comes to running startup code. 
When instantiating in DEV code works as expected AbstractModule -> Controller.class . In PROD, Controller classes are instantiated before AbstractModule (Startup code) is run after the Controller.class is instantiated.

### Expected  vs Actual Behavior
```
/** startup class set in application.conf **/
public class StartupModule extends AbstractModule {
	@Override
	protected void configure() {
		bind(OnStart.class)
			.asEagerSingleton();
	}	
}


public class OnStart{
   OnStart(){
     //STARTUP CODE SHOULD RUN HERE 
   }
}

/** Controller class **/
public class SomeController extends Controller{

   public SomeController(){
    //CONTROLLER INSTANTIATION CODE
   }
}
```
Expected execution flow should be 
StartupModule -> OnStart -> SomeController

--Works in DEV
--Does not wok in PROD. Flow is
SomeController -> StartupModule ->OnStart

**Comment by gmethvin** [comment]
@danielmorozoff You're relying on undefined behavior. If two components don't depend on each other (e.g. one is injected into the other), no instantiation order is defined. If your controller relies on some other actual component, it should generally injected into the controller, thereby ensuring the dependency is always created first.

Assuming you're using Guice, the specific reason you see that behavior in dev mode is that `.asEagerSingleton` forces it to be instantiated eagerly, and Play's router (which depends on controllers) is still instantiated lazily in Dev mode. In Prod, everything is instantiated eagerly.

If you'd like to discuss more about your specific problem, let's do so on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).

**Comment by danielmorozoff** [comment]
Thanks responding on the mailing list. I have a few questions on why this design paradigm was chosen, and how you guys see future development in this direction.
