### ISSUE TITLE
Update Linux installation path upto bin

### ISSUE THREAD

**Issue by cparmar1274** [playframework/playframework#6486]
https://www.playframework.com/documentation/2.5.x/Installing#MacOS-/-Unix

Export path mentioned in doc is not valid. It should be upto bin directory
Currently mentioned path :   export PATH=/path/to/activator-x.x.x:$PATH
Should be updated to    :    export PATH=/path/to/activator-x.x.x/bin:$PATH

**Comment by gamebusterz** [comment]
The export path has already been updated so this issue can be closed.

**Comment by mkurz** [comment]
Fixed via f13f6aa73279e5ed78755bab5a6e30d76927291f (cherry picked from #6655)
