### ISSUE TITLE
Playframework + Akka: avoid excuting scheduled tasks when shutdown application

### ISSUE THREAD

**Issue by almothafar** [playframework/playframework#6488]
### Are you looking for help?

I have issue that could be a bug, or a config? not sure, but I tried to play around config and searched many documentations with nothing to help, I have issue with scheduler that I start when the play application server start, but once application got shutdown, its execute the scheduler even if its not the time to execute.

I posted in stackoverflow no help for it, you can see details, also I believe it could be bug :  http://stackoverflow.com/questions/37771194/playframework-akka-how-to-avoid-excuting-scheduled-tasks-executed-when-shutdo

### Play Version 
* 2.5.4

### API 
* Java

### Operating System 
* Windows 10 & Red Hat

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
* Oracle 1.8.0_X ( tried many updates, from 91 to 101)
* OpenJDK Server VM (build 25.101-b13, mixed mode)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Start scheduler when play application is started
2. Scheduler working while application is up.
3. Once the application is shutting down, the scheduler must not be executed at all, except if its already executing time.

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

1. Start scheduler when play application is started
2. Scheduler working while application is up.
3. Once the application is shutting down, the scheduler is executing before the application start to shutdown.

### Reproducible Test Case

```
@Singleton
public class OnStartup {

    @Inject
    public OnStartup(final ActorSystem system) {
        startScheduler(system);
    }

    private void startScheduler(final ActorSystem system) {
        startImagesCleanupScheduler(system);
        Logger.info("Schedulers started");
    }

    private void startImagesCleanupScheduler(ActorSystem system) {
        system.scheduler().schedule(
                Duration.create(0, TimeUnit.MILLISECONDS), //Initial delay
                Duration.create(1, TimeUnit.DAYS),     //Frequency 1 days
                () -> {
                    //int rows = imageService.cleanupInactiveImages();
                    rows = 1;
                    Logger.info(String.format("%d inactive unused images cleaned from db", rows ));
                },
                system.dispatcher()
        );
    }

}
```

Then create module: 
```
public class OnStartupModule extends AbstractModule {
    @Override
    public void configure() {
        bind(OnStartup.class).asEagerSingleton();
    }
}
```

in application.conf : 

`play.modules.enabled += "modules.OnStartupModule"
`

When I deploy new version and restart application, the log will print the following (note the first line):

```
[info] - application - 1 inactive unused images cleaned from db
[info] - application - Shutting down connection pool.
[info] - application - Creating Pool for datasource 'default'
...
[info] - application - Schedulers started
[info] - play.api.Play - Application started (Prod)
```

**Comment by schmitch** [comment]
That's not a bug in play and is described in the Akka Docs:

http://doc.akka.io/docs/akka/current/scala/scheduler.html#From_akka_actor_ActorSystem
