### ISSUE TITLE
Serious memory leak in 2.5.[5-6]

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#6491]
### JDK Oracle
```
java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

### Actual Behavior

On 2 separate play apps we see the same behaviour since upgrading to 2.5.5, also 2.5.6 did not fix this

This first picture shows an app where memory growing all the time after 2.5.4 -> 2.5.5 upgrade on 22 aug
Memory still growing linearly with 2.5.6 on 25 aug
Issue fixed after reverting to 2.5.4
(no other changes except changing play version)

![image](https://cloud.githubusercontent.com/assets/161305/17988237/3262b312-6b25-11e6-8649-b1d77dfe1b05.png)

Other application that was upgraded 2.5.4 -> 2.5.5 (and back to 2.5.4 in the end)

![image](https://cloud.githubusercontent.com/assets/161305/17988051/f542ce6e-6b23-11e6-97ca-551ca541dbb7.png)

I have no idea what is causing it but seeing this on 2 different play apps after upgrade can hardly be a coincidence.

**Comment by wsargent** [comment]
Unfortunately, there's a number of things it could be, because many of Play's underlying library dependencies were updated in 2.5.5.  If you can run a load test against your application with a memory profiler, that would really help track down the issue.

**Comment by gmethvin** [comment]
Well, it could be related to one of the dependencies we updated (maybe akka?). You can try downgrading to the versions in 2.5.4 and see if you have the same problem.

Other than that, nothing sticks out at me as an obvious cause of a memory leak.

**Comment by francisdb** [comment]
We did downgrade and both version are back to normal, the first graph is an app that handles proxying / balancing
I might try to find the cause but won't be for this week

**Comment by schmitch** [comment]
Actually Netty has had a memory regression. But it's not a memory leak per se, just "more" memory.
http://netty.io/news/2016/07/27/4-0-40-Final-4-1-4-Final.html

what he can try is setting the following:
```
  val netty = "4.0.40.Final"
libraryDependencies ++= Seq(
    "io.netty" % "netty-codec-http" % netty,
    "io.netty" % "netty-handler" % netty,
    "io.netty" % "netty-codec" % netty,
    "io.netty" % "netty-transport" % netty,
    "io.netty" % "netty-buffer" % netty,
    "io.netty" % "netty-common" % netty
)
```

**Comment by francisdb** [comment]
Well, from the first chart you can clearly see that the whole system starts with more memory allocated, so could be related.

**Comment by francisdb** [comment]
@schmitch on first sight play 2.5.6 + netty 4.0.40.Final does not have the leak, but let me report a final verdict later today

**Comment by francisdb** [comment]
![image](https://cloud.githubusercontent.com/assets/161305/18034752/c8419ec6-6d45-11e6-92ba-bec0fa67c7aa.png)

Hmm, still different memory use profile for play 2.5.6 + netty 4.0.40.Final and looks like slow leak. Will have to dig in with a profiler

**Comment by schmitch** [comment]
as already said it's not a memory leak. the memory get's garbage collected. so there is no leak.
A leak would mean that the memory will never been gc'd and the VM will crash after a while.

**Comment by francisdb** [comment]
Euh, it actually crashed with OOM Exception on 25 aug (2.5.5). This chart shows multiple days with multiple versions. The only version where memory is not constantly growing is 2.5.4 (until 22 aug) but I understand this needs more investigation from my side.

**Comment by francisdb** [comment]
Feel free to close this until I provide more details

**Comment by schmitch** [comment]
Just a question does it generated a hs_err_pid?

**Comment by francisdb** [comment]
If I remember correctly the play app just stopped responding but there was no real jvm crash

This was the error we got
```
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3236)
    at java.lang.StringCoding.safeTrim(StringCoding.java:79)
    at java.lang.StringCoding.access$300(StringCoding.java:50)
    at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:305)
    at java.lang.StringCoding.encode(StringCoding.java:344)
    at java.lang.String.getBytes(String.java:918)
    at akka.util.CompactByteString$.apply(ByteString.scala:564)
    at akka.util.ByteString$.apply(ByteString.scala:50)
    at play.api.mvc.Codec$$anonfun$javaSupported$1.apply(Results.scala:294)
    at play.api.mvc.Codec$$anonfun$javaSupported$1.apply(Results.scala:294)
    at play.api.http.DefaultWriteables$$anonfun$writeableOf_JsValue$1.apply(Writeable.scala:95)
    at play.api.http.DefaultWriteables$$anonfun$writeableOf_JsValue$1.apply(Writeable.scala:95)
    at play.api.http.Writeable.toEntity(Writeable.scala:20)
    at play.api.mvc.Results$Status.apply(Results.scala:377)
    at controllers.ResourceController$$anonfun$series$1$$anonfun$apply$8$$anonfun$apply$9.apply(ResourceController.scala:79)
    at controllers.ResourceController$$anonfun$series$1$$anonfun$apply$8$$anonfun$apply$9.apply(ResourceController.scala:78)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Success.map(Try.scala:237)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
```

**Comment by schmitch** [comment]
Actually I've been running our application the whole night on a demo server and doing `watch -n 1 "wrk -t6 -c400 -d30s http://localhost:999/list/endpoint"` without any `-Xmx` and the memory didn't OOM'd the server at any point. the GC always kicked in and released a bunch of memory.
After that I've did a 1 hour test with `-Xmx` against the same endpoint and it didn't OOM, too.

The endpoint didn't do too many just, 3 Queries against a PostgreSQL database (1 authorization query, 1 count query and 1 select limit 20 offset 0 query) against a materialized view with ~4000 rows.
I couldn't find any leak and had yourkit evaluation running the whole time.

**Comment by marcospereira** [comment]
There is a new release of Netty: http://netty.io/news/2016/08/29/4-0-41-Final-4-1-5-Final.html

@francisdb could you please use [`-XX:+HeapDumpOnOutOfMemory`](http://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html#BABFJDIC) to generate a dump we can analyze later?

**Comment by francisdb** [comment]
@marcospereira Redeployed the service with `-XX:+HeapDumpOnOutOfMemory` and the jvm-not-exiting issue fix https://github.com/playframework/playframework/pull/6522

**Comment by francisdb** [comment]
I'm having a hard time reproducing this, generating load does not seem to introduce a steeper curve but only temporary peaks after which mem usage falls back to the slowly growing curve.
@avdv I see you also mentioned this ticket, care to share your findings?

**Comment by timohirt** [comment]
Same here.

![image](https://cloud.githubusercontent.com/assets/2502070/18345444/cf9371bc-75bb-11e6-922b-c6e5d8da53b8.png)

We updated to Play 2.5.6 on August 31. As you can see, memory consumption goes up from that date. Then on September 7 three services running on separate machines crashed one after another in the  same order in which they were deployed. 

They died with the same exception as @francisdb posted above.

After restart memory consumption still goes up and then I switched back to Play 2.5.4 yesterday night. now it seems to be back to normal.

![image](https://cloud.githubusercontent.com/assets/2502070/18345687/cc287e22-75bc-11e6-9ddf-9deef5362c8f.png)

**Comment by schmitch** [comment]
@timohirt als already suggested. Run with `-XX:+HeapDumpOnOutOfMemoryError` and send the Heap Dump to us.

**Comment by avdv** [comment]
> I see you also mentioned this ticket, care to share your findings?

Unfortunately, I cannot add much to the discussion. We got warnings about memory and swap usage by our monitoring tool after upgrading a few services from 2.5.4 to 2.5.6.

Services running with 2.5.6 would occupy much more heap memory (>500MiB) than the 2.5.4 counterparts (~150MiB).

There was no LEAK report from Netty in the logs and a heap dump triggered the garbage collection and memory usage went back to normal. There was no OOM exception in our case.

--- 
Oh, after I wrote the above, I just tried to re-produce the behaviour again, using Netty 4.0.39.Final and I noticed a *huge* spike in heap memory usage doing a `HEAD` request as opposed to when doing a normal GET.

We're making those HEAD requests regularly as part of the monitoring on all our environments.

Does that ring a bell, @francisdb?

**Comment by francisdb** [comment]
@adv tried getting a steeper curve with lots of HEAD requests but did not make a difference. Are you able to reproduce the leak in a short timeframe?

**Comment by avdv** [comment]
No :disappointed:. I let it run the whole night and apart from the spike at the beginning, there seems to be no memory problem on my machine. weird.

**Comment by godenji** [comment]
Not much to offer other than "same here" -- 2.5.4 to 2.5.6 upgrade has caused a large increase in memory usage, just a matter of time before OOME.

Going to downgrade production to 2.5.4, will try to reproduce 2.5.6 issue on staging server.

CentOS 6.7
Java 1.8.0_102

**Comment by schmitch** [comment]
Actually just using more memory is not a memory leak per se.

What's more important is, that it's impossible to actually take this serious when the only provided information is a "version upgrade to 2.5.6" and a Memory Screenshot.
Important Information will be a Heap Dump, what things you are using Java API / Scala API, JDBC, JPA, Cache, whatever, did you upgraded netty..

**Comment by francisdb** [comment]
Sure, trying to get to that OOM heap dump but it takes a lot of time as there is yet to find a way to accelerate the memory growth from this issue. The first time we had a OOM we did not have `-XX:+HeapDumpOnOutOfMemoryError` on and the vm did not actually crash because of #6522.

**Comment by godenji** [comment]
Running a heap dump via Eclipse MAT, leak detection report points to:

> 761 instances of "io.netty.util.Recycler$Stack", loaded by "sun.misc.Launcher$AppClassLoader @ 0xf0000208" occupy 25,892,592 (29.42%) bytes. 

No idea if this is normal behavior, but perhaps this could be a starting point wrt to investigating the source of the problem.

**Comment by godenji** [comment]
In case issue is in fact related to netty util.Recycler, here's a recent [github issue](https://github.com/netty/netty/issues/5521) that may be of interest.

**Comment by schmitch** [comment]
Since Recycler was changed in 41 you could try it out:
```
val nettyVersion = "4.0.41.Final"
libraryDependencies ++= Seq(
    "io.netty" % "netty-codec-http" % nettyVersion,
    "io.netty" % "netty-handler" % nettyVersion,
    "io.netty" % "netty-codec" % nettyVersion,
    "io.netty" % "netty-transport" % nettyVersion,
    "io.netty" % "netty-buffer" % nettyVersion,
    "io.netty" % "netty-common" % nettyVersion
)
``

**Comment by francisdb** [comment]
This is a Yourkit screenshot from the dump I took after the OOM reported previously
(default Play 2.5.6, no Jetty version overrides)

![image](https://cloud.githubusercontent.com/assets/161305/18411614/36bcea38-777b-11e6-8b41-b93273699665.png)

**Comment by francisdb** [comment]
This from a system halfway through the available memory

![image](https://cloud.githubusercontent.com/assets/161305/18411776/de17cbb0-777e-11e6-887e-52c571d0dcfe.png)

![image](https://cloud.githubusercontent.com/assets/161305/18411770/ca2d5f20-777e-11e6-8953-174f8e6cead6.png)

**Comment by francisdb** [comment]
@schmitch now redeploying with Netty 4.0.41.Final

**Comment by francisdb** [comment]
Looks promising so far:

![image](https://cloud.githubusercontent.com/assets/161305/18412938/69e9b722-779b-11e6-9ce5-f90406493d27.png)

**Comment by schmitch** [comment]
You need to fire burst load to trigger that error I guess.

**Comment by francisdb** [comment]
As explained before, traffic bursts / heavy load do not influence the the slow memory growth. That's why it was hard to reproduce this issue in a short timeframe.

Anyway I have been putting heavy load on the service the last 3 hours (GET/HEAD/POST). Cpu is at 80% but does not influence memory use.

Sticking to Netty `4.0.41.Final` for now

**Comment by schmitch** [comment]
be aware that if you have a url with `%20` in it that it will fail on Netty 4.0.41.Final. It's fixed on the 2.5.x branch but we didn't make a revision yet.

**Comment by francisdb** [comment]
Ok, thanks for the pointer. Will let this run until the end of the weekend to be sure this is fixed and drop back to `2.5.4` on Monday.

**Comment by edouardKaiser** [comment]
Not much to offer right now, but same for us, we are reverting to Play `2.5.4`

**Comment by igor-ye** [comment]
Also got OOM error in prod after upgrading from 2.4 to 2.5.6 Found constant leaking of scala.concurrent.forkjoin.ForkJoinTask[] and java.util.concurrent.ForkJoinTask[]
Tried suggested fix with Netty 4.0.41.Final but no luck. Only downgrading to 2.5.4 resolved the issue.

**Comment by godenji** [comment]
While this issue is perhaps correctly labeled as "needs-verification", everyone in this thread has at minimum seen a large increase in memory usage. Further, well before an OOME occurs there's a significant increase in GC events (seen as short period saw tooth graph in Visual GC) which in turn cause increased application latency and CPU load.

Today's heap dump shows:
> 5,606 instances of "io.netty.util.Recycler$Stack", loaded by "sun.misc.Launcher$AppClassLoader @ 0xf0000208" occupy 192,495,920 (55.14%) bytes. 

Something's not right -- if Netty 4.0.41 does indeed solve the issue I'd be more than happy to play guinea pig on a 2.4.7 release ;-)

**Comment by gmethvin** [comment]
@francisdb I'm going to release 2.5.7 with the new netty version. Does the problem appear to be fixed for you.

**Comment by francisdb** [comment]
@gmethvin This is a view of our app for the last 4 days, On 10 sept in the afternoon we switched to Netty `4.0.41.Final`. 

![image](https://cloud.githubusercontent.com/assets/161305/18453698/c9169eda-7940-11e6-895a-b00ace33a205.png)

I have intermittently been running different kinds of load tests. Memory went up few times but we have not seen any OOM issues. Memory most of the time flattens out instead of constantly growing.

Took another heap dump just now

![image](https://cloud.githubusercontent.com/assets/161305/18454661/dfe1dbfc-7945-11e6-9ccd-d53125375a57.png)

![image](https://cloud.githubusercontent.com/assets/161305/18454767/81b2ce28-7946-11e6-9d90-1558b6094f0e.png)

If I understand this correctly the memory currently in use is mainly stuff waiting to be garbage collected

**Comment by francisdb** [comment]
So I guess this can be closed as `2.5.7` is on it's way

**Comment by godenji** [comment]
@gmethvin great, given that the Netty team advises users to avoid 4.0.39 releasing 2.5.7 with latest Netty version should nip this problem in the bud.

btw, HikariCP just [released new version](https://groups.google.com/forum/#!topic/hikari-cp/yZ44iLH7t9s) with some bug fixes, might be worth bundling in with 2.5.7?

**Comment by gmethvin** [comment]
Well, it's usually safe to upgrade to patch releases in your app without a problem. For Netty we needed to fix an issue in the URI encoding/decoding to make it work properly in Play.

**Comment by easel** [comment]
I've been running into weird memory issues seemingly related to leaked ForkJoinTasks as well. Upgrading to Play 2.5.7 is looking good so far. Thanks for tracking this down =p

**Comment by godenji** [comment]
@easel 2.5.8 is actually the latest now 😄 and play (netty) leak has indeed been resolved -- steady, predictable memory usage for over a week now.

**Comment by sloanSeven** [comment]
under zero load i'm seeing memory issues in 2.6 after a couple hours. i'm re-running now without ever actually hitting the restful api. but my current app is just returning some mock data.

**Comment by richdougherty** [comment]
Hi @sloanSeven, since you're seeing this in 2.6 can you please create a separate issue? Please include more info like Java version, heap size, how to reproduce,  etc. If you're not confident this is a Play issue then you may wish to discuss it on the mailing list first in case anyone has any suggestions on how to resolve it.

**Comment by sloanSeven** [comment]
my suggestion is to use any other framework. i'm very confident its play. no i have zero interest in a mailing list.

**Comment by sloanSeven** [comment]
an odd environment to die in , why is play not aws friendly?

**Comment by sloanSeven** [comment]
ok

**Comment by sloanSeven** [comment]
play dies after running on aws for 4 hours. with zero traffic.

**Comment by easel** [comment]
@sloanSeven it sounds like you're experiencing a different issue than this one. With play 2.6.11 I've got multiple boxes with multiple-week uptimes and stable memory usage under load. In order to help you out, we'll need a new ticket with more specific details and probably a minimized reproduction project.
