### ISSUE TITLE
Netty WebSocket specs do not return close frames

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6504]
### Play Version (2.5.x / etc)

master

### API (Scala / Java / Neither / Both)

Scala

### Actual Behavior

We've seen build failures where the WebSocketSpec fails because the close frame does not seem to be returned from the server.  This happens reliably for 

``` scala
  "respond to pings" in {
    withServer(app => WebSocket.accept[String, String] { req =>
      Flow.fromSinkAndSource(Sink.ignore, Source.maybe[String])
    }) { app =>
      import app.materializer
      val frames = runWebSocket { flow =>
        sendFrames(
          PingMessage(ByteString("hello")),
          CloseMessage(1000)
        ).via(flow).runWith(consumeFrames)
      }
      frames must contain(exactly(
        pongFrame(be_==("hello")),
        closeFrame()
      ))
    }
  }

  "not respond to pongs" in {
    withServer(app => WebSocket.accept[String, String] { req =>
      Flow.fromSinkAndSource(Sink.ignore, Source.maybe[String])
    }) { app =>
      import app.materializer
      val frames = runWebSocket { flow =>
        sendFrames(
          PongMessage(ByteString("hello")),
          CloseMessage(1000)
        ).via(flow).runWith(consumeFrames)
      }
      frames must contain(exactly(
        closeFrame()
      ))
    }
  }
```

yields

```
[error]     x respond to pings
[error]      List(SimpleMessage(PongMessage(ByteString(104, 101, 108, 108, 111)),true)) does not contain exactly 2 correct values (WebSocketSpec.scala:273)
[error]     x not respond to pongs
[error]      List() does not contain exactly 1 correct value (WebSocketSpec.scala:291)
```

This doesn't happen on Akka HTTP, only on Netty.  Because this is failing the build every time, we're moving the specs out to https://github.com/playframework/playframework/pull/6501 and marking as pendingUntilNettyHttpFixed to stabilize things a bit.

Looking at the build history on https://travis-ci.org/playframework/playframework/builds --

* Master was working until [job 3089](https://travis-ci.org/playframework/playframework/builds/153766184).  
* We don't see the particular ping error in [build 3112](https://travis-ci.org/playframework/playframework/builds/154544548).
* Earliest indication is [3117.2 failed](https://travis-ci.org/playframework/playframework/jobs/154594497#L2468), when we upgraded to Akka 2.4.9. 
* After that, we see it in [build 3123](https://travis-ci.org/playframework/playframework/jobs/154671232#L2349)

and we keep seeing it from there.  Next step might be moving to Akka 2.4.8 and repeating.

https://travis-ci.org/playframework/playframework/jobs/154594497#L2468

**Comment by schmitch** [comment]
Actually commenting out `.skipUntilNettyHttpFixed` and running against Akka 2.4.8 really fixes this issue.

**Comment by wsargent** [comment]
If we know it happens in Akka 2.4.9 and doesn't happen in 2.4.8 that's a workaround, but we still don't know why it's happening...

**Comment by wsargent** [comment]
We should also try the latest Akka-SNAPSHOT build at http://repo.akka.io/snapshots/com/typesafe/akka/akka-http-core_2.11/

**Comment by drewhk** [comment]
The only change that can relate to this in 2.4.9 is an optimization. Either there is a bug there, or, what is more likely, it exposes a race that was already present. Do you have the fuzzing-mode enabled in your tests? It is a mode of the materializer that explicitly exercises such races. You might had the race even with 2.4.8 it just never happened. I am not sure though, so I will investigate.
