### ISSUE TITLE
[doc] Scalai18n page does not mention PLAY_LANG cookie

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6535]
### Play Version (2.5.x / etc)

2.5.x

### API (Scala / Java / Neither / Both)

Neither

### Actual Behavior

The Scalai18n page doesn't mention how to set the language in a cookie, nor the rich results:

https://www.playframework.com/documentation/2.5.x/ScalaI18N#Externalizing-messages

There's no mention of `clearLang` or `withLang` either -- so unless you use the API and know that it exists as an enriched result with i18nsupport, you're out of luck.

https://www.playframework.com/documentation/2.5.x/api/scala/index.html#play.api.i18n.I18nSupport$ResultWithLang

**Comment by kunalkanojia** [comment]
Updated the documentation. #6536
