### ISSUE TITLE
Assets: Trim diggest

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#6538]
### Play Version (2.5.6)

If using external tools to generate the digest of an asset (e.g. md5sum main.css > main.css.md5), it may happen that the tool adds non printable characters (like \n) after the digest. 

This results in URLs generated like:
/assets/styles/dc5672cb5071cd31a6fb6d670807161c
-main.css

instead of 
/assets/styles/dc5672cb5071cd31a6fb6d670807161c-main.css

Proposed solution: Trim the digest read from the digest file. 

PR will be added in a minute.

**Comment by domdorn** [comment]
closed without comment, @cchantep ?

**Comment by cchantep** [comment]
There is no need to maintain both an issue and a PR
