### ISSUE TITLE
Scala JsonTransformers do not work as documented

### ISSUE THREAD

**Issue by graingert** [playframework/playframework#6540]
### Play Version (2.5.x / etc)
2.4.x / 2.5.x

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux kvell 4.4.0-9136-generic #55-Ubuntu SMP Fri Aug 26 05:58:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Paste the output from `java -version` at the command line.
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-8u102-b14.1-2-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

### Expected Behavior
```scala
scala> import play.api.libs.json._
import play.api.libs.json._

scala> val json = Json.toJson("""{
     |   "key1" : "value1",
     |   "key2" : {
     |     "key21" : 123,
     |     "key22" : true,
     |     "key23" : [ "alpha", "beta", "gamma"],
     |     "key24" : {
     |       "key241" : 234.123,
     |       "key242" : "value242"
     |     }
     |   },
     |   "key3" : 234
     | }""")
json: play.api.libs.json.JsValue = "{\n  \"key1\" : \"value1\",\n  \"key2\" : {\n    \"key21\" : 123,\n    \"key22\" : true,\n    \"key23\" : [ \"alpha\", \"beta\", \"gamma\"],\n    \"key24\" : {\n      \"key241\" : 234.123,\n      \"key242\" : \"value242\"\n    }\n  },\n  \"key3\" : 234\n}"

scala> val jsonTransformer = (__ \ 'key2 \ 'key23).json.pick
jsonTransformer: play.api.libs.json.Reads[play.api.libs.json.JsValue] = play.api.libs.json.Reads$$anon$8@10bbae3f

scala> json.transform(jsonTransformer)
res9: play.api.libs.json.JsResult[play.api.libs.json.JsValue] = 
  JsSuccess(
    ["alpha","beta","gamma"],
    /key2/key23
  )
```

### Actual Behavior

```scala
scala> import play.api.libs.json._
import play.api.libs.json._

scala> val json = Json.toJson("""{
     |   "key1" : "value1",
     |   "key2" : {
     |     "key21" : 123,
     |     "key22" : true,
     |     "key23" : [ "alpha", "beta", "gamma"],
     |     "key24" : {
     |       "key241" : 234.123,
     |       "key242" : "value242"
     |     }
     |   },
     |   "key3" : 234
     | }""")
json: play.api.libs.json.JsValue = "{\n  \"key1\" : \"value1\",\n  \"key2\" : {\n    \"key21\" : 123,\n    \"key22\" : true,\n    \"key23\" : [ \"alpha\", \"beta\", \"gamma\"],\n    \"key24\" : {\n      \"key241\" : 234.123,\n      \"key242\" : \"value242\"\n    }\n  },\n  \"key3\" : 234\n}"

scala> val jsonTransformer = (__ \ 'key2 \ 'key23).json.pick
jsonTransformer: play.api.libs.json.Reads[play.api.libs.json.JsValue] = play.api.libs.json.Reads$$anon$8@10bbae3f

scala> json.transform(jsonTransformer)
res23: play.api.libs.json.JsResult[play.api.libs.json.JsValue] = JsError(List((/key2/key23,List(ValidationError(List(error.path.missing),WrappedArray())))))
```

### Reproducible Test Case

Please provide a PR with a failing test.  Will try...

If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

**Comment by irundaia** [comment]
@graingert, I think you're confusing Play's 'Json.toJson' with 'Json.parse'. 

'Json.toJson' is meant to transform a scala structure to a Json object. If you pass a String to it, you'll end up with an instance of JsString. That's what you're getting with your example.

'Json.parse' is meant to parse a json string to a scala structure. If you change your call from 'Json.parse("<json here>")', you'll get the Json structure in scala objects.

**Comment by cchantep** [comment]
Right, as explained by @irundaia, `Json.parse` must be used in such case.

> Please use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask questions/for help (this tracker being for confirmed issue)

Best regards

**Comment by graingert** [comment]
Ah that's not in the documentation, I'll send a PR with a fix

**Comment by cchantep** [comment]
That's indicated in the first code example of the [documentation](https://www.playframework.com/documentation/2.5.x/ScalaJson).
