### ISSUE TITLE
Post a request with empty body and header: Content-Type : application/json or text/xml will make server hang forever

### ISSUE THREAD

**Issue by lookis** [playframework/playframework#6547]
### Play Version (2.5.x / etc)
2.5.7

### API (Scala / Java / Neither / Both)
only test in Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
OSX 10.11

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

### Library Dependencies

no other library

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. post a request with empty body and header: Content-Type : application/json or text/xml
2. expect error message

### Actual Behavior

server hang with no response, client keep waiting for a very long time, both in dev mode and prod mode

### Reproducible Test Case
create a project with : activator new play-hang play-java
add/modify routes

> POST     /                           controllers.HomeController.index

start the server
post a request with any client, with header: Content-Type: application/json or text/json or text/xml or application/xml

> POST / HTTP/1.1
Host: 127.0.0.1:9000
Content-Type: text/json
Cache-Control: no-cache

or just checkout this project, start and post a request:

https://github.com/lookis/play-hang

**Comment by schmitch** [comment]
```
curl -v -XPOST -H 'Content-Type: application/json' --data '' http://localhost:9000
* Rebuilt URL to: http://localhost:9000/
*   Trying ::1...
* Connected to localhost (::1) port 9000 (#0)
> POST / HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 0
> 
< HTTP/1.1 400 Bad Request
< X-ExampleFilter: foo
< Content-Length: 2321
< Content-Type: text/html; charset=utf-8
< Date: Tue, 13 Sep 2016 05:37:56 GMT
* HTTP error before end of send, stop sending
< 
```

What do you mean with "hanging forever"
I basically did what you wrote.

**Comment by schmitch** [comment]
I may sense what you mean. Did you tried setting `play.server.http.idleTimeout`?

**Comment by lookis** [comment]
@schmitch I found it only happens on OSX, everything is ok on my centos server. I'll look into it and make a test case hours later.

**Comment by lookis** [comment]
I track the code with intellij idea, and I found it stuck here:

https://github.com/playframework/playframework/blob/a743f10550064b7f0fb031d593504276f24ec75c/framework/src/play/src/main/java/play/mvc/BodyParser.java#L416-L417

I am not familiar with scala so I only found that after I step over L416, and try to step into L417, It stuck. 

jstack shows the thread is waiting for something:

> "netty-event-loop-1" #41 prio=5 os_prio=31 tid=0x00007fa9026b1800 nid=0x8513 waiting on condition [0x0000700001656000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007b153dfc0> (a java.util.concurrent.CompletableFuture$WaitNode)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$WaitNode.block(CompletableFuture.java:271)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3226)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:319)
	at java.util.concurrent.CompletableFuture.access$000(CompletableFuture.java:111)
	at java.util.concurrent.CompletableFuture$AsyncCompose.exec(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$Async.run(CompletableFuture.java:428)
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.scala$concurrent$impl$Promise$DefaultPromise$$dispatchOrAddCallback(Promise.scala:280)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:270)


I test on two different osx laptops, they both failed

**Comment by schmitch** [comment]
you should probably upgrade your java version first.
I actually use a Mac and didn't stuck here.

**Comment by lookis** [comment]
@schmitch with JDK 1.8.0u101 problem solved. thanks

**Comment by lookis** [comment]
It seems playframework depends on java 8 is not precise enough, at least 1.8.0u05 can't fully work :)

**Comment by schmitch** [comment]
yeah there was a bug until u25 as far as I remember.
