### ISSUE TITLE
JSON provided as query param stopped working in 2.5.7

### ISSUE THREAD

**Issue by laborg** [playframework/playframework#6549]
### Play Version (2.5.x / etc)
Working: 2.5.6 
Broken: 2.5.7

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

### Expected Behavior

1. Client: provides a JSON as URL encoded query String via GET: 
`dynatable/?queries%5Bsearch%5D=%7B%22condition%22%3A%22AND%22%2C%22rules%22%3A%5B%5D%7D&page=1&perPage=10&offset=0`
2. Server: Parsing with `request.getQueryString("queries[search]")` contains the full JSON String =>
`{"condition":"AND","rules":[]}`

### Actual Behavior
1. As above
2. Server: Parsing with `request.getQueryString("queries[search]") `doesn't contain the full JSON String, but is cut of at "," => `{"condition":"AND"`
Which in the end leads to an Jackson parsing error

### Probable Reason
https://github.com/playframework/playframework/pull/6529/commits/4d0240c85f2fa1fb268b11c3879431070711d97e
```
-      else decodedParameters.asScala.mapValues(_.asScala).toMap
+      else decodedParameters.asScala.mapValues(_.asScala.mkString.split(",").toList).toMap
```

**Comment by schmitch** [comment]
Possible fix would be concat them inside the `RequestHeader` trait, but I'm not sure.
since `getQueryString(key)` should probably get the first param of a multi key query param.
You could possible fix it inside your application easily, with `queryString.get(key).map(_.mkString)`.
