### ISSUE TITLE
Multiple values for a single parameter stopped working as expected in 2.5.7

### ISSUE THREAD

**Issue by breadfan** [playframework/playframework#6551]
Play 2.5.7 
Scala
Ubuntu 16.04

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

### Expected Behavior

If I add ?filter=a&filter=b as a query string, I would expect a play request query param map with a key "filter" -> Seq("a", "b")

### Actual Behavior
I get a Seq("ab")

### Reproducible Test Case

add the following test case to NettyModelConversionSpec in play-netty-server tests:
```
    "parse multiple query params correctly" in {
      val (_, query) = modelConversion.parseUri("/?filter=a&filter=b")
      query must havePair("filter" -> Seq("a", "b"))
    }
```

See also my comment on https://github.com/playframework/playframework/commit/e943b9b10926f57863c8a29fb2f94758608c1ae5

**Comment by tsuyoshizawa** [comment]
Play routes also doesn't work with multiple parameters in 2.5.7.

```
GET /find controllers.SomethingController.find(id: Seq[Long])
```

`/find?id=1&id=2` request returns 404 status.
`/find?id=1` request return 200 status.
