### ISSUE TITLE
[doc] Include examples of implicit request in Action documentation

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6573]
### Play Version (2.5.x / etc)

current
### Expected Behavior

The Play documentation does not go far enough in pushing the importance of an implicit request in an action.  See https://github.com/playframework/playframework/pull/6428 for CSRF for example, and likewise Form processing and template handling is impractical without an implicit request.

The following pages should include references to implicit request:
- ScalaActions
- ScalaAsync
- ScalaTemplates
- JavaTemplates

**Comment by Shruti9520** [comment]
@wsargent Can I take this issue? :)

**Comment by wsargent** [comment]
Absolutely!
