### ISSUE TITLE
CacheApi.getOrElse  can call underlying loading function multi times

### ISSUE THREAD

**Issue by jilen** [playframework/playframework#6588]
### API (Both)

cacheApi.[getOrElse](https://github.com/playframework/playframework/blob/2.5.x/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala#L291)(f) could call function `f`  multi times at high concurrency level

I've appled the double check locking pattern [here](https://github.com/jilen/playframework/blob/cache_getOrElse_fix/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala#L291), but `playframework `  doesn't like `lock`, I don't know whether should make pr

**Comment by gmethvin** [comment]
@jilen I don't see the bug. As far as I can tell `orElse` is called at most once per call to `cache.getOrElse`. Multiple calls to `cache.getOrElse` may result in the value being recomputed more than once, but the implementation is still correct.

Is this causing significant performance issues for you in reality?

If we were to change the behavior, I'd prefer a solution more robust than synchronizing on a String, and it'd have to work properly with the future-based APIs being introduced in 2.6.

**Comment by jilen** [comment]
@gmethvin If the loading function is slow, that may be a problem, but I agree with you, locking is not a good choice, close this currently!

**Comment by jilen** [comment]
@gmethvin I report this issue because I met performance issue here, I use this cache to cache a future which needs abount 400ms. When our qps hits `1000`, this will leads to mutiple future execution which make the server lose response.

**Comment by schmitch** [comment]
@gmethvin I can think of that this may be a good use case for akka-stream.
I.e. where we push to a Source.queue, since only one element can pass trough the current flow all others would be resolved, with the cache data. The plus on that would be full backpressure, the cons would be needing ActorSystem inside the CacheApi and we would need to Await in the SyncCacheApi.
