### ISSUE TITLE
[doc] Guide to installing Play! is incomplete for version 2.5.8

### ISSUE THREAD

**Issue by dotnetCarpenter** [playframework/playframework#6591]
I'm following the `sbt` part of https://playframework.com/documentation/2.5.x/NewApplication but it result in
```
project/build.sbt:5: error: not found: value PlayScala
lazy val root = (project in file(".")).enablePlugins(PlayScala)
```

### Operating System (Ubuntu 16.04.1 LTS)
Linux dot-aspire 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK
```
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. run `sbt` from the terminal in the project directory
2. Play! should be downloaded and ready to be used in the project

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

1. Follow the guide https://playframework.com/documentation/2.5.x/NewApplication
2. See the attached files for my exact configuration ([project.zip](https://github.com/playframework/playframework/files/490014/project.zip) file with the project directory)

### Reproducible Test Case

Please see the attached files. [project.zip](https://github.com/playframework/playframework/files/490014/project.zip)

1. Download the attached files.
2. Unzip [project.zip](https://github.com/playframework/playframework/files/490014/project.zip) in an empty folder.
3. Run `sbt` from the terminal in your folder with the `project` folder, that you unzipped.

[project.zip](https://github.com/playframework/playframework/files/490014/project.zip)

**Comment by schmitch** [comment]
Actually you put the `plugins.sbt` into the main folder, however if you would've followed the guide correctly it would've needed to be in `project/plugins.sbt` you also have the `build.properties` in the wrong folder, it also needs to be in `project/build.properties`.

The guide is correct, you just didn't followed it correctly.

**Comment by dotnetCarpenter** [comment]
@schmitch  Well, I did follow the guide and put the files in the `project` folder. I attached the project folder after running `sbt`. The extra `project` folder inside the root `project` folder is generated by `sbt`.

My file structure is:
```
play1
|_project
  |_build.properties
  |_build.sbt
  |_plugins.sbt        
```
I don't mean to be an ass but you haven't answered or even comment on the issue which is stated in the beginning.

**The error is:**
```
play1/project/build.sbt:5: error: not found: value PlayScala
lazy val root = (project in file(".")).enablePlugins(PlayScala)
                                                     ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```
The guide says to write (in `build.sbt`):
```
name := "my-first-app"

version := "1.0.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)
```
There is even a copy function. If it is suppose to be something else then the guide MUST be updated with the correct content.

**Comment by schmitch** [comment]
if you read the site carefully you should end up with:
```
play
├── build.sbt
├── project
│   ├── build.properties
│   ├── plugins.sbt
```

Also as a beginner you should look at `activator`, this will bootstrap you a application skeleton.

**Comment by dotnetCarpenter** [comment]
I think I need `activator` so I can make a PR with a *correct* sbt guide :smiley_cat:

I was staying away from `activator` because I figured it would be a manual download, one that I would manually have to check for updates and re-download. Personally, I rather spend two days learning a new package manager than do this kind of repetitive labor.

After changing my file structure to your last comment and everything looks good. Thanks for the help. I'll see if I can contribute a newbie text to the docs.

**Comment by schmitch** [comment]
well it's actually already a step by step guide. Probably the only addition I can see of is actually creating the folder project folder upfront and having a directory structure displayed somewhere. but mostly it comes down to clearly reading the text.
