### ISSUE TITLE
Update Iteratees documentation for 2.5.X and later Play versions

### ISSUE THREAD

**Issue by jorgenota** [playframework/playframework#6608]
[Play 2.5 Highlights](https://www.playframework.com/documentation/2.5.x/Highlights25) includes this text:

> the main theme of Play 2.5 has been moving from Play’s iteratee-based asynchronous IO API to Akka Streams

Shouldn't the documentation about iteratees be updated to reflect that change? https://www.playframework.com/documentation/2.5.x/Iteratees

**Comment by cchantep** [comment]
Hi, even if Play is migrating from Iteratees to Akka, Iteratees itself is still available as a standalone library. The [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) is available if you have question about. Best regards.
