### ISSUE TITLE
Play WS API is unintuitive

### ISSUE THREAD

**Issue by mariussoutier** [playframework/playframework#6611]
## Play 2.5 Scala

The WS API makes a strange distinction between calling `withMethod(<method>)` and calling `<method>()` directly. Most notably, I can only call the `withBody` method after calling `withMethod`.

Example:

~~~scala
ws
  .url("http://example.org/endpoint";)
  .withMethod("POST")
  .withBody(StreamedBody(source))
  .execute()
~~~

~~~scala
ws
  .url("http://example.org/endpoint";)
  .post(File)
~~~

It took me a while to realize that the second version executes directly. However what I don't understand is that the second version cannot stream its body.

I suggest that either `post()`, `put()` and so on get renamed to `executePost()`, or that they support WSBody as well.

**Comment by cchantep** [comment]
Hi, please use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to discuss such design changes/feature request. This tracker is for confirmed issue/actionable request. Best regards.

**Comment by mariussoutier** [comment]
The normal mailing list or the dev one?

**Comment by mariussoutier** [comment]
Ok, posted on the mailing list.

**Comment by mchv** [comment]
Please don't rename an introduce an `API` change. It has been quite obvious to me that `post` and `get` (action verbs) will execute  when function prefixed by `with` are using the builder pattern.
