### ISSUE TITLE
Avoid to send a chunked response in Gzip Filter for HTTP/1.0 requests (Play 2.5)

### ISSUE THREAD

**Issue by cristianspinetta** [playframework/playframework#6613]
I've enabled the GZip Filter to serve the static content encoded in that format and all go fine for HTTP/1.1 but the issue occurs for requests that uses HTTP/1.0 protocol and the length of the response is bigger than the limit defined for buffer the gzip process (eg via `play.filters.gzip.chunkedThreshold`), since the filter tries to send the response as chunked and a good validation defined in play breaks the request with a 505 HTTP Version Not Supported.

As a workaround I reimplemented the GzipFilter in order to add a validation within the `handleResult()` method which checks whether it is a HTTP/1.0 or a HTTP/1.1 request and on the first case it returns a result with the complete body consumed, that is a `Result(header, compressStrictEntity(data, entity.contentType))`.

Anyone know a better solution? It would be fine to have this validation in the filter or maybe another solution, so I hope some comments.

**Comment by cchantep** [comment]
I guess it needs to be moved on [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to be discussed. Best regards.
