### ISSUE TITLE
"The Native Packager" docs missing plugin dependency

### ISSUE THREAD

**Issue by arlowhite** [playframework/playframework#6615]
The documentation at:
https://www.playframework.com/documentation/2.5.x/Deploying#The-Native-Packager

Does not mention that you need to add this line to **plugins.sbt**
`addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.1.4")`

---

Also, I was looking at https://github.com/sbt/sbt-native-packager/releases
1.2.0-M5 release mentions "Rescope rpm settings". Does Play need to make adjustments to its RPM build system for that release?

If 1.2 has breaking changes, there should be a note in the documentation saying to only use the 1.1.\* branch.

**Comment by gmethvin** [comment]
@arlowhite SBT Native Packager should automatically be included by the Play SBT plugin. That's why it's not mentioned. Does that not work for you?

**Comment by cchantep** [comment]
Closing as inactive
