### ISSUE TITLE
Debugging play application with activator

### ISSUE THREAD

**Issue by dalibor983** [playframework/playframework#6616]
In documentation for play framework in section for debugging [Debugging](https://www.playframework.com/documentation/2.5.x/PlayConsole#debugging) stends if you want to debug your application you need to start this command:
```
$ activator -jvm-debug 9999
```
I'm using eclipse to attach debugger to port 9999 after running this command and debugger connects but my breakpoints is never hit. For example I put breakpoint in home controller.

I found that statement in build.sbt:
```scala
fork in run := true
```
may produces this problem but if I change this statement to:
```scala
fork in run := false
```
while activator is running debugger still does not stop at breakpoint.
If I try to restart activator it puts:
```scala
fork in run := true
```
in my build.sbt again.

**Comment by gmethvin** [comment]
Hi @dalibor983,

Play Framework doesn't do anything to rewrite your build.sbt file, so this isn't a bug with Play. If it's being rewritten you're probably recreating the project from activator.

I'd suggest posting on the [Play mailing list](https://groups.google.com/forum/#!forum/play-framework) explaining exactly what you are doing, including the commands you use to "restart" activator. From there we can figure out what the problem is.

**Comment by dalibor983** [comment]
@gmethvin The way I restart activator is **Ctrl + C** and then:
```
$ activator -jvm-debug 9999
```
again.

**In a meantime I found the solution for attaching eclipse debugger to my playa application.**

The problem is statement in build.sbt:
```scala
fork in run := true
```
tells activator to fork new jvm process when starts my play application which is not listening on any debugging port you can attach some kind of debugger. So attaching debugger on port 9999 in this way will not hit any break point in your play application code.

For some reason activator will not let me to run my application with
```scala
fork in run := false
```
because it always change this statement to `true` so if you put this in your build.sbt file:
```scala
javaOptions in run += "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000"
```
the forked jvm process with play application will listening, in this example, on port 8000 for debuggers.
Now I can attach eclipse debugger on port 8000 and debugger stops on breakpoints.
You don't need to start activator in debugging mode, you can use normal command to start activator ui:
```
$ activator ui
```

What I want to say here is that documentation on this page [Debugging](https://www.playframework.com/documentation/2.5.x/PlayConsole#debugging) is not correct.

[MORE](http://stackoverflow.com/a/29163163/1624354)

**Comment by gmethvin** [comment]
@dalibor983 Perhaps the `fork in run := false` should be mentioned in the documentation, but this setting is also typically not set in our sample projects.

I have no idea why activator would modify your `build.sbt` file, and I'm unable to reproduce the behavior myself. Running the `activator` command should act just like `sbt`: it opens a console, without modifying anything in your project.

If you need more help with this issue please continue the discussion on the mailing list.
