### ISSUE TITLE
"illegal cyclic reference involving class" while compiling by sbt using “dist” flag

### ISSUE THREAD

**Issue by vikram-gupta** [playframework/playframework#6618]
I am getting a weird error while compiling my Play application using the "dist" flag.The same code compiles well WITHOUT using the "dist" flag. So, I am assuming that the Java code is fine. What can be the issue here? 

`sbt -Dsbt.log.noformat=true clean clean-files update compile package dist
`

The error that i get is:

```
    [error] /data/jenkins/jobs/infra/workspace/app/fig/basic/TFloatMap.java:47: illegal cyclic reference involving class TFloatMap
    [error]     implements Iterable<TFloatMap<T>.Entry>, Serializable
```

Here is the line of the code where i am getting this issue - 

```
    public class TFloatMap<T> extends AbstractTMap<T>
        implements Iterable<TFloatMap<T>.Entry>, Serializable
    {
      protected static final long serialVersionUID = 42;
    }

```

Here are the versions that i am using.

Scala Version - 2.11.6
Play Version - 2.4.6
Sbt Version - 0.13.8

**Comment by gmethvin** [comment]
This looks like [SI-4744](https://issues.scala-lang.org/browse/SI-4744), a scala compiler bug. There's a stackoverflow post with a few ideas for workarounds: https://stackoverflow.com/questions/28158173/building-a-project-with-mixed-scala-and-java-source-files-using-ant-illegal-cy/28161687

Not sure if there's anything we can do about it on the Play side though.

**Comment by vikram-gupta** [comment]
Thanks @gmethvin for the pointers !
