### ISSUE TITLE
Update Scala Anorm Documentation for play 2.5.x 

### ISSUE THREAD

**Issue by abhisheknoldus** [playframework/playframework#6620]
In Play 2.5.x Anorm Documentation (Scala) includes DB object to access methods.
![anorm](https://cloud.githubusercontent.com/assets/19702693/19111964/e26e90fe-8b1f-11e6-9254-36b865a6f06f.png)

DB object is deprecated in Play 2.5.x.
Instead of showing DB object Database trait should be mentioned using DI
for eg.
import play.api.db.Database
import anorm._
class Settings @Inject() (db : Database) {
db.withConnection { implicit connection =>
  val result: Boolean = SQL("Select 1").execute()
}
}

**Comment by gmethvin** [comment]
@abhisheknoldus Anorm is a separate project. You can submit a PR to correct it here: https://github.com/playframework/anorm/blob/master/docs/manual/working/scalaGuide/main/sql/code/ScalaAnorm.scala
