### ISSUE TITLE
[doc] "Unit testing Controller" describes functional test

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6625]
### Play Version (2.5.x / etc)

2.5.x
### API (Scala / Java / Neither / Both)

Neither
### Actual Behavior

The unit testing section in https://www.playframework.com/documentation/2.5.x/JavaTest#Unit-testing-controllers uses `WithApplication` and starts up Guice.  This isn't a unit test, because the entire application functionality is pulled in.  A true unit test would look like mocks supplied to the PersonController class with no external references at all, so testing the `index` method would be something as follows:

``` java
    public void checkIndex() {
        JPAApi jpaApi = mock(JPAApi.class);
        FormFactory formFactory = mock(FormFactory.class);
        final PersonController controller = new PersonController(formFactory, jpaApi);
        final Result result = controller.index();

        assertEquals(OK, result.status());
    }
```

**Comment by gmethvin** [comment]
@wsargent There needs to be a way to wrap the controller so the annotations can be applied.

We actually have a [`MockJavaAction`](https://github.com/playframework/playframework/blob/master/documentation/manual/working/javaGuide/code/MockJavaAction.scala) in the documentation tests that lets you call a Java action and convert the result, but it doesn't provide the same API as the controller.

**Comment by schmitch** [comment]
Also at the moment the Documentation is also too simple. We don't provide a example how to test POST/etc.. Requests with Data, which needs a ThreadLocal: https://github.com/playframework/playframework/blob/master/framework/src/play-test/src/main/java/play/test/Helpers.java#L98
at least in 2.5.x
