### ISSUE TITLE
Parse error in forwarding header when running behind a ipv6 haproxy

### ISSUE THREAD

**Issue by swoopster-sb** [playframework/playframework#6629]
Getting `play.core.server.common.ForwardedHeaderHandler - Error with info in forwarding header ForwardedEntry(Some(::ffff:123.123.123.123),Some(https)), using ConnectionInfo(/10.100.0.5,false) instead: Parse error: Left(failure: ':' expected but '.' found).` when running play framework on ipv4 behind a ipv4+ipv6 haproxy.
### System

Play Version: 2.5.8 scala

Linux vm 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Oracle java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

HA-Proxy version 1.6.3 2015/12/25
### HA-Proxy setup (running on 10.100.0.5)

```
defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    option forwardfor
    option http-server-close

frontend www-http
   bind :::80 v4v6
   reqadd X-Forwarded-Proto:\ http
   default_backend play

frontend www-https
   bind :::443 v4v6 ssl crt /etc/haproxy/ssl/
   reqadd X-Forwarded-Proto:\ https
   default_backend play

backend play
   redirect scheme https if !{ ssl_fc }
   balance roundrobin
   server play 10.103.1.4:9000 check
```
### Play setup

application.conf contains:
`play.http.forwarded.trustedProxies=[ "10.100.0.5/24" ]`
### How to reproduce

accessing haproxy at 10.100.0.5 from 123.123.123.123 produces a request to play, which gives:

`[debug] - access - request header: ArrayBuffer((Host,xxxxxxxxx), (User-Agent,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36), (Accept,image/webp,image/*,*/*;q=0.8), (Accept-Encoding,gzip, deflate, sdch, br), (Accept-Language,de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4), (Cookie,G_ENABLED_IDPS=google), (X-Forwarded-Proto,https), (X-Forwarded-For,::ffff:123.123.123.123), (Connection,close))`
### Expected Behavior

Play Framework should parse the Forwarded Header correctly to 123.123.123.123
### Actual Behavior

Play fails to parse the X-Forwared-For header:
`[debug] - play.core.server.common.ForwardedHeaderHandler - Error with info in forwarding header ForwardedEntry(Some(::ffff:123.123.123.123),Some(https)), using ConnectionInfo(/10.100.0.5,false) instead: Parse error: Left(failure:`:' expected but `.' found).`

How to fix this?

**Comment by gmethvin** [comment]
@richdougherty I think we missed a case in the header parsing?

**Comment by richdougherty** [comment]
Yes, I'll take a look at this.
