### ISSUE TITLE
JsString.toString should escape `/`

### ISSUE THREAD

**Issue by Atry** [playframework/playframework#6636]
### Play Version (2.5.x / etc)

2.4.4

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.11

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

### Expected Behavior

Create a Twirl template:

``` html
<script type="application/javascript">
  var myJson = @Html(JsString("</script><script>alert('XSS')</script>").toString)
  console.log(myJson)
</script>
```

Then visit a page that uses that template.

I expect `</script><script>alert('XSS')</script>` is shown in the browser's debug console. However, the browser shows a message box with text `XSS` instead.

This is a potential XSS-related security problem.

**Comment by Atry** [comment]
This issue also affects `play.api.libs.Jsonp`

**Comment by julienrf** [comment]
The problem is that you have several languages in the same file. Twirl templates sanitize spliced values based on the template’s language (here, HTML). If part of your HTML is JavaScript code, you can not rely on twirl to escape the values you splice in your JavaScript code.

A workaround could be to use the JavaScript’s escaper:
https://static.javadoc.io/com.typesafe.play/twirl-api_2.11/1.2.0/index.html#play.twirl.api.JavaScriptFormat$@escape(text:String):play.twirl.api.JavaScript

**Comment by Atry** [comment]
How about `Jsonp`? Does `Jsonp` guarantee safe in a `<script>` block?

**Comment by Atry** [comment]
It seems like even Lightbend developers tends to rely on twirl's escaping. https://github.com/typesafehub/activator/blob/6e64194/ui/app/views/main.scala.html#L32

**Comment by schmitch** [comment]
Just use `@JavaScript(JsString("</script><script>alert('XSS')</script>").toString)`.

From the Code you actually highlighted:
```
@* The @Html thing prevents the Json from being escaped *@
```
which means that they don't want it to be escaped...

**Comment by gmethvin** [comment]
@Atry No, `Jsonp` does not guarantee safety inside a `<script>` block. That's not the point of `Jsonp`. JSONP is meant to be served with a JavaScript content type, not as HTML.

If you choose to wrap anything in `@Html` you're basically telling Twirl that you've already done the necessary escaping. We document this behavior as well: https://www.playframework.com/documentation/2.5.x/ScalaTemplates#Escaping
