### ISSUE TITLE
activator compile throws StackOverflowError in typechecker after adding more Play routes

### ISSUE THREAD

**Issue by cricanr** [playframework/playframework#6638]
### Are you looking for help?

Hi,

After adding more routes in our application when running activator compile we get a StackOverFlowError. For details please check the attached routes file and the stack trace that we get.

PS: I added txt extension b/c you have a validation. 

Thanks,
Radu

### Play Version (2.5.x / etc)

2.5.6

### API (Scala / Java / Neither / Both)

Scala 2.11.8

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Amazon linux 

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

### Expected Behavior

1. I run ```activator compile``` after adding more routes
2. I do not receive a StackOverFlow exception

### Actual Behavior

Compiling our application after adding more routes results in "StackOverFlowError", by removing some routes exception disappears.

### Reproducible Test Case

[routes.txt](https://github.com/playframework/playframework/files/521621/routes.txt)
[stacktrace.txt](https://github.com/playframework/playframework/files/521622/stacktrace.txt)

**Comment by Technowise** [comment]
I've encountered the StackOverFlowError many times. But it was not related to routes. It was basically with regard to the amount of memory available for the compiler I believe. I had them fixed by either compiling it on a higher configuration(RAM and CPU) machine or by increasing stack/heap size for Java(http://stackoverflow.com/questions/1565388/increase-heap-size-in-java)

**Comment by cricanr** [comment]
Hi, yes I set the stack size to a bigger value and the issue disappears so I can "close/resolve" this from my point of view.

Regards, Radu
