### ISSUE TITLE
Play form not map NULL value

### ISSUE THREAD

**Issue by 0xbaadf00d** [playframework/playframework#6645]
### Play Version (2.5.x / etc)

2.5.9

### API (Scala / Java / Neither / Both)
```
Java
```

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
```
Windows 10 x64
```

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

### Expected Behavior

_This behavior is really useful when Playframework backed project provide a REST API who allow upgrading of optionnal fields (ie: an optional simple field or complex object can be filled or set to null)._

1. Submit a Form containing `null` value as `application/json`
2. Retrieve the submitted Json variable assigned to `null`

**Example (1st query)**
```
[REQUEST] POST /api/user/1
{
  "firstName": "John",
  "bio": "My supa bio"
}

[RESPONSE] POST /api/user/1
{
  "firstName": "John",
  "bio": "My supa bio"
}
```

**Example (2nd query)**
```
[REQUEST] POST /api/user/1
{
  "bio": null
}

[RESPONSE] POST /api/user/1
{
  "firstName": "John",
  "bio": null
}
```

### Actual Behavior

1. Submit a Form containing `null` value as `application/json`
2. Retrieve the submitted Json variable assigned to `null`

**Example (1st query)**
```
[REQUEST] POST /api/user/1
{
  "firstName": "John",
  "bio": "My supa bio"
}

[RESPONSE] POST /api/user/1
{
  "firstName": "John",
  "bio": "My supa bio"
}
```

**Example (2nd query)**
```
[REQUEST] POST /api/user/1
{
  "bio": null
}

[RESPONSE] POST /api/user/1
{
  "firstName": "John",
  "bio": "My supa bio"  // NULL value are not correctly handled on your Form JSON parser
}
```

### Fix proposal

This issue could be quickly fixed by editing the file [Form.scala line 392](https://github.com/playframework/playframework/blob/5428e7f8ed373efd7672eeeb4ea50d80bffcdea0/framework/src/play/src/main/scala/play/api/data/Form.scala#L392), the line `case JsNull => Map.empty` must be replaced with `case JsNull => Map(prefix -> null)`.

**Comment by gmethvin** [comment]
I don't think this is a bug, for a few reasons:
 1. `Form` is intentionally designed to support multiple content types, including urlencoded forms, which don't have a standardized way of distinguishing null values from nonexistent values and empty lists. If you want full JSON functionality, use play-json directly.
 2. `null` is not idiomatic in Scala. Making this API return nulls would violate the principle of least surprise, and would likely cause migration issues and/or unexpected bugs.

**Comment by 0xbaadf00d** [comment]
When user submit a form with a field explicitely set to _null_ (via JSON, XML document or other type), this fields must set to null on form after the execution of _bindFromRequest()_.

You can't just ignore a present field, if user sent a field as null, is because user wan't to set this field to null, and if your parser ignore it : how Play know if the field is set to null explicitely or not provided ?

If we use play-json directly, we loose the validation process and the generic errors message via _getErrors()_ method

**Comment by schmitch** [comment]
no you don't use the validation process when using `play-json`. you can basically do the same validation with play-json and even better, it validates integers correctly.

In play-forms a valid integer is `"1"` and `1`. That's why I don't see that as a bug as well. Play-Forms tries to generalize all formats. That's why you can even use non ideomatic values in these data formats and it will parse them just correctly.

**Comment by 0xbaadf00d** [comment]
Do you have an example of Json validation who working with partial pre-filled object (useful when user only send via POST data who need to be changed, the object to valid is filled with data from Database and only form submitted field are updated) ?

**Comment by schmitch** [comment]
basically pre filling data from the database is probably a bad idea in form validation.
most of the time it's also just unnecessary.

but well the simpliest way without tinkering into another solution is basically that you generate a json object from the database value and then you `deepMerge` the post data with the database object and do a `json.validate` than, of course you need to manually create your json `Reads[T]`.

**Comment by gmethvin** [comment]
Closing since Play Forms doesn't support "partial objects". If you'd like to discuss more solutions let's do so on the mailing list.
