### ISSUE TITLE
Chunked result with Closable Iterator

### ISSUE THREAD

**Issue by PierreAdam** [playframework/playframework#6653]
Play Version 2.5.9
API Java
Operating System Windows 10
JDK Oracle 1.8.0_102
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

### Expected Behavior

When returning a chunked result, if the iterator implements java.io.Closable, the iterator should be closed by calling the method ```void close()``` when the work is done or when the connection is closed to be able to dispose of the potential resources.

This is useful when for example, an SQL connection is used on the iterator.

### Actual Behavior

The method ```void close()``` is never called.

### Reproducible Test Case

The iterator
``` java
public class MyClosableIterator implements Iterator<ByteString>, java.io.Closeable {

    private int i = 0;

    @Override
    public void close() throws IOException {
        // This line is never called.
        // Resources like an SQL connection can be closed here !
        Logger.error("Close the iterator");
    }

    @Override
    public boolean hasNext() {
        // Continue while next hasn't been called 10 times.
        return (this.i < 10);
    }

    @Override
    public ByteString next() {
        // Increment the internal counter
        this.i++;
        return ByteString.fromString("Hello World\n");
    }
}
```

The iterable
``` java
public class MyIterable implements Iterable<ByteString> {

    @Override
    public Iterator<ByteString> iterator() {
        // Return an new instance of the closable iterator.
        return new MyClosableIterator();
    }

    @Override
    public void forEach(final Consumer<? super ByteString> action) {
        // Unnecessary here but for the beauty.
        for (final ByteString byteString : this) {
            action.accept(byteString);
        }
    }

    @Override
    public Spliterator<ByteString> spliterator() {
        // Ignored
        return null;
    }
}
```

The controller
``` java
public class HomeController extends Controller {
    public Result index() {
        // Creation a source with an instance of MyIterable.
        final Source<ByteString, ?> iterable = Source.from(new MyIterable());
        
        return ok().chunked(iterable);
    }
}
```

A zip of the sources is available here : https://dl.dropboxusercontent.com/u/22115896/test_closable_iterator.zip

**Comment by schmitch** [comment]
there is no way of doing that, since you pass the iterator/iterable to an akka-stream we don't have any way to access any value there.
also It's probably a really really bad idea to have a closeable iterator / iterable and hope that it will be auto closed by another api.
i also think it's not a good api to use a Iterable<T> to wrap a Iterator<T>, Closeable.
A better way for that would probably creating a custom Graph that will handle that. 
for you.

**Comment by PierreAdam** [comment]
@schmitch If it's a bad idea why does the ```Source.from(...)``` method take an iterable as parameter ?
Do you have any example for the method you recommend with ```SourceGraph``` ?

**Comment by schmitch** [comment]
First of all, these are all akka related API's. 
Second a `Iterable`/`Iterator` don't have a `close` method by themself's they are just APIs to get elements.
What would be feasible if the `Source.from` and `Source.fromIterator` would yield a `Future<Done>` than you could've close it by yourself however I guess `Source.from` is also used for other stuff not only `Iterable` I guess.

Here is how you can create a Custom Graph:
http://doc.akka.io/docs/akka/2.4/java/stream/stream-customize.html#Custom_processing_with_GraphStage

And here is a example:

```java

import akka.stream.Attributes;
import akka.stream.Outlet;
import akka.stream.SourceShape;
import akka.stream.stage.AbstractOutHandler;
import akka.stream.stage.GraphStage;
import akka.stream.stage.GraphStageLogic;

public class IteratorSource<T> extends GraphStage<SourceShape<T>> {
    // Define the (sole) output port of this stage
    public final Outlet<T> out = Outlet.create("IteratorSource.out");
    private final CloseableIterator<T> iterator;

    // Define the shape of this stage, which is SourceShape with the port we defined above
    private final SourceShape<T> shape = SourceShape.of(out);

    public IteratorSource(CloseableIterator<T> iterator) {
        this.iterator = iterator;
    }

    @Override
    public SourceShape<T> shape() {
        return shape;
    }

    // This is where the actual (possibly stateful) logic is created
    @Override
    public GraphStageLogic createLogic(Attributes inheritedAttributes) {
        return new GraphStageLogic(shape()) {
            // All state MUST be inside the GraphStageLogic,
            // never inside the enclosing GraphStage.
            // This state is safe to access and modify from all the
            // callbacks that are provided by GraphStageLogic and the
            // registered handlers.
            private int counter = 1;

            {
                setHandler(out, new AbstractOutHandler() {
                    @Override
                    public void onPull() throws Exception {
                        if (iterator.hasNext()) {
                            push(out, iterator.next());
                        } else {
                            iterator.close();
                            complete(out);
                        }
                    }
                });
            }

        };
    }

}
```

```java
import java.util.Iterator;

public interface CloseableIterator<T> extends Iterator<T>, java.io.Closeable {
}
```

guess it should be correct.

**Comment by schmitch** [comment]
I'm closing it, as already said there is no actual way that Play! knows that the value passed to the Source has had a close() method. You might ask the Akka guys on their user mailing list if there is a way to directly do it without a Source.

**Comment by 0xbaadf00d** [comment]
Hi @schmitch, 

just to add more information on you snippet:  the  overriding of `onDownstreamFinish` needed to stop the call of `onPull` is missing.

**Comment by schmitch** [comment]
what?
basically `onDownstreamFinish` will get called if the downstream boundary is finished processing, while the `postStop` will called when the stage stops or the stage fails. basically I guess it might happen that the `close` will get called twice. However `onPull` will not be called after `onDownstreamFinish` is called.

**Comment by 0xbaadf00d** [comment]
Ok, it seem to do the job with `postStop`.  Thanks you for tips
