### ISSUE TITLE
JSON basics documentation page is very complicated

### ISSUE THREAD

**Issue by boosh** [playframework/playframework#6663]
The "[JSON basics](https://www.playframework.com/documentation/2.5.x/ScalaJson)" page is a complicated wall of text. It'd be useful to write in large, highlighted text that for 95% of cases you can probably just use [automatic case class serialisation](https://www.playframework.com/documentation/2.5.x/ScalaJsonAutomated). 

Please don't make users wade through 3 or 4 pages of complicated serialisation documenatation before telling them they've wasted their time and Play could have done it for them automatically.

**Comment by wsargent** [comment]
@boosh would you be open to writing a page describing what JSON would be useful for the end user?

**Comment by boosh** [comment]
Sure, I'll give it a try. I would have found it useful if on the first page there was just a pull-out saying "Stop! If you just need to serialise to and from case classes just do this or see this page". I'll update the docs and make a PR.

**Comment by gmethvin** [comment]
@boosh Thanks. This is one of the major areas I think we can improve in our documentation and it'd be great to have someone from the community provide some input.

**Comment by boosh** [comment]
Merged in #6669
