### ISSUE TITLE
Does filters-helpers really have to depend on play-java?

### ISSUE THREAD

**Issue by kutchar** [playframework/playframework#6671]
The issue is when you add the `filters-helpers` as a dependency to an Scala project, it brings in quite a bit of un-needed dependencies such as Spring. Shouldn't that dependency be implicit? As in, if you are adding `filters-helpers`, obviously you already are using play or play-java.

**Comment by wsargent** [comment]
It would be helpful if you share what version of Play you're using, a sample application, or best of all a list of dependencies showing an example and where the dependency tree is picking the filter up.

**Comment by kutchar** [comment]
@wsargent My comment is based on the [published pom for 2.5.9](https://repo1.maven.org/maven2/com/typesafe/play/filters-helpers_2.11/2.5.9/filters-helpers_2.11-2.5.9.pom)

I'm currently using 2.5.9 and tried including the `filters-helpers` package by adding the dependency `"com.typesafe.play" %% "filters-helpers" % "2.5.9"` to my `libraryDependencies` in sbt.

**Comment by kutchar** [comment]
I just tried with a simple project to make a reproducible test case:

1. Download the lasted [play-scala seed](https://example.lightbend.com/v1/download/play-scala)
2. Edit `build.sbt` and add `libraryDependencies += filters` to the end
3. Edit `project/plugins.sbt` and add `addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")`
4. run `sbt update dependency-tree`
5. Inspect the output and you'll see that `filters-helpers` is bringing in `play-java` and all it's "baggage"

**Comment by gmethvin** [comment]
@kutchar This was pointed out to us recently and will actually be fixed in 2.5.10. I had meant to include it in 2.5.9 but forgot to backport it in time. The PR is #6619. For now, I think it should be safe to exclude play-java from your dependencies without issue, assuming you are not using any of the Java features or the dependencies it brought in.

**Comment by kutchar** [comment]
Thanks @gmethvin

**Comment by kutchar** [comment]
@gmethvin, so it turns out that `filters-helpers` does depend on `play-java` because of reference to `play.libs.crypto.CSRFTokenSigner`. Is this address in 2.5.10?

**Comment by gmethvin** [comment]
Yes, the `play.libs.crypto` package has been moved to `play` from `play-java`.
