### ISSUE TITLE
Hardcoded dependency on (doc in Compile) breaks build

### ISSUE THREAD

**Issue by muuki88** [playframework/playframework#6688]
### Are you looking for help?

No

### Play Version (2.5.x / etc)

`2.5.9`

### API (Scala / Java / Neither / Both)

build

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

All systems

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

### Expected Behavior

A successful build when docs aren't able to built. We are using [simulacrum](https://github.com/mpilquist/simulacrum), which generates invalid scaladoc ATM.

1. Add invalid scaladoc (e.g. invalid reference to another class)
2. Configure scalac with `"-Xfatal-warnings"`
3. `sbt universal:packageBin`

### Actual Behavior

I want to disable [the hardcoded sources](https://github.com/playframework/playframework/blob/2.5.x/framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L219-L227). For example with
an extra AutoPlugin

```
disablePlugins(PlayIncludeDocumentation)
```

### Reproducible Test Case

Will provide a failing test

**Comment by schmitch** [comment]
did you tried: `doc in Compile := (target.value / "none")` this might disable the documentation generation completly?

**Comment by muuki88** [comment]
Yes, we disabled it with `sources in (Compile, doc) := Seq.empty`, but this is not a solution, rather a workaround. IMHO putting the scaladoc into the binary distribution only makes sense for special use cases.

**Comment by lunaryorn** [comment]
@schmitch Adding to that, we'd still like to build our docs separately, but due to this dependency  flawed API docs break binary packages and thus our deployment.

**Comment by schmitch** [comment]
well I always tought that the UniversalPlugin stuff needs an overhaul.
Currently there is no way to disable it, which means that if you have 3 projects where one is your main project and two are just projects that have `PlayScala` or `PlayJava` Plugin enabled will also generate a distribution package, even if they are `dependsOn` artifacts for the main project.

I'm just not sure if it's worth to put a whole Plugin for documentation generation for that. I guess in that case a simple SBT setting would do the work.

**Comment by muuki88** [comment]
I'm not sure if the `sbt` macros correctly resolve the following

```scala
mappings in Universal ++= {
  if(includeDocs.value) {
     val docDirectory = (doc in Compile).value
     ....
  } else {
     Seq.empty
  }
}
```

I guess sbt will still generate a dependency on this value as this basically translates to

```scala
mappings in Universal <++= (includeDocs, doc in Compile) map { (includeDocs, docDirectory) =>
  // ...
}
```

With an autoplugin you would remove this logic entirely, which also eliminates the dependency.

**Comment by schmitch** [comment]
well you don't need an autoplugin (http://www.scala-sbt.org/1.0/docs/Tasks.html#Dynamic+Computations+with), but I'm pretty sure it will still try to compile the documentation.
