### ISSUE TITLE
[2.5.9] Routes compiler generates code with unused imports

### ISSUE THREAD

**Issue by gsson** [playframework/playframework#6690]
### Play Version (2.5.x / etc)

2.5.9

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

### Library Dependencies

n/a

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Run `activator new my-first-app play-scala`
2. Add `scalacOptions += "-Ywarn-unused-import"` to build.sbt
3. Run `sbt compile`
4. Build completes with no issues

### Actual Behavior

Steps 1-3 works as expected.
In step 4, compilation emits various warnings.

Relevant to this issue in particular, these warnings are emitted:

```
[warn] /.../my-first-app/conf/routes:10: Unused import
[warn] GET     /message                    controllers.AsyncController.message
[warn] /.../my-first-app/conf/routes:6: Unused import
[warn] GET     /                           controllers.HomeController.index
[warn] /.../my-first-app/conf/routes:8: Unused import
[warn] GET     /count                      controllers.CountController.count
[warn] /.../my-first-app/conf/routes: Unused import
```

In our project, well over 100 such warnings from the routes compiler is generated, making the `-Ywarn-unused-import` warning useless. With no way of selectively disable the warning for the routes compiler we have to disable it altogether.

If any of the above route generator compiler warnings are legitimate issues, I would expect the routes compiler would emit human readable versions of those.

This SO question from May is related: http://stackoverflow.com/questions/37413032/ywarn-unused-import-triggering-on-play-routes-file

I tried manually updating the `RoutesKeys.routesImport` setting, but the warnings remained.

### Reproducible Test Case

1. Run `activator new my-first-app play-scala`
2. Add `scalacOptions += "-Ywarn-unused-import"` to build.sbt
3. Run `sbt compile`

**Comment by godenji** [comment]
Just an FYI, Scala 2.12.2 enables unused imports by default; combined with `-Xfatal-warnings`, kaboom. Easy enough to disable with `-Ywarn-unused:-imports,_`, but would be great to solve this issue and make use of this linting option rather than being forced to disable it.

**Comment by mkurz** [comment]
Because Scala 2.12.2 changed it's default #7250 fails.
