### ISSUE TITLE
default json content-type no longer mentions charset=utf-8

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#6696]
The documentation mentions that json requests have charset utf-8
https://www.playframework.com/documentation/2.5.x/ScalaJsonHttp

> Content-Type: application/json; charset=utf-8

But using play 2.5.x this is not the case

```scala
// slightly modified default new project
def index = Action {
    val json = Json.obj("test" -> "test")
    Ok(json)
}
```

```
curl --head http://localhost:9000
HTTP/1.1 200 OK
X-ExampleFilter: foo
Content-Length: 15
Content-Type: application/json
Date: Thu, 03 Nov 2016 15:49:31 GMT
```

When using play 2.4.x this works as expected

```
curl --head http://localhost:9000
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 15
Date: Thu, 03 Nov 2016 16:07:30 GMT
```

It would be cleaner if the header again mentions the `utf-8` charset because some clients default to `iso-8859-1` if charset is missing

**Comment by gmethvin** [comment]
> It would be cleaner if the header again mentions the `utf-8` charset because some clients default to `iso-8859-1` if charset is missing

This is only an issue for clients that don't  follow the JSON spec. `application/json` doesn't define a `charset` parameter. The charset of `application/json` is determined by looking at the first four bytes of the payload, not the header.

I'd actually suggest removing `charset=utf-8` from the documentation.

**Comment by francisdb** [comment]
Actually created this ticket after encountering this issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=438464
Same thing happens on safari / firefox
https://bugzilla.mozilla.org/show_bug.cgi?id=741776

But agree to follow the spec and fix the docs

**Comment by ginastanford** [comment]
ontent-Type:application/json;charset=utf-8
