### ISSUE TITLE
Need to update sbt.bat, sbtconfig.txt in SBT.

### ISSUE THREAD

**Issue by engrjislam** [playframework/playframework#6699]
### Need to update sbt.bat, sbtconfig.txt in SBT.

in sbt.bat file it has given that,
1. set %SBT_HOME%=%~dp0
2. set FN=%SBT_HOME%..\conf\sbtconfig.txt
3. "%SBT_HOME%sbt-launch.jar" xsbt.boot.Boot %*

and in sbtconfig.txt, -XX:MaxPermSize=256m should be removed.

### Play Version (2.5.x / etc)

2.5.9

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10.

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle 1.8.0_112.

### Expected Behavior

In sbt.bat, SBT_HOME should return the path of the directory upto bin directory but it returns the path directory including bin directory

1. %SBT_HOME% should return sbt home path upto bin directory such as C:\sbt
2. %FN% should return C:\sbt\conf\sbtconfig.txt
3. "%SBT_HOME%sbt-launch.jar" xsbt.boot.Boot %* should include bin directory 

In sbtconfig.txt, -XX:MaxPermSize=256m declares the perm gen size. Java 8 has removed this [please see at release note, http://www.oracle.com/technetwork/java/javase/8-compatibility-guide-2156366.html]

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

In sbt.bat

1. set SBT_HOME=%dp0 should be
set BIN_DIRECTORY=%~dp0
set BIN_DIRECTORY=%BIN_DIRECTORY:~0,-1%
for %%d in ("%BIN_DIRECTORY%") do set SBT_HOME=%%~dpd
set SBT_HOME=%SBT_HOME:~0,-1%

2. set FN=%SBT_HOME%..\conf\sbtconfig.txt [FN returns like as C:\sbt\bin\..\conf\sbtconfig.txt] file not found into the directory. It should be
set FN=%SBT_HOME%\conf\sbtconfig.txt

3. "%SBT_HOME%sbt-launch.jar" xsbt.boot.Boot %* should be
"%SBT_HOME%\bin\sbt-launch.jar" xsbt.boot.Boot %*

Finally in sbtconfig.txt, -XX:MaxPermSize=256m should be removed.

**Comment by gmethvin** [comment]
Not sure how this is a bug in Play. Please start a discussion on the mailing list or report to activator/SBT.
