### ISSUE TITLE
Not all SecurityHeaderFilters apply to non-HTML documents

### ISSUE THREAD

**Issue by strelec** [playframework/playframework#6705]
We could probably optimize request sizes when the type of the document is something else than HTML, like a text/plain or an image.

**Comment by gmethvin** [comment]
@strelec This could potentially be added as an option, but from what I understand, `X-Frame-Options`, `X-Content-Type-Options`, and `X-Permitted-Cross-Domain-Policies` make sense for non-html pages as well.

**Comment by wsargent** [comment]
I don't see this as an issue -- if you're sending an asset and you consider size even to the header to be an issue, then you'll serve directly from an HTTP server like nginx, or you'll be using HTTP/2 and the header data will be handled in frame.  Either way, I don't think it's worth optimizing at the filter level.
