### ISSUE TITLE
[2.5.x] JSON readNullable erroneously fails with "error.path.empty"

### ISSUE THREAD

**Issue by hermanbanken** [playframework/playframework#6710]
In Play 2.5 (and current master) the JSON readers for nullable types do not work when used without a nested path.

````scala
// works
val composableRootReadsNullableScoped: Reads[Root] = (
  (__ \ "foo").read[Foo] and
  (__ \ "bar").readNullable[Bar]
)((foo, barOpt) => Root(foo, barOpt.getOrElse(Bar(-1, -1, -1))))

// does not work
val composableRootReadsNullable: Reads[Root] = (
  (__ \ "foo").read[Foo] and
   __.readNullable[Bar]
)((foo, barOpt) => Root(foo, barOpt.getOrElse(Bar(-1, -1, -1))))
````

using the following JSON inputs
````json
// for first reader
{
  "foo": { "a": 1, "b": 0 },
  "bar": {
    "barA": 0,
    "barB": 0,
    "barC": 0
  }
},

// for second reader
{
  "foo": { "a": 1, "b": 0 },
  "barA": 0,
  "barB": 0,
  "barC": 0
}
````

I expect both examples to result in the same parsed `Root` object containing the same `Foo` and `Bar`. The use-case of handling several fields with their own specialised `Reads` seems very natural to me. Often API's contain rows which are multiple merged objects like bar and foo in this example, and composing the combined `Reads` using other `Reads` is the nicest solution in my opinion.

For all types & a test case, see my full example:
https://gist.github.com/hermanbanken/98057a12f349ddbc6fab9575b8aa5f2e

````
[error] Actual:   JsError(List((,List(ValidationError(List(error.path.empty),WrappedArray())))))
[error] Expected: JsSuccess(Root(Foo(1,0),Bar(0,0,0)),)
````

The JsError originates in [JsPath.scala#L184](https://github.com/playframework/playframework/blob/2.5.x/framework/src/play-json/src/main/scala/play/api/libs/json/JsPath.scala#L184). I'm not sure, but maybe the branch checking Nil is unnecessary? Nil is a valid tail, so maybe it should be handled as a empty tail?

**Comment by schmitch** [comment]
Well I guess that happened, because the old behavior was error prone and since you can just validate the root object it was gone.

However you can just read the JsValue twice with:

```scala
implicit val demoReads: Reads[Root] = new Reads[Root] {
      def reads(json: JsValue): JsResult[Root] = {
        ((json \ "foo").validate[Foo], json.validateOpt[Bar]) match {
          case (JsSuccess(v1, _), JsSuccess(v2, _)) => JsSuccess(Root(v1, v2), __)
          case (JsError(errors), JsSuccess(_, _)) => JsError(errors)
          case (JsSuccess(_, _), JsError(errors)) => JsError(errors)
          case (JsError(e1), JsError(e2)) => JsError(e1 ++ e2)
        }
      }
    }
```

Which is probably the way you should do it

**Comment by hermanbanken** [comment]
That works, but only if you can create Foo without needing Bar. In my actual codebase I have a Root object containing quite some fields (5+) and Bar is one of them. In this case I can't apply the Root in the Reads unless I have a Bar already. 

Probably I can work around this, by doing some scoping, but I think my second example looks much much clearer.

**Comment by schmitch** [comment]
well it also works with 5+ fields, actually it's possible to do it in a more clear way, however this would use a functional library, etc.

As already said, it was removed because it was error prone. Also you can always do it like I did it in my example, even with more fields.

**Comment by hermanbanken** [comment]
Sure it will work, but it will be ugly.

How is it more error prone? The API is exposing both `read` and `readNullable`. It works with read and does not work with readNullable. The fact that the same code is used to read lists as optionals is none of a concern to the user of the API. Maybe I will create a PR, creating a distinct codepath for readNullable instead of using the list path... 

IMO:
- Either the error should be more clear
- or `__.readNullable` should work

**Comment by schmitch** [comment]
Well the alternative is also to write:

```scala
    val composableRootReadsNullable: Reads[Root] = (
        (__ \ "foo").read[Foo] and
            __.read[JsValue]
        )((foo, barOpt) => Root(foo, barOpt.asOpt[Bar].getOrElse(Bar(-1, -1, -1))))
```

Actually I couldn't find anything specific about `readNullable` (maybe I was wrong that it was error prone) so I guess if you can create a PR that fixes it, it's probably fine.

**Comment by gmethvin** [comment]
Moved to playframework/play-json#11
