### ISSUE TITLE
Fix comment or implementation regarding 'future' scala 2.11 functionality

### ISSUE THREAD

**Issue by diamondo25** [playframework/playframework#6718]
I was checking out the code related to routes generation, when I stumbled upon this piece:

https://github.com/playframework/playframework/blob/5428e7f8ed373efd7672eeeb4ea50d80bffcdea0/framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesFileParser.scala#L173-L175

```
  // This won't be needed when we upgrade to Scala 2.11, we will then be able to use JavaTokenParser.ident:
  // https://github.com/scala/scala/pull/1466
def javaIdent: Parser[String] = """\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*""".r
```

There's already development going on for Scala 2.12, so it might be good to check out the routes compiler, too.

Edit: Checked the Scala 2.11 and 2.12 sourcecode, seems like the pull request was accepted 4 years ago, and the parser lib has been extracted from the sourcecode (to scala-parser-combinators) in 2.11-M4.
: https://github.com/scala/scala-parser-combinators/blob/1.0.x/shared/src/main/scala/scala/util/parsing/combinator/JavaTokenParsers.scala

**Comment by marcospereira** [comment]
Fixed by #7376.
