### ISSUE TITLE
Documentation 'ScalaTestingWithDatabases' for 2.5.x is using outdated API

### ISSUE THREAD

**Issue by diamondo25** [playframework/playframework#6722]
I tried to get some testing logic going on for my app, but it seems that the documentation related to this is outdated, which makes it harder for me to get testing working (I am using play-slick and 2.5.9, so it will be something in the lines of dependency injection/different configuration).

URL: https://www.playframework.com/documentation/2.5.x/ScalaTestingWithDatabases

**Comment by schmitch** [comment]
Actually nothing there is outdated.
play-slick just doesn't use the `database` from jdbc but that is a different beast.
You can actually enlarge that documentation or great a play-slick one
