### ISSUE TITLE
Error related to HelloActor in Akka documentation

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#6751]
On this page https://www.playframework.com/documentation/2.5.x/JavaAkka 

There is this text: _Notice here that the `HelloActor` defines a static method called `props`_

But in fact `HelloActor` has no static method named `props`.  `props` is a static field.

**Comment by schmitch** [comment]
Error only happens in the 2.5.x Branch, master is already fixed: https://www.playframework.com/documentation/2.6.x/JavaAkka#Writing-actors (where it actually is a method..)

**Comment by rethab** [comment]
@schmitch This may be closed.
