### ISSUE TITLE
[doc] Link to sbt's download page uses https

### ISSUE THREAD

**Issue by eed3si9n** [playframework/playframework#6754]
https://www.playframework.com/documentation/2.5.x/Installing#Installing-Play-with-SBT links to https://www.scala-sbt.org/download.html, which doesn't work because of GitHub cert :/

**Comment by wsargent** [comment]
Is that really a Play doc bug?

**Comment by eed3si9n** [comment]
Should sbt get off the GitHub pages? Maybe. But for now the link is broken, so I think it is.

**Comment by PromanSEW** [comment]
Why we can't fix this link with HTTP protocol?
