### ISSUE TITLE
[doc] describe how to read optional fields / objects with Json Transformers

### ISSUE THREAD

**Issue by schmitch** [playframework/playframework#6756]
Actually reading optional fields / objects with Json Transformers is possible, but it is currently missing in our [documentation](https://www.playframework.com/documentation/2.5.x/ScalaJsonTransformers), so we should add something like that to our docs: http://stackoverflow.com/a/15998881/2250209

Actually the important part is: `.orElse(__.json.pick[JsObject])`

**Comment by gmethvin** [comment]
Moved to playframework/play-json#12
