### ISSUE TITLE
Failed to set default charset utf8 for data table

### ISSUE THREAD

**Issue by niuchangming** [playframework/playframework#6757]
Hi, I am new to Play framework. Currently I am use hibernate and I want default table charset to be UTF-8. Unfortunately, No matter what values I set in persistence.xml, it will failed and the charset is still remaning latin1.

**persistence.xml**

```
<persistence-unit name="defaultPersistenceUnit" transaction-type="RESOURCE_LOCAL">
        <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
        <non-jta-data-source>DefaultDS</non-jta-data-source>
        <properties>
            <property name="hibernate.show_sql" value="true"/>
            <property name="hibernate.format_sql" value="true"/>
            <property name="hibernate.hbm2ddl.auto" value="update"/>
            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5InnoDBDialect"/>
            <property name="hibernate.connection.charSet" value="utf8"/>
            <property name="hibernate.connection.characterEncoding" value="utf8"/>
            <property name="hibernate.connection.useUnicode" value="true"/>
        </properties>
    </persistence-unit>
```

and **application.conf**

```
default.url="jdbc:mysql://localhost/realstream_db?useUnicode=true&connectionCollation=utf8_general_ci&characterEncoding=UTF-8"
  default.driver=com.mysql.jdbc.Driver
  default.username=root
  default.password=""
  default.jndiName=DefaultDS
```

### Play Version

I am using play framework version 2.5

### API (Java)

java

### Operating System

MacOS 10.11.6

Use `uname -a` if on Linux.

### JDK

java version "1.8.0_91"

### Library Dependencies

```
libraryDependencies ++= Seq(
  javaJdbc,
  cache,
  javaWs,
  javaJpa,
  "mysql" % "mysql-connector-java" % "5.1.38",
  "org.hibernate" % "hibernate-entitymanager" % "5.1.0.Final",
  "com.tokbox" % "opentok-server-sdk" % "2.3.2",
  "com.auth0" % "java-jwt" % "2.2.1",
  "com.monitorjbl" % "json-view" % "0.12"
)
```

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. run 
2. go browser and type localhost:9000
3. open mysql and type 'SHOW CREATE TABLE tablename;'

**This is the result:**

CREATE TABLE `lesson` (
  `id` bigint(20) NOT NULL,
  `description` longtext,
  `end_datetime` datetime DEFAULT NULL,
  `is_publish` bit(1) DEFAULT NULL,
  `published_datetime` datetime DEFAULT NULL,
  `start_datetime` datetime DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `lesson_type_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKpegqguim02ncgmaqkit9fy4l2` (`lesson_type_id`),
  CONSTRAINT `FKpegqguim02ncgmaqkit9fy4l2` FOREIGN KEY (`lesson_type_id`) REFERENCES `lesson_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

**Comment by cchantep** [comment]
Hi, please use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask for help, rather than this tracker (for confirmed Play issue). Best regards.
