### ISSUE TITLE
regression: compilation failure against current Akka master

### ISSUE THREAD

**Issue by SethTisue** [playframework/playframework#6773]
this came up in the 2.12 community build at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1030/consoleFull:

```
[play2-core] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/play2-core-3262e12350c4c6b58f4a66706e3729e6b5d2c9ef/framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala:418: not found: type StatefulStage
[play2-core] [error]     val transformer = new StatefulStage[ByteString, ByteString] {
[play2-core] [error]                           ^
```

it's partly guesswork, but I think this might have to do with https://github.com/akka/akka/pull/21919, cc @ktoso. I opened a similar ticket in the akka-http repo, https://github.com/akka/akka-http/issues/606

for now, to resolve the problem in the community build I have frozen Akka at an earlier commit.

**Comment by gmethvin** [comment]
Yes, I guess this is part of the bigger issue of upgrading to Akka 2.5.0. We are still using a few deprecated stages.

**Comment by SethTisue** [comment]
@ktoso should the community build be tracking some 2.4 branch of Akka, instead of tracking master?

**Comment by ktoso** [comment]
Master is 2.5.0 as of yesterday, so if play is to remain on 2.4 for now it has to track release-2.4 branch in dbuild.
I hope you can upgrade though, other than removal of depreciations they will be binary compatible.

**Comment by gmethvin** [comment]
@ktoso I don't think the upgrade is a major issue; just a question of taking the time to upgrade a few of the deprecated uses.

**Comment by ktoso** [comment]
Cool, happy to help during the week if you need any. It's rather simple to rewrite StatefulStage into GraphStage :)

**Comment by schmitch** [comment]
I submit a pr in a few sec

**Comment by SethTisue** [comment]
I will change the community build to use the release-2.4 branch for now: https://github.com/scala/community-builds/issues/421

(Someone at Lightbend might decide that we ought to have something like the community build, internally, but just for the Lightbend suite, so we catch these things. I gather you're already considering that for akka and akka-http. But I can't afford to be running into stuff like this all the time, the community build chews up way too much of my time as it is...)
