### ISSUE TITLE
Building locally leads to sbt resolve issues

### ISSUE THREAD

**Issue by RookieMaus** [playframework/playframework#6782]
### Play Version (2.5.x / etc)
2.6.0-SNAPSHOT

### API (Scala / Java / Neither / Both)
Neither

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Use `uname -a` if on Linux.
Linux myAwesomeSystemName 4.8.11-1-ARCH #1 SMP PREEMPT Sun Nov 27 09:26:14 CET 2016 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Paste the output from `java -version` at the command line.

Scala code runner version 2.12.1-20161205-201300-2787b47 -- Copyright 2002-2016, LAMP/EPFL and Lightbend, Inc.

openjdk version "1.8.0_112"
OpenJDK Runtime Environment (build 1.8.0_112-b15)
OpenJDK 64-Bit Server VM (build 25.112-b15, mixed mode)

Building currently leads to:
[info] Resolving org.scala-sbt#sbt-launch;0.13.13 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbt#sbt-twirl;1.3.0: not found
[warn]  :: com.typesafe.sbt#sbt-native-packager;1.1.1: not found
[warn]  :: com.typesafe.sbt#sbt-web;1.3.0: not found
[warn]  :: com.typesafe.sbt#sbt-js-engine;1.1.3: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.typesafe.sbt:sbt-twirl:1.3.0 (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-native-packager:1.1.1 (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-web:1.3.0 (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-js-engine:1.1.3 (scalaVersion=2.12, sbtVersion=0.13)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.typesafe.sbt:sbt-twirl:1.3.0 (scalaVersion=2.12, sbtVersion=0.13) (/home/myAwesomeUsername/playframework/framework/build.sbt#L178)
[warn]            +- com.typesafe.play:sbt-plugin:2.6.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-native-packager:1.1.1 (scalaVersion=2.12, sbtVersion=0.13) (/home/myAwesomeUsername/playframework/framework/build.sbt#L178)
[warn]            +- com.typesafe.play:sbt-plugin:2.6.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-web:1.3.0 (scalaVersion=2.12, sbtVersion=0.13) (/home/myAwesomeUsername/playframework/framework/build.sbt#L178)
[warn]            +- com.typesafe.play:sbt-plugin:2.6.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-js-engine:1.1.3 (scalaVersion=2.12, sbtVersion=0.13) (/home/myAwesomeUsername/playframework/framework/build.sbt#L178)
[warn]            +- com.typesafe.play:sbt-plugin:2.6.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=0.13)
[trace] Stack trace suppressed: run last SBT-Plugin/*:update for the full output.
[error] (SBT-Plugin/*:update) sbt.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-twirl;1.3.0: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.1.1: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-web;1.3.0: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-js-engine;1.1.3: not found
[error] Total time: 10 s, completed Dec 6, 2016 9:49:08 PM

I just downloaded a fresh copy of playframework, without any modifications. Also see: http://stackoverflow.com/questions/40990256/cant-download-sbt-plugin-2-5-4-using-activator-on-osx-platform

I can connect to any of those repos, but they are indeed empty or the path is invalid

**Comment by wsargent** [comment]
Please provide a repeatable use case.

**Comment by RookieMaus** [comment]
repeatable test case for me (tried on my local machine (os as mentioned above) and on windows 7 even via mobile hotspot instead of my wired connection):

1) git clone git://github.com/playframework/playframework.git
2) cd playframework/framework
3) sbt
4) +publishLocal

or if you want +++2.12.0 publishLocal or +++2.12.1 publishLocal or with +++2.11.8 publishLocal

Always get the same error. (tried to repeat multiple times now, while deleting whole repository and cloning again, also deleted .ivy2 folder and sbt cache and whatnot)

**Comment by schmitch** [comment]
@RookieMaus 
actually I've just setup a whole new virtual machine centos and didn't had any error.
However on my development mac I had this error once and actually on the new virtual machine it took really really long to download sbt from bintray/akami so I actually copied it, after that it looked like the repositories gone back to normal so I would suggest trying it again.

**Comment by RookieMaus** [comment]
@schmitch thanks, but no luck. Doesn't matter what I try. Again I deleted cache and whatnot and first time it looks like it completes successfully, but still sbt cannot be resolved, second time I build I get that unresolved dependency shit.

Well, now that I tried every proposed option I will just wait. Maybe the gods are merciful and I can compile it successfully someday.

**Comment by schmitch** [comment]
Actually this line can be ignored. Also if you use `sbt` you should have no problem.
I actually encourage you to use the [Mailing List](https://groups.google.com/forum/#!forum/play-framework), since this is not a bug and we only track issue's here and not help questions, these can be asked freely on the mailing list.

(even travis-ci can actually find all the dependencies https://travis-ci.org/schmitch/playframework/builds/182131146)
And if you just want to test 2.12 you can use a snapshot: https://www.playframework.com/documentation/2.5.x/Repositories#Accessing-snapshots

**Comment by RookieMaus** [comment]
Actually, no, 2.12 support is not the only thing I am after. But thanks anyway.

Apart from that, do I have to manually scan the repository to find out what is the latest snapshot version? Because "com.typesafe.play#sbt-plugin;2.6.0-SNAPSHOT" cannot be resolved there either :(

But alas, on to the mailing list or some chat

**Comment by wsargent** [comment]
If you're having issues downloading sbt-twirl from the remote server e.g. sonatype is hiccuping, you can always build from source:

```
git clone https://github.com/playframework/twirl.git
cd twirl
git checkout -b 1.3.0 1.3.0
sbt +compile +publishLocal
```

**Comment by wsargent** [comment]
I think this could be 2.12 related.

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbt#sbt-twirl;1.3.0: not found
[warn]  :: com.typesafe.sbt#sbt-native-packager;1.1.1: not found
[warn]  :: com.typesafe.sbt#sbt-web;1.3.0: not found
[warn]  :: com.typesafe.sbt#sbt-js-engine;1.1.3: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.typesafe.sbt:sbt-twirl:1.3.0 (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-native-packager:1.1.1 (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-web:1.3.0 (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-js-engine:1.1.3 (scalaVersion=2.12, sbtVersion=0.13)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.typesafe.sbt:sbt-twirl:1.3.0 (scalaVersion=2.12, sbtVersion=0.13) (D:\work\playframework\master\framework\build.sbt#L178)
[warn]            +- com.typesafe.play:sbt-plugin:2.6.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-native-packager:1.1.1 (scalaVersion=2.12, sbtVersion=0.13) (D:\work\playframework\master\framework\build.sbt#L178)
[warn]            +- com.typesafe.play:sbt-plugin:2.6.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-web:1.3.0 (scalaVersion=2.12, sbtVersion=0.13) (D:\work\playframework\master\framework\build.sbt#L178)
[warn]            +- com.typesafe.play:sbt-plugin:2.6.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=0.13)
[warn]          com.typesafe.sbt:sbt-js-engine:1.1.3 (scalaVersion=2.12, sbtVersion=0.13) (D:\work\playframework\master\framework\build.sbt#L178)
[warn]            +- com.typesafe.play:sbt-plugin:2.6.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=0.13)
```

Twirl is still running on Interplay 1.2.0, so I wonder if that could be the problem.  Will upgrade to 1.3.0 and Scala 2.12.1

**Comment by wsargent** [comment]
See https://github.com/playframework/twirl/pull/126

**Comment by RookieMaus** [comment]
And, does it work for you now? Here it worked once (seemingly randomly after I deleted my .m2 folder) and then never again.
