### ISSUE TITLE
Potential delete of temporary file before it is used

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#6786]
Play 2.5.10

when using `Action.async(parse.raw)` you get a `RawBuffer` as body.

This internally has a `TemporaryFile` that is unreachable but which will remove the file when it is garbage collected. 

```scala
    /**
     * Delete this file on garbage collection.
     */
    override def finalize() {
      clean()
    }
```

This `RawBuffer` also has a method `asFile()` which returns `backedByTemporaryFile.file`

If you put this file in a queue and want to process it after the request has finished there is a chance that it has been removed by a garbage collection of the no longer referenced TemporaryFile.

It would be better to return the TemporaryFile which has a `moveTo()` after which you become responsible for cleaning up the file.
(preferable this TemporaryFile would not even allow access to its file property)

see #3913 for a related discussion

**Comment by mkurz** [comment]
Also related: #5545

**Comment by wsargent** [comment]
This may be addressed by https://github.com/playframework/playframework/pull/6759

**Comment by wsargent** [comment]
@francisdb also see https://github.com/playframework/play-fileupload-scala

**Comment by francisdb** [comment]
I don't like this body parser solution. Would prefer to get something like a Request[Source[Byte, _]] from my action.

**Comment by wsargent** [comment]
A request is an output from the body parser, so you can probably write your own body parser that returns you a `Source[ByteString, _]]` like you're asking for:

https://www.playframework.com/documentation/2.5.x/ScalaBodyParsers#Writing-a-custom-body-parser

**Comment by wsargent** [comment]
> "If you put this file in a queue and want to process it after the request has finished"

I think this is a special case outside of Play's file handling -- when the request is finished, Play is no longer responsible for ensuring the file sticks around.  If anything, Play should ensure that file does not stick around after the request is done.  As previously noted, there are facilities that Play provides to offload data as it's received, so this is something Play can do, but should not do by default.

**Comment by francisdb** [comment]
That was just an example, I still think this small change would make the api more explicit:

> It would be better to return the TemporaryFile which has a moveTo() after which you become responsible for cleaning up the file.

**Comment by wsargent** [comment]
The user should not be responsible for cleaning up the file, though -- it should be cleaned automatically shortly after the request is completed.

**Comment by francisdb** [comment]
Indeed the user should not unless he/she wants to keep it available after the request what this unaccessible `moveTo()` is normally used for. But in the RawBuffer case you only have `asFile()`.

I like the idea of the type telling you what you get, like `RequestBoundTemporaryFile`.

Anyway, I guess you have more important things to tackle than discussing this so this is my final comment.

**Comment by landlockedsurfer** [comment]
I ran into a similar issue when using `TemporaryFile` when sending E-Mail with an attachment. As with `RawBuffer` and `asFile` in @francisdb's case, I'm passing the `file` member to a mailing library resulting in the same issue: The garbage collector calls the `finalize` method and removes the temporary file prematurely.

Adding to this discussion, I've written a small Scalatest suite to show the effect:
```
package finalize

import java.io.{File, FileWriter}
import java.nio.file.Files

import org.scalatest.FunSuite

case class TempFile(val name:String) {

  val file = new File(name)
  val writer = new FileWriter(file)
  writer.close()

  override def finalize(): Unit = {
    println("finalizing!!!")
    Files.delete(file.toPath)
    super.finalize()
  }
}

class FinalizeSuite extends FunSuite {

  def createTempFileAndReturnFileInstance(name:String) = {
    TempFile(name).file
  }

  def createTempFile(name:String) = {
    TempFile(name)
  }

  test("Keeping Tempfile in helper method scope and returning file member prematurely garbage collects TempFile") {
    val x = createTempFileAndReturnFileInstance("1.txt")
    // Request garbage collection cycle/finalization
    System.gc()
    System.runFinalization()
    // Give VM some time to run garbage collection
    Thread.sleep(1000)
    assertThrows[java.nio.file.NoSuchFileException](Files.move(x.toPath, new File("2.txt").toPath))
  }

  test("Keeping the Tempfile instance in scope of test will not garbage collect TempFile") {
    val tempFile = createTempFile("I.txt")
    // Request garbage collection cycle/finalization
    System.gc()
    System.runFinalization()
    // Give VM some time to run garbage collection
    Thread.sleep(1000)
    val newFile = new File("II.txt")
    Files.move(tempFile.file.toPath, newFile.toPath)
    Files.delete(newFile.toPath)
  }
}
```
Here the `build.sbt` file:
```
name := "TempFile Finalization"

scalaVersion := "2.11.8"

libraryDependencies ++= Seq(
  "org.scalatest"              %% "scalatest"              % "3.0.1" % "test"
)

fork in Test := true
```
And the output:
```
> testOnly finalize.FinalizeSuite
[info] FinalizeSuite:
finalizing!!!
[info] - Keeping TempFile instance in helper method scope and returning file member will prematurely garbage collect TempFile instance
[info] - Keeping the TempFile instance in scope of test will not garbage collect TempFile
[info] Run completed in 2 seconds, 729 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 3 s, completed Apr 8, 2017 6:51:36 PM
```

**Comment by wsargent** [comment]
@landlockedsurfer I still don't see this as something that Play should do by default -- the temporary file is available and you have a file handle to it, and can copy or rename the file, preferably in a future using a different execution context.
