### ISSUE TITLE
MongoDB close connection in akka actor with play framework 2.5 for scala

### ISSUE THREAD

**Issue by LongIT644** [playframework/playframework#6791]
I get exception when interact with mongodb by plugin https://github.com/cloudinsights/play-salat/issues with play framwork for scala, in akka actor fir scheduler job.

`"exception":{"name":"class java.lang.IllegalStateException","message":"open","trace":[["org.bson.util.Assertions.isTrue(Assertions.java:36)","com.mongodb.DBTCPConnector.isMongosConnection(DBTCPConnector.java:375)","com.mongodb.Mongo.isMongosConnection(Mongo.java:622)","com.mongodb.DBCollection.findOne(DBCollection.java:936)","com.mongodb.DBCursor.one(DBCursor.java:807)"]]}

**Comment by gmethvin** [comment]
Hi @LongIT644,

There is no information here to indicate that this is a bug in Play, so I am closing this issue. If you are looking for help please do so on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).

If you still believe this is a bug in Play, please provide the information requested in the issue template and we will re-evaluate.
