### ISSUE TITLE
JNDI data sources are sometimes accessed before they are bound when using JPA API with Hibernate as the provider

### ISSUE THREAD

**Issue by sevasm** [playframework/playframework#6792]
### Play Version

2.5.10

### API

Java

### Operating System

Windows 8.1

### JDK

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

### Library Dependencies

Hibernate 4.3.11 or 5.2.5

### Expected Behavior

Data sources should be bound to JNDI before DefaultJPAApi / Hibernate attempts to look them up.

### Actual Behavior

Our application uses Play with Java, JPA and Hibernate as the JPA provider. We use injected instances of JPAApi throughout the application to access the JPA API. Intermittently, during application startup, we get an injection exception:
Error injecting constructor, javax.persistence.PersistenceException: Unable to build entity manager factory
...
Caused by: javax.naming.NameNotFoundException: [data source name] not found

where [data source name] is the name of our data source.

Looking at the source code for the JPA implementation in Play I have found the following:

1. play.db.jpa.JPAApi is bound to play.db.jpa.DefaultJPAApi.JPAApiProvider by play.db.jpa.JPAModule
2. play.db.jpa.DefaultJPAApi.JPAApiProvider is a singleton and instantiates play.db.jpa.DefaultJPAApi when it is instantiated itself and calls play.db.jpa.DefaultJPAApi#start() during initialisation.
3. play.db.jpa.DefaultJPAApi#start() immediately attempts to create all persistence units returned by play.db.jpa.JPAConfig#persistenceUnits().
4. javax.persistence.Persistence#createEntityManagerFactory(String) is called for each persistence unit name.
5. As the persistence unit uses a JNDI data source, Hibernate attempts to look up the data source, ultimately calling javax.naming.InitialContext#lookup(javax.naming.InitialContext)

Looking at the connection pool implementation in Play (using the default Hikari connection pool) I have found the following:

1. play.api.db.DBApi is bound to play.api.db.DBApiProvider by play.api.db.DBModule
2. play.api.db.DBApiProvider is a singleton and instantiates play.api.db.DefaultDBApi when it is instantiated itself and calls play.api.db.DefaultDBApi#connect(Boolean) during initialisation.
3. This method attempts to retrieve and immediately close a connection from each configured database, which causes all connection pools to be created by calling the ConnectionPool#create(String, DatabaseConfig, Config) method
4. When the Hikari connection pool is created, it creates the underlying data source and binds it to JNDI by calling javax.naming.InitialContext#rebind(String, Object)

Both lists of actions take place during application startup as Guice is instantiating the bound classes. Here's the injection graph for a Play application (obtained using Guice Grapher):

![guice-graph](https://cloud.githubusercontent.com/assets/366521/21099983/502d04ee-c069-11e6-9880-ab1d329c4aac.png)

From the graph it's clear that the implementations of JPAApi and DBApi do not have any dependencies that would ensure the order in which they are both created, so there is no guarantee that the data source is bound to JNDI by HikariCPConnectionPool before it is accessed by DefaultJPAApi.

### Reproducible Test Case

I have not been able to reproduce this reliably without modifying the Play framework code. However, modifying HikariCPConnectionPool to have JPAApi as a dependency causes the same exception to always appear during startup (as it forces DefaultJPAApi to create the entity manager factory and this in turn causes Hibernate to lookup the data source before it is bound).

**Comment by wsargent** [comment]
Thanks for the detailed description.  From your description, this is a case where modules need to have explicit ordering set up, by ensuring they both depend on a provider that does the required config?

Note that there's a JNDI commit which moves JNDI out of Guice completely in the master branch (what will eventually become 2.6.x):

https://github.com/playframework/playframework/pull/6736

**Comment by sevasm** [comment]
Yes, one way to resolve this is to ensure the correct order of dependency injection between DBApi and JPAApi. Locally I have done this by modifying the constructor for play.db.jpa.DefaultJPAApi.JPAApiProvider to take in an additional play.db.DBApi parameter. This ensures that an instance of DBApi is created before DefaultJPAApi is instantiated and started, which in turn causes all connection pools to be initialised and bound to JNDI before they are looked up.

As the additional DBApi constructor parameter is not actually used I am hesitant to call it a fix, more a work around maybe. However, with a comment explaining the unused constructor parameter it could be acceptable. If you agree with this then I can work on the PR.

My final concern is that other than generating a new Guice injection graph that confirms the correct order of injection I cannot think of a test that reproduces the issue and confirms the fix is working as intended. Any comments / suggestions regarding a viable test is of course welcome.

**Comment by marcospereira** [comment]
@sevasm,

I don't think there is another way achieve that with Guice. There is even a comment at the code to express that:

https://github.com/playframework/playframework/blob/613d53b84076d126cb810f79197a5aa50ebd3bb6/framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java#L40-L40

Unfortunately, the dependency on `DBApi` was removed (see https://github.com/playframework/playframework/commit/4956e70f4562560b724d3c46b1f1274a426f8dd2#diff-2b5896479484107dce7c9f1f83f38bd6L37) and the dependency graph is now broken. But, as @wsargent explained, the proper solution is to add the `DBApi` dependency back.

**Comment by sevasm** [comment]
I missed the comment when investigating, but it and the commit you linked explains why we started seeing the problem only after we migrated from 2.2.1 to 2.5.3. Thanks for taking a look. I'll work on the PR.
