### ISSUE TITLE
Broken link on SettingsLogger page

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#6797]
On this page https://www.playframework.com/documentation/2.5.x/SettingsLogger there is this text:

> For details on the performance implications on this, see this [blog post](https://blog.takipi.com/how-to-instantly-improve-your-java-logging-with-7-logback-tweaks/)

but the scheme of the link should be http not https.  The current link causes an error message in Chrome.

**Comment by marcospereira** [comment]
Thanks, @rmcloughlin.

Do you mind to submit a pull request to fix that?

**Comment by marcospereira** [comment]
See #6871.
