### ISSUE TITLE
Url parameters bug

### ISSUE THREAD

**Issue by PatrickSauts** [playframework/playframework#6801]
### Play Version 2.5.10, Api Scala, JDK Oracle 1.8.0_111, 

Tested on **Firefox** for MacOs, **Chrome** for MacOs, **Postman** and **Safari**

We upgrading from Play 2.3.4 to 2.5.10 the migration is completed except for the problem below.

Our urls contain parameters like {} and since the switch to 2.5.10  we're getting this error
```
For request 'GET /pat/resources/BodhiApplication?where={%22name%22:%22hsdashboard%22}' [Illegal character in query at index 38: /pat/resources/BodhiApplication?where={%22name%22:%22hsdashboard%22}]
```

This problem occurs with these "Unsafe characters"
   Left Curly Brace ("{")
   Right Curly Brace ("}")
   Vertical Bar/Pipe ("|")
   Backslash ("\")
   Caret ("^")
   Grave Accent ("`")

The expected behavior would be to accept these characters without error ( "complaint") to be compatible with existing browsers.

**Comment by mlovrovich** [comment]
+1
I am also experiencing this behavior after upgrading

**Comment by wsargent** [comment]
Hi @PatrickSautsThis looks like a java.net.URL error where the URL is passed in without URL encoding. Can you provide a full stacktrace and a test case showing the error?

**Comment by PatrickSauts** [comment]
We're not getting any stacktrace.
We're currently in the process of patching the class below to encode these "Unsafe characters"
```
https://github.com/playframework/playframework/blob/2.5.10/framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
```
This is indeed a java.net.URL error but we previous Play version 2.3.4 works perfectly with the same JDK version.

While patching the class we'll try to produce a stacktrace this however seems related to a fixed bug https://github.com/playframework/playframework/pull/6072
Getting the host has been fixed getting the query parameters is still not working

**Comment by mellster2012** [comment]
Hi @wsargent The URISyntaxException is thrown at line 41-42 in NettyModelConversion.scala in the parseUri method :
```
    // wrapping into URI to handle absoluteURI and Failures
    val javaUri = new URI(rawUri)
```
You are correct that some unsafe characters are not encoded, however many browsers and clients do not encode some of those unsafe characters either - e.g. '{' and '}' - and previous versions of play-netty may not have parsed the URI strictly (probably just dealt with the raw string), so those calls would not fail. Something like a lenient flag for backwards compatibility would be awesome, otherwise we would have to use our own play-netty patched version or use runtime bytecode instrumentation to stay backwards compatible with our clients for the time being.

**Comment by wsargent** [comment]
@mellster2012 if you can provide a failing test case that would be great.

**Comment by PatrickSauts** [comment]
@wsargent can you point me to a way to reproduce using the tests also I can't even reproduce in our application using FakeRequest

FakeRequest Line 65
```
  /**
   * The request query String
   */
  lazy val queryString: Map[String, Seq[String]] =
    play.core.parsers.FormUrlEncodedParser.parse(rawQueryString)
```

```
Having RequestHeader.scala doing line 161
```
lazy val rawQueryString: String = uri.split('?').drop(1).mkString("?")
```

Which just works.
So I'm not really sure how to give you a test case.
