### ISSUE TITLE
Quote filenames for the Content-Disposition: attachment header.

### ISSUE THREAD

**Issue by strelec** [playframework/playframework#6819]
Otherwise you get ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION error in chrome for files with commas in the filename.

Before:
Content-Disposition: attachment; filename=comma,problem.pdf

After:
Content-Disposition: attachment; filename="comma,problem.pdf"

**Comment by marcospereira** [comment]
Which version of Play are you using? Can you create a test case that reproduces the problem?

**Comment by strelec** [comment]
Ok.sendFile(outFile, inline = false, _ => "this,has,a,comma.pdf")

I have latest 2.5.

**Comment by gmethvin** [comment]
We are already quoting filenames and we have tests confirming it: https://github.com/playframework/playframework/blob/2.5.x/framework/src/play/src/test/java/play/mvc/ResultsTest.java#L47

Closing.
