### ISSUE TITLE
Deploying to a cloud service: add openshift to the list

### ISSUE THREAD

**Issue by almothafar** [playframework/playframework#6830]
Currently, I'm working with deploying play framework application to Openshift cloud, I made it work very good and without any complex steps, easy peasy, I forked original cartridge and maintain it to work perfectly with auto scale gears, and I was able to do load test on the production project with 500 concurrent users serving almost half of million requests for 30 minutes load, in better version I was able to handle 500RPS with only 4 gears, it was stable and really nice auto-scale feature in Openshift was working as intended.

You can see the steps and details here:
https://github.com/almothafar/openshift-cartridge-play2

**Comment by marcospereira** [comment]
That is awesome, @almothafar.

Do you mind submitting a pull request to add it here:

https://github.com/playframework/playframework/tree/master/documentation/manual/working/commonGuide/production/cloud

Thanks.

**Comment by almothafar** [comment]
@marcospereira Sure I'll do PR with steps for Openshift, once I get free time, later this week.

**Comment by schmitch** [comment]
unfortunatly OpenShift v2 is deprecated in favor of the new one, where you don't need such a complicated cartridge..

**Comment by almothafar** [comment]
@schmitch oh you right, they will no longer accept users to v2 in next August.
Need some more research and trying to deploy in v3 : http://stackoverflow.com/questions/39528802/how-to-deploy-play-framework-app-to-openshift-v3

**Comment by marcospereira** [comment]
Ok. I'm closing this. We can move this forward later in a pull request explaining how to deploy to OpenShift 3.
