### ISSUE TITLE
Single property case class Json.reads macro wrong path

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#6846]
play 2.5.10

When generating reads/format for single property case classes the resulting reads function returns a JsResult that is not on the root path. For 2 or more properties this behaves correctly.
See the provided test case and output below:

```scala
case class Single(prop1: String)
case class Two(prop1: String, prop2: String)

"correctly path for a single property case class" in {
      val singleReads = Json.reads[Single]
      val json = Json.obj(
        "prop1" -> "foo"
      )
      singleReads.reads(json) must be equalTo JsSuccess(Single("foo"))
}

"correctly path for a two property case class" in {
      val twoReads = Json.reads[Two]
      val json = Json.obj(
        "prop1" -> "foo",
        "prop2" -> "bar"
      )
      twoReads.reads(json) must be equalTo JsSuccess(Two("foo", "bar"))
}
```

the output for this test is

```
[info] the generated reads should
[error]   x correctly path for a single property case class
[error]    'JsSuccess(Single(foo),/prop1)' is not equal to 'JsSuccess(Single(foo),)' (Test.scala:19)
[error] Actual:   ...foo),[/prop1])
[error] Expected: ...foo),[])
[info]
[info]   + correctly path for a two property case class
[info]
```

also found this one but seems it's already fixed
https://github.com/playframework/playframework/pull/6568

**Comment by cchantep** [comment]
Hi,

As far as I can see, the tests for the JSON macros weren't there in 2.5.10.

For now in master of the separate repo, this case is already covered and working: https://github.com/playframework/play-json/blob/master/play-json/src/test/scala/play/api/libs/json/MacroSpec.scala#L36

There may be some code to port if the issue is confirmed in 2.5.x.

**Comment by francisdb** [comment]
This test validates the reading of a simple case class which already works on 2.5.x but not that the path of the returned JsSuccess is correct.

Would be better to validate the whole result instead like 
```scala
Json.reads[Simple].reads(Json.obj("bar" -> "lorem")) // no .get here!
        must_== JsSuccess(Simple("lorem"))
```
