### ISSUE TITLE
Idletimeout netty setting dosen't work 

### ISSUE THREAD

**Issue by leosimoesp** [playframework/playframework#6847]
I'm trying to set Netty server props into application.conf without success.
The Netty server embeed into play not close tcp connections. Is there way to implement IdleStateHandler into play ?

#play.server{
#  provider = "play.core.server.NettyServerProvider"
#  netty {
#    log.wire = true
#  }
#}

#play.server.netty.transport="native"
#play.server.netty.option.child.SO_KEEPALIVE=true
#play.server.netty.option.child.SO_BACKLOG=128
#play.server.netty.option.child.TCP_NODELAY=true
#play.server.netty.option.child.TCP_USER_TIMEOUT=5
#play.server.netty.option.child.CONNECT_TIMEOUT_MILLIS=5 

Hum, It seems a old problem :(

https://github.com/playframework/playframework/issues/1103

**Comment by gmethvin** [comment]
@leosimoesp Can you please clarify what version of Play you're using, what the expected and actual behavior is?

If this is just a general question and not an actual bug report, you can ask on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).

**Comment by leosimoesp** [comment]
Hi, I'm using play scala 2.5.10 with activator. I've created a external netty server test using idleStateHandler and tcp are closed after request. The problem is Play's Netty Server is embeeded. 
My application stops after concurrent connections finished. My client close connection database correctly. I do a test with a simple request without DB access and the problem is the same.
I saw many posts into git and stackoverflow with this similiar issue.

**Comment by schmitch** [comment]
Some Netty/Play Server Options can only be set via System Properties or `devSettings` in Dev Mode.
Also the Play Idle Timeout can be set via: `play.server.http.idleTimeout` or `play.server.https.idleTimeout`.

Also the Mailinglist is definitly a better place to ask questions.

Closing since this is more a question than a bug.
https://www.playframework.com/documentation/2.5.x/ConfigFile#HTTP-server-settings-in-application.conf

**Comment by leosimoesp** [comment]
All of configs dosen't work unfortunately.

**Comment by AlekseyMko** [comment]
I tried play.server.http.idleTimeout=15s in application.conf and via java options
Nothing works
I tried with Play 2.5.18

**Comment by AlekseyMko** [comment]
And there is nothing about this options in the documentation

**Comment by schmitch** [comment]
There is.
In Dev Mode you need to add it in your build.sbt (https://www.playframework.com/documentation/2.5.x/ConfigFile#Using-with-the-run-command):

`PlayKeys.devSettings := Seq("play.server.http.idleTimeout" -> "15s")`

**Comment by AlekseyMko** [comment]
But unfortunately, it doesn't work for Netty in production mode too.
I tried 2.5.x and 2.6.x.
It works only for AkkaHttp

**Comment by mkurz** [comment]
Turns out `play.server.http.idleTimeout` was actually not working for websockets when using the netty backend, see #11420, will be fixed with Play 2.8.19
