### ISSUE TITLE
GzipFilter ignores cookie/session/flash

### ISSUE THREAD

**Issue by AtkinsChang** [playframework/playframework#6849]
### Expected Behavior
use http compression will retain cookies and session/flash

### Actual Behavior
using `play.filters.gzip.GzipFilter` will ignore all cookies and session/flash

### Reproducible Test Case
no need,  in this [this matching](https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala#L66), the result is a new `Result` instance with only header and body which ignore all cookies and flash/session.

I can provide the PR and test cases if needed.

**Comment by marcospereira** [comment]
Thanks @AtkinsChang.

Please, see PR #6851.

**Comment by AtkinsChang** [comment]
LGTM
