### ISSUE TITLE
netty config doesn't work

### ISSUE THREAD

**Issue by peanutgyz** [playframework/playframework#6858]
when is set log.wire = true in conf/application.conf

play.server{
provider = "play.core.server.NettyServerProvider"
netty {
log.wire = true
}
}

and set breakpoint in NettyServer.class

```

class NettyServer(
    config: ServerConfig,
    val applicationProvider: ApplicationProvider,
    stopHook: () => Future[_],
    val actorSystem: ActorSystem)(implicit val materializer: Materializer) extends Server {

  private val nettyConfig = config.configuration.underlying.getConfig("play.server.netty")
// break point here

  private val maxInitialLineLength = nettyConfig.getInt("maxInitialLineLength")

  private val maxHeaderSize = nettyConfig.getInt("maxHeaderSize")
```

nettyConfig read frome jar/reference.conf , not from application.conf

```ConfigOrigin(reference.conf @ jar:file:/Users/gui/.ivy2/cache/com.typesafe.play/play-netty-server_2.11/jars/play-netty-server_2.11-2.5.10.jar!/reference.conf)```

why netty server doesn't read config from application.conf ?

**Comment by schmitch** [comment]
The netty config can't be set in Development Mode via the Application Config:
https://www.playframework.com/documentation/2.5.x/ConfigFile#Using-with-the-run-command

Please ask for Question on the Mailinglist: https://groups.google.com/forum/#!forum/play-framework
