### ISSUE TITLE
File 1.sql keeps beeing created even if evolutions are turned off

### ISSUE THREAD

**Issue by JFCote** [playframework/playframework#6864]
**Play Version:** Tested in 2.4.8 and 2.5.10 (Was working in 2.3.10)
**API:** Java
**Operating System:** Windows 10
**JDK:** 1.8_60

**Expected Behavior**

1. Start Website
2. No files are created in the "conf/evolutions" folder

**Actual Behavior**

1. Start Website
2. A file named "1.sql" is created in the "conf/evolutions" folder

In my application.conf, I have the following

```
play.evolutions {
  db.default.enabled = false
}
```

I have tried different notation but all of them have the 1.sql created anyway.

**Comment by marcospereira** [comment]
Hello @JFCote,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

**Comment by JFCote** [comment]
Well AFAIK it's a bug. A file is created when the config clearly turn it off. So my guess is that the configuration to disable the evolution is broken.

**Comment by vdegrandpre** [comment]
Same here ! (Nice guitar JFCote)

**Comment by shkhln** [comment]
This is actually a feature[*](https://github.com/playframework/play-ebean/blob/6e2250acf87834eac146e14bbfb926ba288da588/play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java#L61) of the play-ebean module. It is not configurable, but you can remove autogenerated contents and leave that file as a placeholder. Play won't touch it again.

**Comment by JFCote** [comment]
Thanks @shkhln . Do you know why it is a feature and the reason why it was implemented?

**Comment by shkhln** [comment]
Well, the *schema generation* itself is a feature of Ebean, so it's kinda nice that play-ebean exposes it. As for why it hasn't been made configurable… I guess nobody had given it much thought.
