### ISSUE TITLE
[doc] NewApplication should be updated

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6867]
### Play Version (2.5.x / etc)

2.5.x

### API (Scala / Java / Neither / Both)

Neither

### Actual Behavior

Right now, the NewApplication page at https://www.playframework.com/documentation/2.5.x/NewApplication / https://github.com/playframework/playframework/blob/master/documentation/manual/gettingStarted/NewApplication.md still includes activator with `play-scala` / `play-java` and does not include a reference to the giter8 seeds.

The documentation should point people directly to http://playframework.com/download, rather than repeating the text.

**Comment by wsargent** [comment]
Note that this should happen as a PR on `master` and then be cherry-picked back to `2.5.x`

**Comment by wsargent** [comment]
Also see https://github.com/playframework/playframework/issues/6868

**Comment by marcospereira** [comment]
See #6856.

**Comment by marcospereira** [comment]
@wsargent can we close this?
