### ISSUE TITLE
[doc] CSRF Token not stored in session

### ISSUE THREAD

**Issue by albuch** [playframework/playframework#6878]
### Play Version (2.5.x / etc)
2.5.x

### API (Scala / Java / Neither / Both)
Both

### Expected Behavior

Documentation should state that a [double submit cookie](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#Double_Submit_Cookie) is used for CSRF protection.

### Actual Behavior

Current documentation states that the CSRF token is stored in the user session.

https://github.com/playframework/playframework/blob/master/documentation/manual/working/javaGuide/main/forms/JavaCsrf.md
https://github.com/playframework/playframework/blob/master/documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
> The primary mechanism is a CSRF token. This token gets placed either in the query string or body of every form submitted, and also gets placed in the users session. Play then verifies that both tokens are present and match.

**Comment by marcospereira** [comment]
Thanks @albuch, do you want to submit a pull request to improve the docs?

**Comment by albuch** [comment]
Sure, in which branch should it be fixed?

**Comment by marcospereira** [comment]
Hey @albuch,

Please submit your PR against master branch. After that, we can backport it (if necessary) to 2.5.x branch.

Thanks!

**Comment by gmethvin** [comment]
@albuch Actually by default the token is stored in the user session (and signed). But it can be configured to use a cookie. See https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/resources/reference.conf#L24

**Comment by albuch** [comment]
@gmethvin thanks for pointing that out. I assumed that the default was a cookie without checking the default config first. Closing the issue.

**Comment by gmethvin** [comment]
Technically it's the same thing as a double submit cookie. It's just storing the random token in the session cookie instead of a separate cookie. You're welcome to submit a pull request providing a more technical explanation if you want.
