### ISSUE TITLE
[activator] Broken link in play-scala project web page

### ISSUE THREAD

**Issue by nloyola** [playframework/playframework#6881]
I'm not sure if this is the right place to submit this issue. If not, where should this be reported?

On the [LIGHTBEND ACTIVATOR / PLAY SCALA SEED](http://www.lightbend.com/activator/template/play-scala) page, the link to the github repository is broken:

https://github.com/playframework/playframework/tree/master/templates/play-scala

Clicking on the link yields a 404 page.

**Comment by wsargent** [comment]
The correct link is https://github.com/playframework/play-scala

**Comment by benmccann** [comment]
http://www.lightbend.com/activator/template/play-java has a broken "Source" link as well

**Comment by wsargent** [comment]
Maybe we can just put https://developer.lightbend.com/start/?group=play as the link everywhere...

**Comment by benmccann** [comment]
Then it'd take three clicks instead of one to get to the source. If we have to update them all I'm not sure it's that much harder to point to the individual repos

**Comment by wsargent** [comment]
Activator is being deprecated in any event...

**Comment by wsargent** [comment]
@corruptmemory I remember I mentioned this but I forgot the context...

**Comment by marcospereira** [comment]
Activator is gone. The example projects can now be accessed here:

https://developer.lightbend.com/start/?group=play

I'm closing this.
