### ISSUE TITLE
Max-Age in DiscardingCookies gets changed to 0 which causes Expires to be now

### ISSUE THREAD

**Issue by gregghz** [playframework/playframework#6888]
### Play Version (2.5.x / etc)

2.5.10

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

    Linux gregg.office.lucidchart.com 3.13.0-106-generic #153-Ubuntu SMP Tue Dec 6 15:44:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

    $ java -version
    openjdk version "1.8.0_111"
    OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-3~14.04.1-b14)
    OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

### Expected Behavior

When calling `Result.discardingCookies` it is expected that Max-Age gets set to -86400 and Expires gets set to 1 day ago on the discarded cookie regardless of additional cookie operations.

Or at least, Max-Age and Expires for discarded cookies should be set to the same values whether or not I perform additional cookie operations.

### Actual Behavior

`Ok.discardingCookies(...)` works as expected (Max-age is -86400 and Expires is 1 day ago). When you add additional cookie operations like `Ok.discardingCookies(...).withCookies(...)` the Max-Age of discarded cookies gets set to 0 and Expires is set to the current date/time.

In [ClientCookieDecoder.java](https://github.com/playframework/playframework/blob/master/framework/src/play-netty-utils/src/main/java/play/core/netty/utils/ClientCookieDecoder.java#L239) you can see where Max-Age is set to 0:

    private void setMaxAge(String value) {
        try {
            maxAge = Math.max(Integer.valueOf(value), 0);
        } catch (NumberFormatException e1) {
            // ignore failure to parse -> treat as session cookie
        }
    }

And then in [ServerCookieEncoder.java](https://github.com/playframework/playframework/blob/master/framework/src/play-netty-utils/src/main/java/play/core/netty/utils/ServerCookieEncoder.java#L87) you find this code:

    if (cookie.maxAge() != Integer.MIN_VALUE) {
        add(buf, CookieHeaderNames.MAX_AGE, cookie.maxAge());
        Date expires = new Date(cookie.maxAge() * 1000l + System.currentTimeMillis());
        add(buf, CookieHeaderNames.EXPIRES, HttpHeaderDateFormat.get().format(expires));
    }

In general, this is probably what you want. However, IE/Edge does _not_ support max-age and relies entirely on the Expires of the cookie. Play is forcing Expires to match Max-Age. If the IE/Edge client has an incorrect clock set slow by a few minutes, the cookies are not expired immediately. In play 2.3.x, Expires would be set to a value a day in the past which would properly expire the cookie in IE/Edge.

I would also expect the Set-Cookie headers to have the same Max-Age and Expires regardless of whether or not I call additional cookie operations.

### Reproducible Test Case

I've created a sample play project here: https://github.com/lucidsoftware/play-cookie-issue

I'm not sure what to test for here. Should Max-Age not get reverted to 0 or should Expires be set to a value matching Max-Age before Max-Age is set to 0?

A test to verify max-age is set to 0 is already present here: https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala#L122

**Comment by gmethvin** [comment]
I don't see any good reason for the `Math.max` call in `ClientCookieDecoder`, so we should probably just read the max-age value in the header. It is valid to have a negative max-age value; it means the same thing as zero: https://tools.ietf.org/html/rfc6265#section-5.2.2

The problem is that whenever you make a call to `withCookies` or `discardingCookies` it tries to decode the existing cookies and re-encode them. So, to work around this you can just make `discardingCookies` the last call you make.
