### ISSUE TITLE
fork in run := true breaks auto-reload

### ISSUE THREAD

**Issue by hnan** [playframework/playframework#6900]
When setting `fork in run := true`, auto reload does not work well.

Auto reload works when changing stuff in index.scala.html, but not work when changing stuff in main.scala.html. (In a fresh new scala project)

**Comment by cchantep** [comment]
Hi @hnan, as mentioned in the guidelines, please use the [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework) to ask question/for help. This tracker is for confirmed issue/discussed feature request. Best regards.
