### ISSUE TITLE
Feature Request: Using custom hikaricp configuration via config file

### ISSUE THREAD

**Issue by benelot** [playframework/playframework#6905]
Hi,

I am a bit disappointed by the extremely small interface of play towards the configuration of Hikaricp and therefore to the configuration of jdbc. Hikaricp has a lot of configuration options that can not be accessed, since Play generates and provides its own configuration. I would suggest that one could configure something like play.db.hikaricp.file="..." in application.conf to add a hikaricp.conf file.

Any thoughts?

**Comment by marcospereira** [comment]
Hello @benelot,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs.

Here is the available HikariCP configurations: https://github.com/playframework/playframework/blob/b1a5164ad55abc96b58198b6251be73a13d08459/framework/src/play-jdbc/src/main/resources/reference.conf#L58-L121

If I remember correctly, the only configuration that we don't support out-of-the box are `metricRegistry` and `healthCheckRegistry`, but it would be easy to extend the default HikariCP module to add them:

https://github.com/playframework/playframework/blob/b1a5164ad55abc96b58198b6251be73a13d08459/framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala#L19-L28

**Comment by benelot** [comment]
Thank you for your answers! I did not get answers on the mailinglist very quickly. What I meant is actually 
https://github.com/brettwooldridge/HikariCP#initialization, you can set:

    config.addDataSourceProperty("cachePrepStmts", "true");
    config.addDataSourceProperty("prepStmtCacheSize", "250");
    config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");

to configure the jdbc driver below. So I would have to add them to the HikariCPModule, right?

**Comment by marcospereira** [comment]
Hey @benelot, I would rather move the discussion to the mailing list to avoid further noise to other contributors here. Also, this could be relevant to other users that can also ask questions there. :-)
