### ISSUE TITLE
Play 2.5.12 spams stdout with config origin

### ISSUE THREAD

**Issue by pettyjamesm** [playframework/playframework#6907]
A call to println seems to have snuck into a release build of play and doesn't seem to be intentional.
Here's the relevant line: https://github.com/playframework/playframework/pull/6824/files#diff-4378e6503263d81d7869f6056b31e6b1R148

This might not be the only occurrence, since I can only find this method called from cases where a config exception is thrown but the application proceeds to boot successfully. In test I can observe something printing the config origin wrapped in `Option` for every instance of Config created (which creates a lot of noise) and can only assume this is the culprit. No such message was printed in play 2.5.10.

### Play Version 

2.5.12

### API

Scala

### Operating System

MacOS 10.10 for me, probably all OS versions though.

### JDK

```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by marcospereira** [comment]
Thank you, @pettyjamesm. See the PRs above.

There are other places where we call print methods, but they are intentional (when the logger isn't ready yet). Looks like this one was accidental.

**Comment by pettyjamesm** [comment]
@marcospereira Thanks for the speedy PRs.
