### ISSUE TITLE
[Documentation] Incorrect placement of the tutorial

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#6913]
### Play Version (2.5.x / etc)
2.5

### API (Scala / Java / Neither / Both)
Neither

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
N/A

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
N/A

### Library Dependencies
N/A

### Expected Behavior
In https://www.playframework.com/documentation/2.5.0/Tutorials#Database there is ```Play Java with Spring Data JPA``` tutorial which is placed under 2.5 section but works only with Play 2.4.

It should be placed under 2.4 section

**Comment by wsargent** [comment]
You are looking at 2.5.0 -- it has a notice saying "You are viewing the documentation for the 2.5.0 release. The latest stable release series is 2.5.x."

The correct documentation is here: https://www.playframework.com/documentation/2.5.x/Tutorials
