### ISSUE TITLE
Add more explicit thread demarcation warnings for database backed projects

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6915]
### Play Version (2.5.x / etc)

Future

### API (Scala / Java / Neither / Both)

Neither

### Expected Behavior

This could be done in documentation, or could be done by adding some loan pattern constructs rather than calling `DB.foo()`.  Community documentation / contributions welcome.

This should be a fairly simple add -- for modules like Play-Slick or Play DB, there should be an application.conf specifying a custom thread pool and a wrapper so that database operations can happen off the main rendering thread.  At the least, we should point them to `CustomExecutionContext`.

### Actual Behavior

Right now, there is a reference to documentation in ThreadPool.md, but it's not clear to users that database operations are inherently something that should be demarcated in a Future block and need a custom execution context.

**Comment by wsargent** [comment]
This is covered partly by the documentation in examples, i.e. 

* https://github.com/playframework/play-scala-anorm-example/blob/2.6.x/app/models/ComputerRepository.scala 
* https://github.com/playframework/play-java-jpa-example/blob/2.6.x/app/models/JPAPersonRepository.java

**Comment by wsargent** [comment]
Connected with https://github.com/playframework/playframework/issues/6489

**Comment by mkurz** [comment]
@wsargent This is fixed by #7253 already or not?

**Comment by wsargent** [comment]
Yes.
