### ISSUE TITLE
Multipart form data with JSON and File is not working using WSClient

### ISSUE THREAD

**Issue by rohitlf** [playframework/playframework#6928]
WSClient is not able to post json and file together in multi-part form data

http://stackoverflow.com/questions/41952551/post-file-and-json-body-together-using-wsclient-in-play-framework-2-5

**Comment by rohitlf** [comment]
Hi Will, 

Thanks your for taking time out of your busy schedule.

Coming to the issue, I can see the POST not working for json and file together using WSClient in Play framework but when I tried running the same using JAX-RS, it worked.


import org.glassfish.jersey.media.multipart.BodyPart;
import org.glassfish.jersey.media.multipart.FormDataMultiPart;
import org.glassfish.jersey.media.multipart.file.FileDataBodyPart;
import org.h2.util.IOUtils;
import play.Configuration;
import play.libs.Json;
import play.libs.ws.WSClient;
import play.mvc.Controller;
import play.mvc.Http;
import play.mvc.Result;
import services.DigioHttpClientProvider;
import util.Util;
import javax.inject.Inject;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;


Client client = ClientBuilder.newBuilder()
                    .sslContext(sslContext)
                    .hostnameVerifier(hostnameVerifier)
                    .register(MultiPartFeature.class)
                    .register(new MapperProvider())
                    .build();

BodyPart fileDataBodyPart = new FileDataBodyPart("file", file/*new File("/Users/test/Downloads/test.pdf")*/);
        formDataMultiPart.field("request", jsonRequest, MediaType.APPLICATION_JSON_TYPE).bodyPart(fileDataBodyPart);
        WebTarget target = client.target(new URI(url));

        String auth = "Basic " + "Adsad";
        DocumentMeta documentMeta = target.request().header("Authorization", auth).post(Entity.entity(formDataMultiPart, MediaType.MULTIPART_FORM_DATA)).readEntity(DocumentMeta.class);


But I am unable to run the same code [defined here.](https://www.playframework.com/documentation/2.5.x/JavaWS#submitting-multipart-form-data)

**Comment by wsargent** [comment]
This is still insufficient -- please provide an actual failing test case.  Showing code from a different framework doesn't count.

**Comment by wsargent** [comment]
Closing from lack of info
