### ISSUE TITLE
Implement JSR 107 interface for Play cache

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6931]
### Play Version (2.5.x / etc)

Future

### API (Scala / Java / Neither / Both)

Both

### Expected Result

There is a standard caching API "javax.cache" that came out as [JSR 107](https://www.jcp.org/en/jsr/detail?id=107) -- see https://github.com/jsr107 for the demo and specification.  Play wraps ehcache, which implements JSR 107, and so it shouldn't be too much work to expose that API.

**Comment by gmethvin** [comment]
Note that JSR 107 doesn't support async interfaces for caching. So this would likely only apply to the synchronous cache.

**Comment by wsargent** [comment]
Also note that it gets a bad review: https://github.com/google/guava/issues/2177

**Comment by igmar** [comment]
The JSR API is pretty had. Play's is worse however, so I wrote an implementation for JSR106 with EHCache, and added that as an annotated Guice module.

Downsides : 

- Not async aware.
- Only properly supports EHCache
- Good written JSR implementation are pretty scarse, memcached is still a void for example.

I would stick to writing a good, async API. If people want JSR : They can write a wrapper around the new API. Just my $.02.

**Comment by marcospereira** [comment]
So we are in agreement that the JRS 107 API, by being block, is not a good fit for Play. Also we now have `AsyncCacheApi`.

Is this issue still valid or can we close it?

**Comment by wsargent** [comment]
Closing :-D
