### ISSUE TITLE
60 second delay within Play framework when receiving a request

### ISSUE THREAD

**Issue by martin-flower** [playframework/playframework#6943]
**Play Version** 
2.5.1 (play_2.11-2.5.1.jar)

**API** 
Scala

**Operating System**
Linux dcdev3 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

**JDK**
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**Expected Behaviour**
Scenario - invoke REST upload for a 3.5MB file to web application built on play framework
Test - performance test with single user, calling upload in sequence at least 100 times (one request at a time, no overlapping requests)
Expected behaviour - the play framework promptly calls the controller for processing the request.

**Actual Behaviour**
In ca 98-99% of the cases, the actual behaviour is the same as the expected behaviour.
But for approximately 1-2% of requests, the play framework receives the request and waits approximately 60 seconds before calling the controller. With log level TRACE the delay occurs at the following place:
```
xx:05:45,640 play.core.server.netty.PlayRequestHandler in netty-event-loop-1 Http request received by netty
xx:06:45,630 play.api.mvc.Action in monolith-akka.actor.default-dispatcher-23 Invoking action with request
```

In this case the delay is of 59.990 seconds.
In my tests, the delay is typically 60 to 61 seconds.

**Reproducible Test Case**
If it can be of help, I will attempt to create a play project and see if I can make the problem reproducible for other people.

**Comment by schmitch** [comment]
you should probably upgrade to 2.5.12

**Comment by martin-flower** [comment]
Thanks for the suggestion - I'm looking into it now.

**Comment by martin-flower** [comment]
I've upgraded the application to 2.5.12, but now it doesn't start. Rather than waste more time on this now, I'll close the issue and re-open it (or create a new one) when we get around to updating our dependencies.

**Comment by schmitch** [comment]
actually 2.5.12 and 2.5.1 should be binary compatible, so it should be possible to just use 2.5.12
