### ISSUE TITLE
Update documentation for ScalaFunctionalTestingWithScalaTest#Testing-with-a-server

### ISSUE THREAD

**Issue by ghost** [playframework/playframework#6955]
### Play Version (2.5.x / etc)
2.5.x

### API (Scala / Java / Neither / Both)
Scala 2.11.8

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

macOS Sierra 10.12.3

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

### Library Dependencies

None

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Documentation Page - https://www.playframework.com/documentation/2.5.x/ScalaFunctionalTestingWithScalaTest#Testing-with-a-server
2. 'Testing with a server' example does not compile.
3. Adding these imports, makes it compilable
import play.api.routing.sird._
import play.api.mvc.Results._

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

1. If you use the example here - https://www.playframework.com/documentation/2.5.x/ScalaFunctionalTestingWithScalaTest#testing-with-a-server
2. It does not compile

### Reproducible Test Case

Not applicable, as the code does not compile.

Note: checked the existing issues and couldn't find any existing issues related to this. And in general I think the playframework website is not up to date with scala test play documentation.

**Comment by marcospereira** [comment]
Hey @shashidesai, thanks for reporting this.

Most of the code examples are already compiled and executed by Play build. See the following page to understand how it works:

https://www.playframework.com/documentation/2.5.x/Documentation#Code-samples

From this specific example, you can see that theres is a snippet indicating which imports should be made:

https://www.playframework.com/documentation/2.5.x/ScalaFunctionalTestingWithScalaTest#Writing-functional-tests-with-ScalaTest

But maybe the imports are incomplete for the examples shown in that page(?). If so, do you want to submit a pull request to solve this? The file you need to edit is here:

https://github.com/playframework/scalatestplus-play/blob/master/docs/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md

**Comment by shashidesai** [comment]
Seems like the file on ScalaGuide seems to have been changed, it has different code than whats on the website. So its just matter of latest ScalaGuide(https://github.com/playframework/scalatestplus-play) not published to the website then ?

The one on the website has this class extended.
class ExampleSpec extends PlaySpec with OneServerPerSuite
but on the ScalaGuide repository its different.
class ExampleSpec extends PlaySpec with GuiceOneServerPerSuite

Scalatestplus-play --> oneserverpersuite --> ExampleSpec.scala
https://github.com/playframework/scalatestplus-play/blob/master/docs/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md#testing-with-a-server
https://github.com/playframework/scalatestplus-play/blob/master/docs/manual/working/scalaGuide/main/tests/code/oneserverpersuite/ExampleSpec.scala

Website has different code - https://www.playframework.com/documentation/2.5.x/ScalaFunctionalTestingWithScalaTest#testing-with-a-server

**Comment by marcospereira** [comment]
The differences are related to the fact that the current docs were published using version 1.5.1 of scalatestplus-play:

https://github.com/playframework/scalatestplus-play/blob/1.5.1/docs/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md

And not the master (previously linked above). So, we would need to cut a new 1.5.x version and update it in Play so that we can see the new docs.

Do you want to submit a PR to solve this?

**Comment by shashidesai** [comment]
sure, will submit a PR. Thanks

**Comment by marcospereira** [comment]
@shashidesai appreciate that.

Thanks.

**Comment by marcospereira** [comment]
This was closed by https://github.com/playframework/omnidoc/commit/3a6a232201f687fed66f3692bbedbe0833dfe9a3 where scalatestplus-play was updated to 2.0.0.
