### ISSUE TITLE
Consider removing jul-to-slf4j bridge to avoid performance issues

### ISSUE THREAD

**Issue by asaarilahti** [playframework/playframework#6958]
From https://www.slf4j.org/api/org/slf4j/bridge/SLF4JBridgeHandler.html

> If you are concerned about application performance, then use of SLF4JBridgeHandler is appropriate only if any one the following two conditions is true:
> - few j.u.l. logging statements are in play
>  - LevelChangePropagator has been installed

> Consequently, j.u.l. to SLF4J translation can seriously increase the cost of disabled logging statements (60 fold or 6000% increase) and measurably impact the performance of enabled log statements (20% overall increase).

Additionally, Play sets JUL root logger level to FINEST, which will cause all logging calls to be forwarded (https://github.com/playframework/playframework/blob/38abd1ca6d17237950c82b1483057c5c39929cb4/framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala#L68)

This can cause issues for example when using JAXB. It logs a lot but has a check for the level:
```
if (logger.isLoggable(Level.FINEST)) {
    logger.log(Level.FINEST, "State.push");
}
```
Under Play the condition always evaluates to true. As a result we saw over million log calls per second being forwarded - which of every one hits a synchronized method inside JUL causing a lot of contention (fix in JDK9: https://bugs.openjdk.java.net/browse/JDK-8077846)
```
    private synchronized void initializeGlobalHandlers() {
        if (initializedGlobalHandlers) {
            return;
        }
```
A simple fix would be not to include jul-to-slf4j bridge and remove the initialization code from LogbackLoggerConfigurator. Bridging logging from JUL is rarely needed at least in my experience, so likely would not be an issue for many if it would be removed. Making it optional and disabled by default would be an alternative.

This issue can be workarounded by setting JUL root logger level to SEVERE after LogbackLoggerConfigurator has run.

### Play Version (2.5.x / etc)
2.3.x, 2.5.x

### API (Scala / Java / Neither / Both)
Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
All / CentOS 6.8

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
All / 1.8.0_101

**Comment by wsargent** [comment]
@asaarilahti Can you include a sample project using JAXB with Gatling?  https://developer.lightbend.com/guides/play-rest-api/ has a gatling example, but there isn't a repeatable benchmark that will tell us the difference here right now for this bug.

**Comment by asaarilahti** [comment]
@wsargent I did a quick experiment with JAXB (just unmarshalling xml in a single thread - no Gatling at this point):

> [info] application - Took 47 ms per item for 500 with bridging true
> [info] application - Took 47 ms per item for 500 with bridging true
> [info] application - Took 11 ms per item for 500 with bridging false
> [info] application - Took 6 ms per item for 500 with bridging false
> [info] application - Took 48 ms per item for 500 with bridging true
> [info] application - Took 47 ms per item for 500 with bridging true
> [info] application - Took 7 ms per item for 500 with bridging false

So initially it looks the performance difference is large. I hope to post the example project soon.

**Comment by wsargent** [comment]
@asaarilahti okay -- then the next concern is going to be the users who don't use JAXB and rely on JUL generated logs.  Those users will have diminished functionality with this PR, and may not care about the performance impact.

**Comment by asaarilahti** [comment]
Here's a quick test project: [slf4j-bridge-test.tar.gz](https://github.com/playframework/playframework/files/765209/slf4j-bridge-test.tar.gz)

I think the issue applies to anything using java.util.logging - JAXB likely just being an extreme case. So I would see it safer to exclude/disable the bridge by default.

If it's excluded, users needing it can just add the dependency and include a couple of lines of initialization code in their project. Or keeping the dependency but making the initialization conditional should be fine too (by a system property or by a application.conf entry - if full Configuration is already available when logger configurator is run).
