### ISSUE TITLE
CSRF handling broken on master

### ISSUE THREAD

**Issue by schmitch** [playframework/playframework#6977]
### Are you looking for help?

when using `CSRFFilter` as a global filter and adding a CSRF field to a Form via ` @helper.CSRF.formField` Play will always fail with a 403 error and sometimes print a `RuntimeException` (when calling the Form via `GET` i.e. refreshing the browser with CTRL + R when the Form raised a 403):
```
Caused by: java.lang.RuntimeException: No CSRF token present!
	at scala.sys.package$.error(package.scala:27)
	at views.html.helper.CSRF$$anonfun$2.apply(CSRF.scala:29)
	at views.html.helper.CSRF$$anonfun$2.apply(CSRF.scala:29)
	at scala.Option.getOrElse(Option.scala:121)
	at views.html.helper.CSRF$.formField(CSRF.scala:29)
```

This does not happen on the 2.5.x branch.

However I still looking for more details and didn't had time lately to debug it more closely.
I guess the changes from Request Tags to the new Typed Request Maps introduced it (but it's just a guess).

### Play Version (2.5.x / etc)

master

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Mac 10.11?

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Java SE 1.8.0_112-b16

**Comment by gmethvin** [comment]
@schmitch can you create a test case for this? I thought our existing test suite for CSRF would catch this, but I guess not...

**Comment by gmethvin** [comment]
I'm not able to reproduce. Is anything happening before the error that might put it in an inconsistent state?

**Comment by schmitch** [comment]
well I still didn't had time to correctly look into it.
But here is how it happens: https://github.com/schmitch/play-form-error

just a simple form with `@helper.CSRF.formField`. neither `Controller` or `AbstractController` seems to work.

**Comment by gmethvin** [comment]
@schmitch Okay. I wasn't able to reproduce the "No CSRF token present" error, but I am getting a 403 error when I try to POST the form on your project. Still investigating what the actual issue is.

**Comment by gmethvin** [comment]
@schmitch Thanks for your help. I found it was an issue with comparing signed tokens. The fix is in #7027

**Comment by schmitch** [comment]
well I think I probably was not a great help, I always tought that for CSRF the Cookie get's updated. But I'm not that much of a CSRF user anyway. But great that it's fixed.

**Comment by JiboStore** [comment]
How do I get the fix?
I am using play-framework 2.6 but is still having the same problem
