### ISSUE TITLE
2.6.0-M1 migration guide: Streams -> IterateeStreams 

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#6980]
![image](https://cloud.githubusercontent.com/assets/100349/23041171/3dca7638-f494-11e6-857f-b45284a002d3.png)

**Comment by domdorn** [comment]
We should note in the migration guide, to include
"com.typesafe.play" %% "play-iteratees" % "2.6.1",
  "com.typesafe.play" %% "play-iteratees-reactive-streams" % "2.6.1"
when people need to interact with iteratees or streams based on iteratees

**Comment by wsargent** [comment]
https://github.com/playframework/play-iteratees/blob/master/README.md updated
