### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by Roland4444** [playframework/playframework#6989]
Hello! On your tutorial Play 1.4 https://playframework.com/documentation/1.4.x/asynchronous#HTTPresponsestreaming

Article about Websockets:

wtitten 
""""""""On the browser side, you open a socket using a “ws://” url:
new Socket("ws://localhost:9000/helloSocket?name=Guillaume")"""""

MUST BE """"""""""
new WebSocket("ws://localhost:9000/helloSocket?name=Guillaume");
"""""""""""""""""""""

THX FOR ATTENTION!

**Comment by mkurz** [comment]
This is the repo for Play 2.
For Play 1 please see https://github.com/playframework/play1
