### ISSUE TITLE
Race condition when accessing a `ClusterClient` from injected adapter in Controller.

### ISSUE THREAD

**Issue by erip** [playframework/playframework#6990]
### Play Version (2.5.x / etc)

Play 2.5.9

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

OS X 10.12.3

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

>Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
>Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Library Dependencies

```
libraryDependencies += "com.typesafe.akka" %% "akka-contrib" % "2.4.11"
libraryDependencies += "com.typesafe.akka" %% "akka-cluster-tools" % "2.4.17"
libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.4.11"
libraryDependencies += "com.typesafe.akka" %% "akka-remote" % "2.4.11"

libraryDependencies += "com.typesafe.play" %% "play" % "2.5.9"
```

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Start cluster with designated cluster receptionist.
2. Inject adapter with client receptionist member into a controller.
3. Communication available between Play application and cluster when HTTP requests are issued to the Play app.

### Actual Behavior

1. Start cluster with designated cluster receptionist.
2. Inject adapter with client receptionist member into a controller.
3. Nondeterministic DeadLetters on cluster for `Message [akka.cluster.client.ClusterReceptionist$Internal$GetContacts$]` message.

___

The point of the adapter is to inject a cluster client for use in a controller within my Play application.

The job of my controller is to simply send the string "Hello!" to my FooActor, who will in turn respond to `sender` with a "World!" message. 

I find that occasionally I'll indeed receive World! from the cluster, which is promising. More often, however, I find that I'll receive a DeadLetters message:

```
[INFO] [02/17/2017 12:10:01.859] [PubSubMember-akka.actor.default-dispatcher-18] [akka://PubSubMember/system/receptionist] Message [akka.cluster.client.ClusterReceptionist$Internal$GetContacts$] from Actor[akka.tcp://HttpServerSystem@127.0.0.1:8888/user/ClusterClient#-482763544] to Actor[akka://PubSubMember/system/receptionist] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

My initial guess is that there was a lazy injection with guice, so I tried to bind the `FooActorAdapte` as an eager singleton and it didn't resolve the DeadLetters. I also added a `Thread.sleep(5000)` after the client is created and this didn't help either.

### Reproducible Test Case

[Adapters](https://www.google.com/url?q=https%3A%2F%2Fgist.github.com%2Ferip%2F073ccc2e28090deeccfd474df5f1edd9&sa=D&sntz=1&usg=AFQjCNH26HaTgxMUH7I8INX58efGiuvleg)
[Controller](https://www.google.com/url?q=https%3A%2F%2Fgist.github.com%2Ferip%2Fab60aaa944a04b31ad2637183309b94c&sa=D&sntz=1&usg=AFQjCNHpYmGF2yck3IYSmyJFmDL58UC07w)

`FooActor`'s receive:

```
def receive = {
    case msg: String => sender ! "World!"
}
```

`FooActor`'s cluster config:

```
FooActor {
  akka {
    cluster.client.receptionist {
      # Actor name of the ClusterReceptionist actor, /system/receptionist
      name = receptionist

      # Start the receptionist on members tagged with this role.
      # All members are used if undefined or empty.
      role = ""

      # The receptionist will send this number of contact points to the client
      number-of-contacts = 3

      # The actor that tunnel response messages to the client will be stopped
      # after this time of inactivity.
      response-tunnel-receive-timeout = 30s

      # The id of the dispatcher to use for ClusterReceptionist actors.
      # If not specified default dispatcher is used.
      # If specified you need to define the settings of the actual dispatcher.
      use-dispatcher = ""

      # How often failure detection heartbeat messages should be received for
      # each ClusterClient
      heartbeat-interval = 2s

      # Number of potentially lost/delayed heartbeats that will be
      # accepted before considering it to be an anomaly.
      # The ClusterReceptionist is using the akka.remote.DeadlineFailureDetector, which
      # will trigger if there are no heartbeats within the duration
      # heartbeat-interval + acceptable-heartbeat-pause, i.e. 15 seconds with
      # the default settings.
      acceptable-heartbeat-pause = 13s

      # Failure detection checking interval for checking all ClusterClients
      failure-detection-interval = 2s
    }
    loglevel = "INFO"
    actor {
      provider = "akka.cluster.ClusterActorRefProvider"
    }
    remote {
      enabled-transports = ["akka.remote.netty.tcp"]
      netty.tcp {
        hostname = "127.0.0.1"
        port = 5225
      }
      log-sent-messages = on
      log-received-messages = on
    }
    extensions = ["akka.cluster.client.ClusterClientReceptionist"]
  }
}
```

Cluster receptionist registration of `FooActor`:

```
val fooActorSystem = ActorSystem("PubSubMember", conf.getConfig("FooActor"))
Cluster(fooActorSystem).join(joinAddress)
val fooActor = fooActorSystem.actorOf(Props[FooActor], "FooActor")
Thread.sleep(5000)
ClusterClientReceptionist(fooActorSystem).registerService(fooActor)
Thread.sleep(5000)
```

**Comment by erip** [comment]
Interesting to note: when I add a log message to the receive, I find that the `FooActor`'s logged protocol is `akka.tcp://PubSubMember@127.0.0.1:5225/user/FooActor`, but when it encounters DeadLetters, the protocol of the receptionist from that logged message is `akka://PubSubMember/system/receptionist`.

**Comment by erip** [comment]
When I send a request and it is successful, I note that my Play app logs the following:

```
[info] application - 127.0.0.1:5225
[info] play.api.Play - Application started (Dev)
[INFO] [02/20/2017 09:02:55.060] [HttpServerSystem-akka.actor.default-dispatcher-3] [akka.tcp://HttpServerSystem@127.0.0.1:8888/user/ClusterClient] Connected to [akka.tcp://PubSubMember@127.0.0.1:5225/system/receptionist]
...
```

But when it isn't successful, I see

```
[info] application - 127.0.0.1:5225
[info] play.api.Play - Application started (Dev)
...
```

**Comment by erip** [comment]
The solution to this was a bit multifaceted.

1. Remove `Provider` from the Controller -- this forces the resources provided to the controller to be lazy. This is bad.
2. Change `routesGenerator` to `InjectedRoutesGenerator` (and remove `@` from `routes`). This forces the routes to be generated at compile-time.
3. Removed the `FooActor` namespace and instead loaded the default config for `ActorSystem`.

Very glad to have solved this.

**Comment by marcospereira** [comment]
Thanks for sharing your solution, @erip. :-)
