### ISSUE TITLE
[doc]: document how to execute something at application starting

### ISSUE THREAD

**Issue by marcospereira** [playframework/playframework#6997]
This was done using `GlobalSettings.onStart` and `GlobalSettings.beforeStart` until Play 2.5, where this was deprecated. The new way involves creating a module and registering components as eager singletons so they will run even if the component is not injected.

We need to add some docs and examples about how to do it.

**Comment by wsargent** [comment]
We did: https://www.playframework.com/documentation/2.5.x/GlobalSettings

**Comment by marcospereira** [comment]
Yep. I was thinking more like a clear code example, for both Java and Scala.
