### ISSUE TITLE
Error while running Play Evolutions for the first time. 

### ISSUE THREAD

**Issue by allnash** [playframework/playframework#6999]
### OVERVIEW

Play requires "play_evolutions_lock" to be present before running any evolutions. Is this new??

### Play Version (2.5.x / etc)

2.5.12

### API (Scala / Java / Neither / Both)

BOTH

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Use `uname -a` if on Linux.

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Paste the output from `java -version` at the command line.

1.8_ALL

### Library Dependencies

MYSQL 5.6.17 (Confirmed)
JDBC driver version   "mysql" % "mysql-connector-java" % "5.1.40"

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

Play framework should not spit an error when I am running an evolution for the first time.

### Actual Behavior

for the following setting in evolution
```
play.evolutions {
  # You can disable evolutions for a specific datasource if necessary
  #db.default.enabled = false
  enabled=true
  autocommit=false
  autoApply=true
  useLocks=true
}
```

Please provide a description of what actually happens, working from the same starting point.

```
warn] application - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
[info] application - Binding application start
[info] application - Binding application stop
[warn] application - application.conf @ file:/Users/opensource//server/target/scala-2.11/classes/application.conf: 340: user is deprecated, use username instead
[warn] application - application.conf @ file:/Users/opensource/Reporting/doubleshot/server/target/scala-2.11/classes/application.conf: 341: pass is deprecated, use password instead
[info] application - Creating Pool for datasource 'default'
[info] p.a.d.DefaultDBApi - Database [default] connected at jdbc:mysql://127.0.0.1:3306/development
[error] o.j.StatementLogger - java.sql.Statement.executeQuery: 
      select `lock` from play_evolutions_lock
    ;
throws exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'development.play_evolutions_lock' doesn't exist
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'development.play_evolutions_lock' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[error] o.j.StatementLogger - java.sql.Statement.executeQuery: select id, hash, apply_script, revert_script, state, last_problem from play_evolutions where state like 'applying_%';
throws exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'development.play_evolutions' doesn't exist
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'development.play_evolutions' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[info] application - ApplicationTimer demo: Starting application at 2017-02-22T15:22:13.950Z
[info] application - Application has started
[info] application - Loading Demo Data
[info] application - Detected deploy type - LOCAL - Skipping Release Email
[info] play.api.Play - Application started (Dev)
```

### Reproducible Test Case

CREATE A SAMPLE TEMPLATE, ADD A MIGRATION MODEL. SET PLAY EVOLUTIONS TO AUTO.

**Comment by mkurz** [comment]
Can you check if the table `play_evolutions` was created?

**Comment by mkurz** [comment]
Also you may want to set a schema via `play.evolutions.schema`:
> schema - Database schema in which the generated evolution and lock tables will be saved to. No schema is set by default.

**Comment by marcospereira** [comment]
Adding to what @mkurz said, what if you have `useLocks = false` (which is the default)?

**Comment by allnash** [comment]
Let me give it a try tomorrow.

Sent from my iPhone

On Feb 22, 2017, at 12:40, Marcos Pereira <notifications@github.com<mailto:notifications@github.com>> wrote:


Adding to what @mkurz<https://github.com/mkurz> said, what if you have useLocks = false (which is the default)?

**Comment by allnash** [comment]
So the table was created, I am guessing this error is harmless. Let me try to add 2.sql migration and also try the other method you were describing. 

schema - Database schema in which the generated evolution and lock tables will be saved to. No schema is set by default. -- FOR THIS I believe the table was created under the default database.

**Comment by mkurz** [comment]
@allnash Could you eventually solve the problem?

**Comment by marcospereira** [comment]
I'm closing this, but we can reopen it later if there is more information about the problem.

**Comment by emonmishra** [comment]
@marcospereira I am also getting this error. How was it fixed?

> [error] o.j.StatementLogger - java.sql.Statement.executeQuery: select id, hash, apply_script, revert_script, state, last_problem from play_evolutions where state like 'applying_%';
> throws exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'dbname.play_evolutions' doesn't exist
> com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'itemset.play_evolutions' doesn't exist
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
>         at com.mysql.jdbc.Util.getInstance(Util.java:408)
>         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
>         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)

but if I look at DB, this table is there in 'dbname' .

**Comment by marcospereira** [comment]
@emonmishra is it possible to create a reproducer for the problem? Also, which version of Play are you using?
