### ISSUE TITLE
Javadoc for AkkaGuiceSupport has incorrect example code

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#7009]
See https://playframework.com/documentation/2.5.12/api/java/play/libs/akka/AkkaGuiceSupport.html#bindActorFactory-java.lang.Class-java.lang.Class-. `sender().send` should be `sender().tell` and the call to `injectedChild` doesn't make sense. We have a correct example here: https://www.playframework.com/documentation/2.5.x/JavaAkka#Dependency-injecting-child-actors

**Comment by keramiozsoy** [comment]
Hi @gmethvin, I would like to take this as my first PR. Can i take this ? :)

**Comment by richdougherty** [comment]
Hi @keramiozsoy, certainly you can take this one! I'll assign it to you now. :)

If you have any questions about the process, just ask on this issue or send a message to the play-framework-dev mailing list. We're happy to help.

**Comment by richdougherty** [comment]
OK I can't assign you for some reason, but we know you're working on it!

**Comment by marcospereira** [comment]
@richdougherty according to [Github docs](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/), "you can assign issues and pull requests to yourself, collaborators on personal projects, or members of your organization with read permissions on the repository".

@keramiozsoy thank you for taking this one. We really appreciate that. :-)

**Comment by keramiozsoy** [comment]
hi @richdougherty i changed it. Is it right ? :) 
https://github.com/playframework/play-generated-docs/pull/11

**Comment by marcospereira** [comment]
Hey @keramiozsoy, the correct place to change it is here:

https://github.com/playframework/playframework/blob/37928701c1a585649f54d634bbb007a747612d99/framework/src/play-guice/src/main/java/play/libs/akka/AkkaGuiceSupport.java#L126-L134

The `play-generated-docs` repository content is not the source of truth, but just the docs generated using our build/release process. So, if you change anything there, it will be replaced. Also, as @gmethvin said, it would be good to replicate the example here:

https://www.playframework.com/documentation/2.6.x/JavaAkka#Dependency-injecting-child-actors

Finally, considering that we have the same example already documented in the link above, maybe we should just remove [this whole section](https://github.com/playframework/playframework/blob/37928701c1a585649f54d634bbb007a747612d99/framework/src/play-guice/src/main/java/play/libs/akka/AkkaGuiceSupport.java#L80-L136) and reference the link above.

**Comment by keramiozsoy** [comment]
hi @marcospereira I added link. 
https://github.com/playframework/playframework/pull/7747
