### ISSUE TITLE
Simple way to add attributes to requests

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#7016]
The Java and Scala `RequestHeader` and `Request` classes contain an immutable map of attributes. Attributes are typed values that associate extra information with the request. It's a common pattern to add a single attribute to a request, but it's complicated to do so. It would be nice if there were a simpler way to do this.

To add an attribute to a header you currently need to read the old attributes map out, create a new map with the old attributes plus the new attribute you want to add, then create a new request with those new attributes. E.g.

```scala
val newAttrs = req.attrs + (MyAttr -> value) // New immutable map
val newReq = req.withAttrs(newAttrs) // New request with new attrs
```

In this example you see we call the `withAttrs` method with a new map of attributes which will return a new `Request` or `RequestHeader` with those new attributes. The old attributes are discarded and the new attributes are used in the new `Request` or `RequestHeader`.

This seems too complicated, and it's easy to forget to include the old attributes. Here are two options for improving the API:

Example 1:
```scala
// Add single new attribute
val newReq = req.addAttr(MyAttr, value)
```

Example 2:
```scala
// Add multiple new attributes
val newReq = req.addAttrs(MyAttr -> value)
```

I don't like the second example because the method `addAttrs` could easily be confused with the existing method `withAttrs`. The method `addAttr` in the first example seems easier to understand and adding a single attribute will be the most common use case.

To fix this issue I would like to see the `addAttr` method implemented. Steps:

1. Add a new `addAttr` (or equivalent) method to the Java and Scala `RequestHeader` types.
2. Override the `addAttr` method return type in the Java and Scala `Request` types. See the way I've overridden the `withAttrs` to see what I mean about changing the return type.
3. Tests for the new methods.
4. Search the Play code, docs and examples to find any uses of `withAttrs` that update only a single attribute and update them so they use the `addAttr` method instead.

*Bonus:* Do the same thing set of steps the Scala `withHeaders` method, i.e. implement an `addHeader` method. You don't need to do this for the Java method because its header object is mutable, so it's easy to add a new header.

**Comment by gmethvin** [comment]
@richdougherty FYI, `withHeaders` already supports adding headers via `withHeaders(header -> value)`. So if we wanted to match the API we should have `withAttrs(MyAttr -> value)`.

But the question is if it's confusing to have the `withAttrs` accepting a `TypedMap` replace the attrs completely, while the other variant just adds/updates.

**Comment by richdougherty** [comment]
Thanks for the info. I did a quick survey:

* The `Request` and `RequestHeader` class have a `withHeaders(headers: Headers)` method that replaces the existing headers. I think this method was added by me. :)
* The `Result` class and `FakeRequest` wrapper class have a `withHeaders(headers: (String, String)*)` method that updates the existing headers.
* Java's API is different because it uses mutable headers and the builder pattern.

> But the question is if it's confusing to have the `withAttrs` accepting a `TypedMap` replace the attrs completely, while the other variant just adds/updates.

I do think this is confusing…

**Comment by gmethvin** [comment]
@richdougherty You're right I was thinking of the `Result` not the `RequestHeader` for `withHeaders`. Actually you're not typically adding headers to a `RequestHeader` so it makes sense that no such API exists.

**Comment by marcospereira** [comment]
Maybe we can have new names like:

1. `withSomething`: replaces the current value
2. `addSomething`: appends to the current value

This sounds more clear to me. What do you think?

**Comment by marcospereira** [comment]
> Actually you're not typically adding headers to a RequestHeader so it makes sense that no such API exists.

You use then while writing tests, I think?

**Comment by richdougherty** [comment]
@marcospereira, those names sound fine to me.
