### ISSUE TITLE
More flexible ErrorHandler

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#7019]
The default error handler hard codes everything to web pages

This is easy enough to override, but it does mean content representation has to be added in as a match statement.

https://github.com/playframework/play-rest-api/blob/master/app/ErrorHandler.scala

```

  override def onClientError(request: RequestHeader,
                             statusCode: Int,
                             message: String): Future[Result] = {
    logger.debug(
      s"onClientError: statusCode = $statusCode, uri = ${request.uri}, message = $message")

    Future.successful {
      val result = statusCode match {
        case BAD_REQUEST =>
          Results.BadRequest(message)
        case FORBIDDEN =>
          Results.Forbidden(message)
        case NOT_FOUND =>
          Results.NotFound(message)
        case clientError if statusCode >= 400 && statusCode < 500 =>
          Results.Status(statusCode)
        case nonClientError =>
          val msg =
            s"onClientError invoked with non client error status code $statusCode: $message"
          throw new IllegalArgumentException(msg)
      }
      result
    }
  }
```

It would be nicer if all error results had a `Content` that could be associated on error.

**Comment by wsargent** [comment]
Possibly related to https://github.com/playframework/playframework/issues/6171

**Comment by gmethvin** [comment]
It would be easier to override if we had a single `onError` method, since in this case you want to deal with both client and server errors. Is it worth implementing that change for 2.6?

See also #6171.

**Comment by mkurz** [comment]
@wsargent 

> The default error handler hard codes everything to web pages

Now that we have the `JsonHttpErrorHandler`, the `HtmlOrJsonHttpErrorHandler` and the more generic `PreferredMediaTypeHttpErrorHandler`, can this issue be closed? Are these error handlers addressing this issue here?
See
- https://www.playframework.com/documentation/2.8.x/ScalaErrorHandling#Handling-errors-in-a-JSON-API
- #8299
- #8540
