### ISSUE TITLE
Cannot find ssl cert in conf

### ISSUE THREAD

**Issue by niuchangming** [playframework/playframework#7020]
### Are you looking for help?

When I deploy to AWS using boxfuse I got error message 'Error in custom provider, java.lang.IllegalArgumentException: requirement failed: Key store file conf/ekooedutrust.jks does not exist!'

I put both server jks file and trust jks file in /conf folder and deploy app to AWS server using boxfuse command 'boxfuse run -ports.https=443 -env=prod', then after a while I got the error.

So, where should I store the two cert and how can I configure in order to access via https ?

This is my application.conf configuation:

play.ws {
  ssl {
    trustManager = {
      stores = [
        { type = "JKS", path = "conf/ekooedutrust.jks", password = "xxxxx"}
      ]
    }
  }
}

http.port=disabled
https.port=443
play.server.https.keyStore.path=conf/ekooeducom.jks
play.server.https.keyStore.password=xxxxxx

### Play Version (2.5.x / etc)

2.5

### API (Scala / Java / Neither / Both)

java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

mac

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

jdk 1.8

### Library Dependencies

Please describe the expected behavior of the issue, starting from the first action.

access website via https

**Comment by wsargent** [comment]
Hi, please ask on the mailing list -- this is is a bug tracker for issues in Play itself, not for issues with applications.
