### ISSUE TITLE
Warning when using flashing with redirect.

### ISSUE THREAD

**Issue by MinusKube** [playframework/playframework#7030]
When we use the flashing method with a redirect method, it logs a warning that shouldn't be logged in this case.

### Play Version (2.5.x / etc)
2.6.0-M1

### API (Scala / Java / Neither / Both)
Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Oracle 1.8.0_101

### Library Dependencies
/

### Expected Behavior
The flashing method should not log any warning when using with redirect method.

### Actual Behavior
The flashing method logs a warning "You are using status code '303' with flashing, which should only be used with a redirect status!" when using it with a redirect.

The problem is here since the commit 49f86a83b23320e65e8ecb4eefa3300761d2801f
(You just need to replace "`header.status / 100 == 3`" by "`header.status / 100 != 3`")

**Comment by wsargent** [comment]
https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/Results.scala#L255
