### ISSUE TITLE
PlayRunners.mutex not necessary if not using global app instance

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#7036]
If you're not using the global application instance, it would be useful to be able to run tests in parallel, so the mutex gets in the way: https://github.com/playframework/playframework/blob/2.6.0-M1/framework/src/play-test/src/main/scala/play/api/test/Helpers.scala#L69

You should be able to disable this mutex at the test level.

**Comment by marcospereira** [comment]
@gmethvin closing after #7091.
