### ISSUE TITLE
Update Documentation for 2.5 Database access with play-slick

### ISSUE THREAD

**Issue by jmcardon** [playframework/playframework#7042]
### Play Version (2.5.x / etc)

2.5

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Doesn't matter

### Library Dependencies

play-slick 2.0.2

### Actual Behavior

Documentation here is off: https://playframework.com/documentation/2.5.x/PlaySlick

play.current is deprecated in favor of Provider[Application]. Currently some non-deprecated source code would be either using a provider: Provider[Application], or following slick best practices as outlined in the play-slick git samples.

**Comment by marcospereira** [comment]
Thanks for reporting that, @jmcardon. We should probably add a note to warn users that the "Global lookup" (using `Play.current`) is deprecated.

Do you want to submit a PR to fix that? If so, you can find the page here:

https://github.com/playframework/play-slick/blob/master/docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md

Thanks.

**Comment by jmcardon** [comment]
@marcospereira Sure! Just give me a few hours while I'm still bit caught up at work with our own play app.

I'll add a hasdatabaseconfigprovider example as well as using Provider[Application] if that's ok and submit a pr.

Cheers.

**Comment by jmcardon** [comment]
I added a pull request and removed all references to Play.current, as opposed to simply stating that Play.current is deprecated. 

I feel like this is a better course of action as it better reflects both the current standards within play-slick and omits the unnecessary reference, which is already covered in the migration guide. 

I hope my writing is up to standard!

**Comment by marcospereira** [comment]
That was way better that what I've suggested.

Thanks @jmcardon.

I'm closing this issue as discussion is now happening at https://github.com/playframework/play-slick/pull/387.
