### ISSUE TITLE
In WS client, order not preserved for repeated query parameters with AhcWSRequest

### ISSUE THREAD

**Issue by leons727** [playframework/playframework#7046]
### Play Version (2.5.x / etc)
2.5.x

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
N/A

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
N/A

### Library Dependencies
N/A

### Expected Behavior

Some web APIs, like Google translate, rely on parameter order for repeated query parameters. For example, https://translation.googleapis.com/language/translate/v2?key=API_KEY&target=ru&q=foo&q=bar would return translations in the order corresponding to the order of "q" parameters in the query string.

Thus, it's expected that query parameters specified during construction of WS request would preserve order in the query URL:

```
ws.url("http://nowhere.net").withQueryString("q" -> "foo", "q" -> "bar")
```

Should produce request URL  http://nowhere.net?q=foo&q=bar, not http://nowhere.net?q=bar&q=foo

### Actual Behavior

However, when constructing WS request with AhcWSClient, the parameter order is not preserved (since a Map is used internally to aggregate parameters), with this test failing: 

``` 
test("repeated parameters should preserve order") {
     WsTestClient.withClient { ws =>
       ws.url("http://nowhere.net").withQueryString("q" -> "foo", "q" -> "bar").queryString("q") match {
         case List("foo", "bar") => // pass
         case List("bar", "foo") => fail("wrong parameter order")
         case _ => fail("wrong parameters")
       }
     }
  }
```

**Comment by wsargent** [comment]
Hi @leons727 as far I know, the the order of query parameters in a URL is not defined by the standard:

* https://stackoverflow.com/questions/1746507/authoritative-position-of-duplicate-http-get-query-keys
* https://tools.ietf.org/html/rfc3986#section-3.4

Can you point to an RFC for given behavior?

**Comment by leons727** [comment]
@wsargent: it does appear that RFC doesn't define a standard here, but:

1. It seems natural to preserve query parameter order
2. There are real-life examples where this matters (Google translate API)
3. It's a very simple fix

**Comment by wsargent** [comment]
@leons727 there's nothing to fix here.  The code's conforming to the RFC, and the error here is in the google translate API.

**Comment by wsargent** [comment]
@leons727 If I recall, you can call WS API using request.url("language/translate/v2?key=API_KEY&target=ru&q=foo&q=bar") and that may work better...

**Comment by leons727** [comment]
@wsargent yes, that's the workaround, but at least from the principle of least surprise, I'd preserve parameter order. Would you accept a patch?

**Comment by wsargent** [comment]
The problem is that the query parameter escaping is incredibly finicky, especially when combined with OAuth signing.  We've had multiple bugs where query parameters would be double escaped or unescaped depending on the logic, so touching it is more likely to break something than not.  Given that this is undefined behavior, it's hard to justify.

**Comment by leons727** [comment]
Actually, I've found this PR: https://github.com/playframework/playframework/pull/6884, and the issue with repeated params is mentioned there, hopefully it'll fix itself in the new ws api.

**Comment by wsargent** [comment]
@leons727 that PR never made it across, and like @gmethvin says, it's based on an implementation detail.

I do think that maintaining URL consistency would help a bunch in HTTP caching...
