### ISSUE TITLE
2.6.0 Migration Guide: DynamicForm.form() removed

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#7050]
For the 2.6 Migration guide, we should include a paragraph that DynamicForm was changed. People should create their own instance or use the form() method of an injected FormFactory instead.

**Comment by mkurz** [comment]
Hi Dominik!

As you probably have seen the [javadoc](https://github.com/playframework/playframework/blob/2.5.12/framework/src/play-java/src/main/java/play/data/Form.java#L51) of the deprecated static `form()` method already tells you to inject a `FormFactory` instead. People should see deprecation warnings in their 2.5 Play right now which hopefully already forces them to take action.
If you think that's too less information I just added a [`Java Form Changes` section](https://github.com/playframework/playframework/blob/master/documentation/manual/releases/release26/migration26/Migration26.md#java-form-changes) in the 2.6 migration docs - feel free to add additional information there :smile:

**Comment by domdorn** [comment]
added a paragraph. let me know what you think.

**Comment by marcospereira** [comment]
Closed by #7473.
