### ISSUE TITLE
2.6.0 Migration: Provide TestHelpers.getJavaContextComponents()

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#7051]
I have testcode that creates Java `Http.Context`s like this: 

`        Http.Context context = new Http.Context(fakeRequest());`

In 2.5 this used to work. In 2.6.0-M1 the Http.Context constructor now requires a `JavaContextComponents`, which I usually only have (afaik) through injecting of a running application. 

This requires me to have a running application (which takes time to start etc.), when all I want to do is create some objects for _unit_ Testing. 

A helper method in `play.test.Helpers` would be great. 

p.s.: I know that I should migrate to Http.RequestBuilder().build() instead of FakeRequest.

**Comment by wsargent** [comment]
It sounds like you want something like:

```
Http.Context context = Helpers.fakeContext(requestBuilder)
```
since you don't have any interest in JavaContextComponents directly...

**Comment by domdorn** [comment]
@wsargent exactly!
We're using the Http.Context to store some user-state for the request which is then later on processed in other parts of the application. This state usually gets set in a filter / actioncreator, but in the unit tests where just creating a context and set it manually to test the various scenarios. starting a full application would be overkill here.

**Comment by domdorn** [comment]
Small update: I found the class play_2.11-2.6.0-M1-sources.jar!/play/core/j/JavaHelpers.scala
It contains
 `def createContextComponents(): JavaContextComponents = {..}`
and
`def createJavaContext(req: Request[RequestBody], components: JavaContextComponents): JContext = { .. }`
as well as 
`def createJavaContext(req: RequestHeader, components: JavaContextComponents): JContext = { .. }`

basically the only thing missing is one 
`def createJavaContext(req: RequestBuilder, components: JavaContextComponents) : JContext`

but I can just combine it with the normal `Helpers.fakeContext(requestBuilder, JavaHelpers.createContextComponents)` ..
