### ISSUE TITLE
Akka actors are not working

### ISSUE THREAD

**Issue by albertoortiz** [playframework/playframework#7058]
### Play Version (2.5.x / etc)
play version: 2.4.10
Akka version: 2.4.17

### API (Scala / Java / Neither / Both)
Scala version: 2.11.8
Java version: 8

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Linux andco-core-production 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

### Library Dependencies
N/A

### Expected Behavior
We are using Play with Akka. 
Akka is is charge of different features in our back-end, like for example our chat system, between different clients that are connected to the play framework via web sockets. 

### Actual Behavior
The application seems to run fine, but for any reason that we don't know all the actors  stop working or they don't do what it is expected. The chat service is not working anymore, along with other services that depend on the Akka framework.

Also there is no specific error in logs, the ony error that is showed is:
```
org.jboss.netty.handler.codec.frame.CorruptedFrameException: unmasked client to server frame
    at org.jboss.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:381)
    at org.jboss.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:171)
    at org.jboss.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:71)
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
```
We think one problem could be a bad web socket connection from a client sending a wrong mask, but the same problem is display in the logs with a play framework version 2.3 and nothing crash. Also the web socket endpoint is up.

Could that error  come from the socket communication between actors instead of an external web socket connection?. 
The logs don't display so much information and the application is running but internally the actors are not working.

Play with 2.4.10  is working fine but not Akka
Play with 2.3.X is working fine and Akka too

**Comment by marcospereira** [comment]
Hello @albertoortiz,

The stacktrace you posted was generate using which version of Play? Also, is it possible to post the complete stacktrace or any additional logs? Also, which minor versions of Play are you using? Can you provide a project that reproduces this problem?

Finally, the [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting confirmed and reproducible bugs and feature requests in Play, not for general discussion and getting help.

**Comment by albertoortiz** [comment]
Hi @marcospereira 
Thanks for your response. We are using play 2.4.10 on a production environment so we thought this could be a bug on the play framework.  So that the reason I posted here.
Finally more that a Play bug I think it was a JVM problem that crash Akka.
Thanks anyway. 
We love play!
