### ISSUE TITLE
[2.5.x] Action composition doesn't provide the path parameters

### ISSUE THREAD

**Issue by igmar** [playframework/playframework#7063]
When doing Action composition (https://www.playframework.com/documentation/2.5.x/JavaActionsComposition), most required info is in ctx.args : The controller that us handing that request, the request method, the controller method it lands on, and the actual left value of the route entry.

What is missing is the actual params passed : 

GET /$locale<[A-Za-z]{2}>/s/*path/subcategory/:category/*subcategory        controllers.Foobar.myHandler(locale, path, category, subcategory).

I need to extract the params provided to Foobar.myHandler myself. It's not that hard, but since it's most likely already available, it would be nice to have it available.

**Comment by wsargent** [comment]
@igmar is this a bug in Play?  I'm sorry, it's not clear what you're asking for.

**Comment by igmar** [comment]
It's not a bug, since it's not documented what it provides or not.

In our case, when doing Action Composition, we get back in ctx.args : 

ROUTE_CONTROLLER
ROUTE_ACTION_METHOD
<few others>

By the time it arrived in the action composition, it already has determined which controller and controller method to call. In the composition, in our case, we need to know the arguments that would be passed to that controller.

In the above example, a Map<String, Object> filled with 

locale  -> en
path -> mypath
category -> foo 
subcategory -> bar

would be called, when the actual GET path is 

/en/s/mypath/subcategory/foo/bar

At the moment, we do the parsing ourselves, since Play doesn't provide it. I hope this makes things more clear.

**Comment by wsargent** [comment]
The processing of tags is done in the GeneratedRouter -- see for example: https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/scala/play/core/routing/GeneratedRouterSpec.scala#L72

Is this something that you do in a filter, or do you have code in the generated router itself?

**Comment by igmar** [comment]
We do this in action composition at the moment. I'm not sure this can be done from within a filter. Isn't the list of args to be passed already available ?

**Comment by wsargent** [comment]
You can fill a map from a filter.  I'd do it in the request.attributes though.
