### ISSUE TITLE
Different type of String in ReverseController? (Java)

### ISSUE THREAD

**Issue by nik** [playframework/playframework#7066]
I'm using IntelliJ for my coding, and seeing something odd. 

Here's a screenshot of what it looks like:

![screen shot 2017-03-10 at 1 33 45 pm](https://cloud.githubusercontent.com/assets/1106705/23808082/61be5100-0596-11e7-9954-5165b2646868.png)

This compiles just fine, and runs the tests (passing) but the editor is showing me red.

This happens only when in the routes file, I set the type of the parameter to a `String` like so:
`GET     /route/:id controllers.OrganizationsController.show(id: String)` 

If I set it to be 
`GET     /route/:id controllers.OrganizationsController.show(id)` 

Then all is fine in the code. I'm new to play so I'm not sure what's really happening here.

**Comment by wsargent** [comment]
This is an error in IntelliJ IDEA not in Play.  IDEA has difficulties with generated code in some instances.

**Comment by nik** [comment]
Ah. Thanks!
