### ISSUE TITLE
[doc] Websocket.reject is deprecated, but docs still mention it

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#7078]
### Play Version (2.5.x / etc)

2.5.x

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

All

### Actual Behavior

The documentation says to use reject:

https://www.playframework.com/documentation/2.5.x/JavaWebSockets#Rejecting-a-WebSocket

```
public LegacyWebSocket<String> socket() {
    if (session().get("user") != null) {
        return WebSocket.withActor(MyWebSocketActor::props);
    } else {
        return WebSocket.reject(forbidden());
    }
}
```

but it is deprecated, and we tell people to use acceptOrResult instead.

**Comment by Captain1653** [comment]
I think the old  issue can be closed. Play 2.5.x are not mantained anymore https://github.com/playframework/playframework/pull/7913#issuecomment-451598007 . And documentation for [2.7.x](https://www.playframework.com/documentation/2.7.x/JavaWebSockets#Rejecting-a-WebSocket) and [2.8.x](https://www.playframework.com/documentation/2.7.x/JavaWebSockets#Rejecting-a-WebSocket) is actual.
