### ISSUE TITLE
Add Same-Site cookie attribute

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#7086]
You might [have heard](https://twitter.com/mikewest/status/709676633712676864) of the new `SameSite` cookie attribute already (formerly known as `First-Party-Only`). It is available [since Chrome 51/Opera 39](https://www.chromestatus.com/feature/4672634709082112) already ([Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=459154)). 
Mozilla is currently actively [working on it](https://bugzilla.mozilla.org/show_bug.cgi?id=795346) as well.
Also check out the [caniuse entry](http://caniuse.com/#feat=same-site-cookie-attribute).

There was a [trending article](https://scotthelme.co.uk/csrf-is-dead/) on hackernews recently. Checkout the ([comments](https://news.ycombinator.com/item?id=13689697)).

Another blog post: http://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/
Draft: https://tools.ietf.org/html/draft-west-first-party-cookies-07

AFAIK GitHub makes use of the attribute already (for it's session cookie I think).

Here is another page which already sets the attribute (to `strict`). To test it:

1. (Make sure you haven't visit the site before. If you have always clean the cookies of the page so they will be set again from scratch)
2. Open Chrome dev tools, goto "Network"
3. Visit https://swehack.org/
4. Open the "Cookie" tab after selecting the "swehack.org" request. You should see the `SameSite` attribute is set for the cookies.

You might also find [this test page](http://rfc6265.biz/tests/) interesting.

@wsargent Because it looks like you do most of the security stuff you might be interested in this.

**Comment by gmethvin** [comment]
Yeah, we've thought about this also. It would require adding the attribute to a couple different cookie models, but should be pretty straightforward. I'd suggest we set it to `lax` by default which would work for most applications.

**Comment by wsargent** [comment]
I would also add some prefix support for cookie prefixes so that cookies with prefixes of __Secure and __Host will only be settable with the Secure attribute...

* https://googlechrome.github.io/samples/cookie-prefixes/ 

And add some kind of a warning saying that an http origin cannot set Secure cookies, since it will not be a thing in Chrome:

* https://www.chromestatus.com/feature/4506322921848832

**Comment by mkurz** [comment]
Great, thank you!

**Comment by gutoMQS** [comment]
Guys, I'm using the SameSite ( = lax) attribute in my application, however I'm facing a weird issue when trying to open dev tools (F12) on Chrome (version greater than 70.X) and also on IE11, my application auto logout and I try to inspect any object. My question is, do you guys already experiencied something like this ? Looks like when I press F12 and try to inspect the elements my JSESSIONID is being cleared somehow. Any thoughts about that ? Thanks.

**Comment by marcospereira** [comment]
Hey @gutoMQS,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. You can also discuss this using [our Gitter channel](https://gitter.im/playframework/playframework).

Best.
