### ISSUE TITLE
Possible bug with PUT request 

### ISSUE THREAD

**Issue by JFCote** [playframework/playframework#7092]
### Play Version

2.5.10

### API 

Tested in Java only (but probably both)

### Operating System

Windows 10

### JDK

1.8

### Expected Behavior

1. Request a PUT method without a body but the curl method specify that the content-type is "application/json".
For example:` curl -X PUT --header 'Content-Type: application/json' --header 'Accept: text/html' 'http://localhost:9000/api/actors/pools/reset'`
2. Play Framework should ignore the empty body and just skip the deserialization of the body
3. The method continue and return a correct code.

### Actual Behavior

On step 2, instead of skipping, it crash in the deserialization since it's empty. Error like this:

```
 For request 'PUT /api/actors/pools/reset' [Error decoding json body: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: akka.util.ByteIterator$ByteArrayIterator$$anon$1@2998da12; line: 1, column: 0]]
```
As you can see, the reason I don't have body is because it is a "reset" method, which is an update. I think there should be a check if the body is empty and skip the deserialization if it is. **But maybe there is a good reason for this decision, if so, I would like to know it. :)** 

I would then change this for a POST instead, but it make more sense as a PUT

**Comment by wsargent** [comment]
This is a bug, but here it's because the correct HTTP response would be 406 -- you want text/html, and the server can't respond based off the request headers you've asked for.

**Comment by wsargent** [comment]
So, it's not 406 (Accepts is fine) or 415 (Content-Type is also fine), but that the input cannot be parsed and is invalid -- you should be getting a 400 Bad Request here.

**Comment by JFCote** [comment]
Ok sorry if it was confusing.
Let me explain the context: I'm testing my API with Swagger-ui. There is a "try it out!" button for each method of your api.

When testing my PUT method, I saw this error, receiving an html response with an error 400 instead of json with a 200.

If you tell me that it's a standard RFC-4627 to always provide the minimum json in the body, then it's a bug in swagger-ui to put nothing in the body when doing a PUT method without any parameter. It should always provide {} by default.

If this is the case, you can close this bug and I'll open one in swagger-ui.

Thank you very much

**Comment by wsargent** [comment]
Yes -- according to https://tools.ietf.org/html/rfc4627#section-4, " A JSON parser MUST accept all texts that conform to the JSON grammar" and "A JSON text is a serialized object or array" -- [RFC 7159](https://tools.ietf.org/html/rfc7159) does not obsolete that section, in that you say you're sending JSON, you have to actually send valid JSON, which an empty body is not.

**Comment by schmitch** [comment]
well to be fair a lot of things actually don't follow the spec (especially since it's "relativly" new).
But I totally agree with wsargent here, that it's necessary to follow the RFC here.

Actually If swagger-ui does not put something in the body you can easily just create your own body parser that ignore's to have a empty body.
I doubt that swagger-ui won't change this default here, since they had that default since a very long time.

**Comment by JFCote** [comment]
Thank you for your answer guys
@schmitch : Can you provide an example or a link to resources about how to create my own body parser? Do I need to edit the Play Framework code or can I just create in my server code to override the default behavior?

Thanks!

**Comment by wsargent** [comment]
Should be here: https://www.playframework.com/documentation/2.5.x/ScalaBodyParsers#writing-a-custom-body-parser
