### ISSUE TITLE
./play install spring-1.0.3 fails with 403

### ISSUE THREAD

**Issue by cpeirens** [playframework/playframework#7101]
### Expected Behavior

1. ./play install spring-1.0.3
2. Expected to install the spring module

### Actual Behavior

1. ./play install spring-1.0.3
2. Receive the following:
         Cannot fetch the modules list from http://www.playframework.com/modules (403)... 
3. If the link is changed from http to https (DEFAULT_REPO = 'https://www.playframework.com') in ./framework/pym/play/commands/modulesrepo.py, the following is observed:
         Cannot fetch the modules list from https://www.playframework.com/modules ...

Did something change about how the supporting modules are retrieved?

**Comment by wsargent** [comment]
Hi @cpeirens this github repository is for Play 2 code -- you probably want https://github.com/playframework.com or https://github.com/playframework/play1

//cc @xael-fry

**Comment by xael-fry** [comment]
Will be handle in [Play1 #1126](https://github.com/playframework/play1/issues/1126)
