### ISSUE TITLE
Stop exposing implementation data on 404 errors

### ISSUE THREAD

**Issue by strelec** [playframework/playframework#7105]
When no route matches, you get a page with play logo displayed.

Exposing the site was built using play framework is not ideal form the security standpoint.

**Comment by marcospereira** [comment]
@strelec thanks for opening this issue.

I think you are mostly talking about the `icon` tag in our default pages here:

https://github.com/playframework/playframework/tree/master/framework/src/play/src/main/scala/views/defaultpages

Do you want to submit a pull request to solve this issue?

Thanks!

**Comment by gmethvin** [comment]
Well, that's sort of the downside to using the default pages, isn't it? Even without the logo, it's possible to figure out it comes from Play by looking at the HTML file. At least having the Play logo encourages you to change it to something custom if you don't want the default.

I'm not totally opposed to changing it for production mode, but this seems a lot like security by obscurity.

**Comment by marcospereira** [comment]
> I'm not totally opposed to changing it for production mode, but this seems a lot like security by obscurity.

It is. But the icons aren't adding any value here, so I think it is not a big deal to remove them.

**Comment by gmethvin** [comment]
I think the production error pages we should also try to remove most of the CSS and keep them as simple as possible.

**Comment by strelec** [comment]
I would stick to empty 404 response. Browsers know how to deal with those.

Or provide an 404 route in the routes file, so you can react as you wish.

**Comment by antoaravinth** [comment]
@strelec: Yes, that should be the case. We need to have a `404` route specifically. I'm new to play, I tried playing with in valid resource request, the default page that it showed wasn't really great. Probably allowing the user to specify an action in route will be the best idea.

**Comment by daveseco7** [comment]
Hi,
You can easily build custom error handler that renders your own template, thus eliminating all traces of the play framework on the client browser.

**Comment by strelec** [comment]
No. What we need is an empty 404 response (empty in a sense of 0-length body). Custom error route is a bonus.

**Comment by shkhln** [comment]
Empty page would just confuse and scare end users.

**Comment by tkopczynski** [comment]
Hi,
This issue seems to be abandoned. Is it ok to just remove icons from all default pages in order to close it ? If so, I can prepare a PR for this one.

**Comment by richdougherty** [comment]
Thanks @tkopczynski that would be great.

**Comment by tkopczynski** [comment]
@richdougherty Cool, I'll prepare a PR for this.
