### ISSUE TITLE
Documentation uses deprecated configuration key

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#7116]
On this page:  https://www.playframework.com/documentation/2.5.x/JavaTestingWithDatabases there is the following code snippet, which describes one way to create a `Database`.

```
Database database = Databases.createFrom(
        "mydatabase",
        "com.mysql.jdbc.Driver",
        "jdbc:mysql://localhost/test",
        ImmutableMap.of(
                "user", "test",
                "password", "secret"
        )
);
```

This does work but a warning is printed in the console:

`[warn] application - hardcoded value: user is deprecated, use username instead`

Like the message says, the code snipped should use `username`, not `user`.

I see the same thing on these pages:

https://www.playframework.com/documentation/2.6.x/JavaTestingWithDatabases
https://www.playframework.com/documentation/2.5.x/ScalaTestingWithDatabases
https://www.playframework.com/documentation/2.6.x/ScalaTestingWithDatabases

**Comment by marcospereira** [comment]
Thanks @rmcloughlin!

Do you want to submit a pull request to solve this?

**Comment by benmccann** [comment]
PR here: https://github.com/playframework/playframework/pull/7120
