### ISSUE TITLE
play.libs.concurrent.Futures Thread-Leak (2.6.0-M2) / "global state"

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#7117]
I discovered a thread leak in play.libs.concurrent.Futures

play.libs.concurrent.Futures creates a TimerTask which is not cleaned up on application shutdown. 
This is an issue, when "fork in test := false" 

I have a small test project showing the issue. I can provide it if necessary

**Comment by marcospereira** [comment]
@domdorn I don't think a small project is necessary here. At least to me it is pretty clear that the `timer` inside `play.libs.concurrent.Futures` is hanging since there is no call to `cancel`. I wonder if it would be better to use some of the existent Executors to schedule the tasks instead of a Timer here. Since the tasks are pretty lightweight, it shouldn't be a problem.

Anyway, the simplest solution here is apparently to have a module that just registers the Timer cancel when the application is being stopped.

Do you want to submit a PR?

**Comment by domdorn** [comment]
I can create one, but lets discuss the approach first..

I would introduce a package scoped method static void shutdown() in play.libs.concurrent.Futures that would be called when the application shuts down. 
For this I would create a module in play.libs.concurrent that has the Lifecycle injected and registers a corresponding stop-hook. 

Would that approach be ok?

**Comment by domdorn** [comment]
after thinking... we'd still have the problem that the timer is static... as far as I remember the goal of removing all the global state was also, that we can run multiple apps/tests at the same time. as the timer is static, we could be killing another apps timer, or am i wrong? at the moment I think the timers are isolated through the classloader?

**Comment by gmethvin** [comment]
@domdorn Right. If we cancel the static timer when the app stops that would mean anyone else in that classloader will not be able to use the timer. This would not work for testing.

I think the most correct solution would be to move the timer stuff to a `FutureTimer` that takes `Timer` as a dependency, and move the `timeout` and `delayed` methods to instance methods there. Then we can easily create a provider that registers a stop hook to kill the timer.

@domdorn Does that seem like a reasonable solution to you?

**Comment by wsargent** [comment]
This also has implications for things like Failsafe that expect a `ScheduledExecutorService` or `Scheduler` -- 

https://github.com/jhalterman/failsafe#asynchronous-api-integration

So if there's a way to expose that Timer it would help overall.

**Comment by marcospereira** [comment]
If we decide to create a `FutureTimer` that would be injected, than we can remove the `Timer` entirely and use a (injectable) `ScheduledExecutorService`. This same executor service can be used by Failsafe it is more flexible to configure and terminate/shutdown.

**Comment by domdorn** [comment]
hmm.. if we create the timer injectable, would the methods in the Futures class still be static? 
I mean, I know a way (=a hack), on how we could inject an instance and still keep the utility class static, but as said, its a hack (basically the old GOF Singelton pattern, just with injection). 
On the other hand, requiring the people to inject the utility class instead of calling the methods statically would probably be counter productive? 

I'm not sure on the failsafe.. Its new to me... do we depend on them or the other way around or is it just about compatibility?

**Comment by wsargent** [comment]
Futures can be static, but it does need to change a bit.

Right now, `Timeout` is an interface:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/libs/concurrent/Timeout.java

and it goes to `Futures.timeout` for the underlying logic.

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/libs/concurrent/Futures.java#L69

This should be broken out so it is more like the Scala version:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/libs/concurrent/Timeout.scala

and takes an ActorSystem as input parameter, then the scheduler can do the heavy lifting and it's more consistent.
