### ISSUE TITLE
Play commands not working

### ISSUE THREAD

**Issue by yogesh-oyo** [playframework/playframework#7122]
Play Commands are not working e.g play run, play dependencies, and showing static response for everything.

### Library Dependencies

- play

** Earlier I added mongo dependency then removed it.

### Expected Behavior

Resolve Dependencies stated in dependencies.yml

### Actual Behavior

Showing static response for every play command e.g. play run, play dependencies inside repo.

~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.4.x-localbuild, https://www.playframework.com
~
~ Oops,
~ Module not found: /opt/play-1.4.4/modules/mongo

### Reproducible Test Case

I don't have exact steps.

**
When I created a new repository, it worked fine.

**Comment by mkurz** [comment]
There is no `play` command anymore in Play 2.x. You have to use `sbt` or `activator` instead now, please check the documentation for more help.
Also you are talking about Play 1.x - which can be found here: https://github.com/playframework/play1

**Comment by yogesh-oyo** [comment]
#

**Comment by yogesh-oyo** [comment]
Thanks for quick response @mkurz
