### ISSUE TITLE
2.6.0-M2: NullPointerException in play.core.j.JavaHelpers#cookieToScalaCookie due to automatic type conversion

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#7124]
2.6.0-M2:

Just stumbled upon this wondering why my test cases fail

Apparently, we get a NullPointerException in play.core.j.JavaHelpers#cookieToScalaCookie
See this screenshot:
![image](https://cloud.githubusercontent.com/assets/100349/24245931/30cfe426-0fc5-11e7-9b6d-90c0bc753e9d.png)

From the first look, everything looks ok. The example cookie (class play.mvc.Http$Cookie) is this:
name: "PLAY_LANG"
value: "de"
maxAge: null
path: "/"
domain: null
secure: false
httpOnly: false

A simple Option(null) gives a None.. everything ok here. The problem is, that maxAge is a Java Integer which is null AND the case class expects a Option[Int]. 
It looks like through automatic conversion it tries to change the Integer to an Int, and an Int is not allowed to be null.

so this thing
`Cookie("PLAY_LANG", "de", Option(c.maxAge()), "", Option(null), false, false)`
throws a NullPointerException
while this thing
`Cookie("PLAY_LANG", "de", Option(if(c.maxAge() == null) null else c.maxAge()), "", Option(null), false, false)`
works correctly.

**Comment by domdorn** [comment]
I found out, that the PLAY_LANG cookie automatically gets generated when we do a 
`ctx.changeLang(Lang.forCode("de"));`

This creates the cookie in https://github.com/playframework/playframework/blob/afcda67c5cada258a662f77c58f57ead3ecfbac8/framework/src/play/src/main/java/play/mvc/Http.java#L244 with the maxAge set to null. 

from there on the error starts. 

We'll currently set the language in the setup methods of certain test suites. Not sure how common this is in other project setups.

**Comment by gmethvin** [comment]
Have you tried on 2.6.0-M3? I think it was fixed here: https://github.com/playframework/playframework/pull/7075/files#diff-a974756ffbaa15779cd31ee5afd857c9R34

**Comment by domdorn** [comment]
hmm.. not yet, as you just released 2.6.0-M3 4 hours ago ;) 
But will try on Monday!

**Comment by domdorn** [comment]
Hmm.. just tried with 2.6.0-2017-04-02-9a8eba8-SNAPSHOT .. cannot really say if the problem is fixed, as sbt now only executes 20 of my testcases instead of all 1000.. any ideas what could be the reason?

**Comment by domdorn** [comment]
works with the latest snapshot 
2.6.0-2017-04-02-9a8eba8-SNAPSHOT

Thanks for the fix!
