### ISSUE TITLE
[2.6.0-M2] Session encoding/decoding not working.

### ISSUE THREAD

**Issue by dispalt** [playframework/playframework#7128]
### Expected Behavior

Setting session variables doesn't seem to work with compile time DI (not sure if it's related but the path looks different enough, so I am guessing it's something there).

If I do `Ok("").withSession("foo" -> "bar")`  I then can see the value come over the wire. If I do I then make another request where I look at `request.session.get("foo")` then it's empty.  I dove into the code and it looks like the `SecretConfiguration` in the `encode` function in `CookieBaker` is set to the default value ("changeme") where the `decode` function it's set to my actual `play.http.secret.key` value.  The code looks error prone, because there are so many ways to create the default request factory that maybe something is missing.  I figure it would be an easy fix for someone who knew what they were doing.

**Comment by dispalt** [comment]
If I override the requestFactory creation,  I can get it to work with something like this:

```scala

override lazy val requestFactory: RequestFactory = new DefaultRequestFactory(
    new DefaultCookieHeaderEncoding(httpConfiguration.cookies),
    new DefaultSessionCookieBaker(httpConfiguration.session, new CookieSignerProvider(httpConfiguration.secret).get),
    new DefaultFlashCookieBaker(httpConfiguration.flash,
                                httpConfiguration.session,
                                new CookieSignerProvider(httpConfiguration.secret).get)
  )
```

**Comment by wsargent** [comment]
@dispalt confirmed, I have this fixed in the JWT PR -- https://github.com/playframework/playframework/pull/7053/files#r107762013

**Comment by gmethvin** [comment]
Yes, this should be fixed in M3

**Comment by dispalt** [comment]
Got M3 looks good, thanks!
