### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by mzuenni** [playframework/playframework#7140]
the current validtion for emails is done by this regex:
```"""^[a-zA-Z0-9\.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$""".r```
(line 80 in Validation.scala)
but this is not a correct validation for emails (my email for example is not allowed since it would contain an ü (ue) which is technically allowed but blocked by this regex) it would be a good idea to just use the corresponding standart for mail adresses. For example java mail has an implementation of RFC822

**Comment by wsargent** [comment]
I think that this has come up before.  For the record, I think the one by Dominic Sayers is the best: https://github.com/lite2073/email-validator

**Comment by wsargent** [comment]
Related:

* https://github.com/playframework/playframework/issues/925 
* https://github.com/playframework/playframework/issues/5440
* https://github.com/playframework/playframework/issues/4022

**Comment by wsargent** [comment]
The current implementation is a reflection of the HTML 5 regex used in browsers -- it's easy to create a custom validation for emails for your criteria using https://www.playframework.com/documentation/2.5.x/ScalaCustomValidations so this isn't a blocker.  Closing.
