### ISSUE TITLE
[2.6.0-M3] Test using FirefoxDriver doesn't work out of the box

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#7142]
### Play Version

2.6.0-M3

### API

Java

### Operating System

Ubuntu 16.04.  x86-64

### JDK

openjdk version "1.8.0_121"

### Library Dependencies

Firefox 52.0.1
[GeckoDriver 0.15.0](https://github.com/mozilla/geckodriver/releases/tag/v0.15.0)

### Description

I noticed that the 2.6 release of Play Framework is using Selenium 3.  In particular it pulls in version 3.0.1 of both

org.seleniumhq.selenium:selenium-api
and
org.seleniumhq.selenium:selenium-firefox-driver

However, a simple browser test using Firefox does not actually work out of the box using Play 2.6-M3, GeckoDriver 0.15 (latest) and FireFox 52.0.1 (latest).  Here is my test:

```
@Test
public void test() {
  System.setProperty("webdriver.gecko.driver", "/path/to/geckodriver");
  running(testServer(3333, fakeApplication()), FIREFOX, browser -> {
      browser.goTo("http://localhost:3333");
      assertTrue(browser.pageSource().contains("Welcome"));
  }); 
}
```

Firefox opens but does not navigate to the URL.  Instead this error is printed on the console:
```
[error] Test IntegrationTest.test failed: org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@50c9a1fe, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@50c9a1fe, version=, platform=ANY}], required capabilities = Capabilities [{}]
[error] Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
```

This can be fixed by updating the version of those two libraries from 3.0.1 to 3.3.1 in build.sbt:

```
"org.seleniumhq.selenium" % "selenium-api" % "3.3.1",
"org.seleniumhq.selenium" % "selenium-firefox-driver" % "3.3.1"
```

Maybe it's a good idea to have the 2.6 release depend on versions 3.3.1 of these libraries.  This could prevent many people from having to update them manually.

**Comment by marcospereira** [comment]
@rmcloughlin if you want to submit a PR, the relevant code is here:

https://github.com/playframework/playframework/blob/2.6.0-M3/framework/project/Dependencies.scala#L237-L248

Be aware that maybe there is a binary incompatibility between Selenium 3.3.1 and [the version required by FluentLenium 3.1.1](http://mvnrepository.com/artifact/org.fluentlenium/fluentlenium-core/3.1.1) (Selenium 3.0.1). Besides that, this should be a pretty straightforward update.
