### ISSUE TITLE
2.6.0-M3: form.data is now immutable, gives runtime errors

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#7146]
in 2.6.0 we finally made the data collection in form immutable - a good thing in general!

However, I encountered a problem: at least in one of my projects,  there are many places where the map was modified, with either calls to 
put() (for adding stuff or changing/sanitizing), 
putall() (instead of fill) or 
clear() (for resetting). 

I think it might be an idea to change the Type of data to be something like 
ReadonlyMap<String, Object> that does not have the corresponding modifier methods. 
I even tweeted to Mark Reinhold about putting this into the JDK. 
https://twitter.com/domdorn/status/846690851325644801
https://twitter.com/domdorn/status/846692358385270784

```
interface ReadonlyMap<T,O> {
      int size();
boolean isEmpty();
boolean contains(Object o);
Iterator<E> iterator();
Object[] toArray();
<T> T[] toArray(T[] a);
boolean containsAll(Collection<?> c);
... other read methods from collection / map
// helper method
 Map<T,O> toJavaMap(); 
}
```

What do you think?

**Comment by mkurz** [comment]
What we could do as well (to keep backward compatibility) is to still return the modifiable list from the `.data()` method but deprecate it and add a `.rawData()` method instead [like suggested](https://github.com/playframework/playframework/pull/6964#issuecomment-282161582) by @gmethvin (which returns the unmodifiable list).

**Comment by mkurz** [comment]
See #7168

**Comment by mkurz** [comment]
Of course the `rawData()` method could also return such a `ReadonlyMap` now. @domdorn feel free to provide a PR : smile:

**Comment by domdorn** [comment]
the reason I wanted to change the type of data() to something that has the getters of a map, but no setters was that it would kind of "force" people to look at their code, if they use unsupported operations on it.. the compiler would show them what would need to be changed.. like right now, I get those errors at "runtime" (or for those parts that are covered by tests, during test) which is quite bad.. I already refactored all the places that make use of changing operations.. but actually, I only think that I catched all of them.. the compiler could tell me for sure if that was the case or not.

**Comment by mkurz** [comment]
@domdorn I fully understand. If you provide a PR we could change the return type of the (new) `.rawData()` method to such a readonly-map (if OK with the core team). Apart from that I think #7168 still was necessary to provide a smoother upgrade experience. Also getting compiler warnings because of the `data()` method deprecation of that PR already gives you hints were to look for write operations (put(), etc.)

**Comment by mkurz** [comment]
@domdorn One more thing: I think http://bugreport.java.com/ is a good starting point to file a Java feature request. (I submitted one a few month ago via this page, took a few weeks to get an answer... but I got one :smile: )

**Comment by domdorn** [comment]
imho, there is no point in having the rawData() return the other type. 
this is about making a "change" (the map is now immutable instead of mutable) explicit and visible. 
I'll try to get a PR up in the weekend on how I would envision it.

**Comment by mkurz** [comment]
I think the question is how we want the upgrade experience to look like (besides that gmethvin suggested to change the method name). Anyway looking forward to the PR

**Comment by mkurz** [comment]
Can we close this @domdorn?
