### ISSUE TITLE
2.6.0-M3 dev-mode does not work anymore

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#7151]
After changing from 2.6.0-M2 to M3, my application does not startup in dev-mode anymore. 

> [ERROR] [03/28/2017 21:49:31.519] [play-dev-mode-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(play-dev-mode)] Internal server error, sending 500 response
> java.lang.NullPointerException
> 	at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:112)
> 	at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:108)
> 	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:262)
> 	at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:108)
> 	at play.runsupport.Reloader.recursivelyListFiles(Reloader.scala:324)
> 	at play.runsupport.Reloader$$anonfun$reload$1$$anonfun$17$$anonfun$apply$1.apply(Reloader.scala:364)
> 	at play.runsupport.Reloader$$anonfun$reload$1$$anonfun$17$$anonfun$apply$1.apply(Reloader.scala:364)
> 	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
> 	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
> 	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
> 	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
> 	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
> 	at scala.collection.mutable.SetBuilder.$plus$plus$eq(SetBuilder.scala:22)
> 	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
> 	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
> 	at scala.collection.TraversableOnce$class.toSet(TraversableOnce.scala:267)
> 	at scala.collection.AbstractIterator.toSet(Iterator.scala:1157)
> 	at play.dev.filewatch.SourceModificationWatch$.watch(PollingFileWatchService.scala:48)
> 	at play.runsupport.Reloader$$anonfun$reload$1.apply(Reloader.scala:364)
> 	at play.runsupport.Reloader$$anon$3.run(Reloader.scala:50)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at play.runsupport.Reloader$.play$runsupport$Reloader$$withReloaderContextClassLoader(Reloader.scala:46)
> 	at play.runsupport.Reloader.reload(Reloader.scala:349)
> 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:120)
> 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:118)
> 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
> 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
> 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
> 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I'm trying to put together a small test project, but maybe you know already whats the issue from looking at the stacktrace.

**Comment by domdorn** [comment]
https://github.com/playframework/playframework/blob/2.6.0-M3/framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala#L324 
is the line in question.

**Comment by benmccann** [comment]
This code was removed in https://github.com/playframework/playframework/commit/78c30ad49a4c6e9d8ccb84211f22f67bc770aec6

@domdorn would you be able to see if it works for you on the latest master?

**Comment by marcospereira** [comment]
@domdorn, 

I was not able to reproduce the problem, but looking at the code, it is probably related to the behavior of [`java.io.File.listFiles`](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#listFiles--) called here:

https://github.com/playframework/playframework/blob/2.6.0-M3/framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala#L322-L325

According to the `File.listFiles` docs, if _pathname does not denote a directory, then this method returns `null`_. So if there if the classpath contains anything besides directories, then we will get a null pointer exception.

The solution would be to check if the value is null before checking if is a directory.

**Comment by domdorn** [comment]
I can try on saturday, I'm on holidays till friday (without the notebook). 
Is there a way to use nightly-snapshots or I have to build play myself?

**Comment by benmccann** [comment]
I know we used to have nightly snapshots, but I've sort of lost track of them, so I'll have to let someone else chime in on whether they still exist and where they are.

For building play you can run `sbt publishLocal` from the framework directory. Then change the version in your app's `plugins.sbt` to `2.6.0-SNAPSHOT`

**Comment by gmethvin** [comment]
@benmccann We still have nightly snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.11/2.6.0-2017-03-29-3030cb5-SNAPSHOT/

**Comment by benmccann** [comment]
thanks! it'd be cool to add these to the docs. I filed an issue to track that: https://github.com/playframework/playframework/issues/7162

**Comment by domdorn** [comment]
Just confirmed.. the problem is FIXED in 2.6.0-2017-04-02-9a8eba8-SNAPSHOT
so I close this issue. 

Should we create a new one to document on how to use snapshots? 
I had to add 
resolvers += Resolver.sonatypeRepo("snapshots")
to my project/plugins.sbt
and my
build.sbt 
file and set 
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.0-2017-04-02-9a8eba8-SNAPSHOT")

**Comment by domdorn** [comment]
damn, @benmccann is fast.. he already did the documentation change in 
https://github.com/playframework/playframework/commit/00412f83cce8c9ec9a335a5368eef3c4e7b5cd79
