### ISSUE TITLE
2.6.0-M2: PUT request returned 403 status with Docker

### ISSUE THREAD

**Issue by fmeriaux** [playframework/playframework#7154]
From 2.6.0-M2 (the problem does not occur in M1), the PUT queries return "403 Forbiden".

Simply : 

```scala
@Singleton
class MyController @Inject()(components: ControllerComponents)(implicit executionContext: ExecutionContext) extends AbstractController(components){

    def check(): Action[AnyContent] = Action {
    NoContent
  }

  def publish() = Action.async(parse.json) { implicit request =>
    Future {
      Accepted
    }
  }
}
```

No problem in dev mode, the status obtained is 202 Accepted. However, with docker (built from the native packager plugin), the same query gets the 403 Forbidden status.

I noticed that 403 status is returned for POST, PUT, PATCH requests, even if no defined route exists. Is this a missing configuration to allow these http verbs ? I have not found any documentation specifying this possible change.

**Comment by marcospereira** [comment]
@fmeriaux,

I'm not sure right now if default filters were added in M2 or M3. Anyway, this section of the migration guide could be relevant for your case:

https://www.playframework.com/documentation/2.6.0-M3/Migration26#Default-Filters

Moreover, the [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

**Comment by fmeriaux** [comment]
@marcospereira,

You're right, this addition in the build.sbt fixes the problem.

`.disablePlugins(PlayFilters)`

I published this issue because it was either a bug or a lack of explicit information. I thought it was appropriate because it helps in some way to improve the framework.

In any case,
Thank you for your quick and relevant response.
