### ISSUE TITLE
Add nightly snapshots to docs

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#7162]
We have nightly snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.11/

But they're not mentioned anywhere. It could be helpful to mention on this page:
https://www.playframework.com/documentation/2.5.x/Repositories

**Comment by gmethvin** [comment]
The snapshot repo is mentioned on that page (https://oss.sonatype.org/content/repositories/snapshots), but the problem is we don't really show you how to find which snapshots are available and use them in your app.

**Comment by benmccann** [comment]
Doh. My problem was I was looking for the word nightly in there. I'll send a PR to fix both issues
