### ISSUE TITLE
idleTimeout documentation for akka backend in 2.6 is wrong

### ISSUE THREAD

**Issue by maxcom** [playframework/playframework#7172]
Documentation at https://playframework.com/documentation/2.6.x/SettingsAkkaHttp says that idle timeout can be configured with this settings:

```
play {
  server {
    akka {
      https.idleTimeout = 6 hours
    }
  }
}
```

however this property is ignored by framework.

Actual settings that is read by [AkkaHttpServer](https://github.com/playframework/playframework/blob/2.6.0-M3/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L66) is

```
play {
  server {
    https.idleTimeout = 6 hours
  }
}
```

**Comment by marcospereira** [comment]
Related to #7067.
