### ISSUE TITLE
[2.6.0-M3] discardingCookies in Result works wrong

### ISSUE THREAD

**Issue by EnverOsmanov** [playframework/playframework#7174]
I think function `play.api.mvc.Result#discardingCookies` in Play 2.6.0-M3 works incorrect. It adds new discarded cookie, but doesn't  removes old cookies.

For example before using `discardingCookies` I have single cookie:

> Cookie(id,test-id,Some(43200),/,None,true,true,None)

After I `discardingCookies` have:

> "Cookie(id,test-id,Some(43200),/,None,true,true,None)"
> "Cookie(id,test-id,Some(43200),/,None,true,true,None)"
>  "Cookie(id,,Some(-86400),/,None,true,true,None)"

Expected result:

>  "Cookie(id,,Some(-86400),/,None,true,true,None)"

So was added extra cookies with same names (one of them with expired age). But cookies with same name whose age is not expired should be deleted instead.

Play 2.5 doesn't have that problem because it was using `ListMap` - so every cookie's name was unique. Now it is just `Seq`uence.

Test [code](https://gist.github.com/EnverOsmanov/e1f7eb17f7208f002e09b07494fe4429) on gist.
Test code in file: [ApplicationSpec.scala.zip](https://github.com/playframework/playframework/files/886413/ApplicationSpec.scala.zip)

**Comment by gmethvin** [comment]
@EnverOsmanov I believe this is not a problem in a real application because when Play writes out the Result it assumes cookies later in the list are meant to override the previous ones. But I agree it would be nice to make sure there are no duplicates in the list so it makes unit testing easier.
