### ISSUE TITLE
2.6.0-M3 (SNAPSHOT 2017-04-02): Netty does not find play logger

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#7186]
I'm using the snapshot published this night: 2.6.0-2017-04-02-9a8eba8-SNAPSHOT

I'm getting the following exception when trying to start my application in prod mode:

> Uncaught error from thread [application-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
> java.lang.NoSuchMethodError: play.api.Logger.trace(Lscala/Function0;)V
> 	at play.core.server.NettyServer$$anonfun$channelSink$1$$anonfun$apply$8.apply(NettyServer.scala:185)
> 	at play.core.server.NettyServer$$anonfun$channelSink$1$$anonfun$apply$8.apply(NettyServer.scala:184)
> 	at scala.Option.foreach(Option.scala:257)
> 	at play.core.server.NettyServer$$anonfun$channelSink$1.apply(NettyServer.scala:184)
> 	at play.core.server.NettyServer$$anonfun$channelSink$1.apply(NettyServer.scala:149)
> 	at akka.stream.impl.fusing.Map$$anon$7.onPush(Ops.scala:47)
> 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
> 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
> 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
> 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent$class.execute(ActorGraphInterpreter.scala:42)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:75)
> 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
> 	at akka.actor.Actor$class.aroundReceive(Actor.scala:513)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
> 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:519)
> 	at akka.actor.ActorCell.invoke(ActorCell.scala:488)
> 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
> 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
> 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
> 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

The exception mentions this Class/Line, but from looking at the code it does not really fit:
https://github.com/playframework/playframework/blob/master/framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala#L185

right before this exception is thrown, I have the following line in my log:
2017-04-03 14:48:05,999 [debug] p.s.a.o.a.n.c.ChannelManager -  - Adding key: https://hooks.slack.com:443 for channel [id: 0x30e78f06, L:/172.17.0.2:33450 - R:hooks.slack.com/13.32.27.245:443] which indicates that a request is performed (we have a slack actor that reports application startup).. but I'm not sure this is related.. 

Any ideas?

**Comment by domdorn** [comment]
Ok, for some reason unknown to me, I still have the Play 2.5.3 netty-server in the classpath. Apparently it gets pulled in by
 com.typesafe.play:play-logback_2.11:2.6.0-2017-04-02-9a8eba8-SNAPSHOT

![image](https://cloud.githubusercontent.com/assets/100349/24615687/4146d3dc-188f-11e7-98f9-9b09b8fe627c.png)

**Comment by marcospereira** [comment]
@domdorn, are you running a test or your application? Using sbt or IDEA?

Regarding IDEA seeing old classes, you can refresh your project using the refresh button in sbt panel:

<img width="482" alt="screen shot 2017-04-03 at 2 14 45 pm" src="https://cloud.githubusercontent.com/assets/4576/24621488/04cfc2a4-1878-11e7-9588-50e8424a2d80.png">

(left top corner)

**Comment by domdorn** [comment]
Ok, I have updates: 
First: The issue was seen when running my app in a docker container. Our docker configuration had the netty-native-transport enabled. After disabling my netty-native-configuration, the app is able to start. 
Before that, my configuration looked like this:
```
play.server {
  provider = "play.core.server.NettyServerProvider"

  netty {
    transport = "native"
  }
}

```

From looking further into the dependencyTree, it looks like one of my dependencies pulled in play 2.5.3 .. almost all of it got evicted with 2.6.0-SNAPSHOT versions, except the netty-server .. because the jar was still on the classpath, the app started up and failed with the above mentioned exception instead of saying "there's no netty server available"

> [0m[[0minfo[0m] [0m  +-it.innove:play2-pdf:1.5.1 [S][0m
> [0m[[0minfo[0m] [0m  | +-com.typesafe.play:play-java_2.11:2.5.3 (evicted by: 2.6.0-2017-0..[0m
> [0m[[0minfo[0m] [0m  | +-com.typesafe.play:play-java_2.11:2.6.0-2017-04-02-9a8eba8-SNAPSH..[0m
> [0m[[0minfo[0m] [0m  | | +-com.typesafe.play:play_2.11:2.6.0-2017-04-02-9a8eba8-SNAPSHOT ..[0m
> ...
> [0m[[0minfo[0m] [0m  | +-com.typesafe.play:play-logback_2.11:2.5.3 (evicted by: 2.6.0-201..[0m
> [0m[[0minfo[0m] [0m  | +-com.typesafe.play:play-logback_2.11:2.6.0-2017-04-02-9a8eba8-SNA..[0m
> ...
> [0m[[0minfo[0m] [0m  | +-com.typesafe.play:play-netty-server_2.11:2.5.3 [S][0m
> [0m[[0minfo[0m] [0m  | | +-com.typesafe.netty:netty-reactive-streams-http:1.0.5[0m
> [0m[[0minfo[0m] [0m  | | | +-com.typesafe.netty:netty-reactive-streams:1.0.5 (evicted by:..[0m
> [0m[[0minfo[0m] [0m  | | | +-com.typesafe.netty:netty-reactive-streams:1.0.8[0m
> [0m[[0minfo[0m] [0m  | | | | +-io.netty:netty-handler:4.0.41.Final (evicted by: 4.0.43.Fi..[0m
> [0m[[0minfo[0m] [0m  | | | | +-io.netty:netty-handler:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | | | | +-io.netty:netty-buffer:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | | | | | +-io.netty:netty-common:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | | | | | [0m
> [0m[[0minfo[0m] [0m  | | | | | +-io.netty:netty-codec:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | | | | | +-io.netty:netty-transport:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | | | | |   +-io.netty:netty-buffer:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | | | | |     +-io.netty:netty-common:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | | | | |     [0m
> [0m[[0minfo[0m] [0m  | | | | | +-io.netty:netty-transport:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | | | |   +-io.netty:netty-buffer:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | | | |     +-io.netty:netty-common:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | | | |     [0m
> [0m[[0minfo[0m] [0m  | | | | +-org.reactivestreams:reactive-streams:1.0.0[0m
> [0m[[0minfo[0m] [0m  | | | | [0m
> [0m[[0minfo[0m] [0m  | | | +-io.netty:netty-codec-http:4.0.34.Final (evicted by: 4.0.43.F..[0m
> [0m[[0minfo[0m] [0m  | | | +-io.netty:netty-codec-http:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |   +-io.netty:netty-codec:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |   | +-io.netty:netty-transport:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |   |   +-io.netty:netty-buffer:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |   |     +-io.netty:netty-common:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |   |     [0m
> [0m[[0minfo[0m] [0m  | | |   +-io.netty:netty-handler:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |     +-io.netty:netty-buffer:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |     | +-io.netty:netty-common:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |     | [0m
> [0m[[0minfo[0m] [0m  | | |     +-io.netty:netty-codec:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |     | +-io.netty:netty-transport:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |     |   +-io.netty:netty-buffer:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |     |     +-io.netty:netty-common:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |     |     [0m
> [0m[[0minfo[0m] [0m  | | |     +-io.netty:netty-transport:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |       +-io.netty:netty-buffer:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |         +-io.netty:netty-common:4.0.43.Final[0m
> [0m[[0minfo[0m] [0m  | | |         [0m
> [0m[[0minfo[0m] [0m  | | +-com.typesafe.play:play-server_2.11:2.5.3 (evicted by: 2.6.0-20..[0m
> [0m[[0minfo[0m] [0m  | | +-com.typesafe.play:play-server_2.11:2.6.0-2017-04-02-9a8eba8-SN..[0m


I just have seen that there is a tiny note in the migration guide about the Netty change (https://www.playframework.com/documentation/2.6.x/Migration26#Netty-4.1) , but it was not clear to me that this was connected. Anyway, problem solved, I close the issue.
