### ISSUE TITLE
[2.6.0-M4] logback.xml dev mode with compile-time DI

### ISSUE THREAD

**Issue by dispalt** [playframework/playframework#7205]
### API
* Scala
* Compile-time 
* MacOS 10.10
* Disabled "play-layout"
* Dev mode (`run` in sbt)

### Expected Behavior

With a logback.xml in the `src/main/resources` directory it doesn't seem to pick up the changes.  It looks like the code has changed since 2.5, so it might be a regression.

### Actual Behavior

I set some breakpoints and looks like during compile time DI it uses a function that searches the classpath for:

```scala
val resourceName = if (mode == Mode.Dev) "logback-play-dev.xml" else "logback-play-default.xml"
```

And it doesn't pick up that change.

**Comment by wsargent** [comment]
Are you specifying the LoggerConfigurator as in https://www.playframework.com/documentation/2.5.x/SettingsLogger#Using-a-custom-application-loader ?

**Comment by dispalt** [comment]
I was not.  It's a vanilla logging setup.

**Comment by wsargent** [comment]
Did you look at the compile time example in the playframework.com/download#examples section?

https://github.com/playframework/play-scala-compile-di-example/blob/master/app/MyApplicationLoader.scala#L11

**Comment by dispalt** [comment]
And that was it, I feel like an idiot, thanks!
