### ISSUE TITLE
Scalatestplus-play broken on M4

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#7206]
### Play Version (2.5.x / etc)

2.6.0-M4

### API (Scala / Java / Neither / Both)

Both

### Actual Behavior

It looks like upgrading to M4 breaks because renaming HMACSHA1CookieSigner to DefaultCookieSigner caused a ClassNotFoundException in scalatestplus-play -- see the builds:

- [x] https://github.com/playframework/play-scala-secure-session-example/pull/14
- [x] https://github.com/playframework/play-scala-streaming-example/pull/20
- [ ] https://github.com/playframework/play-scala-isolated-slick-example/pull/26
- [ ] https://github.com/playframework/play-scala-websocket-example/pull/57
- [x] https://github.com/playframework/play-java-websocket-example/pull/35
- [ ] https://github.com/playframework/play-scala-starter-example/pull/28
- [ ] https://github.com/playframework/play-scala-rest-api-example/pull/55

**Comment by wsargent** [comment]
I'll update scalatestplus-play so it reflects M4 correctly

**Comment by marcospereira** [comment]
@wsargent there are multiple causes for these failures. For example, play-java-websocket-example is failing because of Akka upgrade in Play (now 2.5.0):

https://travis-ci.org/playframework/play-java-websocket-example/jobs/220179335#L739-L752

I'm looking at the problems individually to fix them.

**Comment by marcospereira** [comment]
For play-scala-secure-session-example project, the problem is that, for the test scope, there is a dependency on `play-java` that is not evicted by the newer version. To inspect that, run the following command:
```bash
sbt "test:what-depends-on com.typesafe.play play-java_2.12 2.6.0-M2"
```
And you will get the following output:
```
[info] com.typesafe.play:play-java_2.12:2.6.0-M2 [S]
[info]   +-com.typesafe.play:play-ahc-ws_2.12:2.6.0-M2 [S]
[info]     +-org.scalatestplus.play:scalatestplus-play_2.12:3.0.0-M2 [S]
[info]       +-play-scala-secure-session-example:play-scala-secure-session-example_2.12:1.0-SNAPSHOT [S]
```

The solution would be to add the dependency below to the build:
```scala
libraryDependencies += "com.typesafe.play" %% "play-java" % "2.6.0-M4"
```
But we should revise the dependency tree/graph here to see if this could be avoided.

**Comment by wsargent** [comment]
ah, because play-ahc-ws depends on play-java?

**Comment by marcospereira** [comment]
@wsargent, 

`play-ahc-ws` depends on `play-java`, which is (correctly) not pulled when adding `scalatestplus-play`, and then it is not evicted by the newer version.

**Comment by marcospereira** [comment]
See https://github.com/playframework/play-scala-secure-session-example/pull/20.

**Comment by wsargent** [comment]
Released scalatestplus-play M3
