### ISSUE TITLE
CORSFilter should extend EssentialFilter

### ISSUE THREAD

**Issue by jsw** [playframework/playframework#7208]
...per gitter conversation with @wsargent 

### Play Version (2.5.x / etc)
2.5.14

### API (Scala / Java / Neither / Both)
Scala

**Comment by wsargent** [comment]
Don't see any reason why it isn't an EssentialFilter:

https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala#L39

**Comment by wsargent** [comment]
Fixed by https://github.com/playframework/playframework/pull/7409
