### ISSUE TITLE
Combine log4j and logback together

### ISSUE THREAD

**Issue by txm119161336** [playframework/playframework#7210]
Hi 
In our company ,we have both log4j and logback  framework in use , and i hope we can have a kind of adapter which can allow use to flexibly use log4j and logback.  let's say ,if the user conf is log4j ,we use log4j, if the user's config is logback ,then we load logbak. is there any solution for that？

**Comment by wsargent** [comment]
You can sort of what you want in SLF4J by using a context selector:

https://logback.qos.ch/manual/loggingSeparation.html

but Play assumes you have one application classloader and the
StaticBinderImpl is going to be the source of the logger factory.  So it
would not be easy.

--
Will Sargent
*Engineer, Lightbend, Inc.*
will.sargent@lightbend.com

**Comment by wsargent** [comment]
Closing this as it is not a play issue.
