### ISSUE TITLE
Java routing DSL does not sync context changes to result

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#7213]
The following code doesn't work:

```java
new RouterDSL()
  .GET("/foo").routeTo(() -> {
    Http.Context.current().session().put("foo", "bar");
    return ok();
  }).build()
```

Since changes to the session, other headers, cookies etc, added to the HTTP context created when the method is invoked, are not added to the Scala result.

**Comment by gmethvin** [comment]
Right. We should be using `JavaHelpers.createResult(ctx, javaResult)` but instead we're just using `javaResult.asScala`.
