### ISSUE TITLE
[2.4.x] POST methods log exceptions twice

### ISSUE THREAD

**Issue by akuniko** [playframework/playframework#7215]
### Play Version 
2.4.x
### API 
Java
### JDK 
1.8.0_112
### Expected Behavior

Log error only once, like it is for GET. Having SMTPAppender I am getting two almost the same mails.

### Actual Behavior

When POST action throws exception, error is logged twice. 

- **PlayDefaultUpstreamHandler** Cannot invoke the action

- ! @73jj7458m - Internal server error, for (POST) [/exception] ->Internal server error play.api.http.**HttpErrorHandlerExceptions**$$anon$1: Execution exception[[NullPointerException: null]]

### Reproducible Test Case

Just create post action which throws exception:
_controllers.Application.java_
`	public Result postNullPointer() {
		throw new NullPointerException();
	}
`
_routes_
`
POST    /exception                        controllers.Application.postNullPointer()
`

**Comment by marcospereira** [comment]
Hey @akuniko,

Looks like this is not happening with Play 2.5+. Could you please confirm this? If so, do you mind to submit a pull request to fix this for Play 2.4.x?

Thanks.

**Comment by akuniko** [comment]
Hey,
indeed, issue is only for Play 2.4.x

**Comment by marcospereira** [comment]
Closing since Play 2.4.x is not maintained anymore.
