### ISSUE TITLE
Update deployment documentation for native-packager on systemd, or upgrade sbt-native-packager to newest version

### ISSUE THREAD

**Issue by saosebastiao** [playframework/playframework#7217]
### Play Version 
2.5.x - `PlayScala` plugin

### Operating System 
Ubuntu 16.04

### JDK 
Oracle 1.8.0_121

### Library Dependencies
not applicable 

### Expected Behavior

I should be able to deploy to a systemd-based ubuntu distribution using the native packager

### Actual Behavior

According to the sbt-native-packager docs, I can add a `SystemdPlugin` to my project and then `debian:packageBin` will output a systemd-enabled deb file. However, sbt can't find the `SystemdPlugin`, and running without it results in this installation failure:

> Selecting previously unselected package my-app. (Reading database ... 310635 files and directories currently installed.) Preparing to unpack .../my-app_1.0-SNAPSHOT_all.deb ... Unpacking my-app (1.0-SNAPSHOT) ... Setting up my-app (1.0-SNAPSHOT) ... initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused Failed to start my-app.service: Unit my-app.service not found. my-app could not be registered or started Processing triggers for ureadahead (0.100.0-19) ...

**Comment by marcospereira** [comment]
Play is already using the latest stable version of sbt-native-packager (see [here](https://github.com/playframework/playframework/blob/2.5.x/framework/project/plugins.sbt#L7)). sbt-native-packager 1.2.x still have just milestone releases. Unfortunately, the docs for 1.1.5 were overridden by the milestone versions, but you can still access them here:

https://github.com/sbt/sbt-native-packager/blob/1.1.x/src/sphinx/archetypes/java_server/customize.rst#systemd-support

There is not much we can do in Play docs since sbt-native-package docs aren't published for every version. Or maybe we should link directly to github files, as I did above, but that is not the fully rendered documentation.

What do you think?

**Comment by domdorn** [comment]
@saosebastiao could you elaborate on what you mean with "sbt can't find the SystemdPlugin" ? From the error message, it looks like the package is still using upstart. 
From looking at a old project of mine, I configured SystemD usage like this:
`    serverLoading in Debian := com.typesafe.sbt.packager.archetypes.ServerLoader.SystemV,`
could you try this? Please also post on how you configured the native packager in your build.sbt

**Comment by saosebastiao** [comment]
@domdorn @marcospereira 

The sbt-native-packager documentation linked in the play docs is for version 1.2.0-SNAPSHOT version, and apparently the approach for SystemD is different 1.2 than it is in 1.1 (which I believe play is using). 

Using what I found from the link @marcospereira provided, I've been able to get a working build. 

specifically these changes:

```
import` com.typesafe.sbt.packager.archetypes.ServerLoader

serverLoading in Debian := ServerLoader.Systemd

javaOptions in Universal ++= Seq(
	"-Dpidfile.path=/dev/null"
)
```

I got silent failures when trying to start up the app, and through some journalctl debugging I realized that the play PID file was interfering with startup, so I removed it. Now it starts up, but I'm not sure if I'm gonna run into any problems with starts/stops/restarts/etc.. 

Not being able to refer to the sbt-native-plugin 1.1.5 documentation directly was a huge source of confusion for me, especially since the Play docs link directly to it. It would be nice(r) if the sbt-native-packager website allowed you to link to the docs for a specific version, but in the absence of that ability I think it would be a good idea for the play docs to link directly to the github files for 1.1.5.

**Comment by muuki88** [comment]
Sorry that this is still an issue. The docs are available in all different versions here:

http://sbt-native-packager.readthedocs.io/en/stable/

At some point we need to configure the CNAME for the read-the-docs manual to the scala-sbt subdomain.

**Comment by marcospereira** [comment]
Thank you so much, @muuki88.

@saosebastiao do you want to provide a pull request to update the docs?

**Comment by saosebastiao** [comment]
@marcospereira sure

Would you like me to link directly to the stable link or the pinned link?

**Comment by muuki88** [comment]
The linked I posted is already the stable link. But if you want to pin it to 1.1.5 you can select the version on the bottom-left of the page.

**Comment by benmccann** [comment]
This was fixed in master: https://github.com/playframework/playframework/commit/ae73f5504163874a206f18c20e403110a0d1cae5
