### ISSUE TITLE
Improve RequestHeader#host perofomance

### ISSUE THREAD

**Issue by zavakid** [playframework/playframework#7229]
in the trait `play.api.mvc.RequestHeader`,  there's a lazy value `host`, which using `Regex` to extract the hostPort if there's any :

```scala
    /**
     * The HTTP host (domain, optionally port)
     */
    lazy val host: String = {
      val AbsoluteUri = """(?is)^(https?)://([^/]+)(/.*|$)""".r
      uri match {
        case AbsoluteUri(proto, hostPort, rest) => hostPort
        case _ => headers.get(HeaderNames.HOST).getOrElse("")
      }
    }
```

the `host` is lazy, that means it will compute only once for every request, and it's expected 

but the `AbsoluteUri` `"""(?is)^(https?)://([^/]+)(/.*|$)""".r` will also compile the pattern for every request, it is unnecessary because `AbsoluteUri` is threadsafe.

I think we can extract `AbsoluteUri` outside the `host` value scope, and reuse it for every request. This will reduce unnecessary CPU because it reduces the pattern compiled overhead, especially when a play server receives  many requests.

**Comment by gmethvin** [comment]
@zavakid It would probably be good to extract it into a private var in the `RequestHeader` object. Interested in submitting a pull request?

**Comment by zavakid** [comment]
@gmethvin sure, I'm going for this issue.

**Comment by zavakid** [comment]
check out this PR: https://github.com/playframework/playframework/pull/7233
