### ISSUE TITLE
value get is not a member of play.api.Configuration

### ISSUE THREAD

**Issue by Anujmoglix** [playframework/playframework#7234]
val config = conf.get[Configuration]("play.filters.cors")

**Comment by cchantep** [comment]
Hi, please first have a look at the [documentation]( https://playframework.com/documentation/2.5.x/Home), then/or use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask question (rather than this issue tracker for confirmed issue or feature request). Best regards.
