### ISSUE TITLE
Review default thread pool configuration

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#7242]
Play overrides Akka's default thread pool in a few ways, but it's possible that the defaults could be improved. See [`reference-overrides.conf`](https://github.com/playframework/playframework/blob/38abd1ca6d17237950c82b1483057c5c39929cb4/framework/src/play/src/main/resources/play/reference-overrides.conf).

```
# Settings this to 1 instead of 3 seems to improve performance.
parallelism-factor = 1.0
```

This is set to 1.0 instead of Akka's default 3.0. This improves performance on some workloads (e.g. most Prune tests) but it could hinder other workloads. I noticed recently when I was writing a JDBC benchmark that it was better to remove this setting. This makes me think that we might currently be tuning too much for Prune tests (or need different Prune tests). I suggest we remove this configuration from Play and use Akka's defaults instead.

```
# @richdougherty: Not sure why this is set below the Akka
# default.
parallelism-max = 24
````

Several years after I wrote that comment I think it's probably a bad idea to limit max threads in this way. Again I suggest we remove Play's overridden value and instead use Akka's defaults.

```
# Setting this to LIFO changes the fork-join-executor
# to use a stack discipline for task scheduling. This usually
# improves throughput at the cost of possibly increasing
# latency and risking task starvation (which should be rare).
task-peeking-mode = LIFO
```

This is an opinionated choice, but I still think it's a good default for Play. It helps when you have sequential (rather than fork-join) style concurrency but it does risk failure if there's a lot of blocking happening…

Cc @wsargent.

**Comment by jrudolph** [comment]
The default parallelism setting tries to account for some blocking going on the default dispatcher. If there's is no blocking code running on the main dispatcher over-provisioning of fork join pool threads will mostly lead to those extra threads greedily fighting for tasks which (mostly) eats up CPU idle-time (i.e. bad power efficiency) but might also interfere with scheduling of other threads and processes on the same machine.

I'm not a particular fan of the default setting and usual recommend to use `parallelism-factor = 1` and to set the min and max values so that the number of cores the app runs on is in that range.

**Comment by guizmaii** [comment]
Hi, 

As asked on Twitter. 
Play is now Akka-HTTP based, so Akka values should be the good ones, no ? 
Does Akka-HTTP also tune these values ?

Thanks

**Comment by KoenDG** [comment]
@richdougherty You said

> This is an opinionated choice, but I still think it's a good default for Play. It helps when you have sequential (rather than fork-join) style concurrency but it does risk failure if there's a lot of blocking happening…

Would you consider an application which's main task is to query a database many times in a single call to be such a workload. It seems like it to me, but I'm wonder if that kind of task needs LIFO or FIFO

**Comment by richdougherty** [comment]
I think you'll get more throughput if you use a LIFO/stack structure for scheduling. You'd need to profile to check though. :)
