### ISSUE TITLE
[2.6 - M4] When you add a cookie PLAY_SESSION is set

### ISSUE THREAD

**Issue by GiuseppeCiccone** [playframework/playframework#7246]
### Play Version (2.5.x / etc)
2.6 M4

### API (Scala / Java / Neither / Both)
Java

When I add a cookie PLAY_SESSION is generated.

### Expected Behavior
The cookie is saved without PLAY_SESSION COOKIE

### Actual Behaviour
It seems that only PLAY_SESSION is saved

**Comment by wsargent** [comment]
Can you provide a small project with a test to demo?

**Comment by GiuseppeCiccone** [comment]
It will be quite hard.
I'm developing a restful api for a client in react and I have to send csrf token in the header when a user login/register.
State changing post routes will require the csrf token in the header and a jwt stored in a httpOnly cookie to authenticate the user

**Comment by wsargent** [comment]
@GiuseppeCiccone have you checked out https://github.com/playframework/play-scala-secure-session-example/tree/SNAPSHOT?

**Comment by GiuseppeCiccone** [comment]
@wsargent Thank you very much, I will check it out

I made some tests and I figured out that PLAY_SESSION is automatically generated when I add a cookie
`response().setCookie(new Http.Cookie("accessToken", jwt, 604800, "/", "", true, true, null));`

**Comment by dispalt** [comment]
I am definitely running into this and it is driving me slightly nuts.  The biggest thing I noticed is that even though I changed my `cookieName` I see `PLAY_SESSION` being set.

I am not entirely sure how it's being set, if I restart play and load on no errors, it comes back with my original cookie.  Ill see if I can narrow this down.

**Comment by wsargent** [comment]
This is probably the CSRF token being set from the CSRFFilter, which is loaded by default.

**Comment by GiuseppeCiccone** [comment]
@wsargent I disabled default CSRFFilter, but play session is still here.

**Comment by dispalt** [comment]
@GiuseppeCiccone out of curiosity, do you use compile-time DI?

**Comment by PainterAndHacker** [comment]
I'm having the same issue (or a similar one). I just upgraded to `2.6.0-M5`, and `withSession` is no longer respecting my custom `cookieName` in application.conf. 

> This is probably the CSRF token being set from the CSRFFilter, which is loaded by default.

I agree with this hypothosis. I just set `play.filters.enabled = []` to test, and my `cookieName` is being respected again.

This seems like a pretty dangerous and silent failure.

**Comment by dispalt** [comment]
I've had trouble with M5 wrt to compile-time DI, I think @wsargent even recommended sticking to `M4` for now.  But it still randomly happens that my cookie won't be honored, it seems like either if I start the server and it begins on an error or some other similar condition

**Comment by gmethvin** [comment]
Okay, so it seems there are separate issues here. 

@GiuseppeCiccone What is your CSRF configuration? Have you configured `play.filters.csrf.cookie.name`? If not, `@AddCSRFToken` will add the CSRF token to the session (instead of a separate CSRF cookie), and if you're using the default Play session cookie name, it should create a `PLAY_SESSION`. But that behavior hasn't changed since 2.5.

@dispalt Can you provide a code sample or test of what's not working? By `cookieName` are we talking about `play.http.session.cookieName`? Are you seeing multiple cookies set or just `PLAY_SESSION`? I'm pretty confident we can track down what's going on, but not clear on how to reproduce.

**Comment by GiuseppeCiccone** [comment]
@gmethvin Thanks a lot, it fixed the issue. Closing
