### ISSUE TITLE
2.5.x support for Akka 2.5

### ISSUE THREAD

**Issue by jrudolph** [playframework/playframework#7251]
It seems [people are trying to use Play with Akka 2.5.0](https://groups.google.com/forum/#!topic/akka-user/ZF9O70YYj84) which fails because Play 2.5 used deprecated features of Akka 2.4 which were removed in Akka 2.5. Konrad recently fixed the incompatibility on the master branch. Should that change be backported to Play 2.5?

**Comment by gmethvin** [comment]
Konrad's original change was #7153 but we'll also need #7257. We should be good for the scheduled 2.5.15 release in two weeks though.

**Comment by marcospereira** [comment]
Hey @jrudolph,

We usually don't do bigger updates in stable versions, like 2.5.x, since this can break user code. Considering that Akka 2.5 removed some of the deprecated APIs, that would certainly break some applications out there, which is not desirable for Play 2.5 releases.

So, unfortunately, users will need to wait until we release Play 2.6.0 to also get Akka 2.5.

**Comment by jrudolph** [comment]
I might not have been clear. I didn't want to suggest updating to Akka 2.5.x but including the smallish changes that @gmethvin mentioned. These changes should be enough that people who want are able to update Akka 2.5.x which is otherwise compatible with Akka 2.4. The problem here is that it is play which uses deprecated API from Akka...

**Comment by marcospereira** [comment]
Got it. Reopening then.

**Comment by gmethvin** [comment]
Right. I agree we should not upgrade to Akka 2.5 in Play 2.5, especially as that would break any code using deprecated Akka features. That's not something we normally want to do in a minor release. But if someone makes an explicit choice to upgrade it should be possible.

**Comment by wsargent** [comment]
Does https://github.com/playframework/playframework/pull/7358 address this?

**Comment by gmethvin** [comment]
Yes
