### ISSUE TITLE
Cannot pass parameters in production mode

### ISSUE THREAD

**Issue by cyrilfr** [playframework/playframework#7265]
I cannot pass parameters in production mode with Play Framework 2.5. For example, if I want to use a custom configuration file in production (https://www.playframework.com/documentation/2.5.x/ProductionConfiguration), I get an error.

Here are the commands I run locally according the documentation:

    activator clean stage
    target/universal/stage/bin/myapp -Dconfig.resource=prod.conf
    Bad root server path: /home/me/Documents/MyApp-D

**Comment by cchantep** [comment]
Hi, please use the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/play-framework) to ask question/for help (rather than this issue tracker dedicated for confirmed issue/actionable feature request). Best regards.
