### ISSUE TITLE
Documentation still uses "play" command

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#7268]
On this page:  https://www.playframework.com/documentation/2.5.x/ConfigFile and also the 2.6.x version there is this text:

This supports specifying config options on the command line. ie. `play -Dkey=value run`

**Comment by gmethvin** [comment]
@rmcloughlin We'd be happy to accept a PR if you'd like to make a contribution.

**Comment by rmcloughlin** [comment]
I would, but I don't know how this is done in sbt.  This comment seems to indicate that it can't be done with the same syntax:

https://groups.google.com/forum/#!topic/play-framework/sNVRDC_2KIQ
