### ISSUE TITLE
Websocket trigger callback if connection is lost

### ISSUE THREAD

**Issue by daveseco7** [playframework/playframework#7271]
Hello,
Is there way to catch an `onclose` event on a websocket? Can I configure an **ping/pong** logic to check if a client still connected ? Im facing a problem where, if for some reason a client loses his internet connection, my play instance has no way to delete his info, sense it's oblivious to what happen to the client.

### Expected Behavior
If a client is no longer connected to the websocket, it should trigger `in.close()` callback.

**Settings:**

- Play version 2.5.x
- API Both
- Linux apoc 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**Comment by marcospereira** [comment]
Hello @daveseco7,

See this section of documentation:

1. For Java: https://www.playframework.com/documentation/2.5.x/JavaWebSockets#Detecting-when-a-WebSocket-has-closed
2. For Scala: https://www.playframework.com/documentation/2.5.x/ScalaWebSockets#Detecting-when-a-WebSocket-has-closed

It states that "When the WebSocket has closed, Play will automatically stop the actor".

Moreover, the [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

Best.

**Comment by daveseco7** [comment]
Sorry for opening a new issue, but I'm facing a problem that I think it's not related to an incorrect implementation (**I think**).  Even using when I use: 

 `public void postStop() throws Exception {
    someResource.close();
}`

This method is not called when a client loses connectivity, shouldn't the WebSocket close and this method executed if on of the endpoints closes or is unreachable?

Best regards
