### ISSUE TITLE
Play start project download issue

### ISSUE THREAD

**Issue by jozolam** [playframework/playframework#7274]
I would like to learn play but i got exception: "This exception has been logged with id 73na8egpd."
https://example.lightbend.com/v1/download/play-scala-starter-example
I also tried github but i got 404. 
https://github.com/playframework/play-scala-starter-example/tree/master
Am i doing something wrong?

**Comment by wsargent** [comment]
We renamed the branch from "master" to "2.5.x" but did not update example-code-service.  The example code service needs to be updated.  Please https://github.com/playframework/play-scala-starter-example/tree/2.5.x

PR is https://github.com/typesafehub/example-code-service/pull/84

**Comment by wsargent** [comment]
This has now been resolved.
