### ISSUE TITLE
Ebean Orm mapping exception

### ISSUE THREAD

**Issue by yokidara01** [playframework/playframework#7279]
I'm trying to excute a native sql query with ebean and there is my code

 `  String sql="SELECT DISTINCT  value,propriete_id FROM values_prop WHERE produit_id IN (SELECT produit_id FROM produit WHERE categorie_id ="+idCat+")";

 
   RawSql rawSql =
            RawSqlBuilder
                    .parse(sql)
                    .columnMapping("propriete_id","Values_Prop.proriete")
                    .columnMapping("value ","Values_Prop.value")
                   .create();

    Query<Values_Prop> query = Ebean.find(Values_Prop.class);
    query.setRawSql(rawSql)
            .where().gt("amount", 10);

    List<Values_Prop> list = query.findList();`

the problem that i get exception in this line .columnMapping("value ","Values_Prop.value")

error message : Execution exception [IllegalArgumentException: DB Column [value ] not found in mapping. Expecting one of [[DISTINCT, propriete_id]]]

its most likely that the keyword Distinct in my sql request is responsible for this conlict and i have no idea how to solve it ...

**Comment by marcospereira** [comment]
Hello @yokidara01,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

So I'm closing this.
