### ISSUE TITLE
When try to resolve playframework, some dependencies shows `Forbiden!`

### ISSUE THREAD

**Issue by scweang** [playframework/playframework#7281]
https://dl.bintray.com/sbt/sbt-plugin-releases/de.heikoseeberger/sbt-header/scala_2.10/sbt_0.13/1.8.0/ivys/ivy.xml

this file shows `Forbidden! ` that makes me cannot load code into Intellij Idea.

**Comment by ranchoiver** [comment]
@scweang Same, our CI can't build Play project, because Play sbt plugin ivy.xml is Forbidden.
Also this guy had similar problem: https://github.com/playframework/playframework/issues/7238

**Comment by olitazl** [comment]
It's working again!

**Comment by scweang** [comment]
Yeah...It seems that we can now download the dependencies. But how could this happen? It doesn't make any sense...

**Comment by marcospereira** [comment]
This could have been an issue with Bintray (this plugin is not even released by Play team). Right now it is working as expected:

```bash
curl -I https://dl.bintray.com/sbt/sbt-plugin-releases/de.heikoseeberger/sbt-header/scala_2.10/sbt_0.13/1.8.0/ivys/ivy.xml
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 27 Apr 2017 15:01:53 GMT
Content-Type: application/xml
Content-Length: 1611
Connection: keep-alive
Last-Modified: Mon, 20 Feb 2017 08:37:09 GMT
Accept-Ranges: none
ETag: 7f72f5083120443a3da4c0d023ba00e3786367cad55d19a4c4a997329e157388
X-Checksum-Sha1: 91275b7775e2d76b86145d9b10a5aa044bb4da3c
X-Checksum-Sha2: 7f72f5083120443a3da4c0d023ba00e3786367cad55d19a4c4a997329e157388
```
Bintray has a [status page](http://status.bintray.com/) but I'm not sure this will all appears there. Anyway, I'm closing this since there is nothing we can do regarding this failure specifically.
