### ISSUE TITLE
Missing page JavaHttpRequestHandlers in 2.5

### ISSUE THREAD

**Issue by dluc** [playframework/playframework#7303]
How to reproduce:

Visit https://www.playframework.com/documentation/2.4.x/JavaHttpRequestHandlers

Notice the message

> You are viewing the documentation for the 2.4.x release series. The latest stable release series is 2.5.x.

Click on "2.5.x." link

Result: 404 page not found

**Comment by benmccann** [comment]
The page is here in 2.5.x: https://www.playframework.com/documentation/2.5.x/JavaActionCreator

I'm not sure there's an easy solution to switching between versions when a page doesn't exist in another version. Would it be better to take you to the homepage in this instance?

**Comment by dluc** [comment]
hmm, I'm not too familiar with the framework rendering the documentation, would it be possible to redirect to a search page when the page doesn't exist?
I'm hitting other scenarios, and the number of broken links could grow easily in time.

e.g.
https://www.playframework.com/documentation/2.5.x/Samples doesn't exist (coming from https://www.playframework.com/documentation/2.0/Samples)

**Comment by gmethvin** [comment]
@dluc The code for the website is here: https://github.com/playframework/playframework.com (this issue should probably be moved there as well).

There is a search box at the top of the page. Would it be enough to just suggest to use that search (maybe pre-populate it with the search term). PRs are welcome of course.

**Comment by dluc** [comment]
I think the best user experience would be to automate the search, e.g. providing a solution to the user.

Closing issue here and moving to https://github.com/playframework/playframework.com/issues/146

Thanks
