### ISSUE TITLE
AssetsComponents not mentioned in migration guide

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#7304]
Upgrading a Scala compile time DI app using macwire to Play 2.6, I get the following compile error:

```
[info] [error] /tmp/sbt_a2dee40c/run-all-scaladsl/p/app/Loader.scala:27: Cannot find a value of type: [controllers.AssetsMetadata]
[info] [error]       lazy val assets = wire[controllers.Assets]
```

The migration guide doesn't have any mention of what needs to be modified to fix this.

The answer is, your application needs to extend AssetsComponents, and AssetsComponents provides the assets controller for you, so you don't need to wire it yourself (ie, most Scala apps should delete the above line of code that I had in my app).

**Comment by centaure** [comment]
Thanks @jroper!
