### ISSUE TITLE
Deprecated iteratees example in 2.5.x WebSockets documentation

### ISSUE THREAD

**Issue by vooolll** [playframework/playframework#7308]
Play Version (2.5.x)

API (Scala)

At page - https://www.playframework.com/documentation/2.5.x/ScalaWebSockets. There is matched deprecated API `Websocket.using`.

Сorrect me if I'm wrong, using Iteratee API with Websocket was deprecated in 2.5.x. So I guess heading "Handling WebSockets with iteratees" looks confusing. I think it should be replaced with more akka streams samples which recently appeared there https://www.playframework.com/documentation/2.6.x/ScalaWebSockets#handling-websockets-with-akka-streams-directly

**Comment by wsargent** [comment]
This is connected with https://github.com/playframework/playframework/issues/7325 and https://github.com/playframework/playframework/issues/7354

**Comment by marcospereira** [comment]
We are not maintaining 2.5.x anymore, so this documentation won't be fixed.
