### ISSUE TITLE
@With, Responses are mixed with Action composition

### ISSUE THREAD

**Issue by mrdavidhidalgo** [playframework/playframework#7314]
Hello,

I was working on an authentication project using the annotation @With, and I encountered a concurrency problem where the response was being mixed.

The controller has the following code:

```java
@With(AuthorizationAction.class)
public Result echo(final String id) {
    return Results.ok(id);
}
```

The class `AuthorizationAction` is:

```java
@Singleton
public class AuthorizationAction extends Action.Simple {
      @Override
      public CompletionStage<Result> call(Http.Context ctx) {
          return delegate.call(ctx);
      }
}
```

I am reporting the error because I think it is serious.
I'm using Java 1.8.0_65 and play 2.5.14

![1playbug](https://cloud.githubusercontent.com/assets/3289138/25823709/7f096f70-3402-11e7-8851-fa28cf789310.png)
![2playbug](https://cloud.githubusercontent.com/assets/3289138/25823710/7f124938-3402-11e7-8ba2-651b789837ab.png)

**Comment by marcospereira** [comment]
I don't understand what was the problem exactly. Were you expecting to see `7134c5f9-...` in the second screenshot? If so, can you:

1. Confirm that this is not happening when removing `@With`?
2. Create a small project that reproduces the problem?

Thanks.

**Comment by marcospereira** [comment]
@mrdavidhidalgo any news about this?

**Comment by gmethvin** [comment]
@mrdavidhidalgo My guess is that removing `@Singleton` will fix it.

We should probably clarify in docs that Java `Action`s must not be declared as singleton since we need to create a new instance for each usage.

**Comment by mrdavidhidalgo** [comment]
Hello, thank you very much, the annotation was removed and the error was corrected, thank you very much.
