### ISSUE TITLE
[doc]: Document how to schedule recurring tasks/jobs

### ISSUE THREAD

**Issue by marcospereira** [playframework/playframework#7322]
### API (Scala / Java / Neither / Both)

For both Scala and Java.

### Expected Behavior

We have documentation about how to schedule recurring tasks for both Scala and Java.

### Actual Behavior

We have minimal documentation here:

https://www.playframework.com/documentation/2.5.x/ScalaAkka#Scheduling-asynchronous-tasks

**Comment by wsargent** [comment]
Maybe a reference to https://github.com/tuxBurner/play-akkjobs

**Comment by wsargent** [comment]
Also, when it comes to sending email, I think using a job and https://eigengo.telegr.am/blog_posts/akka-extras-email is much better than using the play email sender from play-plugins...
