### ISSUE TITLE
[doc] Iteratee documentation does not reference migration

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#7325]
### Play Version (2.5.x / etc)

2.6.x

### API (Scala / Java / Neither / Both)

Scala / Java

### Expected Behavior

So, in 2.6.x we still have iteratees in the documentation, but there is no reference to how to install them or that they've been moved out to a different project:

* https://www.playframework.com/documentation/2.6.x/Iteratees
* https://www.playframework.com/documentation/2.6.x/Enumerators 

But in 2.5.x, Akka Streams was the primary motivator, and Iteratees have been moved out to another library:

https://github.com/playframework/play-iteratees

There is a brief note in the README of play-iteratees that says:

> If you are using Play 2.6.x or higher and are looking for Streams class, you can find it under:
> https://github.com/playframework/play-iteratees/blob/master/streams/src/main/scala/play/api/libs/iteratee/streams/IterateeStreams.scala

And there is a section in the Migration Guide:

https://www.playframework.com/documentation/2.6.x/Migration26#Play-Iteratees-moved-to-separate-project

So the migration guide should be referenced from the main pages, and the Iteratees section should reference Akka Streams.

**Comment by marcospereira** [comment]
Given how the other standalone projects are structured, we need to move Iteratees docs to its standalone project. Of course, this could be another issue.
