### ISSUE TITLE
Should be easier to create custom Messages/MessagesApi

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#7333]
We could probably provide default method implementations for most of the methods that delegate, so it's harder to mess up a custom impl. This is already much better than in 2.5.x but could be easier.

**Comment by wsargent** [comment]
Is this about breaking down `DefaultMessagesApi`, or overriding `MessagesImpl`?  What custom implementation are we looking at?

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/i18n/Messages.scala#L409

**Comment by gmethvin** [comment]
Actually, I was just thinking of what you would do in the simple case if I wanted to create a simple pass-through Messages implementation, or a mock implementation for testing or prototyping.

If something takes an `implicit Messages` and I want to provide my own implementation, it would be simpler if there weren't three different translation methods to implement. If I create a `MessagesImpl`, I still have to pass (and implement) `MessagesApi`. I think we could improve things by just providing implementations in the trait.

**Comment by wsargent** [comment]
You'd probably want to replace or extend `DefaultMessagesApi` rather than `MessagesImpl` -- `MessagesImpl` is the intersection of `MessagesApi` and `Lang` and so doesn't do much in itself.

**Comment by wsargent** [comment]
You can see the defaults and testing in `MessagesSpec`:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/scala/play/api/i18n/MessagesSpec.scala#L15

**Comment by gmethvin** [comment]
> You'd probably want to replace or extend DefaultMessagesApi rather than MessagesImpl -- MessagesImpl is the intersection of MessagesApi and Lang and so doesn't do much in itself.

I thought the reason many of the template helpers use `Messages` is because it only needs a specific set of messages for a specific language. So you'd want to mock `Messages` when testing something that renders a UI, not `MessagesApi`.

**Comment by wsargent** [comment]
You don't need to mock anything for template helpers though -- you can pass in `messages` and everything else will default:

```scala
val testMessages = Map(
    "default" -> Map(
      "title" -> "English Title",
      "foo" -> "English foo",
      "bar" -> "English pub")
)
val messagesApi = new DefaultMessagesApi(testMessages)
val messages = messagesApi.preferred(FakeRequest("GET", "/"))
```

See https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/i18n/Messages.scala#L409

**Comment by wsargent** [comment]
Yeah, this is already docced (in specs2 at least):

https://www.playframework.com/documentation/2.6.x/ScalaTestingWithSpecs2#Unit-Testing-Forms

```
To unit test form processing and render validation errors, you will want a MessagesApi instance in implicit scope. The default implementation of MessagesApi is DefaultMessagesApi. For unit testing purposes, DefaultMessagesApi can be instantiated without arguments, and will take a raw map.
```

**Comment by wsargent** [comment]
Also addressed by https://github.com/playframework/playframework/pull/7457
