### ISSUE TITLE
AkkaHttpServer has hardcoded frame size for WebSockets

### ISSUE THREAD

**Issue by ajrnz** [playframework/playframework#7335]
### Play Version
2.5.14 (with AkkaHttpServer)

### OS
Ubuntu 16.04 & Windows 10

`WebSocketHandler` has a parameter for `bufferSize` which sets the max payload size for a websocket frame but this is hardcoded to 16384 in `AkkaHttpServer`

        websocket(taggedRequestHeader).flatMap {
          case Left(result) =>
            modelConversion.convertResult(taggedRequestHeader, result, request.protocol, errorHandler)
          case Right(flow) =>
            Future.successful(WebSocketHandler.handleWebSocket(upgrade, flow, 16384))
        }

could this be made to respect `play.websocket.buffer.limit`?

16k seems small for some use cases

**Comment by marcospereira** [comment]
Thank you @ajrnz. Please see #7337.

**Comment by ajrnz** [comment]
Wow. Great. Thanks @marcospereira
