### ISSUE TITLE
How to integrate Spring Boot in Play

### ISSUE THREAD

**Issue by raderio** [playframework/playframework#7342]
http://stackoverflow.com/questions/43980669/integrate-spring-boot-in-play-framework

**Comment by marcospereira** [comment]
Hello @raderio,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

I would also recommend to take a look at both [this sample application](https://github.com/daxyonis/play25-java-spring) and [play-spring-loader](https://github.com/remithieblin/play-spring-loader). While these aren't official documentation or modules, they can for sure help you get started with this integration.
