### ISSUE TITLE
Slack channel for Play

### ISSUE THREAD

**Issue by raderio** [playframework/playframework#7343]
Is there Slack channel about Play?

**Comment by hagl** [comment]
There is gitter room: https://gitter.im/playframework/playframework

**Comment by raderio** [comment]
I think it will be good to add an icon on index page https://playframework.com/ besides email, twitter, github, ...

**Comment by wsargent** [comment]
If you look on https://playframework.com/ you can see "Chat on Gitter's Play Channel" as the button on the right.
