### ISSUE TITLE
[doc]: move iteratee documentation to the standalone project

### ISSUE THREAD

**Issue by marcospereira** [playframework/playframework#7354]
This is a follow up to issue #7325.

The iteratee docs should be part of play-iteratees standalone project. We need to move the following files: https://github.com/playframework/playframework/tree/master/documentation/manual/working/scalaGuide/advanced/iteratees

The complete work requires:

- [ ] A pull request in play-iteratees to add the docs
- [ ] A pull request here to remove the docs
- [ ] A pull request to add play-iteratees to playframework/omnidoc.

**Comment by RichardMarto** [comment]
Hi, I just found that [play-iteratees](https://github.com/playframework/play-iteratees) has reached End of Life and this issue is from 2017, help is still needed?

**Comment by marcospereira** [comment]
Hey @RichardMarto, you are right and this is not relevant anymore. Thanks for the heads up. :-)
