### ISSUE TITLE
Can I put the encrypt DB password on application.conf?

### ISSUE THREAD

**Issue by nuboat** [playframework/playframework#7361]
### Are you looking for help?
I got the requirement that cannot show plain password in config file. So, Can I put the encrypt DB password on application.conf?  

BTW, I used simple Play JDBC.

### Play Version (2.5.x / etc)
2.5.14

### API (Scala / Java / Neither / Both)
Scala

**Comment by wsargent** [comment]
This is not a bug tracker.  Please ask on the mailing list or on Gitter.im.
