### ISSUE TITLE
Migration from Play 2.4.6 to Play 2.5.9 

### ISSUE THREAD

**Issue by rohitlf** [playframework/playframework#7362]
I am trying to migrate Play 2.4.6 to Play 2.5.9. I am using this seed template
https://github.com/mariussoutier/play-angular-require-seed

I am facing issues with Evolutions. When I start the server. its trying to apply all SQL files downs and then Ups

What seems to be going wrong with Play 2.5.9. Earlier I had tried migrating to 2.5.14 and there were hell lot of memory leak and threads getting creating. http://stackoverflow.com/questions/43897212/play-scala-slick-3-0-connection-pool-issue-play-2-4-vs-play-2-5-issues

My dependancies build.sbt file looks like below

libraryDependencies ++= Seq(
  filters,
  cache,
  ws,
  specs2 % Test,
  evolutions,
  // WebJars (i.e. client-side) dependencies
  "org.webjars" % "requirejs" % "2.3.2",
  "org.webjars" % "underscorejs" % "1.8.3",
  "org.webjars" % "jquery" % "1.12.4",
  "org.webjars" % "bootstrap" % "3.3.7-1" exclude("org.webjars", "jquery"),
  "org.webjars" % "angularjs" % "1.4.10" exclude("org.webjars", "jquery"),
  "com.typesafe.play" %% "play-slick" % "2.0.2",
  "com.typesafe.play" %% "play-slick-evolutions" % "2.0.2",
//  "com.typesafe.slick" % "slick_2.11" % "3.2.0",
  "com.typesafe.play" % "play-mailer_2.11" % "5.0.0",
  "org.postgresql" % "postgresql" % "42.1.1",
  "com.github.nscala-time" % "nscala-time_2.11" % "2.16.0",
  "org.scalatest" % "scalatest_2.11" % "3.0.3",
  "org.specs2" % "specs2-matcher-extra_2.11" % "3.8.9" % "test",
  "org.apache.httpcomponents" % "httpcore" % "4.4.6",
  "org.apache.httpcomponents" % "httpclient" % "4.5.3",
  "com.amazonaws" % "aws-java-sdk-s3" % "1.11.117",
  "ai.api" % "libai" % "1.4.8",
  "org.apache.poi" % "poi" % "3.16",
  "org.apache.poi" % "poi-ooxml" % "3.16",
  "org.apache.poi" % "poi-ooxml-schemas" % "3.16",
  "commons-io" % "commons-io" % "2.5"
)

**Comment by wsargent** [comment]
Hi @rohitlf -- this is a bug tracker, so it's not meant for answering questions about applications.  Please ask on the mailing list.

**Comment by rohitlf** [comment]
@wsargent Hi Will, I am not finding any solution to this memory leak issues which I am facing. This is a bug not some application related. I would appreciate, if you can give it a thought. 

Many Thanks.

**Comment by rohitlf** [comment]
<img width="752" alt="screen shot 2017-07-13 at 4 07 55 pm" src="https://user-images.githubusercontent.com/24771677/28162661-7fd1bde2-67e5-11e7-943a-96bff3480a36.png">

**Comment by rohitlf** [comment]
<img width="771" alt="screen shot 2017-07-13 at 4 12 03 pm" src="https://user-images.githubusercontent.com/24771677/28162831-1be98412-67e6-11e7-8397-c17db7ff16b4.png">

**Comment by marcospereira** [comment]
Hi @rohitlf, 

Could you please provide a sample project that reproduces this problem?

Thanks.

**Comment by rohitlf** [comment]
Hi @marcospereira I will surely provide you workspace during weekend. Thanks.

**Comment by rohitlf** [comment]
[Submit.zip](https://github.com/playframework/playframework/files/1150380/Submit.zip)

Hi @marcospereira and @wsargent I am uploading sample workspace. I have removed most of the code and also the loading angular components from assets is also removed.

Please check and let me know if everything is fine?

**Comment by richdougherty** [comment]
Thanks for that. Can you describe what steps to take to reproduce the problem (e.g. what commands you run, what URLs you request, what you click in the browser) and also what problems you see (e.g. error messages, invalid database state). The more specific the test script and error description you provide the better, because it makes it much easier for us to home in on the problem if we can find it. :)

**Comment by rohitlf** [comment]
There are two api i created for
/users  it list all users from db
and 
/add it add random 100000 around records in db.

I will also share you the video of my live project which exactly depict the thread memory leak issue.

**Comment by rohitlf** [comment]
I am attaching the below where you can download videos of the same.


https://wetransfer.com/downloads/56d1367cbcf10538fe06b857610bbb3520170718054655/98c877ab6988b45b82fc4ea205036f7b20170718054655/738f74?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email


If you look at the task monitor then you can see the thread issue which I am talking about. 

All those html files, scripts are loaded  are loaded usings Assets code logic.

Please let me know if you need anything else?

**Comment by rohitlf** [comment]
Previous link might have been deleted by now. Here is the new one.
https://wetransfer.com/downloads/803b3adc226510f82895d53cc9cf5a7520170725115017/06bb50
