### ISSUE TITLE
[doc] Play 2.6 migration missing mention to new akka-http request timeout 

### ISSUE THREAD

**Issue by mrucci** [playframework/playframework#7364]
### Play Version 2.6

The [Play 2.6 migration guide](https://www.playframework.com/documentation/2.6.x/Migration26) is missing a mention to the new configuration parameter `akka.http.server.request-timeout`.

When the configuration parameter is not set, it defaults to 20 second, that is a different (i.e. backward incompatible) default request timeout than with Play 2.5.  Not sure what was the old default value, but definitely > 60 seconds.

Diagnosing the issue was a bit confusing because when the HTTP response is returned by akka-http, it bypasses our Play `LoggingFilter`... but that's probably out of topic.

**Comment by marcospereira** [comment]
Closed by #7463.
