### ISSUE TITLE
Named SyncCacheApi or CacheApi use the same default underlying cache instead of named

### ISSUE THREAD

**Issue by checat** [playframework/playframework#7401]
### Play Version
2.6.0-RC1 (other versions were not tested)

### API
Java

### Operating System
Windows 10

### JDK
Oracle
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### Library Dependencies

scalaVersion := "2.11.8"
libraryDependencies += guice
libraryDependencies += ehcache
libraryDependencies += "com.typesafe.play" %% "play-test" % "2.6.0-RC1" % "it,test"

### Expected Behavior

In this code
```
    @Inject
    @NamedCache("session-cache")
    SyncCacheApi syncCache;

    @Inject
    SyncCacheApi defaultSyncCache;
```
2 variables should reference different caches.

### Actual Behavior

Both vars internally refer to the same AsyncCacheApi instance and so the same EHCache instance (it's name is seen in the debugger as "play").

The same problem was found with `CacheApi`. There is no such problem with `AsyncCacheApi`.

### Reproducible Test Case

https://gist.github.com/checat/b935c7e20e4742c66d892ee964756f95

log statement prints identical values for underlying AsyncCacheApi objects like
`play.cache.DefaultAsyncCacheApi@4c415271 play.cache.DefaultAsyncCacheApi@4c415271`

**Comment by gmethvin** [comment]
@checat Thanks for reporting this. The issue was pretty obvious: we were binding to the default cache instead of the named cache for `CacheApi` and `SyncCacheApi`. This should be fixed by #7403.
