### ISSUE TITLE
Remove JavaConversions from TemplateImports

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#7406]
https://github.com/playframework/playframework/blob/2.6.0-RC1/framework/src/build-link/src/main/java/play/TemplateImports.java#L31

Its deprecated since Scala 2.12.

See https://github.com/playframework/playframework/pull/6559#issuecomment-305769447

**Comment by gmethvin** [comment]
@mkurz I think we should remove this import, but it might not be as simple as just removing it.

Many of the template helpers require Scala types. I think the original reason for adding that import was to make the experience relatively seamless for Java users. If you removed the implicit conversion, Java users would probably have to use `JavaConverters` and call `javaList.asScala`. I'm worried it would make the templates feel more foreign to Java users.

Perhaps we could solve this problem just by providing alternate constructors for helpers using Java types. Either way, some thought should be put into the user experience and the migration requirements.
