### ISSUE TITLE
DefaultHttpErrorHandler should expose throwableToUsefulException method as protected scope

### ISSUE THREAD

**Issue by velabits** [playframework/playframework#7417]
### Are you looking for help?
No. Filing an enhancement request.

### Play Version (2.5.x / etc)
2.5.x and master
### API (Scala / Java / Neither / Both)
Java
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
All
### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
1.8
### Library Dependencies
None

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Extend DefaultHttpErrorHandler.java class for custom error handler.
2. Want to use logServerError method of the super, which takes an UsefulException type. 
3. Want to use the super's utility method throwableToUsefulException to convert it. 

### Actual Behavior

1. Extended DefaultHttpErrorHandler.java class for custom error handler.
2. Wanted to use logServerError method of the super, which takes an UsefulException type. 
3. Wanted to use the super's utility method throwableToUsefulException to convert it. Since it's defined as "private" scope, I had to reimplement(copy and paste) this in my custom error handler class.

### Reproducible Test Case
n/a. This is an enhancement.

**Comment by richdougherty** [comment]
Sounds like a good idea to me. Alternatively we could change the `logServerError` method to accept a `Throwable` and then convert it to a `UsefulException` if needed. Either approach is probably fine.

**Comment by ahsanbagwan** [comment]
Working on this.
