### ISSUE TITLE
[2.6.x] play.server.websocket.frame.maxLength ignored in application.conf

### ISSUE THREAD

**Issue by ptc-cprodan** [playframework/playframework#7428]
### Play Version (2.5.x / etc)

2.6.x

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux  4.8.0-54-generic #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Made a basic application with a controller that responds to websocket requests: https://github.com/christian/play-websocket-test. 
2. Set the property `play.server.websocket.frame.maxLength = 1024k` (1Mb). I expect the controller to accept frames of size 123Kb. 

### Actual Behavior

Upon sending frames of size ~130K the play application responds with websocket code 1009 (which indicates that the frame is too big).  
I added a log line after this line https://github.com/playframework/playframework/blob/master/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L236 in the play code itself to debug, and the max limit seems to be 64k. 
The funny thing is that starting the application with `-Dwebsocket.frame.maxLength=1024k` does overwrite the max length. 

### Reproducible Test Case

The project which reproduces this can be found here: https://github.com/christian/play-websocket-test
The client is also in the project, in Ruby though https://github.com/christian/play-websocket-test/blob/master/client.rb.

**Comment by djx314** [comment]
Will it work by setting `-Dplay.server.websocket.frame.maxLength=1024k`  in `sbt.bat` as a java -jar parmeter?

**Comment by ptc-cprodan** [comment]
I use it on linux so no `sbt.bat`. This appears to work:

    sbt -Dplay.server.websocket.frame.maxLength=1024k "run 9002"

**Comment by gmethvin** [comment]
I'm assuming this is failing only in dev mode, which is expected. There is already a note about this here: https://www.playframework.com/documentation/2.6.x/SettingsAkkaHttp

If you are able to reproduce in a production app (e.g. `sbt start`) please reopen this issue.

**Comment by akkie** [comment]
As a note. It's also possible to set it in your build file:

```scala
javaOptions in run += "-Dplay.server.websocket.frame.maxLength=1024k"
```
