### ISSUE TITLE
[Bug] SameSite cookie attribute doesn't get set

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#7432]
Neither does the`SameSite` attribute get set on the session cookie nor on a custom cookie like
```
response().setCookie(Cookie.builder("color", "blue").withSameSite(SameSite.LAX).build());
```
Tested with play-java v2.6.0-RC2

**Comment by mkurz** [comment]
I tested with latest Chrome. I am sure it's a Play bug because I also tested the SameSite attribute with this nodejs script:
```
const http = require('http')
const port = 3000

const requestHandler = (request, response) => {
  response.writeHead(200, {
    'Set-Cookie': 'color=blue; SameSite=lax'
  });
  console.log(request.url)
  response.end('Hello World!')
}

const server = http.createServer(requestHandler)

server.listen(port, (err) => {
  console.log(`server is listening on ${port}`)
})
```
In this case the attribute gets set and I can see it in the Chrome developer tools under the response headers as well as in the list of cookies.

**Comment by marcospereira** [comment]
This is happening only for the Java API. See #7433 for a fix.
