### ISSUE TITLE
[2.5.x] WSRequest.setQueryString does not parse encoded content correctly

### ISSUE THREAD

**Issue by dexjq23** [playframework/playframework#7444]
### Are you looking for help?

No

### Play Version (2.5.x / etc)

2.5.x (more specifically, 2.5.15)

### API (Scala / Java / Neither / Both)

Java / `play.libs.ws.WSAPI.url(String)`

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

<pre>
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
</pre>

### Library Dependencies

Not involved

### Expected Behavior

1. Pass a URL with "=" encoded in the query string, e.g. `http://example.org/foo?bar=F%3Dma` .
2. Call .get() to obtain an instance of WSRequest .

### Actual Behavior

1. Pass a URL with "=" encoded in the query string, e.g. `http://example.org/foo?bar=F%3Dma` .
2. API throws RuntimeException, caused by `java.net.MalformedURLException: QueryString parameter should not have more than 2 = per part`.

```
[error] Test test.JavaWSUnexpectedMalformedURLTest.testGetExampleUrlWithEncodedEq failed: java.lang.RuntimeException: java.net.MalformedURLException: QueryString parameter should not have more than 2 = per part, took 1.896 sec
[error]     at play.libs.ws.ahc.AhcWSRequest.setQueryString(AhcWSRequest.java:106)
[error]     at play.libs.ws.ahc.AhcWSRequest.<init>(AhcWSRequest.java:78)
[error]     at play.libs.ws.ahc.AhcWSClient.url(AhcWSClient.java:38)
[error]     at play.libs.ws.ahc.AhcWSAPI.url(AhcWSAPI.java:44)
[error]     at test.JavaWSUnexpectedMalformedURLTest.testGetExampleUrlWithEncodedEq(JavaWSUnexpectedMalformedURLTest.java:31)
[error]     ...
[error] Caused by: java.net.MalformedURLException: QueryString parameter should not have more than 2 = per part
[error]     ... 41 more
```

### Reproducible Test Case

Here is a JUnit test case under  2.5.15 project (generated from g8 seed):
```java
package test;

import static org.junit.Assert.assertNotNull;

import org.junit.Before;
import org.junit.Test;

import play.libs.ws.WSAPI;
import play.test.WithApplication;

public class JavaWSUnexpectedMalformedURLTest extends WithApplication {

  private static final String EXAMPLE_URL = "http://example.org/foo?bar=Fma";

  private static final String EXAMPLE_URL_WITH_ENCODED_EQ  = "http://example.org/foo?bar=F%3Dma";

  private WSAPI ws;

  @Before
  public void setup() {
    this.ws = app.injector().instanceOf(WSAPI.class);
  }

  @Test
  public void testGetExampleUrl() {
    assertNotNull(ws.url(EXAMPLE_URL).get());
  }

  @Test
  public void testGetExampleUrlWithEncodedEq() {
    assertNotNull(ws.url(EXAMPLE_URL_WITH_ENCODED_EQ).get()); /* Always fails at this line */
  }
}
```

**Comment by wsargent** [comment]
A malformed URL is not an error in WS -- it's an error in the input.  Please parse the URL with a URL checker, such as http://galimatias.mola.io/ or https://github.com/palominolabs/url-builder before passing it to Play-WS.

**Comment by wsargent** [comment]
This is completely WS's fault.

```

    @Override
    public StandaloneAhcWSRequest setQueryString(String query) {
        String[] params = query.split("&");
        for (String param : params) {
            String[] keyValue = param.split("=");
            if (keyValue.length > 2) {
                throw new RuntimeException(new MalformedURLException("QueryString parameter should not have more than 2 = per part"));
            } else if (keyValue.length == 2) {
                this.addQueryParameter(keyValue[0], keyValue[1]);
            } else if (keyValue.length == 1 && param.charAt(0) != '=') {
                this.addQueryParameter(keyValue[0], null);
            } else {
                throw new RuntimeException(new MalformedURLException("QueryString part should not start with an = and not be empty"));
            }
        }
        return this;
    }
```

**Comment by gmethvin** [comment]
I think `setQueryString` should probably take a raw query string (with encoded values).

**Comment by wsargent** [comment]
It actually does -- the problem here is that the URL string is decoded by URI.create() in the constructor.

**Comment by wsargent** [comment]
Fixed in play-ws for 2.6.x.  I'll put together a 2.5.x fix as well...

**Comment by marcospereira** [comment]
Reopening to be closed when we fix it for 2.5.x.

**Comment by marcospereira** [comment]
Closed by #7469.

**Comment by Erwyn** [comment]
Do we have an estimation on when this fix will be released?

**Comment by marcospereira** [comment]
@Erwyn no, it is not part of 2.5.15. We are planning to do a new release this week. :-)

**Comment by Erwyn** [comment]
okay thanks :) !

**Comment by Erwyn** [comment]
Hello again! Sorry to disturb, but while I wait for the release of the 2.5.x is there a way to tell sbt to use the dev branch so that I can check if the fix fixes my issue? Thanks

**Comment by marcospereira** [comment]
@Erwyn, you can publish locally. Just follow the steps below:

1. Clone the repository
2. Change to 2.5.x branch
3. Edit framework/version.sbt file as you wish (for example, change version to "2.5.16-Local")
4. `cd` to framework dir
5. Run `sbt publishLocal`.

You can then use this version in your project.

**Comment by Erwyn** [comment]
Super thanks, I'll be able to check this way.

**Comment by rakeshhny** [comment]
I was facing the same problem with Playframework 2.5.13.

Updated locally to version 2.5.16 and the query string parameter error is not occurring now.

However, I cannot right away change the framework version.

How can I workaround this problem in current version i.e. 2.5.13

**Comment by marcospereira** [comment]
Hey @rakeshhny,

2.5.16 is fully binary compatible with 2.5.13. I would say that updating is easier than trying a workaround.
