### ISSUE TITLE
Get list of all Route URL strings in play framework

### ISSUE THREAD

**Issue by sagargit2** [playframework/playframework#7460]
I have many controllers in my **play-scala 2.4.x application**.

I want to get a `list of all route URLs` pointing their respective controllers. I know how to get the URL from the current request. But I need a list of all the URLs available inside a play application.I want to generate this list dynamically because `URLs can be changed/added/deleted` in future.

_So,is there some way I can generate this URL list dynamically ? Or do I have to store all the URLs statically somewhere in cache or dictionary ?_

**Comment by marcospereira** [comment]
Hi @sagargit2,

I think you are looking for [`play.api.routing.Router`](https://github.com/playframework/playframework/blob/2.4.x/framework/src/play/src/main/scala/play/api/routing/Router.scala). See the `documentation` method.

Moreover, the [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

Best.
