### ISSUE TITLE
localhost:9000 redirects to https://localhost

### ISSUE THREAD

**Issue by PromanSEW** [playframework/playframework#7487]
### Play Version (2.5.x / etc)

2.6.0

### API (Scala / Java / Neither / Both)

Maybe both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

macOS 10.12.5

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

### Library Dependencies

None

### Expected Behavior

1. Run project in dev mode
2. Open `localhost:9000`
3. See index page

### Actual Behavior

1. Run project in dev mode
2. Open `localhost:9000`
3. See failed `308 Permanent Redirect` to `https://localhost`

### Reproducible Test Case

1. Download this minimal Play Java project
https://github.com/PromanSEW/play-java-starter-example_2.6.x
2. See Actual Behavior steps

**Comment by PromanSEW** [comment]
Hmm... I removed this filter, and I still see redirect

**Comment by marcospereira** [comment]
Hi @PromanSEW, do you have `play.filters.https.port` configured? It should defaults to `play.server.https.port` (which defaults to `-Dhttps.port`).

Which starter project did you download? How did you add the `RedirectHttpsFilter` (it is not part of the default filters)?

**Comment by PromanSEW** [comment]
@marcospereira no, I didn't configure `play.filters.https.port`
I added `RedirectHttpsFilter`, while migrating, and try to open `localhost:9000` and see redirect to `https://localhost`. When I removed `RedirectHttpsFilter` from enabled filters and reload project nothing changed. Still redirect.
I downloaded `play-java-starter-project` after I found that my project is not working.
Then, I changed SBT plugin to 2.6.0 and run. I saw the same redirect...

**Comment by marcospereira** [comment]
@PromanSEW thanks for the information.

Could you please confirm that after configuring `play.filters.https.port` the redirect is working as expected? Also, please, run a `sbt clean` to ensure that previous compilations aren't interfering here.

**Comment by PromanSEW** [comment]
@marcospereira how to configure this setting for dev mode and production on Heroku?
I added
```scala
devSettings += ("play.filters.https.port", "9000")
```
But nothing changed

**Comment by marcospereira** [comment]
Hi @PromanSEW, it is a Play configuration, not a sbt one.

You need to add the following line to your `conf/application.conf`:

```
play.filters.https.port = 9443
```

See more details here: https://www.playframework.com/documentation/2.6.x/RedirectHttpsFilter#Custom-HTTPS-Port

I don't know exactly how Heroku works, but it usually defines configurations using environment variables, correct? If so, you can define the configuration above like:

```
play.filters.https.port = 9443
play.filters.https.port = ${?NAME_OF_ENV_VAR_IN_HEROKU_THAT_DEFINES_HTTPS_PORT}
```

Please, confirm that you can use this locally. If not, it would be good to have a small project that reproduces the problem (preferably shared via a Github repository).

**Comment by PromanSEW** [comment]
@marcospereira I added
```
play.filters.https.port = 9443
```
but nothing changed.
Here is minimal Java project without any dependencies or features enabled:
https://github.com/PromanSEW/play-java-starter-example_2.6.x

**Comment by marcospereira** [comment]
@PromanSEW this project does not even have the `RedirectHttpsFilter` enabled, so it shouldn't be doing any redirect at all. It also does not compile. 

Finally, I think the [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

Closing this.

**Comment by PromanSEW** [comment]
I found the root of problem. My Firefox 53.0.3 redirected before update to 54.0
I try Safari, and it doesn't redirect too.
It is very strange...
Thanks for support

**Comment by PromanSEW** [comment]
@marcospereira I fixed my test project and added
```
play.filters.enabled += play.filters.https.RedirectHttpsFilter
play.filters.https.port = 9443
```
to `application.conf` and now it redirects to https://localhost:9443 with connection error
Please look sample project again

**Comment by PromanSEW** [comment]
I want to test my project in Firefox, but I can't. I don't want use Safari only for testing because my favourite browser is Firefox.

**Comment by mkurz** [comment]
Maybe this is because you once sent the `Strict-Transport-Security` header:
https://github.com/playframework/playframework/blob/2.6.x/framework/src/play-filters-helpers/src/main/resources/reference.conf#L201-L206
?
As soon as you send the header once the browser itself (not play anymore) will always redirect from http to https until `max-age` (which is a year by default).
Try to clean the whole (app) cache of your firefox browser for localhost:9000 and try again (so the browser forgets about STS setting for this url).

**Comment by PromanSEW** [comment]
@mkurz I perform "Remember this site" for localhost in Firefox, but nothing changed
I read this instruction:
https://www.thesslstore.com/blog/clear-hsts-settings-chrome-firefox/

**Comment by mkurz** [comment]
Please check with Chrome: Go to chrome://net-internals/#hsts and query for "localhost:9000"  and "localhost". If there is "Not found displayed" the browser is ok.

Also try running `wget localhost:9000` from the console and see if that redirects too.

**Comment by PromanSEW** [comment]
@mkurz I run wget:
```
MacBook-Pro-Roman:~ roman$  wget localhost:9000
--2017-06-24 01:58:22--  http://localhost:9000/
Распознаётся localhost (localhost)… ::1, 127.0.0.1
Подключение к localhost (localhost)|::1|:9000... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 308 Permanent Redirect
2017-06-24 01:58:22 ОШИБКА 308: Permanent Redirect.
```
I think you see redirect error without translation from Russian to English

**Comment by mkurz** [comment]
I don't have more time right now to look into this.
Maybe you can just push your project to a github repo to make it easier to reproduce?

**Comment by PromanSEW** [comment]
@mkurz actual project link in issue header:
https://github.com/PromanSEW/play-java-starter-example_2.6.x

**Comment by wsargent** [comment]
90% sure it's the browser remembering the `Strict-Transport-Security` header.  Try using an anonymous Chrome profile and see if it still occurs.

**Comment by PromanSEW** [comment]
@wsargent wget also displays 308 Permanent Redirect. See log above

**Comment by wsargent** [comment]
So here's my sequence of events:

```
git clone git@github.com:PromanSEW/play-java-starter-example_2.6.x.git
cd play-java-starter-example_2.6.x
sbt stage
cd target/universal/stage
bin/play-java -Dplay.http.secret.key=derp -Dhttps.port=9443
```

And then in another window, using httpie:

```
http --verify=no https://localhost:9443
```

results in 

```
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
HTTP/1.1 200 OK
Content-Length: 344
Content-Security-Policy: default-src 'self'
Content-Type: text/html; charset=utf-8
Date: Fri, 23 Jun 2017 19:18:23 GMT
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Permitted-Cross-Domain-Policies: master-only
X-XSS-Protection: 1; mode=block

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Welcome to Play</title>
        <link rel="stylesheet" media="screen" href="/assets/stylesheets/main.css">
        <link rel="shortcut icon" type="image/png" href="/assets/images/favicon.png">
    </head>
    <body>
        
    Your new application is ready.

    </body>
</html>
```

**Comment by wsargent** [comment]
Wait -- the bug is that RedirectHttpsFilter redirects you to the HTTPS port?  That's exactly what it's supposed to.

**Comment by PromanSEW** [comment]
@wsargent how to fix this behavior for dev mode but still working well in production?

**Comment by marcospereira** [comment]
@PromanSEW you can have separated configuration files, one `conf/application.conf` with all you need for dev environment and `conf/production.conf` for prod. Your `production.conf` would look like:

```HOCON
include "application.conf"

play.filters.enabled += play.filters.https.RedirectHttpsFilter
play.filters.https.port = 9443

// any other configuration that is required only for production
```
You can then start your application in production like described here: https://www.playframework.com/documentation/2.6.x/ProductionConfiguration

**Comment by PromanSEW** [comment]
@marcospereira thanks for solution.
But I think it will be more conveniently if this filter is ignored in dev mode.
Please note in docs that it must be enabled only in production configuration
