### ISSUE TITLE
Link in Migration26.md is bad

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#7489]
Starting with Play 2.6, query string parameters will not be bound to a form instance anymore when using bindFromRequest()(implicitrequest:play.api.mvc.Request[_]):play.api.data.Form[T]) in combination with POST, PUT or PATCH requests.

https://www.playframework.com/documentation/2.6.x/Migration26#Form-changes

**Comment by benmccann** [comment]
This looks like it might be fixed by https://github.com/playframework/playframework/pull/7486

**Comment by PromanSEW** [comment]
If it was fixed so this issue can be closed
