### ISSUE TITLE
Missing CSRFFilter logging XML in Migration26.md 

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#7490]
"To check this behavior, please add to your logback.xml"

Missing the XML because it has angle brackets.

https://www.playframework.com/documentation/2.6.x/Migration26#What-changes-do-I-need-to-make?

**Comment by benmccann** [comment]
This is fixed by https://github.com/playframework/playframework/pull/7486

**Comment by marcospereira** [comment]
Will close this after #7503.

**Comment by marcospereira** [comment]
Closed by #7503.
