### ISSUE TITLE
Max-Age for Java Cookie cannot be null

### ISSUE THREAD

**Issue by wjtan** [playframework/playframework#7491]
### Play Version (2.5.x / etc)
2.6.0

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle 1.8.0_131

### Expected Behavior

When max-age for Java Cookie is not set, it should return as a transient cookie.

### Actual Behavior

The max-age for Cookie is returned as 0 instead of none.

When converting from Java Cookie to Scala Cookie:
https://github.com/playframework/playframework/blob/fdbe6432a2f21cedb6eda1145dba9ff09214b31b/framework/src/play/src/main/java/play/mvc/Http.java#L2321

`OptionalInt optMaxAge = OptionalInt.of(Optional.ofNullable(maxAge()).orElse(0));`

When `maxAge()` is null, it will return 0 instead.

**Comment by gmethvin** [comment]
@wjtan Thanks for reporting. See #7496

**Comment by richdougherty** [comment]
@wjtan This issue is now fixed in Play 2.6.1 if you want to test it out.

**Comment by wjtan** [comment]
Yes, it's working fine now. Thanks!

**Comment by richdougherty** [comment]
Thanks for checking and glad to hear it's working. :)
