### ISSUE TITLE
Ignore RedirectHttpsFilter in dev mode

### ISSUE THREAD

**Issue by PromanSEW** [playframework/playframework#7492]
See related discussion in #7487

### Expected Implementation

As described in
https://www.playframework.com/documentation/2.6.x/RedirectHttpsFilter#enabling-the-https-filter

1. Add
```scala
play.filters.enabled += play.filters.https.RedirectHttpsFilter
```
to `application.conf`
2. Run in dev mode
3. Open `localhost:9000`
4. `RedirectHttpsFilter` is ignored and you see non-redirected page

### Actual Implementation

Use separate configurations for dev and production mode:
```scala
# production.conf
include "application.conf"
play.filters.enabled += play.filters.https.RedirectHttpsFilter
```

It is not described in `RedirectHttpsFilter` documentation.
Users don't know why adding this line breaks dev mode, because there is this sentence in documentation:
> This header is only enabled in production, since HSTS can cause problems in development by forcing the browser to always assume https://localhost:9000 for the application – this is especially an issue when working with multiple projects.

so it means `RedirectHttpsFilter` can be added in dev mode.

I propose to update documentation or fix `RedirectHttpsFilter` so it will be really ignored in dev mode.

**Comment by gmethvin** [comment]
This isn't strictly a dev/prod issue. It happens when the HTTPS server is running on any non-default port.

If the Play app responsible for serving both HTTP and HTTPS and doing the proper redirection, you would probably want to test that in dev mode, wouldn't you? Perhaps the better thing to do is document how to make sure it works in dev mode. In general, we try to make sure equivalent functionality is provided in dev mode, except for things like error messages, which are more verbose in dev mode for obvious reasons.

If your TLS termination is handled by a reverse proxy like nginx or HAProxy, it would make more sense to handle the redirection there instead of in Play, so this filter shouldn't be applied.

**Comment by PromanSEW** [comment]
Documentation for `RedirectHttpsFilter` needs additional notes for dev mode anyway.
I use Heroku for production, and I want to use `RedirectHttpsFilter` only for redirecting all `http://` requests to `https://` scheme, so Heroku provides free default SSL certificate.
But I don't want to test `RedirectHttpsFilter` in dev mode, I want it was ignored so I can freely testing on `http://localhost:9000` without any redirects

**Comment by gmethvin** [comment]
It's weird that HSTS is only enabled in prod, I think for the same reason you've described here. I don't see how that makes sense.

**Comment by wsargent** [comment]
@gmethvin the reasoning at the time was that if you were developing on several different applications, the header is **browser-specific** to that URL and not **application-specific**.

**Comment by gmethvin** [comment]
I suggest we disable all filter functionality in dev mode and have a configuration `play.filters.https.redirectEnabled = true` for overriding it. If the redirect is enabled we assume HSTS is enabled as well. If someone wants to disable HSTS, they should just set `strictTransportSecurity = null` in config.

**Comment by wsargent** [comment]
@gmethvin 👍

**Comment by PromanSEW** [comment]
@gmethvin I think CSRFFilter must be enabled in dev mode.

**Comment by gmethvin** [comment]
@PromanSEW Sorry, I meant to say all of the `RedirectHttpsFilter`'s functionality, including the HSTS header.

**Comment by gmethvin** [comment]
@PromanSEW I would prefer not to use `play.filters.disabled` in `devSettings` since that's not very discoverable. If we install the filter and print a log message, it will be easier for users to understand what's going on when it's not working.

**Comment by PromanSEW** [comment]
@gmethvin your suggested behavior in PR is certainly better that dynamically overriding previously enabled filters

**Comment by richdougherty** [comment]
Hi @PromanSEW, this issue is now addressed in Play 2.6.1 if you want to try it out.

**Comment by PromanSEW** [comment]
@richdougherty all works fine in 2.6.1, but I don't like this console output:
```
[info] play.api.Play - Application started (Dev)
[info] p.f.h.RedirectHttpsFilter - Not redirecting to HTTPS because play.filters.https.redirectEnabled flag is not set.
[info] p.f.h.RedirectHttpsFilter - Not redirecting to HTTPS because play.filters.https.redirectEnabled flag is not set.
[info] p.f.h.RedirectHttpsFilter - Not redirecting to HTTPS because play.filters.https.redirectEnabled flag is not set.
...
```
after every request
How to disable these annoying messages?

**Comment by richdougherty** [comment]
@PromanSEW, thanks for checking 2.6.1. I see you've already created an issue about the log messages: #7592.
