### ISSUE TITLE
[doc] Wrong words in ScalaWS.md

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#7497]
https://www.playframework.com/documentation/2.6.x/ScalaWS#Using-WSClient-with-unreliable-networks

"You should size the pool to leave a safety margin large enough to account for futures, and consider using play.api.libs.concurrent.Futures and a Failsafe Circuit Breaker."

account for *failures* -- also don't specify Failsafe, many other circuit breakers as well...

**Comment by gabrielgiussi** [comment]
@wsargent What it means with

> You should size the pool to leave a safety margin large enough to account for failures

It really matters if the futures completes or fails from the point of view of the pool? In the end we need some thread to execute the callback onSuccess or onFailure.
