### ISSUE TITLE
java.lang.NoSuchMethodError: play.api.libs.ws.package$.writeableOf_JsValue()Lplay/api/libs/ws/BodyWritable; when relying on implicit BodyWriteable[JsValue]

### ISSUE THREAD

**Issue by colin-passiv** [playframework/playframework#7508]
There are two package objects for `play.api.libs.ws`.
- One in `play-ws`, which extends `JsonBodyWritables` 
- and one in `play-ws-standalone`, which doesn't.

Both are on the classpath.

Application compile fine since an implicit `BodyWritable[JsValue]` is being found from `play-ws`. But in runtime, it sometimes picks up the `play-ws-standalone` and we get: 
```
java.lang.NoSuchMethodError: play.api.libs.ws.package$.writeableOf_JsValue()Lplay/api/libs/ws/BodyWritable;
```

### Play Version (2.5.x / etc)
2.6.0

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux 2.6.32-696.1.1.el6.x86_64

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "1.8.0_131"

### Expected Behavior

`wsClient.url(...).put(JsValue(...))` should either not compile without providing an explicit `BodyWriteable[JsValue]` or be consistently found in runtime.

### Actual Behavior

```scala
wsClient.url(...).put(JsValue(...))
```
will compile fine. But sometimes throws `java.lang.NoSuchMethodError: play.api.libs.ws.package$.writeableOf_JsValue()Lplay/api/libs/ws/BodyWritable;` at runtime.

Workaround is to explicitly provide the BodyWriteable[JsValue]:

```scala
wsClient.url(...).put(JsValue(...))(play.api.libs.ws.JsonBodyWritables.writeableOf_JsValue)
```

**Comment by cchantep** [comment]
Hi, it rather look like a dependency conflict in the build. Please first ask on the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework).

**Comment by francisdb** [comment]
@colin-passiv how did you fix this? Searched the mailing list and could not find any related thread. We are having exactly the same issue where at runtime we get his:

```
2017-07-17 11:11:17 +0000     akka.actor.ActorSystemImpl - ERROR Uncaught error from thread [application-akka.actor.default-dispatcher-4]: play.api.libs.ws.package$.writeableOf_JsValue()Lplay/api/libs/ws/BodyWritable;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: play.api.libs.ws.package$.writeableOf_JsValue()Lplay/api/libs/ws/BodyWritable;
	at io.waylay.kairosdb.driver.KairosDB.addDataPoints(KairosDB.scala:135)
```

Maybe it's related to our project depending on a project that also depends on play-ws 2.6.1 (might be better to depend on play-ws-standalone so the artifacts end up pointing to the correct classes)

**Comment by colin-passiv** [comment]
I think the problem is that the `play.api.libs.ws` package object conflict isn't a problem during compilation since sbt has consistent ordering based on `libraryDependencies`.
However in runtime, the order may be different, and it may pick up play-ws-standalone's package object first, which doesn't have the `JsonBodyWritables` implicits.

Our workaround was to not rely on the package object, and explicitly pass the writeable.
e.g. replace 
`
wsClient.url(...).put(JsValue(...))
`
with
`
wsClient.url(...).put(JsValue(...))(play.api.libs.ws.JsonBodyWritables.writeableOf_JsValue)
`

Unfortunately, since it's not caught during compilation, this requires searching through the source code, or waiting for runtime errors to identify.

**Comment by francisdb** [comment]
I guess adding these might also fix this.
```
import play.api.libs.ws.JsonBodyReadables._
import play.api.libs.ws.JsonBodyWritables._
```
(as documented at https://github.com/playframework/play-ws)
