### ISSUE TITLE
Streamed Source is blocking outputstream writes and entire Thread

### ISSUE THREAD

**Issue by correllink** [playframework/playframework#7512]
### Library Dependencies (nil)
Used the sample scala project

### Expected Behavior
Sample code to send using the output stream

	def sendStream = Action {
		val SEND_STRING = "Why wont you send!"

		val streamFN = StreamConverters.asOutputStream().mapMaterializedValue {o => {
		  Logger.debug("Start Send")
		  o.write(SEND_STRING.getBytes("UTF8"))
		  Logger.debug("Sent")
		  o.close()
		  Logger.debug("Closed")

		}}

		Status(206).sendEntity(HttpEntity.Streamed(streamFN,None,Some("text/plain")))
	}

Expecting in console
"Start Send"
"Sent"
"Closed"

Expecting response in browser
"Why wont you send!"

(note my actual use case is to send a zipstream but traced the issue down to the output stream)

### Actual Behavior
Console
"Start Send"
"Sent"
`
	java.io.IOException: java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
		at akka.stream.impl.io.OutputStreamAdapter.$anonfun$sendMessage$1(OutputStreamSourceStage.scala:198)
		at akka.stream.impl.io.OutputStreamAdapter.send(OutputStreamSourceStage.scala:169)
		at akka.stream.impl.io.OutputStreamAdapter.sendMessage(OutputStreamSourceStage.scala:188)
		at akka.stream.impl.io.OutputStreamAdapter.close(OutputStreamSourceStage.scala:216)
		at controllers.HomeController.$anonfun$sendStream$2(HomeController.scala:41)
`
Browser
Blocks then times out

Tried variations of 
- not closing the stream
- flushing and closing the stream
- Supplying Some(SEND_STRING.length) for the content length
In some cases browser got the text, but socket didnt close, and subsequent requests after the first one block.

### Reproducible Test Case

Add the code above to the sample scala project and make a route to it.
(zip of project attached)

[output_stream_bug.zip](https://github.com/playframework/playframework/files/1107078/output_stream_bug.zip)

**Comment by correllink** [comment]
[output_stream_bug.zip](https://github.com/playframework/playframework/files/1107081/output_stream_bug.zip)

**Comment by wsargent** [comment]
This sounds similar to https://github.com/playframework/playframework/issues/6579

**Comment by richdougherty** [comment]
Can you get a thread dump for this? You can pass an explicit timeout into the `asOutputStream` method so that you have enough time.

**Comment by correllink** [comment]
The Timeout is 5 seconds, but tried manually setting it to 20, after 20 seconds I get the 
> java.util.concurrent.TimeoutException: Futures timed out after [20 seconds]

But the connections still blocked
I think this is the thread in question:

> "play-dev-mode-akka.io.pinned-dispatcher-5@12016" prio=5 tid=0x2d nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.KQueueArrayWrapper.kevent0(KQueueArrayWrapper.java:-1)
	  at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	  at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	  - locked <0x4671> (a sun.nio.ch.KQueueSelectorImpl)
	  - locked <0x4672> (a java.util.Collections$UnmodifiableSet)
	  - locked <0x4673> (a sun.nio.ch.Util$2)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	  at akka.io.SelectionHandler$ChannelRegistryImpl$$anon$3.tryRun(SelectionHandler.scala:122)
	  at akka.io.SelectionHandler$ChannelRegistryImpl$Task.run(SelectionHandler.scala:240)
	  at akka.io.SelectionHandler$ChannelRegistryImpl$$anon$3.run(SelectionHandler.scala:155)
	  at akka.util.SerializedSuspendableExecutionContext.run$1(SerializedSuspendableExecutionContext.scala:67)
	  at akka.util.SerializedSuspendableExecutionContext.run(SerializedSuspendableExecutionContext.scala:71)
	  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

If you require  all / other threads please let me know.

**Comment by richdougherty** [comment]
Thanks for the thread info. I was interested whether we could see threads waiting for each other. I've since read some of the Akka Streams code and I don't think we're going to see much interesting stuff in the thread dump.

I think at this stage someone needs to get inside a debugger and set some breakpoints in `akka.stream.impl.io.OutputStreamSourceStage` and `akka.stream.impl.io.OutputStreamAdapter`.

**Comment by schmitch** [comment]
well somehow my company fed a InputStream `asInputStream` to jdbc, which didn't worked since akka, 2.5 also.
So this looks like a potential regression in akka, maybe due to the new materializer?
Looks like the whole `StreamConverters` has problems, however I didn't had a problem when creating a small test program:

```scala
    implicit val system = ActorSystem()
    implicit val materializer = ActorMaterializer()
    implicit val ec = system.dispatcher


    val inputStream = Source.fromFuture(Future(ByteString.fromString("Hello World!" * 8192 * 2))).runWith(StreamConverters.asInputStream())

    val writer = new StringWriter
    IOUtils.copy(inputStream, writer, StandardCharsets.UTF_8)
    val theString = writer.toString
    println(theString)
    Await.ready(system.terminate(), 10.minutes)
```

or even with the jdbc driver. so it looks like some kind of race condition that needs to happen I also never tested on Scala 2.11 but as far as I remeber it worked on 2.11.

**Comment by schmitch** [comment]
Created an issue here: https://github.com/akka/akka/issues/23279

**Comment by schmitch** [comment]
Currently the problem is, that in akka-stream 2.5 everything between the mapMaterializedValue needs to be a `Future` or threaded. I.e:

```scala
	val streamFN = StreamConverters.asOutputStream().mapMaterializedValue {o => Future{
	  Logger.debug("Start Send")
	  o.write(SEND_STRING.getBytes("UTF8"))
	  Logger.debug("Sent")
	  o.close()
	  Logger.debug("Closed")

	}}
```
would work.

**Comment by correllink** [comment]
Adding the Future worked great, thanks for the feedback.
Is it worth flagging as a bug in akka?

**Comment by schmitch** [comment]
I already opened a akka bug: https://github.com/akka/akka/issues/23279
but I'm not 100% sure if it is expected to wrap it in a `Future` or a Bug.

**Comment by correllink** [comment]
Cool thank you. If its by design to use a future thats all good. An (OutputStream) => Future[Any]  for the argument or a comment in the scala doc would be handy, but it works so thats the important thing.

**Comment by richdougherty** [comment]
See also: https://stackoverflow.com/questions/47140930/how-to-stream-zipped-file-on-the-fly-via-play-framework-2-5-in-scala

**Comment by schmitch** [comment]
This is fixed at least in the recent akka-stream versions, please feel free, to reopen if you still stumble upon some bugs
