### ISSUE TITLE
Multiple repos use Assets.versioned()

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#7521]
The routes file in both of the seed projects and both of the starter projects use Assets.versioned() which is deprecated.  See below:

https://github.com/playframework/play-java-seed.g8/blob/2.6.x/src/main/g8/conf/routes
https://github.com/playframework/play-scala-seed.g8/blob/2.6.x/src/main/g8/conf/routes
https://github.com/playframework/play-java-starter-example/blob/2.6.x/conf/routes
https://github.com/playframework/play-scala-starter-example/blob/2.6.x/conf/routes

**Comment by gmethvin** [comment]
@rmcloughlin Are you getting deprecation warnings on compile? The method being used is the instance method `Assets#versioned`: https://github.com/playframework/playframework/blob/2.6.0/framework/src/play/src/main/scala/play/api/controllers/Assets.scala#L694

This may be confusing because the syntax used in the routes file makes it look static, but if you're using the injected routes generator it will assume the last part is an instance method.

**Comment by rmcloughlin** [comment]
Ah, I thought it was deprecated because of how it appears in IntelliJ:  
![idea](https://user-images.githubusercontent.com/4472381/27705240-4dce6f26-5cdb-11e7-8535-21d86598ed0b.png)

IntelliJ seems to think that the `versioned` method in the routes file corresponds to this method:  https://github.com/playframework/playframework/blob/2.6.0/framework/src/play/src/main/scala/play/api/controllers/Assets.scala#L542

**Comment by richdougherty** [comment]
OK, so is this an issue with IntelliJ's Play support?

**Comment by gpgekko** [comment]
Seeing this too. Play compiles and runs fine, it's just the IDE tripping up.

**Comment by checat** [comment]
IDEA bugs:
https://youtrack.jetbrains.com/issue/SCL-8812
https://youtrack.jetbrains.com/issue/SCL-9106

**Comment by iamandrewluca** [comment]
So, what I see here is a IDE bug?
![image](https://user-images.githubusercontent.com/1881266/49142528-a5624d80-f301-11e8-8aa2-103b6e895232.png)

![image](https://user-images.githubusercontent.com/1881266/49142547-b27f3c80-f301-11e8-869c-c111047d0a3f.png)

**Comment by pelepelin** [comment]
@iamandrewluca Yes. IDE suggests that `controller.Assets.at` refers to a method of an `object`, however, when injected router is used, this route actually compiles to a reference to the method of a `class` with the same name (which is not deprecated). This affects syntax highlighting, GoTo action (Ctrl+B) and probably code analysis as well.
