### ISSUE TITLE
Result with headers content-type

### ISSUE THREAD

**Issue by limpep** [playframework/playframework#7558]
### Are you looking for help?

Hi, I am currently getting the following warning 

`[WARN] [07/04/2017 11:30:59.017] [play-dev-mode-akka.actor.default-dispatcher-11] [akka.actor.ActorSystemImpl(play-dev-mode)] Explicitly set HTTP header 'Content-Type: application/json' is ignored, explicit Content-Type header is not allowed. Set `HttpResponse.entity.contentType instead.`

I believe its to do with the following code I have, 

```
 public CompletionStage<Result> call(Http.Context ctx) {
        logger.info("Jsonify the response");

        try {
            CompletableFuture<Result> future = (CompletableFuture<Result>) delegate.call(ctx);
            JsonResult container = (JsonResult) future.get();
            Result result = new Result(
                    container.status(),
                    ImmutableMap.of(Http.HeaderNames.CONTENT_TYPE, Http.MimeTypes.JSON),
                    HttpEntity.fromString(gson.toJson(container.getResult()), CHARSET)
            );

            return CompletableFuture.completedFuture(result);

        } catch (ExecutionException | InterruptedException e) {
            logger.error("Can NOT Jsonify the response");
            return CompletableFuture.completedFuture(redirect(Path.LOGIN));
        }
    }
```
I am not sure what the best approach is to fix this. I know the warning message does state what the issue is, but this isn't very clear to me. Thanks

### Play Version (2.5.x / etc)
2.6.0

### API (Scala / Java / Neither / Both)
JAVA

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.12.15

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

### Library Dependencies

libraryDependencies += "com.google.code.gson" % "gson" % "2.8.0"

**Comment by marcospereira** [comment]
What if you have:

```java
HttpEntity entity = HttpEntity.fromString(gson.toJson(container.getResult()), CHARSET);
HttpEntity jsonHttpEntity = entity.as(Http.MimeTypes.JSON);
Result result = new Result(
    container.status(),
    jsonHttpEntity
);
```

Or:

```java
HttpEntity entity = HttpEntity.fromString(gson.toJson(container.getResult()), CHARSET);
Result result = new Result(
    container.status(),
    entity
).as(Http.MimeTypes.JSON);
```

**Comment by limpep** [comment]
@marcospereira define the values outside work for me, the first option.

**Comment by marcospereira** [comment]
@limpep glad to hear that.

Just to be clear, the fix is because the first example uses `entity.as` to set the content type. The second solution is just a shortcut to that.
