### ISSUE TITLE
incompatible type when depending on ApplicationLifecycle

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#7561]
Play Version (2.6.0)
API Scala (compile-time DI)
Scala 2.12.2
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### Expected Behavior

When I define a module that needs access to the ApplicationLifecycle using compile-time dependency injection I use this

```scala
def applicationLifecycle: ApplicationLifecycle
```
(implemented by BuiltInComponents)

### Actual Behavior

I get this compile-time error

```
overriding method applicationLifecycle in trait BuiltInComponents of type => play.api.inject.DefaultApplicationLifecycle;
[error]  method applicationLifecycle in trait MyModule of type => play.api.inject.ApplicationLifecycle has incompatible type
```
(only get this for the last module I add `with`)

This can of course be fixed by changing the dependency to

```scala
def applicationLifecycle: DefaultApplicationLifecycle
```

In play 2.5.x this is not needed.
Any reason why this was changed to an actual implementation? Feels a bit a strange to have to inject/depend on an implementation. This also hinders testing where one might want to replace the implementation of the ApplicationLifecycle.

for reference this change was introduced in:
https://github.com/playframework/playframework/commit/dba7b884114ca8472ce2efcb813680dda325ab3b#diff-3b7eaa744ad895d6a36f11720bbfa0acR236

**Comment by richdougherty** [comment]
Hi @francisdb, this issue is now addressed in Play 2.6.1 if you want to try it out.

**Comment by francisdb** [comment]
that's fast, I can confirm this is fixed 👍🏻

**Comment by richdougherty** [comment]
Great! Thanks for checking. :)
