### ISSUE TITLE
Multi-value query string params passed to RequestHeader in reverse order

### ISSUE THREAD

**Issue by olafos** [playframework/playframework#7567]
### Are you looking for help?

No

### Play Version (2.5.x / etc)

2.6.0

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Ubuntu 16.04 x86_64

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle 1.8.0_101

### Library Dependencies

None

### Expected Behavior

1. Call controller with multi-valued request param: http://localhost:9000/?p2=1&p1=1&p1=2&p1=3
2. The value of parameter p1 read from request header query string should be List("1","2","3")

### Actual Behavior

The value of parameter p1 read from request header query string is List("3","2","1")

### Reproducible Test Case

https://github.com/olafos/play-multivalue-params

**Comment by marcospereira** [comment]
@olafos thanks for the report and project to reproduce the problem.

I can confirm this is happening for 2.6.0 and not for 2.5.15. While there is no saying in the RFC about order, I think this is something we should keep.

**Comment by olafos** [comment]
@marcospereira yep, I think so too. I have to admit I've been relying on this quite consistently - had no idea it's not part of the RFC. I'm glad that the order is deterministic at least so the workaround is pretty straight forward. Thanks for the fix - looking forward to the next release.

**Comment by richdougherty** [comment]
Hi @olafos, this issue is now addressed in Play 2.6.1 if you want to try it out.

**Comment by olafos** [comment]
Thanks @richdougherty, works great.

**Comment by richdougherty** [comment]
Thanks for checking and glad to hear it's working. :)
