### ISSUE TITLE
Form default values not being picked up

### ISSUE THREAD

**Issue by privetgit** [playframework/playframework#7568]
### Are you looking for help?

Yes, https://stackoverflow.com/questions/42907891/scala-play-why-are-the-form-default-values-not-being-picked-up
and official doc https://www.playframework.com/documentation/2.6.x/ScalaForms#default-values 

### Play Version (2.5.x / etc)
Play Version 2.6.0

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 8.1

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) Client VM (build 25.131-b11, mixed mode, sharing)

### Library Dependencies
No

### Expected Behavior
The default values ​​should be displayed in the browser.

### Actual Behavior

The program is compiled without errors, but the default values ​​are not substituted in the form fields.
UPD: default values ​​do not appear in the form fields, but come in the request

### Reproducible Test Case

```
controller
val watchForm = Form(
        mapping(
            "brend" -> longNumber,
            "title" -> default(nonEmptyText, "ss"),
            "cost" -> default(of(doubleFormat), 2.0)
        )(WatchForm.apply)(WatchForm.unapply)
    )

view template 
@helper.form(routes.WatchController.insert) {
        @helper.select(watchForm("brend"), Seq( ("1", "First value"), ("2", "Seconds value"), ("3", "Third value")  ), 'multiple -> None )
        @helper.inputText(watchForm("title"))
        @helper.inputText(watchForm("cost"))
        <button type="submit">Добавить</button>
    }
```

**Comment by marcospereira** [comment]
We may need to clarify what `default` means, but this is the regular behavior. I'm keeping this open so that we can later improve the docs and better explain how `default` works.

**Comment by marcadella** [comment]
Why is that the default behavior? In addition, giving a default value in the form args such as in `@helper.inputText(form("Cutoff"), 'value -> "100")`, does not work either. What can we do then?
