### ISSUE TITLE
Nested Play Applications crashes Slick?

### ISSUE THREAD

**Issue by jducoeur** [playframework/playframework#7581]
### Play Version (2.5.x / etc)

2.6.0

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Ubuntu 14.04.1

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

### Library Dependencies

play-slick 3.0.0
scalatestplus-play 3.0.0

### Expected Behavior

Running a ScalaTest+Play Suite where:

* The Suite is GuiceOneAppPerSuite
* The test is using Server.withRouter() to simulate an external server
* Inside the withRouter() code, we are trying to run Slick operations.

We expect these Slick operations (specifically `db.run()`) to work normally.

### Actual Behavior

The Slick operations crash, consistently, inside AsyncExecutor.  See [the README in the linked repo](https://github.com/jducoeur/ShowAsyncExecutorProblem/blob/master/README.md) for the gory details.

**Note:** I am by no means certain that the problem here is in Play per se.  This is apparently some sort of bad interaction between Play, Slick, and possibly the play-slick library.  I *suspect* that the Play level is causing an environmental problem that causes Slick to crash, but that isn't entirely clear.  It is my hypothesis that this has something to do with having multiple Applications running, but I could be entirely off-base here.

### Reproducible Test Case

See [https://github.com/jducoeur/ShowAsyncExecutorProblem](https://github.com/jducoeur/ShowAsyncExecutorProblem) for a reproducer.  In particular, see the file [ShowProblemSpec](https://github.com/jducoeur/ShowAsyncExecutorProblem/blob/master/show-async-problem/test/controllers/ShowProblemSpec.scala), which has a test that consistently causes Slick to crash.

**Comment by gslowikowski** [comment]
`BrowserSpec` test in [play-scala-slick-example branch 2.6.x](https://github.com/playframework/play-scala-slick-example/tree/2.6.x) application fails with similar exception:
```
! @74hllg3hb - Internal server error, for (GET) [/persons] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IllegalStateException: Cannot initialize ExecutionContext; AsyncExecutor already shut down]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:257)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:184)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:228)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:227)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
Caused by: java.lang.IllegalStateException: Cannot initialize ExecutionContext; AsyncExecutor already shut down
	at slick.util.AsyncExecutor$$anon$2.executionContext$lzycompute(AsyncExecutor.scala:61)
	at slick.util.AsyncExecutor$$anon$2.executionContext(AsyncExecutor.scala:59)
	at slick.util.AsyncExecutor$$anon$2.executionContext(AsyncExecutor.scala:51)
	at slick.jdbc.JdbcBackend$DatabaseDef.synchronousExecutionContext(JdbcBackend.scala:63)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction(BasicBackend.scala:233)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction$(BasicBackend.scala:231)
	at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:38)
	at slick.basic.BasicBackend$DatabaseDef.runInContext(BasicBackend.scala:210)
	at slick.basic.BasicBackend$DatabaseDef.runInContext$(BasicBackend.scala:142)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:38)
```

Maybe the problem is related to `WithBrowser`?

**Comment by richdougherty** [comment]
@jducoeur / @gslowikowski - sorry for the silence on this one. I will try to take a look next week.

The stack trace shown by @gslowikowski seems to indicate that there's an issue with the code for cleaning up after each test. Some code seems to be trying to run even after the test's `ExecutionContext` has been shut down. Perhaps there's a problem with the order that things are shut down.

**Comment by jducoeur** [comment]
Quite possible, but note that mine is showing up on the first test that is run, in the middle of the test -- things *shouldn't* be shut down at the time of the error.

(The error message in one version of my problem says that the AsyncExecutor has apparently been shut down, but it actually *means* that it's in the wrong state: AFAICT, the error message doesn't quite match the actual test that is failing...)

**Comment by richdougherty** [comment]
OK thanks for the clarification. Hopefully I can take a look this week!

**Comment by marcospereira** [comment]
Hi @jducoeur,

Following the code we can see:

1. [`Server.withRouter`](https://github.com/playframework/playframework/blob/master/framework/src/play-server/src/main/scala/play/core/server/Server.scala#L167) calls `Server.withApplication` which calls `Play.star`.
2. `Play.start` tries to stop the application (which stops everything related to the application, including the `ExecutionContext`) if there is one running **and** if `play.allowGlobalApplication` is `true` (which is the default value).
3. Since the application is stopped and we are using one app per suite, the test using `Server.withRouter` fails.

A simple solution here is to configure `play.allowGlobalApplication` to false by changing `fakeApplication` to:

```scala
  override def fakeApplication():Application =
    new GuiceApplicationBuilder()
      // Config settings go here:
      .configure(
        // By default, CSRF doesn't allow running directly from localhost:
        "play.filters.hosts.allowed" -> Seq("localhost"),
        "slick.dbs.default.profile" -> "slick.jdbc.H2Profile$",
        "slick.dbs.default.db.driver" -> "org.h2.Driver",
        "slick.dbs.default.db.url" -> "jdbc:h2:mem:play",
        "play.allowGlobalApplication" -> "false" // this will make the test pass
      )
      // Test-only bits go here:
      .bindings(bind[TestDatabase].to[TestDatabaseImpl])
      .build()
```

You can see more details about `play.allowGlobalApplication` in #6866 and [here](https://playframework.com/documentation/2.6.x/Highlights26#Global-State-Free-Applications).

----

All that said, I think the real problem here is that we don't have a clear API to create the application with a Router, using Guice but not using the now deprecated `Action` builder (see #7553).

@jducoeur, if using `play.allowGlobalApplication` works for you, we can close this issue and further discuss solutions for Guice + Router in #7553.

**Comment by jducoeur** [comment]
It's fine by me, although you might want to consider mentioning this somewhere in the docs.  I've moved on: my client and I talked it over a while ago, and decided at least for now to rewrite the unit tests that were using `withRouter()` to instead stub WSClient, which produces somewhat cleaner test code anyway.

Good to understand what the problem is, though, and how to work around it -- thanks!
