### ISSUE TITLE
[doc] Deprecated Action referenced in Composing Actions section

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#7600]
https://www.playframework.com/documentation/2.6.x/ScalaActionsComposition#composing-actions

```scala
import play.api.mvc._

case class Logging[A](action: Action[A]) extends Action[A] {

  def apply(request: Request[A]): Future[Result] = {
    Logger.info("Calling action")
    action(request)
  }

  override def parser = action.parser
  override def executionContext = action.executionContext
}
```

**Comment by gmethvin** [comment]
@wsargent The `Action` object is deprecated but the example is extending the `Action` trait, which is not deprecated. The `parser` and `executionContext` are being obtained from the wrapped action and not from global state. So it looks ok to me. Am I missing something here?

**Comment by wsargent** [comment]
Reported by user as giving off deprecation warnings -- closing as unconfirmed.
