### ISSUE TITLE
Json Object,Reads trait, Writes trait, are not Serializable

### ISSUE THREAD

**Issue by abdelrahmanmohamed** [playframework/playframework#7605]
Json Object,Reads trait, Writes trait can't be used within RDD operation in spark because it's not serializable
`def dataRDDAsRDDOfBlaBla(data:RDD[String])(implicit sc:SparkContext,ticketReads:Reads[BlaBla],ticketWrites:Writes[BlaBla]): RDD[BlaBla] = {
    data.map(row=>Json.fromJson[BlaBla](Json.parse(row))).filter(jsResult => jsResult.isSuccess).map(_.get)
  }`

**Comment by cchantep** [comment]
Hi,

Please first use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask question/for help (the tracker is for confirmed issue or validated feature request).

Aside from that I doubt it makes sense to have the `JsValue` `Serializable` by default : not sure it's wanted most of the time, and can be avoided easily by writing first by stringifying (to explicitly serialize the string representation, not the instance in JVM memory).

BTW as far as I know Spark 2+ uses dedicated generic codec types, that can be considered as type classes, and so for which instances could be provided.
