### ISSUE TITLE
Reverse routing generates url without escaping special characters

### ISSUE THREAD

**Issue by kastoestoramadus** [playframework/playframework#7610]
### Play Version (2.5.x / etc)

2.5.12 // tested also on 2.5.13

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux walidus-XPS 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### Expected Behavior

There is an endpoint:
`GET        /envelopes/:envelopeId/files/:fileId/content       uk.gov.hmrc.fileupload.controllers.FileController.downloadFile(envelopeId: uk.gov.hmrc.fileupload.EnvelopeId, fileId: uk.gov.hmrc.fileupload.FileId)`

Recreation of the url:
` uk.gov.hmrc.fileupload.controllers.routes.FileController.downloadFile(envelopeId, fileId).url`

for `fileId="%2C"` it should produce URL with escaped result: `"%252C"`

### Actual Behavior

for `fileId="%2C"` it produces URL that contains: `"%2C"` instead of  `"%252C"`

I tried to fix it with `PathBindable` but the decoding can not be added along with encoding in the same class since play decodes all parameters of all endpoints apart from `PathBindable` logics (double decoding).

### Reproducible Test Case

This test fails:
`https://github.com/hmrc/file-upload/blob/play-encoding-bug-proof/test/uk/gov/hmrc/fileupload/HrefSpec.scala`

You can run it with command:
`sbt "testOnly uk.gov.hmrc.fileupload.HrefSpec"`

**Comment by kastoestoramadus** [comment]
In documentation there is: `In the case of path segments (:foo), the value is encoded before the substitution is done. For regex and wildcard patterns the string is substituted in raw form, since the value may span multiple segments. Make sure you escape those components as desired when passing them to the reverse route, and avoid passing unvalidated user input.`

String: "ˮ깉ീ" is not regex nor contain wildcards. According to upper text it should not be in raw form. That is why I claim the problem is on the Play side.

**Comment by codesurf42** [comment]
This simple Play app may be better to show where is the problem:
https://github.com/codesurf42/playPathBinder/

When you use reverse routing to generate URLs for your controllers, the case when raw value is encoded is for string. The generated ReverseRoutes.scala looks like:
```    // @LINE:12
    def getValueT1(name:String): Call = {
      import ReverseRouteContext.empty
      Call("GET", _prefix + { _defaultPrefix } + "val/" + implicitly[PathBindable[String]].unbind("name", dynamicString(name)))
    }
```

however for other types, when you need to add your own implementation of PathBindable[T], the generated code in ReverseRoutes.scala looks like:

```    // @LINE:14
    def getValueT3(name:models.Value2): Call = {
      import ReverseRouteContext.empty
      Call("GET", _prefix + { _defaultPrefix } + "val3/" + implicitly[PathBindable[models.Value2]].unbind("name", name))
    }
  
    // @LINE:13
    def getValueT2(name:models.Value1): Call = {
      import ReverseRouteContext.empty
      Call("GET", _prefix + { _defaultPrefix } + "val2/" + implicitly[PathBindable[models.Value1]].unbind("name", name))
    }
```
(no use of play.utils.UriEncoding.dynamicString())

So while the string value from
https://github.com/codesurf42/playPathBinder/blob/master/app/controllers/HomeController.scala#L19
is encoded properly, the value from 
https://github.com/codesurf42/playPathBinder/blob/master/app/controllers/HomeController.scala#L20
is just raw, unless you explicitly call encoding 
https://github.com/codesurf42/playPathBinder/blob/master/app/models/Models.scala#L20
to fix it.

```
valueAsString=/val/foo-%252C-fo%20o
valueAsClass1=/val2/foo-%2C-fO o
valueAsClass2=/val3/foo-%252C-fO%20o
```

Perhaps we could also add examples to documentation to show how such encoding for string values is used, as for now the cases on https://www.playframework.com/documentation/2.5.x/ScalaRequestBinders are going only about numbers.

**Comment by frankoid** [comment]
It seems to me that the `PathBinder` shouldn't be responsible for encoding the string in unbind, as this is not symmetrical with bind, which does not do decoding.

So the reverse router for `PathBindable` should be encoding the string, like this:
```
    def getValueT3(name:models.Value2): Call = {
      import ReverseRouteContext.empty
      Call("GET", _prefix + { _defaultPrefix } + "val3/" + implicitly[PathBindable[models.Value2]].unbind("name", dynamicString(name)))
    }
```

...unless there is some flaw with this approach?

**Comment by gmethvin** [comment]
@frankoid `DynamicString` encodes a string; it doesn't work for arbitrary types. I'm not sure why String is handled as an exception in that one case. I think a better solution would be something like:

```
 Call("GET", _prefix + { _defaultPrefix } + "val3/" + dynamicString(implicitly[PathBindable[models.Value2]].unbind("name", name)))
```

Effectively, right now the user is expected to handle the encoding in the `PathBindable`. My only worry with changing it is it does give the user less control, and it'll result in a double-encoding bugs as soon as we update Play, so it's effectively a breaking change.

**Comment by codesurf42** [comment]
@gmethvin Maybe config flag with the default generating routes as they are now would do? Newer play versions can have this flag in config the other way around, so it wouldn't break existing code bases.

**Comment by richdougherty** [comment]
We could try introduce some new types to evolve the API a bit while handling backwards compatibility concerns.

For path segment patterns like `/envelopes/:envelopeId/files/:fileId/content` we could use the existing routing/reverse-routing behaviour if the `envelopeId` and/or `fileId` parameters are `String`s. But if the parameters use a new type like `PathSegment` then we could have new encoding/decoding behaviour with clearer semantics.

```
/** A decoded path segment */
case class PathSegment(value: String)
```

We could also introduce new types to fix up the disparity between path segment and regex/wildcard patterns pointed out in [a comment above](https://github.com/playframework/playframework/issues/7610#issuecomment-314703004). We could introduce another new type for regex/wildcard patterns, e.g. `PathSuffix`. If a regex/wildcard pattern is associated with a `String` parameter then we could use the old behaviour. However if a new type like `PathSuffix` is used when routing then we could properly decode the segments—something that will probably make user code more robust.

```
/** A decoded suffix of a URI path */
case class PathSuffix(segments: Seq[PathSegment], endsWithSlash: Boolean)
```

**Comment by gmethvin** [comment]
I think it's probably ok to break here if we need to, since I'd consider the existing behavior a bug, and it's inconsistent with the docs. My guess is most people expect the path segments to be escaped and they may not have noticed this, so this bug will be silently fixed.

But I also agree that we need a better way of distinguishing different types of path sections. It's strange that you have to know what kind of pattern it is to know whether escaping is needed.
