### ISSUE TITLE
object AkkaGuiceSupport is not a member of package play.api.libs.concurrent

### ISSUE THREAD

**Issue by rayronvictor** [playframework/playframework#7637]
### Play Version (2.5.x / etc)
2.6.1

### API (Scala / Java / Neither / Both)
Scala (2.12.2

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
macOS Sierra 10.12.5

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

### Library Dependencies
scala-guice 4.1.0

### Expected Behavior
1. object AkkaGuiceSupport is found in package play.api.libs.concurrent

### Actual Behavior
1. object AkkaGuiceSupport is not a member of package play.api.libs.concurrent
```scala
package modules

import actors.{ProjectActor, Scheduler, SchedulerImpl}
import com.google.inject.AbstractModule
import play.api.libs.concurrent.AkkaGuiceSupport
import services.{MailService, MailServiceImpl}
import net.codingwell.scalaguice.ScalaModule

class ProjectModule extends AbstractModule with ScalaModule with AkkaGuiceSupport {

  def configure() = {
    bindActor[ProjectActor]("project-actor")
    bind[Scheduler].to[SchedulerImpl].asEagerSingleton()

    bind[MailService].to[MailServiceImpl]
  }
}
```

```shell
[error] /Users/usuario/Documents/workspace/materiais/app/modules/ProjectModule.scala:5: object AkkaGuiceSupport is not a member of package play.api.libs.concurrent
[error] import play.api.libs.concurrent.AkkaGuiceSupport
[error]        ^
[error] /Users/usuario/Documents/workspace/materiais/app/modules/ProjectModule.scala:11: not found: type AkkaGuiceSupport
[error] class ProjectModule extends AbstractModule with ScalaModule with AkkaGuiceSupport {
[error]                                                                  ^
[error] /Users/usuario/Documents/workspace/materiais/app/modules/ProjectModule.scala:21: not found: value bindActor
[error]     bindActor[ProjectActor]("project-actor")
[error]     ^
```

**Comment by marcospereira** [comment]
Do you have the following dependency declared on your `build.sbt` file?

```scala
libraryDependencies += guice
```

That is because of [Guice support is now a separated module](https://playframework.com/documentation/2.6.x/Migration26#Guice-DI-support-moved-to-separate-module).

**Comment by rayronvictor** [comment]
Was exactly this!
I skipped this part of the migration.
Thanks @marcospereira !
