### ISSUE TITLE
access to StandaloneWSClient

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#7638]
play 2.6.x scala

Since play-ws has now been migrated to a standalone project (`play-ws-standalone`) it is expected that libraries will start depending on that instead of `play-ws` to reduce their dependencies and allowing use outside of play

This underlying `StandaloneWSClient` is however not accessible in play when using `AhcWSComponents` (or Guice?)

It would be great if AhcWSComponents would also expose the standalone client.
```scala
lazy val standaloneWsClient: StandaloneWSClient = ...
```

example:

kairosdb-scala -> play-ws-standalone
myPlayApp -> kairosdb-scala

When creating an instance of the KairosDB client I need a StandaloneWSClient. Currently I have to create a modified version of AhcWSComponents that exposes the underlying StandaloneAhcWSClient as StandaloneWSClient.

**Comment by marcospereira** [comment]
Maybe this should better be done in the standalone project itself?

If the purpose it to slim down dependencies, it would be better to depends only on play-ws-standalone.

**Comment by wsargent** [comment]
You can bind a standalone client very simply, as it's a wrapper around `AsyncHttpClient`, which is exposed:

https://github.com/playframework/playframework/blob/master/framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSModule.scala#L207

**Comment by francisdb** [comment]
@marcospereira added example to clarify my case
@wsargent exactly, I have to create my own modified `AhcWSComponents` so I can access the `StandaloneWSClient` built in there. It would be simpler if the `AhcWSComponents` would also expose a `StandaloneWSClient` next to the play `WsClient`.

My current workaround:
```scala
trait AhcWSWithStandaloneComponents {

  def environment: Environment
  def configuration: Configuration
  def applicationLifecycle: ApplicationLifecycle
  def materializer: Materializer
  def executionContext: ExecutionContext

  private lazy val standaloneAhcWSClient = {
    implicit val mat = materializer
    implicit val ec = executionContext
    val asyncHttpClient = new AsyncHttpClientProvider(environment, configuration, applicationLifecycle).get
    new StandaloneAhcWSClient(asyncHttpClient)
  }

  lazy val standaloneWsClient: StandaloneWSClient = standaloneAhcWSClient

  lazy val wsClient: WSClient = {
    new AhcWSClient(standaloneAhcWSClient)
  }
}
```

Anyway, this is more a suggestion, nice to have but not blocking.

**Comment by wsargent** [comment]
You can also use `wsClient.underlying[AsyncHttpClient]` in a pinch and provide an implicit conversion to `StandaloneWSClient`.  I'm not sure off the top of my head how much overhead is involved, but IIRC it should be just a wrapper and all the threads and caching are baked into AsyncHttpClient, and there's no lifecycle to take care of.

https://github.com/playframework/playframework/blob/master/framework/src/play-ws/src/main/scala/play/api/libs/ws/WSClient.scala#L28

**Comment by gbersac** [comment]
@francisdb, thanks to your comment, I found that the `wsClient`created by play is accessible within a class by using the trait `play.api.libs.ws.ahc.AhcWSComponents`. That's usefull because I try to avoid runtime dependency injection at any cost !

**Comment by marcospereira** [comment]
> It would be simpler if the AhcWSComponents would also expose a StandaloneWSClient next to the play WsClient.

I don't see a problem in doing that. Keep in mind we will need changes in both Java and Scala versions of `AhcWSComponents`. For the Java implementation, it could be trickier to avoid creating multiple instances of `StandaloneWSClient` though.

**Comment by felipebonezi** [comment]
> > It would be simpler if the AhcWSComponents would also expose a StandaloneWSClient next to the play WsClient.
> 
> I don't see a problem in doing that. Keep in mind we will need changes in both Java and Scala versions of `AhcWSComponents`. For the Java implementation, it could be trickier to avoid creating multiple instances of `StandaloneWSClient` though.

@marcospereira @wsargent 
Could you review if I'm doing what was suggested? ☝🏻

**Comment by felipebonezi** [comment]
@francisdb I've finished this task.
Feel free to check the PR #11318
