### ISSUE TITLE
Invalid compiler warning with custom annotation

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#7640]
**Play 2.6.1
Scala 2.12.2
Java**

When I use a custom annotation (as described [here](https://www.playframework.com/documentation/2.6.x/JavaActionsComposition#Defining-custom-action-annotations)) and then run `sbt dist` I get this warning:

```
[warn] .../app/actions/Basic.java:12: Implementation restriction: subclassing Classfile does not
[warn] make your annotation visible at runtime.  If that is what
[warn] you want, you must write the annotation class in Java.
[warn] public @interface Basic {
[warn]                   ^
```

This is very odd because my annotation _is_ written in Java (my whole project is) and I'm not "subclassing Classfile."  I've created a reproducible test case here: https://github.com/rmcloughlin/annotation-dist

**Comment by marcospereira** [comment]
Looks like this is an (unresolved) issue with Scala itself:

https://github.com/scala/bug/issues/10134

Unfortunately, there is nothing we can do on our side, @rmcloughlin. But, apparently, there is no effect besides the warning, right?
