### ISSUE TITLE
Refactor dev mode to call ApplicationProvider.get only once per request

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#7650]
We should only call `ApplicationProvider.get` at most once per request—ideally only once per reload. Calling it more often can lead to weird things like having the `Application` change in the middle of a single request. It can also lead to deadlock, e.g. #5975, #7614, #7622.

At the moment we don't have any serious bugs caused by calling `Application.get` multiple times per request but this is something we could look at refactoring.

Ideas for a fix: change `AkkaHttpServer` so that whenever the `Application` changes it makes a new `AkkaHttpRequestHandler` object. This object stores the `Application` object and stores derived classes like `AkkaModelConversion` and `ForwardedHeaderHandler`. This is a little bit harder than it sounds because the logic around getting an `Application`

**Comment by wsargent** [comment]
Regardless of what the framework does, application code could call `ApplicationProvider.get` at any point, especially if the application has been migrated from 2.3.x and is using that pattern to avoid global state...

**Comment by richdougherty** [comment]
OK that's interesting. The purpose of the `ApplicationProvider`, as far as I know, is to provide a way to abstract out the difference between an application that can be reloaded (dev mode) and a fixed application (prod mode). I—perhaps mistakenly—thought this would be something that only the server is concerned with.

Can you give an example of the pattern you mention, where user code uses `ApplicationProvider.get` to avoid global state? I can't work out why the user code wouldn't just have a reference to an `Application` directly…

**Comment by wsargent** [comment]
You're right, I was thinking there was a static factory `ApplicationProvider.get` method.

**Comment by richdougherty** [comment]
OK no worries :)

**Comment by richdougherty** [comment]
See also the #8005 for a plan that would probably fix this issue.

**Comment by shkhln** [comment]
I believe this also the reason for #7753.

**Comment by mkurz** [comment]
Looks like this got fixed by #8166
