### ISSUE TITLE
PlayMinimalJava not officially documented

### ISSUE THREAD

**Issue by ddevos78** [playframework/playframework#7654]
Play Java 2.6

I've noticed from the some of the Play 2.6 source that there is a new Java Plugin (PlayMinimalJava) which allows applications to remove dependencies against play-forms (and in particular spring), however this plugin isn't formally documented and hence official support for this feature is unclear.

Assuming that 'PlayMinimalJava' is officially supported, can we please get official documentation for it.

**Comment by gmethvin** [comment]
Where would you suggest adding it in the documentation?

Usually we recommend starting from a sample project, so maybe we need a play-minimal-java-seed.g8 or something like that.

**Comment by ddevos78** [comment]
@gmethvin Great question... so for any enterprise usecase, tightly controlling dependencies (and thus potential security issues) is a very big deal, so I would recommend this feature is documented in the following places:
* [Official 2.6 release highlights](https://www.playframework.com/documentation/2.6.x/Highlights26) > As I said its a big deal for enterprise projects that you can remove the spring dependency if you don't need it
* [Tutorial Section](https://www.playframework.com/documentation/2.6.x/Tutorials) > Agree that a minimal java seed would be useful
* [Java Form section](https://www.playframework.com/documentation/2.6.x/JavaForms) > This is the page that would most benefit from an update. For example, a final section could be written detailing how to disable JavaForms support (via switching from PlayJava > PlayMinimalJava) and thus remove spring as a dependency of your project
