### ISSUE TITLE
Can't disable AllowedHostsFilter

### ISSUE THREAD

**Issue by sergeda** [playframework/playframework#7655]
Play Version (2.6.0 and 2.6.1)
Using compile-time dependency if this does matter.
### Expected Behavior
When I add this line to config I'm expecting to be able to open web interface on http://127.0.0.1:9000/
play.filters.disabled += play.filters.hosts.AllowedHostsFilter

### Actual Behavior
it still returns Bad Request Host not allowed: 127.0.0.1:9000

and there is 
[warn] p.f.h.AllowedHostsFilter - Host not allowed: 127.0.0.1:9000
in the log

**Comment by PromanSEW** [comment]
You need to rewrite `play.filters.enabled` property instead
There is no `play.filters.disabled` functionality, see [comments here](https://github.com/playframework/playframework/issues/7492#issuecomment-310946413)

**Comment by wsargent** [comment]
Compile time dependency does injection differently -- please see https://www.playframework.com/documentation/2.6.x/Filters#Disabling-Compile-Time-Default-Filters
