### ISSUE TITLE
Race condition when multiple unit tests are run with jacoco4sbt

### ISSUE THREAD

**Issue by japhib** [playframework/playframework#7656]
I've got a Play framework (2.5.16) application written in Java running some unit tests. I've added jacoco4sbt to the project [as directed](https://github.com/sbt/jacoco4sbt), and the jacoco:cover task fails with the following error:

```
java.lang.RuntimeException: There is no started application
[error]     at scala.sys.package$.error(package.scala:27)
[error]     at play.api.Play$$anonfun$current$1.apply(Play.scala:86)
[error]     at play.api.Play$$anonfun$current$1.apply(Play.scala:86)
[error]     at scala.Option.getOrElse(Option.scala:121)
[error]     at play.api.Play$.current(Play.scala:86)
[error]     at play.api.Play.current(Play.scala)
```

This is the way I'm starting my fake application for unit tests:

```
public class MainUnitTest extends WithApplication
{
	@Override
	protected Application provideApplication()
	{
		Map<String, Object> config = new HashMap<>();
		config.put(/* some fake config values pertinent to my application */);
		
		return new GuiceApplicationBuilder()
				.configure(config)
				.build();
	}

	@Test
	public void testThatUsuallyWorksFineButSometimesBreaks()
	{
		Option<String> ret = Play.current().configuration().getString("configItem", Option.empty());
		assertFalse(ret.isEmpty());
	}
}
```

Then in another file:

```
public class UnitTestSubClass extends MainUnitTest
{
	@Test
	public void otherTestThatFailsJacoco() throws InterruptedException
	{
		for (int i = 0; i < 500; i++)
		{
			Option<String> ret = Play.current().configuration().getString("configItem", Option.empty());
			assertFalse(ret.isEmpty());
			Thread.sleep(5);
		}
	}
}
```

Both tests pass fine every time when I run `activator test`. One or both tests usually fail with the above error ("there is no started application") when I run `activator jacoco:cover`. 

I believe this is a race condition because:

1. It doesn't always happen -- sometimes it randomly still works
2. It doesn't happen when the second unit test (`otherTestThatFailsJacoco()`) is the same length as the first unit test -- it only fails when the second one takes longer to execute
3. I start an application in the same way for both of them, so it seems pretty likely that the fake application is getting stopped prematurely when one test is shorter than the others.

This might not be relevant but just in case, my dev environment is a MacBook Pro running macOS Sierra 10.12.5, with a 2.7GHz i5 processor.

It's possible this should be posted as an issue in the jacoco4sbt project instead of here, but the interaction with jacoco4sbt is indirect through play framework so I'm hoping someone here can at least point me in the right direction to get this fixed.

**Comment by PromanSEW** [comment]
`Play.current()` is deprecated since 2.5 as it uses global state. Maybe problem is here

**Comment by richdougherty** [comment]
Hi @japhib, can you try accessing the running application through `WithApplication`'s protected `app` field instead of using `Play.current()`?

https://www.playframework.com/documentation/2.5.x/api/java/play/test/WithApplication.html

**Comment by japhib** [comment]
Will do. Let me get back to you in a sec.

**Comment by japhib** [comment]
That fixed the problem. Thanks.

**Comment by richdougherty** [comment]
OK, glad it works. I'll close this ticket now.
