### ISSUE TITLE
Missing application.conf after build

### ISSUE THREAD

**Issue by dluc** [playframework/playframework#7664]
### Play Version (2.6.x / etc)

I'm working on a new web app based on PF 2.6 and often the application won't find custom settings stored in application.conf. 

The problem doesn't happen always though, sometimes the app finds the custom settings and works as expected.

After debugging my code and inspecting the content returned by `ConfigFactory.load()` I noticed that my custom settings were completely missing, so I checked the file system and noticed that the configuration file, **sometimes**, is not copied to the "target" folder.

Now, when this happens I run 
```
cp ./conf/application.conf ./target/scala-2.12/classes/application.conf
```
and everything works for me, however that's quite annoying and seems to be a regression.

### System details
OS: MacOS
IDE: using SBT from the console
Java:
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

### App details

build.properties
```
sbt.version=0.13.15
```

plugins.sbt
```
logLevel := Level.Warn
resolvers += Classpaths.sbtPluginReleases
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.2")
```

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. sbt +compile
2. sbt run
3. my app should find my custom settings
4. `find . -name *.conf` should return at least:
```
./conf/application.conf
./target/scala-2.12/classes/application.conf
```

possibly also `./target/scala-2.12/test-classes/application.conf`

### Actual Behavior

Step 3 fails with 
> ... com.typesafe.config.ConfigException$Missing: No configuration setting found for key ...

Step 4 shows only:
```
./conf/application.conf
```

**Comment by richdougherty** [comment]
Thanks for the detailed report. Does this problem occur for you with an empty starter project or are you using your own project? Is there anything interesting in the `build.sbt`? Also, you mentioned that the file is missing sometimes, about what percentage of the time is it missing for you?

**Comment by dluc** [comment]
I'm working on my own project, and I cannot currently share the code. I tried to remove most of the code from build.sbt, leaving it almost empty, and the problem was still occurring. The problem happens most of the time, I'd say 90% of the times. I'll try to start with an empty project and see if the behavior changes, adding what I use one piece at a time and see if I can reproduce with a codebase that I can share.
By the way I'm noticing the same issue with "logback.xml", looks like the issue affects all the resources.

Quick question, is my assumption correct that "sbt build" should copy the file into "./target/scala-2.12/" ? Or "sbt run" ?

**Comment by richdougherty** [comment]
Yes I think that assumption is correct, all resources should be copied somewhere under target. If you're seeing it happen some of the time, but not all the time, then that's weird.

To help isolate if it's a project issue vs an OS/environment issue would you be able to try a starter project? You can download one here: https://www.playframework.com/download
