### ISSUE TITLE
DefaultTemporaryFileReaper is leaking open file descriptors

### ISSUE THREAD

**Issue by jostick** [playframework/playframework#7667]
When I activate the temporary file reaper, the application starts to accumulate open file descriptors that are not closed anymore.

I'm using Play Framework 2.6.1 with Scala on Ubuntu 17.04 with Oracle Java:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

`uname -a` shows:
```
Linux jostick-XPS-15-9550 4.10.0-28-generic #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Library dependencies do not matter.

### Expected Behavior

The number of open file descriptors stays stable over time.

### Actual Behavior

When I activate the temporary file reaper, e.g. with this configuration
```
play {
 temporaryFile {
    reaper {
      enabled = true
      initialDelay = "1 seconds"
      interval = "10 seconds"
      olderThan = "30 minutes"
    }
  }
}
```

the application starts to accumulate open file descriptors that are not closed anymore or at least not for a long time. The short interval is only for demonstration purposes. It also happens with longer intervals, but takes a bit longer to become obvious. It seems 2 new file descriptors are open in each interval.

`lsof -p 9608 | grep DIR` show a long list like:
```
java    9608 jostick  338r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  391r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  394r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  395r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  396r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  397r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
java    9608 jostick  398r      DIR              253,1     4096 27787664 /tmp/playtemp7618465155593442868
....
```

### Solution

I think the only thing required to fix the problem is to call close on the JFiles.list(f) stream in DefaultTemporaryFileReaper.reap()

If requested I can do a small PR. But it's probably not easy to write a proper unit test for that.

**Comment by marcospereira** [comment]
Thanks for this, @jostick. Yes, a pull request would be great. :-)

**Comment by wsargent** [comment]
Relevant: https://stackoverflow.com/questions/36990053/resource-leak-in-files-listpath-dir-when-stream-is-not-explicitly-closed

**Comment by papauschek** [comment]
thanks for solving this. 👍 

I feel like sharing an anectode because this caused some serious downtimes on our production system. 

All nodes went down exactly within minutes of each other (max file descriptors reached) because of this time bomb. Because the outage is synchronized across all nodes (all nodes have the same Reaper interval causing the same number of FDs leaked) failover did not help, as the nodes failed within minutes of each other.

Glad we found this github issue at least after the second downtime ;)

**Comment by richdougherty** [comment]
Sorry to hear about the outage @papauschek! I wish there was a way to unit test these kinds of leaks - and other leaks too, like memory and thread leaks.

**Comment by richdougherty** [comment]
Hi @jostick, we just released Play 2.6.3 which includes your fix. It would be great if you could check it out and confirm that it's working for you.

Thanks a lot for the contribution. You might notice you're mentioned in the Credits in the release notes: https://blog.playframework.com/play-2-6-3-released/ 🍰

**Comment by jostick** [comment]
@richdougherty I tested it locally and everything looks good. Can't roll it out to production until Wednesday, since we've public holiday tomorrow. It was a pleasure contribute. And thanks for the fast feedback and merge.

**Comment by richdougherty** [comment]
Thanks @jostick! Fingers crossed that everything works in production now.

**Comment by jostick** [comment]
Rolled out to production several hours ago and can confirm that it is working as expected.

**Comment by richdougherty** [comment]
Great!
