### ISSUE TITLE
[2.6.2] Clearing a Flash Cookie with negative Max-Age does not work for all browsers

### ISSUE THREAD

**Issue by el-dom** [playframework/playframework#7680]
### Play Version (2.5.x / etc)
2.6.2

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Ubuntu 16.04

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

When using a flash cookie like described [here](https://www.playframework.com/documentation/2.6.x/ScalaSessionFlash#Flash-scope)
it gets set like this

```
Set-Cookie:PLAY_FLASH=eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImVycm9yIjoicGF5bWVudC5wYXltZW50bWV0aG9kLmludmFsaWQifSwibmJmIjoxNTAxNDk0ODM1LCJpYXQiOjE1MDE0OTQ4MzV9.E7S1-DIm-Y6b3OlcP9bVHWvPQPfEN9yD8m_smdJFDys; SameSite=Lax; Path=/; HTTPOnly
```
and discared with the next response like this
```
Set-Cookie:PLAY_FLASH=; Max-Age=-86400; Expires=Sun, 30 Jul 2017 09:53:56 GMT; Path=/; HTTPOnly
```

Unfortunately, there are browser who tend to treat a cookie with a negative Max-Age as a session cookie. Once Play tries to discard the flash cookie, these clients have a session cookie with an empty value they send with each subsequent request from then on. Play then tries to decode the empty cookie (first JWT, then URI as fallback) and fails with the following exception

```
java.lang.ArrayIndexOutOfBoundsException: 1
 at play.api.mvc.UrlEncodedCookieDataCodec.$anonfun$decode$2(Cookie.scala:507) 
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234) 
 at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32) 
 at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29) 
 at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191) 
 at scala.collection.TraversableLike.map(TraversableLike.scala:234) 
 at scala.collection.TraversableLike.map$(TraversableLike.scala:227) 
 at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:191) 
 at play.api.mvc.UrlEncodedCookieDataCodec.urldecode$1(Cookie.scala:507) 
 at play.api.mvc.UrlEncodedCookieDataCodec.decode(Cookie.scala:536) 
 at play.api.mvc.UrlEncodedCookieDataCodec.decode$(Cookie.scala:501) 
 at play.api.mvc.DefaultUrlEncodedCookieDataCodec.decode(Cookie.scala:750) 
 at play.api.mvc.FallbackCookieDataCodec.decode(Cookie.scala:745) 
 at play.api.mvc.FallbackCookieDataCodec.decode$(Cookie.scala:732) 
 at play.api.mvc.DefaultFlashCookieBaker.decode(Flash.scala:91) 
 at play.api.mvc.CookieBaker.decodeFromCookie(Cookie.scala:431) 
 at play.api.mvc.CookieBaker.decodeFromCookie$(Cookie.scala:428) 
 at play.api.mvc.DefaultFlashCookieBaker.decodeFromCookie(Flash.scala:91) 
 at play.api.mvc.request.DefaultRequestFactory$$anon$3.create(RequestFactory.scala:119) 
 at play.api.mvc.request.DefaultRequestFactory$$anon$3.create(RequestFactory.scala:117) 
 at play.api.mvc.request.LazyCell.value(Cell.scala:66) 
 at play.core.server.common.ServerResultUtils.prepareCookies(ServerResultUtils.scala:227) 
 at play.core.server.AkkaHttpServer.$anonfun$executeAction$3(AkkaHttpServer.scala:303) 
 at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) 
 at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51) 
 at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) 
 at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109) 
 at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71) 
 at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68) 
 at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284) 
 at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284) 
 at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284) 
 at scala.concurrent.Promise.complete(Promise.scala:49) 
 at scala.concurrent.Promise.complete$(Promise.scala:48) 
 at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183) 
 at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:38) 
 at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) 
 at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) 
 at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91) 
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) 
 at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81) 
 at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91) 
 at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38) 
 at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43) 
 at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) 
 at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) 
 at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) 
 at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

`UrlEncodedCookieDataCodec` catches this exception, so it doesn't break anything, but we're getting ~20k - 30k of those exceptions in our log each day.
Looking at https://docs.oracle.com/javaee/7/api/javax/servlet/http/Cookie.html#setMaxAge-int- it seems like the Cookie should be deleted with `Max-Age=0` rather than with a negative value.

I will update if i find out which browsers are actually affected.
Edit: Cannot actually be limited to specific browsers. I'm getting empty PLAY_FLASH Cookies for IE 11, FF 53, Chrome 59 (both Desktop and Android), Safari 9 on iOS 9.3, Safari 10.1 on Mac OS X and others, so it seems to affect pretty much anything out there.

**Comment by gmethvin** [comment]
Can you provide a set of steps to reproduce? I'm doing the following steps (in Chrome on Mac):

 1. Start with https://github.com/playframework/play-scala-starter-example/
 1. Add an action using flash: `def flashing = Action { Redirect("/").flashing("foo" -> "bar") }`
 1. Clear browser cookies for localhost:9000
 1. Navigate to `/flashing`. Play responds with `Set-Cookie: PLAY_FLASH=eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImZvbyI6ImJhciJ9LCJuYmYiOjE1MDE1NDIwODcsImlhdCI6MTUwMTU0MjA4N30.Q2Y-vmtXk_9_dRICdyZmJMb5UJyR42keSlJ1pxA-_z0; SameSite=Lax; Path=/; HTTPOnly`
 1. Browser loads index (`/`) page. Browser sends `Cookie: PLAY_SESSION=eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImNzcmZUb2tlbiI6ImU0YzM3NTQxNjhiYWU1NTkyODQzMThjMjJlOWRmZTA2YWE5ZGJhNzItMTUwMTU0MTM4NzczMS0yNTllM2FiNmE1OWNiYWVhNDE1MmY5NjMifSwibmJmIjoxNTAxNTQxMzg3LCJpYXQiOjE1MDE1NDEzODd9.LNmD1l_ttrplF8bpm0l9Dl7j7yYxOsqMhuOZYVWk2Os; PLAY_FLASH=eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImZvbyI6ImJhciJ9LCJuYmYiOjE1MDE1NDIwODcsImlhdCI6MTUwMTU0MjA4N30.Q2Y-vmtXk_9_dRICdyZmJMb5UJyR42keSlJ1pxA-_z0`
 1. Play sends `Set-Cookie: PLAY_FLASH=; Max-Age=-86400; Expires=Sun, 30 Jul 2017 23:01:27 GMT; Path=/; HTTPOnly`
 1.  Reload index page from browser. Browser sends `Cookie: PLAY_SESSION=eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImNzcmZUb2tlbiI6ImU0YzM3NTQxNjhiYWU1NTkyODQzMThjMjJlOWRmZTA2YWE5ZGJhNzItMTUwMTU0MTM4NzczMS0yNTllM2FiNmE1OWNiYWVhNDE1MmY5NjMifSwibmJmIjoxNTAxNTQxMzg3LCJpYXQiOjE1MDE1NDEzODd9.LNmD1l_ttrplF8bpm0l9Dl7j7yYxOsqMhuOZYVWk2Os` (*no flash cookie*)

So it seems to me everything is working as expected. I don't get any exceptions.

Also, according to the spec, a negative max-age is acceptable to clear a cookie (see https://tools.ietf.org/html/rfc6265#section-5.2.2):

> If delta-seconds is less than or equal to zero (0), let expiry-time be the earliest representable date and time.  Otherwise, let the expiry-time be the current date and time plus delta-seconds seconds. 

Play does not use the servlet API, so the fact that the Cookie implementation from the servlet API uses negative values to represent a non-persistent session cookie is irrelevant here. Play chooses to use a negative value to keep it consistent with `Expires`, and it uses a date in the past for `Expires` to support older browsers without support for `Max-Age` whose clock may not be in sync with the server.

**Comment by richdougherty** [comment]
The comments here on Max-Age might be relevant:

https://stackoverflow.com/a/28914420/49630

**Comment by el-dom** [comment]
> I'm doing the following steps (in Chrome on Mac):
I tried to reproduce it on linux using chrome and firefox and also failed. But according to this testcase https://inikulin.github.io/cookie-compat/#MOZILLA0001 there are versions of IE 11 and Edge that ignore max-age attributes (while the chrome you are using handles it correctly), which might explain why they keep resending the cookie with an empty value.
That leaves me wondering why i recorded empty PLAY_FLASH values for all kinds of browsers, but right now my money would be on Internet Explorer being the culprit.
Since i do not have those old browser versions, i cannot actually prove it, but 30k Exceptions/day make me tend to believe it's a broadly used browser like IE.

**Comment by gmethvin** [comment]
Can you give us more info about where you're using `flashing`? You're only using it on redirect responses, right?

**Comment by gmethvin** [comment]
@el-dom In your initial report you said:

> I'm getting empty PLAY_FLASH Cookies for IE 11, FF 53, Chrome 59 (both Desktop and Android), Safari 9 on iOS 9.3, Safari 10.1 on Mac OS X and others, so it seems to affect pretty much anything out there.

so I had assumed it wasn't a browser specific issue. We always send both the Max-Age and Expires on the cookie, so IE should look at Expires if it doesn't support Max-Age.

Assuming we don't know which browser it is, my suspicion is something is misconfigured on the client. It could be that it doesn't support max-age (like IE), and the clock is set such that setting Expires a day in the past isn't good enough. It could also be something like a crawler that doesn't properly follow the cookie spec. Hard to tell without more info on the client. There are a couple things we could do to further mitigate these issues:
 - special handling for maxAge <= 0 that sets Expires to some constant date far in the past (e.g. Jan 1 1970)
 - ignore empty cookies to avoid throwing the exception
 - catch the exception on decoding and report as only a warning (to avoid other noise in logs)

**Comment by el-dom** [comment]
>Can you give us more info about where you're using flashing? You're only using it on redirect responses, right?

Right, only on redirects. Looks like this
```scala
SeeOther(
      routes.PaymentController.show().absoluteURL()
    ).flashing(("error", Messages("payment.error.transaction.incomplete.fallback")))
```
I'm somewhat frustrated by this since what i said still stands: I'm seeing this for all kinds of browser but still cannot reproduce it myself. I added filter looking like this

```scala
@Singleton
class PlayFlashCookieFilter @Inject()(flashCookieBaker: FlashCookieBaker, implicit val mat: Materializer)
    extends Filter
    with HeaderNames
    with TracedLogging {
  override def apply(next: RequestHeader => Future[Result])(request: RequestHeader): Future[Result] = {
    request.cookies
      .get(flashCookieBaker.COOKIE_NAME)
      .foreach(c => log.debug(Request, s"Received flash cookie with value '${c.value}' from ${request.headers(USER_AGENT)}"))

    next(request)
  }
}
```
and ended up receiving log messages like these:
`Received flash cookie with value '' from Mozilla/5.0 (Linux; Android 4.4.4; GT-I9195I Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36`
`Received flash cookie with value '' from Mozilla/5.0 (Linux; Android 7.0; SM-G920F Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36`
`Received flash cookie with value '' from Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36`
`Received flash cookie with value '' from Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36`
`Received flash cookie with value '' from Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:54.0) Gecko/20100101 Firefox/54.0`

So pretty much anything out there seems to be sending empty flash cookies. This is why i wrote what you quoted. But i simply have no explantion for this.
Maybe something like this would suffice to temper it?

```scala
def urldecode(data: String) =
    if (data.nonEmpty) {
      data
        .split("&")
        .map(_.split("=", 2))
        .map(p => URLDecoder.decode(p(0), "UTF-8") -> URLDecoder.decode(p(1), "UTF-8"))
        .toMap
    } else {
      Map.empty
    }
```

**Comment by gmethvin** [comment]
@el-dom I'm assuming you're printing the User-Agent string there. It's possible (and often the case) that crawlers and bots will use user agent strings from common browsers to hide their true identity. Hard to say if that's what's happening here but maybe that's why you can't reproduce it yourself.

I agree at very minimum we should avoid throwing an exception when passed an empty cookie. I submitted #7688 to fix that. Still, I would like to get to the bottom of what the real problem is here. Though I guess from a practical point of view, if the cookie is empty, it doesn't matter that much as long as it doesn't affect how your application works.

**Comment by el-dom** [comment]
Great! Thank you! Yes, it doesn't affect the app, since the exception gets caught. It's a lot of noise in the log though, so i'm glad this will be silenced. I'm wondering how to continue with this issue now. I guess since i still cannot find a way to reproduce it, we should close it as "won't fix". What do you think?

**Comment by richdougherty** [comment]
@el-dom, without knowing which browser is the problem, the only other thing I can think of is to write a Selenium test and use something like https://saucelabs.com/ to run tests across lots of different browsers. That would be a lot of effort though, so unless someone volunteers to do it we should probably close the ticket for now.

**Comment by el-dom** [comment]
Alright then. Closing, since it cannot be reproduced and https://github.com/playframework/playframework/pull/7688 should avoid the exception.

**Comment by richdougherty** [comment]
Hi @el-dom, we've just released Play 2.6.3 which should reduce the number of errors turning up in your logs. If you get a chance it would be great if you could check it out and let us know how you get on. Thanks!

**Comment by el-dom** [comment]
Looking good. The Exceptions are gone. Thank you guys!

**Comment by richdougherty** [comment]
Great, glad it's working!
