### ISSUE TITLE
[doc]: link to Akka configuration reference is broken

### ISSUE THREAD

**Issue by sarathraj-coder** [playframework/playframework#7683]
link : https://www.playframework.com/documentation/2.6.x/ThreadPools

location : 

The full configuration options available to you can be found here and the link is 
http://doc.akka.io/docs/akka/2.5/general/configuration.html#Listing_of_the_Reference_Configuration is broken

**Comment by marcospereira** [comment]
Thank you, @sarathraj-coder.

Do you want to submit a PR to fix that? I think the new link is:

http://doc.akka.io/docs/akka/2.5.3/java/general/configuration.html#listing-of-the-reference-configuration

**Comment by sarathraj-coder** [comment]
yes , how to fix that doc

**Comment by richdougherty** [comment]
Hi @sarathraj-coder, thanks for helping! You can fix it like this:

1. Go to this page: https://github.com/playframework/playframework/blob/master/documentation/manual/working/commonGuide/configuration/ThreadPools.md
2. Click on the pencil icon to edit the page.
3. Make the changes using the editor.
4. At the bottom of the page under the "Commit changes" heading.
5. Enter a brief description of the change in the title.
6. Put "Fixes #7683" into the extended description field.
7. Select "Create a new branch for this commit and start a pull request."
8. Choose a branch name.
9. Click "Propose file change".
