### ISSUE TITLE
Cannot retrieve attributes from TypedMap

### ISSUE THREAD

**Issue by chorandrey** [playframework/playframework#7707]
### Expected/Actual Behavior

I'm trying to set attributes for incoming request using methods for request - "addAttr" and "withAttrs" and as result I get new instance of Request[A]. Attributes seems to be set successfully, but I **cannot retrieve** these attributes from request.

### Reproducible Test Case

```scala
class CustomController @Inject() (cc: ControllerComponents) extends AbstractController(cc) {
  def checkAttributes = Action { oldReq: Request[AnyContent]=>

    val newReq = oldReq.addAttr(TypedKey[String]("param"), "value")
    println("newReq attrs: " + newReq.attrs)
    println("newReq param: " + newReq.attrs.get(TypedKey[String]("param")))

    val newReq2 = oldReq.withAttrs(TypedMap(TypedKey[String]("param") -> "value"))
    println("newReq2 attrs: " + newReq2.attrs)
    println("newReq2 param: " + newReq2.attrs.get(TypedKey[String]("param")))

    Ok(oldReq.attrs.toString)
  }
}
```

### Output out of this demo

**newReq attrs**: {Session -> Container<Session(Map())>, **param -> value**, Flash -> Container<?>, HandlerDef -> HandlerDef(ReloadableClassLoader(v2){file:/C:/Users/Andrey/Desktop/bug%20-%20attrs/target/scala-2.12/classes/},router,controllers.CustomController,checkAttributes,List(),GET,/, An example controller showing a sample home page,List()), Id -> 2, Tags -> Map(ROUTE_COMMENTS ->  An example controller showing a sample home page, ROUTE_PATTERN -> /, ROUTE_CONTROLLER -> controllers.CustomController, ROUTE_ACTION_METHOD -> checkAttributes, ROUTE_VERB -> GET), Cookies -> Container<Map(SessionId -> Cookie(SessionId,55f5b1a9def8e079699ae5da9bbbdde301958ab4,None,/,None,false,true,None))>, TOKEN_INFO -> play.filters.csrf.CSRF$TokenInfo@4384da97}
**newReq param**: None
**newReq2 attrs:** {**param -> value**}
**newReq2 param**: None

**Comment by pettyjamesm** [comment]
TypedKey instances are stored in the request TypedMap based on identity. To use them correctly, you have to store the TypedKey instance into a val and reuse the same val instance for retrieval.

**Comment by richdougherty** [comment]
Yes @pettyjamesm is correct on this one.

@chorandrey I'm almost 100% certain that this is the issue so I'll close the ticket for now. If you continue to have problems please reply and we can re-open it.

**Comment by chorandrey** [comment]
Thanks you guys! That's enough to get what I deal with. Sorry for disturb

**Comment by richdougherty** [comment]
No worries, we appreciate the report. :)
