### ISSUE TITLE
Updating project to sbt 1.0 

### ISSUE THREAD

**Issue by Shenker93** [playframework/playframework#7728]
Hello! I'm trying to update sbt to latest version, however, got an error after sbt compile command:

_sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.play#sbt-plugin;2.6.2: not found_

Should it be fixed in project settings or requires changes in play framework itself?

### Play Version (2.5.x / etc)
2.6.2

### API (Scala / Java / Neither / Both)
Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Ubuntu 17.04

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Oracle 1.8.0_144

**Comment by PromanSEW** [comment]
See #7366 and https://github.com/playframework/interplay/pull/32

**Comment by richdougherty** [comment]
We need to re-work the build system for Play - and everything it depends on - to get this working. We are planning on getting it ready for a 2.6.x milestone soon, but it will take some work. :)

I'm going to close this issue because this is already a planned feature.
