### ISSUE TITLE
JavaWebSockets 2.6.x documentation page examples not compiling

### ISSUE THREAD

**Issue by JFCote** [playframework/playframework#7739]
### Play Version

2.6.X

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

1.8

### Expected Behavior

The examples in the documentation should compile.

### Actual Behavior

In this page:

https://www.playframework.com/documentation/2.6.x/JavaWebSockets

The examples below does not compile 

https://www.playframework.com/documentation/2.6.x/JavaWebSockets#Handling-WebSockets-with-actors

The function `ActorFlow.actorRef` seems to need 2 more parameters (`bufferSize` and `overflowStrategy`). And even if you add them, this error pops:

```
Method actorRef in class play.api.libs.streams.ActorFlow cannot be applied to given types;
  required: scala.Function1<akka.actor.ActorRef,akka.actor.Props>,int,akka.stream.OverflowStrategy,akka.actor.ActorRefFactory,akka.stream.Materializer
  found: MyWebSocke[...]props,int,akka.stream.OverflowStrategy,akka.actor.ActorSystem,akka.stream.Materializer
  reason: cannot infer type-variable(s) In,Out
    (argument mismatch; scala.Function1 is not a functional interface
      multiple non-overriding abstract methods found in interface scala.Function1)
```

By the way, the example in the same page but for Play 2.5.X is still using LegacyWebSocket which is deprecated. It should be updated to use WebSocket like in Play 2.6.X.
https://www.playframework.com/documentation/2.5.x/JavaWebSockets

**Comment by wsargent** [comment]
The documentation for "Handling Websockets with actors" is here:

https://github.com/playframework/playframework/blob/2.6.x/documentation/manual/working/javaGuide/main/async/JavaWebSockets.md#handling-websockets-with-actors

and the code example is here:

https://github.com/playframework/playframework/blob/2.6.x/documentation/manual/working/javaGuide/main/async/code/javaguide/async/websocket/HomeController.java

The test code compiles because it's run as part of the release, so something else must be happening.  It's not text inside Markdown, it's actually a file.

**Comment by richdougherty** [comment]
I've noticed that Java's type inference algorithm has changed between different versions of Java. Are you using the latest version of Java?

**Comment by JFCote** [comment]
Thanks for the quick feedback @wsargent  and @richdougherty.  To be honest, I have copy pasted this code and included it in my big application. I will start by downloading the complete example and test it standalone. If it doesn't work, I will see if my java version might be a problem. I know I'm using java 8 but not sure if it's the latest.

I'll keep you updated on what I found.

**Comment by JFCote** [comment]
@wsargent : I just found the problem.

Using IntelliJ, while importing, by default it used:
`import play.api.libs.streams.ActorFlow;`

When your example used:
`import play.libs.streams.ActorFlow;`

When using the right import, everything compiles. Sorry for the confusion.

**Comment by marcospereira** [comment]
Closing then.

Thanks for the feedback, @JFCote. :-)
