### ISSUE TITLE
LowPriorityWrites.traversableWrites does not preserve order for SortedSet

### ISSUE THREAD

**Issue by t3hnar** [playframework/playframework#7750]
### Play Version 2.6.3

I found that `LowPriorityWrites.traversableWrites` does not preserve the order.
For instance we have `SortedSet` of elements, however json has wrong output because of
`as.map(w.writes(_))`
I suppose it should be something like `as.toSeq.map(w.writes(_)`

**Comment by cchantep** [comment]
Hi,

Please note that it's rather related to the project [play-json](http://github.com/playframework/play-json).

Also note that as indicated in the [guidelines](https://github.com/playframework/playframework/blob/master/.github/ISSUE_TEMPLATE.md), it's recommended to use the [MailingList](https://groups.google.com/forum/#!forum/play-framework) to first ask question/for help, this tracker being dedicated to confirmed issue.

Moreover, I would first make sure to use an immutable `SortedSet`, as below.

```
scala> Json.toJson(scala.collection.mutable.SortedSet(1, 2, 3))
res7: play.api.libs.json.JsValue = [2,1,3]

scala> Json.toJson(scala.collection.immutable.SortedSet(1, 2, 3))
res8: play.api.libs.json.JsValue = [1,2,3]
```

**Comment by t3hnar** [comment]
@cchantep sorry for inconvenience, will repost to the play-json, as I still think it is an issue even with mutable data structure.
