### ISSUE TITLE
Play 2.6.3 | Override property play.server.http.idleTimeout in dev / test mode

### ISSUE THREAD

**Issue by larede** [playframework/playframework#7752]
In dev and test mode I can't override this property in my application.conf. Example:
play.server.http.idleTimeout = null

https://www.playframework.com/documentation/2.6.x/Migration26#akka-http-as-the-default-server-engine

Can you help please?

**Comment by marcospereira** [comment]
Hi @larede,

There are some configurations that aren't picked when using `run` command. See here:

https://www.playframework.com/documentation/2.6.x/ConfigFile#Using-with-the-run-command

See also the note at the end of this documentation page:

https://www.playframework.com/documentation/2.6.x/SettingsAkkaHttp#Configuring-the-Akka-HTTP-server-backend

Can you confirm that using `devSettings` or passing `-Dplay.server.http.idleTimeout=null` works as you expect?

**Comment by larede** [comment]
Hi @marcospereira,
Thanks for your replay.

I confirm that if I run the play with command `sbt run -Dplay.server.http.idleTimeout=180s` works fine. :)

I could not use `-Dplay.server.http.idleTimeout=null`. Error: `com.typesafe.config.ConfigException$BadValue: system properties: Invalid value at 'http.idleTimeout': No number in duration value 'null'`

According to the documentation would be possible.
https://www.playframework.com/documentation/2.6.x/SettingsAkkaHttp
>  The idle timeout for an open connection after which it will be closed
Set to null to disable the timeout
idleTimeout = 75 seconds

Also try with "infinite" and it also does not work ...

**Comment by marcospereira** [comment]
Thank you, @larede.

See #7762 for a fix. It is backward compatible so that we can backport it to 2.6.x later. As a workaround, you can set the timeout to a really long value now.
