### ISSUE TITLE
Custom Databinder and i18N always load default value

### ISSUE THREAD

**Issue by Flo354** [playframework/playframework#7756]
### Play Version (2.5.x / etc)
2.6.3

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Linux Ubuntu 4.10.0-32-generic #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### Expected Behavior
According to the [custom databinder documentation](https://www.playframework.com/documentation/2.6.x/JavaForms#Register-a-custom-DataBinder)

> When the binding fails an array of errors keys is created, the first one defined in the messages file will be used. This array will generally contain:
["error.invalid.< fieldName >", "error.invalid.< type >", "error.invalid"]

I have a form like that
```java
public class CreateOrganizationForm {

    @Constraints.Required
    private Phonenumber.PhoneNumber phone;

    public Phonenumber.PhoneNumber getPhone() {
        return phone;
    }

    public void setPhone(Phonenumber.PhoneNumber phone) {
        this.phone = phone;
    }
}
```

and my messages file contains:
`error.invalid.phone=A valid phone number is required`

When an invalid phone number is sent, i expect to receive the message:

> A valid phone number is required

### Actual Behavior

I receive the message: 

> Invalid value

which is the default value...

### Linked pull request

Please note that I can not test the key **error.invalid.< type >** since it is a nested class and I can't use **$** symbols in messages files.
#7755 

### Linked discussion

[https://groups.google.com/forum/#!topic/play-framework/5XVJ0U52MFg](https://groups.google.com/forum/#!topic/play-framework/5XVJ0U52MFg)

**Comment by mkurz** [comment]
@Flo354 
I can not reproduce this issue.
I set up a very simple demo project, which behaves correctly, it displays the value of the `error.invalid.phone` message key:
https://github.com/mkurz/play-dataBinder-issue-7756

Please check out this project and run it via `sbt run`. Enter some string in the textbox and submit the form. You will see it works and the correct message gets displayed.
I think you have a problem in your project setup? In which files exactly do you define your messages?

**Comment by Flo354** [comment]
Ok, got it!

Logger.debug(submittedForm.errorsAsJson().toString());
it shows me (on your project): {"phone":["Sorry to tell you, but this field in invalid!"]}

Look at the order of the keys: 
```java
            for(ValidationError error: submittedForm.allErrors()) {
                Logger.debug(error.key());
                error.messages().forEach(Logger::debug);
            }```

> [debug] application - phone
[debug] application - error.invalid
[debug] application - error.invalid.phone

**Comment by Flo354** [comment]
What is weird is: 
```java
 for(ValidationError error: submittedForm.allErrors()) {
      Logger.debug(error.key());
      error.messages().forEach(Logger::debug);
      // if I add this code
      Logger.debug(error.message());
 }
```

It output the correct key: 

> [debug] application - error.invalid.phone

So why the method **errorsAsJson** takes **error.invalid**?

**Comment by Flo354** [comment]
Okay.

From [ValidationError.java](https://github.com/playframework/playframework/blob/master/framework/src/play-java-forms/src/main/java/play/data/validation/ValidationError.java#L70) (lines 70 - 72): 
```java
    public String message() {
        return messages.get(messages.size()-1);
}
```

But from [Form.java](https://github.com/playframework/playframework/blob/master/framework/src/play-java-forms/src/main/java/play/data/Form.java#L725) (line 725):
```java
messages.add(messagesApi.get(lang, error.messages(), translateMsgArg(error.arguments(), messagesApi, lang)));
```

You are giving the raw error.messages()
which is: [error.invalid, error.invalid.phone]

IMO there are two options:

1. You reverse the list in the method
2. You build the list in reverse order

Hope it will help

**Comment by mkurz** [comment]
Thanks I already found this out and working on a fix.
I think for now we should just reverse the field in the `errorsAsJson` method before passing it to `messagesApi.get` so we don't break compatibility for people currently relying on the order.

**Comment by mkurz** [comment]
Fix is here: #7757

@Flo354 thanks for reporting all these issues!

**Comment by Flo354** [comment]
Thanks @mkurz for the explanation on your PR I learned some things on how the translation system works!

**Comment by mkurz** [comment]
@Flo354 All pull requests have been merged and will land in Play 2.6.4. Let me know if it works for you then.

**Comment by Flo354** [comment]
@mkurz As soon as Play 2.6.4 will be available I will test the and come back to you.

Thanks,

**Comment by mkurz** [comment]
@Flo354 Play 2.6.5 is out (don't use 2.6.4)

**Comment by Flo354** [comment]
@mkurz problem solved!

Thanks again

**Comment by mkurz** [comment]
@Flo354 Good to hear :+1:
