### ISSUE TITLE
Support groovy logback configuration

### ISSUE THREAD

**Issue by udalrich** [playframework/playframework#7767]
I have a logback.groovy configuration file which I am trying to use, but it is interpreted as an xml config file (even though the name ends with .groovy).  I have provided details at https://stackoverflow.com/questions/38531771/configure-play-framework-logging-with-logback-groovy.

Since the groovy file is initially parsed, either `play.api.libs.logback.LogbackLoggerConfigurator` could be modified to handle groovy config files or there needs to be a way to not run run play logging configurator.  If that already exists, the documentation needs to be updated to indicate how to do so.

**Comment by marcospereira** [comment]
Hi @udalrich,

It is already possible to use your own `LoggerConfigurator` as documented here:

https://www.playframework.com/documentation/2.6.x/SettingsLogger#Using-a-Custom-Logging-Framework

The documentation is focusing on how to use another log framework, but `play.logger.configurator` can be used to do what you described.
