### ISSUE TITLE
Play seems to generate reverse route even if not requested

### ISSUE THREAD

**Issue by JFCote** [playframework/playframework#7775]
### Play Version (2.5.x / etc)

2.5.15

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

JDK 1.8.0_144

### Expected Behavior

1. I have a function in my Controller. This function is NOT listed in the `play.routing.JavaScriptReversRtouer.create` function.
2. No reverse routing related files should be generated with this function name.

### Actual Behavior

1. I have a function in my Controller. This function is NOT listed in the `play.routing.JavaScriptReversRtouer.create` function.
2. When I do a search using IntelliJ, I can see that the function can be found in multiple "ReverseRouting" generated files, which is wrong. 

In fact, there should be no mention of this function or the controller in any of the ReverseRouter files. 

![reverse router](https://user-images.githubusercontent.com/14336900/29926630-037ac70c-8e32-11e7-8c82-1f203f4e33a6.PNG)

Please note that I use the reverseRouting in this project, but in other controller/method, not this one. This one should not be in it at all.

**Comment by gmethvin** [comment]
This is not a bug. The `JavaScriptReverseRouter.create` method only applies to the *JavaScript code* generated by that method. It does not affect generated reverse routes in the Scala routing code generated by Play.

**Comment by JFCote** [comment]
Hi @gmethvin , thanks for the clarification.
Can you explain why Play needs to generate "reverse routes" in the scala routing code?

I ask this because we have awful compilation times. I say compilation times but the compilation itself is like 20 seconds. But then after that, it starts to generates a LOT of files which may take up to 15 minutes. Since these files all have the word "reverse router" in it, we thought that they might be linked to the javascript reverse router but now it seems it might be linked to the scala reverse routing code.

Is there any way to turn that off?

**Comment by gmethvin** [comment]
@JFCote it's hard to say if that's the main cause of the slow compilation times, but you can disable reverse routes generation with:
```scala
generateReverseRouter := false
```
in your `build.sbt` (see https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala#L23).

If you need more help debugging your slow compilation times, I'd suggest asking on the mailing list: https://groups.google.com/forum/#!forum/play-framework

**Comment by JFCote** [comment]
Ok thanks @gmethvin . But one last question, after that I will use the mailing list.

If I set the `generateReverseRouter` to false, will the Javascript Reverse Routing will work anyway ?

**Comment by gmethvin** [comment]
It wouldn't work in the normal way since the JavaScript reverse routes would not be generated. You'd need to write the JavaScript functions yourself.

**Comment by sjaanus** [comment]
@JFCote  did you solve this? I am having long compilation times and also see a lot of reverse routing in my logs. I would like to disable backend reverse routing and keep the JavaScript ones. 

@gmethvin Or write the JavaScript functions myself. Could you point me to the source code of the JavaScript reverse router play framework has.

**Comment by JFCote** [comment]
@sjaanus After a lot of time wasted on many experiment, this is what I have compiled and the solution we still use today: https://medium.com/@jfcote/the-ultimate-solution-to-play-framework-slow-compilation-53f4fd499df4

**Comment by sjaanus** [comment]
@JFCote oh that was your article. I have read that multiple times. Also have playEnhancerEnabled set to false, but it did not much help. It is not really a huge too complicated project, about 150 routes, 74 db tables, REST based, lots of CRUD operations.

Compliation from 0 takes exactly 2 minutes.
Changing 1 class, reload takes ~35 seconds.

The first compilation time I can live with, but changing 1 class, the 35 seconds wait is a huge pain. Any suggestions?

**Comment by JFCote** [comment]
@sjaanus I don't think here is the best place to talk about this, feel free to come and talk to me on Gitter. I might not answer in real time but I can try to help you. But out of the box I would say that using interface everywhere has the best change to help you if it's not already done. For every service, have an interface instead of the implementation in your injection. That way, Play doesn't have to know everything when compiling.
