### ISSUE TITLE
Uncomfortable highlighting style

### ISSUE THREAD

**Issue by Abrasha** [playframework/playframework#7776]
I am quiet discouraged about highlighting of key words in manuals.
I think that line spacing should be increased a bit because it is really hard to read.

What do you think?

![horrible_style](https://user-images.githubusercontent.com/11317222/29927347-c021ebf6-8e6e-11e7-908f-b3884e1a2d01.png)

Link: https://www.playframework.com/documentation/2.6.x/GlobalSettings

Browsers: Chrome, Mozilla

**Comment by richdougherty** [comment]
I'm personally happy to change the style. This would be a change over here: https://github.com/playframework/playframework.com

**Comment by richdougherty** [comment]
Just to be clear, I'm happy for the style to change, but hopefully someone will contribute an improvement. ;)

**Comment by Abrasha** [comment]
@richdougherty I am really happy to contribute, but I am not sure how to achieve this and even which people to tag for pointing

**Comment by richdougherty** [comment]
Hi @Abrasha, the first step would be to clone the https://github.com/playframework/playframework.com repo and try and get it to run locally on your machine. Then try changing the styling, e.g. https://github.com/playframework/playframework.com/tree/master/app/assets/css.

If you have any questions you can ask on the dev mailing list or on https://gitter.im/playframework/contributors.

**Comment by Abrasha** [comment]
@richdougherty awesome, will take case of it on weekend (:
Will try to keep this ticket up to date to pick up the best solution

**Comment by richdougherty** [comment]
@Abrasha, actually would you mind creating a ticket over on the https://github.com/playframework/playframework.com repo instead? We'll see your updates there too.

**Comment by marcospereira** [comment]
Closing in favor of playframework/playframework.com#170.
