### ISSUE TITLE
Incorrect label on Java Play 2.6.x Examples

### ISSUE THREAD

**Issue by sivakumar-raja** [playframework/playframework#7781]
Under Java Play 2.6.x examples section on the following [url](https://playframework.com/download) there are couple of sample projects with the same name, **Play Java REST API Example** but the github link for one project points to [this](https://github.com/playframework/play-java-rest-api-example/tree/2.6.x) and another one point to [this](https://github.com/playframework/play-java-forms-example/tree/2.6.x).

**Comment by wsargent** [comment]
That looks like the example code service, pinging @corruptmemory

**Comment by gmethvin** [comment]
Should be fixed now
