### ISSUE TITLE
Page not found [ libs/json/JsPath.html ]

### ISSUE THREAD

**Issue by hepin1989** [playframework/playframework#7787]
Could not found the JsPath document 

https://www.playframework.com/documentation/2.6.x/api/libs/json/JsPath.html

**Comment by benmccann** [comment]
I think it's here: https://www.playframework.com/documentation/2.6.1/ScalaJson#JsPath

**Comment by marcospereira** [comment]
The correct link would be:

https://www.playframework.com/documentation/2.6.x/api/scala/play/api/libs/json/JsPath.html

**Comment by marcospereira** [comment]
By the way, I'm not sure why this is not being picked when running the validate docs task.

**Comment by gmethvin** [comment]
Should be correct now (see https://www.playframework.com/documentation/2.6.x/ScalaJson#JsPath)
