### ISSUE TITLE
Document usage of List in routes

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#7788]
[The docs](https://www.playframework.com/documentation/2.6.x/JavaRouting) mention offhand that `List[String]` is a valid parameter type, but don't say how to use it. I was trying a bunch of stuff like `param=a,b,c,d` that wasn't working. I finally saw somewhere that suggested the usage might be `param=a&param=b&param=c&param=d` (note I haven't tried that syntax, so am not 100% certain it works)

**Comment by marcospereira** [comment]
The correct syntax is `param[0]=a&param[1]=b&param[2]=c` to have orderered params. You can also use `param[]=a&param[]=b&param[]=c` which does not guarantee any order.

For anyone taking care of this issue, is also possible to populate inner objects like:

```java
public class Foo {
    public String a;
    public String b;
}

public class Bar {
    public List<Foo> foos;
}
```

And have parameters like `foos[0].a=somethingA&foos[0].b=somethingB`. A pull request would be very welcomed here. :-)

**Comment by Shruti9520** [comment]
@marcospereira @benmccann Can I work on this issue? :)

**Comment by benmccann** [comment]
Yes. Thank you!

**Comment by amtj** [comment]
@Shruti9520 Sorry for the pull request. Did not see your comment. Hope you can work on any other issue :)

**Comment by Shruti9520** [comment]
@amtj No worries. :)

**Comment by mkurz** [comment]
@marcospereira Your [above comment](https://github.com/playframework/playframework/issues/7788#issuecomment-326999740) is not correct.

> The correct syntax is `param[0]=a&param[1]=b&param[2]=c` to have orderered params. You can also use `param[]=a&param[]=b&param[]=c` which does not guarantee any order.
> ...

This is not true how lists are handled regarding query parameters. The only valid way to define a list in query params is via the `param=a&param=b&param=c&param=d` syntax. What you are talking about is how lists in _forms_ [can be bound](https://www.playframework.com/documentation/2.7.x/ScalaForms#Repeated-values) where the syntax you mentioned actually does work.

To be 100% sure I did a quick manual test and even digged into the source code of the akka-http and netty server backend, where its clear that _only_ the `param=a&param=b...` syntax is supported:

**akka-http:**
https://github.com/playframework/playframework/blob/25615dc6e2c56423574b5110aaf697ffa2d427b5/transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala#L114

where `toMultiMap` does:
https://github.com/akka/akka-http/blob/0ac527a3be7924206e5508ca86e10edfd54bbc1d/akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala#L615-L634

**netty:**
https://github.com/playframework/playframework/blob/f0a59d73fa1c3f84b3d7459c199e40e615d7cf2e/transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala#L107

where netty's `QueryStringDecoder` works the same way:
https://github.com/netty/netty/blob/ff7a9fa091a8bf2e10020f83fc4df1c44098bbbb/codec-http/src/main/java/io/netty/handler/codec/http/QueryStringDecoder.java#L207
