### ISSUE TITLE
docs say Mockito is included but it's not

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#7796]
This page https://www.playframework.com/documentation/2.6.x/JavaTest states

_The Mockito library is included in your project build to assist you in using mocks._

but this doesn't appear to be true.  I needed to include

`"org.mockito" % "mockito-core" % "2.9.0"`

in the `libraryDependencies` section of my `build.sbt` file in order for Mockito classes to be available.

**Comment by marcospereira** [comment]
Thank you, @rmcloughlin.

Do you want to submit a pull request to correct the docs?

**Comment by KukkadapuSushma** [comment]
Can I take up this issue, as a new beginner here!
Also, I would like to know, whether this issue is about changing " mockito build"  information presented in docs?

**Comment by gmethvin** [comment]
In the [Java testing docs](https://www.playframework.com/documentation/2.6.x/JavaTest#mocks) we should mention the need to add the mockito dependency (`libraryDependencies += "org.mockito" % "mockito-core" % "2.9.0"`)

I also noticed in the [docs on ScalaTest with Mockito](https://www.playframework.com/documentation/2.6.x/ScalaTestingWithScalaTest#Mockito) we have the wrong package name in the link for `MockitoSugar`. It should be http://doc.scalatest.org/3.0.1/index.html#org.scalatest.mockito.MockitoSugar.
