### ISSUE TITLE
Truncated response from ajax (javascript router) call

### ISSUE THREAD

**Issue by fabgilson** [playframework/playframework#7797]
### JDK Oracle 1.8.0_144

Response from Ajax request (using the play.routing.JavaScriptReverseRouter) is truncated. This feature was working in version 2.5.15 in production code. By trying to curl the call, I get:

`GnuTLS recv error (-110): The TLS connection was non-properly terminated.`

The expected response consists in a partial html page (built from a scala template) in a **CompletionStage<Result>** sent via a **supplyAsync** call. The same truncation occurs also with png images that should be served as **java.io.FileInputStreams** (images were served correctly also in 2.5.15)

`return CompletableFuture.completedFuture(ok(new FileInputStream(configuration.getString("image.store.path") + file)));` 

### Reproducible Test Case

Here are two curl commands, one to a deployed version in 2.5.15 (working, non-truncated), the second on 2.6.3 (truncated).

`curl 'https://webdeb.be/browse?card=false&embedded=false' -H 'Host: webdeb.be' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'Referer: https://webdeb.be/browse' -H 'Cookie: webdeb.accept.cookies=true' -H 'DNT: 1' -H 'Connection: keep-alive' --data 'query=macron&inGroup=0&isArgument=true&isActor=true&isText=true&queryString='`

`curl 'https://qa.webdeb.be/browse?card=false&embedded=false' -H 'Host: qa.webdeb.be' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'Referer: https://qa.webdeb.be/browse' -H 'Cookie: webdeb.accept.cookies=true' -H 'DNT: 1' -H 'Connection: keep-alive' --data 'query=macron&inGroup=0&isArgument=true&isActor=true&isText=true&queryString='`

**Comment by richdougherty** [comment]
Hi @fabgilson sorry about not responding for so long. So what you're saying is that some reponses only return part of the body? Does this happen for all responses and when running locally as well as when running in production?

**Comment by fabgilson** [comment]
Hi. I'm not developing in that project anymore, so I can't say for sure and I do not believe both instances on different versions are still alive. But what I was experiencing was truncated answers on prod environment, not local. It seemed like the server was not outputting the full answer. If no other devers are experiencing the same problem, you may close it.

**Comment by mkurz** [comment]
> If no other devers are experiencing the same problem, you may close it.

Closing, if someone else experiences this issue we can re-open later.
