### ISSUE TITLE
CacheApi and CacheApi hacks should be removed

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#7805]
There are several places in the `EhCacheApi` impl that use `SyncCacheApi with CacheApi` to implement both. We should remove these hacks and simplify the code for 2.7.0, since we can then remove the deprecated `CacheApi`.

**Comment by richdougherty** [comment]
💝

**Comment by PromanSEW** [comment]
Title has typo: "**CacheApi** and **CacheApi**"
