### ISSUE TITLE
Can not connect server side

### ISSUE THREAD

**Issue by peter057x** [playframework/playframework#7811]
playframework v1.25
data 5.1
jdk 1.7

config file ：jvm.memory=-Xms1024m -Xmx2048m

system：Linux 4cores 16G memory

Players can not connect game server when there are around 10k IIS/Internet Information Services. But no error was showed up in log file. Play Status doesn`t work.

Could you help me?

**Comment by cchantep** [comment]
Hi, this repository is for Play 2+ (and this issue tracker is for confirmed issue/actionable request for such releases). Please use the appropriate tracker or Mailing list. Best regards.

**Comment by gmethvin** [comment]
@peter057x You might want to try asking on https://groups.google.com/forum/#!forum/play-framework (that is still mostly 2.x but you might find a few 1.x users).
