### ISSUE TITLE
Allow graceful handling of illegal websocket requests

### ISSUE THREAD

**Issue by jazmit** [playframework/playframework#7817]
When a request to a websocket URL does not contain the 'Upgrade' header, play fails with an Error and the application-provided handler is never invoked:

https://github.com/playframework/playframework/blob/7945944fd032261c7d8fbf11a3c8aba1935b3dd3/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L270

We get several hundred of these in our logs every day, probably due to firewalls that strip the upgrade header.  It'd be nice to be able to log IP addresses and request headers rather than throw an error.

I'm happy to submit a PR, but would like to touch base with you guys first to ask the best way to move forward.  Perhaps add a 'handleIllegalRequest' method to the `Websocket` trait and corresponding convenience method on `Websocket` object?  Perhaps this can be combined with #5322 ?

### Play Version (2.5.x / etc)
2.6.2

### API (Scala / Java / Neither / Both)
Scala (Akka HTTP)

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
All

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
openjdk version "1.8.0_141"

### Reproducible Test Case
For any play server with a websocket at route `/ws`:
`curl localhost:9000/ws`

**Comment by halfninja** [comment]
This affects us as well, and is cluttering up our logs in a way that the Netty server didn't. I tried implementing workarounds for it, but it's not possible to write a Handler that could conditionally delegate to WebSocket as AkkaHttpServer of course does its type check before any handler code can run. Filters only run on Actions.

I'm also happy to submit or collaborate on a PR.

**Comment by alejandrod** [comment]
These logs are a bit annoying. Will be nice to be able to process the error and log more details.

**Comment by blanciq** [comment]
We also struggle with this issue because we've got Sentry in place and it receives this Exception and triggers an (false) alarm.

**Comment by alejandrod** [comment]
Will be great to have this done! These logs are a bit annoying. Thanks!

**Comment by wsargent** [comment]
Why is this using `sys.error` rather than a Logger?

**Comment by AlekseyMko** [comment]
We have live chat which relies on web sockets
It throws thousands of exceptions from time to time.
It looks quite terrible.

Any updates?

**Comment by alejandrod** [comment]
I upgraded to Play 2.6.15 and akka 2.5.11
This error is gone, even when the code is still there. Now I see the below exception.
I'm trying to dig deep and understand how to prevent this. I'm not sure I fully understand the protocol and why there is a problem with proxies, etc. I think will be nice to just not accept these requests if it's not technically possible or just drop them nicely.

```Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:504)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)```

**Comment by marcospereira** [comment]
Hi @alejandrod,

Which version of Akka HTTP are you using? Out-of-the-box, Play 2.6.15 uses 10.0.13 as you can see here:

https://github.com/playframework/playframework/blob/ccff2ec88a50f18485b57b13dba926eeed1a583d/framework/project/Dependencies.scala#L12

If you are overriding this version with a new one, for example, 10.1.2, keep in mind that Akka HTTP 10.1.2 had a problem (https://github.com/akka/akka-http/issues/2066) which was diligently corrected in 10.1.3. If you are using the Akka HTTP version bundled with Play, could you please provide a way to reproduce the problem?

Best.

**Comment by alejandrod** [comment]
@marcospereira Thanks for your answer!
I'm using `com.typesafe.akka.akka-http_2.12-10.1.3.jar` and I was not aware of the issue you mentioned. I'll look at it and see if I can reproduce locally. 

The reason I posted it here is that I don't see the WebSocket error mentioned in here anymore.
Instead, I see this new error. I can confirm that it's from the WebSockets.

Will see if I can reproduce somehow. The only problem is that if it is related with the WebSockets, I'm not 100% familiar with all the protocol and the proxy issues.

**Comment by marcospereira** [comment]
Hey @alejandrod,

Could you also try with the default Akka HTTP version used by Play 2.6 and see how it goes?

Best.
