### ISSUE TITLE
text/javascript mime type is obsolete

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#7827]
Since the `text/javascript` content type is obsolete, we may consider switching to `application/javascript` for our constants in Play 2.7 and/or provide an alternate simple way to use the `application/javascript` type.

(See https://www.iana.org/assignments/media-types/text/javascript)

**Comment by samupra** [comment]
I am working on this.. can you please assign it?

**Comment by samupra** [comment]
Oops, looks like someone already is. Never mind.

**Comment by gmethvin** [comment]
@samupra fyi this is still open; @benmccann's PR just updated one usage of the existing constant.
