### ISSUE TITLE
Request attribute HandlerDef not available

### ISSUE THREAD

**Issue by seprich** [playframework/playframework#7829]
### Play Version
2.6.3
### API
Scala
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
```
$ uname -a
Linux jrs-carbon 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```
### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Paste the output from `java -version` at the command line.
```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

```
### Library Dependencies

```
libraryDependencies ++= Seq(
  jdbc,
  filters,
  "org.scalikejdbc" %% "scalikejdbc"                  % "3.0.+",
  "org.scalikejdbc" %% "scalikejdbc-config"           % "3.0.+",
  "org.scalikejdbc" %% "scalikejdbc-play-initializer" % "2.6.0-scalikejdbc-3.0",
  "org.flywaydb" %% "flyway-play" % "4.0.0",
  "com.squareup.okhttp3" % "okhttp" % "3.8.0",
  "com.github.tototoshi" %% "play-json4s-native" % "0.8.0",
  "org.json4s" %% "json4s-ext" % "3.5.2",
  "mysql" % "mysql-connector-java" % "5.1.42",
  "joda-time" % "joda-time" % "2.9.9",
  "org.joda" % "joda-convert" % "1.8.2",
  "com.beachape" %% "enumeratum-play" % "1.5.12-2.6.0-M5",
  "com.beachape" %% "enumeratum-json4s" % "1.5.13",
  "com.kenshoo" %% "metrics-play" % "2.6.2_0.6.1",
  "com.github.tomakehurst" % "wiremock" % "2.6.0" % Test,
  "com.github.tototoshi" %% "play-json4s-test-native" % "0.8.0" % Test,
  specs2 % Test
)
```

### Expected Behavior
HandlerDef should be available both in filter and in request handler.

### Actual Behavior
On request handler I had this debugging code:
```
lazy val xxxxxApi: Router = Router.from {
    case GET(p"/ping") => Action { request =>
      val handlerDefOpt = request.attrs.get[HandlerDef](Router.Attrs.HandlerDef)
      println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
      println(handlerDefOpt)
      println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
      Db.testConnection().map(_ => Ok(("result" -> "OK"): JValue)).getOrElse(ServiceUnavailable(("reason" -> "DB"): JValue))
    }
    // etc. etc..
}.withPrefix("/api/v1")
```

printout shows that handlerDefOpt to be None when api is called. (sbt run)

**Comment by gmethvin** [comment]
It looks like you're using a custom router instead of the routes file. `HandlerDef` is meant to convey information from the parsed routes file to your actions. I'm not sure what you'd expect it to do here.

**Comment by seprich** [comment]
Well I thought that router would be able to collect the route information to HandlerDef also from this this SIRD type of construct (the project I work on already uses sird and switching to routes file would mean major refactoring).
I am trying to collect metrics per route in a filter, and filter gets the RequestHandler which contains .path but that not useful in order to determine which routing endpoint will handle the request.

**Comment by gmethvin** [comment]
I'm not even sure what you would expect to see in the SIRD scenario as much of the information provided by `HandlerDef` (controller and method for example) would not make sense there.

There are other ways you could structure your code to obtain the same information in your filter. Since you are defining the router yourself, you have complete control over how the request is mapped to actions and which things are considered a single "route". We are happy to help but I'd suggest asking on the mailing list instead of here.
