### ISSUE TITLE
Values in cache expire much faster than expected

### ISSUE THREAD

**Issue by connyduck** [playframework/playframework#7834]
### Are you looking for help?

No

### Play Version

2.6.5

### API

Java

### Operating System

Windows 10

### JDK 

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### Expected Behavior

when calling `SyncCacheApi.set(key, value, expiration) ` the value expires after `expiration` seconds as per the javadoc

### Actual Behavior

The value expires much faster. I suspect somewhere milliseconds and seconds got messed up, because if I multiply `expiration` with 1000 it works as expected

**Comment by gmethvin** [comment]
@connyduck you're right, it's assuming milliseconds and should be seconds. I'll submit a pull request to fix this.

**Comment by gmethvin** [comment]
Note that this only appears to affect the Java `SyncCacheApi` implementation. So as a workaround you can use the `AsyncCacheApi`
