### ISSUE TITLE
intermittent test failures (EhCacheApiSpec, ResourcesTest) in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [playframework/playframework#7849]
in https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1987/ `play.api.cache.ehcache.EhCache​ApiSpec` failed

and in https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1988/ 
`play.libs.ResourcesTest` failed

the next build (1989) was green

**Comment by SethTisue** [comment]
in [run 1990](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/1990/consoleFull), `EhCache​ApiSpec` failed again

**Comment by SethTisue** [comment]
in [run 1997](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/1997/consoleFull), `ResourcesTest` failed again

**Comment by gmethvin** [comment]
@SethTisue Thanks for the report. I think these issues are fixed by #7861 and #7862.

**Comment by schmitch** [comment]
Currently since this appears to be fixed I will close this issue. Feel free to reopen if the issue appears again.

**Comment by SethTisue** [comment]
cool, thanks!
