### ISSUE TITLE
Stange single-threaded behaviour in controller method

### ISSUE THREAD

**Issue by scadgek** [playframework/playframework#7857]
### Play Version (2.5.x / etc)

2.5, 2.6

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux Mint
```
Linux 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle Java 8
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

### Issue description

Take the [default starter app for java](https://github.com/playframework/play-java-starter-example) and add the following to `HomeController`'s `index` method:
```
System.out.println("Before");
Thread.sleep(5000);
System.out.println("After");
```
Then run a few tabs in a browser calling `http://localhost:9000`.

The expected behavior is that `Before` is printed as soon as the request is issued from the browser tab.
While the actual result is that consequent requests start executing only _after_ the previous one has finished. Note that this is only observed when calling the same method in a controller: two different methods successfully run simultaneously.

Maybe I'm getting something wrong, but I tried nearly all possible configurations in `application.conf` and it looked like the thread pools had enough threads, still I couldn't accomplish the simultaneous execution of the method in different threads.

**Comment by cchantep** [comment]
Hi @scadgek , please use the [MailingList](https://groups.google.com/forum/#!forum/play-framework) to ask questions/for help (this tracker is for confirmed issue, see [guidelines](https://playframework.com/contributing)). Best regards.

**Comment by scadgek** [comment]
Thanks @cchantep and sorry for messing it up. I've created a topic at google forums (probably it's on moderation now).
