### ISSUE TITLE
Common tests for Akka HTTP and standard Headers implementations

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#7892]
We currently have the `play.core.server.akkahttp.AkkaHeadersWrapper` in the akka-http-server implementation and `play.api.mvc.Headers`. We should add tests for both and if possible share some of the specification. This could be done by creating a new integration test or having the akka-http-server tests depend on the core play tests.

**Comment by gmethvin** [comment]
See also #7885

**Comment by lousanna** [comment]
I'll begin working on this.

**Comment by ekosutopo** [comment]
Working

Pada tanggal 7 Okt 2017 2:40 AM, "Lousanna" <notifications@github.com>
menulis:
