### ISSUE TITLE
Incremental ~run on 0.13.16 with 2.6.6 can't 'obtain files to watch'

### ISSUE THREAD

**Issue by hayd** [playframework/playframework#7898]
Play Version 2.6.6 (sbt 0.13.16)
Scala 2.12.2
OS OSX
JDK (javac 1.8.0_60)

This can be demonstrated on [play-scala-starter-example](https://github.com/playframework/play-scala-starter-example) by setting the sbt version to `0.13.16`.

### Expected Behavior

1. `sbt ~run` should compile without an error

### Actual Behavior
```
% sbt ~run
[info] Loading global plugins from /Users/andy/.sbt/0.13/plugins
[info] Loading project definition from /Users/andy/projects/play-scala-starter-example/project
[info] Set current project to play-scala-starter-example (in build file:/Users/andy/projects/play-scala-starter-example/)

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[error] Error occurred obtaining files to watch.  Terminating continuous execution...
[info] p.c.s.AkkaHttpServer - Stopping server...

[success] Total time: 4 s, completed Oct 6, 2017 4:42:54 PM
1. Waiting for source changes... (press enter to interrupt)
```
### Reproducible Test Case

See above 

---

Note: This worked in 2.6.5, I think this stems from the sbt 1.0 PR compat but I'm not sure https://github.com/playframework/playframework/commit/f014439ee696a56baa14b75591e5c96cc3500718#diff-df3eb319d0616dd90e49ec8d062b9091 (PlayRunCompat.scala) cc @marcospereira 
The exception is caught here: https://github.com/playframework/playframework/blob/f014439ee696a56baa14b75591e5c96cc3500718/framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala#L146-L154

**Comment by arnbak** [comment]
I'm seeing the same thing.

**Comment by Rovak** [comment]
I'm experiencing the same problems with `run`, where refreshing the webpage does not trigger an incremental compile. It works the few first minutes and then randomly after a while it stops detecting file changes and a refresh does nothing.

**Comment by Daxten** [comment]
I have the same problem as @Rovak , switching to polling seems to make it better, but it still just stops getting updates after some time (Triggers "Compilation Complete" but actually does not compile anything)

**Comment by Flo354** [comment]
Same problem here.
On IntelliJ IDEA, the project doesn't even start.

**Comment by marcospereira** [comment]
Thank you guys for reporting the problem.

See #7907 for a fix.

**Comment by marcospereira** [comment]
@hayd, @arnbak, @Rovak, @Daxten and @Flo354.

Could you please try with version `2.7.0-2017-10-10-ad9e06d-SNAPSHOT`. It is a nightly build so you need to add the following resolver:

```scala
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
```
If it works with this version, then we can consider this as fixed. If not, at least we should get a stack trace to better debug why reload is failing.

**Comment by hayd** [comment]
@marcospereira Works for me, thanks for the quick fix!

**Comment by Rovak** [comment]
@marcospereira the issue still occurs when using `run`. I'm not sure if i should see the  `Error occurred obtaining files to watch.  Terminating continuous execution...` message during `run` or the trace when it stops triggering incremental compiles, i'm not seeing any messages or errors in the console or log files.

**Comment by marcospereira** [comment]
Thanks for the feedback, @Rovak.

Some questions:

1. Which OS are you using? Windows? Mac?
2. Is this reproducible using a new application created with `sbt new`?
3. Is the problem happening after editing some specific file type (assets, views, or just any file)?

Again, thanks!

**Comment by Rovak** [comment]
@marcospereira

1. Ubuntu 16.04
2. Not sure, will try that later today
3. Any file

**Comment by Rovak** [comment]
@marcospereira i can reproduce this consistently on the latest master branch in a new application by dumping around 2k files in the `public` folder and then modifying something in a `view` file

**Comment by gmethvin** [comment]
@Rovak I think what you're experiencing may be a separate issue. I'm unable to repro on Mac but I'll check on Linux later and see if I can. Does `~run` work?

You can also try using the polling watch service:

```scala
// poll every 1000ms
PlayKeys.fileWatchService := play.dev.filewatch.FileWatchService.polling(1000)
```

**Comment by gmethvin** [comment]
I was unable to repro on a Linux machine. I tried creating a bunch of random files in `public`:

```
for n in {1..2000}; do dd if=/dev/urandom of=public/file$n bs=1 count=$((RANDOM + 1024)); done
```
then I tried editing a file both during and after those files are being written. In both cases the app reloads as expected.

If you have a sample project that consistently reproduces it on your machine, perhaps you could open an issue with a link to the project? Also try with the polling watch service and see if that makes a difference, since that will help us narrow down where the bug is.

**Comment by saosebastiao** [comment]
I haven't fully played around with everything yet, but for a while I was experiencing this bug exactly as @Rovak was. Also on Ubuntu 16.04, using sbt 1.0.2 and play 2.6.6. I figured there was a bug in the SBT plugin and decided to roll back to sbt 0.13.16 and play 2.5 and wait it out. @marcospereira convinced me to check out this issue and I've since tried reproducing it, but haven't been able to reproduce. 

Maybe there was some dirty cache shenanigans on the transition from 0.13.16 to 1.0.2, I have no clue. It seems to be working fine now, so I'll try working with it, but I'll update if I run into it again.

**Comment by saosebastiao** [comment]
Okay, I've already been able to reproduce. It takes a few edit cycles before it shows up. 

I get the regular info messages

```
[info] Compiling 1 Scala source to /home/danny/ws/drv/target/scala-2.12/classes ...
[info] Done compiling.
[success] Compiled in 2s
```

I'm serving up a case class using play json, testing by randomly inserting `println("boop")` in the class body. I'll try to reproduce using a template and post that here.

**Comment by saosebastiao** [comment]
Okay, I've successfully reproduced using a template https://github.com/saosebastiao/bug_repro

Environment is Ubuntu 16.04, editing in Intellij, using their sbt build repl. 

Steps to reproduce:

1: enter dev mode with `~run`

2: edit `conf/application.conf`, changing `foovalue` to whatever you want. 

3: run `curl localhost:9000/`

4: repeat steps 2 and 3 repeatedly until results from `curl localhost:9000/` stop changing. For me this took 6 cycles.

**Comment by Flo354** [comment]
I just updated IntelliJ IDEA to the latest version (EAP and stable release), and I can't start anymore in 2.6.5 (previously only with 2.6.6).

**Comment by marcospereira** [comment]
Hey @saosebastiao, could you please test with your repository but changing:

1. The version to use a snapshot version as explained here: https://github.com/playframework/playframework/issues/7898#issuecomment-335619184
2. Change the `fileWatchService` as explained here: https://github.com/playframework/playframework/issues/7898#issuecomment-336304757

So that we can better isolate the problem.

**Comment by marcospereira** [comment]
@Flo354 sorry, I didn't understand what problem you are describing. What do you mean by "can't start anymore". Start what? How?

**Comment by Flo354** [comment]
@marcospereira for me the problem occurred only when I start play with IntelliJ IDEA. Initially, I had the problem only with version 2.6.6. But as of yesterday, there was an update of the IntelliJ's scala plugin and I can't start anymore with version 2.6.6 nor 2.6.5.

But when I type "sbt run" within the console, I can start play

**Comment by saosebastiao** [comment]
@marcospereira 

Just tried it out. 

#1 didn't do anything. 

#2 worked for both 2.6.0 and 2.7.0 SNAPSHOT, at least as far as 20 edits or so.

**Comment by joantune** [comment]
This is also happening with me:

OS: Mac OS X 10.11.6 - with case sensitive FS

sbt: 0.13.15 and 0.13.16
Play: 2.6.6

it doesn't happen with Play 2.6.3

Also, if possible, please change https://github.com/playframework/playframework/blob/6c246b56863c821b6fc4799bc66a9644347f8e6c/framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala#L152
to have the exception with the error? i.e. 
`log.error("Error occurred obtaining files to watch.  Terminating continuous execution...", e)`

as adding in `logback.xml`:

```
  <logger name="play" level="TRACE"/>
    <logger name="sbt" level="TRACE"/>
    <logger name="com.typesafe" level="TRACE"/>

```

or even changing the root level to trace doesn't yield the stacktrace

**Comment by joantune** [comment]
Debugging and evaluating e.getStrackTraceString() yields the following errors. Either: can't assign Tuple8 to Throwable or Cannot evaluate parameter index
I'm downgrading to 2.6.1 as I'm also having other issues with 2.6.3

**Comment by joantune** [comment]
@marcospereira: yup, `2.7.0-2017-10-10-ad9e06d-SNAPSHOT` works well, I'm guessing that there won't be a 2.6.7 with this fix.. any idea more or less when 2.7 will be out?

**Comment by marcospereira** [comment]
Hi @joantune,

#7907 was actually backported to 2.6.x here: https://github.com/playframework/playframework/commit/009e4001c036c00f985ca56ad39bddf8fae0b95b. So this fix will be part of 2.6.7. I was suggesting using a 2.7 snapshot because that is what our nightly build script publishes. :-)

**Comment by joantune** [comment]
Great! Obrigado!

I am nervous to run with a SNAPSHOT, surely 2.6.7 won't be as far away as
2.7.

Cheers

**Comment by marcospereira** [comment]
De nada. :-)

Yep, 2.6.7 is a smaller release fully compatible with 2.6.6. And by the way, there are 2.6.x snapshots, my mistake:

https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.12/

**Comment by gmethvin** [comment]
I believe the issue with `run` is fixed with #7951.

If you want you can test it out by adding to `plugins.sbt`:
```scala
libraryDependencies += "com.lightbend.play" %% "play-file-watch" % "1.1.3"
```
That will just update the file watcher dependency and make no other changes.

**Comment by joantune** [comment]
hmmm, @gmethvin, @marcospereira  CPU usage is constantly up the roof when doing `~run` when executing `run` it isn't so I'm guessing that there's some polling going on instead of 'watch'

May I suggest that a warning should be printed out if this is the case when doing the ~run is doing polling

Also, weirdly enough `~compile` behaves just fine.

ATM I'm using sbt 1.0.2

**Comment by joantune** [comment]
PS: I just confirmed that the same doesn't happen with sbt 0.13.15 and play 2.6.3

**Comment by marcospereira** [comment]
@joantune just to be clear here:

1. When using Play 2.6.6 and sbt 1.0.2 which `fileWatchService` are you using?
2. And which one for Play 2.6.3 and sbt 0.13.15?

Could you please test with `2.6.7-2017-10-24-df85f53-SNAPSHOT` and without changing `fileWatchService` to polling and confirm that:

1. It works for you
2. You have CPU usage compatible with what you are seeing for Play 2.6.3 and sbt 0.13.15.

Thanks.

**Comment by joantune** [comment]
>When using Play 2.6.6 and sbt 1.0.2 which fileWatchService are you using? 

I was using:
```
libraryDependencies += "com.lightbend.play" %% "play-file-watch" % "1.1.3"
```
by Greg's suggestion

>And which one for Play 2.6.3 and sbt 0.13.15?

Play's 2.6.3 default - i.e. I commented that explicit dependency that I added before for 2.6.6

>Could you please test with 2.6.7-2017-10-24-df85f53-SNAPSHOT and without changing fileWatchService to polling and confirm that:

what do you mean by 'without changing fileWatchService to polling'? not using Greg's explicit dependency should work, right? I didn't change anything else.

I'm assuming that the answer above is yes and I'm trying it now with sbt 0.13.15 and `2.6.7-2017-10-24-df85f53-SNAPSHOT`.

I'll let you know soon

De nada

**Comment by gmethvin** [comment]
Just to be clear, there are actually two bugs people are discussing here. The first is a bug specifically with `~run` and the second is a bug in the watch service that also occurs with `run`. Both should now be fixed if you upgrade to `2.6.7-2017-10-24-df85f53-SNAPSHOT`, without a custom `fileWatchService` configuration. We will release a final 2.6.7 soon and it should work like that.

**Comment by joantune** [comment]
@marcospereira:

so, with `2.6.7-2017-10-24-df85f53-SNAPSHOT` **~compile** yields a 30% CPU usage, similar to the 20% of 2.6.3

~run with  `2.6.7-2017-10-24-df85f53-SNAPSHOT` yields a 50-70% CPU usage versus around 20% with 2.6.3

now I'm thinking this warrants me to go back to 2.6.3 to sample a bit more thoroughly the CPU usage to make sure it's ~40% higher with the 2.6.7 SNAPSHOT. Does the fact that it's higher make sense?

**Comment by joantune** [comment]
Yes, I just confirmed that `2.6.3` has a lower baseline CPU usage - from ~25 - 35% vs 50-70%

**Comment by mkurz** [comment]
I didn't really follow that thread here, but sbt 1.0.3 is out, maybe that helps? 
https://github.com/sbt/sbt/releases/tag/v1.0.3
