### ISSUE TITLE
encoding does not escape + characters

### ISSUE THREAD

**Issue by methikas** [playframework/playframework#7905]
Hi,
when encoding a url that has '+' character as part of it's data, play 2.5 does not seem to escape the +'s.
Eg: http://www.example.com/path/?name="string1" "string2" "stringA+B"

Is there away this can be done..?

Regards
Nalu

**Comment by gmethvin** [comment]
Please post questions to the mailing list. This is an issue tracker for bugs in Play framework. Likely you want to encode your `+` as `%2B`.
