### ISSUE TITLE
Returned error for "db cannot connect" reveals sensitive information of application.conf

### ISSUE THREAD

**Issue by georgeathanasopoulositt** [playframework/playframework#7918]
### Play Version (2.5.x / etc)
lazy val root = (project in file(".")).enablePlugins(PlayJava)

### API (Scala / Java / Neither / Both)
Scala 2.11.7
Java 1.8

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.12 but was reproduced on Windows also

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Paste the output from `java -version` at the command line.

### Library Dependencies

We are using RedshiftJDBC42-1.2.1.1001 as JDBC

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Add configuration file application.conf
db {
  #Redshift dev
  default.driver = com.amazon.redshift.jdbc42.Driver
  default.url = {{this is a real url but as a sensitive information its hidden}}
  default.username = {{this is a real username but as a sensitive information its hidden}}
  default.password = {{this is a real password but as a sensitive information its hidden}}
}
2. For any reason like JDBC cannot be found by Play Framework Play should return an html error WITHOUT containing all sensitive data like db url, user, password

### Actual Behavior

1. Add configuration file application.conf
db {
  #Redshift dev
  default.driver = com.amazon.redshift.jdbc42.Driver
  default.url = {{this is a real url but as a sensitive information its hidden}}
  default.username = {{this is a real username but as a sensitive information its hidden}}
  default.password = {{this is a real password but as a sensitive information its hidden}}
}
2. For any reason like JDBC cannot be found by Play Framework play returns an html error containing all sensitive data like db url, user, password

Here are some logs
```
[error] c.z.h.p.PoolBase - HikariPool-3 - Failed to execute isValid() for connection, configure connection test query. (com.amazon.redshift.core.PGDSIOverrideHelper.checkIsValidQuery(Lcom/amazon/redshift/core/PGJDBCConnection;)Z)
[error] application - 
play.api.Configuration$$anon$1: Configuration error[Failed to initialize pool: com.amazon.redshift.core.PGDSIOverrideHelper.checkIsValidQuery(Lcom/amazon/redshift/core/PGJDBCConnection;)Z]
```
![screen shot 2017-10-11 at 12 30 29 pm](https://user-images.githubusercontent.com/22880626/31432749-00af7db0-ae80-11e7-854e-bcfd356ef110.png)

**Comment by marcospereira** [comment]
Hi @georgeathanasopoulositt,

This only happens in DEV mode (using `sbt run`) where the developer already has access to all these information by simply reading `application.conf` file. This does not happen in [PROD mode](https://playframework.com/documentation/2.6.x/Production) though since the error pages aren't showing any of this information. As documented [here](https://playframework.com/documentation/2.6.x/Deploying), the `run` command should not be used to run an application in production mode.

Does this address your concerns here?

**Comment by georgeathanasopoulositt** [comment]
Of course. Sounds great. Didn't want to find out myself on prod! Thanks you can close the issue

Best Regards,
George Athanasopoulos
________________________________
