### ISSUE TITLE
Mention SBT 0.13.16 / 1.0.x in Play 2.6 Migration Guide

### ISSUE THREAD

**Issue by PromanSEW** [playframework/playframework#7922]
https://www.playframework.com/documentation/2.6.x/Migration26#sbt-upgrade-to-0.13.15
There is only SBT 0.13.15 now here

**Comment by MysterionRise** [comment]
@PromanSEW, so the idea of the migration guide is that Play 2.6 requires at least 0.13.15, right? Does it makes sense to mention that or specify that Play 2.6 could be used with 0.13.15+/1.0.0 version?

**Comment by PromanSEW** [comment]
@MysterionRise see #7801 and #7832 
Play Framework 2.6.5 and newer versions supports both SBT 0.13.16 / 1.0.x

**Comment by MysterionRise** [comment]
I've opened PR #7942 to address the issue

**Comment by marcospereira** [comment]
Fixed in #7942.
