### ISSUE TITLE
Application could not serve the requests if application is stated first then database start 

### ISSUE THREAD

**Issue by ayubsarker** [playframework/playframework#7928]
i am using play 2.5 and HikarCP as connection pool. I start application in following way

- Shutdown the Database
- Start application
- send requests to application that have some database transaction
- I can see the log, Pool could not connect the database which ok as database is down
- Start Database
- I can see the log, Pool connected to the database. 
 - then i sent request to application it is logging exception to connect database and request timeout.

- here is my HokarCP config
 

```
 autoCommit = true
    connectionTimeout = 5 seconds
    idleTimeout = 5 minutes
    maxLifetime = 10 minutes
    connectionTestQuery =  SELECT 1
    minimumIdle = 5
    maximumPoolSize = 25
    poolName = keymaker-pool

    initializationFailTimeout = 0
    isolateInternalQueries = false
    allowPoolSuspension = false
    readOnly = false
    registerMbeans = false
    catalog = null

    connectionInitSql = SELECT 1
    transactionIsolation = null
    validationTimeout = 5 seconds
    leakDetectionThreshold = 15 seconds

```
Environment

```
HikariCP version: 2.7.1
JDK version     : 1.8.0_121
Database        : PostgreSQL
Driver version  : x.x.x
```
[test1.log](https://github.com/playframework/playframework/files/1384133/test1.log)

**Comment by marcospereira** [comment]
Hi @ayubsarker,

This is more a pool (HikariCP) configuration question than an issue with Play.

Commonly, when using a database connection pool, connections are established and reused until they reach some time to live time limit (imposed by the pool or by the database server). In HikariCP, you have `maxLifetime` [see the docs](https://github.com/brettwooldridge/HikariCP) where you can configure for how long connections could live inside the pool before they are "renewed".

You can use this to have a small time in dev mode  (not longer than a few seconds) and then emulate the behavior you want. Your current configuration is 10 minutes. The default is 30 minutes.
