### ISSUE TITLE
Java Forms documentation refers to "Model"

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#7937]
The section of the documentation on `DynamicForm` uses the term "related to a `Model`" https://www.playframework.com/documentation/2.6.x/JavaForms#Handling-a-form-that-is-not-related-to-a-Model but what is a `Model`?

**Comment by PromanSEW** [comment]
`Model` is a defined class with fields that can be binded to a `Form` by `bindFromRequest` method

**Comment by rmcloughlin** [comment]
The capitalization and formatting of the word `Model` makes it seem as if this is a real class or interface within Play Framework but as far as I can tell it is not.  There is nothing named `Model` in https://www.playframework.com/documentation/2.6.x/api/java/index.html and the word doesn't appear anywhere else in the Java forms documentation.

**Comment by wsargent** [comment]
It's a good bug -- the `User` class above is an example of a model:

https://www.playframework.com/documentation/2.6.x/JavaForms#Defining-a-form

but is never explicitly described as such.

**Comment by gmethvin** [comment]
I agree it's confusing, especially with the code formatting and capitalization of `Model`. It actually doesn't matter whether it's related to a "model" in your domain. Anytime you know the names of the fields up front it would be possible to map it to a Java class, and that would have benefits in terms of type safety.

Perhaps we should just say "handling a form with dynamic fields"?
