### ISSUE TITLE
Evolutions hang when using Netty instead of AkkaHttp

### ISSUE THREAD

**Issue by davojan** [playframework/playframework#7943]
### Play Version

2.6.6

### API

Scala

### Operating System

MacOS 10.12.6

### JDK

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### Library Dependencies

```scala
lazy val root = (project in file("."))
  .enablePlugins(PlayScala, PlayNettyServer)
  // switched back to Netty because AkkaHttp web-socket implementation incorrectly handles Sec-WebSocket-Protocol header
  // should return to default AkkaHttp when will be fixed: https://github.com/playframework/playframework/issues/7895
  .disablePlugins(PlayAkkaHttpServer)

libraryDependencies ++= Seq(
  filters,
  guice,
  "com.typesafe.play" %% "play-slick" % "3.0.0",
  "com.typesafe.play" %% "play-slick-evolutions" % "3.0.0",
  "com.typesafe.slick" %% "slick-hikaricp" % "3.2.1",
  "org.postgresql" % "postgresql" % "42.1.4"
)
```

### Expected Behavior

1. Create a new evolution (or change the existing one)
2. Refresh the play app in browser, "Database need evolution" shown.
3. Click "Apply this script now!"
4. After a few seconds we should see the the requested play app page. In console "Application started" message appears.

### Actual Behavior

...
4. The browser refreshes page infinitely without result eventually fails, in console - nothing, everything hangs, when checking the DB manually - the changes from evolutions are applied.
5. Ctrl+C in console, ``sbt run`` again.
6. Refresh the play app in browser -> the app page is shown.

Important: When switching build configuration to use ``AkkaHttp`` - everything works as expected. So it looks like it fails to restart the application after the evolutions are applied when using ``Netty``.

### Reproducible Test Case

Reproduces with any evolution. Here is simple example:

```sql
# --- !Ups
CREATE TABLE xxx (x INTEGER);

# --- !Downs
DROP TABLE IF EXISTS xxx;
```

**Comment by dataich** [comment]
same for me

**Comment by masahitojp** [comment]
Also happening in our environment.

**Comment by richdougherty** [comment]
Note to whoever fixes this 😄 : Evolutions is handled in a special way by Play's server backends - using an internal API called `WebCommands`. This may be a bug in how Netty handles it vs Akka HTTP. Be aware that the `WebCommands` implementation has changed a lot on the *master* branch in #7986.

**Comment by marcospereira** [comment]
Hi @davojan, @dataich and @masahitojp.

Could you please confirm if this still happens with the latest version of Play 2.6 (2.6.19)? Asking because we have done some changes related to how web commands are handled (and some others related to how to acquire an `ApplicationProvider`. So better if we can confirm this was fixed while handling other stuff.

Best.

**Comment by masahitojp** [comment]
@marcospereira Sorry to late reply.
 I checked for Play 2.6.21. I feel it fixed. Verrrrrry Thanks 😄

**Comment by marcospereira** [comment]
Thank, @masahitojp. Closing then. :-)
