### ISSUE TITLE
Configuring WS SSL doc isn't available 

### ISSUE THREAD

**Issue by amatosc** [playframework/playframework#7962]
### API (Both)

At this page [Configuring WS SSL](https://www.playframework.com/documentation/2.6.x/WsSSL)
almost all link to Typesafe SSLConfig  are down. Eg: [Typesafe SSLConfig](https://typesafehub.github.io/ssl-config)

**Comment by gmethvin** [comment]
Oops. This probably happened because we moved all those repositories to lightbend, e.g. https://lightbend.github.io/ssl-config/. Basically we need to replace typesafehub with lightbend everywhere.

**Comment by amatosc** [comment]
@gmethvin thanks for the link!

**Comment by samupra** [comment]
Is anyone taking this? If not, I'll work on it now.

**Comment by gmethvin** [comment]
Yes, feel free to take any open issues unless they are assigned.
