### ISSUE TITLE
Same File Have different ETag on from different server response with Play 1.2.10,

### ISSUE THREAD

**Issue by krishtyagi** [playframework/playframework#7966]
Hi Team,
I am working on old play 1.2.10 application , where we use activator start/run to launch the web application. I have load balance server as apache and two server instance of application. I want to generate same ETag from both server. Cloud you please help me , where I can find and fix this. I am new to play and we are using java controller.
I tried to disable using below conf parameter in application.conf, but does not works

Disable the Etag Creation By Play Server

http.useETag=false
I need help to over-ride the Assets functionality using java.

Assets built in Note :Etag support
The Assets controller automatically manages ETag HTTP Headers. The ETag value is generated from the digest (if sbt-digest is being used in the asset pipeline) or otherwise the resource name and the file’s last modification date. If the resource file is embedded into a file, the JAR file’s last modification date is used.

When a web browser makes a request specifying this Etag then the server can respond with 304 NotModified.

Thank you in Advance.

**Comment by mkurz** [comment]
You are wrong here. This GitHub repo is only for Play >= v2.x. The Play 1.x repo - where you should raise your issue instead - is that one: https://github.com/playframework/play1
