### ISSUE TITLE
Request from error handler is different from Action request

### ISSUE THREAD

**Issue by diegoagd10** [playframework/playframework#7968]
### JDK (OpenJDK 1.8.x)

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### Library Dependencies 
None

### Expected Behavior

1. Add attrs to the request from a Filter.
2. Controller action throws an exception.
3. Error handler catches the exception and reads the request attrs.

### Actual Behavior

I created a Filter to set the following attrs to the request:

```
val newRequest = request
      .addAttr(ApiAttrs.RequestStart, new Date(System.currentTimeMillis()))
      .addAttr(ApiAttrs.RequestId, 1002)

nextFilter(newRequest)
```

The following is my Controller:

```
class PeopleController @Inject()(cc: ControllerComponents) extends AbstractController(cc) {
    def get() = Action { implicit request =>
        // Here I can retrieve my requestId from request attrs without issues.
	val requestId = request.attrs.get[UUID](ApiAttrs.RequestId)
        throw new Exception("test")
    }
}
```

The following is my Custom error handler:

```
class CoreErrorHandler @Inject()(
  env: Environment,
  config: Configuration,
  sourceMapper: OptionalSourceMapper,
  router: Provider[Router]) extends DefaultHttpErrorHandler(env, config, sourceMapper, router) {

  override def onServerError(request: RequestHeader, exception: Throwable): Future[Result] = {
        // My custom attrs are missing in this request object.
	val requestId = request.attrs.get[UUID](ApiAttrs.RequestId)
	
	InternalServerError("error")
  }
}

```
Even though in my controller I can read my custom attrs, in the exception handler I cannot.

I wonder if you have an approach for this scenario.

Thanks.

**Comment by gmethvin** [comment]
The top level exception handler only knows about the top level request. If you want to pass along the request with the modifications made in the filter, you need to handle it at that level, for example:

```scala
nextFilter(newRequest).recoverWith {
  case NonFatal(e) => httpErrorHandler.onServerError(newRequest, e)
}
```

**Comment by richdougherty** [comment]
I agree that @gmethvin's suggestion is the best way to handle this. If Play had a mutable request scope then we could use that scope to store attributes. Instead Play has immutable requests. This means that the original request isn't changed when you add new attributes. The error handling code only has access to the original request, not to the modified request. To get access to these your modified request you need to pass it explicitly to the error handler.

Unless there's something else we should consider then I think we can close this issue with the suggested workaround as a 'fix'.

**Comment by diegoagd10** [comment]
Hi @gmethvin and @richdougherty, I agree with you, this is a great workaround and I'm going to proceed to close this issue.

Thanks a lot.
