### ISSUE TITLE
Caffeine cache API

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#7974]
[Caffeine](https://github.com/ben-manes/caffeine) is a much better choice for a local cache and we should recommend it over ehcache in the future. We should create a cache API implementation for caffeine that provides similar features to the current ehcache implementation.

We should support the ability to configure specific named caches and inject them using `@NamedCache("mycache")`. Parts of this would probably look similar to the current [ehcache implementation](https://github.com/playframework/playframework/blob/master/framework/src/play-ehcache/src/main/scala/play/api/cache/ehcache/EhCacheApi.scala). The caches should be configurable via typesafe config.

**Comment by wsargent** [comment]
This would help with the play-ahc-ws-cache as well.

**Comment by ben-manes** [comment]
For this adapter I think it would be something like

```java
Cache<String, Object> cache = Caffeine.newBuilder()
    // user configuration settings - no expiration as explicit in API
    .expiresAfter(new Expiry<String, Object>() {
      // all methods return Long.MAX_VALUE as defaulting is eternal lifetime
    }).build();
VarExpiration<String, Object> policy = cache.policy().expireVariably().get();
...
void set(String key, Object value, int expiration) {
  policy.put(key, value, expiration, TimeUnit.SECONDS);
}
```

**Comment by dusanstanojeviccs** [comment]
Hi, I would love to implement this.

Should I just fork the master repo, and create src/play-caffeine and make implementation like play-ehcache?

**Comment by gmethvin** [comment]
@dusanstanojeviccs That's great. Yes, the module should look similar to play-ehcache and should depend on play-cache (the cache api) just like the ehcache one does: https://github.com/playframework/playframework/blob/master/framework/build.sbt#L316

**Comment by dusanstanojeviccs** [comment]
@gmethvin Hey, I've implemented this and all tests are passing. So should I update cache/ScalaCache.md docs and cache/JavaCache.md and make a PR?

**Comment by gmethvin** [comment]
@dusanstanojeviccs Yes, don't hesitate to make a PR, even if it's still a work in progress. 

We should update the doc to recommend using the caffeine cache module instead of the ehcache module, but still point out that the ehcache module exists. We can give you more detailed feedback on the PR.

**Comment by dusanstanojeviccs** [comment]
Got it awesome, I'll do it in a few hours when I get home 👍
