### ISSUE TITLE
[2.6.7] Provide *PlayMinimal* Autoplugin

### ISSUE THREAD

**Issue by godenji** [playframework/playframework#7991]
Rationale: in many cases play users are shuffling around JSON and have no need whatsoever for the UI features in the framework.

While the added production "weight" isn't important, paying the compile "tax" in development very much is, just look at the output of `sbt -Dsbt.task.timings=true` and see all of the work being done on every `compile`.

By providing a `PlayMinimal` autoplugin (no sbt-web, no twirl, no forms) with the removed modules available via `enablePlugins(...)` the framework can reduce incremental compilation lag in pure server-side applications.

For context see the [google group thread](https://groups.google.com/forum/#!topic/play-framework/Ha9XYOp4DZ8)

**Comment by rayronvictor** [comment]
+1
Or add a doc section showing how to archive this.
