### ISSUE TITLE
Don't ignore exceptions thrown during JPA rollback

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#8023]
I noticed this bit of code [in the JPA implementation](https://github.com/playframework/playframework/blob/cdc2210758d906055774cd9573921d9cdfaaa106/framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java#L150-L154) where we're catching a `Throwable` and ignoring it. See the `catch (Throwable e) {}` below:

```scala
} catch (Throwable t) {
  if (tx != null) {
    try { tx.rollback(); } catch (Throwable e) {}
  }
  throw t;
} ...
```

1. We should try and avoid catching `Throwable` - maybe catch `NonFatal` instead?
2. Since we've got two exceptions at this point but we can only throw one, we should update `catch (Throwable e) {}` to log the value of `e` before we `throw t`.

**Comment by defrancea** [comment]
I'll be happy to take this one.
Regarding the exception's type being caught and according to [the doc](https://docs.oracle.com/javaee/6/api/javax/persistence/EntityTransaction.html#rollback()), one option is to:
1. Check isActive() before calling rollback
2. Catch `PersistenceException` only

Then we cal log the exception as @richdougherty proposed.
