### ISSUE TITLE
Allow CORS from origin file://

### ISSUE THREAD

**Issue by stephenjeba** [playframework/playframework#8037]
Tried with the below configuration, but still 403 forbidden error.

play.filters.cors {
  allowedOrigins = null
}

I have tried also with allowedOrigins = ["file://"] but still issue.

**Comment by NathanC** [comment]
Seems related to this: https://github.com/playframework/playframework/issues/5193

**Comment by tanaka-de-silva** [comment]
You can configure Play to serve content for any origin by using play.filters.cors.serveForbiddenOrigins = true.

**Comment by gmethvin** [comment]
Since this has already been discussed in #5193 I'm closing. If you are getting the 403 error returned to your client, then you can probably deal with this using `play.filters.cors.serveForbiddenOrigins = true`. It's hard to say what the right thing to do is without more context though.
