### ISSUE TITLE
LogbackLoggerConfigurator Does Not Use Standard logback-test.xml

### ISSUE THREAD

**Issue by jamesward** [playframework/playframework#8095]
### Play Version (2.5.x / etc)

2.6.7

### API (Scala / Java / Neither / Both)

Scala

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. A custom `logger-configurator.properties` is used
2. A `test/resources/logback-test.xml` file defines the logger config 
3. According to the [Logback docs](https://logback.qos.ch/manual/configuration.html) the config should be used

### Actual Behavior

The config is not used.

### Workaround

Set the following in the `build.sbt`:

```
javaOptions in Test := Seq("-Dlogger.resource=logback-test.xml")
```

**Comment by wsargent** [comment]
Technically it should run through the entire discovery mechanism:

https://github.com/playframework/playframework/blob/master/framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala#L56
