### ISSUE TITLE
Plain/txt and text/xml body content were assumed encoded by "ISO-8859-1" instead of UTF-8

### ISSUE THREAD

**Issue by blueberrynotblue** [playframework/playframework#8098]
### JDK (Oracle 1.8.0_152)
**java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)**

### Library Dependencies
Play+Akka Http

----------------------------------------------------------------------------
###Example

##request header:
**Content-Type**: **text/xml** or **Content-Type**: **text/plain**

##request body:
```
<xml>
<Chinese>中文字</Chinese>
<English>chinese word</English>
</xml>
```
or 
```
一些txt
```

### Expected Behavior
get utf-8 content

### Actual Behavior
get ISO-8859-1 content(broken, unreadable characters)

-------------------------------------------------------------------------
If **Content-Type** is **text/xml**, changing it to  **application/xml** would fix it, or convert it with code 
`new String(bodyString.getBytes("ISO-8859-1"),"UTF-8")`

**Comment by gmethvin** [comment]
The default charset for `text/xml` and most `text` media types is US-ASCII (which is a subset of ISO-8859-1). If you don't specify a charset that's what it will default to. For `application/xml` the default is utf-8.

**Comment by blueberrynotblue** [comment]
@gmethvin spring treat them as UTF-8 too. Some platforms dont specify charset but using utf-8, which causing problems for developers using play in country like china.

**Comment by gmethvin** [comment]
Is it not possible to simply send it as `text/plain; charset=utf-8` or similar? If you are sending `text/plain` or `text/xml` without a charset parameter and UTF-8 content, technically that's wrong.

`us-ascii` is a subset of both `utf-8` and `iso-8859-1` so neither Play nor Spring's behavior is "wrong". I'm not sure what all the reasons are for Play choosing `iso-8859-1`, but I'm open to discussing on the [dev mailing list](https://groups.google.com/forum/#!forum/play-framework-dev) to understand your reasons more clearly. I suppose if it were widespread in China or elsewhere to send incomplete `Content-Type`s with UTF-8 text, and that's something you can't control, there might be an argument to change the default just to save developers some headache.
