### ISSUE TITLE
[2.5.x, 2.6.x] AbstractCorsPolicy does not correctly check Origin header for the sake of ServeForbiddenOrigins

### ISSUE THREAD

**Issue by eliothxchan** [playframework/playframework#8108]
### JDK

Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### Notes

Hi all. Not a super experienced developer here, but I've been trying to get some CORS stuff working on Play 2.5.18 and it's not looking like it's supposed to. So I took a lot at AbstractCorsPolicy. On lines 50-53 there's the following comment within the case where the Origin header is empty or malformed (`case (Some(originHeader), _) if originHeader.isEmpty || !isValidOrigin(originHeader) =>`):

>If the value of the Origin header is not a case-sensitive match for any of the values in list of origins, do not set any additional headers and terminate this set of steps.

However, given how serveForbiddenOrigins is described, should there not also be a check if the given header is not present in the `allowedOrigins` list? `isValidOrigin(originHeader)` only checks for the construction of the URI, and doesn't take a look at the `allowedOrigins` list whatsoever.

In the Play docs, the serveForbiddenOrigins flag is described as such:

>enable/disable serving requests with origins not in whitelist as non-CORS requests (by default they are forbidden)

But in the actual functionality, it's simply allowing empty or malformed Origins to be served as non-CORS requests, rather than serving any non-whitelisted Origins as non-CORS requests.

Please let me know if I'm missing something obvious here.

Thanks,
Eliot

**Comment by gmethvin** [comment]
@eliothxchan You're correct. The current behavior only works for invalid origins, not for forbidden origins. It should probably work for both, but certainly for forbidden origins. The fix should be to add a check here: https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala#L110

Are you interested in submitting a pull request?

**Comment by eliothxchan** [comment]
I'm definitely interested! I've always wanted to dip my toe into open-source contributions, and this seems like a great place to start. I'll read through the contribution guidelines. Anything in particular I should keep in mind?

**Comment by eliothxchan** [comment]
Will this change be available in 2.5.x once I make it? I found this trying to implement some stuff for my job, and we're not quite ready to port to 2.6 yet.

**Comment by gmethvin** [comment]
Just make sure there are tests. Looks like you fixed the old test which was broken.

We can backport the change to 2.5.x.

**Comment by eliothxchan** [comment]
Thanks for the guidance @gmethvin!
