### ISSUE TITLE
Java formatter

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#8109]
We should add a Java formatter to our code to keep the style consistent. For now it would be nice to just have a format that roughly mirrors what we have now (with four-space indents). We could consider changing the rules in the future.

**Comment by naferx** [comment]
FYI, https://github.com/sbt/sbt-java-formatter can help. I'm not sure it is stable enough

**Comment by rmcloughlin** [comment]
If you _were_ willing to switch two-space wide indents you could use google-java-format (https://github.com/google/google-java-format).  Some nice things about using this format:
* it's supported by Google, who provide a command-line tool and IntelliJ plugin
* it's supported out of the box by checkstyle (see: http://checkstyle.sourceforge.net/cmdline.html#Download_and_Run).  There's also a checkstyle IntelliJ plugin that supports it out of the box.

**Comment by gmethvin** [comment]
I personally prefer the Google style but I think it would be a big change from the current style Play uses. On the other hand a lot of Play's critical code is actually in Scala, so it might not be as big a deal as we think (you can ignore whitespace in git blames for example).

I'd like to see if anyone else has opinions before making a sweeping change.

**Comment by wsargent** [comment]
Also see https://github.com/akka/akka/issues/20891

**Comment by TimMoore** [comment]
Also related: https://github.com/lagom/lagom/pull/1060

It would be good to have a consistent style for all Play & Lagom code... ideally Akka as well.

Lagom's Java formatting is currently inconsistent, with some two-space and some four-space indentation.

I have argued for four-space indentation in the past, mostly because this is the standard Oracle style and is the default used by IDEs AFAIK, but I'm not 100% committed to it and would be happy to change to two-space indentation if we can make it standard across all of these projects (with automatic formatting to enforce it).

**Comment by landsman** [comment]
Still without formatter?

**Comment by wsargent** [comment]
https://github.com/sbt/sbt-java-formatter seems functional but only uses Google Java Format.

There's also a standalone IntelliJ IDEA formatter:

https://confluence.jetbrains.com/display/IDEADEV/Command-Line+Source+Code+Formatter

https://www.jetbrains.com/help/idea/command-line-formatter.html

**Comment by gmethvin** [comment]
I'm currently using sbt-java-formatter in https://github.com/gmethvin/directory-watcher which is a mixed Scala/Java project. It works fine for my purposes. The main downside is lack of customizability, and I'm not a huge fan of the way it formats some more "functional" Java code. It's a matter of opinion though, and I guess I'd prefer to standardize on something even if it's not perfect.

**Comment by hepin1989** [comment]
@gmethvin that's true,can't do anything....

**Comment by marcospereira** [comment]
Closed by https://github.com/playframework/playframework/pull/9026.
