### ISSUE TITLE
logback-test.xml file from play-openid accidentally included in compile artifacts

### ISSUE THREAD

**Issue by svroonland** [playframework/playframework#8124]
Play version 2.6.9

There's a file "playframework/framework/src/play-openid/src/**main**/resources/logback-test.xml" which is included in the play framework's compile artifacts. When using a custom `logback-test.xml` file, logback is giving warnings about multiple logback-test.xml files being found, causing lots of verbose logging.

The file should be in `test/resources`, like all other subprojects have (search for `logback-test.xml`).

This seems to have been introduced accidentally in #6771.

**Comment by mkurz** [comment]
@svroonland Yes you are right, the file was copied wrong: https://github.com/playframework/playframework/pull/6771/files#diff-6da95edfb97230ae92f4472a0395b015

Can you provide a pull request to fix this? Thanks!
