### ISSUE TITLE
Scrollbar issues detected in playframework.com

### ISSUE THREAD

**Issue by Itzmanz** [playframework/playframework#8136]
Today while surfing through playframework.com  i discovered it has a scroll bar problem.
 whereby the issue is the scroll bar of the website at a point ,doesn't move with the page simultaneously
below is the problem.
video https://youtu.be/Cb3v4-2XcXU
Thank you.
I hope my findings would be helpful.
Operating system : Windows 8.1
Browser used: Google chrome Version 63.0.3239.84 (Official Build) (64-bit)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@suleimanz/scrollbar-issues-detected-in-playframework-com">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by TonnyGaric** [comment]
Strange behaviour. On macOS `10.13.1` I am able to reproduce this issue on Mozilla Firefox `57.0.3`. I am **not** able to reproduce this issue on Google Chrome `63.0.3239.108` or Safari `11.0.1`.

**Comment by Itzmanz** [comment]
i checked the webpage recently and the issue still reoccurred with Google
Chrome Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by marcospereira** [comment]
Hey guys,

Thanks for letting us know about this. I'm closing it and opening a new issue at the correct repository here:

https://github.com/playframework/playframework.com/issues/186

That is the repository for playframework.com.

Thanks.
