### ISSUE TITLE
100% thread CPU when running Play framework project via IntelliJ on Windows

### ISSUE THREAD

**Issue by lediur** [playframework/playframework#8145]
### Play Version (2.5.x / etc)

Play 2.6.6 (also occurs in 2.6.10)

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10 1709 (Fall Creators Update, build 16299)

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

```
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

### Library Dependencies

Scala 2.12
sbt 1.0.4 (also occurs with 1.1.0)
IntelliJ IDEA 2017.3.2 (Community Edition)
Build #IC-173.4127.27, built on December 25, 2017

### Expected Behavior

1. Run project using IntelliJ IDEA
1. Wait for compilation to complete
1. Project idles with little to no CPU usage

### Actual Behavior

1. Run project using IntelliJ IDEA
2. Wait for compilation to complete
3. Project uses ~15 - 20% CPU (1 core on a Core i7 7700HQ) - 1 thread is in a tight loop that results in 100% usage of 1 core.

If the project is started via the SBT shell, this issue doesn't occur.

### Thread profile

`sbt` -> `PlayConsoleInteractionMode`

![image](https://user-images.githubusercontent.com/1077648/34789899-cfdf702a-f5f4-11e7-8daa-11b3160b8200.png)

### CPU usage

![image](https://user-images.githubusercontent.com/1077648/34789981-19fd9b0a-f5f5-11e7-88d7-27971ff842ca.png)

**Comment by cchantep** [comment]
Have you ask on the MailingList? This seems quite related to OS/IDE (and this issue tracker is for issue about Play itself).

**Comment by lediur** [comment]
Sure - I wasn't sure where to raise this issue since it involved the `play.sbt` library. I've gone ahead and posted a question on SO.

https://stackoverflow.com/questions/48397894/100-thread-cpu-usage-when-running-sbt-tasks-in-intellij-on-windows-10

**Comment by wsargent** [comment]
This is an intellij idea bug related to the Scala plugin's use of sbt shell -- it's not Play.  Closing.
