### ISSUE TITLE
play.data.Form.errorsAsJson() and Http.Context.current() Issue

### ISSUE THREAD

**Issue by T-PWK** [playframework/playframework#8152]
### Issue
I found an issue with `play.data.Form#errorsAsJson()` when called when there is no HTTP context available. The method tries to get a language and performs a check as follows (line: 733):

`Http.Context.current() != null ? Http.Context.current().lang() : null`

However, `Http.Context.current()` always throws `RuntimeException` with message "There is no HTTP Context available from here." if there is no current context available.

### Suggestion
I would suggest adding a context checking method to `Http.Context` like 
`boolean isAvailable()` or `boolean isCurrentAvailable()` and use that one for checks instead of `Http.Context.current() != null` (as currently it will always throws RuntimeException).

**Comment by mkurz** [comment]
What is your use case? In which case do you call `errorsAsJson()` without a `Http.Context` set?

If you use `errorsAsJson()` outside a http request you should probably use the overloaded method that takes a `play.i18n.Lang` parameter: https://github.com/playframework/playframework/blob/2.6.11/framework/src/play-java-forms/src/main/java/play/data/Form.java#L742

**Comment by T-PWK** [comment]
The issue was discovered during some unit tests. And yes, public `public JsonNode errorsAsJson(Lang lang)` works perfectly fine. 

But the but the issue is more with `public com.fasterxml.jackson.databind.JsonNode errorsAsJson()` method. If it is not meant to be called outside HTTP context then it can be simplified to the following form as `Http.Context.current()` will never return `null` value.

```
public com.fasterxml.jackson.databind.JsonNode errorsAsJson() {
    return errorsAsJson(Http.Context.current().lang());
}
```

The check for `null` from `Http.Context.current()` is a bit misleading.

And I would suggest this as a code enhancement rather than a bug.

**Comment by gmethvin** [comment]
Maybe we need `errorsAsJson(Lang lang)`, and if there is no `Http.Context` we can throw a more meaningful exception, saying something like "No HTTP context here. Did you mean to use errorsAsJson(lang) instead?"

**Comment by mkurz** [comment]
Closing, because starting with Play 2.7 `errorsAsJson()` does not use `Http.Context` internally anymore. Also using `errorsAsJson(Lang lang)` as a workaround seems to work fine as it seems from the comments.
