### ISSUE TITLE
i18n error: controller and templates use different implicit Langs

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#816]
Please see: http://stackoverflow.com/questions/9733082/i18n-error-controller-and-templates-uses-different-implicit-langs

**Comment by cchantep** [comment]
Also related #3782

**Comment by cchantep** [comment]
Should be ok for me

**Comment by wsargent** [comment]
I believe this should be addressed by the messages refactoring in #6438

**Comment by wsargent** [comment]
Fixed by removal of the default lang in https://github.com/playframework/playframework/pull/7319
