### ISSUE TITLE
 Can I use "Action" to monitor the request process？

### ISSUE THREAD

**Issue by yemingfeng** [playframework/playframework#8165]
Hi.
First, I am wild about Play Framework.
But I meet a problem.I need to monitor the request process.
So can I monitor the request process by "Action"?
Best Wishes.

**Comment by yemingfeng** [comment]
Add to it, I need print some log after complete request.

**Comment by wsargent** [comment]
This is an issues list for Play bugs. Please use the mailing list for questions.  Thanks.
