### ISSUE TITLE
Evolutions Fail With a Small Pool

### ISSUE THREAD

**Issue by jamesward** [playframework/playframework#8184]
### Play Version (2.5.x / etc)

Play 2.6.11

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Evolutions should be unaffected by the db pool size

### Actual Behavior

1. I set `db.default.hikaricp.maximumPoolSize = 1`
1. Run evolutions and they failed with `org.postgresql.util.PSQLException: ERROR: relation "play_evolutions" does not exist`

### Reproducible Test Case

1. Set `db.default.hikaricp.maximumPoolSize = 2`
1. Run evolutions.

**Comment by valydia** [comment]
Hi @jamesward!

Could you give more descriptions around your issue, possibly a sample project, please?
As I have tried to replicate this issue [here](https://github.com/valydia/play-evolutions), but it works fine!

**Comment by jamesward** [comment]
Thanks @valydia for looking into this.  I did just notice that I had a typo in my initial `Actual Behavior` section.  The pool size that fails is `1`: `db.default.hikaricp.maximumPoolSize = 1`

Let me know if that helps.  If not, I'll try to recreate this in a simple test.

**Comment by valydia** [comment]
Thanks @jamesward managed to reproduce it with `db.default.hikaricp.maximumPoolSize` set to 1!
