### ISSUE TITLE
[2.6.x] Controller method called twice if it takes too long

### ISSUE THREAD

**Issue by laguiz** [playframework/playframework#8185]
### In short

If action POST takes too long we observe in `dev` and `prod` mode that the method is triggered multiple times. We suspect akka-http to resubmit the akka message by error. Default timeout setup.

### Play Version (2.6.1)

With akka-http (default)

### API (Scala / Java / Neither / Both)

Tested with Java Controller

### Operating System

MacOS 10.13.2

### JDK

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Library Dependencies

Akka-http (not tested with netty)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Create a http POST action in a controller
2. Make this action take a long time (in our case 1min30sec)
3. We expect a timeout with 500 error and for sure only *ONE* call of the controller action

### Actual Behavior

1. Create a http post action in a normal controller
2. Make this action take a long time (in our case 1min30sec)
3. We observe that the http action is called multiple times after a probably timeout
4. The http call form the browser take more or less 4min and during that time the action has been called 3 times (including http filters)

### Reproducible Test Case

That's very easy to setup in a sample project. Simply log at the beginning of the action and sleep 100sec. You will see the action called multiple times. Tell me if you want a sample project.

### Our thought

1. We suspect it's related to akka-http that redeliver akka message to trigger controller actions.
2. Observed in `dev` and `prod` mode

### Stackoverflow similar issue

https://stackoverflow.com/questions/46923677/play-framework-scala-controller-method-called-twice?rq=1
https://stackoverflow.com/questions/30276467/play-framework-controller-method-called-twice

**Comment by shkhln** [comment]
Have you tried reproducing this with `curl` instead of a browser?

**Comment by shkhln** [comment]
https://groups.google.com/forum/#!topic/play-framework/EgTZQX-Nnsk

**Comment by schmitch** [comment]
the redeliver is not because of akka-http. when logging the tcp messages it seems that there is a RST stream, which than results in a retransmission of the request (can be either a browser thing, or not sure). But I could not find out why it ignored idleTimeout and requestTimeout. that needs a further investigation. It could also be that there is some kind of other timeout that I'm missing that needs to be set.

**Comment by shkhln** [comment]
> a retransmission of the request (can be either a browser thing, or tcp directly, not sure exactly)

It's definitely a browser thing, I don't think it is actually properly documented anywhere, but we are not the first people to observe that behaviour: https://stackoverflow.com/questions/19816529/why-does-the-user-agent-resubmit-a-request-after-server-does-a-tcp-reset. It might be possible to prevent by sending 'Connection: close' or some similar workaround.

**Comment by shkhln** [comment]
> documented anywhere
https://mnot.github.io/I-D/Abandoned/httpbis-retry/#current

**Comment by ktoso** [comment]
It is rather weird that a POST is being retried by the way, with GET or other idempotent ones I'd be less surprised. In any case: thanks for the analysis @schmitch! We'll discuss if it should be a close rather than a RST... 

cc @richdougherty @jrudolph

**Comment by laguiz** [comment]
Sorry I was not subscribed to notifications :/
As @ktoso In fact I knew about GET but for POST it's strange. Hope you can handle it via `close` or `RST`.
Tell me if I can help.

**Comment by schmitch** [comment]
well the `RST` is a TCP command.
And basically this might be the case:
https://tools.ietf.org/html/rfc2616#section-8.2.4

And also:
https://tools.ietf.org/html/rfc7230#section-6.3.1
guess since the client does not know that the server recieved the request (i.e. server did not respond, with anything, no status code, header, etc..) the client thinks that the POST is ideotempt.

**Comment by shkhln** [comment]
@laguiz It's not really a framework problem. Idle connections might as well be dropped by firewall/NAT, for example. You should consider separating job submission from status checking: use a POST request to submit a job and receive an identifier, then use that identifier to check job status with polling/SSE/websockets. 

> I mean the best solution would probably to check if there is an Idle Timeout and then try to "Interrupt" any Future's, but I guess there is no way to actually Interrupt a Future.

Solution to what exactly?

**Comment by schmitch** [comment]
> Solution to what exactly?

well at the moment there is no way to know that a connection got dropped because of idle timeout (and yes you are right that long running jobs should be handled differently)

**Comment by laguiz** [comment]
Just to clarify, in my case I discovered the issue due to a "in progress dev bug" in the implementation of an HTTP POST Action. I totally agree that we should not have POST that takes more than few seconds and a better pattern should be used (eg. queue/job style). However I was confused about the behaviour so I raised it here to make sure it was know and managed.

About `Idempotency` I through POST was not an idempotent verb. I guess best way to protect us is to make our `POST` implementation idempotent or at least fail if called a second time.

**Comment by domdorn** [comment]
Are you using a proxy in front of your app (e.g. nginx) ? at a client I recently experienced this behavior, because nginx thought the request died and submitted it again.

**Comment by laguiz** [comment]
@domdorn Thank you for the tips. I discovered the issue without any proxy.

**Comment by schmitch** [comment]
Closed since this is not an issue within play
