### ISSUE TITLE
Change from ValidationError to JsonValidationError should be documented in the Play 2.6 migration guide

### ISSUE THREAD

**Issue by TimMoore** [playframework/playframework#8190]
https://github.com/playframework/playframework/pull/6763 requires updating projects to use `JsonValidationError` in Play JSON reads instead of `play.api.data.validation.ValidationError`.

This is currently missing from the [Play 2.6 Migration Guide](https://www.playframework.com/documentation/2.6.x/Migration26).

**Comment by ajaysunilsharma** [comment]
I am just starting to contribute. I have identified that below file needs modifications:
/documentation/manual/releases/release26/migration26/Migration26.md
Please point out which section of Migration Guide should mention this requirement. Or else should I create a new section at the end of the existing documentation?

**Comment by TimMoore** [comment]
Thanks, @ajaysunilsharma! 

I think it would make sense to add it to the ["Play JSON API changes"](https://www.playframework.com/documentation/2.6.x/Migration26#Play-JSON-API-changes) section, underneath the "JSON array index lookup" sub-section.

**Comment by GKuldeepak-Knoldus** [comment]
Hi Everyone,
Has this issue been resolved, if not, I would like to take this opportunity! Please confirm the same.

**Comment by TimMoore** [comment]
It looks like it has not been resolved, @GKuldeepak-Knoldus.

**Comment by GKuldeepak-Knoldus** [comment]
Thanks @TimMoore for confirming, I have raised the PR for the same.
