### ISSUE TITLE
GuiceOneAppPerSuite seems to be skipping ErrorHandler upons onDevServerError

### ISSUE THREAD

**Issue by tenstriker** [playframework/playframework#8194]
### Expected Behavior

calling play.api.test.Helpers.status(result) should return Http status code and not the scala exception

Please describe the expected behavior of the issue, starting from the first action.

I am trying to test my play application using GuiceOneAppPerSuite, play helper classes and scalatest. 

Here is the snippet of test code

```
class DataRouterSpec extends PlaySpec 
  with GuiceOneAppPerSuite
  with ScalaFutures
  with BeforeAndAfter 
  with DefaultAwaitTimeout   {

"DataRoute" should {
      "send 400 on a invalid json data request - invalid fqn" in  {
        
        val jsonReq = Json.parse(JsonData.invalidFqn)        
        val fakeRequest = FakeRequest(POST, "/api/v1/data/json") 
                            .withJsonBody(jsonReq)	
        val Some(result) = route(app, fakeRequest)        
        status(result) mustEqual BAD_REQUEST      //status(result) returns an exception here instead of //exception being wrapped into Result object in my HttpeErrorHandler  describe below
      }
}

}
```

In above `result` is already a type of `Future(Failure(java.lang.IllegalArgumentException: {"name":["This field is invalid"]}))` so doing `status(result)` doesn't return no http error code.

`result` should be `Future(Success(Result(400, Map())))` so calling `status(result)` returns 400 and my test passes.

This happens because exception that I throw from `ActionBuilder`s method `invokeBlock`  is not getting intercepted by my `ErrorHandler` implementation. It should be caught in `ErrorHandler` onDevServerError method. 

It does get intercepted when calling the api normally. i.e. starting the play server and hit the api via browser or client not through play ScalaTest. 

Could this be issue with `GuiceOneAppPerSuite`?

I can provide fragments of my controller, ActionBuilder and ErrorHandler code if required.

Workaround - Have error handling code inside `ActionBuilder`s method `invokeBlock` itself and return a `result` object `BadRequest(errorAsJson)` instead of throwing the exception. I would however like to handle all my exceptions in one place - HttpErrorHandler.

**Comment by gmethvin** [comment]
For uncaught exceptions, `HttpErrorHandler` is called at the top level by the Play server, not by the `HttpRequestHandler` (which is what `route` calls). It should work fine if you call `onClientError` directly and return the result from your action.

I'm not sure why you need to use an exception here at all. If you are writing a test for it then it's a case you probably should be able to handle without exceptions. From Play's perspective, a failed future from a request implies that something truly unexpected happened.

**Comment by tenstriker** [comment]
You mean calling `onClientError` of my custom `ErrorHandler` manually from Action? That doesn't seem like a good idea. If any failure happens in Action it should be propagated automatically to `ErrorHandler`  
It is a form validation error I am trying to test. However, as I mentioned I don't want to clutter my controllers actions and even a base action with error handling and marsheling code. I was hoping every error can eventually caught by `onClientError` and `onServerError` to be handled there expected or unexpected. But looks like I have to divide them apart because `HttpErrorHandler` seem to be meant for only Unexpected errors. Anything expected I would have to handle it in `BaseActionBuilder`. If I however handle unexpected `Throwable` inside my `BaseActionBuilder` then `ErrorHandler`s onServerError won't get called ever I think. It's clearer now. It would be nice though to have ability to handle all errors in one place.  After all for most of them checked or unchecked you are marshaling them on to some Error Object and sending it to client. At least for APIs that is.

**Comment by gmethvin** [comment]
`ErrorHandler` is designed for all different types of errors, but it's bad practice to use exceptions for handling validation of client input, so Play doesn't exactly make it easy to do that. Calling `onClientError` is a perfectly reasonable way of handling it.

Normally you want to handle things like client input errors in the code that actually is doing that validation.

**Comment by tenstriker** [comment]
so to call `onClientError` I would have to inject `ErrorHandler` into my controller, right? I can do that. I def not want to return result object from validation code because it just clutters things. With rest api you use very standard format for any kind of error(client or server). It make sense to gather all such error messages/code/stacktrace etc in one place and then form a result object there instead of every other place. Also if I am using `ErrorHandler` to do all that how do I test it?

**Comment by tenstriker** [comment]
so to call `onClientError` I would have to inject `ErrorHandler` into my controller, right? I can do that. 
Client input error handling can be done in validation code. But it doesn't seem like a good idea to form a ErrorResponse object there and generate result object. For standard error response in rest api there should be way to handle it in one place. Everywhere else in code you can throw an error or return a failed Future with a message and then a common place (either errorhandler or basecontroller) should be able to form an `ErrorResponse` and result object.

**Comment by gmethvin** [comment]
> so to call onClientError I would have to inject ErrorHandler into my controller, right?

You'd have to inject the `HttpErrorHandler`.

> But it doesn't seem like a good idea to form a ErrorResponse object there and generate result object.

Not sure I follow. The `HttpErrorHandler` will directly generate a `Future[Result]`. Is `ErrorResponse` your custom type?

>  In rest api, error response is pretty standard. It has only few fields - code, message, stacktrace etc. there should be way to handle it in one place.

The problem is you're grouping together different types of errors. Usually there is no reason to display a stack trace if there is a validation error; that's why `onClientError` doesn't take an exception.

> Also it's easier to handle localization in one place. from everywhere else I just throw a message or custom exception with messagebundle key of the message.

This could either be done by writing a custom `HttpErrorHandler` that accepts the key and looks it up, or creating a wrapper around the `HttpErrorHandler` that does that.

Without seeing your code it's hard to make any real suggestions. If you want more advice I'd suggest asking on the mailing list.
