### ISSUE TITLE
Potential database connection leak

### ISSUE THREAD

**Issue by brettwooldridge** [playframework/playframework#8196]
* Play Version 2.6.10 (and others)
 * API Scala/Java
 * OS all

I am reporting this on behalf of a user who asked about an apparent connection leak in HikariCP [here](https://stackoverflow.com/questions/48480611/how-do-i-debug-hikaricp-losing-connections) and [here](https://github.com/brettwooldridge/HikariCP/issues/1077).

I (author of HikariCP) am virtually certain that it is not HikariCP leaking the connection, having investigated.

However, when I looked at the stack trace provided by the user, and then into the Play code, I at least spot a *potential* leak in Play.

User's stacktrace:
```
Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@65cd084 on thread pool-1-thread-1, stack trace follows
java.lang.Exception: Apparent connection leak detected
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.jav
a:85)
        at play.api.db.DefaultDatabase.getConnection(Databases.scala:142)
        at play.api.db.DefaultDatabase.withConnection(Databases.scala:152)
        at play.api.db.DefaultDatabase.withConnection(Databases.scala:148)
        at models.summaries.ActionSummary$.listByStripe(ActionSummary.scala:137)
```

Databases:148 calls line 152, which calls line:142. You can see that line 153 sets up a try-finally block, but the connection aquisition occurs outside of that block. That would be fine if getConnection() actually did *only* that. However, line 143 can throw after the connection is borrowed, but before the try-finally, causing the connection to be leaked.

**Comment by maniyarta** [comment]
This is my first attempt in Open Source Community. Shall I take care of this?
