### ISSUE TITLE
Incomplete sentence in JPA docs

### ISSUE THREAD

**Issue by TimMoore** [playframework/playframework#8210]
The [Integrating with JPA](https://www.playframework.com/documentation/2.6.x/JavaJPA#Running-JPA-transactions) contains this sentence fragment under "Running JPA transactions"

> The following methods are available to execute arbitrary code inside a JPA transaction, but

but what? Don't leave me hanging! 😄 

Related to #6489

**Comment by TimMoore** [comment]
Looks like there used to be more in this section of the page that was accidentally removed while making other improvements: https://github.com/playframework/playframework/pull/7253/files#diff-b464087fa0fe9a2943c976da556514e1L89

**Comment by wsargent** [comment]
Argh.  That's mine.  The API is blocking, and the methods don't take that into account, so...

"but they do not include a custom execution context, and so must be wrapped inside a completeable future with a IO bound execution context."

```
 return CompletableFuture.supplyAsync(() -> {
        // lambda is an instance of Function<EntityManager, Long>
        return jpaApi.withTransaction(entityManager -> {
            Query query = entityManager.createNativeQuery("select max(age) from people");
            return (Long) query.getSingleResult();
        });
    }, executionContext);
```
