### ISSUE TITLE
Remove BoneCP

### ISSUE THREAD

**Issue by schmitch** [playframework/playframework#8211]
Actually I think BoneCP should be deprecated and removed from Play (https://github.com/playframework/playframework/blob/master/framework/project/Dependencies.scala#L58)

Basically it isn't maintained any more (since 2013 no release and since 2015 no new code) and even the author themself moved onto HikariCP:
https://github.com/wwadge/bonecp

I guess we should remove it for 2.7 and don't have a deprecation phase.

**Comment by rmcloughlin** [comment]
BoneCP is mentioned in several places on this page:  https://www.playframework.com/documentation/2.6.x/SettingsJDBC

**Comment by PromanSEW** [comment]
I think that it can be closed now as of #8226
