### ISSUE TITLE
LevelChangePropagator does not get applied in LogbackLoggingConfigurator

### ISSUE THREAD

**Issue by carstenlenz** [playframework/playframework#8212]
### Play Version
Play 2.6.9

### API 
Scala

Hi. I was customizing logging for our Play projects when I stumbled over this code from `LogbackLoggerConfigurator`:

```scala
      val levelChangePropagator = new LevelChangePropagator()
      levelChangePropagator.setContext(ctx)
      levelChangePropagator.setResetJUL(true)
      ctx.addListener(levelChangePropagator)
      SLF4JBridgeHandler.install()

      ctx.reset()
```
The documentation of `context.reset()` says: Removes all context listeners except those with `isResetResistant() == true`. 
The implementation of `LevelChangePropagator` returns `false` for this.

That means that the just added `LevelChangePropagator` gets removed immediately after adding it?

Cheers
Carsten

**Comment by cchantep** [comment]
Hi, please use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask questions/for help (this tracker is for confirmed issue/actionable feature request). Best regards.

**Comment by wsargent** [comment]
This is interesting... it's been that way since 2.3.x at least:

https://github.com/playframework/playframework/blob/2.3.x/framework/src/play/src/main/scala/play/api/Logger.scala#L235

but I agree it certainly looks like the reset would wipe out anything happening before that point...
