### ISSUE TITLE
FEATURE: Add `preStopHook` to ApplicationLifecycle

### ISSUE THREAD

**Issue by bharrisau** [playframework/playframework#8221]
# Context

Currently, when a SIGTERM is received by Play it will unbind listening ports and then await the `lifecycle.stop()`. In deployment scenarios like Kubernetes it is beneficial to remain up to to finish off pending requests before shutting down, so a common pattern is to have the `/healthz` endpoint return unhealthy after the SIGTERM and wait 30-40 seconds until unbinding and shutting down. (For example - http://onelineatatime.io/graceful-shutdown-with-play-framework-and-kubernetes/)

# Design

Add a `preStop` hook system to `ApplicationLifecycle` and an associated `addPreStopHook` method. When `lifecycle.preStop()` is called return a `Future` and have servers (https://github.com/playframework/playframework/blob/4c17455e28f056ffcdcd91d151ed8dff605a3146/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala) await that future before unbinding.

If `lifecycle.stop()` is called before `lifecycle.preStop()` then have the lifecycle trigger the preStop hooks at the same time for backwards compatibility.

# Alternative

As shown in the linked article, the current alternative is to intercept the `SIGTERM` using an unsupported API. This works, but causes the compiler to print warnings about the unsupported API.

**Comment by bharrisau** [comment]
Update to the `Alternative` - it looks like the Signal method doesn't actually work. The best option I have at the moment is clearing all the other shutdown hooks that are installed (to remove Play's hook).

```
private List<Thread> clearShutdownHooks() {
    try {
        Class clazz = Class.forName("java.lang.ApplicationShutdownHooks");
        Field field = clazz.getDeclaredField("hooks");
        field.setAccessible(true);

        List<Thread> ret = new ArrayList<>();

        synchronized (clazz) {
            IdentityHashMap<Thread, Thread> currentHooks = (IdentityHashMap<Thread, Thread>) field
                    .get(null);

            ret.addAll(currentHooks.keySet());
            currentHooks.clear();
        }

        return ret;
    } catch (Exception e) {
        throw new RuntimeException(e);
    }
}
```

Not ideal. Not sure if there are cleaner solutions like overriding `play.core.server. AkkaHttpServer:stop()` and setting a different provider in the configuration.

**Comment by marcospereira** [comment]
> Not ideal. Not sure if there are cleaner solutions like overriding play.core.server. AkkaHttpServer:stop() and setting a different provider in the configuration.

This is an alternative too. Of course, we will need better documentation to explain how the API works and what is expected. Maybe the hooks should be part of the `Server` API instead of `ApplicationLifecycle`? That would make more sense to me to have this as part of Server/ServerProvider API if it is essentially changing the way servers will stop. Also, we already have `stopHook` (that is more like a `postStopHook`), so we can add a `preStopHook` that waits for a configured amount of time.

What do you think?

**Comment by TimMoore** [comment]
I think this also ties in with #8042, which integrates Akka's [coordinated shutdown](https://doc.akka.io/docs/akka/current/actors.html#coordinated-shutdown) more tightly into Play.

Coordinated Shutdown defines several shutdown phases and allows users to hook into any of them.

**Comment by TimMoore** [comment]
CC: @ignasi35

**Comment by bharrisau** [comment]
#8042 Looks like a better solution than extending ApplicationLifecycle. The `preStop` hooks would be equivalent to the phase `before-service-unbind`.

**Comment by richdougherty** [comment]
Cc @patriknw.

**Comment by marcospereira** [comment]
@ignasi35 I think we can now close this considering the work that was done to better integrate Akka Coordinated Shutdown.

WDYT?

**Comment by ignasi35** [comment]
(just noticed this)

I think using [Coordinated Shutdown](https://doc.akka.io/docs/akka/current/actors.html#coordinated-shutdown) phases is the best way forward. Recent versions of Akka HTTP added improvements to enable [graceful shutdown of the HTTP server](https://doc.akka.io/docs/akka-http/current/server-side/graceful-termination.html#graceful-termination-using-serverterminator) which are still not used in Play though.

**Comment by marcospereira** [comment]
Closing since we now can use `CoordinatedShutdown` to add more specific stop tasks.
