### ISSUE TITLE
AkkaHTTP NoContentType("none/none") leaks into Play code.

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#8228]
Akka HTTP models the requests/responses *without* a `Content-Type` header with a special value in the codebase. That special value should be converted to `None` in Play's codebase, instead it's propagated leaking `"none/none"`to Play users.

This issue is blocking Lagom's https://github.com/lagom/lagom/issues/1222

**Comment by marcospereira** [comment]
Fixed in #8236.
