### ISSUE TITLE
Errors on sub-projects documentation

### ISSUE THREAD

**Issue by jn-se** [playframework/playframework#8231]
When using assets in sub-projects there must be a specific configuration.
But the Java code snippet for the Assets subclass provided at https://www.playframework.com/documentation/2.6.x/SBTSubProjects is not working.

Original documentation:

```
import play.api.mvc.*;
import controllers.AssetsMetadata;
import play.api.http.HttpErrorHandler;

import javax.inject.Inject;

class Assets extends controllers.Assets {

    @Inject
    public Assets(HttpErrorHandler errorHandler, AssetsMetadata meta) {
        super(errorHandler, meta);
    }

    public Action<AnyContent> at(String path, String file) {
        boolean aggressiveCaching = true;
        return super.at(path, file, aggressiveCaching);
    }
}
```

There is the package missing and the class must be public. Else the SBT compiler won't compile because the Assets class is not being found.

The correct implementation would be:

```
package controllers.admin;

import play.api.mvc.*;
import controllers.AssetsMetadata;
import play.api.http.HttpErrorHandler;

import javax.inject.Inject;

public class Assets extends controllers.Assets {

    @Inject
    public Assets(HttpErrorHandler errorHandler, AssetsMetadata meta) {
        super(errorHandler, meta);
    }

    public Action<AnyContent> at(String path, String file) {
        boolean aggressiveCaching = true;
        return super.at(path, file, aggressiveCaching);
    }
}
```

Please fix this in the documentation.

Furthermore it would be helpful if this snippet shows the _versioned_ method of the Assets class because it is commonly used.

**Comment by marcospereira** [comment]
Hi @jn-se, thank you for the detailed report.

Do you want to submit a pull request to fix the documentation problem? It looks like you already figured out most of the details so that another contribution would be very welcomed.

Thanks.
