### ISSUE TITLE
Why there used object DefaultHttpErrorHandler instead an from applicationProvider?

### ISSUE THREAD

**Issue by hodenlalala** [playframework/playframework#8233]
Hello there. There is an mistake i think. Now we couldn't to override a onServerError (and all implementations as onDevServerError, onProdServerError). So actualy we can but it's useless. Or i'm wrong?
https://github.com/playframework/playframework/blob/145314cbab94d9ffb8abe14c9e4b65a10839b62f/framework/src/play-server/src/main/scala/play/core/server/Server.scala#L114

**Comment by marcospereira** [comment]
Hi @hodenlalala,

The default HTTP request handler is used there because it also handles other scenarios where an application is not available (code compilation errors in dev mode, for example). In the case we manage to get an application, then it is used to get the request handler, as you can see a few lines above:

https://github.com/playframework/playframework/blob/145314cbab94d9ffb8abe14c9e4b65a10839b62f/framework/src/play-server/src/main/scala/play/core/server/Server.scala#L108

Are you experiencing some specific problem in your application? Can you describe what behavior you were expecting and what behavior you are seeing?

**Comment by hodenlalala** [comment]
@marcospereira Sure. I use play 2.6.6 and try to extend a default error handler:
```
package util

import ...

@Singleton 
class CustomErrorHandler @Inject() (env: Environment, 
                              config: Configuration, 
                              sourceMapper: OptionalSourceMapper, 
                              router: Provider[Router]) 
    extends DefaultHttpErrorHandler(env, config, sourceMapper, router) { 

    override def onClientError(request: RequestHeader, statusCode: Int, message: String): Future[Result] = ...
     
    override def onDevServerError(request: RequestHeader, exception: UsefulException): Future[Result] = ...
     
    override def onProdServerError(request: RequestHeader, exception: UsefulException): Future[Result] = ...
}
```
And sure `errorHandler = "util.CustomErrorHandler"` but when i'm trying to invoke them i get:

- onClientError works good
- onServerError invoking from DefaultHttpErrorHandler and prod and dev methods too

So i started debugging and found out that onClientError's invoked from applicationProvider (as custom or default handler) but not onServer (that's only default via DefaultErrorHandler object).
Sorry my English

**Comment by marcospereira** [comment]
Hi @hodenlalala,

I was not able to reproduce it using Play 2.6.11 with the following error handler:

```scala
package http

import javax.inject.{Inject, Provider}

import org.slf4j.LoggerFactory
import play.api.{Configuration, Environment, OptionalSourceMapper}
import play.api.http.DefaultHttpErrorHandler
import play.api.mvc.{RequestHeader, Result}
import play.api.routing.Router

import scala.concurrent.Future

class CustomHttpErrorHandler @Inject()(
  environment: Environment,
  configuration: Configuration, 
  sourceMapper: OptionalSourceMapper,
  router: Provider[Router]
) extends DefaultHttpErrorHandler(environment, configuration, sourceMapper, router) {

  private lazy val logger = LoggerFactory.getLogger(classOf[CustomHttpErrorHandler])

  override def onClientError(request: RequestHeader, statusCode: Int, message: String): Future[Result] = {
    logger.info("Using custom error handler for onClientError")
    super.onClientError(request, statusCode, message)
  }

  override def onServerError(request: RequestHeader, exception: Throwable): Future[Result] = {
    logger.info("Using custom error handler for onServerError")
    super.onServerError(request, exception)
  }
}
```
And to prove the `onServerError` is being used, I created the following action:

```scala
  def error = Action {
    None.get
    Ok
  }
```
When invoking such action I see the following log:

```
[info] h.CustomHttpErrorHandler - Using custom error handler for onServerError
[error] application -

! @773okhcgf - Internal server error, for (GET) [/error] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NoSuchElementException: None.get]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at http.CustomHttpErrorHandler.onServerError(CustomHttpErrorHandler.scala:25)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:310)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:308)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at controllers.HomeController.$anonfun$error$1(HomeController.scala:34)
	at play.api.mvc.ActionBuilder.$anonfun$apply$11(Action.scala:363)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:482)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:480)
	at play.api.mvc.ActionBuilder$$anon$9.invokeBlock(Action.scala:331)
	at play.api.mvc.ActionBuilder$$anon$9.invokeBlock(Action.scala:326)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:419)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
```
Am I missing something? What kind of errors are not being handled by your custom error handler?

**Comment by hodenlalala** [comment]
@marcospereira  nothing is missing. Difference with me only in `error: Action` (i wrote `Action { _ => throw new Exception()}`) but it's not matter. Now i'm closing the issue with wrong supposition about that line but actualy it's strange thing that i can't make it work with official documentation.

**Comment by marcospereira** [comment]
> actualy it's strange thing that i can't make it work with official documentation

Hum, what do you mean? Which parts of the official documentation are wrong or misleading?

**Comment by marcospereira** [comment]
Hi @zanella, thanks for joining the conversation. Which section/paragraph do you think it is not clear?

**Comment by zanella** [comment]
This: 

> If you don’t want to place your error handler in the root package, or if you want to be able to configure different error handlers for different environments, you can do this by configuring the play.http.errorHandler configuration property in application.conf:

**Comment by zanella** [comment]
Ha!, good question, let's see: 

> If you place your error handler in the root package (i.e. package-less) Play will use it by default.
> 
> But, in case you want to:
> 
> - Add it inside a package;
> 
> - Configure different error handlers for different environments;
> 
> Add in `application.conf` the configuration property `play.http.errorHandler` pointing to your custom error handler class

Something like that...

**Comment by marcospereira** [comment]
Sounds like an improvement to me.

Do you want to submit a PR?
