### ISSUE TITLE
Result get sorted automatically by key

### ISSUE THREAD

**Issue by RadhakrishnanKandasamy** [playframework/playframework#8237]
I am using linkedhashmap with some non contiguous key values like 1,2,7,22,14 as key and some string as values. I just convert this map to json using play's default json converter in my controller and return the json response in ok() method. But when i hit the route in my browser or using postman the map is getting sorted by ids. And it will like 1,2,4,7,14,22. Please help me to resolve this. Thanks in advance

Sample data:My input value is [1,value1],[2,value2],[7,value3],[22,value4],[14,value5].

**Comment by marcospereira** [comment]
Hi @RadhakrishnanKandasamy,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) or our [gitter channel](https://gitter.im/playframework/playframework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

At the channels recommended above, it would be helpful if you can share some code or even a test case that shows your problem in more details. For now, I'm closing this, but we can reopen it later if we decide this is a bug.
