### ISSUE TITLE
Why `MessageRequest` is invariant?

### ISSUE THREAD

**Issue by gakuzzzz** [playframework/playframework#8240]
[Request](https://github.com/playframework/playframework/blob/152844c56eed25ba562c4c6c5f5e137e18414734/framework/src/play/src/main/scala/play/api/mvc/Request.scala#L17) and [WrappedRequest](https://github.com/playframework/playframework/blob/152844c56eed25ba562c4c6c5f5e137e18414734/framework/src/play/src/main/scala/play/api/mvc/WrappedRequest.scala#L16) is covariant.

But [MessageRequest](https://github.com/playframework/playframework/blob/152844c56eed25ba562c4c6c5f5e137e18414734/framework/src/play/src/main/scala/play/api/mvc/MessagesRequest.scala#L45) is invariant.

So we can not define generic request wrappers.

for example.

```scala
final case class GenericFooRequest[+A, R[+_] <: Request[_]](
  foo: Foo, underlying: R[A]
) extends WrappedRequest[A](underlying.asInstanceOf[Request[A]])
```

```scala
type FooRequest[+A]        = GenericFooRequest[A, Request]        // can compile.
type MessageFooRequest[+A] = GenericFooRequest[A, MessageRequest] // can not compile!
```

**Comment by marcospereira** [comment]
Hi @gakuzzzz,

Can't see a strong reason for that. Maybe it is just a small glitch in the API. /cc @wsargent.

In that sense, I think we should also make `play.api.test.FakeRequest` covariant too.

**Comment by wsargent** [comment]
It's just a glitch, it should be covarient.

**Comment by marcospereira** [comment]
Thanks, @wsargent.

@gakuzzzz, do you want to submit a PR to fix this?

**Comment by gakuzzzz** [comment]
awesome work! thanx!
