### ISSUE TITLE
Why is Json.fromJson() turning the exception into a RuntimeException ?

### ISSUE THREAD

**Issue by Erwyn** [playframework/playframework#8248]
Hello there,

In https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/libs/Json.java#L77 the exception caught when calling `mapper().valueToTree()` is turned into a generic `RuntimeException` while the underlying Jackson code is throwing a `JsonProcessingException`.

My issue is that in my controllers, I'd like to know if there is an `Exception` raised while processing the Json meaning the payload was invalid (String instead of Integer for instance), but the only way to catch it is to try/catch a `RuntimeException`...

Would it be possible to wrap this `JsonProcessingException` into a `WhateverJsonException` (`PlayJsonProcessingException` ?) that extends `RuntimeException` so that it won't break the uncheckedness of the exception while still letting the opportunity to precisely catch it ?

I'm willing to open a pull request for this but I want to have your opinion on this first. I guess there was a reason for it to be wrapped as a generic `RuntimeException`.

**Comment by rmcloughlin** [comment]
Just call `Json.mapper().valueToTree(data)` instead of `Json.toJson(data)`.

**Comment by marcospereira** [comment]
Hi @Erwyn, 

> My issue is that in my controllers, I'd like to know if there is an Exception raised while processing the Json meaning the payload was invalid.

Invalid payloads are usually handled by the body parsers, at least for malformed JSON. Anyway, like @rmcloughlin said, you can directly use `ObjectMapper` (it is possible to inject it too if you prefer that).

> I'm willing to open a pull request for this but I want to have your opinion on this first. I guess there was a reason for it to be wrapped as a generic RuntimeException.

I think it was to make the API simpler to use considering the success path. Regarding your suggestion of having a `PlayJsonProcessingException` the problem here is how many of the `PlaySomethingException` we will need if we decide to go this path. `PlayDatabaseException`? `PlayXMLParsingException`? I would prefer to avoid that.

**Comment by Erwyn** [comment]
Hi @marcospereira ,

> Invalid payloads are usually handled by the body parsers, at least for malformed JSON. Anyway, like @rmcloughlin said, you can directly use ObjectMapper (it is possible to inject it too if you prefer that).

Two questions then:

1. How is it supposed to work with body parsers? Right now I have this:

```java
            final CodeCreateRepresentation representation;

            try {
                representation = Json.fromJson(
                        request().body().asJson(),
                        CodeCreateRepresentation.class
                );
            } catch (RuntimeException exception) {
                return badRequest();
            }
```

2. How to inject it properly, will I end up with the configured  Play ObjectMapper or just an ObjectMapper ?

**Comment by rmcloughlin** [comment]
Again, just use

`Json.mapper().treeToValue(request().body().asJson, CodeCreateRepresentation.class);`

You don't need to worry about injecting anything.

**Comment by gmethvin** [comment]
`asJson` is basically just checking if the body is a `JsonNode` and doing a cast. The actual parsing happens in the body parser itself, which happens before your action.

The JSON parser *should* do what you're trying to do automatically. It should catch the parse exception and call `HttpErrorHandler.onClientError` to return a 400. Is it not working that way for you?

**Comment by Erwyn** [comment]
It is. But what we are talking about right now is not a malformed payload
but one that is invalid in regard with what is expected. Or am I missing
something?

Le 23 févr. 2018 7:20 PM, "Greg Methvin" <notifications@github.com> a
écrit :

**Comment by gmethvin** [comment]
It's up to you how you want to validate the JSON afterward.

Basically the only thing `Json.fromJson` adds is wrapping the checked exception in a `RuntimeException`. If you prefer the checked exception just use the `ObjectMapper` directly. You can also catch the `RuntimeException`, unwrap, and rethrow exceptions you don't care about.

Your idea is interesting but I don't really see the point of complicating the API. `Json` is just meant to be a thin wrapper over Jackson.

**Comment by Erwyn** [comment]
Well I guess it's two different point of views, one is letting a runtime exception bubble up and return a 500 error, or being able to distinctively catch it and return an appropriate error code because I feel really uncomfortable to write `catch (RuntimeException exception)` but maybe it's just me.

Anyway, thanks for all your kind answers, I suppose I'll go with the `ObjectMapper` directly now!
