### ISSUE TITLE
Play 1.4.5 webapp war with secure module does not work in tomcat 7 server

### ISSUE THREAD

**Issue by fabra59** [playframework/playframework#8255]
Hello, i have an issue with play framework 1.4.5 and tomcat 7 :

Play version 1.4.5
Oracle JDK 7 (1.7.0_79)
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
Windows 7
PostgreSQL 9.4 database
module secure

My webApp starts with a login page with a form (user / password). Submit the form, user is authenticated and then arrives to Application.index

With play 1.2.7.2, no problem, the webapp works fine : i build the war with 'play war' command and deploy it into tomcat 7 server

With play 1.4.5 i build the war with 'play war' command and deploy it into tomcat 7 server : the login page is well displayed but nothing happens when the user submits the form with correct user / password : we can not get access to the other pages of the web app

With play 1.4.5 the webapp works fine with 'play run' command

Many thanx

**Comment by PromanSEW** [comment]
This repository is for Play 2.x
Repository for Play 1.x is here:
https://github.com/playframework/play1
