### ISSUE TITLE
Template，if a list inlude a child list，after

### ISSUE THREAD

**Issue by sujingyu** [playframework/playframework#8257]
### Play Version (2.5.x / etc)
1.2.6

### API (Scala / Java / Neither / Both)
java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10
### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.
![image](https://user-images.githubusercontent.com/18542145/36768001-f92f1e4a-1c77-11e8-93d0-90b844d8a096.png)

data is right, i expected 

![image](https://user-images.githubusercontent.com/18542145/36767941-d071fd2e-1c77-11e8-8755-e1a8f4c42087.png)

### Actual Behavior
but,is shows:
![image](https://user-images.githubusercontent.com/18542145/36768023-07510bfa-1c78-11e8-9737-24c27b48900c.png)

**Comment by marcospereira** [comment]
Hi @sujingyu,

Closing this since issues with Play 1 must be open at https://github.com/playframework/play1.

Best.
