### ISSUE TITLE
Async appender should use shutdown hook for logback graceful shutdown

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#8277]
This applies to all Play 2.x versions:

The async appender in `logback.xml` uses an async appender:

https://github.com/playframework/playframework/blob/master/framework/src/play-logback/src/main/resources/logback-play-default.xml#L15

```xml
  <appender name="ASYNCSTDOUT" class="ch.qos.logback.classic.AsyncAppender">
    <appender-ref ref="STDOUT" />
  </appender>
```

There's a note saying that when logback closes down, there's a small chance that logged messages will still be in the queue, because Logback does not do graceful shutdown by default.  

The logstash-logback-encoder notes reference this "In order to guarantee that logged messages have had a chance to be processed by asynchronous appenders (including the TCP appender) and ensure background threads have been stopped, you'll need to [cleanly shut down logback](https://logback.qos.ch/manual/configuration.html#stopContext) when your application exits." https://github.com/logstash/logstash-logback-encoder/tree/logstash-logback-encoder-4.11#async-appenders

Cleanly in this case means adding a shutdown hook https://logback.qos.ch/manual/configuration.html#shutdownHook but you must specify `DelayingShutdownHook` explicitly, otherwise you'll get a warning https://jira.qos.ch/browse/LOGBACK-1090

```xml
     <shutdownHook class="ch.qos.logback.core.hook.DelayingShutdownHook"/>
```

**Comment by gmethvin** [comment]
Right, so I think the solution here is to add this hook to both `logback.xml` and `logback-test.xml', and perhaps add a note to the docs?

**Comment by wsargent** [comment]
Yep, that's all that's needed.

**Comment by Pro100AlexHell** [comment]
Quote from play doc
> In order to guarantee that logged messages have had a chance to be processed by asynchronous appenders (including the TCP appender) and ensure background threads have been stopped, you’ll need to cleanly shut down logback when your application exits. For details on a shutdown hook, see this documentation. Also you must specify DelayingShutdownHook explicitly

Explain please: why do we need to "ensure background threads have been stopped" when we terminate jvm? I mean: when JVM terminates, then all of threads and pools (include logback's thread pool) will terminate automatically WITHOUT DelayingShutdownHook, is't it? Note: I dont wart to wait for compression of logs.. is it safe to NOT add DelayingShutdownHook in this case? i.e. DelayingShutdownHook is ONLY needed to ensure of completion of compression of logs with not-zero delay. May be I'm wrong and DelayingShutdownHook will need in any case?

**Comment by Pro100AlexHell** [comment]
> There's a note saying that when logback closes down, there's a small chance that logged messages will still be in the queue, because Logback does not do graceful shutdown by default.

Async queue have some events, which is not written to log yet, and what is the bad thing - when we terminate jvm? Does this hook will wait until all events to write to log file? Imho it's not nececcary to wait. Then, I dont understand the reason of this hook and the case of when it's usable.

**Comment by mrubinwch** [comment]
> Does this hook will wait until all events to write to log file? Imho it's not necessary to wait.

I think it's important (for potential troubleshooting needs, etc.) to have all the log entries the application may have produced written out and not lost due to some buffering/queueing. I think, by default, the application should behave "correctly" and not lose data.

**Comment by mkurz** [comment]
There is/was no need anymore starting with Play 2.7 to add the `DelayingShutdownHook` to the logback config, even worse it does interfere with Play's coordinated shutdown hooks which will cleanly close the logger context anyway. See #11532
