### ISSUE TITLE
deduplicated header

### ISSUE THREAD

**Issue by hepin1989** [playframework/playframework#8283]
![image](https://user-images.githubusercontent.com/501740/37239060-491b81a6-246f-11e8-98e5-6267252bbd12.png)

**Comment by marcospereira** [comment]
Oops. Thanks for noticing.

I found some other files with duplicated headers too.

**Comment by wsargent** [comment]
Shouldn't it be 2018?

**Comment by marcospereira** [comment]
@wsargent see #8241.
