### ISSUE TITLE
Add Java APIs for TestServer.runningHttpPort and TestServer.runningHttpsPort

### ISSUE THREAD

**Issue by marcospereira** [playframework/playframework#8294]
### Play Version

2.6.4 and above.

### API

Java.

### Expected Behavior

We need to have Java APIs for `TestServer.runningHttpPort` and `TestServer.runningHttpsPort`. Ideally, these APIs will return an `Optional<Integer>`.

### Actual Behavior

We currently have `TestServer.port` which is deprecated:

https://github.com/playframework/playframework/blob/21ba2d606931610806f43a6454e46967f477ebf4/framework/src/play-test/src/main/scala/play/api/test/TestServer.scala#L72-L76

And it is recommending to use either `TestServer.runningHttpPort`:

https://github.com/playframework/playframework/blob/21ba2d606931610806f43a6454e46967f477ebf4/framework/src/play-test/src/main/scala/play/api/test/TestServer.scala#L78-L81

Or `TestServer.runningHttpsPort`:

https://github.com/playframework/playframework/blob/21ba2d606931610806f43a6454e46967f477ebf4/framework/src/play-test/src/main/scala/play/api/test/TestServer.scala#L83-L86

But both are returning `Option[Int]`. That is a Scala API, and we need to add the Java correspondents.

**Comment by Shenker93** [comment]
Java 8 also provides _OptionalInt_ container class, it wraps primitive _int_ value, so container object is little bit more lightweight and more precisely conveys the essence. I think it is better to use such approach here. @marcospereira , what do you think of it? I can to open a PR and implement such conversion in [java TestServer class](https://github.com/playframework/playframework/blob/master/framework/src/play-test/src/main/java/play/test/TestServer.java)

**Comment by marcospereira** [comment]
@Shenker93 makes sense to me.

>  I can to open a PR and override such methods for java API

Thank you!
