### ISSUE TITLE
Native library support in development mode(play run)

### ISSUE THREAD

**Issue by chrishumphrey** [playframework/playframework#8297]
I am having the same issue I found in 
Native library support in development mode(play run) #2212
I saw several people still having the issue when it was closed, is there a workaround for the issue?

I am using play framework 2.6.11 (2.6.12 also gives the same issue)

Linux CentOS 7.4

3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

openjdk version "1.8.0_161"

**Comment by marcospereira** [comment]
To anyone having similar problems, see if this project can help you:

https://github.com/playframework/play-native-loader

You will need to create your own application loader as documented here: https://github.com/playframework/play-native-loader/blob/master/src/main/java/play/libs/NativeLoader.java
