### ISSUE TITLE
application to routes

### ISSUE THREAD

**Issue by saikirandarra** [playframework/playframework#8301]
resolve this  issue in my project

[error] /home/govinda/play-2.2.6/Application/dsk/conf/routes:7: object ap is not a member of package controllers
[error] POST     /log                       controllers.ap.validate()
[error] /home/govinda/play-2.2.6/Application/dsk/conf/routes:8: object ap is not a member of package controller
[error] POST     /lt                         controller.ap.logout()
[error] /home/govinda/play-2.2.6/Application/dsk/conf/routes:7: object ap is not a member of package controllers
[error] POST     /log                       controllers.ap.validate()
[error] /home/govinda/play-2.2.6/Application/dsk/conf/routes:8: object ap is not a member of package controller
[error] POST     /lt                         controller.ap.logout()
[error] four errors found
[error] (compile:compile) Compilation failed
[error] Total time: 8 s, completed 19 Mar, 2018 10:32:36 AM

**Comment by gmethvin** [comment]
@saikirandarra This is an issue tracker for the playframework.com website. If you're looking for help you can check out https://discuss.lightbend.com/c/play.
