### ISSUE TITLE
Java context args get lost (not available in error handler)

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#8303]
Before an exception occurs we already put something in the Java context args map:
```java
public Result index() {
    // First let's put something in the context args
    Http.Context.current().args.put("mykey", someObject);
    // Unfortunately some exception occurs...
    throw new RuntimeException("booom!");
}
```
Now the error handler kicks in and we want to access the value we just put in the args map:
```java
public class SomeHttpErrorHandler implements play.http.HttpErrorHandler {

    @Override
    public CompletionStage<Result> onServerError(play.mvc.Http.RequestHeader request,
                                                 Throwable exception) {
        // BUG! someObject expected, but actually it is null:
        Http.Context.current().args.get("mykey"); 
    }

    // ...
}
```
You see we can't access the context args value we just saved in the args map anymore. It's just not there!
Imagine you would have to close a resource you just put in the context args or if you want to write information e.g. about the current user (which you saved in the ctx args) in the log file so you know for which user a request failed...

The problem can be found here:
* When the exception occurs [this `try` block](https://github.com/playframework/playframework/blob/2.6.12/framework/src/play/src/main/scala/play/core/j/JavaAction.scala#L85-L91) calls its `finally` clause which sets the `oldContext` - in whose context args map `mykey` from the example above wasn't set of of course. So here we are, this try/finally causes the context args to be lost.

-----

So you might think now, ok we are [going to remove `Context.current` soon anyway](https://github.com/playframework/playframework/issues/6168), so we should/will in future pass the `Http.Context` object to `onServerError` as argument directly anyway (something like: `onServerError(RequestHeader request, Context context, Throwable exception)` - who knows?). No, this wouldn't work either. Why? Because when the exception occurs we recover with a *Scala* http error handler first (see [here](https://github.com/playframework/playframework/blob/2.6.12/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L320)) - which actually is a `JavaHttpErrorHandlerAdapter` - which [calls `invokeWithContext`](https://github.com/playframework/playframework/blob/2.6.12/framework/src/play/src/main/scala/play/core/j/JavaHttpErrorHandlerAdapter.scala#L22) - which eventually creates the `Http.Context` to be used for the http error handler solely from the request header - and therefore with an empty args map; as you can see [here](https://github.com/playframework/playframework/blob/683e8c01b5c231adec91d9d0da72658fdd516836/framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala#L161-L169). First of all we don't even have the context args exposed [here](https://github.com/playframework/playframework/blob/2.6.12/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L320) to pass it to the *Scala* error handler in the first place and even if in future we would have it available there we would then have to pollute the *Scala* error handler api with the *Java* context args... Bad idea - why should the scala http error handler care about a concept of the Java api just to pass it through?

-----

**The solution: The context args map should become an request attribute so we are sure it can be accessed everywhere (where a request is available).**

**Comment by mkurz** [comment]
Not relevant anymore.

**Comment by ahmetsemsettinozdemirden** [comment]
@mkurz i have the same issue. Can you share with me that how did you overcome this?

**Comment by ahmetsemsettinozdemirden** [comment]
We are using https://github.com/franzgranlund/play-java-jwt jwt auth. In the JWTFilter after user authenticated we add user object to `ctx.args` and use it in the controllers. When an error occured, since attrs are gone, we can not print the user data.

**Comment by mkurz** [comment]
You just have to do the same in the error handler what the JWTFilter does for you to retrieve the user. I guess is that is something like parsing the cookie, get/validated the user-id, etc. Again, in the errorhandler the request is completly fresh again, without any filters applied. That makes sense because the error handler is the last resort if an error occurs (that could also be in a filter, in the action method, wherever). If there would be any data left in the request that comes from a filter or the action method, who knows if that data isn't corrupted, incomplete or whatever because of the exception?

Instead of getting the user you could also of course just display a very simple error page without any user data and with a link like "back to application". Many applications just do that (even facebook, youtube etc.)

**Comment by ahmetsemsettinozdemirden** [comment]
Actually JWTFilter puts the user into context and we use it in the action methods. There is no problem in that. For the error handler part, since we use play as an API for mobile client, when an exception thrown in action method we want the catch it and log corresponding user data.

**Comment by mkurz** [comment]
OK, I had a look again and there is a workaround by using [Action composition](https://www.playframework.com/documentation/2.6.x/JavaActionsComposition).

Define a new action annotation:
```java
import play.mvc.With;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@With(LogExceptionAction.class)
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface LogException {
}
```
The corresponding action:

```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import play.mvc.Action;
import play.mvc.Http;
import play.mvc.Result;
import java.util.concurrent.CompletionStage;

public class LogExceptionAction extends Action<LogException> {

    private final static Logger logger = LoggerFactory.getLogger(LogExceptionAction.class);

    public CompletionStage<Result> call(final Http.Context ctx) {
        try {
            return delegate.call(ctx);
        } catch(final Exception e) {
            logger.error("Exception occured when user " + ctx.args.get("user") + " was logged in.", e);
            throw e;
        }
    } 
}
```

And then annotate you controller with `@LogException`:

```java
@LogException
public class MyController extends Controller {
    // ...
}
```

As you can see you can now log the user, retrieved from the context args, to log an exception. The errorhandler will still be called.


What you can also do is define your own exception:
```java
public class LoggedInException extends RuntimeException {

    private final Object user;

    public LoggedInException(final Object user, final Throwable wrapped) {
        super(wrapped);
        this.user = user;
    }

    public Object getUser() {
        return this.user;
    }
}
```

and then the action could look like this:
```java
import play.mvc.Action;
import play.mvc.Http;
import play.mvc.Result;
import java.util.concurrent.CompletionStage;

public class LogExceptionAction extends Action<LogException> {

    public CompletionStage<Result> call(final Http.Context ctx) {
        try {
            return delegate.call(ctx);
        } catch(final Exception e) {
            throw new LoggedInException(ctx.args.get("user"), e);
        }
    } 
}
```

This now passes the user within the custom exception to the error handler:

```java
public class SomeHttpErrorHandler implements play.http.HttpErrorHandler {

    @Override
    public CompletionStage<Result> onServerError(Http.RequestHeader request, Throwable exception) {
        if(exception instanceof LoggedInException) {
            logger.error("Exception occured when user " + ((LoggedInException)exception).getUser()) + " was logged in.", exception);
        }
        // ... rest of the code
    }
```

One more thing: If you don't want to annotate your controllers (or if you fear that you forget to annotate one) you can also try to use your own [action creator](https://www.playframework.com/documentation/2.6.x/JavaActionCreator#Action-creators) instead of action annotation. That should work too. The advantage is it would be more general.

Let me know if that worked for you.

**Comment by ahmetsemsettinozdemirden** [comment]
Thank you! it's working very well. 💯
