### ISSUE TITLE
Application.conf typo

### ISSUE THREAD

**Issue by nathanmerrill** [playframework/playframework#8305]
I checked out the play-java-starter-example project.  In the `application.conf` on line 59, it says:

    # If there are any built-in modules that you want to disable, you can list them here.
    #enabled += my.application.Module

It should say: 

    # If there are any built-in modules that you want to enable, you can list them here.
    #enabled += my.application.Module

### Play Version (2.5.x / etc)

2.6

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10

**Comment by wsargent** [comment]
This should go on https://github.com/playframework/play-java-starter-example

**Comment by nathanmerrill** [comment]
Done, thanks :)
