### ISSUE TITLE
play test stuck when used with twitterbootstrap

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#832]
Hi,
If I create a new project and run 'play test' the default tests are run and the tests finish but if I add the twitterbootstrap library:
- bootstrap.js (v.2.3.1) copied to public/javascripts - added to main.scala.html

then 'play test' hangs. It hangs for the test in IntegrationSpec.scala.

Migrated from http://play.lighthouseapp.com/projects/82401/tickets/1038-play-test-stuck-when-used-with-twitterbootstrap
@gissues:{"order":69.23076923076917,"status":"backlog"}

**Comment by philipmjohnson** [comment]
@jroper Any progress on "out of the box integration with PhantomJS"?  HTMLUNIT has not improved since 2013. :(

**Comment by benmccann** [comment]
@philipmjohnson you don't really need to do much to use PhantomJS with Play. See my comment above. Is there somewhere this falls short for you?

**Comment by philipmjohnson** [comment]
Hi Ben, 

You're right: using PhantomJS is easier than I expected (I thought I would have to implement the helper method myself).  Thank you! 

I have now spent a couple of hours trying to reduce the debugging output from PhantomJS.  I finally found [this message ](https://github.com/playframework/playframework/issues/3688) which has some good suggestions, but if I create a logging.properties file with:

    org.openqa.selenium.phantomjs.PhantomJSDriverService.level = SEVERE

and set my JAVA_OPTS appropriately, I do not get any reduction in output.  Here is my activator invocation with debugging on which shows it is picking up the -D argument from JAVA_OPTS but not reducing the debugging output at all:

```
[~/projecthosting/ics613s15/digits]-> activator -d test
[residual] arg = 'test'
# Executing command line:
/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/bin/java
-Dactivator.home=/Users/johnson/java/activator-1.2.12
-Xms1024m
-Xmx1024m
-XX:MetaspaceSize=64m
-XX:MaxMetaspaceSize=256m
-Djava.util.logging.config.file=logging.properties
-jar
/Users/johnson/java/activator-1.2.12/activator-launch-1.2.12.jar
test

[info] Loading project definition from /Users/johnson/projecthosting/ics613s15/digits/project
[info] Set current project to digits (in build file:/Users/johnson/projecthosting/ics613s15/digits/)
[INFO  - 2015-03-05T23:19:04.440Z] GhostDriver - Main - running on port 26149
[INFO  - 2015-03-05T23:19:04.580Z] Session [03e04800-c38e-11e4-be3f-b394725f4d24] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.0.0 Safari/538.1","webSecurityEnabled":true}
[INFO  - 2015-03-05T23:19:04.580Z] Session [03e04800-c38e-11e4-be3f-b394725f4d24] - page.customHeaders:  - {}
[INFO  - 2015-03-05T23:19:04.580Z] Session [03e04800-c38e-11e4-be3f-b394725f4d24] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.0.0","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"mac-10.8 (Mountain Lion)-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2015-03-05T23:19:04.580Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 03e04800-c38e-11e4-be3f-b394725f4d24
[INFO  - 2015-03-05T23:19:05.961Z] ShutdownReqHand - _handle - About to shutdown
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 9 s, completed Mar 5, 2015 1:19:06 PM
```

Do you have any ideas on what I'm doing wrong, or if there's a new way to deal with this?

Thanks so much.

**Comment by benmccann** [comment]
Yeah, phantomjs is pretty noisy by default though I've never looked into it so I don't have thoughts off the top of my head

**Comment by philipmjohnson** [comment]
Just wrote up this summary (and will post to the play mailing list for comments):

http://philipmjohnson.github.io/ics613s15/morea/templates/reading-htmlunit-phantomjs.html

If you happen to have any ideas for improvement, please let me know.
