### ISSUE TITLE
Evolutions treat PLPGSQL dolar sign as comment

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#8326]
### Play Version (2.5.x / etc)
2.6.11

### API (Scala / Java / Neither / Both)
N/A

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
JDK 9.0.4

### Library Dependencies
Postgres 9.3.6

### Expected Behavior
I can use PLPGSQL in evolution script

### Actual Behavior
Play throws:
```
We got the following error: Unterminated dollar quote started at position 60 in SQL CREATE OR REPLACE FUNCTION do_something() RETURNS trigger AS $$ BEGIN PERFORM some_action(OLD.my_id); RETURN OLD; END. Expected terminating $$ [ERROR:0, SQLSTATE:42601], while trying to run this SQL script:
CREATE OR REPLACE FUNCTION do_something() RETURNS trigger AS $$
BEGIN
   PERFORM some_action(OLD.my_id);
   RETURN OLD;
END;
$$ LANGUAGE plpgsql;
```
Of course the query has [valid structure](https://www.postgresql.org/docs/9.3/static/plpgsql-structure.html) and works fine in Postgres. 
I also tried with and without escaping `;` as [documentation says](https://www.playframework.com/documentation/2.6.x/Evolutions#Evolutions-scripts)

**Comment by mkurz** [comment]
> I also tried with and without escaping `;`

Can you show us what that PL/pgSQL code looked like?

**Comment by eximius313** [comment]
without:
```
CREATE OR REPLACE FUNCTION do_something() RETURNS trigger AS $$
BEGIN
   PERFORM some_action(OLD.my_id);
   RETURN OLD;
END;
$$ LANGUAGE plpgsql;
```
with:
```
CREATE OR REPLACE FUNCTION do_something() RETURNS trigger AS $$
BEGIN
   PERFORM some_action(OLD.my_id);;
   RETURN OLD;;
END;
$$ LANGUAGE plpgsql;
```

**Comment by mkurz** [comment]
@eximius313 I think you missed to escape the `;` after the `END`:
```
CREATE OR REPLACE FUNCTION do_something() RETURNS trigger AS $$
BEGIN
   PERFORM some_action(OLD.my_id);;
   RETURN OLD;;
END;;
$$ LANGUAGE plpgsql;
```

**Comment by eximius313** [comment]
OMG, you are right!
Sorry for confusion
