### ISSUE TITLE
Deprecate the Twitter bootstrap helper

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#834]
The Twitter bootstrap form template helper wasn't updated since a year and does not yet fully support Bootstrap 2.
In a [pull request](https://github.com/playframework/Play20/pull/217) guillaumebort suppose to deprecated the helper in the next Play version (and publish a Plugin for the helper?).

But in Play 2.1 the [Play Template helper Documentation](http://www.playframework.com/documentation/2.1.0/ScalaFormHelpers) still suppose to use the Twitter template helper and there is no note that Bootstrap 2 isn't fully supported which is frustrating for newbies like me.
@gissues:{"order":66.6666666666666,"status":"backlog"}

**Comment by benmccann** [comment]
The Play 2.3 migration guide mentions this has already been deprecated: https://www.playframework.com/documentation/2.3.x/Migration23

Closing this issue as addressed
