### ISSUE TITLE
Is possible to wait database connection?

### ISSUE THREAD

**Issue by biwugang** [playframework/playframework#8356]
### Are you looking for help?
I add database configuration in application.conf file.
if database is ready, then play will start success,
but if database is not ready, play will exit with:
  Configuration error: Configuration error[Cannot connect to database [default]]

so, Is possible to wait database ready and then continue to start play?
how to implement?

**Comment by biwugang** [comment]
ok, I see. I ask this question to forum and close this one

**Comment by DelukeGit** [comment]
am trying to connect to MySQL database to my play 2.9 project n java for the first time and am not understanding anything in the documentation. can you help me out with the steps to go through.

**Comment by mkurz** [comment]
@DelukeGit This is an issue tracker, if you need help either ask in our discord play-user channel or open a discussion. Thanks!
