### ISSUE TITLE
Some out-of-date info on SBTDebugging page

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#8358]
This page https://www.playframework.com/documentation/2.6.x/SBTDebugging appears to have some out of date / incorrect information on it.  For example it says

_The reports can be found in the `target/resolution-cache/reports` directory_

but they are actually located in `target/scala-2.12/resolution-cache/reports/`

Also it describes using a `last compile` command in sbt but this doesn't seem to work.

**Comment by wsargent** [comment]
@Kavit900 the markdown for the documentation is here: https://github.com/playframework/playframework/edit/2.6.x/documentation/manual/working/commonGuide/build/SBTDebugging.md
