### ISSUE TITLE
Document Play Controller Lifecycle

### ISSUE THREAD

**Issue by eluchsinger** [playframework/playframework#8365]
Is it possible to add the lifecycle of Play components (i.e. Controllers) to the documentation? I don't know when they are instantiated, if I can change their behaviors, etc.

I could find a question about the Lifecycle of Controllers on [SO](https://stackoverflow.com/questions/34863486/is-each-play-framework-web-request-handled-with-a-new-dependency-injected-contro), but wouldn't it be nice to have something official?

**Comment by gmethvin** [comment]
In general, the lifecycle of your controllers and anything injected directly into your controllers is the same as the app itself. 

The section on [router dependency injection](https://www.playframework.com/documentation/2.6.x/ScalaRouting#Dependency-Injection) has some detail:
> Play’s default routes generator creates a router class that accepts controller instances in an @Inject-annotated constructor. That means the class is suitable for use with dependency injection and can also be instantiated manually using the constructor.

So by default one instance of each controller is created and passed to the generated router's constructor.

There is also some info on the [dependency injection page](https://www.playframework.com/documentation/2.6.x/ScalaDependencyInjection#Injected-routes-generator), which explains how to inject a `Provider`:
> When using the injected routes generator, prefixing the action with an @ symbol takes on a special meaning, it means instead of the controller being injected directly, a Provider of the controller will be injected. This allows, for example, prototype controllers, as well as an option for breaking cyclic dependencies.

There's nothing special Play does to manage component lifecycle beyond what your dependency injection framework does by itself. If you want to do something like make a component per request, you have to set that up manually. If you want to make sure you only have one instance of a stateful component, you can do that by using `@Singleton` in runtime DI or declaring as a `lazy val` in compile-time DI.

I guess the question is: what are exactly are you trying to customize? And where did you expect to look in the current docs to find that information?

**Comment by marcospereira** [comment]
I'm closing this, but we can reopen it later if we have some answers to @gmethvin questions.
