### ISSUE TITLE
ConfigLoader for durations drops time unit information

### ISSUE THREAD

**Issue by kubukoz** [playframework/playframework#8370]
To reproduce:

1. Add a duration to your config, e.g. `reload-interval = 1 minute`
2. Get it from the `Configuration` object:

```scala
val interval = config.get[FiniteDuration]("reload-interval")
```

Expected behavior:

```
scala> interval.toString
1 minute
```

Actual behavior:

```
scala> interval.toString
60000000000 nanos
```

Play: 2.6.12
Scala: 2.12.5

**Comment by kubukoz** [comment]
I think this could be fixed by changing the implementation of `implicit val finiteDurationLoader: ConfigLoader[FiniteDuration]` from 

```scala
ConfigLoader(_.getDuration).map(_.toNanos.nanos)
```

to

```scala
ConfigLoader(_.getDuration).map(duration => Duration.fromNanos(duration.nanos))
```

It can still be a bit inaccurate in terms of maintaining the unit specified in the config, as `Duration.fromNanos(long)` will use "the coarsest possible time unit which can exactly express this duration" (from the scaladoc), but it'll definitely describe the duration in a more human readable way.

**Comment by gmethvin** [comment]
I agree it's better to have a more human-readable duration value so this is a great suggestion. It'd be nice to be able to get the same units but that's not something config lets us do.

**Comment by kubukoz** [comment]
I opened a first draft PR ;) https://github.com/playframework/playframework/pull/8371
