### ISSUE TITLE
Ebean version in doumentation not found

### ISSUE THREAD

**Issue by decapo01** [playframework/playframework#8372]
The ebean version given in the documentation for 2.6.x ([here](https://www.playframework.com/documentation/2.6.x/JavaEbean)) leads to an unresolved dependency.  If you look at the repo for the play ebean plugin ([here](https://github.com/playframework/play-ebean)) it appears that the latest version is 4.1.0 so maybe this is a typo but maybe there is something wrong with the repo.

### Play Version (2.5.x / etc)

2.6.x

### API (Scala / Java / Neither / Both)

Java

### Operating System

Linux notebook 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### JDK (OpenJDK 1.8.x)

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)

### Expected Behavior

Dependencies would be downloaded

### Actual Behavior

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.sbt#sbt-play-ebean;4.0.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-play-ebean;4.0.1: not found

**Comment by marcospereira** [comment]
Closing since this should be open in playframework/play-ebean repository instead. @decapo01, please, feel free to open an issue there. :-)

**Comment by decapo01** [comment]
I moved it over there. @marcospereira  I see you are a main contributor there too.
