### ISSUE TITLE
Play application stays running when user ActorSystem terminates

### ISSUE THREAD

**Issue by johanandren** [playframework/playframework#8384]
When the user injects a user `ActorSystem`, which is then terminated, either on purpose or because a critical error has happened (`Error` thrown in actor, bubbling up to user guardian, killing the actor system) the Play application keeps running.

My expectation is that if I'm using Akka inside of my web app and the `ActorSystem` terminates the play app would also terminate so that I notice, rather than keep running, especially since this will never "heal".

If there are use cases where it is ok that the `ActorSystem` is terminated, perhaps we could introduce a setting to support this, but have it default to kill the app?

**Comment by johanandren** [comment]
Verified that this applies both to the dev mode and the prod mode.

**Comment by schmitch** [comment]
Guess this is a related PR for it: https://github.com/playframework/playframework/pull/8406

**Comment by ignasi35** [comment]
I'm a bit confused: "When the user injects a user ActorSystem". @johanandren are you saying the user receives the `ActorSystem` managed by DI and used by the `Application` or that the user handled the creation of a completely separate `ActorSystem`?

Whenever the Application's `ActorSystem` terminates it should take the `Application` down and, in some `Environment`s the also the `Server`.

#8406 is moving all Play shutdown sequence logic to Akka`s `CoordinatedShutdown` so this issue will be automatically resolved if Akka runs `CoordinatedShutdown` when the `ActorSystem` terminates.

**Comment by marcospereira** [comment]
@johanandren, if I remember correctly, this is happening only in DEV mode, right?

> Whenever the Application's ActorSystem terminates it should take the Application down and, in some Environments the also the Server.

I need to confirm this, but I think this is the current behavior in PROD mode. For DEV mode, where we have two actor systems, the behavior is different.

**Comment by johanandren** [comment]
See my second comment above

**Comment by johanandren** [comment]
Sorry, I take that back, I don't remember it clearly, but it seems from a conversation in another channel that when I tried some more it did in fact work fine in prod mode.

**Comment by marcospereira** [comment]
Closing. See the last comment from @johanandren. :-)
