### ISSUE TITLE
Netty Server Recycler Infinite Loop

### ISSUE THREAD

**Issue by pettyjamesm** [playframework/playframework#8397]
Opening an issue since the [PR that will fix the issue](https://github.com/playframework/playframework/pull/8389) is currently only marked as a dependency update.

The version of netty that Play 2.6.13 ships with (4.1.23.Final) has an infinite loop in the recycler that will consume a whole CPU core and fail to clean up resources once triggered. The issue [was fixed in netty-common 4.1.24.Final](https://github.com/netty/netty/pull/7878) and can be worked around by adding it directly as a dependency (ie: `libraryDependencies += "io.netty" % "netty-common" % "4.1.24.Final"`).

Play should merge the netty update ASAP. See charts below for evidence from our staging environment:

CPU usage spikes and stays hot ~20 minutes after application startup:
<img width="535" alt="screen shot 2018-05-05 at 11 42 37 am" src="https://user-images.githubusercontent.com/871949/39664967-3e18beec-505a-11e8-8ca8-0bf3edb07d79.png">

100% CPU time in Recycler Flame Graph:
<img width="1194" alt="screen shot 2018-05-05 at 11 50 39 am" src="https://user-images.githubusercontent.com/871949/39665001-98d7aed8-505a-11e8-938d-6273c8c17e32.png">

### Play Version (2.5.x / etc)
2.6.13

### API (Scala / Java / Neither / Both)
Both, probably- scala definitely

### Library Dependencies
- Netty Server

**Comment by richdougherty** [comment]
I have tagged this for the 2.6.14 release and made a comment on the PR. Thanks for raising this issue.

**Comment by richdougherty** [comment]
Should be fixed by #8389.
