### ISSUE TITLE
why there's no CRUD: Administration generator in Play 2.x

### ISSUE THREAD

**Issue by kevinobama** [playframework/playframework#8401]
why there's no CRUD: Administration generator in Play 2.x?
I only see it Play 1 which is https://www.playframework.com/documentation/1.2.x/crud#usage

Play Version (2.6.x / etc)
API (Java )
Centos7
JDK (Oracle 1.8.0_72)

**Comment by wsargent** [comment]
This is functionality provided by external modules, i.e. https://github.com/hakandilek/play2-crud

**Comment by wsargent** [comment]
Closing as this is not an issue

**Comment by kevinobama** [comment]
thanks. let me try Slick.

**Comment by wsargent** [comment]
Also see https://manuel.bernhardt.io/2013/07/08/crud-trait-for-slick-models-in-the-play-framework/
