### ISSUE TITLE
warnings when JDK 10 uses for Play Framework 2.6.13

### ISSUE THREAD

**Issue by unistylist** [playframework/playframework#8417]
###Environment
Play Version 2.6.13
Scala 2.12.4
All Operating System
JDK 10
sbt 1.1.2

### Library Dependencies
libraryDependencies += guice
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "3.1.2" % Test

### Actual Behavior
when I execute default template which is "playframework/play-scala-seed.g8" by "sbt run"
it says several warnings.

1. Conflicting Dependencies

> [PlayTest] $ evicted
[info] Updating ...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* com.google.guava:guava:22.0 is selected over 19.0
[warn] 	    +- com.typesafe.play:play_2.12:2.6.13                 (depends on 22.0)
[warn] 	    +- com.google.inject:guice:4.1.0                      (depends on 19.0)
[warn] 	* com.typesafe.akka:akka-stream_2.12:2.5.11 is selected over 2.4.20
[warn] 	    +- com.typesafe.play:play-streams_2.12:2.6.13         (depends on 2.5.11)
[warn] 	    +- com.typesafe.akka:akka-http-core_2.12:10.0.13 ()   (depends on 2.4.20)
[warn] 	* com.typesafe.akka:akka-actor_2.12:2.5.11 is selected over 2.4.20
[warn] 	    +- com.typesafe.play:play_2.12:2.6.13                 (depends on 2.5.11)
[warn] 	    +- com.typesafe.akka:akka-stream_2.12:2.5.11 ()       (depends on 2.5.11)
[warn] 	    +- com.typesafe.akka:akka-slf4j_2.12:2.5.11 ()        (depends on 2.5.11)
[warn] 	    +- com.typesafe.akka:akka-parsing_2.12:10.0.13 ()     (depends on 2.4.20)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Here are other depedency conflicts that were resolved:
[info] 	* org.scala-lang.modules:scala-parser-combinators_2.12:1.0.6 is selected over 1.0.4
[info] 	    +- com.typesafe:ssl-config-core_2.12:0.2.2            (depends on 1.0.4)
[info] 	    +- com.typesafe.play:play_2.12:2.6.13                 (depends on 1.0.4)
[info] 	* com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.8.11 is selected over 2.8.9
[info] 	    +- com.typesafe.play:play_2.12:2.6.13                 (depends on 2.8.11)
[info] 	    +- com.typesafe.play:play-json_2.12:2.6.9             (depends on 2.8.9)
[info] 	* com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.8.11 is selected over 2.8.9
[info] 	    +- com.typesafe.play:play_2.12:2.6.13                 (depends on 2.8.11)
[info] 	    +- com.typesafe.play:play-json_2.12:2.6.9             (depends on 2.8.9)
[info] 	* com.fasterxml.jackson.core:jackson-databind:2.8.11 is selected over {2.8.2, 2.8.9}
[info] 	    +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.8.11 (depends on 2.8.11)
[info] 	    +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.8.11 (depends on 2.8.11)
[info] 	    +- com.typesafe.play:play_2.12:2.6.13                 (depends on 2.8.11)
[info] 	    +- com.typesafe.play:play-json_2.12:2.6.9             (depends on 2.8.9)
[info] 	    +- io.jsonwebtoken:jjwt:0.7.0                         (depends on 2.8.2)
[info] 	* com.fasterxml.jackson.core:jackson-annotations:2.8.11 is selected over {2.8.9, 2.8.0}
[info] 	    +- com.typesafe.play:play_2.12:2.6.13                 (depends on 2.8.11)
[info] 	    +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.8.11 (depends on 2.8.0)
[info] 	    +- com.fasterxml.jackson.core:jackson-databind:2.8.11 (depends on 2.8.0)
[info] 	    +- com.typesafe.play:play-json_2.12:2.6.9             (depends on 2.8.9)
[info] 	* com.fasterxml.jackson.core:jackson-core:2.8.11 is selected over {2.8.9, 2.8.10}
[info] 	    +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.8.11 (depends on 2.8.11)
[info] 	    +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.8.11 (depends on 2.8.11)
[info] 	    +- com.typesafe.play:play_2.12:2.6.13                 (depends on 2.8.11)
[info] 	    +- com.fasterxml.jackson.core:jackson-databind:2.8.11 (depends on 2.8.10)
[info] 	    +- com.typesafe.play:play-json_2.12:2.6.9             (depends on 2.8.9)
[info] 	* com.typesafe:config:1.3.2 is selected over 1.2.0
[info] 	    +- com.typesafe:ssl-config-core_2.12:0.2.2            (depends on 1.2.0)
[info] 	    +- com.typesafe.akka:akka-actor_2.12:2.5.11 ()        (depends on 1.2.0)
[success] Total time: 2 s, completed May 17, 2018 5:00:06 PM

I solve this problem by adding following lines in build.sbt

val akkaVersion = "2.5.11"
dependencyOverrides ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % akkaVersion,
  "com.typesafe.akka" %% "akka-stream" % akkaVersion,
  "com.google.guava" % "guava" % "22.0",
  "org.slf4j" % "slf4j-api" % "1.7.25"
)

codes from #7832 
However, is this radical solution? no problem for the futures?

2. Warnings for illegal reflective access

> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by play.runsupport.classloader.DelegatingClassLoader (file:/C:/Users/user/.ivy2/cache/com.typesafe.play/run-support_2.12/jars/run-support_2.12-2.6.13.jar) to
method java.lang.ClassLoader.findResource(java.lang.String)
WARNING: Please consider reporting this to the maintainers of play.runsupport.classloader.DelegatingClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

I  could not find solution for this warning.

### Expected Behavior
No warnings

###Reproducible Test Case
sbt new playframework/play-scala-seed.g8

**Comment by schmitch** [comment]
Actually that is fixed on master https://github.com/playframework/playframework/commit/e6ed774086368eb7e70fba2b7019494b28dc74b8

**Comment by unistylist** [comment]
Ohh Thanks

**Comment by schmitch** [comment]
You can Even ignore it as long as you use play on jdk10 with a classpath

**Comment by unistylist** [comment]
Hm... What classpath should I add?
