### ISSUE TITLE
Broken play-enhancer url on documentation

### ISSUE THREAD

**Issue by rozkerim** [playframework/playframework#8438]
Hi,

At [this page](https://www.playframework.com/documentation/2.6.x/PlayEnhancer) of documentation, play enhancer url is given as `addSbtPlugin("com.typesafe.sbt" % "sbt-play-enhancer" % "1.1.0")`. I could not find this version on maven repository. I added enhancer as a library by adding this code to `build.sbt`:
`libraryDependencies += "com.typesafe.play" % "play-enhancer" % "1.2.2"`

I think first url is broken and second url is not plugin.

**Comment by marcospereira** [comment]
Hi @rozkerim,

> I could not find this version on maven repository.

Play Enhancer and other plugins are published to Bintray instead:

https://bintray.com/playframework/sbt-plugin-releases/play-enhancer

The documentation needs to be updated to reflect the new version, but besides that, it is correct. It is for example used by our sample projects:

https://github.com/playframework/play-java-starter-example/blob/88a6b3f10e636299063643689b4ebdfd5b563e54/project/plugins.sbt#L4-L8

To update the docs, you can submit a pull request changing this file:

https://github.com/playframework/playframework/blob/master/documentation/manual/working/commonGuide/build/code/enhancer.sbt

Best.

**Comment by marcospereira** [comment]
Closing since the current docs are referring to the latest version of play-enhancer.
