### ISSUE TITLE
play framework 2.5.X client connection remains open

### ISSUE THREAD

**Issue by ymkct20** [playframework/playframework#8441]
I am trying to update the existing play application with play 2.5 and getting timeout exception in parallel api call. can anyone help here?

**Comment by schmitch** [comment]
Hello @ymkct20 can you please give more details and maybe make a small reproducer that showcases the problem?

Also if this is more like a question or you need some help, please make a post on our discussion forum: https://discuss.lightbend.com/c/play

**Comment by ymkct20** [comment]
Hello,

Recently i am updating existing play version to play 2.5 and find out that my application is not working on multiple/parallel API call with completion stage and I am getting timeout exception.
