### ISSUE TITLE
RedirectHttpsFilter is Noisy

### ISSUE THREAD

**Issue by jamesward** [playframework/playframework#8448]
### Play Version (2.5.x / etc)

2.6.15

### Expected Behavior

1. Set the conf: `play.filters.enabled += play.filters.https.RedirectHttpsFilter`
2. Run in Dev mode
3. Not see `[info] p.f.h.RedirectHttpsFilter - Not redirecting to HTTPS because play.filters.https.redirectEnabled flag is not set.` logged on every request

### Actual Behavior

1. Every request logs `[info] p.f.h.RedirectHttpsFilter - Not redirecting to HTTPS because play.filters.https.redirectEnabled flag is not set.`

**Comment by PromanSEW** [comment]
Duplicate of #7592

**Comment by jamesward** [comment]
Whoops.  For some reason my search didn't find that one.  Sorry.
