### ISSUE TITLE
java.nio.charset.UnmappableCharacterException on windows 10

### ISSUE THREAD

**Issue by Enalmada** [playframework/playframework#8449]
Playframework 2.6.x doesn't compile on Windows 10 out of the box.  I get "java.nio.charset.UnmappableCharacterException: Input length = 1" [errors when I try and compile](https://stackoverflow.com/a/50594577/1502448) right after checking out 2.6.x.  The compile errors seem to be due to smart quotes in some comments in RequestHeader.scala, Render.scala, Jasonp.scala.  Removing all of them manually seems to have worked to compile.  Then I had to delete the test directory to get around the same problem of special characters in some of the tests to be able to publishLocal.  If someone with access to windows could fix this it would be helpful.  I assume that putting a scalacOptions ++= Seq("-encoding", "UTF-8") in the right place is necessary but I couldn't get it to work.

**Comment by marcospereira** [comment]
> smart quotes

I don't see a problem removing the smart quotes since they don't have a specific use there. Do you want to submit a PR to fix that? It is also possible that we have some other issues while building in Windows. @richdougherty probably has more information about it.

**Comment by Enalmada** [comment]
Unfortunately I think smart quotes are just a symptom of the real problem.  Removing them made compile work, but publishLocal then started to fail because of what appeared to be special characters in the test conditions.  I think it would be ideal if some encoding could be properly set somewhere so that the code would compile without any changes.  If @richdougherty could advise first that would be helpful.  I don't want to have to do a pull request every time someone checks in a smart quote if that can be avoided by some encoding setting in the right place.

**Comment by marcospereira** [comment]
> I call this just a workaround because there is probably a better way to do this play project specific rather than global.

It should be possible to add this to `javacOptions` in our project. If you don't mind, I will reopen the issue to keep track of this specific problem. It shouldn't be complicated to fix, probably just add the options to `playCommonSettings` here:

https://github.com/playframework/playframework/blob/195eb5d3d07d6669b98d2ccc83f9d011a780cc87/framework/project/BuildSettings.scala#L70

**Comment by richdougherty** [comment]
I used Windows 10 for a while and it was difficult. The solution I generally use is to put a `.jvmopts` file with `-Dfile.encoding=UTF=8` into the `framework` directory. I think you can also set this in a `JAVA_TOOLS_OPTS` environment variable, or something like that.

**Comment by richdougherty** [comment]
From memory [this sbt-header problem](https://github.com/sbt/sbt-header/issues/56) is what stops us getting a completely clean Windows 10 build without requiring custom options.

**Comment by Enalmada** [comment]
@richdougherty .jvmopts sounds like a good solution since the *_OPTS forces the setting on all all projects and I don't want to assume everything on the system will be utf-8.  Any reason we shouldn't checkin a .jvmopts file with -Dfile.encoding=UTF=8 into the framework directory?

**Comment by richdougherty** [comment]
I decided not to check in the file because I was thinking that other users might already have a `.jvmopts` with their own settings, e.g. heap size settings. However, it still might be worth fixing up the sbt build as much as possible and just disabling sbt-headers on Windows (or setting the `file.encoding` property manually within the sbt process?).

**Comment by marcospereira** [comment]
@Enalmada can you confirm the changes in #8495 solve the problem to you?

**Comment by Enalmada** [comment]
Yes, that does compile fine on windows!
