### ISSUE TITLE
Improve shutdown with AkkaHTTP's graceful termination

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#8453]
AkkaHTTP (expected in 10.1.2 or 10.2?) includes an [advanced termination handling](https://github.com/akka/akka-http/pull/2035) logic which is more elegant than calling [`unbind`](https://github.com/playframework/playframework/blob/938264b60302ddb978b2a02ebe5d84c4ae31c490/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L402).

The gist of it is that it:

 * unbinds, blocking new connections
 * starts a timeout allowing ongoing requests to finish, but when timeout kicks in an automatic `503` response is sent back.
 * automatically responds `503` to requests incoming on existing connections
 * etc...

**Comment by wsargent** [comment]
This goes all the way back to https://github.com/playframework/playframework/issues/1789 and https://medium.com/@edouard.kaiser/graceful-shutdown-with-play-and-kubernetes-450c7ddfa710

**Comment by ignasi35** [comment]
Some more details (wrt connection pool closing) at https://github.com/playframework/playframework/issues/9216#issue-436655119

**Comment by dwijnand** [comment]
Fixed in #9970
