### ISSUE TITLE
second time full compilation in dev mode for a small change

### ISSUE THREAD

**Issue by manjunath27** [playframework/playframework#8456]
I've got a launcher script that runs 'activator compile' then 'activator run' back to back. But on the first page load, it goes out and recompiles all the code which I just compiled.

Please find the OS and Play framework details

**OS:** Ubuntu 16.04
**Play:** typesafe-activator-1.3.2
**scala version:** 2.11.1
**sbt plugin:** 2.3.7
**Java:** 1.7.0_80
**eclipse:** Java EE IDE for developer version Mars.2 Release (4.5.2)

Please find the source of build.sbt & plugin.sbt

**build.sbt**
name := """star-new-design"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayJava)

scalaVersion := "2.11.1"

libraryDependencies ++= Seq(
  javaJdbc,
  javaEbean,
  cache,
  javaWs
)

**plugin.sbt**
resolvers += "Typesafe repository" at "https://repo.typesafe.com/typesafe/releases/"

// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.7")

// web plugins
addSbtPlugin("com.typesafe.sbt" % "sbt-coffeescript" % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.0.0")

Kindly help me to resolve this issue.

**Comment by marcospereira** [comment]
Hi @manjunath27,

Version 2.3.7 is not maintained anymore, so I'm closing this. If you notice this happening with Play 2.6.x, then it could be good to create a small project that reproduces the problem.

Best.
