### ISSUE TITLE
~run doesn't auto-trigger since sbt 1.1.4

### ISSUE THREAD

**Issue by jamesward** [playframework/playframework#8458]
### Play Version (2.5.x / etc)

Play 2.6.15

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

`Linux t470p 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

`openjdk version "1.8.0_171"`

### Expected Behavior

1. Set sbt version to `1.1.5` or `1.1.6`
2. `sbt ~run`
3. Change a file
4. Rebuild should auto-trigger

### Actual Behavior

The `~run` triggered execution does not happen with sbt > `1.1.4` but does happen with other tasks like `~test` and `~compile`.  This might be a Linux only issue: https://github.com/sbt/sbt/issues/4167

**Comment by marcospereira** [comment]
Thank you for reporting, @jamesward. I was able to reproduce it. And as you said `~run` works with 1.1.4.

**Comment by kirach** [comment]
Any chance this will be fixed? sbt1.2.0 is out today and this issue is still reproducible

**Comment by eed3si9n** [comment]
executeContinuously in sbt 1.1.3:
https://github.com/sbt/sbt/blob/v1.1.3/main-command/src/main/scala/sbt/Watched.scala#L93-L126

in sbt 1.2.0:
https://github.com/sbt/sbt/blob/v1.2.0/main-command/src/main/scala/sbt/Watched.scala#L106-L147

The new implementation uses an attribute key named ContinuousEventMonitor.

**Comment by jamesward** [comment]
I'm also experiencing continuous tasks like ~compile and ~test running twice per file change with using the Play sbt plugin which I think might be related to the root issue here.
