### ISSUE TITLE
Publish play module to maven repository

### ISSUE THREAD

**Issue by danielflorez9612** [playframework/playframework#8465]
Hi! I am new to building modules in play, I have done a SDK to use some mailing API, any Idea on how could I extract that module and publish it to Maven Repository so anyone can import it in their build.sbt?
### JDK (OpenJDK 1.8.0_171)

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by schmitch** [comment]
Actually this is only a issue tracker of Play, please post questions to https://discuss.lightbend.com/ (you already did https://discuss.lightbend.com/t/create-and-publish-a-module-to-maven-repository/1241).
So I'm closing here. I'm soon answering your question there, but please be patient.
