### ISSUE TITLE
 Allow to set the transaction isolation level

### ISSUE THREAD

**Issue by AlexITC** [playframework/playframework#8466]
At the moment, there is no way to specify the transaction isolation level for a single transaction, it would be great to have a syntax like this:
 ```scala
database.withTransaction(TransactionIsolationLevel.Serializable) { implicit conn => ... }
```

The code changes to support that are trivial, would you accept a pull request?

**Comment by schmitch** [comment]
> The code changes to support that are trivial, would you accept a pull request?

we always do ;)
However it is probably a binary breaking change, so it can't be in play before 2.7

**Comment by AlexITC** [comment]
I don't think it would be a breaking change, we could keep the current `withTransaction` method and add another one that supports the transaction isolation level.

**Comment by schmitch** [comment]
the problem is, that `Database` is a trait and adding methods to a trait will **always** break binary compatibility.

**Comment by AlexITC** [comment]
Ah, good point, I'll upload a pull request soon.

**Comment by marcospereira** [comment]
Thanks for the interest here, @AlexITC.

A small note only: this also needs to be done for the Java API so that we can keep it on par with the Scala API. :-)

**Comment by AlexITC** [comment]
Yeah, that's what has stopped me to do upload the pull request until now.

In any case, I was thinking on doing an explicit rollback to the transaction isolation level, while some connection pool libraries like HIkariCP do this automatically, I think it is better to not expect that to avoid having weird bugs, what do you guys think?

**Comment by nuboat** [comment]
Hi, I have use Play for a long time, Can I take care of this issue?

**Comment by AlexITC** [comment]
That would be great.

**Comment by nuboat** [comment]
> At the moment, there is no way to specify the transaction isolation level for a single transaction, it would be great to have a syntax like this:
> 
> ```scala
> database.withTransaction(TransactionIsolationLevel.Serializable) { implicit conn => ... }
> ```
> 
> The code changes to support that are trivial, would you accept a pull request?

Input should be a new enum or just Int by (Connection.TRANSACTION_%)?

**Comment by AlexITC** [comment]
This is the draft that I had completed but it works for Scala only, the idea was to use an ADT instead of ints because the compiler would prevent certain mistakes: https://gist.github.com/AlexITC/d003adf96ee11db69671a193fa8799fe

**Comment by AlexITC** [comment]
Could you upload the patch? seeing what you are trying to do might help us to help.

**Comment by nuboat** [comment]
[issue_8466.diff.zip](https://github.com/playframework/playframework/files/2453586/issue_8466.diff.zip)

**Comment by nuboat** [comment]
Niw, all CI checkpoint has done. Could you help review?

**Comment by AlexITC** [comment]
Done, we could continue the discussion there.
