### ISSUE TITLE
create own project/module for play.api.libs.concurrent and play.libs.concurrent

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#8469]
I have to work on a non-play project atm and Plays concurrency-helpers would be really handy.

I would like to move the code to its own module that gets released and can be included by other projects, probably with Akka as a dependency ( I already brought in Akka+Akka Streams )

Ideas / objections?

**Comment by marcospereira** [comment]
It sounds like a good idea to me.

The only observation is to add it as a dependency of `play`, which is where the code lives now. It may be necessary anyway.

**Comment by TimMoore** [comment]
Doesn't it depend on other parts of Play?

**Comment by marcospereira** [comment]
@TimMoore probably some parts of it, especially considering `Environment`, `ApplicationLifecycle` and `Configuration`. but should be doable anyway and we can avoid moving such parts. But if it breaks too many things, then we should reconsider.

**Comment by marcospereira** [comment]
@domdorn I'm labeling this with "help wanted" since it is not a priority and we are busy with other stuff. But of course, if you want to work on it, we will help as we can. :-)

Best.

**Comment by domdorn** [comment]
@marcospereira sure, I wanted to do it anyway, just checking if there are objections against it.

**Comment by domdorn** [comment]
hmm... just tried it.. its entangled way too much and not worth the effort.. closing now.
