### ISSUE TITLE
YAML file could not be read

### ISSUE THREAD

**Issue by thirunavookkarasu** [playframework/playframework#8484]
I got the following error message when I run my bobcat script for AEM JUnit.

Error message:
com.google.inject.provisionexception unable to provision see the following errors

error in custom provider Java.Lang.IllegalStateException: YAML file could not be read.

API ( Java / )

 Operating System ( Windows 8)

JDK (Oracle 1.8.0_72)

### Expected Behavior

The script should run successfully and the YAML should be readable by the script.

**Comment by marcospereira** [comment]
Hi @thirunavookkarasu,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

When using the forums, I suggest you add some more information to your question. Which version of Play are you using? Post the complete stack trace, the code that is failing and also details about where the YAML file is.

Best.
