### ISSUE TITLE
Parallel execution definitions of tests are ignored

### ISSUE THREAD

**Issue by tam4s** [playframework/playframework#849]
Play ignores SBT test configuration settings like `parallelExecution in Test := true` or test grouping, or defined limits like `Tags.limit(Tags.Test, 3)`.

It's not clear (especially not for a Java developer) and undocumented how to execute tests parallel, even if it's possible somehow. Here is an example Build.scala that defines the tests running in multiple JVMs & multiple threads, but all the tests running in a single JVM in a single thread instead.

```
import sbt._
import Keys._
import play.Project._

object ApplicationBuild extends Build {
    val appName         = "testTest"
    val appVersion      = "1.0-SNAPSHOT"

    val testThreads = 8

    def groupByFirst(tests: Seq[TestDefinition]) =
      tests groupBy (_.name(0)) map {
        case (letter, tests) => new Tests.Group(letter.toString, tests, Tests.SubProcess(Seq("-Dfirst.letter"+letter)))
      } toSeq;

    val appDependencies = Seq(
      javaCore,
    )

    val main = play.Project(appName, appVersion, appDependencies).settings(
      concurrentRestrictions in Global := Seq(
        Tags.limit(Tags.ForkedTestGroup, testThreads),
        Tags.limit(Tags.Test, testThreads),
        Tags.limit(Tags.CPU, testThreads),
        Tags.limit(Tags.Compile, testThreads),
        Tags.limitAll(testThreads),
        Tags.limitUntagged(testThreads)),
      parallelExecution in Test := true,
      testGrouping <<= definedTests in Test map groupByFirst
    )
}
```

I use JUnit as my testing framework.

I put this line into each tests to test whether the tests run in parallel or not:

```
System.out.println(String.format("process id: %s thread id: %s", ManagementFactory.getRuntimeMXBean()
    .getName(), Thread.currentThread().getId()));
```

I understand that certain tests cannot be run parallel (E.g. more than one TestServer in a single JVM or more than one TestServer in multiple JVMs that listens on the same port) but it doesn't mean that parallel execution should be disabled for all kind of tests.

@gissues:{"order":35.89743589743585,"status":"backlog"}

**Comment by axblueblader** [comment]
Hello have anyone got it to work, I've searched and tried all the settings still cannot configure parallel test execution
