### ISSUE TITLE
Build and publish scala 2.13 milestone images for Play Iteratees and Play Omnidoc

### ISSUE THREAD

**Issue by KoenDG** [playframework/playframework#8492]
As request here: https://discuss.lightbend.com/t/play-2-7-0-m1-released/1380/4

By @marcospereira 

Also mentioning the 2.7 migration guide exists but was not published, just in case.

**Comment by marcospereira** [comment]
Related issues:

- [ ] https://github.com/playframework/play-iteratees
- [ ] https://github.com/playframework/omnidoc/issues/20

**Comment by marcospereira** [comment]
I'm closing this since there is an issue on play-iteratees already and the module is now community maintained, so we don't have specific plans for it now.
