### ISSUE TITLE
Authentication/authorization module for Play Framework

### ISSUE THREAD

**Issue by VChirp** [playframework/playframework#8500]
Hello there!
Play Framework was developed to be as stateless as possible.
However, there are not so many web applications that can work without Authentication functionality.
For example I use Play-authenticate library (my project is java based) which is not actively maintained now and it supports Play 2.5 only. I can migrate to other authentication library, but where are guarantees that its lifespan will be longer?

Maybe its time to create official module for this purpose?

**Comment by wsargent** [comment]
This is a bug database -- these kinds of discussions are best asked on https://discuss.lightbend.com/c/play/

**Comment by wsargent** [comment]
Please see https://www.playframework.com/documentation/2.6.x/Tutorials#Sub-projects and https://www.playframework.com/documentation/2.6.x/ModuleDirectory#Authentication-(Login-&-Registration)-and-Authorization-(Restricted-Access) for modules.
