### ISSUE TITLE
[passing json object to javascript] cant not parse Json string when there is a newline character in its content. 

### ISSUE THREAD

**Issue by anhlt** [playframework/playframework#8501]
### Play Version

2.2.2

### API

Scala

### Operating System

MacOS 10.10 

### JDK

OpenJDK 1.8.x

### Expected Behavior

Passing Json stringifyed object to JavaScript. JavaScript `Json.parse` work correctly.

```javascript
var Attribute = JSON.parse('@Html(Json.stringify(attribute))')
```

### Actual Behavior

If there is a newline charactor in object. Javascript cannot parse correctly.
I have to replace '\n' with  \ \ n

```javascript
var shopAttribute = JSON.parse('{"headline":"23","businessHours":"クーポン名（必須）","regularHoliday":"定休日\n\n\n\nabv","parking":"1231231234443334","access":"アクセス","followCouponId":103}')
```

**Comment by marcospereira** [comment]
Hi @anhlt,

Is this happening with the latest release of Play? Play 2.2.2 is not maintained anymore since it is a pretty old release. Can you reproduce the error with Play 2.6?

Best.

**Comment by gmethvin** [comment]
`Json.stringify` just returns a JSON string. Raw JSON is not suited for embedding inside a JavaScript string literal. If you use `@Html()` then you're basically telling twirl "don't escape this". So the behavior is as intended.

I'm assuming you want to pass JSON to a script within an HTML template. I explained one safe way to do it in this answer: https://discuss.lightbend.com/t/how-to-elegantly-replace-quot-with-when-passing-java-string-to-play-framework/1315/3
