### ISSUE TITLE
[2.6.x] Missing asScala API for EssentialFilter

### ISSUE THREAD

**Issue by FranklinYinanDing** [playframework/playframework#8509]
### Play Version (2.5.x / etc)
2.6.x

### API (Scala / Java / Neither / Both)
Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.13

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle 1.8.0_172

### Expected Behavior

1. Java `EssentialFilter`, that is generated by Scala `EssentialFilter.asJava`, should have an `asScala` API to convert back to the previous object.

### Actual Behavior

1. There isn't a way to achieve that.

**Comment by gmethvin** [comment]
Well, technically there is a way to achieve it, since `play.mvc.EssentialFilter` extends `play.api.mvc.EssentialFilter`, so no conversion is needed. But yes it would make sense just for the sake of having symmetrical APIs.

**Comment by FranklinYinanDing** [comment]
Hi @gmethvin, that's correct. However, `play.api.mvc.EssentialFilter.asJava` creates a new `play.mvc.EssentialFilter`, which doesn't hold a reference to the old object. We have an implementation that relies on class type matching. This conversion breaks it because of this conversion.

**Comment by FranklinYinanDing** [comment]
PR for this issue is #8510

**Comment by gmethvin** [comment]
Not opposed to the change you proposed for API consistency reasons, but I'm wondering why you need to match on the class. Maybe there is a better way for Play to provide the functionality you want without having to rely on an implementation detail.

**Comment by FranklinYinanDing** [comment]
Some of our filters need to be mandatory, some of our filters need to use in pair or maintain certain orders. So se have a component to check the filter chain. It examines the filter chain by comparing the filter class types. If it doesn't find legitimate, then the application wouldn't start.

Previously, in Play 2.4, Java `HttpFilters` or Scala `HttpFilters` all return Scala `EssentialFilter`. So there was no conversion if people choose to use Java version of `HttpFilters`. Then the problem declared above comes in, so Play 2.6 breaks the class type comparison.

**Comment by FranklinYinanDing** [comment]
The fix has been merged to 2.6.x and master.
