### ISSUE TITLE
Remove StopHook from ActorSystemProvider.start methods

### ISSUE THREAD

**Issue by TimMoore** [playframework/playframework#8534]
With the changes to use `CoordinatedShutdown` in Play, the `StopHook` returned from the `start` methods is always a no-op:

https://github.com/playframework/playframework/blob/2.7.0-M2/framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala#L189-L191

Because of this, there could be new methods that don't return the `StopHook` and the existing ones could be deprecated. This will allow callers to be cleaned up a bit.

### Play Version (2.5.x / etc)

2.7.0-M2

### API (Scala / Java / Neither / Both)

Scala

**Comment by gmethvin** [comment]
If the stop hook is already a no-op, then maybe it's worth breaking the API here and cleaning it up now. "deprecated" usually means "still works as intended, but will be removed". It's probably safer to also break the API so people migrate instead of depending on now broken functionality, right?

**Comment by TimMoore** [comment]
That works for me. I suspect few end users would call this directly, anyway.
