### ISSUE TITLE
Error in debug play application

### ISSUE THREAD

**Issue by ashu8006kumar** [playframework/playframework#8557]
I am trying to debug play(Java) application but getting error 

sbt  -jvm-debug 9999 run 

error : -
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in a later version

how can we deb-bug now 

I am using  Play 2.6  , sbt 1.1.6 and Java - 1.8

**Comment by marcospereira** [comment]
Hi @ashu8006kumar,

Which sbt launcher are you using? I'm using sbt 1.1.6 and everything works as expected.

Well, anyway our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Best.
