### ISSUE TITLE
fromJsonValidationError does not expand varargs

### ISSUE THREAD

**Issue by SheldonSoftdev** [playframework/playframework#8560]
`ValidationError.fromJsonValidationError` does not expand it's varargs, causing multiple arguments to be passed as a single collection to the `ValidationError` constructor.  This is leading to unexpected error message formatting, like "The minimum length is WrappedArray(3)"

As of Play 2.6.17 current implementation is:

```scala
  def fromJsonValidationError(jve: JsonValidationError): ValidationError = {
    ValidationError(jve.message, jve.args)
  }
```

But it should be

```scala
  def fromJsonValidationError(jve: JsonValidationError): ValidationError = {
    ValidationError(jve.message, jve.args:_*)
  }
```

### Play Version (2.5.x / etc)

Play 2.6.16
Scala

### Expected Behavior

```scala
val jsonError = JsonValidationError("Testing, testing {1} {2} {3}", "one", "two", "three")
val validationError = fromJsonValidationError(jsonError)
jsonError.args(2) == "three"
validationError.args(2) == "three"
```

### Actual Behavior

```scala
// Throws java.lang.ArrayIndexOutOfBoundsException: 2
validationError.args(2) == "three" 
```

**Comment by gmethvin** [comment]
@SheldonSoftdev looks like a bug to me. Are you interested in submitting a fix?

**Comment by SheldonSoftdev** [comment]
Backport to 2.5 not required, the method does not etxist
