### ISSUE TITLE
Logging configuration for Production mode

### ISSUE THREAD

**Issue by Abby1096** [playframework/playframework#8568]
Hi,I'm a newbie to Play Framework. Logging Configuration procedures are working absolutely perfect in Development mode.
While in production mode , it creates the logs storing file but the log lines are not storing there.

My logback.xml file is as follows ,

[logback.txt](https://github.com/playframework/playframework/files/2297108/logback.txt)

Thanks in Advance.

**Comment by marcospereira** [comment]
Hello @Abby1096,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Best.
