### ISSUE TITLE
Open package visibility of PlayIO

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#8584]
In https://github.com/playframework/playframework/pull/8574 the Play copy of `FakeKeyStore` was improved with Lagom's changes.

Lagom changes for SSL support in dev mode also made local copies of `PlayIO` methods into [`LagomIO`](https://github.com/lagom/lagom/blob/master/dev/dev-mode-ssl-support/src/main/scala/com/lightbend/lagom/devmode/ssl/FakeKeyStoreGenerator.scala#L17-L30). 

It'd be great to open up the visibility of `PlayIO` (moving it to `play.internal.utils`) as we did with `CSSupport` in https://github.com/playframework/playframework/pull/8583

**Comment by dwijnand** [comment]
There's an aborted PR for this in #8594.

**Comment by marcospereira** [comment]
@dwijnand and @ignasi35, this is probably not necessary anymore due to all the changes made in ssl-config. Can we close it?

**Comment by dwijnand** [comment]
Sure.  Replaced by https://github.com/lagom/lagom/issues/1612.
