### ISSUE TITLE
Default datasource is trying to connect even when db.default.url is not specified

### ISSUE THREAD

**Issue by hong823** [playframework/playframework#8585]
### Play Version (2.5.x / etc)
2.6.1

### API (Scala / Java / Neither / Both)
Java

### Expected Behavior

When default datasource's url is not specified it should not attempt to connect to datasource.

### Actual Behavior

I'm trying to configure a datasource named other than `default` which is `primary`. 

1. My `application.conf` looks like this:

```
db {
  primary {
    driver = org.postgresql.Driver
    logSql = true
    migration.auto = true
    url = "jdbc:postgresql://192.168.99.100:5432/local"
    username = local
    password = secret
  }
}
```

2. When Play app runs, it attempting to connect to `default` datasource even url is not specified in `application.conf`.

3. I noticed when `play.api.db.DefaultDbApi` is configuring, it has a default value for datasource `default` which is `db.default.migration.auto = false` (See screenshot below with red arrow).
<img width="916" alt="screen shot 2018-08-28 at 4 37 57 pm" src="https://user-images.githubusercontent.com/5250790/44752508-d0f65180-aae0-11e8-9c75-43643d9a21cf.png">

4. This resulting in Play trying to also connect to `default` even `db.default.url` is not specified as it also considered as one of the datasource.

Is this intended to work in this way?

**Comment by marcospereira** [comment]
Hum, could you try that with the latest version (2.6.18)?

In Play 2.6.17 we made some changes related to connecting to the database at application startup. See https://github.com/playframework/playframework/pull/8522 and also https://github.com/playframework/playframework/pull/8524 for a backport.

**Comment by hong823** [comment]
@marcospereira 
I just tested on 2.6.18 and it somehow still didnt work. In the browser i saw:
<img width="424" alt="screen shot 2018-08-29 at 1 32 28 pm" src="https://user-images.githubusercontent.com/5250790/44807755-fee69f00-ab8f-11e8-8557-1e41afda1cd6.png">

When i debug `play.api.db.DefaultDbApi` i see `configuration` still picking up `default` data source:
![screen shot 2018-08-29 at 1 31 00 pm](https://user-images.githubusercontent.com/5250790/44807700-d52d7800-ab8f-11e8-89a0-e031d66a1fa0.png)

Is there any configuration that i should configure other than what I have now for 2.6.18?

**Comment by marcospereira** [comment]
Hi @hong823,

If I understand correctly, you don't have a `default` database configure, but instead, a `primary` only, right? If so, you need to have the following configuration too:

```hocon
play.db.default = "primary"
```

Moreover, our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

If later we decide this is a bug, it could be good to provide a project that reproduces the problem.

Best.

**Comment by hong823** [comment]
@marcospereira i actually did the configuration of below and it's still didn't work (Sorry i now included it in the initial post):

`play.db.default = "primary"`

That's the reason I'm suspecting it's a bug.

**Comment by marcospereira** [comment]
Hey @hong823, better to provide a project that reproduces the problem then.

Thanks. 👍
