### ISSUE TITLE
Reconcile SSLContextProvider from Lagom's Dev Mode

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#8587]
Lagom's dev mode uses a `SSLContextProvider` tuned to use `FakeKeyStore` (see https://github.com/lagom/lagom/blob/master/dev/dev-mode-ssl-support/src/main/scala/com/lightbend/lagom/devmode/ssl/LagomDevModeSSLEngineProvider.scala).

Play, already provides a [`DefaultSSLEngineProvider`](
https://github.com/playframework/playframework/blob/master/framework/src/play-server/src/main/scala/play/core/server/ssl/DefaultSSLEngineProvider.scala) for general use.

These should be consolidated.

Related to https://github.com/playframework/playframework/issues/8584 (probably solving this issue will make https://github.com/playframework/playframework/issues/8584 obsolete).

**Comment by dwijnand** [comment]
Some progress was pushed (see links).  Going to leave the rest of the dedup for another day (and/or another person).
