### ISSUE TITLE
DB Evolution Script not executed

### ISSUE THREAD

**Issue by Marc2017** [playframework/playframework#8592]
### Play Version (2.5.x / etc)

[2.7.0-M3]
2.7.0-M4

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 8.1

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

JDK 1.8_37

### Library Dependencies

sbt-play-ebean 5.0.0-M4

### Expected Behavior

After changes to the DB-beans the DB-evolution page appears normally and the db-script is shown. But the "Apply this script now" button does nothing but a page-reload.

DB-Script is working when executed manually in mysql..

### Reproducible Test Case

Try to run a DB-Evolution.

best regards
marc

**Comment by zhengcan** [comment]
Yes, I have the same issue.
When I set `play.evolutions.autoApply = true`, the SQL script would be executed as expected.

**Comment by ignasi35** [comment]
As detailed in #8849:

> Changes in #7986 cause a denial of service via a chicken-and-egg situation in dev mode because the Evolutions WebCommand is now inside the `Application`. When starting up the `Application` a failure happens because the Evolution is required. The UI to run the evolutions is presented but clicking the button to invoke the evolution fails because the `Application` hasn't started yet.

**Comment by mkurz** [comment]
This should probably be fixed before the final 2.7 release happens...

**Comment by mkurz** [comment]
Fix is here: #8875

**Comment by gslowikowski** [comment]
Hi. Currently, after upgrading of test projects to Play! 2.7.0-RC9, loading evolutions in dev mode in:
- [play-scala-anorm-example](https://github.com/playframework/play-scala-anorm-example/tree/2.7.x) - works
- [play-java-ebean-example](https://github.com/playframework/play-java-ebean-example/tree/2.7.x) - **does not work**
- [play-scala-slick-example](https://github.com/playframework/play-scala-slick-example/tree/2.7.x) - **does not work**

**Comment by mkurz** [comment]
@gslowikowski That's because `play-slick` and `play-ebean` need a new release. Right now they still use broken `play-jdbc-evolutions` from Play `RC8`:
* https://github.com/playframework/play-ebean/blob/master/build.sbt#L5

* https://github.com/playframework/play-slick/blob/master/project/plugins.sbt#L3
* https://github.com/playframework/play-slick/blob/master/project/Dependencies.scala#L21

After that the examples need to be upgraded.

**Comment by gslowikowski** [comment]
Thanks for quick `-RC3` releases. Now it works.
