### ISSUE TITLE
Insecure HTTP/2 requests don't work

### ISSUE THREAD

**Issue by ctoomey** [playframework/playframework#8606]
### Play Version (2.5.x / etc)
2.7.0-M3

### API (Scala / Java / Neither / Both)

Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.13.6

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

### Library Dependencies

akka-http-core-10.1.3

### Expected Behavior

1. Enable HTTP/2 support via `PlayAkkaHttp2Support` plugin
2. `curl -v --http2-prior-knowledge localhost:9000` should return 200

### Actual Behavior

`curl -v --http2-prior-knowledge localhost:9000` returns an error:

```
* Rebuilt URL to: localhost:9000/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9000 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f8f03004000)
> GET / HTTP/2
> Host: localhost:9000
> User-Agent: curl/7.54.0
> Accept: */*
> 
* http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.
* Closing connection 0
curl: (16) Error in the HTTP2 framing layer
```

The server log shows

```
[warn] a.a.ActorSystemImpl - Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method: PRI
```

### Reproducible Test Case

I don't see an easy way to write a test for this. I've described above how to reproduce the problem, and I have a fix for it which I'll provide as a PR.

**Comment by ctoomey** [comment]
Note that per https://github.com/akka/akka-http/issues/1966, since akka-http doesn't support upgrading  insecure requests to HTTP/2, the only way to make insecure requests to an akka-http server supporting HTTP/2 is to have the server always use HTTP/2 and clients assume prior knowledge of HTTP/2 for insecure requests.

I discovered this in the process of getting akka-grpc working in Play, and had originally filed https://github.com/akka/akka-grpc/issues/386 .

**Comment by linsheng9731** [comment]
Use Http2 instead of Http method at server side works for me :
```
Http2().bindAndHandleAsync(
    serviceHandler,
    interface = "localhost",
    port = 8443,
    parallelism = 256, // Needed to allow running multiple requests concurrently, see https://github.com/akka/akka-http/issues/2145
    connectionContext = serverHttpContext())
```
