### ISSUE TITLE
RuntimeException: DataSource user is null?

### ISSUE THREAD

**Issue by bsideup** [playframework/playframework#861]
Hi!

I'm working on simple project by tutorials and my project isn't working. When i'm trying to save model, edited by form (Special Events -> edit -> Save), Play raised Runtime Exception:

> RuntimeException: DataSource user is null?

What is it? Seems like a bug in ebean configuration because similar code form example (computer database) is working fine. Google say nothing except what i'm already done in application.conf

Here is a link to my simple project, you can try in on your own:
https://github.com/bsideup/PlayFrameworkExperiment

Thank you!
@gissues:{"order":15.384615384615328,"status":"backlog"}

**Comment by itonics-tbeauvais** [comment]
What did you do to resolve this?  

I am not seeing this bug on 1.8 but a colleague is seeing this on 1.7.. does that matter?

**Comment by bsideup** [comment]
@itonics-tbeauvais type of "id" of entity was "String", which overlaps with `public void update(java.lang.String server)` method instead of actual update

**Comment by itonics-tbeauvais** [comment]
We have the @Id as UUID, would this also interfere?
