### ISSUE TITLE
Exception when embedding a NettyServer in Play 2.7.0-M3

### ISSUE THREAD

**Issue by Roland4444** [playframework/playframework#8611]
Via tutorial https://www.playframework.com/documentation/2.5.x/ScalaEmbeddingPlay

I embed Netty and play in my app throw Maven adding the dependency:

```xml
        <dependency>
            <groupId>com.typesafe.play</groupId>
            <artifactId>play-netty-server_2.12</artifactId>
            <version>2.7.0-M3</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.play</groupId>
            <artifactId>play_2.12</artifactId>
            <version>2.7.0-M3</version>
        </dependency>
```

So this Scala code 
```scala
object NettyLauncher { // this is my entry object as specified in sbt project definition
  def main(args: Array[String]) {
    import play.core.server._
    import play.api.routing.sird._
    import play.api.mvc._

    val server = NettyServer.fromRouter() {
      case GET(p"/hello/$to") => Action {
        Results.Ok(s"Hello $to")
      }

      case GET(p"/") => Action {
        Results.Ok(s"HI THERE")
      }
    }
  }
}
```
 If i open <http://127.0.0.1:9000/hello/rolan> I got:

![screenshot_2018-09-18_09-57-06](https://user-images.githubusercontent.com/12486232/45669431-9e53dd80-bb0f-11e8-9e32-b7f6572b8b27.png)

p.s.  in application.conf":

```
application.mode=dev
application.secret=PpVCCn0FBRTmOx5ZwjHNxAh303SAdXJmh9ecIeuPb83hqyz2ig6Rs1Z6PUtVjgzc
```

**Comment by marcospereira** [comment]
Hi @Roland4444,

Thanks for that. Is it possible to create a small project that reproduces the problem? Also, keep in mind that we don't support Maven officially, but it could still be good to have a reproducer to verify where is the problem.

Best.

**Comment by Roland4444** [comment]
sure
there pom.xml

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>smallwebApp</groupId>
    <artifactId>smallwebApp</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <kotlin.version>1.2.70</kotlin.version>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.source>1.8</maven.compiler.source>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.typesafe.play</groupId>
            <artifactId>play-netty-server_2.12</artifactId>
            <version>2.7.0-M3</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.play</groupId>
            <artifactId>play_2.12</artifactId>
            <version>2.7.0-M3</version>
        </dependency>

    </dependencies>
    <build>
        <plugins>
          
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>scala-compile-first</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>add-source</goal>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.5.3</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <mainClass>ScalaRunner</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>SRunner</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


</project>`

**Comment by ignasi35** [comment]
related to #8615

**Comment by marcospereira** [comment]
Hum,

So, adding `play-logback` dependency helped to see the problem. What is happening is that `NettyServer.forRouter` is trying to access global state, which is NOT allowed anymore by default (see #8183).

The possible solutions here are:

1. Document in our migration guide that if you are using `NettyServer.fromRouter` or `AkkaHttpServer.fromRouter` you will need to add `play.allowGlobalApplication = true` configuration to `application.conf`.

2. Automatically add `play.allowGlobalApplication = true` when using such methods (should be easy to fix and to test).

I'm inclined to the first solution since we won't need to add more code that handles global state, although the second solution is also simple and more convenient for users.

WDYT?

**Comment by Roland4444** [comment]
please add this => https://www.playframework.com/documentation/2.5.x/ScalaEmbeddingPlay

**Comment by Roland4444** [comment]
for newbies

**Comment by marcospereira** [comment]
@Roland4444 the change only applies to Play 2.7.0-M3 (the version your example uses), so there is no need to change 2.5.x docs. 

The docs for version 2.7.0-M3 are okay since they don't recommend any deprecated API that requires global state:

https://www.playframework.com/documentation/2.7.0-M3/ScalaEmbeddingPlayAkkaHttp

Best.

**Comment by mahesh2492** [comment]
@marcospereira I am facing the same issue with my application. 
Play version: 2.39
So will this solution work for us too? Or is it applicable to the specified version in question?
