### ISSUE TITLE
Subsequent stop hooks are not executed if a Callable stop hook returns null

### ISSUE THREAD

**Issue by Woodz** [playframework/playframework#8624]
### Expected Behavior

I expect all shutdown hooks to be called at least once regardless of the result of previous shutdown hooks

### Actual Behavior

If the following code is added to a component, all shutdown hooks registered before this will not be called. This is because converting the Java `Promise` to a Scala `Future` at https://github.com/playframework/playframework/blob/2.4.x/framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala#L67 fails by throwing a `NullPointerException` and therefore the `foldLeft` skips all subsequent shutdown hooks.

```
lifecycle.addStopHook(() -> { return null; });
```

### Reproducible Test Case

See #8625

**Comment by marcospereira** [comment]
Closing as this is fixed on maintained versions (2.6.x) and will be part of the upcoming 2.7.x (master right now).
