### ISSUE TITLE
Session is not preserved in Result in tests

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#8636]
### Play Version (2.5.x / etc)
2.6.18

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
JDK 9.0.4

### Library Dependencies
N/A

### Expected Behavior
This test should pass:
```
@Test
public void shouldHaveSession() {
    final Result result = Helpers.route(
        getApplication(),
        Helpers.fakeRequest(routes.HomeController.index())
          .header(Http.HeaderNames.HOST, "localhost")
          .session("foo", "bar")
    );

    assertThat(result.session()).isNotNull();
}
```

### Actual Behavior
It fails with:
```
[error] Test controllers.HomeControllerTest.shouldHaveSession failed: java.lang.AssertionError:
[error] Expecting actual not to be null, took 1.581 sec
[error]     at controllers.HomeControllerTest.shouldHaveSession(HomeControllerTest.java:140)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:564)
[error]     ...
```

**Comment by gmethvin** [comment]
Does the `index()` action actually set the session?

This may not be entirely clear, but the `session` in the `Result` only reflects a session set inside the action. If the action doesn't modify the session in any way, then there is no session on the result. From an HTTP perspective you can think of it as a representation of the session cookie to be set in the `Set-Cookie` header. If `result.session()` is `null`, the client should continue sending its existing session cookie.

**Comment by eximius313** [comment]
No, HomeController does not set session, it requires it.
@gmethvin - with your approach, I see three problems: 
1) How to check in test, that HomeController indeed received the session
2) How to check in test, that HomeController did not cleaned the session
3) How to check in test, that HomeController did cleaned the session

**Comment by marcospereira** [comment]
Hi @eximius313,

> How to check in test, that HomeController indeed received the session

If there is some behavior based on the session being present or not, test for that behavior (with and without the session). If there is no behavior change, then I cannot see why to consider the session in your tests. 

> How to check in test, that HomeController did not cleaned the session
> How to check in test, that HomeController did cleaned the session

Inspect the `Set-Cookie` header?

But, as @gmethvin said, if the controller is not touching the session, then it won't return a `Set-Cookie` header since there is nothing to change and the client should just send the same cookies (considering expiration, etc.).

**Comment by eximius313** [comment]
@marcospereira HomeController can (based on some condition) clean the session or not .
So I must test if session was cleaned or not (left untouched) ;)

**Comment by gmethvin** [comment]
Then check the session on the result. If it's there, and see if it changed. If it's an empty session it was cleared. If it's anything else it was set to something else.

**Comment by eximius313** [comment]
@gmethvin 
It indeed works as you described:
* When session was set, then it is non-empty map
* When session was cleared it is empty map
* When session was not changed it is null

For anyone using AssertJ assertions:
```
  public ResultAssertion sessionWasCleared() {
    isNotNull();
    Assertions.assertThat(actual.session())
      .describedAs("Session was cleared")
      .isNotNull()
      .isEmpty();
    return this;
  }

  public ResultAssertion sessionWasNotChanged() {
    isNotNull();
    Assertions.assertThat(actual.session())
      .describedAs("Session was not changed")
      .isNull();
    return this;
  }

  public ResultAssertion sessionWasSet(final String email) {
    isNotNull();
    Assertions.assertThat(actual.session())
      .describedAs("Session was set, logged user: "+email)
      .containsEntry("email", email);
    return this;
  }
```

Nevertheless I don't find it obvious. 
* If it can be done better (in more convenient way) - it should.
* If it depends on how HTTP behaves and it must stay this way - then I think it should be descried better in testing documentation (I've added new point to my old issue: https://github.com/playframework/playframework/issues/8176)

**Comment by eximius313** [comment]
>  is only set if something about the session is new.

then maybe `modifySession` is better?
I instantly thought about `newSession` as a method that will replace existing session (or is it the case?)

**Comment by gmethvin** [comment]
It replaces the session. It maps to the value of the session cookie in the `Set-Cookie` header.

Also, it's worth noting that in Play 2.7, @mkurz added `result.session(request)`, which gives you the actual "current" value of the session. It uses the session on the request if the result session is null.

**Comment by marcospereira** [comment]
I am closing this one since there are multiple ways to achieve what was initially described here.
