### ISSUE TITLE
Better API for cookies in Java

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#8644]
### Play Version (2.5.x / etc)
2.6.18

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
JDK 9.0.4

### Library Dependencies
N/A

### Expected Behavior
`play.mvc.Result#cookie` does `get` on Optional so when cookie is not set it obviously throws `java.util.NoSuchElementException: No value present`

Maybe it's better to return this Optional instead (to be consistent with `header`, `redirectLocation` etc.), or at least provide `hasCookie` method?

**Comment by marcospereira** [comment]
That makes sense to me.

It can be good to have `cookie` and `getCookie` (returning `Optional`) with `cookie` being deprecated. Do you want to submit a PR for this one, @eximius313?

**Comment by dmitraver** [comment]
I can pick this one

**Comment by eximius313** [comment]
@dmitraver @marcospereira The only thing that bothers me with `getCookie` is that the rest of methods that return Optional doesn't start with `get`.
Therefore I suggest:
* On 2.6 deprecate `cookie` and add `getCookie`
* On 2.7 change `cookie` to return Optional and note that in `Migration Guide`.
What do you think?

**Comment by marcospereira** [comment]
@eximius313 it is a little too late to deprecate it on 2.6.x branch. We should instead deprecate `cookie` and add `getCookie`. We can later remove `cookie` or replace it `getCookie`.

**Comment by dmitraver** [comment]
@marcospereira good, I'm on it

**Comment by dmitraver** [comment]
I haven't added any tests as I couldn't find any tests related to existing functionality. Let me know if you would need some and I will update my PR.

**Comment by eximius313** [comment]
Thanks @dmitraver !
@marcospereira, will it be backported to 2.6?
