### ISSUE TITLE
RequestHeader#copy method interferes with case class copy method generation

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#8651]
The `copy` method on `RequestHeader` interferes with copy method generation for case classes, thus making case-class-based requests less convenient to use.

Since this method is already deprecated, we probably should remove it soon, along with the `FakeRequest#copyFakeRequest` method.

**Comment by chenweisomebody126** [comment]
https://github.com/playframework/playframework/pull/8658
I removed the `copy` method on `RequestHeader` interferes
