### ISSUE TITLE
HttpEntity.as(null) ends up NullPointerException

### ISSUE THREAD

**Issue by FranklinYinanDing** [playframework/playframework#8713]
### Play Version (2.5.x / etc)

2.6.x

### API (Scala / Java / Neither / Both)

Both

### Expected Behavior

1. When accidentally call `HttpEntity.as(null)`, it should either work all the way by setting the content-type to `None` eventually, or blow up early if this is not an acceptable value.

### Actual Behavior

1. It won't complain when you call `HttpEntity.as(null)`, but later on, explodes here

> Caused by: java.lang.NullPointerException: null
  at akka.http.scaladsl.model.ErrorInfo$.fromCompoundString(ErrorInfo.scala:29)
  at akka.http.impl.model.parser.HeaderParser.failure(HeaderParser.scala:77)
  at akka.http.scaladsl.model.HttpHeader$.parse(HttpHeader.scala:77)
  at akka.http.scaladsl.model.headers.ModeledCompanion.parseFromValueString(headers.scala:37)
  at akka.http.scaladsl.model.ContentType$.parse(ContentType.scala:113)

This is because `as` wraps the string object in `Some`, instead of `Option`. If `null` is acceptable in `as`, then it should use `Option` (`Optional.ofNullable` for Java). But if `null` is not acceptable, then `as` is better to throw an exception right away, otherwise, the above trace isn't very straightforward enough to point to this place.

https://github.com/playframework/playframework/blob/2.6.x/framework/src/play/src/main/scala/play/api/http/HttpEntity.scala#L83

https://github.com/playframework/playframework/blob/2.6.x/framework/src/play/src/main/java/play/http/HttpEntity.java#L145

**Comment by marcospereira** [comment]
Thanks, @FranklinYinanDing. See #8772 for a fix.

**Comment by FranklinYinanDing** [comment]
Great! Thank you! @marcospereira
