### ISSUE TITLE
Help upload picture

### ISSUE THREAD

**Issue by FOLKQQ** [playframework/playframework#8715]
[NullPointerException: null]

![44335523_350147709066113_2112109558615769088_n](https://user-images.githubusercontent.com/41606593/47250992-25b9a700-d456-11e8-8374-000ddd729aa1.png)
![44393552_307007953362233_4336774310090768384_n](https://user-images.githubusercontent.com/41606593/47244949-9a262300-d421-11e8-9e97-75fd554b4724.png)
![44410788_340310733409338_5446171921790009344_n](https://user-images.githubusercontent.com/41606593/47244950-9abeb980-d421-11e8-8d09-52bdd6e24b85.png)
![Uploading 44335523_350147709066113_2112109558615769088_n.png…]()

**Comment by wsargent** [comment]
This is a bug tracker, and is not for help requests. Please use the discuss group on https://discuss.lightbend.com/c/play/ to discuss issues.
