### ISSUE TITLE
Broken link in ScalaWS documentation page

### ISSUE THREAD

**Issue by dqdinh** [playframework/playframework#8730]
### Are you looking for help?
No.

### Play Version (2.5.x / etc)
2.6.x

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
N/A

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
N/A

### Library Dependencies
N/A

### Expected Behavior

1. Go to "https://www.playframework.com/documentation/2.6.x/ScalaWS"
2. Click on "WS library" link
3. Redirects user to "https://www.playframework.com/documentation/2.6.x/api/scala/index.html#play.api.libs.ws.package"

### Actual Behavior
1. Go to "https://www.playframework.com/documentation/2.6.x/ScalaWS"
2. Click on "WS library" link
3. Page not found if clicked inside the github repo or it will download an HTML page if on the website.

**Comment by marcospereira** [comment]
Thanks for noticing that, @dqdinh.

The correct fix is to use https://www.playframework.com/documentation/2.6.x/api/scala/play/api/libs/ws/package.html (missing `package.html` at the end). Do you want to submit a PR?

**Comment by marcospereira** [comment]
This was fixed for 2.7.x. So I'm closing it then.
