### ISSUE TITLE
Don't suggest UnknownReason when invoking Coordinated Shhutdown

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#8751]
As discussed in https://github.com/playframework/playframework/pull/8531#discussion_r204663149 it's a bad idea to suggest users they set `UnknownReason` when directly invoking Coordinated Shutdown.

We should explain that direct use of Coordinated Shutdown should also include a specific reason.

**Comment by dwijnand** [comment]
The reason is unknown because it's Coordinated Shhhutdown.
