### ISSUE TITLE
HTTP method too long after upgrading to 2.7.0.M4

### ISSUE THREAD

**Issue by moga111** [playframework/playframework#8765]
### Play Version (2.5.x / etc)
2.7.0.M4

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.14

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

### Expected Behavior

1. Sending a post request with `WSClient.post(someJsonString)`
2. The request should go through like it did in all previous versions up to 2.7.0.M3

### Actual Behavior
Error suggesting that `someJsonString` in this case is way beyond its allowed length
I tried versions 2.6.20, 2.7.0.M1 - M3. They all handle it smoothly except for this newer version M4.

```java
a.a.ActorSystemImpl - Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: HTTP method too long (started with '{"requestType":"'). Increase `akka.http.server.parsing.max-method-length` to support HTTP methods with more characters.
```

Here is a sample code:
```java

// Prepare Request
WSRequest sendEmailRequest = ws
         .url(URL_END_POINT)
         .addHeader("Content-Type", "application/json")
         .addHeader(SEND_EMAIL_HEADER_LOCALE_KEY, currentLanguage)
         .setMethod("POST")
         .addQueryParameter(KEY, VALUE);

// Execute request
CompletionStage<? extends WSResponse> responsePromise = sendEmailRequest.post(jsonRequest);

```

Sample json that was used as `someJsonString`:
```json
{"requestType":"VERIFY_EMAIL","idToken":"eyJhbGciOiJSUzI1NiIsImtpZCI6Ijk4Njk0NWJmMWIwNDYxZjBiZDViNTRhZWQ0YzQ1ZWU0ODMzMjgxOWEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYmxhY2tsaXN0LWRldi1uIiwiYXVkIjoiYmxhY2tsaXN0LWRldi1uIiwiYXV0aF90aW1lIjoxNTQxMzk5MDQ4LCJ1c2VyX2lkIjoiellicnVNYW0yRFNrTGVKVTNqRUNxZXlQQlFlMiIsInN1YiI6InpZYnJ1TWFtMkRTa0xlSlUzakVDcWV5UEJRZTIiLCJpYXQiOjE1NDEzOTkwNDgsImV4cCI6MTU0MTQwMjY0OCwiZW1haWwiOiJtci4zc29vbEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibXIuM3Nvb2xAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.YXdS_RdYRxQ3N-Np187A2NfBcBzje_MbhMxUCz_TTFjPJL5oHSGNQ9EpA8zYC0Yp_lPODa1yqW0syteVcWdkgrizAfcqO9Az3zZBwBkZ1Oxj2tVxrtwboV3lp-irrm2D1OoXAjXKedwpA30OS6HLwSfEkBFlyXtNDe2rqQUSj3UfhfJT6iBp_EN0-Nj656Wkf3P975VbwWmrfuaCX9JhIHBXXE1dh88CIo7Z_EeHBGRJeR_qsWzUBM8fB3t8W_nWgZys1ONZwu1VVJYizLHK-yTVFnKFRJqxLs5RIiEUKluLBKnuqQB59natFVn7CVh-LAok9xe4NdeWxVBArKDuRA"}

```

**Comment by marcospereira** [comment]
Hi @moga111,

Could you please provide a full project that reproduces the problem? I tried with this code but I'm it is working as expected:

Action:

```java
@BodyParser.Of(BodyParser.TolerantJson.class)
public Result json() {
    return ok(request().body().asJson());
}
```

And the following test:

```java
@Test
public void testJson() throws Exception {
    final WSClient ws = app.injector().instanceOf(WSClient.class);
    CompletionStage<WSResponse> response = ws
            .url("http://localhost:" + testServer.getRunningHttpPort().orElse(port))
            .addHeader("Content-Type", "application/json")
            .addHeader("X-Language", "us")
            .setMethod("POST")
            .addQueryParameter("Some", "Query")
            .post("{\"requestType\":\"VERIFY_EMAIL\",\"idToken\":\"eyJhbGciOiJSUzI1NiIsImtpZCI6Ijk4Njk0NWJmMWIwNDYxZjBiZDViNTRhZWQ0YzQ1ZWU0ODMzMjgxOWEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYmxhY2tsaXN0LWRldi1uIiwiYXVkIjoiYmxhY2tsaXN0LWRldi1uIiwiYXV0aF90aW1lIjoxNTQxMzk5MDQ4LCJ1c2VyX2lkIjoiellicnVNYW0yRFNrTGVKVTNqRUNxZXlQQlFlMiIsInN1YiI6InpZYnJ1TWFtMkRTa0xlSlUzakVDcWV5UEJRZTIiLCJpYXQiOjE1NDEzOTkwNDgsImV4cCI6MTU0MTQwMjY0OCwiZW1haWwiOiJtci4zc29vbEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibXIuM3Nvb2xAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.YXdS_RdYRxQ3N-Np187A2NfBcBzje_MbhMxUCz_TTFjPJL5oHSGNQ9EpA8zYC0Yp_lPODa1yqW0syteVcWdkgrizAfcqO9Az3zZBwBkZ1Oxj2tVxrtwboV3lp-irrm2D1OoXAjXKedwpA30OS6HLwSfEkBFlyXtNDe2rqQUSj3UfhfJT6iBp_EN0-Nj656Wkf3P975VbwWmrfuaCX9JhIHBXXE1dh88CIo7Z_EeHBGRJeR_qsWzUBM8fB3t8W_nWgZys1ONZwu1VVJYizLHK-yTVFnKFRJqxLs5RIiEUKluLBKnuqQB59natFVn7CVh-LAok9xe4NdeWxVBArKDuRA\"}\n");

    WSResponse wsResponse = response.toCompletableFuture().get();
    Assert.assertEquals(wsResponse.getStatus(), OK);
}
```

As I said, the test is passing as expected.

**Comment by moga111** [comment]
Hello @marcospereira 
Thanks for looking into this.

Sorry if that was not reproducible, but I am very sure that the request is not going through due to some change. It literally the code I provided in my controller. I submit a token to it with request type and it never reaches the end point because of the error  
```
a.a.ActorSystemImpl - Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: HTTP method too long (started with '{"requestType":"'). Increase `akka.http.server.parsing.max-method-length` to support HTTP methods with more characters.
```
Which was very hard to catch. I would put on low priority but I think its worth looking into it since it WS upgrade is part of the recent M4 updated (if I am not mistaken).

Thanks again!

**Comment by marcospereira** [comment]
Hey @moga111,

Do you think it is possible to use your project as a start point to create a reproducer? Is the problem consistently or just for some requests?

**Comment by moga111** [comment]
Hello @marcospereira 

I found the problem, and its mostly my code. Last year, the end point was rejecting my request without providing `Content-Length` in the header, so I used to provide 0 to make it work. It was working fine up until M4, now after trying, I tried to remove this header not thinking it would make any difference, and it finally accepted the request.
I think the `Content-Length` somehow intercepted my provided data.

Here is the sample before and after, and sorry again for not providing that in the code above, I don't know how I missed it

Before
```java
        WSRequest sendEmailRequest = ws
                .url(URL_END_POINT)
                .addHeader("Content-Type", "application/json")
                .addHeader("Content-Length", "0")
                .addHeader(SEND_EMAIL_HEADER_LOCALE_KEY, currentLanguage)
                .setMethod("POST")
                .addQueryParameter(KEY, VALUE);
```
After
```java
        WSRequest sendEmailRequest = ws
                .url(URL_END_POINT)
                .addHeader("Content-Type", "application/json")
                .addHeader(SEND_EMAIL_HEADER_LOCALE_KEY, currentLanguage)
                .setMethod("POST")
                .addQueryParameter(KEY, VALUE);
```

So in your previous test, If you try it with `Content-Length: 0` in the header on M3 and M4, I suspect you would get different results.



Thanks for your time and

**Comment by marcospereira** [comment]
Closing. Thanks for explaining the problem, @moga111.
