### ISSUE TITLE
Documentation improvement suggestion

### ISSUE THREAD

**Issue by vs-slavchev** [playframework/playframework#8773]
Hi, in the official documentation on the page 'Deploying your application' there is an important configuration missing. It is mentioned in https://www.playframework.com/documentation/2.6.x/JavaJPA#deploying-play-with-jpa

**Comment by marcospereira** [comment]
Thank you, @vs-slavchev.

Do you want to submit a PR to add a link between the pages?

Best.

**Comment by vs-slavchev** [comment]
Hi @marcospereira yes I will!

**Comment by marcospereira** [comment]
Closing after #8776.
