### ISSUE TITLE
database url is not working through paly application.conf file with play-slick 3.0.3

### ISSUE THREAD

**Issue by MdMahadiaHossain** [playframework/playframework#8787]
I am using this config in  play application.conf with direct slick library  not with play-slick.
Library dependency is - libraryDependencies += "com.typesafe.play" %% "play-slick" % "3.0.3"
```
mydb {
  dataSourceClass = "slick.jdbc.DatabaseUrlDataSource"
  properties = {
    driver = "slick.driver.PostgresDriver$"  // not working
    url = "postgresql://postgres:admin@localhost:5432/postgres"
  }
}
```
But it is not working while instead this is working-

```
mydb {
  dataSourceClass = "slick.jdbc.DatabaseUrlDataSource"
  properties = {
    driver = "org.postgresql.Driver" //ok
    url = "postgresql://postgres:admin@localhost:5432/postgres"
  }
}
```

**Comment by wsargent** [comment]
Please use  https://discuss.playframework.com/ for issues in your codebase - this is an issue tracker for Play bugs specifically.
