### ISSUE TITLE
Favour javax.inject over Guice-specific features

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#8790]
For Play 2.8 we might want to favour using `javax.inject` over depending directly on Guice.

**Comment by mkurz** [comment]
@dwijnand What are your learning in Lagom regarding Guice?

**Comment by hepin1989** [comment]
Yes...

**Comment by dwijnand** [comment]
Asked for more specifics, discovered my misunderstanding, and amended the ticket.  😄

**Comment by TimMoore** [comment]
@jroper you did  :smile:, but said at the time that it didn't fully remove the dependcy on Guice

https://github.com/lagom/lagom/pull/1360 (later rebased as https://github.com/lagom/lagom/pull/1385)

**Comment by dwijnand** [comment]
Excellent, thanks James and Tim.

So it would seem there's no additional work necessary in Play.  So I'll close the ticket, but comment/reopen if I misunderstood.
