### ISSUE TITLE
Compilation of Default Route Parameters failed if Java Request is defined.

### ISSUE THREAD

**Issue by wjtan** [playframework/playframework#8826]
### Play Version (2.5.x / etc)

2.7.0-RC3

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Ubuntu 16.04

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

### Expected Behavior

Route parameters (including current request) with default values works:
```
GET /show2 controllers.HomeController.show2(req: Request, value: Int ?= 6)
```

### Actual Behavior

Route compilation fails if default parameters are not defined.

```
[error] app/views/index2.scala.html:14:55: not enough arguments for method show2: (value: Int)play.api.mvc.Call.
[error] Unspecified value parameter value.
[error] <div><a href="@controllers.routes.HomeController.show2()">Show</a></div>
[error]                                                       ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

### Reproducible Test Case

https://github.com/wjtan/play-route-bug

**Comment by mkurz** [comment]
Thanks, I will have a look.

**Comment by mkurz** [comment]
Fix is here: #8827

**Comment by wjtan** [comment]
Thanks for the quick fix. Will test on the next release.

**Comment by mkurz** [comment]
@wjtan can you test with the new RC?
https://blog.playframework.com/play-2-7-0-rc8-released/
Thanks!

**Comment by wjtan** [comment]
I have tested both on the test case and my project. Both of them can be compiled.
Thanks!
