### ISSUE TITLE
EndpointIntegrationSpecificationSpec HTTP/2 test failure on Java 11

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#8829]
More details on the failing test on Java 11:

```
Endpoints should
  respond with the highest supported HTTP protocol
    + with Netty HTTP/1.1 (plaintext) (2 seconds, 534 ms)
    + with Netty HTTP/1.1 (encrypted) (2 seconds, 571 ms)
    + with Akka HTTP HTTP/1.1 (plaintext) (2 seconds, 576 ms)
    + with Akka HTTP HTTP/1.1 (encrypted) (2 seconds, 581 ms)
[error]     x with Akka HTTP HTTP/2 (encrypted) (348 ms)
[error]      http/1.1 != h2 (EndpointIntegrationSpecificationSpec.scala:23)
```
caused by the test here:

https://github.com/playframework/playframework/blob/2241bb53b4a023f8a8f84f7679b0a136c2851672/framework/src/play-integration-test/src/test/scala/play/it/test/EndpointIntegrationSpecificationSpec.scala#L22-L23

So `http/1.1` is returned where it should be `http/2.0`

There is also this "error":
```
[jetty-alpn-agent] Could not parse java.version: 11
[jetty-alpn-agent] Could not find a matching alpn-boot JAR for Java version: 11
```
I guess this is because there [is no mapping for Java 11 in jetty-alpn-agent](https://github.com/jetty-project/jetty-alpn-agent/blob/363985edd3a9dce3f8e5d58a0c7d5c3813aacc38/src/main/java/org/mortbay/jetty/alpn/agent/Premain.java#L33-L63) and also not in [jetty-alpn](https://github.com/jetty-project/jetty-alpn/blob/master/docs/version_mapping.properties).

Does this have something to do with jetty-alpn-agent? Or do we even need jetty-alpn-agent with JDK9+ anymore (see [JEP 244](https://openjdk.java.net/jeps/244))? (Unfortunately I don't have much knowledge about jetty, http2 in JDK9+, etc.)

I went ahead and just removed all the `jetty-alpn-agent` code and agents in Play and ran the `EndpointIntegrationSpecificationSpec` again, but exactly the same test failed again.

I guess someone else with more knowledge about jetty, alpn, etc. is able to fix this?

_Originally posted by @mkurz in https://github.com/playframework/playframework/pull/8754#issuecomment-441632660_

**Comment by mkurz** [comment]
Note to myself - more infos [here](https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html#alpn):
I guess we need to use the "*[provider based on the Conscrypt security provider](https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html#alpn-conscrypt)*", because Play supports JDK 8 (and should be faster as well then JDK9 provider). Later, when dropping Java 8 support we could also use "*[the provider based on the ALPN APIs present in the JDK](https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html#alpn-jdk9)*"

Also an interesting [comment here](https://github.com/jetty-project/jetty-alpn/issues/15#issuecomment-361494167).

**Comment by mkurz** [comment]
If we fix this I think we are pretty close to make all Java 11 tests green.

**Comment by ignasi35** [comment]
In https://travis-ci.com/playframework/playframework/jobs/192016513, we no longer see:

```
Endpoints should
  respond with the highest supported HTTP protocol
    + with Netty HTTP/1.1 (plaintext) (2 seconds, 534 ms)
    + with Netty HTTP/1.1 (encrypted) (2 seconds, 571 ms)
    + with Akka HTTP HTTP/1.1 (plaintext) (2 seconds, 576 ms)
    + with Akka HTTP HTTP/1.1 (encrypted) (2 seconds, 581 ms)
[error]     x with Akka HTTP HTTP/2 (encrypted) (348 ms)
[error]      http/1.1 != h2 (EndpointIntegrationSpecificationSpec.scala:23)
```

but 

```
[info]     handle exceptions that happens in web command
[info]       + with Netty HTTP/1.1 (plaintext) (2 seconds, 456 ms)
[info]       + with Netty HTTP/1.1 (encrypted) (2 seconds, 477 ms)
[info]       + with Akka HTTP HTTP/1.1 (plaintext) (2 seconds, 484 ms)
[info]       + with Akka HTTP HTTP/1.1 (encrypted) (2 seconds, 490 ms)
[error]       ! with Akka HTTP HTTP/2 (encrypted) (10 seconds, 88 ms)
[error]        java.net.SocketTimeoutException: timeout (Http2Stream.java:662)
[error] okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:662)
[error] okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:670)
[error] okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
[error] okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
[error] okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
[error] okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
[error] okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[error] okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
[error] okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[error] okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
```

I guess we've introduced change interacting with this since we raised the issue.

**Comment by ignasi35** [comment]
Update:

I am using OpenJDK 11.0.1 (installed using Jabba) locally and: 

 - I can't reproduce the test failure in `EndpointIntegrationSpecificationSpec` (mentioned in the issue description)
 - I can't reproduce the issue I linked on my last comment ( `SocketTimeoutException: timeout (Http2Stream.java:662)` running `play.it.http.FlashCookieSpec`)
