### ISSUE TITLE
Unable to deploy the play 2.5 app by Boxfuse

### ISSUE THREAD

**Issue by comekoolab** [playframework/playframework#8852]
### Are you looking for help?

I am unable to deploy the play app by using Boxfuse due to the lack of application.conf file reported by Boxfuse.

### Play Version (2.5.x / etc)

I am use Play 2.5

### API (Scala / Java / Neither / Both)

Java API

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Mac OS 10.13.6

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

1. sbt clean / activator clean
2. sbt complile / activator compile
3. sbt dist / activator dist
4. boxfuse run -env=prod -X
5. Error Message reported by boxfuse: "Unable to find application.conf in zip file => using defaults"

And I am sure I set the application secret value in conf/application.conf file which is play.crypto.secret="O8rb>3j^uFefDx]hpKJbY2^Jj6J^WjvZu^^2P;kv4;SxIlCw0Q@bV2HA6pBqPD3?"

<img width="1360" alt="screen shot 2018-12-02 at 11 29 44" src="https://user-images.githubusercontent.com/45412079/49335296-defac780-f625-11e8-8140-e491eb2302e7.png">

<img width="552" alt="screen shot 2018-12-02 at 11 32 49" src="https://user-images.githubusercontent.com/45412079/49335304-09e51b80-f626-11e8-8d60-b2ce996c3161.png">

**Comment by marcospereira** [comment]
Hello @comekoolab,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Also, better if you can get in contact with BoxFuse since we don't maintain this integration.

Best.
