### ISSUE TITLE
HttpEntity.Streamed does not send Content-Length header

### ISSUE THREAD

**Issue by Steinliiippp** [playframework/playframework#8853]
### Description

Im trying to create a file download action with HttpEntity.Streamed but the Content-Length header is not send with the response. You cannot set it by your self, because this is blocked by play. I used Chrome and Firefox

### Play Version (2.5.x / etc)

2.6.x

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

### Library Dependencies

just the play api

### Expected Behavior

1. Build up a HttpEntity.Streamed
2. Send it with the headers (Content-Disposition, Content-Length)
3. Let the browser download the file with progress

### Actual Behavior

1. play handles the request and sends the response in chunks
2. Browser receives the response with Content-Disposition but not with Content-Length header
3. Browser downloads the file but does not show progress. The Content-Length Header is not there

### Reproducible Test Case
```
public Result download(String p){
	java.io.File file = new java.io.File("PATH_TO_THE_FILE");
	java.nio.file.Path path = file.toPath();
	Source<ByteString, ?> source = FileIO.fromPath(path);
	Optional<Long> contentLength = Optional.of(file.length());
	Map<String, String> headers = new HashMap();
	headers.put("Content-Disposition", "attachment; filename=\"FILENAME.TXT\"");
	return new Result(
		new ResponseHeader(200, headers),
		new HttpEntity.Streamed(source, contentLength, Optional.of("application/zip"))
	);
}

**Comment by marcospereira** [comment]
Hi @Steinliiippp,

I was not able to reproduce this. I'm using exactly this controller here:

```java
package controllers;

import akka.stream.javadsl.FileIO;
import akka.stream.javadsl.Source;
import akka.util.ByteString;
import play.http.HttpEntity;
import play.mvc.*;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

public class HomeController extends Controller {

    public Result download() {
        java.io.File file = new java.io.File("/Users/marcospereira/tmp/dummy.zip");
        java.nio.file.Path path = file.toPath();
        Source<ByteString, ?> source = FileIO.fromPath(path);
        Optional<Long> contentLength = Optional.of(file.length());
        Map<String, String> headers = new HashMap<>();
        headers.put("Content-Disposition", "attachment; filename=\"FILENAME.TXT\"");
        return new Result(
                new ResponseHeader(200, headers),
                new HttpEntity.Streamed(source, contentLength, Optional.of("application/zip"))
        );
    }
}
```

And when running `curl -I http://localhost:9000/download`, I'm seeing the `Content-Length` header as expected:

```
HTTP/1.1 200 OK
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Content-Disposition: attachment; filename="FILENAME.TXT"
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self'
X-Permitted-Cross-Domain-Policies: master-only
Date: Fri, 14 Dec 2018 22:11:33 GMT
Content-Type: application/zip
Content-Length: 52536
```

And it matches the file size I see when running `ls -l ~/tmp/dummy.zip`:

```
-rw-r--r--  1 marcospereira  staff  52536 14 Dec 17:10 /Users/marcospereira/tmp/dummy.zip
```

Could you create a project that reproduces this problem?
