### ISSUE TITLE
Add 2.13.0-M5 build

### ISSUE THREAD

**Issue by renatocaval** [playframework/playframework#8857]
(copied from https://github.com/playframework/playframework/issues/7940)

We need to have Scala 2.13.0-M5 build. This obviously depends on other libraries support Scala 2.13. The current version of Scala 2.13 is a `2.13.0-M5`, so we need to start from there and have builds for more relevant milestones.

## Dependencies

This **is not** a complete list:

### Direct dependencies:

- [x] interplay: https://github.com/playframework/interplay/pull/53
- [x] play-json: https://github.com/playframework/play-json/pull/194
- [x] play-ws: https://github.com/playframework/play-ws/pull/303
- [x] cachecontrol: https://github.com/playframework/cachecontrol/pull/29
- [x] play-doc: https://github.com/playframework/play-doc/pull/42/files
- [x] twirl: https://github.com/playframework/twirl/pull/190
- [x] scala-java8-compat: https://github.com/scala/scala-java8-compat/issues/119

### Akka & Akka HTTP

Including transitive dependencies.

- [x] ssl-config: https://github.com/lightbend/ssl-config/pull/135
- [x] scala-stm: https://github.com/scala-stm/scala-stm/pull/6
- [x] spray-json: https://github.com/spray/spray-json/pull/275
- [x] specs2: https://github.com/etorreborre/specs2/issues/709
- [x] kind-projector: https://github.com/non/kind-projector/issues/79 

See also https://github.com/playframework/playframework/issues/8492

**Comment by raboof** [comment]
For testing, akka 2.5-SNAPSHOT-c70ce36 and akka-http-core 10.1.5+78-e558ae7b should be available and now pass their own unit tests. We will not be able to merge this work for 2.5.19, but we can likely manually publish 2.5.19-with-scala-2.13.0-M5 from the branch.

**Comment by SethTisue** [comment]
specs2 has published except for parts which depend on cats-effect, which y'all probably aren't using

kind-projector has published.

**Comment by jtjeferreira** [comment]
@dwijnand I see you set the Play 2.8.0 milestone, that mean 2.13 will only land in 2.8.x, or would be possible to introduce it later in the 2.7.x series?

**Comment by dwijnand** [comment]
To be decided.  And also I added it to the 2.8 milestone because I _hope_ we can deliver it, but it's no guarantee.  For 2.7 we'll be able to tell when we see what it means to support Scala 2.13.

**Comment by dwijnand** [comment]
Upgraded play-ws.

We're going to release play-ws 2.0.1 shortly (for Play 2.7), at which point this can be PR'd.

**Comment by dwijnand** [comment]
> We're going to release play-ws 2.0.1 shortly (for Play 2.7), at which point this can be PR'd.

Welp!  https://github.com/playframework/play-ws/issues/274#issuecomment-456838316  😄

**Comment by jtjeferreira** [comment]
> Welp! [playframework/play-ws#274 (comment)](https://github.com/playframework/play-ws/issues/274#issuecomment-456838316) smile

I can give this a try...

**Comment by dwijnand** [comment]
Marcos started, and realised we need play-docs still.

**Comment by jtjeferreira** [comment]
> Marcos started, and realised we need play-docs still.

Well I have pushed what I got into #8986 and there are some errors in the `it:tests` that I need to look into.

However I don't understand whats the problem with play-docs

**Comment by SethTisue** [comment]
should this ticket have been closed? (have artifacts been published for M5?)

**Comment by raboof** [comment]
Jup, for example https://search.maven.org/artifact/com.typesafe.play/play-server_2.13.0-M5/2.7.0/jar

**Comment by dwijnand** [comment]
Published but not released/announced.

**Comment by SethTisue** [comment]
ok, I see. I wanted to try play-webgoat, but it's blocked by omnidoc (https://github.com/playframework/playframework/issues/8492)

**Comment by SethTisue** [comment]
scala/make-release-notes@85f5accf480d413fb0edd1ded076161893fd229b
