### ISSUE TITLE
[2.7.x]: @lang, @flash and @session are now ambiguous in views for Java applications.

### ISSUE THREAD

**Issue by marcospereira** [playframework/playframework#8866]
### Play Version

2.7.0-RC8

### API

Java

### Expected Behavior

Using `@lang`, `@flash` and `@session` should compile successfully to access request's `Lang`, `Flash` and `Session` in views.

### Actual Behavior

It fails to compile because both different methods to access these pieces of information are imported by default:

https://github.com/playframework/playframework/blob/ee30d34432cc26cd1ccfbe03911d7062104ba553/framework/src/build-link/src/main/java/play/TemplateImports.java#L33-L36

The methods are declared in `play.core.j.PlayMagicForJava`:

https://github.com/playframework/playframework/blob/02e58240b2cb1b3d035aa1620e461cee36c2370b/framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala#L51-L58

And in `play.mvc.Http.Context.Implicit`:

https://github.com/playframework/playframework/blob/c39887c59c8f8b0c044cb1e4fbacb7c9bafdd56f/framework/src/play/src/main/java/play/mvc/Http.java#L533-L567

### Reproducible Test Case

Create a Java project that has a view like this:

```html
@()(implicit requerst: Http.Request)

@flash("something-flash")
@session("something-session")

@lang
```

**Comment by mkurz** [comment]
So probably the solution is to rename the methods defined in `TemplateMagicForJava.scala`?

**Comment by marcospereira** [comment]
@mkurz sounds like a good idea to me. We can later do all the dance to reclaim these names after removing `Http.Implicit`.
