### ISSUE TITLE
[2.7.x] Security.Authenticator can't modify Request

### ISSUE THREAD

**Issue by nextdtinc** [playframework/playframework#8873]
### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### Expected Behavior

In Play 2.6, `Security.Authenticator` used to accept a `Http.Context` with the full function signature:

`public String getUsername(Http.Context ctx)`.

Context parameters could be put into the context via `ctx.args.put(key, value)`. This allowed for passing parameters back to controllers from the `Security.Authenticator`.

However, in Play 2.7 the signature of `getUsername` has changed to:

`public Optional<String> getUsername(Http.Request req)`.

While it is possible to put parameters into a **new** `Request` object, it is not possible to change the **existing** (passed-in) `req` object in-place, unlike the `ctx` of the old version of the function.

How can one modify the `Request` object that is now passed, so that parameters can be passed to controllers? (`Request.addAttr` returns a **new**`Request` object; it does not change the Request object in-place.)

**Comment by nextdtinc** [comment]
@mkurz this issue is related to passing Requests instead of Contexts. Requests, as far as I can tell, cannot be modified, unlike Contexts in Play 2.6.

**Comment by mkurz** [comment]
I think you can use [action composition](https://www.playframework.com/documentation/2.7.0-RC8/JavaActionsComposition#Defining-custom-action-annotations) and [request attributes](https://www.playframework.com/documentation/2.7.0-RC8/JavaActionsComposition#Passing-objects-from-action-to-controller) to solve this.
Just add an action annotation like `@RetrieveUser`:
```java
@With(RetrieveUserAction.class)
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface RetrieveUser {
}
```

```java
public class RetrieveUserAction extends Action<RetrieveUser> {
    public CompletionStage<Result> call(Http.Request req) {
        final User user = ....;
        return delegate.call(req.addAttr(Attrs.USER, user));
    }
}
```
As you can see in this action you can retrieve you user (like you did before probably `getUsername`) and save the user or just it's it into a request attribute.
Now make sure you annotate your action method (or controller class) with that action annotation (but _before_ the `@Security.Authenticated` annotation):
```java
@RetrieveUser
@Security.Authenticated
public Result RetrieveUserIndex() {
    return ok("It works!");
}
```

Now you can access the user in the `Authenticator`:
```java
@Override
public Optional<String> getUsername(Request req) {
    req.attrs.get(Attrs.USER); // now you can check if user is authenticate
    //...
}
```

I hope that helps, let me now what you think.

**Comment by marcospereira** [comment]
@mkurz's suggestion to use actions composition looks like the appropriate way to doing this since it better separates the concerns. Having a `get` method also mutates the state of the current request is not intuitive because you usually don't expect `get` methods to do anything besides getting some state.

@nextdtinc does this solution works for you?

@mkurz maybe this is something more to document on our migration guide (arguably since it appears to be a very specific use case)? What do you think?

**Comment by nextdtinc** [comment]
@mkurz @marcospereira Thanks for your comments. While @mkurz's method would work it does seem quite verbose and difficult to understand for most people. The bottomline is that it used to be easier to easily share state between controllers using the global context object. Now that this is no longer possible there is no trivial way anymore, it seems.

**Comment by nextdtinc** [comment]
@marcospereira I hadn't thought of putting mutable data into an attribute, that's a good idea.

Well, I usually use a class derived from `Security.Authenticator` to enforce that a user is logged in (by checking the cookie, and if not logged in giving them a 404 Unauthorized), and a class derived from `play.mvc.Action.Simple`to simply _check_ if the user is logged in or not. In both classes, I would then store the currently logged in user (if any) into a global Context which is seen by all controllers. This was very convenient.

Since with Play 2.7 I couldn't figure out how to store such a shared global state inside a `Request`, I am now just having all my controllers call a function which re-determines from scratch if the user is logged in. It's not more expensive to do so, since the `play.mvc.Action.Simple` and `Security.Authenticator` were also doing that, but this way I don't have to worry about any shared state. This approach also allows me to use fewer Play features, as I always aim to use only trivial features of any web framework (so that I'm not married to any one).

However, in the future I might elect to use your idea of the mutable `Request` attribute.

**Comment by mkurz** [comment]
@nextdtinc I guess we can close this issue since you found a way to solve this?

**Comment by marcospereira** [comment]
Closing.

@nextdtinc fell free to add some more information later if you think we should reopen this. :-)

**Comment by jo-wil** [comment]
Is it possible to update the Security API to return a generic parameter instead of just returning a String from getUsername? I see in the code on line 62 currently in https://github.com/playframework/playframework/blob/master/core/play/src/main/java/play/mvc/Security.java, the username is actually added to the request before calling the wrapped function. If this parameter was updated to be generic, users of this API could set that parameter to whatever they want?

**Comment by ourgit** [comment]
@mkurz @marcospereira,
deprecated the Http.Context sounds make sense,however, howto retrieve the actionMethod with the request under play 2.7?  I use method below  under play 2.6+
```
    Map<String, Object> args = ctx.args;
    String actionMethod = (String) args.get("ROUTE_ACTION_METHOD");
```
I need the actionMethod to identify and authorize the requests, now it seems play  2.7 do not provide the way to us, what should be the correct way to do so under play 2.7+,thank you very much.

**Comment by mkurz** [comment]
@ourgit See https://www.playframework.com/documentation/2.7.x/Migration26#Router-tags-are-now-attributes

**Comment by ourgit** [comment]
> @ourgit See https://www.playframework.com/documentation/2.7.x/Migration26#Router-tags-are-now-attributes

Thank you. That is exactly what i need.

**Comment by jcstritt** [comment]
Release 2.7.x of Play has become very complicated to manage the session! (please KISS). How to manage a session timeout as suggested in the following article (https://www.javacodegeeks.com/2014/04/how-to-implement-a-session-timeout-in-play-framework-2.html), since the request session attributes are now not mutable (I can't reset my timeout timestamp in) ? Have you any exemple (Java) to have mutable data inside the request ? How to clear the session in Security.Authenticator after a timeout comes ? Thanks.

**Comment by jcstritt** [comment]
I finally found the answers to my questions myself. It would have been nice to find an example like the one below in Play's documentation. Finally, managing the session in Play 2.7 is not that complicated.  Have a nice day.

```
public class ActionCreator implements play.http.ActionCreator {
  private final int msTimeout;

  @Inject
  public ActionCreator(Config config) {
    this.msTimeout = config.getInt("application.msTimeout");
  }

  public boolean isTimeout(Http.Request req) {
    boolean timeout = false;
    Optional<String> timestamp = req.session().getOptional("timestamp");
    if (timestamp.isPresent()) {
      long cTime = System.currentTimeMillis();
      long sTime = Long.parseLong(req.session().getOptional("timestamp").orElse("0"));
      timeout =  (cTime - sTime) >= msTimeout;
    }
    return timeout;
  }

  @Override
  public Action<?> createAction(Http.Request request, Method actionMethod) {
    return new Action.Simple() {

      @Override
      public CompletionStage<Result> call(Http.Request req) {

        // http call request
        return delegate.call(req).thenApply(result -> {

          // return final result with adapted headers
          if (isTimeout(req)) {
            return result.withNewSession();
          } else {
            return result.addingToSession(req, "timestamp", "" + System.currentTimeMillis());
          }
        });
      }

    };
  }
}
```
