### ISSUE TITLE
Support additional HTTP response statuses

### ISSUE THREAD

**Issue by gabbah** [playframework/playframework#8892]
Playframework should support additional HTTP status codes, such as 428 Precondition Required, as specified in https://tools.ietf.org/html/rfc6585#section-3

(I know I can manually return any status code)

### Play Version (2.5.x / etc)
2.6

### API (Scala / Java / Neither / Both)
Both

**Comment by marcospereira** [comment]
Hey @gabbah,

Make sense to me. Do you want to submit a PR to add these additional status codes? This would need to be done for both Java and Scala APIs.

**Comment by gabbah** [comment]
> Hey @gabbah,
> 
> Make sense to me. Do you want to submit a PR to add these additional status codes? This would need to be done for both Java and Scala APIs.

Sure. The question I asked myself was if the additional status codes should be added in the existing Status trait, or if should be a new trait: ...status.Additional ?
I think the current idea is that Status holds the standard status codes, as specified in [rfc 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html). Perhaps the additional status codes, in rfc 6585, should not be mixed in there?
Or do we consider these additional codes so prevalent as to be considered the de facto standard now? Thoughts?

**Comment by marcospereira** [comment]
Hey @gabbah,

It is okay to use the `Status` trait since it does not make a distinction between the original and additional status. Also, it already has status `429` for example.

**Comment by gabbah** [comment]
> Hey @gabbah,
> 
> It is okay to use the `Status` trait since it does not make a distinction between the original and additional status. Also, it already has status `429` for example.

Ah ok, good point (didn't notice that before). I'll add it to Status trait then.
