### ISSUE TITLE
Remove/Clean the RabbitMQ module page

### ISSUE THREAD

**Issue by zanella** [playframework/playframework#8904]
The [official docs](https://www.rabbitmq.com/devtools.html#alt-jvm-dev) for RabbitMQ on the scala section point to this page: https://www.playframework.com/modules/rabbitmq-0.0.9/home

1. It's not for Scala, it's for Java
2. It seems to be unmaintained

Maybe it's a good idea to remove/clean it ?

Even better would be to point to a "better/right way" of using RabbitMQ w/ Scala + Play.

**Comment by wsargent** [comment]
This is something that exists for Play 1, which is Java based, and is not maintained by this project team.  There are people who still use Play 1, so the documentation is valid for them.

It's also on the RabbitMQ documentation, so you should file a bug on the RabbitMQ project.
