### ISSUE TITLE
[2.7.0-RC8] Bad example for JavaJavascriptRouter

### ISSUE THREAD

**Issue by slisaasquatch** [playframework/playframework#8911]
### Play Version (2.5.x / etc)
2.7.0-RC8

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
N/A

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
N/A

### Library Dependencies
N/A

### Actual Behavior
The example [here](https://www.playframework.com/documentation/2.7.0-RC8/JavaJavascriptRouter#router-resource) is incorrect. `request.host()` and `"jQuery.ajax"` are backwards.

### Reproducible Test Case
N/A

**Comment by mkurz** [comment]
Yeah, my bad, this needs to be fixed.
