### ISSUE TITLE
2.7-RC9: Play-Modules are started before DB-Mirgation Script was executed

### ISSUE THREAD

**Issue by Marc2017** [playframework/playframework#8935]
### Play Version (2.5.x / etc)

2.7-RC9

### API (Scala / Java / Neither / Both)

Java (Both)

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 8.1.

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

1.8.0_181

### Actual Behavior

> Please describe the expected behavior of the issue, starting from the first action.

When a DB-Evolution script is needed to be executed and autoapply is not set to true the user is normally asked to press "Apply script" in the browser to apply the DB-Changes. And after the evolution-scripts were executed the "play system" is starting.

In 2.7-RC9 the "play-system" already starts (the Play-Modules) before the db-script was executed. If the Modules need the database then the system crashes because of missing db-evolutions.

In 2.7-RC8 this was working.

**Comment by mkurz** [comment]
That's a result of how we fixed the evolutions bug in #8875...

Can you be more specific about "_If the Modules need the database_"? Do you mean when making queries against the db from within a module which would need an updated database?

**Comment by Marc2017** [comment]
Yes, exactly.

I get an Exception in a module that is executed on play-startup and needs to accesss the db.

Eg. fresh DB and there are no tables yet and "1.sql" needs to be executed first (for example) before the module can insert initial data.

before RC9 the modules were started after the evolutions were executed.

best regards
marc

**Comment by mkurz** [comment]
Hmm.. I am not sure how to fix this right now... I have to think more about it...
The easiest for now would probably be to check if the table exists and only insert data if it does?

**Comment by mkurz** [comment]
(that "table exists" check would only be necessary in dev mode however like: `if(mode != dev || table_exists) { run your sql }`)

**Comment by mkurz** [comment]
> ...and then the module is not executed again (or is it?)

Yes it will be executed again. That's because after the evolutions got applied the application will be restarted (and all modules will start again):
https://github.com/playframework/playframework/blob/2.7.0-RC9/framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala#L397

Can you give my approach a try and let us know if that works for you?

**Comment by Marc2017** [comment]
Yes I´ll try.

is there a "does need evolution" check I can access from the java module? 
(better than compare if a table exists, because perhaps another evolution needs to be applied - or a drop first, or...).

thanks.
marc

**Comment by mkurz** [comment]
> is there a "does need evolution" check I can access from the java module?

Not yet ;) I was thinking about the same actually ;)

So I guess you injected a `ApplicationEvolutions` instance into your `OnStartupService`? I think we could expose something like `applicationEvolutions.finished` or similiar (naming suggestions welcome) that indicates if all evolutions have been eventually applied.

**Comment by Marc2017** [comment]
> So I guess you injected a ApplicationEvolutions instance into your OnStartupService?

not yet, but I think I could use it that way.

> applicationEvolutions.finished

would be ok (or something like isUptodate(), .needsEvolution(), ...).
(but I have no clue about how to implement this - currently)

best regards
marc

**Comment by mkurz** [comment]
> (but I have no clue about how to implement this - currently)

I could implement this for you ;)
However if you can try with "if table exists" for now and let me know if that works for you that would be great, so we know how to move on here.

**Comment by Marc2017** [comment]
yes I think it will work this way:

-> I included the check for the table and it asks for evolution if it does not exist (no exeption anymore).
-> (The evolution script then has an error, I need to check this, perhaps its an "new" ebean related issue)
-> if I click "mark as resoolved" then it starts the server.
-> on a second run (db was created before) no evolution is executed and the server is started normally.

> I could implement this for you ;)

that would be perfect.

best regards
marc

**Comment by mkurz** [comment]
@marcospereira what do you think? Is there may be another solution?

**Comment by mkurz** [comment]
See #8943. I implemented `ApplicationEvolutions.finished` which you can check for to see if all evolutions were applied successfully in `DEV` mode instead of checking if the table exists already (actually you don't need to check for dev mode, just checking `finished` is enough).

**Comment by kritikaaarora435** [comment]
I am using applicationEvolutions.upToDate, but my module is not reloaded again, after the playEvolutions are executed.
