### ISSUE TITLE
Set MiMa to check on 2.7.0 on branch 2.7.x

### ISSUE THREAD

**Issue by renatocaval** [playframework/playframework#8945]
This should be the first issue we work after 2.7.0 release. 

On branch 2.7.x, MiMa must be configured to check against 2.7.0 GA. It's not checking against the latest RC (ie: RC9). 

We have some MiMa exclusions introduced in #8944. Those should be removed as they will become obsolete in 2.7.0.

**Comment by mkurz** [comment]
Fixed in #9003
