### ISSUE TITLE
No snapshots are generated anymore

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#8946]
Doc [says](https://www.playframework.com/documentation/2.6.x/Repositories#Accessing-nightly-snapshots) we provide nightly snapshots, however this isn't the case anymore...

* https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.12/
* https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/sbt-plugin_2.12_1.0/
* https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/sbt-plugin_2.10_0.13/

Looks like there is a problem starting in October 2018...

**Comment by marcospereira** [comment]
Yes, we need to adapt our nightly script to generate the snapshots for 2.7.x branch instead of only for 2.6.x one.

**Comment by mkurz** [comment]
Snapshots for 2.7.0 where generated already, however that stopped in October:
`2.7.0-2018-10-24-c19a9bd-SNAPSHOT`

**Comment by TimMoore** [comment]
The snapshots are generated from the `master` and `2.6.x` branches. October must be when `2.7.x` was branched from `master`.

**Comment by mkurz** [comment]
@TimMoore This makes sense of course :+1:

**Comment by dwijnand** [comment]
https://github.com/playframework/interplay/blob/master/bin/stableSnapshots#L18

**Comment by renatocaval** [comment]
PR is on its way: https://github.com/playframework/interplay/pull/57

**Comment by renatocaval** [comment]
The fix worked and snapshots are back:

https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.12/2.7.0-2019-01-17-a68fc6d-SNAPSHOT/

https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.12/2.8.0-2019-01-17-45b903d-SNAPSHOT/

**Comment by mkurz** [comment]
Nice!
