### ISSUE TITLE
i18n matching inversely

### ISSUE THREAD

**Issue by golemiso** [playframework/playframework#8953]
### Play Version (2.5.x / etc)

2.6

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.12 (Sierra)

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

### Expected Behavior

1. application.conf is like below

```
play.i18n.langs = [ "ja", "ja-JP", "en", "en-US" ]
```

2. access with `Accept-Language: en-GB`

3. `en` is chosen for rendering

### Actual Behavior

3. default lang `ja` is chosen

According to the Stackoverflow, in this case, `en-GB` should be matched with `en`:
https://stackoverflow.com/questions/30754287/java-8-locale-lookup-behavior

I found this issue could be occurred because of the code below

https://github.com/playframework/playframework/blob/8793cfaa568f79e822cb11c1d6a156331ca9ba74/framework/src/play/src/main/scala/play/api/i18n/Langs.scala#L58

According to the Javadoc of `Locale#lookup` , first parameter should be `user's Language Priority List` and second be `instances used for matching`, but actually it is in inverse.

**Comment by mkurz** [comment]
The play way to handle this is to add `en-GB` to the supported languages:

```
play.i18n.langs = [ "ja", "ja-JP", "en", "en-US", "en-GB" ]
```

If you have a `messages.en-GB` file it will be used, if not it will fall back to `messages.en`, if this doesn't exist neither then the `messages` file kicks in.

**Comment by golemiso** [comment]
I know how it works. `en-GB` was only an example.
In my opinion, it is preferable for all English users such as `en-AU`, `en-CA`,  `en-IN`, etc. to render in English. However it is not useful to enumerate all possible `en-*` locales. (plus all variant like`en-Latn-US`)

It is nice and clear to add only `en` to the supported languages to support all English users.
I am not only talking about English but all possible situations such as French, Spanish, Chinese and so on.

This behavior is described in RFC 4647 section 3.4.

**Comment by cchantep** [comment]
Hi, please first use the [mailing list](https://discuss.lightbend.com/c/play) to discuss feature change/request. Best regards
