### ISSUE TITLE
Drop support for sbt 0.13

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#8959]
sbt 0.13 is publically EOL, and will eventually be EOL for Lightbend subscribers. 
 When that is the case (or in the run-up to it) we can, and I propose should, drop support for sbt 0.13.  Optimistically putting in the 2.8.0 milestone.

Not to be confused with #8383, which is about moving Play's build from sbt 0.13 to sbt 1, which is related but neither blocks one another.

**Comment by SethTisue** [comment]
I don't see how the EOL status at Lightbend affects the decision here? It seems to me that you can drop 0.13 support in 2.8 regardless of 0.13's EOL date.

**Comment by TimMoore** [comment]
Related: https://github.com/lagom/lagom/issues/1714
