### ISSUE TITLE
Remove support for `play.crypto.secret` & `application.secret` in 2.7.x

### ISSUE THREAD

**Issue by naferx** [playframework/playframework#8981]
They have been marked as deprecated for a while 

`application.secret` since https://www.playframework.com/documentation/2.4.x/Migration24#Configuration-changes and `play.crypto.secret` since https://www.playframework.com/documentation/2.6.x/Migration26#Other-Configuration-changes

**Comment by marcospereira** [comment]
A pull request would be very welcomed here.

**Comment by naferx** [comment]
A PR will be arriving ;)

**Comment by chipz** [comment]
Hi guys, I created a PR on removing the `play.crypto.secret` and `application.secret` on https://github.com/playframework/playframework/pull/9061
