### ISSUE TITLE
Reformat and unnest

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#8992]
Hi!  So there's a number of repository structure issues the @playframework/core team would like to resolve so we've come up with this plan, which we're sharing with the @playframework/integrators team, in case there's anything we didn't consider.

The plan is to:
* send 1 massive PR (rather than several big PRs)
* in which the scope is to:
  * use scalafmt & sbt-java-formatter, and
  * unnest the `framework/` and `framework/src/` directories
* we're going to base most of the config/setup on what the Alpakka Team has recently done
* the PR commits will be, in order:
  * config + build setup
  * reformat
  * unnest
* this is so that any in-flight PRs can: cherry-pick the first commit, then reformat locally, then merge in master (I'll double-check this work with a few PRs)
* then we'll PR 2.7.x and 2.6.x, after ^ is merged

@ignasi35 also would like to consider grouping modules in directories, so it's a more hierarchical directory structure instead of uniform flat structure.  It would make sense to do that in this effort, but he needs a moment to come up with the details of that proposal.

I hope to complete this by Friday 1 February.

**Comment by dwijnand** [comment]
Now I'm not sure if I'll make it for Friday, but I'll try.

Akka's PR is https://github.com/akka/akka/pull/26220

**Comment by ignasi35** [comment]
I take the idea from Lagom's folder structure:

<img width="448" alt="screen shot 2019-01-30 at 11 33 05" src="https://user-images.githubusercontent.com/762126/51975579-e0f4d180-2482-11e9-95e6-41ef18d0e2f6.png">

When navigating Play's flat structure I find confusing having to scroll too much or `grep` the whole project. I was thinking about something on the lines:

```
.
├── cache
│   ├── play-cache
│   ├── play-caffeine-cache
│   ├── play-ehcache
│   └── play-jcache
├── core
│   ├── play
│   ├── play-exceptions
│   ├── play-guice
│   ├── play-logback
│   └── play-streams
├── dev
│   ├── build-link
│   ├── play-docs
│   ├── play-docs-sbt-plugin
│   ├── play-integration-test
│   ├── play-jdbc-evolutions
│   ├── play-microbenchmark
│   ├── routes-compiler
│   ├── run-support
│   └── sbt-plugin
├── persistence
│   ├── play-java-jdbc
│   ├── play-java-jpa
│   ├── play-jdbc
│   └── play-jdbc-api
├── testkit
│   ├── play-specs2
│   └── play-test
├── transport
│   ├── client
│   │   ├── play-ahc-ws
│   │   └── play-ws
│   └── server
│       ├── play-akka-http-server
│       ├── play-akka-http2-support
│       ├── play-netty-server
│       └── play-server
└── web
    ├── play-filters-helpers
    ├── play-java
    ├── play-java-forms
    ├── play-joda-forms
    └── play-openid
```

Note: in the proposal above there may be groups that don't make too much sense or circular dependencies between group categories. This is just a suggestion I put together in 5 minuts to demonstrate how grouping can improve understanding the areas of Play.

**Comment by ignasi35** [comment]
@renatocaval yeah, I wasn't sure where to put `evolutions`.

I would like to keep all the `WebCommands` together, though:

```
│   ├── play-docs
│   ├── play-docs-sbt-plugin   ## This probably belongs to 'dev/'
│   ├── play-jdbc-evolutions
```

The other items I'm not so sure about anymore are:

```
│   ├── play-integration-test
│   ├── play-microbenchmark
```

I put them in `dev/` but they are projects used during development of play itself and not tools provided to the end user for the `Mode.Dev`.

**Comment by marcospereira** [comment]
I would prefer to have `play-jdbc-evolutions` inside `persistence` instead of trying to have all the web commands together. Some suggestions:

1. Rename `dev` to `dev-mode` to make it clear what is it about
1. Move `play-integration-test` and `play-microbenchmark` to `core` makes more sense to me. As you said, this is part of the framework testing (and these projects aren't published anyway).

**Comment by ignasi35** [comment]
@marcospereira what do you think about `play-docs-sbt-plugin` and `play-docs`?

**Comment by marcospereira** [comment]
Hey @ignasi35 I'm okay with keeping them in `dev`/`dev-mode`.

**Comment by ignasi35** [comment]
Summing up previous comments:

```
.
├── cache
│   ├── play-cache
│   ├── play-caffeine-cache
│   ├── play-ehcache
│   └── play-jcache
├── core
│   ├── play
│   ├── play-integration-test
│   ├── play-microbenchmark
│   ├── play-exceptions
│   ├── play-guice
│   ├── play-logback
│   └── play-streams
├── dev-mode (not dev/)
│   ├── build-link
│   ├── play-docs
│   ├── play-docs-sbt-plugin
│   ├── routes-compiler
│   ├── run-support
│   └── sbt-plugin
├── persistence
│   ├── play-jdbc-evolutions
│   ├── play-java-jdbc
│   ├── play-java-jpa
│   ├── play-jdbc
│   └── play-jdbc-api
├── testkit
│   ├── play-specs2
│   └── play-test
├── transport
│   ├── client
│   │   ├── play-ahc-ws
│   │   └── play-ws
│   └── server
│       ├── play-akka-http-server
│       ├── play-akka-http2-support
│       ├── play-netty-server
│       └── play-server
└── web
    ├── play-filters-helpers
    ├── play-java
    ├── play-java-forms
    ├── play-joda-forms
    └── play-openid
```

**Comment by marcospereira** [comment]
It looks great to me, @ignasi35. Thanks for compiling all the comments here. One final observation is that `play-java` belongs in `core`.

**Comment by dwijnand** [comment]
This will subsume #8109 too.

**Comment by dwijnand** [comment]
So after preparing by experimenting with the formatting setup in another repo, I've actually got cold feet on doing _both_ reformat _and_ the unnest in one massive PR.

Because I fear it might take time for CI validation to pass, and then feedback might delay the PR from merging, which makes it go stale (or freeze the PR queue), then there's potential for a bikeshedding session to break out.  There's also the impact on other PRs, and I'm not sure which order to execute the commits in the PR and how PRs could recover from it being merged (cherry-picking, rebase/merge --strategy ours, etc, etc).

So after confering with @renatocaval my plan is to:
1. unnest in one PR
2. reformat in a follow up PR

**Comment by dwijnand** [comment]
Entirely completed:
* unnest master: https://github.com/playframework/playframework/pull/9023
* unnest 2.7.x: https://github.com/playframework/playframework/pull/9027
* unnest 2.6.x: https://github.com/playframework/playframework/pull/9029
* reformat master: https://github.com/playframework/playframework/pull/9026
* reformat 2.7.x: https://github.com/playframework/playframework/pull/9034
* reformat 2.6.x: https://github.com/playframework/playframework/pull/9039
