### ISSUE TITLE
max-age configurable for language-cookie

### ISSUE THREAD

**Issue by Mat2095** [playframework/playframework#9006]
The max-age for the session-cookie can be configured with `play.http.session.maxAge`.
The max-age for the language-cookie however cannot be changed, it is always transient (https://github.com/playframework/playframework/blob/2.7.0/framework/src/play/src/main/scala/play/api/i18n/Messages.scala#L519).
I think it might be a good idea to add the possibility to configure this as well.

**Comment by mkurz** [comment]
@Mat2095 Could you provide a pull request for this?

**Comment by Mat2095** [comment]
@mkurz I guess I can try to. However, I haven't done anything in this project yet, I haven't written a single line of scala yet, and I've just played around with a project that is using play for a few days. So it might take some time for me to get into this. But yes, I'll try.

**Comment by mkurz** [comment]
@Mat2095 Thanks, let me know if you need some help.

**Comment by Mat2095** [comment]
Sorry, I was busy studying for exams. I've implemented it today, though it is untested. For now I'm happy it finally compiles ;)
I hope to be able to test it tomorrow.

**Comment by Mat2095** [comment]
@mkurz CI reports binary-incompatibility. I don't really understand the consequences of that.
Do I have to fix it? Or does it just mean this change won't appear in 2.7.x, but in 2.8.0?

**Comment by mkurz** [comment]
Fixed by #9080
