### ISSUE TITLE
Log4j MatchError in console when terminating with Ctrl + C an application launched with sbt run

### ISSUE THREAD

**Issue by notflorian** [playframework/playframework#9043]
### Play Version (2.5.x / etc)

I encounter this issue with Play 2.7.0 and not with Play 2.6.20.

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Fedora 29

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

### Library Dependencies

Sbt and Log4j2

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Launch the play application with `sbt run`
2. Wait for the message `(Server started, use Enter to stop and go back to the console...)`
3. Stop the application with Ctrl + C

### Actual Behavior

1. Launch the play application with `sbt run`
2. Wait for the message `(Server started, use Enter to stop and go back to the console...)`
3. Stop the application with Ctrl + C
4. I get the following log in the console

```
[info] p.c.s.AkkaHttpServer - Stopping server...
2019-02-19 14:00:57,766 pool-8-thread-4 ERROR No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
[error] scala.MatchError: org.apache.logging.log4j.simple.SimpleLoggerContext@72b026cb (of class org.apache.logging.log4j.simple.SimpleLoggerContext)
[error] 	at sbt.util.LogExchange.logger(LogExchange.scala:28)
[error] 	at sbt.internal.LogManager$.defaultLogger(LogManager.scala:137)
[error] 	at sbt.internal.LogManager$DefaultLogManager.apply(LogManager.scala:104)
[error] 	at sbt.internal.LogManager$.$anonfun$construct$1(LogManager.scala:52)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:178)
[error] 	at sbt.std.TaskStreams.log(Streams.scala:85)
[error] 	at sbt.std.TaskStreams.log$(Streams.scala:85)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:136)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:136)
[error] 	at sbt.Classpaths$.$anonfun$depMap$1(Defaults.scala:2711)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (projectDescriptors) scala.MatchError: org.apache.logging.log4j.simple.SimpleLoggerContext@72b026cb (of class org.apache.logging.log4j.simple.SimpleLoggerContext)
[warn] a.a.CoordinatedShutdown - Task [shutdown-application-dev-mode] failed in phase [service-stop]: Unexpected exception[MatchError: org.apache.logging.log4j.simple.SimpleLoggerContext@72b026cb (of class org.apache.logging.log4j.simple.SimpleLoggerContext)]
```
### Reproducible Test Case

Example of project : https://github.com/KelkooGroup/theGardener/tree/feature/update-play

It looks like a conflict of libraries of log4j2 as the class `sbt.util.LogExchange.logger(LogExchange.scala:28)` try to match a **`org.apache.logging.log4j.core.LoggerContext`** from the lib **`log4j-core`** but the actual variable has the type `org.apache.logging.log4j.simple.SimpleLoggerContext` that extends **`org.apache.logging.log4j.spi.LoggerContext`** from **`log4j-api`**.

Thanks

**Comment by notflorian** [comment]
Update to this issue thanks to the suggestion of @loicdescotte : If I stop the application with Ctrl + D, I don't get this error log in the console.

**Comment by marcospereira** [comment]
I wonder if this is an sbt problem. Did you also update sbt version? If so, could you downgrade to the version you were using before to confirm/deny it is sbt problem?

**Comment by notflorian** [comment]
I tried with sbt 1.1.6 and 1.0.4 and got the same error log in play 2.7.0. 
Then I tried the same sbt versions with play 2.6.21 and didn't got the error log.

Maybe between the 2.6.21 and 2.7.0 a transitive dependency of log4j change from log4-core to log4j-api and that causing a conflict with sbt?

**Comment by stephandischer** [comment]
just want to confirm that I am experiencing the same issues While just playing around with the latest 2.7.0 and 2.6.21 releases I am having this error only in 2.7.0 
I am using sbt 1.2.8

**Comment by mkurz** [comment]
@stephandischer Just FYI, the latest Play release is 2.7.2 (however it wasn't announced yet officially)

**Comment by KyleU** [comment]
Can reproduce on 2.7.2, it dumps that MatchError, and also triggers a recompile/reload of the running play application before it exits

**Comment by Jacke** [comment]
Fixed on 2.7.3

**Comment by neilchaudhuri** [comment]
Reproduced on 2.7.4 FYI

**Comment by aollin** [comment]
Reproduced on 2.8.0 and sbt 1.3.8

**Comment by nicolas-b12** [comment]
Same here, sbt 1.3.13 and Play 2.8.2

**Comment by mkurz** [comment]
I tracked down the core problem of this issue. Here is the fix with explanations what's actually going on: #10661
