### ISSUE TITLE
Increase the version of HikariCP 3.x on Play2.6 as well as Play2.7

### ISSUE THREAD

**Issue by masahitojp** [playframework/playframework#9086]
HikariCP 2.x has a problem.

> HikariCP does not evict (and call connection close) on Query Timeout
https://github.com/brettwooldridge/HikariCP/issues/1308

- We got incident following situations
  - DataBase deadlocked
  - Connection pool timeout (30 seconds) has elapsed. Connection pool makes new connection, but old connection is left as it is due to the above problem
  - Continue DB processing with a new connection, but deadlock again because the table is locked
  - It will repeat from then on, and the number of unmanaged connections will increase

This has been fixed in HikariCP 3.3.1, but it is 2.x that is used in Play 2.6.x 

https://github.com/brettwooldridge/HikariCP/blob/dev/CHANGES
https://github.com/playframework/playframework/blob/2.6.x/project/Dependencies.scala#L66

### Play Version (2.5.x / etc)

2.6.x

**Comment by mkurz** [comment]
Upcoming 2.7.1 will contain latest HikariCP, see #9017

**Comment by masahitojp** [comment]
@mkurz Oh, I see.I look forward to 2.7.1 being released!

By the way, do you plan to make this change(#9017) for 2.6.x?
In the opinion of those who develop services using Play Framework, it is likely that it will take time to test the speed and behavior to upgrade versions.

**Comment by ertra** [comment]
Hello, please will it be added to 2.6 as well?

regards
tomas

**Comment by renatocaval** [comment]
@ertra / @masahitojp, have you tried to update the HikariCP dependency directly on your Play 2.6 project?

That should work without problem unless you are using `play-slick`. In which case you will have an old version of Slick that won't work with recent HikariCP versions because of a deprecated method that got removed in recent versions. 

Apart from that, I see no reason why it wouldn't be enough to simply update the dependency. Please, try it and let us know if you hit any issue.

**Comment by ertra** [comment]
@renatocaval , please how can I do it, I will try it.

**Comment by renatocaval** [comment]
@ertra, you do that by including the HikariCP dependency on your `build.sbt` file like you do for any other dependency you are using.

```scala
libraryDependencies += "com.zaxxer" % "HikariCP" % "3.3.1"
```

**Comment by mkurz** [comment]
Play 2.7 uses latest version of HikariCP. For Play 2.6 you can upgrade manually as described by Renato.
