### ISSUE TITLE
[2.7.0 java] logger.info doesn't work

### ISSUE THREAD

**Issue by Neverminder** [playframework/playframework#9087]
### Expected Behavior

`logger.info("test info")` should output "test info" into the console

### Actual Behavior

It doesn't

### Reproducible Test Case

Create a new blank application:

`sbt new playframework/play-java-seed.g8`

Add logger testing code to the `HomeController` so it looks like this:

```
package controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import play.mvc.*;

public class HomeController extends Controller {

    private final Logger logger = LoggerFactory.getLogger(this.getClass());

    public Result index() {
        logger.info("test info"); //doesn't work
        logger.error("test error"); //works
        return ok(views.html.index.render());
    }

}
```

The logging configuration is default and unchanged.

**Comment by mkurz** [comment]
You need set the log level for the logger you are using. Have a look at your `conf/logback.xml` config.
The default config the `play-java-seed` project comes with is
```xml
...
  <logger name="play" level="INFO" />
  <logger name="application" level="DEBUG" />
...
  <root level="WARN">
    <appender-ref ref="ASYNCFILE" />
    <appender-ref ref="ASYNCSTDOUT" />
  </root>
```
This means by default only `WARN` logs (and therefor also `ERROR`) will be logged.
What you can to is either change `WARN` to `INFO` for your root logger or specify the log level for the `controllers` package or the `HomeController` class to be `INFO`:
```xml
<logger name="controllers" level="INFO" />
// or more specifc, only the HomeController class:
<logger name="controllers.HomeController" level="INFO" />
```
Please read the logback docs: https://logback.qos.ch/documentation.html
