### ISSUE TITLE
bindableOption[A].bind has return type Some[A]

### ISSUE THREAD

**Issue by kryptt** [playframework/playframework#9088]
in QueryStringBindable, the helper function bindableOption returns a queryStringBindable instance who's bind method returns Some[Product with Serializable with scala.util.Either[String,Option[T]]] so it is obvious the type annotation is missing

see: 

https://www.playframework.com/documentation/2.6.x/api/scala/index.html#play.api.mvc.QueryStringBindable$

**Comment by dwijnand** [comment]
Fixed in #9089
