### ISSUE TITLE
Trailing dot ('.') in Host headers confuses CORSFilter

### ISSUE THREAD

**Issue by henricook** [playframework/playframework#9101]
I'm using Play 2.7 as a backend, with a React frontend. This is an issue that occurs when the frontend talks to the backend via CORS

In my Play CORSFilter's allowed hosts I have ['https://www.mywebsite.com'] - this works fine for CORS requests from `https://www.mywebsite.com` (no trailing '.')

It's a little known but valid fact that `https://www.mywebsite.com.` (note the trailing '.') is a valid way of accessing this website.

**Current behaviour:**

Currently if I browse to `https://www.mywebsite.com.` it cannot make CORS requests to my play backend.

**Proposed behaviour:**

The CORS Filter allows hosts that match an allowed host (apart from a trailing '.') to pass

**Suggested solutions:**

This could be achieved by trimming trailing '.'s early in the play logic (probably not ideal) or dealing with trailing '.' in the CORSFilter (probably preferred)

**Comment by gmethvin** [comment]
If you want to make requests with the trailing dot, it should be possible to use `["https://www.mywebsite.com", "https://www.mywebsite.com."]` as the list of origins. The browser considers these to be different origins from a CORS perspective, so it seems reasonable for Play to consider them different as well.

**Comment by henricook** [comment]
I think this is an interesting point @gmethvin 

My personal pain is that nginx ignores the "." in `server_name` directives so it's "impossible" to stop serving my frontend at `www.myfrontend.com.` as well as `www.myfrontend.com`

Thinking on it, I do think Nginx are doing the right thing and server backends like Play should mimic the behaviour (`www.myfrontend.com` == `www.myfrontend.com.`). I  think it's correct of the browser to tell us exactly what the origin is, but we should treat them as equivalent when they are equivalent

**Comment by henricook** [comment]
Admittedly i'm only asking this question because one day a user went to www.myfrontend.com. accidentally and the frontend loaded but didn't work (as CORS to my backend was failing) - I guess a user typing a '.' at the end of the URL accidentally is rare, but possible

**Comment by gmethvin** [comment]
I don't think this is a bug because `https://www.mywebsite.com` and `https://www.mywebsite.com.` are considered different origins, and `allowedOrigins` is simply a list of origins. So the "workaround" I suggested is in fact the correct way to allow origins with a trailing dot. If anything it's a feature request, but I don't think the need is strong enough to warrant the additional complexity.

A better solution for you is to redirect the URL, which is what a lot of servers do. In nginx you can redirect URLs with a trailing dot using:

```
if ($http_host ~ "\.$"){
  rewrite ^(.*) $scheme://$host$1 permanent;
}
```

**Comment by henricook** [comment]
I can't believe I hadn't found that, thanks. In that case I agree with you! Thanks for reading and spending the time on this @gmethvin
