### ISSUE TITLE
ActorSystemProvider should accept a List of Setup

### ISSUE THREAD

**Issue by renatocaval** [playframework/playframework#9106]
https://github.com/playframework/playframework/blob/master/core/play/src/main/scala/play/api/libs/concurrent/Akka.scala#L151

`ActorSystemProvider.start` accept only one setup. This used by Lagom to setup the serializers. It will be very useful to overload that method with one that accepts a `List[Setup]`. As such we can add health-check setups.

**Comment by brownbonnie** [comment]
I've made this change but when I go to push it I get the following error message:

"ERROR: Permission to playframework/playframework.git denied to brownbonnie.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

**Comment by mkurz** [comment]
@brownbonnie You need to push to your fork, not to the upstream repo. You can run `git remote -v` to see the available remote repos.

**Comment by brownbonnie** [comment]
Thanks, 

I've opened a PR on my fork

https://github.com/playframework/playframework/pull/9113/

**Comment by brownbonnie** [comment]
There's some issues with that PR so I'm going to amend them and open a new PR

**Comment by marcospereira** [comment]
Fixed by #9237.
