### ISSUE TITLE
Inconsistency between code and comment of method Result#as(String)

### ISSUE THREAD

**Issue by porchy13** [playframework/playframework#9176]
### Play Version (2.5.x / etc)

2.6.x, 2.7.0

### API (Scala / Java / Neither / Both)

Both

### Expected Behavior

According to the JavaDoc of Result#as(String), it should _return a copy of the result with a different Content-Type header._ (Java version). 

Two alternatives :
* it is expected that the ```session``` and the ```flash``` objects are copied from the original Result instance. That means the constructor ```Result(ResponseHeader, HttpEntity, Session, Flash, List<Cookie>)``` should be called.
* the comment of the method should be rewritten by explicitly declaring that only the headers and the body are copied.

### Actual Behavior

The ```session``` and the ```flash``` objects are dropped because the constructor ```Result(ResponseHeader, HttpEntity)``` is called.

Kind regards,
porchy13

**Comment by marcospereira** [comment]
Yeah, there is a bug in`Result.as`. Better to fix it instead of changing the docs.

See #9177.

**Comment by porchy13** [comment]
Many thanks for the quick fix !!

**Comment by mkurz** [comment]
Fixed by #9177
