### ISSUE TITLE
Documentation claims CSRF check only required for request with Cookie

### ISSUE THREAD

**Issue by nerdydrew** [playframework/playframework#9187]
### Play Version (2.5.x / etc)

2.7.0

### API (Scala / Java / Neither / Both)

Tested in Java, but I assume it applies to both.

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS Mojave (10.14.4)

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

### Library Dependencies

N/A

### Expected Behavior

[According to the CSRF documentation](https://www.playframework.com/documentation/2.7.x/JavaCsrf):

> To allow simple protection for non browser requests, Play only checks requests with cookies in the header.

Because of this, I would expect non-browser requests to bypass the CSRF filter, even if they do use `POST` / `PUT` / etc. and the `Authorization` header.

1. Have a Play application with a `POST` route.
2. Use a non-browser program to make a `POST` request with an `Authorization` header but no cookies.
    * For instance: `curl -I -X POST --header "Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l" http://localhost:9000/post`
3. Expected result: 200 status code (or whatever the route is supposed to do)

### Actual Behavior

1. Instead of step 3 above, I get 403 Forbidden.
2. Play logs: `[warn] p.filters.CSRF - [CSRF] Check failed because no token found in headers for /post`

I have tested this with both curl and my own software.

### Reproducible Test Case

[ I forked the Java starter example](https://github.com/nerdydrew/play-java-starter-example/tree/csrf-example), but I believe this will happen for any project. Here's a curl example that reproduces the bug against my fork:

```curl -I -X POST --header "Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l" http://localhost:9000/post```

**Comment by gmethvin** [comment]
The current default behavior is correct from a CSRF protection point of view. Just like cookies, browsers will automatically send the basic authorization header with the request once the user has authenticated, so a request using basic auth is still vulnerable to CSRF.

As you pointed out, the documentation does say in one place "Play only checks requests with cookies in the header", though in other places it mentions it also checks the `Authorization` header by default. In fact, this behavior is also [configurable](https://github.com/playframework/playframework/blob/ad02105/web/play-filters-helpers/src/main/resources/reference.conf#L67) (though not all configurations will be secure).

So it seems like the action item here is to update the documentation to clarify the actual behavior, and perhaps also mention the `protectHeaders` configuration for customizing this. So I'm marking this as a documentation bug.

**Comment by fusuiyi123** [comment]
Hey @gmethvin I added a pr for this issue:)
