### ISSUE TITLE
RequestHeader.path being decoded and inconsistent with RequestHeader.uri when using AkkaHttpServer

### ISSUE THREAD

**Issue by FranklinYinanDing** [playframework/playframework#9190]
### Play Version (2.5.x / etc)

2.6.x (issue also exists for master - need forward-port)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. `RequestHeader.uri` matches `RequestHeader.path`
2. `RequestHeader.path` should be consistent between NettyServer and AkkaHttpServer

### Actual Behavior

1. When a request coming in with an encoded URI, for example, `/foo%3Abar`, `RequestHeader.uri` is the same, and consistent between two server types. But for AkkaHttpServer, `RequestHeader.path` is decoded as `/foo:bar`.

The similar inconsistent issue for `RequestHeader.uri` was discussed and fixed here #5780, however, the same issue for path wasn't covered back then.

See PR #9191 for both fix and test case.

**Comment by gabrielgiussi** [comment]
Hi, I wonder why was decided to make AkkaHttpServer return the encoded path instead of making NettyServer return the decoded one.
Also, if I want the decoded path the best way to get it will be with `Uri.Path(request.path).toString`, where request is a `RequestHeader`?
Thanks.

**Comment by mkurz** [comment]
Fixed by #9191 already (Looks like GitHub forgot to close this one here after the pull request got merged)
