### ISSUE TITLE
STRICT TRANSPORT SECURITY not sent for X-Forwarded-Proto

### ISSUE THREAD

**Issue by SattaiLanfear** [playframework/playframework#9208]
### Play Version (2.5.x / etc)

2.7

### API (Scala / Java / Neither / Both)

Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

N/A

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

N/A

### Library Dependencies

N/A

### Expected Behavior

1. Deploy to Prod behind a load balancer with:
    * `play.filters.https.RedirectHttpsFilter` enabled
    * `play.filters.https.xForwardedProtoEnabled=true`
    * Defaults otherwise
2.  Attempt to connect on HTTP
3. Get Redirected to HTTPS equivalent
4. HTTPS equivalent of initial request issues `Strict-Transport-Security` header.

### Actual Behavior

1. As Expected
2. As Expected
3. As Expected
4. No Strict-Transport-Security header is found
    * System Logs: `[debug] p.f.h.RedirectHttpsFilter - Not redirecting to HTTPS because play.filters.https.xForwardedProtoEnabled flag is set and X-Forwarded-Proto is not present.`  
      (*this seems like a poorly worded log, but it is debug level*)

Looking at the source, it appears that the header is only attached if `req.secure` is true, and not if the forwarded proto header signals it was HTTPS.

Specifically here (RedirectHttpsFilter.scala):
```scala
  override def apply(next: EssentialAction): EssentialAction = EssentialAction { req =>
    import play.api.libs.streams.Accumulator
    import play.core.Execution.Implicits.trampoline
    if (isExcluded(req)) {
      logger.debug(s"Not redirecting to HTTPS because the path is included in exclude paths")
      next(req)
    } else if (req.secure) {
      next(req).map(_.withHeaders(stsHeaders: _*))
    } else {
      val xForwarded = forwardedProto(req)
      if (redirectEnabled && xForwarded) {
        Accumulator.done(Results.Redirect(createHttpsRedirectUrl(req), redirectStatusCode))
      } else {
        if (xForwarded) {
          logger.debug(s"Not redirecting to HTTPS because $redirectEnabledPath flag is not set.")
        } else {
          logger.debug(s"Not redirecting to HTTPS because $forwardedProtoEnabled flag is set and " +
            "X-Forwarded-Proto is not present.")
        }
        next(req)
      }
    }
  }
```

Seen above `if(req.secure)` causes `withHeaders` to be added, but a forwarded request just invokes `next(req)`.

FWIW My particular test-bed is Heroku

**Comment by mkurz** [comment]
Thanks for reporting @SattaiLanfear. Fix is here: #9659
