### ISSUE TITLE
Improve Akka HTTP server shutdown / use Graceful Shutdown 

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9216]
The current implementation only `unbind`'s the port but it doesn't use the Graceful Shutdown provided via `terminate`:

> A better and more graceful solution to terminate an Akka HTTP server is to use the ServerBinding.terminate(FiniteDuration) method, which not only performs the unbinding, but also handles replying to new incoming requests with (configurable) "terminating" HTTP responses. It also allows setting a deadline after which any connections that are still alive will be shut down forcefully.

Finally, an explicit shutdown of all connection pools should be added too.

See https://github.com/akka/akka-http/issues/1210#issuecomment-484344006 for details.

**Comment by marcospereira** [comment]
Duplicated of #8453?

**Comment by ignasi35** [comment]
> Duplicated of #8453?

It is. Closing
