### ISSUE TITLE
[Feature Suggestion] Support for X-HTTP-Method-Override header

### ISSUE THREAD

**Issue by slisaasquatch** [playframework/playframework#9235]
### Play Version (2.5.x / etc)
2.7.1

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Oracle 1.8.0_181

### Library Dependencies
N/A

### Expected Behavior
When the client sends a `POST` request with the `X-HTTP-Method-Override` header being `PATCH`, then the request should be treated as a `PATCH` request. This should probably be an opt-in feature.

### Actual Behavior
N/A

### Reproducible Test Case
N/A

**Comment by marcospereira** [comment]
Hey @slisaasquatch,

I'm pretty sure it is possible to do that by creating your [custom request handler](https://www.playframework.com/documentation/2.7.x/ScalaHttpRequestHandlers), where you rewrite the request header method if `X-HTTP-Method-Override` is present.

I'm not opposed to having this out-of-the-box in Play, but keep it is not a priority for us. But if you want to submit a pull request, it will be very welcomed.

**Comment by slisaasquatch** [comment]
Oh OK. I was looking at adding a custom Filter, but looks like a request handler is what I want. I'll close the ticket.
