### ISSUE TITLE
[Feature Suggestion] Request Content-Encoding support

### ISSUE THREAD

**Issue by slisaasquatch** [playframework/playframework#9243]
### Play Version (2.5.x / etc)
2.7.1

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Oracle 1.8.0_181

### Library Dependencies
N/A

### Expected Behavior
The client should have the option of sending compressed request bodies. For example, the client can send gzipped data with `Content-Encoding` header being `gzip`. I know the `Content-Encoding` header is meant for responses, but this is not an uncommon thing to do. One example is expressjs body-parser, which supports this feature. Here's a link to their code: https://github.com/expressjs/body-parser/blob/e6ccf98015fece0851c0c673fc2776c30ad79e5d/lib/read.js

This should probably be an opt-in feature.

### Actual Behavior
N/A

### Reproducible Test Case
N/A

**Comment by TimMoore** [comment]
I think Play already supports this. Did you try it and it didn't work?

See for example:
https://github.com/playframework/playframework/blob/ab6697f494a000ba8d19768e9d04eed3bb8cdbf7/core/play-integration-test/src/it/scala/play/it/http/RequestBodyHandlingSpec.scala#L63-L89

**Comment by slisaasquatch** [comment]
Hi I did try it and it didn't work.
Here's my forked sample project with a test I wrote:
https://github.com/slisaasquatch/play-java-hello-world-tutorial/blob/issue-20190506/test/controllers/HomeControllerTest.java

**Comment by gmethvin** [comment]
@slisaasquatch The reason your test doesn't work is because the controller action expects a parsed version of the body. Your test is really more like a unit test, just testing your action code handling the already-parsed body provided by Play. If you test with an actual HTTP request to the server you'll see the body gets decoded from gzip just like it does in the integration test linked above.
