### ISSUE TITLE
Trouble overriding limits, getting EntityStreamException: Request too large

### ISSUE THREAD

**Issue by martinb3** [playframework/playframework#9249]
Hi there -- I'm seeing exceptions thrown from a project that depends on Play, from the underlying Akka Http library, and I'm unable to override it using your documentation. Happy to make a specific reproducible test case if needed.

### Play Version (2.5.x / etc)

```
libraryDependencies += "com.typesafe" % "config" % "1.3.3"
libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.5.21"
libraryDependencies += "com.typesafe.akka" %% "akka-http-core" % "10.1.7"
libraryDependencies += "com.typesafe.play" %% "play-json" % "2.7.1"
libraryDependencies += "org.json4s" %% "json4s-native" % "3.5.1"
libraryDependencies += "org.slf4j" % "slf4j-simple" % "1.6.4"
libraryDependencies += "com.github.slack-scala-client" %% "slack-scala-client" % "0.2.6"
libraryDependencies += "org.scalaj" % "scalaj-http_2.12" % "2.3.0"
libraryDependencies += "org.apache.commons" % "commons-lang3" % "3.0.1"
```

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

OS X (18.5.0 Darwin Kernel Version 18.5.0)

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

### Library Dependencies

Included in dependencies above, also using:
```
libraryDependencies += "com.github.slack-scala-client" %% "slack-scala-client" % "0.2.6"
```

Between Play and my code.

### Expected Behavior

Setting the following JVM properties should allow HTTP client inside Actors to receive large messages:
```
-Dakka.http.parsing.max-content-length=1024M
-Dakka.http.client.parsing.max-content-length=1024M
-Dakka.http.server.parsing.max-content-length=infinite
-Dplay.server.akka.http.parsing.max-content-length=infinite
-Dplay.server.akka.http.client.parsing.max-content-length=infinite
-Dplay.server.akka.http.server.parsing.max-content-length=infinite
-Dplay.client.akka.http.parsing.max-content-length=infinite
-Dplay.client.akka.http.client.parsing.max-content-length=infinite
-Dplay.client.akka.http.server.parsing.max-content-length=infinite
```
(I've tried variations of specific values as well as infiniite.)

### Actual Behavior

```
[error] Exception in thread "main" akka.http.scaladsl.model.EntityStreamException: Request too large: Request was longer than the maximum of 8388608
[error] 	at akka.http.impl.util.ToStrict$$anon$1$$anon$3.onPush(package.scala:130)
[error] 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:515)
[error] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:407)
[error] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
[error] 	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:474)
[error] 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
[error] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:730)
[error] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:745)
[error] 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
[error] 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
[error] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
[error] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
[error] 	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
[error] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
[error] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by marcospereira** [comment]
Hey @martinb3,

> Happy to make a specific reproducible test case if needed. It would also be useful to know which kind of request you are doing.

That would be helpful, thanks!

> Setting the following JVM properties should allow HTTP client inside Actors

What do you mean by HTTP client inside actors? Which HTTP client are you using? Also, which version of Play are you using?

**Comment by martinb3** [comment]
> > Setting the following JVM properties should allow HTTP client inside Actors
>
> What do you mean by HTTP client inside actors? Which HTTP client are you using? Also, which version of Play are you using?

I'm referring to the stack trace above, where `akka.actor.Actor` calls classes inside the akka.stream package, which then calls classes inside akka.http. I'm not directly choosing/using any HTTP client -- it seems that Play depends on one (either directly or indirectly), doesn't it?

**Comment by martinb3** [comment]
Hi there -- I figured this out. It was actually a timeout for a longer HTTP request, showing up as a size issue. Once I adjusted the timeouts for Akka Http, this went away.

**Comment by timlee0119** [comment]
@martinb3 Hi, I have an exact same problem, I'm sending HTTP request to other API and even if I set `akka.http.parsing.max-content-length: infinite`, `akka.http.server.parsing.max-content-length: infinite`, `akka.http.client.parsing.max-content-length: infinite`, I still got this error:
```
java.util.concurrent.ExecutionException: akka.http.scaladsl.model.EntityStreamException: Request too large: Request was longer than the maximum of 8388608
```
Can you tell me what timeout property did you set? Thank you so much

**Comment by mkurz** [comment]
@timlee0119 which version of Play are you using?
For 2.7.x try [this config](https://github.com/playframework/playframework/blob/2.7.9/transport/server/play-akka-http-server/src/main/resources/reference.conf#L53):
```
play.server.akka.max-content-length = infinite
```
For 2.8.x try [this config](https://github.com/playframework/playframework/blob/2.8.8/transport/server/play-server/src/main/resources/reference.conf#L120):
```
play.server.max-content-length = infinite
```
