### ISSUE TITLE
Cross-build to Scala 2.13.0

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#9260]
This is the tracking issue for cross-building Play to Scala 2.13.0.

Currently blocked on the release of Scala 2.13.0.

**Comment by mkurz** [comment]
Is there something holding us back to also cross-build the 2.7.x branch to Scala 2.13?

**Comment by dwijnand** [comment]
Nope, we're already cross-building to 2.13.0-M5 so, barring anything extreme that impacts the stability of the 2.11/2.12 releases of Play 2.7.x, we should be able to update to 2.13.0 and back-publish.

**Comment by notflorian** [comment]
Scala 2.13 is out https://github.com/scala/scala/releases/tag/v2.13.0 :tada:

**Comment by domdorn** [comment]
Is there something blocking for 2.13.0?
I've seen that we've published for 2.13.0-M5 and RC2 before.

**Comment by mkurz** [comment]
@domdorn see #9399

**Comment by renatocaval** [comment]
Fixed in #9399
