### ISSUE TITLE
Play does not run sbt 1.3.0-M5

### ISSUE THREAD

**Issue by jtjeferreira** [playframework/playframework#9368]
### Play Version (2.5.x / etc)
2.6.20

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Arch Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Paste the output from `java -version` at the command line.

### Expected Behavior

1. sbt -sbt-version 1.3.0-M5
2. run
3. should start the play server in dev mode

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

Be descriptive: "it doesn't work" does not describe what the behavior actually is -- instead, say "the page renders a 500 error code with no body content."  Copy and paste logs, and include any URLs.  Turn on internal Play logging with `<logger name="play" value="TRACE"/>` if there is no log output.  

1. sbt -sbt-version 1.3.0-M5
2. run
3. the following exception is throw

```scala
[error] java.lang.NumberFormatException: For input string: "0-M5"
[error]         at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[error]         at java.lang.Integer.parseInt(Integer.java:580)
[error]         at java.lang.Integer.parseInt(Integer.java:615)
[error]         at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
[error]         at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
[error]         at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
[error]         at play.sbt.run.PlayRunCompat.$anonfun$watchContinuously$7(PlayRunCompat.scala:59)
[error]         at play.sbt.run.PlayRunCompat.$anonfun$watchContinuously$7$adapted(PlayRunCompat.scala:59)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error]         at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error]         at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error]         at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error]         at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
[error]         at play.sbt.run.PlayRunCompat.watchContinuously(PlayRunCompat.scala:59)
[error]         at play.sbt.run.PlayRunCompat.watchContinuously$(PlayRunCompat.scala:35)
[error]         at play.sbt.run.PlayRun$.watchContinuously(PlayRun.scala:31)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:108)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:65)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
```

**Comment by jtjeferreira** [comment]
There is an workaround which is to `set sbtVersion := "1.3.0"` in sbt shell.

**Comment by jtjeferreira** [comment]
The problematic line https://github.com/playframework/playframework/blob/ab6697f494a000ba8d19768e9d04eed3bb8cdbf7/dev-mode/sbt-plugin/src/main/scala-sbt-1.0/play/sbt/run/PlayRunCompat.scala#L63.

Is there some better way to parse a version string? Maybe sbt provides something?

**Comment by marcospereira** [comment]
Hey @jtjeferreira,

Yeah, there is a problem there. Thanks for taking the time to test and report the problem.

> Is there some better way to parse a version string? Maybe sbt provides something?

Not sure if `sbt.CrossVersion` has some helper to parse the version getting epoch, minor and patch info, but if not, we can correct the parsing.

**Comment by marcospereira** [comment]
@jtjeferreira see #9369.
