### ISSUE TITLE
Cannot load grand-child routing PlayScala@2.7.2

### ISSUE THREAD

**Issue by sizer** [playframework/playframework#9382]
### Play Version

PlayScala@2.7.2

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

```
$ uname -a
Linux geb 4.15.0-1039-oem #44-Ubuntu SMP Sun May 19 07:35:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
s
```

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-linux64) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-linux64) (build 25.212-b04, mixed mode)
```

### Expected Behavior

1. make your sbt project as 'root'
2. add sub-project as 'buildA'
3. add sub-project as 'appA'
4. buildA include a appA.routes
5. -> Yay, you can create some builds in one root project !!

### Actual Behavior

My child-project (buildA) can NOT load grand-chid-project(appA)' s routing.

```
$ tree -L 2
.
├── build.sbt
├── build-app
│   ├── app
│   ├── build.sbt
│   ├── conf
│   │   ├── application.conf
│   │   ├── logback.xml
│   │   └── routes
├── core
│   ├── app
│   ├── build.sbt
│   ├── conf
│   │   └── core.routes
│   ├── src
├── project
     ├── plugins.sbt
```

`build.sbt`
```
lazy val buildApp = project.in(file("build-app"))
lazy val root = project.in(file("."))
```

`build-app/build.sbt`
```
lazy val core = project.in(file("../core")).enablePlugins(PlayScala)
lazy val buildApp = (project in file("."))
  .enablePlugins(PlayScala)
  .dependsOn(core)
```

`build-app/conf/routes`
```
GET     /                           controllers.app.HomeController.index
->  /core core.Routes
```

`core/conf/core.routes`
```
GET     /                           controllers.core.HomeController.index
```

```
$ sbt "project buildApp" compile
[error] /home/sizer/go/src/github.com/sizer/hello-sbt-multiproject/build-app/conf/routes:3:1: not found: value core
[error] ->  /core core.Routes
```

Can NOT load core.routes :sob: 
Am I Wrong or Is it correct behaviour??

my project is below.

https://github.com/sizer/hello-sbt-multiproject/tree/playframework_failedExample

**Comment by felipehaack** [comment]
Hi @sizer, I believe this issue isn't related to Play, but focusing more on the way to configure your SBT project. Try to enable the Play plugin in the subproject instead of in the `buildApp` sbt file, or move out the `build sbt` code to the root level.
``` 
lazy val core = project.in(file("core"))
  .enablePlugins(PlayScala)

lazy val buildApp = project.in(file("build-app"))
  .enablePlugins(PlayScala)
  .dependsOn(core)
```

```
`$ sbt "project buildApp" "run"`

**Comment by ignasi35** [comment]
Hi @sizer, did @felipehaack's solution work? Can we close this issue?

**Comment by sizer** [comment]
@felipehaack yay! you solved my problem 👍 thx.
