### ISSUE TITLE
Support querystring parameters for Java's redirect method

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#9394]
The Scala API supports this a long time already:
https://github.com/playframework/playframework/blob/1af85d5ea8b1bc841079c60fdea6550ccddf0ef6/core/play/src/main/scala/play/api/mvc/Results.scala#L783-L803

We just need to overload the Java methods to be able to pass query params as well:
https://github.com/playframework/playframework/blob/1af85d5ea8b1bc841079c60fdea6550ccddf0ef6/core/play/src/main/java/play/mvc/Results.java#L4530-L4548

**Comment by felipehaack** [comment]
Hi @ignasi35, would be possible to assign this ticket to me? I will take care of the changes.

**Comment by gurkankaymak** [comment]
Hi i created a pull request #9401 for this issue

**Comment by ignasi35** [comment]
> Hi @ignasi35, would be possible to assign this ticket to me? I will take care of the changes.

Issues and PRs can only be assigned to maintainers. :-(
