### ISSUE TITLE
UnEncoded key on key-value serialisation

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9403]
Searching for `URLEncoder.encode` we find a few places converting `Map[String,String]` into `key1=val1&key2=val2` for queryString representation of body as forlUrlEncoded.

Some of these serialisers fail to use `URLEncoder.encode` for the key. E.g. https://github.com/playframework/playframework/blob/282cb7905f3b4a1b4dc97b2fbc8e8eca9224158b/core/play/src/main/scala/play/api/http/Writeable.scala#L99

Related: https://github.com/playframework/playframework/pull/9389 and https://github.com/playframework/playframework/pull/9401

**Comment by brbrown25** [comment]
@ignasi35 I'd be interested in working on this issue if it's up for grabs.

**Comment by renatocaval** [comment]
@brbrown25 Yep, you can take it. Thanks
