### ISSUE TITLE
How to Use CSP Filter in Play 2.7

### ISSUE THREAD

**Issue by co-category** [playframework/playframework#9410]
Hello,

I was wondering if I could get some assistance with this issue I am facing:

https://stackoverflow.com/questions/56670344/correct-way-to-use-csp-filter-in-play-2-7

**Comment by ihostage** [comment]
@co-category Please, use [forum](https://discuss.lightbend.com/c/play) for questions 😉

**Comment by ignasi35** [comment]
Like @ihostage said, this seems more appropriate for [discuss](https://discuss.lightbend.com/c/play) or SO. I'll close.
