### ISSUE TITLE
Review MiMa settings for 2.8.0

### ISSUE THREAD

**Issue by renatocaval** [playframework/playframework#9414]
We have a huge list of exclusions in master. 
https://github.com/playframework/playframework/blob/master/project/BuildSettings.scala#L218

For 2.8.0, we can consider a clean-up.

**Comment by dwijnand** [comment]
What do you mean by a clean-up?

It's there just as a way to assist PR review.

**Comment by renatocaval** [comment]
I mean remove everything that is not relevant anymore. Is that all checking agains 2.7.x?

**Comment by dwijnand** [comment]
Yep.

I think Marcos prefers how it is, so he can use it as a reference for everything that's changed at the binary level compared to 2.7.

**Comment by renatocaval** [comment]
In that case, I'm closing this. I thought it needed some clean-up. Good if it's ony 2.7.x. Impressed anyway by the number of deprecations.

**Comment by dwijnand** [comment]
We deleted lots of deprecated API.
