### ISSUE TITLE
Break play - omnidoc circular dependency

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9438]
When releasing Play a.b.c the following steps are required:

1. release upstream projects
2. release play a.b.c
3. release satellite projects
4. release omnidoc a.b.c

After running `2.` above, there are issue running/building play until `4.` has completed. The cause is related to this code:

https://github.com/playframework/playframework/blob/d9965b5612e6043c53827a499791dccf81a5e057/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L69-L73

which adds a dependency to `play-omnidoc` when the version is stable (not `-SNAPSHOT`). 

It'd be great if `2.` produced fully functional artifact/state instead of causing a short period of instability causing the release to stretch unnecessarily.

**Comment by ignasi35** [comment]
I am not familiar with the use cases where `play-omnidoc` as a dependency is used. Put another way: why is there a dependency to `"com.typesafe.play" %% "play-omnidoc" ...` at all?

My other doubt is that `"com.typesafe.play" %% "play-omnidoc" ...` seems to only be used in dev mode _and_ when explicitly enabling the `PlayDocsPlugin` plugin. with `PlayDocsPlugin` users can access `localhost:9000/@documentation` to browse a local copy of the documentation (ref and API) on playframework.com.

**Comment by ignasi35** [comment]
It seems to me like [the `playOmnidoc` setting](https://github.com/playframework/playframework/blob/d9965b5612e6043c53827a499791dccf81a5e057/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L69-L73) should be moved from `sbt-plugin` to `play-docs-sbt-plugin` and then `play-docs-sbt-plugin` could be released separately.

**Comment by renatocaval** [comment]
As discussed on call, we have the following options: 

1. remove the offline documentation. The burden to maintain offline documentation is too heavy. 
2. if option 1 is too intrusive, we could instead have the omnidoc integrated back into Play. We release Play and we get the docs. The downstream projects (play-slick, play-ebean) won't have offline documentation in that case. 

I don't know if I understand the proposal to move it to `play-docs-sbt-plugin` and release it separately. Are we just moving the problem to another place instead?
