### ISSUE TITLE
Play Framework 2.1 [Java] Ebean @Encrypted annotation not working

### ISSUE THREAD

**Issue by mwhawkins** [playframework/playframework#944]
When trying to use the Ebean @Encrypted annotation on a field for a database model, a RuntimeException is thrown.  The documentation makes it seem simple enough, but I'm getting a very vague runtime error in the browser for the following sample standard code using the built-in H2 in-memory database:

```
package models; 

import java.util.*; 
import javax.persistence.*; 
import play.db.ebean.*; 
import play.db.ebean.Model.Finder; 
import play.data.format.*; 
import play.data.validation.*; 
import com.avaje.ebean.*; 
import com.avaje.ebean.annotation.*; 

@Entity  
public class Test extends Model { 

 @Id 
 public Long id; 

 @Encrypted 
 public String identifier;

}
```

Produces the following runtime error related to the @Encrypted annotation:

```
Unexpected exception
RuntimeException: Error reading annotations for models.Test
No source available, here is the exception stack trace:
->java.lang.RuntimeException: Error reading annotations for models.Test
     com.avaje.ebeaninternal.server.deploy.parse.ReadAnnotations.readInitial(ReadAnnotations.java:26)
     com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createDeployBeanInfo(BeanDescriptorManager.java:1026)
     com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentInitial(BeanDescriptorManager.java:533)
     com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:250)
     com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:124)
     com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:210)
     com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:64)
     com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:59)
     play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79)
     play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:63)
     play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:63)
     scala.collection.immutable.List.foreach(List.scala:309)
     play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:63)
     play.api.Play$$anonfun$start$1.apply(Play.scala:63)
     play.api.Play$$anonfun$start$1.apply(Play.scala:63)
     play.utils.Threads$.withContextClassLoader(Threads.scala:18)
     play.api.Play$.start(Play.scala:62)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$1.apply(ApplicationProvider.scala:133)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$1.apply(ApplicationProvider.scala:106)
     scala.Option.map(Option.scala:145)
     play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:106)
     play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104)
     scala.util.Either$RightProjection.flatMap(Either.scala:523)
     play.core.ReloadableApplication.get(ApplicationProvider.scala:104)
     play.core.server.Server$class.sendHandler$1(Server.scala:56)
     play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:88)
     play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:87)
     scala.util.Either$RightProjection.flatMap(Either.scala:523)
     play.core.server.Server$class.getHandlerFor(Server.scala:87)
     play.core.server.NettyServer.getHandlerFor(NettyServer.scala:34)
     play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:103)
     org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:75)
     org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:565)
     org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:793)
     org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:104)
     org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:75)
     org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:565)
     org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:793)
     org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
     org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:455)
     org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:538)
     org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:437)
     org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:75)
     org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:565)
     org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
     org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
     org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
     org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:84)
     org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:472)
     org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:333)
     org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
     org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
     org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     java.lang.Thread.run(Thread.java:722)
```

When the @Encrypted annotation is commented out, the issue does not appear and the model functions normally.

I have the encryptionKeyManager settings configured properly in the config (ebean.encryptKeyManager="com.avaje.tests.basic.encrypt.BasicEncyptKeyManager").

As I have followed all of the instructions and spent the better part of two weeks searching for answers, I've only found that I am not alone in this problem so I am reporting it as an issue in hopes it can be resolved.  Thank you.

**Comment by nazeerbashavadapalli** [comment]
Hi, I got similar type of exception 


play.api.UnexpectedException: Unexpected exception[RuntimeException: Error reading annotations for models.device.UserDevice]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:166) ~[play_2.11-2.3.7.jar:2.3.7]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.7.jar:2.3.7]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.7.jar:2.3.7]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.7.jar:2.3.7]
Caused by: java.lang.RuntimeException: Error reading annotations for models.device.UserDevice
	at com.avaje.ebeaninternal.server.deploy.parse.ReadAnnotations.readInitial(ReadAnnotations.java:26) ~[avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createDeployBeanInfo(BeanDescriptorManager.java:1020) ~[avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentInitial(BeanDescriptorManager.java:495) ~[avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:233) ~[avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) ~[avaje-ebeanorm-3.3.4.jar:na]
Caused by: javax.persistence.PersistenceException: Generated update Timestamp not supported on org.joda.time.LocalDateTime
	at com.avaje.ebeaninternal.server.deploy.generatedproperty.UpdateTimestampFactory.createUpdateTimestamp(UpdateTimestampFactory.java:44) ~[avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.deploy.generatedproperty.UpdateTimestampFactory.setUpdateTimestamp(UpdateTimestampFactory.java:22) ~[avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.deploy.generatedproperty.GeneratedPropertyFactory.setUpdateTimestamp(GeneratedPropertyFactory.java:62) ~[avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.deploy.generatedproperty.GeneratedPropertyFactory.setVersion(GeneratedPropertyFactory.java:46) ~[avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.deploy.parse.AnnotationFields.readField(AnnotationFields.java:169) ~[avaje-ebeanorm-3.3.4.jar:na]


My model class is annoted with 

@Entity
@IdClass(UserDevice.CompositeId.class)
public class UserDevice extends Model implements Serializable {

    @Id
    private long userId; 
    @Id
    private int userDeviceId; 

    private String deviceName; 
    private Integer productId;
    private String serialNumber; 
    private String btMacAddress;
    private String firmwareVersion;
    private String hardwareVersion;
    @Version
    private LocalDateTime manufactureDate;


with out this @Version annotation working fine.
