### ISSUE TITLE
Play not working well with the docker plugin in sbt-native-packager 

### ISSUE THREAD

**Issue by ghw59** [playframework/playframework#9487]
### Play Version (2.5.x / etc)
2.7.0

### API (Scala / Java / Neither / Both)
Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.14 

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Generate a project: **sbt new playframework/play-scala-seed.g8**
2. Build docker image: **sbt docker:publishLocal**
3. Run: **docker run -d -p 9000:9000 webapp:1.0-SNAPSHOT**

### Actual Behavior

Not running, log shows the error: 
```
Oops, cannot start the server.
java.nio.file.NoSuchFileException: /opt/docker/RUNNING_PID
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at play.core.server.ProdServerStart$.createPidFile(ProdServerStart.scala:165)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:31)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```
In the docker container, /opt/docker is not writable, and the process try to create a RUNNING_PID file, which cause the problem. 

### Suggestion

RUNNING_PID  can be configured with pidfile.path, the default value is set in reference.conf.
```
    # The path to the process id file created by the server when it runs.
    # If set to "/dev/null" then no pid file will be created.
    pidfile.path = ${play.server.dir}/RUNNING_PID
```
Pid file could be used to find the process id. But as it's not hard to find the process id without the file. Could this value set to /dev/null by default? It's much better for beginners.

**Comment by renatocaval** [comment]
@ghw59, Play is also deployed in non-containerized environments so choosing a default that makes sense for docker is not the best option. 

On the other hand, I agree that the documentation can be improved to make it easier for users to learn about this specific situation. 

I'll open another issue to improve the docs. Closing this one for now. Thanks.

**Comment by pschichtel** [comment]
I would say defaulting pidfile.path to /dev/null makes sense even outside of docker. Forking services into background is less common these days, for me the RUNNING_PID file always caused issues.
