### ISSUE TITLE
json ContravariantFunctor[OWrites] should be a ContravariantFunctor[Writes]

### ISSUE THREAD

**Issue by evantill** [playframework/playframework#952]
OWrites defines an implicit ContravariantFunctor[OWrites]
it should be a  ContravariantFunctor[Writes]
### use case

lets have 

``` scala
case class PoneyFriend(friends: List[String])

object PoneyFriend {
    implicit def poneyFriendWrites: Writes[PoneyFriend] = (
      list(
         (__ \ "friend").write[String]
      ) contramap (unlift(PoneyFriend.unapply))
    )
}
```

list return a Writes[List[String]] and I will have an error :

> scala: value contramap is not a member of play.api.libs.json.Writes[List[String]]
> possible cause: maybe a semicolon is missing before `value contramap'?
>       ) contramap (unlift(PoneyFriend.unapply))
>         ^

adding the following code solve this error

``` scala
implicit val contravariantfunctorWrites: ContravariantFunctor[Writes] = new ContravariantFunctor[Writes] {
    def contramap[A, B](wa: Writes[A], f: (B) => A) = Writes[B](b => wa.writes(f(b)))
  }
```

is it possible to  change ContravariantFunctor[OWrites] as a ContravariantFunctor[Writes] ?

**Comment by gmethvin** [comment]
Moved to playframework/play-json#2
