### ISSUE TITLE
Assets not loaded into classloader during testPlayBinary

### ISSUE THREAD

**Issue by StanfordMCP** [playframework/playframework#9536]
### Play Version

2.6.20

### API

Scala, Java

### Operating System

MacOS 10.14.5 

### JDK

1.8.0_212

### Library Dependencies

None

### Expected Behavior

When running testPlayBinary we expect the asset files to be present in the classloader as it is when running runPlayBinary

### Actual Behavior

The asset files are not present in the classloader during testPlayBinary, however, they are present during runPlayBinary. 

This issue originated from utilizing third party jQuery files. The CDN works and loads the relevant scripts <script src=“https://code.jquery.com/jquery-x.x.js“></script>, however loading it from a local directory does not  <script type=“text/javascript” src=’@routes.Assets.versioned(“javascripts/jquery-x.xjs”)’></script> does not work and continually gives this error trace:

controllers.BrowserTest > test FAILED

org.openqa.selenium.WebDriverException

Caused by: com.gargoylesoftware.htmlunit.ScriptException

Caused by: net.sourceforge.htmlunit.corejs.javascript.EcmaError

org.openqa.selenium.WebDriverException: com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: “$” is not defined. (script in http://localhost:19001/ from (114, 34) to (141, 12)#118)

Build info: version: ‘3.5.3’, revision: ‘a88d25fe6b’, time: ‘2017-08-29T12:42:44.417Z’

**Comment by marcospereira** [comment]
Hey @StanfordMCP,

Gradle support is not maintained by Play team, but instead by Gradle Inc. Depending on the version you are using, you either need to open an issue in https://github.com/gradle/playframework or https://github.com/gradle/gradle.

Given that, I'm closing this issue.
