### ISSUE TITLE
play 2.7.3 java dependency injection error

### ISSUE THREAD

**Issue by EdozdeDandez** [playframework/playframework#9543]
### Play Version

2.7.3

### API

Java

### Operating System

Mac

### JDK

openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
OpenJDK 64-Bit Server VM (build 25.152-b01, mixed mode)

### Expected Behavior

1. I'm injecting into a controller using the @Inject diretive
2.
3.

### Actual Behavior

1. The application gives an error that the it cannot find the symbol Inject
2.
3.

**Comment by marcospereira** [comment]
Hey @EdozdeDandez, this does not sound like a bug, but possibly a missing dependency. Is the application adding `guice` to `libraryDependencies` like documented here:

https://www.playframework.com/documentation/2.7.x/JavaDependencyInjection#Dependency-Injection

Anyway, our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Best.
