### ISSUE TITLE
CompletionStage（redirect）

### ISSUE THREAD

**Issue by lylqccnu** [playframework/playframework#9545]
public CompletionStage<Result> register() {
  return completedFuture(redirect("http://www.baidu.com"));
}

我想要跳转到  www.baidu.com 如何实现？

**Comment by domdorn** [comment]
@lylqccnu please provide an english explanation to your bug report.

**Comment by lylqccnu** [comment]
I want to use 
public CompletionStage register() {
return completedFuture(redirect("http://www.baidu.com"));
} 
 jump to www.baidu.com how to achieve?

**Comment by marcospereira** [comment]
Hey @lylqccnu,

It is documented here: https://www.playframework.com/documentation/2.7.x/JavaAsync

Besides that, our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Best.
