### ISSUE TITLE
no-package-declaration-in-routes-file on Java 11

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#9546]
Forked from https://github.com/playframework/playframework/pull/9521#issuecomment-518799836, `scripted routes-compiler-plugin/no-package-declaration-in-routes-file` on Java 11 (not all versions?) returns:

```
[info] [error] /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_eedb53fd/no-package-declaration-in-routes-file/tests/RouterSpec.scala:13:14: object routes is not a member of package router
[info] [error]       router.routes.Application.takeBool(true).url must equalTo("/take-bool?b=true")
[info] [error]              ^
```

I tweaked the test and I'm seeing this source:

```
[info] Dumping /private/var/folders/8r/km1jjvy15md88bvtrzvmn0rw0000gn/T/sbt_e195d2d/no-package-declaration-in-routes-file/target/scala-2.12/routes/main/router/routes.java:
[info]    1: // @GENERATOR:play-routes-compiler
[info]    2: // @SOURCE:/private/var/folders/8r/km1jjvy15md88bvtrzvmn0rw0000gn/T/sbt_e195d2d/no-package-declaration-in-routes-file/conf/routes
[info]    3: // @DATE:Thu Aug 08 17:55:23 BST 2019
[info]    4:
[info]    5: package router;
[info]    6:
[info]    7: import router.RoutesPrefix;
[info]    8:
[info]    9: public class routes {
[info]   10:
[info]   11:   public static final router.ReverseInstanceController InstanceController = new router.ReverseInstanceController(RoutesPrefix.byNamePrefix());
[info]   12:   public static final router.Reverseπø$7ß πø$7ß = new router.Reverseπø$7ß(RoutesPrefix.byNamePrefix());
[info]   13:   public static final router.ReverseApplication Application = new router.ReverseApplication(RoutesPrefix.byNamePrefix());
[info]   14:
[info]   15:   public static class javascript {
[info]   16:
[info]   17:     public static final router.javascript.ReverseInstanceController InstanceController = new router.javascript.ReverseInstanceController(RoutesPrefix.byNamePrefix());
[info]   18:     public static final router.javascript.Reverseπø$7ß πø$7ß = new router.javascript.Reverseπø$7ß(RoutesPrefix.byNamePrefix());
[info]   19:     public static final router.javascript.ReverseApplication Application = new router.javascript.ReverseApplication(RoutesPrefix.byNamePrefix());
[info]   20:   }
[info]   21:
[info]   22: }
```

and confirmed with javap:

```
17:57:54 ! javap -p -c target/scala-2.12/classes/router/Routes.class
Compiled from "routes.java"
public class router.routes {
  public static final router.ReverseInstanceController InstanceController;

  public static final router.Reverseπø$7ß πø$7ß;

  public static final router.ReverseApplication Application;

  public router.routes();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: return

  static {};
    Code:
       0: new           #2                  // class router/ReverseInstanceController
       3: dup
       4: invokestatic  #3                  // Method router/RoutesPrefix.byNamePrefix:()Lscala/Function0;
       7: invokespecial #4                  // Method router/ReverseInstanceController."<init>":(Lscala/Function0;)V
      10: putstatic     #5                  // Field InstanceController:Lrouter/ReverseInstanceController;
      13: new           #6                  // class router/Reverseπø$7ß
      16: dup
      17: invokestatic  #3                  // Method router/RoutesPrefix.byNamePrefix:()Lscala/Function0;
      20: invokespecial #7                  // Method router/Reverseπø$7ß."<init>":(Lscala/Function0;)V
      23: putstatic     #8                  // Field πø$7ß:Lrouter/Reverseπø$7ß;
      26: new           #9                  // class router/ReverseApplication
      29: dup
      30: invokestatic  #3                  // Method router/RoutesPrefix.byNamePrefix:()Lscala/Function0;
      33: invokespecial #10                 // Method router/ReverseApplication."<init>":(Lscala/Function0;)V
      36: putstatic     #11                 // Field Application:Lrouter/ReverseApplication;
      39: return
}
```

So is `RouterSpec.scala` failing to access `router.routes`'s `public static final router.ReverseApplication Application` field?

**Comment by eed3si9n** [comment]
Should it be `target/scala-2.12/classes/router/Routes.class` or `routes.class` with lowercase?

**Comment by dwijnand** [comment]
Huh.  I wonder who's responsible for the classfile being `Routes.scala`.

**Comment by eed3si9n** [comment]
So do you generate `Routes.scala` and `routes.java` and output under the same package?
https://github.com/playframework/playframework/pull/4490

**Comment by eed3si9n** [comment]
If you pause scripted:

```
# Stage it, so it's easier to debug
> playRoutes
> compile
$ pause
> test:compile
> test
```

you should see 

```
$ ls target/scala-2.12/routes/main/router
ReverseRoutes.scala  Routes.scala         RoutesPrefix.scala   javascript/          module/              routes.java
```

**Comment by eed3si9n** [comment]
Maybe all you need is a macOS or Windows, not even JDK 11.

**Comment by SethTisue** [comment]
case insensitive filesystem?

**Comment by mkurz** [comment]
Related: #6702
Also have a look at this comment regarding case (in)sensitive filesystems: https://github.com/playframework/playframework/issues/6702#issuecomment-453507755

**Comment by mkurz** [comment]
> Maybe all you need is a macOS or Windows, not even JDK 11.

I guess so as well. It's about the filesystem being case in/sensitive.

**Comment by dwijnand** [comment]
Thanks for the links and info.  My best guess is something in recent Java 11 changed something in the filesystem handling that made this more of a problem?

Anyways, I guess we'll have to fix this with that breaking rename of `Routes`?

**Comment by mkurz** [comment]
> Thanks for the links and info. My best guess is something in recent Java 11 changed something in the filesystem handling that made this more of a problem?

No, I don't think Java 11 changed. The behaviour didn't change. You guys now bump into this issue because you run this scripted test locally on your machines on a case insensitive filesystem. Travis never had this issue (see [this comment](https://github.com/playframework/playframework/pull/9521#issuecomment-518799836): _"Travis failure is not relevant since this job is flaky, but it is possible to reproduce the error running locally."_ I am pretty sure the "flaky" test which failed on Travis was a different one.)
This behaviour was brought up already in #6702, where gmethvin and julienrf decided that this is a "_undocumented limitation in the routes compiler and filesystem_". So this is nothing new really.

> Anyways, I guess we'll have to fix this with that breaking rename of `Routes`?

The question here is, are we happy to just document this as a "limitation", meaning for certain scenarios the generated route classes won't work on case insenstive file systems? (Is it hard to change a filesystem or a folder on macOS to be case insensitive? I have no idea since I don't use it, but if this is just a config change, maybe that's good enough - if we document it).

If we change this however, I guess it has to wait for 2.8, because it wil be a breaking change.

**Comment by dwijnand** [comment]
> I am pretty sure the "flaky" test which failed on Travis was a different one.

Ah yes, that makes more sense.  OK, so:

Duplicate of #6702

**Comment by dwijnand** [comment]
Duplicate of #6702
