### ISSUE TITLE
Broken link in sbtSettings docs: More-About-Settings.html

### ISSUE THREAD

**Issue by lionello** [playframework/playframework#9595]
The doc at https://www.playframework.com/documentation/2.7.x/sbtSettings which is https://github.com/playframework/playframework/blob/7c196b9d6fc1032cbd75aa729ba55a81d62fcaa3/documentation/manual/working/commonGuide/build/sbtSettings.md#L6

refers to a moved document at https://www.scala-sbt.org/release/docs/More-About-Settings.html

### Play Version

Doc for 2.7.x

**Comment by renatocaval** [comment]
@lionello, thanks for reporting this.

I created a PR to fix it (#9597).
