### ISSUE TITLE
Inconsistent parsing of json payloads leading to different behaviours

### ISSUE THREAD

**Issue by renatocaval** [playframework/playframework#9602]
We have different APIs that are parsing json using Jackson and they show different behaviours due to how Jackson itself will convert a String to JsonNode.

The problem came up in an application reading a third-party remote app using play-ws in which the payload was not encoded in UTF-8. 

For a payload encoded in ISO_8859_1 as: 

```json
{
  "people" : [
    { "name" : "João" },
    { "name" : "Flávio" }
  ]
}
```

We will have the following results:

```java
wsClient.url("http://localhost:8000/payload.json").get()
	.thenApply(WSResponse::asJson)
	.thenApply(json -> ok(json.toString()));
```
Results in, 

```
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x6f
```

Under the hood `WSResponse::asJson` will do 

```java
// code from JsonBodyReadables
ByteString bodyAsBytes = response.getBodyAsBytes();
objectMapper.readValue(bodyAsBytes.toArray(), JsonNode.class);
```

When using `play.libs.Json` we get different results:

```java
wsClient.url("http://localhost:8000/payload.json").get()
    .thenApply(res -> Json.parse(res.getBody()))
	.thenApply(json -> ok(json.toString()));
```

Encoding gets broken, but parsing doesn't fail.
```json
{
    "people": [
        {
            "name": "Jo�o"
        },
        {
            "name": "Fl�vio"
        }
    ]
}
```

The encoding can be fixed by calling: 

```java
wsClient.url("http://localhost:8000/payload.json").get()
     .thenApply(res -> Json.parse(res.getBodyAsBytes().decodeString(StandardCharsets.ISO_8859_1)))
	.thenApply(json -> ok(json.toString()));
```

Resulting in:

```json
{
    "people": [
        {
            "name": "João"
        },
        {
            "name": "Flávio"
        }
    ]
}
```

Under the hood, `play.libs.Json` uses the following to parse:

```java
mapper().readTree(body)
```

This seems a better option as at least it doesn't blow up the parsing. Alternatively, we could add extense `WSResponse` to also accept a Charset.

**Comment by renatocaval** [comment]
I published a reproducer here: https://github.com/renatocaval/reproducer-play-9602

**Comment by gurkankaymak** [comment]
Hi @renatocaval 
I created a pull request for this in the `play-ws` repository
https://github.com/playframework/play-ws/pull/392
