### ISSUE TITLE
[Feature Suggestion] Gzip filter should avoid compressing small response bodies

### ISSUE THREAD

**Issue by slisaasquatch** [playframework/playframework#9606]
### Play Version
2.7.3

### API
Java

### Operating System
Windows 10

### JDK
Oracle 1.8.0_171

### Library Dependencies
N/A

### Expected Behavior
If the response body is really small, gzipping it can actually make it larger. Expressjs by default avoids compressing anything smaller than 1 KB, and I think Play Gzip filter can probably do the same.

### Actual Behavior
Play's Gzip filter will gzip small response bodies.

### Reproducible Test Case
N/A

**Comment by renatocaval** [comment]
@slisaasquatch, thanks for the suggestion.

Would you be interested in sending a pull-request for this?

**Comment by hepin1989** [comment]
set a threhole.

**Comment by slisaasquatch** [comment]
> @slisaasquatch, thanks for the suggestion.
> 
> Would you be interested in sending a pull-request for this?

I don't think I can at this moment since I don't have a Scala dev environment setup.

**Comment by slisaasquatch** [comment]
> set a threshold.

I don't think it's that simple. Right now the `chunkedThreshold` parameter `GzipFilter` accepts is for chunking the result.

**Comment by Ekzer** [comment]
I think it can be achieved simply by adding a check in **shouldCompress** : 
`  private def shouldCompress(result: Result) =
    isAllowedContent(result.header) &&
      isNotAlreadyCompressed(result.header) &&
      !result.body.isKnownEmpty`
I can give a try if you want

**Comment by Ekzer** [comment]
Okay after a test on my computer, it seems that it is already handled by editing shouldGzip function in GzipFiltersConfig as I thought : 
Example : 
`
class SmallBodyFilters @Inject()(implicit val mat: Materializer, implicit val ec: ExecutionContext) extends HttpFilters {
    def filters = {
      val gzipFilter: GzipFilter = new GzipFilter(shouldGzip = (request, response) => {
        response.body.contentLength.forall(_ > 10000)
      })
      Seq(gzipFilter)
    }
  }
`
I tested inside GzipFiltersSpec by making a simple test like this : 
`
val result = Ok("hello")
      val application = new GuiceApplicationBuilder()
        .configure(
          "play.filters.gzip.chunkedThreshold"      -> 1024,
          "play.filters.gzip.bufferSize"            -> 512,
          "play.filters.gzip.contentType.whiteList" -> List.empty,
          "play.filters.gzip.contentType.blackList" -> List.empty,
          "play.filters.gzip.compressionLevel"      -> Deflater.DEFAULT_COMPRESSION
        )
        .overrides(
          bind[Result].to(result),
          bind[Router].to[ResultRouter],
          bind[HttpFilters].to[SmallBodyFilters]
        )
        .build()
      running(application){
        checkNotGzipped(makeGzipRequest(application), "hello")(application.materializer)
}
`
And it works. With default parameters, body size was 31B. After : 5B.

**Comment by mkurz** [comment]
I like this idea and therefore created a pull request: #9680
(I kept the threshold to 0 bytes for now, but we of course can discuss if this should be a higher value)

**Comment by Ekzer** [comment]
@mkurz I'm gonna follow this pull request. Thanks :)
