### ISSUE TITLE
Support SameSite = None in 2.6.x and/or 2.7.x

### ISSUE THREAD

**Issue by bpiper** [playframework/playframework#9612]
This is just a request to please port/cherry-pick the change that added `None` to the allowed values for `SameSite` in `play.api.mvc.Cookie.SameSite` to 2.6.x and 2.7.x (or at least the latter).  Chrome 80 will require some of us to use that value, and although that Chrome release is still probably 4+ months away, the alternatives of upgrading to Play 2.8.x (which doesn't yet have a final release) or hand-rolling cookies (or using a different library) are somewhat fraught with risk.  Presumably there will be another 2.6 or 2.7 release within that timeframe?

Commit is https://github.com/playframework/playframework/commit/edbb59fff50fcb7d8f92bc4ab09d908270bb7f1d

Many thanks in advance.

**Comment by renatocaval** [comment]
We usually don't backport minor bugs. If the cherry-pick happens without conflict we can go for it.

Note that you can also do the backport yourself and send us a PR. If the community jump-in, we are more then happy. :-)

**Comment by renatocaval** [comment]
@bpiper, both backports worked without conflict. However, we won't cut a release just because of this issue. We try to accumulate as much bug fixes as possible to avoid release overhead.

**Comment by renatocaval** [comment]
Both PRs merged. Closing...

**Comment by bpiper** [comment]
Thanks @renatocaval , much appreciated, and understood that it may be some time before there's another 2.6 or 2.7 release.

**Comment by tsuyoshizawa** [comment]
Play 2.6 is already released including the patch, but Play 2.7 is not released yet.
Do you have a plan to release include the patch on Play 2.7?

Chromium announced Developers: Get Ready for New SameSite=None; Secure Cookie Settings https://blog.chromium.org/2019/10/developers-get-ready-for-new.html
