### ISSUE TITLE
examples in website not found

### ISSUE THREAD

**Issue by AngeloChecked** [playframework/playframework#9626]
https://www.playframework.com/documentation/2.7.x/LearningExamples

the two urls are not found.

**Comment by ignasi35** [comment]
Good catch @AngeloChecked !  Thanks for reporting. This was fixed in [`master`](https://github.com/playframework/playframework/pull/9440) but never backported.

I just request the [backport](https://github.com/playframework/playframework/pull/9633) and it should be fixed in a few minutes.
