### ISSUE TITLE
Config to defer body parsing after action composition(?)

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#9634]
Right now a request is processed as follows:

1. Filters run (with `RequestHeader` which doesn't have a body)
1. Body gets parsed by, yes, a body parser :wink: Now we get a `Request` (including parsed body)
1. Actions from action composition run (with the `Request` from step 2)
1. Finally the action method runs, again with the `Request`

This applies to both to the Scala and Java API.

Now here is the thing:
In my experience, inside the action composition actions' someone hardly ever accesses the body of the request. Usually what people do in such actions is to check permissions (via [`Security.Authenticated`](https://www.playframework.com/documentation/2.7.x/api/java/play/mvc/Security.Authenticated.html) or deadbolt or whatever), [cache the response](https://www.playframework.com/documentation/2.7.x/api/java/play/cache/Cached.html), etc. Most of the time, what such actions do is, read stuff from the session (cookie) or add attributes to the request before passing it on to the next action in the composition chain.

This means we always parse the body, even though later an action of the composition chain decides that the request should not be processed (because of permissions, because of individual user preferences, whatever).

We could optimize this by adding a config which ensures that the body parsing takes place just before the action method gets called, but after the action composition actions are run through (lines 2 and 3 in aboves list switch). The API could stay as it is, the only thing that would change when activating this config is that the `Request` of the effected actions would not have a body anymore.
I do see sense in this config for cases where a file upload happens and you don't want to parse/save files to disk which will be useless immediately just a few moments later anyway (because, as said, an action of the composition chain decides the request should be dropped, but the file was parsed already...). Specially when you have body parsers which redirect the upload to a different service or to S3 buckets or similiar I don't see sense to do that before any permissions or maybe per-user file max-upload size checks have taken place inside the compositon chain.

Another idea: Instead or in addition to a config we might figure out a way to apply such a defered body parsing to just selected action methods or routes.

This is just food for thought and more or less a note to myself. I haven't figured out 100% if this really makes sense, however I was working on body parser stuff and this came to my mind...

I will keep this issue open because I might hack on this someday when everything is clear to me.

**Comment by co-category** [comment]
I came across this issue as I am implementing a service which receives a callback from a third-party service. In order to verify that the callback is indeed coming from this third-party and not any malicious agent, they add a request header attribute which is essentially a hash of the full url + request body (form url encoded). The receiver of the callback then has to essentially reconstruct this digital signature but in order to do that it has to get access to the request body. This is what I was attempting to do in #9635  but kept getting an empty body whenever I tried to materialise the request body.

**Comment by mkurz** [comment]
@co-category I don't think this problem is related to my idea here. You need to access the already materialized request, which is exactly what you can do today when using an action that is part of action composition. I just saw Marcos already commented in your original issue: https://github.com/playframework/playframework/issues/9635#issuecomment-531342439 is what you are looking for.

**Comment by co-category** [comment]
@mkurz Yes you can do it that way but I wanted to do it inside the filter method of the Action Filter so that I don't end up writing a shed load of authorisation logic inside the main Action of the controller method (see my (latest comment)  [https://github.com/playframework/playframework/issues/9635#issuecomment-531354686] )

**Comment by co-category** [comment]
Just to make it super clear, this is what I want to do inside the Action Filter:

```scala
class ExampleActionFilter @Inject()(parse: PlayBodyParsers)(
  implicit materializer: Materializer,
  val executionContext: ExecutionContext
) extends ActionFilter[Request]
    with Logging {
  override protected def filter[A](request: Request[A]): Future[Option[Result]] =
      // grab the request and materialise into a form url encoded type ie Map[String, Seq[String]]
      // do some authorisation logic using the information in the materialised request body
      // determine if request should proceed or not
}
```

**Comment by mkurz** [comment]
Please see https://github.com/playframework/playframework/issues/9635#issuecomment-531358246 and let's keep the conversation over there.

**Comment by mkurz** [comment]
Summarizing the discussions we had about this feature:

We do not want to pass `null` as request body when a user opts into deferred body parsing.
Therefore we have to find a way how to not pass `null`...


* Passing `Either[RequestHeader, Request[A]]` to an `Action` instead of `Request[A]`
  * Not so good I think because we would have to change too much (`ActionBuilder`s `invokeBlock`, which should not care about this stuff)
* Change `def body: A` to `def body: Option[A]` (but that is too generic probably)
* Change `def body: A` to something `def body: LazyBody[A]` where `LazyBody` is defined as (option-like) :
```scala
sealed trait LazyBody[A]
final case class DeferedBody[A](...?) extends LazyBody[A]
final case class Body[A](value: A) extends LazyBody[A]
```
Note for this last implementation: I do think that we still need to parse the body explicitly by calling `BodyParser.parsebody(...)` (and not make some kind of lazy request where you can request the body to be parsed (and memoised)) because parsing needs a `next` action (it would be weird to always pass a `next` action to `request.body(next)` when you want to access the body).


One more thing to take care of when implementing is Java's `Http.Request<RequestBody>`...

I guess I will go with the `LazyBody` approach.  So deprecate `def body: A`, introduce `def getBody: LazyBody[A]`

Some other notes which might be useful:
Running a `HEAD` request, for Scala `req.body` gives me `AnyContentAsEmpty` and for Java it's an instance of `play.mvc.Http.RequestBody` that contains an empty `Optional`. So both are not `null` when a body is empty.

**Comment by dasteraflop** [comment]
Are you guys still working on this feature? It is incredibly useful for cases where you want to use parsers like gridFSBodyParser.

**Comment by mkurz** [comment]
@dasteraflop This feature is high up on my todo list for upcoming Play 2.9
You can follow #9779, I also created a custom Play build with this feature merged already, see https://github.com/playframework/playframework/pull/9779#issuecomment-641158921, maybe you can test and let me know if it works for you?

**Comment by dasteraflop** [comment]
@mkurz I certainly can. I have a project coming up where Im going to use it and can report back over next couple weeks.

**Comment by dasteraflop** [comment]
I just tried using the custom DBP build and cannot download it. My plugins.sbt - 
```
scalaVersion := "2.13.0"
sbtVersion := "1.1.5"

resolvers += Resolver.url(
  "Custom Play releases by mkurz",
  url("https://mkurz.github.io/playframework/releases/")
)(Resolver.ivyStylePatterns)

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.2-DBP")
```
and I tried all the permutations of adding it to my build.sbt I could think of - in common settings for all my modules, at top level and `resolvers in ThisBuild`. The resolver does get hit - 
```
[warn] ==== Custom Play releases by mkurz: tried
[warn]   https://mkurz.github.io/playframework/releases/com.typesafe.play/sbt-plugin/scala_2.13/sbt_1.0/2.8.2-DBP/ivys/ivy.xml
```
but ultimately I still end up with 
```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.play#sbt-plugin;2.8.2-DBP: not found
```

**Comment by mkurz** [comment]
Please remove
```
scalaVersion := "2.13.0"
sbtVersion := "1.1.5"
```
from your `project/plugins.sbt` file.
Instead, `scalaVersion` needs to be set in `build.sbt`, the sbt version in `project/build.properties` (like `sbt.version=1.3.12`)
(Also, don't forget to add the `resolvers += ...` to both `project/plugins.sbt` and also `build.sbt`)

**Comment by mkurz** [comment]
@dasteraflop Did it finally work for you?
