### ISSUE TITLE
Unable to Materialise a Request Body in a Action Filter

### ISSUE THREAD

**Issue by co-category** [playframework/playframework#9635]
### Play Version

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.7.3")

### API

scalaVersion := "2.12.8"

### Operating System

Linux sirius 5.2.11-1-MANJARO #1 SMP PREEMPT Thu Aug 29 07:41:24 UTC 2019 x86_64 GNU/Linux

### JDK

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b05)
OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)

### Expected Behavior

1. Create an action filter (not global)
2. Attempt to materialise the request body of a form url encoded request
3. Log the request body content to the console
4. I should see the request body in the console

### Actual Behavior

1. The request body is empty.

### Reproducible Test Case

Create a simple action filter as follows:

```scala
import akka.stream.Materializer
import javax.inject.Inject
import play.api.Logging
import play.api.mvc.{ActionFilter, PlayBodyParsers, Request, Result}

import scala.concurrent.{ExecutionContext, Future}

class ExampleActionFilter @Inject()(parse: PlayBodyParsers)(
  implicit materializer: Materializer,
  val executionContext: ExecutionContext
) extends ActionFilter[Request]
    with Logging {
  override protected def filter[A](request: Request[A]): Future[Option[Result]] =
    parse.formUrlEncoded.apply(request).run().map {
      case Left(result) => Some(result)
      case Right(formUrl) =>
        logger.info(formUrl.isEmpty.toString)
        None
    }
}
```

Dependency inject the above action filter into a controller class and create a simple controller method as follows:

```scala
  def status = Action.andThen(exampleActionFilter) {
    Ok("foo")
  }
```

Make a curl request as follows to a toy Play service with the above action filter:

```bash
curl  -d "param1=value1&param2=value2" -H "Content-Type: application/x-www-form-urlencoded"  -X POST http://localhost:9000/go
```

**Comment by ignasi35** [comment]
Related to https://github.com/playframework/playframework/issues/9634

**Comment by ignasi35** [comment]
Hi @co-category, I think you are mis-using the API. Please note the following code:

```scala
@Singleton
class HomeController @Inject()(cc: ControllerComponents)
    extends AbstractController(cc) {

  def index() = Action.andThen(ExampleActionFilter) {
    implicit request: Request[AnyContent] =>
      println(s"""
             | * * * * * * * *
             | * * * * * * * * ${request.body}
             | * * * * * * * *
             |""".stripMargin)
      Ok(views.html.index())
  }

  import play.api.mvc.ActionFilter
  import play.api.mvc.Request
  import play.api.mvc.Result

  import scala.concurrent.Future
  def ExampleActionFilter = new ActionFilter[Request] {
    override protected def executionContext: ExecutionContext = cc.executionContext
    override protected def filter[A](
      request: Request[A]
    ): Future[Option[Result]] = {
      println(
        s"""
           | - - - - - - - ${request.body}
           |""".stripMargin)
      Future.successful(None)
    }

  }
}
```

does produce the output:

```
[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter

[info] play.api.Play - Application started (Dev) (no global state)

 - - - - - - - AnyContentAsFormUrlEncoded(ListMap(param1 -> List(value1), param2 -> List(value2)))


 * * * * * * * *
 * * * * * * * * AnyContentAsFormUrlEncoded(ListMap(param1 -> List(value1), param2 -> List(value2)))
 * * * * * * * *
```

Please refer to https://github.com/playframework/playframework/issues/9634 and https://www.playframework.com/documentation/2.7.x/ScalaActionsComposition for details.

**Comment by ignasi35** [comment]
I closed the issue since this looks more like a question than an actual bug.

Feel free to reopen if I misinterpreted your intention.

**Comment by co-category** [comment]
Hi @ignasi35 ,

I may possibly be expecting too much, but my requirement is to be able to access the contents of the request body as a Map[String, Seq[String]] type (ie form url encoded) or any other type for that matter inside the filter so that I can use it to construct a digital signature (see my comment on #9634 which explains this in more detail).

In your example, I still face the same problem. I can't get to the representation of the body I need, in my case a form url encoded body. I only face this issue due to the strange authentication mechanism that the third-party API requires in order to verify that requests actually do emanate from them.

**Comment by co-category** [comment]
Hi @marcospereira ,

I do have a materialised request when inside the Action of the controller method. However, I want to access the materialized request body when inside the filter method of the Action Filter. Is that possible? That is the cruz of the problem I am facing. The reason why I want that is that I need to have that information to determine if the request should be blocked or allowed to proceed.

**Comment by co-category** [comment]
The only option I can see at the moment is not to use an Action filter but just use the standard Action of my controller method and the apply the authorization logic accordingly:

```scala
def index = Action {
   // access materialised request as usual

   // apply business logic
}
```

The reason why I want to split off the authorisation logic into an Action Filter is that this authorisation logic is quite convoluted and by placing it inside the main controller method it will make the business logic less apparent.

**Comment by mkurz** [comment]
As Marcos said you should be able to use `request.body.asFormUrlEncoded`, also within your ActionFilter:
```scala
class ExampleActionFilter @Inject()(parse: PlayBodyParsers)(
  implicit materializer: Materializer,
  val executionContext: ExecutionContext
) extends ActionFilter[Request]
    with Logging {
  override protected def filter[A](request: Request[A]): Future[Option[Result]] = {

  // The request body is already materialised here:
  request.body.asFormUrlEncoded
 
}
```

**Comment by mkurz** [comment]
Maybe there is a misunderstanding: An `ActionFilter` is _not_ a "real" filter in the sense of Play filters: https://www.playframework.com/documentation/2.7.x/ScalaHttpFilters
`ActionFilter` is part of action composition: https://www.playframework.com/documentation/2.7.x/ScalaActionsComposition#Different-request-types
Maybe the naming is a bit confusing here.

**Comment by co-category** [comment]
> ```scala
>  request.body.asFormUrlEncoded
> ```

@mkurz , that code doesn't compile for me and it is whole reason why I went down the route of trying to materialise the request body myself, did it compile for you?

See here:

```scala
import akka.stream.Materializer
import javax.inject.Inject
import play.api.Logging
import play.api.mvc.{ActionFilter, PlayBodyParsers, Request, Result, Results}

import scala.concurrent.{ExecutionContext, Future}

class ExampleActionFilter @Inject()(parse: PlayBodyParsers)(
  implicit materializer: Materializer,
  val executionContext: ExecutionContext
) extends ActionFilter[Request]
  with Logging {
  override protected def filter[A](request: Request[A]): Future[Option[Result]] = Future.successful{
    val forbidden = Some(Results.Forbidden("Blocked"))

    request.body.asFormUrlEncoded

    if(1 == 1){
      None
    }
    else
    forbidden
  }

}
```

Compiler error:

```scala
value asFormUrlEncoded is not a member of type parameter A
[error]     request.body.asFormUrlEncoded
[error]                  ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

**Comment by marcospereira** [comment]
Hey @co-category,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. My suggestion is to open a thread there and link it so people interested can see how the conversation evolved.

**Comment by co-category** [comment]
@marcospereira appreciate that but I have already posted this on [SO](https://stackoverflow.com/q/57915146/3248346) and have not received a response yet. I posted here because I just want a quick yes/no answer from the developers on Play whether this is possible or not. I thought it would be quick to answer.

**Comment by marcospereira** [comment]
We don't pay a lot of attention to StackOverflow since https://discuss.playframework.com/ exists. As I said before, better to move the conversation there.

**Comment by co-category** [comment]
@marcospereira moved the discussion over to the forum [here](https://discuss.lightbend.com/t/unable-to-materialise-request-body-in-action-filter/5056)
