### ISSUE TITLE
Non SBT dependency fetching for java version

### ISSUE THREAD

**Issue by AppyCat** [playframework/playframework#9652]
Would it be possible to have the java version of the framework fetch dependencies via Maven or Gradle?

The 'sbt run' process is problematic due to the cert issue, slowing what could otherwise be a straight line path.

**Comment by ihostage** [comment]
@AppyCat See https://gradle.github.io/playframework/ and https://github.com/play2-maven-plugin/play2-maven-plugin
And [Discuss](https://discuss.lightbend.com/c/play) is more good place for questions. 😉
