### ISSUE TITLE
Action body restarts every 75s

### ISSUE THREAD

**Issue by marcadella** [playframework/playframework#9657]
### Play Version

2.7.1

### API

Scala

### Operating System

Linux marcadella-Precision-T3600 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux  

### JDK

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

### Expected Behavior

1. Given the following action:
```
Action.async {
    implicit request: Request[AnyContent] => 
      logger.warn(s"CALL: $request")
      Future {
        blocking {
          Thread.sleep(120000)
          logger.warn("FINISHED")
          Ok("{}")
        }
      }
  }
```
2. I expect to see `CALL` at t=0s and `FINISHED` at t=120s

### Actual Behavior

What happens is the following:

1. t=0s: `CALL`
2. t=75s: `CALL`
3. t=120s: `FINISHED`
4. t=195s: `FINISHED`
5. Then the page renders "Connection was reset"

So it seems that a the Action body is mysteriously re-executed after 75s. That doesn't seem right.

**Comment by renatocaval** [comment]
@marcadella, this is due to this feature in akka-http. https://doc.akka.io/docs/akka-http/current/client-side/host-level.html#retrying-a-request

You can disable it if you want. I find it strange that you observe a retry after 75s, because by default it's 100s and Play is not overriding it. But it can be due to a change in defaults in previous akka-http version. I didn't check it though.

That's probably not documented in Play and we should improve on this.

**Comment by marcospereira** [comment]
> @marcadella, this is due to this feature in akka-http. https://doc.akka.io/docs/akka-http/current/client-side/host-level.html#retrying-a-request

That is for the Akka HTTP Client and I'm pretty sure this is not a bug in Play. What I think it is happening here is that the action is timing out according to `play.server.http.idleTimeout` (which defaults to 75 seconds) and the client is retrying the request.

@marcadella can you reproduce this using `curl`? If not, which HTTP client are you using to make the request?

**Comment by marcadella** [comment]
Thanks a lot to both of you. I didn't know about those connection pools. I summarized your answer [here](https://stackoverflow.com/a/58092992/4965515).

**Comment by marcadella** [comment]
@marcospereira Sorry I had mis-understood your comment. You're right, it has nothing to do with the connection pool. I will try with curl, but I'm sure that the ajax call is performed only once.

**Comment by ignasi35** [comment]
hi @marcadella, were you able to run your tests? Do you still think this issue is a bug and/or needs more work? Can we close the issue?

**Comment by marcadella** [comment]
Sorry, I completely forgot about this issue. I'm still a bit unsure about what was the cause of the retries, but I guess there is something in my browser sending new requests.
