### ISSUE TITLE
Routes compilation fails for projects with more than one PathBindable

### ISSUE THREAD

**Issue by rtyley** [playframework/playframework#9658]
### Play Version

2.7.3

### API

Scala

### Operating System

MacOSX

### JDK

openjdk version "1.8.0_202"

### Library Dependencies

None

### Expected Behavior

1. Add a second pathbinder to a project which already has one pathbinder
2. sbt compile
3. compilation succeeds

### Actual Behavior

1. Add a second pathbinder ('Apple') to a project which already has one pathbinder ('Dog')
2. sbt compile
3. Compilation error:

```
[error] /Users/roberto_tyley/code/play-pathbindable-issue/conf/routes:11:1: No URL path binder found for type model.Apple. Try to implement an implicit PathBindable for this type.
[error] GET     /apple/:apple                       controllers.HomeController.appleChecker(apple: model.Apple)
[error] /Users/roberto_tyley/code/play-pathbindable-issue/conf/routes:11:1: not enough arguments for method implicitly: (implicit e: play.api.mvc.PathBindable[model.Apple])play.api.mvc.PathBindable[model.Apple].
[error] Unspecified value parameter e.
[error] GET     /apple/:apple                       controllers.HomeController.appleChecker(apple: model.Apple)
[error] /Users/roberto_tyley/code/play-pathbindable-issue/conf/routes:9:1: No URL path binder found for type model.Dog. Try to implement an implicit PathBindable for this type.
[error] GET     /dog/:dog                           controllers.HomeController.dogDescription(dog: model.Dog)
[error] /Users/roberto_tyley/code/play-pathbindable-issue/conf/routes:9:1: not enough arguments for method implicitly: (implicit e: play.api.mvc.PathBindable[model.Dog])play.api.mvc.PathBindable[model.Dog].
[error] Unspecified value parameter e.
[error] GET     /dog/:dog                           controllers.HomeController.dogDescription(dog: model.Dog)
```
(repeats three times)

Note that lines in the routes file that compiled before (the `/dog/:dog`endpoint) are now broken, even though they worked before - as well as the new `/apple/:apple`endpoint being broken.

The generated `Routes.scala` file seems to have sensible imports at the top of it:

```
package router

import play.core.routing._
import play.core.routing.HandlerInvokerFactory._

import play.api.mvc._

import _root_.controllers.Assets.Asset
import _root_.model.DogBinding._
import _root_.model.AppleBinding._
```

...yet neither binding is being found.

### Reproducible Test Case

We have a branch in [this project](https://github.com/guardian/play-pathbindable-issue/commits/add-second-pathbinder-to-break-compilation) for a simple Play application which introduces a second pathbinder. You can see that this change results in a failing compilation (and a [failing Travis build](https://travis-ci.org/guardian/play-pathbindable-issue/builds)).

Issue description and reproduction of failing issue co-authored with @amyhughes.

Note that this issue seems to be distinct from https://github.com/playframework/playframework/issues/911.

**Comment by ignasi35** [comment]
I think the issue is that both `implicit val pathBinder` you implemeted for `Apple` and `Dog` use the same name so when the code is generated and the imports:

```scala
import _root_.model.DogBinding._
import _root_.model.AppleBinding._
```

added, one import shadows the other.

I've sent a [PR](https://github.com/guardian/play-pathbindable-issue/pull/1) to your project.
