### ISSUE TITLE
How to Run Lagom on Https 

### ISSUE THREAD

**Issue by skatturi** [playframework/playframework#9666]
Hello guys,
     **1st issue:**
 I am trying to run lagom service on https port, There is no proper documentation. It is very direct in spring just by adding the ssl cert and pointing to that cert and give the custom port number. 
--> can i know the process how to setup the lagom services to run on HTTPS.

**2nd Issue:**
--> How to implement rest template in lagom. I am trying to make a 3rd party server call from lagom. How to implement that?

**Comment by ihostage** [comment]
Hi, @skatturi! 👋 
It's a Playframework repository, not Lagom 😄 
[Forum](https://discuss.lightbend.com/c/lagom) is a more good place for questions about Play and Lagom.

1st: See [Lagom documentation](https://www.lagomframework.com/documentation/current/java/ConfiguringServicesInDevelopment.html#Using-HTTPS-in-development-mode) about using HTTPS.
2nd: You can use Play WS, or you can write Lagom Service Descriptor for external service and using it.

**Comment by renatocaval** [comment]
Hi @skatturi, I'm closing this one. 
As @ihostage mentioned, the forum is a more suitable place for questions.
