### ISSUE TITLE
Ensure that reverse routing works with vanilla play idea from Java project in IntelliJ

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#969]
In a Java project, IntelliJ seems to consider reverse routes as syntax errors in.

**Comment by milanaleksic** [comment]
This is still going on in latest Intellij 14; NIAs workaround is still OK

**Comment by sunnykaka** [comment]
I put @OlegYch 's answer in my Build.scala and reload the project.
My Intellij still not include "target/scala-2.11/src_managed/main" as source folder.
here is my Build.scala:
![screenshot from 2015-04-02 15 23 10](https://cloud.githubusercontent.com/assets/1176838/6959486/349c475e-d94c-11e4-8db9-b68255fa391d.png)

So I have to add source folder manually every time after project reload : (

**Comment by kflorence** [comment]
FWIW, none of these solutions work for me with Play 2.3.8 and IJ 14.1.x :(

**Comment by bpgriner** [comment]
I'm not sure if this is the same problem, but when trying to perform a `return redirect(routes.Application.index());`, routes is not a known variable that can used.

I'm attempting to following the basic play framework example (YouTube video on front page of playframework.com) with IntelliJ 14.0.4 and latest version of Play (2.3.8?).

**Comment by PeterRangelov** [comment]
Yet my application compiles and runs as expected!! Red squiggles are annoying; guys please fix dis :)

![cannot resolve symbol routes](https://cloud.githubusercontent.com/assets/4349862/8017882/b2ecd404-0bd1-11e5-8fef-816f89922e08.png)

**Comment by bpgriner** [comment]
+1 @PeterRangelov 

I should have provided a screen shot, I'm having the exact same issue.  Everything compiles and runs fine, just annoying to look at in IntelliJ.

**Comment by jwsher** [comment]
FYI, This is still a problem on play 2.4.  The classes compile fine but it's annoying to look at and the previously mentioned workaround of creating the fake directories doesn't work.

![screen shot 2015-06-20 at 8 29 31 pm](https://cloud.githubusercontent.com/assets/471429/8270244/32e5af90-178b-11e5-89c8-217facab4c29.png)

**Comment by vicaba** [comment]
Yep, I have the same problem using intellij idea 14

**Comment by hossamahamid** [comment]
I had the same problem with Intellij Idea 14.1.4 and play framework 2.4.2 but I managed to solve the issue with the help of the link @ghost added but it was old so I had to make little changes, here is what I did.
right click on "target" directory from the project navigator in intellij and choose "mark directory as" then "Cancel Exclusion". After that, right click on "scala-2.11/routes/main" folder and choose "mark directory as sources root". I also excluded "resolution-cache" and "streams".

**Comment by vicaba** [comment]
@hossamahamid I can't exclude the "./target" directory but I can exclude "project->target", nevertheless, the file "scala-2.11/routes/main" is in the "./target" directory. When you refer to "target" are you referring to the "target" directory placed at the root directory of the project?
If you can, take a look at my images and tell me if that was your situation (menu shown when I right-clicked the item highlighted in blue in the project navigator):

![screen shot 2015-07-15 at 11 06 28](https://cloud.githubusercontent.com/assets/2136777/8694957/acda3bbc-2ae2-11e5-9120-fefa3c46f130.png)

![screen shot 2015-07-15 at 11 06 36](https://cloud.githubusercontent.com/assets/2136777/8694964/b5417f0e-2ae2-11e5-9bfe-283dc4f2215c.png)

![screen shot 2015-07-15 at 11 07 46](https://cloud.githubusercontent.com/assets/2136777/8694970/bc47c8e4-2ae2-11e5-8c4a-e5f394811ee1.png)

Maybe I can't do the expected operations because I added a related project in the build.sbt:

```scala

name := """WHTTP-front"""

version := "1.0-SNAPSHOT"

lazy val wcommon = RootProject(file("../WCommon"))

val root = (project in file(".")).enablePlugins(PlayScala).dependsOn(wcommon)

scalaVersion := "2.11.6"

//val whttp_front = Project(id = "root", base = file("."))

libraryDependencies ++= Seq(
  jdbc,
  cache,
  ws,
  specs2 % Test
)

libraryDependencies +=
  "com.typesafe.akka" %% "akka-remote" % "2.4-SNAPSHOT"

resolvers += "Akka Snapshot Repository" at "http://repo.akka.io/snapshots/"

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

// Play provides two styles of routers, one expects its actions to be injected, the
// other, legacy style, accesses its actions statically.
routesGenerator := InjectedRoutesGenerator


fork in run := true


```

**Comment by adis-me** [comment]
I have cancelled exlusion for the `target` folder in the root of my project. And now it works fine!

**Comment by hossamahamid** [comment]
@vicaba yes I mean the target directory at the root. That's weird but try to exclude the target directory from the module settings window. You can open it by right click on the project directory and choosing "Open Module Settings", or by selecting "Project Structure" from "File" menu then "Modules".

**Comment by vicaba** [comment]
@hossamahamid I've tried it and nothing changes. I've tried several combinations too, but I can't get it working. 
But while I was searching for the solution I came out with two discoveries:
The first one is that if I change my default application _class_ controller to an _object_, I get the correct code hints when typing the routes, but the application does not compile :S. In earlier versions of Play, the controllers where _objects_ .
The other interesting thing I discovered is that at the moment, I can disable Play route inspections:
![screen shot 2015-07-15 at 14 26 04](https://cloud.githubusercontent.com/assets/2136777/8698487/07b4739c-2aff-11e5-890e-d7c5fb0c825e.png)

Change the inspections configuration by clicking on the man with a hat at the bottom right.



I'll give it another try in a few days after doing a OS clean install.

Thank you all for the support anyway.

**Comment by thobson** [comment]
@vicaba I have the same issue, I think we need to wait for Jetbrans to fix this (in the ultimate version) because I don't see how it could work without some form of "hack" from the tool vendor. As controllers are now classes the statement route.<Class>.method will always be invalid because in Scala you can't call a method on a class.

**Comment by vicaba** [comment]
@thobson Yep, that's just what I was thinking... We will have to wait.

**Comment by thobson** [comment]
@vicaba I just found an EAP version of the plugin which seems to work in most cases. Take a look here and download the 1.5.2.3.EAP version of the plugin. You will need to uninstall the exisiting Scala plugin then copy this new version into the plugins directory, giving it the folder name "Scala". Of course it's EAP software so it's not perfect but it does seem to work ok for me (so far!)

**Comment by vicaba** [comment]
@thobson Thanks, I'll try it as soon as I can :)

**Comment by kgambrah** [comment]
Scala plugin 1.5.2.3.EAP version didn't work for me. I went with disabling disabiling the play routing action inspection rather.

**Comment by pschichtel** [comment]
This problem still exists in intellij 15-eap and with the scala plugin on version 1.8.

I wonder why this issue is still closed even though it is still very much a problem.

![javascript-red](https://cloud.githubusercontent.com/assets/526104/9428757/25de13d6-49b9-11e5-873a-93605bb42b7a.png)

**Comment by jroper** [comment]
It's closed because it's a problem with the way IntelliJ imports projects, not with Play, so the issue doesn't belong in Play's issue tracker.
