### ISSUE TITLE
Use sbt-dynver

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9703]

**Comment by ignasi35** [comment]
The play build (and probably related scripts in `vegemite`) have custom manipulation of the version. See for example:

https://github.com/playframework/playframework/blob/14e73eee9371069a0551d0a908c5949cb6ada4dc/project/Docs.scala#L137

**Comment by dwijnand** [comment]
Use `isSnapshot.value` instead.  sbt-dynver honours that, see https://github.com/dwijnand/sbt-dynver#detail

**Comment by ignasi35** [comment]
There's some more logic wrt `SNAPSHOT` suffix detection in [playfw.com](https://github.com/playframework/playframework.com/blob/7e4a847d828df993eaf0abff43543d73136b5a72/app/actors/DocumentationPollingActor.scala#L93)

**Comment by mkurz** [comment]
Fixed by #9929
