### ISSUE TITLE
[master/2.7.x] CRON builds fail on scripted tests

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9713]
For about 3 weeks now, the `CRON` builds for the `2.7.x` branch fail the `scripted` tests jobs (both `0.13` and `1.x`).

The failure is caused by a [failure to resolve](https://travis-ci.com/playframework/playframework/jobs/237766102#L1575) Akka (and Akka-HTTP) snapshots from the builds on the `scripted` tests.

~This doesn't seem to happen in either `master` not `2.6.x` `CRON` builds.~

**UDPDATE**: This also happens in `master` (see [this build](https://travis-ci.com/playframework/playframework/jobs/239682764#L4323)) but it is often masked by jobs failing in earlier stages of the build.

**Comment by ignasi35** [comment]
I suspect the latest passing build was: https://travis-ci.com/playframework/playframework/builds/127938141

And the first build failing: https://travis-ci.com/playframework/playframework/builds/128273921

Both are running on:

```
Commit 9d1f829
Branch 2.7.x 
```

 - - - - - - - - - 

Possible causes: 

 * the Travis cache for `2.7.x` had the artifacts already and was cleaned between builds.

**Comment by ignasi35** [comment]
> **UDPDATE**: This also happens in `master` (see [this build](https://travis-ci.com/playframework/playframework/jobs/239682764#L4323)) but it is often masked by jobs failing in earlier stages of the build.

I think that after the [linked build](https://travis-ci.com/playframework/playframework/jobs/239682764#L4323), Akka introduced the "`AbstractBehavior` needs `ActorContext`" masking the issue in `master`.

**Comment by ignasi35** [comment]
https://github.com/playframework/playframework/pull/9656 could be related to this issue except #9659 wasn't backported 🤔.

**Comment by mkurz** [comment]
@ignasi35 You mean #9656, not #9659?

**Comment by ignasi35** [comment]
Slightly related to https://github.com/playframework/play-meta/issues/78

**Comment by ignasi35** [comment]
So it looks like the issue could be:

1. play itself runs on sbt `1.3.0`
2. doing a publisLocal populates the `.coursier` cache
3. `scripted` tests run on sbt `1.2.8` (because [interplay](https://github.com/playframework/interplay/blame/6b62f572294d63a690adaab8348020abf7541377/src/main/scala/interplay/PlayBuildBase.scala#L26))
4. `scripted` tests use ivy (instead of coursier)  and so find the cache unpopulated.

**Comment by ignasi35** [comment]
> So it looks like the issue could be:

The good news is that interplay [was already updated to use `1.3.2`](https://github.com/playframework/interplay/pull/93) but that the bad news is it hasn't been released yet.


- - - -

And the weird news is that this "populating the cache" theory sounds strange when checking the `show fullResolvers` in a project using sbt `1.3.x`:

```
sbt:Play-JDBC> show sbtVersion
[info] 1.3.0
sbt:Play-JDBC> show fullResolvers
[info] * Raw(ProjectResolver(inter-project, mapped: com.typesafe.play#play-netty-server_2.13;2.8.0-SNAPSHOT, com.typesafe.play#play-akka-http-server_2.13;2.8.0-SNAPSHOT, com.typesafe.play#play-specs2_2.13;2.8.0-SNAPSHOT, com.typesafe.play#play-streams_2.13;2.8.0-SNAPSHOT, com.typesafe.play#build-link;2.8.0-SNAPSHOT, com.typesafe.play#play-jdbc-api_2.13;2.8.0-SNAPSHOT, com.typesafe.play#play-test_2.13;2.8.0-SNAPSHOT, com.typesafe.play#play_2.13;2.8.0-SNAPSHOT, com.typesafe.play#play-exceptions;2.8.0-SNAPSHOT, com.typesafe.play#play-guice_2.13;2.8.0-SNAPSHOT, com.typesafe.play#play-server_2.13;2.8.0-SNAPSHOT))
[info] * FileRepository(local, Patterns(ivyPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None))
[info] * public: https://repo1.maven.org/maven2/
[info] * FileRepository(local-preloaded-ivy, Patterns(ivyPatterns=Vector(/Users/ignasi/.sbt/preloaded/[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(/Users/ignasi/.sbt/preloaded/[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None))
[info] * local-preloaded: file:////Users/ignasi/.sbt/preloaded/
[info] * akka-snapshot-repository: https://repo.akka.io/snapshots
[info] * akka-http-snapshot-repository: https://dl.bintray.com/akka/snapshots/
[info] * sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots
[info] * sonatype-releases: https://oss.sonatype.org/content/repositories/releases
[info] * typesafe-releases: https://repo.typesafe.com/typesafe/releases
[info] * URLRepository(typesafe-ivy-releases, Patterns(ivyPatterns=Vector(https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), false)
[success] Total time: 0 s, completed Oct 9, 2019 8:12:47 PM
sbt:Play-JDBC>
```

when displaying `show fullResolvers` in `play-jdbc` (for a shorter output I picked a random module in play) there's a `FileRepository` for `${ivy.home}/local/...` but there's no `FileRepository` pointing to `${coursier.home}` or anything similar. I think I'm missing some setting...

**Comment by ignasi35** [comment]
We couldn't pinpoint the actual cause for this issue, but decided to push #9717 forward as a workaround to get `cron` jobs for `scripted` tests back online (even at the cost of duplicate code).
