### ISSUE TITLE
Feature request: split Configuration into standalone library

### ISSUE THREAD

**Issue by tmccombs** [playframework/playframework#9745]
Play's `Configuration` class (scala) is a nice wrapper around typesafe config. Would it be possible to split it out into a standalone library so that scala projects that don't need all of Play can use it? Similar to how play-json was split out into a separate library.

**Comment by gurkankaymak** [comment]
Hi, I can work on this, how this separation process is being handled? should I create a new repository and transfer it to you when the work is done, or you provide an empty repo and I submit a pr to it

**Comment by marcospereira** [comment]
Hey @gurkankaymak,

You won't need to isolate this in another repository. It should be enough to have a new sbt sub-project (that will then produce a new artifact) and move the code there.
