### ISSUE TITLE
unable to test POST with no body

### ISSUE THREAD

**Issue by sdyura** [playframework/playframework#9757]
### Play Version
2.7.3

### API

java

### Operating System

Linux 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### JDK

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

### Library Dependencies

none

### Expected Behavior

1. I want to test a POST URL that does something when there is a body, and something else when there is no body.

### Actual Behavior

1. request.hasBody() is true even when there is no body, in fact ive not found any way of writing a test where this method will return false.

### Reproducible Test Case

[noBody.zip](https://github.com/playframework/playframework/files/3755868/noBody.zip)

**Comment by renatocaval** [comment]
relates to https://github.com/playframework/playframework/issues/8632

**Comment by renatocaval** [comment]
Thanks for reporting this.

I added this issue to the backlog, but it can take sometime before someone can find time to pick it. 

Would you be interested in sending a PR?

**Comment by knittl** [comment]
I'm trying to cook up a PR. This is only happening when using Java, Scala is behaving correctly (so `hasBody` returns `false`, as expected). It looks like the Java controller receives a `RequestBody` with an empty `RawBuffer`, which is not handled by the `hasBody` implementation.

Adding a new case to the match clause is easy and probably suffices, but I'm not sure if that's the proper fix and why Java and Scala behave differently in this scenario.

**Comment by mkurz** [comment]
Fixed by #9787
