### ISSUE TITLE
FormFactory: multiselect value only returns first selected option

### ISSUE THREAD

**Issue by maaartinko** [playframework/playframework#9780]
### Play Version

2.7.3

### API

Java

### Operating System

Windows 10

### JDK

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

### Library Dependencies

none

### Expected Behavior

1. Submitting a form (GET) including a `<select name="testSelect" multiple="multiple">`.
2. Using the injected `FormFactory` to get the Form data server side.
3. `form.get().testSelect` resulting in a array of the selected values in the multi-select.

#### Example
Form:
```HTML
<form id="test-form" method="get" action="/test">
    <select name="testSelect" multiple="multiple">
            <option value="one">One</option> <!-- Selected on the request -->
            <option value="two">Two</option>
            <option value="three">Three</option> <!-- Selected on the request -->
    </select>
    <button type="submit">Submit</button>
</form>
```

Controller:
```Java
@Inject
protected FormFactory formFactory;

{...}

Form<TestForm> form = formFactory.form(TestForm.class).bindFromRequest(request);
TestForm testForm = form.get();
String[] multiSelectValues = testForm.testSelect; // Returns ["one", "two"]
```

### Actual Behavior

1. Submitting a form (GET) including a `<select name="testSelect" multiple="multiple">`.
2. Using the injected `FormFactory` to get the Form data server side.
3. `form.get().testSelect` results in **only the first selected value listed in the GET parameters**

#### Example
Form:
```HTML
<form id="test-form" method="get" action="/test">
    <select name="testSelect" multiple="multiple">
            <option value="one">One</option> <!-- Selected on the request -->
            <option value="two">Two</option>
            <option value="three">Three</option> <!-- Selected on the request -->
    </select>
    <button type="submit">Submit</button>
</form>
```

Controller:
```Java
@Inject
protected FormFactory formFactory;

{...}

Form<TestForm> form = formFactory.form(TestForm.class).bindFromRequest(request);
TestForm testForm = form.get();
// This wouldn't work -> String[] multiSelectValues = testForm.testSelect;
String multiSelectValue = testForm.testSelect; // Returns "one"
```

**Comment by maaartinko** [comment]
Just in case:
It makes no difference if the `<select>` is generated with the helper or in plain HTML.

So this would also return a String with the value `"one"`
```scala
@helper.select(testForm("testSelect"),
    Seq(
        "one" -> "One", <!-- Selected -->
        "two" -> "Two",
        "three" -> "Three"<!-- Selected -->
    ),
    'multiple -> "multiple")
```

**Comment by mkurz** [comment]
Can you please also post your `TestForm`?

**Comment by mkurz** [comment]
Or even better, push a small project that reproduces the problem here on GitHub, thanks!

**Comment by mkurz** [comment]
The solution is to append `[]` to the name of the `select`:
```html
	    <select name="testSelect[]" multiple="multiple">
		    <option value="one">One</option> <!-- Selected on the request -->
		    <option value="two">Two</option>
		    <option value="three">Three</option> <!-- Selected on the request -->
	    </select>
```
See https://www.playframework.com/documentation/2.7.x/ScalaForms#Repeated-values

Unfortuntaly this section is missing in the [Java docs](https://www.playframework.com/documentation/2.7.x/JavaForms).

**Comment by maaartinko** [comment]
I haven't been able to work on the example project for this issue, so thanks for the research! I tested it on my project and it work.
