### ISSUE TITLE
Request.contentType discard the boundary of the form-data

### ISSUE THREAD

**Issue by hmagrahi** [playframework/playframework#9820]
- Play version 2.7.3
- Project using Scala
- Linux 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Java 8
### Expected Behavior

We use a microservice play as a **proxy** (gateway) for all other microservices, when importing a file using content-type from-data, our client (the front) generate a request with a header contains a **content-type: multipart/form-data; boundary=----WebKitFormBoundary76R0zZdvXnlHAQqg**.

In our gateway we just authenticate and pass the request as it to another microservice in play (the same version). So when we create the new request to call the other microservice, we use the BodyWritable to resend the body.

To create a BodyWritable we need the source and the content-type 

`  
 val hs = filterHeaders(request.headers)

    val ct = request.contentType.getOrElse("")

    val b = BodyWritable(SourceBody.apply, ct)

    ws.url(url)

      .withFollowRedirects(false)

      .addOptQueryStringParameters(request.queryString.mapValues(_.headOption).toSeq: _*)

      .withMethod(request.method)

      .withBody(request.body)(b)

      .addHttpHeaders(hs: _*)

      .streamAndLog

      .map(PlayResults.fromWSResponse)`

### Actual Behavior

this will generate a **Missing boundary header** in the other microservice when we try to read the form-data because  **val ct = request.contentType.getOrElse("")** will delete the boundary and keep only **multipart/form-data**
we had tu use 
**val ct = request.headers.toSimpleMap.get("Content-Type").getOrElse("")**

### Reproducible Test Case
for request with a Content-Type = "multipart/form-data; boundary=----WebKitFormBoundary76R0zZdvXnlHAQqg"
request.contentType should returns "multipart/form-data; boundary=----WebKitFormBoundary76R0zZdvXnlHAQqg" not "multipart/form"

**Comment by renatocaval** [comment]
Thanks for reporting this.

I added this issue to the backlog, but it can take some time before someone can find time to pick it. 

Would you be interested in sending a PR?

**Comment by hmagrahi** [comment]
Hello,

Thank you for your response,
Yes absolutly sir! I'll take care of it,

**Comment by mkurz** [comment]
I think this can be closed, see corresponding pull request (which was also closed): #9854
