### ISSUE TITLE
SLF4J issue in a Non Maven project. Multiple bindings

### ISSUE THREAD

**Issue by Many** [playframework/playframework#9823]
Hi everyone. 

I'm working in a non maven project which runs in a WebSphere Server application 8.5. I'm now trying to migrate this application from a development environment to a local environment. During this process when I try to deploy the application in server the console shows the following error: "slf4j class path contains multiple slf4j bindings", and the installation, although finished the application is not working. 

I've been looking for a solution but I just find this issue related to Maven projects, where the solution is just add an exclusion key in pom.xml. But, for this project, that is a non maven project I can't understand why is this happening.  

I understand that the issue is because of the other library that i use called "logback-classic" which use internally other instance of slf4j. 

Someone who can help me please, I would really appreciate any comment. Thanks.

**Comment by ihostage** [comment]
You are right. You need to remove duplicate libraries from your runtime classpath. 

A [discussion forum](https://discuss.lightbend.com/c/play) is a more good place for questions 😉

**Comment by Many** [comment]
Thanks.

**Comment by Many** [comment]
> You are right. You need to remove duplicate libraries from your runtime classpath.
> 
> A [discussion forum](https://discuss.lightbend.com/c/play) is a more good place for questions 😉

Yes, but the thing is that I don't know how avoid that this "logback-classic" download the slf4j and there's no conflict with the other one. I tried removing my slf4j from my classpath, but when I deploy the application shows me an error because of the class not found the import for slf4j. On this point, I don't know what do.

**Comment by renatocaval** [comment]
Hello @Many,  

In this sbt page (https://www.scala-sbt.org/1.x/docs/Library-Management.html), you can find more information about how to exclude a library. 

I will close this issue, because as said before, it's better to ask for help on the forums and use GitHub to report issues or request features.
Best.
