### ISSUE TITLE
[Query/Feature request]Ability to specify the custom table name  for the play_evolutions

### ISSUE THREAD

**Issue by rp1214** [playframework/playframework#9835]
This is not actually a bug or an issue but a feature request to be able to provide customize name for "play_evolutions" for evolution storage table. this could be very similar to how we can provide the play database schema. 

In my case,  i have one play projects with two sub modules which are not dependent on each other. All the database evolution scripts resides in root project. 

Now there is a requirement to extract and create two separate projects instead of one but they will use the same database. And also separate their evolution scripts so if a developer working on one project would need only respective evolution. so i have them separated.

Everything works smooth until we run the project 1 but when we also run Project 2, it un-apply project 1 evolution scripts and tries to apply the project 2 evolution scripts  since they both using same play_evolution table .

So i am looking to specify a custom table name instead of play_evolutions something like "play_evolutions_project1" and "play_evolutions_project2" to avoid conflicts.

Creating a separate schema is out of question here due to some other complexities. I know this is overkill of ideal designs/patterns but this is what was needed or requested.

if there is any way to achieve it then please share.

Play version : 2.6.11

**Comment by renatocaval** [comment]
Thanks for reporting this.

I added this issue to the backlog, but it can take some time before someone can find time to pick it. 

On the other hand, I would advise having two applications sharing the same database, but I don't know your real requirements. That said, this is a request for a very specific case.
Play being an open-source project, you will need to have more people interested in this feature or take a stab yourself and send a PR. PRs are always welcome.

**Comment by mkurz** [comment]
@MarcinAman I saw you did some work in your [`specify-evolutions-table` branch](https://github.com/MarcinAman/playframework/commits/specify-evolutions-table). Do you want to open a pull request with that fix?

**Comment by mkurz** [comment]
See #10039
