### ISSUE TITLE
Play-twirl support imports deprecated API (scala 2.13)

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9845]
The Java minimal imports:

https://github.com/playframework/playframework/blob/576c0def93c7abe8df7802fb3549b2e02475005b/dev-mode/build-link/src/main/java/play/TemplateImports.java#L32

imports `scala.collection.JavaConverters` which is deprecated in scala 2.13. This triggers the warning/error (dependinc on your `scalac` options):

```
[error] /Users/ignasi/git/projects/lightbend/playframework/play-samples/play-java-forms-example/app/views/listWidgets.scala.html:28:15: object JavaConverters in package col
lection is deprecated (since 2.13.0): Use `scala.jdk.CollectionConverters` instead
[error]         @form.globalErrors.asScala.map { error: play.data.validation.ValidationError =>
[error]               ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Nov 26, 2019 11:58:26 AM
```

Maybe fixable in this [`PlaySettings`](https://github.com/playframework/playframework/blob/b59ea7c532e9218b6d86825a1e5865274c96b5cf/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L35) initialization (branch over `scalaVersion`?)

**Comment by fusuiyi123** [comment]
Hi @ignasi35 may I work on this? But what does `branch over scalaVersion?` means? thanks!

**Comment by raboof** [comment]
> may I work on this?

I'm not aware of anyone currently working on this, so go for it!

> But what does `branch over scalaVersion` means?

It means creating an 'if' where we import either 'CollectionConverters' or 'JavaConverters' depending on the targeted scala version

**Comment by fusuiyi123** [comment]
Hey @raboof I sent a pr, could you suggest how to test it locally? Should I publish a snapshot to local and use a sample play project with the local snapshot version? If then what sample project should I use to test? Thanks!

**Comment by raboof** [comment]
> Hey @raboof I sent a pr

Cool, thanks!

> could you suggest how to test it locally? Should I publish a snapshot to local and use a sample play project with the local snapshot version?

Yes, that would be great.

> If then what sample project should I use to test? Thanks!

Any sample should do - for example the hello world from https://github.com/playframework/play-samples/tree/2.8.x/play-scala-hello-world-tutorial ?

**Comment by fusuiyi123** [comment]
seems I cannot reproduce the error, I entered localhost:9000 and I get
```

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[info] Compiling 10 Scala sources and 1 Java source to /Users/fusuiyi/Desktop/opensource/play-samples-play-scala-hello-world-tutorial/target/scala-2.13/classes ...
[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter

[info] play.api.Play - Application started (Dev) (no global state)
```

**Comment by raboof** [comment]
Perhaps if you add `-Xfatal-warnings` to the `scalacOptions`?

**Comment by fusuiyi123** [comment]
yes I have this in the default hello-world repo, let me remove it to test

**Comment by fusuiyi123** [comment]
still the same

**Comment by ignasi35** [comment]
Hi @fusuiyi123, thanks for stepping in and fixing this. The issue will only manifest when you are using the Java API of Play since the import causing the warning is only added if the `PlayJava` sbt plugin is used.
I see on your console output (pasted above) the project you use is named `play-samples-play-scala-hello-world-tutorial` so I'm assuming you are using the play scala sample (which won't manifest the issue).
Could you try again with the java one?

**Comment by fusuiyi123** [comment]
<img width="1920" alt="Screen Shot 2020-04-07 at 17 13 25 (2)" src="https://user-images.githubusercontent.com/13977613/78730987-392f2b00-78f3-11ea-88bc-83c8d2e42fcf.png">

**Comment by ignasi35** [comment]
Oh, thanks for trying. I guess it's a particular usage. I originally saw the issue in `play-java-forms-example/app/views/listWidgets` (see the description in the issue above).

**Comment by fusuiyi123** [comment]
thanks, just reproduced the error in `play-java-forms-example`

**Comment by fusuiyi123** [comment]
I updated the pr
