### ISSUE TITLE
Support for request refinement before they get to a SIRD Router

### ISSUE THREAD

**Issue by acmoune** [playframework/playframework#9848]
Let's say I have this SIRD Router:

   ```scala
 val adminRouter = Router.from {
      case GET(p"/posts") =>
        Action { implicit request =>
          ...
        }
    }
```

And this Action Refiner:

```scala
object NameSpace {
      class SecuredRequest[A](val username: String, request: Request[A]) extends WrappedRequest[A](request)
      
      def securedAction(implicit ec: ExecutionContext) = new ActionRefiner[Request, SecuredRequest] {
        def executionContext: ExecutionContext = ec
    
        def refine[A](request: Request[A]): Future[Either[Result, SecuredRequest[A]]] = {
          val username = request.session.get("username")
    
          if (username.isDefined)
            Future.successful(Right(new SecuredRequest(username.get, request)))
          else
            Future.successful(Left(Results.Redirect(controllers.routes.AuthController.signInUser())))
        }
      }
    }
```

Then in my `conf/routes` file I have this

   ` ->   /admin   adminRouter`

What I would like is to apply the `securedAction` **action refiner** to all requests sent to the `adminRouter` before they get to it. So the `adminRouter` will just assume that all requests have a `username` field if they managed to get to him.

Do I Have to create a `SecuredAction` **action builder** and use it to create action like this ?

```scala
case GET(p"/posts") =>
      SecuredAction { implicit request =>
        ...
      }
```
The issue with this is that if you change your mind later, you may have too many actions to update. It would be better if the request handlers are not aware of all that, if we could manage it at the Router level.

**Comment by acmoune** [comment]
One way this could have been possible if this an Action could return another Router, and if Routers could do partial pattern matching against the `RequestHeader`, a little bit like with `AkkaHttpServer` `Directives`

Something like this:

```scala
val adminRouter = Router.from {
      case GET(p"/api/$subPath") =>
        SecuredAction { implicit request: SecuredRequest =>
        
          Router.from {
            subPath match {
              case p"posts" => {
                Action { implicit request: SecuredRequest =>
                  ...
                }
              }
            }
          }
        }
    }
```


But it is not supported yet,

**Comment by renatocaval** [comment]
You can achieve this by adding a handler, see https://www.playframework.com/documentation/2.7.x/ScalaHttpRequestHandlers#HTTP-Request-Handlers

However, if you want to have a specific type, like in `SecureRequest`, then you need to have an Action Builder.

**Comment by acmoune** [comment]
Thank you Renato, I will study those request handlers.
