### ISSUE TITLE
Consider PredicatedAction and associated types as part of Play

### ISSUE THREAD

**Issue by huntc** [playframework/playframework#986]
Consider incorporate the predicated action types of this pull request: https://github.com/TechEmpower/FrameworkBenchmarks/pull/124

It may also be useful to consider generalising some sub types of the predicate action e.g. checking that there is a reasonable amount of memory available, checking the database connection pool etc.

**Comment by wsargent** [comment]
Closing -- this is handled better handled through filters and custom actions outside of play-core.
