### ISSUE TITLE
Support ["*"] when configuring play.filters.cors.allowedOrigins

### ISSUE THREAD

**Issue by marcospereira** [playframework/playframework#9880]
### Play Version

Play 2.7+.

### API

Java and Scala APIs.

### Description

`Access-Control-Allow-Origin` header uses `*`wildcard to tell browsers to allow any origin to access the resource. Play, on the other hand, uses `null` to indicate that all origins are allowed. It would be better for developer experience if the configuration in Play supported wildcard too, making it closer to the specifications for the header.

Due to compatibility reasons, we need to support both, meaning both configurations below should be equivalent:

```hocon
play.filters.cors.allowedOrigins = null
```

```hocon
play.filters.cors.allowedOrigins = ["*"]
```

**Comment by risingsmoke** [comment]
Hi, if it is still open, can I work on this?

**Comment by marcospereira** [comment]
Hey @risingsmoke,  Yes, it is still open, so feel free to work on it. :-)

Thanks!
