### ISSUE TITLE
Complete the play-omnidoc cleanup

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9903]
PR #7134 removed `play-omnidoc` from dev mode but some [`PlaySettings`](https://github.com/playframework/playframework/blob/a90d453833ecffd17b76a0ed8805725fb99e08f7/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala#L112-L115) (e.g. `playOmnidoc`) were leftover.

On top of that, we've been maintaining (and [documenting](https://www.playframework.com/documentation/2.8.x/Migration28#Defaults-changes)) default values for those leftovers.

**Comment by renatocaval** [comment]
🤦‍♂

**Comment by ignasi35** [comment]
> 🤦‍♂

🤦🏼‍♂️
