### ISSUE TITLE
Error in download link 1.5

### ISSUE THREAD

**Issue by bastaware** [playframework/playframework#9918]
https://www.playframework.com/documentation/1.5.x/install

Links to wrong download site:

Install Java.
**Download the latest Play binary package and extract the archive.**
Add the ‘play’ command to your system path and make sure it is executable.

Should be [https://www.playframework.com/releases] I guess...

**Comment by mkurz** [comment]
The documentation page you are refefering here is maintained in the Play 1 GitHub repo here:
https://github.com/playframework/play1/blob/master/documentation/manual/install.textile#installation-from-the-binary-package

Please open an issue or pull request at https://github.com/playframework/play1
