### ISSUE TITLE
Error upload file 

### ISSUE THREAD

**Issue by oanh-JL** [playframework/playframework#9920]
### Play Version
2.8.x

### API
upload file in scala

### Operating System
macOS

### JDK
1.8

### Expected Behavior

i found the problem in post file by uploadfile API 
1. `val filename    = Paths.get(picture.filename).getFileName`
2. `picture.ref.copyTo(Paths.get(s"/tmp/picture/$filename"), replace = true)`

### Actual Behavior

 
I found the resolve, at least it work for me you can check it 

1.        val filename    = picture.filename
2.        picture.ref.copyTo(new File(s"/tmp/picture/$filename")

**Comment by ignasi35** [comment]
Hi @oanh-JL, can you detail what was the problem you found? 

PS: This seems to be a topic better suited for our [discuss forum](https://discuss.lightbend.com/c/play).

**Comment by mkurz** [comment]
@oanh-JL you didn't provide any further information, therefore I am closing this issue. You can re-open anytime you want to give us more information what the exact problem is.
