### ISSUE TITLE
Make ALPN optional

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9941]
Seince adding support for JDK11 Play no longer needs to add the ALPN Agent everytime HTTP/2 is used since JDK11 supports ALPN out of the box.

We should allow users to disable the dependency to `jetty-alpn-agent` when using `PlayAkkaHttp2Support`.

See related: https://github.com/akka/akka-grpc/issues/772

**Comment by mkurz** [comment]
Reading through https://webtide.com/jetty-alpn-java-8u252/, with `jetty-alpn-agent` version `2.0.10` (#10268) adding the agent when using JDK >= 8u252 is a no-op, so I think making ALPN optional is not that urgent.

**Comment by ignasi35** [comment]
@mkurz making it a bit more explicit (like in https://github.com/akka/akka-grpc/pull/848) shouldn't harm. :-)

**Comment by mkurz** [comment]
Pull request: #10734
