### ISSUE TITLE
Docs Improvement : Forms, nested values

### ISSUE THREAD

**Issue by gavinbaumanis** [playframework/playframework#9976]
Improve the Play documentation of  forms, nested values to better illustrate multiple nested values.

At the moment the [documentation](https://www.playframework.com/documentation/2.8.x/ScalaForms#Nested-values) illustrates a single nested value at the **end** of the _form_;
```
val userFormNested: Form[UserAddressData] = Form(
  mapping(
    "name" -> text,
    "address" -> mapping(
      "street" -> text,
      "city"   -> text
    )(AddressData.apply)(AddressData.unapply)
  )(UserAddressData.apply)(UserAddressData.unapply)
)
```
Here (AddressData.apply)(...unapply) - directly precedes the (UserAddressData.apply)(...unapply)

What isn't clear (for those that don't know) is; Where do the apply / unapply calls go?
Do they go last (overall) - as it seems to be illustrated in the documentation or do they belong at the end of each mapping?

Perhaps, something along the lines of the following would be better to illustrate the apply/unapply is directly after the matching _mapping_? I.e.;

```
val userFormNested: Form[UserAddressData] = Form(
  mapping(
    "name" -> text,
    "homeAddress" -> mapping(
      "street" -> text,
      "city"   -> text
    )(HomeAddressData.apply)(HomeAddressData.unapply),
    "workAddress" -> mapping(
      "street" -> text,
      "city"   -> text
    )(WorkAddressData.apply)(WorkAddressData.unapply)
  )(UserAddressData.apply)(UserAddressData.unapply)
)
```

### Play Version
2.8

**Comment by mkurz** [comment]
@gavinbaumanis that would be a nice addition to the docs. Do you want you provide a pull request? The file you would need to change is: https://github.com/playframework/playframework/blob/2.8.x/documentation/manual/working/scalaGuide/main/forms/ScalaForms.md

**Comment by gavinbaumanis** [comment]
I have PR 10006,
Please let me know if there is anything I missed.

**Comment by gavinbaumanis** [comment]
@all;
I have signed the CLA, multiple times.
I am not sure why it is still saying I need to do it again.

**Comment by renatocaval** [comment]
Resoled by #10006
