### ISSUE TITLE
Akka Typed actor in play websocket

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [playframework/playframework#9986]
I'm developing a web-socket application in play and using actor based websocket implementation according to their official tutorial (https://www.playframework.com/documentation/2.8.x/JavaWebSockets)

In controller
`public WebSocket socket() {
    System.out.println("socket connecton received");  
    return WebSocket.Text.accept(  
            request -> ActorFlow.actorRef(WebSocketActor::props, actorSystem, materializer));  
}`

WebSocketActor is implemented with Typed actors as below

`public class WebSocketActor extends AbstractBehavior<String> {
`

But the issue is it is giving me following error Incompatible types: ActorRef is not convertible to ActorRef and it seems like ActorFlow.actorRef is only allows un-typed actors.

How can I use a Typed Actor with above implementation.

**Comment by renatocaval** [comment]
There is a sample showing how to use Typed actors with Websocket in Play. You can find it here: https://github.com/playframework/play-samples/tree/2.8.x/play-java-websocket-example

On a side note, our [forums](https://discuss.playframework.com) would be a better place to ask questions like this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.  

Best.

**Comment by alexmnyc** [comment]
@octonato  does this automatically clean up user actors on websocket connections closed? https://github.com/playframework/play-samples/tree/2.8.x/play-scala-websocket-example/app/actors

**Comment by octonato** [comment]
@alexmnyc, it should. 

If you find out that it is not, please report it on an issue in https://github.com/playframework/play-samples
